** Sun Mar 20 06:44:40 2016 (Translate from English to Russian:)

Translate from English to Russian:

amend

изменить

verb
 1. вносить поправки (amend)
 2. исправлять (correct, fix, mend, rectify, repair, amend)
 3. улучшать (improve, better, refine, perfect, improve on, amend)
 4. чинить (repair, fix, mend, darn, bodge, amend)

DEFINITION

verb
 1. make minor changes in (a text) in order to make it fairer, more accurate, or more up-to-date.
    "the rule was amended to apply only to nonmembers"

** Wed Apr 13 16:26:19 2016 (Translate from English to Russian:)

Translate from English to Russian:

deceive

обманывать

verb
 1. обманывать (deceive, cheat, kid, fool, spoof, delude)
 2. вводить в заблуждение (mislead, deceive, delude, misguide, misinform, mystify)
 3. изменять (change, vary, betray, alter, transform, deceive)
 4. сбивать с толку (confuse, bewilder, baffle, mislead, perplex, deceive)
 5. нарушать верность (deceive)

DEFINITION

verb
 1. (of a person) cause (someone) to believe something that is not true, typically in order to gain some personal advantage.
    "I didn't intend to deceive people into thinking it was French champagne"

** Wed Apr 13 16:29:07 2016 (Translate from English to Russian:)

Translate from English to Russian:

profanity

профанация

noun
 1. профанация (profanation, profanity, desecration, defilement)
 2. богохульство (blasphemy, profanity, oath, swear)

DEFINITION

noun
 1. blasphemous or obscene language.
    "an outburst of profanity"

** Wed Apr 13 16:31:00 2016 (Translate from English to Russian:)

Translate from English to Russian:

obscene

непристойный

adjective
 1. непристойный (obscene, indecent, lewd, unseemly, salacious, filthy)
 2. неприличный (indecent, obscene, rude, improper, unbecoming, dirty)
 3. непотребный (obscene, foul)
 4. матерный (obscene, abusive, foul, worthless, cheap)
 5. грязный (dirty, messy, filthy, muddy, foul, obscene)

DEFINITION

adjective
 1. (of the portrayal or description of sexual matters) offensive or disgusting by accepted standards of morality and decency.
    "obscene jokes"

** Wed Apr 13 16:31:48 2016 (Translate from English to Russian:)

Translate from English to Russian:

decency

порядочность

noun
 1. порядочность (decency)
 2. благопристойность (decency, decorum, modesty, convenances)
 3. приличие (decency, grace)
 4. вежливость (courtesy, politeness, civility, comity, urbanity, decency)
 5. любезность (amiability, favor, kindness, civility, compliment, decency)

DEFINITION

noun
 1. behavior that conforms to accepted standards of morality or respectability.
    "she had the decency to come and confess"

** Wed Apr 13 16:37:40 2016 (Translate from English to Russian:)

Translate from English to Russian:

unjust

несправедливый

adjective
 1. несправедливый (unfair, unjust, inequitable, iniquitous, unrighteous, wrongful)
 2. неправый (unjust)

DEFINITION

adjective
 1. not based on or behaving according to what is morally right and fair.
    "resistance to unjust laws"

** Fri Apr 15 17:33:20 2016 (Translate from English to Russian:)

Translate from English to Russian:

infuriating

приводящий в ярость

adjective
 1. приводящий в ярость (infuriating)

DEFINITION

adjective
 1. making one extremely angry and impatient; very annoying.
    "that infuriating half-smile on his face"

verb
 1. make (someone) extremely angry and impatient.
    "her silences infuriated him"

** Fri Apr 15 17:34:37 2016 (Translate from English to Russian:)

Translate from English to Russian:

hapless

незадачливый

adjective
 1. несчастный (unhappy, miserable, unfortunate, poor, wretched, hapless)
 2. незадачливый (hapless, luckless, fortuneless)
 3. злополучный (hapless, accursed, unblessed, unblest, sinistrous, ill-fated)
 4. горемычный (hapless)

DEFINITION

adjective
 1. (especially of a person) unfortunate.
    "if you're one of the many hapless car buyers who've been shafted"

** Fri Apr 15 17:36:14 2016 (Translate from English to Russian:)

Translate from English to Russian:

inflict

причинить

verb
 1. налагать (impose, inflict, give, administer, clap, put on)
 2. навязывать (impose, force, intrude, enforce, thrust, inflict)
 3. накладывать (superimpose, lay, lay on, inflict)
 4. наносить удар (strike a blow, deal a blow, lunge, strike at, deliver a blow, inflict)
 5. причинять страдание (afflict, inflict, distress, ail)

DEFINITION

verb
 1. cause (something unpleasant or painful) to be suffered by someone or something.
    "they inflicted serious injuries on three other men"

** Fri Apr 15 17:43:15 2016 (Title: What are the growth stages of a programmer?)

Title: What are the growth stages of a programmer?
Date: Wed,  9 Dec 2015 04:24:55 UTC
Feed: Top Answers About Computer Programmers on Quora
Link: https://www.quora.com/Wha[...]mmer/answer/Nate-Waddoups

Nate Waddoups

This first one is shamelessly stolen from a presentation I saw at
Microsoft a few years ago:

1 Complex solutions to simple problems.
2 Complex solutions to complex problems.
3 Simple solutions to complex problems.
4 Complex problems disappear

Or, on another axis:

1 You suck.
2 You seek the advice of your teammates.
3 Your teammates seek advice from you.
4 People on other teams come to you for advice.

(Never forget that despite 3 and 4, item 1 is still true and item 2 is
still a good idea.)
Or, on another axis:

1 Your can write code.
2 You can understand your code.
3 You can fix your code.
4 You can understand other peoples' code.
5 You can fix other peoples' code.
6 You can understand and fix your own code even when you wrote it so
  long ago that it might as well have been written by someone else.

[Edited to add one more section...] 
The following is all from a Wikipedia page about Four stages of
competence. It is actually not about programming specifically, but it
is a way to look at one's competence in any endeavor. I've found it
interesting to look at all sorts of skills in these terms:

    1 Unconscious incompetence - The individual does not understand or
      know how to do something and does not necessarily recognize the
      deficit. They may deny the usefulness of the skill. The
      individual must recognize their own incompetence, and the value
      of the new skill, before moving on to the next stage. The length
      of time an individual spends in this stage depends on the
      strength of the stimulus to learn.
    2 Conscious incompetence - Though the individual does not
      understand or know how to do something, he or she does recognize
      the deficit, as well as the value of a new skill in addressing
      the deficit. The making of mistakes can be integral to the
      learning process at this stage.
    3 Conscious competence - The individual understands or knows how
      to do something. However, demonstrating the skill or knowledge
      requires concentration. It may be broken down into steps, and
      there is heavy conscious involvement in executing the new skill.
    4 Unconscious competence - The individual has had so much practice
      with a skill that it has become "second nature" and can be
      performed easily. As a result, the skill can be performed while
      executing another task. The individual may be able to teach it
      to others, depending upon how and when it was learned.

See Questions On Quora

** Fri Apr 15 17:47:03 2016 (Translate from English to Russian:)

Translate from English to Russian:

muggy

спертый

adjective
 1. влажный (wet, humid, damp, moist, dewy, muggy)
 2. спертый (stale, stuffy, close, frowzy, frowsty, muggy)
 3. сырой и теплый (muggy)
 4. удушливый (suffocating, suffocative, muggy, smothery, choky, suffocant)

DEFINITION

adjective
 1. (of the weather) unpleasantly warm and humid.
    "Came home to warm, muggy weather and, apparently, it rained here at the house."

** Fri Apr 15 17:50:16 2016 (Translate from English to Russian:)

Translate from English to Russian:

squeal

визг

noun
 1. визг (squeal, screech, shriek, scream, yelp, yelping)
 2. пронзительный крик (shriek, scream, squawk, yell, squeal, squall)
 3. доносчик (informer, snitch, informant, squeal, sneak, delator)

verb
 1. визжать (squeal, shrill, screech, yelp, shriek, squall)
 2. верещать (squeal, chirp)
 3. жаловаться (complain, lament, beef, grumble, moan, squeal)
 4. пронзительно кричать (scream, squawk, shriek, shrill, squeal, squall)
 5. визгливо произносить (squeal)
 6. протестовать (protest, object, rebel, remonstrate, outcry, squeal)
 7. стать доносчиком (squeak, squeal)
 8. выдавать (issue, extradite, betray, give, produce, squeal)

DEFINITION

noun
 1. a long, high-pitched cry or noise.
    "we heard a splash and a squeal"

verb
 1. make a long, high-pitched cry or noise.
    "the girls squealed with delight"
 2. inform on someone to the police or a person in authority.
    "she feared they would victimize her for squealing on their pals"

** reluctant, lameness, tatter, draught, faltering, barling, marline,
   footsore, limp, hesitate, haggard, smear, plight, midst, attend,
   detain, plausibility, noodle, adolescent, pallor, etiolate, arrears,
   stratification, retard, ramification, aperture, shaft, obscene, flaxen,
   masonry, vestige, hastily, cheerless, sombre, mingle, virtue, anemone,
   slumber, apprehension, tumult, drove, expostulation, desolate, garland,
   rubbing, mite, cramp, decadent, sepulture, exuberant, tether, vigil,
   repugnance, hollow, sloth, groove, curb, begotten, stolid, cunning,
   behoves, despair, desertion, misery, anguish, twig, frenzy, dismay,
   mockery, leprous, faint, stirring, lash, lawn, birch, flit, cease, gibbous,
   plausible, languor, hindrance, abundant, connubial, alliance, putrefaction,
   spite, eddy, clumsy, tentative, weed, feeble, precocious, indolent,
   interrogative, loath, merriment, edifice, startle, vain, stagger, preach,
   spawn, contented, impetus, fret, toil, horticulture, wane, rotundity,
   stinging, amidst, precipitous, queer, fatigue, indolent, staple, fracture,
   dilapidated, stalk, fling, turf, merriment, bow, minikin, manikin, vengeance,
   rage, disarm, venison, attune, ravage, sputter, compunction, distort, peculiar,
   manifest, intertwine, apparel, influx, threshold, shabby, dilapidated,
   contentious, subdue, virtue, conscience, qualm, ferocious, prowess,
   sought, impediment, inept, ascribe, glib, lurch, anguish, vernacular,
   overtly, counselor, delusion, unhinge, exasperation, irreconcilable,
   fidget, affront, sincerity, compassion, congruous, dusk, drowsily,
   silhouette, emerald, tremulous, desperate, fern, amble, respite,
   conducive, earnest, seclude, indignant, vigilance, tamer, warble,
   implacable, bargain, thoroughly, convinced, contemplate, pat, prance,
   courtly, apparition, leek, hue, bogus, entirety, idiom, nominal, encompass,
   futile, coupling, content, cram, impale, impel, hinge, supersede, expenditure,
   inert, vomit, cohesive, longing, remnant, abomination, massacre, fogey,
   dilemma, shed, scavenger, destine, stump, thrice, canopy, tatter, coil, fro,
   elude, crippling, bewilderment, blundering, dazzle, fence, writhe, hawthorn,
   scorch, tumulus, hillock, agape, incessant, stir, exultation, succulent,
   thrust, cling, replenish, foliage, bonfire, carbuncle, scarcely, patter,
   throb, folly, atrocious, insidious, irritable, feverish, calamity, embark,
   upbringing, rig, grapple, proponent, avid, fervent, blaze, steatite, elate,
   crowbar, sealed, wilderness, sombre, semblance, brute, slake, disinclination,
   mace, whimper, aisle, abundant, hesitate, apprehension, diminution, startle,
   attain, readjustment, desiccate, deliquesce, transverse, urchin, deaden,
   vestige, dwelling, ram, contrivance, procure, contrive, scorn, rill, feeble,
   pity, dainty, awaken, hazy, forthwith, sweep, unfathomable, splendid, yore,
   acacia, caress, fatigue, preternatural, wither, fastness, villainy, foul,
   wane, dread, malign, stagger, sustaining, thigh, gorge, ravine, persevere,
   anguish, nausea, discordant, odour, frightful, faint, incontinently, abysmal,
   aperture, slender, disconcerted, descent, shirk, tint, afield, pallid,
   saliva, decent, deception, devastating, capsicum, wit, froth, broth, 



