** Fri Apr 15 17:43:15 2016 (Title: What are the growth stages of a programmer?)

Title: What are the growth stages of a programmer?
Date: Wed,  9 Dec 2015 04:24:55 UTC
Feed: Top Answers About Computer Programmers on Quora
Link: https://www.quora.com/Wha[...]mmer/answer/Nate-Waddoups

Nate Waddoups

This first one is shamelessly stolen from a presentation I saw at
Microsoft a few years ago:

1 Complex solutions to simple problems.
2 Complex solutions to complex problems.
3 Simple solutions to complex problems.
4 Complex problems disappear

Or, on another axis:

1 You suck.
2 You seek the advice of your teammates.
3 Your teammates seek advice from you.
4 People on other teams come to you for advice.

(Never forget that despite 3 and 4, item 1 is still true and item 2 is
still a good idea.)
Or, on another axis:

1 Your can write code.
2 You can understand your code.
3 You can fix your code.
4 You can understand other peoples' code.
5 You can fix other peoples' code.
6 You can understand and fix your own code even when you wrote it so
  long ago that it might as well have been written by someone else.

[Edited to add one more section...] 
The following is all from a Wikipedia page about Four stages of
competence. It is actually not about programming specifically, but it
is a way to look at one's competence in any endeavor. I've found it
interesting to look at all sorts of skills in these terms:

    1 Unconscious incompetence - The individual does not understand or
      know how to do something and does not necessarily recognize the
      deficit. They may deny the usefulness of the skill. The
      individual must recognize their own incompetence, and the value
      of the new skill, before moving on to the next stage. The length
      of time an individual spends in this stage depends on the
      strength of the stimulus to learn.
    2 Conscious incompetence - Though the individual does not
      understand or know how to do something, he or she does recognize
      the deficit, as well as the value of a new skill in addressing
      the deficit. The making of mistakes can be integral to the
      learning process at this stage.
    3 Conscious competence - The individual understands or knows how
      to do something. However, demonstrating the skill or knowledge
      requires concentration. It may be broken down into steps, and
      there is heavy conscious involvement in executing the new skill.
    4 Unconscious competence - The individual has had so much practice
      with a skill that it has become "second nature" and can be
      performed easily. As a result, the skill can be performed while
      executing another task. The individual may be able to teach it
      to others, depending upon how and when it was learned.

See Questions On Quora

** reluctant, lameness, tatter, draught, faltering, barling, marline,
   footsore, limp, hesitate, haggard, smear, plight, midst, attend,
   detain, plausibility, noodle, adolescent, pallor, etiolate, arrears,
   stratification, retard, ramification, aperture, shaft, obscene, flaxen,
   masonry, vestige, hastily, cheerless, sombre, mingle, virtue, anemone,
   slumber, apprehension, tumult, drove, expostulation, desolate, garland,
   rubbing, mite, cramp, decadent, sepulture, exuberant, tether, vigil,
   repugnance, hollow, sloth, groove, curb, begotten, stolid, cunning,
   behoves, despair, desertion, misery, anguish, twig, frenzy, dismay,
   mockery, leprous, faint, stirring, lash, lawn, birch, flit, cease, gibbous,
   plausible, languor, hindrance, abundant, connubial, alliance, putrefaction,
   spite, eddy, clumsy, tentative, weed, feeble, precocious, indolent,
   interrogative, loath, merriment, edifice, startle, vain, stagger, preach,
   spawn, contented, impetus, fret, toil, horticulture, wane, rotundity,
   stinging, amidst, precipitous, queer, fatigue, indolent, staple, fracture,
   dilapidated, stalk, fling, turf, merriment, bow, minikin, manikin, vengeance,
   rage, disarm, venison, attune, ravage, sputter, compunction, distort, peculiar,
   manifest, intertwine, apparel, influx, threshold, shabby, dilapidated,
   contentious, subdue, virtue, conscience, qualm, ferocious, prowess,
   sought, impediment, inept, ascribe, glib, lurch, anguish, vernacular,
   overtly, counselor, delusion, unhinge, exasperation, irreconcilable,
   fidget, affront, sincerity, compassion, congruous, dusk, drowsily,
   silhouette, emerald, tremulous, desperate, fern, amble, respite,
   conducive, earnest, seclude, indignant, vigilance, tamer, warble,
   implacable, bargain, thoroughly, convinced, contemplate, pat, prance,
   courtly, apparition, leek, hue, bogus, entirety, idiom, nominal, encompass,
   futile, coupling, content, cram, impale, impel, hinge, supersede, expenditure,
   inert, vomit, cohesive, longing, remnant, abomination, massacre, fogey,
   dilemma, shed, scavenger, destine, stump, thrice, canopy, tatter, coil, fro,
   elude, crippling, bewilderment, blundering, dazzle, fence, writhe, hawthorn,
   scorch, tumulus, hillock, agape, incessant, stir, exultation, succulent,
   thrust, cling, replenish, foliage, bonfire, carbuncle, scarcely, patter,
   throb, folly, atrocious, insidious, irritable, feverish, calamity, embark,
   upbringing, rig, grapple, proponent, avid, fervent, blaze, steatite, elate,
   crowbar, sealed, wilderness, sombre, semblance, brute, slake, disinclination,
   mace, whimper, aisle, abundant, hesitate, apprehension, diminution, startle,
   attain, readjustment, desiccate, deliquesce, transverse, urchin, deaden,
   vestige, dwelling, ram, contrivance, procure, contrive, scorn, rill, feeble,
   pity, dainty, awaken, hazy, forthwith, sweep, unfathomable, splendid, yore,
   acacia, caress, fatigue, preternatural, wither, fastness, villainy, foul,
   wane, dread, malign, stagger, sustaining, thigh, gorge, ravine, persevere,
   anguish, nausea, discordant, odour, frightful, faint, incontinently, abysmal,
   aperture, slender, disconcerted, descent, shirk, tint, afield, pallid,
   saliva, decent, deception, devastating, capsicum, wit, froth, broth, 




* amend :Demo:
[2016-07-08 Fri 20:09]

When you amend something, you correct or improve it. If you confused
your audience when you gave your speech, don't be afraid to amend what
you said.

Amend can also describe adding amendments to an official document,
such as a constitution or law. If politicians in your state want to
address the growing number of home foreclosures, they might amend the
state constitution to include restrictions intended to reduce
foreclosures. Amend comes from the Latin word emendare, meaning "to
correct, free from fault."

amend
* deceive :Demo:
[2016-07-08 Fri 20:10]

To deceive means to trick or lie. A crafty kid might deceive his
mother into thinking he has a fever by holding the thermometer to a
light bulb to increase the temperature.

Deceive is the trickier cousin of lie. You might lie about why you
were late to school. But if you simply don't explain to your mom that
you were late in the first place, you are deceiving her. Deceive
carries with it a feeling of both craftiness and betrayal. When you
deceive someone, forgiveness can be hard to come by. Have you heard of
the spelling rule, "i before e except after c" that has so many
exceptions? Well, deceive follows that rule.

deceive
* profanity :Demo:
[2016-07-08 Fri 20:25]

Profanity is a type of language that includes dirty words and
ideas. Swear words, obscene gestures, and naughty jokes are all
considered profanity.

You know those four-letter words you're not supposed to say? They're
profanity: language that's vulgar and obscene. R-rated movies and
cable stations like HBO have a lot of profanity, but you won't hear it
on a station like NBC or ABC. Profanity tends to be about off-color
subjects, like sex and going to the bathroom. Everyone probably spews
some profanity at some point, but you better be careful about who's
listening.

profanity
* outburst :Demo:
[2016-07-08 Fri 20:26]

When you can't help an angry shout or a burst of emotion, that's an
outburst. A toddler's outburst might take the form of a full-blown
temper tantrum.

An outburst of passion or emotion can be angry words, a broken glass,
or a triumphant whoop. There are also figurative outbursts, like the
outburst of political enthusiasm within a particular group of voters,
or an outburst of energy in the midst of a modern dance
performance. The Middle English verb that proceeded outburst was
outbresten.

"an outburst of profanity"

* obscene :Demo:
[2016-07-08 Fri 20:28]

Obscene describes something that is morally offensive in a sexual
way. It's never a good idea to use obscene language at school.

Certain films, books, magazines, and other forms of entertainment are
considered obscene because they portray sex in a very frank way that
some people find vulgar and lewd. Obscene material, language, and
jokes are considered taboo in polite society. Obscene can also be used
to describe something repulsive — like when your friend ate an obscene
number of snails at the Bastille Day bash.

obscene
* decency :Demo:
[2016-07-08 Fri 20:29]

The personal quality of decency is one of honesty, good manners, and
respect for other people.

Over time, decency has referred to manners, but today decency is
mainly a strong sense of right and wrong, and a high standard of
honesty. When a criminal or dictator does horrible things, people
assume they have no sense of decency. When a tasteless or violent TV
show becomes popular, some people wonder if society has lost its sense
of decency. Asking "Have you no decency?" is a serious question,
unless you're being silly and complaining about something like
homework.

decency
* unjust :Demo:
[2016-07-08 Fri 20:29]

Something or someone that is unjust is just not fair. An unjust boss
might fire you the very first time you're late for work.

You might think of the word justice in order to remember the meaning
of the word just, which means "fairness or righteousness." An unjust
judge does not play by the rules; he might send a person to jail even
though there isn't enough evidence that a crime was committed. Unjust
behavior is improper or dishonest: "The professor acted in an unjust
manner when he gave everyone an F just because there was a rumor that
his students didn’t like him."

unjust
* infuriating :Demo:
[2016-07-08 Fri 20:30]

Use the adjective infuriating to describe something that makes you
really, really angry. It's infuriating to see a little kid being
bullied.

When something makes you furious it's infuriating. You can use the
word to talk about things that are truly offensive or outrageous —
someone snatching your grandmother's purse, for example — or things
that are merely aggravating or annoying. You might find it infuriating
trying to parallel park on a busy street or waiting in line at the
post office. The roots of infuriating can be traced all the way back
to the Latin furere, which means "to rage" or "to be mad."

infuriating
* hapless :Demo:
[2016-07-08 Fri 20:31]

Use the adjective hapless to describe someone unlucky and deserving of
pity, like the hapless used car buyer who gives in to the fast-talking
salesperson.

The word hapless traces all the way back to the Old Norse word happ,
meaning “chance, good luck.” Combine this with the suffix -less
(“lacking”) and hapless means “unlucky” or “ill-fated.”  A traveler
who goes to Moscow and briefly gets lost on the subway? Just a
tourist. A traveler who goes to Moscow, accidentally eats food he is
allergic to, somehow loses all his money, and by chance gets on a
train destined for Mongolia? Definitely hapless.

hapless
* inflict :Demo:
[2016-07-08 Fri 20:32]

When you force an undesirable or harmful event on someone, you inflict
it on them. You might prefer that someone inflict some physical pain
on you rather than inflict you with the boredom of another trip to the
annual flower show.

The verb inflict comes from the Latin word inflictus, meaning “to
strike or dash against.” If you cause anything bad to happen to a
person, animal, or even an object, you inflict that badness on
them. For example, someone can inflict injuries or suffering on other
people or inflict damage on property. We can inflict pollution or
over-development on our environment. It's always a negative thing —
you wouldn't say you inflict happiness or love on others.

inflict
* muggy :Demo:
[2016-07-08 Fri 20:33]

Think of hot, humid, steamy weather as being so unpleasant that you
feel "mugged" by it when you step outside. That's one way to remember
the meaning of muggy.

"It's not the heat! It's the humidity!" That's what your grandma says
when she wants to complain about muggy weather. Muggy means a
combination of humidity and heat that makes you sweaty and
uncomfortable and long for air-conditioning. You might be cursing the
cold and the snow today, but mark my words, come August and the muggy
dog days of summer, you'll be nostalgic for the cold.

muggy
