** Fri Apr 15 17:43:15 2016 (Title: What are the growth stages of a programmer?)

Title: What are the growth stages of a programmer?
Date: Wed,  9 Dec 2015 04:24:55 UTC
Feed: Top Answers About Computer Programmers on Quora
Link: https://www.quora.com/Wha[...]mmer/answer/Nate-Waddoups

Nate Waddoups

This first one is shamelessly stolen from a presentation I saw at
Microsoft a few years ago:

1 Complex solutions to simple problems.
2 Complex solutions to complex problems.
3 Simple solutions to complex problems.
4 Complex problems disappear

Or, on another axis:

1 You suck.
2 You seek the advice of your teammates.
3 Your teammates seek advice from you.
4 People on other teams come to you for advice.

(Never forget that despite 3 and 4, item 1 is still true and item 2 is
still a good idea.)
Or, on another axis:

1 Your can write code.
2 You can understand your code.
3 You can fix your code.
4 You can understand other peoples' code.
5 You can fix other peoples' code.
6 You can understand and fix your own code even when you wrote it so
  long ago that it might as well have been written by someone else.

[Edited to add one more section...] 
The following is all from a Wikipedia page about Four stages of
competence. It is actually not about programming specifically, but it
is a way to look at one's competence in any endeavor. I've found it
interesting to look at all sorts of skills in these terms:

    1 Unconscious incompetence - The individual does not understand or
      know how to do something and does not necessarily recognize the
      deficit. They may deny the usefulness of the skill. The
      individual must recognize their own incompetence, and the value
      of the new skill, before moving on to the next stage. The length
      of time an individual spends in this stage depends on the
      strength of the stimulus to learn.
    2 Conscious incompetence - Though the individual does not
      understand or know how to do something, he or she does recognize
      the deficit, as well as the value of a new skill in addressing
      the deficit. The making of mistakes can be integral to the
      learning process at this stage.
    3 Conscious competence - The individual understands or knows how
      to do something. However, demonstrating the skill or knowledge
      requires concentration. It may be broken down into steps, and
      there is heavy conscious involvement in executing the new skill.
    4 Unconscious competence - The individual has had so much practice
      with a skill that it has become "second nature" and can be
      performed easily. As a result, the skill can be performed while
      executing another task. The individual may be able to teach it
      to others, depending upon how and when it was learned.

See Questions On Quora

** reluctant, lameness, tatter, draught, faltering, barling, marline,
   footsore, limp, hesitate, haggard, smear, plight, midst, attend,
   detain, plausibility, noodle, adolescent, pallor, etiolate, arrears,
   stratification, retard, ramification, aperture, shaft, obscene, flaxen,
   masonry, vestige, hastily, cheerless, sombre, mingle, virtue, anemone,
   slumber, apprehension, tumult, drove, expostulation, desolate, garland,
   rubbing, mite, cramp, decadent, sepulture, exuberant, tether, vigil,
   repugnance, hollow, sloth, groove, curb, begotten, stolid, cunning,
   behoves, despair, desertion, misery, anguish, twig, frenzy, dismay,
   mockery, leprous, faint, stirring, lash, lawn, birch, flit, cease, gibbous,
   plausible, languor, hindrance, abundant, connubial, alliance, putrefaction,
   spite, eddy, clumsy, tentative, weed, feeble, precocious, indolent,
   interrogative, loath, merriment, edifice, startle, vain, stagger, preach,
   spawn, contented, impetus, fret, toil, horticulture, wane, rotundity,
   stinging, amidst, precipitous, queer, fatigue, indolent, staple, fracture,
   dilapidated, stalk, fling, turf, merriment, bow, minikin, manikin, vengeance,
   rage, disarm, venison, attune, ravage, sputter, compunction, distort, peculiar,
   manifest, intertwine, apparel, influx, threshold, shabby, dilapidated,
   contentious, subdue, virtue, conscience, qualm, ferocious, prowess,
   sought, impediment, inept, ascribe, glib, lurch, anguish, vernacular,
   overtly, counselor, delusion, unhinge, exasperation, irreconcilable,
   fidget, affront, sincerity, compassion, congruous, dusk, drowsily,
   silhouette, emerald, tremulous, desperate, fern, amble, respite,
   conducive, earnest, seclude, indignant, vigilance, tamer, warble,
   implacable, bargain, thoroughly, convinced, contemplate, pat, prance,
   courtly, apparition, leek, hue, bogus, entirety, idiom, nominal, encompass,
   futile, coupling, content, cram, impale, impel, hinge, supersede, expenditure,
   inert, vomit, cohesive, longing, remnant, abomination, massacre, fogey,
   dilemma, shed, scavenger, destine, stump, thrice, canopy, tatter, coil, fro,
   elude, crippling, bewilderment, blundering, dazzle, fence, writhe, hawthorn,
   scorch, tumulus, hillock, agape, incessant, stir, exultation, succulent,
   thrust, cling, replenish, foliage, bonfire, carbuncle, scarcely, patter,
   throb, folly, atrocious, insidious, irritable, feverish, calamity, embark,
   upbringing, rig, grapple, proponent, avid, fervent, blaze, steatite, elate,
   crowbar, sealed, wilderness, sombre, semblance, brute, slake, disinclination,
   mace, whimper, aisle, abundant, hesitate, apprehension, diminution, startle,
   attain, readjustment, desiccate, deliquesce, transverse, urchin, deaden,
   vestige, dwelling, ram, contrivance, procure, contrive, scorn, rill, feeble,
   pity, dainty, awaken, hazy, forthwith, sweep, unfathomable, splendid, yore,
   acacia, caress, fatigue, preternatural, wither, fastness, villainy, foul,
   wane, dread, malign, stagger, sustaining, thigh, gorge, ravine, persevere,
   anguish, nausea, discordant, odour, frightful, faint, incontinently, abysmal,
   aperture, slender, disconcerted, descent, shirk, tint, afield, pallid,
   saliva, decent, deception, devastating, capsicum, wit, froth, broth, 




* shirk							     :Demo:verb:noun:
[2016-06-26 Sun 17:05]

To shirk your responsibilities is to avoid dealing with them — like
when you watch four consecutive hours of infomercials instead of
facing your homework.

A verb is an action word, so it's ironic that the verb shirk suggests
inaction in the avoidance of work. To shirk carries with it a negative
connotation of laziness. When Eleanor Roosevelt was asked how she
conquered her shyness to become a powerful public figure, she
responded, "I faced each problem as it came along. . . . I never tried
to shirk. I tried never to evade an issue. When I found I had
something to do — I just did it." Ah, Eleanor, why can't we all be a
bit more like you?

footsore, limp, hesitate, haggard, smear, plight, midst, attend,
   detain, plausibility, noodle, adolescent, pallor, etiolate, arrears,
   stratification, retard, ramification, aperture, shaft, obscene, flaxen,
   masonry, vestige, hastily, cheerless, sombre, mingle, virtue, anemone,
   slumber, apprehension, tumult, drove, expostulation, desolate, garland,
   rubbing, mite, cramp, decadent, sepulture, exuberant, tether, vigil,
   repugnance, hollow, sloth, groove, curb, begotten, stolid, cunning,
   behoves, despair, desertion, misery, anguish, twig, frenzy, dismay,
   mockery, leprous, faint, stirring, lash, lawn, birch, flit, cease, gibbous,
   plausible, languor, hindrance, abundant, connubial, alliance, putrefaction,
   spite, eddy, clumsy, tentative, weed, feeble, precocious, indolent,
   interrogative, loath, merriment, edifice, startle, vain, stagger, preach,
   spawn, contented, impetus, fret, toil, horticulture, wane, rotundity,
   stinging, amidst, precipitous, queer, fatigue, indolent, staple, fracture,
   dilapidated, stalk, fling, turf, merriment, bow, minikin, manikin, vengeance,
   rage, disarm, venison, attune, ravage, sputter, compunction, distort, peculiar,
   manifest, intertwine, apparel, influx, threshold, shabby, dilapidated,
   contentious, subdue, virtue, conscience, qualm, ferocious, prowess,
   sought, impediment, inept, ascribe, glib, lurch, anguish, vernacular,
   overtly, counselor, delusion, unhinge, exasperation, irreconcilable,
   fidget, affront, sincerity, compassion, congruous, dusk, drowsily,
   silhouette, emerald, tremulous, desperate, fern, amble, respite,
   conducive, earnest, seclude, indignant, vigilance, tamer, warble,
   implacable, bargain, thoroughly, convinced, contemplate, pat, prance,
   courtly, apparition, leek, hue, bogus, entirety, idiom, nominal, encompass,
   futile, coupling, content, cram, impale, impel, hinge, supersede, expenditure,
   inert, vomit, cohesive, longing, remnant, abomination, massacre, fogey,
   dilemma, shed, scavenger, destine, stump, thrice, canopy, tatter, coil, fro,
   elude, crippling, bewilderment, blundering, dazzle, fence, writhe, hawthorn,
   scorch, tumulus, hillock, agape, incessant, stir, exultation, succulent,
   thrust, cling, replenish, foliage, bonfire, carbuncle, scarcely, patter,
   throb, folly, atrocious, insidious, irritable, feverish, calamity, embark,
   upbringing, rig, grapple, proponent, avid, fervent, blaze, steatite, elate,
   crowbar, sealed, wilderness, sombre, semblance, brute, slake, disinclination,
   mace, whimper, aisle, abundant, hesitate, apprehension, diminution, startle,
   attain, readjustment, desiccate, deliquesce, transverse, urchin, deaden,
   vestige, dwelling, ram, contrivance, procure, contrive, scorn, rill, feeble,
   pity, dainty, awaken, hazy, forthwith, sweep, unfathomable, splendid, yore,
   acacia, caress, fatigue, preternatural, wither, fastness, villainy, foul,
   wane, dread, malign, stagger, sustaining, thigh, gorge, ravine, persevere,
   anguish, nausea, discordant, odour, frightful, faint, incontinently, abysmal,
   aperture, slender, disconcerted, descent, shirk, tint, afield, pallid,
   saliva, decent, deception, devastating, capsicum, wit, froth, broth, 
* consecutive							   :Demo:adj:
[2016-06-26 Sun 17:07]

If things are consecutive, they happen one after the other with no
break. If there are five consecutive snowstorms on five consecutive
days, you'll have to shovel your way out on day six.

Consecutive comes from the Latin consecutus, meaning "following
closely" with no gap. Just like those snowstorms — one storm happened
each day, back to back, for five days in a row. Consecutive numbers
also follow each other, or advance in the right order. For example, 5,
6, 7, 8, 9, 10 are consecutive numbers. You should number the pages on
a term paper to keep them consecutive so the teacher doesn't get
confused.

To shirk your responsibilities is to avoid dealing with them — like
when you watch four consecutive hours of infomercials instead of
facing your homework.

* pallid							   :Demo:adj:
[2016-06-26 Sun 17:47]

Santa looks a little pallid, meaning that he has a pale complexion,
from spending too much time at the North Pole. A few days in Hawaii
might do wonders to add color to his pale, bearded face.

Pallid means pale, or lacking color. It's often used together with
complexion to describe someone who has a pale face, either due to a
lack of sunshine or some kind of emotional distress. A reclusive
author could be pallid from spending too much time indoors. His books
can also be called pallid if they're lacking in color and excitement.

'It may seem odd to you, but it was two days before I could follow up the new-found clue in what was manifestly the proper way. I felt a peculiar shrinking
from those pallid bodies. They were just the half-bleached colour of the worms and things one sees preserved in spirit in a zoological museum. And they were
filthily cold to the touch. Probably my shrinking was largely due to the sympathetic influence of the Eloi, whose disgust of the Morlocks I now began to
appreciate.
* splendid							   :Demo:adj:
[2016-06-26 Sun 17:54]

Looking truly magnificent today? Then someone (probably British) might
stop you to say "Wow! You look splendid, darling!" Thanks the person,
because splendid means glorious, fabulous, wonderful, and/or
splendiferous.

Use the adjective splendid to describe something of the highest
quality. If you're so lucky as to have someone buy you, say, a Harry
Winston diamond, splendid! But splendid doesn't apply only to
expensive items such as jewelry, clothing, or art. You can also have a
splendid idea, morning walk, or encounter with an old friend. For
some, using Splenda in their coffee instead of sugar is, for them,
well, splendid!

'Clearly we stood among the ruins of some latter-day South Kensington! Here, apparently, was the Palaeontological Section, and a very splendid array of
fossils it must have been, though the inevitable process of decay that had been staved off for a time, and had, through the extinction of bacteria and fungi,
lost ninety-nine hundredths of its force, was nevertheless, with extreme sureness if with extreme slowness at work again upon all its treasures. Here and
there I found traces of the little people in the shape of rare fossils broken to pieces or threaded in strings upon reeds. And the cases had in some
instances been bodily removed—by the Morlocks as I judged. The place was very silent. The thick dust deadened our footsteps. Weena, who had been rolling a
sea urchin down the sloping glass of a case, presently came, as I stared about me, and very quietly took my hand and stood beside me.

* stave							     :Demo:noun:verb:
[2016-06-26 Sun 17:57]

A stave is the crosspiece between the legs of a chair or a wooden slat
forming the side of a barrel. In music, it's the five lines you write
notes on.

Stave comes from the word staff, as in a walking stick. You're most
likely to encounter the word stave if you're learning woodworking. If
someone "staves in" a door, they've broken a hole in it. You also
might hear the idiom "stave off," which means to hold off for a short
time.

'Clearly we stood among the ruins of some latter-day South Kensington! Here, apparently, was the Palaeontological Section, and a very splendid array of
fossils it must have been, though the inevitable process of decay that had been staved off for a time, and had, through the extinction of bacteria and fungi,
lost ninety-nine hundredths of its force, was nevertheless, with extreme sureness if with extreme slowness at work again upon all its treasures. Here and
there I found traces of the little people in the shape of rare fossils broken to pieces or threaded in strings upon reeds. And the cases had in some
instances been bodily removed—by the Morlocks as I judged. The place was very silent. The thick dust deadened our footsteps. Weena, who had been rolling a
sea urchin down the sloping glass of a case, presently came, as I stared about me, and very quietly took my hand and stood beside me.
* stall							     :Demo:noun:verb:
[2016-06-26 Sun 19:05]

Stall means to stop or delay. If your car stalls, it comes to a
stop. When you want a horse to stop, you put him in a stall, or small
enclosure inside a barn.

The word stall implies stopping something that will start again — a
horse will leave the stall eventually and start moving, a stalled car
can be restarted. Remember that when you're thinking about stall in
the sense of postpone or delay. You can stall your professor from
giving an exam by talking about last night’s big game. Your little
sister can stall going to bed by asking for one more story. If you
want to delay an approaching army, you might steal their boots —
they'll still come but the "stall tactic" will buy you time.

1) "BTW, there's no toilet paper in that stall...." Not the same kind
of issue in the ladies that it is in the gents. Most of the traffic in
the men's room is headed to a urinal with no need of TP. In the
women's I've both encountered stalls out of TP more often and had
people mention it to other women headed for the deficient stall.

* virtue							  :Demo:noun:
[2016-06-26 Sun 20:55]

Virtue is the quality of being morally good. If you're writing a
screenplay and you want it to be a real tearjerker, make sure your
hero is full of virtue.

The word virtue comes from the Latin root vir, for man. At first
virtue meant manliness or valor, but over time it settled into the
sense of moral excellence. Virtue can also mean excellence in
general. One of your virtues might be your generous willingness to
help out your friends. The phrase by virtue of means "as a result of"
or "by authority of." You will achieve success by virtue of hard work
(or by virtue of inside connections).

Your decisions your life : A great poet once said, "Wisdom is
  knowing what to do and virtue is doing it". Take decisions wisely.

* necessarily							   :Demo:adv:
[2016-07-01 Fri 17:29]

Use the adverb necessarily to mean inevitably. The best man won't
necessarily have to speak at the wedding reception, but he should
probably have a speech ready just in case.

Necessarily also means as a logical result or consequence of some
action. Your English composition grade is necessarily based on the
work you turn in for the class. If you write fairly well, you won't
necessarily get an A, but you just might. Necessarily is made up of
the Latin roots ne, meaning not, and cedere, meaning yield. The
adjective "necessary," from which necessarily comes, originally meant
no backing away.

Science is facts; just as houses are made of stone, so is science made of facts; but a pile of stones is not a house, and a collection of facts is not      
 necessarily science.
* superstition 							  :Demo:noun:
[2016-07-01 Fri 17:31]

A superstition is a belief or practice that isn’t entirely based on
facts or reality, like carrying a rabbit’s foot because you think it
brings you good fortune, or believing that Friday the 13th is a day of
bad luck.

When you pick up a penny, is it because you’re poor or do you think
it’s lucky?  If the quickest route makes you walk under a ladder, will
you do it even though it’s bad luck?  These are two examples of
superstitions, irrational decisions we make for some weird reason.
The Latin roots of the word translate as “standing over,” like how you
freeze standing over a broken mirror. Don’t worry, it’s only a
superstition, right?

Science is the great antidote to the poison of enthusiasm and superstition.
* begets							  :Demo:verb:
[2016-07-01 Fri 17:44]

To beget means to generate something, usually children, and it can be
used to refer to the role of either a mother or a father.

If we analyze the word beget, we get the prefix be-, which tends to
intensify the meaning of the following verb, and get, which means to
cause something to enter one's possession. The word is usually used to
refer to having children, although it can be used to refer to anything
that generates something else — for example, an inspiration can beget
a brilliant idea.

There are in fact two things, science and opinion;
the former begets knowledge, the latter ignorance.
* giddy							      :Demo:verb:adj:
[2016-07-01 Fri 17:52]

If you've ever spun in circles until you fell to the ground laughing,
you know how it feels to be giddy. This adjective can mean dizzy,
elated, or — as in the spinning around example –- a lightheaded,
lighthearted combination of the two.

The hackneyed phrase "giddy as a schoolgirl" calls forth the image of
a kid giggling with her friends over some adolescent
foolishness. Giddy has been used to describe someone incapable of
serious thought or easily excited as far back as the sixteenth
century. Given that, in modern usage, giddy describes someone silly
and frivolous, it's interesting to know that the Old English source
for this word has a slightly darker tinge: gidig means "insane" or
"god-possessed."

If anybody says he can think about quantum problems without getting giddy, that only shows he has not understood the first thing about them.
* lacs								  :Demo:noun:
[2016-07-01 Fri 18:00]

Title: I am working in an MNC with a package of 3.4 lacs per annum. Can I earn upto 15 lacs per annum, inspite of being from a non IIT or non NIT college?
* hike							     :Demo:verb:noun:
[2016-07-01 Fri 18:01]

To hike is to walk a long way at a leisurely pace. You might love to
hike in the woods on weekends.

When you hike, you walk for pleasure, often in a wooded or hilly
area. The trip itself is also a hike, whether you hike the Appalachian
Trail or climb a local hill. Another meaning of hike is "to increase,"
as when the library decides to hike the fees for late books. Hike has
been around since the 1800's, when it was spelled hyke, but its origin
is uncertain. The "walk vigorously" meaning is older than the "raise
or increase" meaning.

And it is happening with me. I was getting even lesser than you. I
asked for 30% hike but they said they can't give.
* fervently							   :Demo:adv:
[2016-07-01 Fri 18:05]

If you fervently believe or feel something, then you believe or feel
it strongly — with a lot of passion.

People feel fervently about a lot of things. A sports fan may be
fervently supportive of a football or basketball team and go to every
game. Many religious people fervently believe in a god. If you're
extremely self-confident, you might fervently believe in
yourself. This word means a lot of passion is present. If you feel
blah about something, or you just like it a little, you don't
fervently believe in it.

But there were days I fervently wished for life before him. There were
days we'd broke down about it. There were nights I didn't want to get
up and walk the little guy back to sleep. And only until I accepted
and went through these things, did I find the joy and peace of my
situation. As he gets older, I slowly regain some freedoms I used to
have, and now I can thoroughly appreciate them, unlike before when I
didn't know a life without them.
* contemplation 						       :noun:
[2016-07-01 Fri 18:20]

Contemplation is long, hard thinking about something. If you’re
writing a book on the meaning of the universe, then you’re going to
need to do a great deal of contemplation.

Contemplate has the word temple in its roots, and originally referred
to the kind of thinking you do in a special space set aside for
observation. Now we use it to describe any kind of thinking that we
spend a long time doing. While clicking on someone’s photos on
Facebook doesn’t count as contemplation, usually, you might spend
hours in contemplation of your family and your history if you come
across a box of old photos in the attic.

It is a melancholy of mine own, compounded of many simples, extracted from many objects, and indeed the sundry contemplation of my travels, which, by often rumination, wraps me in a most humorous sadness.
* sundry						      :Demo:adj:noun:
[2016-07-01 Fri 18:21]

A woman emptying out her purse after many years might find an old
stick of gum, a pair of broken sunglasses, a few movie tickets, and
sundry items, meaning that that her purse was filled with a random
collection of unrelated things.

Most people associate the word sundry with the old-fashioned drugstore
in their neighborhood that used to sell all sorts of odds and ends,
from magazines to hairbrushes. The word is typically used as an
adjective to describe a collection of various different items found in
one place, as in — "I discovered records, perfume bottles, and sundry
items at my neighbor's yard sale." The phrase "all and sundry" refers
collectively to a group of people, as in, "I invited all and sundry of
my relatives to my tea party."

It is a melancholy of mine own, compounded of many simples, extracted from many objects, and indeed the sundry contemplation of my travels, which, by often rumination, wraps me in a most humorous sadness.
* rumination							  :Demo:noun:
[2016-07-01 Fri 18:21]

If someone asks you to make a difficult decision — like what to have
for dinner — it might lead to rumination, or a long period of deep
thought.

Use the noun rumination when there's thoughtful consideration going
on. If your grandfather answers every question by saying, "Hmm. Let me
think about that," he is a fan of rumination. It comes from the verb
ruminate, which means "to think deeply," but also means "to chew the
cud." Both words come from the Latin word ruminatus, which has the
same meaning and which is rooted in rumen, or "gullet."

It is a melancholy of mine own, compounded of many simples, extracted from many objects, and indeed the sundry contemplation of my travels, which, by often rumination, wraps me in a most humorous sadness.
* sojourn						     :Demo:noun:verb:
[2016-07-01 Fri 18:23]

A sojourn is a short stay or visit. If you want a fancy way to say
that you took a trip to the countryside, you might talk about your
country sojourn.

The verb is originally from the Latin prefix sub- "under" plus diurnus
"of a day." You might refer to your vacation as a sojourn, but it
might make more sense if you are describing a trip to Provence rather
than a trip to Disney World. Or In figurative use, sojourn means to
delve––your math teacher may stop midway through lessons on fractions
for a brief sojourn into techniques for slicing pie.

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* cunning						      :Demo:adj:noun:
[2016-07-01 Fri 18:35]

In fairy tales, always watch out for the cunning fox or the cunning
witch. Cunning means clever, in the sense of trickery. A cunning plan
might involve setting traps for the innocent and pure at heart to fall
into.

This adjective goes back to the 14th century English verb cunnen,
which meant "to know," and is actually related to our English verb
know. In earlier times, the noun was used to mean a high level of
skill in using the hands. You can be cunning, but you can also use
your cunning to figure out a very clever and tricky plan.

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* considerable							   :Demo:adj:
[2016-07-01 Fri 18:35]

Use the adjective considerable to describe something that is large in
amount. Things you probably spend a considerable amount of time on:
homework and laundry. Things you'd rather spend time on: anything that
isn't homework and laundry!

The adjective considerable can describe something of importance and is
worthy of notice or respect. If you are an excellent singer, dancer,
musician, writer, or similar profession, people may ask you to donate
your considerable talents to charitable causes. If you're not an
excellent singer, dancer, musician, or writer, they will still ask you
to donate, but they are more likely to ask for money!

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* retain							  :Demo:verb:
[2016-07-01 Fri 18:37]

Retain means to hold on to or keep. People who can retain a lot of
information are often mistaken for geniuses, but really they just have
very good memories.

To retain is to keep or maintain, whether in mind, possession or a
certain condition. If you have a great personal assistant, you'll
probably want to retain him for as long as you can. If your body is
retaining water you might look a little plump. The verbs restrain and
detain sound similar, but they mean to keep something by force.

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* penetratingly							   :Demo:adv:
[2016-07-01 Fri 18:40]
I have attempted to draw an accurate and unexaggerated picture of my family
in the following pages; they appear as I saw them. To explain some of their
more curious ways, however, I feel that I should state that at the time we 
were in Corfu the family were all quite young: Larry, the eldest, was 
twenty-three; Leslie was nineteen; Margo eighteen; while I was the youngest,
being of the tender and impressionable age of ten. We have never been very 
certain of my mother's age, for the simple reason that she can never remember 
her date of birth; all I can say is that she was old enough to have four children. 
My mother also insists that I explain that she is a widow for, as she so 
penetratingly observed, you never know what people might think.
* habitually							   :Demo:adv:
[2016-07-01 Fri 18:45]

Your mind is on autopilot all the time and taking 5-10 minutes a day
to just separate from the neurotic mind is necessary save wasted
energy that goes into fantasizing and daydreaming and being habitually
negative.
* deserve							  :Demo:verb:
[2016-07-01 Fri 18:47]

We deserve things based on our actions. For example, many people
believe murderers deserve the death penalty.

Deserve is used in many ways, but it always carries a sense of balance
or justice. If someone receives an award for their work, it means they
deserve praise and attention. If you deserve a day off, it means
you've been working hard and have earned a vacation. If you threw a
book during class, you deserve a punishment of some kind. Many laws —
and lots of arguments — are about deciding what different people
deserve. It's often hard to tell.

No, instead, I'm going to tell you that in order to feel as good as
you know you want and deserve to feel EVERY DAMN DAY, you need to
exercise so that your body rewards you with happiness, literally. When
your body is happy YOU are happy. When your body is recharged through
exercising, so is your mind, so is your heart, and that energy pours
over into every single part of your life. Don't exercise because the
doctor and your parents tell you its necessary to live a long and
healthy life (obviously its important), but exercise because you want
to operate at maximum capacity on a daily basis, and exercising is
necessary to ensure that.

* savor							     :Demo:verb:noun:
[2016-07-02 Sat 17:11]

Whether it’s a feeling of joy or a piece of pecan pie — when you savor
something, you enjoy it to the fullest.

When you savor something, you enjoy it so much that you want to make
it last forever. With that in mind, savor carries a connotation of
doing something slowly. If you savor that flourless chocolate tart,
then you eat it slowly, bit by bit, deliberately picking every last
crumb off the plate. The word is often applied to eating, but you can
savor any pleasurable experience, whether it’s the winning touchdown
or your moment in the spotlight.

When going to bed do a quick mental check on the things you are
grateful for. I don't mean list them by rote.. I mean "savor" them. "I
am grateful my kids are healthy" "I am grateful I have a fabulous wife
who loves me" "I am grateful my job is close to where I live" "I am
grateful my doctor didn't see anything wrong with me" "I am grateful
for friend X"...
* blasphemy							  :Demo:noun:
[2016-07-02 Sat 17:16]

Saying offensive things about God or religion is blasphemy. Blasphemy
can be used for offensive ideas in other areas too.

If you're saying something bad about a god, or taking the Lord's name
in vain, or questioning a religious institution in any way, you could
be accused of blasphemy — insulting something sacred. You can use this
word in a lot of other ways too. At a meeting of conservatives, a
liberal idea could be considered blasphemy (and vice versa). You might
even jokingly cry "Blasphemy!" if a friend said your favorite ice
cream flavor stinks.

blasphemy
* soliciting						     :Demo:verb:noun:
[2016-07-02 Sat 17:17]

Solicit means to ask for. It is what those people on the street are
doing, when they ask, "Do you have a moment to talk about the
destruction of the planet?" They are soliciting donations for their
cause.

Solicit has an official sounding impressiveness to it––doesn't
soliciting donations sound better than begging for money? It can also
have a more sinister cast. "When the teacher left the room, two girls
solicited their friends to throw all the textbooks out the windows,
injuring members of the cheer squad below — where they were soliciting
signatures for a petition banning smoking in the football locker
rooms."

If you're traveling to the US to do business (that is, making a sales
or professional visit), bear in mind that the attitude between
business associates is not like that found in Mediterranean, Hispanic
or Middle Eastern countries; it is more comparable to that of northern
Europeans. Whereas most Middle Eastern and many Hispanic business
hosts want to “get to know you” first, before doing business (asking
about your family, soliciting personal details, and very possibly
sharing a meal or at least coffee, so they can determine if you have
the kind of character worth doing business with), such personal
questions are considered peculiar, intrusive, and possibly even rude
to Americans. They are also unlikely to want or need to be given a
gift, as is customary in some countries. Like northern Europeans, they
are much more likely to get right down to business, without any
elaborate preliminaries or formalities.
* peculiar						      :Demo:adj:noun:
[2016-07-02 Sat 17:18]

Something peculiar is notably unusual. If your friend starts saying
strange things you don't understand, ask her why she's suddenly become
peculiar.

Peculiar comes from the Latin peculiaris, meaning one's own, or
personal.  In English, it originally meant belonging to one person,
private, like your fondness for your peculiar hairbrush.  It also had
the meaning of something unlike others, special, or
remarkable. Eventually we mostly stopped using it for belongings,
instead using peculiar to mean unusual or odd.

If you're traveling to the US to do business (that is, making a sales
or professional visit), bear in mind that the attitude between
business associates is not like that found in Mediterranean, Hispanic
or Middle Eastern countries; it is more comparable to that of northern
Europeans. Whereas most Middle Eastern and many Hispanic business
hosts want to “get to know you” first, before doing business (asking
about your family, soliciting personal details, and very possibly
sharing a meal or at least coffee, so they can determine if you have
the kind of character worth doing business with), such personal
questions are considered peculiar, intrusive, and possibly even rude
to Americans. They are also unlikely to want or need to be given a
gift, as is customary in some countries. Like northern Europeans, they
are much more likely to get right down to business, without any
elaborate preliminaries or formalities.
* customary							   :Demo:adj:
[2016-07-02 Sat 17:19]

Something customary is done according to practice. When a bride walks
down the aisle, it's customary for everyone at the wedding to rise out
of respect.

Every culture has its own customary traditions.  In American culture
it's customary for a child who loses a tooth to put it under her
pillow and wait for the Tooth Fairy to arrive. In Greece, on the other
hand, it's customary to throw a child's lost tooth onto the roof for
good luck. Customary can also reference habitual things a person does,
like taking your shoes off when you come home, or writing in your
diary before bed.

If you're traveling to the US to do business (that is, making a sales
or professional visit), bear in mind that the attitude between
business associates is not like that found in Mediterranean, Hispanic
or Middle Eastern countries; it is more comparable to that of northern
Europeans. Whereas most Middle Eastern and many Hispanic business
hosts want to “get to know you” first, before doing business (asking
about your family, soliciting personal details, and very possibly
sharing a meal or at least coffee, so they can determine if you have
the kind of character worth doing business with), such personal
questions are considered peculiar, intrusive, and possibly even rude
to Americans. They are also unlikely to want or need to be given a
gift, as is customary in some countries. Like northern Europeans, they
are much more likely to get right down to business, without any
elaborate preliminaries or formalities.
* niceties							  :Demo:noun:
[2016-07-02 Sat 17:21]

тонкости

Clearly, you're interested in the nicety of a word's meaning if you're
checking out this website. A nicety is a fine detail or shade of
meaning that anything — not just a word — can possess.

Even the word nicety has niceties. The emphasis on detail can also
refer to a precision or accuracy of sorts; if someone has judged
something "to a nicety," they've judged it exactly. Yet another common
meaning is in the sense of a minor aspect of polite behavior. Washing
your hands before dinner is a "social nicety." So is covering your
mouth when you cough. Now where would we be without niceties?

Americans do not bow, nor do they normally kiss strangers. A simple
handshake is sufficient upon meeting a business associate; and even
that is unnecessary (and even considered strange) when dealing with
more transient and casual contacts (such as store clerks, hotel
clerks, waiters, cab drivers, etc.). It is sufficient just to say “Hi”
or “Good morning,” and state what you need. Most American service
personnel are used to such informal and abrupt contacts, and are not
offended by a lack of social niceties. HOWEVER – it is NEVER
acceptable to treat such people as your servants! Americans are quite
egalitarian, expect to be treated with a normal level of professional
dignity, and will not put up with ill treatment by a stranger. (And
their employers will usually back up the employee if a customer is
abusive.) If you physically strike a service person who has displeased
you, you may expect to be arrested for assault.
* egalitarian						      :Demo:adj:noun:
[2016-07-02 Sat 17:22]

An egalitarian is a person who believes in the equality of all people,
and an egalitarian society gives everyone equal rights.

This is a word that means something close to equality and has to do
with fairness. If you believe that everyone deserves a chance to vote,
go to school, get good jobs, and participate in society, then you are
an egalitarian. When laws make life fairer, the law is getting more
egalitarian. The opposite of an egalitarian system could be a fascist
society or dictatorship. Monarchies are not egalitarian. When you see
this word, think about equality and freedom.

Americans do not bow, nor do they normally kiss strangers. A simple
handshake is sufficient upon meeting a business associate; and even
that is unnecessary (and even considered strange) when dealing with
more transient and casual contacts (such as store clerks, hotel
clerks, waiters, cab drivers, etc.). It is sufficient just to say “Hi”
or “Good morning,” and state what you need. Most American service
personnel are used to such informal and abrupt contacts, and are not
offended by a lack of social niceties. HOWEVER – it is NEVER
acceptable to treat such people as your servants! Americans are quite
egalitarian, expect to be treated with a normal level of professional
dignity, and will not put up with ill treatment by a stranger. (And
their employers will usually back up the employee if a customer is
abusive.) If you physically strike a service person who has displeased
you, you may expect to be arrested for assault.
* courteously 							   :Demo:adv:
[2016-07-02 Sat 17:23]

учтиво

Women in the workforce are typically treated the same as men:
professionally, courteously and directly. Do not assume that a woman
who meets you for a business or professional appointment is merely a
secretary or assistant; she may be the boss! Treating her dismissively
or disdainfully will probably lose you business. Furthermore, bear in
mind that the US has strict prohibitions in law against sexual
harassment. Making suggestive comments, or unwanted physical contact,
can get you in trouble. The same is true of gay and lesbian people.
* dismissively							   :Demo:adv:
[2016-07-02 Sat 17:24]

To be dismissive is to be indifferent and a little rude. Being
dismissive is a sign of disrespect.

If you're dismissive, you show little consideration for others. If a
teacher laughs at a student's earnest answer to a question, that's
dismissive. An employer throwing a resume in the trash without reading
it? Dismissive. People are dismissive to others they think are beneath
them. You can also be dismissive to ideas and suggestions. It's like
waving someone or something away and saying, "whatever."

Women in the workforce are typically treated the same as men:
professionally, courteously and directly. Do not assume that a woman
who meets you for a business or professional appointment is merely a
secretary or assistant; she may be the boss! Treating her dismissively
or disdainfully will probably lose you business. Furthermore, bear in
mind that the US has strict prohibitions in law against sexual
harassment. Making suggestive comments, or unwanted physical contact,
can get you in trouble. The same is true of gay and lesbian people.
* disdainfully							   :Demo:adv:
[2016-07-02 Sat 17:24]

When you do something disdainfully, you do it with disapproval or
contempt. You might look disdainfully at an airplane passenger who's
yelling at his young son.

When you act disdainfully toward someone, you're expressing your lack
of respect — either for the person himself, or what he's doing. If
your grandmother disapproves of just about everyone she meets, she'll
probably glance disdainfully at your friends when they show up in
their loud car to pick you up. The Old French root of disdainfully is
desdeignier, "scorn, refuse, or repudiate," from des, "do the opposite
of," and deignier, "treat with respect."

Women in the workforce are typically treated the same as men:
professionally, courteously and directly. Do not assume that a woman
who meets you for a business or professional appointment is merely a
secretary or assistant; she may be the boss! Treating her dismissively
or disdainfully will probably lose you business. Furthermore, bear in
mind that the US has strict prohibitions in law against sexual
harassment. Making suggestive comments, or unwanted physical contact,
can get you in trouble. The same is true of gay and lesbian people.
* hardship							  :Demo:noun:
[2016-07-05 Tue 17:01]

If something is a hardship, it causes suffering or
unpleasantness. After all the hardship you endured while training for
the marathon, you really hope that you’ll do well — or at least
finish!

The word hard in hardship is a tip-off to its meaning: something
that’s a hardship is hard. It could be hard work that you do for a
larger goal — like training for the marathon — or it could be a
situation that’s hard to endure. If you lose your job, you could end
up experiencing financial hardship. Sometimes a hardship is something
that just happens, like the hardship people suffer following a
disaster.

* liability							  :Demo:noun:
[2016-07-06 Wed 12:24]

A liability is a debt or obligation or a personal flaw that stands in
your way. A company's liabilities are simply the debts on its ledger,
but a personal liability might be your extreme shyness in social
situations.

Depending on how you use it, the word liability has very different
meanings. In a business or financial sense, a liability is a debt or
fiscal obligation, like a mortgage or a loan. A limited liability
company means if the company fails, the partners are on the hook for
only what they initially invested in the company. A personal
liability, however, is some element of your past, your character, or
your behavior that might give you a disadvantage.

* crutch							  :Demo:noun:
[2016-07-07 Thu 20:24]

A crutch is something you lean on when you’re hurt or weak. It can be
a physical crutch you use because you broke your leg, or a friend you
depend on a bit too much when you’re having a tough time.

A medical crutch is a device that helps you walk when you’re
injured. A psychological crutch helps you when you need it, or think
you do. Medical crutches come in pairs and have soft pads that fit
under your arms and handles to help you rest your body weight on
them. Other types of crutches fit securely around the lower part of
your arm. The Old English root word is crycce, "staff," and the
figurative meaning dates from about 1600.

crutch
* cramped						      :Demo:adj:verb:
[2016-07-07 Thu 20:28]

ограниченный

adjective
 1. ограниченный (limited, bounded, restricted, confined, finite, cramped)
 2. стесненный (cramped, constrained, uneasy, straitened, embarrassed, pinched)
 3. неразборчивый (illegible, indiscriminate, promiscuous, unintelligible, unreadable, cramped)
 4. стиснутый (cramped)
 5. чрезмерно сжатый (cramped)
 6. страдающий от судорог (cramped)
 7. сведенный судорогой (cramped)

DEFINITION

adjective
 1. feeling or causing someone to feel uncomfortably confined or hemmed in by lack of space.
    "the staff had to work in cramped conditions"
 2. suffering from a cramp.
    "cramped muscles"

verb
 1. restrict or inhibit the development of.
    "tighter rules will cramp economic growth"
 2. fasten with a cramp or cramps.
    "cramp the gates to the posts"
 3. suffer from sudden and painful contractions of a muscle or muscles.
    "Her hand had such low muscle tone that it cramped painfully as she tried to control the pencil when she wrote."

* whimsical							   :Demo:adj:
[2016-07-08 Fri 14:19]

Whimsical means full of or characterized by whims, which are odd ideas
that usually occur to you very suddenly. If you decide at the last
minute to fly to Europe, you could say you went there on a whim.

Whimsical can also mean tending toward odd or unpredictable
behavior. Both whimsical and whim are derived from an earlier English
word whim-wham, which is of unknown origin. Whim-wham had about the
same meaning as whim, but could also refer to an odd object or piece
of clothing.

This book by Randall Munroe (which is actually a compilation of posts
from his wickedly popular blog xkcd) is equally whimsical and
informative. He explores questions like “from what height would you need
to drop a steak for it to be cooked when it hit the ground?” and “what
would happen if you made a periodic table out of cube-shaped bricks,
where each brick was made of the corresponding element?” and he provides
explanations that are well-researched, sourced and scientifically valid,
while still using a giraffe as a measurement for height. You’ll be
entertained, and Mr. Gates says, “you’ll also learn about a lot of other
things like ballistics, DNA, the oceans, the atmosphere and lightning.”
* plea								  :Demo:noun:
[2016-07-08 Fri 14:30]

A plea is what you make when you're begging for something with a sense
of urgency and emotion. While you wouldn't call asking for a hall pass
a plea, you could make a plea for justice or world peace.

Plea also has a legal meaning. When you get a traffic ticket or if
you're accused of a crime, you have to enter a plea of "guilty" or
"not guilty." A "plea bargain" is when you make a deal with the
prosecutor — you may plead guilty to a charge (by entering a guilty
plea) that has less of a penalty and, in return, the prosecutor drops
the more serious charge.

In this Richard Dawkins book, he poses a question at the beginning of
each chapter, offers colorful myths from different places around the
world and finally reveals an elegant scientific answer. “It’s an
engaging, well-illustrated science textbook offering compelling answers
to big questions, from how the universe formed to what causes
earthquakes,” Mr. Gates writes in his review. “It’s also a plea for
readers of all ages to approach mysteries with rigor and curiosity,
rather than buying into the supernatural myths at the core of most faith
traditions.”

* amend								  :Demo:verb:
[2016-07-08 Fri 20:09]

When you amend something, you correct or improve it. If you confused
your audience when you gave your speech, don't be afraid to amend what
you said.

Amend can also describe adding amendments to an official document,
such as a constitution or law. If politicians in your state want to
address the growing number of home foreclosures, they might amend the
state constitution to include restrictions intended to reduce
foreclosures. Amend comes from the Latin word emendare, meaning "to
correct, free from fault."

amend
* deceive							  :Demo:verb:
[2016-07-08 Fri 20:10]

To deceive means to trick or lie. A crafty kid might deceive his
mother into thinking he has a fever by holding the thermometer to a
light bulb to increase the temperature.

Deceive is the trickier cousin of lie. You might lie about why you
were late to school. But if you simply don't explain to your mom that
you were late in the first place, you are deceiving her. Deceive
carries with it a feeling of both craftiness and betrayal. When you
deceive someone, forgiveness can be hard to come by. Have you heard of
the spelling rule, "i before e except after c" that has so many
exceptions? Well, deceive follows that rule.

deceive
* profanity							  :Demo:noun:
[2016-07-08 Fri 20:25]

Profanity is a type of language that includes dirty words and
ideas. Swear words, obscene gestures, and naughty jokes are all
considered profanity.

You know those four-letter words you're not supposed to say? They're
profanity: language that's vulgar and obscene. R-rated movies and
cable stations like HBO have a lot of profanity, but you won't hear it
on a station like NBC or ABC. Profanity tends to be about off-color
subjects, like sex and going to the bathroom. Everyone probably spews
some profanity at some point, but you better be careful about who's
listening.

profanity
* outburst							  :Demo:noun:
[2016-07-08 Fri 20:26]

When you can't help an angry shout or a burst of emotion, that's an
outburst. A toddler's outburst might take the form of a full-blown
temper tantrum.

An outburst of passion or emotion can be angry words, a broken glass,
or a triumphant whoop. There are also figurative outbursts, like the
outburst of political enthusiasm within a particular group of voters,
or an outburst of energy in the midst of a modern dance
performance. The Middle English verb that proceeded outburst was
outbresten.

"an outburst of profanity"

* obscene							   :Demo:adj:
[2016-07-08 Fri 20:28]

Obscene describes something that is morally offensive in a sexual
way. It's never a good idea to use obscene language at school.

Certain films, books, magazines, and other forms of entertainment are
considered obscene because they portray sex in a very frank way that
some people find vulgar and lewd. Obscene material, language, and
jokes are considered taboo in polite society. Obscene can also be used
to describe something repulsive — like when your friend ate an obscene
number of snails at the Bastille Day bash.

obscene
* decency							  :Demo:noun:
[2016-07-08 Fri 20:29]

The personal quality of decency is one of honesty, good manners, and
respect for other people.

Over time, decency has referred to manners, but today decency is
mainly a strong sense of right and wrong, and a high standard of
honesty. When a criminal or dictator does horrible things, people
assume they have no sense of decency. When a tasteless or violent TV
show becomes popular, some people wonder if society has lost its sense
of decency. Asking "Have you no decency?" is a serious question,
unless you're being silly and complaining about something like
homework.

decency
* unjust							   :Demo:adj:
[2016-07-08 Fri 20:29]

Something or someone that is unjust is just not fair. An unjust boss
might fire you the very first time you're late for work.

You might think of the word justice in order to remember the meaning
of the word just, which means "fairness or righteousness." An unjust
judge does not play by the rules; he might send a person to jail even
though there isn't enough evidence that a crime was committed. Unjust
behavior is improper or dishonest: "The professor acted in an unjust
manner when he gave everyone an F just because there was a rumor that
his students didn’t like him."

unjust
* infuriating						      :Demo:adj:verb:
[2016-07-08 Fri 20:30]

Use the adjective infuriating to describe something that makes you
really, really angry. It's infuriating to see a little kid being
bullied.

When something makes you furious it's infuriating. You can use the
word to talk about things that are truly offensive or outrageous —
someone snatching your grandmother's purse, for example — or things
that are merely aggravating or annoying. You might find it infuriating
trying to parallel park on a busy street or waiting in line at the
post office. The roots of infuriating can be traced all the way back
to the Latin furere, which means "to rage" or "to be mad."

infuriating
* hapless							   :Demo:adj:
[2016-07-08 Fri 20:31]

Use the adjective hapless to describe someone unlucky and deserving of
pity, like the hapless used car buyer who gives in to the fast-talking
salesperson.

The word hapless traces all the way back to the Old Norse word happ,
meaning “chance, good luck.” Combine this with the suffix -less
(“lacking”) and hapless means “unlucky” or “ill-fated.”  A traveler
who goes to Moscow and briefly gets lost on the subway? Just a
tourist. A traveler who goes to Moscow, accidentally eats food he is
allergic to, somehow loses all his money, and by chance gets on a
train destined for Mongolia? Definitely hapless.

hapless
* inflict							  :Demo:verb:
[2016-07-08 Fri 20:32]

When you force an undesirable or harmful event on someone, you inflict
it on them. You might prefer that someone inflict some physical pain
on you rather than inflict you with the boredom of another trip to the
annual flower show.

The verb inflict comes from the Latin word inflictus, meaning “to
strike or dash against.” If you cause anything bad to happen to a
person, animal, or even an object, you inflict that badness on
them. For example, someone can inflict injuries or suffering on other
people or inflict damage on property. We can inflict pollution or
over-development on our environment. It's always a negative thing —
you wouldn't say you inflict happiness or love on others.

inflict
* muggy								   :Demo:adj:
[2016-07-08 Fri 20:33]

Think of hot, humid, steamy weather as being so unpleasant that you
feel "mugged" by it when you step outside. That's one way to remember
the meaning of muggy.

"It's not the heat! It's the humidity!" That's what your grandma says
when she wants to complain about muggy weather. Muggy means a
combination of humidity and heat that makes you sweaty and
uncomfortable and long for air-conditioning. You might be cursing the
cold and the snow today, but mark my words, come August and the muggy
dog days of summer, you'll be nostalgic for the cold.

muggy

* generosity							  :Demo:noun:
[2016-07-10 Sun 11:46]

Generosity is a quality that's a lot like unselfishness. Someone
showing generosity is happy to give time, money, food, or kindness to
people in need.

Generosity is a quality — like honesty and patience — that we all
probably wish we had more of. When you show generosity, you might give
away things or money or put others before yourself.  But generosity is
about more than cash and stuff. When you're forgiving and gentle to
people, you show generosity of spirit. If you give others help or
credit, that shows generosity. The world would certainly be a better
place if more people showed generosity to others.

My grateful thanks, then, to:
    Dr Theodore Stephanides. With typical generosity, he allowed me to make use of material from his unpublished work on Corfu, and supplied me with a number of dreadful puns, some of which I have used.
* puns							     :Demo:noun:verb:
[2016-07-10 Sun 11:47]

A pun is a play on words. If a bird flying overhead takes a poop on
the cake you’re carrying, you could say “Isn’t that just the icing on
the cake!” But only if you want to be punny.

Friend of the double entendre and other witticisms, a pun is a comedic
phrase that plays off of the sounds and double meanings of words. Puns
can be quite clever, but often come off as silly, cheeseball attempts
at humor. That's probably why any good comedian will tell you that "a
pun is a short quip followed by a long groan."

My grateful thanks, then, to:
    Dr Theodore Stephanides. With typical generosity, he allowed me to make use of material from his unpublished work on Corfu, and supplied me with a number of dreadful puns, some of which I have used.
* dreadful							   :Demo:adj:
[2016-07-10 Sun 11:47]

Something that's terribly bad is dreadful. Some people love going to
the opera, but for others there's no more dreadful way to spend three
hours.

Dreadful means "full of dread," "feeling a sense of dread," or
"causing dread." Dread means fear or anxiety. The adjective dreadful
can describe something truly devastating, like the dreadful aftermath
of a tornado, or something that's awful on a more personal level, like
a dreadful blind date. If it's bad, fearsome, or unpleasant, you can
call it dreadful.

My grateful thanks, then, to:
    Dr Theodore Stephanides. With typical generosity, he allowed me to make use of material from his unpublished work on Corfu, and supplied me with a number of dreadful puns, some of which I have used.
* unconsciously							   :Demo:adv:
[2016-07-10 Sun 11:51]
бессознательно

adverb
 1. бессознательно (unconsciously)

My family. They, after all, unconsciously provided a lot of the material, and helped me considerably during the writing of the book by arguing ferociously and rarely agreeing about any incident on which I consulted them.

* ruthless							 :Family:adj:
[2016-07-10 Sun 11:57]

Ruthless means showing no mercy or compassion. If you really want to
cut down on the clutter in your apartment, you can't be sentimental
about keepsakes. You have to be ruthless and throw out everything
that's not absolutely essential.

If you're ruthless, you're the polar opposite of Mother Theresa. You
get called heartless and cold-blooded. That's one of the reasons the
word crops up so often to describe dictators and tyrants, though it
can also apply to other personality types — like corporate raiders and
colleagues so success-driven that they'll gladly steamroll anyone to
get ahead. It finds its way into milder contexts, too: Just be
ruthless and rip off the Band-Aid already!

Sophie, my secretary, who was responsible for the introduction of commas and the ruthless eradication of the split infinitive.
* eradication							:Family:noun:
[2016-07-10 Sun 11:57]

When people talk about the eradication of something, they are
referring to its total destruction. Imagine a movie villain destroying
a planet with a massive laser beam and you'll have the right idea.

If a gardener's goal is the eradication of every single weed in his
back yard, he might start by uprooting dandelions. Fittingly, the root
of eradication is the Latin word for "uproot," ērādīcāre. The
eradication of anything, whether it's disease, poverty, war, or weeds,
involves removing every last trace of it, right down to the roots.

Sophie, my secretary, who was responsible for the introduction of commas and the ruthless eradication of the split infinitive.
* intact							 :Family:adj:
[2016-07-10 Sun 12:24]

If something is intact it's still in one piece. If you'd like your
sand castle to remain intact, I suggest you build it away from the
water.

The Latin word intactus means “untouched,” but today something is
intact if it's whole, if it hasn't fallen apart. After a long day at
work, you might feel lucky to be intact. Your letter to the post
office states that you would prefer your packages to arrive intact
from now on.

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* crate 						   :Family:noun:verb:
[2016-07-10 Sun 12:37]

A crate is a wooden container that's made for transporting or shipping
goods. Your uncle might send you a crate of Florida oranges for a
Christmas gift.

Boxes made of wood that are filled with goods and loaded on trucks,
ships, or planes are called crates, and to fill them is also to
crate. Groceries are often shipped or delivered in crates, like crates
of eggs, milk crates, or a crate of bananas. The amount of some item
that fits in one crate is also called a crate — "The market ordered
seven crates of ice cream for the Fourth of July weekend."

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* quailed							:Family:verb:
[2016-07-10 Sun 12:38]

Smaller than the chicken and not as well known as the pigeon, quail is
like the often-overlooked middle child of the ground-dwelling bird
family. Quail can also mean to cringe in fear or pain. So if you are a
quail, you might quail at the thought of quail-hunting season.

Quail is a broad, catchall word; it can refer to any one of many small
domestic game birds.  So if you’re bragging about the quail you shot
on a hunting trip to your uptight, bird-obsessed pals, they might
demand to know if it was the Bobwhite quail, the Valley quail or the
Scaled quail, to name just a few. If you use this word as a verb, it
means to draw back in fear or pain. You might quail in fear at the
sight of a playground bully. A good way to remember this verb meaning
is to think of how the word chicken is also associated with fear.

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* contingency							:Family:noun:
[2016-07-10 Sun 12:40]

If you plan to walk home if the weather is nice, but bring subway fare
just in case, then taking the subway is your contingency plan. A
contingency is an event you can't be sure will happen or not.

The noun contingency describes something that might or might not
happen. We use it to describe an event or situation that is a possible
outcome but one that's impossible to predict with certainty. A company
might have a contingency plan for what to do if something goes wrong
with their primary strategy, also known as "plan B." They might even
have plans C, D, and E, to prepare for multiple contingencies.

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* flamboyant							 :Family:adj:
[2016-07-10 Sun 12:46]

Flamboyant means elaborate and ostentatious. When you think of
flamboyant, think of Las Vegas showgirls: feathers, sequins,
three-inch heels, enough make-up to disguise any irregularity.

Flamboyant means showy, and though we often roll our eyes at it, it's
not a hateful thing. Liberace was flamboyant. So was Elvis. The word
comes from the French flamboyer, to flame. Think of passion and
pageantry all rolled into one, and you'll have a good idea what
flamboyant should mean at its best. If that doesn't do it for you,
think of a man playing a shiny white grand piano at a rock concert,
wearing a white satin jump suit and 8-foot wide, fully-feathered
wings. See? Flamboyant.

Lastly, I would like to make a point of stressing that all the anecdotes about the island and the islanders are absolutely true. Living in Corfu was rather like living in one of the more flamboyant and slapstick comic operas. The whole atmosphere and charm of the place was, I think, summed up neatly on an Admiralty map we had, which showed the island and the adjacent coastline in great detail. At the bottom was a little inset which read:
    CAUTION: AS the buoys marking the shoals are often out of position, mariners are cautioned to be on their guard when navigating these shores.
* slapstick							:Family:noun:
[2016-07-10 Sun 12:48]
хлопушка

noun
 1. фарс (farce, slapstick)
 2. хлопушка (slapstick, flapper, petard, flap)
 3. дешевый фарс (slapstick comedy, slapstick)
 4. грубый фарс (slapstick comedy, knockabout, slapstick)

DEFINITION

noun
 1. comedy based on deliberately clumsy actions and humorously embarrassing events.
    "slapstick humor"

* adjacent							 :Family:adj:
[2016-07-10 Sun 12:49]

Adjacent means close to or near something. You may consider the people
up and down your street to be neighbors, but your next-door neighbor
is the person who lives in the house or apartment adjacent to yours.

Adjacent can refer to two things that touch each other or have the
same wall or border. And the adjective is often followed by the
preposition to: Her office is adjacent to mine. This word is from
Latin adjacere "to lie near," from the prefix ad- "to" plus jacere "to
lie, throw."

Lastly, I would like to make a point of stressing that all the anecdotes about the island and the islanders are absolutely true. Living in Corfu was rather like living in one of the more flamboyant and slapstick comic operas. The whole atmosphere and charm of the place was, I think, summed up neatly on an Admiralty map we had, which showed the island and the adjacent coastline in great detail. At the bottom was a little inset which read:
    CAUTION: AS the buoys marking the shoals are often out of position, mariners are cautioned to be on their guard when navigating these shores.
* inset							   :Family:noun:verb:
[2016-07-10 Sun 12:50]
вставка

noun
 1. вкладка (inset)
 2. вклейка (insert, inset, plate)
 3. вставка в платье (inset)

verb
 1. вставлять (insert, inset, interpose, paste, embed, plug)
 2. вкладывать (invest, put up, insert, inlay, enclose, inset)

DEFINITION

noun
 1. a thing that is put in or inserted.
    "a pair of doors with their original stained-glass insets"

verb
 1. put in (something, especially a small picture or map) as an inset.
    "type in the text to be inset"

Lastly, I would like to make a point of stressing that all the anecdotes about the island and the islanders are absolutely true. Living in Corfu was rather like living in one of the more flamboyant and slapstick comic operas. The whole atmosphere and charm of the place was, I think, summed up neatly on an Admiralty map we had, which showed the island and the adjacent coastline in great detail. At the bottom was a little inset which read:
    CAUTION: AS the buoys marking the shoals are often out of position, mariners are cautioned to be on their guard when navigating these shores.

* rusty								   :Demo:adj:
[2016-07-11 Mon 06:04]

If your German is rusty, it's like the bike you left out in the rain
too many times that turned brown and flakey on the metal parts. Like
your bike, your German skills became rusty, meaning they're suffering
from neglect.

You can also describe yourself as rusty: you used to do flips on your
skateboard, but you haven't practiced in a while and now you're a
little rusty. Rusty can also refer to the color of rust, which is a
reddish-brown — a rusty-colored dog, for instance. Anything made of
iron or steel that you leave outside in the elements is likely to
oxidize and become rusty, covered with rust.

The skills are rusty, but the knowledge is still there. I'm ready for
the zombie apocalypse.

* reinforce :Demo:
[2016-07-15 Fri 18:31]

To reinforce means to make stronger. You can reinforce your roof by
putting some extra supports under it.

Besides a physical structure, there are many things you can
reinforce. If you want to reinforce a message, you can say it louder,
rephrase and repeat it or give examples of what you expect. You use
dog biscuits to reinforce certain behaviors in your dog. Bad
experiences will reinforce your fears, good ones your hopes. And when
military leaders reinforce their troops, they send additional soldiers
to the front.

Anything you reinforce. So.

* voraciously							   :Demo:adv:
[2016-07-15 Fri 18:33]
 =5=0AKB=>

adverb
 1. =5=0AKB=> (insatiably, voraciously)

* glowing							  :Quora:adj:
[2016-07-15 Fri 18:39]

If something is glowing, it's either lit up like a light or it's full
of praise and enthusiasm. So, you could receive a glowing candle or a
glowing report card. You choose.

When a report or account is glowing, it's unreservedly positive, like
a book critic's glowing review of a new mystery novel or your
grandmother's glowing praise for the good job you did mowing her
lawn. Glowing comes from glow, which can mean "a flush of radiant
feeling," and which comes from the Old English glowan, "to glow or
shine as if red-hot."

Any major work experience (a Job) is considered an Excellent
extracurricular activity, as long as you get a glowing letter of
recommendation from a non-relative manager/supervisor.

* praise						    :Quora:verb:noun:
[2016-07-15 Fri 18:42]

Praise means "admiration or approval," and when you're on the
receiving end of it, you feel great.

Whether it's used as a verb or a noun, praise means "approval." If you
enthusiastically praise your dog, he's likely to wag his tail and
expect a treat. What you've given him (in addition to the treat) is
praise, the noun. In a religious context, the verb praise is
interchangeable with worship, as when a minister says, "Praise God."

verb
 1. хвалить (praise, commend, compliment, laud, talk up, glorify)
 2. восхвалять (praise, eulogize, magnify, exalt, sing the praises of, glamorize)
 3. превозносить (exalt, praise, extol, glorify, laud, eulogize)

* toughy							 :Quora:noun:
[2016-07-15 Fri 18:45]

noun
 1. крепкий орешек (toughie, toughy)
 2. трудная проблема (toughy, toughie)
 3. непокладистый человек (tough customer, toughie, toughy)
 4. тяжелый человек (difficult person, toughy, terror, toughie)
 5. хулиган (bully, hooligan, hoodlum, ruffian, tough, toughie)

* refinement							   :LPT:noun:
[2016-07-16 Sat 08:49]

Do you know which fork is for your salad and which one is for dessert?
Then you have some refinement — good manners and taste.

Things that go through a process of refinement have been refined;
they've lost their rough edges. For people, this means they have good
manners, and for substances like oil and sugar, it means that their
impurities have been removed. With refinement, things and people
become more acceptable: the sugar's refinement makes it appropriate to
serve at a fancy party, and your refinement makes you a perfect guest
there.

This gives you a pretty basic understanding of what we'll be talking
about in this book. There are many refinements and tools to make the
process quicker and easier, but the basic idea is to tell the computer
what you expect, using simple and easily-written chunks of code, and then
tell the computer to double-check your expectations throughout the coding
process. Because expectations are easy to describe, you can write them
down first, allowing the computer to shoulder much of the burden of
debugging your code. Because expectations are easy to describe, you can
write them down fast, allowing you to move on to interesting things while
the computer keeps track of the rest.

* lure							      :LPT:verb:noun:
[2016-07-16 Sat 08:57]

To lure is to entice or bait someone.  A lure is used to bait or
entice fish to attach themselves to your hook.  "He had a new shiny
lure, which was enough to lure me into going on the fishing trip."

The verb lure is related to words that mean “bait,” “deceit,” and
“invite.”  Often, when lure is used, there is a nefarious implication,
as in: “He was able to lure her into the alley, but her friends soon
came looking for her.”  The noun lure is the thing that draws in the
person or animal, which can be either a physical object or a concept.
"The lure of his great wealth kept her in the relationship despite his
infidelity."

For this reason, newcomers to automated testing are sometimes lured into
ignoring the distinction between unit testing and integration testing.

* encompass							   :verb:LPT:
[2016-07-16 Sat 08:58]

Encompass means to contain. When you see the word, picture a campus
which encompasses lecture halls, a football field, a medical center, a
dining hall and some parking lots.

Encompass can be used when talking about anything that contains
something else. A lecture on Edward Hopper might encompass all aspects
of his life and art, a work of art could encompass many techniques,
and a policeman's jurisdiction may encompass an entire state. The
continental U.S. encompasses 48 states. This entry encompasses many
examples of the word encompass in use!

In integration testing, the boundaries of isolation are pushed further
back, so that the tests encompass the interactions between related units.

* shoulder :LPT:
[2016-07-16 Sat 09:09]

noun
 1. the upper joint of the human arm and the part of the body between this and the neck.
    "Occasionally it starts in one region such as the neck and shoulders and spreads over a period of time."
 2. a part of something resembling a shoulder in shape, position, or function.
    "the shoulder of a pulley"
 3. a paved strip alongside a road for stopping on in an emergency.
    "My partner and I had parked on the shoulder of the highway and began to chat."

verb
 1. put (something heavy) over one's shoulder or shoulders to carry.
    "we shouldered our crippling backpacks and set off slowly up the hill"
 2. push (someone or something) out of one's way with one's shoulder.
    "she shouldered him brusquely aside"

allowing the computer to shoulder much of the burden of debugging your code

* legit :Quora:
[2016-07-16 Sat 09:36]

adjective
 1. legal; conforming to the rules.
    "is this car legit?"

Title: Is Udacity's job placement guarantee legit?

* eligible :Quora:
[2016-07-16 Sat 09:39]

If you get good grades, volunteer at the hospital, play varsity
sports, and write for your school paper, you might be eligible for a
college scholarship.

If you’re eligible for something, you’re either qualified for it or
allowed to do it. You’re eligible for unemployment benefits if you’ve
recently been laid off, but not if you've never had a job in the first
place. You may not be eligible to enter a sweepstakes if you work for
the company giving away the money. Neither your dog nor your friend
from Australia is eligible to run for president of the United States,
but you might be!

Like these programs, Udacity's program has the limitation that you
must be able to work in the United States (so only 5% of people are
even eligible).
* discarded :Quora:
[2016-07-16 Sat 12:32]

adjective
 1. выброшенный (ejected, discarded, rejected)
 2. выкинутый (ejected, discarded, rejected)

* noble :Quora:
[2016-07-16 Sat 12:38]

A noble is a titled peer of the realm or an aristocrat. As an
adjective, noble describes someone with high or elevated character, or
who is impressive in appearance.

From feudal times, we have known nobles as the heirs to thrones or as
the holders of aristocratic title. British aristocracy, for example,
produces many people of various noble titles, including dukes, earls,
princes, kings, and queens. As various royal histories tell us,
however, many of these nobles in title weren't quite so noble in
character.

Tywin understands, and so does Tyrion. that killing 10,000 men in
battle is not noble.
* intentionally :Quora:
[2016-07-16 Sat 12:39]

adverb
 1. C<KH;5==> (deliberately, intentionally, willfully, wittingly, by design, designedly)

DEFINITION

adverb
 1. deliberately; on purpose.
    "I didn't do it intentionally"


Then she became pregnant - intentionally, by accident, or
accidentally-on-purpose, I have no idea.

* besotted :Quora:
[2016-07-16 Sat 12:42]

adjective
 1. >4C@<0=5==K9 (besotted, intoxicated, dopey, blotto, dopy, zonked)
 2. >?LO=5==K9 (intoxicated, drunk, besotted)
 3. >A;5?;5==K9 (blindfolded, besotted)

DEFINITION

adjective
 1. strongly infatuated.
    "he became besotted with his best friend's sister"
 2. intoxicated; drunk.
    "After some time, the brigands landed at an island, where they became besotted with drink, and fell asleep."

Their son duly arrived, and instantly became the central joy in his
life. My nephew is now 13, a happy, confident, outgoing boy with two
cheerfully besotted parents. Okay, so they stuck at one - but I don't
think they have ever regretted having him.

* hangover 							      :Quora:
[2016-07-19 Tue 18:51]

noun
 1. a severe headache or other after effects caused by drinking an excess of alcohol.
    "These side-effects are far more severe than a hangover and can act as a strong deterrent to drinking."

* commitment :Quora:
[2016-07-19 Tue 18:33]

Making a commitment involves dedicating yourself to something, like a
person or a cause. Before you make a commitment, think carefully. A
commitment obligates you to do something.

Some commitments are large, like marriage. When you take a job, you're
making a commitment to show up and do the job well, and your employer
makes a commitment to pay you. There are smaller commitments too. If
you said you'd meet a friend at six, that's a commitment  show up or
your friend will be mad. You also can speak of commitment as a
quality. Staying after school for a study group shows your commitment
to good grades.

7. Love is a broad spectrum - Love is a commitment. Love is being
there for someone when things go south. Love is making adjustments and
compromising.

* asset :Quora:
[2016-07-19 Tue 19:02]

An asset is something you have that is positive. It can mean a piece
of property, a piece of equipment, an ability, or even a quality.

"Her facility with math is an asset when it comes to figuring out the
restaurant tab. She is an asset to the group." A person's overall
financial picture is determined by lining up everything they own in
the asset column, and everything they own in the liability (or debit)
column.

In terms of humility, depending on your educational background, you
may end up in a situation where you feel intellectually ahead of some
of your more experienced colleagues, or more familiar with modern
technology, or so forth. But there is also a lot you can learn from
your colleagues and being a friendly and humble person to work with is
always an asset.
* groove :Quora:
[2016-07-19 Tue 19:07]

A groove is an indentation or rut in something — like the grooves on
an old record.

Groove is rooted in an old Dutch word for "furrow" or "ditch." And
that's just what a groove is: a carved out line, like wheel ruts in a
muddy road or the narrow opening that a sliding door moves in. If you
can't "find your groove," you feel off track and out of whack. But
when you're "in the groove," everything is working smoothly and you've
found a good routine. And if someone says "let's groove!", they want
to dance.

She did not just tell me. She actually made me repeat after her
several times, so it wore a groove.
* dorm :Quora:
[2016-07-19 Tue 19:09]

A dorm — short for dormitory — is a place where college or university
students live. You'll find a lot of bunk beds in most dorms.

If you go away to college, you’ll probably live in a dormitory — or
dorm. It's much more common for students to say dorm because it's
shorter and slangier. A dorm is where students live, often with
roommates. Dorms have laundry rooms and rec rooms, and it's a place
where many friendships are made. Students often study or try to avoid
studying in the dorm. It's their home away from home. Dorms are also
called residence halls and student residences.

When I was 18, I was a full-time college student. I was living in a
dorm on campus, about an hour and a half away from my hometown. I
worked a minimum wage job washing dishes in the cafeteria when I was
at school, and I worked at the McDonald's in my hometown when I was
there for breaks. I was still financially dependent on my parents.

* hookup 							      :Quora:
[2016-07-19 Tue 19:12]

noun
 1. a connection to a public electric, water, or sewer line, or to a similar service.
    "the campground has 70 sites with water and sewer hookups"

* sewer :Quora:
[2016-07-19 Tue 19:16]

noun
 1. an underground conduit for carrying off drainage water and waste matter.
    "A common problem is the unlawful channelling of storm water drainage into the sewer system."
 2. a person who sews.
    "Irene Caldwell is the company's costume designer who works with a small group of budding sewers ."

* poultry :MoonWalk:
[2016-07-22 Fri 08:56]

noun
 1. domestic fowl, such as chickens, turkeys, ducks, and geese.
    "Specific arrangements may need to be put in place for poultry , horses, fish and exotic livestock."

From the perspective of the poultry farmer, male chickens are useless.
* ornery :MoonWalk:
[2016-07-22 Fri 08:57]

To be ornery is to be grumpy and hard to please. Oscar the Grouch?
Definitely ornery.

The adjective ornery sprung up in the early 19th century when people
started pronouncing ordinary with an accent.  The root of ordinary is
the Latin word for “order,” and if you disrupt the orderly existence
of an ornery person, prepare to get yelled at.  A person can have a
consistently ornery personality, or maybe you’re feeling ornery today
because you skipped breakfast.  Some synonyms for ornery are
cantankerous and crotchety, words that sound as grumpy as the people
they describe.

* vexed :MoonWalk:
[2016-07-22 Fri 08:59]

Vexed means "difficult and much debated." If your family is having
trouble coming to an agreement about where to go on vacation next
summer, your holiday trip has become a vexed issue.

When people can't resolve an issue or find a solution, it is a vexed
problem — one that's become complicated because of differing and
probably strong opinions. Vexed can also describe being irritated. If
you borrowed your sister's car without asking permission, and if she
had a fancy way of putting things, she might tell you she's incredibly
vexed with you right now.

* divulge :MoonWalk:
[2016-07-22 Fri 09:01]

If you've been sneaking around with your best friend's boyfriend,
that's probably one secret you don't want to divulge, because
revealing that tidbit of information will probably cut your friendship
short.

Divulge often precedes the word secret, because it means to reveal
something, and that something is often of a personal or private
nature. A gossip columnist's job is to divulge which celebrities are
secretly dating and which ones have been caught in embarrassing
situations. Although the word comes from the Latin word for making
something public to the masses, it can also be used to describe
information passed from one person to another. For example, a mother
could divulge to her daughter that she was adopted.

* unveiled :MoonWalk:
[2016-07-22 Fri 09:43]

verb
 1. remove a veil or covering from, especially uncover (a new monument or work of art) as part of a public ceremony.
    "the mayor unveiled a plaque"

* dexterity :MoonWalk:
[2016-07-22 Fri 09:48]

If you fall asleep with your heavy head on your arm, you might not
have the dexterity, or control of your hand, to hit the OFF button on
the alarm clock in the morning.

Very small children do well with mittens, because their dexterity, or
skill in using their hands, isn’t as developed as in older kids and
adults, who wear gloves to separate their fingers. Dexterity helps
fingers and hands to coordinate for completing fine tasks like
writing, sewing, and playing string instruments. "Mental dexterity"
means a sharpness of mind, or skill in thinking creatively and
understanding and expressing something quickly and easily.

* convex :MoonWalk:
[2016-07-22 Fri 09:50]

If something is bulging outwards in a curve, it's convex in shape. The
surface of a soccer balls, old television screens, and eyeballs are
all convex in shape.

One of the most famous uses of a convex shape are the curving mirrors
in a fun house. Not to be confused with its popular partner, the
concave mirror, which curves inwards. How can you tell which is which?
If you look like you're three feet tall and weigh 300 pounds, you're
looking in a convex mirror. If you look like you're twelve feet tall
weigh 30 pounds, you're looking in a concave mirror. Enjoy!

* concave :MoonWalk:
[2016-07-22 Fri 09:51]

Concave describes an inward curve; its opposite, convex, describes a
curve that bulges outward. They are used to describe gentle, subtle
curves, like the kinds found in mirrors or lenses.

A valley is a concave curve, a mountain is a convex curve—you can
remember this by thinking that things that vex you tend to stick out,
and that caves tend to be holes that go in, like valleys or innie
belly buttons. If you want to describe a bowl, you might say there is
a large blue spot on the center of the concave side.

* bead :MoonWalk:
[2016-07-22 Fri 09:52]

A bead is a small bauble or jewel with a hole through its middle for
stringing on a necklace or bracelet. You can make your own jewelry by
stringing colorful beads on a long cord.

Beads are decorative balls made from stone, glass, or plastic. Rosary
beads — or other prayer beads — are used for praying or meditating,
and in some societies beads are the equivalent of money, used as
currency to buy things. You can also describe a round drop of liquid
as a bead, like a bead of sweat on your forehead. The earliest meaning
of bead is "prayer bead," from the Old English gebed, "prayer."

* captivating :MoonWalk:
[2016-07-22 Fri 09:54]

The adjective captivating describes something that's completely
enthralling and holds your attention. You might find a marathon of
episodes of a TV show so captivating that you forget to eat dinner.

When people are captivating, they're often very intelligent,
attractive, charming, or otherwise fascinating. Something that catches
and holds your interest is captivating, like a captivating mystery
novel you just can't put down. In fact, this adjective comes from the
Latin captivatus, "to take or capture," and early in its use,
captivating had that literal meaning. Now it's only used to mean
capturing interest.

* perceives :MoonWalk:
[2016-07-22 Fri 09:56]

When we perceive something, we become aware of or notice it. Sometimes
we perceive things by using our senses of sight, hearing, and smell.

Or we can use our mind to perceive things, which means that we are
able to recognize or understand them. We can also perceive a person or
thing as having certain qualities: Do you perceive yourself as a good
student? The Latin root percipere means "to receive, understand," from
the prefix per- "thoroughly" plus capere "to seize, take."

* plush :MoonWalk:
[2016-07-22 Fri 10:05]

Things that are plush are luxurious and a little over the top. A
bedspread made of mink fur would be considered plush.

Plush originally referred to a rich, soft type of fabric, and it’s now
used to describe anything extravagant. A plush lifestyle is one only
the wealthy can afford, with expensive restaurants, obedient servants,
and fancy furniture. A plush living room is full of paintings and
decorations. Someone who dresses in a plush way only buys the finest,
most expensive clothing. Plush living is lavish living.

* lore 								   :MoonWalk:
[2016-07-22 Fri 10:06]

Lore is a body of knowledge or tradition that is passed down among
members of a culture, usually orally. It's the lore in "folklore," and
responsible for spreading the word on mythical figures like Santa
Claus, Paul Bunyan, and even Uncle Sam.

Most lore begins as an oral tradition, passed on by word of mouth, and
only later takes on a written form. We tend to think of lore as
something centuries-old, as in the British "Arthurian lore"
surrounding the doings of the mythical King Arthur and his
court. However, newer lore — such as baseball lore — is constantly
springing up. Humans need and love their lore.

The Human Performance Lab occupies a plush office complex on the
outskirts of Tallahassee. The bookshelves that line the walls overflow
with an eclectic catalog of titles that have been relevant to Ericsson’s
research: The Musical Temperament, Surgery of the Foot, How to Be a Star
at Work, Secrets of Modern Chess Strategy, Lore of Running, The
Specialist Chick Sexer.

* stroll							   :MoonWalk:
[2016-07-22 Fri 16:27]

As a noun, a stroll is a leisurely walk. After a heavy meal, you may
want to go out for a stroll to help you work off some of the
calories. You also will take a stroll on your day off and the weather
is nice.

The word stroll originally came to English through the German word
strollen, which means to wander aimlessly. The word stroll can also be
used as a verb meaning to take a leisurely walk in which you do some
wandering. You may enjoy a stroll through the park, along the beach,
or down the city streets — take your time.

* plague							   :MoonWalk:
[2016-07-22 Fri 16:31]

When the homeowner described her ant problem as a plague, the
exterminator thought she was being a bit melodramatic. After all, a
few bugs aren't exactly a huge calamity.

Centuries ago, if you had admitted to a friend that you had the
plague, that friend would have hightailed it in the other
direction. In the Middle Ages, the plague was a horribly contagious
illness that spread like wildfire through Europe, killing millions of
people. Thanks to the introduction of better hygiene and antibiotics,
plague doesn't describe a killer disease as often these days. Instead,
it commonly overstates an annoyance, like an apartment dweller
claiming his building is plagued by cockroaches.

My problem is that I have been persecuted by an integer. For seven years
this number has followed me around, has intruded in my most private data,
and has assaulted me from the pages of our most public journals. This
number assumes a variety of disguises, being sometimes a little larger
and sometimes a little smaller than usual, but never changing so much as
to be unrecognizable. The persistence with which this number plagues me
is far more than a random accident. There is, to quote a famous senator,
a design behind it, some pattern governing its appearances. Either there
really is something unusual about the number or else I am suffering from
delusions of persecution.
* delusions :MoonWalk:
[2016-07-22 Fri 16:34]

A delusion is a belief that has no evidence in fact — a complete
illusion. The cook at the hot dog stand who thinks he is the best chef
in the world? That opinion is definitely a delusion.

The noun delusion is often used in the phrase delusions of grandeur,
which expresses the belief that unattainable goals are well within
reach, like a terrible actress's delusions of grandeur that she won't
just land her first role in a movie, it also will make her an Academy
Award winner. Delusions like that can be amusing for onlookers, but
other kinds of delusions are not, like those suffered by the mentally
ill. Their delusions can remove them from reality, making it hard to
function.

* savvy :MoonWalk:
[2016-07-22 Fri 16:48]

You are known as someone with a lot of business savvy, but only
because you've managed to keep your staggering debts a secret. Which
is actually pretty savvy. Someone who is savvy is shrewd and
perceptive.

Most English words stem directly from other European languages, like
French and Latin.  Not savvy.  It comes from the West Indies, a twist
on the French savez vous? — “Do you know?”  Savvy was first recorded
in its adjective form in 1905. Synonyms for the noun form include
acumen, discernment, grasp, perception, and sharpness.

Our working memories serve a critical role as a filter between our
perception of the world and our long-term memory of it. If every
sensation or thought was immediately filed away in the enormous database
that is our long-term memory, we’d be drowning, like S and Funes, in
irrelevant information. Most of the things that pass through our brain
don’t need to be remembered any longer than the moment or two we spend
perceiving them and, if necessary, reacting to them. In fact, dividing
memory between short-term and long-term stores is such a savvy way of
managing information that most computers are built around the same model.
* stain :MoonWalk:
[2016-07-22 Fri 16:51]

?OB=>

noun
 1. ?OB=> (spot, stain, blot, blur, slick, patch)
 2. :@0A:0 (paint, dye, color, flush, stain, tint)
 3. ?>7>@ (disgrace, shame, dishonor, infamy, ignominy, stain)
 4. :@0AOI55 25I5AB2> (coloring matter, dye, dyestuff, color, stain, coloring)
 5. 15AA;0285 (ignominy, shame, dishonor, infamy, contumely, stain)
 6. F25B=0O ?>;8BC@0 (stain)
 7. F25B=0O ?@>B@020 (stain)

verb
 1. >:@0H820BL (dye, paint, stain, color, imbue, blot)
 2. ?0G:0BL (besmirch, smudge, stain, dirty, soil, discolor)
 3. ?0G:0BLAO (smudge, stain, soil, discolor, discolour, foul)
 4. ?OB=0BL (stain, sully, spot, tarnish, speckle, besmirch)
 5. >:@0H820BLAO (dye, stain, color, colour)
 6. =01820BL (fill, stuff, line, tamp, pack, stain)
 7. 2K?0G:0BL (stain, soil)
 8. ?>@B8BL (spoil, deteriorate, corrupt, ruin, mar, stain)
 9. ?>7>@8BL (disgrace, shame, dishonor, discredit, defame, stain)
10. :@0A8BL (color, paint, dye, stain, do out, colour)

DEFINITION

noun
 1. a colored patch or dirty mark that is difficult to remove.
    "there were mud stains on my shoes"
 2. a penetrative dye or chemical used in coloring a material or object.
    "Now several companies are providing training for stamped concrete, polymer overlays, and chemical stains ."

verb
 1. mark (something) with colored patches or dirty marks that are not easily removed.
    "her clothing was stained with blood"
 2. color (a material or object) by applying a penetrative dye or chemical.
    "wood can always be stained to a darker shade"

* strewn :MoonWalk:
[2016-07-22 Fri 16:52]

When you strew something, you scatter it all over the place. At a
wedding, for example, the flower child's job is to strew the path with
petals.

One of the scariest parts of "The Wizard of Oz" is when the winged
monkeys pounce on the Scarecrow and strew his insides all over the
forest floor. It's a tricky word, because it sounds the same in the
present as it does in the past. The monkeys strew the straw then and
might strew it now: in any case, the straw will be strewn all
over. After the clambake, the beach was strewn with empty shells and
beer bottles. After strewing all that stuff, they forgot to clean up.

My own memory test did not occur in front of the Human Performance Lab’s
floor-to-ceiling projection screen. There were no guns holstered to my
belt, no eye-tracking devices attached to my head. My humble contribution
to human knowledge was extracted in Room 218 of the FSU psychology
department, a small windowless office with a stained carpet and old IQ
tests strewn across the floor. Ungenerously, it might be described as a
storage closet.

* staggering :MoonWalk:
[2016-07-22 Fri 17:15]

A staggering amount is an astonishing, astounding, stupefying
amount. Anything staggering blows your mind.

If you know that stagger means to stumble around uncertainly, then
you're close to the meaning of staggering: this is a word for things
that are so hard to believe you might fall down when you hear them. If
the President gets shot, that's staggering news. If there's a major
earthquake, that's staggering. Alien life contacting the Earth would
be extremely staggering. Anything that knocks your socks off or makes
your mind reel is staggering.

You are known as someone with a lot of business savvy, but only
because you've managed to keep your staggering debts a secret. Which
is actually pretty savvy. Someone who is savvy is shrewd and
perceptive.

* calamity :MoonWalk:
[2016-07-22 Fri 17:22]

Use the word calamity to describe an event that causes great harm and
misery, or a general state of distress or misery: the calamity of war.

Near synonyms are catastrophe and disaster. The noun calamity is from
Middle English calamytey, from Latin calamitas, a word which might be
related to Latin clades "destruction." Calamity Jane was the nickname
of a 19th-century woman living on the U.S. frontier. She claimed to
have some very exciting adventures.

* twitch :MoonWalk:
[2016-07-25 Mon 14:31]

noun
 1. a short, sudden jerking or convulsive movement.
    "his mouth gave a slight twitch"
 2. a stick with a small noose attached to one end. The noose may be twisted around the upper lip or the ear of a horse to subdue it, especially during veterinary procedures.
    "Others have resorted to twitches , blindfolds and tying up a front leg."

verb
 1. give or cause to give a short, sudden jerking or convulsive movement.
    "he saw her lips twitch and her eyelids flutter"
 2. apply a sudden pull or jerk to (a horse).
    "Griffin nodded his assent, and twitched Kiwen's reins to turn him."

* noose :MoonWalk:
[2016-07-25 Mon 18:32]

0@:0=

noun
 1. ?5B;O (loop, hinge, noose, buttonhole, mesh, stitch)
 2. 0@:0= (lasso, noose, lariat)
 3. :07=L G5@57 ?>25H5=85 (noose)
 4. ;0AA> (lasso, lariat, rope, noose)
 5. C7K AC?@C65AB20 (noose)
 6. ;>2CH:0 (trap, snare, hook, pitfall, catch, noose)
 7. A8;>: (snare, trap, gin, noose, springe)

verb
 1. ?>9<0BL 0@:0=>< (noose)
 2. ?>9<0BL 0@:0=>< 8;8 A8;:>< (noose)
 3. 70<0=820BL 2 ;>2CH:C (decoy, noose)
 4. 70<0=8BL 2 ;>2CH:C (entrap, noose)
 5. 25H0BL (hang, weigh, suspend, drape, swing, noose)
 6. ?>25A8BL ?@5ABC?=8:0 (noose)
 7. 702O70BL ?5B;59 (noose)

DEFINITION

noun
 1. a loop with a running knot, tightening as the rope or wire is pulled and typically used to hang people or trap animals.
    "Its gnarled branches twisted and turned into the air, and a hangman's noose hung from one of its thickest and strongest branches."

verb
 1. put a noose on (someone).
    "she was noosed and hooded, then strangled by the executioner"

* rigorous :MoonWalk:
[2016-07-25 Mon 18:43]

If you are rigorous when you do something, you do it extremely
carefully and precisely. A rigorous inspection of your tax records has
revealed the government owes you money. Congratulations!

The Latin root for rigorous is rigor, meaning “stiffness.” This might
remind you or rigor mortis, the stiffening of a body after death, as
often seen on cop shows. This is a good, if creepy, way of remembering
the meaning of rigorous: rigorous people are stiff and unbending about
the standards of their work. This requires being alive, of course.

We made some efforts to write our tests in Chapter 2, Working with doctest,
according to this discipline, although we allowed ourselves some wiggle room
because we were focusing on writing a testable specification. In this
chapter, we're going to be more rigorous.
* niggle :Quora:
[2016-07-26 Tue 18:51]

To niggle means to argue over petty things, like battling over who
gets the front seat or bickering about who's turn it is to take out
the garbage.

To niggle is to squabble over something silly or even to persistently
nag or worry someone to death. Etymologists believe the verb niggle
could be from Scandinavian roots, but there's no point quibbling over
its unclear origin. All you need to know is that niggling is largely
annoying to all involved.

It was honestly a mistake the first time. He loved the peas and I told
him he couldn't have any more until after he finished the rest of his
meal. This obviously made him feel it was a restricted food like
cookies and chocolate which he also couldn't have until after his
meal. Before I knew it he started asking me whether he would get peas
if he ate all his food well. Instead of correcting him we just let it
be and now every time I give him a handful of peas he glows like I
handed him a basket of candy. I feel a slight niggle of guilt but then
I figure it can only be good for him.

* cynical :Quora:
[2016-07-26 Tue 18:59]

If you think public officials are nothing but a bunch of greedy
buffoons, you have a cynical attitude about politics.

A cynical person has a bleak outlook about others, always imagining
that people are ruled by their worst instincts. H.L. Mencken was
famous for saying cynical things like, "Nobody ever went broke
underestimating the intelligence of the American public." The original
Cynics were ancient Greek philosophers who never had a good word to
say about anyone. The Greek word kynikos actually means "canine,"
maybe because all of that sneering seemed a little dog-like.

At $75k, I also became slightly cynical due to the many "$30,000
millionaires" in Dallas who make $30-60k yet drive very nice (leased)
cars and rack up huge credit card bills (which often get paid off by
wealthy parents). It used to bother me that people would assume I was
just one of the same when I wanted people to know I was self-made.
* panache :Quora:
[2016-07-26 Tue 19:07]

To have panache is to have a stylish flair. You might wear your giant
polka-dotted scarf with great panache.

Panache comes from the Latin word pinnaculum, which means “small wing”
or “tuft of feathers.” When you decorate yourself with a flourish,
have an elegant appearance, or do something with style, you are said
to have panache. You might wear your beret with new-found
panache. Your aunt Milly may throw a party with unmatched panache. Or
you brother's ability to turn a phrase may show an uncommon panache.

Reputations, prestige, panache do not get you a free pass or any
breaks. They just buy you some time. If that.
* starlet :Quora:
[2016-07-26 Tue 19:09]

2>AE>4OI0O 725740

noun
 1. 72574>G:0 (star, asterisk, sprocket, starlet, sprocket-wheel)
 2. 1C4CI0O 725740 (starlet)
 3. 2>AE>4OI0O 725740 (starlet, whizz-kid, whiz-kid)
 4. =51>;LH0O 725740 (starlet)
 5. B0;0=B;820O <>;>40O :8=>0:B@8A0 (starlet)

DEFINITION

noun
 1. a young actress with aspirations to become a star.
    "a Hollywood starlet"

* tangled :LPT:
[2016-07-27 Wed 10:21]

Tangled is an adjective that describes a confused mass. You're likely
to hear tangled used most often when referring to hair. If it's
tangled, you can't brush or comb through it.

Other than discussing hair, tangled can be used to refer to anything
that's jumbled up and confused. Like that tangled pile of wires behind
your television and computer that you keep tripping over. Tangled can
also mean something highly complicated or intricate, like the
relationships between ex-wives, ex-husbands and stepchildren in a
family. The word tangled is most famous for being included in a
well-known literary quote from Sir Walter Scott's poem, "Marmion" —
"Oh what a tangled web we weave, when first we practise to deceive."

Answer: There are three units that exist in the preceding code and that
  are as follows: __init__, method1, and method2. __init__ is a method,
  just as method1 and method2. The fact that it's a constructor means
  that it's all tangled up with the other units, but it's still a method
  containing code and a possible location for bugs, and so we cannot
  afford to treat this as anything other than a unit.
* rigamarole :LPT:
[2016-07-27 Wed 10:26]

Rigamarole is a messy, complicated process that takes longer than it
should. The rigamarole involved in getting your driver's license might
make it tempting to just keep riding your bike.

The word rigamarole, which is also spelled rigmarole, is a great way
to describe bureaucratic procedures like paying taxes or registering
for college classes, or lengthy tasks like helping a small child put
on boots, mittens, a coat, and a hat before leaving the house on a
snowy day. You can also use it to mean "a long, rambling story:" "He
went into the rigamarole of how he'd pulled himself up by his boot
straps."

The smaller the units are, the more useful the tests tend to be because
they narrow down the location and nature of bugs more quickly. For
example, if you choose to treat the Testable class as a unit, tests of
the class will fail if there is a mistake in any of the methods. This
tells you that there's a mistake in Testable, but not that it's in
method2, or wherever it actually is. On the other hand, there is a
certain amount of rigamarole involved in treating method4 and its like as
units, to such an extent that the next chapter of the book is dedicated
to dealing with such situations. Even so, I recommend using methods and
functions as units most of the time because it pays off in the long run.
* bogged :LPT:
[2016-07-27 Wed 10:28]

You'd be pretty soggy by morning if you accidentally set your tent up
in a bog. A bog is a swampy kind of ground made up mostly of
decomposing plants and mosses.

Nothing can be built on a bog because the ground is so spongy and
damp, and no crops can be grown there. The dried soil from a bog can,
however, be dried and burned for fuel. A figurative bog is anything
that you tend to get stuck in, like a bog of health problems. Things
can also "bog you down", or slow you down literally or figuratively,
like when your homework bogs you down so you can't enjoy the weekend.

We're going to walk through the development of one class, treating it as
a complete programming project and integrating unit testing at each step
of the process. For something as small as a single standalone class, this
may seem silly, but it illustrates the practices that keep larger
projects from getting bogged down in a tangle of bugs.
* laurels :LPT:
[2016-07-27 Wed 12:09]

;02@K

noun
 1. ;02@K (laurel, laurels, bay)
 2. ?>G5AB8 (honors, honor, laurels, laurel, honour)

DEFINITION

noun
 1. an aromatic evergreen shrub related to the bay tree, several kinds of which form forests in tropical and warm countries.
    "With the doors and windows sealed, the air should be purified by sprinkling perfumes and scents and by burning aromatic woods such as laurel , myrtle, rosemary and cypress."
 2. the foliage of the bay tree woven into a wreath or crown and worn on the head as an emblem of victory or mark of honor in classical times.
    "A year later, the king was crowned with the laurels of victory at Fontenoy."

noun
 1. a city in central Maryland, between Washington, DC, and Baltimore; population 22,329 (est. 2008).

* conceal :LPT:
[2016-07-27 Wed 12:14]

When you conceal something, you are keeping it from being discovered:
“To avoid another argument with his cousins, Jonathan worked hard to
conceal his disappointment at the outcome of the race.”

The verb conceal can be used to describe the hiding of feelings (as in
“to conceal anger”) or facts (as in “to conceal identity”). Conceal
also can be used to describe the act of hiding or covering an item to
prevent discovery. If you eat the last piece of chocolate cake, for
example, you may want to conceal the evidence by removing the
icing-stained plate from your room.

I'd wonder, how did my parents conceal the fact that I had an
identical twin? Then I'd realize, it wasn't really hard. Maybe they
sent out one for adoption directly from the hospital. Next question,
why? No good answers there.
* stray :Quora:
[2016-07-27 Wed 12:43]

Little Red Riding Hood strayed from the path and ended up getting
eaten by the Big Bad Wolf. When you stray, you wander off without
paying attention to where you're going, and sometimes you get in
trouble.

Stray can be used as a verb or as a noun. Your attention may stray
when you're tired and listening to a very boring lecture. You may be
the kind of person who brings home strays, the dogs and cats that have
wandered away from their homes and are lost and hungry. When you're
organizing your sock drawer and you've got one sock without a mate,
you might find the stray sock left behind in the dryer.
* enraged							      :Quora:
  
разъяренный

adjective
 1. разъяренный (furious, enraged, savage, frenzied, blistering)
 2. злющий (furious, very angry, enraged)

DEFINITION

adjective
 1. very angry; furious.
    "an enraged mob screamed abuse"

verb
 1. make very angry.
    "the students were enraged at these new rules"
* inflict

причинить

verb
 1. налагать (impose, inflict, give, administer, clap, put on)
 2. навязывать (impose, force, intrude, enforce, thrust, inflict)
 3. накладывать (superimpose, lay, lay on, inflict)
 4. наносить удар (strike a blow, deal a blow, lunge, strike at, deliver a blow, inflict)
 5. причинять страдание (afflict, inflict, distress, ail)

DEFINITION

verb
 1. cause (something unpleasant or painful) to be suffered by someone or something.
    "they inflicted serious injuries on three other men"
* unjust

несправедливый

adjective
 1. несправедливый (unfair, unjust, inequitable, iniquitous, unrighteous, wrongful)
 2. неправый (unjust)

DEFINITION

adjective
 1. not based on or behaving according to what is morally right and fair.
    "resistance to unjust laws"
* pristine
  нетронутый

adjective
 1. чистый (clean, pure, net, clear, unadulterated, pristine)
 2. древний (ancient, pristine, antique, early, venerable, crusted)
 3. нетронутый (intact, untouched, pristine, virgin, untapped, unaffected)
 4. первоначальный (initial, original, primary, pristine, primordial, primal)
 5. неиспорченный (unspoilt, unspoiled, pristine, incorrupt, sweet, sound)

DEFINITION

adjective
 1. in its original condition; unspoiled.
    "pristine copies of an early magazine"
* commitment
  обязательство

noun
 1. обязательство (obligation, commitment, undertaking, liability, engagement, responsibility)
 2. совершение (commission, commitment, perpetration, committal)
 3. передача (broadcast, transfer, transmission, gear, pass, commitment)
 4. вручение (delivery, presentation, serving, commitment, handle, committal)
 5. заключение под стражу (commitment, committal)
 6. арест (arrest, detention, custody, apprehension, arrestment, commitment)
 7. передача законопроекта в комиссию (commitment, committal)
 8. загруженность (functioning capacity, commitment)

DEFINITION

noun
 1. the state or quality of being dedicated to a cause, activity, etc..
    "the company's commitment to quality"
 2. an engagement or obligation that restricts freedom of action.
    "business commitments"
* daunting							      :Quora:
[2016-07-30 Sat 13:57]

Something daunting can scare you off. If you have a lot of studying to
do, it may seem like a daunting task. Good news is you can get through
it by working hard. Or weasel out of it by playing sick.

Often used in the phrases “daunting prospect” and “daunting task,”
daunting describes something that you are not looking forward to
doing. Having to fill out complicated tax forms every year is a
daunting task for many people. Once a daunting task is complete, you
no longer describe it as daunting, but instead can call it a job well
done, or at least another life experience survived.

Keeping track of multiple repositories may seem like a /daunting/
     prospect, but the fundamentals you learn in this chapter apply
     just the same.
* albeit :Quora:
[2016-07-30 Sat 14:05]

E>BO

conjunction
 1. E>BO (although, though, albeit, if, as, notwithstanding)
 2. B5< =5 <5=55 (nevertheless, however, though, but, notwithstanding, albeit)
 3. 4065 E>BO (albeit)

DEFINITION

conjunction
 1. although.
    "he was making progress, albeit rather slowly"

* contentment :Quora:
[2016-07-30 Sat 14:09]

Contentment is the state of being happy and satisfied. On Thanksgiving
when you think about all you are grateful for, hopefully you feel a
sense of contentment. If not, have another piece of pie and then
you’ll feel contentment.

Contentment isn’t an excited kind of happy, it’s more like a peaceful
ease of mind. It’s being satisfied with what you have, whatever that
is. You might feel a sense of contentment knowing you have a cup of
hot chocolate and a good movie to look forward to tonight. Or you
might experience contentment thinking about the vast estate you just
purchased in the Hamptons. Whatever is going on in your life, you’re
pleased about it.

Let’s switch out happiness for well-being for a second. Well-being is
that feeling of contentment you get when you are immensely satisfied
with where you are right now.

* Facilitate :ProGit:
[2016-07-30 Sat 16:38]

To facilitate means to make something easier. If your best friend is
very shy, you could facilitate her efforts to meet new people.

Facilitate comes from the Latin facilis, for easy. It means to make
something easier or more likely to happen. You facilitate growth or a
process, as opposed to, say, dinner.  Often in business meetings
someone will be assigned to facilitate a discussion so people don't
just sit in awkward silence. Synonyms are ease, simplify, expedite,
and assist.

Facilitate Distributed Development
* swaths :ProGit:
[2016-07-30 Sat 17:32]

A swath was originally the long narrow space created by a single swing
of a scythe in a field of grass or corn as the cutter moved through
it. Nowadays it is used more figuratively to mean any kind of path
someone makes.

The figurative use of swath has nonphysical senses as well, as in the
term "a significant swath of the population believes..." Or if someone
is trying to attract attention to themselves, or is making quite a
public stir, they might be said to be "cutting a swath through the
business world" or "cutting a swath on the dance floor." Hopefully,
neither of the latter involves using scythes.

The Open Source community using Git has also exploded. When I originally sat
down to write the book nearly five years ago (it took me a while to get the
first version out), I had just started working at a very little known company
developing a Git hosting website called GitHub. At the time of publishing
there were maybe a few thousand people using the site and just four of us
working on it. As I write this introduction, GitHub is announcing our 10
millionth hosted project, with nearly 5 million registered developer accounts
and over 230 employees. Love it or hate it, GitHub has heavily changed large
swaths of the Open Source community in a way that was barely conceivable when
I sat down to write the first edition.
* conceivable							     :ProGit:
[2016-07-30 Sat 17:33]

If you see yellowish skies on a humid, spring evening in Kansas, it is
entirely conceivable that a tornado is in the making. That is to say,
it's imaginable or even possible, so make sure you take every
conceivable precaution.

If you conceive of something, you imagine or think of it. So, it makes
sense that the adjective conceivable describes things that can be
imagined or thought of. People often use the word conceivable in
extreme contexts. If you look everywhere for your homework but still
can't find it, you might declare, "I searched in every conceivable
location! My homework must have disappeared." In response, your
teacher might remark that disappearing homework is inconceivable, or
"impossible to imagine."

* scythe							     :ProGit:
[2016-07-30 Sat 17:36]

A scythe is a sharp, curved blade used for mowing or reaping. While
farmers use it to cut plants, the grim reaper uses it to, well, scare
you to death.

In Old English, scythe was spelled siðe. Since there is no longer an ð
in modern English, scythe became the accepted form of the word in the
early 15th century. It drew its sc- start from the Latin scissor,
meaning “carver, cutter.” Farmers use these tools to slice and trim
grass and other plant stalks. Napoleon Bonaparte once noted that
“Occupation is the scythe of time,” meaning that work mows down or
diminishes time.

* pondering :ProGit:
[2016-07-30 Sat 17:40]

>14C<K20;

verb
 1. @07<KH;OBL (reflect, meditate, think, ponder, contemplate, speculate)
 2. >14C<K20BL (think, ponder, consider, think over, mull, contemplate)
 3. 2725H820BL (weigh, balance, ponder, scale, deliberate, heft)

DEFINITION

verb
 1. think about (something) carefully, especially before making a decision or reaching a conclusion.
    "I pondered the question of what clothes to wear for the occasion"

* wreak :Quora:
[2016-07-31 Sun 11:33]

To wreak is to cause something to happen, usually with a terrible
consequence. You can make mischief, cause problems, or inflict pain,
but to wreak damage suggests a deeper level of destruction.

Wreak stems from the Old English wrecan, meaning "to avenge." Its
current meaning, that of causing something to happen — usually with
dire consequences — came about in the 19th century. The word is a
transitive verb, often paired with the equally intense havoc, meaning
"devastation."

And that sort of negative feedback can wreak havoc on your psyche.
* havoc :Quora:
[2016-07-31 Sun 11:33]

Havoc is a noun that means devastation or total mayhem. Havoc often
wreaked by hurricanes, angry mobs, plundering Vikings, and wild
parties that get out of control.

If we trace havoc way back, we arrive at a crossroads. Some people
believe that the word comes from the Old French havot, meaning
“plundering, devastation,” while others argue that it was passed down
to us from the Latin habere, meaning “to have, possess.” Either way
you look at it, the meaning remains the same: widespread disorder or
destruction.

* cruft :Quora:
[2016-08-01 Mon 07:03]

E;0<0

DEFINITION

noun
 1. badly designed, unnecessarily complicated, or unwanted code or software.
    "this removes all unnecessary cruft from Word documents saved as HTML"

* cope 								      :Quora:
[2016-08-01 Mon 07:11]

If you are able to cope with something, you are able to deal with
it. If you can cope with waiting in long lines, you'll get the best
seats. If you can cope with the stress, you will be excellent at
defusing bombs.

From the Old French couper, cope means “come to blows with." Coping
can imply struggle, but it’s usually met with success or at the very
least, not failure. Another word to describe the balancing act of a
mother who takes care of three children while also working part-time
and pursuing a graduate degree is coping. “Understanding does not cure
evil, but it is a definite help, inasmuch as one can cope with a
comprehensible darkness,” warns Swiss psychiatrist Carl Jung.

Me: yes. But I can cope. I am still young. And it is good money and
there is not much to do in Saudi.
* ravine :Quora:
[2016-08-01 Mon 07:12]

In a Western, outlaws will lie in wait at the top of a ravine, or
narrow valley, until they see a traveler entering at the bottom. Then,
the outlaws will come pounding down the ravine's steep sides.

Ravines can be lonely and violent places averse to settlement as
nothing can be built along their steep sides. The word ravine itself
derives from the archaic rapin, which is a violent seizure of
property. During times of heavy rains and snow melt, a ravine may be
filled with violent, rushing water.

I had many close calls but there was one close call I will never
forget last 2011 when I was running downhill, slipped a step, and fell
off a ravine. I was rolling and tumbling for I cannot remember how
many times. I just felt roots and stones hitting my ribs, my legs, my
chest, then, I blacked out.
* bruised :Quora:
[2016-08-01 Mon 07:16]

If you're just learning to skateboard, you’ve probably got an ugly
bruise or two to show for it — those purple and yellow patches you get
on your skin where you’ve bumped and scraped. They probably hurt, too!

You can find bruises at the grocery store, too — those soft, mushy
spots on a peach or an apple — and if you drop a tomato, you're likely
to bruise it.  You can bruise your knee or bruise someone's feelings —
if you tell your friend you don't like her novel, you’ll bruise her
ego.

ETA: The only injuries I had were a bruised thigh, cuts and abrasions
in various parts of my body, and a fat lip.
* miserable :Quora:
[2016-08-03 Wed 08:28]

Miserable goes way beyond sad — it means absolutely wretched. Someone
who's miserable feels absolutely awful.

If you were caught in the pouring rain, missed your own birthday
party, and then got food poisoning, you wouldn't just feel bad. You'd
be miserable — which means exceptionally unhappy. Victor Hugo's novel,
Les Miserables ("The Miserable Ones"), is the story of people who live
a wretched life filled with death and unhappiness. You might want to
bring some tissues if you're heading to the musical!

Well, if you want a miserable life, you can learn Visual Basic, COBOL,
and Java, and work inside some carbonized division of some giant
company forever.
* incentive :Quora:
[2016-08-03 Wed 22:25]

If your mom wants you to mow the lawn but you don't feel like it, she
might offer to treat you to ice cream after as an incentive. An
incentive is something that stimulates you to take action or work
harder.

This noun dates back to Middle English, from Late Latin incentivum,
from incentivus "stimulating." In Latin, incentivus meant "setting the
tune," from incinere "to sing." The related English verb is
incentivize. The less common verb incent was first used in the early
1980s, and has been criticized as business jargon.

They all have a strong incentive to make the learning curve for
existing coders as small as possible.
* nigh :Quora:
[2016-08-05 Fri 09:39]

Nigh is an old-fashioned word that can be used as an adjective or
adverb to mean near or nearly. Something that is nigh impossible —
like knitting a sweater in one night — will be very difficult to
accomplish.

As an adjective, nigh is an older form of the word "near," both of
which are rooted in the Old English word neah. People like to use the
word nigh when they talk about the apocalypse: "Repent! The end is
nigh." It's most common to use nigh today when you're trying to sound
poetic or referencing the archaic or biblical uses of the word.

For he hears the lambs' innocent call,
And he hears the ewes' tender reply;
He is watching while they are in peace,
For they know when their Shepherd is nigh.
* rejoice :Quora:
[2016-08-05 Fri 09:43]

To rejoice is to be incredibly happy, or to express your incredible
happiness. If you just won millions in the lottery, you might rejoice
by screaming at the top of your lungs.

The verb rejoice is like to celebrate but it’s taken to more of an
extreme than just a celebration. You might rejoice after scoring the
winning goal in a championship game, or you might rejoice when you
receive an amazing gift on your birthday. You’ll often hear this word
in the phrase “let us rejoice,” especially in some religious settings.

Little Lamb, who made thee
Dost thou know who made thee,
Gave thee life, and bid thee feed
By the stream and o'er the mead;
Gave thee clothing of delight,
Softest clothing, woolly, bright;
Gave thee such a tender voice,
Making all the vales rejoice?
* bereaved :Quora:
[2016-08-05 Fri 09:44]

Bereaved is an adjective describing people in deep sorrow at the loss
of a loved one. For some, being bereaved helps them leave the sadness
or release themselves from it by experiencing it for awhile.

From the Old English berēafian, meaning "deprive of," bereaved
describes the loss you feel when someone you love dies. You are
suddenly deprived of the person's presence, and missing and mourning
leads to being bereaved. Losing a pet causes similar feelings, and you
can be bereaved when a person goes away but is still alive. Loss and
separation even in life are still reason to be bereaved over the
absence. If someone leaves and you miss them deeply, you may be
bereaved.

White as an angel is the English child,
But I am black, as if bereaved of light.

* slew :Quora:
[2016-08-05 Fri 20:44]

Of all the many nouns referring to a large group of things, one of the
most fun is slew, as in "I saw a whole slew of birds in the tree by
the river."

American English is constantly evolving, its richness coming from the
many languages feeding into it. The noun slew, for instance, is from
the Irish Gaelic sluagh, meaning "multitude." As an unrelated verb,
it's the past tense of slay.

I don't think it's that impressive to be able to use a slew of
languages.
* slew :Quora:
[2016-08-05 Fri 20:44]

Of all the many nouns referring to a large group of things, one of the
most fun is slew, as in "I saw a whole slew of birds in the tree by
the river."

American English is constantly evolving, its richness coming from the
many languages feeding into it. The noun slew, for instance, is from
the Irish Gaelic sluagh, meaning "multitude." As an unrelated verb,
it's the past tense of slay.

I don't think it's that impressive to be able to use a slew of
languages.
* mended :Quora:
[2016-08-06 Sat 16:02]

When you mend something, you fix it or make it better. If you can mend
your broken lamp, then it will shine again. If not you'll have to sit
in the dark.

The word mend was originally used as a religious term, meaning to free
a person from sin, usually through repentance and good deeds. Mend has
come to refer to fixing something that is broken. A mechanic might
mend a broken car, or a seamstress might mend a torn dress. The word
also frequently relates health and healing. Someone recovering from a
long bout of the flu is said to be "on the mend." But as the song
goes, "How can you mend a broken heart?"

- Have you *mended the car*?
* torn 								      :Quora:
[2016-08-06 Sat 16:25]


?>@20==K9

adjective
 1. ?>@20==K9 (torn)
 2. @07>@20==K9 (torn, disrupted, lacerated, in rags, disrupt)
 3. @07>4@0==K9 (torn)
 4. ?@>4@0==K9 (torn)

DEFINITION

verb
 1. pull or rip (something) apart or to pieces with force.
    "I tore up the letter"
 2. move very quickly, typically in a reckless or excited manner.
    "she tore along the footpath on her bike"
 3. be in a state of uncertainty between two conflicting options or parties.
    "he was torn between his duty and his better instincts"
 4. (of the eye) produce tears.
    "the freezing wind made her eyes tear"

* parlance :Quora:
[2016-08-06 Sat 17:43]

The noun parlance means the manner of speaking and using words. Your
15-year-old will tell you that you are definitely not fluent in the
parlance of teenagers, no matter how cool you think you are.

Parlance comes from the French word parler, meaning "to speak." The
noun is often used to refer to the jargon or slang a certain group or
industry uses. If you work in the sciences, you'll be familiar with
the parlance of scientists and be familiar with such jargon as
"goodness of fit" and "iff", which means "if and only if". But if you
are not a scientist, you may stumble when you first come across such
terms.

A cherry-pick,
in Git parlance, is an operation which moves a specific glob of changed code
from one branch of the VCS to another.
* Diverge :Quora:
[2016-08-06 Sat 17:44]

When two roads diverge, they split and go in different directions. If
your opinion diverges from mine, we do not agree. To diverge means to
move apart or be separate.

The poet, Robert Frost, wrote: "Two roads diverged in a wood, and I -/
I took the one less traveled by / And that has made all the
difference." The word diverge in the poem carries both the meaning of
separating and of being apart from the main. As a poet, it was Frost's
job to use words properly. Here he does not diverge from this role.

When Branches Diverge
* Brittle :Quora:
[2016-08-06 Sat 18:32]

Something brittle is easily broken. Do you have brittle bones? Then no
football or rugby for you.

Besides meaning easily fractured and emotionally cold, brittle is also
a type of candy made of cooled sugar. To make peanut brittle, bake the
ingredients on a cookie sheet then let the brittle cool into sheets
which you break into pieces (and then eat — wreaking havoc with your
braces). It's ok to use the adjective brittle freely to describe lots
of things that will break easily — such as a heart, a theory, or a
poorly equipped army.

Red-Green-Refactor – The TDD Cycle 
***** Tests are executable requirements 
***** Arrange-Act-Assert 
***** Documenting our tests 
***** Testing for exceptions 
***** Exploring assert methods 
***** Specific asserts versus generic asserts 
***** Setup and teardown 
***** Brittle tests 
***** Refactoring the design 
***** Refactoring tests 
***** Exploring the Rule classes 
***** Exercise 
***** Summary 
**** 3.