** Fri Apr 15 17:43:15 2016 (Title: What are the growth stages of a programmer?)

Title: What are the growth stages of a programmer?
Date: Wed,  9 Dec 2015 04:24:55 UTC
Feed: Top Answers About Computer Programmers on Quora
Link: https://www.quora.com/Wha[...]mmer/answer/Nate-Waddoups

Nate Waddoups

This first one is shamelessly stolen from a presentation I saw at
Microsoft a few years ago:

1 Complex solutions to simple problems.
2 Complex solutions to complex problems.
3 Simple solutions to complex problems.
4 Complex problems disappear

Or, on another axis:

1 You suck.
2 You seek the advice of your teammates.
3 Your teammates seek advice from you.
4 People on other teams come to you for advice.

(Never forget that despite 3 and 4, item 1 is still true and item 2 is
still a good idea.)
Or, on another axis:

1 Your can write code.
2 You can understand your code.
3 You can fix your code.
4 You can understand other peoples' code.
5 You can fix other peoples' code.
6 You can understand and fix your own code even when you wrote it so
  long ago that it might as well have been written by someone else.

[Edited to add one more section...] 
The following is all from a Wikipedia page about Four stages of
competence. It is actually not about programming specifically, but it
is a way to look at one's competence in any endeavor. I've found it
interesting to look at all sorts of skills in these terms:

    1 Unconscious incompetence - The individual does not understand or
      know how to do something and does not necessarily recognize the
      deficit. They may deny the usefulness of the skill. The
      individual must recognize their own incompetence, and the value
      of the new skill, before moving on to the next stage. The length
      of time an individual spends in this stage depends on the
      strength of the stimulus to learn.
    2 Conscious incompetence - Though the individual does not
      understand or know how to do something, he or she does recognize
      the deficit, as well as the value of a new skill in addressing
      the deficit. The making of mistakes can be integral to the
      learning process at this stage.
    3 Conscious competence - The individual understands or knows how
      to do something. However, demonstrating the skill or knowledge
      requires concentration. It may be broken down into steps, and
      there is heavy conscious involvement in executing the new skill.
    4 Unconscious competence - The individual has had so much practice
      with a skill that it has become "second nature" and can be
      performed easily. As a result, the skill can be performed while
      executing another task. The individual may be able to teach it
      to others, depending upon how and when it was learned.

See Questions On Quora

** reluctant, lameness, tatter, draught, faltering, barling, marline,
   footsore, limp, hesitate, haggard, smear, plight, midst, attend,
   detain, plausibility, noodle, adolescent, pallor, etiolate, arrears,
   stratification, retard, ramification, aperture, shaft, obscene, flaxen,
   masonry, vestige, hastily, cheerless, sombre, mingle, virtue, anemone,
   slumber, apprehension, tumult, drove, expostulation, desolate, garland,
   rubbing, mite, cramp, decadent, sepulture, exuberant, tether, vigil,
   repugnance, hollow, sloth, groove, curb, begotten, stolid, cunning,
   behoves, despair, desertion, misery, anguish, twig, frenzy, dismay,
   mockery, leprous, faint, stirring, lash, lawn, birch, flit, cease, gibbous,
   plausible, languor, hindrance, abundant, connubial, alliance, putrefaction,
   spite, eddy, clumsy, tentative, weed, feeble, precocious, indolent,
   interrogative, loath, merriment, edifice, startle, vain, stagger, preach,
   spawn, contented, impetus, fret, toil, horticulture, wane, rotundity,
   stinging, amidst, precipitous, queer, fatigue, indolent, staple, fracture,
   dilapidated, stalk, fling, turf, merriment, bow, minikin, manikin, vengeance,
   rage, disarm, venison, attune, ravage, sputter, compunction, distort, peculiar,
   manifest, intertwine, apparel, influx, threshold, shabby, dilapidated,
   contentious, subdue, virtue, conscience, qualm, ferocious, prowess,
   sought, impediment, inept, ascribe, glib, lurch, anguish, vernacular,
   overtly, counselor, delusion, unhinge, exasperation, irreconcilable,
   fidget, affront, sincerity, compassion, congruous, dusk, drowsily,
   silhouette, emerald, tremulous, desperate, fern, amble, respite,
   conducive, earnest, seclude, indignant, vigilance, tamer, warble,
   implacable, bargain, thoroughly, convinced, contemplate, pat, prance,
   courtly, apparition, leek, hue, bogus, entirety, idiom, nominal, encompass,
   futile, coupling, content, cram, impale, impel, hinge, supersede, expenditure,
   inert, vomit, cohesive, longing, remnant, abomination, massacre, fogey,
   dilemma, shed, scavenger, destine, stump, thrice, canopy, tatter, coil, fro,
   elude, crippling, bewilderment, blundering, dazzle, fence, writhe, hawthorn,
   scorch, tumulus, hillock, agape, incessant, stir, exultation, succulent,
   thrust, cling, replenish, foliage, bonfire, carbuncle, scarcely, patter,
   throb, folly, atrocious, insidious, irritable, feverish, calamity, embark,
   upbringing, rig, grapple, proponent, avid, fervent, blaze, steatite, elate,
   crowbar, sealed, wilderness, sombre, semblance, brute, slake, disinclination,
   mace, whimper, aisle, abundant, hesitate, apprehension, diminution, startle,
   attain, readjustment, desiccate, deliquesce, transverse, urchin, deaden,
   vestige, dwelling, ram, contrivance, procure, contrive, scorn, rill, feeble,
   pity, dainty, awaken, hazy, forthwith, sweep, unfathomable, splendid, yore,
   acacia, caress, fatigue, preternatural, wither, fastness, villainy, foul,
   wane, dread, malign, stagger, sustaining, thigh, gorge, ravine, persevere,
   anguish, nausea, discordant, odour, frightful, faint, incontinently, abysmal,
   aperture, slender, disconcerted, descent, shirk, tint, afield, pallid,
   saliva, decent, deception, devastating, capsicum, wit, froth, broth, 




* shirk							     :Demo:verb:noun:
[2016-06-26 Sun 17:05]

To shirk your responsibilities is to avoid dealing with them — like
when you watch four consecutive hours of infomercials instead of
facing your homework.

A verb is an action word, so it's ironic that the verb shirk suggests
inaction in the avoidance of work. To shirk carries with it a negative
connotation of laziness. When Eleanor Roosevelt was asked how she
conquered her shyness to become a powerful public figure, she
responded, "I faced each problem as it came along. . . . I never tried
to shirk. I tried never to evade an issue. When I found I had
something to do — I just did it." Ah, Eleanor, why can't we all be a
bit more like you?

footsore, limp, hesitate, haggard, smear, plight, midst, attend,
   detain, plausibility, noodle, adolescent, pallor, etiolate, arrears,
   stratification, retard, ramification, aperture, shaft, obscene, flaxen,
   masonry, vestige, hastily, cheerless, sombre, mingle, virtue, anemone,
   slumber, apprehension, tumult, drove, expostulation, desolate, garland,
   rubbing, mite, cramp, decadent, sepulture, exuberant, tether, vigil,
   repugnance, hollow, sloth, groove, curb, begotten, stolid, cunning,
   behoves, despair, desertion, misery, anguish, twig, frenzy, dismay,
   mockery, leprous, faint, stirring, lash, lawn, birch, flit, cease, gibbous,
   plausible, languor, hindrance, abundant, connubial, alliance, putrefaction,
   spite, eddy, clumsy, tentative, weed, feeble, precocious, indolent,
   interrogative, loath, merriment, edifice, startle, vain, stagger, preach,
   spawn, contented, impetus, fret, toil, horticulture, wane, rotundity,
   stinging, amidst, precipitous, queer, fatigue, indolent, staple, fracture,
   dilapidated, stalk, fling, turf, merriment, bow, minikin, manikin, vengeance,
   rage, disarm, venison, attune, ravage, sputter, compunction, distort, peculiar,
   manifest, intertwine, apparel, influx, threshold, shabby, dilapidated,
   contentious, subdue, virtue, conscience, qualm, ferocious, prowess,
   sought, impediment, inept, ascribe, glib, lurch, anguish, vernacular,
   overtly, counselor, delusion, unhinge, exasperation, irreconcilable,
   fidget, affront, sincerity, compassion, congruous, dusk, drowsily,
   silhouette, emerald, tremulous, desperate, fern, amble, respite,
   conducive, earnest, seclude, indignant, vigilance, tamer, warble,
   implacable, bargain, thoroughly, convinced, contemplate, pat, prance,
   courtly, apparition, leek, hue, bogus, entirety, idiom, nominal, encompass,
   futile, coupling, content, cram, impale, impel, hinge, supersede, expenditure,
   inert, vomit, cohesive, longing, remnant, abomination, massacre, fogey,
   dilemma, shed, scavenger, destine, stump, thrice, canopy, tatter, coil, fro,
   elude, crippling, bewilderment, blundering, dazzle, fence, writhe, hawthorn,
   scorch, tumulus, hillock, agape, incessant, stir, exultation, succulent,
   thrust, cling, replenish, foliage, bonfire, carbuncle, scarcely, patter,
   throb, folly, atrocious, insidious, irritable, feverish, calamity, embark,
   upbringing, rig, grapple, proponent, avid, fervent, blaze, steatite, elate,
   crowbar, sealed, wilderness, sombre, semblance, brute, slake, disinclination,
   mace, whimper, aisle, abundant, hesitate, apprehension, diminution, startle,
   attain, readjustment, desiccate, deliquesce, transverse, urchin, deaden,
   vestige, dwelling, ram, contrivance, procure, contrive, scorn, rill, feeble,
   pity, dainty, awaken, hazy, forthwith, sweep, unfathomable, splendid, yore,
   acacia, caress, fatigue, preternatural, wither, fastness, villainy, foul,
   wane, dread, malign, stagger, sustaining, thigh, gorge, ravine, persevere,
   anguish, nausea, discordant, odour, frightful, faint, incontinently, abysmal,
   aperture, slender, disconcerted, descent, shirk, tint, afield, pallid,
   saliva, decent, deception, devastating, capsicum, wit, froth, broth, 
* consecutive							   :Demo:adj:
[2016-06-26 Sun 17:07]

If things are consecutive, they happen one after the other with no
break. If there are five consecutive snowstorms on five consecutive
days, you'll have to shovel your way out on day six.

Consecutive comes from the Latin consecutus, meaning "following
closely" with no gap. Just like those snowstorms — one storm happened
each day, back to back, for five days in a row. Consecutive numbers
also follow each other, or advance in the right order. For example, 5,
6, 7, 8, 9, 10 are consecutive numbers. You should number the pages on
a term paper to keep them consecutive so the teacher doesn't get
confused.

To shirk your responsibilities is to avoid dealing with them — like
when you watch four consecutive hours of infomercials instead of
facing your homework.

* pallid							   :Demo:adj:
[2016-06-26 Sun 17:47]

Santa looks a little pallid, meaning that he has a pale complexion,
from spending too much time at the North Pole. A few days in Hawaii
might do wonders to add color to his pale, bearded face.

Pallid means pale, or lacking color. It's often used together with
complexion to describe someone who has a pale face, either due to a
lack of sunshine or some kind of emotional distress. A reclusive
author could be pallid from spending too much time indoors. His books
can also be called pallid if they're lacking in color and excitement.

'It may seem odd to you, but it was two days before I could follow up the new-found clue in what was manifestly the proper way. I felt a peculiar shrinking
from those pallid bodies. They were just the half-bleached colour of the worms and things one sees preserved in spirit in a zoological museum. And they were
filthily cold to the touch. Probably my shrinking was largely due to the sympathetic influence of the Eloi, whose disgust of the Morlocks I now began to
appreciate.
* splendid							   :Demo:adj:
[2016-06-26 Sun 17:54]

Looking truly magnificent today? Then someone (probably British) might
stop you to say "Wow! You look splendid, darling!" Thanks the person,
because splendid means glorious, fabulous, wonderful, and/or
splendiferous.

Use the adjective splendid to describe something of the highest
quality. If you're so lucky as to have someone buy you, say, a Harry
Winston diamond, splendid! But splendid doesn't apply only to
expensive items such as jewelry, clothing, or art. You can also have a
splendid idea, morning walk, or encounter with an old friend. For
some, using Splenda in their coffee instead of sugar is, for them,
well, splendid!

'Clearly we stood among the ruins of some latter-day South Kensington! Here, apparently, was the Palaeontological Section, and a very splendid array of
fossils it must have been, though the inevitable process of decay that had been staved off for a time, and had, through the extinction of bacteria and fungi,
lost ninety-nine hundredths of its force, was nevertheless, with extreme sureness if with extreme slowness at work again upon all its treasures. Here and
there I found traces of the little people in the shape of rare fossils broken to pieces or threaded in strings upon reeds. And the cases had in some
instances been bodily removed—by the Morlocks as I judged. The place was very silent. The thick dust deadened our footsteps. Weena, who had been rolling a
sea urchin down the sloping glass of a case, presently came, as I stared about me, and very quietly took my hand and stood beside me.

* stave							     :Demo:noun:verb:
[2016-06-26 Sun 17:57]

A stave is the crosspiece between the legs of a chair or a wooden slat
forming the side of a barrel. In music, it's the five lines you write
notes on.

Stave comes from the word staff, as in a walking stick. You're most
likely to encounter the word stave if you're learning woodworking. If
someone "staves in" a door, they've broken a hole in it. You also
might hear the idiom "stave off," which means to hold off for a short
time.

'Clearly we stood among the ruins of some latter-day South Kensington! Here, apparently, was the Palaeontological Section, and a very splendid array of
fossils it must have been, though the inevitable process of decay that had been staved off for a time, and had, through the extinction of bacteria and fungi,
lost ninety-nine hundredths of its force, was nevertheless, with extreme sureness if with extreme slowness at work again upon all its treasures. Here and
there I found traces of the little people in the shape of rare fossils broken to pieces or threaded in strings upon reeds. And the cases had in some
instances been bodily removed—by the Morlocks as I judged. The place was very silent. The thick dust deadened our footsteps. Weena, who had been rolling a
sea urchin down the sloping glass of a case, presently came, as I stared about me, and very quietly took my hand and stood beside me.
* stall							     :Demo:noun:verb:
[2016-06-26 Sun 19:05]

Stall means to stop or delay. If your car stalls, it comes to a
stop. When you want a horse to stop, you put him in a stall, or small
enclosure inside a barn.

The word stall implies stopping something that will start again — a
horse will leave the stall eventually and start moving, a stalled car
can be restarted. Remember that when you're thinking about stall in
the sense of postpone or delay. You can stall your professor from
giving an exam by talking about last night’s big game. Your little
sister can stall going to bed by asking for one more story. If you
want to delay an approaching army, you might steal their boots —
they'll still come but the "stall tactic" will buy you time.

1) "BTW, there's no toilet paper in that stall...." Not the same kind
of issue in the ladies that it is in the gents. Most of the traffic in
the men's room is headed to a urinal with no need of TP. In the
women's I've both encountered stalls out of TP more often and had
people mention it to other women headed for the deficient stall.

* virtue							  :Demo:noun:
[2016-06-26 Sun 20:55]

Virtue is the quality of being morally good. If you're writing a
screenplay and you want it to be a real tearjerker, make sure your
hero is full of virtue.

The word virtue comes from the Latin root vir, for man. At first
virtue meant manliness or valor, but over time it settled into the
sense of moral excellence. Virtue can also mean excellence in
general. One of your virtues might be your generous willingness to
help out your friends. The phrase by virtue of means "as a result of"
or "by authority of." You will achieve success by virtue of hard work
(or by virtue of inside connections).

Your decisions your life : A great poet once said, "Wisdom is
  knowing what to do and virtue is doing it". Take decisions wisely.

* necessarily							   :Demo:adv:
[2016-07-01 Fri 17:29]

Use the adverb necessarily to mean inevitably. The best man won't
necessarily have to speak at the wedding reception, but he should
probably have a speech ready just in case.

Necessarily also means as a logical result or consequence of some
action. Your English composition grade is necessarily based on the
work you turn in for the class. If you write fairly well, you won't
necessarily get an A, but you just might. Necessarily is made up of
the Latin roots ne, meaning not, and cedere, meaning yield. The
adjective "necessary," from which necessarily comes, originally meant
no backing away.

Science is facts; just as houses are made of stone, so is science made of facts; but a pile of stones is not a house, and a collection of facts is not      
 necessarily science.
* superstition 							  :Demo:noun:
[2016-07-01 Fri 17:31]

A superstition is a belief or practice that isn’t entirely based on
facts or reality, like carrying a rabbit’s foot because you think it
brings you good fortune, or believing that Friday the 13th is a day of
bad luck.

When you pick up a penny, is it because you’re poor or do you think
it’s lucky?  If the quickest route makes you walk under a ladder, will
you do it even though it’s bad luck?  These are two examples of
superstitions, irrational decisions we make for some weird reason.
The Latin roots of the word translate as “standing over,” like how you
freeze standing over a broken mirror. Don’t worry, it’s only a
superstition, right?

Science is the great antidote to the poison of enthusiasm and superstition.
* begets							  :Demo:verb:
[2016-07-01 Fri 17:44]

To beget means to generate something, usually children, and it can be
used to refer to the role of either a mother or a father.

If we analyze the word beget, we get the prefix be-, which tends to
intensify the meaning of the following verb, and get, which means to
cause something to enter one's possession. The word is usually used to
refer to having children, although it can be used to refer to anything
that generates something else — for example, an inspiration can beget
a brilliant idea.

There are in fact two things, science and opinion; the former begets knowledge, the latter ignorance.
* giddy							      :Demo:verb:adj:
[2016-07-01 Fri 17:52]

If you've ever spun in circles until you fell to the ground laughing,
you know how it feels to be giddy. This adjective can mean dizzy,
elated, or — as in the spinning around example –- a lightheaded,
lighthearted combination of the two.

The hackneyed phrase "giddy as a schoolgirl" calls forth the image of
a kid giggling with her friends over some adolescent
foolishness. Giddy has been used to describe someone incapable of
serious thought or easily excited as far back as the sixteenth
century. Given that, in modern usage, giddy describes someone silly
and frivolous, it's interesting to know that the Old English source
for this word has a slightly darker tinge: gidig means "insane" or
"god-possessed."

If anybody says he can think about quantum problems without getting giddy, that only shows he has not understood the first thing about them.
* lacs								  :Demo:noun:
[2016-07-01 Fri 18:00]

Title: I am working in an MNC with a package of 3.4 lacs per annum. Can I earn upto 15 lacs per annum, inspite of being from a non IIT or non NIT college?
* hike							     :Demo:verb:noun:
[2016-07-01 Fri 18:01]

To hike is to walk a long way at a leisurely pace. You might love to
hike in the woods on weekends.

When you hike, you walk for pleasure, often in a wooded or hilly
area. The trip itself is also a hike, whether you hike the Appalachian
Trail or climb a local hill. Another meaning of hike is "to increase,"
as when the library decides to hike the fees for late books. Hike has
been around since the 1800's, when it was spelled hyke, but its origin
is uncertain. The "walk vigorously" meaning is older than the "raise
or increase" meaning.

And it is happening with me. I was getting even lesser than you. I
asked for 30% hike but they said they can't give.
* fervently							   :Demo:adv:
[2016-07-01 Fri 18:05]

If you fervently believe or feel something, then you believe or feel
it strongly — with a lot of passion.

People feel fervently about a lot of things. A sports fan may be
fervently supportive of a football or basketball team and go to every
game. Many religious people fervently believe in a god. If you're
extremely self-confident, you might fervently believe in
yourself. This word means a lot of passion is present. If you feel
blah about something, or you just like it a little, you don't
fervently believe in it.

But there were days I fervently wished for life before him. There were
days we'd broke down about it. There were nights I didn't want to get
up and walk the little guy back to sleep. And only until I accepted
and went through these things, did I find the joy and peace of my
situation. As he gets older, I slowly regain some freedoms I used to
have, and now I can thoroughly appreciate them, unlike before when I
didn't know a life without them.
* contemplation 						       :noun:
[2016-07-01 Fri 18:20]

Contemplation is long, hard thinking about something. If you’re
writing a book on the meaning of the universe, then you’re going to
need to do a great deal of contemplation.

Contemplate has the word temple in its roots, and originally referred
to the kind of thinking you do in a special space set aside for
observation. Now we use it to describe any kind of thinking that we
spend a long time doing. While clicking on someone’s photos on
Facebook doesn’t count as contemplation, usually, you might spend
hours in contemplation of your family and your history if you come
across a box of old photos in the attic.

It is a melancholy of mine own, compounded of many simples, extracted from many objects, and indeed the sundry contemplation of my travels, which, by often rumination, wraps me in a most humorous sadness.
* sundry						      :Demo:adj:noun:
[2016-07-01 Fri 18:21]

A woman emptying out her purse after many years might find an old
stick of gum, a pair of broken sunglasses, a few movie tickets, and
sundry items, meaning that that her purse was filled with a random
collection of unrelated things.

Most people associate the word sundry with the old-fashioned drugstore
in their neighborhood that used to sell all sorts of odds and ends,
from magazines to hairbrushes. The word is typically used as an
adjective to describe a collection of various different items found in
one place, as in — "I discovered records, perfume bottles, and sundry
items at my neighbor's yard sale." The phrase "all and sundry" refers
collectively to a group of people, as in, "I invited all and sundry of
my relatives to my tea party."

It is a melancholy of mine own, compounded of many simples, extracted from many objects, and indeed the sundry contemplation of my travels, which, by often rumination, wraps me in a most humorous sadness.
* rumination							  :Demo:noun:
[2016-07-01 Fri 18:21]

If someone asks you to make a difficult decision — like what to have
for dinner — it might lead to rumination, or a long period of deep
thought.

Use the noun rumination when there's thoughtful consideration going
on. If your grandfather answers every question by saying, "Hmm. Let me
think about that," he is a fan of rumination. It comes from the verb
ruminate, which means "to think deeply," but also means "to chew the
cud." Both words come from the Latin word ruminatus, which has the
same meaning and which is rooted in rumen, or "gullet."

It is a melancholy of mine own, compounded of many simples, extracted from many objects, and indeed the sundry contemplation of my travels, which, by often rumination, wraps me in a most humorous sadness.
* sojourn						     :Demo:noun:verb:
[2016-07-01 Fri 18:23]

A sojourn is a short stay or visit. If you want a fancy way to say
that you took a trip to the countryside, you might talk about your
country sojourn.

The verb is originally from the Latin prefix sub- "under" plus diurnus
"of a day." You might refer to your vacation as a sojourn, but it
might make more sense if you are describing a trip to Provence rather
than a trip to Disney World. Or In figurative use, sojourn means to
delve––your math teacher may stop midway through lessons on fractions
for a brief sojourn into techniques for slicing pie.

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* cunning						      :Demo:adj:noun:
[2016-07-01 Fri 18:35]

In fairy tales, always watch out for the cunning fox or the cunning
witch. Cunning means clever, in the sense of trickery. A cunning plan
might involve setting traps for the innocent and pure at heart to fall
into.

This adjective goes back to the 14th century English verb cunnen,
which meant "to know," and is actually related to our English verb
know. In earlier times, the noun was used to mean a high level of
skill in using the hands. You can be cunning, but you can also use
your cunning to figure out a very clever and tricky plan.

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* considerable							   :Demo:adj:
[2016-07-01 Fri 18:35]

Use the adjective considerable to describe something that is large in
amount. Things you probably spend a considerable amount of time on:
homework and laundry. Things you'd rather spend time on: anything that
isn't homework and laundry!

The adjective considerable can describe something of importance and is
worthy of notice or respect. If you are an excellent singer, dancer,
musician, writer, or similar profession, people may ask you to donate
your considerable talents to charitable causes. If you're not an
excellent singer, dancer, musician, or writer, they will still ask you
to donate, but they are more likely to ask for money!

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* retain							  :Demo:verb:
[2016-07-01 Fri 18:37]

Retain means to hold on to or keep. People who can retain a lot of
information are often mistaken for geniuses, but really they just have
very good memories.

To retain is to keep or maintain, whether in mind, possession or a
certain condition. If you have a great personal assistant, you'll
probably want to retain him for as long as you can. If your body is
retaining water you might look a little plump. The verbs restrain and
detain sound similar, but they mean to keep something by force.

THIS is the story of a five-year sojourn that I and my family made on the Greek island of Corfu. It was originally intended to be a mildly nostalgic account of the natural history of the island, but I made a grave mistake by introducing my family into the book in the first few pages. Having got themselves on paper, they then proceeded to establish themselves and invite various friends to share the chapters. It was only with the greatest difficulty, and by exercising considerable cunning, that I managed to retain a few pages here and there which I could devote exclusively to animals.
* penetratingly							   :Demo:adv:
[2016-07-01 Fri 18:40]
I have attempted to draw an accurate and unexaggerated picture of my family
in the following pages; they appear as I saw them. To explain some of their
more curious ways, however, I feel that I should state that at the time we 
were in Corfu the family were all quite young: Larry, the eldest, was 
twenty-three; Leslie was nineteen; Margo eighteen; while I was the youngest,
being of the tender and impressionable age of ten. We have never been very 
certain of my mother's age, for the simple reason that she can never remember 
her date of birth; all I can say is that she was old enough to have four children. 
My mother also insists that I explain that she is a widow for, as she so 
penetratingly observed, you never know what people might think.
* habitually							   :Demo:adv:
[2016-07-01 Fri 18:45]

Your mind is on autopilot all the time and taking 5-10 minutes a day
to just separate from the neurotic mind is necessary save wasted
energy that goes into fantasizing and daydreaming and being habitually
negative.
* deserve							  :Demo:verb:
[2016-07-01 Fri 18:47]

We deserve things based on our actions. For example, many people
believe murderers deserve the death penalty.

Deserve is used in many ways, but it always carries a sense of balance
or justice. If someone receives an award for their work, it means they
deserve praise and attention. If you deserve a day off, it means
you've been working hard and have earned a vacation. If you threw a
book during class, you deserve a punishment of some kind. Many laws —
and lots of arguments — are about deciding what different people
deserve. It's often hard to tell.

No, instead, I'm going to tell you that in order to feel as good as
you know you want and deserve to feel EVERY DAMN DAY, you need to
exercise so that your body rewards you with happiness, literally. When
your body is happy YOU are happy. When your body is recharged through
exercising, so is your mind, so is your heart, and that energy pours
over into every single part of your life. Don't exercise because the
doctor and your parents tell you its necessary to live a long and
healthy life (obviously its important), but exercise because you want
to operate at maximum capacity on a daily basis, and exercising is
necessary to ensure that.

* savor							     :Demo:verb:noun:
[2016-07-02 Sat 17:11]

Whether it’s a feeling of joy or a piece of pecan pie — when you savor
something, you enjoy it to the fullest.

When you savor something, you enjoy it so much that you want to make
it last forever. With that in mind, savor carries a connotation of
doing something slowly. If you savor that flourless chocolate tart,
then you eat it slowly, bit by bit, deliberately picking every last
crumb off the plate. The word is often applied to eating, but you can
savor any pleasurable experience, whether it’s the winning touchdown
or your moment in the spotlight.

When going to bed do a quick mental check on the things you are
grateful for. I don't mean list them by rote.. I mean "savor" them. "I
am grateful my kids are healthy" "I am grateful I have a fabulous wife
who loves me" "I am grateful my job is close to where I live" "I am
grateful my doctor didn't see anything wrong with me" "I am grateful
for friend X"...
* blasphemy							  :Demo:noun:
[2016-07-02 Sat 17:16]

Saying offensive things about God or religion is blasphemy. Blasphemy
can be used for offensive ideas in other areas too.

If you're saying something bad about a god, or taking the Lord's name
in vain, or questioning a religious institution in any way, you could
be accused of blasphemy — insulting something sacred. You can use this
word in a lot of other ways too. At a meeting of conservatives, a
liberal idea could be considered blasphemy (and vice versa). You might
even jokingly cry "Blasphemy!" if a friend said your favorite ice
cream flavor stinks.

blasphemy
* soliciting						     :Demo:verb:noun:
[2016-07-02 Sat 17:17]

Solicit means to ask for. It is what those people on the street are
doing, when they ask, "Do you have a moment to talk about the
destruction of the planet?" They are soliciting donations for their
cause.

Solicit has an official sounding impressiveness to it––doesn't
soliciting donations sound better than begging for money? It can also
have a more sinister cast. "When the teacher left the room, two girls
solicited their friends to throw all the textbooks out the windows,
injuring members of the cheer squad below — where they were soliciting
signatures for a petition banning smoking in the football locker
rooms."

If you're traveling to the US to do business (that is, making a sales
or professional visit), bear in mind that the attitude between
business associates is not like that found in Mediterranean, Hispanic
or Middle Eastern countries; it is more comparable to that of northern
Europeans. Whereas most Middle Eastern and many Hispanic business
hosts want to “get to know you” first, before doing business (asking
about your family, soliciting personal details, and very possibly
sharing a meal or at least coffee, so they can determine if you have
the kind of character worth doing business with), such personal
questions are considered peculiar, intrusive, and possibly even rude
to Americans. They are also unlikely to want or need to be given a
gift, as is customary in some countries. Like northern Europeans, they
are much more likely to get right down to business, without any
elaborate preliminaries or formalities.
* peculiar						      :Demo:adj:noun:
[2016-07-02 Sat 17:18]

Something peculiar is notably unusual. If your friend starts saying
strange things you don't understand, ask her why she's suddenly become
peculiar.

Peculiar comes from the Latin peculiaris, meaning one's own, or
personal.  In English, it originally meant belonging to one person,
private, like your fondness for your peculiar hairbrush.  It also had
the meaning of something unlike others, special, or
remarkable. Eventually we mostly stopped using it for belongings,
instead using peculiar to mean unusual or odd.

If you're traveling to the US to do business (that is, making a sales
or professional visit), bear in mind that the attitude between
business associates is not like that found in Mediterranean, Hispanic
or Middle Eastern countries; it is more comparable to that of northern
Europeans. Whereas most Middle Eastern and many Hispanic business
hosts want to “get to know you” first, before doing business (asking
about your family, soliciting personal details, and very possibly
sharing a meal or at least coffee, so they can determine if you have
the kind of character worth doing business with), such personal
questions are considered peculiar, intrusive, and possibly even rude
to Americans. They are also unlikely to want or need to be given a
gift, as is customary in some countries. Like northern Europeans, they
are much more likely to get right down to business, without any
elaborate preliminaries or formalities.
* customary							   :Demo:adj:
[2016-07-02 Sat 17:19]

Something customary is done according to practice. When a bride walks
down the aisle, it's customary for everyone at the wedding to rise out
of respect.

Every culture has its own customary traditions.  In American culture
it's customary for a child who loses a tooth to put it under her
pillow and wait for the Tooth Fairy to arrive. In Greece, on the other
hand, it's customary to throw a child's lost tooth onto the roof for
good luck. Customary can also reference habitual things a person does,
like taking your shoes off when you come home, or writing in your
diary before bed.

If you're traveling to the US to do business (that is, making a sales
or professional visit), bear in mind that the attitude between
business associates is not like that found in Mediterranean, Hispanic
or Middle Eastern countries; it is more comparable to that of northern
Europeans. Whereas most Middle Eastern and many Hispanic business
hosts want to “get to know you” first, before doing business (asking
about your family, soliciting personal details, and very possibly
sharing a meal or at least coffee, so they can determine if you have
the kind of character worth doing business with), such personal
questions are considered peculiar, intrusive, and possibly even rude
to Americans. They are also unlikely to want or need to be given a
gift, as is customary in some countries. Like northern Europeans, they
are much more likely to get right down to business, without any
elaborate preliminaries or formalities.
* niceties							  :Demo:noun:
[2016-07-02 Sat 17:21]

тонкости

Clearly, you're interested in the nicety of a word's meaning if you're
checking out this website. A nicety is a fine detail or shade of
meaning that anything — not just a word — can possess.

Even the word nicety has niceties. The emphasis on detail can also
refer to a precision or accuracy of sorts; if someone has judged
something "to a nicety," they've judged it exactly. Yet another common
meaning is in the sense of a minor aspect of polite behavior. Washing
your hands before dinner is a "social nicety." So is covering your
mouth when you cough. Now where would we be without niceties?

Americans do not bow, nor do they normally kiss strangers. A simple
handshake is sufficient upon meeting a business associate; and even
that is unnecessary (and even considered strange) when dealing with
more transient and casual contacts (such as store clerks, hotel
clerks, waiters, cab drivers, etc.). It is sufficient just to say “Hi”
or “Good morning,” and state what you need. Most American service
personnel are used to such informal and abrupt contacts, and are not
offended by a lack of social niceties. HOWEVER – it is NEVER
acceptable to treat such people as your servants! Americans are quite
egalitarian, expect to be treated with a normal level of professional
dignity, and will not put up with ill treatment by a stranger. (And
their employers will usually back up the employee if a customer is
abusive.) If you physically strike a service person who has displeased
you, you may expect to be arrested for assault.
* egalitarian						      :Demo:adj:noun:
[2016-07-02 Sat 17:22]

An egalitarian is a person who believes in the equality of all people,
and an egalitarian society gives everyone equal rights.

This is a word that means something close to equality and has to do
with fairness. If you believe that everyone deserves a chance to vote,
go to school, get good jobs, and participate in society, then you are
an egalitarian. When laws make life fairer, the law is getting more
egalitarian. The opposite of an egalitarian system could be a fascist
society or dictatorship. Monarchies are not egalitarian. When you see
this word, think about equality and freedom.

Americans do not bow, nor do they normally kiss strangers. A simple
handshake is sufficient upon meeting a business associate; and even
that is unnecessary (and even considered strange) when dealing with
more transient and casual contacts (such as store clerks, hotel
clerks, waiters, cab drivers, etc.). It is sufficient just to say “Hi”
or “Good morning,” and state what you need. Most American service
personnel are used to such informal and abrupt contacts, and are not
offended by a lack of social niceties. HOWEVER – it is NEVER
acceptable to treat such people as your servants! Americans are quite
egalitarian, expect to be treated with a normal level of professional
dignity, and will not put up with ill treatment by a stranger. (And
their employers will usually back up the employee if a customer is
abusive.) If you physically strike a service person who has displeased
you, you may expect to be arrested for assault.
* courteously 							   :Demo:adv:
[2016-07-02 Sat 17:23]

учтиво

Women in the workforce are typically treated the same as men:
professionally, courteously and directly. Do not assume that a woman
who meets you for a business or professional appointment is merely a
secretary or assistant; she may be the boss! Treating her dismissively
or disdainfully will probably lose you business. Furthermore, bear in
mind that the US has strict prohibitions in law against sexual
harassment. Making suggestive comments, or unwanted physical contact,
can get you in trouble. The same is true of gay and lesbian people.
* dismissively							   :Demo:adv:
[2016-07-02 Sat 17:24]

To be dismissive is to be indifferent and a little rude. Being
dismissive is a sign of disrespect.

If you're dismissive, you show little consideration for others. If a
teacher laughs at a student's earnest answer to a question, that's
dismissive. An employer throwing a resume in the trash without reading
it? Dismissive. People are dismissive to others they think are beneath
them. You can also be dismissive to ideas and suggestions. It's like
waving someone or something away and saying, "whatever."

Women in the workforce are typically treated the same as men:
professionally, courteously and directly. Do not assume that a woman
who meets you for a business or professional appointment is merely a
secretary or assistant; she may be the boss! Treating her dismissively
or disdainfully will probably lose you business. Furthermore, bear in
mind that the US has strict prohibitions in law against sexual
harassment. Making suggestive comments, or unwanted physical contact,
can get you in trouble. The same is true of gay and lesbian people.
* disdainfully							   :Demo:adv:
[2016-07-02 Sat 17:24]

When you do something disdainfully, you do it with disapproval or
contempt. You might look disdainfully at an airplane passenger who's
yelling at his young son.

When you act disdainfully toward someone, you're expressing your lack
of respect — either for the person himself, or what he's doing. If
your grandmother disapproves of just about everyone she meets, she'll
probably glance disdainfully at your friends when they show up in
their loud car to pick you up. The Old French root of disdainfully is
desdeignier, "scorn, refuse, or repudiate," from des, "do the opposite
of," and deignier, "treat with respect."

Women in the workforce are typically treated the same as men:
professionally, courteously and directly. Do not assume that a woman
who meets you for a business or professional appointment is merely a
secretary or assistant; she may be the boss! Treating her dismissively
or disdainfully will probably lose you business. Furthermore, bear in
mind that the US has strict prohibitions in law against sexual
harassment. Making suggestive comments, or unwanted physical contact,
can get you in trouble. The same is true of gay and lesbian people.
* hardship							  :Demo:noun:
[2016-07-05 Tue 17:01]

If something is a hardship, it causes suffering or
unpleasantness. After all the hardship you endured while training for
the marathon, you really hope that you’ll do well — or at least
finish!

The word hard in hardship is a tip-off to its meaning: something
that’s a hardship is hard. It could be hard work that you do for a
larger goal — like training for the marathon — or it could be a
situation that’s hard to endure. If you lose your job, you could end
up experiencing financial hardship. Sometimes a hardship is something
that just happens, like the hardship people suffer following a
disaster.

* liability							  :Demo:noun:
[2016-07-06 Wed 12:24]

A liability is a debt or obligation or a personal flaw that stands in
your way. A company's liabilities are simply the debts on its ledger,
but a personal liability might be your extreme shyness in social
situations.

Depending on how you use it, the word liability has very different
meanings. In a business or financial sense, a liability is a debt or
fiscal obligation, like a mortgage or a loan. A limited liability
company means if the company fails, the partners are on the hook for
only what they initially invested in the company. A personal
liability, however, is some element of your past, your character, or
your behavior that might give you a disadvantage.

* crutch							  :Demo:noun:
[2016-07-07 Thu 20:24]

A crutch is something you lean on when you’re hurt or weak. It can be
a physical crutch you use because you broke your leg, or a friend you
depend on a bit too much when you’re having a tough time.

A medical crutch is a device that helps you walk when you’re
injured. A psychological crutch helps you when you need it, or think
you do. Medical crutches come in pairs and have soft pads that fit
under your arms and handles to help you rest your body weight on
them. Other types of crutches fit securely around the lower part of
your arm. The Old English root word is crycce, "staff," and the
figurative meaning dates from about 1600.

crutch
* cramped						      :Demo:adj:verb:
[2016-07-07 Thu 20:28]

ограниченный

adjective
 1. ограниченный (limited, bounded, restricted, confined, finite, cramped)
 2. стесненный (cramped, constrained, uneasy, straitened, embarrassed, pinched)
 3. неразборчивый (illegible, indiscriminate, promiscuous, unintelligible, unreadable, cramped)
 4. стиснутый (cramped)
 5. чрезмерно сжатый (cramped)
 6. страдающий от судорог (cramped)
 7. сведенный судорогой (cramped)

DEFINITION

adjective
 1. feeling or causing someone to feel uncomfortably confined or hemmed in by lack of space.
    "the staff had to work in cramped conditions"
 2. suffering from a cramp.
    "cramped muscles"

verb
 1. restrict or inhibit the development of.
    "tighter rules will cramp economic growth"
 2. fasten with a cramp or cramps.
    "cramp the gates to the posts"
 3. suffer from sudden and painful contractions of a muscle or muscles.
    "Her hand had such low muscle tone that it cramped painfully as she tried to control the pencil when she wrote."

* whimsical							   :Demo:adj:
[2016-07-08 Fri 14:19]

Whimsical means full of or characterized by whims, which are odd ideas
that usually occur to you very suddenly. If you decide at the last
minute to fly to Europe, you could say you went there on a whim.

Whimsical can also mean tending toward odd or unpredictable
behavior. Both whimsical and whim are derived from an earlier English
word whim-wham, which is of unknown origin. Whim-wham had about the
same meaning as whim, but could also refer to an odd object or piece
of clothing.

This book by Randall Munroe (which is actually a compilation of posts
from his wickedly popular blog xkcd) is equally whimsical and
informative. He explores questions like “from what height would you need
to drop a steak for it to be cooked when it hit the ground?” and “what
would happen if you made a periodic table out of cube-shaped bricks,
where each brick was made of the corresponding element?” and he provides
explanations that are well-researched, sourced and scientifically valid,
while still using a giraffe as a measurement for height. You’ll be
entertained, and Mr. Gates says, “you’ll also learn about a lot of other
things like ballistics, DNA, the oceans, the atmosphere and lightning.”
* plea								  :Demo:noun:
[2016-07-08 Fri 14:30]

A plea is what you make when you're begging for something with a sense
of urgency and emotion. While you wouldn't call asking for a hall pass
a plea, you could make a plea for justice or world peace.

Plea also has a legal meaning. When you get a traffic ticket or if
you're accused of a crime, you have to enter a plea of "guilty" or
"not guilty." A "plea bargain" is when you make a deal with the
prosecutor — you may plead guilty to a charge (by entering a guilty
plea) that has less of a penalty and, in return, the prosecutor drops
the more serious charge.

In this Richard Dawkins book, he poses a question at the beginning of
each chapter, offers colorful myths from different places around the
world and finally reveals an elegant scientific answer. “It’s an
engaging, well-illustrated science textbook offering compelling answers
to big questions, from how the universe formed to what causes
earthquakes,” Mr. Gates writes in his review. “It’s also a plea for
readers of all ages to approach mysteries with rigor and curiosity,
rather than buying into the supernatural myths at the core of most faith
traditions.”

* amend								  :Demo:verb:
[2016-07-08 Fri 20:09]

When you amend something, you correct or improve it. If you confused
your audience when you gave your speech, don't be afraid to amend what
you said.

Amend can also describe adding amendments to an official document,
such as a constitution or law. If politicians in your state want to
address the growing number of home foreclosures, they might amend the
state constitution to include restrictions intended to reduce
foreclosures. Amend comes from the Latin word emendare, meaning "to
correct, free from fault."

amend
* deceive							  :Demo:verb:
[2016-07-08 Fri 20:10]

To deceive means to trick or lie. A crafty kid might deceive his
mother into thinking he has a fever by holding the thermometer to a
light bulb to increase the temperature.

Deceive is the trickier cousin of lie. You might lie about why you
were late to school. But if you simply don't explain to your mom that
you were late in the first place, you are deceiving her. Deceive
carries with it a feeling of both craftiness and betrayal. When you
deceive someone, forgiveness can be hard to come by. Have you heard of
the spelling rule, "i before e except after c" that has so many
exceptions? Well, deceive follows that rule.

deceive
* profanity							  :Demo:noun:
[2016-07-08 Fri 20:25]

Profanity is a type of language that includes dirty words and
ideas. Swear words, obscene gestures, and naughty jokes are all
considered profanity.

You know those four-letter words you're not supposed to say? They're
profanity: language that's vulgar and obscene. R-rated movies and
cable stations like HBO have a lot of profanity, but you won't hear it
on a station like NBC or ABC. Profanity tends to be about off-color
subjects, like sex and going to the bathroom. Everyone probably spews
some profanity at some point, but you better be careful about who's
listening.

profanity
* outburst							  :Demo:noun:
[2016-07-08 Fri 20:26]

When you can't help an angry shout or a burst of emotion, that's an
outburst. A toddler's outburst might take the form of a full-blown
temper tantrum.

An outburst of passion or emotion can be angry words, a broken glass,
or a triumphant whoop. There are also figurative outbursts, like the
outburst of political enthusiasm within a particular group of voters,
or an outburst of energy in the midst of a modern dance
performance. The Middle English verb that proceeded outburst was
outbresten.

"an outburst of profanity"

* obscene							   :Demo:adj:
[2016-07-08 Fri 20:28]

Obscene describes something that is morally offensive in a sexual
way. It's never a good idea to use obscene language at school.

Certain films, books, magazines, and other forms of entertainment are
considered obscene because they portray sex in a very frank way that
some people find vulgar and lewd. Obscene material, language, and
jokes are considered taboo in polite society. Obscene can also be used
to describe something repulsive — like when your friend ate an obscene
number of snails at the Bastille Day bash.

obscene
* decency							  :Demo:noun:
[2016-07-08 Fri 20:29]

The personal quality of decency is one of honesty, good manners, and
respect for other people.

Over time, decency has referred to manners, but today decency is
mainly a strong sense of right and wrong, and a high standard of
honesty. When a criminal or dictator does horrible things, people
assume they have no sense of decency. When a tasteless or violent TV
show becomes popular, some people wonder if society has lost its sense
of decency. Asking "Have you no decency?" is a serious question,
unless you're being silly and complaining about something like
homework.

decency
* unjust							   :Demo:adj:
[2016-07-08 Fri 20:29]

Something or someone that is unjust is just not fair. An unjust boss
might fire you the very first time you're late for work.

You might think of the word justice in order to remember the meaning
of the word just, which means "fairness or righteousness." An unjust
judge does not play by the rules; he might send a person to jail even
though there isn't enough evidence that a crime was committed. Unjust
behavior is improper or dishonest: "The professor acted in an unjust
manner when he gave everyone an F just because there was a rumor that
his students didn’t like him."

unjust
* infuriating						      :Demo:adj:verb:
[2016-07-08 Fri 20:30]

Use the adjective infuriating to describe something that makes you
really, really angry. It's infuriating to see a little kid being
bullied.

When something makes you furious it's infuriating. You can use the
word to talk about things that are truly offensive or outrageous —
someone snatching your grandmother's purse, for example — or things
that are merely aggravating or annoying. You might find it infuriating
trying to parallel park on a busy street or waiting in line at the
post office. The roots of infuriating can be traced all the way back
to the Latin furere, which means "to rage" or "to be mad."

infuriating
* hapless							   :Demo:adj:
[2016-07-08 Fri 20:31]

Use the adjective hapless to describe someone unlucky and deserving of
pity, like the hapless used car buyer who gives in to the fast-talking
salesperson.

The word hapless traces all the way back to the Old Norse word happ,
meaning “chance, good luck.” Combine this with the suffix -less
(“lacking”) and hapless means “unlucky” or “ill-fated.”  A traveler
who goes to Moscow and briefly gets lost on the subway? Just a
tourist. A traveler who goes to Moscow, accidentally eats food he is
allergic to, somehow loses all his money, and by chance gets on a
train destined for Mongolia? Definitely hapless.

hapless
* inflict							  :Demo:verb:
[2016-07-08 Fri 20:32]

When you force an undesirable or harmful event on someone, you inflict
it on them. You might prefer that someone inflict some physical pain
on you rather than inflict you with the boredom of another trip to the
annual flower show.

The verb inflict comes from the Latin word inflictus, meaning “to
strike or dash against.” If you cause anything bad to happen to a
person, animal, or even an object, you inflict that badness on
them. For example, someone can inflict injuries or suffering on other
people or inflict damage on property. We can inflict pollution or
over-development on our environment. It's always a negative thing —
you wouldn't say you inflict happiness or love on others.

inflict
* muggy								   :Demo:adj:
[2016-07-08 Fri 20:33]

Think of hot, humid, steamy weather as being so unpleasant that you
feel "mugged" by it when you step outside. That's one way to remember
the meaning of muggy.

"It's not the heat! It's the humidity!" That's what your grandma says
when she wants to complain about muggy weather. Muggy means a
combination of humidity and heat that makes you sweaty and
uncomfortable and long for air-conditioning. You might be cursing the
cold and the snow today, but mark my words, come August and the muggy
dog days of summer, you'll be nostalgic for the cold.

muggy

* generosity							  :Demo:noun:
[2016-07-10 Sun 11:46]

Generosity is a quality that's a lot like unselfishness. Someone
showing generosity is happy to give time, money, food, or kindness to
people in need.

Generosity is a quality — like honesty and patience — that we all
probably wish we had more of. When you show generosity, you might give
away things or money or put others before yourself.  But generosity is
about more than cash and stuff. When you're forgiving and gentle to
people, you show generosity of spirit. If you give others help or
credit, that shows generosity. The world would certainly be a better
place if more people showed generosity to others.

My grateful thanks, then, to:
    Dr Theodore Stephanides. With typical generosity, he allowed me to make use of material from his unpublished work on Corfu, and supplied me with a number of dreadful puns, some of which I have used.
* puns							     :Demo:noun:verb:
[2016-07-10 Sun 11:47]

A pun is a play on words. If a bird flying overhead takes a poop on
the cake you’re carrying, you could say “Isn’t that just the icing on
the cake!” But only if you want to be punny.

Friend of the double entendre and other witticisms, a pun is a comedic
phrase that plays off of the sounds and double meanings of words. Puns
can be quite clever, but often come off as silly, cheeseball attempts
at humor. That's probably why any good comedian will tell you that "a
pun is a short quip followed by a long groan."

My grateful thanks, then, to:
    Dr Theodore Stephanides. With typical generosity, he allowed me to make use of material from his unpublished work on Corfu, and supplied me with a number of dreadful puns, some of which I have used.
* dreadful							   :Demo:adj:
[2016-07-10 Sun 11:47]

Something that's terribly bad is dreadful. Some people love going to
the opera, but for others there's no more dreadful way to spend three
hours.

Dreadful means "full of dread," "feeling a sense of dread," or
"causing dread." Dread means fear or anxiety. The adjective dreadful
can describe something truly devastating, like the dreadful aftermath
of a tornado, or something that's awful on a more personal level, like
a dreadful blind date. If it's bad, fearsome, or unpleasant, you can
call it dreadful.

My grateful thanks, then, to:
    Dr Theodore Stephanides. With typical generosity, he allowed me to make use of material from his unpublished work on Corfu, and supplied me with a number of dreadful puns, some of which I have used.
* unconsciously							   :Demo:adv:
[2016-07-10 Sun 11:51]
бессознательно

adverb
 1. бессознательно (unconsciously)

My family. They, after all, unconsciously provided a lot of the material, and helped me considerably during the writing of the book by arguing ferociously and rarely agreeing about any incident on which I consulted them.

* ruthless							 :Family:adj:
[2016-07-10 Sun 11:57]

Ruthless means showing no mercy or compassion. If you really want to
cut down on the clutter in your apartment, you can't be sentimental
about keepsakes. You have to be ruthless and throw out everything
that's not absolutely essential.

If you're ruthless, you're the polar opposite of Mother Theresa. You
get called heartless and cold-blooded. That's one of the reasons the
word crops up so often to describe dictators and tyrants, though it
can also apply to other personality types — like corporate raiders and
colleagues so success-driven that they'll gladly steamroll anyone to
get ahead. It finds its way into milder contexts, too: Just be
ruthless and rip off the Band-Aid already!

Sophie, my secretary, who was responsible for the introduction of commas and the ruthless eradication of the split infinitive.
* eradication							:Family:noun:
[2016-07-10 Sun 11:57]

When people talk about the eradication of something, they are
referring to its total destruction. Imagine a movie villain destroying
a planet with a massive laser beam and you'll have the right idea.

If a gardener's goal is the eradication of every single weed in his
back yard, he might start by uprooting dandelions. Fittingly, the root
of eradication is the Latin word for "uproot," ērādīcāre. The
eradication of anything, whether it's disease, poverty, war, or weeds,
involves removing every last trace of it, right down to the roots.

Sophie, my secretary, who was responsible for the introduction of commas and the ruthless eradication of the split infinitive.
* intact							 :Family:adj:
[2016-07-10 Sun 12:24]

If something is intact it's still in one piece. If you'd like your
sand castle to remain intact, I suggest you build it away from the
water.

The Latin word intactus means “untouched,” but today something is
intact if it's whole, if it hasn't fallen apart. After a long day at
work, you might feel lucky to be intact. Your letter to the post
office states that you would prefer your packages to arrive intact
from now on.

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* crate 						   :Family:noun:verb:
[2016-07-10 Sun 12:37]

A crate is a wooden container that's made for transporting or shipping
goods. Your uncle might send you a crate of Florida oranges for a
Christmas gift.

Boxes made of wood that are filled with goods and loaded on trucks,
ships, or planes are called crates, and to fill them is also to
crate. Groceries are often shipped or delivered in crates, like crates
of eggs, milk crates, or a crate of bananas. The amount of some item
that fits in one crate is also called a crate — "The market ordered
seven crates of ice cream for the Fourth of July weekend."

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* quailed							:Family:verb:
[2016-07-10 Sun 12:38]

Smaller than the chicken and not as well known as the pigeon, quail is
like the often-overlooked middle child of the ground-dwelling bird
family. Quail can also mean to cringe in fear or pain. So if you are a
quail, you might quail at the thought of quail-hunting season.

Quail is a broad, catchall word; it can refer to any one of many small
domestic game birds.  So if you’re bragging about the quail you shot
on a hunting trip to your uptight, bird-obsessed pals, they might
demand to know if it was the Bobwhite quail, the Valley quail or the
Scaled quail, to name just a few. If you use this word as a verb, it
means to draw back in fear or pain. You might quail in fear at the
sight of a playground bully. A good way to remember this verb meaning
is to think of how the word chicken is also associated with fear.

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* contingency							:Family:noun:
[2016-07-10 Sun 12:40]

If you plan to walk home if the weather is nice, but bring subway fare
just in case, then taking the subway is your contingency plan. A
contingency is an event you can't be sure will happen or not.

The noun contingency describes something that might or might not
happen. We use it to describe an event or situation that is a possible
outcome but one that's impossible to predict with certainty. A company
might have a contingency plan for what to do if something goes wrong
with their primary strategy, also known as "plan B." They might even
have plans C, D, and E, to prepare for multiple contingencies.

I should like to pay a special tribute to my mother, to whom this book is dedicated. Like a gentle, enthusiastic, and understanding Noah, she has steered her vessel full of strange progeny through the stormy seas of life with great skill, always faced with the possibility of mutiny, always surrounded by the dangerous shoals of overdraft and extravagance, never being sure that her navigation would be approved by the crew, but certain that she would be blamed for anything that went wrong. That she survived the voyage is a miracle, but survive it she did, and, moreover, with her reason more or less intact. As my brother Larry rightly points out, we can be proud of the way we have brought her up; she is a credit to us. That she has reached that happy Nirvana where nothing shocks or startles is exemplified by the fact that one week-end recently, when all alone in the house, she was treated to the sudden arrival of a series of crates containing two pelicans, a scarlet ibis, a vulture, and eight monkeys. A lesser mortal might have quailed at such a contingency, but not Mother. On Monday morning I found her in the garage being pursued round and round by an irate pelican which she was trying to feed with sardines from a tin.
* flamboyant							 :Family:adj:
[2016-07-10 Sun 12:46]

Flamboyant means elaborate and ostentatious. When you think of
flamboyant, think of Las Vegas showgirls: feathers, sequins,
three-inch heels, enough make-up to disguise any irregularity.

Flamboyant means showy, and though we often roll our eyes at it, it's
not a hateful thing. Liberace was flamboyant. So was Elvis. The word
comes from the French flamboyer, to flame. Think of passion and
pageantry all rolled into one, and you'll have a good idea what
flamboyant should mean at its best. If that doesn't do it for you,
think of a man playing a shiny white grand piano at a rock concert,
wearing a white satin jump suit and 8-foot wide, fully-feathered
wings. See? Flamboyant.

Lastly, I would like to make a point of stressing that all the anecdotes about the island and the islanders are absolutely true. Living in Corfu was rather like living in one of the more flamboyant and slapstick comic operas. The whole atmosphere and charm of the place was, I think, summed up neatly on an Admiralty map we had, which showed the island and the adjacent coastline in great detail. At the bottom was a little inset which read:
    CAUTION: AS the buoys marking the shoals are often out of position, mariners are cautioned to be on their guard when navigating these shores.
* slapstick							:Family:noun:
[2016-07-10 Sun 12:48]
хлопушка

noun
 1. фарс (farce, slapstick)
 2. хлопушка (slapstick, flapper, petard, flap)
 3. дешевый фарс (slapstick comedy, slapstick)
 4. грубый фарс (slapstick comedy, knockabout, slapstick)

DEFINITION

noun
 1. comedy based on deliberately clumsy actions and humorously embarrassing events.
    "slapstick humor"

* adjacent							 :Family:adj:
[2016-07-10 Sun 12:49]

Adjacent means close to or near something. You may consider the people
up and down your street to be neighbors, but your next-door neighbor
is the person who lives in the house or apartment adjacent to yours.

Adjacent can refer to two things that touch each other or have the
same wall or border. And the adjective is often followed by the
preposition to: Her office is adjacent to mine. This word is from
Latin adjacere "to lie near," from the prefix ad- "to" plus jacere "to
lie, throw."

Lastly, I would like to make a point of stressing that all the anecdotes about the island and the islanders are absolutely true. Living in Corfu was rather like living in one of the more flamboyant and slapstick comic operas. The whole atmosphere and charm of the place was, I think, summed up neatly on an Admiralty map we had, which showed the island and the adjacent coastline in great detail. At the bottom was a little inset which read:
    CAUTION: AS the buoys marking the shoals are often out of position, mariners are cautioned to be on their guard when navigating these shores.
* inset							   :Family:noun:verb:
[2016-07-10 Sun 12:50]
вставка

noun
 1. вкладка (inset)
 2. вклейка (insert, inset, plate)
 3. вставка в платье (inset)

verb
 1. вставлять (insert, inset, interpose, paste, embed, plug)
 2. вкладывать (invest, put up, insert, inlay, enclose, inset)

DEFINITION

noun
 1. a thing that is put in or inserted.
    "a pair of doors with their original stained-glass insets"

verb
 1. put in (something, especially a small picture or map) as an inset.
    "type in the text to be inset"

Lastly, I would like to make a point of stressing that all the anecdotes about the island and the islanders are absolutely true. Living in Corfu was rather like living in one of the more flamboyant and slapstick comic operas. The whole atmosphere and charm of the place was, I think, summed up neatly on an Admiralty map we had, which showed the island and the adjacent coastline in great detail. At the bottom was a little inset which read:
    CAUTION: AS the buoys marking the shoals are often out of position, mariners are cautioned to be on their guard when navigating these shores.

* rusty								   :Demo:adj:
[2016-07-11 Mon 06:04]

If your German is rusty, it's like the bike you left out in the rain
too many times that turned brown and flakey on the metal parts. Like
your bike, your German skills became rusty, meaning they're suffering
from neglect.

You can also describe yourself as rusty: you used to do flips on your
skateboard, but you haven't practiced in a while and now you're a
little rusty. Rusty can also refer to the color of rust, which is a
reddish-brown — a rusty-colored dog, for instance. Anything made of
iron or steel that you leave outside in the elements is likely to
oxidize and become rusty, covered with rust.

The skills are rusty, but the knowledge is still there. I'm ready for
the zombie apocalypse.

* reinforce :Demo:
[2016-07-15 Fri 18:31]

To reinforce means to make stronger. You can reinforce your roof by
putting some extra supports under it.

Besides a physical structure, there are many things you can
reinforce. If you want to reinforce a message, you can say it louder,
rephrase and repeat it or give examples of what you expect. You use
dog biscuits to reinforce certain behaviors in your dog. Bad
experiences will reinforce your fears, good ones your hopes. And when
military leaders reinforce their troops, they send additional soldiers
to the front.

Anything you reinforce. So.
* voraciously :Demo:
[2016-07-15 Fri 18:33]
 =5=0AKB=>

adverb
 1. =5=0AKB=> (insatiably, voraciously)

* glowing :Quora:
[2016-07-15 Fri 18:39]

If something is glowing, it's either lit up like a light or it's full
of praise and enthusiasm. So, you could receive a glowing candle or a
glowing report card. You choose.

When a report or account is glowing, it's unreservedly positive, like
a book critic's glowing review of a new mystery novel or your
grandmother's glowing praise for the good job you did mowing her
lawn. Glowing comes from glow, which can mean "a flush of radiant
feeling," and which comes from the Old English glowan, "to glow or
shine as if red-hot."

Any major work experience (a Job) is considered an Excellent
extracurricular activity, as long as you get a glowing letter of
recommendation from a non-relative manager/supervisor.

* praise :Quora:
[2016-07-15 Fri 18:42]

Praise means "admiration or approval," and when you're on the
receiving end of it, you feel great.

Whether it's used as a verb or a noun, praise means "approval." If you
enthusiastically praise your dog, he's likely to wag his tail and
expect a treat. What you've given him (in addition to the treat) is
praise, the noun. In a religious context, the verb praise is
interchangeable with worship, as when a minister says, "Praise God."

verb
 1. хвалить (praise, commend, compliment, laud, talk up, glorify)
 2. восхвалять (praise, eulogize, magnify, exalt, sing the praises of, glamorize)
 3. превозносить (exalt, praise, extol, glorify, laud, eulogize)
* toughy :Quora:
[2016-07-15 Fri 18:45]

nil

noun
 1. крепкий орешек (toughie, toughy)
 2. трудная проблема (toughy, toughie)
 3. непокладистый человек (tough customer, toughie, toughy)
 4. тяжелый человек (difficult person, toughy, terror, toughie)
 5. хулиган (bully, hooligan, hoodlum, ruffian, tough, toughie)

* refinement 								:LPT:
[2016-07-16 Sat 08:49]

Do you know which fork is for your salad and which one is for dessert?
Then you have some refinement — good manners and taste.

Things that go through a process of refinement have been refined;
they've lost their rough edges. For people, this means they have good
manners, and for substances like oil and sugar, it means that their
impurities have been removed. With refinement, things and people
become more acceptable: the sugar's refinement makes it appropriate to
serve at a fancy party, and your refinement makes you a perfect guest
there.

This gives you a pretty basic understanding of what we'll be talking
about in this book. There are many refinements and tools to make the
process quicker and easier, but the basic idea is to tell the computer
what you expect, using simple and easily-written chunks of code, and then
tell the computer to double-check your expectations throughout the coding
process. Because expectations are easy to describe, you can write them
down first, allowing the computer to shoulder much of the burden of
debugging your code. Because expectations are easy to describe, you can
write them down fast, allowing you to move on to interesting things while
the computer keeps track of the rest.

* lured :LPT:
[2016-07-16 Sat 08:57]

To lure is to entice or bait someone.  A lure is used to bait or
entice fish to attach themselves to your hook.  "He had a new shiny
lure, which was enough to lure me into going on the fishing trip."

The verb lure is related to words that mean “bait,” “deceit,” and
“invite.”  Often, when lure is used, there is a nefarious implication,
as in: “He was able to lure her into the alley, but her friends soon
came looking for her.”  The noun lure is the thing that draws in the
person or animal, which can be either a physical object or a concept.
"The lure of his great wealth kept her in the relationship despite his
infidelity."

For this reason, newcomers to automated testing are sometimes lured into
ignoring the distinction between unit testing and integration testing.
* encompass :LPT:
[2016-07-16 Sat 08:58]

Encompass means to contain. When you see the word, picture a campus
which encompasses lecture halls, a football field, a medical center, a
dining hall and some parking lots.

Encompass can be used when talking about anything that contains
something else. A lecture on Edward Hopper might encompass all aspects
of his life and art, a work of art could encompass many techniques,
and a policeman's jurisdiction may encompass an entire state. The
continental U.S. encompasses 48 states. This entry encompasses many
examples of the word encompass in use!

In integration testing, the boundaries of isolation are pushed further
back, so that the tests encompass the interactions between related units.
* shoulder :LPT:
[2016-07-16 Sat 09:09]

noun
 1. the upper joint of the human arm and the part of the body between this and the neck.
    "Occasionally it starts in one region such as the neck and shoulders and spreads over a period of time."
 2. a part of something resembling a shoulder in shape, position, or function.
    "the shoulder of a pulley"
 3. a paved strip alongside a road for stopping on in an emergency.
    "My partner and I had parked on the shoulder of the highway and began to chat."

verb
 1. put (something heavy) over one's shoulder or shoulders to carry.
    "we shouldered our crippling backpacks and set off slowly up the hill"
 2. push (someone or something) out of one's way with one's shoulder.
    "she shouldered him brusquely aside"

allowing the computer to shoulder much of the burden of debugging your code

* legit :Quora:
[2016-07-16 Sat 09:36]

adjective
 1. legal; conforming to the rules.
    "is this car legit?"

Title: Is Udacity's job placement guarantee legit?

* eligible :Quora:
[2016-07-16 Sat 09:39]

If you get good grades, volunteer at the hospital, play varsity
sports, and write for your school paper, you might be eligible for a
college scholarship.

If you’re eligible for something, you’re either qualified for it or
allowed to do it. You’re eligible for unemployment benefits if you’ve
recently been laid off, but not if you've never had a job in the first
place. You may not be eligible to enter a sweepstakes if you work for
the company giving away the money. Neither your dog nor your friend
from Australia is eligible to run for president of the United States,
but you might be!

Like these programs, Udacity's program has the limitation that you
must be able to work in the United States (so only 5% of people are
even eligible).
* discarded :Quora:
[2016-07-16 Sat 12:32]

adjective
 1. выброшенный (ejected, discarded, rejected)
 2. выкинутый (ejected, discarded, rejected)

* noble :Quora:
[2016-07-16 Sat 12:38]

A noble is a titled peer of the realm or an aristocrat. As an
adjective, noble describes someone with high or elevated character, or
who is impressive in appearance.

From feudal times, we have known nobles as the heirs to thrones or as
the holders of aristocratic title. British aristocracy, for example,
produces many people of various noble titles, including dukes, earls,
princes, kings, and queens. As various royal histories tell us,
however, many of these nobles in title weren't quite so noble in
character.

Tywin understands, and so does Tyrion. that killing 10,000 men in
battle is not noble.
* intentionally :Quora:
[2016-07-16 Sat 12:39]

adverb
 1. C<KH;5==> (deliberately, intentionally, willfully, wittingly, by design, designedly)

DEFINITION

adverb
 1. deliberately; on purpose.
    "I didn't do it intentionally"


Then she became pregnant - intentionally, by accident, or
accidentally-on-purpose, I have no idea.

* besotted :Quora:
[2016-07-16 Sat 12:42]

adjective
 1. >4C@<0=5==K9 (besotted, intoxicated, dopey, blotto, dopy, zonked)
 2. >?LO=5==K9 (intoxicated, drunk, besotted)
 3. >A;5?;5==K9 (blindfolded, besotted)

DEFINITION

adjective
 1. strongly infatuated.
    "he became besotted with his best friend's sister"
 2. intoxicated; drunk.
    "After some time, the brigands landed at an island, where they became besotted with drink, and fell asleep."

Their son duly arrived, and instantly became the central joy in his
life. My nephew is now 13, a happy, confident, outgoing boy with two
cheerfully besotted parents. Okay, so they stuck at one - but I don't
think they have ever regretted having him.

* hangover 							      :Quora:
[2016-07-19 Tue 18:51]

noun
 1. a severe headache or other after effects caused by drinking an excess of alcohol.
    "These side-effects are far more severe than a hangover and can act as a strong deterrent to drinking."

* commitment :Quora:
[2016-07-19 Tue 18:33]

Making a commitment involves dedicating yourself to something, like a
person or a cause. Before you make a commitment, think carefully. A
commitment obligates you to do something.

Some commitments are large, like marriage. When you take a job, you're
making a commitment to show up and do the job well, and your employer
makes a commitment to pay you. There are smaller commitments too. If
you said you'd meet a friend at six, that's a commitment  show up or
your friend will be mad. You also can speak of commitment as a
quality. Staying after school for a study group shows your commitment
to good grades.

7. Love is a broad spectrum - Love is a commitment. Love is being
there for someone when things go south. Love is making adjustments and
compromising.

* asset :Quora:
[2016-07-19 Tue 19:02]

An asset is something you have that is positive. It can mean a piece
of property, a piece of equipment, an ability, or even a quality.

"Her facility with math is an asset when it comes to figuring out the
restaurant tab. She is an asset to the group." A person's overall
financial picture is determined by lining up everything they own in
the asset column, and everything they own in the liability (or debit)
column.

In terms of humility, depending on your educational background, you
may end up in a situation where you feel intellectually ahead of some
of your more experienced colleagues, or more familiar with modern
technology, or so forth. But there is also a lot you can learn from
your colleagues and being a friendly and humble person to work with is
always an asset.
* groove :Quora:
[2016-07-19 Tue 19:07]

A groove is an indentation or rut in something — like the grooves on
an old record.

Groove is rooted in an old Dutch word for "furrow" or "ditch." And
that's just what a groove is: a carved out line, like wheel ruts in a
muddy road or the narrow opening that a sliding door moves in. If you
can't "find your groove," you feel off track and out of whack. But
when you're "in the groove," everything is working smoothly and you've
found a good routine. And if someone says "let's groove!", they want
to dance.

She did not just tell me. She actually made me repeat after her
several times, so it wore a groove.
* dorm :Quora:
[2016-07-19 Tue 19:09]

A dorm — short for dormitory — is a place where college or university
students live. You'll find a lot of bunk beds in most dorms.

If you go away to college, you’ll probably live in a dormitory — or
dorm. It's much more common for students to say dorm because it's
shorter and slangier. A dorm is where students live, often with
roommates. Dorms have laundry rooms and rec rooms, and it's a place
where many friendships are made. Students often study or try to avoid
studying in the dorm. It's their home away from home. Dorms are also
called residence halls and student residences.

When I was 18, I was a full-time college student. I was living in a
dorm on campus, about an hour and a half away from my hometown. I
worked a minimum wage job washing dishes in the cafeteria when I was
at school, and I worked at the McDonald's in my hometown when I was
there for breaks. I was still financially dependent on my parents.

* hookup 							      :Quora:
[2016-07-19 Tue 19:12]

noun
 1. a connection to a public electric, water, or sewer line, or to a similar service.
    "the campground has 70 sites with water and sewer hookups"

* sewer :Quora:
[2016-07-19 Tue 19:16]

noun
 1. an underground conduit for carrying off drainage water and waste matter.
    "A common problem is the unlawful channelling of storm water drainage into the sewer system."
 2. a person who sews.
    "Irene Caldwell is the company's costume designer who works with a small group of budding sewers ."
