application: valuesets
version: a07
runtime: python
api_version: 1
handlers:
- url: /static
  static_dir: static

- url: /xml/.*
  script: xml.py

- url: /uploadadmin/.*
  script: csv_upload.py
  
- url: /autocomplete/.*
  script: autocomplete.py

- url: /.*
  script: medhelper.py
