Hello friends this week I'm very happy to say that we are going to
learn how to learn Peter C Brown is the co-author of make it stick.

That book is about seminars you can get in the world of learning to
learn no matter what your area of pursuit in life it's pretty likely
that being able to expedite your capacity to intake information and
then recall it at will is probably gonna be pretty useful and that
doesn't matter if it's learning a new subject or learning a new
physical skill if it's knitting or archery or law all of them require
you to be able to remember and recall what it is that you're trying to
learn and Peter manages to lay out a really good framework for doing
that today in other news the modern wisdom YouTube channel has now
crossed a thousand subscribers and has nearly hit two million watch
minutes which is pretty crazy in the first two months of it being up
so if you haven't already please head to youtube search modern wisdom
podcast and give it a subscribe it would be a massive help also if you
haven't already whatever platform you're on whether it's tune in fm
I'm not even sure if that's a podcast listening platform we are
everywhere Spotify iTunes stitcher wherever you're listening please
try and give us a five star rating I don't really know if it helps but
it strokes the ego a little bit so do if you can but now we're gonna
learn how to learn Peter Brown bring it on 

[Music]

mr. Peter Brown welcome to modern wisdom. Thank You Chris. It's great to
be here how are you today I'm doing just dandy it's a middle of summer
here in Minnesota. 

It's nice time to be here lovely I've recently recently returned from
the states and the the weather was fantastic but apparently I've
missed the one warm week that we get in the UK as well I love the
white so I should have doubled that I should have doubled down and
just stayed home. 

I guess I understand. So I want to get straight into it. 
* ==>                                                                 :drill:
  Can you define to me what learning means?

** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide2cloze
  :END:

   For me I define learning is [picking up] knowledge or [skill] that
   [resides] in your memory and is [available] to you when you need it
   later to solve a problem or [take advantage] of an [opportunity].

Ok that sounds like a very a very curated definition. Was that
something that you came upon easily or is that something that you had
to develop through a lot of a lot of thinking a lot of conceptual
deconstruction? 

Yeah. I just made it up but it's because I made it up
when I started working on writing the book make it stick because I
felt that I owed the reader a definition of what we're talking about
with learning and I figured well I'll just try that and see if it
holds up and it held up fine was there a satisfactory definition in
advance of that no I'm sorry but I might have a problem with my
headphones because that kind of comes on and off oh ok I'm not too
sure what's going on there that might be that might be on my side. 

ok. so ask the question again. Was there an existing definition of
learning that you were happy with or was that one that you just
created? 

Did that need to be there as far as you were concerned. I felt
it needed I felt we needed we owed the reader a definition of writing
a book about learning we owed the reader a definition of what learning
is and so I sort of thought about a little bit and I wrote that. And I
thought we'll start with that and see if it holds up as we go through
the book and and it held up fine some people in science. The sciences
refer to learning as three things one being in encoding which is when
you first encounter material and it's it's encoded as traces in the
hippocampus. 

Consolidation this is the process by which it moves it
migrates over hours or days into other parts of the brain where
long-term memories are stored in retrieval being able to recall it
again later. So the scientists think of it as that's learning for them.
For me it's you learn it and you remember it and you can recall it
when you need it. 

I understand so can you give us a little bit of background to the book
make it stick and why you were compelled to write that?

Yeah, sure. I've been retired for some years I made my living as
marketing and planning consultant to corporations here in Minnesota
and I had turned to writing books and I was between book projects now
sitting down with my brother-in-law Henry wrote agur Henry wrote a
girl who goes by Roddy is internationally preeminent in the field of
memory and learning he's a cognitive psychologist and he was telling
me that he was just coming to the end of a ten year study of what
strategies lead to better retention of the new material and he had a
team of a cognitive psychologist at 11 different universities doing
this work with their their doctoral students and postdocs and over a
decade of such studies they were coming to some findings that were
counterintuitive and he said I've been trying to figure out how to get
this out to a broader general audience? Maybe we should collaborate on
a book?

So that's how I got into it. I'm not a scientist but I was very
taken by what they were finding so Roddy Henry wrote agar and one of
his colleagues Mark McDaniel was also a cognitive psychologist they're
both at Washington University in st. Louis Missouri the two of them
and I collaborated on this book. 

Okay. So I guess you've got the you've got the cognitive firepower in
there on those guys's sides you know 10 years and 11 facilities that
have been used for that particular study it's not as if you're it's
not as if you short of of research on that side. 

No and the book is based on decades of research and reaches far beyond
the work of that team but you're right that it's it's firmly grounded
in the empirical evidence but I tried to write a book that was highly
anecdotal and engaging to read so that people would stick with it and
we could tell stories that Illustrated what the science shows about
how learning works well. 

That gave it a different kind of twist than the typical scientific
study publication. Yeah. For sure I think in order to get the wider
population to be able to buy into books like these. 

You need to bring it back down to earth, there needs to be some tacit
examples and some things that people can relate to everyday life.

Talking about standard deviations away from the norm and you know it
doesn't like anyone's eyes it'll light some people's eyes apart your
two co-authors would be it would get would get turned on by that but I
guess for the for the normal reader that's not going to be that's not
exactly gonna like light the fire in their valley so to speak I
wouldn't keep me up at night it put on your right to sleep yeah agreed
agreed so you've got the existing research there did you think that
writing a book on the science of learning was was important to to
publish to it's a wider wider audience well I thought so and they did
too and I think the reason it struck home with me is because I have a
bachelor's degree from college I brought us I don't have a graduate
degree you know higher training I've always been someone who's taken
an interest in things and then gone about learning about them and
figuring them out and what their research showed is that the way a lot
of people particularly students go about learning is by review when
we're reading and trying to push stuff another brain but what is far
more effective is trying to get it out of the brain it's the tinkering
the trial and error the experimentation the learning from the turns
and setbacks that you get and I just felt very much personally
affirmed by what the research showed and I thought I would really
enjoy getting my hands on this and because I felt it was very
important but I also felt I was really interesting well it's superbly
fundamental isn't it that no matter what discipline it is that you're
studying in that the science of learning to learn is foundationally
ahead of all of the things ahead of everything that you're trying to
do you need to be able to know how to learn because it's it's
universal right it's ubiquitous it is and from the moment we leave the
womb children are experimenting touching tasting trying things and
when we get older we lose some of that and I think the traditions of
our schools are such that learning involves an expert who imparts
knowledge to students and in fact it doesn't really it's not really
very effective I think athletes know this when they go out on the
field and they have a coach the athlete knows that she or he has to
figure this out and the coach can give feedback and they could work at
it but most students including athletes who walk into a classroom
expect the learning to be aparted to them and and learning is not
imparted learning is something that's really acquired unless you know
extraordinary circumstances were you you have some tremendously
significant emotionally significant events of things that we're trying
to build in the way of mental understanding and mental models and
mastery you have to acquire that's interesting so did you have a look
at or can you give us some of the typical approaches of an unlearned
learner as I as I'm gonna call call someone someone who's
unenlightened as to perhaps what is what the research suggests did you
have a look at what's the typical approach well that well in surveying
students college students that by far and away the major study
strategies are rereading material underlining and highlighting and
note-taking that kind of thing but the science shows that what's far
more effective after you've heard a lecture or read a passages to turn
aside and give yourself a little quiz what were the big ideas in this
material try to recall it and try to say to yourself this relates to
what I already know in the following ways or if I were to put this in
my own words here's how I would do it it's engaging the mind in the
material so I I summarized all of make it stick with three ideas the
first one is the one I've just described learning happens when you
struggle to get the learning out and apply it not when you continue to
reexpose yourself to it it's about getting it out a second big idea
for me is we try to make learning simple for students but actually
there are some kinds of difficulties that are desirable an example of
a couple one would be when you practice a a motor skill like your golf
putt or you practice something you're learning like solving
mathematical problems it's good to practice a little lot of them space
it out and come back to it at a later time but at a later time takes
more effort to recall what was the formula and how to successfully
apply it and it that kind of spaced practice feels like you're not
getting it because your performance is rough but the actual effort
involved in recalling that new material from your long-term memory
strengthens the connections - it helps it reconsolidate helps bring
forward the most important points and it makes it easier recall again
later so spacing out your practice is better than practicing things in
a masked fashion that's a desirable difficulty it doesn't feel good it
definitely doesn't know another desirable difficulty is mixing the
practice of similar problem types so if you're let's take the bath the
math example if you're practicing learning how to find the volume of a
cube and a wedge and some other kind of series of different solids the
typical way that you would do that with a math book was you you just
look at eight different wedges and you'd apply the formula eight times
and then you'd move on and do these other different kinds of solids
and during practice you do very well you've got tests that you do
about ninety percent but if in fact once you've learned each of the
formulas your practice problems were in random sequence you would only
do about 50 percent right and you wouldn't feel too good about that
but a week later you will have remembered that same 50 percent you
would do extremely well on a test compared to the others who have gone
from ninety percent down to 23 percent because they didn't mix it up
and when you get a test where it's mixed up they can't remember which
formula went with which problem yes so this whole notion of mixing
your practice which does not feel good is very powerful for improving
your ability to recognize the kind of problem you're facing and
picking the kind of solution that's going to be correct that's
interesting so there are other kinds of desirable difficulties and so
the notion of if it's clear as a bell I'm sure I'll remember it you
know it's not really true if you have to reconcile different ideas
between the lecture and the book chapter or what have you that mental
effort is what's going to make it stick that's interesting is the
second big idea that some did some difficulties are desirably okay I'm
the third number three number three is that our intuition leads us
astray so our intuition is when I reread it many times I get very
fluent in it I'm on top of it I can do that can do that and take a
test the next morning I pull an all-nighter and I can get a great
grade on the test it doesn't stick though what happens if you're
tested again a week later you've lost about a half of it our intuition
says if we practice our 20 foot putt over and over again we see
improvement and it's true you do but that improvement leans not short
to remember it but the skills have not been consolidated in long-term
memory that takes overnight or it takes days so you walk off the golf
course thinking you've really done a service to yourself on your 20
foot putt but much better would be to do a few 20 foot putts then do
other strokes and then come back and mix it up and it doesn't feel you
don't see that same kind of improvement but your brain is getting
better at judging distances and the motor skills required you know to
to make a good stroke so our intuition leads us astray and it causes
us to spend time in strategies that are not paying us back okay so I
mean that's a to me conceptually make sense but it's quite a probably
quite a big departure away from anecdotally what I would have thought
good learning should be done you know the kind of the force it down
your throat so to speak I'm sure you know the the the really drill it
into you stick to one task for a long time I know if you if you listen
to the podcast that I did with dr. you and Lawson we discuss in that
about multitasking and the Pomodoro Technique deep work and trying to
focus wholly on one task it's not too far of a jump to think that
instead of just focusing on revision you should drill that down again
to just focusing on one topic within your revision right and I think
that that could quite erroneous yeah erroneously be one step too far
in terms of the house of specific your being with your agent with your
revision time so let's go from the start can you explain how learning
and memory or learning and recall relate to each other yeah sure our
memory has two components actually my co-author Roddy rota ger is his
field is memory and he's really written the break a lot of the
breakthrough material on memory including uh discovering this whole
field of false memory but in any case long-term memory is is in
different parts of the brain than short-term memory so when we're
talking about short-term memory or working memory it's the list you go
to the grocery store you maybe remember it long enough to pick up the
things and then maybe you might or might not remember you need to stop
by the dry cleaner on the way home but that's gone is there a is there
a time if they're a approximate time limit usually on that 24 hours or
not particularly but III don't I don't think so I think it depends on
whether you're trying if you're making an effort to remember it for
longer for example you're you rent a bike and it's got a four-digit
combination lock and you're trying to remember those four digits when
you can give yourself a tool to do that I was with a friend and in
Adelaide Australia and she said I can't I can't even remember my pin
number on my card how am I gonna do this with my bike well what are
the numbers she said it's five to six eight no no I said well I'll
break it into 52 and 68 what can you do with that all 52 is easy
that's the cards in a deck of cards in 68 oh that's the swirly girly
she said so she still remembers this four-digit number of years later
so there aren't devices you can use you know well if I have
information to keep to keep in your mind so but the long-term memory
is different from short-term memory and that is it needs to migrate to
another part of the brain and be connected to the other things that
you know so the two aspects of long-term memory are one that it gets
thoroughly and embedded in the brain and connected to many different
points of knowledge if you can attach a visual image like us medical
schools to annales talking to who was trying to remember stuff medical
stuff and he said I realized after reading the research that if I
paused and made a mental picture of the the organ I was reading about
and thought about its connections that I could remember that whole
thing better what you get more different connections in the brain
which become routes to finding it again later and recalling it so it's
partly about having having it thoroughly embedded in your brain and
it's partly about having the cues you need to find it later when you
want it a lot of things that we've learned in life we can't recall
because we've reassigned the cues to other things in the meantime in
terms of what you saw to use well what I mean Chris is when you come
to LA and you rent a car you have to create no queues to remember to
stay on the right side of the road the queues if you are going to take
your a-levels for example in psychology as was the case of a
psychology professor at Oxford that we talked to he took his students
his students were have mastered the content but the pressure and the
a-levels you don't know which materials are gonna be asked to write
and then in each of the ones you're asked to write there's you know
multiple paragraphs I'm sure you know this better than I but yes so he
took his students to coffee shops and he'd say ok and I'm imagine that
you've what you're walking into the coffee shop and you're going
around the perimeter of the shop and they will attach meaning to the
different parts of the furnishings with the layout that give them cues
a name of something that cue that next paragraph in there right up so
when they learn what the subject is they have to write about they say
ok that was at the such-and-such you know pastry shop yeah and I was
sitting there and I can see I came in oh yeah I called that fern you
know something or other and they and on they can go they have the
queues so under pressure when we tend to kind of freeze up in being
able to recall material that's a cert of mnemonic device yeah those
are accused by which you can bring it up it's the it's the beginning
of the deck of cards that starts to tumble into the rest of the
knowledge right exactly so I can certainly draw a parallel between
that and my learning style so to give you a little bit of a little bit
of context for myself my learning style from probably my GCSEs of 15
and 16 was to write summarise notes and to then completely verbatim
record in my mind what the notes were on the page so I would know that
top left starting at the top it was this particular bit than this then
I could see when I got into the exam I could actually feel in my mind
where let's say that I'd written a word incorrectly and I'd crossed it
out I'd be like ok so it's three pages in it's that old is that
there's the word that's written correctly and those sort of hues I'm
aware that that you know had I have had I've been able to read your
book before I went to university I'd have probably had probably had a
much easier time of it but it was kind of for me I guess I was I was I
was using recall but that was blunt force like just complete yet
source verbatim great and that wasn't using the desirable difficulties
spacing and that also wasn't using point number three either so you
know I think I'd maybe I'd maybe focused on the recall and I was I
discovered myself that using recall was a good way for me to at least
wait it's pointless learning something if you then can't if you can't
then pull it back out as you say you know it's almost as if what
happened either yeah is pointless and so we had an email from someone
recently he would read the book and said I'm you know I've developed a
new way of taking notes and I'd like to know what you think of it he
said instead of trying to capture everything that the lecturer tells
me I've read the material and I hear the lecture I start have been
writing questions in each area so that when I go back to review my
notes I'm actually requiring myself to recall from memory and look up
if I can't recall it what the material is yeah that's pretty kind of
you know that's a clever way of doing it because that's what you're
gonna have to do a test time yeah and then the other issue about
memorizing notes or memorizing a text is tempted temptation to
memorize terms in as opposed to concepts so it's always important when
you've read something or taken the notes to be able to elaborate on
them to explain why is this important what would happen if this
weren't true what how does it relate to what I already know I guess
that's the difference between pure recall and comprehension that right
yes and and which leads ultimately into consent try learning right
okay that's interesting so I did question that I want you to ask him
we've led onto it pretty perfectly here is it possible to learn
something but not remember it well sure there's all kinds of things
we've learned that we don't but we can't recall functionally do I
guess there's two ways I don't recall it yeah yeah there's a lot of
stuff that you've learned that you can't recall until you get some
kind of a clue you'll see someone out of your past or you start
talking to someone about past things and all these memories start
flooding back or you catch a smell that's particularly were when
something happened and the memories start flooding back so that's
maybe a little different from what you're asking no I think I think
that's right I think you I think you correct you what you what we've
fallen back to here is the cues right right exactly right I had this
problem in 1998 my wife and I spent a year in Italy and I would go and
take lessons on the language and and the only non English language I
had in me and I didn't have much of it was four years of French and so
my brain kept presenting the French whenever I was trying to say
something he's not gonna go down very well within its own yeah I
didn't go down startled to me well I understood it better after I
wrote this book that I'm I'm cueing you know a foreign word for
whatever and then I discovered after a year in the country and getting
mildly able to get by with the language that I could differentiate
between the French and the Italian on demand but it was because I got
more diverse cues I suppose yes that's that's that's really
interesting so okay we we've understood the recall would you is it
fair to say that recall forms the foundation for learning or that the
ability yes okay so without without the capacity for recall the
learning any learning that you build on top of that from comprehension
to that what was what was the terminology that you used in conceptual
knowledge conceptual knowledge right okay so what when in there here's
an interesting thing that lets take or you can take hitting a fastball
well you don't play baseball over there but take some kind of a soccer
move or take it you know driving a stick shift car yeah you get into a
car you're a brand new driver you got to adjust the seat and adjust
the mirror you got to look here and look there you got to push in the
clutch and push in the the shifter and let out the clutch while you're
putting on the guys very complicated set of moves and look and steer
out into the roadway and move along well you and I do that without any
thought whatsoever I mean we're thinking about the luncheon we're
about to arrive at yeah so there's a lot of learning and particular
procedural learning that the recall is that the procedural learning is
kind of chunked like the scientists actually call it chunked in a part
of the brain and it's available to us just like that without having to
think no how what do I do with this shift lever what do I do with my
feet is there and we get to people who are at very high level in the
sciences for example or any field musicians whatever they have spent
enough time with the fundamentals of physics or energy and transfer or
whatever those things are that they just invoke this law or that law
subconsciously as you're looking at a situation so those of us who
don't have that knowledge we had to think through every darn step we
had to think through every part of that shifting and driving sequence
but with practice especially if it's spaced out it becomes second
nature to us and then we possess it and then that becomes a mental
model that we can build on in other in connected to other abilities or
other bodies of knowledge I understand so time and attention that to a
degree is is going to be an important factor that trying you know
cramming and and rushing you're learning together is not giving you
enough time to allow that to settle and then to come back to it right
well that's exactly so it isn't just spacing out the practice of
something with intervals between so that you're a little rusty so it's
a little more difficult to do and that difficulty actually strengthens
there's our really difficulties again right yeah right but it's also
true that in a course if you're let's say your professor and of course
is better to introduce a lot of the material earlier in the course and
come back to it in distributed over the period of the course because
when learning is distributed like that it sticks better and it has
more opportunities to connect with the other related material instead
of doing it in block fashion or in a silo okay you know first we're
gonna do this we're gonna do that yeah so you kind of look you take an
overview of the entire map and then you begin to move through the map
piece by piece right and so if you're managing your time I know I'm
gonna have a test next Thursday on such-and-such you don't want to say
Wednesday is my day I'm dedicating to that you're better off
dedicating some a little a little bit of time each day between now and
then because that distributing that out over time is going to help
your brain do what it does well our brains are such that if we go to
bed pondering a challenge or a problem the brain we've discovered is
working at that through the night and it will throw out your relevant
stuff and try to connect us to other stuff it's a remarkable thing so
you are kind of empowering your brain to take some responsibility for
learning this material if you start it early and come back to it from
time to time instead of trying to force it force it into your brain
well I'm afraid that now I'm afraid that eighteen years of full-time
education led me to do everything less knit so I memorably I'm
probably patient zero for how bad you can be at cramming but you know
I can I can certainly appreciate the times when I have spent a little
bit more time over stuff and I've distributed it throughout my week or
however it may be I'm right in thinking I read a I read a study
recently that talked about the capacity for problem-solving before and
after a night sleep versus if you had one 5-hour chunk or two
two-and-a-half hour chunks spread over two days and the difference
between the group that had the sleep in between and was their brains
were allowed to reset and look at the problem with fresh eyes the
capacity for them to complete the problem was so much so much more
impressive than the group that just had one yeah one go at it for five
hours which two-degree almost sounds counterintuitive do you think oh
I've got to get back in the same headspace and I've got to get myself
up to speed again when I start yeah I've got to recall all this stuff
that I did that I might have forgotten but you know almost slightly
covered intuitively it doesn't seem to be that way it seems to be that
like you say distributing it is yeah there's a really interesting
study of medical residents who are learning to reattach tiny vessels
with a surgical stitch in the way in this country they do that they go
away for a day and there's four lessons the first they get a video and
then they're given a little bit of rubber tubing called a Penrose
drain and they're shown how to pass their stitches through an entire
surgical knots and then they see a video and they're given some
synthetic tissue and they practice that then they're seen a video and
they get given a turkey thigh so there's four videos four sessions one
day the end of the day they are supposedly on top of this this skill
okay so well in this in the study half the group did it that way there
are 38 of them and the other half came in and did the first video and
practice and they went away for a week and they came back to second
week for the second video on practice and I'm thinking those those
doctors are sitting there thinking wow let's see if I can remember
what was that less yeah exactly my life is busy you know and they
struggle to kind of recall what it was and they had this next lesson
and they went away for a week so I would like this for weeks so they
had the exact same training but those whose learning was spaced out
over four weeks far exceeded the others in all expert measures and
they were then they had a surprise test they were given a rat that had
a severed aorta and their challenge was to save the rat to reattach
the art and all of those who's learning was spaced out succeeded in a
large percentage of those whose learning wasn't spaced out and we're
not able to see if they're lucky if you were right I want them to do
this first goal and then just a great example of this the simple power
of exposing your brain to something and working with a little bit than
going away and coming back later and making that effort to recall and
then adding in okay so we've got we've got recall we understand the
importance of that moving on to the second the second key concept that
you had which was desirable difficulties and the spacing our effort
can you explain how someone can apply that how can you how can you
force desirable difficulties into a studying practice well let's take
a subject I mean you can you can study let's say there was a great
study of Y don't worry I'll use one where people were identifying
learning to identify birds and so they had I don't know four or five
different families of birds and they were given exemplars of each of
the families so they'd be given a bunch of Thrasher's to learn and
then they'd be given a bunch of you know I'm not a bird guy maybe
Raptors or whatever the different groups were okay yeah and and then
and then they were a challenge they were showing a bird they hadn't
studied and they were challenged to identify which family belong to
and the interesting thing about birds is within these families there's
no single characteristic that is true of all birds within a family so
you're looking at a comp a sort of a a group of different kinds of
characteristics that generally would come to define a family okay so
those who learned it in this way looking at many types of one and many
many examples of another's worth didn't learn them nearly as well as
those who had the different exemplars shown them in random order so
this is a study if you were studying you study in random order and
they learned far better they learned they were better able to identify
the unifying characteristics as well as the differentiating
characteristics of those birds and in other kinds of same motor skills
learning in the same way of mixing up the the particular problems that
you're trying to do or the motor skills movements they become much
better at transferring that skill to an unfamiliar situation so what
if you're in a study situation where you've got a group of different
types of problems that you're trying to master you can take it upon
yourself use flashcards to mix up your expand amaz'd order in a random
way right okay that's interesting so neurologically there must be
something going on within the brain that this particular mix-up of
recall of recall requirements that must help to embed the learning
somehow yes so I'll say that one of the differences between cognitive
psychology and neuroscience is that the cognitive psychologists do
these empirical studies if this happens what is the result and they
learned from that the neuroscientists then are saying well how does
that work in the brain what is going on in the brain and so those two
fields are coming together but there's a long way from our really
understanding exactly how this works but I'll give you a very brief
example these were elementary school children who were tossing
beanbags into baskets okay and 12 weeks everyday at gym for 12 weeks
ladies a boring 12 well they're pretty young kids they like tossing
the 30 bags and if they're easily they're easily pleased tossed every
time into a four foot basket the other group toss sometimes into three
foot and sometimes into five foot never in the forfeit at the end of
12 weeks they're all tested on the 4-foot basket and those who are
best able to hit the 4 foot basket we're the ones that have practice
on three feet and five feet but never on the four feet that's so
interesting so the reason for that the speculation you know what the
scientists believe is the reason for that is that these four foot the
three foot and five foot challenges required variation in judging
distance and the motor response to it and gave them more complex that
the really interesting thing for me was it they believed that this
skill of the three and five foot tossers was encoded in a different
part of the brain where more complex motor skills are encoded than
those who just repeated the four foot toss over and over and over
again one was a little more robotic and didn't require the yep the
extra comprehension right the conceptualization yeah right that's
really interesting that's a fascinating study so I think what you've
done there is you've touched on what again is a cognitive bias that we
sometimes have to presume that because we're able to recall you know
if we stick to one thing for a night and you're able to recall that
one thing you're like yes I've got some work done it's planting a flag
in the ground that okay I can remember this one thing whereas the
desirable difficulty which is potentially a better route to learning
longer term in the short term can actually make you feel like you're
doing less work right or like you're making less progress so oh well I
can't really in full recall any of these individual parts but across
the whole the amount that you've learned in quotation marks has
increased is that fair to say yes it is I think you do are more easily
discouraged when you do that is there I just must say in any of these
things that you're gonna try to practice in a random order you want to
try you know you want to try your 20-foot putt a few times you kind of
get a sense of what you're trying to do you want to find the volume of
of the spheroid a few different ones a few times so you get a sense of
what that is and then the practice is mixed up so don't keep doing the
single one until you've got it nailed so to speak interrupt it
interrupt it and move on to the others and come back to it later it
won't feel as good but just going back to my own personal experience
struggling with the Italian language well you got over there the first
of the year and by the fall of that year I was with some young
Italians we had befriended from the school and and we were chatting in
Italian and I heard myself using idioms that I didn't know I knew and
these had come to me through stopping I rode my bike around a lot and
I'd stop at the town water pumps to get water and I'd try to chat with
the people who are hunting birds or whatever you know and there was
always a struggle and a frustration but the brain is probably for both
it probably some both holidays as well probably a frustration for them
as well as for years and Americans give too much weight to your
frustration you just need to kind of trust your brain and then your
brains working at making sense of it as long as you give it the
challenge yeah okay so I get that sort of touches on the one of the
third main concepts isn't it as well that too you don't really know I
guess using your own judgment for how your learning is going sometimes
you kind of just need to stick to the program right well right a
really important thing that this these cognitive psychologists talk
about us well they call it metacognition which is thinking about your
thinking and that is we're easily duped into thinking we're or on top
of something that we've got it and so what's important is to test
yourself from time to time do you really have it can you really do it
can you really explain this and so self testing has a couple of
benefits one is you learn whether your judgement of what you know and
can do actually is accurate and it and it helps you focus where you
need to bring it up a little bit but the other is the fact of
recalling this stuff is a great way to strengthen your retention of
your mastery and retention of us so as as a study strategy as
self-quizzing ism is potent in several ways there's a kind of goals me
go well I just say when we're talking in schools with professors and
teachers one of the fundamental things that is highly effective is for
the instructor to incorporate frequent low stakes quizzing in the
course low stakes so that people aren't freaked out by no pressure
yeah right you just really dial really dial down the pressure and have
the the experience and ultimately the habit of recalling from memory
what this stuff is in the end that if you can do that in a course
where you're reaching back to earlier material as well as more recent
stuff that stuff gets brought forward and better connected it's a very
potent and not very difficult a strategy for helping students get to
the middle and the end of their course on top of the material that's
interesting there's a program that I know a lot of my friends who
adopt is medical students use called Anki I'm not sure thank you yes
so on keys cue cards write randomized cue cards mostly with
multiple-choice questions and would that fit into your model of
consistent low-level testing yes Anke is great yeah I wish I wish that
I'd known about Anki while I was at while I was at university I think
it might have made my my last minute procrastination tactics a little
bit less about Anki and some other online stuff is it you can have it
you can set it up to to come to your phone and periodically yeah you
did they get reminders will be side dinner and I look over to one of
the guys and they'll have his lab is an kikyo cause his reminders
popped up laughs you were in our household if you were doing anything
other than practicing what he's supposed to learn he'd get a steep
scolding from my wife right that's a disgust that's an undesirable
difficulty right there okay so we've got the capacity for recoil we've
got the desirable difficulties and we've got kind of trying to trying
to ignore what your brain is telling you about how your learning is
going yeah I think it helps if if you can think about stuff you
struggle with that you've had these kind of breakthrough moments it
might be I think of people on BMX stunt bikes I think of people doing
video games trying to find their way to the next level trying this
trying that you know and oh yeah this is what I did last time that
worked kind of thing all the different ways that we're not thinking of
as academics but in our lives where we go through these kinds of space
and episodic exposures to something we're trying to master and then at
some point you realize it's coming to you you know you've kind of got
it yeah that's going to be the same with the somatic material in a
class or with the motor skills stuff when you're trying to learn how
to stitch up a rat or trying to you know I do I went viral oh oh I saw
yeah okay I understand on that um did you in the book did you touch on
anything to do with the focused and diffuse mode networks did you look
at did you look at that much at all I don't think I've heard of that
okay okay so there was this - so there's a course from Coursera which
is a massive open online course and it's called learning how to learn
and I had a little bit of a look through that before I before I knew
we were gonna have our podcast today and with that they they're
focusing a lot on the focus and diffuse mode networks what they were
talking about there was it seems to me the longer term the ability to
recall over time and this as you say this more open mode of thinking
as opposed to a more procedural mode of thinking that when you're
learning something and you go away and then you come back you often
have a very open mind to what the what the solutions may be we've
discussed it previously I've said I did a podcast and meditation not
very long ago with Cory Allen and one of the one of the things that I
wish wouldn't happen but I also appreciate does is when I sit down to
meditate and I quieten my thoughts that's often when I have some of my
best ideas of the day which is terrible because I'm trapped in this
I'm supposed to be trapped focusing on clearing my mind and I've got
all of these really good like awesome ideas coming to me and I think
God I just could can you not happen when I'm not meditating can the
meditating just be allowed to continue on its own all right yeah I've
had that experience but of course this is the brain offering you some
ideas and I if I understand this difference between the focus and
diffused I think one of the one of the astonishing things in writing
is when your mind presents a metaphor for something that helps make
clear the this other thing you know this notion of the similarities
between things that your brain recognizes and so this is one of the
things I believe from what I've read about sleep that begins to happen
when you think about struggle a little bit with a problem or maybe a
conceptual problem in the evening and in the night the brain will kind
of look around and see what do I know that's similar to this are there
models that are like this others is it like this other thing and you
can get some great breakthrough ideas that way so maybe in the in the
meditation where you're just giving your brain you're trying to focus
on the mantra but you're also focusing on your breathing and your
relaxation and it's a very freeing thing and if the brain is
presenting you with images and ideas you know I I think I can only
think that that's constructive you know I agree I couldn't agree more
I think one of the examples that was used was Newton and it was that
he would sit in his chair with ball bearings in his hand and he would
wait he would wait until he just fell asleep and the ball bearings
would drop from his hand and crack on the floor and it would wake him
up and that was the moment at which for him he often had a lot of
breakthroughs and you know if it's if it's good enough Newton it's
probably good enough for us it happens for me when I get when I get
frustrated with my writing and I get on the bike and I head up the
hill and I just smell the smells and look at the horizon and I bike
along and all of a sudden you know my brain starts giving me ideas I
get this like aha moment this is this is what what I could do about
that problem is and then I can come back and work on it do you think
it's difficult to ask someone who is learning or trying to be
productive or writing or whatever it might be do you think it's
difficult to learn when enough focused time is enough and it's time to
move on to oh it's time to take as you say like a planned break to
give yourself that room to breathe because you know you need to spend
some time and attention exposed to the material or exposed to the
particular physical practice or whatever might be but then also you
need this time away from it as well do you think it can be a difficult
scheduling problem for people to know when enough is enough well I'm
sure it can be I don't know I don't know of research into that
question my own human nature tells me you need to have you need to mix
it up and you need to get out of your chair or get out and get some
exercise and then come back to it but I don't know I'm not aware of
research on it one of the things that was a pleasant surprise for me
when I was working on this book I hadn't been aware of the search tool
Google Scholar where you can search for published research on you know
you can put in a term and see where research has been done and thumb
through the different published studies yeah yeah that's kind of
useful I suppose most everybody else knows about it but I didn't and I
found it very awful but I you know it to me intuitively yeah but of
course I'm saying intuition leads us astray with learnings so you
gotta be careful on both sides of the fence right yeah well there's
one thing you know one of the things about being a non-scientist
writing this book with two scientists was I was I tried to be I tried
to take liberties in relating the science to stories of real people
and incidents in their lives and so forth and drawing parallels but
stay within the strict limits of what the empirical research shows us
and what and where we're drifting in a speculation to say this is
speculation but it might be because of such and such yeah so we've
gone through the the three key concepts that you've got there the
capacity for recall the desirable difficulties and then ignoring me
ignoring the cognitive biases to to one degree or another or cutting
yourself some slack if it feels difficult thinking you're not getting
it yeah cut yourself some slack you think you're not getting it but
you probably are yeah okay um so other any other elements that you
think that people need to be able to understand when it comes to
learning is there anything that we haven't gone through yet well there
is this theory of a growth mindset that has been introduced by
cognitive psychologists Stanford University in California named Carol
Dweck and she's done some work that she or she studied with she she
got she would took an interest in why do some people become helpless
when faced with a difficult problem and so she did some work with some
low performing New York middle school junior high school students and
gave them a little seminar on how the brain works and then half the
students she took aside and talked about memory the other half she
took aside and said a lot of people think that their abilities are set
at birth by the gift of their genes but in fact when you work hard to
learn something you are building new connections in the brain and over
time your actual increasing your intellectual abilities through these
challenges these mental challenges she sent them all back into class
she didn't tell the teachers about these two different subgroups and
the students who had been taught that they have some influence or
other intellectual abilities by picking tougher problems and
persisting at them began out performing the other students and she dr.
Dweck developed this sort of duality of a fixed mindset versus a
growth mindset that people with a fixed mindset tend not to pick
problems they won't do well at because it'll indict their sense of
their native ability or as those who have a growth mindset when they
encounter a difficult problem try a little hard or try a different way
you know carry on forward and do better now so there's an issue here I
think when we're saying that some difficulties are desirable it's not
doesn't sound like good news to students a lot of students want the
easiest path possible right I mean we all do we're all we all did yeah
we all want to get as much as possible for as little as possible right
it's in nature I think we all agree on that so I think I think that
there's more research that needs to be done about whether a belief in
an understanding of this ability to improve your brain is actually a
motivator for people but the fact remains nonetheless that when you
learn new things especially you you rise up the complexity of the
topic you're dealing with you are increasing your intellectual ability
and there's that many more things that you now have the ability to
learn because you have places to attach them you can't learn something
new or if you don't have something to attach it to that you already
know so I think there's the field of motivation is one where there's
some interesting work being done and it's one that I think it helps
for people to keep in mind that you need to you need to be a kind of a
coach to your own brain saying I know this doesn't feel too good but
guess what it's really gonna pay off yeah I totally get that is it a
weird a weird analogy that I can draw between this and a recent
podcast that I did with some CrossFit coaches from the UK and in it I
was asking about mental toughness in sport and I was talking to them
about how they prepare for these competitions and during these
CrossFit competitions a lot of the athletes very very heavily mediated
by their capacity to suffer discomfort and again with that it's a lot
to do with mental state so I was asking the guys you know how do they
prepare in an appropriate way and what they said was how many events
is it over a weekend is it seven events over a weekend okay well
during you prep for it do 20 do 20 events over a weekend and then when
you get there you realize I've prepared so much further above and
beyond where I needed to to bring it back to you know you're right the
difference between an athlete that's doing that and typically how
someone will be learning even if they're being taught by a lecturer or
a teacher on a formal course at university or whatever it might be the
coach is mediating that impression of how the training is going right
it's very rare I don't think I ever once spoke to a lecturer at
university or spoke to my tutor and said my learning is going slowly I
just perceived that as a byproduct of our world like learning isn't
easy and I need to just help put get my head in the book a little bit
more until it sticks and right I think that the the paradigm the
environment that students exist in it's very different to that
typically if someone patata perhaps who's doing sport that you know
your coach can see when you are and when you're not getting it whereas
yes there's a lot more a lot more variables that can well does your
lecturer think that your test scores during the build-up to exams are
low because you're not working hard enough they don't really know they
don't see you practice do you know I mean and the practice is a lot
less visual as well it's a lot less easy for them to work out so yeah
I think the the concept of desirable difficulties is it's something
that shy of definition as as we've done today is probably gonna be
really hard for people to actually work out where it's right yes I
don't think it it has to be real hard I have a couple thoughts one is
that we're encouraging teachers to help students construct their own
understanding of the material as opposed to lecturing here's what the
material is in trying to impart the lecturers understanding so that
means the classrooms become much more involved in exercises that
engage the students and working through and figuring stuff out and so
that's one thought I've lost the other ones oh did you end up with
your comment I said it was about it was about CrossFit and it was
about having a high level of difficulty than you need so you can go
off train hard train hard perform easy right yeah I think I don't know
it's gone sorry um but no I I think you're totally right I can
definitely say you know I enjoyed my time at Newcastle University but
the course that I was doing quite often we'd have 200 to 250 people in
a lecture theatre and that was for a lot of the a lot of the modules
that I took and in terms of comprehension and that two-way
communication with the person who is disseminating the course
information it was non-existent like you can't you can't ask us around
the room of 200 people you can bet I mean they could barely barely
keep us awake because it's such a big room now so unengaging it so on
and so forth so yeah the the implications for teachers here are almost
as wide as the implications are for students right right I think
that's right and I think the the revelation for the teacher is it's
really about learning it's not about teaching this is about learning
this is about how you can help students become the learners not you be
the teacher and the the oh this other thought came and now it's gone
back again it's just making me yeah I don't know it's all this it's
all this talk it's all this talk of recall it's ruining your capacity
for recall I think my short-term memory is that status my working
memory it's just a little fried right now right well that's fun that's
totally fine maybe you should go away maybe need to go away and come
back to it probably need to do that I think we'd laid out some some
quite nice concepts there we've gone through what does learning mean
how do learning and memory relate what does recall mean the desirable
difficulties and giving yourself a little bit of a break and and not I
think I liked it the the third key concept that you've got there
because I think that's the one which will mediate all of the rest that
if you don't believe that you're making progress you're you're going
to fall back into the typical brute force one concept at a time
approach and I think that the all of the others are relying on you
having faith in the learning process working right so I got my idea
back so I would have yeah I have two thoughts one one is that often an
instructor what instructor is teaching you about a topic the
information is arbitrary the student doesn't know why it's important
or what it connects to and so forth it's really important for
instructors to when they lay out something new say to explain here's
how this relates to where we've been and where we're going here's how
it connects to what we already know oh so that the students have a way
of connecting to it and grabbing hold of it okay and making sense you
know the other side of that is I think students have an opportunity if
they're not getting it - to say to the instructor I'm not getting it I
don't quite understand how this relates could you give me an example
of how this is true elsewhere or in another topic or something to help
me understand it okay and then I can practice at you know building
that learning dialogue I think is we just used to a kind of I'm the
expert you're the student I'm gonna tell you how it is you're gonna
take notes then we're gonna have a test yeah that's definitely my
functional [Music] experience of learning that is it's very much a
one-way street and that there will be it almost felt sometimes like
lecturers knew that they had to ask a particular number of questions
and that that was just a hurdle they had to overcome the same as
saying the next slide it wasn't something which was being done to
actually embed the learning right yeah which I think that's really
interesting are the implications for the teachers and lecturers I mean
you know in an ideal world every University course would probably
start with two weeks on learning how to learn right no I think every
incoming student at a university should have of course in that how
learning works and how to manage your time and you know I was in
Florida International University of Miami where they read make a stick
and sat down at the law school and they've completely restructured
their orientation and their management students through the two-year
law school all day around these principles they've gone from typically
fourth or fifth place in the bar exam in Florida as escort to placing
first place if I have out of the last six exams but it's by this
conscious effort is when the students come in let's talk about these
principles and how they work and having experience with it what I just
was having correspondence with someone in Ecuador who was saying I
would like to have a simple classroom experience and my co-author Mart
McDaniel said well they were there learning vocabulary he said well
here's what you could do you could give them half the vocabulary and a
sheet to memorize and you could give them the other half of the
vocabulary flashcards to learn and then have a test and see for
themselves which ones they learn better yeah yeah yeah and now you
know I think that getting students to buy into the process is is super
super important that you're right that there's more difficulty going
to be through this particular style of learning it's going to feel
less immediately gratifying right because you can't straightaway
recall big chunks of concepts and you need to have faith you need to
trust the process it's what we say about when when we talk to power
lifting coaches and stuff like that and some of the athletes aren't
happy with where the lifts are at and they don't feel right and they
said look just trust the process have faith in the fact that you have
out sourced the specific task of programming what is to be done and
when to someone who knows what they're talking about and it is your
job to do what they say or they tell you to do and not vice versa you
shouldn't be questioning it obviously there needs to be a
back-and-forth as you've said when you know you need two regular
points reassess where your where your learning is that and how you're
learning is progressing but stick to the program I think right not
only stick to the program but I think have two goals 1 goal is to
master the content or the skill the other is to learn how to be a
superior learner so that when you get out of whatever this program is
and you find something else you want to do you know you have the
habits that will make you a highly effective at mastering that and
that will make you a competitor out in this crazy world give you a
great advantage for sure I mean it's a principle that's completely as
we've said at the start it's ubiquitous right if you can if you can
learn well then it's the the first domino has fallen on even a single
everything and that goes from as you've you know you've used a wide
range from physical pursuits to intellectual pursuits as specialists
you know it's it's definitely definitely something very crucial I
think you know I I wish that I'd had a better comprehension of time
management when I was at university and of how learning works and of
the strategies that I could have implemented I think had I have had
that it would have made my life a lot easier I by look managed to fall
on at least one of the three key concepts that you have put in here
and I genuinely think that's probably the majority of what's carried
me through carried me through my university degree so you know it's
it's fortunate that I stumbled upon that kind of just through trial
and error but if people can implement all of these I think they'll
they'll have a much easier and much much more comprehensive learning
experience well I hope that some of your listeners tumbled to it and
give it a shot I'm sure that they will so can make it stick make it
stick indeed can you tell the listeners where they can find you online
well there's a website make it stick comm all one word make it stick
yep the book is make it stick the science of successful learning is
published by Harvard University Press it's available on Amazon it's
being translated into 14 different languages so if you have listeners
who will prefer to read it in a language other than English some of
those are already out and others will be out soon so some of your
Italian friends can make them learn English yeah that's it that's it
yeah exactly that's fantastic Peter I'll make sure that links to the
book and to your website we'll be in the show notes below so if anyone
does want to get hold of the book and highly recommend it and they can
grab that through the show notes in the links I'm sure that we're
going to become inundated with some questions and stuff like that so
if we do have something I'll fly them over to you and I'll be able to
answer those on future episodes as well but I really appreciate your
time I think I appreciate yours Chris yeah it's really been fun
sharing with you it's been fantastic I really do think that would have
helped some people in reframe their their approach to learning the we
keep coming back to it but I do think that you can't emphasize it
enough that the capacity your understanding of how to learn is the
fundamental case of what is going to restrict your ability to learn
anything like it's happened and I think it I think it's a really
fundamental task and hopefully as well over the coming years as you
say universities and institutions have started to latch on to the idea
that this is important and I know if you can continue singing that
song then maybe maybe University won't be quite such a daunting and
difficult task for some people in the future as well I think the
window be at your back if you do that's the plan well Peter thank you
very much again and I agree thank you very much yes hey thank you very
much
