application: ovivogae
version: c03
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /sitemap.xml
  script: sitemap.application

- url: /vikarbureau/.*
  script: vikar.application

- url: /tag/.*
  script: vikar.application

- url: /concept
  script: concept.application

- url: /.*
  script: index.application

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: django
  version: latest