-*- coding: utf-8 -*-



* merits :Covey:
[2018-11-01 Thu 11:31]

Merit means "worthiness or excellence." If you receive a certificate
of merit in school, you are being recognized for doing a good job. As
a verb, merit means "deserve." Your certificate might merit a
prominent place on your bulletin board!

You will often hear the phrases merit-based promotion and merit-based
pay, which come up when employees are pushing against a system in
which time on the job––and not job performance––determines when
workers are promoted and how much they are paid. Using the word merit
suggests impartiality and objectivity––such as when you swear off a
prejudiced approach to something and vow to "judge it on its merits."

We call these choices mistakes, and
they are the second thing that merits our deeper thought.
* commitments :Covey:
[2018-11-01 Thu 11:36]

Making a commitment involves dedicating yourself to something, like a
person or a cause. Before you make a commitment, think carefully. A
commitment obligates you to do something.

Some commitments are large, like marriage. When you take a job, you're
making a commitment to show up and do the job well, and your employer
makes a commitment to pay you. There are smaller commitments too. If
you said you'd meet a friend at six, that's a commitment — show up or
your friend will be mad. You also can speak of commitment as a
quality. Staying after school for a study group shows your commitment
to good grades.

At the very heart of our Circle of Influence is our ability to make and keep
commitments and promises.
* awareness :Covey:
[2018-11-01 Thu 11:38]

Awareness is the state of knowing something, such as the awareness
that the sun comes up every morning.

The adjective aware gets turned into a noun when the suffix -ness is
added, so awareness is the state of being aware, or having knowledge
of something. Its roots are Germanic, and come from the Old English
wær meaning "wary, cautious." Awareness can be something you notice,
want to tell others about, or already know. You could "raise
awareness" of a cause, like fighting breast cancer. Yet, your
awareness of the baby sleeping next door might prevent you from having
band practice in the garage. Smart move.

As we make and keep commitments, even small commitments, we
begin to establish an inner integrity that gives us the awareness of
self-control and the courage and strength to accept more of the
responsibility for our own lives.
* accusation :Covey:
[2018-11-01 Thu 11:42]

When you say someone is guilty of doing something wrong you make an
accusation, like your accusation that your brother used your computer
without asking first.

Accusation comes from the verb accuse, which means to charge someone
with a crime. It is important to remember that an accusation comes
about when someone thinks another person has done something wrong or
committed a crime. It doesn't mean, however, that the person is
guilty. There needs to be proof — an investigation or trial, even
admission of guilt — before a conviction, meaning the person really is
guilty.

Look at the weaknesses of others with compassion, not accusation.
* distended :Covey:
[2018-11-05 Mon 16:58]

A soda and pizza binge might make your stomach distend, meaning your
stomach will swell as a result of pressure from the inside.

If you’ve ever eaten too much food it won’t surprise you to learn that
the verb distend traces back to the Latin words dis-, meaning “apart,”
and tendere, meaning “to stretch.” Your stomach will certainly feel
stretched out if you do something — like overeat — that causes it to
distend. The word distend often applies to stomachs — a pregnancy
would also cause a stomach to distend — but it can also refer to
anything that is stretched out as a result of internal pressure.

When I first heard the term brain attic—back in the days of
  firelight and the old crimson hardcover—all I could picture in my
  seven-year-old head was the cover of the black-and-white Shel
  Silverstein book that sat prominently on my bookshelf, with its
  half-smiling, [lopsided] face whose forehead was distended to a
  wrinkled triangle, complete with roof, chimney, and window with open
  shutters.

* vindictive :Covey:
[2018-11-06 Tue 18:23]

It is no fun hanging out with vindictive people, who are forever out
to get back at people they think have hurt them. If you forget to say
hello to them one day in the hall, they will carry a grudge against
you into next week.

Vindictive is often paired with mean, as in "the atmosphere of the
cheerleading squad at my new school was vindictive and mean and I
wanted nothing to do with it." Vindictive rumors show a spirit full of
revenge. Vindictive is from Latin vindicta "revenge." The related
Latin verb vindicare has the very different meaning "to defend or
clear someone from guilt," and this is the source of the English verb
vindicate.

One of Gawker’s editors would say in a documentary about
Peter Thiel’s plot, “It was scarcely believable that something so
cinematically vindictive and conspiratorial and underhanded could
have actually happened.”
* underhanded :Covey:
[2018-11-06 Tue 18:23]

Use the adjective underhanded to describe someone who plays dirty
tricks, like a cheating poker player or a manipulative classmate.

It would be underhanded to spread gossip about your opponent during a
student council election, just as it's underhanded for a business
owner to pay herself more while laying off workers. If it's unfair and
sneaky, it's underhanded — unless you're pitching a softball, in which
case you're simply throwing it from below your shoulder instead of
above.

One of Gawker’s editors would say in a documentary about
Peter Thiel’s plot, “It was scarcely believable that something so
cinematically vindictive and conspiratorial and underhanded could
have actually happened.”
* apocryphal :Covey:
[2018-11-06 Tue 18:25]

Urban legends — stories about phantom hitchhikers, deep-fried rats,
and spider eggs in bubblegum — are classic examples of apocryphal
tales. They're told as if they're true, but no one can ever verify
their origins or authenticity.

Today, any dubious or unverifiable story may be dismissed as
apocryphal. Originally, however, apocryphal was reserved for religious
writings that were not included in the Torah or the New Testament of
the Bible because the divinity of the texts was not certain. These
texts are known as the Apocrypha and are included in the Septuagint (a
Greek version of the Hebrew Bible) and the Vulgate (a Latin Bible
edited in the 4th century).

There is the
apocryphal story about Vanderbilt after he was cheated by two
business partners in Nicaragua and lost his license to operate in the
country.
* undertaken :Covey:
[2018-11-06 Tue 18:26]

When you undertake a task or challenge, you attempt to accomplish it.
If you want to undertake a verbal challenge right now, try saying
“sushi chef” ten times quickly without messing up.

Way back in the 13th century, undertake meant “seize” or “entrap.” Of
course, the meaning has shifted significantly since then, and we hope
you don’t feel entrapped when you decide to undertake a project.
However, undertake does convey a level of commitment and involvement
that’s somewhat stronger than the words try or attempt might suggest.

He sent them a letter, “Gentlemen: You have undertaken to
cheat me.
* wielded :Covey:
[2018-11-06 Tue 18:27]

If you wield a tool or a weapon, you handle it effectively. Picture a
gallant knight wielding a sword or a skillful chef wielding a whisk.

You don't just have to wield something physical; you can also wield or
exert influence or authority. Wield is frequently followed by the word
power. If you were a king, you could wield great power in your kingdom
— exerting your influence over everything from food rations to castle
upkeep. As it is, though, you might just wield power over your pet
goldfish. Note: wield follows the i before e, except after c spelling
rule.

Power is sought so it can be wielded.