-*- coding: utf-8 -*-


* obstinate :satellite:
[2018-12-04 Tue 16:41]

When someone is beyond stubborn, use the word obstinate instead: "You
obstinate old mule! Get out of my way!"

While stubborn may have positive or negative connotations, obstinate
is most definitely negative, because it implies a kind of hard-headed
determination not to change your mind even when it might be best to
rethink your position. "The obstinate Man does not hold Opinions, but
they hold him," wrote Samuel Butler way back in the seventeenth
century. The word still does the trick if you want a put-down for
someone you think is being a pig-headed fool or a stick in the mud.

Kipling and Earhart almost capture the secret to achievement, but we need to qualify
them because they can lead to obstinate persistence either to goals or methods that
aren’t working, and because they ignore or dismiss the emotional component of achieving
goals.
* disengage :satellite:
[2018-12-04 Tue 17:05]

To disengage means to "free or disentangle" yourself or some object
from another person or object. No, it doesn't mean breaking off your
engagement to your beloved — that's "chickening out."

Does your mind wander when someone (your fiancé, for example) talks to
you? Well, your mind can disengage as well, that is, stop paying
attention. Disengage has quite a formal, intellectual ring to it, even
if used about a situation as physical as two armies "disengaging from
combat." It's a technical term, and faintly clinical; the kind of word
frequently used by politicians and diplomats.

Then, about two years ago, my bestie, Josh Wateskin, recognizing that I couldn’t unwind
or disengage from my relentless analyzing of the world – especially the financial world
– recommended that I take up meditation.
* relinquish :satellite:
[2018-12-04 Tue 17:07]

If you relinquish something, you let it go. You relinquish control of
the army when you resign as general. You relinquish your plan to sneak
into town when your parents find out what's going on.

Relinquish is also commonly used to mean physically letting go of
something: The monkey wouldn't relinquish its grasp on the banana.
Relinquish descends from Latin relinquere, from the prefix re- "again"
plus linquere "to leave."

But, I eventually
reframed meditation as a way to relinquish control of my conscious mind so that my more
powerful unconscious mind could take over, and my analysis of the world would improve.
* beckons :satellite:
[2018-12-04 Tue 17:21]

To beckon is to use a physical gesture to call someone over to you.
Universally recognized gestures used to beckon include crooking the
finger or nodding the head to invite someone over.

We get the word beckon from the Old English gebecnian, meaning "to
make a mute sign," which comes from bēacen, meaning "a sign or
beacon." (Remember that "beacon" is a noun while beckon is a verb).
When you beckon to someone, you give them a physical sign to "come
here." Figuratively, an ice cream sundae might beckon you, calling you
away from your diet.

Almost always, the answer is,
“My mission,” which is like a beacon that always beckons.
* beacon :satellite:
[2018-12-04 Tue 17:22]

If your nose is shining like a beacon, I hope you are a reindeer
employed by a jolly fat man from the North Pole.

Beacon comes from an Old English word meaning “sign,” and that's what
actual beacons are for lost ships: signs of having made it to land.
Beacons are often some kind of light, like the bonfires that the
ancient Greeks lit on hillsides to communicate that an army had come
home from overseas. You'll also see beacon used figuratively,
especially in the phrase “beacon of hope.”

Almost always, the answer is,
“My mission,” which is like a beacon that always beckons.
* inherent :satellite:
[2018-12-04 Tue 17:25]

Use the adjective inherent for qualities that are considered permanent
or cannot be separated from an essential character.

We use the adjective inherent to describe attributes that are part of
the essential nature of something. It's different from you being tall,
rather than being a description, it has to be a quality and this
quality is unchangeable. So, for example, if you have never been able
to eat spinach, you have an inherent dislike of it.

It’s especially
hard for me because of my inherent optimism and my unflagging enthusiasm, and because I
always lean into each moment and every encounter expecting magic or miracles, and
because life has rewarded me increasingly with tantalizing offers.
* pursuits :satellite:
[2018-12-04 Tue 18:51]

A pursuit is a chase or a quest for something. When a guard runs after
an escaping jewel thief, she's in pursuit — while the thief may have
stolen the jewels because he was in pursuit of wealth.

Whether it's a police officer in a car chase or a student working
towards a college degree at a university in the tropics, both can be
considered in “hot pursuit.”  Derived from the Anglo-French purseute,
pursuit means the act of pursuing or striving towards goals. In the
late 14th century it implied persecution, but things have changed
since then.

Keep in mind that the time spent on pursuits not related to your mission is time that
could’ve been spent on it – not that all your time, of course, should be devoted to your
mission.
* ambushing :satellite:
[2018-12-04 Tue 18:55]

An ambush is a sneak attack. To ambush your enemy, hide and wait for
him to come near and then pounce on him.

In war or in backyards, an ambush is a great way to surprise someone.
Ambush comes from a Latin word meaning “to place in a wood,” and
hiding in the woods behind a tree is a classic starting point for an
ambush. The actual attack is called an ambush, but ambush is also a
verb, so you can ambush your mom by dropping water balloons on her
head from a tree. Please don’t tell her where you got that idea.

I get endless delight covertly ambushing unsuspecting strangers with
random acts of kindness.
* comprised :satellite:
[2018-12-06 Thu 00:44]

When something comprises other things, it is made up of them or formed
from them. The periodic table comprises 118 elements, because the
whole comprises the parts.

In its traditional use, the word comprise is the opposite of compose:
if A comprises X, Y, and Z, then X, Y, and Z compose A. But because
compose and comprise sound so much alike, people have long confused
the two. So now you often hear things like "The band is comprised of a
guitarist, a bassist, and a hairy drummer," whereas sticklers would
prefer "is composed of" in that sentence. The word is undergoing a
usage shift, making it just as hairy as that drummer!

In order to write a personal mission statement, we must begin at the
very center of our Circle of Influence, that center comprised of our
most basic paradigms, the lens through which we see the world.
* fickle :satellite:
[2018-12-06 Thu 01:28]

People who are fickle change their minds so much you can't rely on
them. If your best friend suddenly decides that she doesn't like you
one week, and then the next week she wants to hang out again, she's
being fickle.

Fickle comes from the Old English word ficol, for deceitful. We
usually use fickle to talk about people, but it can also be used for
abstract things that alternately favor you and abuse you, like the
weather. If you win the lottery and then lose everything else in the
world that's important to you, fate is being fickle.

Your security lies somewhere on the continuum between extreme
insecurity on one end, wherein your life is buffeted by all the
fickle forces that play upon it, and a deep sense of high intrinsic
worth and personal security on the other end.

* accolades :satellite:
[2018-12-11 Tue 21:56]

A knight being honored with the tap of a sword-blade was the earliest
form of accolade. Today, an accolade is more than a way to bestow
knighthood, it is a form of praise or an award.

In the early 17th century, the French accoler meant to "embrace the
neck," which was done as part of a knighthood ceremony. By the 19th
century, accolade came to mean "award." A person who achieves a goal
in research or service may receive an official paper certificate or
trophy, an accolade of achievement, while a performer or speaker might
get an accolade in the form of applause from the audience. Rarely does
either of these types of accolade involve a sword.

Or that we
need certain things (like accolades, nominations,
invitations, etc.)
* hoe :satellite:
[2018-12-13 Thu 18:13]

A hoe is a gardening tool made up of a long handle with a sharp metal
blade at the end, used to stab the ground and loosen it.

Hoe can be a noun or a verb, so you can use your hoe to remove weeds
from a lawn, or you can hoe your garden and make it ready to plant.
The word shares the same root as hew, which is a verb that means "to
strike, chop, or cut." The “oe” seems tricky, but remember that it
never changes, and even if you’re hoeing with three hoes in grass you
hoed yesterday, the hoe stays the same.

2 You may think one is more of a hoe than another who goes
 after a matatu driver/conductor but more likely, you will
 find that even that other one has an assessment criteria
 for all suitors and potential suitors in her life factored
 into her decision making process.
* stoke :satellite:
[2018-12-13 Thu 21:06]

To stoke is to poke a fire and fuel it so that it burns higher. Stoke
can also mean "incite" — a principal's impassive silence in the face
of requests for more tater tots might stoke the flames of student
anger.

When a surfer says, "I am so stoked," it means she is excited — the
fire of enthusiasm is burning hotter. It's interesting to reflect on
how many words in our language have to do with the tending of fires,
an activity that has become much less common in recent human history.

When he was a young boy, he would use the verbal and
physical abuse he suffered at the hands of his father to
stoke the fires in him for achievement.
* seamless :satellite:
[2018-12-16 Sun 13:55]

Something seamless could literally be a piece of clothing without
seams, but it's usually something else that's smooth or unbroken, like
a seamless transition.

Seamless things are connected so well that you can't see what's
holding them together. They're flowing, consistent, and
well-put-together. If an employee leaves, and the replacement does a
great job immediately, that's a seamless transition. In basketball, if
a team goes from offense to defense without missing a beat, that's
seamless play. And that underwear that seems to be made out of one
piece of material? Seamless. And super comfortable.

Containerization makes CI/CD seamless.
* fraught :satellite:
[2018-12-20 Thu 19:44]

Fraught means filled with something — often something bad. Your
Thanksgiving was fraught with awkward moments when your family saw
your blue hair, and it only got worse when you told them you'd quit
law school to join the circus.

Fraught is related to the word freight, and comes from the Middle
English fraughten, meaning "to load with cargo." Think of a cargo ship
loaded up with freight for a journey — it's full of supplies, just
like Thanksgiving was filled with — or fraught with — awkward moments.
Fraught can also describe a situation filled with distress. If
relations between two countries are fraught, they are not getting
along with each other.

They
are actually incredibly difficult and fraught with failure.
* impinge :satellite:
[2018-12-26 Wed 18:09]

Whether you have a habit of standing too close when talking to others
or bringing luggage on a crowded rush-hour subway car, you'll find
people don't like it when you impinge on their personal space.

When you impinge, you intrude on something, whether it’s someone
else’s space, time, or rights. Think of it as moving in on someone’s
territory. The word also can be used in the sense of affecting
something, usually negatively, often by restricting it. For example,
constantly inviting your friend to go shopping and meet you in nice
restaurants might impinge on her desire to save money.

We become
vulnerable to the moods and feelings, the behavior and treatment of
our spouse, or to any external event that may impinge on the
relationship—a new child, in-laws, economic setbacks, social
successes, and so forth.
* resort :satellite:
[2018-12-26 Wed 18:12]

The noun resort means "turning to something or someone else for
assistance." You tried everything to figure out your math homework on
your own, so asking your dad for help was your last resort.

Resort, pronounced "re-ZORT," is also a verb that means "to adopt a
course of action to improve your situation." It's when you use that
last resort: if you can't convince your mom to let you go
rock-climbing, you will resort to begging. Resort also means a fancy
hotel, usually in a very scenic location, or a place you go often —
when your friends didn't know where you were, they checked your
resorts: the gym and the park.

So we resort to sarcasm, cutting
humor, criticism—anything that will keep from exposing the tenderness
within.
* accusations :satellite:
[2018-12-26 Wed 18:14]

When you say someone is guilty of doing something wrong you make an
accusation, like your accusation that your brother used your computer
without asking first.

Accusation comes from the verb accuse, which means to charge someone
with a crime. It is important to remember that an accusation comes
about when someone thinks another person has done something wrong or
committed a crime. It doesn't mean, however, that the person is
guilty. There needs to be proof — an investigation or trial, even
admission of guilt — before a conviction, meaning the person really is
guilty.

Each partner tends to wait on the initiative of the other for
love, only to be disappointed but also confirmed as to the rightness
of the accusations made.
* anxious :satellite:
[2018-12-26 Wed 18:19]

When you are anxious, you are very concerned or worried, but it can
also refer to when you are quite interested in something. You might be
anxious to improve your performance in math class after falling asleep
during a big test.

The word anxious has generally been used to describe when someone is
very concerned about something. In medical terms, to be anxious means
feeling uneasy and worried but not always with a specific focus. On
the other hand, being anxious can also mean that you are very eager.
One meaning is negative and the other is positive!

Since many factors affect
these economic foundations, I become anxious and uneasy, protective
and defensive, about anything that may affect them.