-*- coding: utf-8 -*-



* merits :Covey:
[2018-11-01 Thu 11:31]

Merit means "worthiness or excellence." If you receive a certificate
of merit in school, you are being recognized for doing a good job. As
a verb, merit means "deserve." Your certificate might merit a
prominent place on your bulletin board!

You will often hear the phrases merit-based promotion and merit-based
pay, which come up when employees are pushing against a system in
which time on the job––and not job performance––determines when
workers are promoted and how much they are paid. Using the word merit
suggests impartiality and objectivity––such as when you swear off a
prejudiced approach to something and vow to "judge it on its merits."

We call these choices mistakes, and
they are the second thing that merits our deeper thought.
* commitments :Covey:
[2018-11-01 Thu 11:36]

Making a commitment involves dedicating yourself to something, like a
person or a cause. Before you make a commitment, think carefully. A
commitment obligates you to do something.

Some commitments are large, like marriage. When you take a job, you're
making a commitment to show up and do the job well, and your employer
makes a commitment to pay you. There are smaller commitments too. If
you said you'd meet a friend at six, that's a commitment — show up or
your friend will be mad. You also can speak of commitment as a
quality. Staying after school for a study group shows your commitment
to good grades.

At the very heart of our Circle of Influence is our ability to make and keep
commitments and promises.
* awareness :Covey:
[2018-11-01 Thu 11:38]

Awareness is the state of knowing something, such as the awareness
that the sun comes up every morning.

The adjective aware gets turned into a noun when the suffix -ness is
added, so awareness is the state of being aware, or having knowledge
of something. Its roots are Germanic, and come from the Old English
wær meaning "wary, cautious." Awareness can be something you notice,
want to tell others about, or already know. You could "raise
awareness" of a cause, like fighting breast cancer. Yet, your
awareness of the baby sleeping next door might prevent you from having
band practice in the garage. Smart move.

As we make and keep commitments, even small commitments, we
begin to establish an inner integrity that gives us the awareness of
self-control and the courage and strength to accept more of the
responsibility for our own lives.
* accusation :Covey:
[2018-11-01 Thu 11:42]

When you say someone is guilty of doing something wrong you make an
accusation, like your accusation that your brother used your computer
without asking first.

Accusation comes from the verb accuse, which means to charge someone
with a crime. It is important to remember that an accusation comes
about when someone thinks another person has done something wrong or
committed a crime. It doesn't mean, however, that the person is
guilty. There needs to be proof — an investigation or trial, even
admission of guilt — before a conviction, meaning the person really is
guilty.

Look at the weaknesses of others with compassion, not accusation.