-*- coding: utf-8 -*-

* fidget                                                             :Ferris:
[2018-07-07 Sat 13:23]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       1062d00d-912c-4d28-bf3c-409cf2cb83d1
   :END:

 fidget

*** --->
  ерзать

  noun
   1. непоседа (fidget, gadabout)
   2. беспокойство (concern, anxiety, worry, trouble, disturbance, fidget)
   3. егоза (fidget)
   4. вьюн (loach, fidget)
   5. беспокойное состояние (fidget)
   6. беспокойный человек (worrier, fidget, hellion, fussbudget, fuss-pot)
   7. суетливый человек (fidget, fussbudget, fuss-pot)

  verb
   1. ерзать (fidget, wiggle, fidget about, shuffle, wiggle-waggle)
   2. нервировать (irritate, unnerve, spook, fidget, harrow)
   3. беспокойно двигаться (fidget)
   4. быть в волнении (fidget)

  DEFINITION

  noun
   1. a quick, small movement, typically a repeated one, caused by nervousness or impatience.
      "he disturbed other people with convulsive fidgets"

  verb
   1. make small movements, especially of the hands and feet, through nervousness or impatience.
      "the audience had begun to fidget on their chairs"


  To fidget is to make little movements with your hands and feet. Even
  if you're nervous during your job interview, try not to fidget.

  The word fidget is related to the Old Norse fikja, meaning "move
  briskly, be restless or eager." If you are feeling impatient or
  anxious you might fidget in your seat or fidget with a pen in your
  hands. A person who fidgets a lot can be referred to as a fidget and
  so can that quick anxious movement itself.

  In the strictest sense, you shouldn’t be trying to do more in each day,
  trying to fill every second with a work fidget of some type.

* fuss :Ferris:
[2018-07-07 Sat 13:32]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       7ee99bda-73fe-4f51-991d-456413147b75
   :END:

 fuss

*** --->
  суетиться

  verb
   1. суетиться (fuss, bustle, hustle, bother, scurry, bustle about)
   2. ссориться (quarrel, brawl, bicker, fall out, fuss, dispute)
   3. надоедать с пустяками (fuss)
   4. хороводиться (fuss)
   5. приставать с пустяками (fuss)
   6. объясняться (fuss)
   7. волноваться из-за пустяков (fuss, fuss about)

  noun
   1. суматоха (turmoil, bustle, ado, flurry, clutter, fuss)
   2. нервное состояние (nerves, jitters, willies, twitch, fuss)
   3. возбужденное состояние (fuss)
   4. суета из-за пустяков (fuss)
   5. беспокойство из-за пустяков (fuss)

  DEFINITION

  noun
   1. a display of unnecessary or excessive excitement, activity, or interest.
      "I don't know what all the fuss is about"

  verb
   1. show unnecessary or excessive concern about something.
      "she's always fussing about her food"


  If you are making a fuss, settle down! A fuss is a state of
  excitement, and it's usually about something not worth worrying or
  "fussing" about.

  Most fusses are types of commotion. If someone makes a fuss, they're
  overexcited and in a tizzy over something, like someone who can't stop
  asking questions. Another fuss is angrier: you might say "What's the
  fuss?" if you hear two people yelling at each other. A fuss is also
  any kind of hubbub or whirlwind of activity, like a huge crowd
  swarming toward a sale. Parents tend to fuss over their children.
  Someone who fusses is worrying too much.

  The options are almost limitless for creating “busyness”: You could
  call a few hundred unqualified sales leads, reorganize your Outlook
  contacts, walk across the office to request documents you don’t really
  need, or fuss with your BlackBerry for a few hours when you should be
  prioritizing.

* fart                                                               :Ferris:
[2018-07-07 Sat 13:40]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       93385a90-b063-4747-b358-432ee979ca96
   :END:

 fart

*** --->
  пердеть

  verb
   1. пердеть (fart, bullshit)
   2. пукать (fart)

  noun
   1. бздун (fart, farter)

  DEFINITION

  noun
   1. an emission of gas from the anus.
      "We know also that farts are warm (not hot), so I'll add that: a fart is warm wind emitted from the anus."

  verb
   1. emit gas from the anus.
      "The proletarians were said to have bodies that were not sublimated, which farted and belched and emitted all sorts of cacophonous noises."


  We don’t all like to admit it, but we all fart. That is, we all pass
  smelly gas out of our anus.

  Kids — and a few adults too — find farting funny. If someone lets out
  a long fart during church or class, someone is bound to laugh.
  However, the teacher probably won’t laugh, and the culprit could be in
  big trouble. Be careful about accusing others of farting, because one
  of the oldest rules of the schoolyard is “He who smelt it, dealt it.”
  A less slangy word for fart is flatulence.

  This is also true for the person who checks e-mail 30 times per day and
  develops an elaborate system of folder rules and sophisticated techniques
  for ensuring that each of those 30 brain farts moves as quickly as
  possible.

* truism                                                             :Ferris:
[2018-07-07 Sat 13:41]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       f6a93fa0-59d6-4e5f-abd3-fea9613d62e2
   :END:

 truism

*** --->
  трюизм

  noun
   1. трюизм (truism)
   2. прописная истина (truism, common truth)

  DEFINITION

  noun
   1. a statement that is obviously true and says nothing new or interesting.
      "the truism that you get what you pay for"


  Here's a truism for you: Only people who look up words they don't know
  can expand their vocabularies. Did you find that statement obvious,
  boring, and saying nothing new or interesting? That's the perfect
  description of a truism.

  Sometimes truisms can be mistaken for factual statements. In fact,
  despite their seeming obviousness, they are usually opinions. Many
  people who look up words in the dictionary don't improve their
  vocabularies, as much as they'd like to. Another truism: You get what
  you pay for. Well, a lot of the time, sure, but not always. That's why
  the word bargain was invented.

  Here are two truisms to keep in mind:

* futility                                                           :Ferris:
[2018-07-07 Sat 13:44]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       39dfdba9-c811-44ba-a14b-18825254aab6
   :END:

 futility

*** --->
  бесполезность

  noun
   1. тщетность (futility, otioseness)
   2. бесполезность (uselessness, futility, disutility, inutility, needlessness, vainness)
   3. бесцельность (aimlessness, pointlessness, futility, idleness)
   4. поверхностность (superficiality, perfunctoriness, futility)
   5. несерьезность (flippancy, futility, facetiousness)

  DEFINITION

  noun
   1. pointlessness or uselessness.
      "the horror and futility of war"


  When you can’t see the point in even trying, that’s the feeling of
  futility, the sense that no matter how much you work at it, nothing
  good will happen, so you might as well give up.

  What’s the point? That’s the question asked by anyone who senses the
  futility of something. The futility of war makes soldiers put down
  their weapons, and your father’s strict rules makes any protest an act
  of futility. The root word is the Latin futilis, which literally means
  “leaky.” Imagine pouring lemonade into a cup that has no bottom. No
  matter how long you pour, you’ll never get a sip because of that leaky
  cup. Ah, the futility!

  Pareto and His Garden: 80/20 and Freedom from Futility

* wily :Ferris:
[2018-07-07 Sat 13:47]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       f09a19bb-6235-4380-902e-039a54d625cc
   :END:

 wily

*** --->
  коварный

  adjective
   1. хитрый (cunning, tricky, sly, artful, crafty, wily)
   2. коварный (insidious, treacherous, cunning, crafty, wily, scheming)
   3. лукавый (sly, wily, arch, quizzical, gamine, pawky)

  DEFINITION

  adjective
   1. skilled at gaining an advantage, especially deceitfully.
      "his wily opponents"


  Did you fall for that wily door to door salesman's pitch? He must be
  very slick and tricky to have convinced you to buy a set of new tires,
  considering you don't have a car.

  How can you remember the meaning of the adjective wily? Just think
  about the old Warner Brothers Looney Tunes cartoons. Their aptly named
  cartoon character, Wile E. Coyote, got his name from a clever play on
  words. Wile E. is supposed to be cunning, crafty, and clever — in
  other words, wily. Wile E. is all those things, but unfortunately he
  was usually bested by that pesky roadrunner anyway. Meep. Meep.

  Vilfredo Pareto was a wily and controversial economist-cum-sociologist
  who lived from 1848 to 1923.

* seminal :Ferris:
[2018-07-07 Sat 13:48]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-08-20 Mon>
   :PROPERTIES:
   :ID:       b06bf73e-050d-4471-a61f-564d3a6c620e
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-08-16 Thu 11:06]
   :END:

 seminal

*** --->
  плодотворный

  adjective
   1. семенной (seminal, spermatic)
   2. плодотворный (fruitful, productive, seminal, fructuous)
   3. зародышевый (embryonic, germinal, embryo, fetal, germinative,
      seminal)
   4. конструктивный (constructive, constructional, seminal,
      functional, constitutive, architectonic)
   5. сперматический (spermatic, seminal)

  DEFINITION

  adjective
   1. (of a work, event, moment, or figure) strongly influencing later
      developments. "his seminal work on chaos theory"
   2. of, relating to, or denoting semen. "The seminal plasma of
      mammals is a complex fluid, which serves as a carrier for the
      spermatozoa in their journey from the male testes to their
      target, the female uterus."


  Call something seminal when it's so original, so groundbreaking and
  awesome that it will influence everything that comes after it.
  Picasso produced more than a few seminal works of art, for example.

  Technically, seminal means something related to semen or seeds. But
  these days people more often use the word to describe something that
  plants the seed for creative growth. An innovative piece of music or
  literature, a fresh new idea, or an invention that changes
  everything could each be called seminal. Synonyms include critical,
  fundamental, original, and primary.

  His seminal work, Cours d’economie politique, included a then
  little-explored “law” of income distribution that would later bear
  his name: “Pareto’s Law” or the “Pareto Distribution,” in the last
  decade also popularly called the “80/20 Principle.”

* skewed                                                             :Ferris:
[2018-07-08 Sun 07:10]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       32fcf4f6-dd86-41ae-9c2c-36258d62f635
   :END:

 skewed

*** --->
  перекос

  verb
   1. искажать (distort, misrepresent, deform, twist, corrupt, skew)
   2. уклоняться (dodge, skew, avoid, shrink, evade, deviate)
   3. отклоняться (deviate, digress, deflect, depart, diverge, wander)
   4. сворачивать в сторону (swerve, skew)
   5. перекашивать (distort, skew)
   6. располагать наискось (skew)
   7. сдвигать (shift, dislocate, skew)
   8. смещать (displace, remove, depose, dislodge, dislocate, translocate)
   9. отклонять (reject, dismiss, deflect, divert, turn down, turn away)
  10. смотреть искоса (squint, leer, skew)
  11. косить глазами (squint, skew)
  12. извращать (pervert, distort, skew, warp, sophisticate)

  DEFINITION

  verb
   1. suddenly change direction or position.
      "the car had skewed across the track"


  Something skewed is slanted or off-center in some way. A picture frame
  or viewpoint can be skewed.

  This is a word, like so many, that can apply to physical things or
  ideas. A painting on the wall is skewed if it's leaning to one side.
  Also, opinions are often skewed: this is another way of saying someone
  is biased. People often accuse news reports of being skewed toward one
  political viewpoint. A movie could be skewed toward one character more
  than the other. When you think of skewed, think of leaning and
  slanting of all sorts.

  The list is infinitely long and diverse, and the ratio is often skewed
  even more severely: 90/10, 95/5, and 99/1 are not uncommon, but the
  minimum ratio to seek is 80/20.
* mere :Ferris:
[2018-07-08 Sun 07:24]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       d5e38ec8-d6ed-436f-96e1-e9768b15ad6b
   :END:

 mere
*** --->
  всего лишь

  adjective
   1. простой (plain, simple, ordinary, elementary, idle, mere)
   2. сущий (mere, sheer, very, arrant, regular, rank)
   3. не более чем (mere)
   4. чистый (clean, pure, net, clear, unadulterated, mere)
   5. явный (explicit, obvious, apparent, sheer, evident, mere)

  noun
   1. озеро (lake, loch, lough, mere, flood)
   2. пруд (pond, pool, impoundment, mere, laguna, stank)
   3. водное пространство (mere)

  DEFINITION

  adjective
   1. that is solely or no more or better than what is specified.
      "it happened a mere decade ago"

  noun
   1. a lake, pond, or arm of the sea.
      "Cecilia's surname Dela-mere puns ingeniously: over the sea, but also over the mere or lake."


  Mere means pure and simple, nothing more and nothing less. If the mere
  mention of someone's name makes you happy, then just hearing his name
  — and that alone — is enough to make you smile.

  Mere can have a little irony attached. If you introduce yourself as "a
  mere student," when you’re announcing your astounding invention,
  you're contrasting your lowly status with the enormity of your
  invention. This kind of mere comes from the Latin for "undiluted."
  Mere has a homograph — a completely different word that's spelled the
  same — and this mere means a lake or a pond. It’s related to the Dutch
  word meer — there’s lots of water in Holland.

  Out of more than 120 wholesale customers, a mere 5 were bringing in 95%
  of the revenue.

* cajoling :Ferris:
[2018-07-08 Sun 07:25]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       ddd23fc4-3dbd-41ab-baa4-882940efcac4
   :END:

 cajoling

*** --->
  уговаривать

  verb
   1. задобрить (cajole, coax, wheedle)
   2. умасливать (cajole, butter up, soft-soap)
   3. обхаживать (cajole, nurse, wheedle)
   4. льстить (flatter, cajole, adulate, toady, compliment, please)

  DEFINITION

  verb
   1. persuade someone to do something by sustained coaxing or flattery.
      "he hoped to cajole her into selling the house"


  To cajole someone is to persuade them by using insincere compliments
  or promises. If you say "Please, pretty-please, I'll be your best
  friend," when asking for a stick of gum, you are cajoling the gum
  holder.

  The origin of this word is probably a blend of two French words
  meaning "to chatter like a jaybird" and "to lure into a cage." When
  you cajole that guy into lending you some money, picture him as the
  bird going into the cage. In fact, the word cajole may be associated
  with another French word meaning "to put in jail."

  I was spending 98% of my time chasing the remainder, as the
  aforementioned 5 ordered regularly without any follow-up calls,
  persuasion, or cajoling.

* plucking :Ferris:
[2018-07-08 Sun 12:40]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       e036287d-2311-4269-b86f-0fd1626e9e78
   :END:

 plucking

*** --->
  выщипывание

  noun
   1. выщипывание (plucking)
   2. ощипывание (plucking, picking, pulling)
   3. сбор ягод (plucking)
   4. провал на экзамене (plowing, plucking, ploughing)
   5. ледниковое выпахивание (plucking)

  DEFINITION

  verb
   1. take hold of (something) and quickly remove it from its place; pick.
      "she plucked a blade of grass"
   2. quickly or suddenly remove someone from a dangerous or unpleasant situation.
      "the baby was plucked from a grim foster home"
   3. sound (a musical instrument or its strings) with one's finger or a plectrum.
      "I sat with the lute in my lap, trying to reach for forgotten notes as my fingers plucked the strings."


  To pluck is to pick or pull a single item out of many, like a flower
  or a hair. As a noun, pluck is energy or enthusiasm, even when things
  are looking grim.

  Don't pluck only the best cherries off the tree: that's
  cherry-picking! Before you cook a goose, you need to pluck its
  feathers. If it looks like your goose is cooked, however, then show
  some pluck, and figure out a way to save yourself. Some characters who
  are famous for showing pluck include the Artful Dodger, Little Orphan
  Annie, and Benji the dog. They all kept their chins up and kept on
  trying, even when things looked really dark.

  When a character from Shakespeare calls the world his oyster, that's
  his boastful way of saying that all the riches of the world are his
  for the taking, like plucking a pearl from an oyster shell.

* servitude :Ferris:
[2018-07-16 Mon 10:29]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       92c5e35c-b550-4cf3-b59a-14296cb8876a
   :END:

 servitude

*** --->
  сервитут

  noun
   1. рабство (slavery, bondage, servitude, enslavement, captivity, serfdom)
   2. порабощение (enslavement, servitude, enthrallment, enthralment)
   3. отбытие наказания (servitude)

  DEFINITION

  noun
   1. the state of being a slave or completely subject to someone more powerful.
      "Her status as slave condemns her to a life of servitude , with little or no control over her future."


  If you're free-spirited you won't enjoy servitude, mainly because
  servitude means you have to answer to a master, like a servant does.

  Slavery, a brutal form of servitude, existed in the United States
  until the ratification of the Thirteenth Amendment in 1865. Before
  this, thousands upon thousands of African Americans were forced into
  servitude, where they were forced to perform labor for their masters.
  A key to remembering the meaning of servitude is the fact that it
  resembles servant.

  If your friend rear-ends you but doesn't have insurance, let him pay
  for the damage in servitude. Make him your personal assistant for a
  month!

  and 5:00 P.M., and since you’re trapped in the office for that period
  of servitude, you are compelled to create activities to fill that time.

* compel                                                             :Ferris:
[2018-07-16 Mon 10:30]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       86722656-8864-4bed-9bc9-8c365fe1bfa6
   :END:

 compel

*** --->
  принуждать

  verb
   1. принуждать (compel, force, coerce, enforce, oblige, constrain)
   2. заставлять (force, make, cause, get, compel, lead)
   3. вынуждать (force, compel, necessitate, drive, constrain, enforce)
   4. добиваться (achieve, seek, get, obtain, press for, compel)
   5. подчинять (subordinate, submit, subject, subdue, subjugate, compel)

  DEFINITION

  verb
   1. force or oblige (someone) to do something.
      "a sense of duty compelled Harry to answer her questions"


  Compel means to force or drive someone to do something. Even if you
  don't like toast, when you visit the toast-eating natives of
  Shrintakook Island, you'll be compelled to eat it, or they will not
  trust you.

  You don't want to be compelled to go to a classical music concert if
  you'd rather listen to rap. School officials might be upset if a
  winter storm compels them to cancel classes, but you'd be okay with
  that. A compelling mystery forces you to pay attention because you
  want to find out "whodunit."

  and 5:00 P.M., and since you’re trapped in the office for that period
  of servitude, you are compelled to create activities to fill that time.

* imminent :Ferris:
[2018-07-16 Mon 10:38]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-08-20 Mon>
   :PROPERTIES:
   :ID:       524ef909-0c5a-4779-be08-9a131bf34383
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-08-16 Thu 11:08]
   :END:

 imminent

*** --->
  неизбежный

  adjective
   1. надвигающийся (oncoming, imminent, impendent)
   2. угрожающий (threatening, menacing, ominous, rampant, critical, imminent)
   3. близкий (close, near, intimate, familiar, nearby, imminent)
   4. грозящий (threatening, impending, imminent, impendent, fulminatory)
   5. нависший (imminent, beetling, threatening, beetle, low-browed)

  DEFINITION

  adjective
   1. about to happen.
      "they were in imminent danger of being swept away"
   2. overhanging.


  Something that is imminent is just about to happen: if you light a
  firecracker and then stick it down your pants, a very bad situation is
  imminent.

  Imminent is from Latin imminere "to overhang," and to say that
  something is imminent is to say that it is hanging over you and about
  to fall, in a metaphorical way. If you take your mom’s car and drive
  it into the mailbox, getting grounded is imminent. You don’t want that
  hanging over your head!

  It is the magic of the imminent deadline.

* bustle                                                             :Ferris:
[2018-07-16 Mon 10:45]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       88782eca-bd5e-4ae4-9388-c2dba52f3dc4
   :END:

 bustle

*** --->
  суматоха

  noun
   1. суета (vanity, bustling, bustle, rush, scurry, stir)
   2. суматоха (turmoil, bustle, ado, flurry, clutter, tumult)
   3. турнюр (bustle, pad)

  verb
   1. суетиться (fuss, bustle, hustle, bother, scurry, bustle about)
   2. юлить (wriggle, bustle)
   3. тыкаться (knock, bustle)
   4. спешить (haste, hasten, push on, be in a hurry, speed, bustle)
   5. торопиться (rush, hurry, hasten, hurry up, haste, bustle)
   6. торопить (rush, hurry, hasten, hurry up, haste, bustle)

  DEFINITION

  noun
   1. excited activity and movement.
      "all the noise and the traffic and the bustle"
   2. a pad or frame worn under a skirt and puffing it out behind.
      "This staged cross-dressing was a great shock to audiences used to only seeing women on stage when they were hidden behind voluminous bustles , hoops and frills."

  verb
   1. move in an energetic or noisy manner.
      "people clutching clipboards bustled about"


  A flurry of activity and commotion is often referred to as bustle. If
  you want to see true bustle in action, just walk through Times Square
  in New York during lunch hour.

  If it's busy, energetic or moving about at a rapid pace, then it's
  bustling. Word historians think bustle might stem from an Old Norse
  word meaning "to prepare." However, it's probably easier to remember
  bustle by the synonym it's often used with — hustle, as in "the hustle
  and bustle of a big city."

  Love of bustle is not industry.

* plop                                                               :Ferris:
[2018-07-16 Mon 17:00]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-08-20 Mon>
   :PROPERTIES:
   :ID:       4300255f-425c-4e89-bb20-44fe077bd077
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-08-16 Thu 11:09]
   :END:

 plop

*** --->
  шлеп

  verb
   1. хлопнуть (pop, plop, bang, swat)
   2. хлопнуться (plop)
   3. шлепаться (plop, flop, splash, squash, thud, plunk)
   4. бултыхнуться (plop, splash)
   5. бултыхнуть (plop)

  adverb
   1. без всплеска (plop)
   2. внезапно (suddenly, abruptly, all of a sudden, all at once, pop, plop)

  noun
   1. падение в воду (plop)

  DEFINITION

  noun
   1. a short sound as of a small, solid object dropping into water
      without a splash. "The fly lands with a soft plop hardly
      breaking the water surface."

  verb
   1. fall or cause to fall with a plop. "the stone plopped into the
      pond"


  To plop is to drop something (or yourself) with a short sound. The
  sound itself is also a plop — like something landing in water
  without much of a splash.

  The sound of a plop is abrupt and hollow — you could also call it a
  plunk or a or a plonk. You might plop an ice cube in your glass of
  water, or watch a flock of bird plop themselves on the surface of a
  pond. Plop is imitative or onomatopoeic (it sounds like its
  meaning), and it first appeared in the 1820s after the brief
  popularity of the alternative word plap.

  Between my tenth and twelfth cupcakes, I plopped down on the couch
  to revel in the sugar high until the clock struck midnight and sent
  me back to my adultsville Sunday–Friday diet.

* guise :Ferris:
[2018-07-07 Sat 13:29]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-08-20 Mon>
   :PROPERTIES:
   :ID:       94ba8e8f-32e0-45e8-bb0b-d460b1324bc0
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-08-16 Thu 11:05]
   :END:

 guise

*** --->
    [gaɪz]
  личина

  noun
   1. облик (guise, image, shape, figure, physiognomy, person)
   2. личина (guise, mask, disguise, cloak, cover, likeness)
   3. маска (mask, guise, disguise, cover, visor, cloak)
   4. вид (view, kind, form, look, appearance, guise)
   5. предлог (pretext, excuse, preposition, guise, plea, cloak)
   6. наружность (appearance, outside, exterior, mien, semblance, guise)
   7. одеяние (apparel, garment, robe, dress, garb, guise)
   8. наряд (attire, garb, finery, detail, livery, guise)
   9. манера (manner, style, way, fashion, mannerism, guise)

  DEFINITION

  noun
   1. an external form, appearance, or manner of presentation,
      typically concealing the true nature of something. "he visited
      in the guise of an inspector"


  The noun guise refers to an outward appearance that conceals the
  true nature of someone or something. Your classmate might chat with
  you under the guise of friendship, but you know she's really just
  looking for juicy gossip.

  No doubt you’ve noticed the similarity between guise and disguise.
  Both involve the art of deception: it’s the methods that differ.
  Guise is about trying on new attitudes and mannerisms, such as
  speaking and acting in the guise of a native in a place where you
  are actually a tourist. Disguise involves hiding your real identity,
  disappearing in the new role.

  Being busy is most often used as a guise for avoiding the few
  critically important but uncomfortable actions.

* disguise :Ferris:
[2018-07-16 Mon 17:06]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       45d43161-b7c5-4802-ab72-69491b0f58f5
   :END:

 disguise

*** --->
    [dɪs↗gaɪz]
  маскировать

  noun
   1. маскировка (disguise, camouflage, concealment, disguising, cloaking, screening)
   2. переодевание (disguise)
   3. сокрытие (concealment, hiding, cloaking, disguise, secretion)
   4. обман (deception, deceit, fraud, trick, hype, disguise)
   5. маска (mask, guise, disguise, cover, visor, cloak)
   6. обманчивая внешность (disguise)
   7. личина (guise, mask, disguise, cloak, cover, likeness)

  verb
   1. скрывать (hide, conceal, mask, cover, keep, disguise)
   2. маскировать (mask, camouflage, disguise, conceal, cloak, veil)
   3. переодевать (disguise)
   4. делать неузнаваемым (disguise, defeature)

  DEFINITION

  noun
   1. a means of altering one's appearance or concealing one's identity.
      "his bizarre disguise drew stares from fellow shoppers"

  verb
   1. give (someone or oneself) a different appearance in order to conceal one's identity.
      "he disguised himself as a girl"


  A disguise is something you put on so no one recognizes you. It also
  can be used as a verb. You can disguise yourself with a wig and
  mustache; that's a great disguise.

  Disguise can be used anytime you're talking about concealing or hiding
  something. Most of the time we think of a disguise as something you
  wear, but you can also disguise your feelings. Criminals might
  disguise their intentions. You can also use the word to describe
  something that seems to be one thing, but turns out to be another. You
  missed the plane, but then the plane crashed. That's a blessing in
  disguise.

  Dedication is often just meaningless work in disguise.

* sane :Ferris:
[2018-07-16 Mon 17:12]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       f58f68be-9547-4888-a8f9-1ceb49dc430e
   :END:

 sane

*** --->
  в своем уме

  adjective
   1. здравомыслящий (sane, sensible, sober, clear-headed, judicious, sagacious)
   2. нормальный (normal, standard, regular, sane, ordinary, natural)
   3. разумный (reasonable, intelligent, sensible, rational, sane, understanding)
   4. в своем уме (sane)
   5. здравый (robust, sound, sensible, sane, sober, wholesome)

  DEFINITION

  adjective
   1. (of a person) of sound mind; not mad or mentally ill.
      "hard work kept me sane"


  A sane person doesn't have any screws loose — in other words, they're
  free of mental illness and in a reasonable state of mind.

  You probably know that the word insane means crazy. Well, the opposite
  of insane is sane — or not crazy. A sane person is of sound mind and
  is mentally healthy. Sane people have good judgment, are reasonable,
  and can tell the difference between what's real and imagined. Whenever
  someone commits a crime or does something totally outlandish, people
  usually wonder if they're sane or not.

  Used even once per month, this question alone can keep you sane and on
  track.

* ditto                                                              :Ferris:
[2018-07-16 Mon 17:21]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       47225817-4e02-4da1-adaf-5c5f5a52e831
   :END:

 ditto

*** --->
  то же самое

  noun
   1. то же (same, ditto)
   2. такой же (ditto)
   3. столько же (ditto)
   4. точная копия (replica, carbon copy, dead ringer, ringer, counterpart, ditto)
   5. костюм из одного материала (suit of dittos, ditto)

  adverb
   1. таким же образом (the same way, same, so, just the same, do, ditto)

  verb
   1. делать повторения (ditto)

  DEFINITION

  noun
   1. used in accounts and lists to indicate that an item is repeated (often indicated by a ditto mark under the word or figure to be repeated).
   2. a similar thing; a duplicate.


  A ditto looks like a quotation mark — " — and it's used as you go down
  a list to indicate you're repeating whatever is above.

  If your jellies and jams all cost $2.00, you can write $2.00 just once
  with the first item on your price list and " in the price column next
  to each item listed below. You can also use the word ditto informally
  to describe repetition: "I can't believe you wore those shoes. Ditto
  that hat." You may recognize Ditto as the aptly named son of the comic
  strip characters Hi and Lois; he’s the twin brother of Dot.

  Ditto.

* uncanny :Ferris:
[2018-07-17 Tue 20:42]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-08-20 Mon>
   :PROPERTIES:
   :ID:       6daa912c-749c-4e69-8f74-609d4fffcdfa
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-08-16 Thu 11:09]
   :END:

 uncanny

*** --->
  сверхъестественный

  adjective
   1. сверхъестественный (supernatural, uncanny, weird, preternatural,
      eerie, miraculous)
   2. жуткий (eerie, spooky, scary, uncanny, eery, scarey)

  DEFINITION

  adjective
   1. strange or mysterious, especially in an unsettling way.
      "an uncanny feeling that she was being watched"


  If something is uncanny, it is so mysterious, strange, or unfamiliar
  that it seems supernatural. If you hear strange music echoing
  through your attic, you might refer to it as positively uncanny.

  You can also use uncanny to refer to something that is so remarkable
  that it is beyond what is natural: as in "uncanny abilities." This
  adjective was formed in English from the prefix un- "not" and canny
  "fortunate, safe." The current meaning of English canny is "careful
  and clever, especially in handling money."

  FROM THIS POINT forward, I’m going to propose that you develop an
  uncanny ability to be selectively ignorant.

* lieu :Ferris:
[2018-07-17 Tue 20:45]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       d1c69c0f-5d17-4220-831d-1c8b8d35a24d
   :END:

 lieu

*** --->
  место

  noun
   1. место (place, site, space, spot, room, lieu)

  DEFINITION

  noun
   1. instead.
      "the company issued additional shares to shareholders in lieu of a cash dividend"


  To be in lieu of something is to replace it or substitute for it. A
  restaurant that's run out of clams might serve French onion soup in
  lieu of chowder.

  The word lieu originally comes from the Latin locus, meaning "place,"
  and its meaning has stayed true to its origins ever since. Though it
  does have a standalone definition, "the position or function formerly
  held by another," this noun is most commonly encountered in the phrase
  "in lieu of," which means, basically, "instead of."

  It gives you something new to ask the rest of the population in lieu
  of small talk: “Tell me, what’s new in the world?”

* crib :Ferris:
[2018-07-17 Tue 20:46]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       beec494d-695c-4bc5-b64d-2b52dd7d523b
   :END:

 crib

*** --->
  детская кроватка

  noun
   1. детская кроватка (cot, crib)
   2. ясли (nursery, manger, crib)
   3. шпаргалка (crib, cabbage, trot, cab, pony)
   4. плагиат (plagiarism, crib, plagiary, rip-off)
   5. подстрочник (pony, crib, gloss, trot)
   6. хижина (hut, cabin, shack, cottage, crib, cot)
   7. дом (house, home, dwelling, door, premises, crib)
   8. кормушка (feeder, trough, manger, crib, rack, pork)
   9. стойло (stall, stable, box, bay, crib)
  10. небольшая комната (crib)
  11. квартира (apartment, flat, room, quarter, condominium, crib)
  12. магазин (store, shop, magazine, trade, depot, crib)
  13. верша для ловли лососей (crib)
  14. сруб крепи (crib)
  15. костровая крепь (chock, cog, crib)
  16. ларь (chest, bin, pocket, crib)
  17. закром (bin, hutch, crib)

  verb
   1. совершать плагиат (crib, lift)
   2. запирать (lock, shut, lock up, pawl, latch, crib)
   3. заключать в тесное помещение (crib)
   4. списать (copy, crib)
   5. красть (steal, swipe, thieve, glom, snitch, crib)
   6. воровать (steal, pilfer, thieve, mooch, plunder, crib)
   7. списывать тайком (crib)
   8. пользоваться шпаргалкой (cab, cabbage, crib)

  DEFINITION

  noun
   1. a young child's bed with barred or latticed sides.
      "Normally, the hospital beds for infants are big cribs , but the sides come down so you can examine the baby and take care of them."
   2. a translation of a text for use by students, especially in a surreptitious way.
      "an English crib of Caesar's Gallic Wars"
   3. an apartment or house.
      "Mary lives wiv him in a council crib ."
   4. a heavy timber framework used in foundations for a building or to line a mine shaft.
      "On the interior, the building was further divided into two cribs made of slats with an open work space in the middle of the building."

  verb
   1. copy (another person's work) illicitly or without acknowledgment.
      "he was doing an exam and didn't want anybody to crib the answers from him"
   2. restrain.
      "he had been so cabined, cribbed, and confined by office"


  A crib is a bed with high sides that babies sleep in. To crib is to
  cheat, like copying off someone else during an exam. How babyish!

  A crib is a small, cozy bed that has high sides known as slats. The
  slats keep the baby from falling out. To crib is different — it means
  to cheat, especially by copying or stealing information. If you stole
  an answer key to a test, you cribbed it. If you friend told you the
  answers to some homework, you cribbed the answers. Cribbing is
  dishonest.

  Using my crib notes approach to world affairs, I also retain more than
  someone who loses the forest for the trees in a sea of extraneous details.

* eschew                                                             :Ferris:
[2018-07-18 Wed 20:10]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       2fcf006a-d43f-4818-b5d2-e3982af2eec7
   :END:

 eschew

*** --->
    [ɪs↗tʃʊ:]
  сторониться

  verb
   1. избегать (avoid, shun, escape, evade, steer clear of, eschew)
   2. сторониться (eschew, avoid, steer clear of)
   3. воздерживаться от (eschew, keep from)
   4. остерегаться (beware, shun, watch out, guard, keep away, eschew)

  DEFINITION

  verb
   1. deliberately avoid using; abstain from.
      "he appealed to the crowd to eschew violence"


  If you eschew something, you deliberately avoid it. If you live the
  bohemian life in the city, then most likely you eschew the suburbs.

  Eschew comes from a word meaning dread, or shun. So to eschew
  something isn’t simply to avoid it, the way you would avoid walking in
  a puddle––it's stronger than that. You eschew things that you find
  morally or aesthetically wrong, or that you have chosen to find wrong.
  A dieter might eschew a chocolate sundae, not because he doesn’t like
  it, but because he’s afraid of what it will do to his waistline.

  Eschew what’s gone before and build your own lightweight distro

* palpitations :Ferris:
[2018-07-18 Wed 20:31]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       5987682d-261a-497f-94db-9df2f074a101
   :END:

 palpitations

*** --->
  учащенное сердцебиение

  noun
   1. сердцебиение (palpitation, heartthrob, heartquake)
   2. трепет (trembling, thrill, awe, trepidation, tremor, flutter)
   3. сильное сердцебиение (palpitation)
   4. пальпитация (palpitation)
   5. трепетание (flutter, fibrillation, palpitation, flicker, throbbing, oscillation)
   6. пульсация (pulsation, ripple, pulse, throbbing, throb, beat)
   7. дрожь (shiver, trembling, tremble, shake, tremor, shudder)

  DEFINITION

  noun
   1. a noticeably rapid, strong, or irregular heartbeat due to agitation, exertion, or illness.
      "Most of the time, palpitations and irregular heartbeats are harmless."


  A palpitation is when your heart beats quickly and irregularly. It's
  also any kind of shaky, quivery motion.

  You know how your heart goes a mile a minute when you're excited? Then
  you've felt palpitations: that's when your heart beats fast and out of
  rhythm. Palpitations can be nothing serious or they could be signs of
  heart trouble. Also, a palpitation is any type of shaky motion, such
  as quivering or trembling. People with Parkinson's disorder have a lot
  of palpitations, and we all have palpitations — such as shaky hands —
  when we're nervous.

  If this gives you heart palpitations, speak with your immediate
  supervisor and propose to trial the approach for one to three days.

* meander :Ferris:
[2018-07-18 Wed 20:38]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       3e2c3fd6-d422-44b7-9105-866c588c0231
   :END:

 meander

*** --->
  меандр

  noun
   1. меандр (meander)
   2. изгиб (bend, curve, curvature, bent, flexure, meander)
   3. извилина дороги (meander)

  verb
   1. извиваться (wriggle, squirm, coil, meander, serpentine, wiggle)
   2. бродить без цели (meander, ramble, meander along, slosh)
   3. змеиться (snake, meander)

  DEFINITION

  verb
   1. (of a river or road) follow a winding course.
      "a river that meandered gently through a meadow"

  noun
   1. a winding curve or bend of a river or road.
      "the river flows in sweeping meanders"


  To meander means to wander aimlessly on a winding roundabout course.
  If you want some time to yourself after school, you might meander
  home, taking the time to window shop and look around.

  Meander comes from a river in modern-day Turkey, the Maiandros, which
  winds and wanders on its course. Today, a stream or a path meanders,
  as does a person who walks somewhere in a roundabout fashion. If your
  speech meanders, you don't keep to the point. It's hard to understand
  what your teacher is trying to impart if he keeps meandering off with
  anecdotes and digressions. Pronounce meander with three syllables not
  two — me-AN-der.

  If they meander or try to postpone for a later undefined call, reel
  them in and get them to come to the point.

* feign :Ferris:
[2018-07-19 Thu 20:47]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       b54e38c6-062e-4e2f-9512-b9911f9ad295
   :END:

 feign

*** --->
  симулировать

  verb
   1. симулировать (simulate, pretend, feign, sham, assume, dissimulate)
   2. притворяться (pretend, act, feign, dissemble, play, sham)
   3. придумывать (invent, think, think up, think of, devise, feign)
   4. выдумывать (invent, think up, make up, dream up, fabricate, feign)

  DEFINITION

  verb
   1. pretend to be affected by (a feeling, state, or injury).
      "she feigned nervousness"


  For a more formal way to say pretend to or imitate, choose the verb
  feign. You might feign indifference when you hear about some gossip,
  but you're probably dying to know.

  Feign comes from the Latin fingere "to devise, fabricate." The word
  fiction comes from the same source, so if you feign something such as
  sleep, you give off the fiction that you are sleeping. This can be
  done to be polite but also to deceive such as when you feign an injury
  or the flu so you can stay home from school or work. You can also
  feign an accent, though some are better at this than others.

  If you have to, feign an urgent phone call.

* cubicle :Ferris:
[2018-07-19 Thu 20:49]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       b43f442e-a8b7-478d-9e2c-32a211d804db
   :END:

 cubicle

*** --->
  кабинка

  noun
   1. одноместная больничная палата (cubicle)
   2. кабина на пляже (cubicle)
   3. небольшая комнатка (cubicle)

  DEFINITION

  noun
   1. a small partitioned-off area of a room, for example one containing a bed in a dwelling or one containing a desk in an office.
      "each cubicle is equipped with a PC and printer, and there are two fax machines in the east alcove"


  A cubicle is a small space partitioned off within a larger space for a
  particular purpose — usually reading or studying. Or just surfing the
  Internet.

  Cubicle comes from the Latin term for a monk's bedroom, cubiculum,
  which itself is from the word cubare, "to lie down." Back then a monk
  would probably share it with an illuminated manuscript and a Bible;
  nowadays the average worker drone has a computer and a bunch of
  Post-it notes. Still great for sleeping in, though, as long as you
  don't get caught.

  The cubicle is your temple—don’t permit casual visitors.

* seldom                                                             :Ferris:
[2018-07-19 Thu 20:52]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       ee770dfd-a162-4a90-b51a-a1da9532e7aa
   :END:

 seldom

*** --->
  редко

  adverb
   1. редко (rarely, seldom, infrequently, on rare occasions)

  DEFINITION

  adverb
   1. not often; rarely.
      "Islay is seldom visited by tourists"

  adjective
   1. not common; infrequent.
      "a great but seldom pleasure"


  If you seldom see your grandmother because she lives far away, you
  might be grateful for the opportunity to visit her over the summer.
  Use the adjective seldom to refer to things that don't happen very
  often.

  A near synonym is rarely. Seldom is a Middle English word, from Old
  English seldum, a spelling alteration of seldan "strange, rare." In
  Old English, the spelling seldum came about by analogy with forms such
  as Old English hwilum "formerly, at one time," from hwil "time,
  while."

  Of course, the return seldom happens.

* falter                                                             :Ferris:
[2018-07-19 Thu 20:56]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       2b4ef1f6-48ba-4fd5-952a-ef60a08f2633
   :END:

 falter

*** --->
  спотыкаться

  verb
   1. колебаться (hesitate, fluctuate, sway, oscillate, vibrate, falter)
   2. спотыкаться (stumble, falter, trip, hobble, blunder, reel)
   3. дрогнуть (falter, waver, flinch, quail, reel)
   4. запинаться (stammer, stumble, falter, stutter, hesitate, hem)
   5. шататься (stagger, totter, falter, reel, gad, mosey)
   6. действовать нерешительно (falter)
   7. замяться (falter, stumble)
   8. идти неуверенно (falter)
   9. говорить нерешительно (falter)
  10. говорить заикаясь (falter)

  DEFINITION

  verb
   1. start to lose strength or momentum.
      "her smile faltered and then faded"


  Falter means to hesitate, stumble, or waver, and everything from faith
  to voices can do it. So if you want to keep your bride or groom happy,
  it's best not to falter when it's your turn to say "I do."

  Experts may falter if you ask them where falter came from, because the
  origins are pretty unclear. But everyone agrees on the current
  meaning: someone who falters is unsteady, wobbly, or unsure. You might
  falter while reciting a poem if you forget some of the lines, or
  falter crossing a rickety rope bridge when fear gets the most of you.
  But you certainly won't falter when someone asks you the meaning of
  this word.

  Time Consumers: Batch and Do Not Falter
