-*- coding: utf-8 -*-



* awareness :satellite:
[2018-10-02 Tue 09:33]

Awareness is the state of knowing something, such as the awareness
that the sun comes up every morning.

The adjective aware gets turned into a noun when the suffix -ness is
added, so awareness is the state of being aware, or having knowledge
of something. Its roots are Germanic, and come from the Old English
wær meaning "wary, cautious." Awareness can be something you notice,
want to tell others about, or already know. You could "raise
awareness" of a cause, like fighting breast cancer. Yet, your
awareness of the baby sleeping next door might prevent you from having
band practice in the garage. Smart move.

Personal development covers activities that improve awareness and
identity, develop talents and potential, build human capital and
facilitate employability, enhance the quality of life and contribute to
the realization of dreams and aspirations.
* aspirations :satellite:
[2018-10-02 Tue 09:34]

If your aspiration, or ambition, is to climb Mt. Everest someday, you
better start training, because it’s a long, hard climb that requires a
lot of preparation.

Aspiration means "inhalation" or "breathing." So how did it come to
mean "ambition" or "the will to succeed"? The Latin gives us a clue:
spirare ("to breathe") and spiritus ("spirit"). It was once believed
that our breath was our soul or spirit, which might explain why we
talk about "breathing life into" something, or coming up with energy
and ideas to invigorate it. How else to breathe life into something
than with ambition and drive, in other words, "spirit"?

Personal development covers activities that improve awareness and
identity, develop talents and potential, build human capital and
facilitate employability, enhance the quality of life and contribute to
the realization of dreams and aspirations.
* prevalence :satellite:
[2018-10-02 Tue 09:39]

Prevalence means there is a lot of something. If you get a bad grade
on a paper for having a prevalence of typos, you need to proofread
your work more carefully.

The word prevalence comes from the Latin praevalere, meaning
"condition of being widespread or general." The word is often used to
describe a phenomenon that is widespread in a community, like the
prevalence of a disease across a country. Prevalence is another word
for "commonness." If there's a prevalence of thefts in your
neighborhood, that means the likelihood of your house getting robbed
is pretty high.

However, there are two
newer ways increasing in prevalence: consumer-to-business and
consumer-to-consumer.
* astray :Covey:
[2018-10-11 Thu 16:32]

If you go astray, you lose the path. If you went to college intending
to become a doctor, but instead became interested in making violent
video games, your parents might feel you have gone astray.

A stray animal is one that has gotten loose, and the adverb astray
comes from this sense of wandering off from the proper place, even
though it's not just for animals. If you go astray, you lose the right
way, or are out of place. It can be a moral judgment: juvenile
delinquents are kids who have gone astray. But it can also refer to
small details. If you dress impeccably, you make sure that no thread
is astray.

Something or someone described as [errant] has gone astray or done
  wrong by going in an unexpected direction.
* piecemeal :Covey:
[2018-10-17 Wed 16:54]

When you do something piecemeal, you're doing it little by little, but
in a seemingly random way, with no order or system.

Say you're a computer geek and someone calls you desperate to find out
how to fix a computer that's just crashed. If you respond piecemeal to
the caller's questions, she'll have to call you back many times to get
all the information she needs to get the computer up again. You may
like to talk to her, but she's not going to be impressed with your
computer smarts.

The Seven Habits are not a set of separate or piecemeal psych-up formulas.
* smack :Covey:
[2018-10-17 Wed 17:00]

A smack is a slap or blow made with the palm of a hand or something
else that's flat. Instead of giving your dog a smack for chasing the
cat, you should speak calmly and firmly to him.

Smack also describes the sound of a smack, like when your Frisbee hits
your neighbor's house with a smack. It's a verb too: "I'm tempted to
smack you for saying that about my brother." Sometimes, smack takes
the form of a descriptive adverb: "I ran smack into the mailbox while
I was texting and walking." Informally, a smack can also be a kiss, or
an eager movement of the lips in anticipation of something delicious.

The little understood concept of interdependence appears to many to smack
of dependence, and therefore, we find people, often for selfish reasons,
leaving their marriages, abandoning their children, and forsaking all kinds
of social responsibility—all in the name of independence.
* impatience :Covey:
[2018-10-19 Fri 13:04]

Impatience is the tendency to be irritable or easily frustrated. A bus
driver's impatience often results in her yelling, honking her horn,
and gesturing angrily at other drivers.

If you are easily annoyed or provoked, your impatience is showing.
Impatience is also why you hate being late, or having to wait for
something or someone. It comes from patience, the habit or trait of
being able to wait calmly or even tolerate discomfort without
complaining. The "opposite of" prefix im- tells you that impatience is
the complete opposite.

But with his increasing wealth comes greed and impatience.
* appraised :Covey:
[2018-10-19 Fri 13:04]

When you buy a house someone will need to appraise its value before
you can get a mortgage. To appraise something is to figure out its
worth in the marketplace, on the field, or in the world of ideas.

To appraise the value of a friendship is difficult, but to appraise
the value of your grandfather’s pocket watch — just go to the pawn
shop. The verb appraise comes from the Late Latin word appretiare,
which means “value” or “estimate.” You can appraise your chances of
marrying royalty, which are probably slim. You can also appraise the
value of a quarterback on your fantasy football team by looking at the
statistics for his completed passes.

But as he starts to throw the egg aside, he has second
thoughts and takes it in to be appraised instead.
* wherewithal :Covey:
[2018-10-19 Fri 13:06]

If you have the wherewithal to do something, it means you've got what
you need to make it happen.

Another word for wherewithal is resources, which can mean money,
energy, support, or some other necessary means. If you have the
wherewithal to build a new house, it can mean you have the knowledge
and patience to do it yourself, or that you've got the money to pay
someone to build it for you. The word combines where and withal — a
now-obscure word that means "in addition." Don't forget to spell it
with only one l.

On the
other hand, if you only take care of the goose with no aim toward the
golden eggs, you soon won’t have the wherewithal to feed yourself or the
goose.
* tremendous :Covey:
[2018-10-19 Fri 13:09]

Tremendous means extraordinarily large in size, extent, amount, power,
or degree. It can also mean really marvelous and fantastic — or really
awful and terrible.

We often use tremendous if something is super wonderful. If someone
comes into your office and tells you you just won a big contract and
are getting a huge bonus, you might exclaim, “Tremendous!” Tremendous
comes from the Latin for "trembling," and is connected with fear.
Something tremendous can be big in a terrifying way, like the
tremendous noise of an approaching hurricane, or a tremendous tidal
wave about to crash on the shore.

Keeping P and PC in balance makes a tremendous difference in
the effective use of physical assets.
* kindnesses :Covey:
[2018-10-19 Fri 13:14]

If someone asks you to do them a kindness, they mean a nice, kind act,
the kind that makes you think of puppies and daisies.

The noun kindness can be used for a kind act or to describe someone's
temperament. You might say of someone that her kindness is quite
genuine, or on the other hand she fakes kindness to get what she
wants.

When two people in a marriage are more concerned about getting the golden
eggs, the benefits, than they are in preserving the relationship that makes
them possible, they often become insensitive and inconsiderate, neglecting
the little kindnesses and courtesies so important to a deep relationship.
* courtesies :Covey:
[2018-10-19 Fri 13:14]

A courtesy is a polite remark or respectful act. Complain about a bad
meal, and you might get kicked out. But the common courtesy is usually
an apology from the manager and, if you're lucky, a free dinner.

Courtesy is all about using your good manners, which is why it shares
roots with the word courteous. Holding the door open for someone,
writing a thank-you note for a gift, and letting the pregnant lady
have the last seat on the bus are all courtesies that would make your
parents proud. And if something is kindly presented to you free of
charge, the gift-giver may say it's "courtesy of" someone special.

When two people in a marriage are more concerned about getting the golden
eggs, the benefits, than they are in preserving the relationship that makes
them possible, they often become insensitive and inconsiderate, neglecting
the little kindnesses and courtesies so important to a deep relationship.
* permissive :Covey:
[2018-10-19 Fri 13:15]

Being permissive is the opposite of being strict. Permissive parents
let their kids stay up later and have more sweets.

A permissive person is a little more lenient or loosey-goosey with the
rules. A permissive teacher is easier on the students and lets them
get away with more. A permissive coach will cut players slack during
practices and games. Laws can be permissive too — about drugs, guns,
and other things that could be tightly controlled. A permissive
society is one with more freedom. When a situation is permissive,
there's permission to do more things.

Either way—authoritarian or permissive—you have the golden egg mentality.
* undermine :Covey:
[2018-10-19 Fri 13:18]

To undermine literally means to dig a hole underneath something,
making it likely to collapse. But we more often use the word to
describe sabotage or the act of weakening someone else's efforts.

Originally spelled with a ‘y’ instead of an ‘i’, undermine has
Germanic roots and means to weaken, hinder, or impair. Accidentally
undermine the foundation of a house by digging a tunnel to China
beneath it and you might be forgiven. Undermine your teacher’s
authority by speaking out of turn and throwing spitballs and odds are
you’ll get in trouble.

You might even escalate your
efforts to threatening or yelling, and in your desire to get the golden
egg, you undermine the health and welfare of the goose.
* serendipitous :Covey:
[2018-10-19 Fri 13:21]

Serendipitous is an adjective that describes accidentally being in the
right place at the right time, like bumping into a good friend in some
unusual location, or finding a hundred dollar bill on the ground.

The root of serendipitous comes from the fairy tale "The Three Princes
of Serendip," in which three princes make one lucky and surprising
discovery after another. A serendipitous moment happens by accident,
usually when you’re doing something completely unrelated, like digging
a hole in your yard to bury your hamster and finding a treasure chest
of jewels. That’s a sad but serendipitous funeral.

That experience was not a planned P experience; it was the serendipitous
fruit of a PC investment.
* immensely :Covey:
[2018-10-19 Fri 13:22]

Immensely is an adverb that means vastly, or very, or hugely. An
immensely good time is a really, really good time.

If you know that immense means huge, then you probably already have a
sense of what immensely means. It's a word for describing the enormous
degree of something. A New York Times bestseller is an immensely
popular book. Any offensive lineman is an immensely large human being.
The earth is immensely old. A mouse can't be described as doing
anything immensely, but an elephant does things immensely all the
time.

One of the immensely valuable aspects of any correct principle is that it
is valid and applicable in a wide variety of circumstances.
* clam :Covey:
[2018-10-19 Fri 13:25]

A clam is a marine animal with two shells that eats by straining food
from water, sand, or mud. You can sometimes find clams by digging in
the sand close to the seashore.

The largest clams are used for food by humans, including the scallop,
a particularly big form of clam. When you order soup in New England,
it's not unlikely that it will be clam chowder, a creamy, thick stew
with potatoes and pieces of clam. When clam is a verb, it means "to
dig clams on the beach," and if your friend offers to pay you 1000
clams for your old car, she means "dollars."

I know of a restaurant that served a fantastic clam chowder and was packed
with customers every day at lunchtime.
* chowder :Covey:
[2018-10-19 Fri 13:25]

Chowder is a thick, chunky soup that often contains fish or shellfish.
New England is well known for its creamy, rich version of clam
chowder.

Chowder is somewhere between a soup and a stew — it's full of chunks
of potato and onions, thick with bacon, fish, or vegetables, and
sometimes eaten with crackers on the side or crumbled on top. Chowder
is one of many words that distinctly originated in America, and it was
included in the first edition of Noah Webster's dictionary of American
English. Chowder comes from the pot in which it's cooked, chaudière,
French for "a pot."

I know of a restaurant that served a fantastic clam chowder and was packed
with customers every day at lunchtime.
* dwindled :Covey:
[2018-10-19 Fri 13:26]

What do love, money, and the earth all have in common? All can
dwindle, or shrink away, if we don't handle them properly.

The word dwindle has a wonderfully descriptive, almost childlike sound
to it, as though it belongs in a nursery rhyme. That might help you
remember the meaning, which is to shrink away gradually, like the
Cheshire Cat in "Alice in Wonderland," who dwindles away until nothing
is left but his grin.

Trust was gone, and
business dwindled to almost nothing.
* misdeeds :Covey:
[2018-10-19 Fri 17:43]

A misdeed is a type of bad behavior, especially behavior that's
immoral. If you get caught stealing someone’s lunch, you’ll be
punished for your misdeed.

A deed is an action, and a misdeed is a specific type of action. It’s
one that's wicked, unethical, illegal, or just plain wrong. It’s the
opposite of a good deed. Cheating on a test is a misdeed. So is
cheating on your spouse. Stealing is a misdeed, as is any other crime.
Politicians get caught in scandals when their misdeeds are discovered,
such as lying or taking bribes. It’s from the Old English misdæd for
"sin, evil.”

The word scapegoat first
  occurred in the earliest English translation of the Bible, and it has
  come to mean any individual punished for the misdeeds of others.
* evade :Covey:
[2018-10-19 Fri 17:50]

When you evade something, you escape it. You could evade a police
chase by slipping into a secret alley, or you could evade your
mother's questions about the missing cookies by slipping into another
topic.

Other things people like to evade? Death. Taxes. Creepy ex-boyfriends.
The verb evade comes from Latin roots ex ("away) and vadere ("to
walk"), meaning literally "to walk away or to escape." Definitely what
you want to do with creepy ex-boyfriends.

Master criminals
  rely on their ingenuity in order to evade the law when they are
  chased.
* abstain :Covey:
[2018-10-20 Sat 09:06]

If you abstain from something, you restrain yourself from consuming
it. People usually abstain from things that are considered vices —
like eating French fries every day for lunch.

Roots of the word abstain are from the 14th-century French, "to
withhold oneself," and the word often refers to people who hold
themselves back from indulging in habits that are bad for them,
physically or morally. Abstain can also mean to withhold a vote, and
sometimes a difficult decision is stalled when government
representatives abstain from voting one way or another.

deliberately avoid using; abstain from.
* condemns :Covey:
[2018-10-20 Sat 09:08]

You can condemn, or openly criticize, someone who is behaving
inappropriately. If you are an animal rights activist, you would
probably condemn someone for wearing fur.

Condemn originally comes, through Old French, from the Latin word
condemnāre, "to sentence, condemn." You may see politicians condemn
each other in political ads during a campaign in hopes of improving
their chances of winning an election. You also might hear of a convict
being "condemned to death." In this sense of the word, to condemn
still carries on its Latin meaning of "to sentence."

"Her status as slave condemns her to a life of servitude , with little or no control over her future."
* reel :Covey:
[2018-10-20 Sat 09:15]

A reel is a cylinder that can be wound with flexible material like
film or fishing line. If you found dozens of reels of old home movies
in your grandparents' attic, you'd search for a projector.

You might find an old movie reel, a reel of copper wire, or a fishing
reel. Use the reel on your fishing pole to reel in your fish! Yes,
it’s a verb, too. And it’s a lively folk dance — or the music for it —
from Scotland (Highland reel), or America (Virginia reel). As a verb,
reel also means to sway from dizziness. If an ear infection messes
with your balance, you might reel down the hall like you were drunk.

If they meander or try to postpone for a later undefined call, reel
  them in and get them to come to the point.
* batch                                                               :Covey:
[2018-10-20 Sat 14:02]

A batch is a completed group, collection, or quantity of something,
especially something that's just been made. You might, for example,
bake a batch of cookies to take to your new neighbor.

A company that makes soap might deliver a batch, loaded on a truck, to
a new store in Vermont, and if you manage a bakery you might declare,
"That's it! This is our last batch of gingerbread until next year!" In
computer lingo, a batch is, similarly, a group or collection of
records. The Old English root, bæcce, means "something baked," from
bacan, "bake."

Time Consumers: Batch and Do Not Falter
* Excessive :Covey:
[2018-10-21 Sun 08:22]

Excessive means beyond what is typical or normal. When something is
excessive, there's way too much.

Excessive refers to something that is extra — usually in a negative
way. A 90-second drum solo in a two-minute song is excessive. Getting
down on your knees and kissing someone's feet to thank them for a
favor is excessive, unless they gave you their firstborn. Often this
means something that exceeds the bounds of good taste, or is
extravagant and inappropriately expensive. You should dress up for
dinner, but wearing a ball gown to a diner is excessive.

Excessive focus on P results in ruined
health, worn-out machines, depleted bank accounts, and broken
relationships.
* deteriorated :Covey:
[2018-10-21 Sun 14:02]

When something gets worse due to neglect or an unfortunate health
problem, stuff starts to deteriorate — or fall apart.

The word deteriorate describes anytime something gets worse. Due to
neglect, a relationship can deteriorate but so can the American
highway system. Sadly, there seems to be no end to applications for
the word deteriorate. And, the truth is at a certain age we all start
deteriorating too.

As you open yourself to the next three habits—the habits of Public
Victory—you will discover and unleash both the desire and the resources to
heal and rebuild important relationships that have deteriorated, or even
broken.
* internalized :Covey:
[2018-10-21 Sun 14:03]

If you feel anger, pain, fear or hurt but never show it, you
internalize it — you keep it inside.

If you think about the prefix inter- which always indicated something
within, you have the meaning of the adjective internalize, "to keep or
take something in." It can be used in either a positive or negative
way. If you are a debater who internalizes a topic, then you know it
inside and out. On the other hand, you're not doing yourself any
favors if you internalize your guilt.

The seventh habit, if deeply internalized, will renew the first six and
will make you truly independent and capable of effective interdependence.
* possess :Covey:
[2018-10-21 Sun 14:13]

To possess something is to have or own it. You can possess a physical
object, you can possess a particular quality or skill, or you can
possess control or influence over someone.

Related words are possessive (describing those who hold onto people or
things in a controlling way), and possessed, as in a person being
possessed by an idea or even by a demon. This verb is from Middle
French possesser "to own," from Latin possidēre, from potis "able,
having the power" plus sedēre "to sit."

Animals do not
 possess this ability.
* dominion :Covey:
[2018-10-21 Sun 14:13]

When you are in charge of something or rule it, you have dominion over
it. The most famous use of the word occurs in the Christian Bible,
when God grants people dominion over other animals.

If you know the word domination, then you won't be surprised that
dominion also has to do with a type of ruling over others. This is an
old-fashioned and Biblical-sounding word for having power. A king has
dominion over his kingdom. You'd never say the President has dominion,
because we live in a democracy. Dominion implies more power than that
— even absolute power. A dominion can also be an area or territory
controlled by a larger country or state.

This is the reason why man has
 dominion over all things in the world and why he can make significant
 advances from generation to generation.
* upbringing :Covey:
[2018-10-24 Wed 18:26]

Your upbringing is how you were raised as a child. You might have had
a rough upbringing or a gentler one, but at least you made it this
far.

Looking at the base “bring” in upbringing, we find a Germanic origin
meaning "to carry." You might consider the "carry" idea as a way to
remember the word, considering a parent "carries" a child to
adulthood, providing what then becomes the child’s upbringing.

Your
upbringing, your childhood experience essentially laid out your personal
tendencies and your character structure.
* repugnant :Covey:
[2018-10-24 Wed 18:29]

Repugnant refers to something you detest so thoroughly it threatens to
make you physically sick, like the idea of marrying your sister. Or
wearing last year's jeans.

A repugnant thing is a thing offensive, detestable, or obscene. It can
be repugnant to your mind or your morals. It can also be physically
repugnant, like the smell that comes from a restaurant’s dumpster,
which hasn't been emptied since the very exciting "Omelet Week," way
back at the beginning of August. Makes you want to "re-PLUG-nant" your
nose!

He was imprisoned in the death
camps of Nazi Germany, where he experienced things that were so repugnant
to our sense of decency that we shudder to even repeat them.
* indignities :Covey:
[2018-10-24 Wed 18:30]

An indignity is something embarrassing. An indignity is usually
something that happens to us rather than something we do ourselves.

As you might guess from that negative prefix in-, an indignity is a
word that takes dignity (or self-esteem) away. If you find a fly in
your soup, that's an indignity — not to mention protein. If you're
making a speech and you realize your fly is open, that's a major
indignity. Many people find waiting in line a long time to be an
indignity. When you say "This is an indignity!" you're really saying,
"I'm better than this, and I shouldn't have to deal with it." Needless
to say, life is full of indignities.

Frankl
himself suffered torture and innumerable indignities, never knowing from
one moment to the next if his path would lead to the ovens or if he would
be among the “saved” who would remove the bodies or shovel out the ashes
of those so fated.
* captors :Covey:
[2018-10-24 Wed 18:31]

Someone who catches a person or animal and keeps them confined or
imprisoned is a captor. Visiting the zoo, you might find yourself
wondering if the lions see the zookeepers as friends or as captors.

The word captor sounds a little bit like capture, and it's no
coincidence — they're both rooted in the Latin capere, "to take, hold,
or seize." So if you capture a cricket and keep it in a little cage,
you are its captor. And, when a police force captures a criminal and
puts them in prison, the police become captors too. The original
meaning of captor was actually "a censor."

One day, naked and alone in a small room, he began to become aware of what
he later called “the last of the human freedoms”—the freedom his Nazi
captors could not take away.
* intact :Covey:
[2018-10-24 Wed 18:32]

If something is intact it's still in one piece. If you'd like your
sand castle to remain intact, I suggest you build it away from the
water.

The Latin word intactus means “untouched,” but today something is
intact if it's whole, if it hasn't fallen apart. After a long day at
work, you might feel lucky to be intact. Your letter to the post
office states that you would prefer your packages to arrive intact
from now on.

His basic identity was intact.
* endowment :Covey:
[2018-10-24 Wed 18:34]

An endowment is a gift. It might be money given to an institution like
a college. Or, an endowment might be a natural gift, say of a physical
attribute or a talent. If you lack the endowment of musical talent,
you could play the tambourine.

To endow means "to give or bequeath," and the background of the word
endowment goes back to the 15th Century, where it was used to refer to
money or property that is given to an institution. An example can be
found in the National Endowment for the Arts, an organization
dedicated to providing grants to fund artistic endeavors. Your natural
endowments — speed, agility, endurance — make you an excellent soccer
player. If only you could wake up in time for practice.

In the midst of the most degrading circumstances imaginable, Frankl used
the human endowment of self-awareness to discover a fundamental principle
about the nature of man: Between stimulus and response, man has the
freedom to choose.
* conscience :Covey:
[2018-10-24 Wed 18:35]

A conscience is a built-in sense of what's right and what's wrong.
That sick feeling in your stomach after you meanly told your younger
brother the truth about Santa Claus? That might be your conscience
bothering you.

The word conscience contains the word science, which comes from the
Latin word scientia, meaning "to know" or "knowledge." You can think
of your conscience as your knowledge of yourself, especially when it
comes to your own morals, or your feelings about right and wrong.
Pangs of conscience, which feel like an uncomfortable inner voice, are
helpful when you're trying to decide the right thing to do in a
particular situation.

We have conscience—a deep
inner awareness of right and wrong, of the principles that govern our
behavior, and a sense of the degree to which our thoughts and actions are
in harmony with them.
* empower :Covey:
[2018-10-24 Wed 18:41]

Empower means "give power or authority to." When you educate children
and believe in them, you empower those kids to go after their dreams.

Empower might seem like a new word, but it's been around since the
17th century. Today, empower often refers to helping someone realize
their abilities and potential, perhaps for the first time. For
example, in the 1960s, when women felt like second-class citizens, the
women's movement empowered them to stand up and demand their equal
rights.

Because we are, by nature, proactive, if our lives are a function of
conditioning and conditions, it is because we have, by conscious decision
or by default, chosen to empower those things to control us.
* internalized :Covey:
[2018-10-24 Wed 18:43]

If you feel anger, pain, fear or hurt but never show it, you
internalize it — you keep it inside.

If you think about the prefix inter- which always indicated something
within, you have the meaning of the adjective internalize, "to keep or
take something in." It can be used in either a positive or negative
way. If you are a debater who internalizes a topic, then you know it
inside and out. On the other hand, you're not doing yourself any
favors if you internalize your guilt.

Proactive people are
driven by values—carefully thought about, selected and internalized
values.
* crucibles :Covey:
[2018-10-30 Tue 09:06]

A crucible is a melting pot used for extremely hot chemical reactions
— the crucible needs to be melt-proof.

Literally, a crucible is a vessel used for very hot processes, like
fusing metals. Another meaning of the word is a very significant and
difficult trial or test. Scaling Mt. Everest with your legs tied
together would be a crucible, as would swimming the English Channel
blindfolded. Whether or not to have children is a crucible for many
people. The title of Arthur Miller’s play The Crucible is an example
of this meaning.

In fact, our most difficult experiences become the crucibles
that forge our character and develop the internal powers, the freedom to
handle difficult circumstances in the future and to inspire others to do
so as well.
* ennobles :Covey:
[2018-10-30 Tue 09:08]

To ennoble someone is to make them a Lord or a Baroness — to bestow a
noble title upon them. The Queen of England has the power to ennoble
people, turning Paul McCartney into Sir Paul McCartney, for example.

One way to use the verb ennoble is to mean, literally, "make someone a
noble or a member of the nobility." It can also mean "bestow or lend
dignity to" or "make dignified." You could say, "Reading great books
ennobles the mind," or "Treating others with kindness ennobles a
person." Ennoble comes from the Old French ennoblir, from the prefix
en-, "put in," and the Latin root nobilis, "excellent, superior, or
splendid."

Nothing has a greater, longer lasting impression upon another person than
the awareness that someone has transcended suffering, has transcended
circumstance, and is embodying and expressing a value that inspires and
ennobles and lifts life.
* protracted :Covey:
[2018-10-30 Tue 09:09]

Something protracted has been drawn out, usually in a tedious way.
Protracted things are long and seem like they're never going to end.

Anything protracted is lasting longer than you would like. A speech
that seems to go on forever is protracted. If an employer and a union
can't reach an agreement, there could be a protracted strike. Before a
movie, the previews are almost always protracted — they never seem to
stop. If something is long and annoying, and there's no good reason it
couldn't be shorter, it's protracted.

She returned from
those protracted and difficult sessions almost transfixed by admiration
for her friend’s courage and her desire to write special messages to be
given to her children at different stages in their lives.
* pushy :Covey:
[2018-10-30 Tue 09:14]

Pushy people are aggressive and bold about getting what they want. A
pushy used car salesperson will make you feel bullied into buying
something even if you were just interested in admiring convertibles.

If you're pushy, you're not afraid to let your ambition show, or to
boss other people around. Pushy parents might argue with a teacher who
gives their child a bad grade, and pushy newspaper reporters will
invade your privacy to get a good story. This adjective was originally
used, around 1891, to describe a cow. Just a few years later, it began
to describe people as well.

Taking initiative does not mean being pushy, obnoxious, or aggressive.
* obnoxious :Covey:
[2018-10-30 Tue 09:14]

If something is obnoxious, it's annoying and unpleasant. Generally,
people like to avoid obnoxious folks.

If something is driving you absolutely crazy, it's probably obnoxious.
Yelling and stomping your feet is obnoxious. Poking someone repeatedly
is obnoxious. Driving like a maniac is obnoxious. If the teacher comes
in and finds students jumping up and down and throwing books, she
might say, "Stop being so obnoxious!" Anytime someone is obnoxious,
someone else probably wants them to stop it.

Taking initiative does not mean being pushy, obnoxious, or aggressive.
* counseled :Covey:
[2018-10-30 Tue 09:15]

When you give counsel or counsel someone, you give advice. If your
neighbor is suing you because your dog keeps eating his begonias, you
might seek the counsel of a dog trainer or, if that doesn't work, a
lawyer.

You can get professional counsel — from a minister or psychiatrist or
someone else trained in counseling — or you can get counsel from
anyone you trust. You can ask your stylish friend to counsel you on
your hairstyle, or you could write to Dear Abby for counsel on your
lovelife. Counsel is also what you call a lawyer who represents you in
court. In your begonia-eating dog case, your lawyer would be counsel
for the defense.

Over the years, I have frequently counseled people who wanted better jobs
to show more initiative—to take interest and aptitude tests, to study the
industry, even the specific problems the organizations they are interested
in are facing, and then to develop an effective presentation showing how
their abilities can help solve the organization’s problem.
* demeaning :Covey:
[2018-10-30 Tue 09:17]

The adjective demeaning describes something that lowers a person's
reputation or dignity. If your boss always asks you to pick up her dry
cleaning and get her coffee, you might feel like you usually get the
demeaning jobs.

The adjective demeaning comes from the verb demean, which itself is
based on the construction of the word "debase." The word demean has
two almost opposite meanings, to degrade and to conduct oneself in a
particular manner, usually a proper one. The adjective, however,
always describes something that is degrading. Overhearing two friends
gossiping about you can be a demeaning experience, even if they're
just criticizing your new haircut.

Holding people to the responsible course is not demeaning; it is
affirming.
* affirming :Covey:
[2018-10-30 Tue 09:18]

To affirm something is to give it a big "YES" or to confirm that it is
true.

The verb affirm means to answer positively, but it has a more weighty
meaning in legal circles. People are asked to swear an oath or affirm
that they will tell the truth in a court of law. Lawyers may ask
people to affirm facts, and judges may affirm rulings. In these cases,
affirm means to verify or attest to the validity of something.

Holding people to the responsible course is not demeaning; it is
affirming.
* uninhibited :Covey:
[2018-10-30 Tue 09:21]

The prefix "un-" means "not," making the meaning of uninhibited "not
inhibited, not restrained or holding back." Someone who is uninhibited
is not afraid to act however he or she wishes.

Uninhibited is the opposite of inhibited, from the Latin inhibēre, "to
prohibit or hinder." In the late 19th century the word took on a new
importance to psychologists, describing a person not afraid to express
emotions, even in public. The following quote from writer Norman
Podhoretz gives a contextual definition: "Creativity represents a
miraculous coming together of the uninhibited energy of the child with
its apparent opposite and enemy, the sense of order imposed on the
disciplined adult intelligence."

At one time I worked with a group of people in the home improvement
industry, representatives from twenty different organizations who met
quarterly to share their numbers and problems in an uninhibited way.
