-*- coding: utf-8 -*-



* awareness :satellite:
[2018-10-02 Tue 09:33]

** Translate from English to Russian:                                 :drill:

 awareness

*** --->
  осознание

  noun
   1. осознание (awareness, realization, perception, knowing)
   2. осведомленность (awareness, knowledge, information, conversance, privity, info)

  DEFINITION

  noun
   1. knowledge or perception of a situation or fact.
      "we need to raise public awareness of the issue"


  Awareness is the state of knowing something, such as the awareness
  that the sun comes up every morning.

  The adjective aware gets turned into a noun when the suffix -ness is
  added, so awareness is the state of being aware, or having knowledge
  of something. Its roots are Germanic, and come from the Old English
  wær meaning "wary, cautious." Awareness can be something you notice,
  want to tell others about, or already know. You could "raise
  awareness" of a cause, like fighting breast cancer. Yet, your
  awareness of the baby sleeping next door might prevent you from having
  band practice in the garage. Smart move.

  Personal development covers activities that improve awareness and
  identity, develop talents and potential, build human capital and
  facilitate employability, enhance the quality of life and contribute to
  the realization of dreams and aspirations.
* aspiration                                                      :satellite:
[2018-10-02 Tue 09:34]
** Translate from English to Russian:                                 :drill:

 aspiration
*** --->
  стремление

  noun
   1. стремление (aspiration, pursuit, tendency, intention, ambition, endeavor)
   2. аспирация (aspiration, inhalation)
   3. устремление (aspiration, rush)
   4. желание (desire, wish, will, want, aspiration, would)
   5. придыхание (aspiration, breathing)
   6. сильное желание (yearning, desire, urge, aspiration, hunger, lech)
   7. удаление из полости (aspiration)

  DEFINITION

  noun
   1. a hope or ambition of achieving something.
      "he had nothing tangible to back up his literary aspirations"
   2. the action or process of drawing breath.
      "These factors lead to either inhalation or aspiration of pathogens into the respiratory tract."
   3. the action of pronouncing a sound with an exhalation of breath.
      "If voicing is delayed, the voiceless region at the beginning of the vowel is known as aspiration ."


  If your aspiration, or ambition, is to climb Mt. Everest someday, you
  better start training, because it’s a long, hard climb that requires a
  lot of preparation.

  Aspiration means "inhalation" or "breathing." So how did it come to
  mean "ambition" or "the will to succeed"? The Latin gives us a clue:
  spirare ("to breathe") and spiritus ("spirit"). It was once believed
  that our breath was our soul or spirit, which might explain why we
  talk about "breathing life into" something, or coming up with energy
  and ideas to invigorate it. How else to breathe life into something
  than with ambition and drive, in other words, "spirit"?

  Personal development covers activities that improve awareness and
  identity, develop talents and potential, build human capital and
  facilitate employability, enhance the quality of life and contribute to
  the realization of dreams and aspirations.
* prevalence :satellite:
[2018-10-02 Tue 09:39]
** Translate from English to Russian:                                 :drill:

 prevalence
*** --->
  распространенность

  noun
   1. распространенность (prevalence, abundance)
   2. преобладание (predominance, prevalence, dominance, preponderance, domination, predomination)
   3. широкое распространение (prevalence)
   4. господство (domination, rule, dominance, dominating, supremacy, prevalence)

  DEFINITION

  noun
   1. the fact or condition of being prevalent; commonness.
      "the prevalence of obesity in adults"


  Prevalence means there is a lot of something. If you get a bad grade
  on a paper for having a prevalence of typos, you need to proofread
  your work more carefully.

  The word prevalence comes from the Latin praevalere, meaning
  "condition of being widespread or general." The word is often used to
  describe a phenomenon that is widespread in a community, like the
  prevalence of a disease across a country. Prevalence is another word
  for "commonness." If there's a prevalence of thefts in your
  neighborhood, that means the likelihood of your house getting robbed
  is pretty high.

  However, there are two
  newer ways increasing in prevalence: consumer-to-business and
  consumer-to-consumer.
* astray :Covey:
[2018-10-11 Thu 16:32]
** Translate from English to Russian:                                 :drill:

 astray
*** --->
  заблудившись

  verb
   1. заблудиться (astray, stray, go astray, lose, wander, lose oneself)

  adverb
   1. заблудившись (astray)

  adjective
   1. заблудившийся (astray, stray, strayed, bushed)

  DEFINITION

  adverb
   1. away from the correct path or direction.
      "we went astray but a man redirected us"
   2. into error or morally questionable behavior.
      "he was led astray by boozy colleagues"


  If you go astray, you lose the path. If you went to college intending
  to become a doctor, but instead became interested in making violent
  video games, your parents might feel you have gone astray.

  A stray animal is one that has gotten loose, and the adverb astray
  comes from this sense of wandering off from the proper place, even
  though it's not just for animals. If you go astray, you lose the right
  way, or are out of place. It can be a moral judgment: juvenile
  delinquents are kids who have gone astray. But it can also refer to
  small details. If you dress impeccably, you make sure that no thread
  is astray.

  Something or someone described as [errant] has gone astray or done
    wrong by going in an unexpected direction.
* piecemeal :Covey:
[2018-10-17 Wed 16:54]
** Translate from English to Russian:                                 :drill:

 piecemeal
*** --->
  по частям

  adverb
   1. по частям (piecemeal, by piecemeal)
   2. постепенно (gradually, little by little, by degrees, piecemeal, bit by bit, insensibly)
   3. поштучно (by the piece, apiece, piecemeal)
   4. на куски (apart, asunder, piecemeal)
   5. на части (apart, to pieces, asunder, piecemeal)

  adjective
   1. частичный (partial, fractional, half, piecemeal, local, fractionary)
   2. постепенный (gradual, progressive, slow, piecemeal)
   3. сделанный по частям (piecemeal)

  DEFINITION

  adjective
   1. characterized by unsystematic partial measures taken over a period of time.
      "the village is slowly being killed off by piecemeal development"


  When you do something piecemeal, you're doing it little by little, but
  in a seemingly random way, with no order or system.

  Say you're a computer geek and someone calls you desperate to find out
  how to fix a computer that's just crashed. If you respond piecemeal to
  the caller's questions, she'll have to call you back many times to get
  all the information she needs to get the computer up again. You may
  like to talk to her, but she's not going to be impressed with your
  computer smarts.

  The Seven Habits are not a set of separate or piecemeal psych-up formulas.
* smack :Covey:
[2018-10-17 Wed 17:00]
** Translate from English to Russian:                                 :drill:

 smack
*** --->
  хлопать

  verb
   1. хлопать (clap, slam, slap, pop, flap, smack)
   2. чмокать (smack)
   3. шлепать (slap, smack, splash, flap, cuff, pat)
   4. смахивать (whisk, smack, brush off, whisk away, brush aside, whisk off)
   5. отдавать (give, give away, return, render, give back, smack)
   6. иметь вкус (taste, relish, smack, savor, savour)
   7. иметь примесь (partake, smack)
   8. пахнуть (smell, scent, smack)
   9. отзываться (respond, speak, react, smack, relish, report)
  10. ощущаться (handle, smack)
  11. чмокать губами (smack, smack one's lips)

  noun
   1. привкус (flavor, smack, tinge, odor, spice, suspicion)
   2. вкус (taste, flavor, liking, palate, style, smack)
   3. шлепок (slap, smack, swat, spank, pat, flap)
   4. героин (heroin, smack, dynamite, horse, snow)
   5. чмоканье (smack, smacking)
   6. хлопок (cotton, clap, pat, flap, smack, swat)
   7. примесь (impurity, admixture, addition, additive, touch, smack)
   8. звонкий шлепок (smack, smacker)
   9. глоток питья (smack)
  10. немного еды (smack)
  11. звонкий поцелуй (buss, smack, smacker)
  12. сильный наркотик (smack)
  13. запах (smell, odor, scent, flavor, flavour, smack)

  adverb
   1. с треском (crash, smack, snap)
   2. в самую точку (smack)
   3. прямо в самую точку (smack)

  DEFINITION

  adverb
   1. in a sudden and violent way.
      "I ran smack into the back of a parked truck"
   2. exactly; precisely.
      "our mother's house was smack in the middle of the city"

  noun
   1. a sharp slap or blow, typically one given with the palm of the hand.
      "she gave Mark a smack across the face"
   2. a flavor or taste of.
      "anything with even a modest smack of hops dries the palate"
   3. a fishing boat, often one equipped with a well for keeping the caught fish alive.
      "The smack is amplified by the posture of the falling fish, which typically flops sideways so that its flank hits the water."
   4. heroin.
      "Something he has never done: Hard drugs like smack or cocaine."
   5. speak insultingly of someone, especially to intentionally rankle them.
      "I love the Yankee fans talking smack , only to see their team collapse once again."

  verb
   1. strike (someone or something), typically with the palm of the hand and as a punishment.
      "Jessica smacked his face quite hard"
   2. have a flavor of; taste of.
      "the tea smacked of peppermint"


  A smack is a slap or blow made with the palm of a hand or something
  else that's flat. Instead of giving your dog a smack for chasing the
  cat, you should speak calmly and firmly to him.

  Smack also describes the sound of a smack, like when your Frisbee hits
  your neighbor's house with a smack. It's a verb too: "I'm tempted to
  smack you for saying that about my brother." Sometimes, smack takes
  the form of a descriptive adverb: "I ran smack into the mailbox while
  I was texting and walking." Informally, a smack can also be a kiss, or
  an eager movement of the lips in anticipation of something delicious.

  The little understood concept of interdependence appears to many to smack
  of dependence, and therefore, we find people, often for selfish reasons,
  leaving their marriages, abandoning their children, and forsaking all kinds
  of social responsibility—all in the name of independence.
* impatience :Covey:
[2018-10-19 Fri 13:04]
** Translate from English to Russian:                                 :drill:

 impatience
*** --->
  нетерпение

  noun
   1. нетерпение (impatience, hurry)
   2. нетерпимость (intolerance, impatience)
   3. раздражительность (irritability, petulance, temper, impatience, irascibility, grumpiness)

  DEFINITION

  noun
   1. the tendency to be impatient; irritability or restlessness.
      "she crumpled up the pages in a burst of impatience"


  Impatience is the tendency to be irritable or easily frustrated. A bus
  driver's impatience often results in her yelling, honking her horn,
  and gesturing angrily at other drivers.

  If you are easily annoyed or provoked, your impatience is showing.
  Impatience is also why you hate being late, or having to wait for
  something or someone. It comes from patience, the habit or trait of
  being able to wait calmly or even tolerate discomfort without
  complaining. The "opposite of" prefix im- tells you that impatience is
  the complete opposite.

  But with his increasing wealth comes greed and impatience.
* appraise                                                            :Covey:
[2018-10-19 Fri 13:04]
** Translate from English to Russian:                                 :drill:

 appraise
*** --->
  оценивать

  verb
   1. оценивать (appreciate, estimate, evaluate, assess, rate, appraise)
   2. расценивать (appraise, rate, cost)

  DEFINITION

  verb
   1. assess the value or quality of.
      "she stealthily appraised him in a pocket mirror"


  When you buy a house someone will need to appraise its value before
  you can get a mortgage. To appraise something is to figure out its
  worth in the marketplace, on the field, or in the world of ideas.

  To appraise the value of a friendship is difficult, but to appraise
  the value of your grandfather’s pocket watch — just go to the pawn
  shop. The verb appraise comes from the Late Latin word appretiare,
  which means “value” or “estimate.” You can appraise your chances of
  marrying royalty, which are probably slim. You can also appraise the
  value of a quarterback on your fantasy football team by looking at the
  statistics for his completed passes.

  But as he starts to throw the egg aside, he has second
  thoughts and takes it in to be appraised instead.
* wherewithal :Covey:
[2018-10-19 Fri 13:06]
** Translate from English to Russian:                                 :drill:

 wherewithal
*** --->
  необходимые средства

  noun
   1. необходимые средства (wherewithal)
   2. необходимые деньги (wherewithal)

  DEFINITION

  noun
   1. the money or other means needed for a particular purpose.
      "they lacked the wherewithal to pay"


  If you have the wherewithal to do something, it means you've got what
  you need to make it happen.

  Another word for wherewithal is resources, which can mean money,
  energy, support, or some other necessary means. If you have the
  wherewithal to build a new house, it can mean you have the knowledge
  and patience to do it yourself, or that you've got the money to pay
  someone to build it for you. The word combines where and withal — a
  now-obscure word that means "in addition." Don't forget to spell it
  with only one l.

  On the
  other hand, if you only take care of the goose with no aim toward the
  golden eggs, you soon won’t have the wherewithal to feed yourself or the
  goose.
* tremendous :Covey:
[2018-10-19 Fri 13:09]
** Translate from English to Russian:                                 :drill:

 tremendous
*** --->
  огромный

  adjective
   1. огромный (huge, enormous, great, vast, immense, tremendous)
   2. потрясающий (tremendous, terrific, shocking, startling, incredible, breathtaking)
   3. громадный (enormous, huge, vast, great, tremendous, immense)
   4. страшный (terrible, fearful, horrible, frightful, frightening, tremendous)
   5. ужасный (terrible, horrible, awful, appalling, dreadful, tremendous)
   6. потрясный (incredible, zingy, super, cool, killing, tremendous)

  DEFINITION

  adjective
   1. very great in amount, scale, or intensity.
      "Penny put in a tremendous amount of time"


  Tremendous means extraordinarily large in size, extent, amount, power,
  or degree. It can also mean really marvelous and fantastic — or really
  awful and terrible.

  We often use tremendous if something is super wonderful. If someone
  comes into your office and tells you you just won a big contract and
  are getting a huge bonus, you might exclaim, “Tremendous!” Tremendous
  comes from the Latin for "trembling," and is connected with fear.
  Something tremendous can be big in a terrifying way, like the
  tremendous noise of an approaching hurricane, or a tremendous tidal
  wave about to crash on the shore.

  Keeping P and PC in balance makes a tremendous difference in
  the effective use of physical assets.
* kindness                                                            :Covey:
[2018-10-19 Fri 13:14]
** Translate from English to Russian:                                 :drill:

 kindness
*** --->
  доброта

  noun
   1. доброта (kindness, goodness, gentleness, kindliness, graciousness, benignity)
   2. доброжелательность (goodwill, kindness, good feeling, good-neighborhood)
   3. любезность (amiability, kindness, favor, civility, compliment, grace)
   4. ласка (weasel, kindness, caress, tenderness, endearment)
   5. мягкосердечие (kindness)
   6. благоволение (goodwill, grace, kindness, smile)
   7. одолжение (favor, service, kindness, good offices, favour)
   8. доброе дело (kindness)
   9. доброжелательство (benevolence, goodwill, kindness)

  DEFINITION

  noun
   1. the quality of being friendly, generous, and considerate.
      "A special thank you to neighbors and friends for their kindness , support and help."


  If someone asks you to do them a kindness, they mean a nice, kind act,
  the kind that makes you think of puppies and daisies.

  The noun kindness can be used for a kind act or to describe someone's
  temperament. You might say of someone that her kindness is quite
  genuine, or on the other hand she fakes kindness to get what she
  wants.

  When two people in a marriage are more concerned about getting the golden
  eggs, the benefits, than they are in preserving the relationship that makes
  them possible, they often become insensitive and inconsiderate, neglecting
  the little kindnesses and courtesies so important to a deep relationship.
* courtesy                                                            :Covey:
[2018-10-19 Fri 13:14]
** Translate from English to Russian:                                 :drill:

 courtesy
*** --->
  учтивость

  noun
   1. вежливость (courtesy, politeness, civility, comity, urbanity, decency)
   2. учтивость (courtesy, politeness, urbanity, affability, delicacy, suavity)
   3. обходительность (courtesy, complaisance, suavity)
   4. правила вежливости (courtesy)
   5. этикет (etiquette, decorum, courtesy, form)

  DEFINITION

  noun
   1. the showing of politeness in one's attitude and behavior toward others.
      "he had been treated with a degree of courtesy not far short of deference"


  A courtesy is a polite remark or respectful act. Complain about a bad
  meal, and you might get kicked out. But the common courtesy is usually
  an apology from the manager and, if you're lucky, a free dinner.

  Courtesy is all about using your good manners, which is why it shares
  roots with the word courteous. Holding the door open for someone,
  writing a thank-you note for a gift, and letting the pregnant lady
  have the last seat on the bus are all courtesies that would make your
  parents proud. And if something is kindly presented to you free of
  charge, the gift-giver may say it's "courtesy of" someone special.

  When two people in a marriage are more concerned about getting the golden
  eggs, the benefits, than they are in preserving the relationship that makes
  them possible, they often become insensitive and inconsiderate, neglecting
  the little kindnesses and courtesies so important to a deep relationship.
* permissive :Covey:
[2018-10-19 Fri 13:15]
** Translate from English to Russian:                                 :drill:

 permissive
*** --->
  разрешающий

  adjective
   1. разрешающий (permissive)
   2. либеральный (liberal, permissive, broad-minded, broad-gauge)
   3. позволяющий (allowing, permitting, permissive)
   4. необязательный (optional, dispensable, permissive, elective, facultative)
   5. дозволяющий (permissive)
   6. снисходительный (indulgent, lenient, forgiving, permissive, gracious, facile)
   7. терпимый (tolerant, tolerable, bearable, supportable, indulgent, permissive)
   8. рекомендующий (permissive)
   9. факультативный (optional, facultative, elective, permissive)
  10. не строгий в вопросах морали (permissive)

  DEFINITION

  adjective
   1. allowing or characterized by great or excessive freedom of behavior.
      "I was not a permissive parent"
   2. allowed but not obligatory; optional.
      "the Hague Convention was permissive, not mandatory"
   3. allowing a biological or biochemical process to occur.
      "the mutants grow well at the permissive temperature"


  Being permissive is the opposite of being strict. Permissive parents
  let their kids stay up later and have more sweets.

  A permissive person is a little more lenient or loosey-goosey with the
  rules. A permissive teacher is easier on the students and lets them
  get away with more. A permissive coach will cut players slack during
  practices and games. Laws can be permissive too — about drugs, guns,
  and other things that could be tightly controlled. A permissive
  society is one with more freedom. When a situation is permissive,
  there's permission to do more things.

  Either way—authoritarian or permissive—you have the golden egg mentality.
* undermine :Covey:
[2018-10-19 Fri 13:18]
** Translate from English to Russian:                                 :drill:

 undermine
*** --->
  подрывать

  verb
   1. подрывать (undermine, disrupt, destroy, sap, destabilize, mine)
   2. разрушать (destroy, ruin, break, break down, disrupt, undermine)
   3. подкапывать (undermine, sap, mine)
   4. подмывать (undermine, wash underneath)
   5. минировать (mine, undermine, sap)
   6. делать подкоп (undermine, sap)

  DEFINITION

  verb
   1. erode the base or foundation of (a rock formation).
      "The lighthouse stands on a plinth of rock undermined by caves, perhaps once used by smugglers."
   2. damage or weaken (someone or something), especially gradually or insidiously.
      "this could undermine years of hard work"


  To undermine literally means to dig a hole underneath something,
  making it likely to collapse. But we more often use the word to
  describe sabotage or the act of weakening someone else's efforts.

  Originally spelled with a ‘y’ instead of an ‘i’, undermine has
  Germanic roots and means to weaken, hinder, or impair. Accidentally
  undermine the foundation of a house by digging a tunnel to China
  beneath it and you might be forgiven. Undermine your teacher’s
  authority by speaking out of turn and throwing spitballs and odds are
  you’ll get in trouble.

  You might even escalate your
  efforts to threatening or yelling, and in your desire to get the golden
  egg, you undermine the health and welfare of the goose.
* serendipitous :Covey:
[2018-10-19 Fri 13:21]
** Translate from English to Russian:                                 :drill:

 serendipitous
*** --->
  связанный со счастливым случаем

  adjective
   1. связанный со счастливым случаем (serendipitous)

  DEFINITION

  adjective
   1. occurring or discovered by chance in a happy or beneficial way.
      "a serendipitous encounter"


  Serendipitous is an adjective that describes accidentally being in the
  right place at the right time, like bumping into a good friend in some
  unusual location, or finding a hundred dollar bill on the ground.

  The root of serendipitous comes from the fairy tale "The Three Princes
  of Serendip," in which three princes make one lucky and surprising
  discovery after another. A serendipitous moment happens by accident,
  usually when you’re doing something completely unrelated, like digging
  a hole in your yard to bury your hamster and finding a treasure chest
  of jewels. That’s a sad but serendipitous funeral.

  That experience was not a planned P experience; it was the serendipitous
  fruit of a PC investment.
* immensely :Covey:
[2018-10-19 Fri 13:22]
** Translate from English to Russian:                                 :drill:

 immensely
*** --->
  очень

  adverb
   1. безмерно (immensely, excessively, no end)
   2. очень (very, very much, extremely, so, highly, immensely)
   3. чрезвычайно (extremely, highly, exceedingly, particularly, enormously, immensely)

  DEFINITION

  adverb
   1. to a great extent; extremely.
      "the president was immensely popular"


  Immensely is an adverb that means vastly, or very, or hugely. An
  immensely good time is a really, really good time.

  If you know that immense means huge, then you probably already have a
  sense of what immensely means. It's a word for describing the enormous
  degree of something. A New York Times bestseller is an immensely
  popular book. Any offensive lineman is an immensely large human being.
  The earth is immensely old. A mouse can't be described as doing
  anything immensely, but an elephant does things immensely all the
  time.

  One of the immensely valuable aspects of any correct principle is that it
  is valid and applicable in a wide variety of circumstances.
* clam :Covey:
[2018-10-19 Fri 13:25]
** Translate from English to Russian:                                 :drill:

 clam
*** --->
  моллюск

  noun
   1. моллюск (shellfish, mollusk, clam, mollusc)
   2. съедобный морской моллюск (clam)
   3. скупец (miser, curmudgeon, tightwad, clam, moneybags, skinflint)
   4. скряга (miser, hunks, curmudgeon, cheapskate, skinflint, clam)
   5. скрытный человек (clam)
   6. необщительный человек (clam, bad mixer)

  verb
   1. собирать моллюсков (clam)
   2. прилипать (adhere, cling, clave, glue, cleave, clam)
   3. липнуть (stick, cling, clam)
   4. быть молчаливым (clam)
   5. быть необщительным (clam)
   6. стать молчаливым (clam)
   7. стать необщительным (clam)
   8. замолчать (fall silent, sign off, clam, shush, say no more, cease talking)

  DEFINITION

  noun
   1. a marine bivalve mollusk with shells of equal size.
      "Their tricuspid teeth (three sharp points per tooth) are especially adapted to feed on organisms with hard shells such as clams , snails, crabs and shrimp."
   2. a dollar.
      "all I got for the job was 50 lousy clams"
   3. a shy or withdrawn person.

  verb
   1. dig for or collect clams.
      "it was one of the worst times for clamming"
   2. abruptly stop talking, either for fear of revealing a secret or from shyness.
      "When he's around people he doesn't know he clams up completely and just stops talking."


  A clam is a marine animal with two shells that eats by straining food
  from water, sand, or mud. You can sometimes find clams by digging in
  the sand close to the seashore.

  The largest clams are used for food by humans, including the scallop,
  a particularly big form of clam. When you order soup in New England,
  it's not unlikely that it will be clam chowder, a creamy, thick stew
  with potatoes and pieces of clam. When clam is a verb, it means "to
  dig clams on the beach," and if your friend offers to pay you 1000
  clams for your old car, she means "dollars."

  I know of a restaurant that served a fantastic clam chowder and was packed
  with customers every day at lunchtime.
* chowder :Covey:
[2018-10-19 Fri 13:25]
** Translate from English to Russian:                                 :drill:

 chowder
*** --->
  густая похлебка

  noun
   1. густая похлебка (chowder)

  DEFINITION

  noun
   1. a rich soup typically containing fish, clams, or corn with potatoes and onions.
      "clam chowder"


  Chowder is a thick, chunky soup that often contains fish or shellfish.
  New England is well known for its creamy, rich version of clam
  chowder.

  Chowder is somewhere between a soup and a stew — it's full of chunks
  of potato and onions, thick with bacon, fish, or vegetables, and
  sometimes eaten with crackers on the side or crumbled on top. Chowder
  is one of many words that distinctly originated in America, and it was
  included in the first edition of Noah Webster's dictionary of American
  English. Chowder comes from the pot in which it's cooked, chaudière,
  French for "a pot."

  I know of a restaurant that served a fantastic clam chowder and was packed
  with customers every day at lunchtime.
* dwindle                                                             :Covey:
[2018-10-19 Fri 13:26]
** Translate from English to Russian:                                 :drill:

 dwindle
*** --->
  истощаться

  verb
   1. сокращаться (shrink, contract, shorten, dwindle, depopulate, close in)
   2. терять значение (dwindle, recede into the background)
   3. уменьшаться (decrease, fall off, decline, diminish, lower, dwindle)
   4. истощаться (dwindle, run out, waste away, run down, run low, waste)
   5. ухудшаться (deteriorate, worsen, decline, degenerate, decay, dwindle)
   6. вырождаться (degenerate, deteriorate, dwindle, degrade)
   7. приходить в упадок (fall into decay, decline, decay, dwindle, degrade, dilapidate)

  DEFINITION

  verb
   1. diminish gradually in size, amount, or strength.
      "traffic has dwindled to a trickle"


  What do love, money, and the earth all have in common? All can
  dwindle, or shrink away, if we don't handle them properly.

  The word dwindle has a wonderfully descriptive, almost childlike sound
  to it, as though it belongs in a nursery rhyme. That might help you
  remember the meaning, which is to shrink away gradually, like the
  Cheshire Cat in "Alice in Wonderland," who dwindles away until nothing
  is left but his grin.

  Trust was gone, and
  business dwindled to almost nothing.
* misdeed                                                             :Covey:
[2018-10-19 Fri 17:43]
** Translate from English to Russian:                                 :drill:

 misdeed
*** --->
  проступок

  noun
   1. злодеяние (crime, atrocity, malfeasance, misdeed, misdoing)
   2. преступление (crime, offense, wrongdoing, misdemeanor, misdeed, perpetration)
   3. ошибка (error, mistake, fault, fallacy, flaw, misdeed)
   4. оплошность (oversight, gaffe, misstep, lapse, omission, misdeed)

  DEFINITION

  noun
   1. a wicked or illegal act.
      "Take some time to reflect on your past virtues and misdeeds ."


  A misdeed is a type of bad behavior, especially behavior that's
  immoral. If you get caught stealing someone’s lunch, you’ll be
  punished for your misdeed.

  A deed is an action, and a misdeed is a specific type of action. It’s
  one that's wicked, unethical, illegal, or just plain wrong. It’s the
  opposite of a good deed. Cheating on a test is a misdeed. So is
  cheating on your spouse. Stealing is a misdeed, as is any other crime.
  Politicians get caught in scandals when their misdeeds are discovered,
  such as lying or taking bribes. It’s from the Old English misdæd for
  "sin, evil.”

  The word scapegoat first
    occurred in the earliest English translation of the Bible, and it has
    come to mean any individual punished for the misdeeds of others.
* evade :Covey:
[2018-10-19 Fri 17:50]
** Translate from English to Russian:                                 :drill:

 evade
*** --->
  уклоняться

  verb
   1. уклоняться (dodge, avoid, shrink, evade, deviate, shy)
   2. увернуться (dodge, evade)
   3. избегать (avoid, shun, escape, evade, steer clear of, eschew)
   4. обходить (bypass, get round, skirt, evade, walk, sidestep)
   5. ускользать (escape, elude, slip, evade)
   6. увиливать (shirk, prevaricate, equivocate, dodge, evade, wriggle out of)
   7. отвиливать (evade, dodge)
   8. не поддаваться усилиям (evade)

  DEFINITION

  verb
   1. escape or avoid, especially by cleverness or trickery.
      "friends helped him to evade capture for a time"


  When you evade something, you escape it. You could evade a police
  chase by slipping into a secret alley, or you could evade your
  mother's questions about the missing cookies by slipping into another
  topic.

  Other things people like to evade? Death. Taxes. Creepy ex-boyfriends.
  The verb evade comes from Latin roots ex ("away) and vadere ("to
  walk"), meaning literally "to walk away or to escape." Definitely what
  you want to do with creepy ex-boyfriends.

  Master criminals
    rely on their ingenuity in order to evade the law when they are
    chased.
* abstain :Covey:
[2018-10-20 Sat 09:06]
** Translate from English to Russian:                                 :drill:

 abstain
*** --->
  воздерживаться

  verb
   1. воздерживаться (refrain, abstain, forgo, desist, keep, resist)
   2. не принимать участия (abstain)

  DEFINITION

  verb
   1. restrain oneself from doing or enjoying something.
      "abstaining from chocolate"
   2. formally decline to vote either for or against a proposal or motion.
      "forty-one voted with the opposition, and some sixty more abstained"


  If you abstain from something, you restrain yourself from consuming
  it. People usually abstain from things that are considered vices —
  like eating French fries every day for lunch.

  Roots of the word abstain are from the 14th-century French, "to
  withhold oneself," and the word often refers to people who hold
  themselves back from indulging in habits that are bad for them,
  physically or morally. Abstain can also mean to withhold a vote, and
  sometimes a difficult decision is stalled when government
  representatives abstain from voting one way or another.

  deliberately avoid using; abstain from.
* condemn                                                             :Covey:
[2018-10-20 Sat 09:08]
** Translate from English to Russian:                                 :drill:

 condemn
*** --->
  осуждать

  verb
   1. осуждать (condemn, judge, denounce, criticize, convict, censure)
   2. обречь (condemn)
   3. порицать (blame, censure, condemn, deplore, decry, reprove)
   4. приговаривать (sentence, condemn, adjudge)
   5. уличать (condemn, expose, show up, prove)
   6. браковать (condemn, cull, cast)
   7. конфисковать (confiscate, seize, impound, sequester, sequestrate, condemn)
   8. признавать негодным (disqualify, condemn)
   9. наглухо забивать (condemn)
  10. выносить приговор (convict, adjudicate, adjudge, condemn, judge)

  DEFINITION

  verb
   1. express complete disapproval of, typically in public; censure.
      "fair-minded people declined to condemn her on mere suspicion"
   2. sentence (someone) to a particular punishment, especially death.
      "the rebels had been condemned to death"


  You can condemn, or openly criticize, someone who is behaving
  inappropriately. If you are an animal rights activist, you would
  probably condemn someone for wearing fur.

  Condemn originally comes, through Old French, from the Latin word
  condemnāre, "to sentence, condemn." You may see politicians condemn
  each other in political ads during a campaign in hopes of improving
  their chances of winning an election. You also might hear of a convict
  being "condemned to death." In this sense of the word, to condemn
  still carries on its Latin meaning of "to sentence."

  "Her status as slave condemns her to a life of servitude , with little or no control over her future."
* reel :Covey:
[2018-10-20 Sat 09:15]
** Translate from English to Russian:                                 :drill:

 reel
*** --->
  бобина

  noun
   1. катушка (coil, bobbin, reel, spool, sheave)
   2. барабан (drum, reel, barrel, cylinder, roll, tambour)
   3. рулон (roll, web, reel, bolt, lap)
   4. шатание (reel, vacillation, stagger, wandering, play, roaming)
   5. мотовило (reel, reeler, swift)
   6. бобина (bobbin, spool, reel, magazine)
   7. рил (reel)
   8. часть (part, portion, piece, section, proportion, reel)
   9. рулетка (roulette, tape, reel, tape-measure, tape-line)
  10. шпулька (bobbin, spool, reel, quill, pirn, hasp)
  11. ворот (winch, windlass, pulley, capstan, neckband, reel)
  12. катушка для провода (reel)
  13. колебание (oscillation, swing, fluctuation, hesitation, wobble, reel)
  14. вихрь (vortex, swirl, whirl, whirlwind, eddy, reel)

  verb
   1. наматывать (reel up, wind, wind up, reel, coil, quill)
   2. сматывать (reel, wind up, reel off, hank, interwind)
   3. шататься (stagger, totter, falter, reel, gad, mosey)
   4. дрогнуть (falter, waver, flinch, reel, quail)
   5. пошатнуться (reel)
   6. водить хоровод (reel)
   7. наматывать на катушку (reel, spool, reel in, reel up)
   8. разматывать (unwind, uncoil, unreel, reel off, reel, wind off)
   9. танцевать рил (reel)
  10. отступать (back down, retreat, digress, back, depart, reel)
  11. кружиться (whirl, circle, spin, dance, swim, reel)
  12. спотыкаться (stumble, falter, trip, hobble, blunder, reel)
  13. идти пошатываясь (reel)
  14. вертеться (twirl, turn, spin, pivot, revolve, reel)
  15. чувствовать головокружение (reel, swim)
  16. шатнуться (be loose, reel, be unsteady)
  17. покачнуться (reel)
  18. качаться (sway, swing, shake, rock, dangle, reel)

  DEFINITION

  noun
   1. a cylinder on which film, wire, thread, or other flexible materials can be wound.
      "‘I have to keep rolling the thread reels which keeps my elbows moving,’ he said."
   2. a lively Scottish or Irish folk dance.
      "As a young officer in the Argyll and Sutherland Highlanders, he became adept at reels , strathspeys and sword dances."

  verb
   1. wind a line onto a reel by turning the reel.
      "That's his hand holding my spent target, after I emptied a round in it and reeled it in ."
   2. lose one's balance and stagger or lurch violently.
      "he punched Connolly in the ear, sending him reeling"
   3. dance a reel.
      "Anyone who wanted to dance could reel to the sound of the ceilidh band playing at the Butter Cross."


  A reel is a cylinder that can be wound with flexible material like
  film or fishing line. If you found dozens of reels of old home movies
  in your grandparents' attic, you'd search for a projector.

  You might find an old movie reel, a reel of copper wire, or a fishing
  reel. Use the reel on your fishing pole to reel in your fish! Yes,
  it’s a verb, too. And it’s a lively folk dance — or the music for it —
  from Scotland (Highland reel), or America (Virginia reel). As a verb,
  reel also means to sway from dizziness. If an ear infection messes
  with your balance, you might reel down the hall like you were drunk.

  If they meander or try to postpone for a later undefined call, reel
    them in and get them to come to the point.
* batch                                                               :Covey:
[2018-10-20 Sat 14:02]
** Translate from English to Russian:                                 :drill:

 batch
*** --->
  партия

  noun
   1. партия (party, game, batch, lot, part, installment)
   2. пакет (package, packet, pack, batch, parcel, bundle)
   3. серия (series, range, batch, part, suite, chapter)
   4. группа (group, party, bunch, class, series, batch)
   5. загрузка (loading, download, downloading, charge, batch)
   6. замес (batch)
   7. шихта (charge, batch, stock)
   8. пачка (pack, tutu, packet, package, sheaf, batch)
   9. кучка (knot, parcel, batch)
  10. количество хлеба (batch, baking)
  11. замес бетона (batch)
  12. партия выпеченного хлеба (batch)
  13. количество выпекаемого хлеба (batch)
  14. беч (batch)

  verb
   1. группировать программы (batch)
   2. пакетировать (batch)

  DEFINITION

  noun
   1. a quantity or consignment of goods produced at one time.
      "a batch of cookies"

  verb
   1. arrange (things) in sets or groups.
      "Here's a mechanism for batching them into a locked-and-loaded tool for firing them into the world."


  A batch is a completed group, collection, or quantity of something,
  especially something that's just been made. You might, for example,
  bake a batch of cookies to take to your new neighbor.

  A company that makes soap might deliver a batch, loaded on a truck, to
  a new store in Vermont, and if you manage a bakery you might declare,
  "That's it! This is our last batch of gingerbread until next year!" In
  computer lingo, a batch is, similarly, a group or collection of
  records. The Old English root, bæcce, means "something baked," from
  bacan, "bake."

  Time Consumers: Batch and Do Not Falter
* excessive                                                           :Covey:
[2018-10-21 Sun 08:22]
** Translate from English to Russian:                                 :drill:

 excessive
*** --->
  чрезмерное

  adjective
   1. чрезмерный (excessive, over, undue, superfluous, exceeding, extreme)
   2. излишний (surplus, excessive, superfluous, unnecessary, redundant, needless)
   3. безмерный (immense, immeasurable, measureless, excessive, unmeasured, exceeding)

  noun
   1. эксцессив (excessive)
   2. чрезмерная степень (excessive)

  DEFINITION

  adjective
   1. more than is necessary, normal, or desirable; immoderate.
      "he was drinking excessive amounts of brandy"


  Excessive means beyond what is typical or normal. When something is
  excessive, there's way too much.

  Excessive refers to something that is extra — usually in a negative
  way. A 90-second drum solo in a two-minute song is excessive. Getting
  down on your knees and kissing someone's feet to thank them for a
  favor is excessive, unless they gave you their firstborn. Often this
  means something that exceeds the bounds of good taste, or is
  extravagant and inappropriately expensive. You should dress up for
  dinner, but wearing a ball gown to a diner is excessive.

  Excessive focus on P results in ruined
  health, worn-out machines, depleted bank accounts, and broken
  relationships.
* deteriorate                                                         :Covey:
[2018-10-21 Sun 14:02]
** Translate from English to Russian:                                 :drill:

 deteriorate
*** --->
  ухудшать

  verb
   1. ухудшаться (deteriorate, worsen, decline, degenerate, decay, slip)
   2. ухудшать (deteriorate, worsen, impair, aggravate, make worse, deprave)
   3. портиться (spoil, deteriorate, corrupt, rot, decay, give way)
   4. разрушаться (break, break down, disintegrate, deteriorate, crumble, decay)
   5. вырождаться (degenerate, deteriorate, dwindle, degrade)
   6. портить (spoil, deteriorate, corrupt, ruin, mar, damage)
   7. дегенерировать (deteriorate)

  DEFINITION

  verb
   1. become progressively worse.
      "relations between the countries had deteriorated sharply"


  When something gets worse due to neglect or an unfortunate health
  problem, stuff starts to deteriorate — or fall apart.

  The word deteriorate describes anytime something gets worse. Due to
  neglect, a relationship can deteriorate but so can the American
  highway system. Sadly, there seems to be no end to applications for
  the word deteriorate. And, the truth is at a certain age we all start
  deteriorating too.

  As you open yourself to the next three habits—the habits of Public
  Victory—you will discover and unleash both the desire and the resources to
  heal and rebuild important relationships that have deteriorated, or even
  broken.
* possess :Covey:
[2018-10-21 Sun 14:13]
** Translate from English to Russian:                                 :drill:

 possess
*** --->
  обладать

  verb
   1. обладать (have, possess, enjoy, own, be possessed of, rejoice)
   2. владеть (own, possess, hold, master, wield, command)
   3. овладевать (master, acquire, possess, hold, dominate, grip)
   4. сохранять (save, keep, retain, preserve, maintain, possess)
   5. захватывать (grab, grip, capture, seize, grasp, possess)
   6. удерживать (hold, hold back, refrain, hold down, retain, possess)

  DEFINITION

  verb
   1. have as belonging to one; own.
      "I do not possess a television set"
   2. (of a demon or spirit, especially an evil one) have complete power over (someone) and be manifested through their speech or actions.
      "she was possessed by the Devil"
   3. have sexual intercourse with (a woman).
   4. maintain (oneself or one's mind or soul) in a state or condition of patience or quiet.
      "I tried to possess my soul in patience and to forget how hungry I was"


  To possess something is to have or own it. You can possess a physical
  object, you can possess a particular quality or skill, or you can
  possess control or influence over someone.

  Related words are possessive (describing those who hold onto people or
  things in a controlling way), and possessed, as in a person being
  possessed by an idea or even by a demon. This verb is from Middle
  French possesser "to own," from Latin possidēre, from potis "able,
  having the power" plus sedēre "to sit."

  Animals do not
   possess this ability.
* dominion :Covey:
[2018-10-21 Sun 14:13]
** Translate from English to Russian:                                 :drill:

 dominion
*** --->
  владычество

  noun
   1. власть (power, authority, rule, control, grip, dominion)
   2. владычество (dominion, rule, mastery)
   3. доминион (dominion)
   4. владение (possession, ownership, hold, domain, tenure, dominion)
   5. суверенное право (dominion)

  DEFINITION

  noun
   1. sovereignty; control.
      "man's attempt to establish dominion over nature"
   2. the territory of a sovereign or government.
      "the Angevin dominions"


  When you are in charge of something or rule it, you have dominion over
  it. The most famous use of the word occurs in the Christian Bible,
  when God grants people dominion over other animals.

  If you know the word domination, then you won't be surprised that
  dominion also has to do with a type of ruling over others. This is an
  old-fashioned and Biblical-sounding word for having power. A king has
  dominion over his kingdom. You'd never say the President has dominion,
  because we live in a democracy. Dominion implies more power than that
  — even absolute power. A dominion can also be an area or territory
  controlled by a larger country or state.

  This is the reason why man has
   dominion over all things in the world and why he can make significant
   advances from generation to generation.
* upbringing :Covey:
[2018-10-24 Wed 18:26]
** Translate from English to Russian:                                 :drill:

 upbringing
*** --->
  воспитание

  noun
   1. воспитание (education, breeding, upbringing, training, nurture, accomplishment)

  DEFINITION

  noun
   1. the treatment and instruction received by a child from its parents throughout its childhood.
      "his Quaker upbringing influenced his character"


  Your upbringing is how you were raised as a child. You might have had
  a rough upbringing or a gentler one, but at least you made it this
  far.

  Looking at the base “bring” in upbringing, we find a Germanic origin
  meaning "to carry." You might consider the "carry" idea as a way to
  remember the word, considering a parent "carries" a child to
  adulthood, providing what then becomes the child’s upbringing.

  Your
  upbringing, your childhood experience essentially laid out your personal
  tendencies and your character structure.
* repugnant :Covey:
[2018-10-24 Wed 18:29]
** Translate from English to Russian:                                 :drill:

 repugnant
*** --->
  отвратительный

  adjective
   1. отвратительный (disgusting, hideous, heinous, abominable, revolting, repugnant)
   2. противный (nasty, contrary, disgusting, repugnant, obnoxious, yucky)
   3. противоречащий (contradictory, inconsistent, dissonant, repugnant, contravening, gainsaying)
   4. невыносимый (unbearable, insufferable, intolerable, unendurable, impossible, repugnant)
   5. несовместимый (incompatible, inconsistent, irreconcilable, incongruous, contradictory, repugnant)

  DEFINITION

  adjective
   1. extremely distasteful; unacceptable.
      "the thought of going back into the fog was repugnant to him"
   2. in conflict with; incompatible with.
      "a bylaw must not be repugnant to the general law of the country"


  Repugnant refers to something you detest so thoroughly it threatens to
  make you physically sick, like the idea of marrying your sister. Or
  wearing last year's jeans.

  A repugnant thing is a thing offensive, detestable, or obscene. It can
  be repugnant to your mind or your morals. It can also be physically
  repugnant, like the smell that comes from a restaurant’s dumpster,
  which hasn't been emptied since the very exciting "Omelet Week," way
  back at the beginning of August. Makes you want to "re-PLUG-nant" your
  nose!

  He was imprisoned in the death
  camps of Nazi Germany, where he experienced things that were so repugnant
  to our sense of decency that we shudder to even repeat them.
* indignity                                                           :Covey:
[2018-10-24 Wed 18:30]
** Translate from English to Russian:                                 :drill:

 indignity
*** --->
  унижение

  noun
   1. унижение (humiliation, abjection, indignity, abasement, debasement, mortification)
   2. оскорбление (insult, abuse, affront, offense, outrage, indignity)
   3. пренебрежение (neglect, disregard, disdain, scorn, slight, indignity)
   4. унизительность (indignity)

  DEFINITION

  noun
   1. treatment or circumstances that cause one to feel shame or to lose one's dignity.
      "the indignity of needing financial help"


  An indignity is something embarrassing. An indignity is usually
  something that happens to us rather than something we do ourselves.

  As you might guess from that negative prefix in-, an indignity is a
  word that takes dignity (or self-esteem) away. If you find a fly in
  your soup, that's an indignity — not to mention protein. If you're
  making a speech and you realize your fly is open, that's a major
  indignity. Many people find waiting in line a long time to be an
  indignity. When you say "This is an indignity!" you're really saying,
  "I'm better than this, and I shouldn't have to deal with it." Needless
  to say, life is full of indignities.

  Frankl
  himself suffered torture and innumerable indignities, never knowing from
  one moment to the next if his path would lead to the ovens or if he would
  be among the “saved” who would remove the bodies or shovel out the ashes
  of those so fated.
* captor                                                              :Covey:
[2018-10-24 Wed 18:31]
** Translate from English to Russian:                                 :drill:

 captor
*** --->
  капер

  noun
   1. капер (privateer, captor, caper, corsair)
   2. взявший в плен (captor)

  adjective
   1. взявший (captor)
   2. взявший в плен (captor)
   3. захвативший в плен (captor)

  DEFINITION

  noun
   1. a person or animal that catches or confines another.
      "This seemed to catch their captor by surprise, but he quickly regained his composure."


  Someone who catches a person or animal and keeps them confined or
  imprisoned is a captor. Visiting the zoo, you might find yourself
  wondering if the lions see the zookeepers as friends or as captors.

  The word captor sounds a little bit like capture, and it's no
  coincidence — they're both rooted in the Latin capere, "to take, hold,
  or seize." So if you capture a cricket and keep it in a little cage,
  you are its captor. And, when a police force captures a criminal and
  puts them in prison, the police become captors too. The original
  meaning of captor was actually "a censor."

  One day, naked and alone in a small room, he began to become aware of what
  he later called “the last of the human freedoms”—the freedom his Nazi
  captors could not take away.
* intact :Covey:
[2018-10-24 Wed 18:32]
** Translate from English to Russian:                                 :drill:

 intact
*** --->
  неповрежденный

  adjective
   1. неповрежденный (intact, uninjured, uncrippled, inviolate)
   2. целый (whole, entire, all, full, integral, intact)
   3. нетронутый (intact, untouched, pristine, virgin, untapped, unaffected)

  DEFINITION

  adjective
   1. not damaged or impaired in any way; complete.
      "the church was almost in ruins, but its tower remained intact"


  If something is intact it's still in one piece. If you'd like your
  sand castle to remain intact, I suggest you build it away from the
  water.

  The Latin word intactus means “untouched,” but today something is
  intact if it's whole, if it hasn't fallen apart. After a long day at
  work, you might feel lucky to be intact. Your letter to the post
  office states that you would prefer your packages to arrive intact
  from now on.

  His basic identity was intact.
* endowment :Covey:
[2018-10-24 Wed 18:34]
** Translate from English to Russian:                                 :drill:

 endowment
*** --->
  дарование

  noun
   1. дар (gift, grant, donation, talent, endowment, boon)
   2. вклад (contribution, deposit, investment, endowment, deposition, holding)
   3. пожертвование (donation, donating, endowment, contribution, offering, grant)
   4. дарование (gift, endowment, ability, faculty)
   5. надел (allotment, portion, endowment)
   6. дарение (donation, giving, grant, endowment)
   7. талант (talent, gift, endowment, dowry)
   8. завещание (will, testament, bequest, devise, bequeathing, endowment)

  DEFINITION

  noun
   1. the action of endowing something or someone.
      "he tried to promote the endowment of a Chair of Psychiatry"


  An endowment is a gift. It might be money given to an institution like
  a college. Or, an endowment might be a natural gift, say of a physical
  attribute or a talent. If you lack the endowment of musical talent,
  you could play the tambourine.

  To endow means "to give or bequeath," and the background of the word
  endowment goes back to the 15th Century, where it was used to refer to
  money or property that is given to an institution. An example can be
  found in the National Endowment for the Arts, an organization
  dedicated to providing grants to fund artistic endeavors. Your natural
  endowments — speed, agility, endurance — make you an excellent soccer
  player. If only you could wake up in time for practice.

  In the midst of the most degrading circumstances imaginable, Frankl used
  the human endowment of self-awareness to discover a fundamental principle
  about the nature of man: Between stimulus and response, man has the
  freedom to choose.
* conscience :Covey:
[2018-10-24 Wed 18:35]
** Translate from English to Russian:                                 :drill:

 conscience
*** --->
  совесть

  noun
   1. совесть (conscience, breast)
   2. сознание (consciousness, conscious, conscience, sense, feeling, recognition)

  DEFINITION

  noun
   1. an inner feeling or voice viewed as acting as a guide to the rightness or wrongness of one's behavior.
      "he had a guilty conscience about his desires"


  A conscience is a built-in sense of what's right and what's wrong.
  That sick feeling in your stomach after you meanly told your younger
  brother the truth about Santa Claus? That might be your conscience
  bothering you.

  The word conscience contains the word science, which comes from the
  Latin word scientia, meaning "to know" or "knowledge." You can think
  of your conscience as your knowledge of yourself, especially when it
  comes to your own morals, or your feelings about right and wrong.
  Pangs of conscience, which feel like an uncomfortable inner voice, are
  helpful when you're trying to decide the right thing to do in a
  particular situation.

  We have conscience—a deep
  inner awareness of right and wrong, of the principles that govern our
  behavior, and a sense of the degree to which our thoughts and actions are
  in harmony with them.
* empower :Covey:
[2018-10-24 Wed 18:41]
** Translate from English to Russian:                                 :drill:

 empower
*** --->
  уполномочивать

  verb
   1. уполномочивать (authorize, empower, commission, delegate, accredit, authorise)
   2. давать возможность (enable, permit, let, empower)
   3. разрешать (allow, authorize, resolve, permit, solve, empower)

  DEFINITION

  verb
   1. give (someone) the authority or power to do something.
      "nobody was empowered to sign checks on her behalf"


  Empower means "give power or authority to." When you educate children
  and believe in them, you empower those kids to go after their dreams.

  Empower might seem like a new word, but it's been around since the
  17th century. Today, empower often refers to helping someone realize
  their abilities and potential, perhaps for the first time. For
  example, in the 1960s, when women felt like second-class citizens, the
  women's movement empowered them to stand up and demand their equal
  rights.

  Because we are, by nature, proactive, if our lives are a function of
  conditioning and conditions, it is because we have, by conscious decision
  or by default, chosen to empower those things to control us.
* internalize                                                         :Covey:
[2018-10-24 Wed 18:43]
** Translate from English to Russian:                                 :drill:

 internalize
*** --->
  усваивать

  verb
   1. усваивать (assimilate, digest, internalize, adopt, master, imbibe)

  DEFINITION

  verb
   1. make (attitudes or behavior) part of one's nature by learning or unconscious assimilation.
      "Of course many of us have internalized toxic attitudes such as racism and homophobia, Gage writes."
   2. incorporate (costs) as part of a pricing structure, especially social costs resulting from the manufacture and use of a product.
      "You could say we should internalize those costs in prices, so that it affects people's behaviour."


  If you feel anger, pain, fear or hurt but never show it, you
  internalize it — you keep it inside.

  If you think about the prefix inter- which always indicated something
  within, you have the meaning of the adjective internalize, "to keep or
  take something in." It can be used in either a positive or negative
  way. If you are a debater who internalizes a topic, then you know it
  inside and out. On the other hand, you're not doing yourself any
  favors if you internalize your guilt.

  Proactive people are
  driven by values—carefully thought about, selected and internalized
  values.
* crucible                                                            :Covey:
[2018-10-30 Tue 09:06]
** Translate from English to Russian:                                 :drill:

 crucible
*** --->
  тигель

  noun
   1. тигель (crucible, pot, melting pot, platen, bowl, platten)
   2. суровое испытание (crucible, ordeal)

  DEFINITION

  noun
   1. a ceramic or metal container in which metals or other substances may be melted or subjected to very high temperatures.
      "Molten magnesium does not attack iron in the same way as molten aluminum, and the metal can therefore be melted and held at temperature in crucibles fabricated from ferrous materials."


  A crucible is a melting pot used for extremely hot chemical reactions
  — the crucible needs to be melt-proof.

  Literally, a crucible is a vessel used for very hot processes, like
  fusing metals. Another meaning of the word is a very significant and
  difficult trial or test. Scaling Mt. Everest with your legs tied
  together would be a crucible, as would swimming the English Channel
  blindfolded. Whether or not to have children is a crucible for many
  people. The title of Arthur Miller’s play The Crucible is an example
  of this meaning.

  In fact, our most difficult experiences become the crucibles
  that forge our character and develop the internal powers, the freedom to
  handle difficult circumstances in the future and to inspire others to do
  so as well.
* ennoble                                                             :Covey:
[2018-10-30 Tue 09:08]
** Translate from English to Russian:                                 :drill:

 ennoble
*** --->
  облагораживать

  verb
   1. облагораживать (ennoble, elevate, refine, dignify, humanize, subtilize)
   2. жаловать дворянством (ennoble)

  DEFINITION

  verb
   1. give (someone) a noble rank or title.
      "When he was ennobled in 1964, someone remarked he should take the title Lord Corridor of Power."


  To ennoble someone is to make them a Lord or a Baroness — to bestow a
  noble title upon them. The Queen of England has the power to ennoble
  people, turning Paul McCartney into Sir Paul McCartney, for example.

  One way to use the verb ennoble is to mean, literally, "make someone a
  noble or a member of the nobility." It can also mean "bestow or lend
  dignity to" or "make dignified." You could say, "Reading great books
  ennobles the mind," or "Treating others with kindness ennobles a
  person." Ennoble comes from the Old French ennoblir, from the prefix
  en-, "put in," and the Latin root nobilis, "excellent, superior, or
  splendid."

  Nothing has a greater, longer lasting impression upon another person than
  the awareness that someone has transcended suffering, has transcended
  circumstance, and is embodying and expressing a value that inspires and
  ennobles and lifts life.
* protracted                                                          :Covey:
[2018-10-30 Tue 09:09]
** Translate from English to Russian:                                 :drill:

 protracted
*** --->
  затянувшийся

  adjective
   1. затяжной (protracted, lingering, chronic, torpid)
   2. длительный (long, durable, prolonged, longer, extended, protracted)
   3. затянувшийся (protracted, prolonged, long-drawn, long-drawn-out)

  DEFINITION

  adjective
   1. lasting for a long time or longer than expected or usual.
      "a protracted and bitter dispute"

  verb
   1. prolong.
      "he had certainly taken his time, even protracting the process"
   2. draw (a plan, etc.) to scale.


  Something protracted has been drawn out, usually in a tedious way.
  Protracted things are long and seem like they're never going to end.

  Anything protracted is lasting longer than you would like. A speech
  that seems to go on forever is protracted. If an employer and a union
  can't reach an agreement, there could be a protracted strike. Before a
  movie, the previews are almost always protracted — they never seem to
  stop. If something is long and annoying, and there's no good reason it
  couldn't be shorter, it's protracted.

  She returned from
  those protracted and difficult sessions almost transfixed by admiration
  for her friend’s courage and her desire to write special messages to be
  given to her children at different stages in their lives.
* pushy :Covey:
[2018-10-30 Tue 09:14]
** Translate from English to Russian:                                 :drill:

 pushy
*** --->
  напористый

  adjective
   1. напористый (assertive, pushy, punchy, pushing, feisty, self-assertive)
   2. пробивной (punchy, disruptive, pushy, pushing, hotshot)
   3. нахальный (impudent, cheeky, sassy, brash, cocky, pushy)

  DEFINITION

  adjective
   1. excessively or unpleasantly self-assertive or ambitious.
      "She is ambitious but too pushy even for parliamentary circles."


  Pushy people are aggressive and bold about getting what they want. A
  pushy used car salesperson will make you feel bullied into buying
  something even if you were just interested in admiring convertibles.

  If you're pushy, you're not afraid to let your ambition show, or to
  boss other people around. Pushy parents might argue with a teacher who
  gives their child a bad grade, and pushy newspaper reporters will
  invade your privacy to get a good story. This adjective was originally
  used, around 1891, to describe a cow. Just a few years later, it began
  to describe people as well.

  Taking initiative does not mean being pushy, obnoxious, or aggressive.
* obnoxious :Covey:
[2018-10-30 Tue 09:14]
** Translate from English to Russian:                                 :drill:

 obnoxious
*** --->
  противный

  adjective
   1. неприятный (unpleasant, disagreeable, nasty, distasteful, obnoxious, unpalatable)
   2. противный (nasty, contrary, disgusting, repugnant, obnoxious, yucky)
   3. отвратительный (disgusting, hideous, heinous, abominable, revolting, obnoxious)
   4. несносный (obnoxious)

  DEFINITION

  adjective
   1. extremely unpleasant.
      "I assume he was not aware of the fact that he was in a church and being extremely obnoxious ."


  If something is obnoxious, it's annoying and unpleasant. Generally,
  people like to avoid obnoxious folks.

  If something is driving you absolutely crazy, it's probably obnoxious.
  Yelling and stomping your feet is obnoxious. Poking someone repeatedly
  is obnoxious. Driving like a maniac is obnoxious. If the teacher comes
  in and finds students jumping up and down and throwing books, she
  might say, "Stop being so obnoxious!" Anytime someone is obnoxious,
  someone else probably wants them to stop it.

  Taking initiative does not mean being pushy, obnoxious, or aggressive.
* counsel                                                             :Covey:
[2018-10-30 Tue 09:15]
** Translate from English to Russian:                                 :drill:

 counsel
*** --->
  адвокат

  noun
   1. адвокат (lawyer, attorney, counsel, advocate, solicitor, barrister)
   2. совет (advice, council, board, Soviet, counsel, tip)
   3. юрисконсульт (legal adviser, counsel, lawyer, solicitor)
   4. совещание (conference, session, consultation, counsel, council, palaver)
   5. обсуждение (discussion, consideration, deliberation, dispute, airing, counsel)
   6. планы (counsel, dispositions)
   7. намерение (intention, intent, plan, aim, purpose, counsel)
   8. группа адвокатов (counsel)

  verb
   1. рекомендовать (recommend, advise, commend, counsel)
   2. давать совет (counsel)
   3. напутствовать (address, counsel)

  DEFINITION

  noun
   1. advice, especially that given formally.
      "As for the European Union, the situation is really bad, though wiser counsels may prevail in the next week or so."
   2. the lawyer or lawyers conducting a case.
      "the counsel for the defense"

  verb
   1. give advice to (someone).
      "he was counseled by his supporters to return to Germany"


  When you give counsel or counsel someone, you give advice. If your
  neighbor is suing you because your dog keeps eating his begonias, you
  might seek the counsel of a dog trainer or, if that doesn't work, a
  lawyer.

  You can get professional counsel — from a minister or psychiatrist or
  someone else trained in counseling — or you can get counsel from
  anyone you trust. You can ask your stylish friend to counsel you on
  your hairstyle, or you could write to Dear Abby for counsel on your
  lovelife. Counsel is also what you call a lawyer who represents you in
  court. In your begonia-eating dog case, your lawyer would be counsel
  for the defense.

  Over the years, I have frequently counseled people who wanted better jobs
  to show more initiative—to take interest and aptitude tests, to study the
  industry, even the specific problems the organizations they are interested
  in are facing, and then to develop an effective presentation showing how
  their abilities can help solve the organization’s problem.
* demeaning :Covey:
[2018-10-30 Tue 09:17]
** Translate from English to Russian:                                 :drill:

 demeaning
*** --->
  унизительно

  verb
   1. унижать (humiliate, degrade, stoop, put down, demean, humble)
   2. унижаться (degrade, grovel, stoop, demean, debase, condescend)
   3. вести себя (behave, act, do, conduct oneself, carry, walk)

  DEFINITION

  adjective
   1. causing someone to lose their dignity and the respect of others.
      "the poster was not demeaning to women"

  verb
   1. cause a severe loss in the dignity of and respect for (someone or something).
      "I had demeaned the profession"
   2. conduct oneself in a particular way.
      "no man demeaned himself so honorably"


  The adjective demeaning describes something that lowers a person's
  reputation or dignity. If your boss always asks you to pick up her dry
  cleaning and get her coffee, you might feel like you usually get the
  demeaning jobs.

  The adjective demeaning comes from the verb demean, which itself is
  based on the construction of the word "debase." The word demean has
  two almost opposite meanings, to degrade and to conduct oneself in a
  particular manner, usually a proper one. The adjective, however,
  always describes something that is degrading. Overhearing two friends
  gossiping about you can be a demeaning experience, even if they're
  just criticizing your new haircut.

  Holding people to the responsible course is not demeaning; it is
  affirming.
* affirming :Covey:
[2018-10-30 Tue 09:18]
** Translate from English to Russian:                                 :drill:

 affirming
*** --->
  подтверждая

  verb
   1. утверждать (claim, affirm, assert, say, maintain, approve)
   2. подтверждать (confirm, reaffirm, acknowledge, affirm, support, verify)
   3. торжественно заявлять (affirm, asseverate, testify, protest)
   4. скреплять подписью (endorse by signature, countersign, affirm, ratify)

  DEFINITION

  verb
   1. state as a fact; assert strongly and publicly.
      "he affirmed the country's commitment to peace"
   2. offer (someone) emotional support or encouragement.
      "there are five common ways parents fail to affirm their children"


  To affirm something is to give it a big "YES" or to confirm that it is
  true.

  The verb affirm means to answer positively, but it has a more weighty
  meaning in legal circles. People are asked to swear an oath or affirm
  that they will tell the truth in a court of law. Lawyers may ask
  people to affirm facts, and judges may affirm rulings. In these cases,
  affirm means to verify or attest to the validity of something.

  Holding people to the responsible course is not demeaning; it is
  affirming.
* uninhibited :Covey:
[2018-10-30 Tue 09:21]
** Translate from English to Russian:                                 :drill:

 uninhibited
*** --->
  раскованный

  adjective
   1. раскованный (uninhibited, unselfconscious, unshod)
   2. свободный (free, spare, leisure, loose, easy, uninhibited)
   3. несдерживаемый (uninhibited)

  DEFINITION

  adjective
   1. expressing one's feelings or thoughts unselfconsciously and without restraint.
      "fits of uninhibited laughter"


  The prefix "un-" means "not," making the meaning of uninhibited "not
  inhibited, not restrained or holding back." Someone who is uninhibited
  is not afraid to act however he or she wishes.

  Uninhibited is the opposite of inhibited, from the Latin inhibēre, "to
  prohibit or hinder." In the late 19th century the word took on a new
  importance to psychologists, describing a person not afraid to express
  emotions, even in public. The following quote from writer Norman
  Podhoretz gives a contextual definition: "Creativity represents a
  miraculous coming together of the uninhibited energy of the child with
  its apparent opposite and enemy, the sense of order imposed on the
  disciplined adult intelligence."

  At one time I worked with a group of people in the home improvement
  industry, representatives from twenty different organizations who met
  quarterly to share their numbers and problems in an uninhibited way.

* abdicated :Covey:
[2018-10-30 Tue 17:21]

** Translate from English to Russian:                                 :drill:

 abdicated

*** --->
  отрекся

  verb
   1. отказываться (refuse, deny, give up, waive, reject, disclaim)
   2. отрекаться (renounce, deny, repudiate, retract, abdicate, disown)
   3. слагать полномочия (abdicate)

  DEFINITION

  verb
   1. (of a monarch) renounce one's throne.
      "in 1918 Kaiser Wilhelm abdicated as German emperor"


  Sometimes someone in power might decide to give up that power and step
  down from his or her position. When they do that, they abdicate their
  authority, giving up all duties and perks of the job.

  The original meaning of the verb abdicate came from the combination of
  the Latin ab- "away" and dicare "proclaim." (Note that in the charming
  relationships between languages with common roots, the Spanish word
  for "he says" is dice, which comes directly from dicare.) The word
  came to refer to disowning one's children, and it wasn't until the
  17th century that the first use of the word relating to giving up
  power or public office was recorded.

  If our feelings control our actions, it is because we have abdicated
  our responsibility and empowered them to do so.

* absolving :Covey:
[2018-10-31 Wed 19:00]

** Translate from English to Russian:                                 :drill:

 absolving

*** --->
  оправдывающий

  verb
   1. освобождать (rid, free, exempt, release, loose, liberate)
   2. отпускать (let go, release, dismiss, loosen, absolve, set loose)
   3. прощать (forgive, pardon, excuse, remit, overlook, absolve)
   4. оправдывать (justify, warrant, defend, excuse, acquit, explain)
   5. избавлять от ответственности (absolve)

  DEFINITION

  verb
   1. set or declare (someone) free from blame, guilt, or responsibility.
      "the pardon absolved them of any crimes"


  To be absolved is to be let off the hook, to be set free from a
  certain obligation or to be forgiven for a wrongdoing. The Church may
  absolve you of your sins, but that won't absolve you of the need to
  attend mass.

  The Latin absolvere, which means "to set free," is the root of the
  word absolve. In the religious sense, to be absolved means to be truly
  forgiven in the eyes of the Lord, which must feel like being set free.
  In a more mundane everyday usage, absolve can be used to describe
  being let off the hook. For instance, putting a campaign poster in
  your window does not absolve you of the responsibility to vote.

  But they did it endlessly, absolving themselves of responsibility in
  the name of the president’s weaknesses.
