-*- coding: utf-8 -*-


* floss :satellite:
[2018-05-29 Tue 16:58]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       0719a10e-91cc-4190-b4dc-360e28516572
   :END:

 floss

*** --->
  зубочистка

  noun
   1. зубочистка (toothpick, floss, quill)
   2. ручей (stream, creek, brook, rivulet, groove, floss)
   3. шелк-сырец (raw silk, floss, filoselle)

  DEFINITION

  noun
   1. the rough silk enveloping a silkworm's cocoon.
      "Since mankind discovered the wonder of the silkworm's floss , it has been used for the costliest of garments."

  verb
   1. clean between (one's teeth) with dental floss.
      "I flossed my teeth"


  Floss is what you use to clean between your teeth. Dental floss is a
  strong, thick thread that can reach small pieces of food in tight
  spaces.

  Your dentist will be happy with you if you really do use floss every
  day — and to do this is to floss. Other types of floss are soft
  threads with different uses: some floss is made for stitching or
  embroidering designs on fabric, and the strands of silk spun by a
  silkworm are also floss. The origin of this word is uncertain, but one
  guess connects it to floche, "tuft of wool" in French.

  That gunk between your teeth that comes out when you floss?

* harmful :Holmes:
[2018-05-29 Tue 17:00]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       da03011c-4970-4085-b5e6-434be0c04a47
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:57]
   :END:

 harmful

*** --->
  вредный

  adjective
   1. вредный (harmful, adverse, detrimental, pernicious, bad, deleterious)
   2. пагубный (pernicious, harmful, fatal, destructive, malign, evil)
   3. губительный (harmful, ruinous, fatal, baneful, subversive, blasting)
   4. тлетворный (pestilential, pestilent, harmful)
   5. разлагающий (harmful)

  DEFINITION

  adjective
   1. causing or likely to cause harm.
      "shield the planet from harmful cosmic rays"


  Things that are harmful hurt people, or are likely to hurt them.
  Listening to loud music through headphones can be harmful to your
  hearing.

  Harmful is an adjective that comes in handy when you're talking about
  things that cause injury to someone or damage something. Burning coal
  can be harmful to the environment, and eating too much candy can be
  harmful for your teeth. Harmful words can hurt someone's feelings and
  harmful actions might put them in danger. The Old English hearm,
  "hurt, evil, or grief," is at the root of harmful.

  No one wants it, and it's harmful if it stays.
* scarcely :satellite:
[2018-05-29 Tue 17:08]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       bed0ceb1-6894-4ac8-a046-fa10bfa60a2b
   :END:

 scarcely
*** --->
  едва

  adverb
   1. едва (barely, hardly, scarcely, just, slightly, faintly)
   2. едва ли (hardly, scarcely, unlikely, scarce, ill, illy)
   3. вряд ли (hardly, unlikely, scarcely, scarce)
   4. с трудом (hardly, hard, scarcely, heavily, ill, scarce)
   5. еле (hardly, scarcely)
   6. только что (just, newly, freshly, scarcely, this moment, scarce)
   7. не совсем (scarcely)
   8. как только (instant, scarcely, no sooner than, scarce, ever as)
   9. еле-еле (barely, faintly, scarcely, scant)

  DEFINITION

  adverb
   1. only just; almost not.
      "her voice is so low I can scarcely hear what she is saying"


  Scarcely means just before, hardly, or “almost not.” If you had
  scarcely made it to bed when the sun started to rise, you are probably
  pretty tired by now.

  Scarcely may have just made it in the nick of time and by the skin of
  its teeth, but it’s here now, even if it is just barely hanging on —-
  which means you can scarcely accuse it of not showing up. Though an ly
  adverb, scarcely is unusual in that it is not so much a descriptor of
  its root adjective as a synonym of the adverb form scarce. If you
  scarcely believe me, look it up for yourself!

  "he could [scarcely fathom] the idea that people actually
     lived in Las Vegas"
* feat                                                            :satellite:
[2018-05-29 Tue 19:28]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       d574d4f1-6fa4-4313-a50e-884284264377
   :END:

 feat
*** --->
  подвиг

  noun
   1. подвиг (feat, exploit, deed, achievement, act of bravery, performance)
   2. проявление большой ловкости (feat)
   3. проявление большого искусства (feat)

  adjective
   1. ловкий (deft, clever, dexterous, nimble, artful, feat)
   2. искусный (cunning, adept, skilled, skillful, skilful, feat)

  DEFINITION

  noun
   1. an achievement that requires great courage, skill, or strength.
      "the new printing presses were considerable feats of engineering"


  A feat is an exemplary, even bold achievement, often an act of great
  courage or skill. Getting your cat to wear a leash was quite a feat.

  The noun feat developed from the Latin facere, meaning "make do."
  Today, it gets applied to a deed that's noble or out of the ordinary.
  Have you ever accomplished amazing feats in your dreams, like flying?
  If so, I hope you didn't wake up on the roof. Maybe you perform feats
  of daring in your everyday life, if you're a firefighter or a
  tightrope walker. If you're afraid of heights, just taking the glass
  elevator counts as a courageous feat!

  But his insights into the human mind [rival] his greatest feats of
  criminal justice.
* instant :satellite:
[2018-06-01 Fri 16:28]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       29697b78-3950-4cd8-8d62-1eb7d95441ed
   :END:

 instant
*** --->
  мгновенное

  noun
   1. момент (moment, point, momentum, instant, minute, factor)
   2. мгновение (instant, moment, flash, second, minute, twinkling)

  adjective
   1. немедленный (instant, immediate, instantaneous)
   2. растворимый (soluble, instant, dissoluble, resolvable, resoluble)
   3. текущий (current, actual, flowing, operating, running, instant)
   4. настоятельный (urgent, imperative, insistent, pressing, instant, clamorous)
   5. текущего месяца (instant)
   6. безотлагательный (urgent, immediate, speedy, instant, importunate)

  adverb
   1. как только (instant, scarcely, no sooner than, scarce, ever as)

  DEFINITION

  adjective
   1. happening or coming immediately.
      "the offense justified instant dismissal"
   2. urgent; pressing.
      "an instant desire to blame others when things go wrong"
   3. (in business letters) of the current month.
      "your letter of the 6th instant"
   4. of the present moment.
      "In the instant case, the direct given by the judge has not been shown to be inappropriate in the circumstances."

  noun
   1. a precise moment of time.
      "come here this instant!"
   2. a very short space of time; a moment.
      "for an instant the moon disappeared"
   3. instant coffee.
      "Many sins are forgivable, but charging handsomely for coffee that comes directly from an outsized tin of own-label instant is not one of them."


  An instant is a very short time. In combinations like instant coffee
  and instant replay it means available right away without a wait.

  Instant and moment mean the same thing if you are talking about a
  particular time in the past like you remember the instant or moment
  you realized that you had won the lottery. However, the two words are
  very different when talking about time in the future. "I'll be there
  in an instant" means you're coming as quickly as possible, whereas if
  you say "I'll be there in a moment," someone is going to have to wait
  a bit for you.

  We understand and believe in [the same instant]
* potent :Holmes:
[2018-06-02 Sat 10:20]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       74adc8f1-7782-44a7-9b3c-5e9ace7002fe
   :END:

 potent
*** --->
  сильнодействующий

  adjective
   1. мощный (powerful, potent, mighty, heavy, forceful, sledgehammer)
   2. сильный (strong, keen, powerful, severe, heavy, potent)
   3. сильнодействующий (potent, powerful, drastic, stiff)
   4. могущественный (powerful, mighty, potent, puissant, imperious, prepotent)
   5. крепкий (strong, hard, sturdy, solid, fast, potent)
   6. убедительный (convincing, persuasive, conclusive, cogent, forceful, potent)
   7. обладающий потенцией (potent)

  DEFINITION

  adjective
   1. having great power, influence, or effect.
      "thrones were potent symbols of authority"
   2. (of a male) able to achieve an erection or to reach an orgasm.
      "The answer lies in the widespread assumption that ‘awakening’ a young lass is the mark of a potent man."
   3. formed of crutch-shaped pieces; (especially of a cross) having a straight bar across the end of each extremity.
      "a cross potent"
   4. of the fur called potent (as a tincture).
      "Potent gules and Or, a triskelion reversed of three armoured legs argent."

  noun
   1. fur resembling vair, but with the alternating pieces T-shaped.
      "Potent is believed to have been originally derived from vair."


  Potent means really strong, but not like a body builder. Use potent
  instead to describe things like intense smells, powerful magic
  potions, and very influential people.

  From the Latin potentum, meaning “powerful,” potent is just that:
  having tremendous strength or influence in either a moral or physical
  sense. A potent question gets to the heart of the matter and sparks
  serious discussion. Really stiff drinks can be potent, as can your
  breath after a garlicky meal. And as the composer Igor Stravinsky once
  asked, "What force is more potent than love?"

  And we should never forget that potent combination of mindfulness
  and motivation.
* substantive :Holmes:
[2018-06-02 Sat 10:25]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       fefe8ed7-8801-49c5-a1e2-0385d31d3f1f
   :END:

 substantive
*** --->
  основной

  adjective
   1. субстантивный (substantive, substantival)
   2. независимый (independent, irrespective, autonomous, free, sovereign, substantive)
   3. самостоятельный (independent, separate, solo, substantive, fledged, unaided)

  noun
   1. имя существительное (noun, substantive, name)

  DEFINITION

  adjective
   1. having a firm basis in reality and therefore important, meaningful, or considerable.
      "there is no substantive evidence for the efficacy of these drugs"
   2. having a separate and independent existence.
      "Nothing has a substantive existence apart from everything else and exists only in the context of everything else."
   3. (of law) defining rights and duties as opposed to giving the rules by which such things are established.
      "The submission there is that one needs primary statutory backing before a power to make procedural rules can affect substantive limitation periods."

  noun
   1. a noun.
      "All entities, substantives , adverbs, sentences are patiently, and joyously, called into question."


  When you talk about substantive change, you mean change that really
  makes a difference. After a substantive discussion, you will have an
  in-depth understanding of what you are talking about.

  When something is substantive, there is a lot of there there, be it
  meaning or volume of things. The word brings a serious tone. While it
  is often used to talk about problems and their solutions, a big steak
  dinner could be called substantive as could a very long piece of
  writing. In any case, you use it when there is a lot of substance
  involved.

  Did it, on the other hand, simply reframe someone else’s observation
  or fail to add anything truly substantive?
* ensnare                                                            :Holmes:
[2018-06-02 Sat 10:26]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       7e5ae563-6986-4226-bdfc-3c1c8f86c90d
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:57]
   :END:

 ensnare
*** --->
  заманивать

  verb
   1. поймать в ловушку (ensnare, entrap, snare, catch)
   2. заманивать (entice, ensnare, trap, wile, allure, inveigle)
   3. заловить (ensnare)

  DEFINITION

  verb
   1. catch in or as in a trap.
      "they were ensnared in downtown traffic"


  To ensnare something is to trap it. Instead of using snapping
  mousetraps, you might try to ensnare the mice in your kitchen and set
  them free outside.

  While you can use the verb ensnare to talk about literally catching
  something in a trap, it's also useful for more figurative kinds of
  traps. Your French teacher might try to ensnare you in becoming more
  involved in the French club, or rush hour traffic might ensnare you as
  you rush to make it to work on time. The word combines the prefix en,
  or "put in," and snare, with its Old Norse root snara, "noose or
  snare."

  Try as I might, I kept finding myself ensnared by the intonation and
  accent, by the cadence of sentences and not their content.
* cadence :Holmes:
[2018-06-02 Sat 10:27]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       dabf2a89-4d11-477d-8532-55a00626175b
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:58]
   :END:

 cadence
*** --->
  каденция

  noun
   1. каденция (cadence, cadenza, cadency, close)
   2. ритм (rhythm, beat, tempo, cadence, pulse, swing)
   3. модуляция (modulation, inflexion, cadence, inflection, control, tone)
   4. мерный шаг (cadence, cadency)
   5. движение в ногу (cadence, cadency)
   6. понижение голоса (cadence, cadency)

  DEFINITION

  noun
   1. a modulation or inflection of the voice.
      "the measured cadences that he employed in the Senate"
   2. a sequence of notes or chords comprising the close of a musical phrase.
      "the final cadences of the Prelude"


  The word cadence has its own lovely cadence — rhythm of sound as it's
  spoken.

  Cadence has come to mean "the rhythm of sounds" from its root cadere
  which means "to fall." Originally designating falling tones especially
  at the end of lines of music or poetry, cadence broadened to mean the
  rhythms of the tones and sometimes even the rhythm of sounds in
  general. Think of the cadence of the marching band at a football game
  or the cadence of the crickets on a warm spring night. You can
  remember the "fall" idea by thinking of one of the only words that
  contains it — decadence — which has the prefix de- at the front to
  mean down, or downfall.

  Try as I might, I kept finding myself ensnared by the intonation and
  accent, by the cadence of sentences and not their content.
* odds :Holmes:
[2018-06-02 Sat 10:29]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       ab50a90e-1fbc-439d-a76d-c298956a0e29
   :END:

 odds
*** --->
  шансы

  noun
   1. шансы (odds, look-out)
   2. перевес (advantage, superiority, preponderance, overweight, odds, overbalance)
   3. разница (difference, distinction, odds, inequality, dissemblance)
   4. преимущество (advantage, edge, excellence, privilege, start, odds)
   5. неравенство (inequality, disparity, odds, imparity)
   6. гандикап (handicap, odds)
   7. разногласие (disagreement, discord, difference, odds, dissension, discrepancy)

  DEFINITION

  noun
   1. the ratio between the amounts staked by the parties to a bet, based on the expected probability either way.
      "the bookies are offering odds of 8-1"


  The odds are the chances that something will happen. If you flip a
  coin, the odds are 50-50 you'll get heads.

  When we talk about odds, we're talking about probabilities,
  specifically, how likely it is that something will happen. Is there a
  5% chance? Is there a 95% chance? If there's a 95% chance, then the
  odds are great. We can talk about the odds of anything happening, as
  long as it hasn't happened yet. Anyone predicting the weather is
  telling the odds of rain or snow — they don't know for sure. If
  something strange happens people often say, "What were the odds of
  that?", which means: "I can't believe that happened. The odds were
  against it."

  My notes and my memory and impression were at complete odds.
* nagging :Holmes:
[2018-06-02 Sat 10:30]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       f7db72a8-07ea-41e6-a212-a3db9d0221ba
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 3.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:56]
   :END:

 nagging
*** --->
  нытье

  noun
   1. нытье (nagging, whining, yammer)
   2. ворчание (grunt, nagging, growl, grumble, grunting, snarl)
   3. попреки (nagging)

  adjective
   1. придирчивый (picky, captious, nagging, cantankerous, fault-finding, exacting)
   2. ноющий (aching, nagging, whining, yammering)
   3. ворчливый (grouchy, querulous, nagging, crabbed, murmurous, capernoited)
   4. неотвязный (persistent, nagging)

  DEFINITION

  adjective
   1. (of a person) constantly harassing someone to do something.
      "their overprotective and nagging parents"
   2. persistently painful or worrying.
      "a nagging pain"

  verb
   1. annoy or irritate (a person) with persistent fault-finding or continuous urging.
      "she constantly nags her daughter about getting married"


  Something that's nagging really bothers you — whether it's your
  nagging older sister, reminding you to take out the trash, or a
  nagging headache that lingers all day.

  A nagging boss might continually complain about your work — you could
  also describe her as "overcritical" or "faultfinding." When a physical
  pain or discomfort is nagging, it's just as disagreeable, tormenting
  or irritating you in an ongoing way, like a nagging pain in your lower
  back. The source of nagging is nag, which originally meant "gnaw or
  bite."

  And even after, I couldn’t quite kick the nagging feeling that the
  Oxford girl had been robbed.
* profound :Holmes:
[2018-06-02 Sat 10:32]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       6b0b03b9-a23a-4afe-84ac-d2a375f86bbe
   :END:

 profound
*** --->
  глубокий

  adjective
   1. глубокий (deep, profound, thorough, rich, keen, sound)
   2. основательный (thorough, solid, profound, staunch, intimate, stanch)
   3. проникновенный (profound)
   4. полный (full, complete, utter, total, absolute, profound)
   5. мудрый (wise, sage, profound, sapient, sapiential, Solomonic)
   6. абсолютный (absolute, stark, perfect, complete, total, profound)
   7. низкий (low, lower, poor, deep, short, profound)

  noun
   1. глубина (depth, deep, profound, intensity, deepness, profoundness)
   2. бездна (abyss, deep, chasm, gulf, profound, abysm)
   3. море (sea, water, waters, waves, blue, profound)
   4. океан (ocean, pond, deep, blue, main, profound)
   5. пучина (abyss, gulf, depth, profound, abysm, vortex)

  DEFINITION

  adjective
   1. (of a state, quality, or emotion) very great or intense.
      "profound social changes"
   2. (of a person or statement) having or showing great knowledge or insight.
      "a profound philosopher"
   3. at, from, or extending to a great depth; very deep.
      "he opened the door with a profound bow"

  noun
   1. the vast depth of the ocean or of the mind.


  When you need a word that's deeper than "deep," consider profound.

  Profundus meant literally "deep" in Latin, and profound had the same
  meaning when it entered English in the 14th century. But even then, it
  also meant "figuratively deep" — that is, very great or intense: "The
  new laws have had a profound impact." Of people, it means "very
  knowledgeable or insightful," but sometimes if a person tries to sound
  profound they're really just giving you superficial knowledge dressed
  up with big words.

  And so it is essential to ask, when in the grip of a profound
  intuition (this is a wonderful person; a beautiful house; a worthy
  endeavor; a gifted debater): on what is my intuition based?
* inattentive :Holmes:
[2018-06-02 Sat 10:35]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       6d9d65bf-c0ee-4555-8b17-2145b0e106e2
   :END:

 inattentive
*** --->
  невнимательный

  adjective
   1. невнимательный (inattentive, careless, remiss, heedless, unobservant, unheeding)
   2. неучтивый (discourteous, impolite, disobliging, inattentive)

  DEFINITION

  adjective
   1. not paying attention to something.
      "a particularly dull and inattentive student"


  Someone who's inattentive isn't paying enough attention. An
  inattentive lunch companion might spend the whole meal texting on his
  phone.

  Inattentive people are sometimes distracted, like an inattentive
  babysitter who loses track of the kids he's watching at the
  playground. You can also be inattentive simply through indifference or
  boredom — if you're inattentive at the opera, you're not paying
  attention to it because you're not interested in it. Inattentive tacks
  the "not" prefix in- onto attentive, from the Latin root attendere,
  "give heed to" or "stretch toward."

  Just as we aren’t inattentive to begin with, we aren’t born destined
  to act in keeping with our faulty thought habits.
* adversary                                                          :Holmes:
[2018-06-02 Sat 10:39]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       562148d9-de52-45c5-99d3-e4d2dc5a66b0
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 3.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:50]
   :END:

 adversary
*** --->
    [↗ædvɜsɜrɪ]
  состязательный

  noun
   1. противник (enemy, opponent, adversary, foe, rival, antagonist)
   2. враг (enemy, foe, adversary, opponent, hostile, philistine)
   3. соперник (rival, contender, competitor, contestant, adversary, antagonist)
   4. неприятель (enemy, adversary)
   5. оппонент (opponent, adversary, enemy, opposer, contradictor)

  DEFINITION

  noun
   1. one's opponent in a contest, conflict, or dispute.
      "Davis beat his old adversary in the quarterfinals"


  An adversary is someone who fights against or opposes another. In
  tennis, you stand across the net from your adversary.

  Adversary as in "enemy" or "opponent" is related to the words
  adversarial, or hostile, or adverse, meaning against or contrary. The
  Adversary is a specific reference to Satan, or the Devil. The word
  adversary is from Middle English adversarie, from Latin adversarius,
  from adversus "against."

  Holmes’s awareness enables him to avoid many of the faults that plague
  Watson, the inspectors, his clients, and his adversaries.
* harrowing :Holmes:
[2018-06-02 Sat 10:42]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       4b5c8fa0-ef04-4666-8d2a-543d227e383d
   :END:

 harrowing
*** --->
  боронование

  noun
   1. боронование (harrowing)

  adjective
   1. душераздирающий (heartbreaking, harrowing, heartrending, shrill, soul-destroying)
   2. горестный (woeful, sorrowful, grievous, rueful, harrowing, plaintive)

  DEFINITION

  adjective
   1. acutely distressing.
      "a harrowing film about racism and violence"

  verb
   1. draw a harrow over (land).
      "Wheat fields are harrowed before the crop emerges to get the first flush of weeds."
   2. cause distress to.
      "Todd could take it, whereas I'm harrowed by it"


  Being attacked by a hungry shark or being chased by an unruly mob on
  the streets can be described as harrowing, which means "provoking
  feelings of fear or horror."

  The adjective harrowing is often used to describe a firsthand
  experience that is terrifying, such as a harrowing drive home in icy
  weather, but it can also refer to a secondhand experience, such as
  reading or watching something that is very frightening or disturbing.
  If you read someone’s account of being shipwrecked in Antarctica, you
  might describe that as a harrowing story. A harrowing experience
  typically unfolds over a period of time. For example, if you bump into
  a shark while swimming, that’s merely scary. If the shark attacks you,
  then it becomes a harrowing ordeal.

  Earlier in the week we had finished The Count of Monte Cristo—after a
  harrowing journey that took several months to complete—and the bar was
  set high indeed.
* excess :Ferris:
[2018-06-02 Sat 15:52]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       c2b64395-84f1-40b8-93c7-5af1d910ad95
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:58]
   :END:

 excess
*** --->
  избыток

  noun
   1. избыток (excess, surplus, abundance, glut, overflow, overabundance)
   2. превышение (excess, command)
   3. излишек (over, surplus, excess, overage, superfluity, superabundance)
   4. эксцесс (excess)
   5. излишество (excess, luxury, superfluity, surfeit, abuse, glut)
   6. неумеренность (excess, surfeit)
   7. крайность (extreme, extremity, excess, extremeness, extravagance, emergency)
   8. невоздержанность (intemperance, incontinence, excess, debauchery, insobriety)
   9. выходка (trick, prank, excess, vagary, vagrancy)

  adjective
   1. лишний (excess, extra, redundant, unnecessary, spare, odd)
   2. избыточный (excess, surplus, exuberant, over, overabundant, excrescent)
   3. дополнительный (additional, more, further, complementary, extra, excess)

  verb
   1. увольнять по сокращению штатов (excess)

  DEFINITION

  adjective
   1. exceeding a prescribed or desirable amount.
      "trim any excess fat off the meat"

  noun
   1. an amount of something that is more than necessary, permitted, or desirable.
      "are you suffering from an excess of stress in your life?"
   2. lack of moderation in an activity, especially eating or drinking.
      "bouts of alcoholic excess"
   3. the action of exceeding a permitted limit.
      "there is no issue as to excess of jurisdiction"


  Excess is too much of something, like big-time overindulgence. Eating
  to excess makes your stomach hurt, and spending to excess means you
  can't pay your credit card bills.

  Excess comes from the Latin word excessus meaning, "go out, going
  beyond the bounds of reason," like eating and spending in excess. (Not
  so reasonable.) Although it spends most of its time as a noun, it can
  also be an adjective to describe "more than is required or needed,"
  like when excess water spills over the top of the bathtub, or those
  excess pounds spill over the top of your jeans.

  Lifestyle Design is thus not interested in creating an excess of idle
  time, which is poisonous, but the positive use of free time, defined
  simply as doing what you want as opposed to what you feel obligated to
  do.
* scapegoat :Ferris:
[2018-06-02 Sat 15:56]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       6d5deddd-847c-481a-b306-6b698ac97ec2
   :END:

 scapegoat
*** --->
  козел отпущения

  noun
   1. козел отпущения (scapegoat, goat, fall guy, patsy, whipping-boy)

  DEFINITION

  noun
   1. (in the Bible) a goat sent into the wilderness after the Jewish chief priest had symbolically laid the sins of the people upon it (Lev. 16).
      "Like the dogs, the scapegoats were, Strelan argues, central to the purificatory rites of Asia Minor where the churches addressed in Revelation are located."

  verb
   1. make a scapegoat of.
      "The Republicans scapegoated gays to win the election."


  The Bible depicts a ritual in which a goat is sent out into the desert
  bearing the faults of the people of Israel. The word scapegoat first
  occurred in the earliest English translation of the Bible, and it has
  come to mean any individual punished for the misdeeds of others.

  When a politician gets caught lying, he or she might use an assistant
  as a scapegoat. Somehow the lie will wind up being the assistant's
  fault. Your mom might tell you to use her as a scapegoat if you need
  to. So if your friends want you to go to a wild party and you don't
  want to, you should tell them your mom won't let you. That way, they
  will be mad at her and not at you. A fall guy is similar to a
  scapegoat, but it is mostly used if your scheme has been found out and
  one of your group of schemers must take the consequences.

  By using money as the scapegoat and work as our all-consuming routine,
  we are able to conveniently disallow ourselves the time to do
  otherwise: “John, I’d love to talk about the gaping void I feel in my
  life, the hopelessness that hits me like a punch in the eye every time
  I start my computer in the morning, but I have so much work to do!
* almighty :Ferris:
[2018-06-02 Sat 16:01]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       bfda8150-0675-440f-82d6-0ef2172359a9
   :DRILL_LAST_INTERVAL: 4.14
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 5.0
   :DRILL_EASE: 2.6
   :DRILL_LAST_QUALITY: 5
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:40]
   :END:

 almighty
*** --->
  всемогущий

  adjective
   1. всемогущий (omnipotent, almighty, omnipotence, all-powerful)
   2. ужасный (terrible, horrible, awful, appalling, dreadful, almighty)
   3. очень сильный (almighty)

  noun
   1. бог (god, deity, heaven, divinity, almighty, king)
   2. божество (deity, divinity, god, godhead, idol, almighty)

  adverb
   1. ужасно (terribly, awfully, horribly, ghastly, dreadfully, almighty)

  DEFINITION

  adjective
   1. having complete power; omnipotent.
      "God almighty"


  Anything that's almighty is extremely powerful. In fact, being
  almighty gives something (or someone) an infinite amount of power.

  Originally, the adjective almighty was capitalized and used to refer
  to God. It comes from the Old English ælmihtig, "all-powerful." You
  could also describe something that's almighty as "omnipotent" or even
  "godlike." Today people often use almighty in a sarcastic or ironic
  way to talk about things that exert a ridiculously huge amount of
  control over people: "All he cares about is the almighty dollar."

  Absolute income is measured using one holy and inalterable variable: the
  raw and almighty dollar.
* amuck :Ferris:
[2018-06-02 Sat 16:03]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       26d276ef-a0e0-4058-af13-f023c1c53961
   :END:

 amuck
*** --->
  набрасываться

  adverb
   1. вне себя (amok, amuck)
   2. бешено (furiously, madly, frantically, rabidly, without restraint, amuck)
   3. в ярости (in a towering rage, amok, frenzied, amuck)

  noun
   1. амок (amok, amuck, amock)

  adjective
   1. озверевший (amuck, amok)
   2. бешеный (mad, rabid, frantic, furious, frenzied, amuck)
   3. вышедший из-под контроля (runaway, amok, amuck)


  When things go amuck, they are wildly out of control. Someone running
  amuck is showing no self-control.

  This is a word that has to do with chaos and disorder. A riot is an
  example of people running amuck. In a cafeteria, if people are yelling
  and throwing food, they are going amuck. This word applies to times
  when control has been lost: people are showing no self-control, and
  the situation is out of hand. Sometimes, going amuck is positive,
  though. If a football player scores five touchdowns in a game, you
  could say he's running amuck.

  If I make $100 per hour but only work one hour per week, it’s going to
  be hard for me to run amuck like a superstar.

* unbeknownst                                                        :Ferris:
[2018-06-02 Sat 16:06]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       0548d816-5db7-48c1-8d96-bbf0166733a5
   :END:

 unbeknownst

*** --->
  неведомый

  adjective
   1. неведомый (unfamiliar, unbeknownst, unbeknown)

  DEFINITION

  adjective
   1. without the knowledge of (someone).
      "unbeknown to me, she made some inquiries"


  If someone plans your birthday party unbeknownst to you — that is,
  you're completely unaware of it — it will probably be a surprise
  party.

  Used as an adjective or adverb, unbeknownst is descended from
  unbeknown (1848), which combines the prefix un- ("not") with be ("by,
  about") and know. Sometimes the FBI might be secretly working on a
  case, unbeknownst to the CIA, which is also secretly working on it.
  Imagine their frustration when everyone finds out they could have
  shared information and work, while saving time and manpower.

  Unbeknownst to most fun-loving bipeds, not all stress is bad.
* resplendent :Ferris:
[2018-06-02 Sat 16:13]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       12168918-b27e-4510-be56-d7e460b1db12
   :END:

 resplendent
*** --->
  блистательный

  adjective
   1. блистательный (brilliant, resplendent, magnificent)
   2. великолепный (great, sumptuous, gorgeous, magnificent, excellent, resplendent)
   3. сверкающий (sparkling, glistening, brilliant, flashing, incandescent, resplendent)
   4. блестящий (brilliant, shiny, shining, bright, glossy, resplendent)

  DEFINITION

  adjective
   1. attractive and impressive through being richly colorful or sumptuous.
      "she was resplendent in a sea-green dress"


  Someone or something that is resplendent has great beauty and is a
  pleasure to behold. "She was there, at the base of the stairs,
  resplendent in her flowing gown and jewels."

  When people or things are resplendent, they are dazzling,
  splendiferous, glorious, or lovely. The adjective resplendent comes
  from a Latin word that means “to shine brightly.” The gilded
  entranceway was resplendent in the golden glow of the afternoon light.
  When he flashed his resplendent smile, she was helpless against his
  charms.

  Fear was behind him on the mountaintop, and thousands of feet above the
  resplendent green rain forest and pristine white beaches of Copacabana,
  Hans Keeling had seen the light.
* posh :Ferris:
[2018-06-02 Sat 16:14]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       d04bbc54-cb31-4c0d-99c8-fb3b495065ed
   :DRILL_LAST_INTERVAL: 4.14
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 5.0
   :DRILL_EASE: 2.6
   :DRILL_LAST_QUALITY: 5
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:38]
   :END:

 posh
*** --->
  шикарный

  adjective
   1. шикарный (chic, posh, plush, swanky, classy, snazzy)
   2. превосходный (excellent, superb, superior, superlative, fine, posh)

  verb
   1. иметь шикарный вид (posh)

  DEFINITION

  adjective
   1. elegant or stylishly luxurious.
      "a posh Munich hotel"

  adverb
   1. in an upper-class way.
      "trying to talk posh"

  noun
   1. the quality or state of being elegant, stylish, or upper-class.
      "we finally bought a color TV, which seemed the height of posh"


  Things that are posh are swanky, fancy, and high-class. Posh things
  usually cost a lot of money, too.

  If something is dirty, cheap, and shoddy, it will never be accused of
  being posh. Posh things are elegant and expensive. A posh apartment is
  gorgeous and classy. A posh restaurant has fancy food and you probably
  have to dress up to go there. Posh places are luxurious and
  fancy-schmancy. So it's no surprise that rich people tend to like
  things and places that are posh.

  On Monday, Hans returned to his law office in Century City, Los
  Angeles’s posh corporate haven, and promptly handed in his three-week
  notice.
* expletive :Ferris:
[2018-06-03 Sun 10:16]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       b6c786b6-73ec-4499-9590-c89b73e59d66
   :END:

 expletive
*** --->
  бранное слово

  noun
   1. бранное слово (expletive, pejorative, swearword, cussword)
   2. присловье (saying, household word, expletive, household term)
   3. бранное выражение (expletive)
   4. вставное слово (expletive)

  adjective
   1. вставной (plug-in, epenthetic, expletive, set-in)
   2. бранный (abusive, expletive, pejorative, vituperative)
   3. дополнительный (additional, more, further, complementary, extra, expletive)
   4. дополняющий (expletive, follow-up)

  DEFINITION

  noun
   1. an oath or swear word.
      "She let out a long string of oaths and expletives , carefully picking herself up from the floor."

  adjective
   1. (of a word or phrase) serving to fill out a sentence or line of verse.
      "Icelandic takes the non-referential property of quasi-argumental null subjects as basic, therefore quasi-argumental null subjects in the language can be interpreted as basically expletive ."


  An expletive is a swear word, a curse you let out when you are
  startled or mad. You probably already know a lot of expletives, but
  you don’t need to see them here, no way in heck.

  An expletive is a vulgar word that will greatly upset your grandmother
  if you say it in her presence. An expletive usually sneaks out because
  you get surprised or angry, like if you stub your toe, you might yell
  out an expletive. Even though you did it by accident, one of your
  parents still might put a bar of soap in your mouth, so watch your
  words. In a pinch, try these substitutes: fudge, sugar, heck, and
  walrus.

  Buckle up and stop being such a (insert expletive)!
* pry :Ferris:
[2018-06-03 Sun 10:20]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       26458721-886c-47fe-b0f6-b1c79c59fc45
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:57]
   :END:

 pry
*** --->
  подглядывать

  verb
   1. подглядывать (pry, peep, keek, pry into, kike, pry about)
   2. совать нос (pry, pry into, nose, nuzzle)
   3. подсматривать (pry, oversee, pry into, pry about)
   4. вырывать (pull out, snatch, wrest, pry, tear out, extract)
   5. любопытствовать (pry, rubberneck, poke about, rubber)
   6. поднимать посредством рычага (prize, pry, prise, prise up)
   7. взламывать посредством рычага (prize, pry, prise, prise up)
   8. извлекать с трудом (pry)

  noun
   1. рычаг (lever, arm, rod, cradle, pry, jack)
   2. любопытство (curiosity, pry)
   3. любопытный человек (pry, rubberneck)

  adjective
   1. любопытный (curious, nosy, newsy, pry, nosey)

  DEFINITION

  verb
   1. inquire too closely into a person's private affairs.
      "I'm sick of you prying into my personal life"
   2. use force in order to move or open (something) or to separate (something) from something else.
      "using a screwdriver, he pried open the window"


  To pry is to try and find something out that is none of your business.
  We all hate people who pry, sticking their nose into our personal
  affairs, and it is an annoying and disrespectful habit.

  We are taught as children to ask questions, but sometimes those
  questions are used to pry, or peek into someone's private business. A
  nosy person will peek into some else's life the same way one might use
  a crowbar to pry open a crate (though — alert! — that pry has a
  different origin). Our word is thought to come from a word related to
  the Old English verb beprīwan, "to wink," which evolved into the
  Middle English prie, "to peer in," which gives us today's meaning.

  How do I pry myself from the tentacles of workaholism and the fear
  that it would fall to pieces without my 15-hour days?
* backpedal :Ferris:
[2018-06-03 Sun 10:30]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       62714617-7028-40c6-99e5-1f8514a533d9
   :END:

 backpedal
*** --->
  идти на попятный

  verb
   1. тормозить (brake, inhibit, slow down, hamper, retard, backpedal)
   2. тормозить велосипед (backpedal)
   3. приостанавливать дело (backpedal)
   4. идти на попятный (beat a retreat, cry off, crawfish, backpedal, off, crayfish)

  DEFINITION

  verb
   1. move the pedals of a bicycle backward in order to brake.


  When you backpedal, you completely change your position or opinion.
  You might backpedal on your promise to buy your friend lunch when you
  see how expensive the restaurant is.

  If a politician supports a certain position and then seems to reverse
  her opinion or significantly change it, she backpedals. And if you
  guarantee you'll make cupcakes for a bake sale, but then you run out
  of time, you might have to backpedal. A more literal meaning of
  backpedal is, just as it sounds, to pedal a bicycle backwards.

  In my undying quest to make myself miserable, I accidentally began to
  backpedal.
* scantiest :Ferris:
[2018-06-03 Sun 10:31]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       51fd7e65-fa54-4728-91a3-fd55bef1b9d4
   :END:

 scantiest
*** --->
  scantiest

  adjective
   1. мизерный (scanty, meager, meagre)
   2. скудный (scarce, meager, scanty, scant, lean, poor)
   3. ограниченный (limited, bounded, restricted, confined, finite, scanty)
   4. недостаточный (inadequate, insufficient, scarce, deficient, poor, scanty)

  DEFINITION

  adjective
   1. small or insufficient in quantity or amount.
      "scanty wages"


  We refer to an amount or thing that is not quite enough as scanty, or
  lacking. It's an adjective used to describe something that doesn't
  offer enough, as in "farmers having a scanty crop in a drought year."

  The adjective scanty comes from the Old Norse scamt, which means
  "short or brief," and so suggests a small amount. The word usually
  suggests a meager amount, and can refer to anything that is barely
  sufficient. Someone trying to stretch a meal might offer scanty
  servings. On a humorous note, a Roaring Twenties flapper referred to
  her underwear as scanties.

  Set aside a certain number of days, during which you shall be content
  with the scantiest and cheapest fare, with course and rough dress,
  saying to yourself the while: “Is this the condition that I feared?”
* fare :Ferris:
[2018-06-03 Sun 10:31]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       31f57d49-7ff3-4b61-bbb6-6e9a52658b17
   :END:

 fare
*** --->
  плата за проезд

  noun
   1. плата за проезд (fare)
   2. стоимость проезда (fare)
   3. пища (food, nutrition, meat, diet, nourishment, fare)
   4. еда (food, meal, eating, fare, meat, feed)
   5. пассажир (passenger, fare)
   6. ездок (rider, horseman, fare)
   7. провизия (provisions, food, provision, victual, victuals, fare)
   8. съестные припасы (food, comestibles, fare)

  verb
   1. поживать (fare, do)
   2. быть (be, exist, fare, play)
   3. происходить (occur, happen, take place, be, come, fare)
   4. случаться (happen, occur, be, match, take place, fare)
   5. оказаться (turn up, fare)
   6. путешествовать (travel, go, journey, voyage, hike, fare)
   7. ехать (go, ride, drive, travel, fare)

  DEFINITION

  noun
   1. the money a passenger on public transportation has to pay.
      "Although not illegal, charging double fares by breaking journeys into different segments to maximise profits on one route is downright immoral."
   2. a range of food, especially of a particular type.
      "delicious Provençal fare"

  verb
   1. perform in a specified way in a particular situation or over a particular period of time.
      "the party fared badly in the spring elections"
   2. travel.
      "a young knight fares forth"


  It's not fair that fare means three unrelated things. As a verb, it
  means to proceed or get along, as in "Fare thee well." As a noun, it
  can refer to the cost of travel ("Train fare is ten dollars") or to
  food ("Tatertots are typical cafeteria fare").

  To remember fare's different meanings, think of how, for people living
  close to the bone, the question "How are you eating/faring?" is not so
  different from "How are you getting along/faring?" And when you pay
  plane fare and fly to France, you will most assuredly be eating French
  fare once you get there.

  Set aside a certain number of days, during which you shall be content
  with the scantiest and cheapest fare, with course and rough dress,
  saying to yourself the while: “Is this the condition that I feared?”
* salvage :Ferris:
[2018-06-03 Sun 10:34]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       9abe25f8-dd61-40ee-a444-f300c2477f23
   :END:

 salvage
*** --->
  спасение

  noun
   1. спасение (salvation, rescue, saving, escape, salvage, redemption)
   2. спасение имущества (salvage)
   3. трофеи (booty, haul, spoils of war, salvage, captured material)
   4. сбор трофеев (salvage)
   5. утильсырье (scrap, rubble, salvage, refutable, refuse, junk)
   6. подъем затонувших судов (salvage)
   7. спасенное имущество (salvage)
   8. трофеи и боевой утиль (salvage)
   9. сбор и использование утильсырья (salvage)
  10. кромка (edge, hem, flange, bead, selvedge, salvage)

  verb
   1. спасать (save, rescue, salvage, redeem, retrieve, bring off)
   2. собирать трофеи (salvage)
   3. спасать имущество (salvage, salve)

  DEFINITION

  noun
   1. the rescue of a wrecked or disabled ship or its cargo from loss at sea.
      "a salvage operation was under way"

  verb
   1. rescue (a wrecked or disabled ship or its cargo) from loss at sea.
      "an emerald and gold cross was salvaged from the wreck"


  To salvage something is to save it...before it's too late. You might
  try to salvage your damaged reputation by defending yourself, or
  salvage a burnt piece of toast by scraping off the black residue.

  As a noun salvage is the act of rescuing stuff from a disaster like a
  shipwreck or fire — or the rescued goods themselves. As a verb,
  salvage means to collect or rescue that sort of item, or more
  generally to save something from harm or ruin. If you want to salvage
  your grade, you need to stop gaming so much and start studying more.

  Suddenly, I started thinking of simple steps I could take to salvage
  my remaining resources and get back on track if all hell struck at
  once.
* drought :Ferris:
[2018-06-03 Sun 10:59]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       5bcba49a-7803-45ab-be7e-0b88cd42adfb
   :END:

 drought
*** --->
  засуха

  noun
   1. засуха (drought, dry, drouth)
   2. сухость (dryness, aridity, drought, aridness)
   3. жажда (thirst, hunger, itch, want, drought)
   4. сухость воздуха (drought)

  DEFINITION

  noun
   1. a prolonged period of abnormally low rainfall; a shortage of water resulting from this.
      "Chinese officials say cloud seeding has helped to relieve severe droughts and water shortages in cities."


  When there is a drought somewhere, there's not enough rainfall. In
  certain areas, a drought can last for weeks, months, sometimes even
  years! Forget about running your lawn sprinkler during a drought; the
  water is needed for drinking, bathing, and toilet flushing.

  Another way drought can be used is to refer to a shortage of something
  (other than rainfall) that lasts for a long period of time, like a
  drought in job growth during a recession. Typically a drought is not a
  good thing and something you hope to avoid. For example, if your
  friend Kenny hasn't gone on a date in five years, it's safe to say
  that he is having a romantic drought.

  He arrived in Ghana in the early 1980s, in the middle of a coup
  d’état, at the peak of hyperinflation, and just in time for the worst
  drought in a decade.
* fondest :Ferris:
[2018-06-03 Sun 11:02]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-06-08 Fri>
   :PROPERTIES:
   :ID:       ceee3481-80a2-4c5c-a047-09125fc04820
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-06-04 Mon 10:57]
   :END:

 fondest
*** --->
  Заветной

  adjective
   1. любящий (loving, fond, affectionate, tender, amatory)
   2. нежный (tender, gentle, delicate, affectionate, soft, fond)
   3. излишне доверчивый (dupeable, fond, dupable)
   4. излишне оптимистичный (fond)

  DEFINITION

  adjective
   1. having an affection or liking for.
      "I'm very fond of Mike"


  To be fond of something is to like it. Sports fans are fond of sports.
  Oddly, this adjective can also mean foolish and silly.

  We're all fond of some things and people: the things and people we
  like. Being fond can mean anything from liking something a little
  ("I'm fond of that band") to be extremely, almost absurdly interested
  in something ("He's a little too fond of football"). This word
  sometimes implies foolishness and absurdity: almost like you love
  something so much that you've lost your mind. But usually being fond
  is a good thing: it just means you enjoy something.

  Some of his fondest memories still include nothing but friends and
  gruel.
* ingenuity :Ferris:
[2018-06-03 Sun 15:17]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       bde46ac9-3b38-45f9-9c0c-519229a71f56
   :END:

 ingenuity
*** --->
  изобретательность

  noun
   1. изобретательность (ingenuity, inventiveness, resourcefulness, invention, ingeniousness, contrivance)
   2. искусность (adeptness, subtlety, finesse, ingenuity, cleverness, adroitness)
   3. мастерство (skill, craftsmanship, mastery, workmanship, excellence, ingenuity)

  DEFINITION

  noun
   1. the quality of being clever, original, and inventive.
      "In every way - performance, build quality, ingenuity of design - it is the better car."


  Ingenuity is the ability to think creatively about a situation or to
  solve problems in a clever way. If you want to build a boat out of
  toothpicks and yarn, you’ll need a lot of ingenuity.

  The Latin word for “mind, intellect” is a root of ingenuity, and it
  takes a bright and fast-thinking intellect to use ingenuity in a
  situation. Athletes show ingenuity all the time, finding exciting ways
  to outwit their opponents and to achieve victory. Master criminals
  rely on their ingenuity in order to evade the law when they are
  chased. Ingenuity is all about imagination, and an imaginative mind
  knows that every obstacle can be overcome with a little ingenuity.

  It is [mightier] than the [mightiest] weapon of destruction devised by
  the [ingenuity] of man
* impediment                                                         :Docker:
[2018-06-03 Sun 19:30]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       70336404-c8e1-4570-a567-2ae1e1dbd2e7
   :END:

 impediment
*** --->
  препятствие

  noun
   1. препятствие (let, obstacle, obstruction, barrier, hurdle, impediment)
   2. помеха (hindrance, noise, obstacle, impediment, nuisance, handicap)
   3. задержка (delay, setback, retention, lag, retardation, impediment)
   4. заикание (stuttering, stammering, stutter, stammer, titubation, impediment)
   5. дефект речи (impediment)
   6. препятствие к браку (impediment)

  DEFINITION

  noun
   1. a hindrance or obstruction in doing something.
      "a serious impediment to scientific progress"


  An impediment is anything that slows or blocks progress. It can refer
  to a physical thing, like a fallen tree in the road, or something more
  intangible, like how piracy is an impediment to the pleasure cruise
  industry in Somalia.

  See the pedi in there? Pedi means "feet" and hundreds of years ago,
  the word impediment referred to shackling one's feet. Now its use has
  broadened considerably. Impediment is something that blocks or impedes
  your path. There's no end to the things in your life that can be
  considered impediments: your small bank account, your terrible
  childhood, your country's economic malaise — any one of these could be
  considered an impediment in your quest for happiness.

  This is one of the main reasons why organizations like Amazon and
  Netflix use these architectures — to ensure they remove as many
  impediments as possible to getting software out the door.
* exacerbate                                                         :Docker:
[2018-06-03 Sun 19:31]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       608239ce-d4f6-4b0f-9432-d071f154482a
   :END:

 exacerbate
*** --->
  обострять

  verb
   1. обострять (sharpen, exacerbate, aggravate, escalate, subtilize, peak)
   2. усиливать (strengthen, increase, enhance, reinforce, intensify, exacerbate)
   3. раздражать (provoke, irritate, displease, annoy, exasperate, exacerbate)
   4. ожесточать (harden, sear, acerbate, steel, empoison, exacerbate)

  DEFINITION

  verb
   1. make (a problem, bad situation, or negative feeling) worse.
      "the forest fire was exacerbated by the lack of rain"


  For a formal-sounding verb that means to make worse, try exacerbate.
  If you're in trouble, complaining about it will only exacerbate the
  problem.

  Exacerbate is related to the adjective acrid, often used to describe
  sharp-smelling smoke. Think of exacerbate then as a sharp or bitter
  thing that makes something worse. A drought will exacerbate a
  country's food shortage. Worsen, intensify, aggravate and compound are
  similar, but exacerbate has the sense of an irritant being added in to
  make something bad even worse.

  These problems can be exacerbated when the team is distributed.
* seam                                                               :Docker:
[2018-06-03 Sun 19:34]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       cf739c2b-b909-4bb9-be86-963fdd12ba62
   :END:

 seam
*** --->
  шов

  noun
   1. шов (seam, joint, suture, stitch, juncture, dart)
   2. пласт (layer, stratum, seam, bed, sheet, ledge)
   3. пропласток (seam)
   4. соединение (compound, connection, conjunction, joint, combination, seam)
   5. рубец (scar, tripe, cicatrix, rumen, welt, seam)
   6. линия шва (seam)
   7. шрам (scar, mark, seam, cicatrix, cicatrice, chalk)
   8. спай (juncture, seam)
   9. морщина (wrinkle, cockle, ruck, corrugation, line, seam)
  10. прослоек (layer, seam, streak, parting)

  verb
   1. соединять швами (seam)
   2. покрывать рубцами (seam)
   3. покрывать морщинами (furrow, seam)
   4. покрываться морщинами (seam, take lines)
   5. бороздить (furrow, plow, busk, seam, plough)
   6. сшивать (sew, sew together, seam, lace)

  DEFINITION

  noun
   1. a line along which two pieces of fabric are sewn together in a garment or other article.
      "He turned to the foreman and said, ‘The patterns of the side seams on these coats do not match.’"
   2. an underground layer, as of ore or coal.
      "A seam of coal about two feet thick was discovered, but underlying this seam of coal was a seam of clay approximately four feet thick."

  verb
   1. join with a seam.
      "it can be used for seaming garments"
   2. make a long narrow indentation in.
      "men in middle age have seamed faces"


  When you sew two pieces of fabric together, the line you are sewing is
  the seam. Coal appears in long, linear underground deposits referred
  to as seams.

  A garment that is coming to pieces will often first tear at the seams,
  the weakest parts. People use this image to describe anything that has
  reached a point where it is simply not holding together––your car
  could be falling apart at the seams, or if there's been a lot of
  stress in your life, you could be too — and you might have to move
  into a seamy neighborhood.

  With microservices, think of us opening up seams in our system that
  are addressable by outside parties.
* curtailed :Docker:
[2018-06-03 Sun 19:43]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       9e31b9fd-0090-4887-83e0-434db4296dc9
   :END:

 curtailed
*** --->
  свернуты

  verb
   1. сокращать (cut, reduce, shrink, abbreviate, contract, prune)
   2. урезать (cut, cut down, curtail, skimp, truncate, pare down)
   3. сворачивать (turn off, curtail, wrap, wrap up, shunt, de-escalate)
   4. укорачивать (shorten, curtail, truncate, take up, bobtail)

  DEFINITION

  verb
   1. reduce in extent or quantity; impose a restriction on.
      "civil liberties were further curtailed"


  To curtail something is to slow it down, put restrictions on it, or
  stop it entirely. If I give up cake, I am curtailing my cake-eating.

  Curtail is an official-sounding word for stopping or slowing things
  down. The police try to curtail crime — they want there to be less
  crime in the world. A company may want to curtail their employees'
  computer time, so they spend more time working and less time goofing
  around. Teachers try to curtail whispering and note-passing in class.
  When something is curtailed, it's either stopped entirely or stopped
  quite a bit — it's cut short.

  Second, the ease with which you can scale parts of your system
  independently from each other is curtailed.
* surrendering :Docker:
[2018-06-03 Sun 19:49]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       9d284b51-cd3f-46bd-8acd-5a61c61fe2c4
   :END:

 surrendering
*** --->
  капитуляция

  verb
   1. сдаваться (give up, surrender, give in, yield, capitulate, give way)
   2. капитулировать (capitulate, surrender)
   3. сдавать (hand over, surrender, pass, turn in, deliver, yield)
   4. уступать (give, concede, give in, yield, give way, defer)
   5. отказываться (refuse, deny, give up, waive, reject, disclaim)
   6. подчиняться (obey, submit, surrender, comply, conform, bow)
   7. предаваться (indulge, surrender, devote, abandon, addict, abandon oneself)
   8. поддаваться (succumb, yield, give way, fall for, surrender, take)

  DEFINITION

  verb
   1. cease resistance to an enemy or opponent and submit to their authority.
      "over 140 rebels surrendered to the authorities"


  To surrender is to give up control of something to someone else. If
  you miss curfew, your parents might make you surrender the keys to the
  car. Okay, it's only a minivan, but it's still cooler than being on
  foot patrol.

  If you want someone to give up, you might order them to surrender. The
  witch in the Wizard of Oz wrote "Surrender Dorothy!" in the sky above
  the Emerald City. You can use the noun surrender when you give up on a
  task. For example, if you are cleaning the house, but every time you
  finish a room, the kids mess up another, you can throw your hands up
  and declare, "I surrender!"

  The modules themselves soon become tightly coupled with the rest of
  the code, surrendering one of their key benefits.
* opinionated :Docker:
[2018-06-03 Sun 19:54]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       0bad117d-3340-43fb-9108-64b7f2c804be
   :END:

 opinionated
*** --->
  упрямый

  adjective
   1. упрямый (stubborn, obstinate, opinionated, headstrong, dogged, willful)
   2. самоуверенный (assertive, confident, opinionated, cocky, perky, presumptuous)
   3. своевольный (willful, headstrong, high-handed, opinionated, arbitrary, contrary)
   4. чрезмерно самоуверенный (opinionated)

  DEFINITION

  adjective
   1. conceitedly assertive and dogmatic in one's opinions.
      "an arrogant and opinionated man"


  Your opinion is your view, belief, or judgment. If you are
  opinionated, you obstinately hold on to your opinions, and you don't
  hesitate to let other people know what those opinions are.

  Opinionated is based on the word "opinion," which itself comes from
  the Latin word opinari, meaning to think. If you and your sister are
  both extremely opinionated, it must have been hard growing up in the
  same house — for you and for your parents. Someone who is not at all
  opinionated can be just as frustrating to live with, though, if their
  response always seems to be, "I don't care."

  In this chapter, I’ll take a fairly opinionated view of what the role
  of an architect is, and hopefully launch one final assault on the
  ivory tower.
* assault :Docker:
[2018-06-03 Sun 19:55]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       330df3ea-6528-43d7-b8b7-a0dc058031e0
   :END:

 assault
*** --->
  нападение

  noun
   1. нападение (attack, assault, offense, onslaught, aggression, charge)
   2. штурм (storm, assault)
   3. атака (attack, assault, charge, onslaught, thrust, onset)
   4. насилие (violence, force, assault, coercion, violation, outrage)
   5. нападки (attacks, attack, assault, down)
   6. приступ (attack, fit, assault, bout, seizure, stroke)
   7. изнасилование (rape, assault, violation, ravishment)
   8. высадка десанта с боем (assault, opposed landing)

  adjective
   1. штурмовой (assault, attack)

  verb
   1. штурмовать (storm, assault)
   2. атаковать (attack, charge, assault, assail)
   3. нападать (attack, assault, assail, hit, come, hit off)
   4. идти на приступ (assault)
   5. грозить физическим насилием (assault)
   6. набрасываться (pounce, lash out, attack, come down, wade into, assault)
   7. изнасиловать (rape, ravish, violate, deflower, assault, interfere)

  DEFINITION

  noun
   1. a physical attack.
      "his imprisonment for an assault on the film director"
   2. a concerted attempt to do something demanding.
      "a winter assault on Mt. Everest"

  verb
   1. make a physical attack on.
      "he pleaded guilty to assaulting a police officer"


  An assault is an attack. Getting punched, yelled at, or bombed are all
  types of assault.

  To assault is to attack or bombard someone in some way. Fighter planes
  can make an aerial assault, while ground troops make a ground assault.
  Verbal assault consists of insults, swearing, or threats. A strong
  criticism, like a negative review in the newspaper, is a written
  assault. Physical assault can range from getting pushed to getting
  shot. You could even say "That music is so loud it's assaulting my ear
  drums!"

  In this chapter, I’ll take a fairly opinionated view of what the role
  of an architect is, and hopefully launch one final assault on the
  ivory tower.
* rigor :Docker:
[2018-06-03 Sun 20:28]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       8c4ef88d-edd9-49f6-b691-4b64353f7717
   :END:

 rigor
*** --->
  строгость

  noun
   1. строгость (rigor, severity, austerity, stringency, rigidity, restraint)
   2. озноб (chills, chill, ague, shakes, rigor, dither)
   3. суровость (severity, rigor, austerity, sternness, hardness, inclemency)
   4. точность (accuracy, precision, exactness, fidelity, correctness, rigor)
   5. тщательность (thoroughness, accuracy, rigor, exactness, particularity, elaboration)
   6. окоченение (rigor, numbness, congealment)
   7. оцепенение (consternation, stupor, torpor, catalepsy, stupefaction, rigor)
   8. неумолимость (inexorability, implacability, deadliness, rigor, rockiness, rigour)

  DEFINITION

  noun
   1. the quality of being extremely thorough, exhaustive, or accurate.
      "his analysis is lacking in rigor"


  When a school boasts of its academic rigor, it means its students
  learn a lot and work really hard. Rigor means thoroughness and
  exhaustiveness––the gold standard for a good teacher.

  You may have heard of "rigor mortis"––which is a medical term
  describing the stiffness of a body after death. Rigor used to mean
  stiffness outside of the corpse context, i.e., sternness. The word
  changes meaning along with our changing standards for what we want
  teachers to be.

  Architects and engineers have a rigor and discipline we could only
  dream of, and their importance in society is well understood.
* subservient :Docker:
[2018-06-03 Sun 20:33]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       4be3a76b-69cb-4096-98a9-d29be99a000a
   :END:

 subservient
*** --->
  раболепный

  adjective
   1. раболепный (servile, fawning, subservient, obsequious, creeping, menial)
   2. подчиненный (subordinate, subject, inferior, under, subdued, subservient)
   3. содействующий (contributory, contributor, coefficient, subservient, ministerial, adjutant)
   4. служащий средством (instrumental, subservient)

  DEFINITION

  adjective
   1. prepared to obey others unquestioningly.
      "she was subservient to her parents"


  Subservient means "compliant," "obedient," "submissive," or having the
  qualities of a servant. Something that's subservient has been made
  useful, or put into the service of, something else.

  Our word subservient is unusual because it actually comes from the
  Latin word of exactly the same spelling and almost the identical
  meaning — "subjecting to" or "complying with." Usually words change a
  little in spelling or meaning when they are adopted from another
  language, but this one did not. Maybe the word subservient seemed so
  subservient that it could comply with the rules of any language!

  The balance of part artist, part engineer, overseeing the creation of
  what is normally a singular vision, with all other viewpoints being
  subservient, except for the occasional objection from the structural
  engineer regarding the laws of physics.
* utterly                                                            :Docker:
[2018-06-03 Sun 20:34]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       f0b32f89-5874-4aac-9e1f-ddafc847e527
   :END:

 utterly
*** --->
  вконец

  adverb
   1. крайне (extremely, utterly, exceedingly, sorely, enormously, vastly)
   2. абсолютно (absolutely, totally, utterly, sheer)
   3. чрезвычайно (extremely, highly, exceedingly, enormously, particularly, utterly)
   4. дотла (utterly, completely)
   5. вконец (completely, utterly, thoroughly, absolutely)

  DEFINITION

  adverb
   1. completely and without qualification; absolutely.
      "he looked utterly ridiculous"


  Utterly is an intensifying word: something utterly delicious is very,
  very delicious.

  One thing people love to do is exaggerate. You often hear people
  talking about how awesome or awful things are. When you're laying it
  on thick, utterly is an utterly useful word: it means something
  similar to completely, totally, or very. Something utterly
  disappointing is extremely disappointing. Something utterly wonderful
  is wonderful times ten. When you get tired of writing very, utterly is
  a good word choice.

  Utterly devoid of any understanding as to how hard it will be to
  implement, or whether or not it will actually work, let alone having
  any ability to change as we learn more.
