-*- coding: utf-8 -*-

* fidget                                                             :Ferris:
[2018-07-07 Sat 13:23]

To fidget is to make little movements with your hands and feet. Even
if you're nervous during your job interview, try not to fidget.

The word fidget is related to the Old Norse fikja, meaning "move
briskly, be restless or eager." If you are feeling impatient or
anxious you might fidget in your seat or fidget with a pen in your
hands. A person who fidgets a lot can be referred to as a fidget and
so can that quick anxious movement itself.

In the strictest sense, you shouldn’t be trying to do more in each day,
trying to fill every second with a work fidget of some type.

* guise :Ferris:
[2018-07-07 Sat 13:29]

The noun guise refers to an outward appearance that conceals the true
nature of someone or something. Your classmate might chat with you
under the guise of friendship, but you know she's really just looking
for juicy gossip.

No doubt you’ve noticed the similarity between guise and disguise.
Both involve the art of deception: it’s the methods that differ. Guise
is about trying on new attitudes and mannerisms, such as speaking and
acting in the guise of a native in a place where you are actually a
tourist. Disguise involves hiding your real identity, disappearing in
the new role.

Being busy is most often used as a guise for avoiding the few critically
important but uncomfortable actions.

* fuss :Ferris:
[2018-07-07 Sat 13:32]

If you are making a fuss, settle down! A fuss is a state of
excitement, and it's usually about something not worth worrying or
"fussing" about.

Most fusses are types of commotion. If someone makes a fuss, they're
overexcited and in a tizzy over something, like someone who can't stop
asking questions. Another fuss is angrier: you might say "What's the
fuss?" if you hear two people yelling at each other. A fuss is also
any kind of hubbub or whirlwind of activity, like a huge crowd
swarming toward a sale. Parents tend to fuss over their children.
Someone who fusses is worrying too much.

The options are almost limitless for
creating “busyness”: You could call a few hundred unqualified sales
leads, reorganize your Outlook contacts, walk across the office to
request documents you don’t really need, or fuss with your BlackBerry for
a few hours when you should be prioritizing.
* fart                                                               :Ferris:
[2018-07-07 Sat 13:40]

We don’t all like to admit it, but we all fart. That is, we all pass
smelly gas out of our anus.

Kids — and a few adults too — find farting funny. If someone lets out
a long fart during church or class, someone is bound to laugh.
However, the teacher probably won’t laugh, and the culprit could be in
big trouble. Be careful about accusing others of farting, because one
of the oldest rules of the schoolyard is “He who smelt it, dealt it.”
A less slangy word for fart is flatulence.

This is also true for the person who checks e-mail 30 times per day and
develops an elaborate system of folder rules and sophisticated techniques
for ensuring that each of those 30 brain farts moves as quickly as
possible.
* truism                                                             :Ferris:
[2018-07-07 Sat 13:41]

Here's a truism for you: Only people who look up words they don't know
can expand their vocabularies. Did you find that statement obvious,
boring, and saying nothing new or interesting? That's the perfect
description of a truism.

Sometimes truisms can be mistaken for factual statements. In fact,
despite their seeming obviousness, they are usually opinions. Many
people who look up words in the dictionary don't improve their
vocabularies, as much as they'd like to. Another truism: You get what
you pay for. Well, a lot of the time, sure, but not always. That's why
the word bargain was invented.

Here are two truisms to keep in mind:
*fFutility :Ferris:
[2018-07-07 Sat 13:44]

When you can’t see the point in even trying, that’s the feeling of
futility, the sense that no matter how much you work at it, nothing
good will happen, so you might as well give up.

What’s the point? That’s the question asked by anyone who senses the
futility of something. The futility of war makes soldiers put down
their weapons, and your father’s strict rules makes any protest an act
of futility. The root word is the Latin futilis, which literally means
“leaky.” Imagine pouring lemonade into a cup that has no bottom. No
matter how long you pour, you’ll never get a sip because of that leaky
cup. Ah, the futility!

Pareto and His Garden: 80/20 and Freedom from Futility
* wily :Ferris:
[2018-07-07 Sat 13:47]

Did you fall for that wily door to door salesman's pitch? He must be
very slick and tricky to have convinced you to buy a set of new tires,
considering you don't have a car.

How can you remember the meaning of the adjective wily? Just think
about the old Warner Brothers Looney Tunes cartoons. Their aptly named
cartoon character, Wile E. Coyote, got his name from a clever play on
words. Wile E. is supposed to be cunning, crafty, and clever — in
other words, wily. Wile E. is all those things, but unfortunately he
was usually bested by that pesky roadrunner anyway. Meep. Meep.

Vilfredo Pareto was a wily and controversial economist-cum-sociologist
who lived from 1848 to 1923.
* seminal :Ferris:
[2018-07-07 Sat 13:48]

Call something seminal when it's so original, so groundbreaking and
awesome that it will influence everything that comes after it. Picasso
produced more than a few seminal works of art, for example.

Technically, seminal means something related to semen or seeds. But
these days people more often use the word to describe something that
plants the seed for creative growth. An innovative piece of music or
literature, a fresh new idea, or an invention that changes everything
could each be called seminal. Synonyms include critical, fundamental,
original, and primary.

His seminal work, Cours d’economie politique, included a then
little-explored “law” of income distribution that would later bear his
name: “Pareto’s Law” or the “Pareto Distribution,” in the last decade
also popularly called the “80/20 Principle.”
* skewed                                                             :Ferris:
[2018-07-08 Sun 07:10]

Something skewed is slanted or off-center in some way. A picture frame
or viewpoint can be skewed.

This is a word, like so many, that can apply to physical things or
ideas. A painting on the wall is skewed if it's leaning to one side.
Also, opinions are often skewed: this is another way of saying someone
is biased. People often accuse news reports of being skewed toward one
political viewpoint. A movie could be skewed toward one character more
than the other. When you think of skewed, think of leaning and
slanting of all sorts.

The list is infinitely long and diverse, and the ratio is often skewed
even more severely: 90/10, 95/5, and 99/1 are not uncommon, but the
minimum ratio to seek is 80/20.
* mere :Ferris:
[2018-07-08 Sun 07:24]

Mere means pure and simple, nothing more and nothing less. If the mere
mention of someone's name makes you happy, then just hearing his name
— and that alone — is enough to make you smile.

Mere can have a little irony attached. If you introduce yourself as "a
mere student," when you’re announcing your astounding invention,
you're contrasting your lowly status with the enormity of your
invention. This kind of mere comes from the Latin for "undiluted."
Mere has a homograph — a completely different word that's spelled the
same — and this mere means a lake or a pond. It’s related to the Dutch
word meer — there’s lots of water in Holland.

Out of more than 120 wholesale customers, a mere 5 were bringing in 95%
of the revenue.
* cajoling :Ferris:
[2018-07-08 Sun 07:25]

To cajole someone is to persuade them by using insincere compliments
or promises. If you say "Please, pretty-please, I'll be your best
friend," when asking for a stick of gum, you are cajoling the gum
holder.

The origin of this word is probably a blend of two French words
meaning "to chatter like a jaybird" and "to lure into a cage." When
you cajole that guy into lending you some money, picture him as the
bird going into the cage. In fact, the word cajole may be associated
with another French word meaning "to put in jail."

I was spending 98% of my time chasing the remainder, as
the aforementioned 5 ordered regularly without any follow-up calls,
persuasion, or cajoling.
* mere :Ferris:
[2018-07-08 Sun 07:30]

Mere means pure and simple, nothing more and nothing less. If the mere
mention of someone's name makes you happy, then just hearing his name
— and that alone — is enough to make you smile.

Mere can have a little irony attached. If you introduce yourself as "a
mere student," when you’re announcing your astounding invention,
you're contrasting your lowly status with the enormity of your
invention. This kind of mere comes from the Latin for "undiluted."
Mere has a homograph — a completely different word that's spelled the
same — and this mere means a lake or a pond. It’s related to the Dutch
word meer — there’s lots of water in Holland.

Out of more than 120 wholesale customers, a mere 5 were bringing in 95%
of the revenue.
* plucking :Ferris:
[2018-07-08 Sun 12:40]

To pluck is to pick or pull a single item out of many, like a flower
or a hair. As a noun, pluck is energy or enthusiasm, even when things
are looking grim.

Don't pluck only the best cherries off the tree: that's
cherry-picking! Before you cook a goose, you need to pluck its
feathers. If it looks like your goose is cooked, however, then show
some pluck, and figure out a way to save yourself. Some characters who
are famous for showing pluck include the Artful Dodger, Little Orphan
Annie, and Benji the dog. They all kept their chins up and kept on
trying, even when things looked really dark.

When a character from Shakespeare calls the world his oyster, that's
his boastful way of saying that all the riches of the world are his
for the taking, like plucking a pearl from an oyster shell.

* servitude :Ferris:
[2018-07-16 Mon 10:29]

If you're free-spirited you won't enjoy servitude, mainly because
servitude means you have to answer to a master, like a servant does.

Slavery, a brutal form of servitude, existed in the United States
until the ratification of the Thirteenth Amendment in 1865. Before
this, thousands upon thousands of African Americans were forced into
servitude, where they were forced to perform labor for their masters.
A key to remembering the meaning of servitude is the fact that it
resembles servant.

If your friend rear-ends you but doesn't have insurance, let him pay
for the damage in servitude. Make him your personal assistant for a
month!

and 5:00 P.M., and since you’re trapped in the office for that period
of servitude, you are compelled to create activities to fill that time.
* compelled :Ferris:
[2018-07-16 Mon 10:30]

Compel means to force or drive someone to do something. Even if you
don't like toast, when you visit the toast-eating natives of
Shrintakook Island, you'll be compelled to eat it, or they will not
trust you.

You don't want to be compelled to go to a classical music concert if
you'd rather listen to rap. School officials might be upset if a
winter storm compels them to cancel classes, but you'd be okay with
that. A compelling mystery forces you to pay attention because you
want to find out "whodunit."

and 5:00 P.M., and since you’re trapped in the office for that period
of servitude, you are compelled to create activities to fill that time.
* imminent :Ferris:
[2018-07-16 Mon 10:38]

Something that is imminent is just about to happen: if you light a
firecracker and then stick it down your pants, a very bad situation is
imminent.

Imminent is from Latin imminere "to overhang," and to say that
something is imminent is to say that it is hanging over you and about
to fall, in a metaphorical way. If you take your mom’s car and drive
it into the mailbox, getting grounded is imminent. You don’t want that
hanging over your head!

It is
the magic of the imminent deadline.
* bustle :Ferris:
[2018-07-16 Mon 10:45]

A flurry of activity and commotion is often referred to as bustle. If
you want to see true bustle in action, just walk through Times Square
in New York during lunch hour.

If it's busy, energetic or moving about at a rapid pace, then it's
bustling. Word historians think bustle might stem from an Old Norse
word meaning "to prepare." However, it's probably easier to remember
bustle by the synonym it's often used with — hustle, as in "the hustle
and bustle of a big city."

Love of bustle is not industry.
* plopped :Ferris:
[2018-07-16 Mon 17:00]

To plop is to drop something (or yourself) with a short sound. The
sound itself is also a plop — like something landing in water without
much of a splash.

The sound of a plop is abrupt and hollow — you could also call it a
plunk or a or a plonk. You might plop an ice cube in your glass of
water, or watch a flock of bird plop themselves on the surface of a
pond. Plop is imitative or onomatopoeic (it sounds like its meaning),
and it first appeared in the 1820s after the brief popularity of the
alternative word plap.

Between my tenth and twelfth cupcakes, I plopped down on the couch to
revel in the sugar high until the clock struck midnight and sent me back
to my adultsville Sunday–Friday diet.
* disguise :Ferris:
[2018-07-16 Mon 17:06]

A disguise is something you put on so no one recognizes you. It also
can be used as a verb. You can disguise yourself with a wig and
mustache; that's a great disguise.

Disguise can be used anytime you're talking about concealing or hiding
something. Most of the time we think of a disguise as something you
wear, but you can also disguise your feelings. Criminals might
disguise their intentions. You can also use the word to describe
something that seems to be one thing, but turns out to be another. You
missed the plane, but then the plane crashed. That's a blessing in
disguise.

Dedication is
often just meaningless work in disguise.
* sane :Ferris:
[2018-07-16 Mon 17:12]

A sane person doesn't have any screws loose — in other words, they're
free of mental illness and in a reasonable state of mind.

You probably know that the word insane means crazy. Well, the opposite
of insane is sane — or not crazy. A sane person is of sound mind and
is mentally healthy. Sane people have good judgment, are reasonable,
and can tell the difference between what's real and imagined. Whenever
someone commits a crime or does something totally outlandish, people
usually wonder if they're sane or not.

Used even
once per month, this question alone can keep you sane and on track.
* Ditto :Ferris:
[2018-07-16 Mon 17:21]

A ditto looks like a quotation mark — " — and it's used as you go down
a list to indicate you're repeating whatever is above.

If your jellies and jams all cost $2.00, you can write $2.00 just once
with the first item on your price list and " in the price column next
to each item listed below. You can also use the word ditto informally
to describe repetition: "I can't believe you wore those shoes. Ditto
that hat." You may recognize Ditto as the aptly named son of the comic
strip characters Hi and Lois; he’s the twin brother of Dot.

Ditto.
* uncanny :Ferris:
[2018-07-17 Tue 20:42]

If something is uncanny, it is so mysterious, strange, or unfamiliar
that it seems supernatural. If you hear strange music echoing through
your attic, you might refer to it as positively uncanny.

You can also use uncanny to refer to something that is so remarkable
that it is beyond what is natural: as in "uncanny abilities." This
adjective was formed in English from the prefix un- "not" and canny
"fortunate, safe." The current meaning of English canny is "careful
and clever, especially in handling money."

FROM THIS POINT forward, I’m going to propose that you develop an uncanny
ability to be selectively ignorant.
* lieu :Ferris:
[2018-07-17 Tue 20:45]

To be in lieu of something is to replace it or substitute for it. A
restaurant that's run out of clams might serve French onion soup in
lieu of chowder.

The word lieu originally comes from the Latin locus, meaning "place,"
and its meaning has stayed true to its origins ever since. Though it
does have a standalone definition, "the position or function formerly
held by another," this noun is most commonly encountered in the phrase
"in lieu of," which means, basically, "instead of."

It gives you something new to ask
the rest of the population in lieu of small talk: “Tell me, what’s new in
the world?”
* crib :Ferris:
[2018-07-17 Tue 20:46]

A crib is a bed with high sides that babies sleep in. To crib is to
cheat, like copying off someone else during an exam. How babyish!

A crib is a small, cozy bed that has high sides known as slats. The
slats keep the baby from falling out. To crib is different — it means
to cheat, especially by copying or stealing information. If you stole
an answer key to a test, you cribbed it. If you friend told you the
answers to some homework, you cribbed the answers. Cribbing is
dishonest.

Using my crib notes approach to world affairs, I also retain more than
someone who loses the forest for the trees in a sea of extraneous details.