-*- coding: utf-8 -*-



* awareness :satellite:
[2018-10-02 Tue 09:33]

Awareness is the state of knowing something, such as the awareness
that the sun comes up every morning.

The adjective aware gets turned into a noun when the suffix -ness is
added, so awareness is the state of being aware, or having knowledge
of something. Its roots are Germanic, and come from the Old English
wær meaning "wary, cautious." Awareness can be something you notice,
want to tell others about, or already know. You could "raise
awareness" of a cause, like fighting breast cancer. Yet, your
awareness of the baby sleeping next door might prevent you from having
band practice in the garage. Smart move.

Personal development covers activities that improve awareness and
identity, develop talents and potential, build human capital and
facilitate employability, enhance the quality of life and contribute to
the realization of dreams and aspirations.
* aspirations :satellite:
[2018-10-02 Tue 09:34]

If your aspiration, or ambition, is to climb Mt. Everest someday, you
better start training, because it’s a long, hard climb that requires a
lot of preparation.

Aspiration means "inhalation" or "breathing." So how did it come to
mean "ambition" or "the will to succeed"? The Latin gives us a clue:
spirare ("to breathe") and spiritus ("spirit"). It was once believed
that our breath was our soul or spirit, which might explain why we
talk about "breathing life into" something, or coming up with energy
and ideas to invigorate it. How else to breathe life into something
than with ambition and drive, in other words, "spirit"?

Personal development covers activities that improve awareness and
identity, develop talents and potential, build human capital and
facilitate employability, enhance the quality of life and contribute to
the realization of dreams and aspirations.
* prevalence :satellite:
[2018-10-02 Tue 09:39]

Prevalence means there is a lot of something. If you get a bad grade
on a paper for having a prevalence of typos, you need to proofread
your work more carefully.

The word prevalence comes from the Latin praevalere, meaning
"condition of being widespread or general." The word is often used to
describe a phenomenon that is widespread in a community, like the
prevalence of a disease across a country. Prevalence is another word
for "commonness." If there's a prevalence of thefts in your
neighborhood, that means the likelihood of your house getting robbed
is pretty high.

However, there are two
newer ways increasing in prevalence: consumer-to-business and
consumer-to-consumer.
* astray :Covey:
[2018-10-11 Thu 16:32]

If you go astray, you lose the path. If you went to college intending
to become a doctor, but instead became interested in making violent
video games, your parents might feel you have gone astray.

A stray animal is one that has gotten loose, and the adverb astray
comes from this sense of wandering off from the proper place, even
though it's not just for animals. If you go astray, you lose the right
way, or are out of place. It can be a moral judgment: juvenile
delinquents are kids who have gone astray. But it can also refer to
small details. If you dress impeccably, you make sure that no thread
is astray.

Something or someone described as [errant] has gone astray or done
  wrong by going in an unexpected direction.