-*- coding: utf-8 -*-

* fidget                                                             :Ferris:
[2018-07-07 Sat 13:23]

To fidget is to make little movements with your hands and feet. Even
if you're nervous during your job interview, try not to fidget.

The word fidget is related to the Old Norse fikja, meaning "move
briskly, be restless or eager." If you are feeling impatient or
anxious you might fidget in your seat or fidget with a pen in your
hands. A person who fidgets a lot can be referred to as a fidget and
so can that quick anxious movement itself.

In the strictest sense, you shouldn’t be trying to do more in each day,
trying to fill every second with a work fidget of some type.

* guise :Ferris:
[2018-07-07 Sat 13:29]

The noun guise refers to an outward appearance that conceals the true
nature of someone or something. Your classmate might chat with you
under the guise of friendship, but you know she's really just looking
for juicy gossip.

No doubt you’ve noticed the similarity between guise and disguise.
Both involve the art of deception: it’s the methods that differ. Guise
is about trying on new attitudes and mannerisms, such as speaking and
acting in the guise of a native in a place where you are actually a
tourist. Disguise involves hiding your real identity, disappearing in
the new role.

Being busy is most often used as a guise for avoiding the few critically
important but uncomfortable actions.

* fuss :Ferris:
[2018-07-07 Sat 13:32]

If you are making a fuss, settle down! A fuss is a state of
excitement, and it's usually about something not worth worrying or
"fussing" about.

Most fusses are types of commotion. If someone makes a fuss, they're
overexcited and in a tizzy over something, like someone who can't stop
asking questions. Another fuss is angrier: you might say "What's the
fuss?" if you hear two people yelling at each other. A fuss is also
any kind of hubbub or whirlwind of activity, like a huge crowd
swarming toward a sale. Parents tend to fuss over their children.
Someone who fusses is worrying too much.

The options are almost limitless for
creating “busyness”: You could call a few hundred unqualified sales
leads, reorganize your Outlook contacts, walk across the office to
request documents you don’t really need, or fuss with your BlackBerry for
a few hours when you should be prioritizing.
* fart                                                               :Ferris:
[2018-07-07 Sat 13:40]

We don’t all like to admit it, but we all fart. That is, we all pass
smelly gas out of our anus.

Kids — and a few adults too — find farting funny. If someone lets out
a long fart during church or class, someone is bound to laugh.
However, the teacher probably won’t laugh, and the culprit could be in
big trouble. Be careful about accusing others of farting, because one
of the oldest rules of the schoolyard is “He who smelt it, dealt it.”
A less slangy word for fart is flatulence.

This is also true for the person who checks e-mail 30 times per day and
develops an elaborate system of folder rules and sophisticated techniques
for ensuring that each of those 30 brain farts moves as quickly as
possible.
* truism                                                             :Ferris:
[2018-07-07 Sat 13:41]

Here's a truism for you: Only people who look up words they don't know
can expand their vocabularies. Did you find that statement obvious,
boring, and saying nothing new or interesting? That's the perfect
description of a truism.

Sometimes truisms can be mistaken for factual statements. In fact,
despite their seeming obviousness, they are usually opinions. Many
people who look up words in the dictionary don't improve their
vocabularies, as much as they'd like to. Another truism: You get what
you pay for. Well, a lot of the time, sure, but not always. That's why
the word bargain was invented.

Here are two truisms to keep in mind:
*fFutility :Ferris:
[2018-07-07 Sat 13:44]

When you can’t see the point in even trying, that’s the feeling of
futility, the sense that no matter how much you work at it, nothing
good will happen, so you might as well give up.

What’s the point? That’s the question asked by anyone who senses the
futility of something. The futility of war makes soldiers put down
their weapons, and your father’s strict rules makes any protest an act
of futility. The root word is the Latin futilis, which literally means
“leaky.” Imagine pouring lemonade into a cup that has no bottom. No
matter how long you pour, you’ll never get a sip because of that leaky
cup. Ah, the futility!

Pareto and His Garden: 80/20 and Freedom from Futility
* wily :Ferris:
[2018-07-07 Sat 13:47]

Did you fall for that wily door to door salesman's pitch? He must be
very slick and tricky to have convinced you to buy a set of new tires,
considering you don't have a car.

How can you remember the meaning of the adjective wily? Just think
about the old Warner Brothers Looney Tunes cartoons. Their aptly named
cartoon character, Wile E. Coyote, got his name from a clever play on
words. Wile E. is supposed to be cunning, crafty, and clever — in
other words, wily. Wile E. is all those things, but unfortunately he
was usually bested by that pesky roadrunner anyway. Meep. Meep.

Vilfredo Pareto was a wily and controversial economist-cum-sociologist
who lived from 1848 to 1923.
* seminal :Ferris:
[2018-07-07 Sat 13:48]

Call something seminal when it's so original, so groundbreaking and
awesome that it will influence everything that comes after it. Picasso
produced more than a few seminal works of art, for example.

Technically, seminal means something related to semen or seeds. But
these days people more often use the word to describe something that
plants the seed for creative growth. An innovative piece of music or
literature, a fresh new idea, or an invention that changes everything
could each be called seminal. Synonyms include critical, fundamental,
original, and primary.

His seminal work, Cours d’economie politique, included a then
little-explored “law” of income distribution that would later bear his
name: “Pareto’s Law” or the “Pareto Distribution,” in the last decade
also popularly called the “80/20 Principle.”
* skewed                                                             :Ferris:
[2018-07-08 Sun 07:10]

Something skewed is slanted or off-center in some way. A picture frame
or viewpoint can be skewed.

This is a word, like so many, that can apply to physical things or
ideas. A painting on the wall is skewed if it's leaning to one side.
Also, opinions are often skewed: this is another way of saying someone
is biased. People often accuse news reports of being skewed toward one
political viewpoint. A movie could be skewed toward one character more
than the other. When you think of skewed, think of leaning and
slanting of all sorts.

The list is infinitely long and diverse, and the ratio is often skewed
even more severely: 90/10, 95/5, and 99/1 are not uncommon, but the
minimum ratio to seek is 80/20.
* mere :Ferris:
[2018-07-08 Sun 07:24]

Mere means pure and simple, nothing more and nothing less. If the mere
mention of someone's name makes you happy, then just hearing his name
— and that alone — is enough to make you smile.

Mere can have a little irony attached. If you introduce yourself as "a
mere student," when you’re announcing your astounding invention,
you're contrasting your lowly status with the enormity of your
invention. This kind of mere comes from the Latin for "undiluted."
Mere has a homograph — a completely different word that's spelled the
same — and this mere means a lake or a pond. It’s related to the Dutch
word meer — there’s lots of water in Holland.

Out of more than 120 wholesale customers, a mere 5 were bringing in 95%
of the revenue.
* cajoling :Ferris:
[2018-07-08 Sun 07:25]

To cajole someone is to persuade them by using insincere compliments
or promises. If you say "Please, pretty-please, I'll be your best
friend," when asking for a stick of gum, you are cajoling the gum
holder.

The origin of this word is probably a blend of two French words
meaning "to chatter like a jaybird" and "to lure into a cage." When
you cajole that guy into lending you some money, picture him as the
bird going into the cage. In fact, the word cajole may be associated
with another French word meaning "to put in jail."

I was spending 98% of my time chasing the remainder, as
the aforementioned 5 ordered regularly without any follow-up calls,
persuasion, or cajoling.
* mere :Ferris:
[2018-07-08 Sun 07:30]

Mere means pure and simple, nothing more and nothing less. If the mere
mention of someone's name makes you happy, then just hearing his name
— and that alone — is enough to make you smile.

Mere can have a little irony attached. If you introduce yourself as "a
mere student," when you’re announcing your astounding invention,
you're contrasting your lowly status with the enormity of your
invention. This kind of mere comes from the Latin for "undiluted."
Mere has a homograph — a completely different word that's spelled the
same — and this mere means a lake or a pond. It’s related to the Dutch
word meer — there’s lots of water in Holland.

Out of more than 120 wholesale customers, a mere 5 were bringing in 95%
of the revenue.
* plucking :Ferris:
[2018-07-08 Sun 12:40]

To pluck is to pick or pull a single item out of many, like a flower
or a hair. As a noun, pluck is energy or enthusiasm, even when things
are looking grim.

Don't pluck only the best cherries off the tree: that's
cherry-picking! Before you cook a goose, you need to pluck its
feathers. If it looks like your goose is cooked, however, then show
some pluck, and figure out a way to save yourself. Some characters who
are famous for showing pluck include the Artful Dodger, Little Orphan
Annie, and Benji the dog. They all kept their chins up and kept on
trying, even when things looked really dark.

When a character from Shakespeare calls the world his oyster, that's
his boastful way of saying that all the riches of the world are his
for the taking, like plucking a pearl from an oyster shell.
