-*- coding: utf-8 -*-


* obstinate :satellite:
[2018-12-04 Tue 16:41]

When someone is beyond stubborn, use the word obstinate instead: "You
obstinate old mule! Get out of my way!"

While stubborn may have positive or negative connotations, obstinate
is most definitely negative, because it implies a kind of hard-headed
determination not to change your mind even when it might be best to
rethink your position. "The obstinate Man does not hold Opinions, but
they hold him," wrote Samuel Butler way back in the seventeenth
century. The word still does the trick if you want a put-down for
someone you think is being a pig-headed fool or a stick in the mud.

Kipling and Earhart almost capture the secret to achievement, but we need to qualify
them because they can lead to obstinate persistence either to goals or methods that
aren’t working, and because they ignore or dismiss the emotional component of achieving
goals.
* disengage :satellite:
[2018-12-04 Tue 17:05]

To disengage means to "free or disentangle" yourself or some object
from another person or object. No, it doesn't mean breaking off your
engagement to your beloved — that's "chickening out."

Does your mind wander when someone (your fiancé, for example) talks to
you? Well, your mind can disengage as well, that is, stop paying
attention. Disengage has quite a formal, intellectual ring to it, even
if used about a situation as physical as two armies "disengaging from
combat." It's a technical term, and faintly clinical; the kind of word
frequently used by politicians and diplomats.

Then, about two years ago, my bestie, Josh Wateskin, recognizing that I couldn’t unwind
or disengage from my relentless analyzing of the world – especially the financial world
– recommended that I take up meditation.
* relinquish :satellite:
[2018-12-04 Tue 17:07]

If you relinquish something, you let it go. You relinquish control of
the army when you resign as general. You relinquish your plan to sneak
into town when your parents find out what's going on.

Relinquish is also commonly used to mean physically letting go of
something: The monkey wouldn't relinquish its grasp on the banana.
Relinquish descends from Latin relinquere, from the prefix re- "again"
plus linquere "to leave."

But, I eventually
reframed meditation as a way to relinquish control of my conscious mind so that my more
powerful unconscious mind could take over, and my analysis of the world would improve.
* beckons :satellite:
[2018-12-04 Tue 17:21]

To beckon is to use a physical gesture to call someone over to you.
Universally recognized gestures used to beckon include crooking the
finger or nodding the head to invite someone over.

We get the word beckon from the Old English gebecnian, meaning "to
make a mute sign," which comes from bēacen, meaning "a sign or
beacon." (Remember that "beacon" is a noun while beckon is a verb).
When you beckon to someone, you give them a physical sign to "come
here." Figuratively, an ice cream sundae might beckon you, calling you
away from your diet.

Almost always, the answer is,
“My mission,” which is like a beacon that always beckons.
* beacon :satellite:
[2018-12-04 Tue 17:22]

If your nose is shining like a beacon, I hope you are a reindeer
employed by a jolly fat man from the North Pole.

Beacon comes from an Old English word meaning “sign,” and that's what
actual beacons are for lost ships: signs of having made it to land.
Beacons are often some kind of light, like the bonfires that the
ancient Greeks lit on hillsides to communicate that an army had come
home from overseas. You'll also see beacon used figuratively,
especially in the phrase “beacon of hope.”

Almost always, the answer is,
“My mission,” which is like a beacon that always beckons.
* inherent :satellite:
[2018-12-04 Tue 17:25]

Use the adjective inherent for qualities that are considered permanent
or cannot be separated from an essential character.

We use the adjective inherent to describe attributes that are part of
the essential nature of something. It's different from you being tall,
rather than being a description, it has to be a quality and this
quality is unchangeable. So, for example, if you have never been able
to eat spinach, you have an inherent dislike of it.

It’s especially
hard for me because of my inherent optimism and my unflagging enthusiasm, and because I
always lean into each moment and every encounter expecting magic or miracles, and
because life has rewarded me increasingly with tantalizing offers.
* pursuits :satellite:
[2018-12-04 Tue 18:51]

A pursuit is a chase or a quest for something. When a guard runs after
an escaping jewel thief, she's in pursuit — while the thief may have
stolen the jewels because he was in pursuit of wealth.

Whether it's a police officer in a car chase or a student working
towards a college degree at a university in the tropics, both can be
considered in “hot pursuit.”  Derived from the Anglo-French purseute,
pursuit means the act of pursuing or striving towards goals. In the
late 14th century it implied persecution, but things have changed
since then.

Keep in mind that the time spent on pursuits not related to your mission is time that
could’ve been spent on it – not that all your time, of course, should be devoted to your
mission.
* ambushing :satellite:
[2018-12-04 Tue 18:55]

An ambush is a sneak attack. To ambush your enemy, hide and wait for
him to come near and then pounce on him.

In war or in backyards, an ambush is a great way to surprise someone.
Ambush comes from a Latin word meaning “to place in a wood,” and
hiding in the woods behind a tree is a classic starting point for an
ambush. The actual attack is called an ambush, but ambush is also a
verb, so you can ambush your mom by dropping water balloons on her
head from a tree. Please don’t tell her where you got that idea.

I get endless delight covertly ambushing unsuspecting strangers with
random acts of kindness.
* comprised :satellite:
[2018-12-06 Thu 00:44]

When something comprises other things, it is made up of them or formed
from them. The periodic table comprises 118 elements, because the
whole comprises the parts.

In its traditional use, the word comprise is the opposite of compose:
if A comprises X, Y, and Z, then X, Y, and Z compose A. But because
compose and comprise sound so much alike, people have long confused
the two. So now you often hear things like "The band is comprised of a
guitarist, a bassist, and a hairy drummer," whereas sticklers would
prefer "is composed of" in that sentence. The word is undergoing a
usage shift, making it just as hairy as that drummer!

In order to write a personal mission statement, we must begin at the
very center of our Circle of Influence, that center comprised of our
most basic paradigms, the lens through which we see the world.
* fickle :satellite:
[2018-12-06 Thu 01:28]

People who are fickle change their minds so much you can't rely on
them. If your best friend suddenly decides that she doesn't like you
one week, and then the next week she wants to hang out again, she's
being fickle.

Fickle comes from the Old English word ficol, for deceitful. We
usually use fickle to talk about people, but it can also be used for
abstract things that alternately favor you and abuse you, like the
weather. If you win the lottery and then lose everything else in the
world that's important to you, fate is being fickle.

Your security lies somewhere on the continuum between extreme
insecurity on one end, wherein your life is buffeted by all the
fickle forces that play upon it, and a deep sense of high intrinsic
worth and personal security on the other end.
