-*- coding: utf-8 -*-


* delight :satellite:
[2018-04-17 Tue 10:20]

** Translate from English to Russian:                                 :drill:

 delight

*** --->
  восторг

  noun
   1. восторг (delight, enthusiasm, rapture, admiration, elation, exaltation)
   2. наслаждение (pleasure, delight, enjoyment, gratification, relish, treat)
   3. удовольствие (pleasure, delight, enjoyment, gratification, treat, joy)
   4. восхищение (admiration, rapture, delight, adoration, applause, ravishment)
   5. прелесть (beauty, delight, loveliness, fascination, attraction, amenity)
   6. услада (delight)
   7. очарование (charm, fascination, glamor, enchantment, allure, delight)

  verb
   1. наслаждаться (enjoy, relish, delight, savor, revel, take pleasure in)
   2. восхищать (marvel, delight, enrapture, ravish, bewitch, entrance)
   3. восхищаться (admire, marvel, delight)
   4. услаждать (delight, regale)
   5. восторгать (delight, ravish, enrapture, entrance)
   6. доставлять наслаждение (delight)

  DEFINITION

  noun
   1. great pleasure.
      "she took great delight in telling your story"

  verb
   1. please (someone) greatly.
      "an experience guaranteed to delight both young and old"


  When you like someone, you might say, "She is an absolute delight."
  You mean you think she's great: a delight is a source of joy, and to
  delight is to cause pleasure. Babies are particularly good at
  expressing delight in new things.

  Delight is often associated with an initial impression—one says, "She
  continues to delight us," to suggest that the first impression
  continues. The word delight derives from the Latin delectare "to
  charm," which also gives us delectable, and the same lighthearted
  sense of pure, uncomplicated pleasure.

  My dad took special delight in the pseudoscientific jargon that Dr.
* afflicted :satellite:
[2018-04-17 Tue 10:23]
** Translate from English to Russian:                                 :drill:

 afflicted
*** --->
  страдающий

  adjective
   1. страдающий (suffering, afflicted, anguished)
   2. пораженный болезнью (afflicted, affected)
   3. огорченный (sorry, pained, grieved, sore, chagrined, afflicted)

  DEFINITION

  verb
   1. (of a problem or illness) cause pain or suffering to; affect or trouble.
      "serious ills afflict the industry"


  Afflicted means "impaired" or "stricken" and usually refers to a
  person who is mentally or physically unfit, or has been grievously
  affected by disease.

  This adjective's Latin root, afflictare, means "to damage, harass, or
  torment," which may sometimes be a good description of how an
  afflicted person feels. Those with mental illness may be tormented by
  voices in their head and thus be unable to distinguish what is real
  from what is not. Those afflicted by ALS, or Lou Gehrig's Disease,
  slowly lose control of their muscles and become paralyzed.

  My father’s
  business was especially afflicted with the “Teeter-Totter Syndrome” (“a
  complete inability to make decisions”) and “Cachinatory Inertia” (“the
  habit of telling jokes instead of getting on with business”).
* quaint :satellite:
[2018-04-17 Tue 10:24]
** Translate from English to Russian:                                 :drill:

 quaint
*** --->
  причудливый

  adjective
   1. причудливый (bizarre, quaint, fancy, whimsical, fanciful, freakish)
   2. необычный (unusual, extraordinary, odd, different, peculiar, quaint)
   3. привлекательный (attractive, appealing, engaging, inviting, lovable, quaint)
   4. привлекательный своей стариной (quaint)
   5. эксцентричный (eccentric, bizarre, whimsical, queer, erratic, quaint)
   6. приятный своей необычностью (quaint)
   7. приятный своей стариной (quaint)

  DEFINITION

  adjective
   1. attractively unusual or old-fashioned.
      "quaint country cottages"


  Quaint means strange and unusual in an old-fashioned and charming way.
  It's a word you'd use to describe a little store that sells tea cozies
  and antique tea services, or your grandmother's habit of calling the
  radio the "wireless."

  There is a commonly used sarcastic sense of quaint––when something is
  run down or shabby and you're trying to say something positive, you
  might substitute "How...quaint" for "How...interesting." In Middle
  English, this adjective meant clever or cunning. Its origin is Old
  French queinte, cointe, from Latin cognitus "known," from cognōscere
  "to learn."

  I expected it
  would be a quaint curiosity, that Dr.
* malady                                                          :satellite:
[2018-04-17 Tue 10:25]
** Translate from English to Russian:                                 :drill:

 malady
*** --->
  болезнь

  noun
   1. болезнь (disease, illness, sickness, ailment, malady, sick)
   2. расстройство (disorder, frustration, upset, disturbance, disorganization, malady)

  DEFINITION

  noun
   1. a disease or ailment.
      "an incurable malady"


  A malady is an illness, like a malady that keeps you home, sick in bed
  for days, or something that causes you to have trouble or to suffer,
  like jet lag — a malady that affects travelers.

  Malady, pronounced "MAL-uh-dee," comes from the Latin words male,
  meaning "bad or ill" and habitus for "have, hold." When you have a
  malady, it is like something bad is holding you, such as an illness —
  the common cold: a malady of winter. Some bad habits cause maladies,
  such as never having any money — the malady of people who spend
  freely, not thinking of the future.

  I presumed that the application of
  business knowledge developed over the last forty years would have
  stamped out many maladies described by Dr.
* engaging :satellite:
[2018-04-17 Tue 10:45]
** Translate from English to Russian:                                 :drill:

 engaging
*** --->
  обаятельный

  adjective
   1. привлекательный (attractive, appealing, engaging, inviting, lovable, catching)
   2. обаятельный (charming, glamorous, winsome, engaging, winning, ravishing)
   3. очаровательный (charming, enchanting, fascinating, glamorous, captivating, engaging)
   4. зацепляющийся (engaging)

  DEFINITION

  adjective
   1. charming and attractive.
      "Sophie had a sunny personality that was very engaging"

  verb
   1. occupy, attract, or involve (someone's interest or attention).
      "he plowed on, trying to outline his plans and engage Sutton's attention"
   2. participate or become involved in.
      "organizations engage in a variety of activities"


  A story, song, or person that is engaging is entertaining, fun, and
  interesting — you want to see or hear more.

  To remember the meaning of engaging, it might help to think of what
  engaged means. When a couple is engaged, they've agreed to get
  married. When something or somebody is engaging, you want to spend
  more time with them too. Boring is the complete opposite of engaging.
  Think of your favorite movie or TV show — especially one you can't
  stop watching — it must be very engaging.

  Peter, that market forces
  would have eliminated many or most organizations that were riddled with
  incompetence, and that subsequent writings on the subject would be more
  useful and engaging than The Peter Principle.
* fallacy :satellite:
[2018-04-17 Tue 10:53]
** Translate from English to Russian:                                 :drill:

 fallacy
*** --->
  ошибочность

  noun
   1. заблуждение (error, delusion, fallacy, mistake, wrong, aberration)
   2. ошибочность (wrong, fallacy, fallibility, falsity, falseness, fallaciousness)
   3. ошибка (error, mistake, fault, flaw, fallacy, miscarriage)
   4. софизм (sophism, fallacy, quibbling, quibble, quip, quiddity)
   5. обманчивость (deceitfulness, fallacy)
   6. ложный вывод (fallacy)

  DEFINITION

  noun
   1. a mistaken belief, especially one based on unsound argument.
      "the notion that the camera never lies is a fallacy"


  A fallacy is a misleading argument or belief based on a falsehood. If
  you oppose state testing in schools, you think it is a fallacy that
  educational quality can be measured by standardized tests.

  Fallacy comes from the Latin fallacia, for deceit. It technically
  means a flaw in an argument that makes it deceptive or misleading. In
  poetry, the "pathetic fallacy" is the false idea that things like
  rocks or stars have human feelings (pathos). Fallacy can also be used
  more generally for any false statement or idea. Some synonyms are
  misconception and error.

  Satire works when it exposes the truth and upends fallacy.
* incisive :satellite:
[2018-04-17 Tue 10:53]
** Translate from English to Russian:                                 :drill:

 incisive
*** --->
  язвительный

  adjective
   1. острый (acute, sharp, keen, spicy, poignant, incisive)
   2. резкий (cutting, sharp, abrupt, harsh, severe, incisive)
   3. язвительный (caustic, biting, acrimonious, waspish, incisive, spiteful)
   4. режущий (cutting, edgy, incisive, clipping, trenchant)
   5. колкий (caustic, poignant, prickly, barbed, sharp, incisive)

  DEFINITION

  adjective
   1. (of a person or mental process) intelligently analytical and clear-thinking.
      "she was an incisive critic"


  The adjective incisive describes something that is sharp, decisive,
  and direct. A comment that cuts right to the bone can be just as
  incisive as an actual knife.

  The word incisive is rooted in a Latin word that literally means "to
  cut with a sharp edge." To help you remember the meaning, you can
  think of the similar word, incisors, which are the teeth that are
  sharp and cut and tear. The more figurative meaning of describing
  something that is mentally sharp first appeared in the 1850s. Keen
  criticism and cutting remarks have been called incisive ever since.

  Peter was not only an incisive thinker but masterfully creative with
  words.
* stilted :satellite:
[2018-04-17 Tue 10:54]
** Translate from English to Russian:                                 :drill:

 stilted
*** --->
  неестественный

  adjective
   1. высокопарный (stilted, bombastic, grandiloquent, pompous, sonorous, magniloquent)
   2. неестественный (unnatural, stilted, hammy, stagey, affected, forced)
   3. ходульный (stilted, hammy)
   4. напыщенный (pompous, bombastic, stilted, turgid, highfalutin, flatulent)
   5. ходящий на ходулях (stilted)
   6. стоящий на сваях (stilted)

  DEFINITION

  adjective
   1. (of a manner of talking or writing) stiff and self-conscious or unnatural.
      "we made stilted conversation"
   2. standing on stilts.
      "villages of stilted houses"


  The adjective stilted describes something—usually a style of writing
  or speaking—that is unnaturally formal.

  Imagine someone walking awkwardly on a pair of stilts and you have a
  good impression of the word stilted — wooden and stiff. Stilt is found
  in the mid-15th century, referring to walking on wooden stilts across
  marshy ground. A hundred years later, the word stilted came to refer
  to the posts holding up a building. It wasn't until 1820 that the word
  was used as we use it now, to describe writing or speaking that does
  not flow smoothly.

  Peter invented dozens of strange,
  stilted, and pseudoscientific phrases and words.
* incumbent :satellite:
[2018-04-17 Tue 10:58]
** Translate from English to Russian:                                 :drill:

 incumbent
*** --->
  возложенный

  adjective
   1. возложенный (incumbent)
   2. возлежащий (incumbent, accumbent)
   3. лежащий (lying, recumbent, incumbent, superincumbent, decumbent)
   4. налегший всей тяжестью (incumbent)

  noun
   1. лицо, занимающее должность (incumbent)
   2. священник, имеющий приход (incumbent)

  DEFINITION

  adjective
   1. necessary for (someone) as a duty or responsibility.
      "it is incumbent on all decent people to concentrate on destroying this evil"
   2. (of an official or regime) currently holding office.
      "the incumbent president had been defeated"

  noun
   1. the holder of an office or post.
      "Voters may look back on an incumbent 's performance in office, and cast a retrospective vote, or may compare what the candidates promise to do if elected to office, and vote prospectively."


  An incumbent is an official who holds an office. If you want to run
  for congress, you're going to have to beat the incumbent.

  Incumbent comes from the Latin word incumbens, which means lying in or
  leaning on, but came to mean holding a position. It was first used in
  English for someone holding a church office, and then someone holding
  any office. You'll most likely hear it today for political officials.
  In a race for mayor, the incumbent mayor faces a challenger. Incumbent
  also means obligation. It is incumbent upon you to do the dishes.

  And I can’t find any behavioral science research on terms such as
  “Percussive Sublimation” (“being kicked upstairs: a pseudo promotion
  ”) and “Peter’s Circumambulation” (“a detour around a
  super-incumbent,” who is “a person above you who, having reached his
  level of incompetence, blocks your path to promotion”).
* detour :satellite:
[2018-04-17 Tue 10:58]
** Translate from English to Russian:                                 :drill:

 detour
*** --->
  объезд

  noun
   1. объезд (detour, tour, circuit, visitation)
   2. обход (bypass, detour, round, beat, diversion, flanker)
   3. окольный путь (detour, roundabout, sideway, back way, circumbendibus)

  verb
   1. изменять маршрут (reroute, detour)

  DEFINITION

  noun
   1. a long or roundabout route taken to avoid something or to visit somewhere along the way.
      "he had made a detour to a cafe"

  verb
   1. take a long or roundabout route.
      "he detoured around the walls"


  A detour is a longer, less direct way to get where you're going. A
  traffic accident sometimes means you have to take a detour to get
  home.

  When signs direct drivers to take a detour, it's usually because of
  road work or an emergency that's blocking traffic. You can also
  detour, or take an unexpected route, while you're running errands,
  stopping at your favorite bakery for a cookie before you continue on.
  The French détour comes from the verb destorner, "turn aside."

  And I can’t find any behavioral science research on terms such as
  “Percussive Sublimation” (“being kicked upstairs: a pseudo promotion
  ”) and “Peter’s Circumambulation” (“a detour around a
  super-incumbent,” who is “a person above you who, having reached his
  level of incompetence, blocks your path to promotion”).
* mock                                                            :satellite:
[2018-04-17 Tue 11:00]
** Translate from English to Russian:                                 :drill:

 mock
*** --->
  издеваться

  verb
   1. высмеивать (make fun of, ridicule, mock, deride, satirize, laugh)
   2. издеваться (scoff, mock, flout, ride, guy, roast)
   3. насмехаться (mock, taunt, scoff, razz, sneer, deride)
   4. глумиться (mock, scoff, sneer, jeer, flout)
   5. измываться (mock)
   6. передразнивать (mimic, imitate, mock, ape, give an imitation of, mime)
   7. сводить на нет (nullify, negate, stultify, whittle down, whittle away, mock)
   8. осмеивать (ridicule, mock, deride, guy)
   9. пародировать (parody, mimic, mock, travesty, burlesque)
  10. делать бесплодным (sterilize, mock)
  11. делать бесполезным (shrivel, frustrate, mock, destroy, spike)

  adjective
   1. ложный (false, spurious, mock, dummy, pseudo, erroneous)
   2. фиктивный (fictitious, dummy, bogus, mock, null)
   3. пародийный (burlesque, mock)
   4. мнимый (imaginary, alleged, supposed, mock, putative, seeming)
   5. притворный (mock, feigned, sham, pretended, simulated, hypocritical)
   6. поддельный (counterfeit, forged, spurious, bogus, faked, mock)

  noun
   1. насмешка (mockery, ridicule, sneer, taunt, jibe, mock)
   2. пародия (parody, travesty, spoof, skit, mockery, mock)
   3. подражание (imitation, emulation, echo, mock, takeoff)
   4. посмешище (mockery, laughing-stock, joke, derision, mock, jest)
   5. осмеяние (mockery, ridicule, derision, mocking, mock, jesting)

  DEFINITION

  adjective
   1. not authentic or real, but without the intention to deceive.
      "a mock-Georgian red brick house"

  noun
   1. an object of derision.
      "he has become the mock of all his contemporaries"

  verb
   1. tease or laugh at in a scornful or contemptuous manner.
      "he mocks them as Washington insiders"


  Imitation may be the most sincere form of flattery, but to mock is to
  make fun of or mimic someone with contempt, ridicule or derision.
  "Louise’s favorite pastime was to mock her brother’s inability to sing
  on key."

  The verb mock — as in the use that inspired the name of the
  mockingbird — can be simple imitation but, more often, to mock someone
  is to show disdain through mimicry or parody. As an adjective, mock
  indicates a fake or a simulation: "The design team made the most
  fabulous mock Eiffel Tower for our staging of An American in Paris."
  "His mock gratitude was, at times, unbearable."

  Peter’s claims also somehow mocks the overconfidence that runs
  through most self-help and business books, while simultaneously
  making his arguments more convincing.
* flourish :satellite:
[2018-04-17 Tue 11:03]
** Translate from English to Russian:                                 :drill:

 flourish
*** --->
  процветать

  verb
   1. процветать (prosper, thrive, flourish, do)
   2. расцветать (bloom, blossom, flourish, expand, effloresce)
   3. преуспевать (succeed, do well, prosper, get on, thrive, flourish)
   4. жить (live, dwell, stay, reside, exist, flourish)
   5. разрастаться (thrive, flourish, swell)
   6. размахивать (swing, swish, wave, brandish, shake, flourish)
   7. пышно расти (thrive, flourish)
   8. быть в расцвете (flourish, flower)
   9. действовать (act, operate, work, function, proceed, flourish)
  10. выставлять напоказ (flaunt, parade, display, air, splurge, flourish)
  11. цветисто выражаться (flourish)
  12. делать росчерк пером (flourish)

  noun
   1. туш (flourish, flourish of trumpets)
   2. загогулина (flourish)
   3. росчерк (flourish, scratch, twirl, dash, scroll)
   4. процветание (prosperity, flourish, bonanza, thrift, well-being)
   5. цветение (bloom, flowering, blossom, blossoming, flower, flourish)
   6. размахивание (swinging, flourish, flourishing)
   7. завитушка (twirl, flourish)
   8. помахивание (waggle, flourish)
   9. пышность (pomp, splendor, grandeur, flamboyance, glitter, flourish)
  10. цветистое выражение (flourish)
  11. фанфары (flourish, tucket)

  DEFINITION

  noun
   1. a bold or extravagant gesture or action, made especially to attract the attention of others.
      "with a flourish , she ushered them inside"
   2. a fanfare played by brass instruments.
      "a flourish of trumpets"

  verb
   1. (of a person, animal, or other living organism) grow or develop in a healthy or vigorous way, especially as the result of a particularly favorable environment.
      "wild plants flourish on the banks of the lake"
   2. (of a person) wave (something) around to attract the attention of others.
      "“Happy New Year!” he yelled, flourishing a bottle of whiskey"


  A flourish is an extra touch — a trumpet's "ta-ta-da!" announcing a
  king's entrance, a fancy carving atop an otherwise utilitarian pillar,
  a wave of a flag or a cheerleader's pompom.

  Flourish can also mean "growth": "With the right teacher, a child will
  flourish." To understand how the two meanings of flourish connect,
  remember that the word "flower" (spelled flour-) is hiding inside it.
  Flowers are used for decoration and ornamentation, but they also grow.
  Get it? Good for you! Imagine a cheerleader shouting out your name,
  flourishing her pom-poms.

  Peter’s rhetorical flourish and keen eye.
* renowned :satellite:
[2018-04-17 Tue 11:03]
** Translate from English to Russian:                                 :drill:

 renowned
*** --->
  прославленный

  adjective
   1. знаменитый (famous, renowned, celebrated, illustrious, famed, noted)
   2. прославленный (famous, renowned, celebrated, illustrious, famed, featured)

  DEFINITION

  adjective
   1. known or talked about by many people; famous.
      "a restaurant renowned for its Southwestern-style food"


  Celebrated, gushed over, and even legendary, something that's renowned
  is really famous. If you not only find a cure for cancer, but you also
  go on lots of talk shows so everyone knows who you are, then you'll be
  a renowned scientist.

  Renown comes from the Anglo-Norman for "re-name," as in repeatedly
  name, so something is renowned is something that people are talking
  about, or naming, over and over. If you are a huge celebrity, people
  from your home town might boast, "The renowned Madame X was born
  here." Something renowned is really good, not just famous. Just
  because you make the cover of a trashy tabloid magazine doesn't mean
  you're a renowned actress. But if you win an Oscar, you are.

  Stanford Professor and renowned economist Edward P.
* incomprehensible :satellite:
[2018-04-17 Tue 11:04]
** Translate from English to Russian:                                 :drill:

 incomprehensible
*** --->
  непостижимый

  adjective
   1. непонятный (incomprehensible, unclear, obscure, inexplicable, weird, inexplicit)
   2. непостижимый (incomprehensible, inconceivable, unfathomable, inscrutable, unknowable, mysterious)

  DEFINITION

  adjective
   1. not able to be understood; not intelligible.
      "a language that is incomprehensible to anyone outside the office"


  If your poetry is incomprehensible, it's difficult to understand, and
  it might be impossible to explain. Could be you're a genius! Could be
  you're just not very good at poetry.

  Incomprehensible originates from the Latin incomprehensibilis: in-
  ("not") and comprehensibilis ("perceptible, evident, intelligible").
  Many unfamiliar customs or rituals seem incomprehensible from a
  distance, for example, the early Chinese practice of foot binding, in
  which girls tightly bandaged their feet to prevent them from getting
  bigger. Similarly, future generations may find today's Western
  high-heeled shoes incomprehensible, leading them to ask, "What in the
  world were they thinking?!"

  Professor Lazear provides a string of impressive and (to most
  of us) incomprehensible mathematical formulas to explain why
  “individuals perform worse after having received promotion.”
* bliss :satellite:
[2018-04-17 Tue 11:08]
** Translate from English to Russian:                                 :drill:

 bliss
*** --->
  блаженство

  noun
   1. блаженство (bliss, blessedness, beatitude, felicity, blessing)
   2. счастье (happiness, luck, fortune, bliss, blessing, felicity)
   3. нега (bliss)

  DEFINITION

  noun
   1. perfect happiness; great joy.
      "she gave a sigh of bliss"

  verb
   1. reach a state of perfect happiness, typically so as to be oblivious of everything else.
      "blissed-out hippies"


  Bliss is a state of complete happiness or joy. Marriage is often
  associated with this joyous feeling: people who are married and still
  in love are described as living in wedded bliss.

  Another common association is heaven or paradise, as in eternal bliss.
  Bliss is from Middle English blisse, from Old English bliss, blīths.
  The final -s in this Old English word is actually a suffix and the
  word itself is related to blīthe, the source of modern English blithe,
  which means happy.

  Peter’s assertion that ignorance is bliss.
* exhort :satellite:
[2018-04-17 Tue 11:08]
** Translate from English to Russian:                                 :drill:

 exhort
*** --->
  увещевать

  verb
   1. увещевать (exhort, admonish, remonstrate, coax, expostulate)
   2. убеждать (urge, assure, convince, persuade, exhort, argue)
   3. заклинать (conjure, adjure, implore, exorcise, conjure up, exhort)
   4. защищать (protect, defend, advocate, uphold, guard, exhort)
   5. поддерживать (support, maintain, endorse, sustain, encourage, exhort)
   6. предупреждать (warn, prevent, notify, anticipate, notice, exhort)

  DEFINITION

  verb
   1. strongly encourage or urge (someone) to do something.
      "the media have been exhorting people to turn out for the demonstration"


  French roots for the word exhort mean "thoroughly encourage," so to
  exhort is to fill up with encouragement! "When he heard the crowd
  exhort him with stomping and cheers, he knew that he could finish the
  marathon."

  Some synonyms for exhort include stimulate, excite, and urge on. Words
  and shouts can exhort, and this is especially true when the recipient
  of those chants fears coming up short with an effort. Exhortations may
  make the difference between winning or losing and marching on or
  giving up. A sergeant might exhort his troops after a defeat just as a
  dad can exhort his daughter after a missed note during a piano
  recital.

  This conclusion clashes with numerous experts who
  exhort employees—especially managers—to face “brutal truths” and “hard
  facts.”
* ripe :satellite:
[2018-04-18 Wed 11:46]
** Translate from English to Russian:                                 :drill:

 ripe
*** --->
  созревший

  adjective
   1. спелый (ripe, mellow, mature)
   2. зрелый (mature, ripe, adult, virile, mellow)
   3. созревший (ripe, mature, full-fledged, fully-fledged)
   4. готовый (ready, prepared, willing, made, ripe, ready-made)
   5. выдержанный (seasoned, aged, vintage, mellow, mature, ripe)
   6. возмужалый (virile, ripe, grown-up)
   7. возмужавший (virile, ripe, grown-up)

  noun
   1. берег (coast, bank, strand, waterfront, riverside, ripe)

  DEFINITION

  adjective
   1. (of fruit or grain) developed to the point of readiness for harvesting and eating.
      "Outside in the back garden, he could see Mrs Galloway, who was their cook, picking ripe fruit from the strawberry patches nearby the greenhouse, collecting them in her apron."


  When a fruit is ripe, it is time to pick it and eat it. If you say the
  time is ripe, then now is the time for action. Ripe means ready.

  Ripe can also describe something that is not only ready to happen but
  well-suited for whatever is happening. A company can expect profits if
  the market is ripe for its product. When a ballpark has a short field,
  batters will say that the field is ripe for home runs. When things are
  ripe, it's a good thing — the time for action is now.

  Creative incompetence is another idea from The Peter Principle ripe for
  development.
* reprimand                                                       :satellite:
[2018-04-18 Wed 11:48]
** Translate from English to Russian:                                 :drill:

 reprimand
*** --->
  выговор

  noun
   1. выговор (rebuke, reprimand, pronunciation, scolding, reproof, demerit)
   2. замечание (comment, remark, observation, note, reprimand, admonition)
   3. встрепка (reprimand, scolding)

  verb
   1. выговаривать (reprimand, scold, lecture, speak at, talk to, tick off)
   2. объявлять выговор (reprimand)
   3. делать выговор (reprimand, admonish, reprove, rebuke, tax, reprehend)

  DEFINITION

  noun
   1. a rebuke, especially an official one.
      "The destruction of the Afghan Buddhas was met with reprimands from our officials, while ancient religious sites in our own country are being turned into quarries."

  verb
   1. rebuke (someone), especially officially.
      "officials were dismissed or reprimanded for poor work"


  If you're reprimanded, someone in authority speaks to you in an angry
  way because you've done something wrong. Or you might reprimand your
  dog if he steals your hot dog.

  The House of Representatives has a couple of ways to punish naughty
  members. One way is to reprimand them by voting to express
  disapproval. In 2009, Representative Joe Wilson was reprimanded after
  his outburst of "You lie!" during President Obama's speech. In the
  halls of Congress, this is considered "unparliamentary language," but
  if you yell at your congressman, that's okay.

  Greene” intentionally loses numerous receipts
  and packing slips, which leads to reprimands from the accounting
  department and causes his superiors to conclude that he has achieved
  final placement.
* deflect :satellite:
[2018-04-18 Wed 11:49]
** Translate from English to Russian:                                 :drill:

 deflect
*** --->
  отклонять

  verb
   1. отклонять (reject, dismiss, deflect, divert, turn down, turn away)
   2. отклоняться (deviate, digress, deflect, depart, diverge, wander)
   3. преломлять (refract, diffract, deflect)
   4. преломляться (deflect)

  DEFINITION

  verb
   1. cause (something) to change direction by interposing something; turn aside from a straight course.
      "the bullet was deflected harmlessly into the ceiling"


  The verb deflect describes blocking something or changing its course.
  Hockey goalies deflect the flying puck with their sticks or blockers,
  making it travel in a different direction, preferably to a teammate's
  stick.

  In a cartoon, a mouse might ask an approaching cat, "Hey, what's that
  up in the sky?" When the cat looks up, the mouse runs away, successful
  in his attempt to deflect the cat's attention. When you deflect, you
  throw someone or something off course, often by using a distraction.
  Another way to deflect something — such as criticism — is to blame
  someone else. Eventually the truth, like the cat who quickly sees
  there's nothing unusual up in the sky, catches up with those who
  deflect.

  It almost always works to deflect work one doesn’t want to
  do—without ever having to admit it.”
* cloak :satellite:
[2018-04-18 Wed 11:51]
** Translate from English to Russian:                                 :drill:

 cloak
*** --->
  плащ

  noun
   1. плащ (cloak, cape, slicker, pallium)
   2. мантия (mantle, gown, robe, cloak, pallium, pall)
   3. покров (cover, covering, veil, coat, blanket, cloak)
   4. маска (mask, guise, disguise, cover, visor, cloak)
   5. личина (guise, mask, disguise, cloak, cover, likeness)
   6. отговорка (excuse, pretense, subterfuge, pretext, evasion, cloak)
   7. предлог (pretext, excuse, preposition, guise, plea, cloak)

  verb
   1. маскировать (mask, camouflage, disguise, conceal, cloak, veil)
   2. скрывать (hide, conceal, mask, cover, keep, cloak)
   3. покрывать плащом (cloak)
   4. надевать плащ (cloak)
   5. прикрывать (cover, screen, cloak, shelter, veil, blank)

  DEFINITION

  noun
   1. an outdoor overgarment, typically sleeveless, that hangs loosely from the shoulders.
      "Though cloaks were standard dress from the 1st century AD, wool or linen clothes have not survived from Roman Britain."

  verb
   1. dress in a cloak.
      "she cloaked herself in black"


  A cloak is anything that conceals or hides something, like an
  over-sized, dark raincoat you wear when you don't want your friends to
  see you're going to the movies without them.

  As a noun, a cloak is usually a loose piece of clothing that you wear
  over your other clothes, like a cape or a gown. It especially refers
  to an outer garment that you might wear while traveling in order to
  protect your outfit or to conceal your identity. As a verb, to cloak
  is to conceal or hide something. If you were a famous person who
  wanted to go out alone, you might cloak your identity with a cloak.

  Peter (and coauthor Raymond Hull) decided to
  cloak these ideas in such a delightfully weird and perversely funny
  package.
* somber :satellite:
[2018-04-18 Wed 11:52]
** Translate from English to Russian:                                 :drill:

 somber
*** --->
  угрюмый

  adjective
   1. мрачный (gloomy, dark, grim, bleak, dismal, somber)
   2. угрюмый (sullen, gloomy, morose, surly, moody, somber)
   3. хмурый (frowning, gloomy, overcast, somber, sombre, glum)
   4. унылый (sad, dull, bleak, dismal, despondent, somber)
   5. темный (dark, obscure, deep, black, murky, somber)

  DEFINITION

  adjective
   1. dark or dull in color or tone; gloomy.
      "the night skies were somber and starless"


  Funerals are often somber affairs, and you might have a somber
  expression on face after your teacher hands back an exam you failed.
  Somber is used to describe situations, facial expressions, or moods
  that are dark, gloomy, or depressing.

  Something that is somber is often thought of as "in shadow," as in
  "the shadow of grief," or "the shadow of a bad mood." This is not just
  a coincidence. Somber comes from French sombre, which comes from Late
  Latin subumbrāre "to cast a shadow," from Latin sub umbrā "under a
  shadow."

  Peter
  realized that these unconventional and contrary ideas wouldn’t spread if
  they were enclosed in the usual, overly somber business book.
* clot                                                            :satellite:
[2018-04-18 Wed 11:54]
** Translate from English to Russian:                                 :drill:

 clot
*** --->
  сгусток

  noun
   1. сгусток (clot, bunch, gout, conglomeration, clod, coagulate)
   2. комок (ball, wad, clot, gob, nugget)
   3. тромб (thrombus, clot)
   4. свернувшаяся кровь (clot, gore)
   5. болван (boob, blockhead, doodle, dummy, loggerhead, clot)
   6. сверток (bundle, package, parcel, roll, clot)
   7. идиот (idiot, moron, jerk, wanker, nutcase, clot)
   8. участок породы (clot)

  verb
   1. свертываться (roll, clot, roll up, coagulate, curdle, furl)
   2. сгущаться (thicken, condense, coagulate, clot, deepen, boil down)
   3. запекаться (bake, clot, parch)
   4. створаживаться (clot)

  DEFINITION

  noun
   1. a thick mass of coagulated liquid, especially blood, or of material stuck together.
      "a flat, wet clot of dead leaves"
   2. a foolish or clumsy person.
      "“Watch where you're going, you clot!”"

  verb
   1. form or cause to form into clots.
      "drugs that help blood to clot"


  A clot is a mass of coagulated blood. It's your body's way of
  repairing itself, stopping blood from flowing and beginning to heal a
  wound.

  You can use the noun clot for any liquid that forms a solid lump or
  mass, though it's usually a medical term specifically related to
  blood. Some clots are useful, like the ones that form on skin that's
  been cut, while others — like those that occur inside blood vessels —
  can be harmful. Clot can also be a verb, meaning to clog or coagulate.
  The root is the German word Klotz, which means "lump or block."

  A Clot for Every Slot
* oversight :satellite:
[2018-04-18 Wed 11:55]
** Translate from English to Russian:                                 :drill:

 oversight
*** --->
  надзор

  noun
   1. недосмотр (oversight, inadvertence, inadvertency)
   2. надзор (supervision, oversight, surveillance, control, charge, superintendence)
   3. оплошность (oversight, gaffe, misstep, lapse, omission, inadvertence)
   4. присмотр (oversight, keeping, tendance)

  DEFINITION

  noun
   1. an unintentional failure to notice or do something.
      "he said his failure to pay for the tickets was an oversight"
   2. the action of overseeing something.
      "effective oversight of the financial reporting process"


  An oversight is a mistake you make when you're not paying full
  attention. Your failure to add the sugar to the cookies was an
  unfortunate oversight — you were so engrossed in texting that you
  forgot it.

  Oversights are not intentional mistakes. Usually they're just the
  result of inattention. If you make an oversight in your inspection of
  a nuclear power plant and it later goes into meltdown, you'll get
  fired. An inspector is supposed to pay attention. But if you forgot
  your cousin's birthday because you're busy taking care of Grandma,
  that's a forgivable oversight. Oversight is also the act of
  supervising something, like the construction of a dam, or a high
  school prom.

  I was not concerned with the oversight, the slip of the tongue, the faux
  pas, the occasional error which can be an embarrassment to any of us.
* faux :satellite:
[2018-04-18 Wed 11:56]
** Translate from English to Russian:                                 :drill:

 faux
*** --->
  Фо

  DEFINITION

  adjective
   1. made in imitation; artificial.
      "a string of faux pearls"


  Faux means fake, or imitation. If you love the look of diamonds but
  can't afford one, get a faux diamond ring.

  Faux is a French word that has crept into our lexicon, because faux in
  French means "fake." Now if we have the words fake, imitation, and
  false (all of which are good synonyms), why use faux? For fashion,
  dahling. Use faux to talk about faux fur, faux gemstones, or to make
  fun of a "faux pas," which is French for "no-no," widely used among
  the witty international set when someone does something gauche (French
  for "clumsy").

  I was not concerned with the oversight, the slip of the tongue, the faux
  pas, the occasional error which can be an embarrassment to any of us.
* lapse                                                           :satellite:
[2018-04-18 Wed 11:56]
** Translate from English to Russian:                                 :drill:

 lapse
*** --->
  упущение

  noun
   1. промежуток (interval, gap, space, lapse, distance, interspace)
   2. упущение (omission, lapse, flaw, overlook, dereliction, default)
   3. ошибка (error, mistake, fault, flaw, fallacy, lapse)
   4. оплошность (oversight, gaffe, misstep, lapse, omission, inadvertence)
   5. ляпсус (lapse, lapsus, trip)
   6. промежуток времени (period, while, interim, span, space, lapse)
   7. падение (drop, fall, incidence, falling, decline, lapse)
   8. прегрешение (lapse, trespass, peccancy)
   9. пропуск (pass, skip, omission, permit, gap, lapse)
  10. описка (slip of the pen, lapse, erratum, lapsus calami, lapse of the pen)
  11. ход (progress, stroke, running, travel, process, lapse)
  12. прекращение права (lapse)
  13. прошествие (lapse)
  14. падение температуры (drop in temperature, defervescence, lapse)
  15. прекращение права на владение (lapse)
  16. понижение давления (decompression, lapse)
  17. течение времени (passing of time, stream of time, course, flight, lapse)
  18. несерьезная ошибка (lapse)

  verb
   1. впадать (fall, lapse, sink, go into, empty, discharge)
   2. течь (flow, stream, run, course, flux, lapse)
   3. пасть (descend, lapse)
   4. проходить (pass, penetrate, go, run, cover, lapse)
   5. падать (fall, drop, tumble, go down, sink, lapse)
   6. приниматься за старое (lapse)
   7. терять силу (expire, lapse, sink, be out of court)
   8. истекать (expire, lapse, run out, emanate, outflow, fall in)
   9. переходить в другие руки (move, lapse)

  DEFINITION

  noun
   1. a temporary failure of concentration, memory, or judgment.
      "a lapse of concentration in the second set cost her the match"
   2. an interval or passage of time.
      "there was a considerable lapse of time between the two events"

  verb
   1. (of a right, privilege, or agreement) become invalid because it is not used, claimed, or renewed; expire.
      "my membership to the gym has lapsed"
   2. pass gradually into (an inferior state or condition).
      "the country has lapsed into chaos"


  A lapse is a temporary slip, failure or break in continuity. Eating a
  second helping of cake when you're otherwise doing well on your diet
  is a lapse. Eating the whole cake in one sitting is a serious lapse in
  judgment.

  First used to imply a “slip of the memory,” the noun lapse evolved in
  the sixteenth century from the Latin lapsus, meaning “a slipping and
  falling, falling into error.” The connotation of “a moral slip”
  developed later, and the verb form came into existence even later than
  that. Behaving badly one day when you're usually on your best behavior
  is a lapse; Behaving badly again after a short stint being
  well-mannered means you're lapsing back into nasty old habits.

  The most competent men throughout history
  have had their lapses.
* inept :satellite:
[2018-04-18 Wed 11:58]
** Translate from English to Russian:                                 :drill:

 inept
*** --->
  неподходящий

  adjective
   1. неподходящий (unsuitable, inappropriate, improper, inopportune, inept, ineligible)
   2. глупый (stupid, silly, foolish, fool, dumb, inept)
   3. неспособный (unable, incapable, incompetent, inefficient, inept, ineffective)
   4. неуместный (irrelevant, inappropriate, improper, incongruous, impertinent, inept)
   5. абсурдный (absurd, preposterous, grotesque, priceless, monstrous, inept)
   6. бессмысленный (nonsensical, senseless, meaningless, pointless, mindless, inept)
   7. недействительный (invalid, void, ineffective, null, unavailable, inept)

  DEFINITION

  adjective
   1. having or showing no skill; clumsy.
      "the inept handling of the threat"


  A clumsy, incompetent person — or an ineffective action — is inept.
  When you're inept, you don't know what you're doing or just can't get
  it done.

  Someone inept is bumbling, clueless, and ineffective. Inept people are
  dumb or clueless; they don't understand things. More than that, inept
  people are bad at what they do. An inept lawyer always loses cases. An
  inept figure skater wipes out on the ice. An inept postal worker loses
  mail and puts it in the wrong box. An inept person is downright bad at
  something. The opposite of inept is competent.

  Many others were inept at research
  design and, in desperation, were simply intending to replicate some
  oft-repeated statistical exercise.
* predicament :satellite:
[2018-04-18 Wed 11:59]
** Translate from English to Russian:                                 :drill:

 predicament
*** --->
  затруднительное положение

  noun
   1. затруднительное положение (predicament, fix, quandary, dilemma, quagmire, involvement)
   2. затруднение (difficulty, embarrassment, trouble, crux, quandary, predicament)
   3. категория (category, class, rank, denomination, predicament)

  DEFINITION

  noun
   1. a difficult, unpleasant, or embarrassing situation.
      "the club's financial predicament"
   2. (in Aristotelian logic) each of the ten “categories,” often listed as: substance or being, quantity, quality, relation, place, time, posture, having or possession, action, and passion.


  If you're engaged to get married but suddenly fall in love with
  someone else, you have gotten yourself into quite a predicament. A
  predicament is a difficult, confusing, and unpleasant situation.

  The Greek word that predicament originally descends from means "a
  state of being." Which makes sense considering the words that sound
  like predicate are all about states of being––predict, or say what's
  going to happen in the future, and predicate the second part of a
  sentence that's led by the verb. Think of predicament as an unpleasant
  state of being.

  As I became aware of their plan to spend time and taxpayers’ money on
  rediscovering the wheel, I decided to explain their predicament by
  introducing them to the Peter Principle.
* confide                                                         :satellite:
[2018-04-18 Wed 11:59]
** Translate from English to Russian:                                 :drill:

 confide
*** --->
  поверять

  verb
   1. доверять (trust, trust in, confide, entrust, rely on, believe)
   2. поверять (confide, unbosom, disembosom)
   3. полагаться (rely, lean, depend, trust, rely on, confide)
   4. признаваться (confess, own, avow, confide, avouch)
   5. вверять (entrust, commit, trust, commend, intrust, confide)
   6. поручать (entrust, charge, commit, delegate, commission, confide)
   7. сообщать по секрету (confide, whisper)

  DEFINITION

  verb
   1. tell someone about a secret or private matter while trusting them not to repeat it to others.
      "he confided his fears to his mother"


  To confide in someone is to tell them something privately. We confide
  in people we trust.

  We all have secrets and subjects that are hard to talk about. When we
  want to talk about something sensitive, we look for someone to confide
  in: a person we trust not to blab about our business to the rest of
  the world. Most people confide in close friends or family, often to
  get advice. If you tell someone a secret, and then they tell ten of
  their friends, you made a mistake by confiding in that person.

  Later he confided that his intense reaction was caused
  by my humorous presentation of outrageous ideas while at the same time
  he was watching the district research director’s face turn red, then
  purple.
* ensue                                                           :satellite:
[2018-04-18 Wed 12:01]
** Translate from English to Russian:                                 :drill:

 ensue
*** --->
  вытекать

  verb
   1. следовать (follow, abide by, result, steer, ensue, behoove)
   2. вытекать (flow out, run out, stream, ensue, outflow, overflow)
   3. происходить (occur, happen, take place, be, come, ensue)
   4. получаться в результате (issue, ensue)

  DEFINITION

  verb
   1. happen or occur afterward or as a result.
      "the difficulties that ensued from their commitment to Cuba"


  If something happens after something else, it will ensue, meaning it
  will follow after or be the result. When a sneeze comes out, and he
  hears the "Achoo!," a "Bless you" or "Gesundheit" soon will ensue.

  One way to remember the verb ensue is to rhyme it with "due." A
  happening that is due to happen will ensue, "Throwing a glass of ice
  water in his face guaranteed that a chase would ensue." Often what
  follows is a response to words or actions, so what will ensue is what
  will happen as a consequence. A struggle might ensue if a thief grabs
  a purse, and a discussion might ensue if two sides disagree.

  In the conversation that ensued, Mr.
* inquire                                                         :satellite:
[2018-04-18 Wed 12:04]
** Translate from English to Russian:                                 :drill:

 inquire
*** --->
  спрашивать

  verb
   1. спрашивать (ask, question, inquire, demand, interrogate, inquire for)
   2. исследовать (explore, investigate, examine, study, research, inquire)
   3. узнавать (learn, recognize, know, inquire, find out, get to know)
   4. наводить справки (inquire, investigate, enquire)
   5. справляться о (inquire, inquire after, ask after, enquire)
   6. добиваться сведений (inquire, enquire)

  DEFINITION

  verb
   1. ask for information from someone.
      "“How well do you know Berlin?” he inquired of Hencke"
   2. investigate; look into.
      "the task of political sociology is to inquire into the causes of political events"


  The verb inquire means "to ask for information." If you wonder about
  how the world began, you inquire about its origin.

  Inquire comes from the Latin combination of words in, meaning "into"
  and quærere, meaning "ask, seek." When you inquire, you look into
  something. You might ask a question, like inquiring if the bakery is
  hiring any cake decorators. Inquire can also mean "to conduct an
  investigation." No matter how you do it, when you inquire, you seek
  answers.

  In March, 1968, the President of William Morrow inquired about the
  possibility of a book about the Peter Principle.
* incessant :satellite:
[2018-04-18 Wed 17:12]
** Translate from English to Russian:                                 :drill:

 incessant
*** --->
  непрекращающийся

  adjective
   1. непрерывный (continuous, unbroken, uninterrupted, continued, continual, incessant)
   2. непрекращающийся (incessant, unceasing, perpetual, inextinguishable, never-ceasing, never-ending)
   3. непрестанный (ceaseless, incessant)
   4. несмолкаемый (incessant)
   5. ежесекундный (incessant, occurring every second)
   6. неумолкаемый (incessant)
   7. безумолчный (incessant, unceasing)

  DEFINITION

  adjective
   1. (of something regarded as unpleasant) continuing without pause or interruption.
      "the incessant beat of the music"


  Something incessant continues without interruption. When you're on a
  cross-country flight, it's tough to tolerate the incessant crying of a
  baby.

  In Latin, cessare means 'to stop,' so when you add the negative prefix
  in- you get a word meaning never stopping. A near synonym is
  continual, but something incessant is more relentless; ceaseless is a
  closer synonym. It's rare to find incessant used in a positive way.
  Even incessant sunshine would grow boring.

  A near synonym is incessant,
    which also refers to something unpleasant that continues without
    stopping.
* bland :satellite:
[2018-04-18 Wed 17:13]
** Translate from English to Russian:                                 :drill:

 bland
*** --->
  ласковый

  adjective
   1. мягкий (soft, mild, gentle, benign, bland, tender)
   2. вежливый (polite, courteous, gentle, bland, urbane, civil)
   3. ласковый (gentle, tender, sweet, soft, bland)
   4. вкрадчивый (insinuating, smarmy, smooth, bland, silky, wheedling)
   5. безвкусный (tasteless, gaudy, flavorless, insipid, inelegant, bland)
   6. успокаивающий (calming, soothing, sedative, tranquilizing, restful, bland)
   7. льстивый (flattering, sycophantic, smarmy, wheedling, ingratiating, bland)

  DEFINITION

  adjective
   1. lacking strong features or characteristics and therefore uninteresting.
      "rebelling against the bland uniformity"


  When you have a nasty cold and you’re very congested, food can taste
  unappealingly bland. That means dull, flavorless, or just plain
  “blah.”

  Bland comes to us from the Latin word blandus, meaning “mild, smooth,
  flattering, alluring.” Funny, because today you wouldn't say there's
  anything "alluring" about something bland. People still use bland to
  mean pleasant and tranquil, but it more often has a negative
  connotation. Use it to describe plain old oatmeal before you’ve added
  brown sugar and berries to it, or to depict the forgettable,
  uninteresting personality of the lunch lady who served it to you.

  [Mauve] is often considered a somewhat wishy-washy color,
    inoffensive and bland.
* sidewalk :satellite:
[2018-04-18 Wed 17:29]
** Translate from English to Russian:                                 :drill:

 sidewalk
*** --->
  тротуар

  noun
   1. тротуар (sidewalk, pavement, footpath, causeway, footway, sideway)
   2. пешеходная дорожка (footpath, sidewalk, footway, sideway)

  DEFINITION

  noun
   1. a paved path for pedestrians at the side of a road.
      "Proud old trees stood on the side of a large road, keeping the sidewalks in calming shade."


  A sidewalk is a paved path for walking, often alongside a road. If
  your neighborhood has sidewalks, it's easier and safer to take a
  little jog.

  While English speakers in other parts of the world might use words
  like footpath or pavement instead, North Americans typically use
  sidewalk. Most sidewalks are slightly higher than the street and are
  often separated from them by a curb or a strip of grass. There is some
  historical evidence that Ancient Greece had sidewalks, though the word
  itself dates from about 1740.

  A sidewalk is often composed of one cement [slab] after another —
    these are sometimes called paving [slab]s.
* slathered :satellite:
[2018-04-18 Wed 17:29]
** Translate from English to Russian:                                 :drill:

 slathered
*** --->
  намазанный

  verb
   1. намазывать толстым слоем (slather)
   2. тратить в больших количествах (slather)

  DEFINITION

  verb
   1. spread or smear (a substance) thickly or liberally.
      "slather on some tanning lotion"


  When you slather something, you apply or spread a lot of it. So you
  might slather your hamburger with ketchup, or slather shampoo on your
  damp head.

  Before it came to mean "spread liberally" in the nineteenth century,
  people in parts of England used slather to mean "slip or slide." Today
  we use this informal verb to describe smearing or rubbing, so we
  slather paint on a fence to cover up graffiti, slather aloe on our
  sunburnt skin, and slather peanut butter and jelly on bread.

  Even your lunch might be a [slab], if it's a thick hunk of cheesy
    pizza or a huge [slab] of bread slathered with peanut butter.
