-*- coding: utf-8 -*-



* merits :Covey:
[2018-11-01 Thu 11:31]

Merit means "worthiness or excellence." If you receive a certificate
of merit in school, you are being recognized for doing a good job. As
a verb, merit means "deserve." Your certificate might merit a
prominent place on your bulletin board!

You will often hear the phrases merit-based promotion and merit-based
pay, which come up when employees are pushing against a system in
which time on the job––and not job performance––determines when
workers are promoted and how much they are paid. Using the word merit
suggests impartiality and objectivity––such as when you swear off a
prejudiced approach to something and vow to "judge it on its merits."

We call these choices mistakes, and
they are the second thing that merits our deeper thought.
* commitments :Covey:
[2018-11-01 Thu 11:36]

Making a commitment involves dedicating yourself to something, like a
person or a cause. Before you make a commitment, think carefully. A
commitment obligates you to do something.

Some commitments are large, like marriage. When you take a job, you're
making a commitment to show up and do the job well, and your employer
makes a commitment to pay you. There are smaller commitments too. If
you said you'd meet a friend at six, that's a commitment — show up or
your friend will be mad. You also can speak of commitment as a
quality. Staying after school for a study group shows your commitment
to good grades.

At the very heart of our Circle of Influence is our ability to make and keep
commitments and promises.
* awareness :Covey:
[2018-11-01 Thu 11:38]

Awareness is the state of knowing something, such as the awareness
that the sun comes up every morning.

The adjective aware gets turned into a noun when the suffix -ness is
added, so awareness is the state of being aware, or having knowledge
of something. Its roots are Germanic, and come from the Old English
wær meaning "wary, cautious." Awareness can be something you notice,
want to tell others about, or already know. You could "raise
awareness" of a cause, like fighting breast cancer. Yet, your
awareness of the baby sleeping next door might prevent you from having
band practice in the garage. Smart move.

As we make and keep commitments, even small commitments, we
begin to establish an inner integrity that gives us the awareness of
self-control and the courage and strength to accept more of the
responsibility for our own lives.
* accusation :Covey:
[2018-11-01 Thu 11:42]

When you say someone is guilty of doing something wrong you make an
accusation, like your accusation that your brother used your computer
without asking first.

Accusation comes from the verb accuse, which means to charge someone
with a crime. It is important to remember that an accusation comes
about when someone thinks another person has done something wrong or
committed a crime. It doesn't mean, however, that the person is
guilty. There needs to be proof — an investigation or trial, even
admission of guilt — before a conviction, meaning the person really is
guilty.

Look at the weaknesses of others with compassion, not accusation.
* distended :Covey:
[2018-11-05 Mon 16:58]

A soda and pizza binge might make your stomach distend, meaning your
stomach will swell as a result of pressure from the inside.

If you’ve ever eaten too much food it won’t surprise you to learn that
the verb distend traces back to the Latin words dis-, meaning “apart,”
and tendere, meaning “to stretch.” Your stomach will certainly feel
stretched out if you do something — like overeat — that causes it to
distend. The word distend often applies to stomachs — a pregnancy
would also cause a stomach to distend — but it can also refer to
anything that is stretched out as a result of internal pressure.

When I first heard the term brain attic—back in the days of
  firelight and the old crimson hardcover—all I could picture in my
  seven-year-old head was the cover of the black-and-white Shel
  Silverstein book that sat prominently on my bookshelf, with its
  half-smiling, [lopsided] face whose forehead was distended to a
  wrinkled triangle, complete with roof, chimney, and window with open
  shutters.

* vindictive :Covey:
[2018-11-06 Tue 18:23]

It is no fun hanging out with vindictive people, who are forever out
to get back at people they think have hurt them. If you forget to say
hello to them one day in the hall, they will carry a grudge against
you into next week.

Vindictive is often paired with mean, as in "the atmosphere of the
cheerleading squad at my new school was vindictive and mean and I
wanted nothing to do with it." Vindictive rumors show a spirit full of
revenge. Vindictive is from Latin vindicta "revenge." The related
Latin verb vindicare has the very different meaning "to defend or
clear someone from guilt," and this is the source of the English verb
vindicate.

One of Gawker’s editors would say in a documentary about
Peter Thiel’s plot, “It was scarcely believable that something so
cinematically vindictive and conspiratorial and underhanded could
have actually happened.”
* underhanded :Covey:
[2018-11-06 Tue 18:23]

Use the adjective underhanded to describe someone who plays dirty
tricks, like a cheating poker player or a manipulative classmate.

It would be underhanded to spread gossip about your opponent during a
student council election, just as it's underhanded for a business
owner to pay herself more while laying off workers. If it's unfair and
sneaky, it's underhanded — unless you're pitching a softball, in which
case you're simply throwing it from below your shoulder instead of
above.

One of Gawker’s editors would say in a documentary about
Peter Thiel’s plot, “It was scarcely believable that something so
cinematically vindictive and conspiratorial and underhanded could
have actually happened.”
* apocryphal :Covey:
[2018-11-06 Tue 18:25]

Urban legends — stories about phantom hitchhikers, deep-fried rats,
and spider eggs in bubblegum — are classic examples of apocryphal
tales. They're told as if they're true, but no one can ever verify
their origins or authenticity.

Today, any dubious or unverifiable story may be dismissed as
apocryphal. Originally, however, apocryphal was reserved for religious
writings that were not included in the Torah or the New Testament of
the Bible because the divinity of the texts was not certain. These
texts are known as the Apocrypha and are included in the Septuagint (a
Greek version of the Hebrew Bible) and the Vulgate (a Latin Bible
edited in the 4th century).

There is the
apocryphal story about Vanderbilt after he was cheated by two
business partners in Nicaragua and lost his license to operate in the
country.
* undertaken :Covey:
[2018-11-06 Tue 18:26]

When you undertake a task or challenge, you attempt to accomplish it.
If you want to undertake a verbal challenge right now, try saying
“sushi chef” ten times quickly without messing up.

Way back in the 13th century, undertake meant “seize” or “entrap.” Of
course, the meaning has shifted significantly since then, and we hope
you don’t feel entrapped when you decide to undertake a project.
However, undertake does convey a level of commitment and involvement
that’s somewhat stronger than the words try or attempt might suggest.

He sent them a letter, “Gentlemen: You have undertaken to
cheat me.
* wielded :Covey:
[2018-11-06 Tue 18:27]

If you wield a tool or a weapon, you handle it effectively. Picture a
gallant knight wielding a sword or a skillful chef wielding a whisk.

You don't just have to wield something physical; you can also wield or
exert influence or authority. Wield is frequently followed by the word
power. If you were a king, you could wield great power in your kingdom
— exerting your influence over everything from food rations to castle
upkeep. As it is, though, you might just wield power over your pet
goldfish. Note: wield follows the i before e, except after c spelling
rule.

Power is sought so it can be wielded.
* vicissitude                                                     :satellite:
[2018-11-15 Thu 10:18]

When you talk of the vicissitudes of life, you're referring to the
difficult times that we all go through: sickness, job loss, and other
unwelcome episodes. No one can escape the vicissitudes of life.

While vicissitude comes from the Latin vicis, which means "change" and
technically can mean a change of any kind, you'll find that
vicissitude is almost always used to talk about an unfortunate event
or circumstance. Losing a pet, crashing the car, being called in for
jury duty: these are examples of vicissitudes — chapters in one's life
that one would rather avoid but must get through. Some lives have more
vicissitudes than others, to be sure, but no life is without events
that test and challenge us.

Then as the
vicissitudes, as the challenges come, I can make my decisions based on those values.
* allegiance                                                      :satellite:
[2018-11-15 Thu 11:46]

Every second grader knows how to pledge allegiance to the flag, but do
you think they realize when they place their right hand over their
hearts that they're expressing loyalty to what we call the "Red,
White, and Blue"?

You can pledge your allegiance to a flag or swear your allegiance to a
government or cause. Either way you're expressing your commitment and
devotion in the firmest sense of the word. The liege in allegiance
comes from the Old French word meaning "lord and master," which is who
you would have been swearing your allegiance to if you'd been a
servant in France centuries ago.

It is the document the president agrees to defend and support when he takes
the Oath of Allegiance.
* admit                                                           :satellite:
[2018-11-15 Thu 11:47]

When you admit something, you confess that it happened. It wasn't easy
to admit that you'd broken the vase, but how else could you explain
that your hand was glued to it?

Besides meaning "confess," admit can also mean "let in," like a
theater ticket that says "ADMIT ONE." If you admit that you have a bag
of popcorn hidden in your backpack, you might not be admitted to the
movie. A doorway admits you into a room, and if a room can hold up to
50 people, that room admits 50. You can even use admit for
metaphorical entrances, like the way your wild style admits you into
high fashion circles.

It is the criterion by which people are admitted into
citizenship.
* value :satellite:
[2018-11-15 Thu 11:50]

When you value something, you consider it important and worthwhile.
For example, if you value someone’s opinion, you will ask that
person's advice before making a big decision.

Value has to do with how much something is worth, either in terms of
cash or importance. As a verb, it means "holding something in high
regard," (like "I value our friendship") but it can also mean
"determine how much something is worth," like a prize valued at $200.
The noun value also relates to worth, like a used car that is a good
value, the value of good health, or the ideals we have, like "My
values include honesty and fairness."

The key to
the ability to change is a changeless sense of who you are, what you are about and what
you value.

* creed :satellite:
[2018-12-02 Sun 07:53]

Without reading the long document about the group's beliefs — its
creed — he knew he didn't fit in, because he just couldn't bow to the
12-foot statue of a rabbit, no matter what it symbolized.

A creed can be a formal doctrine, or system of beliefs, for a church
or religious group, or it can be a philosophy, or personal set of
beliefs. The origins of the word are in the Latin crēdō, "I believe,"
once specific to the Christian faith, but by the 17th century it was
used for many different faiths. Companies, societies, and disciplines
might also adopt a creed — as in a political creed, a national creed,
or a management creed — that lays out a particular belief-system or
way of doing things.

The most effective way I know to begin with the end in mind is to develop a personal
mission statement or philosophy or creed.
* proficiency :satellite:
[2018-12-02 Sun 07:55]

If you have proficiency with something, you are pretty good at it. If
you have proficiency with Spanish, you can understand and communicate
well in that language.

Proficiency, pronounced "pro-FISH-en-cee," comes from the Latin word
proficere, meaning "accomplish, make progress, be useful." If you have
achieved proficiency in something, you have done well at gaining a
skill. However, having proficiency doesn't make you an expert. Still,
proficiency is something to be proud of — it means you have worked
hard, and if you keep going, you probably will become an expert.

Develop one new proficiency a year.
* decisive :satellite:
[2018-12-02 Sun 07:55]

If you make decisions quickly, you are someone who is decisive. A
decisive event can settle something, like a war.

People who are wishy-washy are the opposite of decisive: being
decisive means you don't waffle or take forever to make up your mind,
and then you stick by what you decided. People admire politicians,
coaches, and friends who are decisive. In sports, if a home run won
the game, that was the decisive run. When you reach a crisis point in
life — when things are going to change one way or the other — you've
reached a decisive moment.

Be sincere yet decisive.
* orderly :satellite:
[2018-12-02 Sun 07:56]

Orderly means neat, tidy, and well-organized. An orderly library makes
it easy to find the books you want.

A thing or place can be orderly, like a desk, refrigerator, or a
hospital, and so can a person, particularly if they are very calm and
well-behaved. And when it's a noun, orderly means a hospital worker
who does many non-medical jobs and generally keeps things neat and
tidy — orderly, in other words. The Latin root is ordinem,
"arrangement or row," which originally meant "a row of threads in a
loom."

Be orderly in person and in work.
* allegiance                                                      :satellite:
[2018-12-02 Sun 07:58]

Every second grader knows how to pledge allegiance to the flag, but do
you think they realize when they place their right hand over their
hearts that they're expressing loyalty to what we call the "Red,
White, and Blue"?

You can pledge your allegiance to a flag or swear your allegiance to a
government or cause. Either way you're expressing your commitment and
devotion in the firmest sense of the word. The liege in allegiance
comes from the Old French word meaning "lord and master," which is who
you would have been swearing your allegiance to if you'd been a
servant in France centuries ago.

It is the document the president agrees to defend and support when he takes
the Oath of Allegiance.
* grudge                                                          :satellite:
[2018-12-02 Sun 13:46]

If you tend to hold a grudge, you don't let it go when you feel
someone's insulted or wronged you. I hope you won't hold a grudge
against me for bringing it up.

Grudge comes from the now dead Middle English word "grutch," which
meant "to complain or grumble." Someone who bears a grudge might often
be grouchy. You can specify a type of grudge: political grudge,
personal grudge, etc. You know Grandpa's been holding a grudge against
the neighbors for years, but you have to wonder: How long can he hold
that shotgun?

4 Holding grudges does not make you strong, it makes you bitter.
