-*- coding: utf-8 -*-

* tidy :satellite:
[2018-02-22 Thu 14:03]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       19629eb6-5b81-444b-b82e-d7462543108c
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:05]
   :END:

 tidy

*** --->
    [↗taɪdɪ]
  аккуратный

  adjective
   1. опрятный (neat, tidy, clean, trim, dapper, natty)
   2. аккуратный (orderly, careful, neat, tidy, trim, snug)
   3. чистый (clean, pure, net, clear, unadulterated, tidy)
   4. неплохой (fair, tidy)
   5. значительный (significant, great, considerable, large, substantial, tidy)
   6. довольно хороший (tolerable, middling good, tidy)

  verb
   1. убирать (remove, take away, tidy, clean up, tidy up, put away)
   2. прибирать (clean up, tidy, tidy up, clear up, pick up, do)
   3. приводить в порядок (put in order, settle, tidy, adjust, set in order, spruce)

  noun
   1. приборка (tidy)
   2. уборка (cleaning, harvesting, clean, cleanup, sweeping, tidy)
   3. салфеточка (doily, antimacassar, tidy)
   4. детский передник (tidy)

  DEFINITION

  adjective
   1. arranged neatly and in order.
      "his scrupulously tidy apartment"
   2. (of an amount, especially of money) considerable.
      "the book will bring in a tidy sum"

  noun
   1. a receptacle for holding small objects or waste scraps.
      "a desk tidy"

  verb
   1. bring order to; arrange neatly.
      "the boys have finally tidied their bedroom"


  Use the adjective tidy for something that is neat and clean. If your
  desk were more tidy, you would be able to find your computer.

  Tidy (or tidy up) also means “to clean up” and is also a noun for a
  container for small objects, like scraps or sewing materials. These
  senses of tidy have a formal or even old-fashioned note. (We’re more
  likely to say clean, organize, or bin now in everyday conversation.) A
  less informal use is as an adjective, meaning “large.” If you can put
  the word tidy before your profit or the sum in your bank account, it’s
  a good thing.

  on creating an environment for effectiveness refer
  to such matters as having a tidy office or home for unleashing
  creativity, and the need to protect "prime time".

* credentials :satellite:
[2018-03-10 Sat 11:41]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       ab60178b-fb13-4e3b-9bc3-68466536eefd
   :END:

 credentials

*** --->
  полномочия

  noun
   1. верительные грамоты (credentials, letters of credence, credential letters)

  DEFINITION

  noun
   1. a qualification, achievement, personal quality, or aspect of a person's background, typically when used to indicate that they are suitable for something.
      "recruitment is based mainly on academic credentials"


  Credentials offer proof of a fact, or of qualifications. A driver’s
  license, a doctor’s badge, or a diploma all count as credentials — as
  long as they’re real!

  One document can be a credential, but the word usually still gets
  pluralized. Credentials prove that the bearer has gotten credit for
  what he or she has done, as with a transcript, diploma, or certificate
  proving a person’s activities. Your credentials allow you to get the
  job, but your skills are what make you good at your job. Credentials
  can also prove that you are allowed to do something or go somewhere,
  like a badge that gets you past security.

  Before having her tonsils removed, Jahi McMath, a thirteen-year-old
  African-American girl from Oakland, California, asked her doctor,
  Frederick Rosen, about his credentials.
* slumber :satellite:
[2018-03-10 Sat 11:43]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       1a779e26-da56-4ff0-b8a9-adae1ff3305b
   :END:

 slumber
*** --->
  дремота

  noun
   1. сон (sleep, dream, sleeping, slumber, rest, repose)
   2. дремота (nap, slumber, drowsiness, dormancy, doze, somnolence)

  verb
   1. дремать (doze, nap, slumber, drowse, nod)
   2. спать (sleep, bed, rest, be asleep, slumber, do)

  DEFINITION

  noun
   1. a sleep.
      "scaring folk from their slumbers"

  verb
   1. sleep.
      "Sleeping Beauty slumbered in her forest castle"


  Slumber means "sleep" — as a verb or noun. If you're a sound sleeper,
  you might slumber peacefully right through a thunderstorm, your
  slumber undisturbed.

  To slumber is to sleep, sometimes specifically to sleep lightly or
  doze. You can slumber in your bed, in your airplane seat, or through
  your alarm in the morning. Slumber can also describe a peacefulness,
  like your quiet street that seems to slumber early in the morning. The
  phrase slumber party was first used in the 1940s to mean a gathering
  held at night, that usually involves very little slumbering.

  She snored so
  loudly that she was too embarrassed to go to slumber parties.
* chunky :satellite:
[2018-03-10 Sat 11:47]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       f8d98ce8-3f5d-4a33-88d5-55bd9f287de7
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 1.667
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:09]
   :END:

 chunky
*** --->
  коренастый

  adjective
   1. коренастый (stocky, chunky, thickset, stumpy, squat, dumpy)
   2. лохматый (shaggy, rough, bushy, shag, chunky, mope-headed)
   3. короткий и толстый (squab, chunky, squat, podgy, squatty, squabby)

  DEFINITION

  adjective
   1. bulky and solid.
      "a chunky bracelet"
   2. (of food) containing chunks.
      "fresh chunky salsa"


  Something that's full of little lumps and bits is chunky. Some people
  are crazy about chunky peanut butter, while others prefer it to be
  smooth and creamy.

  Some kinds of soup are chunky, with hunks of potato and pieces of
  broccoli, and you can also make a chunky spaghetti sauce that's full
  of tomato bits. When a person is described as chunky, it means they're
  dense and thick-bodied, and sometimes quite muscular. Chunky is an
  American English word, from the sense of chunk as "a thick piece of
  something,"

  Her classmates made
  fun of her for being “chunky,” and she absorbed the insults without
  protest.
* soothe :satellite:
[2018-03-10 Sat 11:49]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       946e6f55-96d6-4182-a813-95cd39da4a67
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:07]
   :END:

 soothe
*** --->
  успокаивать

  verb
   1. успокаивать (calm down, soothe, calm, settle down, reassure, comfort)
   2. утешать (comfort, console, soothe, solace, reassure, becalm)
   3. смягчать (soften, mitigate, remit, alleviate, moderate, soothe)
   4. облегчать (facilitate, alleviate, ease, relieve, lighten, soothe)
   5. тешить (amuse, soothe, salve)
   6. униматься (soothe, calm, stop)

  DEFINITION

  verb
   1. gently calm (a person or their feelings).
      "a shot of brandy might soothe his nerves"


  To soothe is to relieve or to bring comfort. If the pounding in your
  head is driving you mad, it sounds like you might need an aspirin or
  two to soothe your headache.

  Soothing is meant to make you feel better, both physically and
  emotionally. Spend too many hours on the beach without sunblock?
  You'll need some aloe to soothe that sunburn. Had a bad breakup with a
  boyfriend? Soothing that broken heart might take something stronger —
  chocolates, a gabfest with good friends, and sappy movies are usually
  just what the doctor ordered.

  on December 9, 2013, the nurses gave her a
  grape Popsicle to soothe her throat.
* digression :satellite:
[2018-03-11 Sun 11:18]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       98a10099-0623-486d-9c67-72c05b8f5325
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 4
   :DRILL_FAILURE_COUNT: 3
   :DRILL_AVERAGE_QUALITY: 1.75
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:09]
   :END:

 digression
*** --->
  отступление

  noun
   1. отступление (retreat, deviation, departure, digression, fallback, retirement)
   2. отклонение (deviation, deflection, rejection, departure, variation, digression)
   3. отступное (retreat, digression, deviation)

  DEFINITION

  noun
   1. a temporary departure from the main subject in speech or writing.
      "let's return to the main topic after that brief digression"


  When your essay about French cooking starts describing a childhood
  trip to Disneyland, it's taken a digression — it's strayed from the
  main topic.

  "But I digress" is a phrase often used by people when they realize
  they're no longer "on-topic." A digression is like a tangent, only
  digression often describes speech patterns, whereas tangent comes to
  us from mathematics. Another trick to remembering the meaning of
  digression is its relationship to the word progression. A progression
  is a series of ideas which proceeds in the same direction; a
  digression, logically enough, is an idea that goes off in another
  direction.

  I apologize for this digression but let's take a moment to talk
  about one of your past sponsors, namely Datadog.
* pageant                                                         :satellite:
[2018-03-12 Mon 14:37]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       186a285f-07f4-4b0e-8c26-83302ed13b74
   :END:

 pageant
*** --->
  маскарад

  noun
   1. зрелище (spectacle, sight, show, scene, pageant, raree-show)
   2. карнавальное шествие (pageant)
   3. маскарад (masquerade, pageant, mummery, fancy-dress ball)
   4. живая картина (tableau, tableau vivant, pageant)
   5. пышное зрелище (pageantry, pageant)
   6. инсценировка (staging, dramatization, pageant)
   7. пышная процессия (pageant)
   8. показное зрелище (pageant)
   9. бессодержательное зрелище (pageant)
  10. пустой блеск (pageant)
  11. подвижная сцена (pageant)

  DEFINITION

  noun
   1. a public entertainment consisting of a procession of people in elaborate, colorful costumes, or an outdoor performance of a historical scene.
      "Street pageants , parades and outdoor concerts have been lined-up to entertain locals and visitors and the street spectacular should not be missed for those who enjoy the magic of performance arts."


  A pageant is an elaborate show or parade that usually depicts a
  historical or religious event, although these days more people know
  them as Miss America-type beauty contests.

  Pageants aren't just for beauty queens — any richly decorated
  spectacle or ceremony could be considered a pageant. Around Christmas
  time, many Christian churches put on pageants that reenact the birth
  of Jesus. The Carnival parades in Brazil represent another type of
  pageant. And if your school organized a show where students had to act
  out famous moments in history? That would be a pageant, too.

  The Pageant of Fireflies
* spurt :satellite:
[2018-03-12 Mon 14:40]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       f7971373-7a24-44ae-a493-4914b39f9c26
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 1.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:06]
   :END:

 spurt
*** --->
  рывок

  noun
   1. рывок (jerk, spurt, dash, tug, snatch, yank)
   2. бросок (throw, cast, shot, dash, fling, spurt)
   3. приступ (attack, fit, assault, bout, seizure, spurt)
   4. вспышка (flash, outbreak, flare, outburst, burst, spurt)
   5. внезапное резкое усилие (spurt)
   6. взрыв чувства (spurt)
   7. сильная струя (spurt)

  verb
   1. бить струей (jet, spurt, spurt out, squirt, spurt down, spout)
   2. делать рывок (spurt)
   3. делать внезапное усилие (spurt)
   4. хлынуть (gush, flow, gush out, surge, stream, spurt)
   5. выбрасывать струей (spurt)

  DEFINITION

  noun
   1. a sudden gushing stream.
      "a sudden spurt of blood gushed into her eyes"

  verb
   1. gush out in a sudden and forceful stream.
      "he cut his finger, and blood spurted over the sliced potatoes"


  Things that spurt gush, stream, or flow rapidly. If you laugh too hard
  while drinking a Coke, soda might spurt out of your nose. Ouch!

  Spurt is also a noun: "A spurt of water erupted from the hole in the
  water balloon before she had a chance to throw it." Though a jet of
  liquid is usually what spurts, the word is also used for quick bursts
  of speed, like a race car that spurts forward suddenly, winning at the
  last second. The origin of spurt isn't certain, but it may be related
  to the German spürzen, "to spit" and sprützen, "to squirt."

  In the fields the maize
  was starting to fill out, the silken tassels turning from brown to butter-blond; when
  you tore off the wrapping of leaves and bit into the rows of pearly seeds the juice
  would spurt into your mouth like milk.
* salvo :satellite:
[2018-03-12 Mon 14:42]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       bdcbeb87-80c6-4088-baaa-be7514d41a38
   :END:

 salvo
*** --->
  залп

  noun
   1. залп (volley, salvo, discharge, round, flight)
   2. оправдание (justification, excuse, acquittal, defense, vindication, salvo)
   3. увертка (subterfuge, evasion, dodge, quip, quibble, salvo)
   4. отговорка (excuse, pretense, subterfuge, pretext, evasion, salvo)
   5. утешение (comfort, consolation, solace, relief, reassurance, salvo)
   6. оговорка (reservation, clause, proviso, qualification, slip of the tongue, salvo)
   7. лимитирование (salvo)
   8. бомбовый залп (salvo)
   9. батарейная очередь (salvo)
  10. взрыв аплодисментов (burst of applause, storm of applause, salvo)

  DEFINITION

  noun
   1. a simultaneous discharge of artillery or other guns in a battle.
      "Three days later, after the Leningrad - Moscow railway had been cleared, Stalin declared the blockade broken, and that night the city's anti-aircraft batteries fired victory salvos while the battle rumbled on the western horizon."


  A salvo is when troops fire their guns all at the same time. A salvo
  of shots might signal the beginning of a military battle.

  Another word for the gunfire kind of salvo is a "volley." Military
  planners have used salvos as a way to overwhelm an opposing army,
  including during engagements between battleships and tanks. You can
  also use salvo in a more figurative way, describing a verbal barrage
  or attack: "Her direct, almost rude questions were seen as the opening
  salvo in the battle between the two political candidates."

  Up on the hills, among the dark cypress and the heather, shoals of butterflies danced
  and twisted like wind-blown confetti, pausing now and then on a leaf to lay a salvo of
  eggs.
* lank :satellite:
[2018-03-12 Mon 14:43]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       7c561a5f-e76a-4e8d-b1db-505dc3a5928b
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:08]
   :END:

 lank
*** --->
  тощий

  adjective
   1. худощавый (thin, spare, slight, lank, scrawny, slabsided)
   2. тощий (skinny, lean, gaunt, scrawny, meager, lank)
   3. гладкий (smooth, sleek, plain, slick, polished, lank)
   4. высокий и тонкий (lank, slabsided)
   5. прямой (direct, right, straight, outright, straightforward, lank)
   6. невьющийся (lank, straight)
   7. длинный и мягкий (lank)

  DEFINITION

  adjective
   1. (of hair) long, limp, and straight.
      "My hair was lank and dull, I was very thin, brown pigmentation began to spread up my arms and on my cheeks; I was depressingly unattractive."


  Lank can describe grass that is long, hair that is limp, and people
  who are tall and thin.

  From the Old English hlanc (which is fun to say out loud), meaning
  loose and empty, lank is an adjective used to describe plant life
  which is long and slender, hair that hangs long and limp, and people
  who are long and slim. So you might hire a lank basketball player with
  lank hair to cut the grass when it’s lank. Or you might cut it
  yourself.

  They were
  lank and green, with chinless faces and monstrous globular eyes, frosty gold, with an
  expression of intense, predatory madness in them.
* mauve :satellite:
[2018-03-12 Mon 14:45]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       8991347d-ebe4-41fe-b924-bb5d868d0f80
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:06]
   :END:

 mauve
*** --->
  розовато-лиловый

  noun
   1. розовато-лиловый цвет (mauve)

  adjective
   1. розовато-лиловый (mauve)

  DEFINITION

  adjective
   1. of a pale purple color.
      "She wore a white tunic with pale mauve sleeves and veil."

  noun
   1. a pale purple color.
      "a few pale streaks of mauve were all that remained of the sunset"
   2. a bright but delicate pale purple aniline dye prepared by William H. Perkin ( 1838–1907 ) in 1856. It was the first synthetic dyestuff.
      "The first synthetic dye, mauve , was prepared in 1856 by the English chemist William Henry Perkin."


  Mauve is a paler tone of the color purple, and for some strange reason
  a beloved color for mothers of the bride.

  Mauve is often considered a somewhat wishy-washy color, inoffensive
  and bland. After all, the American novelist Alice Walker didn't
  entitle her great 1982 novel about black women's' lives in the
  American South The Color Mauve; she called it The Color Purple — far
  more suggestive of the powerful, violence-soaked drama it is.

  When
  the sun sank there was a brief, apple-green twilight which faded and became mauve, and
  the air cooled and took on the scents of evening.
* gauze :satellite:
[2018-03-12 Mon 14:46]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       78d4bdbe-2f5d-4172-87cb-5bf59a7cab5f
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:07]
   :END:

 gauze
*** --->
  марля

  noun
   1. марля (gauze, cheesecloth)
   2. газ (gas, gauze, gossamer)
   3. металлическая сетка (gauze)
   4. кисея (gauze)
   5. дымка в воздухе (gauze)
   6. проволочная ткань (gauze)

  adjective
   1. газовый (gas, gaseous, gauze, fiery, dampy)

  DEFINITION

  noun
   1. a thin translucent fabric of silk, linen, or cotton.
      "In their methods and approach, they use a range of materials that includes sand, printed fabric, mud, gauze and textured whites."
   2. a very fine wire mesh.


  Gauze is a loosely woven, almost translucent fabric that's used to
  bandage wounds. If you get a bad burn, a doctor might clean it and
  cover it with gauze.

  In medicine, gauze has several uses. Sterile gauze is usually kept in
  a sealed package, to ensure that it's perfectly clean. It can be used
  to clean cuts, scrapes, and burns, and also acts as a large bandage.
  There is also a non-medical fabric called gauze that's used in light,
  warm-weather clothing. The word's origin is mysterious — one guess
  traces it to the Arabic gazz, or "raw silk."

  They hopped furtively
  among the long grass clumps in the olive-groves, where the crane-flies' unsteady flight
  seemed to cover the ground with a drifting curtain of gauze.
* trifle :satellite:
[2018-03-12 Mon 14:46]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       62fe811f-abeb-4fa1-934c-65cdc106a1bc
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:07]
   :END:

 trifle
*** --->
  мелочь

  noun
   1. мелочь (trifle, small change, change, nothing, pocket money, short change)
   2. пустяк (trifle, nothing, nonsense, trinket, little, a mere nothing)
   3. безделица (trifle, bagatelle, minim, fiddlededee)
   4. безделушка (bauble, trinket, knick-knack, trifle, bijou, gadget)
   5. ничтожество (nothingness, nonentity, nullity, nobody, cipher, trifle)
   6. небольшая сумма (driblet, trifle, dribblet)
   7. небольшое количество (little, bit, dollop, sprinkling, mouthful, trifle)
   8. бездельник (lounger, idler, slacker, layabout, bum, trifle)

  verb
   1. шутить (joke, jest, trifle, fun, droll, rally)
   2. играть (play, act, perform, play on, toy, trifle)
   3. вертеть в руках (fumble, fiddle, trifle, toy, pick at)
   4. несерьезно относиться (dally, toy, trifle)
   5. заниматься пустяками (piddle, dally, niggle, chronicle small beer, trifle, palter)
   6. вести себя легкомысленно (trifle)
   7. тратить понапрасну (trifle, chuck away, trifle away)
   8. теребить (trifle, pick at, keep tugging)

  DEFINITION

  noun
   1. a thing of little value or importance.
      "we needn't trouble the headmaster over such trifles"
   2. a cold dessert of sponge cake and fruit covered with layers of custard, jelly, and cream.
      "There were cold meats of every kind, huge bowls of mixed salads, large desserts, trifles , jellies tarts and mince pies, and also some very interesting looking hors d' oeuvres."

  verb
   1. treat (someone or something) without seriousness or respect.
      "he is not a man to be trifled with"
   2. talk or act frivolously.
      "we will not trifle—life is too short"


  A trifle is something that's totally unimportant. If your friend is
  freaking out over which poster to buy and you call her dilemma a
  trifle, you're saying she shouldn't get so worked up over nothing.

  Trifle comes from the Middle English trufle, meaning "fraud, joke,
  trick." You'll usually hear it used to mean "insignificant, trivial."
  If you write a little ditty to sing at a birthday party, you could say
  it's just a trifle. As a verb, trifle means "toy with, waste." If you
  play with someone's feelings without seriously meaning anything, you
  are trifling with his affection. Trifle is also a sweet, sticky cake.
  Don't trifle the day away dreaming about trifle. Make some!

  They sat there blinking,
  and then would suddenly snap at a passing crane-fly; sitting back, looking a trifle
  embarrassed, they stuffed the trailing ends of wing and leg into their great mouths with
  the aid of their thumbs.
* soot :satellite:
[2018-03-12 Mon 14:48]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       1589f31b-b616-47f9-9bcb-f09b1ca9cca2
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:08]
   :END:

 soot
*** --->
  сажа

  noun
   1. сажа (soot, carbon black, smut, grime, smoke-black)
   2. копоть (soot, smoke)

  verb
   1. покрывать сажей (soot)

  DEFINITION

  noun
   1. a black powdery or flaky substance consisting largely of amorphous carbon, produced by the incomplete burning of organic matter.
      "Diesel particulate matter consists of soot mixed with anything from volatile organic compounds to sulphur and nitrous oxides."

  verb
   1. cover or clog (something) with soot.
      "The tremendous heat has consumed all vegetation, destabilized ground areas, sooted the work environment and caused burned trees to become unsafe."


  The powdery black stuff that's sometimes created when fuel burns is
  called soot. A chimney sweep's job is to clean all the soot and ash
  from inside a chimney.

  Soot is mostly made of carbon, and it forms when matter burns
  incompletely. Engines, burning coal, and house fires are all sources
  of soot, and soot is a major contributor to air pollution around the
  world. It's dangerous for people to breathe too much soot into their
  lungs. Soot comes from a Germanic root that literally means "what
  settles."

  The owls appeared now, drifting from tree to tree as silently as flakes of soot,
  hooting in astonishment as the moon rose higher and higher, turning to pink, then gold,
  and finally riding in a nest of stars, like a silver bubble.
* interminable :satellite:
[2018-03-12 Mon 14:50]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       f9180ac1-a079-4076-8e0d-52dc9c47a3b5
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:08]
   :END:

 interminable
*** --->
  бесконечный

  adjective
   1. бесконечный (endless, infinite, unending, perpetual, interminable, eternal)
   2. вечный (eternal, everlasting, perpetual, timeless, perennial, interminable)

  DEFINITION

  adjective
   1. endless (often used hyperbolically).
      "we got bogged down in interminable discussions"


  Use interminable to describe something that has or seems to have no
  end. Your math class. Your sister's violin recital. A babysitting job
  where five kids are going through your purse and the parents didn't
  leave a number.

  Something that is interminable is often boring, annoying, or hard to
  bear, such as an interminable noise. A near synonym is incessant,
  which also refers to something unpleasant that continues without
  stopping. It descends from the Latin prefix in- "not," terminare "to
  end," and the suffix -abilis "able to." Latin terminare is also the
  source of the English verb terminate "to end" and the corresponding
  noun termination "an act of ending something."

  At first the lessons were painful to an extreme: interminable
  wrestling with fractions and percentages, geological strata and warm currents, nouns,
  verbs, and adverbs.
* extricating :satellite:
[2018-03-12 Mon 14:55]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       f346c250-0d70-4aef-a141-28764803a12d
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 1.667
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:09]
   :END:

 extricating
*** --->
  высвобождая

  verb
   1. выводить (deduce, derive, conclude, show, remove, extricate)
   2. выпутываться (extricate, extricate oneself, bail out)
   3. выпутывать (extricate, disengage, disembarrass)
   4. разрешать (allow, authorize, resolve, permit, solve, extricate)

  DEFINITION

  verb
   1. free (someone or something) from a constraint or difficulty.
      "he was trying to extricate himself from official duties"


  If you need to be untangled, set free or otherwise released from
  something or someone, you need to be extricated.

  Extricate is a mixture of the prefix ex, which means "out" or "out
  of," and the Latin word tricae, which means "hindrances." So to
  extricate is to get out of what's hindering you. But it's not always
  so simple. You just try and extricate yourself from the loving death
  grip of a grandma who hasn't seen you in awhile!

  Sometimes these
  climaxes were so complicated and fraught with danger that I had great difficulty in
  extricating the family intact on the following day.
* protruding :satellite:
[2018-03-12 Mon 14:55]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       75cf51f6-4df6-449e-b1a9-472ae891671e
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:08]
   :END:

 protruding
*** --->
  выступающий

  adjective
   1. торчащий (sticking, protruding, erect, prominent, protrusive, obtrusive)
   2. выдающийся (outstanding, prominent, eminent, distinguished, remarkable, protruding)
   3. выступающий вперед (protruding, underhung, undershot)
   4. высунутый наружу (protruding)

  adverb
   1. навыкат (protruding)

  DEFINITION

  adjective
   1. sticking out; projecting.
      "a stocky guy with a furrowed brow and a protruding bottom lip"


  Something protruding is sticking out. When you're playing hide and
  seek, be sure your whole body is under the bed — a protruding arm or
  leg will give away your hiding spot.

  The part sticking out of an otherwise flat surface can be described as
  protruding. If a display is protruding from a storefront, you have to
  walk around it. If you have a big, red zit protruding from your
  forehead, you should probably see a dermatologist. And if you look up
  the mountainside and see rocks protruding, look out! Protruding rocks
  tend to fall down, which could put a damper on the hike.

  While I was at work on my
  masterpiece, breathing heavily, tongue protruding, breaking off for discussions with
  Roger on the finer points of the plot, Peter and Margo would take a stroll in the sunken
  garden to look at the flowers.
* conscience :satellite:
[2018-03-12 Mon 14:56]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       0b8eeff2-eb7e-4ea8-8fd3-cd4fc66b1003
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:07]
   :END:

 conscience
*** --->
    [↗kɘnʃɜns]
  совесть

  noun
   1. совесть (conscience, breast)
   2. сознание (consciousness, conscious, conscience, sense, feeling, recognition)

  DEFINITION

  noun
   1. an inner feeling or voice viewed as acting as a guide to the rightness or wrongness of one's behavior.
      "he had a guilty conscience about his desires"


  A conscience is a built-in sense of what's right and what's wrong.
  That sick feeling in your stomach after you meanly told your younger
  brother the truth about Santa Claus? That might be your conscience
  bothering you.

  The word conscience contains the word science, which comes from the
  Latin word scientia, meaning "to know" or "knowledge." You can think
  of your conscience as your knowledge of yourself, especially when it
  comes to your own morals, or your feelings about right and wrong.
  Pangs of conscience, which feel like an uncomfortable inner voice, are
  helpful when you're trying to decide the right thing to do in a
  particular situation.

  Occasionally, in the early days, Peter suffered from sudden spasms of conscience, my
  epic would be relegated to a drawer, and we would pore over mathematical problems.
* relegated :satellite:
[2018-03-12 Mon 14:57]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       6c826b85-08fc-48ba-b3a9-6f6919d75703
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 1.667
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:09]
   :END:

 relegated
*** --->
     [↗rɛlɪgɛɪt]
  низведена

  verb
   1. относить (refer, attribute, relegate, take, take to, take back)
   2. передавать (pass, transmit, transfer, send, convey, communicate)
   3. низводить (relegate)
   4. отсылать (send, refer, send off, dispatch, relegate, bundle)
   5. направлять (guide, head, direct, destine, route, refer)
   6. разжаловать (bust, degrade, disgrace, relegate, break, lower)
   7. классифицировать (classify, categorize, sort, class, rank, pigeonhole)
   8. передавать для исполнения (relegate)
   9. передавать для решения (relegate)
  10. переводить в низшую категорию (relegate)
  11. переводить в низшую лигу (relegate)
  12. сдавать в архив (file, relegate)
  13. ссылать (exile, deport, relegate)
  14. высылать (expel, deport, send out, banish, dispatch, proscribe)

  DEFINITION

  verb
   1. consign or dismiss to an inferior rank or position.
      "they aim to prevent women from being relegated to a secondary role"


  Relegate means assign to a lower position. If the quarterback of the
  football team stops making decent throws he might be relegated to the
  position of benchwarmer, while another kid is given the chance to
  play.

  Relegate rhymes with delegate––both words derive from the Latin legare
  "send." Relegate means to send someone down in rank. Delegate means to
  send someone in your place to complete a task. In the workplace,
  managers who can't figure out how to delegate may get relegated to a
  lesser rank.

  Occasionally, in the early days, Peter suffered from sudden spasms of conscience, my
  epic would be relegated to a drawer, and we would pore over mathematical problems.
* pore :satellite:
[2018-03-12 Mon 14:57]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       3b6716c4-4ce7-4025-9ab4-ae6fa357079a
   :END:

 pore
*** --->
  поры

  noun
   1. пора (time, pore, date, day, season, tide)
   2. скважина (well, hole, bore, chink, slit, pore)

  verb
   1. размышлять (reflect, meditate, think, ponder, contemplate, pore)
   2. сосредоточенно разглядывать (pore)
   3. сосредоточенно изучать (pore)
   4. обдумывать (think, ponder, consider, think over, mull, pore)
   5. сосредоточиться (pore)

  DEFINITION

  noun
   1. a minute opening in a surface, especially the skin or integument of an organism, through which gases, liquids, or microscopic particles can pass.
      "Stomata are minute pores in the surface of leaves through which water vapor and gases, including carbon dioxide, pass."

  verb
   1. be absorbed in the reading or study of.
      "Heather spent hours poring over cookbooks"


  That trickle of sweat didn't just miraculously appear — it was
  secreted out of a pore, a really tiny opening on the surface of your
  skin.

  When used as a noun, pore means any tiny hole or opening that allows
  the passage of liquid. In humans, pores are the little holes that
  bring us such pleasures as armpit sweat and, when clogged, pimples.
  But when used as a verb, to pore means to concentrate your attention
  on or devote hours of focus to something: like poring over the
  overwhelming choices in the antiperspirant aisle.

  Occasionally, in the early days, Peter suffered from sudden spasms of conscience, my
  epic would be relegated to a drawer, and we would pore over mathematical problems.
* slab :satellite:
[2018-03-12 Mon 15:00]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       e8117f11-bde4-4d45-b777-d3a3dc3953af
   :END:

 slab
*** --->
  горбыль

  noun
   1. плита (plate, stove, cooker, slab, table, flag)
   2. пластина (bar, slab, platten)
   3. горбыль (slab, flitch)
   4. плоская заготовка (slab)
   5. ломоть (hunk, slice, chunk, hunch, slab)
   6. кус (slab)
   7. большой кусок (slab)
   8. слабина паруса (slab)
   9. жидкая грязь (slop, slab)

  adjective
   1. густой (thick, dense, bushy, heavy, rich, slab)
   2. вязкий (viscous, ductile, tough, viscid, pasty, slab)

  verb
   1. мостить плитами (slab)
   2. срезать горбыли (slab)

  DEFINITION

  noun
   1. a large, thick, flat piece of stone, concrete, or wood, typically rectangular.
      "paving slabs"

  verb
   1. remove slabs from (a log or tree) to prepare it for sawing into planks.
      "The company has developed and supplies a unique slabbing system."


  A slab is a great big thick piece of something. Your backyard patio,
  for example, might be made of a huge slab of concrete.

  A sidewalk is often composed of one cement slab after another — these
  are sometimes called paving slabs. You could refer to large pieces of
  stone or wood as slabs too. Even your lunch might be a slab, if it's a
  thick hunk of cheesy pizza or a huge slab of bread slathered with
  peanut butter. The origins of the word slab are unknown, though we do
  know it's been around since the thirteenth century.

  The walls were sparsely, but tastefully, decorated with a slab slate
  containing the fossilized remains of a fish, a photograph of myself shaking hands with a
  chimpanzee, and a stuffed bat.
* slate :satellite:
[2018-03-12 Mon 15:01]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       50a744d2-88b5-47db-90bb-6d3b79caca68
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:06]
   :END:

 slate
*** --->
  шифер

  noun
   1. шифер (slate, shiver, schist)
   2. список кандидатов (slate, waiting list)
   3. грифельная доска (slate)
   4. аспидный сланец (schist, slate, shale)
   5. шиферный сланец (slate)
   6. аспид (asp, viper, slate, schist)
   7. шиферная плита (slate)
   8. синевато-серый цвет (slate)

  verb
   1. намечать (schedule, target, chalk out, slate, trace, roughcast)
   2. крыть шифером (slate)
   3. крыть шиферными плитами (slate)
   4. заносить в список кандидатов (slate)
   5. выдвигать на должность (slate)
   6. назначать (assign, appoint, nominate, set, administer, slate)
   7. планировать (plan, schedule, glide, map out, target, slate)
   8. выбранить (sit on, sit upon, slate)
   9. делать выговор (reprimand, admonish, reprove, rebuke, tax, slate)
  10. раскритиковать (cut up, slam, slate, scalp, cry down)

  DEFINITION

  noun
   1. a fine-grained gray, green, or bluish metamorphic rock easily split into smooth, flat pieces.
      "The most resistant rocks are quartzite and quartz-rich sandstones, and tough fine-grained rocks such as slate ."
   2. a flat piece of slate used for writing on, typically framed in wood, formerly used in schools.
      "The colliery village's principle attractions are the driftwood mine, where the visitor is taken to the coalface, and the school, in which children can try out the desks and writing slates and play games of the period."
   3. a bluish-gray color.
      "suits of slate gray"
   4. a list of candidates for election to a post or office, typically a group sharing a set of political views.
      "another slate of candidates will be picked for the state convention"

  verb
   1. cover (something, especially a roof) with slates.
      "The roof will be slated and the front elevations will mostly be of natural stone, and each house has a large back garden."
   2. criticize severely.
      "his work was slated by the critics"
   3. schedule; plan.
      "renovations are slated for late June"
   4. identify (a movie take) using a slate.
      "They discuss how to proceed, conduct run-throughs, slate shots, film the filming; and as they do so, you get to know these young people."


  Slate is a type of gray metamorphic rock that is made up of quartz and
  other minerals. The rock can be split into thin layers and the slate
  used for things like roofing tiles.

  In the past when paper was expensive, schoolchildren used slates to do
  their school work. These were usually made of actual slate rock.
  Students could practice their writing on the slate with a slate
  pencil. When they were done, the slate could be erased, which gave
  rise to the term "clean slate." If you've done things in the past you
  aren't proud of, you may hope to start over with a clean slate.

  The walls were sparsely, but tastefully, decorated with a slab slate
  containing the fossilized remains of a fish, a photograph of myself
  shaking hands with a chimpanzee, and a stuffed bat.

* freckled :satellite:
[2018-03-15 Thu 09:33]

** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       eac7c217-a948-46b5-99ed-ecfc8aa34adc
   :END:

 freckled

*** --->
  веснушчатый

  adjective
   1. веснушчатый (freckled)
   2. конопатый (freckled)

  DEFINITION

  verb
   1. cover or become covered with freckles.
      "skin that freckles easily"


  If you have freckles scattered across your nose, you can call yourself
  freckled. It's pretty common for people with red hair to be freckled.

  Freckles are tiny concentrated spots of color on the skin, and someone
  who has them on her body is freckled. You might appear more freckled
  after spending time in the sun — or you may just be naturally freckled
  no matter how little sun you get. The number of freckles you have is
  genetic: if your mom and grandma are freckled, chances are you will
  be, too.

  On the vines the grapes hung in tiny
  clusters, freckled and warm.
* weighed :satellite:
[2018-03-15 Thu 09:34]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       e99a2f30-ab51-4d60-bb43-c69403f64ade
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:06]
   :END:

 weighed
*** --->
  взвешенный

  adjective
   1. взвешенный (suspended, weighed, measured, deliberated)

  DEFINITION

  verb
   1. find out how heavy (someone or something) is, typically using scales.
      "weigh yourself on the day you begin the diet"
   2. assess the nature or importance of, especially with a view to a decision or action.
      "the consequences of the move would need to be very carefully weighed"


  To weigh is all about judging; you could be seeing how heavy something
  is or if it is a good choice. You could weigh the tomatoes you're
  buying or weigh your options when applying to college.

  To weigh something can mean to physically assess its weight — is it 3
  pounds? 40 kilos? 22 grams? But it's no accident that the symbol for
  justice is often a scale. That's because all of the facts of a case
  need to be weighed or evaluated for justice to be served. And
  hopefully the decision will be balanced and fair.

  The olives seemed weighed down under the
  weight of their fruit, smooth drops of green jade among which the choirs
  of cicadas zithered.
* supplication :satellite:
[2018-03-15 Thu 09:37]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       5fbfe34e-c8c6-45da-903d-2af295e4e384
   :END:

 supplication
*** --->
  мольба

  noun
   1. мольба (pleading, plea, supplication, prayer, entreaty, cry)
   2. просьба (request, application, plea, petition, wish, supplication)

  DEFINITION

  noun
   1. the action of asking or begging for something earnestly or humbly.
      "he fell to his knees in supplication"


  Think of a supplication as sort of a prayer, a request for help from a
  deity. The word carries a sense of awe and adoration with it,
  suggesting something tentative, even servile, a respectful appeal to a
  higher power.

  Although it is a noun, supplication comes from the Latin verb
  supplicare, which means "to plead humbly." While a supplication is
  often thought of as a religious prayer (it is used 60 times in the
  Bible), it can logically be applied to any situation in which you must
  entreat someone in power for help or a favor. Still, it carries with
  it an aura of religiosity and deep entreaty, and should not be used to
  describe just any simple request.

  The crooked arms, with their fringes of sharp teeth, would be
  raised in mock supplication to the insect world, so humble, so fervent,
  trembling slightly when a butterfly flew too close.

* furtively :satellite:
[2018-03-15 Thu 09:39]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       687f4948-7f63-47b3-9201-96fc34cb3439
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 1.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:04]
   :END:

 furtively

*** --->
  украдкой

  adverb
   1. украдкой (by stealth, stealthily, furtively, tiptoe, on tiptoe)
   2. тайно (secretly, in secrecy, stealthily, privily, underground, furtively)
   3. крадучись (furtively)
   4. воровски (furtively, thievishly)


  The adverb furtively is great for describing the movements or behavior
  of someone who's being sneaky or sly. Kids decorating their neighbor's
  trees with toilet paper on Halloween tend to sneak furtively around
  the yard.

  If you do something furtively, you don't want anyone to notice you;
  you're keeping a low profile. Usually, a person acting furtively feels
  guilty, or knows they're in danger of getting in trouble or being
  embarrassed. Furtively comes from the Latin word for "theft," fur. You
  can think of furtively as meaning "acting like a thief." Even though
  not everyone who behaves furtively is a thief, you might think they
  are, seeing them sneak away.

  They hopped furtively among the
  long grass clumps in the olive-groves, where the crane-flies' unsteady
  flight seemed to cover the ground with a drifting curtain of gauze.

* exuberance :satellite:
[2018-03-16 Fri 11:21]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       dbadb960-f55d-424a-968a-eeef660b743d
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:06]
   :END:

 exuberance

*** --->
  изобилие

  noun
   1. изобилие (abundance, plenty, galore, fertility, wealth, exuberance)
   2. богатство (wealth, riches, richness, rich, fortune, exuberance)
   3. избыток (excess, surplus, abundance, glut, overflow, exuberance)

  DEFINITION

  noun
   1. the quality of being full of energy, excitement, and cheerfulness; ebullience.
      "a sense of youthful exuberance"


  Use exuberance to describe joyful enthusiasm and liveliness. You
  appreciate the natural exuberance of small children, but you prefer to
  enjoy it from a distance.

  The noun exuberance comes from the adjective exuberant, which itself
  came from a Latin word that originally described an overflowing supply
  of milk from the udder of a cow or goat! The word still means
  "overflowing," not with milk but with joy and enthusiasm. After your
  winning home run, the fans ran onto the field and, in their
  exuberance, carried you off on their shoulders . . . before you
  touched home plate.

  One night a pair of squirrel dormice appeared in
  the tree above me, and chased each other in wild exuberance up and down
  the grove, leaping from branch to branch like acrobats, skittering up
  and down the tree-trunks, their bushy tails like puffs of grey smoke in
  the moonlight.
* menace :satellite:
[2018-03-16 Fri 17:18]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       c08682f6-7106-4fe9-a51b-fc5c0a06ae6e
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 3.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:03]
   :END:

 menace
*** --->
  угроза

  noun
   1. угроза (threat, danger, menace, impendence, imminence, denunciation)
   2. опасность (danger, hazard, peril, menace, jeopardy, gravity)
   3. зануда (downer, drag, sickener, wet blanket, prune, menace)
   4. надоеда (kibitzer, menace)
   5. чистое наказание (menace)

  verb
   1. угрожать (threaten, menace, overhang, hang over, denounce, impend)
   2. грозить (threaten, thunder, menace, hang over)

  DEFINITION

  noun
   1. a person or thing that is likely to cause harm; a threat or danger.
      "a new initiative aimed at beating the menace of drugs"

  verb
   1. threaten, especially in a malignant or hostile manner.
      "Africa's elephants are still menaced by poaching"


  If it's threatening you or otherwise posing some sort of danger, then
  it's a menace. Angry rabid dogs, smog clouds, and annoying little
  brothers are all probable menaces.

  The word menace works as both a noun and a verb, but it wasn't used to
  describe threatening or bothersome people until 1936. Before then,
  common menaces probably included things like the plague, locusts, and
  roving bands of pirate ships. Today, a bad reputation can menace an
  otherwise promising career, weeds can menace your garden, and burglars
  are a menace to society.


* hideout :satellite:
[2018-03-28 Wed 15:58]

** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       2f3dfcbb-8868-42dd-b4f6-169fc1004720
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 3.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:04]
   :END:

 hideout

*** --->
  укрытие

  noun
   1. убежище (asylum, refuge, shelter, haven, sanctuary, hideout)
   2. укрытие (shelter, cover, hideout, hideaway, hide, covering)

  DEFINITION

  noun
   1. a hiding place, especially one used by someone who has broken the law.
      "The pair then went on the run and were only discovered at a hideout in Leeds following a nationwide manhunt after the killing."


  A hideout is a secret place where someone can take refuge. Criminals
  or outlaws often lie low in a hideout to avoid being found by the
  police.

  A car thief might use his grandmother's apartment as a hideout to
  avoid detection. A group of ten year-olds might also have a hideout, a
  place that's protected from parents, bullies, older siblings, and
  anyone else who might interfere. Before the first use of hideout, in
  the 1880s, came the verb phrase hide out, or "hide from authorities,"
  which was coined during the Civil War in reference to draft dodgers.

  So, I hunted
  laboriously through the olive-groves for their hideout, but it was a
  hopeless quest, for every gnarled and twisted trunk was hollow, and each
  contained half a dozen holes.
* indignant :satellite:
[2018-03-28 Wed 16:02]
** Translate from English to Russian:                                 :drill:
   :PROPERTIES:
   :ID:       69e0b6b5-3e86-4c10-959a-daa13439b650
   :END:

 indignant
*** --->
  возмущенный

  adjective
   1. возмущенный (indignant, resentful, scandalized)
   2. негодующий (indignant)

  DEFINITION

  adjective
   1. feeling or showing anger or annoyance at what is perceived as unfair treatment.
      "he was indignant at being the object of suspicion"


  When you're indignant, you're angry about an unfair situation. If you
  discovered that a teacher gave ten extra points on a test to all
  students who sat in the front row, you'd be indignant.

  Indignant is from Latin indignus "unworthy," and it refers to anger
  based on unworthy or unfair behavior rather than merely injury to
  one's own interests. You may be angry, even furious, if someone shoves
  you, but you are indignant if the shove is directed at someone weak or
  helpless. The related noun is indignation, and something that arouses
  indignation is an indignity.

  We regarded each other for a moment, and then the bird,
  apparently indignant at my ill-mannered laughter at his appearance, dug
  his tiny claws deeply into my thumb, and I lost my grip on the branch,
  so that we fell out of the tree together.
* gurgle :satellite:
[2018-03-28 Wed 16:59]
** Translate from English to Russian:                                 :drill:
   SCHEDULED: <2018-04-20 Fri>
   :PROPERTIES:
   :ID:       02bab68c-3854-419d-9352-edfe6787e84e
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 3.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2018-04-16 Mon 13:01]
   :END:

 gurgle
*** --->
  бульканье

  noun
   1. бульканье (gurgling, gurgle, guggle, hubble-bubble)
   2. булькающий звук (gurgle, hubble-bubble)

  verb
   1. булькать (gurgle, simper, simmer, guggle)
   2. булькнуть (gurgle)
   3. журчать (splatter, murmur, purl, babble, gurgle, bubble)
   4. полоскать горло (gargle, gurgle)

  DEFINITION

  noun
   1. a gurgling sound.
      "Catherine gave a gurgle of laughter"

  verb
   1. make a hollow bubbling sound like that made by water running out of a bottle.
      "my stomach gurgled"


  To gurgle is to make a sound like bubbling or splashing water. Not to
  be confusing, but when you gargle mouthwash, you probably gurgle.

  People gurgle when they say something (or make a noise) with an
  accompanying wet, gurgling sound. Your stomach might gurgle too,
  especially when you're hungry. And liquid itself gurgles, like a
  stream that gurgles over rocks or sweet iced tea that gurgles from a
  bottle into your glass. Experts aren't sure if gurgle is an imitative
  word, from the sound itself, or if it's rooted in Latin.

  Drifting there, relaxed, and dreamy, I was suddenly startled
  to hear, quite close to me, a clop and gurgle of water, followed by a
  long, deep sigh, and a series of gentle ripples rocked me up and down.
