-*- coding: utf-8 -*-

* thoracic :Titans:
[2019-04-03 Wed 14:13]

Thoracic is a medical word for things pertaining to the thorax area of
your body: your chest.

You’re likely to see the word thoracic in biology class. The thorax is
your chest: the area between your neck and abdomen. Therefore, this
area is the thoracic region, and that word can be used for issues
dealing with this area. Certain exercises are thoracic because they
strengthen your chest muscles. Your pectoral muscles are in the
thoracic area. Your heart is the most important part of the thoracic
area. If you have thoracic pains, you should see a doctor.

This can perform miracles for thoracic,
or mid-back, mobility, all while helping the hamstrings
in the pike position.
* compound :eww:
[2019-04-03 Wed 17:05]

If you compound a problem you add something to it to make it worse,
like say, putting water on a grease fire. Compound means to combine; a
compound is a combination or mixture of two or more things.

Compound has several specialized uses. A compound is either a mixture
or two or more things, or a heavily guarded residence, such as a drug
lord might have. In botany, a compound leaf consists of more than one
part. In linguistics, a compound is a word that consists of two or
more independent words. In chemistry, a compound is a substance
created when atoms from chemical elements join together.

Because you have the ability to compound
  more than older people.
* cheat :eww:
[2019-04-03 Wed 17:08]

To cheat is to use sneaky, unfair methods to get something you want.
No one's going to want to play with you if you always cheat at mini
golf.

Some people cheat at cards, and others cheat during math tests by
copying from the student beside them. In either case, they're trying
to succeed using underhanded tricks. You can refer to someone who does
this as a cheat as well. Cheat comes from the Old French escheat, a
legal term for the state taking someone's property when he or she dies
without heirs. This practice was resented, and it came to mean
"confiscate unfairly."

25 Husbands cheat on their wives.
* pertaining :eww:
[2019-04-16 Tue 08:18]

To pertain is to be relevant or somehow associated with something. If
you're a lawyer, you try to find evidence that will pertain to the
case and eliminate anything that is not connected.

Behind the verb pertain lies the Latin verb pertinēre, which means "to
be applicable" or "to hold through." If you think the rules of the
road don't pertain to you, try explaining that to the state trooper
when you get pulled over. Usage note: The word pertain often takes an
s at the end, as in "That pertains to this matter," but loses it with
a helper: “That doesn’t pertain to it.”

5 Learn something pertaining to your career every day of the week.

* reconnaissance :eww:
[2019-04-16 Tue 08:21]

Reconnaissance is checking out a situation before taking action. Often
it’s used as a military term, but you could also do reconnaissance on
a new employee before you hire her, or a resort before you take a
vacation.

Reconnaissance is a noun, and it technically means “the act of
reconnoitering.” Whoa. Never heard that word before? Reconnoitering is
just a fancy way of saying that you’re checking something out —
sometimes in a sneaky way. If you like a girl in your Spanish class,
you might ask a friend to do some reconnaissance to find out what
she’s like. The word comes from the French reconnaître, which means
“recognize.”

Think of it as
  reconnaissance.
* dare :eww:
[2019-04-16 Tue 08:25]

When you challenge or provoke someone to try something risky, it's a
dare. If you accept a dare, you're probably trying to prove how brave
you are.

When you challenge your friend to a dare, you dare him. You might, for
example, dare your brother to jump off the garage into a pile of
leaves. Another way to dare is to actually be brave: "I admire her so
much, because she dares to stand up to bullies." The Old English root
of dare is durran, "to brave danger, venture, or presume." If you say,
"How dare you?" you're expressing outrage or indignation.

1 Life tends to reward those who dare, and punish those who fear.
* lump :eww:
[2019-04-16 Tue 08:39]

If it's hard to determine its shape and otherwise looks like a big
blob of something, it's probably safe to call it a lump.

Jabba the Hut looks like a disgusting lump. So does the growing mound
on your noggin where you walked into the glass door. And if you've
been lumped together with a bad bunch, you might have been grouped
with people indiscriminately. But all lumps aren't bad. Little old
ladies put lumps of sugar into their tea. And that choked up feeling
you get during a sappy movie? That's just a lump in your throat.

5 Don’t start a business because others are doing it or because you’ve just
  come across a lump sum.
* deterred :eww:
[2019-04-16 Tue 08:51]

Deter means to discourage, or literally “to frighten away.” Halloween
decorations that are too scary might deter trick-or-treaters, and the
risk of being expelled deters kids from cheating in school.

Deter comes from the Latin de meaning "away" and terrere meaning
"frighten." Something that deters isn’t always scary, though:
citronella plants deter mosquitoes, and fines deter people from
littering. Teddy Roosevelt's foreign policy dictum "speak softly and
carry a big stick" was meant to deter other countries from attacking
the United States.

20 Never be deterred by other peoples opinions of your abilities.
* blessing :eww:
[2019-04-16 Tue 08:53]

A blessing is a prayer asking for God's protection, or a little gift
from the heavens. It's also any act of approving, like when your
roommate wants to move out and you give her your blessings.

Blessings have to do with approval. The first meaning is asking God
for protection or favor. Priests and ministers say blessings in
church, and some families say a blessing before dinner. Outside a
religious context, blessings are less formal. "I give you my blessing"
simply means "It's OK with me." People give their blessings to ideas
and actions when they agree with them. Giving a blessing is often the
same as giving permission.

26 Every failure is a blessing in disguise.
* strike :eww:
[2019-04-16 Tue 09:27]

At its most basic, strike means to hit. If you strike someone, you hit
them with your hand or a weapon. If lightning strikes, it makes
contact. If you strike out on a trip, you're "hitting" the road. If
you strike gold, you've "struck it rich"!

Strike can also mean not to hit, as in miss –– as in "three strikes
and you're out." That meaning might have evolved from strike meaning
to cross off, as in "If you don't come to practice, coach will strike
your name from the starting lineup." It might also have led to the
idea of a labor strike. If employees want to protest their work
conditions, they go on strike, or refuse to work until conditions
improve.

and strike oil.”
* slid :eww:
[2019-04-16 Tue 09:33]

To slide is to move down or across something in a smooth way. If
you’re into that kind of thing, head to a playground and go down a
slide. Just don’t push any toddlers out of the way.

You can slide your bed across your room so it's near the window, or
slide on the kitchen floor in your socks. You can also slide down a
slide, a play structure that's designed for climbing up and sliding
down. Another kind of slide is the small rectangular piece of glass
that scientists slide under a microscope to examine specimens, or the
photography slide you slide into a projector for viewing.

As detailed in this account of the Angola Train Horror the car slid
down into a gorge catching fire along the way and killing 49
passengers in the process.
* gorge :eww:
[2019-04-16 Tue 09:33]

A gorge is a very deep crevice between two mountains or hills. Gorges
are formed by rivers running through and eroding rock over a very long
period of time.

The Latin root of gorge means "throat," leading to both the "narrow
passage" meaning and the French gorgier, "to swallow," which
influenced the verb version of gorge, "to overeat." You may love to
gorge on ice cream, but the stomachache afterward won't be very
pleasant. To remember the "canyon" meaning, think of the famous
upstate New York bumper sticker, “Ithaca is gorges.” It's a play on
gorgeous, meaning beautiful, and the beautiful ravines in the area.

As detailed in this account of the Angola Train Horror the car slid
down into a gorge catching fire along the way and killing 49
passengers in the process.
* graft :eww:
[2019-04-16 Tue 09:35]

Graft can mean bribery or corruption. It's also a way of transplanting
skin or bones in medicine, as in a skin graft.

People who get terrible burns on their faces often have pieces of skin
taken from other parts of their bodies to help them heal and look
better. That transplanted skin is called a graft. There are also
grafts in agriculture, when farmers take a branch from one tree and
graft it onto another tree. The most common use of graft is in
political corruption cases when politicians are accused of taking
money in exchange for granting favors.

“EVERYBODY is talkin’ these days about Tammany men growin’ rich on
graft, but nobody thinks of drawin’ the distinction between honest
graft and dishonest graft….
