-*- coding: utf-8 -*-


* nestle                                                            :Goleman:
[2019-03-01 Fri 09:18]

** Translate from English to Russian:                                 :drill:

 nestle

*** --->
  прижаться

  verb
   1. прижаться (cuddle, snuggle, nestle, nuzzle)
   2. примоститься (nestle, nestle down)
   3. угнездиться (nestle)
   4. прильнуть (snuggle, snuggle up, nestle)
   5. ютиться (nestle, cabin)
   6. укрываться (shelter, take cover, ensconce, nestle, pavilion)
   7. удобно устроиться (nestle, cose, niche)
   8. уютно примоститься (nestle)
   9. уютно усаживаться (nestle)
  10. обхватить (enfold, nestle)
  11. прижать к груди (nestle, fold to one's breast)

  DEFINITION

  verb
   1. settle or lie comfortably within or against something.
      "the baby deer nestled in her arms"


  To nestle into something is to get snug, comfy, and warm in it. You
  might nestle into your mother’s shoulder, or into a pile of blankets
  on the couch.

  People must think that birds live comfortable lives, because they
  describe really cozy, safe, and comfortable places as nests: places to
  nestle into. And it’s not just people and birds that nestle. A cottage
  might be nestled into the crook of a hill, or a mouse nestled into a
  pile of wood shavings.

  Dalhousie nestles in the lower reaches of the Dhauladhar range, a
  branch of the Himalayas that stretches into India’s Punjab and
  Himachal Pradesh states.

* despair :Goleman:
[2019-03-01 Fri 09:19]

** Translate from English to Russian:                                 :drill:

 despair

*** --->
  отчаяние

  noun
   1. отчаяние (despair, desperation, hopelessness, despondency, desolation, despond)
   2. безысходность (despair)
   3. источник огорчения (despair)

  verb
   1. отчаиваться (despair)
   2. терять надежду (despair, despond)

  DEFINITION

  noun
   1. the complete loss or absence of hope.
      "driven to despair , he throws himself under a train"

  verb
   1. lose or be without hope.
      "we should not despair"


  Despair is the feeling of not having any hope left. If you completely
  forgot to study for your final exam in math, you might feel despair
  when your teacher passes out the test.

  Despair can also refer to someone or something that causes you to
  worry or be sad. Unfortunately, some children are the despair of their
  parents. The verb despair means to lose hope. Despair is from Latin
  desperare "to be without hope," from the prefix de- "without" plus
  sperare "to hope," from spes "hope."

  In brain science, excitement revolved around the recent discovery of
  neurotransmitters, the chemicals that send messages between neurons,
  like the mood regulator serotonin—magic molecules that could pitch us
  into ecstasy or despair.

* loom                                                              :Goleman:
[2019-03-01 Fri 09:21]

** Translate from English to Russian:                                 :drill:

 loom

*** --->
  ткацкий станок

  noun
   1. ткацкий станок (loom, frame)
   2. тень (shadow, shade, ghost, loom, dark, reflection)
   3. очертания (line, set, loom, lineament)
   4. ткачество (weaving, loom)
   5. мираж (mirage, illusion, fata morgana, looming, loom)
   6. отблеск (reflection, glow, gleam, glint, reflexion, loom)

  verb
   1. маячить (loom, stick out, stand out)
   2. неясно вырисовываться (loom)
   3. принимать угрожающие размеры (loom)

  DEFINITION

  noun
   1. an apparatus for making fabric by weaving yarn or thread.
      "Their elaborate fabrics, woven on looms from cotton and alpaca wool, are known today because they were used in a type of mummification process."
   2. a vague and often exaggerated first appearance of an object seen in darkness or fog, especially at sea.
      "the loom of the land ahead"

  verb
   1. appear as a shadowy form, especially one that is large or threatening.
      "vehicles loomed out of the darkness"


  Loom has two distinct meanings. First, it's a tool for weaving.
  Second, it means to appear or stand over someone in a threatening way.
  The future loomed grim. The shadow loomed above us.

  A common way we hear loom is in "loomed large," as in, "The specter of
  getting fired loomed large in Amanda's imagination." Deriving from Low
  German or Dutch, the word sounds smoky (or misty) and spectral: the
  Antarctic ice-shelf loomed on the horizon as Shackleton's ship
  approached the continent.

  William James Hall looms over Cambridge as an architectural mistake, a
  fifteen-story modernist white slab glaringly out of place amid the
  surrounding Victorian homes and the low-lying brick-and-stone
  buildings of the Harvard campus.

* meager                                                            :Goleman:
[2019-03-01 Fri 09:22]

** Translate from English to Russian:                                 :drill:

 meager

*** --->
  скудный

  adjective
   1. скудный (scarce, meager, scanty, lean, scant, poor)
   2. мизерный (scanty, meager, meagre)
   3. бедный (poor, lean, penniless, meager, humble, indigent)
   4. тощий (skinny, lean, gaunt, scrawny, meager, scraggy)
   5. худой (thin, lean, meager, spare, gracile, angular)
   6. небольшой (small, little, low, moderate, narrow, meager)
   7. постный (lean, meatless, lenten, meager, meagre)
   8. недостаточный (inadequate, insufficient, scarce, deficient, poor, meager)
   9. ограниченный (limited, bounded, restricted, confined, finite, meager)
  10. бедный содержанием (meager, meagre)

  DEFINITION

  adjective
   1. (of something provided or available) lacking in quantity or quality.
      "they were forced to supplement their meager earnings"


  Meager means small and often applies to portions. Your mother may only
  allow you a meager serving of chocolate cake, and you may need to eat
  a meager serving of veggies in order to deserve that dessert.

  Meager doesn't mean adequate — it means not enough. People with a
  limited supply of food may try to subsist on meager portions. People
  who make a meager amount of money probably have a hard time making
  rent. Meager and emaciated both derive from the Old French maigre. If
  you can remember that you will look emaciated if your diet is meager,
  you’ll use the word correctly.

  Of the more than eight hundred articles Dan wrote at the Times, just a
  meager handful had anything to do with meditation—even as we both
  continued to attend meditation retreats on our own time.

* hallmark :Goleman:
[2019-03-01 Fri 09:23]

** Translate from English to Russian:                                 :drill:

 hallmark

*** --->
  отличительный признак

  noun
   1. отличительный признак (hallmark, character, difference, earmark, note, kind)
   2. проба (try, sample, test, trial, probe, hallmark)
   3. критерий (criterion, test, measure, yardstick, touchstone, hallmark)
   4. пробирное клеймо (hallmark, countermark, mark of assay, plate-mark)
   5. проба металлов (assay, hallmark)

  verb
   1. ставить пробу (hallmark)
   2. устанавливать критерий (hallmark)

  DEFINITION

  noun
   1. a mark stamped on articles of gold, silver, or platinum in Britain, certifying their standard of purity.
      "This is to be an appeal against the proposal by Italy for the abandonment of hallmarks on gold and silver throughout the EU."

  verb
   1. stamp with a hallmark.
      "For 700 years - let me repeat that for 700 years we have had a system for hallmarking precious metals."


  A hallmark is a distinctive characteristic of something or someone.
  That can mean a literal symbol on the bottom of a piece of pottery, or
  just a rock star's signature hair style.

  Though some products have real hallmarks on them, indicating their
  creator or origin, this word is usually used in a less literal way to
  describe a unique attribute, a special style, or typical feature. A
  basketball player could say that coming to practice early is a
  hallmark of her success. A business could say their success is a
  hallmark of their commitment to customers. And you could definitely
  say Elvis' hip swivel was a hallmark of his performances.

  This methodological sleight of hand, tacking an element of
  consciousness studies on to an otherwise respectable, mainstream
  research study, was to be a hallmark of Richie’s research for the next
  decade or so, when his interest in meditation found little to no
  support in the ethos of the time.

* sleight :Goleman:
[2019-03-01 Fri 09:23]

** Translate from English to Russian:                                 :drill:

 sleight

*** --->
  ловкость

  noun
   1. ловкость (agility, dexterity, skill, knack, sleight, adroitness)

  DEFINITION

  noun
   1. the use of dexterity or cunning, especially so as to deceive.
      "except by sleight of logic, the two positions cannot be harmonized"


  The noun sleight refers to being able to use your hands with ease,
  especially when doing a trick. Sleight is often used in the phrase
  "sleight of hand." If you are a good magician, you can make a coin
  disappear with sleight of hand.

  The noun sleight refers to cunning or cleverness, especially when used
  to trick or deceitfully. You can use a sleight of mind to trick
  yourself into believing that if you eat a box of cookies at dinnertime
  it counts as dinner. The word sleight with its meaning as being sneaky
  has a long history and comes from the Middle English word, sleghth,
  which also meant cunning. Back then people would have pronounced the
  "gh" even though today we don't.

  This methodological sleight of hand, tacking an element of
  consciousness studies on to an otherwise respectable, mainstream
  research study, was to be a hallmark of Richie’s research for the next
  decade or so, when his interest in meditation found little to no
  support in the ethos of the time.

* satiety :Goleman:
[2019-03-01 Fri 09:24]

** Translate from English to Russian:                                 :drill:

 satiety

*** --->
  сытость

  noun
   1. насыщение (saturation, satiety, satiation)
   2. сытость (satiety, fullness, bellyful, fill, fulness)
   3. пресыщение (satiety, satiation, surfeit, repletion, glut, gorge)
   4. пресыщенность (satiety)

  DEFINITION

  noun
   1. the feeling or state of being sated.
      "A diet high in fat, low in fiber and high in fluid calories rather than solid calories doesn't provide effective cues to regulate hunger and satiety ."


  The noun satiety means a state of fullness. Eating a huge, delicious
  meal will give you a satisfying feeling of satiety.

  You don't often hear people using the word satiety in casual
  conversation. It's more often a technical term used by nutrition
  experts when they discuss the diet issues of populations or individual
  patients. Satiety is a state of being completely full, but the related
  adjective satiated is much more commonly used to describe someone who
  has eaten enough. The Latin root of satiety is satis, which means
  "enough."

  His hypothesis was that because daydreams take us out of the present,
  we become less sensitive to the body’s cues of satiety, and so
  continue eating instead of stopping.

* visage                                                            :Goleman:
[2019-03-01 Fri 09:26]

** Translate from English to Russian:                                 :drill:

 visage

*** --->
  лицо

  noun
   1. лицо (face, person, countenance, image, visage, front)
   2. вид (view, form, kind, look, appearance, visage)
   3. выражение лица (facial expression, face, countenance, air, aspect, visage)

  DEFINITION

  noun
   1. a person's face, with reference to the form or proportions of the features.
      "an elegant, angular visage"


  Visage is a literary term for referring to someone's face or facial
  features. You may notice that some face creams use the word visage to
  try to sound fancier than they are.

  A famous use of visage is in Shakespeare's Julius Caesar. Brutus says:
  "O conspiracy/Shamest thou to show thy dangerous brow by night,/When
  evils are most free? O, then by day/Where wilt thou find a cavern dark
  enough/To mask thy monstrous visage?" Now there's a quote that will
  help you remember the meaning of visage, and even give you nightmares.

  Among the images Scotch-taped to the dashboard were Neem Karoli Baba,
  as well as other saints he had heard about: an otherworldly image of
  Nityananda, a radiantly smiling Ramana Maharshi, and the mustached,
  mildly amused visage of Meher Baba with his slogan—later popularized
  by singer Bobby McFerrin—“Don’t worry.

* ubiquitous :Goleman:
[2019-03-01 Fri 09:26]

** Translate from English to Russian:                                 :drill:

 ubiquitous

*** --->
  вездесущий

  adjective
   1. вездесущий (ubiquitous, omnipresent, ever-present)
   2. повсеместный (ubiquitous, general)
   3. встречающийся повсюду (ubiquitous)

  DEFINITION

  adjective
   1. present, appearing, or found everywhere.
      "his ubiquitous influence was felt by all the family"


  It's everywhere! It's everywhere! When something seems like it's
  present in all places at the same time, reach for the adjective
  ubiquitous.

  "Cities like Singapore aim to cloak themselves in ubiquitous, free
  Wi-Fi in the next few years," The Wall Street Journal reported
  recently — meaning that those savvy Singaporeans will find a wireless
  connection everywhere they go. The word comes from the Latin ubique,
  meaning — you guessed it — "everywhere." The usual pronunciation is
  "yoo-BIK-wih-tihs," but Joseph Heller must have had the older variant
  "ooh-BIK-wih-tihs" in mind when he wrote in Catch-22 that a character
  "padded through the shadows fruitlessly like an ubiquitous spook."

  If it’s one of the ubiquitous huge, lumbering Tata trucks, and the
  driver happens to be Sikh, the pictures will feature Guru Nanak, the
  revered founder of that religion.

* scant :Goleman:
[2019-03-01 Fri 09:27]

** Translate from English to Russian:                                 :drill:

 scant

*** --->
  скудный

  adjective
   1. скудный (scarce, meager, scanty, lean, scant, poor)
   2. ограниченный (limited, bounded, restricted, confined, finite, scant)
   3. недостаточный (inadequate, insufficient, scarce, deficient, poor, scant)

  verb
   1. скупиться (skimp, stint, scrimp, scant, begrudge, pinch)
   2. ограничивать (limit, restrict, confine, constrain, restrain, scant)

  adverb
   1. еле-еле (barely, faintly, scarcely, scant)

  DEFINITION

  adjective
   1. barely sufficient or adequate.
      "companies with scant regard for the safety of future generations"

  verb
   1. provide grudgingly or in insufficient amounts.
      "he does not scant his attention to the later writings"


  Scant is an adjective that means "a tiny amount," like your scant
  attendance at practice this week that results in being benched from
  the big game.

  Scant is also a verb, that means "to supply sparingly" — don't scant
  with the brownies, or I will keep asking for more. Scant also means
  "to deal with inadequately or carelessly." When you scant the reports
  on homelessness, they are so superficial on data that they don't
  reflect the real problem. Scant comes from the Old Norse word skamt,
  meaning "short, brief."

  Just before coming to India, Dan had written an article—based on his
  own first flings with meditation during college and on the scant
  sources on the topic then available in English—that proposed the
  existence of such a lasting ultra-benign mode of consciousness.

* equanimity :Goleman:
[2019-03-01 Fri 09:27]

** Translate from English to Russian:                                 :drill:

 equanimity

*** --->
  невозмутимость

  noun
   1. хладнокровие (composure, cool, equanimity, coolness, cold blood, calmness)
   2. невозмутимость (equanimity, imperturbability, calmness, impassiveness, impassivity, ataraxia)
   3. спокойствие (tranquility, calm, serenity, peace, calmness, equanimity)
   4. самообладание (composure, countenance, poise, temper, control, equanimity)
   5. беспристрастие (impartiality, equanimity, candor, disinterest, candour)

  DEFINITION

  noun
   1. mental calmness, composure, and evenness of temper, especially in a difficult situation.
      "she accepted both the good and the bad with equanimity"


  If you take the news of your parakeet's death with equanimity, it
  means you take it calmly without breaking down. Equanimity refers to
  emotional calmness and balance in times of stress.

  If equanimity reminds you of equal, that's because the words have a
  lot in common. The noun equanimity was borrowed from Latin
  aequanimitās, from aequanimus "even-tempered, fair," formed from
  aequus "even, level, equal" plus animus "mind." The archaic phrase to
  bear with equal mind means "to bear with a calm mind," and is a
  translation from the Latin. The phrase a level mind also refers to
  calmness. A near synonym is composure.

  Spiritual literature throughout Eurasia converges in descriptions of
  an internal liberation from everyday worry, fixation, self-focus,
  ambivalence, and impulsiveness—one that manifests as freedom from
  concerns with the self, equanimity no matter the difficulty, a keenly
  alert “nowness,” and loving concern for all.

* ebb                                                               :Goleman:
[2019-03-01 Fri 09:28]

** Translate from English to Russian:                                 :drill:

 ebb

*** --->
  отлив

  noun
   1. отлив (low tide, ebb, reflux, low water, refluence, revulsion)
   2. упадок (decline, decay, decadence, collapse, fall, ebb)
   3. перемена к худшему (turn for the worse, ebb)
   4. морской отлив (ebb)

  verb
   1. угасать (fade away, ebb, die down, decay, ebb away, expire)
   2. убывать (decrease, wane, subside, ebb, recede, tail away)
   3. ослабевать (wane, abate, fail, ease up, fall off, ebb)
   4. отливать (cast, pour, ebb, found, pour out)

  DEFINITION

  noun
   1. the movement of the tide out to sea.
      "I knew the tide would be on the ebb"

  verb
   1. (of tidewater) move away from the land; recede.
      "the tide began to ebb"
   2. (of an emotion or quality) gradually lessen or reduce.
      "my enthusiasm was ebbing away"


  When something ebbs, it is declining, falling, or flowing away. The
  best time to look for sea creatures in tidal pools is when the tide is
  on the ebb — meaning it has receded from the shore.

  Ebb is often used in the phrase, "ebb and flow," referring to the
  cyclical changing of the tides from low to high and back to low again.
  This sense of cyclical change can also be applied to other things. If
  you want to make money investing, you have to weather the ebb and flow
  of the stock market.

  Such transformative moments mark the boundary of mindfulness, where we
  observe the ordinary ebb and flow of the mind, with a further reach
  where we gain insight into the mind’s nature.

* repute :Goleman:
[2019-03-01 Fri 09:29]

** Translate from English to Russian:                                 :drill:

 repute

*** --->
  репутация

  noun
   1. репутация (reputation, standing, repute, rep, image, character)
   2. известность (fame, prominence, renown, notoriety, celebrity, repute)

  verb
   1. считать (think, consider, count, feel, find, repute)
   2. полагать (believe, think, suppose, guess, consider, repute)

  DEFINITION

  noun
   1. the opinion generally held of someone or something; the state of being generally regarded in a particular way.
      "pollution could bring the authority's name into bad repute"

  verb
   1. be generally said or believed to do something or to have particular characteristics.
      "he was reputed to have a fabulous house"


  A person of great or fine repute is someone who's widely known and
  highly respected. The word has a stuffy feel, so you're better off
  describing a cellist as being of great repute than, say, a rapper or
  comedian.

  Like the words reputation and putative, repute comes from the Latin
  word putare, which means "consider." And the re? Let's say that the
  cellist Yo-Yo Ma is widely respected. That means a lot of people
  consider him to be great. He's considered great not just once but
  again (and again and again).

  Munindra had studied vipassana (the Theravadan meditation and root
  source of many now-popular forms of mindfulness) under Burmese masters
  of great repute.

* ineffable :Goleman:
[2019-03-01 Fri 09:30]

** Translate from English to Russian:                                 :drill:

 ineffable

*** --->
  несказанный

  adjective
   1. невыразимый (inexpressible, unspeakable, ineffable, unutterable, nameless, speechless)
   2. несказанный (ineffable, nameless)

  DEFINITION

  adjective
   1. too great or extreme to be expressed or described in words.
      "the ineffable natural beauty of the Everglades"


  When you find something hard to express or difficult to pin down, it's
  ineffable. The feeling when you get a new puppy is ineffable — too
  strange and wonderful to define.

  You could call something "indescribable", but it wouldn't be quite the
  same as calling it ineffable. An ineffable feeling, for example, has
  an almost ghostly quality. You can almost touch it, but it slips away
  just before you do. The bubbles in a glass of champagne have an
  ineffable joy to them. The sense of sadness that you feel watching
  certain TV commercials is often ineffable: you simply can't explain
  it. You know that strange feeling of satisfaction you feel when you
  learn a new word? That's an ineffable feeling.

  There was something about his ineffable state of mind that Dan had
  never sensed in anyone before meeting Maharaji.

* rapture :Goleman:
[2019-03-01 Fri 09:30]

** Translate from English to Russian:                                 :drill:

 rapture

*** --->
  упоение

  noun
   1. восторг (delight, enthusiasm, rapture, admiration, elation, exaltation)
   2. восхищение (admiration, rapture, delight, adoration, applause, ravishment)
   3. упоение (rapture, intoxication, enravishment, extasy)
   4. экстаз (ecstasy, rapture, entrancement, enravishment)
   5. выражение восторга (rapture)
   6. похищение (abduction, rape, ravishment, rapture, rapine)
   7. взятие живым на небо (rapture)

  verb
   1. восхищать (marvel, delight, enrapture, ravish, bewitch, rapture)

  DEFINITION

  noun
   1. a feeling of intense pleasure or joy.
      "Leonora listened with rapture"
   2. (according to some millenarian teaching) the transporting of believers to heaven at the Second Coming of Christ.
      "These focus on salvation, the Rapture , and the Second Coming of Jesus."

  verb
   1. (according to some millenarian teaching) transport (a believer) from earth to heaven at the Second Coming of Christ.
      "Christ will return secretly to rapture his saints before the great tribulation."


  Rapture is a feeling of emotional ecstasy so magical it's almost as if
  you've been transported to some other world.

  Coming to us from an old French word meaning "carried away," rapture
  certainly involves getting swept off to Shangri-La. It's happiness so
  extreme that you just about float to heaven, complete with big goofy
  grin plastered to your face. Traditionally reserved for those feeling
  spiritual ecstasy, rapture now extends to anyone feeling overwhelmed
  by emotion — sparked by everything from a passionate kiss to scoring
  an awesome dress on sale.

  Maharaji seemed always to be absorbed in some state of ongoing quiet
  rapture, and, paradoxically, at the same time was attentive to whoever
  was with him.

* itinerant :Goleman:
[2019-03-01 Fri 09:31]

** Translate from English to Russian:                                 :drill:

 itinerant

*** --->
  странствующий

  adjective
   1. странствующий (wandering, itinerant, errant, peripatetic, wayfaring, vagrant)
   2. объезжающий свой округ (itinerant)

  noun
   1. бродяга (tramp, stroller, vagabond, vagrant, hobo, itinerant)
   2. тот, кто объезжает свой округ (itinerant)

  DEFINITION

  adjective
   1. traveling from place to place.
      "itinerant traders"

  noun
   1. a person who travels from place to place.
      "A party of Irish itinerants travelling in around 24 vehicles arrived at the Back Lane side of the factory on Sunday evening."


  An itinerant is a person who moves from place to place, typically for
  work, like the itinerant preacher who moves to a new community every
  few years.

  Itinerant is pronounced "eye-TIN-er-ant." It might remind you of
  itinerary, the traveler's schedule that lists flights, hotel check-in
  times, and other plans. It's no surprise that both words come from the
  Latin word itinerare, meaning "to travel." Itinerant was first used in
  the 16th century to describe circuit judges who traveled to faraway
  courtrooms. Today, almost anyone can be an itinerant.

  Like most sadhus, he was itinerant, unpredictably on the move.

* outright :Goleman:
[2019-03-01 Fri 09:32]

** Translate from English to Russian:                                 :drill:

 outright

*** --->
  прямой

  adjective
   1. прямой (direct, right, straight, straightforward, outright, upright)
   2. полный (full, complete, utter, total, entire, outright)
   3. открытый (open, opened, uncovered, public, discovered, outright)
   4. совершенный (perfect, complete, accomplished, ideal, perfective, outright)

  adverb
   1. прямо (direct, right, straight, directly, live, outright)
   2. сразу (at once, right away, straight, straight away, promptly, outright)
   3. открыто (openly, publicly, overtly, in public, outright, avowedly)
   4. наповал (outright)
   5. совершенно (completely, quite, absolutely, entirely, perfectly, outright)
   6. вполне (quite, completely, well, fully, perfectly, outright)
   7. до конца (to the last, thoroughly, down, throughly, outright, home)
   8. раз и навсегда (outright)

  DEFINITION

  adjective
   1. open and direct; not concealed.
      "an outright refusal"

  adverb
   1. altogether; completely.
      "logging has been banned outright"
   2. immediately.
      "the impact killed four horses outright"


  If you do something outright, you do it in a wholehearted,
  unrestricted way. If you declare outright that you’re never eating
  another cupcake, that’s the end of that. If you eat one anyway, you
  told an outright lie.

  If an event is cancelled outright, there's no question about it being
  rescheduled, and if you buy a new car outright, you pay for it all at
  once, instead of making monthly payments. Outright means direct and
  immediate — whether it's an adverb or an adjective: "The child's
  outright refusal to put on his shoes exasperated his babysitter." It
  can also mean “right away.” If you step on a slug, you’ll probably
  kill it outright. Ew.

  That training focused on negatives: neurotic patterns, overpowering
  burdensome feelings, and outright psychopathology.

* perch                                                             :Goleman:
[2019-03-01 Fri 09:33]

** Translate from English to Russian:                                 :drill:

 perch

*** --->
  окунь

  noun
   1. окунь (perch, bass)
   2. насест (perch, roost, henroost)
   3. шест (pole, perch, stave)
   4. дрога (perch)
   5. перч (perch)
   6. выступ (projection, ledge, protrusion, lip, lug, perch)
   7. жердь (pole, beanpole, perch, barling)
   8. высокое положение (position, eminence, top, perch, grandeur, throne)
   9. прочное положение (foothold, footing, standfast, perch)
  10. веха (milestone, landmark, mark, pole, marker, perch)
  11. карниз (cornice, eaves, bench, perch, table, tabling)
  12. мера длины (line, perch, pole, ell, rod)

  verb
   1. взгромоздиться (perch, climb, clamber)
   2. садиться на насест (perch)
   3. сажать на насест (perch)
   4. усесться (perch, settle down, take a seat, set down, seat oneself, find a seat)
   5. садиться (sit down, take, set, board, have a seat, perch)
   6. вскарабкаться (perch)
   7. забраться (climb, perch)
   8. помещать высоко (perch)
   9. опираться (lean, rest, be based, bear, abut, perch)

  DEFINITION

  noun
   1. a thing on which a bird alights or roosts, typically a branch or a horizontal rod or bar in a birdcage.
      "Dead branches also make perfect perches for resting birds and are good places to hang feeders."
   2. an edible freshwater fish with a high spiny dorsal fin, dark vertical bars on the body, and orange lower fins.
      "Out back of the house, oak, hemlock and cedar trees crown a path toward a 30-acre lake stocked with largemouth bass, yellow perch , pumpkinseed sunfish, and more."
   3. a linear or square rod (see rod ( sense 3 ) ).
      "This strange measure undoubtedly is related to other archaisms such as the furlong, the perch and the fathom."

  verb
   1. (of a bird) alight or rest on something.
      "a herring gull perched on the mast"


  A perch is a temporary resting place. In the middle of climbing a
  tree, you might find a good perch on a high branch. Bet some birds
  will be perching there too.

  Perch has many different meanings. A bird perch is a little stick it
  can balance on, and the armrest of the couch can offer you a perch
  during a party. It's also the name of a kind of fish with spiny fins.
  And it's also an old measurement of 16.5 feet.

  A wooden-plank tucket served as both bed and day couch, with a small
  stand alongside for perching texts to read—and little else.

* amble                                                             :Goleman:
[2019-03-01 Fri 09:34]

** Translate from English to Russian:                                 :drill:

 amble

*** --->
  иноходь

  noun
   1. иноходь (amble, ambling, pace, rack)
   2. легкая походка (tripping, amble)
   3. легкий шаг (trip, amble)

  verb
   1. бежать иноходью (amble)
   2. ехать на иноходце (amble)
   3. идти иноходью (pace, amble, rack)
   4. идти легким шагом (amble)

  DEFINITION

  noun
   1. a walk at a slow, relaxed pace, especially for pleasure.
      "a peaceful riverside amble"

  verb
   1. walk or move at a slow, relaxed pace.
      "they ambled along the riverbank"


  To amble is to take a leisurely, pleasurable walk. Care to amble down
  a pleasant country road instead of reading the rest of this word
  description? That would certainly be understandable.

  Amble is both a noun meaning "a stroll" and a verb meaning "to walk in
  a slow, leisurely way." You might amble (or take an amble) over to the
  snack table and grab a brownie. Amble comes from the Latin ambulare,
  which means "to walk about," as in ambulatory. Weirdly enough, it was
  once only used for horses or those on horseback. We use it for people
  now, but it still retains some of its horse-like, country feel.

  Through the mist that morning, Dan glimpsed an elderly Tibetan monk
  amble by as he made his postdawn rounds, circumambulating the holy
  site.

* spire :Goleman:
[2019-03-01 Fri 09:34]

** Translate from English to Russian:                                 :drill:

 spire

*** --->
  шпиль

  noun
   1. шпиль (spire, steeple, capstan, needle, top, pin)
   2. шпиц (spire, spitz, Pomeranian, steeple, pom, pinnacle)
   3. виток (turn, coil, loop, convolution, spire, wind)
   4. пик (peak, crest, pike, spire)
   5. игла (needle, point, spine, spire, aiguille, prickle)
   6. спираль (spiral, helix, scroll, loop, volute, spire)
   7. острие (point, edge, spike, spearhead, peak, spire)
   8. стрелка злака (spire)
   9. росток (sprout, shoot, sprig, spire, chit, bourgeon)
  10. остроконечная верхушка (spire)

  verb
   1. колоситься (ear, spire)
   2. прорастать (germinate, sprout, spring, spire, grow out, pullulate)
   3. подниматься ввысь (soar, spire)
   4. заостряться (thin down, spire)
   5. суживаться кверху (spire)
   6. двигаться по спирали (gyrate, corkscrew, spire)
   7. закручиваться в спираль (spire)
   8. чертить спиральную линию (spire)

  DEFINITION

  noun
   1. a tapering conical or pyramidal structure on the top of a building, typically a church tower.
      "He enjoyed a reputation for building tall elegant masonry structures such as church towers and spires ."
   2. the upper tapering part of the spiral shell of a gastropod mollusk, comprising all but the whorl containing the body.
      "However, the upper spire whorls of P. calafia are shorter than the corresponding ones on P. acuminata."


  A pointed cone shape on top of a building is called a spire,
  especially when it rises from the roof of a church.

  The part of a church roof that rises above a city skyline or a
  village's rolling hills, pointing sharply up toward the sky, is its
  spire. Many church spires have a cross at the very top. Other
  buildings — religious or secular — can also have spires, though it's
  most common to see one on a Christian church. The root of spire is the
  Old English spir, "sprout, shoot, or stalk of grass."

  Our story starts one early November morning in 1970, when the spire of
  the stupa in Bodh Gaya was lost to view, enveloped in the ethereal
  mist rising from the Niranjan River nearby.

* conjecture                                                            :EWW:
[2019-03-01 Fri 17:16]

** Translate from English to Russian:                                 :drill:

 conjecture

*** --->
  догадка

  noun
   1. предположение (assumption, hypothesis, guess, supposition, speculation, conjecture)
   2. догадка (guess, conjecture, surmise, guesstimate, inkling)
   3. конъектура (conjecture)

  verb
   1. предполагать (assume, guess, suppose, expect, suspect, conjecture)
   2. гадать (conjecture, divine, augur)
   3. предлагать исправление конъектуру (conjecture)
   4. предлагать исправление текста (conjecture)

  DEFINITION

  noun
   1. an opinion or conclusion formed on the basis of incomplete information.
      "conjectures about the newcomer were many and varied"

  verb
   1. form an opinion or supposition about (something) on the basis of incomplete information.
      "he conjectured the existence of an otherwise unknown feature"


  Can you guess what conjecture means? It's a word to use when you are
  not sure of something and have to "guess or surmise."

  You can see how the word conjecture means that you create a theory or
  opinion about something without basing it in fact because the original
  definition of conjecture, from Old French, is "interpretation of signs
  and omens." Since signs and omens are pretty subjective, it makes
  sense that the word would then move to its current meaning. However,
  even though it only seems like weather reports are conjectures, they
  are actually based on evidence!

  Let me be clear, this is not an article filled with theory or conjecture.
* cessation :EWW:
[2019-03-01 Fri 17:46]
** Translate from English to Russian:                                 :drill:

 cessation
*** --->
  прекращение

  noun
   1. прекращение (cessation, stop, cease, discontinuation, suspension, discontinuance)
   2. остановка (stop, stopping, halt, stoppage, standstill, cessation)
   3. перерыв (break, interruption, pause, interval, rest, cessation)

  DEFINITION

  noun
   1. the fact or process of ending or being brought to an end.
      "the cessation of hostilities"


  Cessation is an end to something, such as the stopping of a bad habit,
  like the cessation of smoking.

  Cessation and cease sound alike and have similar meanings because they
  both come from the Latin word cessare, which means "to delay, to
  stop." The cessation can be permanent, such as when the protests
  resulted in the cessation of the use of baby bunnies to test lipsticks
  (forever ending the bunny torture); or temporary, such as the
  cessation of the rain during the storm that let us run to the car
  without getting wet (but rain, like sunshine, always comes back).

* tycoon :EWW:
[2019-03-01 Fri 17:49]

If you are meeting with someone who is considered a tycoon in his
industry, keep in mind that he is very successful and probably
accustomed to high-stakes negotiations.

Tycoon is derived from the Japanese word taikun, which means “great
lord or prince.” This noun made its way to the West in the mid-19th
century and originally referred to the shogun, or military leader, of
Japan. It was also used in reference to Abraham Lincoln to indicate
that he was an important man. Now, tycoons are generally understood to
be unusually successful heads of business or industry.

Arnold Schwarzenegger, the infamous bodybuilder, real estate tycoon,
and “Governator” of California

* calisthenics :EWW:
[2019-03-01 Fri 17:50]

** Translate from English to Russian:                                 :drill:

 calisthenics

*** --->
  физподготовка

  noun
   1. пластика (calisthenics, callisthenics)
   2. ритмическая гимнастика (calisthenics, callisthenics, aerobics, eurhythmics)
   3. физическая подготовка (physical training, sportsmanship, callisthenics, calisthenics)
   4. физподготовка (physical training, sportsmanship, calisthenics, callisthenics)

  DEFINITION

  noun
   1. gymnastic exercises to achieve bodily fitness and grace of movement.


  Calisthenics is exercise, like jumping jacks or pull-ups, that people
  do to stay in shape or get in better shape.

  Doing calisthenics usually involves simple movements, like stretching,
  jumping, bending, and kicking, that don't involve a lot of equipment,
  if any. Kids in gym class do calisthenics, and calisthenics are
  helpful to many people, including athletes and people in the military.
  The push-up is a famous example of calisthenics. Those limber folks on
  cheerleading squads are masters of calisthenics. A little calisthenics
  can be helpful in anyone's everyday routine as a way to build
  endurance and stay healthy.

* berate                                                                :EWW:
[2019-03-01 Fri 18:10]

** Translate from English to Russian:                                 :drill:

 berate

*** --->
  бранить

  verb
   1. ругать (swear, scold, abuse, berate, revile, rail)
   2. бранить (scold, revile, berate, rail, chide, upbraid)

  DEFINITION

  verb
   1. scold or criticize (someone) angrily.
      "his mother came out and berated me for raising my voice"


  A strong verb for harshly cutting someone down with words is berate.
  "He didn't just correct the cashier who gave him the wrong change, he
  started to berate her, calling her names in front of the whole store."

  When you berate someone it is more than just raising your voice at
  them; it implies putting them down by insulting their character.
  Berate comes from the 16th-century English and French for "to scold"
  or "to blame." Often the anger behind the scolding seems over-the-top,
  as in "When the young man behind the counter dropped the scoop of
  vanilla, the manager berated him excessively by declaring him
  worthless and weak."

  The most unproductive thing you can do is to berate and belittle
  yourself because you haven’t been as successful or productive as you
  want.

* belittle                                                              :EWW:
[2019-03-01 Fri 18:11]

** Translate from English to Russian:                                 :drill:

 belittle

*** --->
  умалить

  verb
   1. умалить (belittle, derogate)
   2. умалять (belittle, detract, derogate, disparage, depreciate, cry down)
   3. принижать (belittle, downplay, detract, debase, cry down, efface)
   4. преуменьшать (belittle, downplay, minimize, understate, play down, lessen)
   5. уменьшать (reduce, decrease, diminish, lower, lessen, belittle)

  DEFINITION

  verb
   1. make (someone or something) seem unimportant.
      "this is not to belittle his role"


  To belittle means to put down, or to make another person feel as
  though they aren't important. Saying mean things about another person
  literally makes them feel "little."

  To belittle someone is a cruel way of making someone else seem less
  important than yourself. A candidate for office might belittle his
  opponent by pointing out during a press conference that his fellow
  candidate has an inferior intellect. Belittling doesn't have to come
  in the form of verbal abuse. A manager who forces his administrative
  assistant to scrub his office floor with a toothbrush belittles her as
  well.

  The most unproductive thing you can do is to berate and belittle
  yourself because you haven’t been as successful or productive as you
  want.




* resurgence :EWW:
[2019-03-01 Fri 18:12]

Resurgence means coming back. Biker jackets are always cool––but in
certain decades they experience a resurgence, and suddenly you see
them everywhere.

There is nothing steady about resurgence––a surge is a sudden
gush––think dancing fountain or an oil well that's just been tapped.
Often, after a national tragedy, there is a resurgence in interest in
family values and getting back to basics. In prosperous times, there's
often a resurgence in sales of contemporary art.

There’s an age old practice in the middle of a resurgence…

* grind :EWW:
[2019-03-03 Sun 10:12]

If you like to grind your own coffee beans, it means you prefer to buy
whole beans, put them in an electric grinder, and pulverize them into
tiny bits before you brew your coffee.

When you grind something, you mill or crush it into smaller pieces,
the way you grind pepper or grind a grain into flour. Two things that
rub up against each other also grind together, which is what your
teeth do if you grind them in your sleep. Informally, grind also means
boring, tedious work, often in the sense of "grind away" or "the daily
grind." This sense of grind was invented in the 1800s as college
slang.

The constant grind to find the next dollar, to bed the next woman, to
seal the next deal, to land the next gig, to leave the legacy of which
you can be proud, to achieve, achieve, achieve!

* angst :EWW:
[2019-03-03 Sun 10:14]

Angst is a feeling of anxiety and frustration that isn't specific.
People often feel angst about the state of the world, or about the
state of their homework.

Angst is anxiety that is mixed with frustration and negativity. Angst
often doesn’t have a specific target: people feel angst in general.
Teenagers are known for their angst, which is shown when they act
miserable about nothing in particular. Often, angst refers to
philosophical displeasure with world events or personal freedom. An
angst-filled person is dissatisfied and unhappy.

The problem is, that all this responsibility and angst can overwhelm
you and create tremendous stress.

* hasten :EWW:
[2019-03-03 Sun 17:31]

The verb hasten means to move at a high speed. If you hasten to your
room, no one will know that you came in late.

Hasten comes from the word haste, which means "excessive speed or
urgency." The words hurry and hasten are synonyms. Hasten can also
mean "to make happen quickly," like when you open a window in the
kitchen when you are cooking to hasten the room's cooling down. Hasten
also means "to be quick," like when you hasten to tell everyone that
the rumor going around about you isn't true.

“There are different things one can do to establish and hasten the
peace process.

* chaste :EWW:
[2019-03-04 Mon 10:51]

If you belong to a chastity club, you might have to take a pledge to
be chaste until marriage. Chaste can be defined as "pure and
virtuous," but basically it means "not having sex."

This word is related to the Latin source of the verb castrate "to
remove a man's testicles," so it's definitely related to sex. And
chaste is from the same Latin source as the noun caste "a Hindu social
class separated from other classes." So the word chaste means no sex,
and the word caste means pure and virtuous.

And how do sex and meditation relate, especially since most people –
imagining the asceticism of chaste monks – separate the two concepts?

* primordial :EWW:
[2019-03-04 Mon 10:56]

Primordial, an adjective, describes something that has been around
forever, like cockroaches.

Primordial comes from the Latin words primus, meaning "first" and
ordiri, "to begin." So it is easy to see that this adjective means
"first of all, original." When something is primordial, it has existed
since the earliest time, like the primordial mud some scientists
believe was the source of all life on Earth. Remember that is it a
scientific term — don't call your teacher primordial just because
she's been teaching at your school since it opened.

Sam Harris, in his 2014 book “Waking Up: A Guide to Spirituality
Without Religion ” recommends the Tibetan Buddhist practice of
Dzogchen, aimed at attaining the natural primordial state or natural
condition for the sake of liberation.

* amble :Goleman:
[2019-03-05 Tue 18:39]

To amble is to take a leisurely, pleasurable walk. Care to amble down
a pleasant country road instead of reading the rest of this word
description? That would certainly be understandable.

Amble is both a noun meaning "a stroll" and a verb meaning "to walk in
a slow, leisurely way." You might amble (or take an amble) over to the
snack table and grab a brownie. Amble comes from the Latin ambulare,
which means "to walk about," as in ambulatory. Weirdly enough, it was
once only used for horses or those on horseback. We use it for people
now, but it still retains some of its horse-like, country feel.

Through the mist that morning, Dan glimpsed an elderly Tibetan monk
amble by as he made his postdawn rounds, circumambulating the holy
site.

* burdensome :Goleman:
[2019-03-05 Tue 18:40]

Something that's burdensome is very difficult or tiring. It's better
to weed your garden regularly, rather than put it off until it becomes
an exhausting, burdensome task.

Some summer jobs are easy and relaxing, like your laid-back dog
walking business — other jobs are much more burdensome, like
babysitting a large family of kids or lifeguarding at a pool where
people keep nearly drowning. Something that's a burden, a physical
load or a duty that weighs heavily on you, is burdensome. The
Proto-Indo-European root means "to bear" or "to carry," and also "to
give birth."

That training focused on negatives: neurotic patterns, overpowering
burdensome feelings, and outright psychopathology.

* exude                                                             :Goleman:
[2019-03-05 Tue 18:40]

To exude is to give off small amounts, usually of liquids or gases,
through small openings, such as pores. Think of how you exude sweat
after a workout.

The word exude is often used to describe sweating — the original Latin
root, sudāre means "to sweat." Still, we frequently use the word exude
to refer to anything that seems to ooze or pour forth from an object
or person. John F. Kennedy was said to exude confidence, while his
wife, Jackie, exuded class. But the verb can also have a negative
sense, as when we say a skunk exudes a foul smell.

Khunu, on the other hand, quietly exuded the better side of human
nature.

* repute :Goleman:
[2019-03-05 Tue 18:42]

A person of great or fine repute is someone who's widely known and
highly respected. The word has a stuffy feel, so you're better off
describing a cellist as being of great repute than, say, a rapper or
comedian.

Like the words reputation and putative, repute comes from the Latin
word putare, which means "consider." And the re? Let's say that the
cellist Yo-Yo Ma is widely respected. That means a lot of people
consider him to be great. He's considered great not just once but
again (and again and again).

Munindra had studied vipassana (the Theravadan meditation and root
source of many now-popular forms of mindfulness) under Burmese masters
of great repute.

* premise :Goleman:
[2019-03-06 Wed 07:41]

A premise is what forms the basis of a theory or a plot. When you
called 911 on the guy in your back yard, it was on the premise that he
was a thief and not the meter-reader.

In logic, the premise is the basic statement upon whose truth an
argument is based. Criticize alternative theories by demonstrating
their false premises. In a more general sense, it's a basic assertion.
On the premise that people are generally good, you keep your doors
unlocked. Premise is also used more loosely for the starting point for
a plot. A movie's premise could be that two people trapped on a desert
island will inevitably fall in love.

The manuals shared the premise that filling one’s life with meditation
and related practices produces remarkable transformations of being.

* affirm :Goleman:
[2019-03-06 Wed 07:42]

To affirm something is to give it a big "YES" or to confirm that it is
true.

The verb affirm means to answer positively, but it has a more weighty
meaning in legal circles. People are asked to swear an oath or affirm
that they will tell the truth in a court of law. Lawyers may ask
people to affirm facts, and judges may affirm rulings. In these cases,
affirm means to verify or attest to the validity of something.

And the overlap in qualities between Khunu, Maharaji, and a handful of
other such beings Dan met in his travels around India seemed to affirm
just such possibilities.

* fling                                                             :Goleman:
[2019-03-06 Wed 07:44]

To fling is to throw something with force. You'll start a food fight
in the cafeteria if you fling your vegetables at the kid across the
table.

The act of throwing something recklessly or with force can also be
called a fling. Your mail sorting ritual might be putting bills in one
pile and personal letters in another, then giving junk mail a fling
into the recycling bin. A brief period of revelry or indulgence is
another kind of fling. You and your friends could plan a weekend fling
in New York, staying in a hotel, eating out, and shopping without
worrying about how much money you spend.

Just before coming to India, Dan had written an article—based on his
own first flings with meditation during college and on the scant
sources on the topic then available in English—that proposed the
existence of such a lasting ultra-benign mode of consciousness.6 The
major states of consciousness, from the perspective of the science of
the day, were waking, sleeping, and dreaming—all of which had
distinctive brain wave signatures.

* benign :Goleman:
[2019-03-06 Wed 07:45]

Someone or something that is benign is gentle, kind, mild, or
unharmful: a benign soul wouldn't hurt a fly.

Benign describes a range of qualities, all of them positive. When
talking about a person, it means "gentle." In reference to weather or
climate, it means "mild." In some other contexts, it simply means "not
harmful"; you might speak of "a benign tumor" or "an environmentally
benign chemical." The word comes from a Latin root benignus meaning
"well born," but the implied meaning is "kind" or "pleasant" — it's
hard to get mad at someone who has a benign disposition.

Just before coming to India, Dan had written an article—based on his
own first flings with meditation during college and on the scant
sources on the topic then available in English—that proposed the
existence of such a lasting ultra-benign mode of consciousness.6 The
major states of consciousness, from the perspective of the science of
the day, were waking, sleeping, and dreaming—all of which had
distinctive brain wave signatures.

* imposition :Goleman:
[2019-03-06 Wed 07:56]

Imposition means you force something — usually an unwanted burden — on
someone else. If your friends invite themselves over for dinner the
night before your big test, that's an imposition because you'll have
to cook instead of studying.

Imposition comes from the 14th century Old French word of the same
spelling, meaning "the levying of taxes, a tax, duty." Taxes are a
good way to remember the meaning of imposition. You never want to pay
taxes — but you have no choice but to pay. It can be the same for
other kinds of burdens: if something is an imposition, you don't want
to do it, but you likely will have to.

And the imposition of “noble silence” from day one meant that Richie
never really knew who else shared that tent—his vague impression was
that they were mostly Europeans.

* equanimity :Goleman:
[2019-03-06 Wed 07:59]

If you take the news of your parakeet's death with equanimity, it
means you take it calmly without breaking down. Equanimity refers to
emotional calmness and balance in times of stress.

If equanimity reminds you of equal, that's because the words have a
lot in common. The noun equanimity was borrowed from Latin
aequanimitās, from aequanimus "even-tempered, fair," formed from
aequus "even, level, equal" plus animus "mind." The archaic phrase to
bear with equal mind means "to bear with a calm mind," and is a
translation from the Latin. The phrase a level mind also refers to
calmness. A near synonym is composure.

Though Richie found his focus returning again and again to the
throbbing pain in that knee, he also started to glimpse a sense of
equanimity and well-being.

* ambivalence :Goleman:
[2019-03-07 Thu 08:11]

Someone who shows ambivalence about a person or thing has conflicting
feelings. If you love your mom but find her totally embarrassing, you
might feel ambivalent about having her give a presentation at your
school.

Originally a psychological term, ambivalence was borrowed from the
German word Ambivalenz, coined in 1910 by the Swiss psychologist Eugen
Bleuler. The German word was formed from the Latin prefix ambi- "in
two ways" plus Latin valentia "vigor, strength."

Spiritual literature throughout Eurasia converges in descriptions of
an internal liberation from everyday worry, fixation, self-focus,
ambivalence, and impulsiveness—one that manifests as freedom from
concerns with the self, equanimity no matter the difficulty, a keenly
alert “nowness,” and loving concern for all.

* pervasive :Goleman:
[2019-03-07 Thu 08:15]

When something is pervasive, it's everywhere. Common things are
pervasive — like greed and cheap perfume.

Ever notice how certain trends seem to spread all over the place? When
something — like a hairstyle — is super-common, it's pervasive.
Pervasive things can't be escaped. Playing video games is pervasive
among kids. Talking about the weather is pervasive among adults.
Ideas, diseases, habits, and all sorts of things can be pervasive. If
you're sick of seeing something because you're seeing it again and
again, it must be pervasive.

Dan resolved that on his return to Harvard from India, he would make
his colleagues aware of what seemed an inner upgrade far more
pervasive than any dreamed of in our psychology.

* wend                                                              :Goleman:
[2019-03-07 Thu 08:20]

To wend means to choose a path and then walk that path. The path may
not always be the fastest route, but at least it should get you there.
Eventually.

It’s always good to have a goal, and that’s true with wending. You
know where you want to go, so you wend your way there. You’ll notice
that wend looks like the verb wind, and they both come from the same
Old English wendan, which means “to turn, depart.” When you wend, you
may take curvy, windy roads, a more scenic route, some detours and
side alleys, just for fun. But don’t wend too much or you’ll be late.

The high rode with him on the bus down the mountains via roads wending
through fields and villages with mud-walled, thatch-roofed houses, on
to the busier cities of the plains, and finally through the throbbing,
packed roads of Delhi.

* wane :Goleman:
[2019-03-07 Thu 08:22]

Things that wax and wane grow larger and smaller, like the moon.
Things that wane simply grow smaller. "My initial enthusiasm for
helping waned when I saw the pile of envelopes that needed licking."

You may have heard the expression "on the wane." It means a fad, or a
fashion, or a disease, that is on its way out the door. "The face mask
fad at school was on the wane as new reports of kids infected with a
dreaded new fly virus waned."

There Richie felt that high begin to wane as he and Susan spent a few
days in the bare-bones guesthouse they could afford on their grad
student budget, venturing out to Delhi’s cacophonous and crowded
streets to have a tailor make some clothes and buy souvenirs.

* terrain :Goleman:
[2019-03-07 Thu 08:27]

An ATV, or all-terrain vehicle, is useful for people who drive on lots
of different terrain, hence the name. Terrain is a noun used to talk
about the ground, when you're specifically interested in how it
appears or is shaped.

In times of war, you'll often hear the term "hostile terrain" used to
describe a region with lots of mountains, vast stretches of desert, or
impenetrable jungles. These are all areas of difficult terrain that
are hard to pass. Much of humankind's history can be traced by its
effort to alter the terrain. We've made mountains into meadows, rivers
into lakes, and prairies into roads, all to make the terrain more
livable for us. You could even go so far as to say that a person's
psyche is mysterious terrain.

And just where in the mind’s terrain had Richie been?

* wobbly :Goleman:
[2019-03-08 Fri 12:09]

If something's wobbly, it has a tendency to sway or lurch from side to
side, like the wobbly wheel on a broken tricycle or the wobbly legs of
a cruise ship passenger who has just set foot on solid ground after a
week at sea.

If your chair is wobbly, you may need to tighten the legs with a
screwdriver. And if you're feeling wobbly during gym class, you
probably need to sit down and drink some water. Anything or anyone
that wobbles can be described as wobbly, and both words come from a
root meaning "to weave back and forth." When the word is capitalized,
it's a nickname for a member of the labor union called International
Workers of the World.

For beginners this means a wobbly dance between full focus and a
wandering mind.

* frenetic :Goleman:
[2019-03-08 Fri 12:11]

The adjective frenetic is another way to say frenzied, frantic, or
totally worked up. Kind of how you'd run around the kitchen madly
trying to cook a last-minute dinner for 30 of your closest friends.

Sometimes tinged with fear and often quite maniacal, frenetic comes
from the Latin phreneticus, meaning “delirious.” The Latin word, in
turn, came from a similarly spelled Greek word which, when translated
literally, means “inflammation of the brain.” So it's no surprise that
a frenetic person looks absolutely crazed and super anxious.

Actually, the sense of a torrent of thoughts seems to be due to paying
close attention to our natural state, which Asian cultures dub “monkey
mind,” for its wildly frenetic randomness.

* ado :EWW:
[2019-03-08 Fri 20:50]

Someone who makes a lot of ado about things has a tendency to make
them more busy or complicated than they need to be.

A flurry of activity or a lot of complaining about a little problem
are both examples of ado. It's an old fashioned word, dating back to
the fourteenth century, when it meant "conflict or trouble." "At do"
was a Norse version of the English phrase "to do," which was
eventually shortened to ado. The most famous use of the word is
probably the Shakespeare play "Much Ado About Nothing."

Tim Ferriss: So without further ado, let’s get started.

* corroborate :EWW:
[2019-03-09 Sat 17:01]

To corroborate is to back someone else’s story. If you swear to your
teacher that you didn't throw the spitball, and your friends
corroborate your story by promising that you were concentrating on
math homework, she might actually believe you.

For example, a witness in court corroborates the testimony of others,
and further experimentation can corroborate a scientific theory. Near
synonyms are substantiate and confirm. Corroborate, originally meaning
"to support or strengthen," was borrowed from Latin corrōborāre,
formed from the prefix cor- "completely" plus rōborāre "to strengthen"
(from rōbur "strength").

I can corroborate this.

* keel :EWW:
[2019-03-09 Sat 17:02]

The keel of a boat is the beam that runs the length of the hull — the
body of the boat — and can extend vertically into the water to provide
stability.

A keel doesn't just refer to the stabilization of boats. When you're
on "an even keel," you're stable and steady. On a bird, the keel (or
breastbone) enables a bird to fly. On the other hand, if you keel
over, you're quite the opposite, since you've just gone crashing to
the floor.

As a lifelong night owl, my stability tends to be much more under
control, much more even keel when I go to bed by 11:00 p.m.

* woe :EWW:
[2019-03-09 Sat 17:16]

"O, woe is me!" This line is from Shakespeare. When Hamlet scorns
Ophelia, she utters these words to express the grief and despair that
will soon drive her to suicide.

Another famously dejected figure, Job, echoes this unhappy cry in the
Old Testament when he contemplates his sad fate, "If I be wicked, woe
unto me." Today, woe generally means problem or worry. You may
experience financial woes, if you spend too much on your credit card.
And study hard for your classes or in addition to your academic woes,
you may get grounded by your parents. Sometimes woe is used in a
slightly ironic way. If your friends tell you to forget about your
woes and go out with them, they think your problems are not too
serious.

If you miss one of your naps, woe unto thee because you are going to
have at least two days of complete zombie state.

* thee :EWW:
[2019-03-09 Sat 17:16]

The word thou, used in place of "you," is not used much in modern
language. In fact, with its Biblical feeling, it’s most often used in
religious contexts. Otherwise, it might be used as slang for thousand.

Anyone familiar with the Bible knows the word thou means "you." As the
word worked its way from Old English, it varied a little in its
subtext, from a plural referring to higher-ups, then to equals, and,
around 1450, as a slightly insulting reference suggesting inferiority.
Today, it's used primarily by specific religious groups, or as a
somewhat affected, archaic word in poetry. As a side note, if someone
asks you for a thou, they mean a thousand dollars.

If you miss one of your naps, woe unto thee because you
are going to have at least two days of complete zombie
state.

* allude                                                                :EWW:
[2019-03-09 Sat 17:47]

When you allude to something, you don't identify it or mention it
specifically. If you allude to the fact that a cop is sitting right
behind you, your friends might stop talking about their plans to rob a
bank.

Allude is from Latin allūdere "to play with, joke" from the prefix ad-
"toward" plus lūdere "to play." The corresponding noun is allusion,
which is often used of an indirect reference in literature: Helen, a
fitting name for a woman of great beauty, is an allusion to Helen of
Troy.

I should also update this because noting that I, in the last few
weeks, have been experimenting with something that he produces called
the Yin Reserve, which includes several different components that he
alludes to in this conversation.

* adhesion                                                              :EWW:
[2019-03-09 Sat 18:13]

Dab some Krazy Glue onto a surface and you'll see how powerful its
properties of adhesion, or stickiness, are. Similarly, someone who
sticks to a cause no matter what has a really strong adhesion or
commitment to that cause.

Adhesion comes from the Latin adhaesionem meaning "a sticking to," a
translation that perfectly captures that adhesive quality. Objects can
be characterized by their adhesion — like Scotch tape or Velcro.
Similarly, when you see a group of protesters camped outside the
Capital fighting for a cause, it's their adhesion (or dedication) that
keeps them stuck there rain or shine. In medicine, adhesion is used to
describe abnormal bands of scar tissue that might form after a
surgery.

There’s a lot of stuff out there that exists to get rid of adhesions
and improve range of motion.

* contestant                                                            :EWW:
[2019-03-09 Sat 18:47]

A contestant is someone who competes in a game or contest. Contestants
in many beauty competitions need to demonstrate a talent, like singing
or dancing, as well as look pretty.

If you're a contestant on a TV game show, you might have to answer
trivia questions, and if you're a debate contestant, you need to argue
your case clearly. You can also be a contestant in a sporting
competition or on a reality show. Contestant comes from the verb
contest, from the French contester, "oppose," which has a Latin root,
contestari, "to bring action."

Tim Ferriss: It’s somewhat contraindicated for contestants in fat
adaption.

* chagrin :EWW:
[2019-03-09 Sat 18:48]

Chagrin is a noun that represents an emotion or feeling and it's an
uncomfortable one. If you feel chagrin, it means that you are
embarrassed or distressed as a result of a failure.

The word chagrin, a noun, comes from the French word of the same
spelling and means "melancholy, anxiety, vexation." An odd fact about
the word in English is that it had been thought to be related to
another, similar-sounding word, shagreen, "an untanned leather with a
granular surface, prepared from the hide of a horse, shark, seal,
etc." When one mistakes one word as a relative of another, it's called
"false etymology."

Tim Ferriss: Much to my chagrin, anyways.

* flinch :EWW:
[2019-03-09 Sat 18:50]

To flinch is to react to pain by wincing, pulling away, or cringing.
Often it's used to describe a person who shows a moment of weakness or
fright: he was so tough, I thought he'd never flinch, but snakes
really freak him out.

To flinch is to pull away suddenly or recoil when something frightens
or hurts you. People flinch at different things. Needles, for example,
cause some people to flinch, while they're not even noticed by others.
If you can withstand something awful without showing it, you're likely
to hear someone say "Wow! You didn't even flinch!" Think of it as a
combination of flee and pinch. If you don't flee when you get pinched,
you don't flinch.

Tim Ferriss: That’s why you didn’t flinch when we were talking about
Jocko Willink, the SEAL Commander.

* supposedly :EWW:
[2019-03-09 Sat 19:02]

If you hear that something is supposedly going to happen, it may or
may not occur. If a friend is supposedly having a pool party next
week, wait until you know for sure before you buy that new swimsuit.

When you add supposedly to a sentence, it means you aren't sure. If a
teacher says there is supposedly an early dismissal next week, it
means that decision isn't final yet, but it could happen. If a singer
is supposedly dating a certain actor, it isn't official — it might
just be gossip. Don't confuse supposedly with similar-sounding
supposed to be, which can imply a judgment.

The air pressure chambers that supposedly flush out lactic acid.

* exaggeration :EWW:
[2019-03-09 Sat 19:03]

If you're prone to exaggeration, it means you habitually overstate the
truth. If you have a dog and a hamster, it would be an exaggeration to
describe yourself as "practically Doctor Dolittle," living in a house
full of animals.

When you make something showier, or more noticeable than normal,
that's also called exaggeration. The exaggeration of your hand
movements might be necessary on stage so the audience can see them,
but in real life it just looks silly. Exaggeration comes from the
Latin word exaggerare, which means to magnify or to heap or pile on.

Or is that an exaggeration?

* proponent :EWW:
[2019-03-09 Sat 19:07]

Proponent means someone who is in favor of something. You might be a
proponent of longer vacations, but your parents are proponents of a
longer school year.

If you’re in favor of long school vacations, you’re pro or "for" long
vacations. The prefix pro- also carries the meaning of “forward,”
“ahead,” or “before.” All of these senses are at work in proponent:
someone who suggests (puts forward) an idea or who is in favor of an
idea. A proponent proposes an idea or advocates for a proposal or a
proposition.

Tim Ferriss: Are you a proponent of ice, ice baths, or anything like
that or not?

* delirious :EWW:
[2019-03-10 Sun 15:50]

If you're delirious you're uncontrollably excited or a bit crazy, like
when you win the lottery and run screaming through the streets,
delirious with happiness.

While we sometimes like to say, metaphorically, that strong emotions
make us delirious, this adjective has more grim origins, in the Latin
word for delirium or "madness" — in the medical sense, that is. When
you're delirious from a high fever or a serious bump to the head, you
might become incoherent, hallucinate, or have disturbing dreams. The
story of The Wizard of Oz is based on the delirious dream Dorothy has
after she bumps her head during a tornado.

You’re so tired at that point, and so delirious, that I guess I didn’t
even realize the import of that situation.

* uncanny :EWW:
[2019-03-10 Sun 15:59]

If something is uncanny, it is so mysterious, strange, or unfamiliar
that it seems supernatural. If you hear strange music echoing through
your attic, you might refer to it as positively uncanny.

You can also use uncanny to refer to something that is so remarkable
that it is beyond what is natural: as in "uncanny abilities." This
adjective was formed in English from the prefix un- "not" and canny
"fortunate, safe." The current meaning of English canny is "careful
and clever, especially in handling money."

Mike Birbiglia: He has this really uncanny skill of talking in circles
and slow and circling back to the first topic and then the next topic
and then another thing and then a digression.

* semblance :EWW:
[2019-03-10 Sun 16:07]

Semblance is all about illusion. Cramming all of your dirty clothes
into the closet gives the semblance, or false appearance, that you've
done your laundry — but the stench might give you away.

Semblance comes from the 14th-century French word for "resemble," and
it is a noun for things that look one way on the outside but are very
different on the inside. A popular combination is to say that a person
or place has the "semblance of order," when, underneath, everything is
out of control.

I wonder if it makes the value of the rituals even greater if you are
able to maintain some semblance of a routine when touring?

* irksome :EWW:
[2019-03-10 Sun 16:10]

If your little brother keeps saying the same phrase over and over
again, you might find it irksome — that is, annoying in a tiresome
way.

If you are a person who likes to know exactly where words come from,
you might find it irksome that the etymology of irksome's 15th century
ancestor irken is unknown. If you complain about this to all of your
friends, they might start to find you irksome also.

I think that there’s a cultural thing right now that it is kind of
irksome, which is that people feel like – I read it recently in The
New York Times, where someone said, I’m forgetting her name who wrote
this, but she said “If I had advice for college students, it would be
don’t ask what do I want to be when I grow up?

* veer                                                                  :EWW:
[2019-03-10 Sun 18:04]

To veer is to make a sudden turn, like when a driver veers off the
pavement or a pleasant conversation veers off in a troubling
direction.

When you make any quick change of direction you veer. You can veer
toward an attractive person at a party, leaving your friends
mid-sentence. You veer away from an oncoming truck on the highway to
avoid getting crushed. Originally, veer described a change in the
direction of the wind, but as you can see, today, anyone or anything
that changes direction veers.

Though strong concentration can be an enormous aid along the way, the
Buddha’s path veers into a different kind of inner focus: the path of
insight.



* stance :EWW:
[2019-03-10 Sun 18:07]

Your stance is your posture or the way you stand. Figuratively, if you
take a stance against bullying, you are standing against it.

If you take a stance on a contentious issue, it means you believe
strongly about it one way or the other. If your stance is unpopular,
you'll need some courage to speak your mind. The word comes from the
Italian stanza which means stopping place. Your stance is something
that's not likely to change. You have stopped there, your decision is
made. You're done.

If we think much of anything
about what just arose, or let it trigger any reactivity
at all, we have lost our mindful stance—unless that
reaction or thought in turn becomes the object of
mindfulness.
* compel :EWW:
[2019-03-10 Sun 18:10]

Compel means to force or drive someone to do something. Even if you
don't like toast, when you visit the toast-eating natives of
Shrintakook Island, you'll be compelled to eat it, or they will not
trust you.

You don't want to be compelled to go to a classical music concert if
you'd rather listen to rap. School officials might be upset if a
winter storm compels them to cancel classes, but you'd be okay with
that. A compelling mystery forces you to pay attention because you
want to find out "whodunit."

Ordinarily our thoughts compel us: our loathing or
self-loathing generates one set of feelings and actions;
our romantic fantasies quite another.
* absolve :EWW:
[2019-03-11 Mon 10:18]

To be absolved is to be let off the hook, to be set free from a
certain obligation or to be forgiven for a wrongdoing. The Church may
absolve you of your sins, but that won't absolve you of the need to
attend mass.

The Latin absolvere, which means "to set free," is the root of the
word absolve. In the religious sense, to be absolved means to be truly
forgiven in the eyes of the Lord, which must feel like being set free.
In a more mundane everyday usage, absolve can be used to describe
being let off the hook. For instance, putting a campaign poster in
your window does not absolve you of the responsibility to vote.

It’s possible to try to optimize health to the point
where it’s in your best interest to just sit in the
metal box and absolve yourself of interacting with
anything in life.
* crude :EWW:
[2019-03-11 Mon 17:07]

Is it gross? Unsophisticated? Totally tasteless and positively
offensive? Then you can describe it as crude.

Crude is not rude when it’s used to describe unprocessed oil, which it
first was associated with in 1865. From the Latin crudo, meaning
"rough, raw," crude today can be used to describe anything or anyone
that's unrefined and rough around the edges. So don’t be too insulted
by the large-nosed portrait that cartoonist made for you. It’s just a
quick, crude drawing meant to be funny.

At the time, it
was highly crude.
* fuzzy :EWW:
[2019-03-11 Mon 17:11]

Fuzzy things are soft, downy, or furry. Few people can resist the
charms of a tiny, fuzzy kitten.

Your dad's bearded face is fuzzy, and your favorite mohair sweater is
also fuzzy. You can also use this adjective to mean "blurry" or
"clouded," the way a badly lit scene in a movie might look fuzzy, with
vague shapes moving in the dark. The inside of your head can feel
fuzzy too, when you're groggy or dizzy: "I remember getting hit in the
head by the soccer ball, but after that everything's fuzzy."

Peter Attia: Yeah, it’s kind of a fuzzy definition.
* meticulous :EWW:
[2019-03-19 Tue 21:02]

People who are meticulous can be pretty annoying, what with their
extreme attention to detail. But if that person is, say, your surgeon
or your accountant, you'll want them to be meticulous.

The Latin root of meticulous is metus, which means "fear," so it's
easy to see how eventually meticulous got its meaning. Someone who's
meticulous is afraid of what will happen if they're not careful enough
to get every detail right. "Detail oriented" and "perfectionist" are
other ways of describing someone who cares deeply about the small
things and about getting things exactly right, every time. Concert
pianists must be meticulous, because audiences are always listening
for wrong notes.

Tim Ferriss: Orthorexia is used as a derogatory term,
but I think you’re very meticulous in your own testing
and perhaps even separate from [inaudible], but you’ve
introduced me to quite a few interesting tools or
concepts.
* derogatory :EWW:
[2019-03-19 Tue 21:02]

Something that's derogatory is insulting or disrespectful. If you make
derogatory comments, that means you say things that are unflattering,
unkind, or demeaning.

Derogatory means about the same as insulting. Derogatory language is
meant to hurt, and it usually does. If you feel offended or insulted
by what someone says, the person probably said something derogatory.
Racial, sexist, and homophobic slurs are all derogatory. Insults that
mean someone is stupid or crazy are derogatory. Making a joke about
someone's mother is derogatory.

Tim Ferriss: Orthorexia is used as a derogatory term,
but I think you’re very meticulous in your own testing
and perhaps even separate from [inaudible], but you’ve
introduced me to quite a few interesting tools or
concepts.
* palatable :EWW:
[2019-03-20 Wed 00:26]

Something that is palatable is acceptable to one’s sense of
taste—literally or figuratively. If it's palatable, then you can put
up with it — whether it's leftovers or a mediocre made-for-TV movie.

The palate is the roof of the mouth, the combination of structures
that separates the mouth from the nose. Early anatomists believed that
the sense of taste was located in the palate, and, just as taste is
metaphorically expanded to include sensibilities beyond the experience
of food and drink, so palatable can be used to describe phenomena
beyond the culinary. And, while palatable can mean pleasing or
agreeable, it generally means merely tolerable—edible, rather than
delicious.

I tear open the box – and
also there was a note in there that explained a somewhat
palatable cocktail that you could mix – like how you
could mix this with ten other things.
* gagging :EWW:
[2019-03-20 Wed 00:28]

A gag is a piece of cloth that's tied around a person's face to keep
them from speaking or being heard. Cartoon bad guys often tie up their
victims and put gags over their mouths.

To use a gag for shutting someone up is to gag them. Both the noun and
verb forms of gag can also be figurative: "Her government is trying to
gag her by censoring her," or "The lack of a right to free speech in
some countries is a gag." Another way to gag is to retch, or begin to
vomit. The root of gag is probably the Old Norse gag-hals, "with head
thrown back."

Then my next thought was just,
ohmygod, you’re gagging.
* odd :EWW:
[2019-03-21 Thu 07:57]

The numbers 1, 3, 5, and 35 are all odd numbers — they can't be
divided by two. They are not even. Also, things that are weird or
strange are called odd.

This word covers things that are slightly off-kilter, like odd
numbers. You can use odd for a single thing that belongs in a pair,
like an odd sock or odd mitten. If someone wants you to do odd jobs,
that could mean almost anything: odd jobs are random and unpredictable
jobs that could come up. When you describe a person as odd, or that
they’re exhibiting odd behavior, it means they're peculiar and out of
the ordinary.

But look, outside of the odd,
let’s do a one-week-a-year fast sort of thing, how does
that play into something beyond that?

* unwittingly :Keller:
[2019-03-21 Thu 10:08]

When you do something unwittingly, you don't do it on purpose. It's
completely accidental or unintentional, like when you unwittingly
offended the Queen by not curtseying properly.

If you know exactly what you're doing, you're not doing it
unwittingly; you're doing it intentionally. This adverb comes from
unwitting and its Old English root unwitende, "ignorant." Wit means
"knowledge," so if you do something unwittingly, you act without
knowledge. If you post too much personal information online, you might
unwittingly set yourself up to have your identity stolen.

Whether the writers knew it
or unwittingly stumbled on it, what they wrote was the
absolute truth.
* turmoil :Keller:
[2019-03-21 Thu 10:10]

Mashed potatoes flew in one direction, peas in another. Kids were
standing on chairs. The principal was shouting, but no one listened.
"Food fight!" the seniors cried. The cafeteria was in a state of
turmoil.

Turmoil rhymes with boil––think of the way that boiling water moves,
and you'll understand what turmoil looks like. It refers to confusion,
chaos, violent disturbance. The economy can be in turmoil––the markets
behaving erratically, people losing their jobs, and no one
understanding why.

For all the
dedication and hard work, my life was in turmoil and it
felt as if everything was crumbling around me.
* plywood :Keller:
[2019-03-21 Thu 12:58]

Plywood is a building material that's made from layers of wood that
are glued together. This construction means that plywood is very
strong and resistant to chipping or warping.

There are many kinds of plywood, and even more ways to use it. Plywood
made from soft woods is used for sub-flooring in new homes and
packaging of various kinds. Harder plywood can be made into furniture,
walls, cabinets, stereo speakers, and sports equipment. The layers (or
plies) in a piece of plywood are glued together with the grain
direction alternating, which makes it sturdy even when it's thin.

In
2001 a physicist from San Francisco’s Exploratorium
reproduced Whitehead’s experiment by creating eight
dominoes out of plywood, each of which was 50 percent
larger than the one before.
* topple :Keller:
[2019-03-21 Thu 12:58]

To topple something is to knock it down. A house of cards can be
toppled — so can a government.

Things can topple in several ways. If a building collapses or falls
down for any reason, it topples. If you knocked over another student,
you toppled that person. Governments that are overthrown are also said
to be toppled. When you see the word topple, someone or something is
going down.

In 1983, Lorne Whitehead wrote in the American Journal
of Physics that he’d discovered that domino falls could
not only topple many things, they could also topple
bigger things.
* defy :Keller:
[2019-03-21 Thu 13:00]

To defy is to openly refuse to do something. You can defy the
no-costumes-in-class rule if you wear your fairy wings to school, but
just don’t try to defy the laws of gravity unless you can actually
fly.

If you deliberately break a rule or ignore an order, you defy, or
resist, that rule. The word defy comes from the Latin word disfidare
for "renounce one's faith." So if you're expected to be faithful to a
certain law or rule but you refuse to be, you defy it. There are
different ways to defy — defy your parents by staying out past curfew,
or defy common sense by walking in with shoes on your head.

The
result could defy the imagination.
* lease :Keller:
[2019-03-21 Thu 13:17]

To lease something is to borrow it in exchange for money. If you lease
a car from a dealer, for example, you make payments and you get to
drive the car, but at the end of the contract you have to give it
back.

As a noun, a lease is both the thing you are contracting to rent (the
car itself is a lease) and the contract spelling out the terms of use
— in other words, a rental agreement. Be sure to check the fine print
on your apartment lease to avoid any unpleasant surprises when you
move out — like owing money for painting over that hideous wallpaper
in the living room.

Then, when Sam was opening his first
Wal-Mart, Robson secretly paid a landlord $20,000 to
provide a pivotal expansion lease.
* lone :Keller:
[2019-03-21 Thu 13:25]

Something described as lone is the only one of its kind — it's on its
own. The lone child waiting for a ride home from school is the very
last kid to be picked up.

The lone tree in your yard is the only one growing there, and if your
well is your lone source of water, it's the only way that water flows
from the shower or the kitchen faucet. Sometimes lone is used to mean
"lacking support," as when a state senator's vote is a lone voice in
opposition to a proposed bill. If someone calls you a "lone wolf,"
they see you as someone who prefers acting alone.

He was the lone survivor.
* honing :Keller:
[2019-03-21 Thu 13:27]

The verb hone means to sharpen skills. When you practice shooting
baskets every day after school, you are honing your skills as a
basketball player.

Hone, the verb, literally means to sharpen with a hone, a whetstone
used to sharpen cutting tools. Use hone to describe someone working
hard, perfecting or sharpening skills, as in "She is honing her skills
as an actress by working in community theater." Hone, which rhymes
with phone, is from the Old English word, han, meaning "stone, rock."

He came to Texas and kept competing, honing his skills.
* propel :Keller:
[2019-03-21 Thu 13:29]

To propel is to push or drive forward, like a sheep dog nipping at the
heels of his flock to keep them moving.

When you hear the verb propel, imagine the propeller on an airplane —
that spinning thing on the front that pulls the plane forward. Or
maybe think of the old proverb that goes, “Our passions are the winds
that propel our vessel. Our reason is the pilot that steers her.
Without winds the vessel would not move and without a pilot she would
be lost.”

Applying the ONE Thing to your work—and in your
life—is the simplest and smartest thing you can do to
propel yourself toward the success you want.
* flung :Keller:
[2019-03-21 Thu 13:34]

To fling is to throw something with force. You'll start a food fight
in the cafeteria if you fling your vegetables at the kid across the
table.

The act of throwing something recklessly or with force can also be
called a fling. Your mail sorting ritual might be putting bills in one
pile and personal letters in another, then giving junk mail a fling
into the recycling bin. A brief period of revelry or indulgence is
another kind of fling. You and your friends could plan a weekend fling
in New York, staying in a hotel, eating out, and shopping without
worrying about how much money you spend.

The doors to the world have been flung wide open, and
the view that’s available is staggering.
* premise :EWW:
[2019-03-23 Sat 07:29]

A premise is what forms the basis of a theory or a plot. When you
called 911 on the guy in your back yard, it was on the premise that he
was a thief and not the meter-reader.

In logic, the premise is the basic statement upon whose truth an
argument is based. Criticize alternative theories by demonstrating
their false premises. In a more general sense, it's a basic assertion.
On the premise that people are generally good, you keep your doors
unlocked. Premise is also used more loosely for the starting point for
a plot. A movie's premise could be that two people trapped on a desert
island will inevitably fall in love.

So, these commonalities were the premise of my most
recent book and No.
* wellness :EWW:
[2019-03-23 Sat 07:32]

Wellness is the opposite of illness. When you're healthy and not
suffering from any diseases, you're enjoying a state of wellness.

It might seem like the phrase "health and wellness" is a little
repetitive, but the two terms have increasingly distinct meanings.
Since the middle of the 20th century, wellness has become the popular
term, especially in alternative medicine, to describe health that
includes a balance of body, mind, and spirit.

So, in this particular episode, I have gathered some of
the best advice from past guests about fitness,
nutrition, and for lack of a better term, wellness,
although that term bugs me, but it’s a good catchall.
* intermittent :EWW:
[2019-03-23 Sat 07:43]

Reach for the adjective intermittent to describe periodic movement and
stopping and starting over a period of time.

The adjective intermittent modifies things that work or stop and start
at periodic intervals. An interesting use of something intermittent is
a metronome, a device that marks off time in music by making a sound
in a regular pattern. It provides structure for musicians, especially
when there are several instruments all playing different melodies at
the same time. Other intermittent things are the windshield wipers on
your car and thank goodness for them when it rains!

And there are many different varieties of intermittent
fasting.
* contiguous :EWW:
[2019-03-23 Sat 07:49]

Use the adjective contiguous when you want to describe one thing
touching another thing, or next to it but not actually touching.

Things that are contiguous are near or next to but not actually
touching and yet they are also defined as "touching, sharing a
border." You can use this adjective to describe people or things
related to and nearby others. It comes from the Latin word contiguus,
which means pretty much the same thing, "bordering upon." Because the
word has two meanings that are very similar but not always the same it
can be a bit confusing. This is an example of what's called "semantic
ambiguity," when something can mean more than one thing or a word or
phrase is not precise.

But I like to do a contiguous three-day
fast each month, generally Thursday dinner to Sunday
dinner, and that should be medically supervised.
* slew :EWW:
[2019-03-23 Sat 07:50]

Of all the many nouns referring to a large group of things, one of the
most fun is slew, as in "I saw a whole slew of birds in the tree by
the river."

American English is constantly evolving, its richness coming from the
many languages feeding into it. The noun slew, for instance, is from
the Irish Gaelic sluagh, meaning "multitude." As an unrelated verb,
it's the past tense of slay.

I have a slew of
questions, but the one that I have been asked to ask
you, Stan, more than perhaps any other is, why one meal
a day?
* pretzels :EWW:
[2019-03-23 Sat 07:54]

A pretzel is a crispy snack or a soft, baked good. Both kinds of
pretzel usually have a distinctive, knot-like, twisted shape.

Pretzels are salty snack foods, so you'll find them alongside potato
chips and popcorn in the grocery store. Pretzels that come in a bag
are crisp and small, while the soft kind is often sold from food carts
and topped with mustard. The pretzel was originally a German
invention, so it makes sense that the word comes from the German
Brezel, which is rooted in the Medieval Latin brachitella, "biscuit in
the shape of folded arms."

And
I used to keep a bin of those hard pretzels in my office
in Afghanistan, and I’d grab a handful of those.
* haunts :Keller:
[2019-03-23 Sat 08:03]

The verb to haunt means to appear as a ghost or some kind of
supernatural phenomenon. Ebenezer Scrooge was haunted by the Ghosts of
Christmases Past, Present and Future.

The first recorded usage of the word haunt is in William Shakespeare’s
A Midsummer Night’s Dream, a play filled with supernatural characters
running around scaring the knickers off each other. As Shakespeare
knew, haunting is at its most effective in the passive voice, because
there is much more drama in being haunted than haunting. Another use
of the word haunt is as a noun, and it means "a place that is
frequented often," like a popular hangout. The gym, a bar, a corner:
these are all potential haunts. The dentist, the principal’s office, a
busy intersection: these are not.

Harried and hurried, a nagging
sense that we attempt too much and accomplish too little
haunts our days.
* banish :Keller:
[2019-03-23 Sat 08:07]

To banish is to get rid of. Think very carefully before you banish
someone from your group. Someday, you may want that person around
again.

Banish rhymes with vanish, which is exactly what happens when you
banish someone. Suppose a king, angry with some of his subjects,
banishes them. They have to leave the kingdom and vanish — not just go
home and wait for the king to change his mind. Banish comes from the
Old French word banir, which means “proclaim as an outlaw.” It is
serious and absolute. You can see the word ban in banish, but to ban
something is not as harsh as banishing it.

Once we banish these from our minds, we can take up the ONE Thing with
an open mind and a clear path.

* perceptible :EWW:
[2019-03-23 Sat 20:12]

Something perceptible is noticeable, even if just slightly. A
perceptible noise can be heard.

You perceive through your senses, and things that are perceptible can
be perceived; you can sense them. A flavor is perceptible if you can
taste it. A sound is perceptible if you can hear it. The opposite of
perceptible is imperceptible, for things that can't be noticed or
detected. If you notice a sound, sight, or change, then it must be
perceptible.

After one in-person training session with Wim, I went for my normal
45-second breath-hold or so, to four minutes and 45 seconds with no
perceptible side effects.
* accolades :EWW:
[2019-03-23 Sat 20:15]

A knight being honored with the tap of a sword-blade was the earliest
form of accolade. Today, an accolade is more than a way to bestow
knighthood, it is a form of praise or an award.

In the early 17th century, the French accoler meant to "embrace the
neck," which was done as part of a knighthood ceremony. By the 19th
century, accolade came to mean "award." A person who achieves a goal
in research or service may receive an official paper certificate or
trophy, an accolade of achievement, while a performer or speaker might
get an accolade in the form of applause from the audience. Rarely does
either of these types of accolade involve a sword.

You have such a fascinating story, and you have a
lot of accolades, a lot of records, I think more than 20
world records at this point −
* Refrain :EWW:
[2019-03-23 Sat 20:34]

When someone burps in a quiet classroom it can be hard to refrain from
laughing. Use the verb refrain if you have a sudden impulse to do
something, and you have stopped yourself from doing it.

It's usually hard to refrain from doing something, because this word
is used to describe habits, like smoking, or uncontrollable urges,
like laughing. The Latin word refrēnāre is formed from the prefix re-
"back" plus frēnāre "to hold a horse back with a bridle." There is a
noun refrain, but that's a different and unrelated word.

Refrain
from breathing.
* heed :Titans:
[2019-03-24 Sun 20:52]

Heed is an old word, meaning to listen to and follow. It can also be
used as a noun: "Take heed of my instructions, little boy," said the
old bearded man. "My potion will only work for the one who wears the
ring."

The most common use of heed is with warnings. The word derives from
Old English hēdan and is related to the Dutch hoeden and German
hüten––from Germanic cultures where fairy tales with mysterious
warnings and magical consequences abound.

If
you find anything ridiculous in this book, it’s because
I didn’t heed their advice or made a mistake.
* compendium :Titans:
[2019-03-24 Sun 21:01]

When you search an online encyclopedia, you are searching a compendium
of information on just about everything. A compendium is a
comprehensive collection of something.

You can also use the word compendium to describe a collection of
written works. If you gather all of the anecdotes your parents and
grandparents have told you into a book, you'll have created a
compendium of family stories. The plural of compendium is either
compendiums or compendia.

This book, like my others, is a compendium of recipes
for high performance that I gathered for my own use.
* percolating :Titans:
[2019-03-24 Sun 21:04]

When something percolates, it spreads gradually. If the news of your
victory in the spelling bee spread slowly through your entire school,
you could sit back and enjoy watching it percolate.

When a liquid percolates, it's filtered through something, and when an
idea percolates, it's filtered through a group of people. Percolate
often refers specifically to coffee, which is brewed by mixing ground
coffee beans with hot water and filtering them through paper — in
other words, coffee percolates. The Latin root is percolatus, which
comes from per, or "through," plus colare, "to strain."

Hemingway wandered up
and down the sidewalks, his books percolating in his
mind, wine no doubt percolating in his blood.
* motley :Titans:
[2019-03-24 Sun 21:06]

If you've encountered the word motley, it's most likely in the phrase
"motley crew," which means a diverse and poorly organized group. Think
of a band of pirates, or the assorted characters who became The
Fellowship of the Ring.

In contemporary usage, motley can be used in virtually any context as
a synonym for mismatched, heterogeneous, or ragtag. But the word was
first used to describe multicolored fabric, especially the type of
material used in a jester's costume. This distinctive apparel was a
sign of the fool's place outside the class system — and, in the
Elizabethan era, it signified that the jester was beyond the sumptuary
laws that determined who could wear what. Thus, the fool had the
exceptional ability to speak freely, even to royalty.

It was a motley crew.
* lofty :Titans:
[2019-03-24 Sun 21:09]

Lofty is a good word for describing something that's high above the
ground, or someone who acts like she's high above everyone else.

Dating from the 15th century, lofty originally meant "exalted," or
spiritually high, but soon came to mean physically high as well. A
towering mountain can be called "lofty." So can someone who walks
around with her nose in the air and speaks in a fake English accent.
Even if she's only five-foot-two.

That was the lofty goal, at least, and I wasn’t sure
what the result would be.
* revelatory :Titans:
[2019-03-25 Mon 19:25]

Anything revelatory reveals something you've never seen or realized
before. A revelatory article in a tabloid paper might give you the
scoop about a celebrity's (previously) private life.

A revelatory artwork might show you something in a completely new
light, like a giant art installation that incorporates the natural
landscape around it, or a piece of music that stirs a deep feeling of
nostalgia or sadness when you listen to it. People often describe
religious experiences as revelatory, and early uses of revelation were
also religious, meaning "disclosure of information from a divine
source." The Latin root is revelare, "uncover or lay bare."

The process of piecing them together was
revelatory.
* weave :Titans:
[2019-03-25 Mon 19:29]

Weaving involves lacing strips of fabric, string, or some other
material together to make something. You can weave wool to make a rug,
or weave the details of a story together to make a great book.

While weave originally only meant to make cloth by interlacing
material, it later came to also mean more generally “combine into a
whole.” Think of a spider and how it weaves its web, or of how some
songs expertly weave in unexpected elements, like the sound of a siren
or the waves crashing. You can also use weave to describe a swaying
motion, like that of a car darting through traffic when it’s trying to
move ahead.

To help you see the same, I’ve done my best to weave
patterns together throughout the book, noting where
guests have complementary habits, beliefs, and
recommendations.
* onerous :Titans:
[2019-03-25 Mon 19:38]

If one teacher gives you three hours of homework a night, that's
rough. But if all of your teachers do it, that makes the task of
completing your homework an onerous one, to say the least. If
something is onerous, it is very difficult to deal with or do.

A near synonym is burdensome. In legal usage, onerous describes a
contract or lease that has more obligations than advantages. Onerous
derives from Middle English, from Old French onereus, from Latin
onerōsus, from onus "burden." In English, an onus is a task or duty
that is onerous, or very difficult.

When organizing all of the material for myself, I didn’t
want an onerous 37-step program.
* outliers :Titans:
[2019-03-25 Mon 19:45]

In statistics an outlier is a piece of data that is far from the rest;
think of a graph with dots, where most dots are clustered together in
the middle, but one dot, the outlier, is at the top.

Think of an outlier as an outsider. An outlier refers to anything that
strays from, or isn’t part of, the norm. If you like to sleep in a
tent in the backyard while your neighbors and family sleep in their
beds, you’re probably an outlier. You may also be an outlier if you
have to travel far to your job. In geology, rock that is separated
from another rock formation is called an outlier.

Some of
the most encouraging workarounds are found in the
outliers.

* pinpoint :eww:
[2019-03-28 Thu 08:59]

To pinpoint something is to nail down its exact location.

The point of a pin is very small and fine. Similarly, when you
pinpoint something, you have narrowed down its location to the
smallest possibility: you've found out exactly where it is. The
government is constantly trying to pinpoint the location of
terrorists, just as police try to pinpoint the location of criminals.
Dogs can pinpoint many things through smell. It's often hard to
pinpoint which car is producing an annoying car alarm. When you
pinpoint something, you've found it.

2 You can’t learn as much from succeeding because it’s
  harder to pinpoint where mistakes are (and it means
  you are not taking enough chances).
* acclamation :eww:
[2019-03-28 Thu 09:07]

Acclamation is acclaim or recognition for some achievement. A major
league baseball team might have to win the World Series to get
acclamation, but a t-ball team might get acclamation simply for
finishing an entire game.

The acclamation you get on opening night might be your main incentive
for acting in plays. Likewise, the acclamation they receive while
campaigning is probably more attractive to some politicians than the
actual work of governing. Acclamation can sometimes take the form of
enthusiastic shouting, and in fact the Latin root acclamationem means
"a shout of approval."

“Speaking” that vocabulary is pleasurable because you
can enjoy the art form more, you can succeed more
easily, you get acclamation for your success, you make
friends with others who are also successful because you
speak their language - but it requires every day
learning new “words” in your art form.
* acclamation :eww:
[2019-03-28 Thu 09:07]

Acclamation is acclaim or recognition for some achievement. A major
league baseball team might have to win the World Series to get
acclamation, but a t-ball team might get acclamation simply for
finishing an entire game.

The acclamation you get on opening night might be your main incentive
for acting in plays. Likewise, the acclamation they receive while
campaigning is probably more attractive to some politicians than the
actual work of governing. Acclamation can sometimes take the form of
enthusiastic shouting, and in fact the Latin root acclamationem means
"a shout of approval."

“Speaking” that vocabulary is pleasurable because you
can enjoy the art form more, you can succeed more
easily, you get acclamation for your success, you make
friends with others who are also successful because you
speak their language - but it requires every day
learning new “words” in your art form.
* circuitous :Titans:
[2019-03-28 Thu 13:27]

Circuitous means indirect or roundabout. If you're in a hurry to get
to the hospital where your wife is having a baby, you want to take the
straightest, fastest way, not a circuitous one!

Circuitous comes from the Latin word circuitus meaning basically "a
going around." If you're being circuitous it's like you're going
around and around in circles. It can also refer to someone's manner or
speech, if they are not being direct. For example, if you want someone
to get you another piece of cake but just you sit there looking
longingly at your empty plate, saying "More cake sure would be nice,"
then you're being circuitous. And annoying.

Seconds later, we were pulled
back into the fray, as the attendees were all taking
turns talking about the circuitous paths that brought
them there that day.
* solace :Titans:
[2019-03-28 Thu 13:30]

If something eases your disappointment or grief, consider it a solace.
If you're sad, you might find solace in music or in talking to your
friends.

It is no surprise that consolation and solace are similar in meaning
as they share a root in the Latin verb sōlārī "to comfort." In fact,
solace and consolation are synonyms meaning relief from grief or
disappointment. When you go to sleepaway camp, your parents will miss
you, but they'll find solace in knowing that you are having fun.

Take solace in that.
* Ditto :Titans:
[2019-03-28 Thu 13:34]

A ditto looks like a quotation mark — " — and it's used as you go down
a list to indicate you're repeating whatever is above.

If your jellies and jams all cost $2.00, you can write $2.00 just once
with the first item on your price list and " in the price column next
to each item listed below. You can also use the word ditto informally
to describe repetition: "I can't believe you wore those shoes. Ditto
that hat." You may recognize Ditto as the aptly named son of the comic
strip characters Hi and Lois; he’s the twin brother of Dot.

Ditto for 4HB and 4HC.
* wager :Titans:
[2019-03-28 Thu 13:38]

To wager is to bet: you might say to your fellow train passengers,
"I'll wager ten dollars that we won't get to Chicago on time."

You can use the word wager as either a noun or a verb, to mean "place
a bet" or "the amount of money being risked in a bet." So you could
offer a wager at the poker table, or ask if anyone wants to wager on
Monday's football game. Either way you use it, wager is a Middle
English word that comes from the Old North French wage, "to pledge."

I’d still wager you’d forget it within a week.
* regurgitate :Titans:
[2019-03-28 Thu 13:40]

To regurgitate is to bring already swallowed food back up through
one's throat and out the mouth. Not so nice in humans, but much more
understandable (if still gross) in birds — who feed their baby chicks
by regurgitating.

Finished cramming for your exam? Ready to do a data dump? Then you're
about to regurgitate all you've learned — repeat information verbatim
without any real understanding or analysis of it. Don't worry,
everyone does it, from high school and college students, to grown-ups
in corporate boardrooms.

The context and original
language teaches you how to THINK like a world-class
performer, not just regurgitate quotes.
* regurgitate :Titans:
[2019-03-28 Thu 13:40]

To regurgitate is to bring already swallowed food back up through
one's throat and out the mouth. Not so nice in humans, but much more
understandable (if still gross) in birds — who feed their baby chicks
by regurgitating.

Finished cramming for your exam? Ready to do a data dump? Then you're
about to regurgitate all you've learned — repeat information verbatim
without any real understanding or analysis of it. Don't worry,
everyone does it, from high school and college students, to grown-ups
in corporate boardrooms.

The context and original
language teaches you how to THINK like a world-class
performer, not just regurgitate quotes.
* ample :Titans:
[2019-03-28 Thu 13:47]

Ample describes an abundance of something. An ample supply of apple
muffins at the bake sale is a good thing, as is ample legroom in your
new van, but you probably don't want your ample waistline spilling
over the top of your jeans.

Like amplify (crank up the volume), ample is from the Latin word
amplus, meaning "large or spacious" and has the word plus in it, like
plus-sized models. Ample can be enough or even too much of something.
It's great when there's ample parking or water for the hike, but there
are things that some people don't want more of, like extra pounds.
It's a cheeky insult to tell someone he or she has ample thighs, but
we'd all be happy if we had ample time and money.

I’ve included ample doses of the ridiculous.

* grudges :eww:
[2019-04-10 Wed 08:30]

If you tend to hold a grudge, you don't let it go when you feel
someone's insulted or wronged you. I hope you won't hold a grudge
against me for bringing it up.

Grudge comes from the now dead Middle English word "grutch," which
meant "to complain or grumble." Someone who bears a grudge might often
be grouchy. You can specify a type of grudge: political grudge,
personal grudge, etc. You know Grandpa's been holding a grudge against
the neighbors for years, but you have to wonder: How long can he hold
that shotgun?

This generation has this habit of holding unnecessarily long grudges.
