-*- coding: utf-8 -*-

* thoracic :Titans:
[2019-04-03 Wed 14:13]

Thoracic is a medical word for things pertaining to the thorax area of
your body: your chest.

You’re likely to see the word thoracic in biology class. The thorax is
your chest: the area between your neck and abdomen. Therefore, this
area is the thoracic region, and that word can be used for issues
dealing with this area. Certain exercises are thoracic because they
strengthen your chest muscles. Your pectoral muscles are in the
thoracic area. Your heart is the most important part of the thoracic
area. If you have thoracic pains, you should see a doctor.

This can perform miracles for thoracic,
or mid-back, mobility, all while helping the hamstrings
in the pike position.
* compound :eww:
[2019-04-03 Wed 17:05]

If you compound a problem you add something to it to make it worse,
like say, putting water on a grease fire. Compound means to combine; a
compound is a combination or mixture of two or more things.

Compound has several specialized uses. A compound is either a mixture
or two or more things, or a heavily guarded residence, such as a drug
lord might have. In botany, a compound leaf consists of more than one
part. In linguistics, a compound is a word that consists of two or
more independent words. In chemistry, a compound is a substance
created when atoms from chemical elements join together.

Because you have the ability to compound
  more than older people.
* cheat :eww:
[2019-04-03 Wed 17:08]

To cheat is to use sneaky, unfair methods to get something you want.
No one's going to want to play with you if you always cheat at mini
golf.

Some people cheat at cards, and others cheat during math tests by
copying from the student beside them. In either case, they're trying
to succeed using underhanded tricks. You can refer to someone who does
this as a cheat as well. Cheat comes from the Old French escheat, a
legal term for the state taking someone's property when he or she dies
without heirs. This practice was resented, and it came to mean
"confiscate unfairly."

25 Husbands cheat on their wives.
* pertaining :eww:
[2019-04-16 Tue 08:18]

To pertain is to be relevant or somehow associated with something. If
you're a lawyer, you try to find evidence that will pertain to the
case and eliminate anything that is not connected.

Behind the verb pertain lies the Latin verb pertinēre, which means "to
be applicable" or "to hold through." If you think the rules of the
road don't pertain to you, try explaining that to the state trooper
when you get pulled over. Usage note: The word pertain often takes an
s at the end, as in "That pertains to this matter," but loses it with
a helper: “That doesn’t pertain to it.”

5 Learn something pertaining to your career every day of the week.

* reconnaissance :eww:
[2019-04-16 Tue 08:21]

Reconnaissance is checking out a situation before taking action. Often
it’s used as a military term, but you could also do reconnaissance on
a new employee before you hire her, or a resort before you take a
vacation.

Reconnaissance is a noun, and it technically means “the act of
reconnoitering.” Whoa. Never heard that word before? Reconnoitering is
just a fancy way of saying that you’re checking something out —
sometimes in a sneaky way. If you like a girl in your Spanish class,
you might ask a friend to do some reconnaissance to find out what
she’s like. The word comes from the French reconnaître, which means
“recognize.”

Think of it as
  reconnaissance.
* dare :eww:
[2019-04-16 Tue 08:25]

When you challenge or provoke someone to try something risky, it's a
dare. If you accept a dare, you're probably trying to prove how brave
you are.

When you challenge your friend to a dare, you dare him. You might, for
example, dare your brother to jump off the garage into a pile of
leaves. Another way to dare is to actually be brave: "I admire her so
much, because she dares to stand up to bullies." The Old English root
of dare is durran, "to brave danger, venture, or presume." If you say,
"How dare you?" you're expressing outrage or indignation.

1 Life tends to reward those who dare, and punish those who fear.
* lump :eww:
[2019-04-16 Tue 08:39]

If it's hard to determine its shape and otherwise looks like a big
blob of something, it's probably safe to call it a lump.

Jabba the Hut looks like a disgusting lump. So does the growing mound
on your noggin where you walked into the glass door. And if you've
been lumped together with a bad bunch, you might have been grouped
with people indiscriminately. But all lumps aren't bad. Little old
ladies put lumps of sugar into their tea. And that choked up feeling
you get during a sappy movie? That's just a lump in your throat.

5 Don’t start a business because others are doing it or because you’ve just
  come across a lump sum.
* deterred :eww:
[2019-04-16 Tue 08:51]

Deter means to discourage, or literally “to frighten away.” Halloween
decorations that are too scary might deter trick-or-treaters, and the
risk of being expelled deters kids from cheating in school.

Deter comes from the Latin de meaning "away" and terrere meaning
"frighten." Something that deters isn’t always scary, though:
citronella plants deter mosquitoes, and fines deter people from
littering. Teddy Roosevelt's foreign policy dictum "speak softly and
carry a big stick" was meant to deter other countries from attacking
the United States.

20 Never be deterred by other peoples opinions of your abilities.
* blessing :eww:
[2019-04-16 Tue 08:53]

A blessing is a prayer asking for God's protection, or a little gift
from the heavens. It's also any act of approving, like when your
roommate wants to move out and you give her your blessings.

Blessings have to do with approval. The first meaning is asking God
for protection or favor. Priests and ministers say blessings in
church, and some families say a blessing before dinner. Outside a
religious context, blessings are less formal. "I give you my blessing"
simply means "It's OK with me." People give their blessings to ideas
and actions when they agree with them. Giving a blessing is often the
same as giving permission.

26 Every failure is a blessing in disguise.
* strike :eww:
[2019-04-16 Tue 09:27]

At its most basic, strike means to hit. If you strike someone, you hit
them with your hand or a weapon. If lightning strikes, it makes
contact. If you strike out on a trip, you're "hitting" the road. If
you strike gold, you've "struck it rich"!

Strike can also mean not to hit, as in miss –– as in "three strikes
and you're out." That meaning might have evolved from strike meaning
to cross off, as in "If you don't come to practice, coach will strike
your name from the starting lineup." It might also have led to the
idea of a labor strike. If employees want to protest their work
conditions, they go on strike, or refuse to work until conditions
improve.

and strike oil.”
* slid :eww:
[2019-04-16 Tue 09:33]

To slide is to move down or across something in a smooth way. If
you’re into that kind of thing, head to a playground and go down a
slide. Just don’t push any toddlers out of the way.

You can slide your bed across your room so it's near the window, or
slide on the kitchen floor in your socks. You can also slide down a
slide, a play structure that's designed for climbing up and sliding
down. Another kind of slide is the small rectangular piece of glass
that scientists slide under a microscope to examine specimens, or the
photography slide you slide into a projector for viewing.

As detailed in this account of the Angola Train Horror the car slid
down into a gorge catching fire along the way and killing 49
passengers in the process.
* gorge :eww:
[2019-04-16 Tue 09:33]

A gorge is a very deep crevice between two mountains or hills. Gorges
are formed by rivers running through and eroding rock over a very long
period of time.

The Latin root of gorge means "throat," leading to both the "narrow
passage" meaning and the French gorgier, "to swallow," which
influenced the verb version of gorge, "to overeat." You may love to
gorge on ice cream, but the stomachache afterward won't be very
pleasant. To remember the "canyon" meaning, think of the famous
upstate New York bumper sticker, “Ithaca is gorges.” It's a play on
gorgeous, meaning beautiful, and the beautiful ravines in the area.

As detailed in this account of the Angola Train Horror the car slid
down into a gorge catching fire along the way and killing 49
passengers in the process.
* graft :eww:
[2019-04-16 Tue 09:35]

Graft can mean bribery or corruption. It's also a way of transplanting
skin or bones in medicine, as in a skin graft.

People who get terrible burns on their faces often have pieces of skin
taken from other parts of their bodies to help them heal and look
better. That transplanted skin is called a graft. There are also
grafts in agriculture, when farmers take a branch from one tree and
graft it onto another tree. The most common use of graft is in
political corruption cases when politicians are accused of taking
money in exchange for granting favors.

“EVERYBODY is talkin’ these days about Tammany men growin’ rich on
graft, but nobody thinks of drawin’ the distinction between honest
graft and dishonest graft….

* ruffling :eww:
[2019-04-27 Sat 09:25]

A ruffle a pleated piece of decorative fabric often used as trim on
clothes, like the ruffles on a pirate’s shirt. To ruffle is to make
someone lose their composure. Argh.

The word ruffle is mysterious, but it might be from the Low German
word ruffelen which means "to wrinkle." A ruffle on the bottom of a
dress is like a fancy wrinkle. To ruffle someone is to upset them, and
they’ll need to get straightened out. Often, this word is used in the
expression "ruffle their feathers." Hearing bad news will ruffle most
people's feathers. An unruffled person and an unruffled shirt will
both be smoother.

Then after
sundown, when the rosy light fades from the sky and the
shadows rise slowly through the wood, out she comes ruffling
and blinking from the old hollow tree.
* slumbers :eww:
[2019-04-27 Sat 09:27]

Slumber means "sleep" — as a verb or noun. If you're a sound sleeper,
you might slumber peacefully right through a thunderstorm, your
slumber undisturbed.

To slumber is to sleep, sometimes specifically to sleep lightly or
doze. You can slumber in your bed, in your airplane seat, or through
your alarm in the morning. Slumber can also describe a peacefulness,
like your quiet street that seems to slumber early in the morning. The
phrase slumber party was first used in the 1940s to mean a gathering
held at night, that usually involves very little slumbering.

Now there was a certain old Owl who had become very cross and hard to
please as she grew older, especially if anything disturbed her daily
slumbers.
* raspy :eww:
[2019-04-27 Sat 09:28]

A sound is raspy when it is rough or scratchy. If you get a bad cold
or scream encouragement to a losing team for a few hours, you will end
up with a raspy voice.

A rasp is a tool, usually used by wood- or metal-workers, to scrape.
Nail files and kitchen graters do the same work that a rasp does. A
raspy voice sounds like it had to pass through a rasp or a grater to
get out of your mouth. If you can barely speak, you might ask for
water in a raspy whisper. Other sounds can seem raspy too like a dry
cough, the caw of a crow or the bark of a dog that has been at it for
a long time.

One warm summer afternoon as she dozed away in her den in
the old oak tree, a Grasshopper nearby began a joyous but very raspy
song.
* den :eww:
[2019-04-27 Sat 09:32]

Where’s the one place that bears go to hibernate and you go to watch
the big game? It’s the den, a secluded room or shelter.

Den is an Old English word meaning “shelter for a wild animal.” While
we still use it in this sense, the word has taken on some additional
meanings. For example, den can refer to a room that's used primarily
for relaxing, watching television, and socializing with friends. (If
your friends tend to act wild at times, then perhaps this definition
isn’t so far off from the original one.) Den can also mean "a hideout
for criminals."

Up he jumped to the Owl's den, but as soon as he was near enough so
the old Owl could see him clearly, she pounced upon him and ate him
up.
* pounced :eww:
[2019-04-27 Sat 09:33]

To pounce is to attack suddenly by leaping onto your prey. A tiger
will slowly sneak up on its prey and then suddenly pounce, using speed
as much as strength to make the kill.

Of all the animals, cats are the best at pouncing. Snakes strike.
Elephants charge. But when an animal leaps onto its prey, that's
pouncing. When we talk about how people pounce, however, we're usually
talking more figuratively. When we say that a person pounced on
another person, we mean that they attacked viciously without warning —
usually giving the victim no time to defend themselves. Lawyers pounce
on witnesses, for example. If you feel suddenly ganged-up on, you
might feel pounced upon.

Up he jumped to the Owl's den, but as soon as he was near enough so
the old Owl could see him clearly, she pounced upon him and ate him
up.
* slender :eww:
[2019-04-27 Sat 09:38]

Something slender is slight, or skinny. A young colt is slender
compared to the full grown horse it will grow into.

Slender can be used in both positive and negative ways. If someone
tells you you have a slender figure, you'll probably be happy, unless
you're going for muscle-mass. A slender portion of potatoes will not
cheer a hungry growing boy. If you don't know much about something,
you can say your knowledge of it is slender. And if you become an
artist, get used to living on a slender budget. Now that's a nice way
to put it.

A Giant Oak stood near a brook in which grew some slender Reeds.
* tempest :eww:
[2019-04-27 Sat 09:39]

Shakespeare's The Tempest begins with one –– a tempest, or a violent
and windy storm.

The meaning of tempest has expanded over time to include the idea of
anger or fighting. A "tempest in a tea pot" means a passionate fight
over something that is in fact fairly trivial. For example, a
passionate discussion about whether to use cloth or paper napkins at
Thanksgiving could be considered a "tempest in a tea pot" to some.

"The slightest breeze that
ruffles the surface of the water makes you bow your heads, while I, the
mighty Oak, stand upright and firm before the howling tempest."
* folly :eww:
[2019-04-27 Sat 09:40]

Folly is a noun that means "foolish or crazy behavior." It would be
folly to spend all night playing video games when you have a difficult
exam the next day.

Folly comes from the Old French word folie meaning "madness,
stupidity." It can describe the silly or nonsensical things you do,
like the folly of trying to rush across town in the middle of a
snowstorm. Or it can describe the trait that makes people act that
way: the folly of an inexperienced driver who doesn't know you can't
speed on snow-covered roads. Can you see the word fool in folly? Not a
coincidence.

Better to yield when it is folly to resist, than to resist stubbornly
and be destroyed.
* brook :eww:
[2019-04-27 Sat 09:42]

A brook is a small stream. On a hot day, you might enjoy wading in a
babbling brook. As a verb, brook is a rather stuffy word for "put up
with." The lord of the manor might say, "I will brook no trespassing
on my land."

Brook is tailor-made for talking about what you won't stand for—it's
always "brook no..." If you brook no criticism of your friend, it
means you won't let people speak ill of her. If you brook no brooks,
it means you've developed a bizarre stream-hating fetish and will
spend the rest of your days trying to stop their flow.

A Giant Oak stood near a brook in which grew some slender Reeds.
* yield :eww:
[2019-04-27 Sat 10:02]

Yield has two meanings that seem quite different: "an amount" or "to
give way." The yield of the recipe was twelve brownies. To avoid being
tripped, Mary was forced to yield to the children on her way to the
brownie plate.

While these meanings seem quite different, they both essentially mean
"to give." The recipe gives twelve brownies to those who follow it,
and Mary is giving up her right to go first. Yield can also mean the
rate of return on an investment. A bond yields an interest rate of 2%,
or gives an investor $2.00 for every $100 invested.

Better to yield when it is folly to resist, than to resist stubbornly
and be destroyed.
