-*- coding: utf-8 -*-

* forfeit :Duke:
[2019-06-10 Mon 20:00]

Forfeit means to lose or give up something, usually as a penalty. If
you don’t finish your homework and eat all your broccoli, you'll most
likely forfeit your right to watch TV before going to bed.

An adjective, noun, and verb all rolled into one, forfeit came into
existence around 1300 meaning “to lose by misconduct.” To forfeit is
to lose or give up something as punishment for making an error. A
forfeit is what is lost. You've probably heard of forfeiting a game or
match — like when you don't show up with enough players or pick one
too many fights with the opposing team.

Could the player who lost have made the winner forfeit if they
chose to play the hand differently?
* daunting :eww:
[2019-06-23 Sun 20:13]

Something daunting can scare you off. If you have a lot of studying to
do, it may seem like a daunting task. Good news is you can get through
it by working hard. Or weasel out of it by playing sick.

Often used in the phrases “daunting prospect” and “daunting task,”
daunting describes something that you are not looking forward to
doing. Having to fill out complicated tax forms every year is a
daunting task for many people. Once a daunting task is complete, you
no longer describe it as daunting, but instead can call it a job well
done, or at least another life experience survived.

We, too, can face up to
daunting challenges with an open spirit.
