-*- coding: utf-8 -*-


* wary                                                            :satellite:
[2019-02-06 Wed 13:14]

** Translate from English to Russian:                                 :drill:

 wary
*** --->
  осторожный

  adjective
   1. осторожный (careful, cautious, prudent, wary, discreet, watchful)
   2. настороженный (wary, alert, awake)
   3. подозрительный (suspicious, suspect, fishy, distrustful, dubious, wary)

  DEFINITION

  adjective
   1. feeling or showing caution about possible dangers or problems.
      "dogs that have been mistreated often remain very wary of strangers"

*** --->                                                              :drill:
  Describe yourself as [wary] if you don't quite trust someone or
  something and want to proceed with caution. Be [wary] of risky things
  like wild mushrooms and Internet deals!
*** --->                                                              :drill:
  You can trace [wary] through Old English back to Old High German giwar
  "aware, attentive." If you keep a [wary] eye on something, you are
  attentive for signs that it is becoming dangerous. Likewise, if you
  give someone a [wary] glance, your face conveys the suspicion and
  caution you feel. When you are [wary] of driving alone at night or
  making promises, you fear something bad might happen if you do these
  things.

*** --->                                                              :drill:
  “I mainly went to Iraq because I couldn’t walk around the Mall
  without being hypervigilant, [wary] of how people looked at me,
  totally on guard,” Steve recalls.
* chalk                                                           :satellite:
[2019-02-06 Wed 13:17]
** Translate from English to Russian:                                 :drill:

 chalk
*** --->
  мел

  noun
   1. мел (chalk, whiting, whitening)
   2. мелок (chalk)
   3. известь (lime, chalk, calx)
   4. кредит (credit, tick, trust, chalk, jawbone)
   5. углекислый кальций (chalk)
   6. пастель (pastel, crayon, chalk)
   7. долг (debt, duty, obligation, credit, trust, chalk)
   8. счет в игре (tally, chalk)
   9. шрам (scar, mark, seam, cicatrix, cicatrice, chalk)
  10. царапина (scratch, scrape, graze, excoriation, notch, chalk)

  verb
   1. рисовать мелом (chalk)
   2. удобрять известью (chalk, lime)
   3. натирать мелом (chalk)
   4. писать мелом (chalk)

  DEFINITION

  noun
   1. a soft white limestone (calcium carbonate) formed from the skeletal remains of sea creatures.
      "Calcium carbonate exists as whole mountain ranges of chalk , limestone, and marble."

  verb
   1. draw or write with chalk.
      "I have been drawing, painting and chalking since I was 2 years old."
   2. rub (something, especially a pool cue) with chalk.
      "Former world champion Steve Davis chalks his cue as the UK Snooker Championships got under way today at York's Barbican Centre."
   3. charge (drinks bought in a bar) to a person's account.

*** --->                                                              :drill:
  [Chalk] is a very soft kind of rock or limestone. While [chalk] is made
  of shells and the skeletons of sea creatures, it's usually found
  above sea level in pits or quarries.
*** --->                                                              :drill:
  [Chalk] is made of the element calcium carbonite, and it has
  agricultural uses, as well as showing up (in tiny amounts) in both
  toothpaste and antacids. The kind of [chalk] that you use for writing
  on a blackboard or decorating the sidewalk was originally made from
  calcium carbonite, but modern writing [chalk] is more often made of
  gypsum, a related form of calcium. [Chalk] comes from the Latin calx,
  "limestone," with the Greek root khalix, "small pebble."
*** --->                                                              :drill:
  Not everything [chalk]ed up to meditation’s magic actually stands up
  to rigorous tests.

* angst :satellite:
[2019-02-06 Wed 13:19]

** Translate from English to Russian:                                 :drill:

 angst
*** --->
  тоска

  noun
   1. беспокойство (concern, anxiety, worry, disturbance, trouble, unrest)
   2. страх (fear, awe, terror, fright, dread, anxiety)

  DEFINITION

  noun
   1. a feeling of deep anxiety or dread, typically an unfocused one about the human condition or the state of the world in general.
      "adolescent angst"

*** --->                                                              :drill:
  [Angst] is a feeling of anxiety and frustration that isn't specific.
  People often feel [angst] about the state of the world, or about the
  state of their homework.
*** --->                                                              :drill:
  [Angst] is anxiety that is mixed with frustration and negativity.
  [Angst] often doesn’t have a specific target: people feel [angst] in
  general. Teenagers are known for their [angst], which is shown when
  they act miserable about nothing in particular. Often, [angst] refers
  to philosophical displeasure with world events or personal freedom.
  An [angst]-filled person is dissatisfied and unhappy.
*** --->                                                              :drill:
  Yet mindfulness, part of an ancient meditation tradition, was not
  intended to be such a cure; this method was only recently adapted as
  a balm for our modern forms of [angst].
* overt :satellite:
[2019-02-07 Thu 09:04]
** Translate from English to Russian:                                 :drill:

 overt
*** --->
  неприкрытый

  adjective
   1. открытый (open, opened, uncovered, public, discovered, overt)
   2. явный (explicit, obvious, apparent, sheer, evident, overt)
   3. неприкрытый (uncovered, overt, barefaced, bald, unsheltered, nude)
   4. очевидный (evident, obvious, apparent, demonstrable, visible, overt)
   5. нескрываемый (unconcealed, overt, barefaced)

  DEFINITION

   1. done or shown openly; plainly or readily apparent, not secret or
      hidden. "an [overt] act of aggression"

*** --->                                                              :drill:
  [Overt] means open and done in plain sight. An [overt] attempt to get
  your teacher off-track might fail. Instead, try asking subtle
  questions about her kids, and she'll stay off topic all class.
*** --->                                                              :drill:
  If you speak French, remember that [overt] is the same as the French
  ouvert "open." If you don't speak French, give up all hope of ever
  learning this word. Just kidding –– forgive the [overt] attempt at
  humor. English speakers, here's your trick for remembering the
  difference between [overt] and c[overt]: [overt] = "open," c[overt] =
  "covered."
*** --->                                                              :drill:
  Time for plan “[overt] and obvious”.
* infatuation :satellite:
[[2019-02-07 Thu 09:07]]
** Translate from English to Russian:                                 :drill:

 infatuation
*** --->
  безрассудная страсть

  noun
   1. слепое увлечение (infatuation)
   2. безрассудная страсть (infatuation)
   3. страстная влюбленность (infatuation)

  DEFINITION

  noun
   1. an intense but short-lived passion or admiration for someone or
      something. "he had developed an [infatuation] with the girl"

*** --->                                                              :drill:
  [Infatuation] is falling in love with or becoming extremely interested
  in someone or something for a short time. If you have an [infatuation]
  with a particular singer, you probably listen to her on repeat all
  day long, at least this week.
*** --->                                                              :drill:
  If something infatuates you, it has caused you to become foolish. We
  say you have an [infatuation] when you express a crazy, extreme love
  of something––a person, a style, a band, anything. [Infatuation]s
  usually don’t last. Like incredibly intense crushes or the stomach
  flu, [infatuation]s come on strong and then get forgotten.
*** --->                                                              :drill:
  Fun quickly turned to [infatuation].
