-*- coding: utf-8 -*-


* nestle                                                            :Goleman:
[2019-03-01 Fri 09:18]

To nestle into something is to get snug, comfy, and warm in it. You
might nestle into your mother’s shoulder, or into a pile of blankets
on the couch.

People must think that birds live comfortable lives, because they
describe really cozy, safe, and comfortable places as nests: places to
nestle into. And it’s not just people and birds that nestle. A cottage
might be nestled into the crook of a hill, or a mouse nestled into a
pile of wood shavings.

Dalhousie nestles in the lower reaches of the Dhauladhar range, a
branch of the Himalayas that stretches into India’s Punjab and
Himachal Pradesh states.

* despair :Goleman:
[2019-03-01 Fri 09:19]

Despair is the feeling of not having any hope left. If you completely
forgot to study for your final exam in math, you might feel despair
when your teacher passes out the test.

Despair can also refer to someone or something that causes you to
worry or be sad. Unfortunately, some children are the despair of their
parents. The verb despair means to lose hope. Despair is from Latin
desperare "to be without hope," from the prefix de- "without" plus
sperare "to hope," from spes "hope."

In brain science, excitement revolved around the recent discovery of
neurotransmitters, the chemicals that send messages between neurons,
like the mood regulator serotonin—magic molecules that could pitch us
into ecstasy or despair.

* loom                                                              :Goleman:
[2019-03-01 Fri 09:21]

Loom has two distinct meanings. First, it's a tool for weaving.
Second, it means to appear or stand over someone in a threatening way.
The future loomed grim. The shadow loomed above us.

A common way we hear loom is in "loomed large," as in, "The specter of
getting fired loomed large in Amanda's imagination." Deriving from Low
German or Dutch, the word sounds smoky (or misty) and spectral: the
Antarctic ice-shelf loomed on the horizon as Shackleton's ship
approached the continent.

William James Hall looms over Cambridge as an architectural mistake, a
fifteen-story modernist white slab glaringly out of place amid the
surrounding Victorian homes and the low-lying brick-and-stone
buildings of the Harvard campus.

* meager :Goleman:
[2019-03-01 Fri 09:22]

Meager means small and often applies to portions. Your mother may only
allow you a meager serving of chocolate cake, and you may need to eat
a meager serving of veggies in order to deserve that dessert.

Meager doesn't mean adequate — it means not enough. People with a
limited supply of food may try to subsist on meager portions. People
who make a meager amount of money probably have a hard time making
rent. Meager and emaciated both derive from the Old French maigre. If
you can remember that you will look emaciated if your diet is meager,
you’ll use the word correctly.

Of the more than eight hundred articles Dan wrote at the Times, just a
meager handful had anything to do with meditation—even as we both
continued to attend meditation retreats on our own time.

* hallmark :Goleman:
[2019-03-01 Fri 09:23]

A hallmark is a distinctive characteristic of something or someone.
That can mean a literal symbol on the bottom of a piece of pottery, or
just a rock star's signature hair style.

Though some products have real hallmarks on them, indicating their
creator or origin, this word is usually used in a less literal way to
describe a unique attribute, a special style, or typical feature. A
basketball player could say that coming to practice early is a
hallmark of her success. A business could say their success is a
hallmark of their commitment to customers. And you could definitely
say Elvis' hip swivel was a hallmark of his performances.

This methodological sleight of hand, tacking an element of
consciousness studies on to an otherwise respectable, mainstream
research study, was to be a hallmark of Richie’s research for the next
decade or so, when his interest in meditation found little to no
support in the ethos of the time.

* sleight :Goleman:
[2019-03-01 Fri 09:23]

The noun sleight refers to being able to use your hands with ease,
especially when doing a trick. Sleight is often used in the phrase
"sleight of hand." If you are a good magician, you can make a coin
disappear with sleight of hand.

The noun sleight refers to cunning or cleverness, especially when used
to trick or deceitfully. You can use a sleight of mind to trick
yourself into believing that if you eat a box of cookies at dinnertime
it counts as dinner. The word sleight with its meaning as being sneaky
has a long history and comes from the Middle English word, sleghth,
which also meant cunning. Back then people would have pronounced the
"gh" even though today we don't.

This methodological sleight of hand, tacking an element of
consciousness studies on to an otherwise respectable, mainstream
research study, was to be a hallmark of Richie’s research for the next
decade or so, when his interest in meditation found little to no
support in the ethos of the time.

* satiety :Goleman:
[2019-03-01 Fri 09:24]

The noun satiety means a state of fullness. Eating a huge, delicious
meal will give you a satisfying feeling of satiety.

You don't often hear people using the word satiety in casual
conversation. It's more often a technical term used by nutrition
experts when they discuss the diet issues of populations or individual
patients. Satiety is a state of being completely full, but the related
adjective satiated is much more commonly used to describe someone who
has eaten enough. The Latin root of satiety is satis, which means
"enough."

His hypothesis was that because daydreams take us out of the present,
we become less sensitive to the body’s cues of satiety, and so
continue eating instead of stopping.

* visage                                                            :Goleman:
[2019-03-01 Fri 09:26]

Visage is a literary term for referring to someone's face or facial
features. You may notice that some face creams use the word visage to
try to sound fancier than they are.

A famous use of visage is in Shakespeare's Julius Caesar. Brutus says:
"O conspiracy/Shamest thou to show thy dangerous brow by night,/When
evils are most free? O, then by day/Where wilt thou find a cavern dark
enough/To mask thy monstrous visage?" Now there's a quote that will
help you remember the meaning of visage, and even give you nightmares.

Among the images Scotch-taped to the dashboard were Neem Karoli Baba,
as well as other saints he had heard about: an otherworldly image of
Nityananda, a radiantly smiling Ramana Maharshi, and the mustached,
mildly amused visage of Meher Baba with his slogan—later popularized
by singer Bobby McFerrin—“Don’t worry.

* ubiquitous :Goleman:
[2019-03-01 Fri 09:26]

It's everywhere! It's everywhere! When something seems like it's
present in all places at the same time, reach for the adjective
ubiquitous.

"Cities like Singapore aim to cloak themselves in ubiquitous, free
Wi-Fi in the next few years," The Wall Street Journal reported
recently — meaning that those savvy Singaporeans will find a wireless
connection everywhere they go. The word comes from the Latin ubique,
meaning — you guessed it — "everywhere." The usual pronunciation is
"yoo-BIK-wih-tihs," but Joseph Heller must have had the older variant
"ooh-BIK-wih-tihs" in mind when he wrote in Catch-22 that a character
"padded through the shadows fruitlessly like an ubiquitous spook."

If it’s one of the ubiquitous huge, lumbering Tata trucks, and the
driver happens to be Sikh, the pictures will feature Guru Nanak, the
revered founder of that religion.

* scant :Goleman:
[2019-03-01 Fri 09:27]

Scant is an adjective that means "a tiny amount," like your scant
attendance at practice this week that results in being benched from
the big game.

Scant is also a verb, that means "to supply sparingly" — don't scant
with the brownies, or I will keep asking for more. Scant also means
"to deal with inadequately or carelessly." When you scant the reports
on homelessness, they are so superficial on data that they don't
reflect the real problem. Scant comes from the Old Norse word skamt,
meaning "short, brief."

Just before coming to India, Dan had written an article—based on his
own first flings with meditation during college and on the scant
sources on the topic then available in English—that proposed the
existence of such a lasting ultra-benign mode of consciousness.

* equanimity :Goleman:
[2019-03-01 Fri 09:27]

If you take the news of your parakeet's death with equanimity, it
means you take it calmly without breaking down. Equanimity refers to
emotional calmness and balance in times of stress.

If equanimity reminds you of equal, that's because the words have a
lot in common. The noun equanimity was borrowed from Latin
aequanimitās, from aequanimus "even-tempered, fair," formed from
aequus "even, level, equal" plus animus "mind." The archaic phrase to
bear with equal mind means "to bear with a calm mind," and is a
translation from the Latin. The phrase a level mind also refers to
calmness. A near synonym is composure.

Spiritual literature throughout Eurasia converges in descriptions of
an internal liberation from everyday worry, fixation, self-focus,
ambivalence, and impulsiveness—one that manifests as freedom from
concerns with the self, equanimity no matter the difficulty, a keenly
alert “nowness,” and loving concern for all.

* ebb                                                               :Goleman:
[2019-03-01 Fri 09:28]

When something ebbs, it is declining, falling, or flowing away. The
best time to look for sea creatures in tidal pools is when the tide is
on the ebb — meaning it has receded from the shore.

Ebb is often used in the phrase, "ebb and flow," referring to the
cyclical changing of the tides from low to high and back to low again.
This sense of cyclical change can also be applied to other things. If
you want to make money investing, you have to weather the ebb and flow
of the stock market.

Such transformative moments mark the boundary of mindfulness, where we
observe the ordinary ebb and flow of the mind, with a further reach
where we gain insight into the mind’s nature.

* repute :Goleman:
[2019-03-01 Fri 09:29]

A person of great or fine repute is someone who's widely known and
highly respected. The word has a stuffy feel, so you're better off
describing a cellist as being of great repute than, say, a rapper or
comedian.

Like the words reputation and putative, repute comes from the Latin
word putare, which means "consider." And the re? Let's say that the
cellist Yo-Yo Ma is widely respected. That means a lot of people
consider him to be great. He's considered great not just once but
again (and again and again).

Munindra had studied vipassana (the Theravadan meditation and root
source of many now-popular forms of mindfulness) under Burmese masters
of great repute.

* ineffable :Goleman:
[2019-03-01 Fri 09:30]

When you find something hard to express or difficult to pin down, it's
ineffable. The feeling when you get a new puppy is ineffable — too
strange and wonderful to define.

You could call something "indescribable", but it wouldn't be quite the
same as calling it ineffable. An ineffable feeling, for example, has
an almost ghostly quality. You can almost touch it, but it slips away
just before you do. The bubbles in a glass of champagne have an
ineffable joy to them. The sense of sadness that you feel watching
certain TV commercials is often ineffable: you simply can't explain
it. You know that strange feeling of satisfaction you feel when you
learn a new word? That's an ineffable feeling.

There was something about his ineffable state of mind that Dan had
never sensed in anyone before meeting Maharaji.

* rapture :Goleman:
[2019-03-01 Fri 09:30]

Rapture is a feeling of emotional ecstasy so magical it's almost as if
you've been transported to some other world.

Coming to us from an old French word meaning "carried away," rapture
certainly involves getting swept off to Shangri-La. It's happiness so
extreme that you just about float to heaven, complete with big goofy
grin plastered to your face. Traditionally reserved for those feeling
spiritual ecstasy, rapture now extends to anyone feeling overwhelmed
by emotion — sparked by everything from a passionate kiss to scoring
an awesome dress on sale.

Maharaji seemed always to be absorbed in some state of ongoing quiet
rapture, and, paradoxically, at the same time was attentive to whoever
was with him.1 What struck Dan was how utterly at peace and how kind
Maharaji was.

* itinerant :Goleman:
[2019-03-01 Fri 09:31]

An itinerant is a person who moves from place to place, typically for
work, like the itinerant preacher who moves to a new community every
few years.

Itinerant is pronounced "eye-TIN-er-ant." It might remind you of
itinerary, the traveler's schedule that lists flights, hotel check-in
times, and other plans. It's no surprise that both words come from the
Latin word itinerare, meaning "to travel." Itinerant was first used in
the 16th century to describe circuit judges who traveled to faraway
courtrooms. Today, almost anyone can be an itinerant.

Like most sadhus, he was itinerant, unpredictably on the move.

* outright :Goleman:
[2019-03-01 Fri 09:32]

If you do something outright, you do it in a wholehearted,
unrestricted way. If you declare outright that you’re never eating
another cupcake, that’s the end of that. If you eat one anyway, you
told an outright lie.

If an event is cancelled outright, there's no question about it being
rescheduled, and if you buy a new car outright, you pay for it all at
once, instead of making monthly payments. Outright means direct and
immediate — whether it's an adverb or an adjective: "The child's
outright refusal to put on his shoes exasperated his babysitter." It
can also mean “right away.” If you step on a slug, you’ll probably
kill it outright. Ew.

That training focused on negatives: neurotic patterns, overpowering
burdensome feelings, and outright psychopathology.

* perch                                                             :Goleman:
[2019-03-01 Fri 09:33]

A perch is a temporary resting place. In the middle of climbing a
tree, you might find a good perch on a high branch. Bet some birds
will be perching there too.

Perch has many different meanings. A bird perch is a little stick it
can balance on, and the armrest of the couch can offer you a perch
during a party. It's also the name of a kind of fish with spiny fins.
And it's also an old measurement of 16.5 feet.

A wooden-plank tucket served as both bed and day couch, with a small
stand alongside for perching texts to read—and little else.

* amble                                                             :Goleman:
[2019-03-01 Fri 09:34]

To amble is to take a leisurely, pleasurable walk. Care to amble down
a pleasant country road instead of reading the rest of this word
description? That would certainly be understandable.

Amble is both a noun meaning "a stroll" and a verb meaning "to walk in
a slow, leisurely way." You might amble (or take an amble) over to the
snack table and grab a brownie. Amble comes from the Latin ambulare,
which means "to walk about," as in ambulatory. Weirdly enough, it was
once only used for horses or those on horseback. We use it for people
now, but it still retains some of its horse-like, country feel.

Through the mist that morning, Dan glimpsed an elderly Tibetan monk
amble by as he made his postdawn rounds, circumambulating the holy
site.

* spire :Goleman:
[2019-03-01 Fri 09:34]

A pointed cone shape on top of a building is called a spire,
especially when it rises from the roof of a church.

The part of a church roof that rises above a city skyline or a
village's rolling hills, pointing sharply up toward the sky, is its
spire. Many church spires have a cross at the very top. Other
buildings — religious or secular — can also have spires, though it's
most common to see one on a Christian church. The root of spire is the
Old English spir, "sprout, shoot, or stalk of grass."

Our story starts one early November morning in 1970, when the spire of
the stupa in Bodh Gaya was lost to view, enveloped in the ethereal
mist rising from the Niranjan River nearby.

* conjecture :EWW:
[2019-03-01 Fri 17:16]

Can you guess what conjecture means? It's a word to use when you are
not sure of something and have to "guess or surmise."

You can see how the word conjecture means that you create a theory or
opinion about something without basing it in fact because the original
definition of conjecture, from Old French, is "interpretation of signs
and omens." Since signs and omens are pretty subjective, it makes
sense that the word would then move to its current meaning. However,
even though it only seems like weather reports are conjectures, they
are actually based on evidence!

Let me be clear, this is not an article filled with theory or conjecture.
* cessation :EWW:
[2019-03-01 Fri 17:46]

Cessation is an end to something, such as the stopping of a bad habit,
like the cessation of smoking.

Cessation and cease sound alike and have similar meanings because they
both come from the Latin word cessare, which means "to delay, to
stop." The cessation can be permanent, such as when the protests
resulted in the cessation of the use of baby bunnies to test lipsticks
(forever ending the bunny torture); or temporary, such as the
cessation of the rain during the storm that let us run to the car
without getting wet (but rain, like sunshine, always comes back).

* tycoon :EWW:
[2019-03-01 Fri 17:49]

If you are meeting with someone who is considered a tycoon in his
industry, keep in mind that he is very successful and probably
accustomed to high-stakes negotiations.

Tycoon is derived from the Japanese word taikun, which means “great
lord or prince.” This noun made its way to the West in the mid-19th
century and originally referred to the shogun, or military leader, of
Japan. It was also used in reference to Abraham Lincoln to indicate
that he was an important man. Now, tycoons are generally understood to
be unusually successful heads of business or industry.

Arnold Schwarzenegger, the infamous bodybuilder, real estate tycoon, and
“Governator” of California stated that his one year of intense TM
(Transcendental Meditation) practice has created results that
Arnold Schwarnze 
* calisthenics :EWW:
[2019-03-01 Fri 17:50]

Calisthenics is exercise, like jumping jacks or pull-ups, that people
do to stay in shape or get in better shape.

Doing calisthenics usually involves simple movements, like stretching,
jumping, bending, and kicking, that don't involve a lot of equipment,
if any. Kids in gym class do calisthenics, and calisthenics are
helpful to many people, including athletes and people in the military.
The push-up is a famous example of calisthenics. Those limber folks on
cheerleading squads are masters of calisthenics. A little calisthenics
can be helpful in anyone's everyday routine as a way to build
endurance and stay healthy.

* berate :EWW:
[2019-03-01 Fri 18:10]

A strong verb for harshly cutting someone down with words is berate.
"He didn't just correct the cashier who gave him the wrong change, he
started to berate her, calling her names in front of the whole store."

When you berate someone it is more than just raising your voice at
them; it implies putting them down by insulting their character.
Berate comes from the 16th-century English and French for "to scold"
or "to blame." Often the anger behind the scolding seems over-the-top,
as in "When the young man behind the counter dropped the scoop of
vanilla, the manager berated him excessively by declaring him
worthless and weak."

The most unproductive thing you can do is to berate and belittle yourself
because you haven’t been as successful or productive as you want.
* belittle :EWW:
[2019-03-01 Fri 18:11]

To belittle means to put down, or to make another person feel as
though they aren't important. Saying mean things about another person
literally makes them feel "little."

To belittle someone is a cruel way of making someone else seem less
important than yourself. A candidate for office might belittle his
opponent by pointing out during a press conference that his fellow
candidate has an inferior intellect. Belittling doesn't have to come
in the form of verbal abuse. A manager who forces his administrative
assistant to scrub his office floor with a toothbrush belittles her as
well.

The most unproductive thing you can do is to berate and belittle yourself
because you haven’t been as successful or productive as you want.
* resurgence :EWW:
[2019-03-01 Fri 18:12]

Resurgence means coming back. Biker jackets are always cool––but in
certain decades they experience a resurgence, and suddenly you see
them everywhere.

There is nothing steady about resurgence––a surge is a sudden
gush––think dancing fountain or an oil well that's just been tapped.
Often, after a national tragedy, there is a resurgence in interest in
family values and getting back to basics. In prosperous times, there's
often a resurgence in sales of contemporary art.

There’s an age old practice in the middle of a resurgence…
* grind :EWW:
[2019-03-03 Sun 10:12]

If you like to grind your own coffee beans, it means you prefer to buy
whole beans, put them in an electric grinder, and pulverize them into
tiny bits before you brew your coffee.

When you grind something, you mill or crush it into smaller pieces,
the way you grind pepper or grind a grain into flour. Two things that
rub up against each other also grind together, which is what your
teeth do if you grind them in your sleep. Informally, grind also means
boring, tedious work, often in the sense of "grind away" or "the daily
grind." This sense of grind was invented in the 1800s as college
slang.

The constant grind to find the next dollar, to bed the next woman, to seal
the next deal, to land the next gig, to leave the legacy of which you can be
proud, to achieve, achieve, achieve!
* angst :EWW:
[2019-03-03 Sun 10:14]

Angst is a feeling of anxiety and frustration that isn't specific.
People often feel angst about the state of the world, or about the
state of their homework.

Angst is anxiety that is mixed with frustration and negativity. Angst
often doesn’t have a specific target: people feel angst in general.
Teenagers are known for their angst, which is shown when they act
miserable about nothing in particular. Often, angst refers to
philosophical displeasure with world events or personal freedom. An
angst-filled person is dissatisfied and unhappy.

The problem is, that all this responsibility and angst can overwhelm you and
create tremendous stress.
* hasten :EWW:
[2019-03-03 Sun 17:31]

The verb hasten means to move at a high speed. If you hasten to your
room, no one will know that you came in late.

Hasten comes from the word haste, which means "excessive speed or
urgency." The words hurry and hasten are synonyms. Hasten can also
mean "to make happen quickly," like when you open a window in the
kitchen when you are cooking to hasten the room's cooling down. Hasten
also means "to be quick," like when you hasten to tell everyone that
the rumor going around about you isn't true.

“There are different things one can do to establish and hasten the peace
process.
* chaste :EWW:
[2019-03-04 Mon 10:51]

If you belong to a chastity club, you might have to take a pledge to
be chaste until marriage. Chaste can be defined as "pure and
virtuous," but basically it means "not having sex."

This word is related to the Latin source of the verb castrate "to
remove a man's testicles," so it's definitely related to sex. And
chaste is from the same Latin source as the noun caste "a Hindu social
class separated from other classes." So the word chaste means no sex,
and the word caste means pure and virtuous.

And how do sex and meditation relate, especially since most people –
imagining the asceticism of chaste monks – separate the two concepts?
* primordial :EWW:
[2019-03-04 Mon 10:56]

Primordial, an adjective, describes something that has been around
forever, like cockroaches.

Primordial comes from the Latin words primus, meaning "first" and
ordiri, "to begin." So it is easy to see that this adjective means
"first of all, original." When something is primordial, it has existed
since the earliest time, like the primordial mud some scientists
believe was the source of all life on Earth. Remember that is it a
scientific term — don't call your teacher primordial just because
she's been teaching at your school since it opened.

Sam Harris, in his
2014 book “Waking Up: A Guide to Spirituality Without Religion
” recommends the Tibetan Buddhist practice of Dzogchen, aimed at attaining
the natural primordial state or natural condition for the sake of
liberation.

* amble :Goleman:
[2019-03-05 Tue 18:39]

To amble is to take a leisurely, pleasurable walk. Care to amble down
a pleasant country road instead of reading the rest of this word
description? That would certainly be understandable.

Amble is both a noun meaning "a stroll" and a verb meaning "to walk in
a slow, leisurely way." You might amble (or take an amble) over to the
snack table and grab a brownie. Amble comes from the Latin ambulare,
which means "to walk about," as in ambulatory. Weirdly enough, it was
once only used for horses or those on horseback. We use it for people
now, but it still retains some of its horse-like, country feel.

Through the mist that morning, Dan glimpsed an elderly Tibetan monk amble by as he
made his postdawn rounds, circumambulating the holy site.
* perching :Goleman:
[2019-03-05 Tue 18:39]

A perch is a temporary resting place. In the middle of climbing a
tree, you might find a good perch on a high branch. Bet some birds
will be perching there too.

Perch has many different meanings. A bird perch is a little stick it
can balance on, and the armrest of the couch can offer you a perch
during a party. It's also the name of a kind of fish with spiny fins.
And it's also an old measurement of 16.5 feet.

A wooden-plank tucket served as both bed and day couch, with a small stand
alongside for perching texts to read—and little else.
* outright :Goleman:
[2019-03-05 Tue 18:40]

If you do something outright, you do it in a wholehearted,
unrestricted way. If you declare outright that you’re never eating
another cupcake, that’s the end of that. If you eat one anyway, you
told an outright lie.

If an event is cancelled outright, there's no question about it being
rescheduled, and if you buy a new car outright, you pay for it all at
once, instead of making monthly payments. Outright means direct and
immediate — whether it's an adverb or an adjective: "The child's
outright refusal to put on his shoes exasperated his babysitter." It
can also mean “right away.” If you step on a slug, you’ll probably
kill it outright. Ew.

That training focused on negatives: neurotic patterns, overpowering
burdensome feelings, and outright psychopathology.
* burdensome :Goleman:
[2019-03-05 Tue 18:40]

Something that's burdensome is very difficult or tiring. It's better
to weed your garden regularly, rather than put it off until it becomes
an exhausting, burdensome task.

Some summer jobs are easy and relaxing, like your laid-back dog
walking business — other jobs are much more burdensome, like
babysitting a large family of kids or lifeguarding at a pool where
people keep nearly drowning. Something that's a burden, a physical
load or a duty that weighs heavily on you, is burdensome. The
Proto-Indo-European root means "to bear" or "to carry," and also "to
give birth."

That training focused on negatives: neurotic patterns, overpowering
burdensome feelings, and outright psychopathology.
* exuded :Goleman:
[2019-03-05 Tue 18:40]

To exude is to give off small amounts, usually of liquids or gases,
through small openings, such as pores. Think of how you exude sweat
after a workout.

The word exude is often used to describe sweating — the original Latin
root, sudāre means "to sweat." Still, we frequently use the word exude
to refer to anything that seems to ooze or pour forth from an object
or person. John F. Kennedy was said to exude confidence, while his
wife, Jackie, exuded class. But the verb can also have a negative
sense, as when we say a skunk exudes a foul smell.

Khunu, on the other hand, quietly exuded the better side of human nature.
* itinerant :Goleman:
[2019-03-05 Tue 18:41]

An itinerant is a person who moves from place to place, typically for
work, like the itinerant preacher who moves to a new community every
few years.

Itinerant is pronounced "eye-TIN-er-ant." It might remind you of
itinerary, the traveler's schedule that lists flights, hotel check-in
times, and other plans. It's no surprise that both words come from the
Latin word itinerare, meaning "to travel." Itinerant was first used in
the 16th century to describe circuit judges who traveled to faraway
courtrooms. Today, almost anyone can be an itinerant.

Like most sadhus, he was
itinerant, unpredictably on the move.
* rapture :Goleman:
[2019-03-05 Tue 18:42]

Rapture is a feeling of emotional ecstasy so magical it's almost as if
you've been transported to some other world.

Coming to us from an old French word meaning "carried away," rapture
certainly involves getting swept off to Shangri-La. It's happiness so
extreme that you just about float to heaven, complete with big goofy
grin plastered to your face. Traditionally reserved for those feeling
spiritual ecstasy, rapture now extends to anyone feeling overwhelmed
by emotion — sparked by everything from a passionate kiss to scoring
an awesome dress on sale.

Maharaji seemed always to be absorbed in some state of ongoing quiet rapture, and,
paradoxically, at the same time was attentive to whoever was with him.1 What struck
Dan was how utterly at peace and how kind Maharaji was.
* ineffable :Goleman:
[2019-03-05 Tue 18:42]

When you find something hard to express or difficult to pin down, it's
ineffable. The feeling when you get a new puppy is ineffable — too
strange and wonderful to define.

You could call something "indescribable", but it wouldn't be quite the
same as calling it ineffable. An ineffable feeling, for example, has
an almost ghostly quality. You can almost touch it, but it slips away
just before you do. The bubbles in a glass of champagne have an
ineffable joy to them. The sense of sadness that you feel watching
certain TV commercials is often ineffable: you simply can't explain
it. You know that strange feeling of satisfaction you feel when you
learn a new word? That's an ineffable feeling.

There was something about his ineffable state of mind that Dan had never sensed in
anyone before meeting Maharaji.
* repute :Goleman:
[2019-03-05 Tue 18:42]

A person of great or fine repute is someone who's widely known and
highly respected. The word has a stuffy feel, so you're better off
describing a cellist as being of great repute than, say, a rapper or
comedian.

Like the words reputation and putative, repute comes from the Latin
word putare, which means "consider." And the re? Let's say that the
cellist Yo-Yo Ma is widely respected. That means a lot of people
consider him to be great. He's considered great not just once but
again (and again and again).

Munindra had studied vipassana (the Theravadan meditation and root source of many
now-popular forms of mindfulness) under Burmese masters of great repute.

* premise :Goleman:
[2019-03-06 Wed 07:41]

A premise is what forms the basis of a theory or a plot. When you
called 911 on the guy in your back yard, it was on the premise that he
was a thief and not the meter-reader.

In logic, the premise is the basic statement upon whose truth an
argument is based. Criticize alternative theories by demonstrating
their false premises. In a more general sense, it's a basic assertion.
On the premise that people are generally good, you keep your doors
unlocked. Premise is also used more loosely for the starting point for
a plot. A movie's premise could be that two people trapped on a desert
island will inevitably fall in love.

The manuals shared the premise that filling one’s life with meditation and related
practices produces remarkable transformations of being.
* affirm :Goleman:
[2019-03-06 Wed 07:42]

To affirm something is to give it a big "YES" or to confirm that it is
true.

The verb affirm means to answer positively, but it has a more weighty
meaning in legal circles. People are asked to swear an oath or affirm
that they will tell the truth in a court of law. Lawyers may ask
people to affirm facts, and judges may affirm rulings. In these cases,
affirm means to verify or attest to the validity of something.

And the overlap in qualities
between Khunu, Maharaji, and a handful of other such beings Dan met in his travels
around India seemed to affirm just such possibilities.
* flings :Goleman:
[2019-03-06 Wed 07:44]

To fling is to throw something with force. You'll start a food fight
in the cafeteria if you fling your vegetables at the kid across the
table.

The act of throwing something recklessly or with force can also be
called a fling. Your mail sorting ritual might be putting bills in one
pile and personal letters in another, then giving junk mail a fling
into the recycling bin. A brief period of revelry or indulgence is
another kind of fling. You and your friends could plan a weekend fling
in New York, staying in a hotel, eating out, and shopping without
worrying about how much money you spend.

Just before coming to India, Dan had written an article—based on his own first flings
with meditation during college and on the scant sources on the topic then available
in English—that proposed the existence of such a lasting ultra-benign mode of
consciousness.6 The major states of consciousness, from the perspective of the
science of the day, were waking, sleeping, and dreaming—all of which had distinctive
brain wave signatures.
* benign :Goleman:
[2019-03-06 Wed 07:45]

Someone or something that is benign is gentle, kind, mild, or
unharmful: a benign soul wouldn't hurt a fly.

Benign describes a range of qualities, all of them positive. When
talking about a person, it means "gentle." In reference to weather or
climate, it means "mild." In some other contexts, it simply means "not
harmful"; you might speak of "a benign tumor" or "an environmentally
benign chemical." The word comes from a Latin root benignus meaning
"well born," but the implied meaning is "kind" or "pleasant" — it's
hard to get mad at someone who has a benign disposition.

Just before coming to India, Dan had written an article—based on his own first flings
with meditation during college and on the scant sources on the topic then available
in English—that proposed the existence of such a lasting ultra-benign mode of
consciousness.6 The major states of consciousness, from the perspective of the
science of the day, were waking, sleeping, and dreaming—all of which had distinctive
brain wave signatures.
* imposition :Goleman:
[2019-03-06 Wed 07:56]

Imposition means you force something — usually an unwanted burden — on
someone else. If your friends invite themselves over for dinner the
night before your big test, that's an imposition because you'll have
to cook instead of studying.

Imposition comes from the 14th century Old French word of the same
spelling, meaning "the levying of taxes, a tax, duty." Taxes are a
good way to remember the meaning of imposition. You never want to pay
taxes — but you have no choice but to pay. It can be the same for
other kinds of burdens: if something is an imposition, you don't want
to do it, but you likely will have to.

And the imposition of “noble
silence” from day one meant that Richie never really knew who else shared that
tent—his vague impression was that they were mostly Europeans.
* equanimity :Goleman:
[2019-03-06 Wed 07:59]

If you take the news of your parakeet's death with equanimity, it
means you take it calmly without breaking down. Equanimity refers to
emotional calmness and balance in times of stress.

If equanimity reminds you of equal, that's because the words have a
lot in common. The noun equanimity was borrowed from Latin
aequanimitās, from aequanimus "even-tempered, fair," formed from
aequus "even, level, equal" plus animus "mind." The archaic phrase to
bear with equal mind means "to bear with a calm mind," and is a
translation from the Latin. The phrase a level mind also refers to
calmness. A near synonym is composure.

Though Richie found his focus returning again and
again to the throbbing pain in that knee, he also started to glimpse a sense of
equanimity and well-being.

* ambivalence :Goleman:
[2019-03-07 Thu 08:11]

Someone who shows ambivalence about a person or thing has conflicting
feelings. If you love your mom but find her totally embarrassing, you
might feel ambivalent about having her give a presentation at your
school.

Originally a psychological term, ambivalence was borrowed from the
German word Ambivalenz, coined in 1910 by the Swiss psychologist Eugen
Bleuler. The German word was formed from the Latin prefix ambi- "in
two ways" plus Latin valentia "vigor, strength."

Spiritual literature throughout Eurasia converges in descriptions of an internal
liberation from everyday worry, fixation, self-focus, ambivalence, and
impulsiveness—one that manifests as freedom from concerns with the self, equanimity
no matter the difficulty, a keenly alert “nowness,” and loving concern for all.
* pervasive :Goleman:
[2019-03-07 Thu 08:15]

When something is pervasive, it's everywhere. Common things are
pervasive — like greed and cheap perfume.

Ever notice how certain trends seem to spread all over the place? When
something — like a hairstyle — is super-common, it's pervasive.
Pervasive things can't be escaped. Playing video games is pervasive
among kids. Talking about the weather is pervasive among adults.
Ideas, diseases, habits, and all sorts of things can be pervasive. If
you're sick of seeing something because you're seeing it again and
again, it must be pervasive.

Dan resolved that on his return to Harvard from India, he would make his
colleagues aware of what seemed an inner upgrade far more pervasive than any dreamed
of in our psychology.


* wending :Goleman:
[2019-03-07 Thu 08:20]

To wend means to choose a path and then walk that path. The path may
not always be the fastest route, but at least it should get you there.
Eventually.

It’s always good to have a goal, and that’s true with wending. You
know where you want to go, so you wend your way there. You’ll notice
that wend looks like the verb wind, and they both come from the same
Old English wendan, which means “to turn, depart.” When you wend, you
may take curvy, windy roads, a more scenic route, some detours and
side alleys, just for fun. But don’t wend too much or you’ll be late.

The high rode with him on the
bus down the mountains via roads wending through fields and villages with mud-walled,
thatch-roofed houses, on to the busier cities of the plains, and finally through the
throbbing, packed roads of Delhi.
* wane :Goleman:
[2019-03-07 Thu 08:22]

Things that wax and wane grow larger and smaller, like the moon.
Things that wane simply grow smaller. "My initial enthusiasm for
helping waned when I saw the pile of envelopes that needed licking."

You may have heard the expression "on the wane." It means a fad, or a
fashion, or a disease, that is on its way out the door. "The face mask
fad at school was on the wane as new reports of kids infected with a
dreaded new fly virus waned."

There Richie felt that high begin to wane as he and Susan spent a few days in the
bare-bones guesthouse they could afford on their grad student budget, venturing out
to Delhi’s cacophonous and crowded streets to have a tailor make some clothes and buy
souvenirs.
* terrain :Goleman:
[2019-03-07 Thu 08:27]

An ATV, or all-terrain vehicle, is useful for people who drive on lots
of different terrain, hence the name. Terrain is a noun used to talk
about the ground, when you're specifically interested in how it
appears or is shaped.

In times of war, you'll often hear the term "hostile terrain" used to
describe a region with lots of mountains, vast stretches of desert, or
impenetrable jungles. These are all areas of difficult terrain that
are hard to pass. Much of humankind's history can be traced by its
effort to alter the terrain. We've made mountains into meadows, rivers
into lakes, and prairies into roads, all to make the terrain more
livable for us. You could even go so far as to say that a person's
psyche is mysterious terrain.

And just where in the mind’s terrain had Richie been?
