-*- coding: utf-8 -*-

* thoracic :Titans:
[2019-04-03 Wed 14:13]

Thoracic is a medical word for things pertaining to the thorax area of
your body: your chest.

You’re likely to see the word thoracic in biology class. The thorax is
your chest: the area between your neck and abdomen. Therefore, this
area is the thoracic region, and that word can be used for issues
dealing with this area. Certain exercises are thoracic because they
strengthen your chest muscles. Your pectoral muscles are in the
thoracic area. Your heart is the most important part of the thoracic
area. If you have thoracic pains, you should see a doctor.

This can perform miracles for thoracic,
or mid-back, mobility, all while helping the hamstrings
in the pike position.
* compound :eww:
[2019-04-03 Wed 17:05]

If you compound a problem you add something to it to make it worse,
like say, putting water on a grease fire. Compound means to combine; a
compound is a combination or mixture of two or more things.

Compound has several specialized uses. A compound is either a mixture
or two or more things, or a heavily guarded residence, such as a drug
lord might have. In botany, a compound leaf consists of more than one
part. In linguistics, a compound is a word that consists of two or
more independent words. In chemistry, a compound is a substance
created when atoms from chemical elements join together.

Because you have the ability to compound
  more than older people.
* cheat :eww:
[2019-04-03 Wed 17:08]

To cheat is to use sneaky, unfair methods to get something you want.
No one's going to want to play with you if you always cheat at mini
golf.

Some people cheat at cards, and others cheat during math tests by
copying from the student beside them. In either case, they're trying
to succeed using underhanded tricks. You can refer to someone who does
this as a cheat as well. Cheat comes from the Old French escheat, a
legal term for the state taking someone's property when he or she dies
without heirs. This practice was resented, and it came to mean
"confiscate unfairly."

25 Husbands cheat on their wives.
