-*- coding: utf-8 -*-


* nestle                                                            :Goleman:
[2019-03-01 Fri 09:18]

To nestle into something is to get snug, comfy, and warm in it. You
might nestle into your mother’s shoulder, or into a pile of blankets
on the couch.

People must think that birds live comfortable lives, because they
describe really cozy, safe, and comfortable places as nests: places to
nestle into. And it’s not just people and birds that nestle. A cottage
might be nestled into the crook of a hill, or a mouse nestled into a
pile of wood shavings.

Dalhousie nestles in the lower reaches of the Dhauladhar range, a
branch of the Himalayas that stretches into India’s Punjab and
Himachal Pradesh states.

* despair :Goleman:
[2019-03-01 Fri 09:19]

Despair is the feeling of not having any hope left. If you completely
forgot to study for your final exam in math, you might feel despair
when your teacher passes out the test.

Despair can also refer to someone or something that causes you to
worry or be sad. Unfortunately, some children are the despair of their
parents. The verb despair means to lose hope. Despair is from Latin
desperare "to be without hope," from the prefix de- "without" plus
sperare "to hope," from spes "hope."

In brain science, excitement revolved around the recent discovery of
neurotransmitters, the chemicals that send messages between neurons,
like the mood regulator serotonin—magic molecules that could pitch us
into ecstasy or despair.

* loom                                                              :Goleman:
[2019-03-01 Fri 09:21]

Loom has two distinct meanings. First, it's a tool for weaving.
Second, it means to appear or stand over someone in a threatening way.
The future loomed grim. The shadow loomed above us.

A common way we hear loom is in "loomed large," as in, "The specter of
getting fired loomed large in Amanda's imagination." Deriving from Low
German or Dutch, the word sounds smoky (or misty) and spectral: the
Antarctic ice-shelf loomed on the horizon as Shackleton's ship
approached the continent.

William James Hall looms over Cambridge as an architectural mistake, a
fifteen-story modernist white slab glaringly out of place amid the
surrounding Victorian homes and the low-lying brick-and-stone
buildings of the Harvard campus.

* meager :Goleman:
[2019-03-01 Fri 09:22]

Meager means small and often applies to portions. Your mother may only
allow you a meager serving of chocolate cake, and you may need to eat
a meager serving of veggies in order to deserve that dessert.

Meager doesn't mean adequate — it means not enough. People with a
limited supply of food may try to subsist on meager portions. People
who make a meager amount of money probably have a hard time making
rent. Meager and emaciated both derive from the Old French maigre. If
you can remember that you will look emaciated if your diet is meager,
you’ll use the word correctly.

Of the more than eight hundred articles Dan wrote at the Times, just a
meager handful had anything to do with meditation—even as we both
continued to attend meditation retreats on our own time.

* hallmark :Goleman:
[2019-03-01 Fri 09:23]

A hallmark is a distinctive characteristic of something or someone.
That can mean a literal symbol on the bottom of a piece of pottery, or
just a rock star's signature hair style.

Though some products have real hallmarks on them, indicating their
creator or origin, this word is usually used in a less literal way to
describe a unique attribute, a special style, or typical feature. A
basketball player could say that coming to practice early is a
hallmark of her success. A business could say their success is a
hallmark of their commitment to customers. And you could definitely
say Elvis' hip swivel was a hallmark of his performances.

This methodological sleight of hand, tacking an element of
consciousness studies on to an otherwise respectable, mainstream
research study, was to be a hallmark of Richie’s research for the next
decade or so, when his interest in meditation found little to no
support in the ethos of the time.

* sleight :Goleman:
[2019-03-01 Fri 09:23]

The noun sleight refers to being able to use your hands with ease,
especially when doing a trick. Sleight is often used in the phrase
"sleight of hand." If you are a good magician, you can make a coin
disappear with sleight of hand.

The noun sleight refers to cunning or cleverness, especially when used
to trick or deceitfully. You can use a sleight of mind to trick
yourself into believing that if you eat a box of cookies at dinnertime
it counts as dinner. The word sleight with its meaning as being sneaky
has a long history and comes from the Middle English word, sleghth,
which also meant cunning. Back then people would have pronounced the
"gh" even though today we don't.

This methodological sleight of hand, tacking an element of
consciousness studies on to an otherwise respectable, mainstream
research study, was to be a hallmark of Richie’s research for the next
decade or so, when his interest in meditation found little to no
support in the ethos of the time.

* satiety :Goleman:
[2019-03-01 Fri 09:24]

The noun satiety means a state of fullness. Eating a huge, delicious
meal will give you a satisfying feeling of satiety.

You don't often hear people using the word satiety in casual
conversation. It's more often a technical term used by nutrition
experts when they discuss the diet issues of populations or individual
patients. Satiety is a state of being completely full, but the related
adjective satiated is much more commonly used to describe someone who
has eaten enough. The Latin root of satiety is satis, which means
"enough."

His hypothesis was that because daydreams take us out of the present,
we become less sensitive to the body’s cues of satiety, and so
continue eating instead of stopping.

* visage                                                            :Goleman:
[2019-03-01 Fri 09:26]

Visage is a literary term for referring to someone's face or facial
features. You may notice that some face creams use the word visage to
try to sound fancier than they are.

A famous use of visage is in Shakespeare's Julius Caesar. Brutus says:
"O conspiracy/Shamest thou to show thy dangerous brow by night,/When
evils are most free? O, then by day/Where wilt thou find a cavern dark
enough/To mask thy monstrous visage?" Now there's a quote that will
help you remember the meaning of visage, and even give you nightmares.

Among the images Scotch-taped to the dashboard were Neem Karoli Baba,
as well as other saints he had heard about: an otherworldly image of
Nityananda, a radiantly smiling Ramana Maharshi, and the mustached,
mildly amused visage of Meher Baba with his slogan—later popularized
by singer Bobby McFerrin—“Don’t worry.

* ubiquitous :Goleman:
[2019-03-01 Fri 09:26]

It's everywhere! It's everywhere! When something seems like it's
present in all places at the same time, reach for the adjective
ubiquitous.

"Cities like Singapore aim to cloak themselves in ubiquitous, free
Wi-Fi in the next few years," The Wall Street Journal reported
recently — meaning that those savvy Singaporeans will find a wireless
connection everywhere they go. The word comes from the Latin ubique,
meaning — you guessed it — "everywhere." The usual pronunciation is
"yoo-BIK-wih-tihs," but Joseph Heller must have had the older variant
"ooh-BIK-wih-tihs" in mind when he wrote in Catch-22 that a character
"padded through the shadows fruitlessly like an ubiquitous spook."

If it’s one of the ubiquitous huge, lumbering Tata trucks, and the
driver happens to be Sikh, the pictures will feature Guru Nanak, the
revered founder of that religion.

* scant :Goleman:
[2019-03-01 Fri 09:27]

Scant is an adjective that means "a tiny amount," like your scant
attendance at practice this week that results in being benched from
the big game.

Scant is also a verb, that means "to supply sparingly" — don't scant
with the brownies, or I will keep asking for more. Scant also means
"to deal with inadequately or carelessly." When you scant the reports
on homelessness, they are so superficial on data that they don't
reflect the real problem. Scant comes from the Old Norse word skamt,
meaning "short, brief."

Just before coming to India, Dan had written an article—based on his
own first flings with meditation during college and on the scant
sources on the topic then available in English—that proposed the
existence of such a lasting ultra-benign mode of consciousness.

* equanimity :Goleman:
[2019-03-01 Fri 09:27]

If you take the news of your parakeet's death with equanimity, it
means you take it calmly without breaking down. Equanimity refers to
emotional calmness and balance in times of stress.

If equanimity reminds you of equal, that's because the words have a
lot in common. The noun equanimity was borrowed from Latin
aequanimitās, from aequanimus "even-tempered, fair," formed from
aequus "even, level, equal" plus animus "mind." The archaic phrase to
bear with equal mind means "to bear with a calm mind," and is a
translation from the Latin. The phrase a level mind also refers to
calmness. A near synonym is composure.

Spiritual literature throughout Eurasia converges in descriptions of
an internal liberation from everyday worry, fixation, self-focus,
ambivalence, and impulsiveness—one that manifests as freedom from
concerns with the self, equanimity no matter the difficulty, a keenly
alert “nowness,” and loving concern for all.

* ebb                                                               :Goleman:
[2019-03-01 Fri 09:28]

When something ebbs, it is declining, falling, or flowing away. The
best time to look for sea creatures in tidal pools is when the tide is
on the ebb — meaning it has receded from the shore.

Ebb is often used in the phrase, "ebb and flow," referring to the
cyclical changing of the tides from low to high and back to low again.
This sense of cyclical change can also be applied to other things. If
you want to make money investing, you have to weather the ebb and flow
of the stock market.

Such transformative moments mark the boundary of mindfulness, where we
observe the ordinary ebb and flow of the mind, with a further reach
where we gain insight into the mind’s nature.

* repute :Goleman:
[2019-03-01 Fri 09:29]

A person of great or fine repute is someone who's widely known and
highly respected. The word has a stuffy feel, so you're better off
describing a cellist as being of great repute than, say, a rapper or
comedian.

Like the words reputation and putative, repute comes from the Latin
word putare, which means "consider." And the re? Let's say that the
cellist Yo-Yo Ma is widely respected. That means a lot of people
consider him to be great. He's considered great not just once but
again (and again and again).

Munindra had studied vipassana (the Theravadan meditation and root
source of many now-popular forms of mindfulness) under Burmese masters
of great repute.

* ineffable :Goleman:
[2019-03-01 Fri 09:30]

When you find something hard to express or difficult to pin down, it's
ineffable. The feeling when you get a new puppy is ineffable — too
strange and wonderful to define.

You could call something "indescribable", but it wouldn't be quite the
same as calling it ineffable. An ineffable feeling, for example, has
an almost ghostly quality. You can almost touch it, but it slips away
just before you do. The bubbles in a glass of champagne have an
ineffable joy to them. The sense of sadness that you feel watching
certain TV commercials is often ineffable: you simply can't explain
it. You know that strange feeling of satisfaction you feel when you
learn a new word? That's an ineffable feeling.

There was something about his ineffable state of mind that Dan had
never sensed in anyone before meeting Maharaji.

* rapture :Goleman:
[2019-03-01 Fri 09:30]

Rapture is a feeling of emotional ecstasy so magical it's almost as if
you've been transported to some other world.

Coming to us from an old French word meaning "carried away," rapture
certainly involves getting swept off to Shangri-La. It's happiness so
extreme that you just about float to heaven, complete with big goofy
grin plastered to your face. Traditionally reserved for those feeling
spiritual ecstasy, rapture now extends to anyone feeling overwhelmed
by emotion — sparked by everything from a passionate kiss to scoring
an awesome dress on sale.

Maharaji seemed always to be absorbed in some state of ongoing quiet
rapture, and, paradoxically, at the same time was attentive to whoever
was with him.1 What struck Dan was how utterly at peace and how kind
Maharaji was.

* itinerant :Goleman:
[2019-03-01 Fri 09:31]

An itinerant is a person who moves from place to place, typically for
work, like the itinerant preacher who moves to a new community every
few years.

Itinerant is pronounced "eye-TIN-er-ant." It might remind you of
itinerary, the traveler's schedule that lists flights, hotel check-in
times, and other plans. It's no surprise that both words come from the
Latin word itinerare, meaning "to travel." Itinerant was first used in
the 16th century to describe circuit judges who traveled to faraway
courtrooms. Today, almost anyone can be an itinerant.

Like most sadhus, he was itinerant, unpredictably on the move.

* outright :Goleman:
[2019-03-01 Fri 09:32]

If you do something outright, you do it in a wholehearted,
unrestricted way. If you declare outright that you’re never eating
another cupcake, that’s the end of that. If you eat one anyway, you
told an outright lie.

If an event is cancelled outright, there's no question about it being
rescheduled, and if you buy a new car outright, you pay for it all at
once, instead of making monthly payments. Outright means direct and
immediate — whether it's an adverb or an adjective: "The child's
outright refusal to put on his shoes exasperated his babysitter." It
can also mean “right away.” If you step on a slug, you’ll probably
kill it outright. Ew.

That training focused on negatives: neurotic patterns, overpowering
burdensome feelings, and outright psychopathology.

* perch                                                             :Goleman:
[2019-03-01 Fri 09:33]

A perch is a temporary resting place. In the middle of climbing a
tree, you might find a good perch on a high branch. Bet some birds
will be perching there too.

Perch has many different meanings. A bird perch is a little stick it
can balance on, and the armrest of the couch can offer you a perch
during a party. It's also the name of a kind of fish with spiny fins.
And it's also an old measurement of 16.5 feet.

A wooden-plank tucket served as both bed and day couch, with a small
stand alongside for perching texts to read—and little else.

* amble                                                             :Goleman:
[2019-03-01 Fri 09:34]

To amble is to take a leisurely, pleasurable walk. Care to amble down
a pleasant country road instead of reading the rest of this word
description? That would certainly be understandable.

Amble is both a noun meaning "a stroll" and a verb meaning "to walk in
a slow, leisurely way." You might amble (or take an amble) over to the
snack table and grab a brownie. Amble comes from the Latin ambulare,
which means "to walk about," as in ambulatory. Weirdly enough, it was
once only used for horses or those on horseback. We use it for people
now, but it still retains some of its horse-like, country feel.

Through the mist that morning, Dan glimpsed an elderly Tibetan monk
amble by as he made his postdawn rounds, circumambulating the holy
site.

* spire :Goleman:
[2019-03-01 Fri 09:34]

A pointed cone shape on top of a building is called a spire,
especially when it rises from the roof of a church.

The part of a church roof that rises above a city skyline or a
village's rolling hills, pointing sharply up toward the sky, is its
spire. Many church spires have a cross at the very top. Other
buildings — religious or secular — can also have spires, though it's
most common to see one on a Christian church. The root of spire is the
Old English spir, "sprout, shoot, or stalk of grass."

Our story starts one early November morning in 1970, when the spire of
the stupa in Bodh Gaya was lost to view, enveloped in the ethereal
mist rising from the Niranjan River nearby.
