-*- coding: utf-8 -*-


* faring :Angela:
[2020-10-01 Thu 12:52]

It's not fair that fare means three unrelated things. As a verb, it
means to proceed or get along, as in "Fare thee well." As a noun, it
can refer to the cost of travel ("Train fare is ten dollars") or to
food ("Tatertots are typical cafeteria fare").

To remember fare's different meanings, think of how, for people living
close to the bone, the question "How are you eating/faring?" is not so
different from "How are you getting along/faring?" And when you pay
plane fare and fly to France, you will most assuredly be eating French
fare once you get there.

In contrast, several of the students who
initially struggled were faring better than
I’d expected.

* mustered :Angela:
[2020-10-01 Thu 12:57]

Originally meaning "to gather soldiers," muster has been expanded to
include gathering up just about anything — you can muster up some
dinner, some friends, or even some ketchup, pickles and mustard.

Remember that muster used to involve getting reluctant soldiers out of
bed and into the field of battle — so it involves overcoming a certain
inertia. When you muster up the courage to face something, it's clear
that this is pretty scary for you.

Still,
when it came to learning seventh-grade math,
could it be that if they and I mustered
sufficient effort over time, they’d get to
where they needed?
* alternate :Angela:
[2020-10-01 Thu 12:58]

On a checkerboard, black squares alternate with white ones. As a verb,
alternate means to do something in turns. As a noun, an alternate is a
replacement.

While the noun and verb seem not to mean the same thing, think of it
this way: If you are brought on in a game to be someone's alternate,
you are there to take their turn. Alternate can also be used as an
adjective, meaning different or other. An alternate view of history is
one that looks at the past from an uncommon perspective. Pay attention
to the pronunciation of alternate: as a verb the end is pronounced
"-nāt" and as a noun or adjective "-nət."

Compared to my Lower East Side classroom,
Lowell was an alternate universe.
* aced :Angela:
[2020-10-01 Thu 13:02]

An ace is a playing card with the highest value in a deck. There are
four aces in a full deck of cards, each with a single heart, spade,
diamond, or club pictured on it.

Ace can also describe someone who's excellent at a particular skill:
"He's an ace at making homemade jam!" In tennis, an ace is a point
scored on a missed serve, and in golf it's a hole in one. When you ace
something, you do a great job: "Just get in there and ace that math
test today!" The earliest meaning was "one at dice," from the Latin
as, "a unit, one, or a whole."

He aced my quizzes and tests.
* rapt :Angela:
[2020-10-01 Thu 13:03]

To be rapt is to be carried away, caught up, or otherwise engrossed in
something. If a performer is really good or particularly mesmerizing,
the audience will be totally rapt.

Rapt developed from the Latin raptus, meaning to “seize, carry off."
So imagine something so interesting that it seizes your attention and
carries you off to another world. In fact, rapt is related to the word
rapture, which is an experience of extreme, other-worldly happiness.
So do your teacher a favor and give her your rapt attention during
math class.

In class, his
attention was rapt.
* wonder :Angela:
[2020-10-01 Thu 13:04]

When you wonder about something, you want to learn more about it. You
wonder why the car is making that noise so you ask the mechanic to
explain it.

Wonder comes from the Old English word wundor, which means "marvelous
thing, the object of astonishment." For example, the Taj Mahal is one
of the great wonders of the world, so beautiful and magical. But
wonders are all around us — anything that amazes and marvels is a
wonder, like high-definition television, the Internet, your mom's
homemade pizza — though we tend to forget this because we are used to
them.

I began to wonder what the heck this kid was
doing in my class.
* faintest :Angela:
[2020-10-02 Fri 09:28]

Something faint has no courage or vigor. If you suddenly round the
corner and see a gang of bullies staring straight at you, chances are
you'll feel faint.

Faint comes from the French feindre, for being cowardly or shirking
duties. We usually use it to mean without great strength. If you
faint, you pass out, from low blood supply to your brain. If you feel
faint, you feel weak. Faint also means dim or vague. If you're staring
out to sea, you might see the faint outline of an approaching ship. If
you really can't remember the answer to something, say you "haven't
the faintest idea."

Lines that I had imagined were funny did not produce the faintest
titter.
