-*- coding: utf-8 -*-


* despise :misc:
[2020-12-04 Fri 11:23]

If the mere thought of a burrito with sour cream in it turns your
stomach, you could say that you despise sour cream. You loathe it,
abhor it, hate it, and think it's vile.

Despise dates all the way back to the Latin word despicare, which
combines de "down" with specere "to look at." So if you look down your
nose at something, you could say you despise it. Nowadays the word
gets used a lot to describe things people really, really dislike, too.
Note how similar in meaning and spelling despise is to Sylvester the
cartoon cat's old favorite catchphrase despicable. Despicable means
something worth of being despised.

Kids didn't admire it or despise it.


* concealing :misc:
[2020-12-04 Fri 11:24]

If the other kids in junior high school envied me, they did a great
job of concealing it.

* weigh                                                                :misc:
[2020-12-04 Fri 11:26]

To weigh is all about judging; you could be seeing how heavy something
is or if it is a good choice. You could weigh the tomatoes you're
buying or weigh your options when applying to college.

To weigh something can mean to physically assess its weight — is it 3
pounds? 40 kilos? 22 grams? But it's no accident that the symbol for
justice is often a scale. That's because all of the facts of a case
need to be weighed or evaluated for justice to be served. And
hopefully the decision will be balanced and fair.

At the time I never tried to separate my wants and weigh them against
one another.

* piecemeal :misc:
[2020-12-08 Tue 09:48]

When you do something piecemeal, you're doing it little by little, but
in a seemingly random way, with no order or system.

Say you're a computer geek and someone calls you desperate to find out
how to fix a computer that's just crashed. If you respond piecemeal to
the caller's questions, she'll have to call you back many times to get
all the information she needs to get the computer up again. You may
like to talk to her, but she's not going to be impressed with your
computer smarts.

A popular recipe for new programming languages in the past 20 years
has been to take the C model of computing and add to it, piecemeal,
parts taken from the Lisp model, like runtime typing and garbage
collection.

* satiety :misc:
[2020-12-10 Thu 09:51]

The noun satiety means a state of fullness. Eating a huge, delicious
meal will give you a satisfying feeling of satiety.

You don't often hear people using the word satiety in casual
conversation. It's more often a technical term used by nutrition
experts when they discuss the diet issues of populations or individual
patients. Satiety is a state of being completely full, but the related
adjective satiated is much more commonly used to describe someone who
has eaten enough. The Latin root of satiety is satis, which means
"enough."

"The condition of man is already close to satiety and arrogance, and
there is danger of destruction of everything in existence."

