-*- coding: utf-8 -*-


* faring :Angela:
[2020-10-01 Thu 12:52]

It's not fair that fare means three unrelated things. As a verb, it
means to proceed or get along, as in "Fare thee well." As a noun, it
can refer to the cost of travel ("Train fare is ten dollars") or to
food ("Tatertots are typical cafeteria fare").

To remember fare's different meanings, think of how, for people living
close to the bone, the question "How are you eating/faring?" is not so
different from "How are you getting along/faring?" And when you pay
plane fare and fly to France, you will most assuredly be eating French
fare once you get there.

In contrast, several of the students who initially struggled were
faring better than I’d expected.

* muster                                                             :Angela:
[2020-10-01 Thu 12:57]

Originally meaning "to gather soldiers," muster has been expanded to
include gathering up just about anything — you can muster up some
dinner, some friends, or even some ketchup, pickles and mustard.

Remember that muster used to involve getting reluctant soldiers out of
bed and into the field of battle — so it involves overcoming a certain
inertia. When you muster up the courage to face something, it's clear
that this is pretty scary for you.

Still, when it came to learning seventh-grade math, could it be that
if they and I mustered sufficient effort over time, they’d get to
where they needed?

* alternate :Angela:
[2020-10-01 Thu 12:58]

On a checkerboard, black squares alternate with white ones. As a verb,
alternate means to do something in turns. As a noun, an alternate is a
replacement.

While the noun and verb seem not to mean the same thing, think of it
this way: If you are brought on in a game to be someone's alternate,
you are there to take their turn. Alternate can also be used as an
adjective, meaning different or other. An alternate view of history is
one that looks at the past from an uncommon perspective. Pay attention
to the pronunciation of alternate: as a verb the end is pronounced
"-nāt" and as a noun or adjective "-nət."

Compared to my Lower East Side classroom, Lowell was an alternate
universe.

* ace                                                                :Angela:
[2020-10-01 Thu 13:02]

An ace is a playing card with the highest value in a deck. There are
four aces in a full deck of cards, each with a single heart, spade,
diamond, or club pictured on it.

Ace can also describe someone who's excellent at a particular skill:
"He's an ace at making homemade jam!" In tennis, an ace is a point
scored on a missed serve, and in golf it's a hole in one. When you ace
something, you do a great job: "Just get in there and ace that math
test today!" The earliest meaning was "one at dice," from the Latin
as, "a unit, one, or a whole."

He aced my quizzes and tests.

* rapt :Angela:
[2020-10-01 Thu 13:03]

To be rapt is to be carried away, caught up, or otherwise engrossed in
something. If a performer is really good or particularly mesmerizing,
the audience will be totally rapt.

Rapt developed from the Latin raptus, meaning to “seize, carry off."
So imagine something so interesting that it seizes your attention and
carries you off to another world. In fact, rapt is related to the word
rapture, which is an experience of extreme, other-worldly happiness.
So do your teacher a favor and give her your rapt attention during
math class.

In class, his attention was rapt.

* wonder :Angela:
[2020-10-01 Thu 13:04]

When you wonder about something, you want to learn more about it. You
wonder why the car is making that noise so you ask the mechanic to
explain it.

Wonder comes from the Old English word wundor, which means "marvelous
thing, the object of astonishment." For example, the Taj Mahal is one
of the great wonders of the world, so beautiful and magical. But
wonders are all around us — anything that amazes and marvels is a
wonder, like high-definition television, the Internet, your mom's
homemade pizza — though we tend to forget this because we are used to
them.

I began to wonder what the heck this kid was doing in my class.

* faintest :Angela:
[2020-10-02 Fri 09:28]

Something faint has no courage or vigor. If you suddenly round the
corner and see a gang of bullies staring straight at you, chances are
you'll feel faint.

Faint comes from the French feindre, for being cowardly or shirking
duties. We usually use it to mean without great strength. If you
faint, you pass out, from low blood supply to your brain. If you feel
faint, you feel weak. Faint also means dim or vague. If you're staring
out to sea, you might see the faint outline of an approaching ship. If
you really can't remember the answer to something, say you "haven't
the faintest idea."

Lines that I had imagined were funny did not produce the faintest
titter.


* eminently :Angela:
[2020-10-06 Tue 11:16]


“For I have always maintained that, excepting fools, men did not
differ much in intellect, only in zeal and hard work; and I still
think this is an eminently important difference.”

* embellish :Angela:
[2020-10-06 Tue 11:48]

The word "bell" shows up in the middle of embellish, and bells are
something that decorate, or embellish something, making it more
attractive. If you embellish speech, though, it can get ugly if you
add a lot of details that aren't true.

Embellish often has the positive meaning of adding something to make
it more handsome or beautifully decorated. But, while adding bells to
something looks great at first, after a couple of hours of bells
ringing in the ears, what was meant to embellish and beautify can get
annoying. That's what can happen when you embellish by adding too many
false or exaggerated details to a story. Embellishing with true,
colorful details and vivid descriptions is what can really enhance the
beauty of a story.

And, if Chia’s research is right, that explanation would embellish her
accomplishments with more luster, more mystery, and more awe than the
alternative: “My god!

* lavish :Angela:
[2020-10-06 Tue 11:48]

Lavish means "generous and extravagant" as an adjective and "to give
generously" as a verb. If you don't like it when people lavish you
with attention, you might appreciate a lavish spread of excellent food
instead.

Lavish comes from the Old French lavache meaning "deluge, torrent,"
referring to rain. When you see it, think of a shower of good things
coming down on you as you never use lavish with something bad. Didn't
your parents lavish you with praise and love when you were small? With
lavish as an adjective, you can rephrase that question like this:
Didn't your parents offer you lavish praise and love when you were
little?

We begin to lavish extra attention on them and hold them to higher
expectations.

* prophecy :Angela:
[2020-10-06 Tue 11:49]

If a fortune teller made a prophecy that you were going to become a
billionaire in your lifetime, you'd be pretty excited. A prophecy is a
prediction, or a magical look into the future.

The noun prophecy means a magical foreknowledge, although it can also
be used in a playful way to describe an ordinary guess or prediction
about the future. So you could say, "Her prophecy for the weather next
week is incredibly depressing." The word comes from the Greek
prophetia — literally, "gift of interpreting the will of the gods".
The verb form is prophesy, or predict, and it's spelled with an s
instead of a c.

We expect them to excel, and that expectation becomes a
self-fulfilling prophecy.

* denizen                                                            :Angela:
[2020-10-06 Tue 11:52]

A denizen is an inhabitant or frequenter of a particular place: a
citizen of a country, a resident in a neighborhood, a maven of a
museum, a regular at a bar, or, even, a plant that is naturalized in a
region.

The noun denizen comes from words that mean “from” and “within” and is
related to “citizen.” Denizen can be used when talking about any
person or group of people that have a specific relationship with a
place. It was historically used to refer to foreigners who were either
naturalized or becoming citizens but now it is used much more
generally, as in: "The denizens of my aunt’s neighborhood all have
contracts with the same gardener."

It’s almost impossible, the journalist observed, to overestimate “the
premium placed within the McKinsey culture on analytic ability, or as
its denizens say, on being ‘bright.’ ”


* brainteaser                                                        :Angela:
[2020-10-06 Tue 11:52]


My interviews with McKinsey unfolded as most do, with a series of
brainteasers designed to test my analytic mettle.


* mettle :Angela:
[2020-10-06 Tue 11:53]

Mettle is the courage to carry on. If someone wants to "test your
mettle," they want to see if you have the heart to follow through when
the going gets tough.

Having the mettle to do something means you have guts. In short,
you're a pretty impressive person. If you have the intellectual mettle
to enter a political debate, not only do you know a lot about
politics, but you have the spunk to show it off. Metal and mettle were
once used interchangeably meaning a solid material like gold and the
"stuff a person is made of" — until everyone got confused and the
words went their separate ways.

My interviews with McKinsey unfolded as most do, with a series of
brainteasers designed to test my analytic mettle.

* thorny :Angela:
[2020-10-06 Tue 11:58]

Thorny things are either sharp and spiky, like a thorny briar patch,
or troublesome and difficult, like a thorny problem. Either way, they
can be painful!

When you tackle a thorny rosebush, you'll need thick gloves and sharp
pruning shears. When you tackle a thorny issue at work or at school,
on the other hand, you might need tools like diplomacy and
intelligence. This figurative meaning of thorny is useful for
describing especially complex or distressing issues, like a thorny
political problem that divides a nation.

For a very large sum of money per month, companies can hire a McKinsey
team to solve problems too thorny to be solved by the folks who are
already working on them.

* exorbitant :Angela:
[2020-10-06 Tue 12:00]

Use the adjective exorbitant when you want to describe something that
is really just too much! You'll often hear people griping about
exorbitant bank fees or exorbitant interest rates.

The adjective exorbitant was originally a legal term to describe a
case that was outside the bounds of the law. It comes from the Latin
roots — the prefix ex, meaning "out of," and orbita, meaning "wheel
track." You can see how the word now has come to be described as
something that has gone way off the beaten track, especially in terms
of price and value.

Why hire us, then, at such an exorbitant cost?

* culling :Angela:
[2020-10-06 Tue 12:01]

To cull means to select or gather. If you decide to make a literary
anthology, you must cull the best possible stories and then arrange
them in a pleasing manner.

When you use cull as a verb, the things you gather can be the good or
bad ones from a group. In your garden, you can cull the good
vegetables for dinner, or the rotten ones for the compost pile. In
fact, often no judgment of quality is made, as when you cull
information from the Internet for your next research project. The
sorting through will come later. However, if you use the word as a
noun, a cull is a selection of things you intend to reject, often in
reference to a group of animals. An outbreak of a disease such as
foot-and-mouth disease can cause authorities to order a cull of farm
pigs.

According to The War for Talent, the companies that excel are those
that aggressively promote the most talented employees while just as
aggressively culling the least talented.

* disparity                                                          :Angela:
[2020-10-06 Tue 12:01]

If there is a disparity between how great you think you are at tennis
and how you actually play, you are probably surprised by how often you
lose. Disparity is the condition of being unequal, and a disparity is
a noticeable difference.

Disparity usually refers to a difference that is unfair: economic
disparities exist among ethnic groups, there is a disparity between
what men and women earn in the same job. This noun derives from Latin
dispar "unequal." The opposite of disparity is parity, the condition
of being equal or the same.

In such companies, huge disparities in salary are not only justified
but desirable.

* debacle :Angela:
[2020-10-06 Tue 12:04]

Use debacle to refer to a fiasco, disaster, or great failure. If
several dogs run onto the field during the big baseball game, tripping
players and chewing up the bases, you can call the whole event a
debacle.

Debacle is sometimes used to describe a military defeat. If your army
retreats, that's one thing. If your army is outmaneuvered and ends up
huddled in a valley, surrounded on all sides by the enemy, forced to
sing 70s sitcom theme songs by their savage captors––that's a debacle.
Debacle comes from French débâcler "to clear," from Middle French
desbacler, from the prefix des- "completely, utterly" plus bacler "to
block."

You can’t blame the Enron debacle on a surfeit of IQ points.

* surfeit :Angela:
[2020-10-06 Tue 12:05]

Steve baked a surfeit of jam tarts. Steve ate a surfeit of jam tarts.
Steve surfeited himself on jam tarts. Whether surfeit is a noun or a
verb (as in "overabundance" or "gorge"), Steve is likely to end up
with a bellyache.

Overabundance, glut, gorge, and cloy: these are all synonyms for
surfeit, and they all convey a sense of too-much-ness, as does the Old
French root of the word — surfaire, "to overdo." When it is used in
reference to food or eating, surfeit tends to suggest indulging to the
point of sickness or disgust. In other contexts, though, the meaning
is not necessarily negative: "A surfeit of kindness," for example,
would hardly be a bad thing.

You can’t blame the Enron debacle on a surfeit of IQ points.

* smug :Angela:
[2020-10-06 Tue 12:22]

A smug person is self-satisfied. You can usually recognize someone who
is pleased with himself by his smug little smile and self-righteous
remarks.

Smug is the opposite of modest and unsure. In cartoons, the smug
character often walks around with his chest puffed out and his ego
leading the way. “Too much good fortune can make you smug and
unaware,” thought Rachel Field, the children’s author. What she means
is that successes are appreciated much more when they don't come so
often that you begin to feel entitled to them.

But Gladwell argues convincingly that demanding Enron employees prove
that they were smarter than everyone else inadvertently contributed to
a narcissistic culture, with an overrepresentation of employees who
were both incredibly smug and driven by deep insecurity to keep
showing off.


* ascendency :Angela:
[2020-10-06 Tue 12:23]

During the company’s ascendency, it was a brash and brilliant former
McKinsey consultant named Jeff Skilling who was Enron’s CEO.


* brash :Angela:
[2020-10-06 Tue 12:23]

Brash sounds like what it means: harsh, loud, and maybe a little rude.
Sometimes that’s good, like when you have a serious rash on your face
and give Aunt Nell a brash warning before she showers you with kisses.

There's nothing warm and fuzzy about brash. New Yorkers are sometimes
thought of as the poster children for brash behavior: they can be bold
and brazen. Pushy even. You might find brashness offensive, or maybe
you think it's refreshingly direct. If you're a cab driver, a tough
exterior might be useful, but being brash probably won’t advance your
career if you work in a hotel, where you’re supposed to be polite and
welcoming.

During the company’s ascendency, it was a brash and brilliant former
McKinsey consultant named Jeff Skilling who was Enron’s CEO.

* yank :Angela:
[2020-10-06 Tue 12:24]

To yank is to pull or move suddenly and sharply. You might reach for a
pan on the stove and then yank your hand away when you realize the
handle is hot.

Your little sister might yank at your arm to get your attention, while
a bully might yank your hair just to be mean. In both cases, they're
tugging abruptly, and you can call the pull itself a yank. Don't
confuse this noun with the yank that serves as a slightly offensive
nickname for Americans, or even more specifically, for New Englanders.
Dutch settlers in then New Amsterdam first used this word to insult
English colonists in Connecticut.

Inside Enron, this practice was known as “rank-and-yank.”

* inadvertently :Angela:
[2020-10-06 Tue 12:26]

Inadvertently is an adverb that means "without knowledge or intent,"
like when you inadvertently take someone else's coat from the coatroom
because it looks just like yours.

When you do something inadvertently, you don't mean to do it — you
might inadvertently step in a puddle, leave something important at
home, or hurt your friend's feelings. Some things that happen
inadvertently aren't mistakes, though: They happen by chance. For
example, if you just happen to park your car at the exact place that
blocks a bus from hitting a pedestrian, you've inadvertently saved a
life.

We inadvertently send the message that these other factors—including
grit—don’t matter as much as they really do.

* halting :Angela:
[2020-10-06 Tue 12:28]

The adjective halting is used to describe something that is
fragmentary or prone to interruptions. If you are overcome with
emotion at your wedding, you may choke out your vows in a halting
voice.

The adjective halting can describe something or someone with limping
or disabled legs or feet. If you have sprained your ankle and it's icy
out this winter, you will probably walk with a halting gait and walk
slowly and carefully. The word halting in this sense comes from the
Old English word lemphalt, which means "limping."

So halting was his academic progress, in fact, that he was placed in
special education classes.

* pivot :Angela:
[2020-10-06 Tue 12:29]

To pivot is to turn or rotate, like a hinge. Or a basketball player
pivoting back and forth on one foot to protect the ball.

When you're not talking about a type of swiveling movement, you can
use pivot to mean the one central thing that something depends upon.
The central pivot of your student government campaign, for example,
might be longer recess time. Or your plans to go to the beach this
weekend could pivot upon whether it rains, as the weather channel has
predicted, or gets surprisingly sunny.

Meeting a teacher who believed in his potential was a critical turning
point: a pivot from This is all you can do to Who knows what you can
do?

* hopeless :Angela:
[2020-10-06 Tue 12:30]

Someone who's hopeless believes that nothing good can happen — a happy
ending seems impossible. If you realize there's no way you'll pass
your biology class, it's a hopeless situation.

When you're struggling to learn a new language or tackling a difficult
task and feeling utterly discouraged, you can say that you're
hopeless. In other words, you have no hope that things will work out
the way you wish they would. A plan that's doomed to failure is also
hopeless, because there's no chance that it'll be successful: "His
scheme to save enough money to backpack through Europe is hopeless,
because he still hasn't found a job."

What Scott learned is that he wasn’t hopeless.

* trump :Angela:
[2020-10-06 Tue 12:33]

To trump is to outrank or defeat someone or something, often in a
highly public way. Safety might trump appearance when you're buying a
car, or your desires may trump your brother's when it comes to making
weekend plans.

In the card game bridge, the trump card is the most powerful card in a
particular round and defeats all the others — sort of like when your
needs or wishes trump someone else's. Originally trump implied a
deceptive form of victory involving cheating, but that sense has been
largely lost, though it's still around in the term trumped up, meaning
something that's been falsely made up. A politician may face trumped
up charges that could ruin his career.

“At what point,” Scott asked, “does achievement trump potential?”

* stellar :Angela:
[2020-10-06 Tue 12:33]

Meaning outstanding, wonderful, better than everything else, stellar
is a word of praise or excitement. Thomas Edison invented many things,
but his stellar achievement might have been the light bulb.

Stellar literally means "like a star." When it comes time for your
debut on Broadway, you will sure hope that the reviews say that you
delivered a stellar performance. You could also use stellar to talk
about actual stars, of course, or you could even blend the two: enjoy
the stellar beauty of your beloved under the stellar light of a
moonless night.

The rejection letter did not specify why, of course, but given his
stellar grades and extracurricular accomplishments, Scott could only
conclude that the impediment was his low SAT scores.

* impediment :Angela:
[2020-10-06 Tue 12:34]

An impediment is anything that slows or blocks progress. It can refer
to a physical thing, like a fallen tree in the road, or something more
intangible, like how your short stature is an impediment to becoming a
professional basketball player.

See the pedi in there? Pedi means "feet" and hundreds of years ago,
the word impediment referred to shackling one's feet. Now its use has
broadened considerably. An impediment is something that blocks or
impedes your path. There's no end to the things in your life that can
be considered impediments: your small bank account, your terrible
childhood, your country's economic malaise — any one of these could be
considered an impediment in your quest for happiness.

The rejection letter did not specify why, of course, but given his
stellar grades and extracurricular accomplishments, Scott could only
conclude that the impediment was his low SAT scores.

* deem                                                               :Angela:
[2020-10-06 Tue 12:35]

To deem is a verb that means to view as or judge. Your parents or boss
may deem something necessary that you don't, like coming home by
midnight or working late.

Deem comes from the Old English word, deman — meaning "act as a
judge." If you deem something, you essentially become the judge of
whether it has a characteristic. For example, if you deem your little
sister's jokes to be too ridiculous to listen to, you will probably
just walk away.

Like Scott, I took an IQ test early in my schooling and was deemed
insufficiently bright to benefit from gifted and talented classes.

* gird                                                                 :misc:
[2020-10-06 Tue 13:21]

"Gird your loins and prepare for battle!" Okay, no one says "gird your
loins" anymore (which basically means "tighten your pants"), but gird
is still used as a verb to mean "get ready for a dangerous situation."

To gird is to prepare for a military attack, but more loosely it
refers to readying oneself for any kind of confrontation. When you
gird for something, you are preparing for the worst-case scenario.
Gird can also mean "fasten something tightly with a belt or a band"
(as in "gird your loins"), or it can mean "to surround or encircle." A
field that is girded by trees is surrounded and encircled by trees.

Nevertheless, the government is girding for possible trouble.

* tapped :misc:
[2020-10-06 Tue 13:26]

He turned as someone tapped him on the shoulder.


* foul :misc:
[2020-10-06 Tue 13:36]

Foul is most commonly used as an adjective to describe a bad smell. As
a verb, foul usually means “make dirty or messy.” You might foul your
room to the point where it smells a bit foul.

In general, foul can be used as an adjective meaning "bad." Foul luck
is bad luck; a foul day is a bad day. As a verb, foul can mean "break
the rules." It’s used this way in sports, like when you commit a foul
on the basketball court. The phrase "foul play" can be used in the
context of sports or more generally, to indicate unfair or violent
behavior. Avoid confusing foul with fowl, which refers to birds,
especially chickens.

There was a foul smell coming up from the river.
