-*- coding: utf-8 -*-


* mow                                                                  :Farm:
[2021-05-03 Mon 08:03]

When you clip grass or other plants, you mow it. If you realize your
front lawn is taller than your dog, it might be time to mow it.

People with grassy lawns usually mow them throughout the growing
season, keeping them neatly trimmed and green. Farmers mow some food
crops and hay as well, when they're ready to be harvested, although
they use different tools to do it, including a curved blade called a
scythe. An old-fashioned meaning of mow is "a stack of hay," or "a
place where hay is stored."

As for the horses, they knew every inch of the field, and in fact
understood the business of mowing and raking far better than Jones and
his men had ever done.
* TODO grudge                                                           :sat:

* grudging :Farm:
[2021-05-03 Mon 08:06]

If you do something in a grudging manner (or grudgingly), you do it
with reluctance. Doing homework, paying taxes, and saying sorry are
all commonly done in a grudging manner.

"Grudging apology" and "grudging acceptance" are probably the two most
common uses of this word, which perhaps says something about our lack
of grace as a species. The word derives from the medieval French word
groucher, meaning "to murmur or mumble." A related word is grudge,
meaning a long-lasting sense of ill will dating to a previous
incident.

Every mouthful of food was an acute positive pleasure, now that it was
truly their own food, produced by themselves and for themselves, not
doled out to them by a grudging master.
* cockerel                                                             :Farm:
[2021-05-03 Mon 08:08]

He had made an arrangement with one of the cockerels to call him in
the mornings half an hour earlier than anyone else, and would put in
some volunteer labour at whatever seemed to be most needed, before the
regular day’s work began.
* obstinate :Farm:
[2021-05-03 Mon 08:11]

When someone is beyond stubborn, use the word obstinate instead: "You
obstinate old mule! Get out of my way!"

While stubborn may have positive or negative connotations, obstinate
is most definitely negative, because it implies a kind of hard-headed
determination not to change your mind even when it might be best to
rethink your position. "The obstinate Man does not hold Opinions, but
they hold him," wrote Samuel Butler way back in the seventeenth
century. The word still does the trick if you want a put-down for
someone you think is being a pig-headed fool or a stick in the mud.

He did his work in the same slow obstinate way as he had done it in
Jones’s time, never shirking and never volunteering for extra work
either.

* muddle :Gideon:
[2021-05-13 Thu 18:22]

A muddle is something that's messy and confusing. If your bedroom
looks like a hurricane just hit it, you might describe it as a muddle.

Oftentimes, we create the muddles in our lives, so it’s appropriate
that muddle can be used as a verb meaning “to mix up” or “confuse.”
Conveniently, though, the word muddle also describes a way out of
difficult situations; to muddle through a troublesome task is to
somehow figure it out, even if you don’t quite know what you’re
doing. It has been suggested that muddle comes from an old Dutch word
meaning “to make muddy.”

No problem there we might use that - native speakers might say it
like that but you could use another word a native speaker might use an
advanced words such as MUDDLE or IN A MUDDLE I was in such a muddle
this morning I tried to put my trousers on my head and I stepped into
my hat. So this is just one example so words that native speakers or
advanced users will use. 26 words that will help your speaking and
help your comprehension coming right up so stay tuned.
* budge :Gideon:
[2021-05-13 Thu 18:26]

To budge is to move — but just a little bit. People can budge
physically from where they're sitting or standing, and people can
budge from opinions and positions too.

If a bunch of your friends are sitting on a bench, and they're taking
up too much space for you to sit, you could ask them to budge, meaning
"Move over!" If you hate eggs and refuse to eat them no matter how
they're cooked, you are refusing to budge from your anti-egg
policy. Budge is most often used in a negative way, as in "I won't
budge" or "They wouldn't budge." This word often applies to stubborn
people. Since budge means to move just a tiny bit, what's the big
deal? Someone who accuses you of not budging is basically saying you
should.

B is for BUDGE and this is a synonym of to move or change position and
we especially use it when we want to talk about people changing their
minds or their decisions so for example "we asked them to improve
their offer but they wouldn't budge." "We tried to convince the
President to resign but he wouldn't budge." You can also use it to
mean move something heavy "hey! can you help me budge the sofa." So
there you are you can use BUDGE instead of MOVE.
* comeuppance :Gideon:
[2021-05-13 Thu 19:18]

Comeuppance describes a fate or punishment that's deserved, like when
an arrogant trash-talking quarterback fumbles the ball on the last
play and loses the game for his team.

Comeuppance began as a term that meant "present oneself for judgment
by a tribunal." That was in 1859. You can picture an accused person
approaching a judge, or "coming up" to the front of a
courtroom. Guilt, innocence — comeuppance can be either, and it can
apply to things beyond the justice system. Nowadays you'll most likely
hear this word describe something bad. If someone gets a deserved
punishment, you'd say "He got his comeuppance."

C is for COMEUPPANCE which means a punishment or fate that someone
deserves "He's a dishonest guy now he's free but one day he'll get his
comeuppance and end up in prison."
* TODO dodge                                                            :sat:
* dodgy :Gideon:
[2021-05-13 Thu 19:18]

A dodgy situation is risky and suspicious. A dodgy person is skilled
in lying and deceiving. Neither should be trusted.

When a person or situation is called dodgy, it's a clue that they
should be dodged if at all possible. A job might be dodgy because it's
illegal or dangerous. A shortcut might be dodgy if it could damage
your car. Running a marathon without preparation is very
dodgy. Similarly, a dodgy person is untrustworthy because they’re
evasive, cunning, sly, or just a flat-out liar.

D is for DODGY. DODGY is a great word because it has so many uses. It
can mean suspicious or bad quality or strange for example: "it's got a
dodgy haircut" "There's a dodgy man outside". "My position in this
company is a bit dodgy: I might lose my job any minute."
* incite :Gideon:
[2021-05-13 Thu 19:21]

To incite is to cause to act or occur. Violent words can incite
violent actions which, in turn, might incite public outcry against
violence.

Incite comes from a Latin verb meaning "to move into action" and if
you incite someone to do something, that is exactly how to describe
it. Usually it is used in a negative context. Radical and intolerant
teachings can incite hatred in those who listen. And if a government
restricts its people too much, it can incite unrest and rebellion in
the population.

by the way EGG ON doesn't have anything to do with eggs. It comes from
an old-world Old Norse world EGGJA (not sure I'm pronouncing that
right) which means to incite and it's been in the English language
since around 1200.
