-*- coding: utf-8 -*-


* irascible :misc:
[2021-03-01 Mon 15:49]

If you're irascible, you get angry easily — perhaps blowing up in rage
when someone brushes into you.

Irascible comes from the Latin root ira, which means "anger" or
"rage," the same root that gives us the word ire, "anger." The -sc in
the middle of irascible, means "becoming," so irascible doesn't just
mean you're angry — it's got action built into it. If you're looking
for a fight most of the time, then you're irascible — ready for the
spark that's going to set you on fire.

He begins to get more irascible and one day while his wife is out
he decides that he's going to collect all his childhood mementos the
memories of his youth and burn them as if he's trying to eradicate his
past.

* heir :misc:
[2021-03-03 Tue 17:07]

If your grandfather leaves his candy factory to you in his will, it
means you're the heir to the family candy business, and after your
grandfather dies, you will inherit the factory.

When you're named in a will or are legally entitled to inherit
something, you're an heir. You can be the heir to someone's money,
business, or title; in a monarchy, the king or queen's oldest son is
usually the heir to the throne. The word heir isn't pronounced like
"hair," but instead has a silent h and sounds like "air."

The bats weren't surprised you to know that some men blamed their own
midlife crises on the menopause, their wife's menopause as well so let
me go back to Reginald Perrin.

* wee                                                                  :misc:
[2021-03-03 Wed 12:54]

I had a flashback to when I was a wee girl.

* presbyterian                                                         :misc:
[2021-03-03 Wed 13:03]

Not even the one that says, "Did you know that Britney Spears is an
anagram for Presbyterian?".

* hourglass :misc:
[2021-03-03 Wed 13:10]

So it's kind of like an hourglass effect: when you're young you're
great at being yourself; when you're old you're great at being
yourself; but the bit in the middle is sometimes the most problematic.

* inferiority :misc:
[2021-03-03 Wed 13:11]

Inferiority is the quality of being worse than other things or people.

You know how some movies are terrible — inferior — compared to other
movies? You've noticed the inferiority of those films. Inferiority is
a quality possessed by people and things that are not as good as
others. To a king, the common people are defined by their inferiority.
Most people agree on the inferiority of a TV dinner to a home-cooked
meal. When someone feels like they are always worse off than others,
they have an inferiority complex. Inferiority is the opposite of
superiority.

If you've got an inferiority complex you suffer from an over-modest
self-regard.
* vantage :misc:
[2021-03-03 Wed 13:15]

A vantage is a really good place from which to survey a scene. You
might find that the roof of the house offers an excellent vantage from
which to drop water balloons on your kid brother’s head.

Vantage is a variation of advantage, but when we use vantage we’re
almost always talking about a position, not just general superiority.
If you had extra tutoring for a big exam, you would have the advantage
over a classmate who didn’t. But if your seat for the test allowed you
to see the answer sheet lying on the desk, well then you would have a
superior vantage — not that you would take advantage of that, of
course!

Interiority is entirely unrelative, so to operate from this position
of interiority, it's like a perceptual vantage point.

<<<<<<< HEAD
* whence :misc:
[2021-03-10 Wed 13:47]

Use the adverb whence as an old-fashioned way to say "from which" or
"from where." If you found a hundred dollar bill on the ground, you
might ask, "Whence did this money come?"

Not many people use the word whence these days — you're most likely to
hear it in a Shakespeare play or if a speaker is trying to sound
especially formal. Many people say, "from whence," as in "Throw that
fish back in the sea from whence it came," although strictly speaking
the "from" is unnecessary. Instead, a dinner party guest could ask,
"Whence came this delicious fish?"

That's from whence that creative spark of genius often comes.
* leftover :misc:
[2021-03-10 Wed 13:56]

This was one of those leftover Victorian ideals from England, where my
mother grew up.
* patchwork :misc:
[2021-03-11 Thu 12:09]

You don't develop an identity that's predicated on being a patchwork
personality.
* bifurcation :misc:
[2021-03-11 Thu 12:26]

Bifurcation is a process in which something splits in two.

Bifurcation is a word that sounds fancy but has a very simple meaning:
splitting or cutting in two. If a stream divides into two smaller
streams, that's a bifurcation. If you split a company into two
divisions, that's a bifurcation too. This word can also refer to the
exact spot where one thing splits into two. Since bi means two in many
words, such as bimonthly, that's a good reminder of what bifurcation
means.

Now, they're not always as well sign-posted as this one, but you know
those times in your life when you come to a bifurcation on the path,
and you sense that the potential for change is heightened.
* castigation :misc:
[2021-03-11 Thu 12:31]

If your coach yells at your team for sloppy play, her post-game speech
might be called a castigation. A castigation is a harsh verbal
reprimand.

No one likes to be on the receiving end of castigation. The word comes
from the Latin castigus which means "to make pure." Try to remember
during castigation that the castigator is, in their own misguided way,
trying to make you a better person. But that may be hard to think of
when someone is bawling you out.

Those are two extremes of your ego, and one of them is about
self-congratulation, and the other one is about self-castigation.
* toast :misc:
[2021-03-11 Thu 12:33]

What do you get when you heat a piece of bread long enough for it to
become golden-brown on both sides? Congratulations, you've made a
piece of toast!

To make toast, you simply toast bread, or heat it on a grill, in a
toaster, or in an oven. People put all kinds of things on toast, from
butter to jam to baked beans. Making or giving a toast is another
thing all together — this kind of toast is a brief speech given while
raising glasses and drinking together: "A toast to the birthday girl!"
And if you are so highly regarded in a particular area that you're
almost famous, you're "the toast of the town."

If you didn't have an ego you'd be toast.
* equanimity :misc:
[2021-03-11 Thu 12:34]

If you take the news of your parakeet's death with equanimity, it
means you take it calmly without breaking down. Equanimity refers to
emotional calmness and balance in times of stress.

If equanimity reminds you of equal, that's because the words have a
lot in common. The noun equanimity was borrowed from Latin
aequanimitās, from aequanimus "even-tempered, fair," formed from
aequus "even, level, equal" plus animus "mind." The archaic phrase to
bear with equal mind means "to bear with a calm mind," and is a
translation from the Latin. The phrase a level mind also refers to
calmness. A near synonym is composure.

That's what I would call equanimity, or equilibrium, and it's the kind
of state of mind that cannot be perfumed in any way by anything that
happens outside you.
* gorgeous :misc:
[2021-03-11 Thu 12:34]

Reach for the adjective gorgeous to describe jaw-droppingly beautiful,
magnificent people or things.

Good-looking is one thing. Beautiful is another. But reserve gorgeous
for the kind of looks that take your breath away. Some synonyms
include resplendent, dazzling, spectacular, and splendid. We know that
the word comes from Old French gorgias, meaning "elegant," but beyond
that it's hard to say for sure. It might have something to do with
fancy necklaces adorning the throat — la gorge in French. If calling
someone gorgeous isn't enough, pack some extra punch and say
"drop-dead gorgeous" instead.

When you look at the sky, and it's made a rainbow, and it's absolutely
gorgeous, there's no question that the sky's up there going, "Ha, did
you see my rainbow?"
* impermanence :misc:
[2021-03-11 Thu 12:35]

No, the sky just is, because the sky sees the impermanence of the
clouds, and the impermanence of the rainbows, and you have to develop
an inner state of mind that's as impervious to all the good shit and
bad shit that happens to you as the sky is to the weather.
* impervious                                                           :misc:
[2021-03-11 Thu 12:35]

An impervious surface is one that can't be penetrated. The word is
often followed by "to," as in "His steely personality made him
impervious to jokes about his awful haircut."

Most of the sentences you'll run across using impervious will be
followed by the word "to" and a noun. Things are often described as
being impervious to physical assaults like heat, water, bullets,
weather, and attack, but just as frequently to less tangible things,
like reason, criticism, pain, and pressure. The word comes from Latin:
in- + pervius, meaning "not letting things through." A common synonym
is impermeable.

No, the sky just is, because the sky sees the impermanence of the
clouds, and the impermanence of the rainbows, and you have to develop
an inner state of mind that's as impervious to all the good shit and
bad shit that happens to you as the sky is to the weather.
* lass                                                                 :misc:
[2021-03-11 Thu 13:18]

A lass is a girl. Your Scottish folk dance teacher might announce,
"Lads line up on that side, lasses on this side!"

Lass is an old-fashioned way to say "young girl," and it's more common
in parts of Britain than in the US. You're most likely to hear this
word in Scotland and the north of England, although lass is most
likely rooted in Scandinavian languages, like the Old Swedish løsk
kona, "unmarried woman," or the Old Norse löskr, "idle or weak."

One night my mother came up to get us and we were having pillow fights
she showed up and she said, "Right lasses, everybody's ready.
* disregard :misc:
[2021-03-11 Thu 13:20]

If everyone at the city council meeting tends to disregard anything
that's said by the eccentric gentleman with the parrot on his
shoulder, it means that no one pays any attention to him.

To disregard something is to ignore it, or to deliberately pay it no
attention. Sometimes the word is used to mean "neglect," implying that
something important is not being taken care of. Disregard can also be
a noun; you could complain that your family has a complete disregard
for your privacy when they gather outside your bedroom door to
eavesdrop on your telephone conversations.

But what it has left me with is spectacular disregard for where my
abilities end, and spectacular disregard for being the center of
attention.
* dial :misc:
[2021-03-11 Thu 13:25]

A dial is a circle that has a series of numbers or marks representing
numbers, like the dial of a clock face, a compass, or an old-fashioned
telephone. If you have a watch that glows in the dark, it's the dial
you can see even in a dark movie theater.

Old telephones and televisions both have dials — the first has numbers
from zero to nine in a circle, and the latter has a round disc for
changing channels. When you call someone, you can say that you dial
their number. In fact, people tend to use the word dial when they use
a phone, even if they're pushing buttons or tapping a touch screen.
The Latin root is dialis, "daily," and the earliest dial was a
sundial.

That's what happens when you dial in to the personal pronoun.

* counteract :misc:
[2021-03-12 Fri 17:48]

To counteract is to work against something in an attempt to reverse it
or cancel it out. You can try to counteract the neighbors' annoyance
at your loud music by bringing them some homemade brownies.

When you counteract something, you act counter — or in opposition — to
it. To counteract rising global temperatures, we have to reduce the
greenhouse gases flowing into the atmosphere. In order to counteract
the effects of a long sleepless night, you may want to drink a cup of
coffee or tea. And a good way to counteract a limited vocabulary is to
learn a new word every day!

The pigs had an even harder struggle to counteract the lies put about
by Moses, the tame raven.
* compartmentalized :misc:
[2021-03-12 Fri 17:56]

The world is very clean and compartmentalized.
* malleable :misc:
[2021-03-12 Fri 17:57]

A malleable metal is able to be pounded or pressed into various
shapes, and a malleable personality is capable of being changed or
trained. It's easier to learn when you're young and malleable.

Just as there are substances that are malleable, including clay and
some metals, there are also ductile metals that can be hammered out
into wire or thread; gold, silver, and platinum are examples. The
adjective malleable dates back to Middle English, from Old French,
from Medieval Latin malleābilis, from malleāre, "to hammer."

Software is at least as malleable as software requirements.
* derogatory :misc:
[2021-03-12 Fri 17:59]

Something that's derogatory is insulting or disrespectful. If you make
derogatory comments, that means you say things that are unflattering,
unkind, or demeaning.

Derogatory means about the same as insulting. Derogatory language is
meant to hurt, and it usually does. If you feel offended or insulted
by what someone says, the person probably said something derogatory.
Racial, sexist, and homophobic slurs are all derogatory. Insults that
mean someone is stupid or crazy are derogatory. Making a joke about
someone's mother is derogatory.

The label “jack-of-all-trades but master of none” is normally meant to
be derogatory, implying that the labelee lacks the focus to really
dive into a subject and master it.
* obsolete :misc:
[2021-03-12 Fri 18:31]

Use the adjective obsolete for something that is out of date. As the
Rolling Stones song "Out of Time" goes, "You're obsolete, my baby, my
poor old-fashioned baby."

Obsolete is from the Latin obsolescere "to fall into disuse," and it
is a very handy adjective for anything that is no longer used, from
words to factories to computer software to ways of thinking. Something
that is obsolete has usually been displaced by a newer, shinier
innovation. Compact discs made records and cassettes obsolete, and
then downloadable digital music files made compact discs obsolete.

What if it let its now-sexy technology become obsolete?
* frenzy :misc:
[2021-03-12 Fri 18:36]

In a frenzy, people go into a state of hysteria. Stay away from hungry
sharks or kids at a 16th birthday party when the pizza arrives if you
don't want to get caught up in a feeding frenzy.

Frenzy is derived from the Latin word phreneticus meaning "delirious."
If you're in a frenzy, you're certainly delirious. You can be in a
frenzy because something made you mad, happy, or even just hungry —
whatever makes you so crazy you're not thinking clearly. Frenzy is
often used when talking about a group of people (or animals) who get
worked up at the same time about the same thing, like sharks near
tasty fish or teenagers near pizza.

It may sound like some kind of rah-rah cheerleader crap, aimed at
whipping you into an idealistic frenzy, but it’s too important not to
mention.
* vibrant :misc:
[2021-03-12 Fri 18:37]

Vibrant colors are bright. Vibrant sounds are loud and resonant.
Vibrant people are ones you remember––they're bright and full of
personality.

Vibrant was originally intended to describe sounds. Sound waves
vibrate, and when they vibrate more rapidly, they sound brighter.
Singers and string instrument players increase this effect by shaking
the notes they play through a technique called vibrato that increases
the vibrancy of their sound.

I was expecting a vibrant after-work life of user group meetings and
deep, philosophical discussions on software development methodologies
and techniques.

* deafening :misc:
[2021-03-13 Sat 15:20]

When a sound is deafening, it's overwhelmingly loud. You may think
you're prepared after a flash of lightning, but the deafening sound of
thunder can still make you jump!

Deafening noises are so loud that they block out all other sounds. The
deafening siren from a passing ambulance easily overwhelms the quiet
conversation at your breakfast table, and a deafening roar inside a
music venue may make you regret your decision to see your favorite
band live. While deafen means "make deaf," deafening generally means
something closer to "making you temporarily unable to hear."

I would come home late after a deafening
evening at a bar and browse Gopher5 sites with
tutorials on programming until the sun came up.
* parlay :misc:
[2021-03-13 Sat 16:22]

If you parlay a bet, then you take the winnings from one bet and bet
it again on something else. You might have seen a gambler on TV parlay
her winnings into a huge fortune.

The verb parlay is often used to talk about gambling, but it can be
used more broadly to describe any initial stake that you turn into
something much larger. You might parlay your early investment in your
brother’s company into a high-paying leadership role. Parlay also has
a noun form that describes these kinds of transactions. You might
notice your Uncle Bob once again betting a baseball parlay.

Suf-fice it say that it all happened through
a perfect set of opportunities that I was able
parlay.
* dime :misc:
[2021-03-13 Sat 16:33]



nil

In business, ideas and even talent are a
dime a dozen.
* rabid :misc:
[2021-03-14 Sun 18:23]

Chances are that if the tail-wagging dog that just appeared on your
doorstep is also foaming at the mouth and chewing on your welcome mat,
it's rabid and you should back away slowly; no petting for this
infectious pup.

While you've likely heard it used to describe an animal infected by
rabies, rabid (derived from the Latin verb rabere "be mad, rave") can
also dramatically describe a person exhibiting fanatical, extremely
enthusiastic, or raging behavior. That guy who nearly knocked you off
the stands at the football game with his energetic fist-pumping and
then was later kicked out for getting into a fight with another fan?
Rabid on both counts.

In exchange, the
younger musicians are fiercely loyal, building up a
support and rabid fan network around their mentors.

* lodging :misc:
[2021-03-16 Tue 22:23]

Lodging is a name for the place you stay when you're not at home. Your
lodging could be a luxury hotel, a yurt in the woods, or a college
dormitory.

Your accommodations while traveling, going away to school, being an
exchange student, or doing temporary work are all called lodging or
lodgings. A room in a hotel is one kind of lodging, and a sleeping bag
on the floor of a tent is another kind. Lodging comes from lodge and
its earlier form, loggen, "to set up camp," from the Old French root
loge, "hut or cabin."

One afternoon, at low water, Mr. Isbister, a young artist lodging at
Boscastle, walked from that place to the picturesque cove of Pentargen,
desiring to examine the caves there.
* cove :misc:
[2021-03-16 Tue 22:23]

A cove is a small, sheltered part of an ocean's coast. A cove can be a
good place to put a sea kayak in the water and start paddling along
the shore.

A cove is basically the same thing as a "bay," but smaller. Coves are
protected coastal areas affected by tides and connected to the open
sea by a narrow entrance. The water in a cove is calmer than the open
ocean, and the cove itself is often oval or circular in shape. The
earliest meaning of cove was "den or cave," and later "small bay,"
probably influenced by a Scottish meaning of the word, "hollow place
in coastal rocks."

One afternoon, at low water, Mr. Isbister, a young artist lodging at
Boscastle, walked from that place to the picturesque cove of Pentargen,
desiring to examine the caves there.

* precipitous                                                          :misc:
[2021-03-16 Tue 22:24]

A sharp, steep drop — whether it's in a stock price, a roller coaster,
or a star's popularity — could be described as a precipitous one. Put
simply, precipitous means perilously steep.

Look closely and you'll spot most of the word precipice (a sheer,
almost vertical cliff) in precipitous. Now imagine how you'd feel
standing at the edge peering over, and you'll grasp the sense of
impending danger that precipitous tends to imply. Precipitous declines
in sales lead to bankruptcy. Precipitous mountainside hiking trails
are not for the acrophobic. It can describe an ascent, but precipitous
is most often used for things going literally or figuratively
downhill.

Halfway down the precipitous path to the Pentargen beach he came
suddenly upon a man sitting in an attitude of profound distress
beneath a projecting mass of rock. The hands of this man hung limply
over his knees, his eyes were red and staring before him, and his face
was wet with tears.
* disconcert                                                           :misc:
[2021-03-16 Tue 22:25]

A concert is a choreographed harmony of sounds but throw the prefix
"dis" in front it and you have the opposite: disconcerted — a word
used to describe someone whose composure has been disturbed or
unsettled.

Disconcerted is a combination of the French prefix des- which
indicates reversal and the word concerter meaning "bring together," so
something disconcerted is not brought together, but rather torn apart,
or thrown into confusion. If you are under a lot of stress or worried
about something, you're in a disconcerted or discombobulated state.
Take a breath. Relax a moment. Everything will be OK.

He glanced round at Isbister’s footfall. Both men were disconcerted,
Isbister the more so, and, to override the awkwardness of his
involuntary pause, he remarked, with an air of mature conviction, that
the weather was hot for the time of year.
* involuntary :misc:
[2021-03-16 Tue 22:26]

Involuntary describes a reflex or action done without conscious
control or will — like a blink, a sneeze, a yawn, or “the giggles.”

If you volunteered to do it, it’s voluntary. If you didn’t volunteer,
but you find yourself doing it anyway, it’s involuntary. This can go
for the involuntary hiccups you wrestle with on your blind date, as
well as the involuntary task you do at your manager’s
insistence. Involuntary gets a lot of blame, but something that is
involuntary is not necessarily bad: Breathing is involuntary, but you
would probably do it anyway if given the choice.

He glanced round at Isbister’s footfall. Both men were disconcerted,
Isbister the more so, and, to override the awkwardness of his
involuntary pause, he remarked, with an air of mature conviction, that
the weather was hot for the time of year.


* fervid :misc:
[2021-03-19 Fri 14:39]

Fervid can be used to describe something that is physically hot such
as “a fervid day in August,” but it is more often used to describe
heated emotions like anger, love, or desire.

When passions and emotions run wild, you should expect to hear some
fervid language thrown about. The adjective fervid comes from the
Latin fervidus which means “glowing, burning, or boiling.” It is often
used like the word fiery. You might hear a politician deliver a
“fervid speech” if he or she is particularly worked up over an issue.

A blazing sun upon a fierce August day was no greater rarity in southern France then, than
at any other time, before or since. Everything in Marseilles, and about Marseilles, had
stared at the fervid sky, and been stared at in return, until a staring habit had become
universal there. Strangers were stared out of countenance by staring white houses,
staring white walls, staring white streets, staring tracts of arid road, staring hills from
which verdure was burnt away. The only things to be seen not fixedly staring and glaring
were the vines drooping under their load of grapes. These did occasionally wink a little, as
the hot air barely moved their faint leaves.
* arid :misc:
[2021-03-19 Fri 14:40]

Arid is so dry that nothing will grow. Death Valley in California
features an arid climate, which is why it's called Death Valley and
not Life Valley.

Arid can also mean terribly dull or lifeless. A textbook about the
climate of Death Valley might be called arid if it's written in an
uninteresting way. Just like you wouldn't want to live in an arid
climate, you wouldn't want to sit through an arid performance of the
film-turned-musical, "Some Like it Hot."

A blazing sun upon a fierce August day was no greater rarity in southern France then, than
at any other time, before or since. Everything in Marseilles, and about Marseilles, had
stared at the fervid sky, and been stared at in return, until a staring habit had become
universal there. Strangers were stared out of countenance by staring white houses,
staring white walls, staring white streets, staring tracts of arid road, staring hills from
which verdure was burnt away. The only things to be seen not fixedly staring and glaring
were the vines drooping under their load of grapes. These did occasionally wink a little, as
the hot air barely moved their faint leaves.
* verdure :misc:
[2021-03-19 Fri 14:40]

Verdure is lush green foliage, the kind you'd find in a beautiful
garden, in a park, or in a forest.

Verdure is related to many words for the color green, and that's
exactly what it means: greenery, and a lot of it, in nature. This word
conveys a sense of life: think of a park where there's green
everywhere you see. That's verdure. A forest will have even more
verdure, and you could find verdure in someone's garden, if it's a big
one with a lot of plants. Verdure is so brightly alive that it makes
people feel good.

A blazing sun upon a fierce August day was no greater rarity in southern France then, than
at any other time, before or since. Everything in Marseilles, and about Marseilles, had
stared at the fervid sky, and been stared at in return, until a staring habit had become
universal there. Strangers were stared out of countenance by staring white houses,
staring white walls, staring white streets, staring tracts of arid road, staring hills from
which verdure was burnt away. The only things to be seen not fixedly staring and glaring
were the vines drooping under their load of grapes. These did occasionally wink a little, as
the hot air barely moved their faint leaves.
* abominable :misc:
[2021-03-19 Fri 14:42]

Abominable is as bad as it gets. So if the food at camp is abominable,
the campers might start to shout, "Ick! Ick! Your stew is making us
sick!"

Abominable is an adjective that should be used only when something is
exceptionally bad or threatening, like a gigantic furry snowman who is
terrorizing a village. Abominable is so absolutely awful that it
causes physical revulsion. So odious that it brings even the toughest
of tough guys to tears. Which is a bummer, because it's a surprisingly
fun word to say out loud.

There was no wind to make a ripple on the foul water within the harbour, or on the
beautiful sea without. The line of demarcation between the two colours, black and blue,
showed the point which the pure sea would not pass; but it lay as quiet as the abominable
pool, with which it never mixed. Boats without awnings were too hot to touch; ships
blistered at their moorings; the stones of the quays had not cooled, night or day, for
months. Hindoos, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen,
Genoese, Neapolitans, Venetians, Greeks, Turks, descendants from all the builders of
Babel, come to trade at Marseilles, sought the shade alike—taking refuge in any
hiding-place from a sea too intensely blue to be looked at, and a sky of purple, set with
one great flaming jewel of fire.
* awnings :misc:
[2021-03-19 Fri 14:42]

An awning is a covering that's like a roof or extends from a roof. If
you walk down a street with a lot of stores and it starts raining,
you'll probably try to stay under the awnings.

An awning provides shelter from rain and sun. You will often see
awnings extending over the entryways of businesses. Under an awning is
a place you can hang out as you collapse your umbrella on your way in,
or as you open your umbrella on your way out. Awnings are often made
from some type of canvas, and they protrude from the top of the store
or building, kind of like the brim of a cap, which has a similar
function.

There was no wind to make a ripple on the foul water within the harbour, or on the
beautiful sea without. The line of demarcation between the two colours, black and blue,
showed the point which the pure sea would not pass; but it lay as quiet as the abominable
pool, with which it never mixed. Boats without awnings were too hot to touch; ships
blistered at their moorings; the stones of the quays had not cooled, night or day, for
months. Hindoos, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen,
Genoese, Neapolitans, Venetians, Greeks, Turks, descendants from all the builders of
Babel, come to trade at Marseilles, sought the shade alike—taking refuge in any
hiding-place from a sea too intensely blue to be looked at, and a sky of purple, set with
one great flaming jewel of fire.
* quays :misc:
[2021-03-19 Fri 14:45]

You know that wharf on the bank of the river where all the boats park?
It's not an aqua parking lot. It's called a quay.

When you visit France and take a walk beside the wharves where boats
dock and unload passengers, you can say you've been strolling along
the quays of the Seine. The English spelling of this word was
originally key, and that's one way to pronounce it even today, an
alternative to "qway." Quay comes from the Old North French cai, "sand
bank."

There was no wind to make a ripple on the foul water within the harbour, or on the
beautiful sea without. The line of demarcation between the two colours, black and blue,
showed the point which the pure sea would not pass; but it lay as quiet as the abominable
pool, with which it never mixed. Boats without awnings were too hot to touch; ships
blistered at their moorings; the stones of the quays had not cooled, night or day, for
months. Hindoos, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen,
Genoese, Neapolitans, Venetians, Greeks, Turks, descendants from all the builders of
Babel, come to trade at Marseilles, sought the shade alike—taking refuge in any
hiding-place from a sea too intensely blue to be looked at, and a sky of purple, set with
one great flaming jewel of fire.

* compelling :misc:
[2021-03-22 Mon 21:41]

Compelling means attractive, or irresistible, or really, really
convincing. You know your argument for backpacking across Europe is
compelling when your parents not only let you go but also pay for all
your expenses.

To compel is to drive or force into action––you mom could compel you
to finish your homework by threatening not to feed you until it's
done. A compelling argument compels you to agree with its logic––it's
irresistible. That cute skirt you’ve been eyeing for months is now 75%
off? The price is a compelling reason to buy the skirt.

I’ve seen no compelling evidence.
* imperiling :misc:
[2021-03-22 Mon 21:44]

One thing can imperil another when it threatens to be harmful. For
example, an approaching storm with hurricane-force winds might imperil
the geraniums you just planted in your front yard.

A city's budget cuts might imperil a school's ability to hire new
teachers and buy supplies. The lack of money, in other words, is a
threat to schools. Likewise, a factory's refusal to reduce its
greenhouse gas emissions will imperil the air quality nearby — and
ultimately, imperil the health of the whole planet. The word imperil
comes from in and peril, meaning "danger."

To grasp why people bury themselves in debt you don’t need to study interest
rates; you need to study the history of greed, insecurity, and optimism. To
get why investors sell out at the bottom of a bear market you don’t need to
study the math of expected future returns; you need to think about the agony
of looking at your family and wondering if your investments are imperiling
their future.
* unaltered :misc:
[2021-03-22 Mon 21:45]

Unaltered means unchanged. If your parents’ poor opinion of your
boyfriend remains unaltered no matter how polite he is or how early he
brings you home, it may be because of his tattoos and motorcycle.

Unaltered is the opposite of altered, meaning to adjust or change. If
you meet a friend you haven't seen in ten years, and she looks the
same as you remember, you might exclaim at how unaltered she seems. If
you buy a pair of pants that need to be hemmed, you won't be able to
wear them in their unaltered state.

It was called The Psychology of Money, and over one million people have read
it. This book is a deeper dive into the topic. Some short passages from the
report appear unaltered in this book.
* compelling :misc:
[2021-03-22 Mon 21:47]

Compelling means attractive, or irresistible, or really, really
convincing. You know your argument for backpacking across Europe is
compelling when your parents not only let you go but also pay for all
your expenses.

To compel is to drive or force into action––you mom could compel you
to finish your homework by threatening not to feed you until it's
done. A compelling argument compels you to agree with its logic––it's
irresistible. That cute skirt you’ve been eyeing for months is now 75%
off? The price is a compelling reason to buy the skirt.

Everyone has their own unique experience with how the world works. And what
you’ve experienced is more compelling than what you learn second-hand. So all
of us—you, me, everyone—go through life anchored to a set of views about how
money works that vary wildly from person to person. What seems crazy to you
might make sense to me.
* basking :misc:
[2021-03-22 Mon 21:49]

To bask in something is to take it in, receive its warmth, or bathe in
its goodness. On the first warm day of the spring, you may bask in the
sunshine. When you win the Pulitzer, you bask in your own glory.

In Shakespeare’s “As You Like It,” Jaques says: “...As I do live by
food, I met a fool; Who laid him down and bask'd him in the sun,; And
rail'd on Lady Fortune in good terms...” That was most likely the
first time bask was used in the way that we most often use it now: to
bask is to warm yourself, either literally or figuratively, in the
glow of the sun, good fortune, happiness, or a job well done.

The stock broker who lost everything during the Great Depression experienced
something the tech worker basking in the glory of the late 1990s can’t
imagine.
* overarching :misc:
[2021-03-23 Tue 15:50]
=======

* maltreating :misc:
[2021-03-17 Wed 19:41]

If you maltreat someone, you treat them very badly. It's best not to
maltreat your little sister — she may grow up to be bigger, stronger,
and smarter than you. Also, it's just not very nice.

If you're cruel to someone on purpose, you maltreat them. You can also
say abuse or mistreat. If a big company maltreats its workers, they
may rebel by going on strike or joining a lawsuit. This verb combines
the prefix mal-, "badly, poorly, or wrong," and the word treat, from
the Latin root tractare, "manage or handle."

They had never seen animals behave like this before,
and this sudden uprising of creatures whom they were used to thrashing and
maltreating just as they chose, frightened them almost out of their wits.
* pasture :misc:
[2021-03-18 Thu 16:52]

If your cattle are feeling hungry, you should let them pasture, or
graze, in a grassy field known as a pasture. Pasture is both a noun
and a verb associated with grazing animals.

As a noun, a pasture is a field where animals such as horses and
cattle can graze, or feed. Pasture can also refer to the grasses or
other plants that grow in a pasture. As a verb, pasture means "to
graze" or "to release animals into a pasture for grazing." You also
might hear this word used in the idiom "Put out to pasture," which
means "to retire someone," usually because of old age.

But they woke at dawn as usual, and suddenly remembering the glorious thing
that had happened, they all raced out into the pasture together.
* knoll :misc:
[2021-03-18 Thu 16:55]

A knoll is a small hill or mound of earth, which makes a shady knoll a
perfect spot for a summer picnic.

The word knoll is associated with the tragic assassination of
President John F. Kennedy, who was shot in Dallas just as his
motorcade passed a grassy knoll. At first people thought that was
where the shots had come from, but it was later determined that the
assassin had fired from a nearby building instead. The "grassy knoll”
became symbolic of a theory that others had participated in the
assassination, and the term has become shorthand for any conspiracy
theory.

A little
way down the pasture there was a knoll that commanded a view of most of the
farm.
* spinney :misc:
[2021-03-18 Thu 16:57]


* morsels :misc:
[2021-03-23 Tue 15:52]

A morsel is a small amount of something, a tid-bit, a sliver, usually
of something of high-quality and much desired — like a morsel of dark
chocolate or a morsel of secret information.

Originally it referred specifically to food — a nineteenth century
lady might partake of a "dainty morsel" to eat, for example. More
often than not morsel now refers to non-food items: a morsel of good
taste; a morsel of common sense, and, of course, most popular of all,
a morsel of gossip. That's why, like all good food, all good gossip is
juicy.

My approach is based on the assumption that most books are a few
morsels of real insight wrapped in layers and layers of fluff. As
I read, I systematically unravel those layers of fluff and extract
only those insights, like a chemist distilling only the purest
compound.
* strands :misc:
[2021-03-23 Tue 16:49]

A single hair, a noodle, even a line of thought — any of these things
could be called a strand, a long thin length of something.

The noun strand describes things that are long and thin like a rope,
or a strand of spaghetti, hair, or thread. Strands are often twisted
together to form thicker, stronger things like cables. As a verb, the
meaning is very different: "to leave helpless," like unreliable cars
that strand their drivers, or a snowstorm that strands people at
airports.

* These branching connections were marked in red as close as
 possible to the point where the branch began
* Any of these branches could also have their own branches. The
 card for fellow German sociologist Jürgen Habermas, for example,
 was labeled 21/3d26g53
* As he read, he would create new cards, update or add comments to
 existing ones, create new branches from existing cards, and
 create new links between cards on different “strands”
* daring :misc:
[2021-03-24 Wed 17:09]

To be daring is to be bold, adventurous, and a little nervy. It’s a
quality possessed by people who tend to take risks. If someone says,
“I dare you,” and you always do, you’re a daring person.

If you're daring, you dare to do things that are risky and even
dangerous. A daring mountain climber goes for the top of Mount
Everest, and a daring policeman enters the scariest houses to catch a
crook. In comics and movies, superheroes are daring. Even quitting
your job to start your own business is daring. The seafarers who first
traveled across the globe were daring. Daring people are brave, and
daring adventures are pretty exciting.

About twenty years ago Jobs and Wozniak, the founders of Apple,
 came up with the very strange idea of selling information
 processing machines for use in the home. The business took off, and
 its founders made a lot of money and received the credit they
 deserved for being daring visionaries. But around the same time,
 Bill Gates and Paul Allen came up with an idea even stranger and
 more fantastical: selling computer operating systems. This was much
 weirder than the idea of Jobs and Wozniak. A computer at least had
 some sort of physical reality to it. It came in a box, you could
 open it up and plug it in and watch lights blink. An operating
 system had no tangible incarnation at all. It arrived on a disk, of
 course, but the disk was, in effect, nothing more than the box that
 the OS came in. The product itself was a very long string of ones
 and zeroes that, when properly installed and coddled, gave you the
 ability to manipulate other very long strings of ones and zeroes.
* tangible :misc:
[2021-03-24 Wed 17:10]

When you can touch something, it's tangible: "I need tangible proof
that aliens exist — I want to shake their little green hands!"

Tangible is from Latin tangere, "to touch," and it simply means
something that can be touched or felt, though it can be used in
metaphorical senses: tangible assets have a value that can be
precisely measured, and tangible grief can be clearly sensed by an
onlooker. So you might not need to physically touch something for it
to be tangible, but it has to be grounded in the real world of facts:
"Has the teen pop star demonstrated any tangible ability to sing?"

About twenty years ago Jobs and Wozniak, the founders of Apple,
 came up with the very strange idea of selling information
 processing machines for use in the home. The business took off, and
 its founders made a lot of money and received the credit they
 deserved for being daring visionaries. But around the same time,
 Bill Gates and Paul Allen came up with an idea even stranger and
 more fantastical: selling computer operating systems. This was much
 weirder than the idea of Jobs and Wozniak. A computer at least had
 some sort of physical reality to it. It came in a box, you could
 open it up and plug it in and watch lights blink. An operating
 system had no tangible incarnation at all. It arrived on a disk, of
 course, but the disk was, in effect, nothing more than the box that
 the OS came in. The product itself was a very long string of ones
 and zeroes that, when properly installed and coddled, gave you the
 ability to manipulate other very long strings of ones and zeroes.
* coddled :misc:
[2021-03-24 Wed 17:11]

While it is okay for parents to coddle, spoil, or pamper a young
child, it’s a little unnerving when parents coddle, or pamper adult
children. And downright weird when adult children wear Pampers.

Coddle is an old word. Originally, it meant to cook gently in water
that is near boiling, as in coddling an egg. It most likely gained its
association with pampering and taking care of someone via a drink made
for invalids that was prepared by coddling. “Mollycoddle,” a synonym
for coddle, originally meant a person who coddles himself, or an
effeminate man.

About twenty years ago Jobs and Wozniak, the founders of Apple,
 came up with the very strange idea of selling information
 processing machines for use in the home. The business took off, and
 its founders made a lot of money and received the credit they
 deserved for being daring visionaries. But around the same time,
 Bill Gates and Paul Allen came up with an idea even stranger and
 more fantastical: selling computer operating systems. This was much
 weirder than the idea of Jobs and Wozniak. A computer at least had
 some sort of physical reality to it. It came in a box, you could
 open it up and plug it in and watch lights blink. An operating
 system had no tangible incarnation at all. It arrived on a disk, of
 course, but the disk was, in effect, nothing more than the box that
 the OS came in. The product itself was a very long string of ones
 and zeroes that, when properly installed and coddled, gave you the
 ability to manipulate other very long strings of ones and zeroes.
* arcane :misc:
[2021-03-24 Wed 17:12]

Something arcane is understood or known by only a few people. Almost
everyone knows the basics of baseball, but only an elite few possess
the arcane knowledge of its history that marks the true fan.

A near synonym is esoteric, as in "relating to remote information or
knowledge." Experts in academic fields often show off the depth of
their knowledge by mentioning some arcane and esoteric fact as if it
was common for everyone to know. The origin of arcane is Latin
arcānus, "secret, closed," from arca, "a chest, box." Arcana (singular
arcanum) are pieces of mysterious knowledge or information.

Even those few who actually understood what a computer operating
 system was were apt to think of it as a fantastically arcane
 engineering prodigy, like a breeder reactor or a U-2 spy plane, and
 not something that could ever be (in the parlance of high-tech)
 "productized."
* hazy :misc:
[2021-03-24 Wed 17:44]

If it's hazy, it's definitely not clear — there's fog, mist, smoke or
something like that blurring the view.

Hazy usually describes a sky that's fogged over or otherwise
unclear. But if you're feeling a little uncertain or unsure about
something, with only a bleary outline in your mind, you could say
you're a bit hazy on the details.

Yet now the company that Gates and Allen founded is selling
 operating systems like Gillette sells razor blades. New releases of
 operating systems are launched as if they were Hollywood
 blockbusters, with celebrity endorsements, talk show appearances,
 and world tours. The market for them is vast enough that people
 worry about whether it has been monopolized by one company. Even
 the least technically-minded people in our society now have at
 least a hazy idea of what operating systems do; what is more, they
 have strong opinions about their relative merits. It is commonly
 understood, even by technically unsophisticated computer users,
 that if you have a piece of software that works on your Macintosh,
 and you move it over onto a Windows machine, it will not run. That
 this would, in fact, be a laughable and idiotic mistake, like
 nailing horseshoes to the tires of a Buick.
* balky :misc:
[2021-03-24 Wed 17:50]

Then they made a tour
of inspection of the whole farm and surveyed with speechless admiration the
ploughland, the hayfield, the orchard, the pool, the spinney.
* tiptoed :misc:
[2021-03-18 Thu 16:58]

To tiptoe is to walk with your weight on your toes, moving quietly. If
you're late to your yoga class and everyone's lying still with their
eyes closed, you may want to tiptoe to your mat.

You can also use tiptoe as a noun or an adjective: "She had to stand
on her tiptoes to reach the cabinet where the cookies are kept."
Figuratively, you tiptoe when you avoid a certain topic: "There's no
need to tiptoe around the subject of money—I don't mind talking about
it." The variation tippy toes dates from the early 1800s.

They tiptoed from room to
room, afraid to speak above a whisper and gazing with a kind of awe at the
unbelievable luxury, at the beds with their feather mattresses, the
lookingglasses, the horsehair sofa, the Brussels carpet, the lithograph of
Queen Victoria over the drawing-room mantelpiece.
* mantelpiece :misc:
[2021-03-18 Thu 16:59]

A mantelpiece is a frame around a fireplace, or a shelf above it. When
families celebrate Christmas, they often hang stockings from the
mantelpiece on Christmas Eve.

If you have a fireplace, you probably have a mantelpiece, or a mantel.
While some mantelpieces are elaborate and decorative, made of heavy
stone like granite or marble, and sometimes extending far up the wall
above the fireplace. Others are very simple, made of a plain wooden
shelf. The original, medieval mantelpieces were hoods that caught
smoke from the fire.

They tiptoed from room to
room, afraid to speak above a whisper and gazing with a kind of awe at the
unbelievable luxury, at the beds with their feather mattresses, the
lookingglasses, the horsehair sofa, the Brussels carpet, the lithograph of
Queen Victoria over the drawing-room mantelpiece.
* scullery :misc:
[2021-03-18 Thu 17:01]

You're most likely to see the word scullery in an English novel, since
it's a small room off the kitchen, usually in a very old, very British
home.

In the old days, maids cleaned dishes and utensils — and sometimes
clothing — in the scullery, out of sight of their wealthy employers.
In some parts of Britain, the word scullery is still used to mean
"kitchen," although few people would claim to employ a "scullery
maid," or a low-ranking member of a household staff. The root of the
word is in doubt, but it probably comes from the Latin word for wooden
platter, scutra, or the Old Norse skola, "to wash."

Some hams
hanging in the kitchen were taken out for burial, and the barrel of beer in
the scullery was stove in with a kick from Boxer’s hoof, – otherwise nothing
in the house was touched.
* stove :misc:
[2021-03-18 Thu 17:01]

A stove is a machine that heats or cooks. If you want really delicious
popcorn, don't use the microwave — cook it the old-fashioned way, in a
pot of hot oil on the stove.

Stoves typically use gas or electricity. If you have a wood-burning
stove in your house, you know it's an apparatus that burns split logs
to create enough heat to warm up a room — or several rooms. In the
15th century, stove meant either "heated room" or "bathroom." Experts
aren't sure about the word's origin, although some guess a connection
to Vulgar Latin's extufare, "take a steam bath."

Some hams
hanging in the kitchen were taken out for burial, and the barrel of beer in
the scullery was stove in with a kick from Boxer’s hoof, – otherwise nothing
in the house was touched.
* attended :misc:
[2021-03-18 Thu 17:03]




nil


The other, somewhat subtler point, was that interface is very
 important. Sure, the MGB was a lousy car in almost every way that
 counted: balky, unreliable, underpowered. But it was fun to drive.
* innards :misc:
[2021-03-24 Wed 17:53]

Your innards are your stomach, intestines, and other abdominal
organs. Catching a fish is fun, but gutting it, or removing its
innards, is less fun.

The slang term innards is sometimes used to mean "the parts of the
digestive system," and other times refers more generally to any of the
inside parts or organs of a human or animal body. Innards was coined
in the 1800s, originally spelled innerds, from a dialect form of
inwards, and meaning "the bowels."

There was a competing bicycle dealership next door (Apple) that one
 day began selling motorized vehicles--expensive but attractively
 styled cars with their innards hermetically sealed, so that how
 they worked was something of a mystery.
* yearn :misc:
[2021-03-25 Thu 17:56]

To yearn for something is to really, really want it. You might yearn
for freedom or you might yearn for a perfect tamale. Usually you yearn
for something or someone you can't easily get.

If you have a hankering for pie, you could also say that you yearn for
it. Yearn also means "to feel sweet on someone" or "to have affection
for something." If your girlfriend moves to Alaska and you’re stuck in
Texas, you’d probably yearn for her. And when she comes back to visit,
you would still yearn — meaning you’d still feel affection for her.

don't drum up the men to gather wood, divide the work and give
      orders. Instead, teach them to yearn for the vast and endless
      sea. - 

But there is another matter that
must be attended to first.’
* unalterable :misc:
[2021-03-18 Thu 17:05]

You take your dress to the tailor to be altered. He tells you he can't
alter it. The dress is unalterable. Something unalterable cannot be
changed.

Take the prefix un-, meaning "not". Add it to the word alter, meaning
"change." Tack on the suffix -able, meaning "possible." The result?
Unalterable, "impossible to change." The things you've done in the
past are unalterable. The only things you have the power to change are
the things you're doing right now or that you will do in the future.
How can you alter things that haven't happened yet? Good question. For
all we know, they're unalterable too.

These Seven Commandments would now be inscribed on the
wall; they would form an unalterable law by which all the animals on Animal
Farm must live for ever after.
* ramifications :misc:
[2021-03-18 Thu 20:09]

A ramification is an accidental consequence that complicates things.
Remember that time you borrowed your father's car without asking? The
ramification was that Dad missed an important meeting, his company
went under, and he had to sell the car. Oops!

The ramifications are the broader effects that fan out into the world
from one situation, or decision, that kicks it all off. Ramification
also refers to something branching out, like limbs on a tree — which
is what bad decisions tend to do. Ramification is like consequence,
but usually unintended and bad. The word is often used in political
discussions about laws or government decisions because they might be
made locally but could affect people worldwide.

But, knowing facts is not the same as understanding
their causes and ramifications.

