-*- coding: utf-8 -*-


* tangible :misc:
[2021-04-05 Mon 11:10]

When you can touch something, it's tangible: "I need tangible proof
that aliens exist — I want to shake their little green hands!"

Tangible is from Latin tangere, "to touch," and it simply means
something that can be touched or felt, though it can be used in
metaphorical senses: tangible assets have a value that can be
precisely measured, and tangible grief can be clearly sensed by an
onlooker. So you might not need to physically touch something for it
to be tangible, but it has to be grounded in the real world of facts:
"Has the teen pop star demonstrated any tangible ability to sing?"

Our standard of living increased 20-fold in these 170 years, but
barely a day went by that lacked tangible reasons for pessimism.
* invincible :misc:
[2021-04-05 Mon 11:11]

Something invincible is victorious over everything. Disease, death,
destruction? No match for something truly invincible. Mere humans who
imagine they're invincible, however, will inevitably prove that
they're not.

Invincible comes ultimately from the Latin verb vincere, "to conquer."
Many of the uses for invincible are for describing someone or
something victorious or unbeatable at what they do. A company can be
invincible when it outsells similar businesses for years, a tennis
player is invincible after winning all of the majors in a year or a
career, and Superman and the Indomitable Snowman are invincible as
long as they stay away from kryptonite and the warm sun.

He associated good times with the end of bad times. Getting wealthy made him
feel like staying wealthy was inevitable, and that he was invincible. After
losing nearly everything he reflected:
* invince
* belabor :misc:
[2021-04-05 Mon 11:13]

Belabor means to go at something with everything you've got. When you
say, "Don't belabor or agonize over the decision," it means, "Move
on."

Belabor is made up of the Latin roots be and labor meaning "to exert
one's strength upon." You can belabor a point by using excessive
detail, or you could belabor the obvious by stating over and over what
everyone already knows. Belaboring can be a physical attack as well. A
person can belabor or beat the living daylights out of you with a
club.

“I’ve been banging away at this thing for 30 years. I think the simple math
is, some projects work and some don’t. There’s no reason to belabor either
one. Just get on to the next.”
* bargain :misc:
[2021-04-05 Mon 11:15]

The table you bought at a yard sale for five dollars might seem like a
bargain until you get it home and realize it only has three legs. A
bargain is a good deal.

Inexpensive items are one type of bargain, and another kind of bargain
is an agreement you make with someone — a deal or compromise. Two
countries might strike a trade bargain, or you could make a bargain
with your friend that you'll drive to the mall if she buys you a giant
cinnamon roll. Bargain also means to negotiate the details of a
purchase, which makes sense because the root word is bargaignier,
French for "haggle over the price."

It was such a bargain that the Germans effectively considered it a donation.
* preemptively :misc:
[2021-04-05 Mon 11:18]

A preemptive action is made to keep some other action from being
taken.  Before you could be accused of eating the whole cake, you
decided to make a preemptive apology, which was met with awkward
silence.

Tired of being disturbed by your roommate's loud music, your
preemptive strike was to crank up your favorite opera as soon as you
arrived home.  Unfortunately, he'd already made a preemptive strike of
his own by borrowing your stereo.  Don't confuse preemptive with
peremptory, a word meaning “arrogant.” You don't have to be arrogant
to make a preemptive move, just cautious.

The Chris Rock I see on TV is hilarious, flawless. The Chris Rock that
performs in dozens of small clubs each year is just OK. That is by design. No
comedic genius is smart enough to preemptively know what jokes will land
well. Every big comedian tests their material in small clubs before using it
in big venues. Rock was once asked if he missed small clubs. He responded:
* preemptive
* fumbling :misc:
[2021-04-05 Mon 11:20]



nil

One newspaper profiled these small-club sessions. It described Rock thumbing
through pages of notes and fumbling with material. “I’m going to have to cut
some of these jokes,” he says mid-skit. The good jokes I see on Netflix are
the tails that stuck out of a universe of hundreds of attempts.
* fumble
* thumbing :misc:
[2021-04-05 Mon 11:21]

Your thumb is the fifth digit on your hand, the one that doesn't quite
match your fingers. Thumbs help us grip objects with care and
precision — it would be difficult to hold chopsticks without a thumb.

Humans are more dextrous than our closest primate relatives because of
our nimble thumbs. They're opposable, so we can move them forward and
touch them to our fingers. Some monkeys share this trait, and they're
the best able to use primitive tools. Your thumbs make it possible for
you to brush your teeth, write with a pen, and snap. You can also
thumb through the pages of a book — in other words, turn each page
with your thumb.

One newspaper profiled these small-club sessions. It described Rock thumbing
through pages of notes and fumbling with material. “I’m going to have to cut
some of these jokes,” he says mid-skit. The good jokes I see on Netflix are
the tails that stuck out of a universe of hundreds of attempts.
* thumb
* incur                                                                :misc:
[2021-04-05 Mon 12:01]

To incur is to get or receive — and usually it's something you brought
upon yourself. If you don't pay your credit card bills on time, you'll
likely incur lots of fees and some serious debt.

Generally, when you incur something, that something is
undesirable. You can incur penalties, expenses, a parking ticket, or a
friend’s wrath, for example. But it's pretty unlikely that you'd incur
free tickets to the World Series. Frederick Douglass once famously
said, “I prefer to be true to myself, even at the hazard of incurring
the ridicule of others, rather than to be false, and to incur my own
abhorrence."

Part of why this isn’t intuitive is because in most fields we only see the
finished product, not the losses incurred that led to the tail-success
product.
* horrendous :misc:
[2021-04-05 Mon 12:02]

Bad luck, an injury, a mistake, an unfortunate outfit, or a crime —
anything can be called horrendous if it causes such dread or fear that
you can barely even think about it.

If you’ve ever encountered something horrendous, you won’t be
surprised to learn that the word traces back to the Latin word
horrere, meaning "to bristle with fear, shudder." That’s a good way to
think about horrendous things — they cause you to shudder. You can use
the word to describe any type of thing — people, ideas, actions, and
so on — but save it for those things that are not merely bad but
instead are truly horrifying.

Something I’ve learned from both investors and entrepreneurs is that no one
makes good decisions all the time. The most impressive people are packed
full of horrendous ideas that are often acted upon.
* quip :misc:
[2021-04-05 Mon 12:02]

A quip — a short, witty comment — can be pleasant, wise, or sarcastic,
but usually carries an element of humor.

A quip is a witty or clever remark that sounds spur-of-the-moment. A
successful quip must sound offhand, as though it were an afterthought,
even if the speaker has been honing the statement for days.  Dorothy
Parker was a famous writer known for her quick quips, such as, "The
best way to keep children home is to make the home atmosphere pleasant
— and let the air out of the tires."

There is the old pilot quip that their jobs are “hours and hours of boredom
punctuated by moments of sheer terror.” It’s the same in investing. Your
success as an investor will be determined by how you respond to punctuated
moments of terror, not the years spent on cruise control.
* genius :misc:
[2021-04-05 Mon 12:02]

Genius is an exceptional talent or skill, something above and beyond
the norm. A genius is someone who possesses this brilliance, like a
child prodigy who learned the piano at age 3 and played sold-out
concerts by age 5.

Genius comes from the Latin word of the same name, meaning "guardian
deity or spirit which watches over each person from birth" or "innate
ability."  Your genius — your superior talent — at the game of chess
could make you a world champion. Your amazing genius would also make
you a genius. The word can be used more lightheartedly to describe a
natural ability or flair for something. You may have a genius for
putting together stylish outfits.

Napoleon’s definition of a military genius was, “The man who can do the
average thing when all those around him are going crazy.”
* dud                                                                  :misc:
[2021-04-05 Mon 12:04]

Your duds are your clothes. Your grandmother might hand you a hundred
dollar bill at the mall and say, "Go buy yourself some new duds."

The noun duds is an informal, slang term for "clothing." You can pack
your duds in a suitcase before a vacation or arrange your duds by
color in your closet. Though experts aren't sure where the word duds
came from originally, they know that it was dudde in the 1300s, which
meant "cloak or mantle," and later came to be duddes and to mean
"ragged clothing."

Most public companies are duds, a few do well, and a handful become
extraordinary winners that account for the majority of the stock market’s
returns.
* stupendously :misc:
[2021-04-05 Mon 12:04]



nil

Perhaps 99% of the works someone like Berggruen acquired in his life turned
out to be of little value. But that doesn’t particularly matter if the other
1% turn out to be the work of someone like Picasso. Berggruen could be wrong
most of the time and still end up stupendously right.
* stupendous
* exclusive :misc:
[2021-04-05 Mon 12:05]

Exclusive means with limited access. The only way you might get
reservations at one of the most exclusive restaurants in Los Angeles
is to become friends with the maitre d', or become famous.

By its nature, something that is exclusive leaves people out, or
excludes them. You would think this was a bad thing, since excluding
people is not very nice, but by being exclusive, things like clubs,
restaurants, and resorts become all the more desirable. Exclusive can
also mean sole or only: The company became the exclusive soda vendor
at the new stadium. The local newspaper got an exclusive interview and
broke the news.

Optimism is usually defined as a belief that things will go well. But that’s
incomplete. Sensible optimism is a belief that the odds are in your favor,
and over time things will balance out to a good outcome even if what happens
in between is filled with misery. And in fact you know it will be filled
with misery. You can be optimistic that the long-term growth trajectory is
up and to the right, but equally sure that the road between now and then is
filled with landmines, and always will be. Those two things are not mutually
exclusive.
* excluse
* laughs :misc:
[2021-04-05 Mon 12:06]

To let out a chuckle or giggle is to laugh: people laugh when
something is funny.

To chortle, cackle, guffaw, or titter is to laugh. The job of a
comedian is to make people laugh. Often people laugh at things that
aren't supposed to be funny, and people also laugh to be polite. If
something is silly, you can say "That's a laugh!" If you had fun at a
party, you can say "Thanks for the laughs." Everybody's laugh sounds a
little different. It would be a shame if your laugh sounded like Elmer
Fudd.

What’s the saying? You plan, God laughs. Financial and investment planning
are critical, because they let you know whether your current actions are
within the realm of reasonable. But few plans of any kind survive their
first encounter with the real world. If you’re projecting your income,
savings rate, and market returns over the next 20 years, think about all the
big stuff that’s happened in the last 20 years that no one could have
foreseen: September 11th, a housing boom and bust that caused nearly 10
million Americans to lose their homes, a financial crisis that caused almost
nine million to lose their jobs, a record-breaking stock-market rally that
ensued, and a coronavirus that shakes the world as I write this.
* gnaw :misc:
[2021-04-05 Mon 12:06]

To gnaw is to bite or chew. Your favorite food might be corn on the
cob, because you love to gnaw along each row of kernels.

To gnaw also means to deteriorate or wear away as if by gnawing with
the teeth. In Arches National Park, the weather has gnawed away at the
rocks creating beautiful formations like arches, bridges, and balanced
rocks. In this sense, to gnaw can be used even more
figuratively. Something might gnaw at the back of your mind —
something you were supposed to do, although now you can't quite
remember what it was.

No one wants to hold cash during a bull market. They want to own assets that
go up a lot. You look and feel conservative holding cash during a bull
market, because you become acutely aware of how much return you’re giving up
by not owning the good stuff. Say cash earns 1% and stocks return 10% a
year. That 9% gap will gnaw at you every day.
* complacent :misc:
[2021-04-05 Mon 12:06]

Someone who is complacent has become overly content — the
junk-food-eating couch potato might be feeling complacent about his
health.

The literal meaning of this word's Latin root is "very pleased," but
even though complacent people may seem pleased with themselves, we are
rarely pleased with them. They are unconcerned by things that should
concern them, and they may neglect their duties. A complacent person
might be heard saying, "Ehh, don't worry about it!" — when there
really is something to worry about.

Moritz: There’s a lot of truth to that … We assume that tomorrow won’t be
like yesterday. We can’t afford to rest on our laurels. We can’t be
complacent. We can’t assume that yesterday’s success translates into
tomorrow’s good fortune.
* complace
* takeaway :misc:
[2021-04-05 Mon 12:09]



nil

The practical takeaway is that the counterintuitiveness of compounding may
be responsible for the majority of disappointing trades, bad strategies, and
successful investing attempts.

* clamor :misc:
[2021-04-05 Mon 21:16]

To clamor is to make a demand — LOUDLY. It's usually a group that
clamors — like Americans might clamor for comprehensive health care
coverage.

The noun clamor is often used specifically to describe a noisy outcry
from a group of people, but more generally, the word means any loud,
harsh sound. You could describe the clamor of sirens in the night or
the clamor of the approaching subway in the tunnel.

As we put our final touches on this book, we find that our thoughts are now
mostly elsewhere. This is, in part, because other tasks and projects clamor
for our attention, but also because it’s just really hard to look long and
intently at our selfish motives, at what we’ve called “the elephant in the
brain.” Even we, the authors of a book on the subject, are relieved for the
chance to look away, to let our minds wander to safer, more comfortable
topics.
