-*- coding: utf-8 -*-


* tangible :misc:
[2021-04-05 Mon 11:10]

When you can touch something, it's tangible: "I need tangible proof
that aliens exist — I want to shake their little green hands!"

Tangible is from Latin tangere, "to touch," and it simply means
something that can be touched or felt, though it can be used in
metaphorical senses: tangible assets have a value that can be
precisely measured, and tangible grief can be clearly sensed by an
onlooker. So you might not need to physically touch something for it
to be tangible, but it has to be grounded in the real world of facts:
"Has the teen pop star demonstrated any tangible ability to sing?"

Our standard of living increased 20-fold in these 170 years, but
barely a day went by that lacked tangible reasons for pessimism.
* invincible :misc:
[2021-04-05 Mon 11:11]

Something invincible is victorious over everything. Disease, death,
destruction? No match for something truly invincible. Mere humans who
imagine they're invincible, however, will inevitably prove that
they're not.

Invincible comes ultimately from the Latin verb vincere, "to conquer."
Many of the uses for invincible are for describing someone or
something victorious or unbeatable at what they do. A company can be
invincible when it outsells similar businesses for years, a tennis
player is invincible after winning all of the majors in a year or a
career, and Superman and the Indomitable Snowman are invincible as
long as they stay away from kryptonite and the warm sun.

He associated good times with the end of bad times. Getting wealthy
made him feel like staying wealthy was inevitable, and that he was
invincible. After losing nearly everything he reflected:
* invince
* belabor :misc:
[2021-04-05 Mon 11:13]

Belabor means to go at something with everything you've got. When you
say, "Don't belabor or agonize over the decision," it means, "Move
on."

Belabor is made up of the Latin roots be and labor meaning "to exert
one's strength upon." You can belabor a point by using excessive
detail, or you could belabor the obvious by stating over and over what
everyone already knows. Belaboring can be a physical attack as well. A
person can belabor or beat the living daylights out of you with a
club.

“I’ve been banging away at this thing for 30 years. I think the simple
math is, some projects work and some don’t. There’s no reason to
belabor either one. Just get on to the next.”
* bargain :misc:
[2021-04-05 Mon 11:15]

The table you bought at a yard sale for five dollars might seem like a
bargain until you get it home and realize it only has three legs. A
bargain is a good deal.

Inexpensive items are one type of bargain, and another kind of bargain
is an agreement you make with someone — a deal or compromise. Two
countries might strike a trade bargain, or you could make a bargain
with your friend that you'll drive to the mall if she buys you a giant
cinnamon roll. Bargain also means to negotiate the details of a
purchase, which makes sense because the root word is bargaignier,
French for "haggle over the price."

It was such a bargain that the Germans effectively considered it a
donation.
* preemptively :misc:
[2021-04-05 Mon 11:18]

A preemptive action is made to keep some other action from being
taken.  Before you could be accused of eating the whole cake, you
decided to make a preemptive apology, which was met with awkward
silence.

Tired of being disturbed by your roommate's loud music, your
preemptive strike was to crank up your favorite opera as soon as you
arrived home.  Unfortunately, he'd already made a preemptive strike of
his own by borrowing your stereo.  Don't confuse preemptive with
peremptory, a word meaning “arrogant.” You don't have to be arrogant
to make a preemptive move, just cautious.

That is by design. No comedic genius is smart enough to preemptively
know what jokes will land well. Every big comedian tests their
material in small clubs before using it in big venues.
* preemptive
* fumbling :misc:
[2021-04-05 Mon 11:20]

One newspaper profiled these small-club sessions. It described Rock
thumbing through pages of notes and fumbling with material. “I’m going
to have to cut some of these jokes,” he says mid-skit. The good jokes
I see on Netflix are the tails that stuck out of a universe of
hundreds of attempts.
* fumble
* thumbing :misc:
[2021-04-05 Mon 11:21]

Your thumb is the fifth digit on your hand, the one that doesn't quite
match your fingers. Thumbs help us grip objects with care and
precision — it would be difficult to hold chopsticks without a thumb.

Humans are more dextrous than our closest primate relatives because of
our nimble thumbs. They're opposable, so we can move them forward and
touch them to our fingers. Some monkeys share this trait, and they're
the best able to use primitive tools. Your thumbs make it possible for
you to brush your teeth, write with a pen, and snap. You can also
thumb through the pages of a book — in other words, turn each page
with your thumb.

One newspaper profiled these small-club sessions. It described Rock
thumbing through pages of notes and fumbling with material. “I’m going
to have to cut some of these jokes,” he says mid-skit. The good jokes
I see on Netflix are the tails that stuck out of a universe of
hundreds of attempts.
* thumb
* incur                                                                :misc:
[2021-04-05 Mon 12:01]

To incur is to get or receive — and usually it's something you brought
upon yourself. If you don't pay your credit card bills on time, you'll
likely incur lots of fees and some serious debt.

Generally, when you incur something, that something is
undesirable. You can incur penalties, expenses, a parking ticket, or a
friend’s wrath, for example. But it's pretty unlikely that you'd incur
free tickets to the World Series. Frederick Douglass once famously
said, “I prefer to be true to myself, even at the hazard of incurring
the ridicule of others, rather than to be false, and to incur my own
abhorrence."

Part of why this isn’t intuitive is because in most fields we only see
the finished product, not the losses incurred that led to the
tail-success product.
* horrendous :misc:
[2021-04-05 Mon 12:02]

Bad luck, an injury, a mistake, an unfortunate outfit, or a crime —
anything can be called horrendous if it causes such dread or fear that
you can barely even think about it.

If you’ve ever encountered something horrendous, you won’t be
surprised to learn that the word traces back to the Latin word
horrere, meaning "to bristle with fear, shudder." That’s a good way to
think about horrendous things — they cause you to shudder. You can use
the word to describe any type of thing — people, ideas, actions, and
so on — but save it for those things that are not merely bad but
instead are truly horrifying.

Something I’ve learned from both investors and entrepreneurs is that
no one makes good decisions all the time. The most impressive people
are packed full of horrendous ideas that are often acted upon.
* quip :misc:
[2021-04-05 Mon 12:02]

A quip — a short, witty comment — can be pleasant, wise, or sarcastic,
but usually carries an element of humor.

A quip is a witty or clever remark that sounds spur-of-the-moment. A
successful quip must sound offhand, as though it were an afterthought,
even if the speaker has been honing the statement for days.  Dorothy
Parker was a famous writer known for her quick quips, such as, "The
best way to keep children home is to make the home atmosphere pleasant
— and let the air out of the tires."

There is the old pilot quip that their jobs are “hours and hours of
boredom punctuated by moments of sheer terror.”
* Napoleon's definition of genius                                      :misc:
[2021-04-05 Mon 12:02]

Genius is an exceptional talent or skill, something above and beyond
the norm. A genius is someone who possesses this brilliance, like a
child prodigy who learned the piano at age 3 and played sold-out
concerts by age 5.

Genius comes from the Latin word of the same name, meaning "guardian
deity or spirit which watches over each person from birth" or "innate
ability."  Your genius — your superior talent — at the game of chess
could make you a world champion. Your amazing genius would also make
you a genius. The word can be used more lightheartedly to describe a
natural ability or flair for something. You may have a genius for
putting together stylish outfits.

Napoleon’s definition of a military genius was, “The man who can do
the average thing when all those around him are going crazy.”
* dud                                                                  :misc:
[2021-04-05 Mon 12:04]

Your duds are your clothes. Your grandmother might hand you a hundred
dollar bill at the mall and say, "Go buy yourself some new duds."

The noun duds is an informal, slang term for "clothing." You can pack
your duds in a suitcase before a vacation or arrange your duds by
color in your closet. Though experts aren't sure where the word duds
came from originally, they know that it was dudde in the 1300s, which
meant "cloak or mantle," and later came to be duddes and to mean
"ragged clothing."

Most public companies are duds, a few do well, and a handful become
extraordinary winners that account for the majority of the stock
market’s returns.
* stupendously :misc:
[2021-04-05 Mon 12:04]

Perhaps 99% of the works someone like Berggruen acquired in his life
turned out to be of little value. But that doesn’t particularly matter
if the other 1% turn out to be the work of someone like
Picasso. Berggruen could be wrong most of the time and still end up
stupendously right.
* stupendous
* exclusive :misc:
[2021-04-05 Mon 12:05]

Exclusive means with limited access. The only way you might get
reservations at one of the most exclusive restaurants in Los Angeles
is to become friends with the maitre d', or become famous.

By its nature, something that is exclusive leaves people out, or
excludes them. You would think this was a bad thing, since excluding
people is not very nice, but by being exclusive, things like clubs,
restaurants, and resorts become all the more desirable. Exclusive can
also mean sole or only: The company became the exclusive soda vendor
at the new stadium. The local newspaper got an exclusive interview and
broke the news.

You can be optimistic that the long-term growth trajectory is up and
to the right, but equally sure that the road between now and then is
filled with landmines, and always will be. Those two things are not
mutually exclusive.
* excluse
* God laughs                                                           :misc:
[2021-04-05 Mon 12:06]

To let out a chuckle or giggle is to laugh: people laugh when
something is funny.

To chortle, cackle, guffaw, or titter is to laugh. The job of a
comedian is to make people laugh. Often people laugh at things that
aren't supposed to be funny, and people also laugh to be polite. If
something is silly, you can say "That's a laugh!" If you had fun at a
party, you can say "Thanks for the laughs." Everybody's laugh sounds a
little different. It would be a shame if your laugh sounded like Elmer
Fudd.

What’s the saying? You plan, God laughs. Financial and investment planning
are critical, because they let you know whether your current actions are
within the realm of reasonable.
* gnaw :misc:
[2021-04-05 Mon 12:06]

To gnaw is to bite or chew. Your favorite food might be corn on the
cob, because you love to gnaw along each row of kernels.

To gnaw also means to deteriorate or wear away as if by gnawing with
the teeth. In Arches National Park, the weather has gnawed away at the
rocks creating beautiful formations like arches, bridges, and balanced
rocks. In this sense, to gnaw can be used even more
figuratively. Something might gnaw at the back of your mind —
something you were supposed to do, although now you can't quite
remember what it was.

No one wants to hold cash during a bull market. They want to own
assets that go up a lot. You look and feel conservative holding cash
during a bull market, because you become acutely aware of how much
return you’re giving up by not owning the good stuff. Say cash earns
1% and stocks return 10% a year. That 9% gap will gnaw at you every
day.
* complacent :misc:
[2021-04-05 Mon 12:06]

Someone who is complacent has become overly content — the
junk-food-eating couch potato might be feeling complacent about his
health.

The literal meaning of this word's Latin root is "very pleased," but
even though complacent people may seem pleased with themselves, we are
rarely pleased with them. They are unconcerned by things that should
concern them, and they may neglect their duties. A complacent person
might be heard saying, "Ehh, don't worry about it!" — when there
really is something to worry about.

Moritz: There’s a lot of truth to that … We assume that tomorrow won’t
be like yesterday. We can’t afford to rest on our laurels. We can’t be
complacent. We can’t assume that yesterday’s success translates into
tomorrow’s good fortune.
* complace
* takeaway :misc:
[2021-04-05 Mon 12:09]

The practical takeaway is that the counterintuitiveness of compounding
may be responsible for the majority of disappointing trades, bad
strategies, and successful investing attempts.

* clamor :misc:
[2021-04-05 Mon 21:16]

To clamor is to make a demand — LOUDLY. It's usually a group that
clamors — like Americans might clamor for comprehensive health care
coverage.

The noun clamor is often used specifically to describe a noisy outcry
from a group of people, but more generally, the word means any loud,
harsh sound. You could describe the clamor of sirens in the night or
the clamor of the approaching subway in the tunnel.

This is, in part, because other tasks and projects clamor for our
attention, but also because it’s just really hard to look long and
intently at our selfish motives, at what we’ve called “the elephant in
the brain.”


* fad                                                                  :misc:
[2021-04-06 Tue 16:38]

If it’s all the rage, everybody’s into it, your parents don’t get it,
and teenage girls across the globe are trying to outdo each other with
it, it’s officially a fad.

From hairstyles to hula hoops to saying “that’s hot,” fads are known
to rise to crazed levels of popularity seemingly overnight. But they
fade out just as fast, leaving late adopters with outdated sayings and
some seriously uncool shoes. Much like a fad itself, no one has any
real idea where this word came from. But it’s still in fashion some
144 years later.

But all I found was an avalanche of management fads and techniques,
cod philosophy, self-help manuals, life coaches and gurus, all of
varying degrees of dubiousness, and all insisting that they definitely
knew the secret to happiness, no matter who you are.
* credible :misc:
[2021-04-06 Tue 16:42]

Someone who's credible is honest and believable. A pathological liar,
for example, might not be the most credible witness for your case
against the bank robber.

Similar to words like reliable and plausible, credible is an adjective
that comes to us from the Latin credibilis, meaning “worthy to be
believed.” A credible reputation is often earned through consistent
good behavior and an overall trustworthy personality. Spill a secret
you promised to keep, or lie under oath in a courtroom, and you lose
all credibility.

If you’re an experienced neurobod, you can easily spot when someone is
just borrowing the terminology of your field to sound credible, rather
than actually having any useful understanding of it.
* smattering :misc:
[2021-04-06 Tue 16:43]

A smattering is a small but inexact amount of something. If you know a
smattering of things about Australia, then you don't know much.

A smattering is a small amount of something, but it's hard to say how
much. It's probably less than a bunch, but it's not much more than a
whit or a jot. If you said "There's a smattering of squirrels in the
park," then there are only a few squirrels. This word also implies
that you don't understand a subject very well — a smattering of
knowledge is only a tiny bit of knowledge.

To truly explain how the brain deals with happiness would take more
than a vague two-line summary or a smattering of impressive-sounding
terminology, it would take a whole book …
* grievances :misc:
[2021-04-06 Tue 16:44]

A grievance is a complaint.  It can be formal, as when an employee
files a grievance because of unsafe working conditions, or more of an
emotional matter, like a grievance against an old friend who betrayed
you.

A grievance is a complaint that may or may not be justified. Often a
grievance is a complaint about something that breaks a rule or a law,
like a grievance filed against a person who builds a fence in his
front yard in a town that does not allow that. If that same neighbor
plants flowers he knows make you sneeze uncontrollably, you might be
unhappy about that, but this is the kind of grievance you can work out
among yourselves.

Because if there’s one thing I do, it’s go to ridiculous extremes to
settle minor grievances, even if the party that caused them remains
blissfully unaware of my existence.
* blissfully :misc:
[2021-04-06 Tue 16:44]

Because if there’s one thing I do, it’s go to ridiculous extremes to
settle minor grievances, even if the party that caused them remains
blissfully unaware of my existence.
* abundantly :misc:
[2021-04-06 Tue 16:46]

One thing that is abundantly clear from the sheer variety of supposed
‘secrets’ to happiness is that it has an undeniably strong subjective
element.
* dungeon                                                              :misc:
[2021-04-06 Tue 16:47]

That dank, stone-walled underground prison where wretched prisoners
were kept manacled in medieval days? That was a dungeon, otherwise
known as the "keep," and most familiar to us today from a million
video games and movies.

In fact, the original meaning of dungeon was of something overground
rather than underground, coming from the Old French term donjon,
meaning the "great tower of a castle," and the underground meaning
only came later. Rapunzel in the fairy tale was held captive in a
tower rather than an underground cell and if she hadn't been, her long
hair wouldn't have been much help in her escape.

So, I wanted to include insights from a wide range of people from
different walks of life, to see what makes them happy (or not). As a
result, I ended up talking with stars of stage and screen,
millionaires, leading scientists, journalists, ghost-hunters and one
person who … well, let’s just say that in no other research I’ve done
did I ever hear the term ‘sex dungeon’ used so freely and so often.
* warn :misc:
[2021-04-06 Tue 16:48]

When you warn someone, you advise them to be careful or tell them
about a problem or danger. If you perform a dangerous stunt, you
should probably warn your audience, "Don't try this at home."

Many traffic signs are meant to warn drivers about hazards, like
bridges that get slippery in the rain or bumps in the road. And the
purpose of a dog's growl is to warn another dog (or human) that it's
stressed or fearful. A warning is a helpful message, no matter what
form it comes in, and to warn is to send this message. The Old English
root is warnian, "give notice of impending danger."

I should warn you though, that this is not meant to be a self-help
book, or some model for how to live a happier and fuller life, or
anything like that.
* din :misc:
[2021-04-06 Tue 19:32]

Walk into the average school cafeteria at lunchtime, and you'll get a
good sense of what a din is — loud, confused, continuous, generally
unpleasant, and often potentially headache-inducing noise.

Who knew noise pollution was a problem in ancient times? Humans have
been experiencing loud, sustained, annoying sounds for centuries,
judging by the etymology of the word din. It traces its roots back to
Old English dyne or dynn, which had the same meaning as din does
today, only with a different pronunciation. Before that, it popped up
in Old Norse as dynr and meant to "come rumbling down" — fitting, from
the language that gave us Thor, the God of Thunder.

Would you like to be stuffed head first into a tube, a cold and
confining one, where you’re not allowed to move? For hours at a time?
A tube that makes incredibly loud noises, an ongoing din of clicks and
screeches like an enraged metal dolphin?
* fairly :misc:
[2021-04-06 Tue 19:46]

When you do something fairly, you treat everyone with equal
consideration. Sharing a pizza fairly between six people is easy: just
give each person one slice.

A teacher who doesn't treat all students fairly isn't a very good
teacher — and a police officer who doesn't act fairly toward all
citizens is also doing a poor job. When you behave fairly, you're
unbiased and impartial, and you follow the rules. You can also use
this adverb to mean "to a large degree" or "reasonably." For example,
you could say, "I'm fairly certain that it's going to snow again
tomorrow."

It may not sound that impressive, but this activity is essentially the
basis of our mind and consciousness, in much the same way that
individual cells make up our body (cells combine in complex ways to
form tissues, which combine in complex ways to form organs, which
combine to form one functioning entity that is you). Scientifically
speaking, this is a fairly big deal.
* utterly :misc:
[2021-04-06 Tue 19:49]

Utterly is an intensifying word: something utterly delicious is very,
very delicious.

One thing people love to do is exaggerate. You often hear people
talking about how awesome or awful things are. When you're laying it
on thick, utterly is an utterly useful word: it means something
similar to completely, totally, or very. Something utterly
disappointing is extremely disappointing. Something utterly wonderful
is wonderful times ten. When you get tired of writing very, utterly is
a good word choice.

So of course happiness comes from the brain. But that’s like being
asked where Southampton is and replying ‘the solar system’; correct,
but utterly unhelpful.
* reward :misc:
[2021-04-06 Tue 20:05]

A reward is something you get for a job well done. If you study hard
for that vocabulary test, an "A" might be the reward in your future.

You can use reward as a verb, as when the mayor rewards a firefighter
who saves a family from a terrible blaze, or as a noun, to talk about
the actual payment or item that's given to the firefighter. People
often offer a reward for the return of lost or stolen things, like
bicycles or jewelry or dogs. Reward meant "a regarding" or "an
observation" in the 1300's, but it soon came to mean "repayment for
some service."

Dopamine is an obvious one. Dopamine is a neurotransmitter that fulfils a
wide variety of functions in the brain, but one of the most familiar and
established is its role in reward and pleasure.
* perilous                                                             :misc:
[2021-04-06 Tue 20:06]

Something that is dangerous or very risky can be described with the
adjective perilous. If you are driving in a blizzard, you may kick
yourself for making such a perilous journey.

The adjective perilous comes from the Latin word periculum, meaning
dangerous. Words from the same root include peril, a noun meaning a
dangerous situation, and imperil, a verb meaning to put in danger. The
last thing you want to do as a parent is to imperil your
children. Unfortunately, childhood is filled with peril — from
climbing on the monkey bars to eating paste, dirt, or bugs. If you
think you can prevent all perilous situations, you haven't been a
parent very long!

Whenever the brain recognises that you’ve done something it approves
of (drunk water while thirsty, escaped a perilous situation, been
sexually intimate with a partner, etc.), it typically rewards this
behaviour by causing you to experience brief but often intense
pleasure triggered by the release of dopamine. And pleasure makes you
happy, right?


* surge :misc:
[2021-04-07 Wed 17:38]

A surge is a sudden strong swelling, like a tsunami wave that engulfs
the land. Although a surge offers a fluid image, anything can
experience a sudden surge, including emotions, political support, or
an angry mob.

The original Latin word surgere, meaning “to spring up or rise,”
serves as the basis for the word surge, which refers to a great sudden
growth or swelling.  If you are watching a sad movie and you
experience a sudden surge of emotion, do you quietly reach for a
tissue, pretend something's in your eye, or simply weep and sob with
reckless abandon?  Yeah, me too.  Christmas shopping can be dangerous
when there is a surge of interest in one toy and desperate shoppers
surge into stores trying to grab it up.

Expected rewards correspond with an initial dopamine surge, which then
tails off. But unexpected rewards correspond with an increased level
of dopamine release for a longer period after the reward is
experienced.
* gorging :misc:
[2021-04-07 Wed 17:41]

A gorge is a very deep crevice between two mountains or hills. Gorges
are formed by rivers running through and eroding rock over a very long
period of time.

The Latin root of gorge means "throat," leading to both the "narrow
passage" meaning and the French gorgier, "to swallow," which
influenced the verb version of gorge, "to overeat." You may love to
gorge on ice cream, but the stomachache afterward won't be very
pleasant. To remember the "canyon" meaning, think of the famous
upstate New York bumper sticker, “Ithaca is gorges.” It's a play on
gorgeous, meaning beautiful, and the beautiful ravines in the area.

Of course, endorphin neurotransmitters are the ‘big daddy’ of
pleasure-causing chemicals. Whether they are released from gorging on
chocolate or due to the rush of sex, endorphins provide that
oh-so-wonderful intense giddy warm sensation that permeates your very
being.
* permeate                                                             :misc:
[2021-04-07 Wed 17:41]

When you live in a big city like New York, you know all too well how
the smells of spices and cooking meats can permeate a hallway, easily
passing through those thin apartment doors to make your mouth water.

The verb permeate literally means to "pass through." It's often used
to describe smells or liquids that not only pass through, but also
spread to fill an entire area. When you bake cookies, you'll notice
that the rich, sweet smell of those cookies isn't confined just to
your oven — it permeates the entire kitchen and even the whole
house. In science class, you might have learned about a permeable
membrane — a thin material that is porous enough to let liquids or
gases to pass through.

Of course, endorphin neurotransmitters are the ‘big daddy’ of
pleasure-causing chemicals. Whether they are released from gorging on
chocolate or due to the rush of sex, endorphins provide that
oh-so-wonderful intense giddy warm sensation that permeates your very
being.6
* debilitating :misc:
[2021-04-07 Wed 17:42]

Something that's debilitating seriously affects someone or something's
strength or ability to carry on with regular activities, like a
debilitating illness.

Debilitating comes from the Latin word debilis, meaning "weak." That's
why you'll often see the adjective used to describe illness. After
all, serious diseases weaken the body. Other things that can be
debilitating are those that can stop you from reaching a goal, like a
debilitating snow storm that forces you to stay home, or debilitating
shyness that keeps you from reaching out to the people you want to
meet.

They’re obviously pleasurable (hence the alarming number of people who
use them), but these drugs are also clearly debilitating.
* drooling :misc:
[2021-04-07 Wed 17:43]

The dampness that forms in your mouth when you smell something
delicious is drool. When it actually drips from your mouth, you drool.

The official term for drool is saliva. Babies drool, dogs drool — we
all drool sometimes. Sometimes people drool (or salivate) because of
problems with their salivary glands. You might drool when you skip
breakfast and your friend offers you a warm, homemade cinnamon
roll. The word comes from drivel, which today means "speak nonsense,"
but originally had the sense of "to slobber or run at the nose."

Someone in the grip of an intense opiate ‘high’ isn’t much good for
anything other than staring into space and occasionally drooling.
* facilitate :misc:
[2021-04-07 Wed 17:45]

To facilitate means to make something easier. If your best friend is
very shy, you could facilitate her efforts to meet new people.

Facilitate comes from the Latin facilis, for "easy." It means to make
something easier or more likely to happen. You facilitate growth or a
process, as opposed to, say, dinner.  Often in business meetings
someone will be assigned to facilitate a discussion so people don't
just sit in awkward silence. Synonyms are ease, simplify, expedite,
and assist.

Mothers use many terms to describe childbirth – ‘miraculous’, ‘incredible’,
‘amazing’, and so on – but ‘enjoyable’ is rarely among them. And yet despite
the extreme physical demands it places on a woman’s body, they get through
it, and often do it again. This is because human women have evolved many
different adaptations to facilitate childbirth, and one of these is the
build-up and release of endorphins as it progresses.
* dampen :misc:
[2021-04-07 Wed 17:45]

To dampen something is to stifle it, to lessen its effect, or to
moisten it. Getting a cold will dampen your enthusiasm.

This word has several related meanings, most of which make something
less effective or powerful. Using a towel will dampen it in the sense
of getting it wet, but dampening goes beyond things that are damp
(wet). Bad news will dampen your mood, bringing it down. Boxing gloves
dampen the force of punches because they cushion the blows. Anything
dampened has been weakened and brought down a notch.

The brain deploys endorphins to dampen the pain and stop it from reaching
heart-stopping levels (which can happen8). This could also contribute to the
almost deliriously happy state women experience the moment the baby is born
(although that’s possibly just relief). Thanks to endorphins, childbirth, no
matter how gruelling it is, could be worse.
* deliriously :misc:
[2021-04-07 Wed 17:46]



nil

The brain deploys endorphins to dampen the pain and stop it from reaching
heart-stopping levels (which can happen8). This could also contribute to the
almost deliriously happy state women experience the moment the baby is born
(although that’s possibly just relief). Thanks to endorphins, childbirth, no
matter how gruelling it is, could be worse.
* contentment :misc:
[2021-04-07 Wed 17:50]

Contentment is the state of being happy and satisfied. On Thanksgiving
when you think about all you are grateful for, hopefully you feel a
sense of contentment. If not, have another piece of pie and then
you’ll feel contentment.

Contentment isn’t an excited kind of happy, it’s more like a peaceful
ease of mind. It’s being satisfied with what you have, whatever that
is. You might feel a sense of contentment knowing you have a cup of
hot chocolate and a good movie to look forward to tonight. Or you
might experience contentment thinking about the vast estate you just
purchased in the Hamptons. Whatever is going on in your life, you’re
pleased about it.

One problem with both the dopamine and endorphin explanations is they assume
‘happiness’ is the same as ‘pleasure’. While it’s certainly possible (normal,
even) to be happy while experiencing pleasure, to be truly happy surely
requires a lot more than that. Life is more than just a series of euphoric
moments. Happiness is also about contentment, satisfaction, love,
relationships, family, motivation, wellbeing, and many other words found in
Facebook memes. Could there be a chemical that supports this more ‘profound’
stuff? Maybe.
* cuddle :misc:
[2021-04-07 Wed 17:51]

To cuddle is to embrace in a loving, affectionate way. If you're
having a terrible day, you probably wish you could just go home, get
in bed, and cuddle with your cat.

Cuddle might come from the Middle English couth, "known" — after all,
you only cuddle with those you know. Or, cuddle may have started as
baby talk that caught on. When you cuddle, you give a snuggly hug to
make yourself or another person feel loved or comforted. As a noun,
cuddle describes the time of the embrace, like having one last cuddle
before leaving for a long trip.

One contender would be oxytocin. Oxytocin has an unusual reputation, often
being described as the ‘love’ hormone, or the ‘cuddle’ hormone. Despite what
much of the modern media would suggest, humans are a very friendly species,
and usually actively need social bonds with others in order to be happy. The
closer and more intense these bonds, the more important they are. The bonds
between lovers, relatives, very close friends, tend to make people happy over
the long term. And oxytocin is apparently integral for these.
* fidelity :misc:
[2021-04-07 Wed 17:53]

Fidelity is the quality of being faithful or loyal. Dogs are famous
for their fidelity.

Fidelity comes from the Latin root fides, which means faith, so
fidelity is the state of being faithful. Marital fidelity is
faithfulness to your spouse. If you're a journalist, your reports
should have fidelity to the facts.  Someone without fidelity to a
religion or group belief is called an infidel.

Going back to the process of childbirth again, oxytocin’s most established
role is as a chemical released in high doses during labour and
breastfeeding.12 It is key for this most fundamental of meetings between
individuals – it causes the immediate and intense bonding between mother and
baby, is present in breast milk, and induces lactation.13 However, oxytocin
has since been implicated in a much wider variety of situations: sexual
arousal and responses, stress, social interaction, fidelity, and no doubt
much more.
* intercourse :misc:
[2021-04-07 Wed 17:53]



nil

This has a number of weird consequences. For instance, oxytocin is important
for forming and enhancing social bonds but it is also released during sexual
intercourse. This may be why the oft-referenced ‘friends with benefits’
arrangement (where two friends opt to be physically intimate without any
stifling relationship/commitment) is so notoriously difficult to maintain.
* longing :misc:
[2021-04-07 Wed 17:54]

A longing is a strong feeling of need or desire for someone or
something. If you're stuck in detention and all of your friends are
outside enjoying a sunny day, you might be looking out the window with
longing.

A longing describes an unfulfilled desire. The days might feel long as
long as you are longing to see someone you love, if that person is far
away. You might be longing for your mother's home-made chicken soup,
if you are sick and far from home. Or perhaps you are a pregnant
woman, wide awake and longing for pickles and ice-cream at four in the
morning. Let's hope there's a twenty-four hour deli open somewhere to
help satisfy your longing.

Thanks to oxytocin, sexual interaction can fundamentally alter your
perception of your partner, changing purely physical attraction into genuine
affection and longing. Oxytocin is what’s ‘making the love’ during
lovemaking.
* warier :misc:
[2021-04-07 Wed 17:55]

Describe yourself as wary if you don't quite trust someone or
something and want to proceed with caution. Be wary of risky things
like wild mushrooms and Internet deals!

You can trace wary through Old English back to Old High German giwar
"aware, attentive." If you keep a wary eye on something, you are
attentive for signs that it is becoming dangerous. Likewise, if you
give someone a wary glance, your face conveys the suspicion and
caution you feel. When you are wary of driving alone at night or
making promises, you fear something bad might happen if you do these
things.

And while oxytocin affects women more than men, it does still have potent
effects on men; for instance, one study showed that, when dosed with
oxytocin, men in relationships will keep more of a distance between
themselves and attractive women in a social context than single men do.14 The
conclusion drawn here is that increased oxytocin makes men more committed to
their partner, making them more aware of how their actions might impact on
them, meaning they’d be warier of interacting with unfamiliar attractive
women, especially when others are there to see it. Basically, it can be
argued that oxytocin strengthens existing romantic bonds. But it doesn’t
create them per se, hence single men don’t show similar behaviour.
* hostility :misc:
[2021-04-07 Wed 17:57]

Hostility is the state of ill will and bad feeling. If a teacher
embarrasses you in front of the whole class, you will probably regard
him or her with hostility for the remainder of the school year.

Hostility can be used to describe aggressive relations between two
countries as well as between people. The issue of territorial borders
can often cause hostility between neighboring countries. If actual
fighting breaks out, use the word hostilities to refer to the violent
actions between them. The ordinary citizens of the countries involved
will look forward to the end of hostilities when the two governments
are able to work together for peace.

Not quite. As with most things, oxytocin has a down side. For instance,
increasing your social bonds with an individual or a group can increase your
hostility to anyone outside that bond. One study found that men dosed with
oxytocin were much quicker to ascribe negative traits to anyone not from
their culture or ethnic background.15 Or, to put it another way, oxytocin
makes you racist. If racism is integral to happiness, then I’m not sure
humans deserve it.
* ascribe :misc:
[2021-04-07 Wed 17:57]

Ascribe means to give credit to, like if you ascribe the A you got on
your group project to the hard work of your partners!

Ascribe's Latin root is ascribere, meaning basically "to write in.''
Makes sense, because ascribe is often used to link writers to their
words. Many a quirky quote, like "Age is an issue of mind over
matter. If you don't mind, it doesn't matter," is ascribed to that
famous scribe Mark Twain. It can also be a way of blaming something —
you might ascribe your bad attitude to your mom because she won't let
you have cupcakes for dinner.

Not quite. As with most things, oxytocin has a down side. For instance,
increasing your social bonds with an individual or a group can increase your
hostility to anyone outside that bond. One study found that men dosed with
oxytocin were much quicker to ascribe negative traits to anyone not from
their culture or ethnic background.15 Or, to put it another way, oxytocin
makes you racist. If racism is integral to happiness, then I’m not sure
humans deserve it.
* integral :misc:
[2021-04-07 Wed 17:58]

/ˈɪntɪɡr(ə)l,ɪnˈtɛɡr(ə)l/
Something that is integral is very important or necessary. If you are
an integral part of the team, it means that the team cannot function
without you.

An integral part is necessary to complete the whole. In this sense,
the word essential is a near synonym. In mathematics, there are
integrals of functions and equations. Integral is from Middle English,
from Medieval Latin integralis "making up a whole," from Latin integer
"untouched, entire."

Not quite. As with most things, oxytocin has a down side. For
instance, increasing your social bonds with an individual or a group
can increase your hostility to anyone outside that bond. One study
found that men dosed with oxytocin were much quicker to ascribe
negative traits to anyone not from their culture or ethnic
background.15 Or, to put it another way, oxytocin makes you racist. If
racism is integral to happiness, then I’m not sure humans deserve it.
* resentment :misc:
[2021-04-07 Wed 17:58]

Resentment, or the strong and painful bitterness you feel when someone
does something wrong to you, doesn’t have actual physical weight, but
it feels very heavy and can last a long time. Forgiveness is one way
to get rid of resentment.

Sometimes resentment lasts for years. It can be strong and hard to
pull out, like an old, gnarled tree root. While resentment over being
wronged can come from just one act against you, it also can get
stronger over time, as in "your growing resentment might just come
from the fact that the team captain always picks you last." It also
comes from misunderstandings, like feeling resentment over a dirty
look you thought was directed at you but really wasn't. It's usually
best to root out resentment early.

It doesn’t have to be so extreme though; you’ve probably witnessed
someone (or even been that someone) experiencing bitter jealousy and
resentment, even hatred, when the object of their affection is seen to
interact in an overly friendly way with someone else. The fact that
‘crimes of passion’ exist shows just how potent and destructive this
reaction can be. There are many ways to describe someone gripped by
jealous rage or paranoid suspicion; ‘happy’ isn’t one of
them. Oxytocin may be crucially important for social bonding, but not
all social bonding leads to happiness. It can, in fact, lead to the
opposite.

* unanimously :Elephant:
[2021-04-08 Thu 17:46]

If a group decides something unanimously, it means that every single
member is in agreement. A vote passed unanimously has no one objecting
to it.

When Congress passes a bill unanimously, each member agrees that it
should become a law. Things that are done or agreed on unanimously
have no dissenters, no one arguing against them — it's as if the group
were thinking as a single entity. In fact, the root of unanimously is
the Latin unanimus, "of one mind," from unus, "one," and animus,
"mind."

We’re quite curious to see how the world reacts to our book. Early reviews
were almost unanimously positive, and we expect the typical reader to accept
roughly two-thirds of our claims about human motives and institutions. Yet,
we find it hard to imagine the book’s central thesis becoming widely accepted
among any large population, even of scholars. As better minds than ours have
long advanced similar ideas, but to little apparent effect, we suspect that
human minds and cultures must contain sufficient antibodies to keep such
concepts at bay.

* to keep at a bay

  


* bedrock :Elephant:
[2021-04-08 Thu 17:51]

Bedrock is the hard layer of rock beneath looser rocks and soil. In
some places, the bedrock is exposed, while in others it lies deep
underground.

A geologist who's interested in studying the bedrock in different
areas might have to dig through the various layers of soil to reach
that bedrock. You can also use the word in a figurative way, to mean
"the heart of the matter," or "the basic, fundamental principles." For
example, you might say that fairness and freedom is the bedrock of a
good government. The word combines bed — here meaning "plot of land" —
and rock.

As he immersed himself in the literature, however, he started noticing data
that didn’t add up, and soon he began to question even the most basic,
bedrock assumptions. Why do patients spend so much on medical care? To get
healthier: That’s their one and only goal, right?
* exorbitantly :Elephant:
[2021-04-08 Thu 17:54]



nil

Meanwhile, non-medical interventions—such as efforts to alleviate stress or
improve diet, exercise, sleep, or air quality—have a much bigger apparent
effect on health, and yet patients and policymakers are far less eager to
pursue them. Patients are also easily satisfied with the appearance of good
medical care, and show shockingly little interest in digging beneath the
surface—for example, by getting second opinions or asking for outcome
statistics from their doctors or hospitals. (One astonishing study found that
only 8 percent of patients about to undergo a dangerous heart surgery were
willing to pay $50 to learn the different death rates for that very surgery
at nearby hospitals.) Finally, people spend exorbitantly on heroic
end-of-life care even though cheap, palliative care is usually just as
effective at prolonging life and even better at preserving quality of life.
* considerable :Elephant:
[2021-04-08 Thu 17:55]

Use the adjective considerable to describe something that is large in
amount. Things you probably spend a considerable amount of time on:
homework and laundry. Things you'd rather spend time on: anything that
isn't homework and laundry!

The adjective considerable can describe something of importance and is
worthy of notice or respect. If you are an excellent singer, dancer,
musician, writer, or similar profession, people may ask you to donate
your considerable talents to charitable causes. If you're not an
excellent singer, dancer, musician, or writer, they will still ask you
to donate, but they are more likely to ask for money!

Altogether, these puzzles cast considerable doubt on the simple idea that
medicine is strictly about health.
* lurks :Elephant:
[2021-04-08 Thu 17:57]

To lurk is to creep around, hide out, and wait to attack. Your team’s
strategy for winning capture the flag might be to lurk in the bushes
for an hour until the opposing side thinks you gave up and went home.

The verb lurk means to move furtively or sneak around, usually while
you wait to pounce. Tigers lurk through the jungle, stalking their
prey, and creepy characters are always lurking in the shadows in
horror movies. Perhaps that's why you'll often hear people describe
not-so-safe places by saying that danger lurks at every turn.  Other
words for lurk include creep, prowl, and snoop.

Robin’s hypothesis is that a similar transaction lurks within our modern
medical system, except we don’t notice it because it’s masked by all the
genuine healing that takes place. In other words, expensive medical care does
heal us, but it’s simultaneously an elaborate adult version of “kiss the
boo-boo.” In this transaction, the patient is assured of social support,
while those who provide such support are hoping to buy a little slice of
loyalty from the patient. And it’s not just doctors who are on the “kissing”
or supportive side of the transaction, but everyone who helps the patient
along the way: the spouse who insists on the doctor’s visit, the friend who
watches the kids, the boss who’s lenient about work deadlines, and even the
institutions, like employers and national governments, that sponsored the
patient’s health insurance in the first place. Each of these parties is
hoping for a bit of loyalty in exchange for their support. But the net result
is that patients end up getting more medicine than they need strictly for
their health.
* lenient :Elephant:
[2021-04-08 Thu 17:59]

If you're not overly strict, and you show tolerance and mercy when
someone does something wrong, you're being lenient.

Lenient means tolerant or relaxed, and is usually used when we’re
talking about someone’s attitude toward discipline. In 19th-century
child-rearing books, we often read about strict teachers who punish
children just for squirming in their seats. These days teachers are
more likely to be lenient, more understanding. If you're a big fan of
discipline and punishment, however, lenient might mean "soft" or
"indulgent."

Robin’s hypothesis is that a similar transaction lurks within our modern
medical system, except we don’t notice it because it’s masked by all the
genuine healing that takes place. In other words, expensive medical care does
heal us, but it’s simultaneously an elaborate adult version of “kiss the
boo-boo.” In this transaction, the patient is assured of social support,
while those who provide such support are hoping to buy a little slice of
loyalty from the patient. And it’s not just doctors who are on the “kissing”
or supportive side of the transaction, but everyone who helps the patient
along the way: the spouse who insists on the doctor’s visit, the friend who
watches the kids, the boss who’s lenient about work deadlines, and even the
institutions, like employers and national governments, that sponsored the
patient’s health insurance in the first place. Each of these parties is
hoping for a bit of loyalty in exchange for their support. But the net result
is that patients end up getting more medicine than they need strictly for
their health.
* conspicuous :Elephant:
[2021-04-08 Thu 18:00]

Keep your eye on the adjective conspicuous for something that stands
out so much you notice it right away — like that zit in the center of
your friend's forehead.

Conspicuous comes from the adjectival form of the Latin verb,
conspicere, meaning "to look at." Conspicuous can mean either very
obvious to the eye (like something that is conspicuous from a
distance) or attracting attention (like conspicuous consumption). If
you are doing something wrong, it's wise not to be conspicuous about
it!

The conclusion is that medicine isn’t just about health—it’s also an exercise
in conspicuous caring.
* morphed :Elephant:
[2021-04-08 Thu 18:03]

To morph is to change from one shape to another. A cute bunny, for
example, might morph into a killer dragon in a fairy tale or an
animated film.

Morph comes from the word metamorphosis, which is a Greek word meaning
"a transforming." As a verb, it has only been around since the 1980s,
when computers allowed animators to make things change shape in an
apparently seamlessly way. With the right skills, you can morph a
toaster into a highly intelligent robot that helps fight crime, offers
dating advice to the protagonist of the film, and still makes an
excellent piece of toast.

Initially, Kevin took the startup scene for a straightforward exercise in
company-building: gather some people together; give them time to think, talk,
and write code; and eventually, like Legos clicking into place, out pops
useful software. Then he read Hierarchy in the Forest by anthropologist
Christopher Boehm, a book that analyzes human societies with the same
concepts used to analyze chimpanzee communities. After reading Boehm’s book,
Kevin began to see his environment very differently. An office full of
software engineers soon morphed, under the flickering fluorescent lights,
into a tribe of chattering primates. All-hands meetings, shared meals, and
team outings became elaborate social grooming sessions. Interviews began to
look like thinly veiled initiation rituals. The company logo took on the
character of a tribal totem or religious symbol.
* thinly :Elephant:
[2021-04-08 Thu 18:04]



nil

Initially, Kevin took the startup scene for a straightforward exercise in
company-building: gather some people together; give them time to think, talk,
and write code; and eventually, like Legos clicking into place, out pops
useful software. Then he read Hierarchy in the Forest by anthropologist
Christopher Boehm, a book that analyzes human societies with the same
concepts used to analyze chimpanzee communities. After reading Boehm’s book,
Kevin began to see his environment very differently. An office full of
software engineers soon morphed, under the flickering fluorescent lights,
into a tribe of chattering primates. All-hands meetings, shared meals, and
team outings became elaborate social grooming sessions. Interviews began to
look like thinly veiled initiation rituals. The company logo took on the
character of a tribal totem or religious symbol.
* unaware :Elephant:
[2021-04-08 Thu 18:10]

Unaware is simply the opposite of "aware." If you are unaware, you
have no idea what's going on.

To be unaware is to be totally incognizant (but not incontinent). To
be "caught unawares" means you were caught off guard or by
surprise. Either way you've got your head in the clouds about
something. Now some people might say that ignorance is bliss, but the
guy in the crosswalk who was unaware of the bus barreling down on him
at full speed might disagree.

But this is odd. Why should we be less than fully conscious of such important
motives? Biology teaches us that we’re competitive social animals, with all
the instincts you’d expect from such creatures. And consciousness is
useful—that’s why it evolved. So shouldn’t it stand to reason that we’d be
hyper-conscious of our deepest biological incentives? And yet, most of the
time, we seem almost willfully unaware of them.
* flinch :Elephant:
[2021-04-08 Thu 18:11]

To flinch is to react to pain by wincing, pulling away, or
cringing. Often it's used to describe a person who shows a moment of
weakness or fright: he was so tough, I thought he'd never flinch, but
snakes really freak him out.

To flinch is to pull away suddenly or recoil when something frightens
or hurts you. People flinch at different things. Needles, for example,
cause some people to flinch, while they're not even noticed by
others. If you can withstand something awful without showing it,
you're likely to hear someone say "Wow! You didn't even flinch!" Think
of it as a combination of flee and pinch. If you don't flee when you
get pinched, you don't flinch.

It’s not that we’re literally incapable of perceiving these motives within
our psyches. We all know they’re there. And yet they make us uncomfortable,
so we mentally flinch away.
* ploy :Elephant:
[2021-04-09 Fri 10:15]

A ploy is a clever plan that helps you get what you want. A
manipulative little girl might shed tears simply as a ploy to get her
mother to buy her ice cream.

A politician might add amendments to a bill as a ploy to delay voting,
or a hooligan might yell, "Fire!" in a movie theater as a ploy to
sneak his friends in. A sneaky move in a game is a ploy, and
sensational news about a celebrity can be just a ploy to get him more
media attention. The first recorded use of ploy was in 1722, meaning
"anything with which one amuses oneself" in Scottish and Northern
English dialects.

Self-deception is therefore strategic, a ploy our brains use to look good
while behaving badly. Understandably, few people are eager to confess to this
kind of duplicity. But as long as we continue to tiptoe around it, we’ll be
unable to think clearly about human behavior. We’ll be forced to distort or
deny any explanation that harks back to our hidden motives. Key facts will
remain taboo, and we’ll forever be mystified by our own thoughts and actions.
* duplicity :Elephant:
[2021-04-09 Fri 10:16]

Though he said he didn't know anything about the footprints in the new
sidewalk, his duplicity, or deceitfulness, was obvious from the cement
caking his shoes. His mouth said one thing, his feet said another.

Many words with "du" have meanings with "two" or "duo." Duplicity is
from a Latin word meaning "twofold, having two parts." Someone who
shows duplicity is two-faced — maybe showing one side in public and
another in private — or is just a liar, saying something known to be
untrue or misleading. A fraud uses duplicity to gain something with
false promises, and someone described as "fake" might use duplicity
just to fit in or be accepted.

Self-deception is therefore strategic, a ploy our brains use to look good
while behaving badly. Understandably, few people are eager to confess to this
kind of duplicity. But as long as we continue to tiptoe around it, we’ll be
unable to think clearly about human behavior. We’ll be forced to distort or
deny any explanation that harks back to our hidden motives. Key facts will
remain taboo, and we’ll forever be mystified by our own thoughts and actions.
* harks :Elephant:
[2021-04-09 Fri 10:18]

Hark! This is an old fashioned word for “listen up!” Hark also means
“to look back.” If you ride a horse to school, your behavior harks
back to the days before cars.

Hark is an order to pay attention and listen carefully, but it also
means to go back to or remember something from the past. Hark has an
interesting origin: it comes from the term "to hark back," which was
when hunting dogs retraced the scent of their prey when they had lost
it to try to pick it up again. Using hark these days sounds very
literary and old fashioned. It harks back to ye olde times.

Self-deception is therefore strategic, a ploy our brains use to look good
while behaving badly. Understandably, few people are eager to confess to this
kind of duplicity. But as long as we continue to tiptoe around it, we’ll be
unable to think clearly about human behavior. We’ll be forced to distort or
deny any explanation that harks back to our hidden motives. Key facts will
remain taboo, and we’ll forever be mystified by our own thoughts and actions.
* confronting :Elephant:
[2021-04-09 Fri 10:21]

Confront means either to face a situation that makes you
uncomfortable, or to say something to someone about something they've
done that bothers you. Rather than letting things go, when people are
rude to you you should confront them.

Confront derives from the Latin con- "with" and -front "front." You
can confront a sad truth, you can confront a person by calling them on
their behavior, you can confront someone with the fact that they have
terrible breath. You can be confronted, too—on the trip through the
mountains, we were confronted by the impassibility of the road.

It’s only by confronting the elephant, then, that we can begin to see what’s
really going on.
* unsavory :Elephant:
[2021-04-09 Fri 10:21]

Call something unsavory if it's unappetizing, tasteless, or morally
offensive. Curdled sour milk is pretty unsavory, as are the dirty
details of the latest political scandal.

The adjective unsavory was formed by merging un, meaning “not,” with
savory, meaning “pleasant, agreeable.” So if it's unsavory, it's
unpleasant. First used to describe revolting tastes, unsavory now also
applies to just about anything that figuratively leaves a bad taste in
your mouth. Mobsters do all kinds of unsavory things to the people
that cross them. So you probably shouldn't hang out with such unsavory
characters.

Again, it’s not that we’re completely unaware of our unsavory motives—far
from it. Many are readily apparent to anyone who chooses to look. For each
“hidden” motive that we discuss in the book, some readers will be acutely
aware of it, some dimly aware, and others entirely oblivious. This is why
we’ve chosen the elephant as our metaphor (see Box 1). The elephant—whether
in a room or in our brains—simply stands there, out in the open, and can
easily be seen if only we steel ourselves to look in its direction (see
Figure 1). But generally, we prefer to ignore the elephant, and as a result,
we systematically give short shrift to explanations of our behavior that call
attention to it.
* shrift :Elephant:
[2021-04-09 Fri 10:23]

Use the noun shrift to describe the act of confessing, especially to a
priest.

Shrift is an old-fashioned way to talk about the traditional religious
ritual of confession and absolution. Shrift comes from the equally
antique word shrive, which is what a priest does when he hears a
confession. The phrase "short shrift" began as a description of the
brief chance a condemned prisoner had to confess his sins before being
put to death, and evolved to mean "to dismiss with little
consideration."

Again, it’s not that we’re completely unaware of our unsavory motives—far
from it. Many are readily apparent to anyone who chooses to look. For each
“hidden” motive that we discuss in the book, some readers will be acutely
aware of it, some dimly aware, and others entirely oblivious. This is why
we’ve chosen the elephant as our metaphor (see Box 1). The elephant—whether
in a room or in our brains—simply stands there, out in the open, and can
easily be seen if only we steel ourselves to look in its direction (see
Figure 1). But generally, we prefer to ignore the elephant, and as a result,
we systematically give short shrift to explanations of our behavior that call
attention to it.
* intrinsic :Money:
[2021-04-09 Fri 10:57]

The intrinsic qualities of something have to do with its nature. An
intrinsic quality of dogs is that they're loyal.

Anything intrinsic comes from within. Doing a job for only money is
not intrinsic. Doing a job because you love it is intrinsic; the
motivation comes from within. It's good to treat people as having
intrinsic value. If you like someone for intrinsic reasons, then you
have no other motivation. The opposite of intrinsic is extrinsic, for
things that come from the outside instead of from the inside.

Money’s greatest intrinsic value—and this can’t be overstated—is its ability
to give you control over your time. To obtain, bit by bit, a level of
independence and autonomy that comes from unspent assets that give you
greater control over what you can do and when you can do it.
* obtain :Money:
[2021-04-09 Fri 10:58]

Obtain means to get something that is not so easy to come by such as
knowledge, rights, or a large amount of money. You wouldn't say you
obtained a pair of pants, unless they were one of a kind.

At times in its history, obtain has meant to be victorious or to
succeed. Today, it mostly means to acquire, but keeping its prior
meanings in mind helps you to use it in the right way. College degrees
are something that you obtain as is permission from your parents to go
to a party. When you obtain something, you have worked hard to get it,
so you are pretty happy to have it.

Money’s greatest intrinsic value—and this can’t be overstated—is its ability
to give you control over your time. To obtain, bit by bit, a level of
independence and autonomy that comes from unspent assets that give you
greater control over what you can do and when you can do it.
* reactance :Money:
[2021-04-09 Fri 11:03]



nil

There is a name for this feeling. Psychologists call it reactance. Jonah
Berger, a marketing professor at the University of Pennsylvania, summed it
up well:
* recluse :Money:
[2021-04-09 Fri 11:13]

A recluse lives alone, works alone, eats alone, and generally stays
away from other people. Anti-social old hermits are recluses, as are a
lot of students during exam time.

In the early 13th century, a recluse was a person who shut out the
world to go meditate on religious issues. But nowadays recluses can
think about whatever they want while they're sitting in solitude —
they're simply people who shy away from social interaction and live
secluded lives. Or think of the Brown Recluse spider, who likes to
hide out in dark old boots or undisturbed corners of the basement.

He was also a recluse, spending most of his time by himself. He rarely
spoke, deliberately making himself inaccessible and staying quiet when you
caught his attention.
* deliverable :Money:
[2021-04-09 Fri 11:16]



nil

Rockefeller’s job wasn’t to drill wells, load trains, or move barrels. It
was to think and make good decisions. Rockefeller’s product—his
deliverable—wasn’t what he did with his hands, or even his words. It was
what he figured out inside his head. So that’s where he spent most of his
time and energy. Despite sitting quietly most of the day in what might have
looked like free time or leisure hours to most people, he was constantly
working in his mind, thinking problems through.