-*- coding: utf-8 -*-


* tangible :misc:
[2021-04-05 Mon 11:10]

When you can touch something, it's tangible: "I need tangible proof
that aliens exist — I want to shake their little green hands!"

Tangible is from Latin tangere, "to touch," and it simply means
something that can be touched or felt, though it can be used in
metaphorical senses: tangible assets have a value that can be
precisely measured, and tangible grief can be clearly sensed by an
onlooker. So you might not need to physically touch something for it
to be tangible, but it has to be grounded in the real world of facts:
"Has the teen pop star demonstrated any tangible ability to sing?"

Our standard of living increased 20-fold in these 170 years, but
barely a day went by that lacked tangible reasons for pessimism.
* invincible :misc:
[2021-04-05 Mon 11:11]

Something invincible is victorious over everything. Disease, death,
destruction? No match for something truly invincible. Mere humans who
imagine they're invincible, however, will inevitably prove that
they're not.

Invincible comes ultimately from the Latin verb vincere, "to conquer."
Many of the uses for invincible are for describing someone or
something victorious or unbeatable at what they do. A company can be
invincible when it outsells similar businesses for years, a tennis
player is invincible after winning all of the majors in a year or a
career, and Superman and the Indomitable Snowman are invincible as
long as they stay away from kryptonite and the warm sun.

He associated good times with the end of bad times. Getting wealthy made him
feel like staying wealthy was inevitable, and that he was invincible. After
losing nearly everything he reflected:
* invince
* belabor :misc:
[2021-04-05 Mon 11:13]

Belabor means to go at something with everything you've got. When you
say, "Don't belabor or agonize over the decision," it means, "Move
on."

Belabor is made up of the Latin roots be and labor meaning "to exert
one's strength upon." You can belabor a point by using excessive
detail, or you could belabor the obvious by stating over and over what
everyone already knows. Belaboring can be a physical attack as well. A
person can belabor or beat the living daylights out of you with a
club.

“I’ve been banging away at this thing for 30 years. I think the simple math
is, some projects work and some don’t. There’s no reason to belabor either
one. Just get on to the next.”
* bargain :misc:
[2021-04-05 Mon 11:15]

The table you bought at a yard sale for five dollars might seem like a
bargain until you get it home and realize it only has three legs. A
bargain is a good deal.

Inexpensive items are one type of bargain, and another kind of bargain
is an agreement you make with someone — a deal or compromise. Two
countries might strike a trade bargain, or you could make a bargain
with your friend that you'll drive to the mall if she buys you a giant
cinnamon roll. Bargain also means to negotiate the details of a
purchase, which makes sense because the root word is bargaignier,
French for "haggle over the price."

It was such a bargain that the Germans effectively considered it a donation.
* preemptively :misc:
[2021-04-05 Mon 11:18]

A preemptive action is made to keep some other action from being
taken.  Before you could be accused of eating the whole cake, you
decided to make a preemptive apology, which was met with awkward
silence.

Tired of being disturbed by your roommate's loud music, your
preemptive strike was to crank up your favorite opera as soon as you
arrived home.  Unfortunately, he'd already made a preemptive strike of
his own by borrowing your stereo.  Don't confuse preemptive with
peremptory, a word meaning “arrogant.” You don't have to be arrogant
to make a preemptive move, just cautious.

The Chris Rock I see on TV is hilarious, flawless. The Chris Rock that
performs in dozens of small clubs each year is just OK. That is by design. No
comedic genius is smart enough to preemptively know what jokes will land
well. Every big comedian tests their material in small clubs before using it
in big venues. Rock was once asked if he missed small clubs. He responded:
* preemptive
* fumbling :misc:
[2021-04-05 Mon 11:20]



nil

One newspaper profiled these small-club sessions. It described Rock thumbing
through pages of notes and fumbling with material. “I’m going to have to cut
some of these jokes,” he says mid-skit. The good jokes I see on Netflix are
the tails that stuck out of a universe of hundreds of attempts.
* fumble
* thumbing :misc:
[2021-04-05 Mon 11:21]

Your thumb is the fifth digit on your hand, the one that doesn't quite
match your fingers. Thumbs help us grip objects with care and
precision — it would be difficult to hold chopsticks without a thumb.

Humans are more dextrous than our closest primate relatives because of
our nimble thumbs. They're opposable, so we can move them forward and
touch them to our fingers. Some monkeys share this trait, and they're
the best able to use primitive tools. Your thumbs make it possible for
you to brush your teeth, write with a pen, and snap. You can also
thumb through the pages of a book — in other words, turn each page
with your thumb.

One newspaper profiled these small-club sessions. It described Rock thumbing
through pages of notes and fumbling with material. “I’m going to have to cut
some of these jokes,” he says mid-skit. The good jokes I see on Netflix are
the tails that stuck out of a universe of hundreds of attempts.
* thumb
* incur                                                                :misc:
[2021-04-05 Mon 12:01]

To incur is to get or receive — and usually it's something you brought
upon yourself. If you don't pay your credit card bills on time, you'll
likely incur lots of fees and some serious debt.

Generally, when you incur something, that something is
undesirable. You can incur penalties, expenses, a parking ticket, or a
friend’s wrath, for example. But it's pretty unlikely that you'd incur
free tickets to the World Series. Frederick Douglass once famously
said, “I prefer to be true to myself, even at the hazard of incurring
the ridicule of others, rather than to be false, and to incur my own
abhorrence."

Part of why this isn’t intuitive is because in most fields we only see the
finished product, not the losses incurred that led to the tail-success
product.
* horrendous :misc:
[2021-04-05 Mon 12:02]

Bad luck, an injury, a mistake, an unfortunate outfit, or a crime —
anything can be called horrendous if it causes such dread or fear that
you can barely even think about it.

If you’ve ever encountered something horrendous, you won’t be
surprised to learn that the word traces back to the Latin word
horrere, meaning "to bristle with fear, shudder." That’s a good way to
think about horrendous things — they cause you to shudder. You can use
the word to describe any type of thing — people, ideas, actions, and
so on — but save it for those things that are not merely bad but
instead are truly horrifying.

Something I’ve learned from both investors and entrepreneurs is that no one
makes good decisions all the time. The most impressive people are packed
full of horrendous ideas that are often acted upon.
* quip :misc:
[2021-04-05 Mon 12:02]

A quip — a short, witty comment — can be pleasant, wise, or sarcastic,
but usually carries an element of humor.

A quip is a witty or clever remark that sounds spur-of-the-moment. A
successful quip must sound offhand, as though it were an afterthought,
even if the speaker has been honing the statement for days.  Dorothy
Parker was a famous writer known for her quick quips, such as, "The
best way to keep children home is to make the home atmosphere pleasant
— and let the air out of the tires."

There is the old pilot quip that their jobs are “hours and hours of boredom
punctuated by moments of sheer terror.” It’s the same in investing. Your
success as an investor will be determined by how you respond to punctuated
moments of terror, not the years spent on cruise control.
* genius :misc:
[2021-04-05 Mon 12:02]

Genius is an exceptional talent or skill, something above and beyond
the norm. A genius is someone who possesses this brilliance, like a
child prodigy who learned the piano at age 3 and played sold-out
concerts by age 5.

Genius comes from the Latin word of the same name, meaning "guardian
deity or spirit which watches over each person from birth" or "innate
ability."  Your genius — your superior talent — at the game of chess
could make you a world champion. Your amazing genius would also make
you a genius. The word can be used more lightheartedly to describe a
natural ability or flair for something. You may have a genius for
putting together stylish outfits.

Napoleon’s definition of a military genius was, “The man who can do the
average thing when all those around him are going crazy.”
* dud                                                                  :misc:
[2021-04-05 Mon 12:04]

Your duds are your clothes. Your grandmother might hand you a hundred
dollar bill at the mall and say, "Go buy yourself some new duds."

The noun duds is an informal, slang term for "clothing." You can pack
your duds in a suitcase before a vacation or arrange your duds by
color in your closet. Though experts aren't sure where the word duds
came from originally, they know that it was dudde in the 1300s, which
meant "cloak or mantle," and later came to be duddes and to mean
"ragged clothing."

Most public companies are duds, a few do well, and a handful become
extraordinary winners that account for the majority of the stock market’s
returns.
* stupendously :misc:
[2021-04-05 Mon 12:04]



nil

Perhaps 99% of the works someone like Berggruen acquired in his life turned
out to be of little value. But that doesn’t particularly matter if the other
1% turn out to be the work of someone like Picasso. Berggruen could be wrong
most of the time and still end up stupendously right.
* stupendous
* exclusive :misc:
[2021-04-05 Mon 12:05]

Exclusive means with limited access. The only way you might get
reservations at one of the most exclusive restaurants in Los Angeles
is to become friends with the maitre d', or become famous.

By its nature, something that is exclusive leaves people out, or
excludes them. You would think this was a bad thing, since excluding
people is not very nice, but by being exclusive, things like clubs,
restaurants, and resorts become all the more desirable. Exclusive can
also mean sole or only: The company became the exclusive soda vendor
at the new stadium. The local newspaper got an exclusive interview and
broke the news.

Optimism is usually defined as a belief that things will go well. But that’s
incomplete. Sensible optimism is a belief that the odds are in your favor,
and over time things will balance out to a good outcome even if what happens
in between is filled with misery. And in fact you know it will be filled
with misery. You can be optimistic that the long-term growth trajectory is
up and to the right, but equally sure that the road between now and then is
filled with landmines, and always will be. Those two things are not mutually
exclusive.
* excluse
* laughs :misc:
[2021-04-05 Mon 12:06]

To let out a chuckle or giggle is to laugh: people laugh when
something is funny.

To chortle, cackle, guffaw, or titter is to laugh. The job of a
comedian is to make people laugh. Often people laugh at things that
aren't supposed to be funny, and people also laugh to be polite. If
something is silly, you can say "That's a laugh!" If you had fun at a
party, you can say "Thanks for the laughs." Everybody's laugh sounds a
little different. It would be a shame if your laugh sounded like Elmer
Fudd.

What’s the saying? You plan, God laughs. Financial and investment planning
are critical, because they let you know whether your current actions are
within the realm of reasonable. But few plans of any kind survive their
first encounter with the real world. If you’re projecting your income,
savings rate, and market returns over the next 20 years, think about all the
big stuff that’s happened in the last 20 years that no one could have
foreseen: September 11th, a housing boom and bust that caused nearly 10
million Americans to lose their homes, a financial crisis that caused almost
nine million to lose their jobs, a record-breaking stock-market rally that
ensued, and a coronavirus that shakes the world as I write this.
* gnaw :misc:
[2021-04-05 Mon 12:06]

To gnaw is to bite or chew. Your favorite food might be corn on the
cob, because you love to gnaw along each row of kernels.

To gnaw also means to deteriorate or wear away as if by gnawing with
the teeth. In Arches National Park, the weather has gnawed away at the
rocks creating beautiful formations like arches, bridges, and balanced
rocks. In this sense, to gnaw can be used even more
figuratively. Something might gnaw at the back of your mind —
something you were supposed to do, although now you can't quite
remember what it was.

No one wants to hold cash during a bull market. They want to own assets that
go up a lot. You look and feel conservative holding cash during a bull
market, because you become acutely aware of how much return you’re giving up
by not owning the good stuff. Say cash earns 1% and stocks return 10% a
year. That 9% gap will gnaw at you every day.
* complacent :misc:
[2021-04-05 Mon 12:06]

Someone who is complacent has become overly content — the
junk-food-eating couch potato might be feeling complacent about his
health.

The literal meaning of this word's Latin root is "very pleased," but
even though complacent people may seem pleased with themselves, we are
rarely pleased with them. They are unconcerned by things that should
concern them, and they may neglect their duties. A complacent person
might be heard saying, "Ehh, don't worry about it!" — when there
really is something to worry about.

Moritz: There’s a lot of truth to that … We assume that tomorrow won’t be
like yesterday. We can’t afford to rest on our laurels. We can’t be
complacent. We can’t assume that yesterday’s success translates into
tomorrow’s good fortune.
* complace
* takeaway :misc:
[2021-04-05 Mon 12:09]



nil

The practical takeaway is that the counterintuitiveness of compounding may
be responsible for the majority of disappointing trades, bad strategies, and
successful investing attempts.

* clamor :misc:
[2021-04-05 Mon 21:16]

To clamor is to make a demand — LOUDLY. It's usually a group that
clamors — like Americans might clamor for comprehensive health care
coverage.

The noun clamor is often used specifically to describe a noisy outcry
from a group of people, but more generally, the word means any loud,
harsh sound. You could describe the clamor of sirens in the night or
the clamor of the approaching subway in the tunnel.

As we put our final touches on this book, we find that our thoughts are now
mostly elsewhere. This is, in part, because other tasks and projects clamor
for our attention, but also because it’s just really hard to look long and
intently at our selfish motives, at what we’ve called “the elephant in the
brain.” Even we, the authors of a book on the subject, are relieved for the
chance to look away, to let our minds wander to safer, more comfortable
topics.
* fads :misc:
[2021-04-06 Tue 16:38]

If it’s all the rage, everybody’s into it, your parents don’t get it,
and teenage girls across the globe are trying to outdo each other with
it, it’s officially a fad.

From hairstyles to hula hoops to saying “that’s hot,” fads are known
to rise to crazed levels of popularity seemingly overnight. But they
fade out just as fast, leaving late adopters with outdated sayings and
some seriously uncool shoes. Much like a fad itself, no one has any
real idea where this word came from. But it’s still in fashion some
144 years later.

The reason I was interested was because I was meant to be writing a second
book, but I had no idea what it should be about. Everyone I asked gave
different suggestions, but eventually always said, ‘Just write about what
makes you happy.’ As a very literal, scientifically minded type, I tried to
look this up: what does make us happy? But all I found was an avalanche of
management fads and techniques, cod philosophy, self-help manuals, life
coaches and gurus, all of varying degrees of dubiousness, and all insisting
that they definitely knew the secret to happiness, no matter who you are. I
wouldn’t mind so much, but barely any of these ‘secrets’ matched up,
suggesting that a lot of them might be nonsense.
* credible :misc:
[2021-04-06 Tue 16:42]

Someone who's credible is honest and believable. A pathological liar,
for example, might not be the most credible witness for your case
against the bank robber.

Similar to words like reliable and plausible, credible is an adjective
that comes to us from the Latin credibilis, meaning “worthy to be
believed.” A credible reputation is often earned through consistent
good behavior and an overall trustworthy personality. Spill a secret
you promised to keep, or lie under oath in a courtroom, and you lose
all credibility.

Even more annoying for a doctor of neuroscience, science writer and apparent
go-to guy for mainstream commentary on brain-based news like me, is that a
lot of these so-called secrets invoke my discipline, or constantly refer to
some valid-sounding-but-unspecific aspect of the brain’s functioning, like
‘dopamine’ or ‘oxytocin’ or ‘emotion centres’, in support of their claims. If
you’re an experienced neurobod, you can easily spot when someone is just
borrowing the terminology of your field to sound credible, rather than
actually having any useful understanding of it.
* smattering :misc:
[2021-04-06 Tue 16:43]

A smattering is a small but inexact amount of something. If you know a
smattering of things about Australia, then you don't know much.

A smattering is a small amount of something, but it's hard to say how
much. It's probably less than a bunch, but it's not much more than a
whit or a jot. If you said "There's a smattering of squirrels in the
park," then there are only a few squirrels. This word also implies
that you don't understand a subject very well — a smattering of
knowledge is only a tiny bit of knowledge.

And I thought, you know what? If you’re going to exploit my field, at least
put some effort into it. Sure, the brain isn’t perfect, I’m often the first
person to point that out, but it’s still one of the most fantastically and
terrifyingly complex things to study. To truly explain how the brain deals
with happiness would take more than a vague two-line summary or a smattering
of impressive-sounding terminology, it would take a whole book …
* grievances :misc:
[2021-04-06 Tue 16:44]

A grievance is a complaint.  It can be formal, as when an employee
files a grievance because of unsafe working conditions, or more of an
emotional matter, like a grievance against an old friend who betrayed
you.

A grievance is a complaint that may or may not be justified. Often a
grievance is a complaint about something that breaks a rule or a law,
like a grievance filed against a person who builds a fence in his
front yard in a town that does not allow that. If that same neighbor
plants flowers he knows make you sneeze uncontrollably, you might be
unhappy about that, but this is the kind of grievance you can work out
among yourselves.

And that’s when it dawned on me. I could write that book! The one about how
the brain really handles happiness at the fundamental levels. And that’s the
book you’re holding now. Because if there’s one thing I do, it’s go to
ridiculous extremes to settle minor grievances, even if the party that caused
them remains blissfully unaware of my existence.
* blissfully :misc:
[2021-04-06 Tue 16:44]



nil

And that’s when it dawned on me. I could write that book! The one about how
the brain really handles happiness at the fundamental levels. And that’s the
book you’re holding now. Because if there’s one thing I do, it’s go to
ridiculous extremes to settle minor grievances, even if the party that caused
them remains blissfully unaware of my existence.
* abundantly :misc:
[2021-04-06 Tue 16:46]



nil

One thing that is abundantly clear from the sheer variety of supposed
‘secrets’ to happiness is that it has an undeniably strong subjective
element. We all have different ideas of what makes, or will make, us happy,
be it wealth, fame, love, sex, power, laughter, and so on. And yet we can
only ever truly know what works for us. So, I wanted to include insights from
a wide range of people from different walks of life, to see what makes them
happy (or not). As a result, I ended up talking with stars of stage and
screen, millionaires, leading scientists, journalists, ghost-hunters and one
person who … well, let’s just say that in no other research I’ve done did I
ever hear the term ‘sex dungeon’ used so freely and so often.
* dungeon :misc:
[2021-04-06 Tue 16:47]

That dank, stone-walled underground prison where wretched prisoners
were kept manacled in medieval days? That was a dungeon, otherwise
known as the "keep," and most familiar to us today from a million
video games and movies.

In fact, the original meaning of dungeon was of something overground
rather than underground, coming from the Old French term donjon,
meaning the "great tower of a castle," and the underground meaning
only came later. Rapunzel in the fairy tale was held captive in a
tower rather than an underground cell and if she hadn't been, her long
hair wouldn't have been much help in her escape.

One thing that is abundantly clear from the sheer variety of supposed
‘secrets’ to happiness is that it has an undeniably strong subjective
element. We all have different ideas of what makes, or will make, us happy,
be it wealth, fame, love, sex, power, laughter, and so on. And yet we can
only ever truly know what works for us. So, I wanted to include insights from
a wide range of people from different walks of life, to see what makes them
happy (or not). As a result, I ended up talking with stars of stage and
screen, millionaires, leading scientists, journalists, ghost-hunters and one
person who … well, let’s just say that in no other research I’ve done did I
ever hear the term ‘sex dungeon’ used so freely and so often.
* warn :misc:
[2021-04-06 Tue 16:48]

When you warn someone, you advise them to be careful or tell them
about a problem or danger. If you perform a dangerous stunt, you
should probably warn your audience, "Don't try this at home."

Many traffic signs are meant to warn drivers about hazards, like
bridges that get slippery in the rain or bumps in the road. And the
purpose of a dog's growl is to warn another dog (or human) that it's
stressed or fearful. A warning is a helpful message, no matter what
form it comes in, and to warn is to send this message. The Old English
root is warnian, "give notice of impending danger."

I should warn you though, that this is not meant to be a self-help book, or
some model for how to live a happier and fuller life, or anything like that.
* din :misc:
[2021-04-06 Tue 19:32]

Walk into the average school cafeteria at lunchtime, and you'll get a
good sense of what a din is — loud, confused, continuous, generally
unpleasant, and often potentially headache-inducing noise.

Who knew noise pollution was a problem in ancient times? Humans have
been experiencing loud, sustained, annoying sounds for centuries,
judging by the etymology of the word din. It traces its roots back to
Old English dyne or dynn, which had the same meaning as din does
today, only with a different pronunciation. Before that, it popped up
in Old Norse as dynr and meant to "come rumbling down" — fitting, from
the language that gave us Thor, the God of Thunder.

Would you like to be stuffed head first into a tube, a cold and confining
one, where you’re not allowed to move? For hours at a time? A tube that makes
incredibly loud noises, an ongoing din of clicks and screeches like an
enraged metal dolphin?
* fairly :misc:
[2021-04-06 Tue 19:46]

When you do something fairly, you treat everyone with equal
consideration. Sharing a pizza fairly between six people is easy: just
give each person one slice.

A teacher who doesn't treat all students fairly isn't a very good
teacher — and a police officer who doesn't act fairly toward all
citizens is also doing a poor job. When you behave fairly, you're
unbiased and impartial, and you follow the rules. You can also use
this adverb to mean "to a large degree" or "reasonably." For example,
you could say, "I'm fairly certain that it's going to snow again
tomorrow."

But more attentive readers will have noticed that I referred to fMRI. The ‘f’
is important. It stands for ‘functional’, so it’s functional magnetic
resonance imaging. This means that the same approach used to look at the
structure of the body can be adapted to observe the activity of the working
brain, allowing us to witness the interactions occurring between the
countless neurons that make up our brains. It may not sound that impressive,
but this activity is essentially the basis of our mind and consciousness, in
much the same way that individual cells make up our body (cells combine in
complex ways to form tissues, which combine in complex ways to form organs,
which combine to form one functioning entity that is you). Scientifically
speaking, this is a fairly big deal.
* utterly :misc:
[2021-04-06 Tue 19:49]

Utterly is an intensifying word: something utterly delicious is very,
very delicious.

One thing people love to do is exaggerate. You often hear people
talking about how awesome or awful things are. When you're laying it
on thick, utterly is an utterly useful word: it means something
similar to completely, totally, or very. Something utterly
disappointing is extremely disappointing. Something utterly wonderful
is wonderful times ten. When you get tired of writing very, utterly is
a good word choice.

Wrong. While it is technically correct to say that happiness comes from the
brain, it is also essentially a meaningless statement. Because, using that
logic, everything comes from the brain. Everything we perceive, remember,
think and imagine. Every facet of human life involves the brain to some
degree. Despite massing just a few pounds, the human brain does a ridiculous
amount of work and has hundreds of different parts doing thousands of
different things on a second-by-second basis, providing us with the rich
detailed existence we take for granted. So of course happiness comes from the
brain. But that’s like being asked where Southampton is and replying ‘the
solar system’; correct, but utterly unhelpful.
* reward :misc:
[2021-04-06 Tue 20:05]

A reward is something you get for a job well done. If you study hard
for that vocabulary test, an "A" might be the reward in your future.

You can use reward as a verb, as when the mayor rewards a firefighter
who saves a family from a terrible blaze, or as a noun, to talk about
the actual payment or item that's given to the firefighter. People
often offer a reward for the return of lost or stolen things, like
bicycles or jewelry or dogs. Reward meant "a regarding" or "an
observation" in the 1300's, but it soon came to mean "repayment for
some service."

Dopamine is an obvious one. Dopamine is a neurotransmitter that fulfils a
wide variety of functions in the brain, but one of the most familiar and
established is its role in reward and pleasure.2 Dopamine is the
neurotransmitter underpinning all activity in the mesolimbic reward pathway
in the brain, sometimes called the dopaminergic reward pathway in
acknowledgement of this. Whenever the brain recognises that you’ve done
something it approves of (drunk water while thirsty, escaped a perilous
situation, been sexually intimate with a partner, etc.), it typically rewards
this behaviour by causing you to experience brief but often intense pleasure
triggered by the release of dopamine. And pleasure makes you happy, right?
* perilous :misc:
[2021-04-06 Tue 20:06]

Something that is dangerous or very risky can be described with the
adjective perilous. If you are driving in a blizzard, you may kick
yourself for making such a perilous journey.

The adjective perilous comes from the Latin word periculum, meaning
dangerous. Words from the same root include peril, a noun meaning a
dangerous situation, and imperil, a verb meaning to put in danger. The
last thing you want to do as a parent is to imperil your
children. Unfortunately, childhood is filled with peril — from
climbing on the monkey bars to eating paste, dirt, or bugs. If you
think you can prevent all perilous situations, you haven't been a
parent very long!

Dopamine is an obvious one. Dopamine is a neurotransmitter that fulfils a
wide variety of functions in the brain, but one of the most familiar and
established is its role in reward and pleasure.2 Dopamine is the
neurotransmitter underpinning all activity in the mesolimbic reward pathway
in the brain, sometimes called the dopaminergic reward pathway in
acknowledgement of this. Whenever the brain recognises that you’ve done
something it approves of (drunk water while thirsty, escaped a perilous
situation, been sexually intimate with a partner, etc.), it typically rewards
this behaviour by causing you to experience brief but often intense pleasure
triggered by the release of dopamine. And pleasure makes you happy, right?