-*- coding: utf-8 -*-


* mowing :Farm:
[2021-05-03 Mon 08:03]

When you clip grass or other plants, you mow it. If you realize your
front lawn is taller than your dog, it might be time to mow it.

People with grassy lawns usually mow them throughout the growing
season, keeping them neatly trimmed and green. Farmers mow some food
crops and hay as well, when they're ready to be harvested, although
they use different tools to do it, including a curved blade called a
scythe. An old-fashioned meaning of mow is "a stack of hay," or "a
place where hay is stored."

As for
the horses, they knew every inch of the field, and in fact understood the
business of mowing and raking far better than Jones and his men had ever
done.
* grudging :Farm:
[2021-05-03 Mon 08:06]

If you do something in a grudging manner (or grudgingly), you do it
with reluctance. Doing homework, paying taxes, and saying sorry are
all commonly done in a grudging manner.

"Grudging apology" and "grudging acceptance" are probably the two most
common uses of this word, which perhaps says something about our lack
of grace as a species. The word derives from the medieval French word
groucher, meaning "to murmur or mumble." A related word is grudge,
meaning a long-lasting sense of ill will dating to a previous
incident.

Every
mouthful of food was an acute positive pleasure, now that it was truly their
own food, produced by themselves and for themselves, not doled out to them
by a grudging master.
* cockerels :Farm:
[2021-05-03 Mon 08:08]



nil

He had made an arrangement with one of the cockerels to call him in
the mornings half an hour earlier than anyone else, and would put in some
volunteer labour at whatever seemed to be most needed, before the regular
day’s work began.
* obstinate :Farm:
[2021-05-03 Mon 08:11]

When someone is beyond stubborn, use the word obstinate instead: "You
obstinate old mule! Get out of my way!"

While stubborn may have positive or negative connotations, obstinate
is most definitely negative, because it implies a kind of hard-headed
determination not to change your mind even when it might be best to
rethink your position. "The obstinate Man does not hold Opinions, but
they hold him," wrote Samuel Butler way back in the seventeenth
century. The word still does the trick if you want a put-down for
someone you think is being a pig-headed fool or a stick in the mud.

He did his work in the same slow obstinate way as he had done it in
Jones’s time, never shirking and never volunteering for extra work
either.
