-*- coding: utf-8 -*-

* facetious :Zen:
[2021-06-21 Mon 17:48]

Don’t take a facetious comment seriously because it’s supposed to be
funny. Anything facetious is a joke. If you've just won a
hotdog-eating contest and someone asks if you'd like to go out for
burgers, they’re probably being facetious.

If you forget how to spell facetious, notice that it has all five
vowels in a row. The word facetious comes from the French facétie,
“joke,” and it has come to describe a joke with a little drop of
sarcasm. It used to simply mean “funny and witty,” but now it often
implies that someone is being inappropriately funny about a serious
topic.

He looks at me pleadingly. He really does want to know things sometimes. Being
facetious is not being a very good father. “Sure,” I say, reversing myself, “I
believe in ghosts too.”

* sheared :Zen:
[2021-06-21 Mon 17:51]



nil

On this trip I think we should notice it, explore it a little, to see if in that
strange separation of what man is from what man does we may have some clues as to
what the hell has gone wrong in this twentieth century. I don't want to hurry
it. That itself is a poisonous twentieth-century attitude. When you want to hurry
something, that means you no longer care about it and want to get on to other
things. I just want to get at it slowly, but carefully and thoroughly, with the
same attitude I remember was present just before I found that sheared pin. It was
that attitude that found it, nothing else.
* tappets :Zen:
[2021-06-21 Mon 17:51]



nil

The overhead-cam chain-tensioner bolt was also missing, meaning it would have
been hopeless to try to adjust the tappets anyway. Nightmare.
* nut :Zen:
[2021-06-21 Mon 17:51]

A nut is a kind of fruit made of a large, edible seed with a very hard
shell around it. The nuts that squirrels typically gather (sometimes
storing them temporarily in their cheek pouches) are acorns.

It might seem strange that a nut is a fruit, since until they've been
cracked open, most nuts are as hard and inedible as rocks. Think of
the meat of a walnut or almond that hides inside — this is the edible
seed within the fruit. If someone calls you a nut, or describes you as
nuts or nutty, they think you're crazy or wacky, and when you refer to
"a tough nut to crack," you're talking about a tricky problem.

I got out of there as fast as possible, noisy tappets, shot tappet covers, greasy
machine, down the road, and then felt a bad vibration at speeds over twenty. At
the curb I discovered two of the four engine-mounting bolts were missing and a
nut was missing from the third. The whole engine was hanging on by only one bolt.
* chisel :Zen:
[2021-06-21 Mon 17:52]

When you carve a statue from a block of marble, you use a tool called
a chisel to cut out the shape. Chisel is the name of the tool and also
the name of the action.

A chisel has a flat, sharp end. To carve using a chisel, you hit the
back of it with a hammer or another blunt instrument. Chisel can also
mean "to cheat." If someone chisels you out of your allowance, they
shaved it away from you bit by bit.

He brought out a hammer and cold chisel and started to pound them loose. The
chisel punched through the aluminum cover and I could see he was pounding the
chisel right into the engine head. On the next blow he missed the chisel
completely and struck the head with the hammer, breaking off a portion of two of
the cooling fins.
* cirrus :Zen:
[2021-06-21 Mon 17:52]



nil

If it's just thunderheads or broken line squalls you can try to ride around
them, but this one isn't. That long dark streak without any preceding cirrus
clouds is a cold front. Cold fronts are violent and when they are from the
southwest, they are the most violent. Often they contain tornadoes. When they
come it's best to just hole up and let them pass over. They don't last long
and the cool air behind them makes good riding.
* demean :Zen:
[2021-06-21 Mon 17:52]

To demean someone is to insult them. To demean is to degrade or put
down a person or thing.

If you noticed the word mean in demean, that's a good clue to its
meaning. To demean someone is very mean. You are demeaning your sister
or brother if you run their underwear up a flagpole. A teacher could
demean a student by saying "You're stupid!" To demean is to insult: no
one wants to be demeaned. Insulting language is often called
demeaning. We can also say a bad president demeaned his office.

I disagree with them about cycle maintenance, but not because I am out of
sympathy with their feelings about technology. I just think that their flight
from and hatred of technology is self-defeating. The Buddha, the Godhead, resides
quite as comfortably in the circuits of a digital computer or the gears of a
cycle transmission as he does at the top of a mountain or in the petals of a
flower. To think otherwise is to demean the Buddhawhich is to demean oneself.
* TRESPASSING :Zen:
[2021-06-21 Mon 17:53]

Something that is trespassing is slowly intruding into where it
doesn't belong. A trespassing stranger is breaking the law.

If you've ever seen a "No trespassing" sign, you probably know it
means "Keep out!" Similarly, anything described as trespassing is
creeping or otherwise moving where it doesn't belong. Trespassing kids
are playing in the neighbor's lawn. A trespassing dog is getting into
the chicken coop. A trespassing tree might be growing where it
shouldn't be and needs to be trimmed. This word always describes
people, animals, and things that go where they shouldn't. Trespassing
things are invasive and encroaching.

That attitude is not hard to come to. You go through a heavy industrial area of a
large city and there it all is, the technology. In front of it are high
barbed-wire fences, locked gates, signs saying NO TRESPASSING, and beyond,
through sooty air, you see ugly strange shapes of metal and brick whose purpose
is unknown, and whose masters you will never see. What it's for you don't
know, and why it's there, there's no one to tell, and so all you can feel
is alienated, estranged, as though you didn't belong there. Who owns and
understands this doesn't want you around. All this technology has somehow made
you a stranger in your own land. Its very shape and appearance and mysteriousness
say, “Get out.” You know there's an explanation for all this somewhere and
what it's doing undoubtedly serves mankind in some indirect way but that
isn't what you see. What you see is the NO TRESPASSING, KEEP OUT signs and not
anything serving people but little people, like ants, serving these strange,
incomprehensible shapes. And you think, even if I were a part of this, even if I
were not a stranger, I would be just another ant serving the shapes. So the final
feeling is hostile, and I think that's ultimately what's involved with this
otherwise unexplainable attitude of John and Sylvia. Anything to do with valves
and shafts and wrenches is a part of that dehumanized world, and they would
rather not think about it. They don't want to get into it.
* faucet :Zen:
[2021-06-21 Mon 17:53]

Water comes out of your faucet and into your sink or bathtub. A faucet
is a device that allows you to turn the flow of water on and off.

The faucet is not just the metal part that the water comes through, it
is the whole mechanism for controlling the flow of water. If you cry
easily, someone might say you are a regular faucet. This is because
water comes out of your eyes more often than it does for most
people. If you ask your parents a little too often for cash, they
might joke that they're going to turn off the money faucet.

It's not the motorcycle maintenance, not the faucet. It's all of technology
they can't take. And then all sorts of things started tumbling into place and
I knew that was it. Sylvia's irritation at a friend who thought computer
programming was “creative.” All their drawings and paintings and photographs
without a technological thing in them. Of course she's not going to get mad at
that faucet, I thought. You always suppress momentary anger at something you
deeply and permanently hate. Of course John signs off every time the subject of
cycle repair comes up, even when it is obvious he is suffering for it. That's
technology. And sure, of course, obviously. It's so simple when you see it. To
get away from technology out into the country in the fresh air and sunshine is
why they are on the motorcycle in the first place. For me to bring it back to
them just at the point and place where they think they have finally escaped it
just frosts both of them, tremendously. That's why the conversation always
breaks and freezes when the subject comes up.
* choke :Zen:
[2021-06-21 Mon 17:53]

When you choke, you are suddenly unable to breathe, often because
something is stuck in your throat. Your dad's rude joke might make you
gasp and choke on your grilled cheese sandwich.

You might choke in a smoky room, or choke on a grape that's lodged
halfway down your throat. In either case, your body can't get enough
oxygen. People also choke up with emotion, figuratively choking on
their sobs. Likewise, a child might complain, "This scarf chokes me!"
— it's uncomfortably tight, but he's not literally unable to
breathe. When the weeds in your garden outnumber the vegetables, you
can also say they choke, or crowd, your plants.

He scratches his head. “Well, why don't they tell you that in the
instructions?” He opens the choke and on the second kick it starts. “I guess that
was it,” he says cheerfully.
* scorcher :Zen:
[2021-06-21 Mon 17:54]



nil

Not a bit of moisture in the sky. Today's going to be a scorcher.
* hoarse :Zen:
[2021-06-21 Mon 17:54]

A hoarse voice is deep and rough and kind of hard to make out. People
get hoarse when they're sick, or when they are calling in sick to
work.

If you're supposed to perform in a play tonight, you'd better hope you
don't get hoarse: a hoarse voice doesn't sound the way it should. It's
scratchy, gruff, and hard to understand. Sometimes people get hoarse
from talking too much. Inhaling smoke can make you hoarse too. On the
other hand, some people have raspy, husky, rough-sounding voices that
sound hoarse all the time. You could ask them, "Are you hoarse?" They
might say, "Nah, I always sound like this."

So it is with John. I could preach the practical value and worth of motorcycle
maintenance till I'm hoarse and it would make not a dent in him. After two
sentences on the subject his eyes go completely glassy and he changes the
conversation or just looks away. He doesn't want to hear about it.
* apparent :Zen:
[2021-06-21 Mon 17:55]

Apparent means obvious, but — and this is confusing — it can also mean
something that seems to be true but isn't definite. "The train's
arrival is apparent — it's in the station — but apparently my friend
missed it because she is not getting off."

It makes sense that apparent has the same ancient root as appear
because it's about what is plain to see. Its subtle power of
suggestion, however, is wonderfully useful. The "heir apparent"
technically means next in line, but the ink isn't dry. The power of
apparent is that it leaves the door open for a little ambiguity. Maybe
the heir apparent will be the next king, or maybe he'll be overthrown
in a bloodless coup by his apparently more ambitious cousin.

And, of course, when you discover something like that it's like discovering a
tooth with a missing filling. You can never leave it alone. You have to probe it,
work around it, push on it, think about it, not because it's enjoyable but
because it's on your mind and it won't get off your mind. And the more I
probe and push on this subject of cycle maintenance the more irritated he gets,
and of course that makes me want to probe and push all the more. Not deliberately
to irritate him but because the irritation seems symptomatic of something deeper,
something under the surface that isn't immediately apparent.
* deadpan :Zen:
[2021-06-21 Mon 17:55]

Use the word deadpan to describe someone who uses no expression when
speaking, such as the deadpan way some comedians deliver even their
funniest jokes — which can make them even funnier.

Deadpan dates to 1928, when pan was slang for "face." So if you seem
to have a "dead face" as you say something, it means your face looks
very blank — no energy or animation. Deadpan is associated with
sarcasm, and like sarcasm, if you use it for comic effect, there's a
risk your audience won't pick up on it. Nevertheless, deadpan humor
can be funny and popular — witness the success of deadpan humor in the
sitcom Seinfeld.

”Let's not start that,” Sylvia says. They look at each other deadpan and then
both look over at me.
* silt :Zen:
[2021-06-21 Mon 17:55]

Silt is the fine bits of clay and sand that become sediment settling
at the bottom of a river or lake. If there's a lot of silt flowing in
a river, it looks murky.

Silt is the super-fine dirt that you might see at the bottom of a lake
or river. When your feet touch silt it feels slimy, and once it’s
stirred it up the water looks muddy. Where the Mississippi River
enters the Gulf of Mexico, a lot of silt has been deposited and over
time has built up a portion of land called the Mississippi Delta. The
region surrounding this accumulation of silt is home to music called
the Delta Blues.

The old channels cannot contain it and in its search for new ones there seems to
be growing havoc and destruction along its banks. In this Chautauqua I would like
not to cut any new channels of consciousness but simply dig deeper into old ones
that have become silted in with the debris of thoughts grown stale and platitudes
too often repeated. “What's new?” is an interesting and broadening eternal
question, but one which, if pursued exclusively, results only in an endless
parade of trivia and fashion, the silt of tomorrow. I would like, instead, to be
concerned with the question “What is best?,” a question which cuts deeply rather
than broadly, a question whose answers tend to move the silt downstream. There
are eras of human history in which the channels of thought have been too deeply
cut and no change was possible, and nothing new ever happened, and “best” was a
matter of dogma, but that is not the situation now. Now the stream of our common
consciousness seems to be obliterating its own banks, losing its central
direction and purpose, flooding the lowlands, disconnecting and isolating the
highlands and to no particular purpose other than the wasteful fulfillment of its
own internal momentum. Some channel deepening seems called for.
* nutty :Zen:
[2021-06-21 Mon 17:57]



nil

”It's completely natural,” I say, “to think of Europeans who believed in
ghosts or Indians who believed in ghosts as ignorant. The scientific point of
view has wiped out every other view to a point where they all seem primitive, so
that if a person today talks about ghosts or spirits he is considered ignorant or
maybe nutty. It's just all but completely impossible to imagine a world where
ghosts can actually exist.”
* swanky                                                               :Dahl:
[2021-06-23 Wed 13:02]

Swanky things are fancy and stylish, like a swanky hotel lobby with
sparkling chandeliers, plush furniture, and elegant guests.

You can also call swanky things ritzy or classy. They're expensive and
luxurious, like a swanky car, a swanky apartment building with a
doorman, or a swanky neighborhood where only movie stars can afford to
live. The adjective swanky comes from its less-common synonym swank,
which stems from the now-obsolete verb swank, "to behave
ostentatiously."

There were no shops on this wide street that he was walking along, only a
line of tall houses on each side, all of them identical. They had porches and
pillars and four or five steps going up to their front doors, and it was obvious
that once upon a time they had been very swanky residences. But now, even in the
darkness, he could see that the paint was peeling from the woodwork on their
doors and windows, and that the handsome white façades were cracked and blotchy
from neglect.
* vault                                                                :Dahl:
[2021-06-23 Wed 13:02]

Vault is a verb that means "to jump over something." If you were
hurrying out to the pasture to visit your favorite cow, you might
vault over the gate in your excitement.

When you support yourself with your hands as you jump over some
hurdle, you vault, just as a gymnast might do across a vault — a piece
of gymnastic equipment made to be vaulted over after a running
start. Another meaning of vault is the arched roof of a building, or
something that resembles such an archway. A storage chamber,
especially one that's kept underground, is also a vault, like a bank
vault.

“So the next problem would be to remove your brain, intact and
 undamaged, from your dead body. The body is useless. In fact it has already
 started to decay. The skull and the face are also useless. They are both
 encumbrances and I don’t want them around. All I want is the brain, the clean
 beautiful brain, alive and perfect. So when I get you on the table I will
 take a saw, a small oscillating saw, and with this I shall proceed to remove
 the whole vault of your skull. You’d still be unconscious at that point so I
 wouldn’t have to bother with anaesthetic.”
* encumbrances                                                         :Dahl:
[2021-06-23 Wed 13:03]

A burden or serious concern is an encumbrance. Your being five feet
tall could be an encumbrance when it comes to your dream of playing
professional basketball.

Something that blocks you from doing what you want to do is an
encumbrance, like the rocky soil in your garden that makes it
impossible for you to grow tomatoes. A burden or hindrance can also be
an encumbrance, the way wearing thick knitted mittens makes it harder
for you to dial your cell phone — your mittens are an encumbrance. The
word comes from the Latin word incombrare, which means "barricade or
obstacle."

“So the next problem would be to remove your brain, intact and
 undamaged, from your dead body. The body is useless. In fact it has already
 started to decay. The skull and the face are also useless. They are both
 encumbrances and I don’t want them around. All I want is the brain, the clean
 beautiful brain, alive and perfect. So when I get you on the table I will
 take a saw, a small oscillating saw, and with this I shall proceed to remove
 the whole vault of your skull. You’d still be unconscious at that point so I
 wouldn’t have to bother with anaesthetic.”
* riddled                                                              :Dahl:
[2021-06-23 Wed 13:03]

If an object is riddled with something, that means it's covered by
that thing: for example, a tree trunk might be riddled with tiny holes
made by the beaks of woodpeckers.

The adjective riddled most often describes something damaged by or
spread full of holes, like a rusty old mailbox riddled with bullet
holes or a block of Swiss cheese riddled with holes. You can also use
it figuratively: "It's so sad, her dog is riddled with cancer," or
"The plot of your novel is riddled with holes — it just doesn't hold
up." Riddled comes from the Old English hriddel, "sieve."

“My dear William, just think for a moment of your own brain. It is in
 perfect shape. It is crammed full of a lifetime of learning. It has taken you
 years of work to make it what it is. It is just beginning to give out some
 first-rate original ideas. Yet soon it is going to have to die along with the
 rest of your body simply because your silly little pancreas is riddled with
 cancer.”
* gruesome                                                             :Dahl:
[2021-06-23 Wed 13:03]

Gothic novels, horror movies, and crime dramas don't shy away from
showing gruesome scenes of death, pictures that inspire fright and
repulsion. Synonyms include "ghastly," "grisly," "loathsome," and
"macabre."

Once upon a time, English contained a variety of words related to
gruesome. The verb grue meant "to shudder," just as its Middle Dutch
source gruwen did. Grueful and grueing also conveyed the sense of
shivering with horror and disgust. All of these variations have been
lost leaving us only with gruesome. Texting while driving has caused
many gruesome accidents that you might not want to hear the gruesome
details of. Although if you like gruesome movies, you might want to
know.

“Quite a long time ago,” he said, “I saw a short medical film that had
 been brought over from Russia. It was a rather gruesome thing, but
 interesting. It showed a dog’s head completely severed from the body, but
 with the normal blood supply being maintained through the arteries and veins
 by means of an artificial heart. Now the thing is this: that dog’s head,
 sitting there all alone on a sort of tray, was alive. The brain was
 functioning. They proved it by several tests. For example, when food was
 smeared on the dog’s lips, the tongue would come out and lick it away; and
 the eyes would follow a person moving across the room.
* denture :Dahl:
[2021-06-23 Wed 13:04]

A denture is a section of false teeth, made to replace missing teeth
in a person's mouth. Some kinds of dentures need to be soaked in a
cleansing solution overnight.

The denture part of a dental appliance is officially the plate to
which false teeth are attached, but people tend to refer more
generally to dentures, meaning the whole device. If an accident or
dental disease causes you to lose adult teeth, you can have a dentist
make dentures that are fitted exactly to your mouth. Some of these are
permanent, while others are removable. Denture comes from the Latin
root dens, "tooth."

I am sure he was expecting me to jump when he said this, but for some
 reason I was ready for it. I lay quite still, watching his face and that slow
 white smile of his that always revealed the gold clasp of an upper denture
 curled around the canine on the left side of his mouth.
* effrontery :Dahl:
[2021-06-23 Wed 13:04]

If you rudely behave as if you have a right to something that you have
no right to, you're committing effrontery. When a couple stroll into a
crowded restaurant, demand the best table, and threaten the staff
unless they're seated right away, that's effrontery.

People have been guilty of outrageously self-centered behavior at
least since 1715, when effrontery was coined. Tracing to the French
word effronté, meaning "shameless," the word effrontery is also
connected to brazen, which means "of brass," and describes someone so
accustomed to effrontery that he's hardened to it and has no concern
for the harm done to others.

The details of the illness that struck me down so suddenly in my
 middle life are known to you. I need not waste time upon them—except to admit
 at once how foolish I was not to have gone earlier to my doctor. Cancer is
 one of the few remaining diseases that these modern drugs cannot cure. A
 surgeon can operate if it has not spread too far; but with me, not only did I
 leave it too late, but the thing had the effrontery to attack me in the
 pancreas, making both surgery and survival equally impossible.
* wistful :Dahl:
[2021-06-23 Wed 13:05]

Only one letter separates the two words, but "wishful" is having hope
for something, and wistful is having sadness or melancholy about
something. "Wist" isn't even a word that's used anymore, but you can
still be wistful.

People who appear wistful often show a longing for something or a look
of serious reflection. One way to describe the adjective wistful is as
the sad appearance of someone looking back and thinking "if only..." A
thoughtful or pensive mood centered on something good in the past that
is missed or something not so good in the present that could have been
better "if only" something had gone differently — these things make
for a wistful outlook.

As you read on, you must forgive me, if you will, for the coolness of
 my style, but this is the only way I know of getting my message over to you
 clearly. You see, as my time draws near, it is natural that I begin to brim
 with every kind of sentimentality under the sun. Each day I grow more
 extravagantly wistful, especially in the evenings, and unless I watch myself
 closely my emotions will be overflowing on to these pages.
* brim :Dahl:
[2021-06-23 Wed 13:05]

The brim is the top of a container, like the edge of a cup. Also, if a
cup is brimming, it’s full.

This word has a couple meanings related to fullness. If a cup is full,
it’s filled to the brim. The brim is the top. Containers such as
buckets and pitchers have brims too. Also, the bucket is brimming if
it's totally full. A brimming container is likely to spill. People can
brim too: you can be brimming with enthusiasm or happiness. Like a cup
about to spill, you can’t quite contain yourself when you’re brimming
with joy.

As you read on, you must forgive me, if you will, for the coolness of
 my style, but this is the only way I know of getting my message over to you
 clearly. You see, as my time draws near, it is natural that I begin to brim
 with every kind of sentimentality under the sun. Each day I grow more
 extravagantly wistful, especially in the evenings, and unless I watch myself
 closely my emotions will be overflowing on to these pages.
* dare :Dahl:
[2021-06-23 Wed 13:05]

When you challenge or provoke someone to try something risky, it's a
dare. If you accept a dare, you're probably trying to prove how brave
you are.

When you challenge your friend to a dare, you dare him. You might, for
example, dare your brother to jump off the garage into a pile of
leaves. Another way to dare is to actually be brave: "I admire her so
much, because she dares to stand up to bullies." The Old English root
of dare is durran, "to brave danger, venture, or presume." If you say,
"How dare you?" you're expressing outrage or indignation.

Do not be alarmed by the sight of all this writing. It is nothing but
 an attempt on my part to explain to you precisely what Landy is going to do
 to me, and why I have agreed that he should do it, and what are his theories
 and his hopes. You are my wife and you have a right to know these things. In
 fact you must know them. During the past few days I have tried very hard to
 speak with you about Landy, but you have steadfastly refused to give me a
 hearing. This, as I have already told you, is a very foolish attitude to
 take, and I find it not entirely an unselfish one either. It stems mostly
 from ignorance, and I am absolutely convinced that if only you were made
 aware of all the facts, you would immediately change your view. That is why I
 am hoping that when I am no longer with you, and your mind is less
 distracted, you will consent to listen to me more carefully through these
 pages. I swear to you that when you have read my story, your sense of
 antipathy will vanish, and enthusiasm will take its place. I even dare to
 hope that you will become a little proud of what I have done.
* steadfastly :Dahl:
[2021-06-23 Wed 13:06]



nil

Do not be alarmed by the sight of all this writing. It is nothing but
 an attempt on my part to explain to you precisely what Landy is going to do
 to me, and why I have agreed that he should do it, and what are his theories
 and his hopes. You are my wife and you have a right to know these things. In
 fact you must know them. During the past few days I have tried very hard to
 speak with you about Landy, but you have steadfastly refused to give me a
 hearing. This, as I have already told you, is a very foolish attitude to
 take, and I find it not entirely an unselfish one either. It stems mostly
 from ignorance, and I am absolutely convinced that if only you were made
 aware of all the facts, you would immediately change your view. That is why I
 am hoping that when I am no longer with you, and your mind is less
 distracted, you will consent to listen to me more carefully through these
 pages. I swear to you that when you have read my story, your sense of
 antipathy will vanish, and enthusiasm will take its place. I even dare to
 hope that you will become a little proud of what I have done.
* thrifty :Dahl:
[2021-06-23 Wed 13:06]

Being thrifty means being careful of your money and how you spend
it. Think twice before you spend, but if you must shop, hitting the
sales and using coupons are good ways to be thrifty.

Note the similarity between the adjective thrifty and the verb thrive,
and you'll realize that being careful with your money might be an
important survival tactic. Everyone worries about having enough — look
at how thrift shops have become important sources of clothing and
other goods for many people, allowing them to buy without spending a
fortune. Being thrifty is a solid virtue, as suggested by the old
German proverb, "Prudent men woo thrifty women."

My dear Mary, I trust that you will not permit my departure from this world
 to upset you too much, but that you will continue to observe those precepts
 which have guided you so well during our partnership together. Be diligent
 and dignified in all things. Be thrifty with your money. Be very careful that
 you do not . . . et cetera, et cetera.
* bequests :Dahl:
[2021-06-23 Wed 13:06]

When you receive some kind of gift, be it money or property, through a
will, that gift is known as a bequest.  Your aunt left you a bequest
of the earrings she always thought you admired.

The noun bequest is something one arranges to give away after death,
sort of a gift from beyond the grave.  Basically, putting a bequest in
a will is a way of making sure the right person will get certain goods
after your death. If you are very wealthy, universities and charitable
organizations may court you in an attempt to gain bequests for their
institutions.

William Pearl did not leave a great deal of money when he died, and his will was
a simple one. With the exception of a few small bequests to relatives, he left
all his property to his wife.
* blemish :Dahl:
[2021-06-23 Wed 13:07]

A blemish is a small flaw. If you borrow your brother's brand new
bicycle, you'd better be careful — what might seem like the tiniest
blemish to you might be a horribly ruined paint job to him.

The classic example of a blemish is a pimple or other mark on your
skin, but you can call any small defect a blemish — like a worm hole
in an apple or a scrape on the side of your car. A flaw or fault in
your personality or morals can also be called a blemish. You might say
that the one time your dog accidentally nipped you is the only blemish
on his reputation as a sweet, gentle pet.

“He was actually twenty-eight. And yet I never would have guessed it if he hadn’t
told me, never in my whole life. There wasn’t a blemish on his body.”
* trifle :Dahl:
[2021-06-23 Wed 13:07]

A trifle is something that's totally unimportant. If your friend is
freaking out over which poster to buy and you call her dilemma a
trifle, you're saying she shouldn't get so worked up over nothing.

Trifle comes from the Middle English trufle, meaning "fraud, joke,
trick." You'll usually hear it used to mean "insignificant, trivial."
If you write a little ditty to sing at a birthday party, you could say
it's just a trifle. As a verb, trifle means "toy with, waste." If you
play with someone's feelings without seriously meaning anything, you
are trifling with his affection. Trifle is also a sweet, sticky
cake. Don't trifle the day away dreaming about trifle. Make some!

“Seventeen!” she cried. “Oh, it’s the perfect age! Mr Mulholland was also
seventeen. But I think he was a trifle shorter than you are, in fact I’m sure he
was, and his teeth weren’t quite so white. You have the most beautiful teeth, Mr
Weaver, did you know that?”
* whiff :Dahl:
[2021-06-23 Wed 13:07]

A whiff can mean the hint of something you smell. When you drive past
the sewage treatment plant and suddenly roll up your car windows, it's
usually because you've gotten a whiff of the plant's special odor.

Whiff can be used as either a noun or verb, and it implies a brief or
small puff or sniff. A person can have "a whiff of the exotic," which
means they are living like the rest of us, but there is a little
something about them that seems foreign or different. Sometimes, of
course, odors are so overpowering that a small sniff is all you need:
"Take a whiff of this," your friend might say to you, holding out a
carton of sour milk. In that case, one whiff will be more than enough.

Billy started sipping his tea. She did the same. For half a minute or so,
neither of them spoke. But Billy knew that she was looking at him. Her body was
half turned towards him, and he could feel her eyes resting on his face, watching
him over the rim of her teacup. Now and again, he caught a whiff of a peculiar
smell that seemed to emanate directly from her person. It was not in the least
unpleasant, and it reminded him—well, he wasn’t quite sure what it reminded him
of. Pickled walnuts? New leather? Or was it the corridors of a hospital?
* tantalising :Dahl:
[2021-06-23 Wed 13:08]



nil

There is nothing more tantalising than a thing like this which lingers
just outside the borders of one’s memory. He hated to give up.
* dotty :Dahl:
[2021-06-23 Wed 13:08]



nil

The old girl is slightly dotty, Billy told himself. But at five and
sixpence a night, who gives a damn about that? “I should’ve thought you’d be
simply swamped with applicants,” he said politely.
* dithering :Dahl:
[2021-06-23 Wed 13:08]



nil

After dithering about like this in the cold for two or three minutes,
Billy decided that he would walk on and take a look at The Bell and Dragon before
making up his mind. He turned to go.
* rapacious :Dahl:
[2021-06-23 Wed 13:08]

Something rapacious is out to devour — anything, and little can stand
in its way. A rapacious landlord is out for more rent, and a rapacious
eater is only satisfied at the all-you-can-eat buffet.

A 17th-century word, from the Latin rapere, "to snatch," rapacious
originally described the people and animals who often preyed on weaker
creatures and devoured them, by eating them or by ruining them through
some scandal. Modern-day companies even get the label rapacious when
their appetites for profit seem to devour "lesser" interests, like the
environment and employee benefits.

There would be beer and darts in the evenings, and lots of people to talk to, and
it would probably be a good bit cheaper, too. He had stayed a couple of nights in
a pub once before and he had liked it. He had never stayed in any
boarding-houses, and, to be perfectly honest, he was a tiny bit frightened of
them. The name itself conjured up images of watery cabbage, rapacious landladies,
and a powerful smell of kippers in the living-room.
* congenial :Dahl:
[2021-06-23 Wed 13:09]

A congenial person is easy to get along with. If you're trying to
decide which of your friends to take on a road trip, choose the most
congenial one.

Congenial means sharing the same temperament, or agreeing with your
temperament.  You can talk about a congenial person, place, or
environment. Maybe you enjoy the congenial atmosphere of the
library. Or perhaps for you the disco is more congenial.  As you might
expect for such a vaguely approving word, there are many synonyms:
agreeable, pleasant, delectable, delightful, enjoyable, and so on.

On the other hand, a pub would be more congenial than a boarding-house.
* laymen :Dahl:
[2021-06-23 Wed 13:15]

A layman might have a small amount of knowledge about something, but
she isn't officially trained in the subject. If you need brain
surgery, don't consult a layman; stick to a professional brain
surgeon.

Use the noun layman to describe your brother, who is an amateur bird
watcher rather than a professional ornithologist. The word layman is
most often used to contrast with expert or professional. Another way
to use it is to distinguish between a member of the clergy — a priest
or minister, for example — and an ordinary church member, or layman.

“As you wish, William. And now, as I say, I’d take a small oscillating
 saw and carefully remove your complete calvarium—the whole vault of the
 skull. This would expose the top half of the brain, or rather the outer
 covering in which it is wrapped. You may or may not know that there are three
 separate coverings around the brain itself—the outer one called the dura
 mater or dura, the middle one called the arachnoid, and the inner one called
 the pia mater or pia. Most laymen seem to have the idea that the brain is a
 naked thing floating around in fluid in your head. But it isn’t. It’s wrapped
 up neatly in these three strong coverings, and the cerebrospinal fluid
 actually flows within the little gap between the two inner coverings, known
 as the subarachnoid space. As I told you before, this fluid is manufactured
 by the brain and it drains off into the venous system by osmosis.
* jugular :Dahl:
[2021-06-23 Wed 13:16]

Jugular is short for “jugular vein,” the major vein that brings blood
from your head to your heart. You can also call any vulnerable area
the jugular.

If you hear someone say, “Go for the jugular!” Watch out! A serious
attack is coming. When lions attack prey, they chomp down on the
jugular to kill the animal fast. If your jugular is cut, you could die
very quickly without medical help. You can also call your neck and
throat the jugular area. Because this is a vulnerable area, you can
use this word for other vulnerable things, like a weak spot on a
sports team.

“I myself would leave all three coverings—don’t they have lovely
 names, the dura, the arachnoid, and the pia?—I’d leave them all intact. There
 are many reasons for this, not least among them being the fact that within
 the dura run the venous channels that drain the blood from the brain into the
 jugular.
* severing :Dahl:
[2021-06-23 Wed 13:21]



nil

“At this point, I would be ready for the final move. To one side, on a
 table, I’d have a basin of a special shape, and this would be filled with
 what we call Ringer’s Solution. That is a special kind of fluid we use for
 irrigation in neurosurgery. I would now cut the brain completely loose by
 severing the supply arteries and the veins. Then I would simply pick it up in
 my hands and transfer it to the basin. This would be the only other time
 during the whole proceeding when the blood flow would be cut off; but once it
 was in the basin, it wouldn’t take a moment to re-connect the stubs of the
 arteries and veins to the artificial heart.
* brain :Dahl:
[2021-06-23 Wed 13:24]

The brain is the most complex organ in the body, located inside the
protective skull. The word can also be used as a verb in the phrase
"to brain," which means to injure or kill someone by hitting them in
the head.

The human brain has inspired many idioms, or colorful
phrases. Thinking intently (or obsessively) about something means that
you've got it "on the brain," and to "pick someone's brain" means to
get their ideas on something. A puzzle is a "brainteaser, someone
smart is called "a brain," and the person who runs something is said
to be "the brains" of the operation.

“Ah!” he cried. “I knew I’d forgotten something! I never told you
 about the eye. Listen. I am going to try to leave one of your optic nerves
 intact, as well as the eye itself. The optic nerve is a little thing about
 the thickness of a clinical thermometer and about two inches in length as it
 stretches between the brain and the eye. The beauty of it is that it’s not
 really a nerve at all. It’s an outpouching of the brain itself, and the dura
 or brain covering extends along it and is attached to the eyeball. The back
 of the eye is therefore in very close contact with the brain, and
 cerebrospinal fluid flows right up to it.
* submerged :Dahl:
[2021-06-23 Wed 13:25]

When something is submerged, it's under water — like a submarine, a
car caught in a flood, or your feet in a wading pool.

Use the adjective submerged to describe something that stays under the
surface of the water. The flood in your basement might cause your
exercise equipment to be submerged, and you probably snorkel with your
face submerged. You can also use submerged to describe something
that's covered up. For example, you might try to keep your sad
feelings about your dog's death submerged when you're with your
friends.

“All this suits my purpose very well, and makes it reasonable to
 suppose that I could succeed in preserving one of your eyes. I’ve already
 constructed a small plastic case to contain the eyeball, instead of your own
 socket, and when the brain is in the basin, submerged in Ringer’s Solution,
 the eyeball in its case will float on the surface of the liquid.”
* resented :Dahl:
[2021-06-23 Wed 13:30]

To resent something is to feel anger or bitterness toward it. You
might resent someone who has treated you poorly.

To resent is a strong, negative feeling.  You may resent the
accusation that you were stealing cookies, or when a teacher yelled at
you for whispering, even though everyone else was too. You might
resent a friend who has more money or friends than you. Lots of people
resent celebrities because they're famous and wealthy.  If your friend
borrowed a sweater and didn’t return it, you would probably resent
it. Resenting is the opposite of being grateful.

“No,” I said. Landy was already taking it for granted that I was going
 to go through with this business, and I resented his attitude. “Go away now
 and leave me alone,” I told him. “You won’t get anywhere by trying to rush
 me.”
* impurities :Dahl:
[2021-06-23 Wed 13:35]

An impurity is something that ruins the uncontaminated nature of
something. If someone accuses you of impurity, they think you or your
nature has been spoiled in some way by sin.

When water is pure, the only thing in that water is water. Add a
contaminant, say salt or bleach, and you are introducing an impurity,
something that turns the water impure. When used with people, the word
has a religious overtone. Someone who is pure is unspoiled by
sin. Think Snow White. If you convinced Snow White to rob a bank with
you, you'd be spoiling her good nature with your wretched impurity.

There would be no impurities in it, no virus, no bacteria, nothing. Of course
 it’s foolish to guess, but I believe that a brain might live for two or three
 hundred years in circumstances like these. Good-bye for now,” he said. “I’ll
 drop in and see you tomorrow.” He went out quickly, leaving me, as you might
 guess, in a fairly disturbed state of mind.

* TODO ministration                                                    :Dahl:
[2021-06-29 Tue 13:57]



nil

The man had a way of making her feel that she was altogether a rather remarkable
woman, a person of subtle and exotic talents, fascinating beyond measure; and
what a very different thing that was from the dentist husband at home who never
succeeded in making her feel that she was anything but a sort of eternal patient,
someone who dwelt in the waiting-room, silent among the magazines, seldom if ever
nowadays to be called in to suffer the finicky precise ministrations of those
clean pink hands.
* ravishing :Dahl:
[2021-06-29 Tue 13:57]

The adjective ravishing describes something or someone of exceptional
beauty. If you say the dress your friend picked for the prom is
ravishing, you mean it's beautiful and she looks beautiful in it.

The adjective ravishing comes from the verb ravish, which is from the
Latin word rapere, meaning to seize. In English, the verb meant to
plunder or to carry away, and later a sense arose that meant to carry
away in pleasure, or to seduce. So a dress that is ravishing is
seductive or sexy––or, as the word became more popular, simply
beautiful, as in "ravishing scenery."

“Tally-ho!” the Colonel would cry each time he met her at the station
in the big car. “My dear, I’d almost forgotten how ravishing you
looked. Let’s go to earth.”
* flabbergasted :Dahl:
[2021-06-29 Tue 13:57]

When you see your mom come back from the salon with bright green spiky
hair and your jaw drops to the floor in total shock, you’re
flabbergasted. You are really, really shocked — pretty much
speechless.

Use the adjective flabbergasted to describe someone who's astounded or
surprised for any reason, good or bad. You could be flabbergasted at
how astonishingly expensive a parking ticket is, or at how incredibly
delicious pineapple pizza is. Flabbergasted has been used since the
late 18th century, but no one knows for sure where it originated. The
word sounds like what it means: when you say it out loud —
"flabbergasted!" — it somehow captures the spirit of astonishment and
shock.

The woman is flabbergasted, stupefied, humiliated, defeated. The
audience of men around the bar smiles quietly to itself and takes a
little comfort from the fantasy.
* lecherous :Dahl:
[2021-06-29 Tue 13:58]

To be lecherous is to be full of strong sexual desire and to act on
it, usually in an unpleasant way.

People who are lecherous are kind of obsessed with sex — they can't
stop thinking about it or having it. This is a word that is used more
often to describe men than women: lecherous men are called
lechers. There is also a creepy flavor to this word. If you describe
someone as lecherous, it usually isn't a compliment. A common use is
talking about a lecherous old man who hits on younger women.

The basic theme of these stories never varies. There are always three
main characters—the husband, the wife, and the dirty dog. The husband
is a decent clean-living man, working hard at his job. The wife is
cunning, deceitful, and lecherous, and she is invariably up to some
sort of jiggery-pokery with the dirty dog.
* unduly :Dahl:
[2021-06-29 Tue 13:58]

If something is done unduly, it's done out of proportion with what's
reasonable or right. If you're unduly treated, you're not treated in
the way you deserve to be.

Duly comes from the late 14th century duweliche meaning "rightly,
properly." The prefix un-, meaning "not" of course reverses that
meaning so with unduly we get "not rightly or properly." You might
become unduly angry with a toddler for tracking mud into the
house. Unduly can also mean "excessively." Worrying unduly about the
future can be paralyzing. Sometimes it's good to take the days as they
come.

The husband’s death also brings satisfactory rewards and some ladies
prefer to rely upon this method. They know that the waiting period
will not be unduly protracted, for overwork and hypertension are bound
to get the poor devil before long, and he will die at his desk with a
bottle of benzedrines in one hand and a packet of tranquillizers in
the other.
* protracted :Dahl:
[2021-06-29 Tue 13:58]

Something protracted has been drawn out, usually in a tedious
way. Protracted things are long and seem like they're never going to
end.

Anything protracted is lasting longer than you would like. A speech
that seems to go on forever is protracted. If an employer and a union
can't reach an agreement, there could be a protracted strike. Before a
movie, the previews are almost always protracted — they never seem to
stop. If something is long and annoying, and there's no good reason it
couldn't be shorter, it's protracted.

They know that the waiting period will not be unduly protracted, for
overwork and hypertension are bound to get the poor devil before long,
and he will die at his desk with a bottle of benzedrines in one hand
and a packet of tranquillizers in the other.
* parlay :Dahl:
[2021-06-29 Tue 13:58]

If you parlay a bet, then you take the winnings from one bet and bet
it again on something else. You might have seen a gambler on TV parlay
her winnings into a huge fortune.

The verb parlay is often used to talk about gambling, but it can be
used more broadly to describe any initial stake that you turn into
something much larger. You might parlay your early investment in your
brother’s company into a high-paying leadership role. Parlay also has
a noun form that describes these kinds of transactions. You might
notice your Uncle Bob once again betting a baseball parlay.

Divorce has become a lucrative process, simple to arrange and easy to
forget; and ambitious females can repeat it as often as they please
and parlay their winnings to astronomical figures.
* TODO buttercups                                                      :Dahl:
[2021-06-29 Tue 13:59]



nil

Mr Boggis walked out into the yard and through the gate and then down the
long track that led across the field towards the road. He found himself giggling
quite uncontrollably, and there was a feeling inside him as though hundreds and
hundreds of tiny bubbles were rising up from his stomach and bursting merrily in
the top of his head; like sparkling-water. All the buttercups in the field were
suddenly turning into golden sovereigns, glistening in the sunlight. The ground
was littered with them, and he swung off the track on to the grass so that he
could walk among them and tread on them and hear the little metallic tinkle they
made as he kicked them around with his toes. He was finding it difficult to stop
himself from breaking into a run. But clergymen never run; they walk slowly. Walk
slowly, Boggis. Keep calm, Boggis. There’s no hurry now. The commode is yours!
* scoundrel                                                            :Dahl:
[2021-06-29 Tue 13:59]

A scoundrel is a person who does deliberately evil things. If your
brother hides a fake mouse in your shoe and you therefore almost have
a heart attack while getting dressed, you have every right to call him
a scoundrel.

Though the term scoundrel isn’t used as much as it once was, it’s the
perfect way to describe someone who breaks the law, has no morals, or
someone like your sneaky sibling who loves to play practical
jokes. Most villains in movies and on television can be put in this
category. Interestingly, though women are quite capable of equally
wicked behavior, this particular term is usually reserved for men.

“You are quite right, my friend. But these scoundrels have their own
secret methods.”
* knavery :Dahl:
[2021-06-29 Tue 13:59]

The quality of acting like a villain or a rascal is knavery. You'll
know that knavery happened last night if you wake to find toilet paper
strung from the branches of your trees.

The noun knavery comes from knave, an old-fashioned word meaning
"rascal or rogue." Shakespeare was especially famous for using knave
as an insult, and knavery reflects this sense of a foolish and
terrible person who's up to no good. Dirty political tricks can be
called knavery, as can rascally practical jokes, and even wickedness,
dishonesty, and cruelty.

I can almost see them doing it, the long, complicated ritual of
rubbing the wood with linseed oil, coating it over with french polish
that has been cunningly coloured, brushing it down with pumice-stone
and oil, bees-waxing it with a wax that contains dirt and dust, and
finally giving it the heat treatment to crack the polish so that it
looks like two-hundred-year-old varnish! It really upsets me to
contemplate such knavery!
* plump :Dahl:
[2021-06-29 Tue 13:59]

Something that's plump has a nice round shape. You could describe
watching your plump little cousin eating one plump grape after
another.

Objects and people can both be described as plump, as long as they're
full or round or chubby. Though some people might be offended by being
called plump, it's meant to describe an appealing roundness. And when
you plump something, you pat or shake it so that it becomes fuller:
"Let me plump those pillows on the bed while you tuck the sheets in."

He was beginning literally to shake with excitement, and to calm
himself he walked over to the window and stared out at a plump brown
hen pecking around for stray grains of corn in the yard.
* saunter :Dahl:
[2021-06-29 Tue 14:00]

To saunter is to stroll at a leisurely pace. The next time someone
accuses you of dragging your feet and asks you to speed it up, calmly
tell them that you’re perfecting your saunter.

A verb of unconfirmed origin, saunter means to “walk with a leisurely
gait.” As a noun, saunter describes that leisurely gait. Henry David
Thoreau once said “it is a great art to saunter.” So while crossing a
busy street may not be the best time to test out your sauntering
abilities, feel free to practice when you're not in a hurry.

He began to saunter off, then he checked himself and turned slowly
back again. He placed the tip of one finger against the point of his
chin, laid his head over to one side, and frowned as though deep in
thought.
* luscious :Dahl:
[2021-06-29 Tue 14:00]

Calling something luscious means it's appealing and incredibly
pleasing to the senses. That goes for good-looking people as well as a
rich piece of chocolate cake.

An adjective meaning richly appealing or scrumptious, luscious is
actually believed to be a shortened version of delicious. Synonyms
include succulent, savory and enticing — all words that can also be
used to either describe a perfectly cooked steak or your crush's
unbelievable, irresistible lips.

Just imagine the faces of the boys up there in London when they got a
look at it tomorrow morning! And the luscious offers coming in from
the big fellows over in the West End—Frank Partridge, Mallett, Jetley,
and the rest of them!
* veneers :Dahl:
[2021-06-29 Tue 14:00]

You know how some furniture looks like solid oak or maple until it
gets chipped and reveals itself to be nothing more than some cheap
particle-board covered with a thin layer of fancy wood?  That thin
layer is called a veneer.

A veneer can be anything that makes something look more elegant or
attractive than it is. Originally it was a furniture word, but over
time its meaning expanded.  If someone smiles at you while making some
passive-aggressive remark, like, "Gee, you actually look really nice
today," you could say that her inner meanness is showing through her
veneer of sweetness.

Some man, Mr Boggis couldn’t remember his name, had made a study of
these commodes fairly recently and had proved that all three must have
come from the same workshop, for the veneers were all from the same
log, and the same set of templates had been used in the construction
of each.
* fatuous :Dahl:
[2021-06-29 Tue 14:00]

Fatuous means lacking intelligence. When your mother outlaws calling
your brother stupid, use fatuous instead.

Fatuous derives from the Latin fatuus meaning "foolish." It sounds
like it should have something to do with being fat, but it actually
has no relation to size. Fatuus itself comes from a root that also
gave us "debate" and this might be a good way to remember it. You want
to debate someone who's fatuous, because they are unintelligent, silly
and even a bit conceited, so they probably won't be very persuasive
debaters. Just don't call them fatuous to their face. Even if they
don't know what it means, it's just not nice!

Bert fetched him the water, handed it to him, and stayed close beside
him, staring down at him with a fatuous leer on his face.
* leer :Dahl:
[2021-06-29 Tue 14:01]

A leer is an unpleasant facial expression. A leer means the person
doesn't like you, or even worse, does — in a creepy way.

Leer can also be used as a verb, meaning "to look at someone with a
suggestive, rude, or contemptuous expression." Your sworn enemy might
leer at you whenever you enter a room to express scorn and
superiority. Leer derives from the Old English word hleor, meaning
"the face or the cheek."

Bert fetched him the water, handed it to him, and stayed close beside
him, staring down at him with a fatuous leer on his face.
* larder :Dahl:
[2021-06-29 Tue 14:01]

When your mother buys groceries, she puts them in the larder or the
pantry. A larder is a room or cabinet where you store food.

Larder is an old-fashioned word, created back when people used lard —
rendered animal fat — to grease pans and cook food. The larder is
where they kept their bacon and their lard. Now it's where you keep
your potato chips and your cookies.

“I don’t want to pry into your cupboards or into your larder. I just
want to look at the furniture to see if you happen to have any
treasures here, and then I can write about them in our Society
magazine.”
* enquire :Dahl:
[2021-06-29 Tue 14:01]

You might enquire, or ask about, the difference between the words
enquire and "inquire." Good question. The answer is, not much. They
are the same word with different spellings. Typically the British
prefer the "e" version, but both are correct.

When you enquire about something, you are asking a question. This can
come in many forms. Sometimes when you enquire, you are doing an
investigation of a crime or an unsolved mystery. The National Enquirer
is a tabloid that investigates celebrity gossip. But enquiring doesn't
always have to be so dramatic. You could just be enquiring about the
time.

“Might I enquire if you are the owner?” Mr Boggis asked, undaunted,
addressing himself to Rummins.
* jeer :Dahl:
[2021-06-29 Tue 14:02]

As a noun, jeer is the act of scoffing, taunting, or mocking. Think of
it as an anti-cheer.  If you offer cheers for the visiting team and
jeers for the home team, you might not be too popular in the stands.

As a verb, jeer means to laugh at in a mean way.  Even if you did
forget the words to the national anthem, it wasn't polite for the
crowd to jeer.  But don't feel too bad: the last singer remembered all
the words and they jeered her anyway!  Tough crowd.

Again the silence, and Mr Boggis glanced quickly from Rummins to Bert,
then to Claud, then back again to Rummins, and he noticed that each of
them had the same peculiar expression on his face, something between a
jeer and a challenge, with a contemptuous curl to the mouth and a
sneer around the nose.
* corrugated :Dahl:
[2021-06-29 Tue 14:02]

Corrugated means molded into tight ridges and valleys. You've probably
seen corrugated cardboard or corrugated metal roofs.

Materials are put into a corrugated shape to ensure elasticity and
strength — cardboard boxes hold their shape because the cardboard is
reinforced with a corrugated layer inside the two flat pieces. To
remember corrugated, think about corduroy pants — which also have
ridges and valleys. If you're lucky enough to have had ribbon candy,
that's corrugated as well.

The shortish flat-faced man with a narrow corrugated brow and
immensely broad shoulders was Claud.
* TODO stumpy                                                          :Dahl:
[2021-06-29 Tue 14:02]



nil

The oldest of the three was a stumpy man with a wide frog mouth and small
shifty eyes, and although Mr Boggis didn’t know it, his name was Rummins and he
was the owner of the farm.
* rambling :Dahl:
[2021-06-29 Tue 14:02]

The adjective rambling means confused and long-winded, the way you
could describe your grandfather's endless rambling stories of his
childhood.

Rambling always means indirect and a little confusing, which can be a
negative quality in a classroom lecture or movie plot — but when
you're talking about a path through the woods, rambling is a charming
way to describe it. You might love to hike through the woods on
rambling trails that twist and turn. Rambling comes from the verb
ramble, "walk or stroll," which is a variant on the older verb romen,
"to walk, or to go," and related to "roam."

This place, he noticed as he approached, was a good deal smaller than
the last, and he didn’t hold out much hope for it. It looked rambling
and dirty, and some of the sheds were clearly in bad repair.
* TODO mortice                                                         :Dahl:
[2021-06-29 Tue 14:03]



nil

It was a favourite test of his, and it was always an intriguing sight to see him
lowering himself delicately into the seat, waiting for the “give,” expertly
gauging the precise but infinitesimal degree of shrinkage that the years had
caused in the mortice and dovetail joints.
* TODO honeysuckle                                                     :Dahl:
[2021-06-29 Tue 14:03]



nil

But that was not all. There was a chair there as well, a single chair, and
if he were not mistaken it was of an even finer quality than the table. Another
Hepplewhite, wasn’t it? And oh, what a beauty! The lattices on the back were
finely carved with the honeysuckle, the husk, and the paterae, the caning on the
seat was original, the legs were very gracefully turned and the two back ones had
that peculiar outward splay that meant so much. It was an exquisite chair.
* lattices :Dahl:
[2021-06-29 Tue 14:03]

A lattice is a decorative wooden frame or fence. Your grandmother's
prize garden might include a lattice covered in bright pink roses.

An ornamental design — made usually of wood — that you might see on
the porch of a house or a garden trellis, is a lattice. Lattice is
often made of a criss-crossed, diamond pattern of wood or metal
slats. Lattice is a nice material for a porch because it lets in air
and light but still gives privacy. You can also call something that
resembles such a pattern lattice, like lattice wallpaper, or a
lattice-patterned silver necklace.

The lattices on the back were finely carved with the honeysuckle, the
husk, and the paterae, the caning on the seat was original, the legs
were very gracefully turned and the two back ones had that peculiar
outward splay that meant so much. It was an exquisite chair.
* eulogy :Dahl:
[2021-06-29 Tue 14:03]

At every funeral, there comes a moment when someone speaks about the
life of the person who died. The speaker is delivering what is known
as a eulogy. A eulogy is a formal speech that praises a person who has
died.

Usually a eulogy makes the dead person sound a lot more impressive
than they really were. A couple of less common synonyms for this kind
of "praise the dead" speech are panegyric and encomium. Sometimes the
dead person was so unimpressive that there's nothing nice to say. And
sometimes they were so awful that the only appropriate speech is a
dyslogy that describes their faults and failings.

From then on, it was easy. A Tory in riding-breeches, male or female,
was always a sitting duck for Mr Boggis. He spent two minutes
delivering an impassioned eulogy on the extreme Right Wing of the
Conservative Party, then two more denouncing the Socialists.
* whinny :Dahl:
[2021-06-29 Tue 14:04]

A cow moos, a dog barks, a rooster crows, and a horse whinnies. Whinny
is both a noun and a verb. As a noun, it's the sound a horse makes. As
a verb, it's the horse making the sound.

A familiar word with the same meaning as whinny is neigh. When you
visit your cousins on their farm, the rooster wakes you up every
morning with his crowing. The cow moos to let you know she’s ready to
be milked. The dog’s barking alerts you that the tractor is coming
down the drive. And it’s the horse’s whinny that tells you he’s ready
to go for a ride. Every time you hear that whinny, you’ve got to
saddle up!

Mr Boggis, who half expected her to whinny any moment, raised his hat,
made a little bow, and handed her his card. “I do apologise for
bothering you,” he said, and then he waited, watching her face as she
read the message.
* stables :Dahl:
[2021-06-29 Tue 14:04]

When something is stable, it's fixed and steady. If you needed advice,
you'd probably go to your most stable friend, the one least likely to
act crazy or be easily upset.

Whether you're talking about an object or a person, the adjective
stable implies reliability and strength. You can describe a government
as stable, or a relationship, or a desk. A completely different
meaning of stable is the noun "building used for housing horses or
other animals." Both senses of the word come from the Latin stabilis,
"firm or steadfast."

He approached the front door and rang the bell. He heard the sound of
footsteps in the hall and the door opened and suddenly there stood
before him, or rather above him, a gigantic woman dressed in
riding-breeches. Even through the smoke of her cigarette he could
smell the powerful odour of stables and horse manure that clung about
her.
* rustic :Dahl:
[2021-06-29 Tue 14:04]

When you think of the word rustic, think of the rural country. This
word can be given a positive or a negative spin depending on how you
use it; a rustic inn, for example, might be quaint or it might be
virtually uninhabitable.

The words rustic and "rural" spring from the same ancient root: *rur-,
which means "open space" in the hypothetical ancestor language
Proto-Indo-European. In early usage, these two words were used
interchangeably, but now, rural is used to describe locations –-
"rural community," "rural location" — while rustic refers to the
unrefined qualities associated with country life. The best antonym is
cosmopolitan, which implies the sophistication and worldliness of city
life.

He was dressed in a black suit with the usual parson’s dog-collar
round his neck, and on his head a soft black hat. He carried an old
oak walking-stick which lent him, in his opinion, a rather rustic
easy-going air.
* lent :Dahl:
[2021-06-29 Tue 14:04]

When you lend something, you loan it or let someone borrow it. You
might, for example, lend your bike to your brother — if he promises to
be careful with it.

Libraries lend people books, and car rental companies lend people cars
— in both cases, the item that's been borrowed is supposed to be
returned eventually. Another way to lend is to "add a quality to," or
"be suitable for." You could say that you think your hat lends you a
mysterious quality, or that your trench coat lends itself to walking
through a foggy city at dusk.

He carried an old oak walking-stick which lent him, in his opinion, a
rather rustic easy-going air.
* parson :Dahl:
[2021-06-29 Tue 14:05]

Use the noun parson to describe a member of the clergy — a person with
the authority to lead worship in a church or perform religious rites
such as weddings and christenings.

Historically, parson has been what Anglican church members call their
minister or priest, but the term can also be used as a generic term
for "clergy member." You might ask a parson to preside at your
wedding, or to officiate at your grandmother's funeral, for
example. Experts are uncertain about the exact origins of parson,
although one theory says it's a shortened form of the Latin persona
ecclesiae, "person of the church."

Mr Boggis strode briskly up the drive. He was a small fat-legged man
with a belly. The face was round and rosy, quite perfect for the part,
and the two large brown eyes that bulged out at you from this rosy
face gave an impression of gentle imbecility. He was dressed in a
black suit with the usual parson’s dog-collar round his neck, and on
his head a soft black hat.
* spinster :Dahl:
[2021-06-29 Tue 14:05]

A spinster is an older, unmarried woman. Even if you're in awe of your
Aunt Sally's glamorous, single life, your grandmother might dismiss
her as a spinster.

Spinster originally meant "a spinner of thread," and as that was a job
typically done by unmarried women, it came to have the meaning — even
in legal documents — of "single woman." Another term for spinster is
the equally old-fashioned sounding old maid. Either way, it means a
woman who never got married. Spinster is not a word you should call
anyone: it reduces single women to one detail about their lives.

 He was a talented salesman, and when buying or selling a piece he
could slide smoothly into whichever mood suited the client best. He
could become grave and charming for the aged, obsequious for the rich,
sober for the godly, masterful for the weak, mischievous for the
widow, arch and saucy for the spinster.
* TODO godly                                                           :Dahl:
[2021-06-29 Tue 14:05]



nil

Apart from the fact that he was at this moment disguised in the uniform of
a clergyman, there was nothing very sinister about Mr Cyril Boggis. By trade he
was a dealer in antique furniture, with his own shop and showroom in the King’s
Road, Chelsea. His premises were not large, and generally he didn’t do a great
deal of business, but because he always bought cheap, very very cheap, and sold
very very dear, he managed to make quite a tidy little income every year. He was
a talented salesman, and when buying or selling a piece he could slide smoothly
into whichever mood suited the client best. He could become grave and charming
for the aged, obsequious for the rich, sober for the godly, masterful for the
weak, mischievous for the widow, arch and saucy for the spinster. He was well
aware of his gift, using it shamelessly on every possible occasion; and often, at
the end of an unusually good performance, it was as much as he could do to
prevent himself from turning aside and taking a bow or two as the thundering
applause of the audience went rolling through the theatre.
* obsequious :Dahl:
[2021-06-29 Tue 14:05]

If you disapprove of the overly submissive way someone is acting —
like the teacher's pet or a celebrity's assistant — call them by the
formal adjective obsequious.

There are many words in the English language for a person or an action
that is overly obedient and submissive. Obsequious people are usually
not being genuine; they resort to flattery and other fawning ways to
stay in the good graces of authority figures. An obsequious person can
be called a bootlicker, a brownnoser or a toady. You can also say that
someone gives an obsequious bow, a gesture that means, "your wish is
my command."

He could become grave and charming for the aged, obsequious for the
rich, sober for the godly, masterful for the weak, mischievous for the
widow, arch and saucy for the spinster.
* premise                                                              :Dahl:
[2021-06-29 Tue 14:06]

The premises of a property consist of the land and buildings on it,
usually of a business or organization. If there are no dogs allowed on
the premises of a school, you'll have to leave your furry friend at
home.

A game of hide-and-go-seek where you can’t leave the house will go a
lot faster than one that permits hiding anywhere on the premises,
including outdoors. Premises has another, unrelated meaning — it can
also be the assumption or hypothesis from which a conclusion is
drawn. The English writer Samuel Butler said, “Life is the art of
drawing sufficient conclusions from insufficient premises.” Meaning,
much of life is about guesswork.

His premises were not large, and generally he didn’t do a great deal
of business, but because he always bought cheap, very very cheap, and
sold very very dear, he managed to make quite a tidy little income
every year.
* confound                                                             :Dahl:
[2021-06-29 Tue 14:06]

If you have an identical twin, you've probably tried dressing alike so
that people confound you with, or mistake you for, one another. You've
also probably learned that, unfortunately, this trick doesn’t work on
your mom.

The verb confound means both "to mistake" and "to confuse." If you
decide to treat yourself to a delicious dessert, you might find
yourself confounded by the overwhelming number of choices. If you end
up ordering the chocolate cake but the waiter brings you chocolate
mousse, the waiter has somehow confounded those two options. Another
meaning you may come across in literature is "to damn," as in
"Confound it! You are the most exasperating person on the planet."

Her husband continued searching through the pockets of his coat. Then
he unbuttoned the coat and felt around in his jacket. “Confound it,”
he said, “I must’ve left it in my bedroom. I won’t be a moment.”
* disconsolate :Dahl:
[2021-06-29 Tue 14:06]

If you are sad and can't be cheered up, you're disconsolate.  Why were
you disconsolate after scoring a touchdown?  Oh...it was for the other
team.

In addition to meaning "inconsolable," the adjective disconsolate can
also mean "dejected."  Most people would be disconsolate after being
laid off from a job, losing a beloved pet, or missing out on tickets
to see a favorite band play live. This word ultimately derives from
the Latin verb consolari, meaning "to cheer (someone) up or offer
comfort to."

Without a word, Mrs Foster jumped out and hurried through the main
entrance into the building. There was a mass of people inside, mostly
disconsolate passengers standing around the ticket counters. She
pushed her way through and spoke to the clerk.
* dapper :Dahl:
[2021-06-29 Tue 14:06]

A neatly and stylishly dressed man can be described as dapper. If you
like to wear a well-made fedora, you appreciate clothes. Place a
brightly colored feather in the brim and you’re dapper.

Dapper is a Germanic word coming from a Middle Dutch word that meant
"strong," "quick," or "nimble." Think of the words dashing, jaunty and
spiffy when you think of dapper as these are all near synonyms. All of
these words are used specifically to describe men. Although there
doesn't seem to be a parallel term for a well-dressed woman, if you
call her chic or stylish, she will be pleased.

As he spoke, a door opened and Mr Foster came into the hall. He stood
for a moment, looking intently at his wife, and she looked back at
him—at this diminutive but still quite dapper old man with the huge
bearded face that bore such an astonishing resemblance to those old
photographs of Andrew Carnegie.
* fond :Dahl:
[2021-06-29 Tue 14:07]

To be fond of something is to like it. Sports fans are fond of
sports. Oddly, this adjective can also mean foolish and silly.

We're all fond of some things and people: the things and people we
like. Being fond can mean anything from liking something a little
("I'm fond of that band") to be extremely, almost absurdly interested
in something ("He's a little too fond of football"). This word
sometimes implies foolishness and absurdity: almost like you love
something so much that you've lost your mind. But usually being fond
is a good thing: it just means you enjoy something.

This was an important journey for Mrs Foster. She was going all alone
to Paris to visit her daughter, her only child, who was married to a
Frenchman. Mrs Foster didn’t care much for the Frenchman, but she was
fond of her daughter, and, more than that, she had developed a great
yearning to set eyes on her three grandchildren.
* TODO bustling                                                        :Dahl:
[2021-06-29 Tue 14:07]



nil

Mr Eugene Foster, who was nearly seventy years old, lived with his wife in
a large six-storey house in New York City, on East Sixty-second Street, and they
had four servants. It was a gloomy place, and few people came to visit them. But
on this particular morning in January, the house had come alive and there was a
great deal of bustling about. One maid was distributing bundles of dust sheets to
every room, while another was draping them over the furniture. The butler was
bringing down suitcases and putting them in the hall. The cook kept popping up
from the kitchen to have a word with the butler, and Mrs Foster herself, in an
old-fashioned fur coat and with a black hat on the top of her head, was flying
from room to room and pretending to supervise these operations. Actually, she was
thinking of nothing at all except that she was going to miss her plane if her
husband didn’t come out of his study soon and get ready.

* finicky :Dahl:
[2021-06-30 Wed 17:37]

You reject any vegetable that isn't yellow. You like basmati rice, but
detest jasmine, Arborio, and brown. You dine at one restaurant, and
you always order the same meal. You are a finicky eater — that is, you
are quite particular about food.

Fastidious, fussy, picky, persnickety: these are all synonyms for
finicky, and they all suggest someone with extremely exacting tastes
and habits, someone almost impossible to please. Finicky can also be
used to describe something that demands a great deal of care and
attention to detail — a finicky lock might require that you jiggle the
key just so. Finicky generally conveys the sense that the person or
thing it describes is quirky and pointlessly precise.

The man had a way of making her feel that she was altogether a rather remarkable
woman, a person of subtle and exotic talents, fascinating beyond measure; and
what a very different thing that was from the dentist husband at home who never
succeeded in making her feel that she was anything but a sort of eternal patient,
someone who dwelt in the waiting-room, silent among the magazines, seldom if ever
nowadays to be called in to suffer the finicky precise ministrations of those
clean pink hands.
* wizened :Dahl:
[2021-06-30 Wed 17:37]

"You're looking quite wizened today," is a something you should never,
ever say to your grandmother, no matter how shriveled with age she
might be. Think of a caricature of a witch — not your beloved granny.

The verb wizen has fallen out of usage, but the past participle,
wizened, continues to function as an adjective meaning wrinkled and
shrunken with age or disease. You will see lots of elderly, wizened
faces at the park feeding the birds and watching the children
play. Although you might expect that folks with lined faces have
learned a thing or two, there is no etymological connection between
wizened and wise.

“The Colonel asked me to give you this,” a voice beside her said. She
turned and saw Wilkins, the Colonel’s groom, a small wizened dwarf with grey
skin, and he was pushing a large flattish cardboard box into her arms.
* tendrils :Dahl:
[2021-06-30 Wed 17:40]

Plants don't have arms or tentacles, but they have something a tiny
bit similar: tendrils. Tendrils are thin organs of plants that wrap
around other objects for support.

Tendrils are very thin, stem-like appendages that stretch outward from
the plant. The main purpose of the tendrils is to support the plant:
the tendrils wrap around objects (like a post or fence) to help keep
the plant upright, which helps it receive sunlight. Tendrils are an
example of how, even without a brain, plants are pretty smart.

She shut her eyes tight and slowly lifted off the lid. Then she put one
hand down into the box. There was some tissue paper on top; she could feel it and
hear it rustling. There was also an envelope or a card of some sort. She ignored
this and began burrowing underneath the tissue paper, the fingers reaching out
delicately, like tendrils.
* panting :Dahl:
[2021-06-30 Wed 17:42]



nil

She just couldn’t take her eyes off it. Nor, for that matter, could she
wait to try it on. Quickly she slipped off her own plain red coat. She was
panting a little now, she couldn’t help it, and her eyes were stretched very
wide. But oh God, the feel of that fur! And those huge wide sleeves with their
thick turned-up cuffs! Who was it had once told her that they always used female
skins for the arms and male skins for the rest of the coat? Someone had told her
that. Joan Rutfield, probably; though how Joan would know anything about mink she
couldn’t imagine.
* voluptuous :Dahl:
[2021-06-30 Wed 17:44]

The adjective voluptuous is used to describe someone who is attractive
and curvy. Marilyn Monroe was known for her voluptuous figure.

Being voluptuous means being full-figured and curvy, but this word
doesn't only apply to body types. A house that's luxurious, lavishly
decorated, and full of delicious food could also be called
voluptuous. This word derives from a Latin root meaning "delightful or
pleasurable."

She looked dazzling, radiant, rich, brilliant, voluptuous, all at the same time.
* pawnbroker :Dahl:
[2021-06-30 Wed 17:49]

A pawnbroker is someone who owns a shop that loans people money in
exchange for valuable items. If you want to hock your engagement ring,
head to a pawnbroker!

If you pawn your bike at a pawnbroker's shop (also called a pawnshop),
you will leave with cash, but not quite as much as your bike is
worth. To get it back, you'll have to pay back the money plus interest
— and if you don't, the pawnbroker will eventually sell your bike to
someone else. To pawn is to "give an object as security in exchange
for money," and a broker is a "seller of other people's goods."

“Driver,” she said, “would you know of a pawnbroker that’s still open
around here?”
* proprietor :Dahl:
[2021-06-30 Wed 17:51]

Someone who owns a business or a property is a proprietor.  A
bookstore proprietor might wish she became a librarian instead so the
books would come back.

The first part of proprietor sounds a lot like "property," and a
proprietor is someone with ownership of property. Sometimes a
proprietor oversees the business, such as a restaurant proprietor who
is also a chef or hostess, and other times a proprietor owns many
businesses and has different people running them. A proprietor of a
local bakery might make and sell his own donuts, while the proprietor
of a chain of donut shops might work from an office managing the
people who manage the stores.

“Yes?” the proprietor said, emerging from a dark place in the back of the
shop.
* redeem :Dahl:
[2021-06-30 Wed 17:52]

If you redeem yourself, you make up for wrongs by doing something that
makes you seem good again, like when after being irritable and snappy
with your grandmother, you redeem yourself by bringing her flowers and
apologizing.

Redeem comes from the French rédimer, which means "to deliver," and
which in turn comes from the Latin for "buy back." In Christianity you
can be redeemed by renouncing your sins. Classic heroes fail and then
redeem themselves with valiant acts. But redeem doesn't have to be
religious or moral. When you turn in a glass bottle for recycling, you
redeem it, just as you redeem your coupon for 20% off your next
hamburger.

Then I’ll come back and redeem it.”
* fondling :Dahl:
[2021-06-30 Wed 17:53]



nil

“It looks new,” the man said, fondling the soft fur.
* horseradish :Dahl:
[2021-06-30 Wed 17:59]

Horseradish is a root vegetable that's closely related to
mustard. It's also the name of a sharp-flavored condiment made from
the horseradish plant.

You're most likely to find horseradish on a roast beef sandwich or
adding its pungent flavor to the cocktail sauce you dip your shrimp
in. In Poland and the U.K., horseradish is extremely common,
especially as part of a "roast dinner." The prepared horseradish
that's used as a condiment is made by grating the plant's root and
mixing it with vinegar, salad dressing, or mayonnaise.

It was funny how small he always looked after the Colonel. The Colonel was
huge and bristly, and when you were near to him he smelled faintly of
horseradish. This one was small and neat and bony and he didn’t really smell of
anything at all, except peppermint drops, which he sucked to keep his breath nice
for the patients.
* prognathous :Dahl:
[2021-07-01 Thu 17:29]



nil

I really must try to make him change the way he dresses, she told
herself. His suits are just too ridiculous for words. There had been a time
when she thought they were wonderful, those Edwardian jackets with high
lapels and six buttons down the front, but now they merely seemed absurd. So
did the narrow stovepipe trousers. You had to have a special sort of face to
wear things like that, and Cyril just didn’t have it. His was a long bony
countenance with a narrow nose and a slightly prognathous jaw, and when you
saw it coming up out of the top of one of those tightly fitting old-fashioned
suits it looked like a caricature of Sam Weller. He probably thought it
looked like Beau Brummel. It was a fact that in the office he invariably
greeted female patients with his white coat unbuttoned so that they would
catch a glimpse of the trappings underneath; and in some obscure way this was
obviously meant to convey the impression that he was a bit of a dog. But Mrs
Bixby knew better. The plumage was a bluff. It meant nothing. It reminded her
of an ageing peacock strutting on the lawn with only half its feathers left.
* strutting :Dahl:
[2021-07-01 Thu 17:30]

When you strut, you walk with a proud swagger that has a little
arrogance thrown in, like the prance of a running back who has just
flown past the 250-pound linebackers and planted the ball in the end
zone.

You can't strut and be shy about it — when you strut, you know people
are watching you. The big boss in a gangster film, a model on the
runway, and the rap artist whose album has just gone platinum all know
how to strut. The noun form of strut has a little less flash and
refers to a vertical or horizontal support that holds something up,
like the long steel bars holding up a building.

I really must try to make him change the way he dresses, she told
herself. His suits are just too ridiculous for words. There had been a time
when she thought they were wonderful, those Edwardian jackets with high
lapels and six buttons down the front, but now they merely seemed absurd. So
did the narrow stovepipe trousers. You had to have a special sort of face to
wear things like that, and Cyril just didn’t have it. His was a long bony
countenance with a narrow nose and a slightly prognathous jaw, and when you
saw it coming up out of the top of one of those tightly fitting old-fashioned
suits it looked like a caricature of Sam Weller. He probably thought it
looked like Beau Brummel. It was a fact that in the office he invariably
greeted female patients with his white coat unbuttoned so that they would
catch a glimpse of the trappings underneath; and in some obscure way this was
obviously meant to convey the impression that he was a bit of a dog. But Mrs
Bixby knew better. The plumage was a bluff. It meant nothing. It reminded her
of an ageing peacock strutting on the lawn with only half its feathers left.
* fatuous :Dahl:
[2021-07-01 Thu 17:31]

Fatuous means lacking intelligence. When your mother outlaws calling
your brother stupid, use fatuous instead.

Fatuous derives from the Latin fatuus meaning "foolish." It sounds
like it should have something to do with being fat, but it actually
has no relation to size. Fatuus itself comes from a root that also
gave us "debate" and this might be a good way to remember it. You want
to debate someone who's fatuous, because they are unintelligent, silly
and even a bit conceited, so they probably won't be very persuasive
debaters. Just don't call them fatuous to their face. Even if they
don't know what it means, it's just not nice!

Or one of those fatuous self-fertilising flowers—like the dandelion. A
dandelion never has to get fertilised for the setting of its seed, and all
those brilliant yellow petals are just a waste of time, a boast, a
masquerade. What’s the word the biologists use? Sub-sexual. A dandelion is
subsexual. So, for that matter, are the summer broods of water fleas. It
sounds a bit like Lewis Carroll, she thought—water fleas and dandelions and
dentists.
* broods :Dahl:
[2021-07-01 Thu 17:32]

A brood is a group of young born at the same time — like a brood of
chicks — but your parents might use the word for you and your
siblings: "We're taking the whole brood to the movies tonight."

Brood is also what a chicken does when she sits on her eggs to hatch
them. You can also brood, when you worry and sulk and dwell on
something obsessively — maybe as tedious as sitting on eggs, but no
chicks when you're done. Things like clouds or silence can also brood,
hanging over something ominously, as a storm that broods over the sea,
sending fishermen scurrying for safety.

Or one of those fatuous self-fertilising flowers—like the dandelion. A
dandelion never has to get fertilised for the setting of its seed, and all
those brilliant yellow petals are just a waste of time, a boast, a
masquerade. What’s the word the biologists use? Sub-sexual. A dandelion is
subsexual. So, for that matter, are the summer broods of water fleas. It
sounds a bit like Lewis Carroll, she thought—water fleas and dandelions and
dentists.
* handkerchief :Dahl:
[2021-07-01 Thu 17:34]

A handkerchief is a square of fabric that you can use to blow your
nose. You can also tuck a handkerchief in the breast pocket of a suit,
or wear it tied jauntily around your neck.

You can call a handkerchief a "hanky," or just a kerchief, although
this more often means "a square piece of cloth worn as a head
covering." This last part of handkerchief comes from the Old French
couvrechief, literally meaning "cover head," from couvrir, "cover,"
and chief, "head." So a handkerchief is a similar cloth held in the
hand — to mop your brow or wipe your eyes.

“This Martini is perfect,” Mrs Bixby said, setting down her glass on
the side table. “Quite perfect.” She opened her bag and took out a
handkerchief as if to blow her nose. “Oh look!” she cried, seeing the ticket.
* minutely :Dahl:
[2021-07-01 Thu 17:34]

Do something minutely and you'll do it in an attentive or meticulous,
careful way. If you minutely edit your English paper, you'll be sure
to catch every last mistake.

A detective might investigate a crime minutely, examining every
possible clue in an intent way. Minutely can also modify an adjective,
as in a minutely detailed news report or a minutely precise dollhouse
version of Buckingham Palace. At the root of minutely is the Latin
minutus, "little, small, or minute."

She handed the small piece of stiff brown paper to her husband, who
took it in his fingers and began examining it minutely from all angles, as
though it were a suspect tooth.
* magnanimously :Dahl:
[2021-07-01 Thu 17:41]



nil

“In that case I’ll give it to you for Christmas,” Mrs Bixby said
magnanimously. “I’ll be delighted. But if it’s a woman’s thing, I want it
myself. Is that agreed?”
* rather :Dahl:
[2021-07-01 Thu 17:44]

Use rather to specify a preference for one thing over
another. Wouldn't you rather go to the movies than stay home and clean
the house?

Rather can also be used to mean "on the contrary," or to introduce a
contradiction. You didn't believe in ghosts — rather thinking there
was a scientific explanation for any ghostly appearances — until you
saw a ghost yourself. The adverb rather also means "to a certain
degree." You might grudgingly admit that your mom's strange-sounding
chocolate-avocado pudding was actually rather tasty.

“You know, I’m sort of hoping it’ll be something for you, Cyril. I’d
much rather it was for you than for me.”
* Coyly :Dahl:
[2021-07-01 Thu 17:49]



nil

Coyly, beginning to giggle, she raised one eyelid a fraction of an
inch, just enough to give her a dark blurry view of the man standing there in
his white overalls holding something up in the air.
* neckpiece :Dahl:
[2021-07-01 Thu 17:51]



nil

But there was no coat. There was only a ridiculous little fur
neckpiece dangling from her husband’s hand.
* lilt :Dahl:
[2021-07-01 Thu 17:54]

Use the word lilt to describe a swinging kind of tempo in music. You
might love old fashioned big band jazz because of its distinctive
lilt.

Upbeat, rhythmic music of any kind has a lilt, and you can also
describe certain ways of speaking as having a lilt. In this case, the
lilt is either the rhythm of a person's speech, or her accent — an
Irish accent is often called an "Irish lilt." Lilt can be a verb, too,
as when you lilt out a song. The earliest meaning of the word was "to
lift up one's voice," from the West Midlands lulten, "to sound an
alarm."

“Isn’t it a gorgeous day?” Miss Pulteney said as she went by, flashing
a smile. There was lilt in her walk, a little whiff of perfume attending her,
and she looked like a queen, just exactly like a queen in the beautiful black
mink coat that the Colonel had given to Mrs Bixby.
* translucent :Dahl:
[2021-07-08 Thu 13:04]

A translucent material lets light pass through, but objects on the
other side can't be seen clearly. Think Shrinky Dinks or stained
glass.

In contrast, a transparent material allows you to clearly see the
objects on the other side. Frosted glass is translucent, and regular
glass is transparent. But opaque glass doesn't let any light through
at all, and so you can't see through it. The adjective translucent is
from Latin translucens, from translucere "to shine through."

The skin on the baby’s face had a pearly translucent quality, and was
stretched very tightly over the bones.
* weeny :Dahl:
[2021-07-08 Thu 13:05]



nil

“Please,” she said. “Take just a weeny bit more.”
* cot :Dahl:
[2021-07-08 Thu 13:09]

A cot is a small, portable bed. You might sleep on a cot when you go
camping.

Some hotels offer cots for extra guests who stay in your room, and
campers and soldiers on the move often use cots for sleeping. A cot's
benefits include its light weight and ability to be folded into an
easily carried size. In Britain, a cot is a baby bed or crib. Cot has
a Hindi source, khat, "couch, bed, or hammock" from the Sanskrit
khatva.

In a little while he heard her moving about in the bedroom directly
over his head, quick nervous footsteps going tap tap tap on the linoleum
above. Soon the footsteps would stop, and then he would have to get up and
follow her, and when he went into the bedroom he would find her sitting
beside the cot as usual, staring at the child and crying softly to herself
and refusing to move.
* noxious :Dahl:
[2021-07-08 Thu 13:12]

Something noxious is harmful and could be even fatal — whether it is
colorless, odorless, and invisible like carbon monoxide, or dark,
strong-smelling, and obvious, like black smoke from a fire. People are
called noxious too when they hurt others with cruelty or mental
anguish.

English and Latin roots for noxious are related to the meanings of
"harm," "damage," and "injury." While obnoxious might come to mind
when seeing the word noxious, obnoxious is a much less damaging
adjective to describe someone annoying. Most uses for noxious involve
real physical or emotional damage unless the word is used in
exaggeration. Examples range from "the noxious gas fumes made the dog
pass out" to "his cologne was so noxious I had to exit the elevator
and take the stairs."

His father, who was a bricklayer, said there must be some witch’s
stench about the boy, something noxious that came oozing out through the
pores of the skin, and that no good would ever come of it, hypnotising
insects like that. But the mother said it was a gift given him by God, and
even went so far as to compare him with St Francis and the birds.
* diluted :Dahl:
[2021-07-08 Thu 13:19]



nil

Royal jelly is fed in concentrated form to all bee larvae for the first
 three days after hatching from the egg; but beyond that point, for all
 those who are destined to become drones or workers, this precious food is
 greatly diluted with honey and pollen. On the other hand, the larvae
 which are destined to become queens are fed throughout the whole of their
 larval period on a concentrated diet of pure royal jelly. Hence the name.
* nipper :Dahl:
[2021-07-08 Thu 13:24]



nil

“I’m taking the nipper and myself and the alarm clock into the spare
room this very moment, so you just lie down and relax and forget all about
us. Right?” Already he was pushing the cradle out through the door.
* frowning :Dahl:
[2021-07-08 Thu 13:28]



nil

She looked up at him across the cot, frowning. “No,” she said. “Oh no,
I wouldn’t allow you to do that.”