-*- coding: utf-8 -*-



* muster :misc:
[2021-02-02 Tue 13:43]

Originally meaning "to gather soldiers," muster has been expanded to
include gathering up just about anything — you can muster up some
dinner, some friends, or even some ketchup, pickles and mustard.

Remember that muster used to involve getting reluctant soldiers out of
bed and into the field of battle — so it involves overcoming a certain
inertia. When you muster up the courage to face something, it's clear
that this is pretty scary for you.

When I didn’t feel like I was having an impact during office hours, it
was that much harder to muster the effort to have an impact afterward.

* feasible :misc:
[2021-02-03 Wed 15:10]

If something is feasible, then you can do it without too much
difficulty. When someone asks "Is it feasible?" the person is asking
if you'll be able to get something done.

Feasible things are possible. If you have enough time, money, or
energy to do something, it's feasible. Something might be feasible at
one time and then not feasible at another time. Because of
technological advances and competition with the Russians, going to the
moon was feasible for the United States in the sixties. Often, people
disagree about what's feasible, especially in politics, where how
feasible a project is counts for a lot.

The music industry is too cruel an environment for this to be a
feasible plan.
* facet                                                                :misc:
[2021-02-03 Wed 15:15]

A facet is one side or aspect of something. If you’re thinking about
quitting your day job to become a circus performer, you should first
consider every facet of what your new life would be like.

Facet, which is related to the word face, can also refer to one of the
flat “faces” of a diamond or other gem. This was the word’s original
definition, and it was evidently seen as an apt metaphor for one side
of a complex idea. When a problem has many parts to consider (or when
it’s just a huge mess), you can describe it as multifaceted.

And we’ll see how these four facets can be applied to our careers:
* languish :misc:
[2021-02-03 Wed 15:20]

To languish is to become pitiful or weak because you're sick, in love,
or stuck somewhere. A prisoner might languish in jail, longing for her
freedom.

Languish, like languid, is from the Latin word languere which means
"to be weak or faint." Your houseplants might languish in a dark dry
corner. A Romantic poet might languish on a velvet couch with the back
of her hand to her forehead. People in operas love to languish: The
main character in La Traviata, Violetta, languishes from longing and
eventually tuberculosis.

Remarkable software developers don’t languish.
* recoup :misc:
[2021-02-03 Wed 15:26]

To recoup is a kind of recovery: If you lost some money but then made
that amount back, you recouped your loss.

When you recuperate, you get better after being sick. And when you
recoup something, you get better or bounce back after a loss.
Businesses that lose money try to recoup it by throwing a sale or
cutting their budget. If a runner falls behind in a race but then
speeds up to the front of the pack, he's recouped his lead. In some
cases this word also means "to reimburse."

On the other hand, you have no guarantee that you’ll even recoup your
original investment.
* pundit                                                               :misc:
[2021-02-03 Wed 15:32]

A pundit is a well-known expert, someone whose opinions show up on
television, online, or in the newspaper. Some TV news programs are
nothing more than a bunch of pundits arguing about current events.

Why not just call them experts? Because pundit is a lovely word that
is very close to its Sanskrit root, payndita-s, "learned man or
scholar." Originally, a pundit was a "learned Hindu" or Sanskrit
expert. Today's classic examples of the pundit are guests on talk
radio and professional sports commentators, all brilliant dispensers
of insights, statistics, and occasional hot air.

The platform created a definite buzz, and the pundits were giddy in
anticipation of a solid new contender on the operating system block.
* stalwart                                                             :misc:
[2021-02-04 Thu 14:25]

To be stalwart is to be loyal, no matter what, like your friend who
remains a devoted fan of an actor she's admired since childhood, even
if that was the last time the guy made a decent movie.

Stalwart can describe someone who's able to keep on going even when
things get hard, like a marathon runner who doesn't slow down, even
after spraining an ankle, or a supporter of a political cause that
everyone else has long declared over. In U.S. history, the word
stalwart was used in 1877 to describe Republicans who remained
unwilling to trust the South, even though the Civil War was long over
by that time.

It’s easy to imagine that the careers of the last-remaining stalwarts
of an aged and dying technology are in the same death spiral as the
technology itself.
* tyke                                                                 :misc:
[2021-02-04 Thu 14:27]

A tyke is a child, especially a small one. A nursery school is full of
tykes.

Little kids are a handful, as all parents and teachers know. Maybe
that's why there are some slangy words for them, such as rugrat and
tyke. Tyke is a very informal word: a letter from the principal
wouldn't call a kid a tyke. However, an uncle or friend of the family
might say, "How are you tykes doing?" This word is a little
old-fashioned, but it's still used.

Typically, the young tykes don’t know (or want to know) how to make
the old systems listen.
* clump :misc:
[2021-02-04 Thu 14:32]

A clump is a "bunch" or a "cluster." If you're a gardener, the last
thing you want to see is a clump of weeds growing in the middle of
your newly groomed lawn.

Essentially, a clump is a grouping. You might see a clump of sheep
grazing in a field or you might throw a clump of clothes into the
washing machine. Clump can also mean lump, like when you find a clump
of grass stuck to your shoe. As a verb, clump means "to gather," as in
"a flock of birds clumped together in a tree."

Do they clump?
* cater                                                                :misc:
[2021-02-04 Thu 14:41]

To cater means to supply food for meetings or celebrations. If you're
having a big barbecue party but would rather hang out with your
friends than grill, you could pay someone to cater it.

In Middle English, the food supply in a big household was known as the
cates, and so to cater meant keeping the pantry full. These days,
caterers don't do pantries. They cook food for many different
households or offices. Cater has also come to mean "giving what is
desired or needed." You might cater to your grandfather by bringing
him tea, reading to him, and laughing at his bad jokes.

India caters to the
already balanced IT services markets.
* nimble :misc:
[2021-02-04 Thu 14:45]

If you're nimble, you can move quickly and with ease. That spryness
can be both physical and mental, so even if your granny isn't very
nimble on her feet, she can probably still whip you in chess.

A toddler might recognize the word nimble from the nursery rhyme:
"Jack be nimble / Jack be quick / Jack jump over / The candlestick,"
but may not be nimble enough to deduce the meaning. Nimble, from the
14th century Old English næmel, meaning "quick to grasp," can refer to
one's mental quickness or physical agility.

In either case, it pays to understand the forces at work and to be
skilled and nimble enough to react to them.

* unnerving :misc:
[2021-02-08 Mon 12:06]

Use the adjective unnerving to describe situations and experiences
that cause you to lose your courage. No matter how brave you are, a
walk alone through a cemetery at night is bound to be a little
unnerving.

You might find it unnerving to get a flat tire on a deserted country
road at sunset, or to find yourself onstage mid-play having completely
forgotten your lines. In the 1620's, the root word unnerve meant "to
destroy the strength of," but by the early 1700's it came to mean "to
deprive of courage."

Yes, it’s extremely unnerving at first.
* sore :misc:
[2021-02-08 Mon 12:07]

A sore is a broken patch of skin — something you might put a bandage
on — or it's something that gives you pain, like a sore throat, that’s
red and scratchy and painful.

You can have a sore and you can also be sore: if you've just ridden
your bike over the Alps, you're probably pretty sore — achy and
hurting all over. Maybe you've heard phrases like "Don't be sore at
me, boss," from old gangster movies, meaning "don't be angry." A sore
point or a sore subject is something you don't want to discuss, like
the sensitive topic of your last history quiz, the one you slept
through.

As a young musician, I would find myself in situations where I was so
obviously the worst guy in the band that I was sure I would stick out like a
sore thumb.
* glamorous :misc:
[2021-02-08 Mon 12:10]

Movie stars look glamorous when they walk down the red carpet in their
designer gowns. Glamorous means full of glamour, beauty, and
excitement.

Glamorous comes from the Scottish gramarye meaning "magic,
enchantment, spell." See a glamorous woman walking down the street and
you might be captivated or enchanted by her beauty. A person can
appear or act glamorous. An event like a really over-the-top party can
be glamorous. Or a lifestyle that one chooses for herself can be
glamorous, full of parties and swanky events.

I’d like to think I had some kind of superhuman
ability to morph into a genius simply by standing next to one, but in
retrospect I think it’s a lot less glamorous than that.
* slurs :misc:
[2021-02-08 Mon 12:14]

A slur is an insulting remark. In a political campaign, it’s not
unheard of for a candidate to launch a slur at her opponent, though
doing so is usually frowned upon.

Slur can also be used as a verb meaning “to insult,” and it has a
number of additional meanings as well. To slur one’s speech is to
pronounce words in a clumsy, lazy way. In the context of music, to
slur is to slide smoothly from one note to another. The word history
of slur is hazy, but some scholars have suggested a relationship with
a Dutch word meaning "to drag."

Also, like an alcoholic who slurs his speech even when he’s not drunk, I’d find
the bad habits of the bar bands carrying over to my non-bar-band nights.
* outright :misc:
[2021-02-08 Mon 13:26]

If you do something outright, you do it in a wholehearted,
unrestricted way. If you declare outright that you’re never eating
another cupcake, that’s the end of that. If you eat one anyway, you
told an outright lie.

If an event is cancelled outright, there's no question about it being
rescheduled, and if you buy a new car outright, you pay for it all at
once, instead of making monthly payments. Outright means direct and
immediate — whether it's an adverb or an adjective: "The child's
outright refusal to put on his shoes exasperated his babysitter." It
can also mean “right away.” If you step on a slug, you’ll probably
kill it outright. Ew.

Acknowledging outright that you’re not the best
wipes away the fear of being discovered for the not-best person you are.
* provable :misc:
[2021-02-08 Mon 13:34]



nil

It’s definitely not a scientifically provable measure of
popularity, but it’s a pretty good indicator.