-*- coding: utf-8 -*-

* facetious :Zen:
[2021-06-21 Mon 17:48]

Don’t take a facetious comment seriously because it’s supposed to be
funny. Anything facetious is a joke. If you've just won a
hotdog-eating contest and someone asks if you'd like to go out for
burgers, they’re probably being facetious.

If you forget how to spell facetious, notice that it has all five
vowels in a row. The word facetious comes from the French facétie,
“joke,” and it has come to describe a joke with a little drop of
sarcasm. It used to simply mean “funny and witty,” but now it often
implies that someone is being inappropriately funny about a serious
topic.

He looks at me pleadingly. He really does want to know things sometimes. Being
facetious is not being a very good father. “Sure,” I say, reversing myself, “I
believe in ghosts too.”

* sheared :Zen:
[2021-06-21 Mon 17:51]



nil

On this trip I think we should notice it, explore it a little, to see if in that
strange separation of what man is from what man does we may have some clues as to
what the hell has gone wrong in this twentieth century. I don't want to hurry
it. That itself is a poisonous twentieth-century attitude. When you want to hurry
something, that means you no longer care about it and want to get on to other
things. I just want to get at it slowly, but carefully and thoroughly, with the
same attitude I remember was present just before I found that sheared pin. It was
that attitude that found it, nothing else.
* tappets :Zen:
[2021-06-21 Mon 17:51]



nil

The overhead-cam chain-tensioner bolt was also missing, meaning it would have
been hopeless to try to adjust the tappets anyway. Nightmare.
* nut :Zen:
[2021-06-21 Mon 17:51]

A nut is a kind of fruit made of a large, edible seed with a very hard
shell around it. The nuts that squirrels typically gather (sometimes
storing them temporarily in their cheek pouches) are acorns.

It might seem strange that a nut is a fruit, since until they've been
cracked open, most nuts are as hard and inedible as rocks. Think of
the meat of a walnut or almond that hides inside — this is the edible
seed within the fruit. If someone calls you a nut, or describes you as
nuts or nutty, they think you're crazy or wacky, and when you refer to
"a tough nut to crack," you're talking about a tricky problem.

I got out of there as fast as possible, noisy tappets, shot tappet covers, greasy
machine, down the road, and then felt a bad vibration at speeds over twenty. At
the curb I discovered two of the four engine-mounting bolts were missing and a
nut was missing from the third. The whole engine was hanging on by only one bolt.
* chisel :Zen:
[2021-06-21 Mon 17:52]

When you carve a statue from a block of marble, you use a tool called
a chisel to cut out the shape. Chisel is the name of the tool and also
the name of the action.

A chisel has a flat, sharp end. To carve using a chisel, you hit the
back of it with a hammer or another blunt instrument. Chisel can also
mean "to cheat." If someone chisels you out of your allowance, they
shaved it away from you bit by bit.

He brought out a hammer and cold chisel and started to pound them loose. The
chisel punched through the aluminum cover and I could see he was pounding the
chisel right into the engine head. On the next blow he missed the chisel
completely and struck the head with the hammer, breaking off a portion of two of
the cooling fins.
* cirrus :Zen:
[2021-06-21 Mon 17:52]



nil

If it's just thunderheads or broken line squalls you can try to ride around
them, but this one isn't. That long dark streak without any preceding cirrus
clouds is a cold front. Cold fronts are violent and when they are from the
southwest, they are the most violent. Often they contain tornadoes. When they
come it's best to just hole up and let them pass over. They don't last long
and the cool air behind them makes good riding.
* demean :Zen:
[2021-06-21 Mon 17:52]

To demean someone is to insult them. To demean is to degrade or put
down a person or thing.

If you noticed the word mean in demean, that's a good clue to its
meaning. To demean someone is very mean. You are demeaning your sister
or brother if you run their underwear up a flagpole. A teacher could
demean a student by saying "You're stupid!" To demean is to insult: no
one wants to be demeaned. Insulting language is often called
demeaning. We can also say a bad president demeaned his office.

I disagree with them about cycle maintenance, but not because I am out of
sympathy with their feelings about technology. I just think that their flight
from and hatred of technology is self-defeating. The Buddha, the Godhead, resides
quite as comfortably in the circuits of a digital computer or the gears of a
cycle transmission as he does at the top of a mountain or in the petals of a
flower. To think otherwise is to demean the Buddhawhich is to demean oneself.
* TRESPASSING :Zen:
[2021-06-21 Mon 17:53]

Something that is trespassing is slowly intruding into where it
doesn't belong. A trespassing stranger is breaking the law.

If you've ever seen a "No trespassing" sign, you probably know it
means "Keep out!" Similarly, anything described as trespassing is
creeping or otherwise moving where it doesn't belong. Trespassing kids
are playing in the neighbor's lawn. A trespassing dog is getting into
the chicken coop. A trespassing tree might be growing where it
shouldn't be and needs to be trimmed. This word always describes
people, animals, and things that go where they shouldn't. Trespassing
things are invasive and encroaching.

That attitude is not hard to come to. You go through a heavy industrial area of a
large city and there it all is, the technology. In front of it are high
barbed-wire fences, locked gates, signs saying NO TRESPASSING, and beyond,
through sooty air, you see ugly strange shapes of metal and brick whose purpose
is unknown, and whose masters you will never see. What it's for you don't
know, and why it's there, there's no one to tell, and so all you can feel
is alienated, estranged, as though you didn't belong there. Who owns and
understands this doesn't want you around. All this technology has somehow made
you a stranger in your own land. Its very shape and appearance and mysteriousness
say, “Get out.” You know there's an explanation for all this somewhere and
what it's doing undoubtedly serves mankind in some indirect way but that
isn't what you see. What you see is the NO TRESPASSING, KEEP OUT signs and not
anything serving people but little people, like ants, serving these strange,
incomprehensible shapes. And you think, even if I were a part of this, even if I
were not a stranger, I would be just another ant serving the shapes. So the final
feeling is hostile, and I think that's ultimately what's involved with this
otherwise unexplainable attitude of John and Sylvia. Anything to do with valves
and shafts and wrenches is a part of that dehumanized world, and they would
rather not think about it. They don't want to get into it.
* faucet :Zen:
[2021-06-21 Mon 17:53]

Water comes out of your faucet and into your sink or bathtub. A faucet
is a device that allows you to turn the flow of water on and off.

The faucet is not just the metal part that the water comes through, it
is the whole mechanism for controlling the flow of water. If you cry
easily, someone might say you are a regular faucet. This is because
water comes out of your eyes more often than it does for most
people. If you ask your parents a little too often for cash, they
might joke that they're going to turn off the money faucet.

It's not the motorcycle maintenance, not the faucet. It's all of technology
they can't take. And then all sorts of things started tumbling into place and
I knew that was it. Sylvia's irritation at a friend who thought computer
programming was “creative.” All their drawings and paintings and photographs
without a technological thing in them. Of course she's not going to get mad at
that faucet, I thought. You always suppress momentary anger at something you
deeply and permanently hate. Of course John signs off every time the subject of
cycle repair comes up, even when it is obvious he is suffering for it. That's
technology. And sure, of course, obviously. It's so simple when you see it. To
get away from technology out into the country in the fresh air and sunshine is
why they are on the motorcycle in the first place. For me to bring it back to
them just at the point and place where they think they have finally escaped it
just frosts both of them, tremendously. That's why the conversation always
breaks and freezes when the subject comes up.
* choke :Zen:
[2021-06-21 Mon 17:53]

When you choke, you are suddenly unable to breathe, often because
something is stuck in your throat. Your dad's rude joke might make you
gasp and choke on your grilled cheese sandwich.

You might choke in a smoky room, or choke on a grape that's lodged
halfway down your throat. In either case, your body can't get enough
oxygen. People also choke up with emotion, figuratively choking on
their sobs. Likewise, a child might complain, "This scarf chokes me!"
— it's uncomfortably tight, but he's not literally unable to
breathe. When the weeds in your garden outnumber the vegetables, you
can also say they choke, or crowd, your plants.

He scratches his head. “Well, why don't they tell you that in the
instructions?” He opens the choke and on the second kick it starts. “I guess that
was it,” he says cheerfully.
* scorcher :Zen:
[2021-06-21 Mon 17:54]



nil

Not a bit of moisture in the sky. Today's going to be a scorcher.
* hoarse :Zen:
[2021-06-21 Mon 17:54]

A hoarse voice is deep and rough and kind of hard to make out. People
get hoarse when they're sick, or when they are calling in sick to
work.

If you're supposed to perform in a play tonight, you'd better hope you
don't get hoarse: a hoarse voice doesn't sound the way it should. It's
scratchy, gruff, and hard to understand. Sometimes people get hoarse
from talking too much. Inhaling smoke can make you hoarse too. On the
other hand, some people have raspy, husky, rough-sounding voices that
sound hoarse all the time. You could ask them, "Are you hoarse?" They
might say, "Nah, I always sound like this."

So it is with John. I could preach the practical value and worth of motorcycle
maintenance till I'm hoarse and it would make not a dent in him. After two
sentences on the subject his eyes go completely glassy and he changes the
conversation or just looks away. He doesn't want to hear about it.
* apparent :Zen:
[2021-06-21 Mon 17:55]

Apparent means obvious, but — and this is confusing — it can also mean
something that seems to be true but isn't definite. "The train's
arrival is apparent — it's in the station — but apparently my friend
missed it because she is not getting off."

It makes sense that apparent has the same ancient root as appear
because it's about what is plain to see. Its subtle power of
suggestion, however, is wonderfully useful. The "heir apparent"
technically means next in line, but the ink isn't dry. The power of
apparent is that it leaves the door open for a little ambiguity. Maybe
the heir apparent will be the next king, or maybe he'll be overthrown
in a bloodless coup by his apparently more ambitious cousin.

And, of course, when you discover something like that it's like discovering a
tooth with a missing filling. You can never leave it alone. You have to probe it,
work around it, push on it, think about it, not because it's enjoyable but
because it's on your mind and it won't get off your mind. And the more I
probe and push on this subject of cycle maintenance the more irritated he gets,
and of course that makes me want to probe and push all the more. Not deliberately
to irritate him but because the irritation seems symptomatic of something deeper,
something under the surface that isn't immediately apparent.
* deadpan :Zen:
[2021-06-21 Mon 17:55]

Use the word deadpan to describe someone who uses no expression when
speaking, such as the deadpan way some comedians deliver even their
funniest jokes — which can make them even funnier.

Deadpan dates to 1928, when pan was slang for "face." So if you seem
to have a "dead face" as you say something, it means your face looks
very blank — no energy or animation. Deadpan is associated with
sarcasm, and like sarcasm, if you use it for comic effect, there's a
risk your audience won't pick up on it. Nevertheless, deadpan humor
can be funny and popular — witness the success of deadpan humor in the
sitcom Seinfeld.

”Let's not start that,” Sylvia says. They look at each other deadpan and then
both look over at me.
* silt :Zen:
[2021-06-21 Mon 17:55]

Silt is the fine bits of clay and sand that become sediment settling
at the bottom of a river or lake. If there's a lot of silt flowing in
a river, it looks murky.

Silt is the super-fine dirt that you might see at the bottom of a lake
or river. When your feet touch silt it feels slimy, and once it’s
stirred it up the water looks muddy. Where the Mississippi River
enters the Gulf of Mexico, a lot of silt has been deposited and over
time has built up a portion of land called the Mississippi Delta. The
region surrounding this accumulation of silt is home to music called
the Delta Blues.

The old channels cannot contain it and in its search for new ones there seems to
be growing havoc and destruction along its banks. In this Chautauqua I would like
not to cut any new channels of consciousness but simply dig deeper into old ones
that have become silted in with the debris of thoughts grown stale and platitudes
too often repeated. “What's new?” is an interesting and broadening eternal
question, but one which, if pursued exclusively, results only in an endless
parade of trivia and fashion, the silt of tomorrow. I would like, instead, to be
concerned with the question “What is best?,” a question which cuts deeply rather
than broadly, a question whose answers tend to move the silt downstream. There
are eras of human history in which the channels of thought have been too deeply
cut and no change was possible, and nothing new ever happened, and “best” was a
matter of dogma, but that is not the situation now. Now the stream of our common
consciousness seems to be obliterating its own banks, losing its central
direction and purpose, flooding the lowlands, disconnecting and isolating the
highlands and to no particular purpose other than the wasteful fulfillment of its
own internal momentum. Some channel deepening seems called for.
* nutty :Zen:
[2021-06-21 Mon 17:57]



nil

”It's completely natural,” I say, “to think of Europeans who believed in
ghosts or Indians who believed in ghosts as ignorant. The scientific point of
view has wiped out every other view to a point where they all seem primitive, so
that if a person today talks about ghosts or spirits he is considered ignorant or
maybe nutty. It's just all but completely impossible to imagine a world where
ghosts can actually exist.”
* swanky                                                               :Dahl:
[2021-06-23 Wed 13:02]

Swanky things are fancy and stylish, like a swanky hotel lobby with
sparkling chandeliers, plush furniture, and elegant guests.

You can also call swanky things ritzy or classy. They're expensive and
luxurious, like a swanky car, a swanky apartment building with a
doorman, or a swanky neighborhood where only movie stars can afford to
live. The adjective swanky comes from its less-common synonym swank,
which stems from the now-obsolete verb swank, "to behave
ostentatiously."

There were no shops on this wide street that he was walking along, only a
line of tall houses on each side, all of them identical. They had porches and
pillars and four or five steps going up to their front doors, and it was obvious
that once upon a time they had been very swanky residences. But now, even in the
darkness, he could see that the paint was peeling from the woodwork on their
doors and windows, and that the handsome white façades were cracked and blotchy
from neglect.
* vault                                                                :Dahl:
[2021-06-23 Wed 13:02]

Vault is a verb that means "to jump over something." If you were
hurrying out to the pasture to visit your favorite cow, you might
vault over the gate in your excitement.

When you support yourself with your hands as you jump over some
hurdle, you vault, just as a gymnast might do across a vault — a piece
of gymnastic equipment made to be vaulted over after a running
start. Another meaning of vault is the arched roof of a building, or
something that resembles such an archway. A storage chamber,
especially one that's kept underground, is also a vault, like a bank
vault.

“So the next problem would be to remove your brain, intact and
 undamaged, from your dead body. The body is useless. In fact it has already
 started to decay. The skull and the face are also useless. They are both
 encumbrances and I don’t want them around. All I want is the brain, the clean
 beautiful brain, alive and perfect. So when I get you on the table I will
 take a saw, a small oscillating saw, and with this I shall proceed to remove
 the whole vault of your skull. You’d still be unconscious at that point so I
 wouldn’t have to bother with anaesthetic.”
* encumbrances                                                         :Dahl:
[2021-06-23 Wed 13:03]

A burden or serious concern is an encumbrance. Your being five feet
tall could be an encumbrance when it comes to your dream of playing
professional basketball.

Something that blocks you from doing what you want to do is an
encumbrance, like the rocky soil in your garden that makes it
impossible for you to grow tomatoes. A burden or hindrance can also be
an encumbrance, the way wearing thick knitted mittens makes it harder
for you to dial your cell phone — your mittens are an encumbrance. The
word comes from the Latin word incombrare, which means "barricade or
obstacle."

“So the next problem would be to remove your brain, intact and
 undamaged, from your dead body. The body is useless. In fact it has already
 started to decay. The skull and the face are also useless. They are both
 encumbrances and I don’t want them around. All I want is the brain, the clean
 beautiful brain, alive and perfect. So when I get you on the table I will
 take a saw, a small oscillating saw, and with this I shall proceed to remove
 the whole vault of your skull. You’d still be unconscious at that point so I
 wouldn’t have to bother with anaesthetic.”
* riddled                                                              :Dahl:
[2021-06-23 Wed 13:03]

If an object is riddled with something, that means it's covered by
that thing: for example, a tree trunk might be riddled with tiny holes
made by the beaks of woodpeckers.

The adjective riddled most often describes something damaged by or
spread full of holes, like a rusty old mailbox riddled with bullet
holes or a block of Swiss cheese riddled with holes. You can also use
it figuratively: "It's so sad, her dog is riddled with cancer," or
"The plot of your novel is riddled with holes — it just doesn't hold
up." Riddled comes from the Old English hriddel, "sieve."

“My dear William, just think for a moment of your own brain. It is in
 perfect shape. It is crammed full of a lifetime of learning. It has taken you
 years of work to make it what it is. It is just beginning to give out some
 first-rate original ideas. Yet soon it is going to have to die along with the
 rest of your body simply because your silly little pancreas is riddled with
 cancer.”
* gruesome                                                             :Dahl:
[2021-06-23 Wed 13:03]

Gothic novels, horror movies, and crime dramas don't shy away from
showing gruesome scenes of death, pictures that inspire fright and
repulsion. Synonyms include "ghastly," "grisly," "loathsome," and
"macabre."

Once upon a time, English contained a variety of words related to
gruesome. The verb grue meant "to shudder," just as its Middle Dutch
source gruwen did. Grueful and grueing also conveyed the sense of
shivering with horror and disgust. All of these variations have been
lost leaving us only with gruesome. Texting while driving has caused
many gruesome accidents that you might not want to hear the gruesome
details of. Although if you like gruesome movies, you might want to
know.

“Quite a long time ago,” he said, “I saw a short medical film that had
 been brought over from Russia. It was a rather gruesome thing, but
 interesting. It showed a dog’s head completely severed from the body, but
 with the normal blood supply being maintained through the arteries and veins
 by means of an artificial heart. Now the thing is this: that dog’s head,
 sitting there all alone on a sort of tray, was alive. The brain was
 functioning. They proved it by several tests. For example, when food was
 smeared on the dog’s lips, the tongue would come out and lick it away; and
 the eyes would follow a person moving across the room.
* denture :Dahl:
[2021-06-23 Wed 13:04]

A denture is a section of false teeth, made to replace missing teeth
in a person's mouth. Some kinds of dentures need to be soaked in a
cleansing solution overnight.

The denture part of a dental appliance is officially the plate to
which false teeth are attached, but people tend to refer more
generally to dentures, meaning the whole device. If an accident or
dental disease causes you to lose adult teeth, you can have a dentist
make dentures that are fitted exactly to your mouth. Some of these are
permanent, while others are removable. Denture comes from the Latin
root dens, "tooth."

I am sure he was expecting me to jump when he said this, but for some
 reason I was ready for it. I lay quite still, watching his face and that slow
 white smile of his that always revealed the gold clasp of an upper denture
 curled around the canine on the left side of his mouth.
* effrontery :Dahl:
[2021-06-23 Wed 13:04]

If you rudely behave as if you have a right to something that you have
no right to, you're committing effrontery. When a couple stroll into a
crowded restaurant, demand the best table, and threaten the staff
unless they're seated right away, that's effrontery.

People have been guilty of outrageously self-centered behavior at
least since 1715, when effrontery was coined. Tracing to the French
word effronté, meaning "shameless," the word effrontery is also
connected to brazen, which means "of brass," and describes someone so
accustomed to effrontery that he's hardened to it and has no concern
for the harm done to others.

The details of the illness that struck me down so suddenly in my
 middle life are known to you. I need not waste time upon them—except to admit
 at once how foolish I was not to have gone earlier to my doctor. Cancer is
 one of the few remaining diseases that these modern drugs cannot cure. A
 surgeon can operate if it has not spread too far; but with me, not only did I
 leave it too late, but the thing had the effrontery to attack me in the
 pancreas, making both surgery and survival equally impossible.
* wistful :Dahl:
[2021-06-23 Wed 13:05]

Only one letter separates the two words, but "wishful" is having hope
for something, and wistful is having sadness or melancholy about
something. "Wist" isn't even a word that's used anymore, but you can
still be wistful.

People who appear wistful often show a longing for something or a look
of serious reflection. One way to describe the adjective wistful is as
the sad appearance of someone looking back and thinking "if only..." A
thoughtful or pensive mood centered on something good in the past that
is missed or something not so good in the present that could have been
better "if only" something had gone differently — these things make
for a wistful outlook.

As you read on, you must forgive me, if you will, for the coolness of
 my style, but this is the only way I know of getting my message over to you
 clearly. You see, as my time draws near, it is natural that I begin to brim
 with every kind of sentimentality under the sun. Each day I grow more
 extravagantly wistful, especially in the evenings, and unless I watch myself
 closely my emotions will be overflowing on to these pages.
* brim :Dahl:
[2021-06-23 Wed 13:05]

The brim is the top of a container, like the edge of a cup. Also, if a
cup is brimming, it’s full.

This word has a couple meanings related to fullness. If a cup is full,
it’s filled to the brim. The brim is the top. Containers such as
buckets and pitchers have brims too. Also, the bucket is brimming if
it's totally full. A brimming container is likely to spill. People can
brim too: you can be brimming with enthusiasm or happiness. Like a cup
about to spill, you can’t quite contain yourself when you’re brimming
with joy.

As you read on, you must forgive me, if you will, for the coolness of
 my style, but this is the only way I know of getting my message over to you
 clearly. You see, as my time draws near, it is natural that I begin to brim
 with every kind of sentimentality under the sun. Each day I grow more
 extravagantly wistful, especially in the evenings, and unless I watch myself
 closely my emotions will be overflowing on to these pages.
* dare :Dahl:
[2021-06-23 Wed 13:05]

When you challenge or provoke someone to try something risky, it's a
dare. If you accept a dare, you're probably trying to prove how brave
you are.

When you challenge your friend to a dare, you dare him. You might, for
example, dare your brother to jump off the garage into a pile of
leaves. Another way to dare is to actually be brave: "I admire her so
much, because she dares to stand up to bullies." The Old English root
of dare is durran, "to brave danger, venture, or presume." If you say,
"How dare you?" you're expressing outrage or indignation.

Do not be alarmed by the sight of all this writing. It is nothing but
 an attempt on my part to explain to you precisely what Landy is going to do
 to me, and why I have agreed that he should do it, and what are his theories
 and his hopes. You are my wife and you have a right to know these things. In
 fact you must know them. During the past few days I have tried very hard to
 speak with you about Landy, but you have steadfastly refused to give me a
 hearing. This, as I have already told you, is a very foolish attitude to
 take, and I find it not entirely an unselfish one either. It stems mostly
 from ignorance, and I am absolutely convinced that if only you were made
 aware of all the facts, you would immediately change your view. That is why I
 am hoping that when I am no longer with you, and your mind is less
 distracted, you will consent to listen to me more carefully through these
 pages. I swear to you that when you have read my story, your sense of
 antipathy will vanish, and enthusiasm will take its place. I even dare to
 hope that you will become a little proud of what I have done.
* steadfastly :Dahl:
[2021-06-23 Wed 13:06]



nil

Do not be alarmed by the sight of all this writing. It is nothing but
 an attempt on my part to explain to you precisely what Landy is going to do
 to me, and why I have agreed that he should do it, and what are his theories
 and his hopes. You are my wife and you have a right to know these things. In
 fact you must know them. During the past few days I have tried very hard to
 speak with you about Landy, but you have steadfastly refused to give me a
 hearing. This, as I have already told you, is a very foolish attitude to
 take, and I find it not entirely an unselfish one either. It stems mostly
 from ignorance, and I am absolutely convinced that if only you were made
 aware of all the facts, you would immediately change your view. That is why I
 am hoping that when I am no longer with you, and your mind is less
 distracted, you will consent to listen to me more carefully through these
 pages. I swear to you that when you have read my story, your sense of
 antipathy will vanish, and enthusiasm will take its place. I even dare to
 hope that you will become a little proud of what I have done.
* thrifty :Dahl:
[2021-06-23 Wed 13:06]

Being thrifty means being careful of your money and how you spend
it. Think twice before you spend, but if you must shop, hitting the
sales and using coupons are good ways to be thrifty.

Note the similarity between the adjective thrifty and the verb thrive,
and you'll realize that being careful with your money might be an
important survival tactic. Everyone worries about having enough — look
at how thrift shops have become important sources of clothing and
other goods for many people, allowing them to buy without spending a
fortune. Being thrifty is a solid virtue, as suggested by the old
German proverb, "Prudent men woo thrifty women."

My dear Mary, I trust that you will not permit my departure from this world
 to upset you too much, but that you will continue to observe those precepts
 which have guided you so well during our partnership together. Be diligent
 and dignified in all things. Be thrifty with your money. Be very careful that
 you do not . . . et cetera, et cetera.
* bequests :Dahl:
[2021-06-23 Wed 13:06]

When you receive some kind of gift, be it money or property, through a
will, that gift is known as a bequest.  Your aunt left you a bequest
of the earrings she always thought you admired.

The noun bequest is something one arranges to give away after death,
sort of a gift from beyond the grave.  Basically, putting a bequest in
a will is a way of making sure the right person will get certain goods
after your death. If you are very wealthy, universities and charitable
organizations may court you in an attempt to gain bequests for their
institutions.

William Pearl did not leave a great deal of money when he died, and his will was
a simple one. With the exception of a few small bequests to relatives, he left
all his property to his wife.
* blemish :Dahl:
[2021-06-23 Wed 13:07]

A blemish is a small flaw. If you borrow your brother's brand new
bicycle, you'd better be careful — what might seem like the tiniest
blemish to you might be a horribly ruined paint job to him.

The classic example of a blemish is a pimple or other mark on your
skin, but you can call any small defect a blemish — like a worm hole
in an apple or a scrape on the side of your car. A flaw or fault in
your personality or morals can also be called a blemish. You might say
that the one time your dog accidentally nipped you is the only blemish
on his reputation as a sweet, gentle pet.

“He was actually twenty-eight. And yet I never would have guessed it if he hadn’t
told me, never in my whole life. There wasn’t a blemish on his body.”
* trifle :Dahl:
[2021-06-23 Wed 13:07]

A trifle is something that's totally unimportant. If your friend is
freaking out over which poster to buy and you call her dilemma a
trifle, you're saying she shouldn't get so worked up over nothing.

Trifle comes from the Middle English trufle, meaning "fraud, joke,
trick." You'll usually hear it used to mean "insignificant, trivial."
If you write a little ditty to sing at a birthday party, you could say
it's just a trifle. As a verb, trifle means "toy with, waste." If you
play with someone's feelings without seriously meaning anything, you
are trifling with his affection. Trifle is also a sweet, sticky
cake. Don't trifle the day away dreaming about trifle. Make some!

“Seventeen!” she cried. “Oh, it’s the perfect age! Mr Mulholland was also
seventeen. But I think he was a trifle shorter than you are, in fact I’m sure he
was, and his teeth weren’t quite so white. You have the most beautiful teeth, Mr
Weaver, did you know that?”
* whiff :Dahl:
[2021-06-23 Wed 13:07]

A whiff can mean the hint of something you smell. When you drive past
the sewage treatment plant and suddenly roll up your car windows, it's
usually because you've gotten a whiff of the plant's special odor.

Whiff can be used as either a noun or verb, and it implies a brief or
small puff or sniff. A person can have "a whiff of the exotic," which
means they are living like the rest of us, but there is a little
something about them that seems foreign or different. Sometimes, of
course, odors are so overpowering that a small sniff is all you need:
"Take a whiff of this," your friend might say to you, holding out a
carton of sour milk. In that case, one whiff will be more than enough.

Billy started sipping his tea. She did the same. For half a minute or so,
neither of them spoke. But Billy knew that she was looking at him. Her body was
half turned towards him, and he could feel her eyes resting on his face, watching
him over the rim of her teacup. Now and again, he caught a whiff of a peculiar
smell that seemed to emanate directly from her person. It was not in the least
unpleasant, and it reminded him—well, he wasn’t quite sure what it reminded him
of. Pickled walnuts? New leather? Or was it the corridors of a hospital?
* tantalising :Dahl:
[2021-06-23 Wed 13:08]



nil

There is nothing more tantalising than a thing like this which lingers
just outside the borders of one’s memory. He hated to give up.
* dotty :Dahl:
[2021-06-23 Wed 13:08]



nil

The old girl is slightly dotty, Billy told himself. But at five and
sixpence a night, who gives a damn about that? “I should’ve thought you’d be
simply swamped with applicants,” he said politely.
* dithering :Dahl:
[2021-06-23 Wed 13:08]



nil

After dithering about like this in the cold for two or three minutes,
Billy decided that he would walk on and take a look at The Bell and Dragon before
making up his mind. He turned to go.
* rapacious :Dahl:
[2021-06-23 Wed 13:08]

Something rapacious is out to devour — anything, and little can stand
in its way. A rapacious landlord is out for more rent, and a rapacious
eater is only satisfied at the all-you-can-eat buffet.

A 17th-century word, from the Latin rapere, "to snatch," rapacious
originally described the people and animals who often preyed on weaker
creatures and devoured them, by eating them or by ruining them through
some scandal. Modern-day companies even get the label rapacious when
their appetites for profit seem to devour "lesser" interests, like the
environment and employee benefits.

There would be beer and darts in the evenings, and lots of people to talk to, and
it would probably be a good bit cheaper, too. He had stayed a couple of nights in
a pub once before and he had liked it. He had never stayed in any
boarding-houses, and, to be perfectly honest, he was a tiny bit frightened of
them. The name itself conjured up images of watery cabbage, rapacious landladies,
and a powerful smell of kippers in the living-room.
* congenial :Dahl:
[2021-06-23 Wed 13:09]

A congenial person is easy to get along with. If you're trying to
decide which of your friends to take on a road trip, choose the most
congenial one.

Congenial means sharing the same temperament, or agreeing with your
temperament.  You can talk about a congenial person, place, or
environment. Maybe you enjoy the congenial atmosphere of the
library. Or perhaps for you the disco is more congenial.  As you might
expect for such a vaguely approving word, there are many synonyms:
agreeable, pleasant, delectable, delightful, enjoyable, and so on.

On the other hand, a pub would be more congenial than a boarding-house.
* laymen :Dahl:
[2021-06-23 Wed 13:15]

A layman might have a small amount of knowledge about something, but
she isn't officially trained in the subject. If you need brain
surgery, don't consult a layman; stick to a professional brain
surgeon.

Use the noun layman to describe your brother, who is an amateur bird
watcher rather than a professional ornithologist. The word layman is
most often used to contrast with expert or professional. Another way
to use it is to distinguish between a member of the clergy — a priest
or minister, for example — and an ordinary church member, or layman.

“As you wish, William. And now, as I say, I’d take a small oscillating
 saw and carefully remove your complete calvarium—the whole vault of the
 skull. This would expose the top half of the brain, or rather the outer
 covering in which it is wrapped. You may or may not know that there are three
 separate coverings around the brain itself—the outer one called the dura
 mater or dura, the middle one called the arachnoid, and the inner one called
 the pia mater or pia. Most laymen seem to have the idea that the brain is a
 naked thing floating around in fluid in your head. But it isn’t. It’s wrapped
 up neatly in these three strong coverings, and the cerebrospinal fluid
 actually flows within the little gap between the two inner coverings, known
 as the subarachnoid space. As I told you before, this fluid is manufactured
 by the brain and it drains off into the venous system by osmosis.
* jugular :Dahl:
[2021-06-23 Wed 13:16]

Jugular is short for “jugular vein,” the major vein that brings blood
from your head to your heart. You can also call any vulnerable area
the jugular.

If you hear someone say, “Go for the jugular!” Watch out! A serious
attack is coming. When lions attack prey, they chomp down on the
jugular to kill the animal fast. If your jugular is cut, you could die
very quickly without medical help. You can also call your neck and
throat the jugular area. Because this is a vulnerable area, you can
use this word for other vulnerable things, like a weak spot on a
sports team.

“I myself would leave all three coverings—don’t they have lovely
 names, the dura, the arachnoid, and the pia?—I’d leave them all intact. There
 are many reasons for this, not least among them being the fact that within
 the dura run the venous channels that drain the blood from the brain into the
 jugular.
* severing :Dahl:
[2021-06-23 Wed 13:21]



nil

“At this point, I would be ready for the final move. To one side, on a
 table, I’d have a basin of a special shape, and this would be filled with
 what we call Ringer’s Solution. That is a special kind of fluid we use for
 irrigation in neurosurgery. I would now cut the brain completely loose by
 severing the supply arteries and the veins. Then I would simply pick it up in
 my hands and transfer it to the basin. This would be the only other time
 during the whole proceeding when the blood flow would be cut off; but once it
 was in the basin, it wouldn’t take a moment to re-connect the stubs of the
 arteries and veins to the artificial heart.
* brain :Dahl:
[2021-06-23 Wed 13:24]

The brain is the most complex organ in the body, located inside the
protective skull. The word can also be used as a verb in the phrase
"to brain," which means to injure or kill someone by hitting them in
the head.

The human brain has inspired many idioms, or colorful
phrases. Thinking intently (or obsessively) about something means that
you've got it "on the brain," and to "pick someone's brain" means to
get their ideas on something. A puzzle is a "brainteaser, someone
smart is called "a brain," and the person who runs something is said
to be "the brains" of the operation.

“Ah!” he cried. “I knew I’d forgotten something! I never told you
 about the eye. Listen. I am going to try to leave one of your optic nerves
 intact, as well as the eye itself. The optic nerve is a little thing about
 the thickness of a clinical thermometer and about two inches in length as it
 stretches between the brain and the eye. The beauty of it is that it’s not
 really a nerve at all. It’s an outpouching of the brain itself, and the dura
 or brain covering extends along it and is attached to the eyeball. The back
 of the eye is therefore in very close contact with the brain, and
 cerebrospinal fluid flows right up to it.
* submerged :Dahl:
[2021-06-23 Wed 13:25]

When something is submerged, it's under water — like a submarine, a
car caught in a flood, or your feet in a wading pool.

Use the adjective submerged to describe something that stays under the
surface of the water. The flood in your basement might cause your
exercise equipment to be submerged, and you probably snorkel with your
face submerged. You can also use submerged to describe something
that's covered up. For example, you might try to keep your sad
feelings about your dog's death submerged when you're with your
friends.

“All this suits my purpose very well, and makes it reasonable to
 suppose that I could succeed in preserving one of your eyes. I’ve already
 constructed a small plastic case to contain the eyeball, instead of your own
 socket, and when the brain is in the basin, submerged in Ringer’s Solution,
 the eyeball in its case will float on the surface of the liquid.”
* resented :Dahl:
[2021-06-23 Wed 13:30]

To resent something is to feel anger or bitterness toward it. You
might resent someone who has treated you poorly.

To resent is a strong, negative feeling.  You may resent the
accusation that you were stealing cookies, or when a teacher yelled at
you for whispering, even though everyone else was too. You might
resent a friend who has more money or friends than you. Lots of people
resent celebrities because they're famous and wealthy.  If your friend
borrowed a sweater and didn’t return it, you would probably resent
it. Resenting is the opposite of being grateful.

“No,” I said. Landy was already taking it for granted that I was going
 to go through with this business, and I resented his attitude. “Go away now
 and leave me alone,” I told him. “You won’t get anywhere by trying to rush
 me.”
* impurities :Dahl:
[2021-06-23 Wed 13:35]

An impurity is something that ruins the uncontaminated nature of
something. If someone accuses you of impurity, they think you or your
nature has been spoiled in some way by sin.

When water is pure, the only thing in that water is water. Add a
contaminant, say salt or bleach, and you are introducing an impurity,
something that turns the water impure. When used with people, the word
has a religious overtone. Someone who is pure is unspoiled by
sin. Think Snow White. If you convinced Snow White to rob a bank with
you, you'd be spoiling her good nature with your wretched impurity.

There would be no impurities in it, no virus, no bacteria, nothing. Of course
 it’s foolish to guess, but I believe that a brain might live for two or three
 hundred years in circumstances like these. Good-bye for now,” he said. “I’ll
 drop in and see you tomorrow.” He went out quickly, leaving me, as you might
 guess, in a fairly disturbed state of mind.
