-*- coding: utf-8 -*-


* irascible :misc:
[2021-03-01 Mon 15:49]

If you're irascible, you get angry easily — perhaps blowing up in rage
when someone brushes into you.

Irascible comes from the Latin root ira, which means "anger" or
"rage," the same root that gives us the word ire, "anger." The -sc in
the middle of irascible, means "becoming," so irascible doesn't just
mean you're angry — it's got action built into it. If you're looking
for a fight most of the time, then you're irascible — ready for the
spark that's going to set you on fire.

He begins to get more irascible and one day while his wife is out
he decides that he's going to collect all his childhood mementos the
memories of his youth and burn them as if he's trying to eradicate his
past.

* heir :misc:
[2021-03-03 Tue 17:07]

If your grandfather leaves his candy factory to you in his will, it
means you're the heir to the family candy business, and after your
grandfather dies, you will inherit the factory.

When you're named in a will or are legally entitled to inherit
something, you're an heir. You can be the heir to someone's money,
business, or title; in a monarchy, the king or queen's oldest son is
usually the heir to the throne. The word heir isn't pronounced like
"hair," but instead has a silent h and sounds like "air."

The bats weren't surprised you to know that some
men blamed their own midlife crises on the menopause, their wife's
menopause as well so let me go back to Reginald Perrin.

*  wee                                                                 :misc:
[2021-03-03 Wed 12:54]

I had a flashback to when I was a wee girl.

* presbyterian                                                         :misc:
[2021-03-03 Wed 13:03]

Not even the one that says, "Did you know that Britney Spears is an
anagram for Presbyterian?".

* hourglass :misc:
[2021-03-03 Wed 13:10]

So it's kind of like an hourglass effect: when you're young you're
great at being yourself; when you're old you're great at being
yourself; but the bit in the middle is sometimes the most problematic.

* inferiority :misc:
[2021-03-03 Wed 13:11]

Inferiority is the quality of being worse than other things or people.

You know how some movies are terrible — inferior — compared to other
movies? You've noticed the inferiority of those films. Inferiority is
a quality possessed by people and things that are not as good as
others. To a king, the common people are defined by their inferiority.
Most people agree on the inferiority of a TV dinner to a home-cooked
meal. When someone feels like they are always worse off than others,
they have an inferiority complex. Inferiority is the opposite of
superiority.

If you've got an inferiority complex you suffer from an over-modest
self-regard.
* vantage :misc:
[2021-03-03 Wed 13:15]

A vantage is a really good place from which to survey a scene. You
might find that the roof of the house offers an excellent vantage from
which to drop water balloons on your kid brother’s head.

Vantage is a variation of advantage, but when we use vantage we’re
almost always talking about a position, not just general superiority.
If you had extra tutoring for a big exam, you would have the advantage
over a classmate who didn’t. But if your seat for the test allowed you
to see the answer sheet lying on the desk, well then you would have a
superior vantage — not that you would take advantage of that, of
course!

Interiority is entirely unrelative, so to operate from this position
of interiority, it's like a perceptual vantage point.

* lodging :misc:
[2021-03-16 Tue 22:23]

Lodging is a name for the place you stay when you're not at home. Your
lodging could be a luxury hotel, a yurt in the woods, or a college
dormitory.

Your accommodations while traveling, going away to school, being an
exchange student, or doing temporary work are all called lodging or
lodgings. A room in a hotel is one kind of lodging, and a sleeping bag
on the floor of a tent is another kind. Lodging comes from lodge and
its earlier form, loggen, "to set up camp," from the Old French root
loge, "hut or cabin."

One afternoon, at low water, Mr. Isbister, a young artist lodging at
Boscastle, walked from that place to the picturesque cove of Pentargen,
desiring to examine the caves there.
* cove :misc:
[2021-03-16 Tue 22:23]

A cove is a small, sheltered part of an ocean's coast. A cove can be a
good place to put a sea kayak in the water and start paddling along
the shore.

A cove is basically the same thing as a "bay," but smaller. Coves are
protected coastal areas affected by tides and connected to the open
sea by a narrow entrance. The water in a cove is calmer than the open
ocean, and the cove itself is often oval or circular in shape. The
earliest meaning of cove was "den or cave," and later "small bay,"
probably influenced by a Scottish meaning of the word, "hollow place
in coastal rocks."

One afternoon, at low water, Mr. Isbister, a young artist lodging at
Boscastle, walked from that place to the picturesque cove of Pentargen,
desiring to examine the caves there.

* precipitous                                                          :misc:
[2021-03-16 Tue 22:24]

A sharp, steep drop — whether it's in a stock price, a roller coaster,
or a star's popularity — could be described as a precipitous one. Put
simply, precipitous means perilously steep.

Look closely and you'll spot most of the word precipice (a sheer,
almost vertical cliff) in precipitous. Now imagine how you'd feel
standing at the edge peering over, and you'll grasp the sense of
impending danger that precipitous tends to imply. Precipitous declines
in sales lead to bankruptcy. Precipitous mountainside hiking trails
are not for the acrophobic. It can describe an ascent, but precipitous
is most often used for things going literally or figuratively
downhill.

Halfway down the precipitous path to the Pentargen beach he came
suddenly upon a man sitting in an attitude of profound distress
beneath a projecting mass of rock. The hands of this man hung limply
over his knees, his eyes were red and staring before him, and his face
was wet with tears.
* disconcert                                                           :misc:
[2021-03-16 Tue 22:25]

A concert is a choreographed harmony of sounds but throw the prefix
"dis" in front it and you have the opposite: disconcerted — a word
used to describe someone whose composure has been disturbed or
unsettled.

Disconcerted is a combination of the French prefix des- which
indicates reversal and the word concerter meaning "bring together," so
something disconcerted is not brought together, but rather torn apart,
or thrown into confusion. If you are under a lot of stress or worried
about something, you're in a disconcerted or discombobulated state.
Take a breath. Relax a moment. Everything will be OK.

He glanced round at Isbister’s footfall. Both men were disconcerted,
Isbister the more so, and, to override the awkwardness of his
involuntary pause, he remarked, with an air of mature conviction, that
the weather was hot for the time of year.
* involuntary :misc:
[2021-03-16 Tue 22:26]

Involuntary describes a reflex or action done without conscious
control or will — like a blink, a sneeze, a yawn, or “the giggles.”

If you volunteered to do it, it’s voluntary. If you didn’t volunteer,
but you find yourself doing it anyway, it’s involuntary. This can go
for the involuntary hiccups you wrestle with on your blind date, as
well as the involuntary task you do at your manager’s
insistence. Involuntary gets a lot of blame, but something that is
involuntary is not necessarily bad: Breathing is involuntary, but you
would probably do it anyway if given the choice.

He glanced round at Isbister’s footfall. Both men were disconcerted,
Isbister the more so, and, to override the awkwardness of his
involuntary pause, he remarked, with an air of mature conviction, that
the weather was hot for the time of year.

* fervid :misc:
[2021-03-19 Fri 14:39]

Fervid can be used to describe something that is physically hot such
as “a fervid day in August,” but it is more often used to describe
heated emotions like anger, love, or desire.

When passions and emotions run wild, you should expect to hear some
fervid language thrown about. The adjective fervid comes from the
Latin fervidus which means “glowing, burning, or boiling.” It is often
used like the word fiery. You might hear a politician deliver a
“fervid speech” if he or she is particularly worked up over an issue.

A blazing sun upon a fierce August day was no greater rarity in southern France then, than
at any other time, before or since. Everything in Marseilles, and about Marseilles, had
stared at the fervid sky, and been stared at in return, until a staring habit had become
universal there. Strangers were stared out of countenance by staring white houses,
staring white walls, staring white streets, staring tracts of arid road, staring hills from
which verdure was burnt away. The only things to be seen not fixedly staring and glaring
were the vines drooping under their load of grapes. These did occasionally wink a little, as
the hot air barely moved their faint leaves.
* arid :misc:
[2021-03-19 Fri 14:40]

Arid is so dry that nothing will grow. Death Valley in California
features an arid climate, which is why it's called Death Valley and
not Life Valley.

Arid can also mean terribly dull or lifeless. A textbook about the
climate of Death Valley might be called arid if it's written in an
uninteresting way. Just like you wouldn't want to live in an arid
climate, you wouldn't want to sit through an arid performance of the
film-turned-musical, "Some Like it Hot."

A blazing sun upon a fierce August day was no greater rarity in southern France then, than
at any other time, before or since. Everything in Marseilles, and about Marseilles, had
stared at the fervid sky, and been stared at in return, until a staring habit had become
universal there. Strangers were stared out of countenance by staring white houses,
staring white walls, staring white streets, staring tracts of arid road, staring hills from
which verdure was burnt away. The only things to be seen not fixedly staring and glaring
were the vines drooping under their load of grapes. These did occasionally wink a little, as
the hot air barely moved their faint leaves.
* verdure :misc:
[2021-03-19 Fri 14:40]

Verdure is lush green foliage, the kind you'd find in a beautiful
garden, in a park, or in a forest.

Verdure is related to many words for the color green, and that's
exactly what it means: greenery, and a lot of it, in nature. This word
conveys a sense of life: think of a park where there's green
everywhere you see. That's verdure. A forest will have even more
verdure, and you could find verdure in someone's garden, if it's a big
one with a lot of plants. Verdure is so brightly alive that it makes
people feel good.

A blazing sun upon a fierce August day was no greater rarity in southern France then, than
at any other time, before or since. Everything in Marseilles, and about Marseilles, had
stared at the fervid sky, and been stared at in return, until a staring habit had become
universal there. Strangers were stared out of countenance by staring white houses,
staring white walls, staring white streets, staring tracts of arid road, staring hills from
which verdure was burnt away. The only things to be seen not fixedly staring and glaring
were the vines drooping under their load of grapes. These did occasionally wink a little, as
the hot air barely moved their faint leaves.
* abominable :misc:
[2021-03-19 Fri 14:42]

Abominable is as bad as it gets. So if the food at camp is abominable,
the campers might start to shout, "Ick! Ick! Your stew is making us
sick!"

Abominable is an adjective that should be used only when something is
exceptionally bad or threatening, like a gigantic furry snowman who is
terrorizing a village. Abominable is so absolutely awful that it
causes physical revulsion. So odious that it brings even the toughest
of tough guys to tears. Which is a bummer, because it's a surprisingly
fun word to say out loud.

There was no wind to make a ripple on the foul water within the harbour, or on the
beautiful sea without. The line of demarcation between the two colours, black and blue,
showed the point which the pure sea would not pass; but it lay as quiet as the abominable
pool, with which it never mixed. Boats without awnings were too hot to touch; ships
blistered at their moorings; the stones of the quays had not cooled, night or day, for
months. Hindoos, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen,
Genoese, Neapolitans, Venetians, Greeks, Turks, descendants from all the builders of
Babel, come to trade at Marseilles, sought the shade alike—taking refuge in any
hiding-place from a sea too intensely blue to be looked at, and a sky of purple, set with
one great flaming jewel of fire.
* awnings :misc:
[2021-03-19 Fri 14:42]

An awning is a covering that's like a roof or extends from a roof. If
you walk down a street with a lot of stores and it starts raining,
you'll probably try to stay under the awnings.

An awning provides shelter from rain and sun. You will often see
awnings extending over the entryways of businesses. Under an awning is
a place you can hang out as you collapse your umbrella on your way in,
or as you open your umbrella on your way out. Awnings are often made
from some type of canvas, and they protrude from the top of the store
or building, kind of like the brim of a cap, which has a similar
function.

There was no wind to make a ripple on the foul water within the harbour, or on the
beautiful sea without. The line of demarcation between the two colours, black and blue,
showed the point which the pure sea would not pass; but it lay as quiet as the abominable
pool, with which it never mixed. Boats without awnings were too hot to touch; ships
blistered at their moorings; the stones of the quays had not cooled, night or day, for
months. Hindoos, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen,
Genoese, Neapolitans, Venetians, Greeks, Turks, descendants from all the builders of
Babel, come to trade at Marseilles, sought the shade alike—taking refuge in any
hiding-place from a sea too intensely blue to be looked at, and a sky of purple, set with
one great flaming jewel of fire.
* quays :misc:
[2021-03-19 Fri 14:45]

You know that wharf on the bank of the river where all the boats park?
It's not an aqua parking lot. It's called a quay.

When you visit France and take a walk beside the wharves where boats
dock and unload passengers, you can say you've been strolling along
the quays of the Seine. The English spelling of this word was
originally key, and that's one way to pronounce it even today, an
alternative to "qway." Quay comes from the Old North French cai, "sand
bank."

There was no wind to make a ripple on the foul water within the harbour, or on the
beautiful sea without. The line of demarcation between the two colours, black and blue,
showed the point which the pure sea would not pass; but it lay as quiet as the abominable
pool, with which it never mixed. Boats without awnings were too hot to touch; ships
blistered at their moorings; the stones of the quays had not cooled, night or day, for
months. Hindoos, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen,
Genoese, Neapolitans, Venetians, Greeks, Turks, descendants from all the builders of
Babel, come to trade at Marseilles, sought the shade alike—taking refuge in any
hiding-place from a sea too intensely blue to be looked at, and a sky of purple, set with
one great flaming jewel of fire.

* compelling :misc:
[2021-03-22 Mon 21:41]

Compelling means attractive, or irresistible, or really, really
convincing. You know your argument for backpacking across Europe is
compelling when your parents not only let you go but also pay for all
your expenses.

To compel is to drive or force into action––you mom could compel you
to finish your homework by threatening not to feed you until it's
done. A compelling argument compels you to agree with its logic––it's
irresistible. That cute skirt you’ve been eyeing for months is now 75%
off? The price is a compelling reason to buy the skirt.

I’ve seen no compelling evidence.
* imperiling :misc:
[2021-03-22 Mon 21:44]

One thing can imperil another when it threatens to be harmful. For
example, an approaching storm with hurricane-force winds might imperil
the geraniums you just planted in your front yard.

A city's budget cuts might imperil a school's ability to hire new
teachers and buy supplies. The lack of money, in other words, is a
threat to schools. Likewise, a factory's refusal to reduce its
greenhouse gas emissions will imperil the air quality nearby — and
ultimately, imperil the health of the whole planet. The word imperil
comes from in and peril, meaning "danger."

To grasp why people bury themselves in debt you don’t need to study interest
rates; you need to study the history of greed, insecurity, and optimism. To
get why investors sell out at the bottom of a bear market you don’t need to
study the math of expected future returns; you need to think about the agony
of looking at your family and wondering if your investments are imperiling
their future.
* unaltered :misc:
[2021-03-22 Mon 21:45]

Unaltered means unchanged. If your parents’ poor opinion of your
boyfriend remains unaltered no matter how polite he is or how early he
brings you home, it may be because of his tattoos and motorcycle.

Unaltered is the opposite of altered, meaning to adjust or change. If
you meet a friend you haven't seen in ten years, and she looks the
same as you remember, you might exclaim at how unaltered she seems. If
you buy a pair of pants that need to be hemmed, you won't be able to
wear them in their unaltered state.

It was called The Psychology of Money, and over one million people have read
it. This book is a deeper dive into the topic. Some short passages from the
report appear unaltered in this book.
* compelling :misc:
[2021-03-22 Mon 21:47]

Compelling means attractive, or irresistible, or really, really
convincing. You know your argument for backpacking across Europe is
compelling when your parents not only let you go but also pay for all
your expenses.

To compel is to drive or force into action––you mom could compel you
to finish your homework by threatening not to feed you until it's
done. A compelling argument compels you to agree with its logic––it's
irresistible. That cute skirt you’ve been eyeing for months is now 75%
off? The price is a compelling reason to buy the skirt.

Everyone has their own unique experience with how the world works. And what
you’ve experienced is more compelling than what you learn second-hand. So all
of us—you, me, everyone—go through life anchored to a set of views about how
money works that vary wildly from person to person. What seems crazy to you
might make sense to me.
* basking :misc:
[2021-03-22 Mon 21:49]

To bask in something is to take it in, receive its warmth, or bathe in
its goodness. On the first warm day of the spring, you may bask in the
sunshine. When you win the Pulitzer, you bask in your own glory.

In Shakespeare’s “As You Like It,” Jaques says: “...As I do live by
food, I met a fool; Who laid him down and bask'd him in the sun,; And
rail'd on Lady Fortune in good terms...” That was most likely the
first time bask was used in the way that we most often use it now: to
bask is to warm yourself, either literally or figuratively, in the
glow of the sun, good fortune, happiness, or a job well done.

The stock broker who lost everything during the Great Depression experienced
something the tech worker basking in the glory of the late 1990s can’t
imagine.
* overarching :misc:
[2021-03-23 Tue 15:50]



nil

They would often list dozens of tips and tricks that had little to
do with each other. There was never an overarching system for
turning notes into concrete results.
* morsels :misc:
[2021-03-23 Tue 15:52]

A morsel is a small amount of something, a tid-bit, a sliver, usually
of something of high-quality and much desired — like a morsel of dark
chocolate or a morsel of secret information.

Originally it referred specifically to food — a nineteenth century
lady might partake of a "dainty morsel" to eat, for example. More
often than not morsel now refers to non-food items: a morsel of good
taste; a morsel of common sense, and, of course, most popular of all,
a morsel of gossip. That's why, like all good food, all good gossip is
juicy.

My approach is based on the assumption that most books are a few
morsels of real insight wrapped in layers and layers of fluff. As
I read, I systematically unravel those layers of fluff and extract
only those insights, like a chemist distilling only the purest
compound.
* strands :misc:
[2021-03-23 Tue 16:49]

A single hair, a noodle, even a line of thought — any of these things
could be called a strand, a long thin length of something.

The noun strand describes things that are long and thin like a rope,
or a strand of spaghetti, hair, or thread. Strands are often twisted
together to form thicker, stronger things like cables. As a verb, the
meaning is very different: "to leave helpless," like unreliable cars
that strand their drivers, or a snowstorm that strands people at
airports.

* These branching connections were marked in red as close as
 possible to the point where the branch began
* Any of these branches could also have their own branches. The
 card for fellow German sociologist Jürgen Habermas, for example,
 was labeled 21/3d26g53
* As he read, he would create new cards, update or add comments to
 existing ones, create new branches from existing cards, and
 create new links between cards on different “strands”
* daring :misc:
[2021-03-24 Wed 17:09]

To be daring is to be bold, adventurous, and a little nervy. It’s a
quality possessed by people who tend to take risks. If someone says,
“I dare you,” and you always do, you’re a daring person.

If you're daring, you dare to do things that are risky and even
dangerous. A daring mountain climber goes for the top of Mount
Everest, and a daring policeman enters the scariest houses to catch a
crook. In comics and movies, superheroes are daring. Even quitting
your job to start your own business is daring. The seafarers who first
traveled across the globe were daring. Daring people are brave, and
daring adventures are pretty exciting.

About twenty years ago Jobs and Wozniak, the founders of Apple,
 came up with the very strange idea of selling information
 processing machines for use in the home. The business took off, and
 its founders made a lot of money and received the credit they
 deserved for being daring visionaries. But around the same time,
 Bill Gates and Paul Allen came up with an idea even stranger and
 more fantastical: selling computer operating systems. This was much
 weirder than the idea of Jobs and Wozniak. A computer at least had
 some sort of physical reality to it. It came in a box, you could
 open it up and plug it in and watch lights blink. An operating
 system had no tangible incarnation at all. It arrived on a disk, of
 course, but the disk was, in effect, nothing more than the box that
 the OS came in. The product itself was a very long string of ones
 and zeroes that, when properly installed and coddled, gave you the
 ability to manipulate other very long strings of ones and zeroes.
* tangible :misc:
[2021-03-24 Wed 17:10]

When you can touch something, it's tangible: "I need tangible proof
that aliens exist — I want to shake their little green hands!"

Tangible is from Latin tangere, "to touch," and it simply means
something that can be touched or felt, though it can be used in
metaphorical senses: tangible assets have a value that can be
precisely measured, and tangible grief can be clearly sensed by an
onlooker. So you might not need to physically touch something for it
to be tangible, but it has to be grounded in the real world of facts:
"Has the teen pop star demonstrated any tangible ability to sing?"

About twenty years ago Jobs and Wozniak, the founders of Apple,
 came up with the very strange idea of selling information
 processing machines for use in the home. The business took off, and
 its founders made a lot of money and received the credit they
 deserved for being daring visionaries. But around the same time,
 Bill Gates and Paul Allen came up with an idea even stranger and
 more fantastical: selling computer operating systems. This was much
 weirder than the idea of Jobs and Wozniak. A computer at least had
 some sort of physical reality to it. It came in a box, you could
 open it up and plug it in and watch lights blink. An operating
 system had no tangible incarnation at all. It arrived on a disk, of
 course, but the disk was, in effect, nothing more than the box that
 the OS came in. The product itself was a very long string of ones
 and zeroes that, when properly installed and coddled, gave you the
 ability to manipulate other very long strings of ones and zeroes.
* coddled :misc:
[2021-03-24 Wed 17:11]

While it is okay for parents to coddle, spoil, or pamper a young
child, it’s a little unnerving when parents coddle, or pamper adult
children. And downright weird when adult children wear Pampers.

Coddle is an old word. Originally, it meant to cook gently in water
that is near boiling, as in coddling an egg. It most likely gained its
association with pampering and taking care of someone via a drink made
for invalids that was prepared by coddling. “Mollycoddle,” a synonym
for coddle, originally meant a person who coddles himself, or an
effeminate man.

About twenty years ago Jobs and Wozniak, the founders of Apple,
 came up with the very strange idea of selling information
 processing machines for use in the home. The business took off, and
 its founders made a lot of money and received the credit they
 deserved for being daring visionaries. But around the same time,
 Bill Gates and Paul Allen came up with an idea even stranger and
 more fantastical: selling computer operating systems. This was much
 weirder than the idea of Jobs and Wozniak. A computer at least had
 some sort of physical reality to it. It came in a box, you could
 open it up and plug it in and watch lights blink. An operating
 system had no tangible incarnation at all. It arrived on a disk, of
 course, but the disk was, in effect, nothing more than the box that
 the OS came in. The product itself was a very long string of ones
 and zeroes that, when properly installed and coddled, gave you the
 ability to manipulate other very long strings of ones and zeroes.
* arcane :misc:
[2021-03-24 Wed 17:12]

Something arcane is understood or known by only a few people. Almost
everyone knows the basics of baseball, but only an elite few possess
the arcane knowledge of its history that marks the true fan.

A near synonym is esoteric, as in "relating to remote information or
knowledge." Experts in academic fields often show off the depth of
their knowledge by mentioning some arcane and esoteric fact as if it
was common for everyone to know. The origin of arcane is Latin
arcānus, "secret, closed," from arca, "a chest, box." Arcana (singular
arcanum) are pieces of mysterious knowledge or information.

Even those few who actually understood what a computer operating
 system was were apt to think of it as a fantastically arcane
 engineering prodigy, like a breeder reactor or a U-2 spy plane, and
 not something that could ever be (in the parlance of high-tech)
 "productized."
* hazy :misc:
[2021-03-24 Wed 17:44]

If it's hazy, it's definitely not clear — there's fog, mist, smoke or
something like that blurring the view.

Hazy usually describes a sky that's fogged over or otherwise
unclear. But if you're feeling a little uncertain or unsure about
something, with only a bleary outline in your mind, you could say
you're a bit hazy on the details.

Yet now the company that Gates and Allen founded is selling
 operating systems like Gillette sells razor blades. New releases of
 operating systems are launched as if they were Hollywood
 blockbusters, with celebrity endorsements, talk show appearances,
 and world tours. The market for them is vast enough that people
 worry about whether it has been monopolized by one company. Even
 the least technically-minded people in our society now have at
 least a hazy idea of what operating systems do; what is more, they
 have strong opinions about their relative merits. It is commonly
 understood, even by technically unsophisticated computer users,
 that if you have a piece of software that works on your Macintosh,
 and you move it over onto a Windows machine, it will not run. That
 this would, in fact, be a laughable and idiotic mistake, like
 nailing horseshoes to the tires of a Buick.
* balky :misc:
[2021-03-24 Wed 17:50]



nil

The other, somewhat subtler point, was that interface is very
 important. Sure, the MGB was a lousy car in almost every way that
 counted: balky, unreliable, underpowered. But it was fun to drive.
* innards :misc:
[2021-03-24 Wed 17:53]

Your innards are your stomach, intestines, and other abdominal
organs. Catching a fish is fun, but gutting it, or removing its
innards, is less fun.

The slang term innards is sometimes used to mean "the parts of the
digestive system," and other times refers more generally to any of the
inside parts or organs of a human or animal body. Innards was coined
in the 1800s, originally spelled innerds, from a dialect form of
inwards, and meaning "the bowels."

There was a competing bicycle dealership next door (Apple) that one
 day began selling motorized vehicles--expensive but attractively
 styled cars with their innards hermetically sealed, so that how
 they worked was something of a mystery.
* yearn :misc:
[2021-03-25 Thu 17:56]

To yearn for something is to really, really want it. You might yearn
for freedom or you might yearn for a perfect tamale. Usually you yearn
for something or someone you can't easily get.

If you have a hankering for pie, you could also say that you yearn for
it. Yearn also means "to feel sweet on someone" or "to have affection
for something." If your girlfriend moves to Alaska and you’re stuck in
Texas, you’d probably yearn for her. And when she comes back to visit,
you would still yearn — meaning you’d still feel affection for her.

don't drum up the men to gather wood, divide the work and give
      orders. Instead, teach them to yearn for the vast and endless
      sea. - 
