-*- coding: utf-8 -*-


* mow                                                                  :Farm:
[2021-05-03 Mon 08:03]

When you clip grass or other plants, you mow it. If you realize your
front lawn is taller than your dog, it might be time to mow it.

People with grassy lawns usually mow them throughout the growing
season, keeping them neatly trimmed and green. Farmers mow some food
crops and hay as well, when they're ready to be harvested, although
they use different tools to do it, including a curved blade called a
scythe. An old-fashioned meaning of mow is "a stack of hay," or "a
place where hay is stored."

As for the horses, they knew every inch of the field, and in fact
understood the business of mowing and raking far better than Jones and
his men had ever done.
* TODO grudge                                                           :sat:

* grudging :Farm:
[2021-05-03 Mon 08:06]

If you do something in a grudging manner (or grudgingly), you do it
with reluctance. Doing homework, paying taxes, and saying sorry are
all commonly done in a grudging manner.

"Grudging apology" and "grudging acceptance" are probably the two most
common uses of this word, which perhaps says something about our lack
of grace as a species. The word derives from the medieval French word
groucher, meaning "to murmur or mumble." A related word is grudge,
meaning a long-lasting sense of ill will dating to a previous
incident.

Every mouthful of food was an acute positive pleasure, now that it was
truly their own food, produced by themselves and for themselves, not
doled out to them by a grudging master.
* cockerel                                                             :Farm:
[2021-05-03 Mon 08:08]

He had made an arrangement with one of the cockerels to call him in
the mornings half an hour earlier than anyone else, and would put in
some volunteer labour at whatever seemed to be most needed, before the
regular day’s work began.
* obstinate :Farm:
[2021-05-03 Mon 08:11]

When someone is beyond stubborn, use the word obstinate instead: "You
obstinate old mule! Get out of my way!"

While stubborn may have positive or negative connotations, obstinate
is most definitely negative, because it implies a kind of hard-headed
determination not to change your mind even when it might be best to
rethink your position. "The obstinate Man does not hold Opinions, but
they hold him," wrote Samuel Butler way back in the seventeenth
century. The word still does the trick if you want a put-down for
someone you think is being a pig-headed fool or a stick in the mud.

He did his work in the same slow obstinate way as he had done it in
Jones’s time, never shirking and never volunteering for extra work
either.

* muddle :Gideon:
[2021-05-13 Thu 18:22]

A muddle is something that's messy and confusing. If your bedroom
looks like a hurricane just hit it, you might describe it as a muddle.

Oftentimes, we create the muddles in our lives, so it’s appropriate
that muddle can be used as a verb meaning “to mix up” or “confuse.”
Conveniently, though, the word muddle also describes a way out of
difficult situations; to muddle through a troublesome task is to
somehow figure it out, even if you don’t quite know what you’re
doing. It has been suggested that muddle comes from an old Dutch word
meaning “to make muddy.”

No problem there we might use that - native speakers might say it
like that but you could use another word a native speaker might use an
advanced words such as MUDDLE or IN A MUDDLE I was in such a muddle
this morning I tried to put my trousers on my head and I stepped into
my hat. So this is just one example so words that native speakers or
advanced users will use. 26 words that will help your speaking and
help your comprehension coming right up so stay tuned.
* budge :Gideon:
[2021-05-13 Thu 18:26]

To budge is to move — but just a little bit. People can budge
physically from where they're sitting or standing, and people can
budge from opinions and positions too.

If a bunch of your friends are sitting on a bench, and they're taking
up too much space for you to sit, you could ask them to budge, meaning
"Move over!" If you hate eggs and refuse to eat them no matter how
they're cooked, you are refusing to budge from your anti-egg
policy. Budge is most often used in a negative way, as in "I won't
budge" or "They wouldn't budge." This word often applies to stubborn
people. Since budge means to move just a tiny bit, what's the big
deal? Someone who accuses you of not budging is basically saying you
should.

B is for BUDGE and this is a synonym of to move or change position and
we especially use it when we want to talk about people changing their
minds or their decisions so for example "we asked them to improve
their offer but they wouldn't budge." "We tried to convince the
President to resign but he wouldn't budge." You can also use it to
mean move something heavy "hey! can you help me budge the sofa." So
there you are you can use BUDGE instead of MOVE.
* comeuppance :Gideon:
[2021-05-13 Thu 19:18]

Comeuppance describes a fate or punishment that's deserved, like when
an arrogant trash-talking quarterback fumbles the ball on the last
play and loses the game for his team.

Comeuppance began as a term that meant "present oneself for judgment
by a tribunal." That was in 1859. You can picture an accused person
approaching a judge, or "coming up" to the front of a
courtroom. Guilt, innocence — comeuppance can be either, and it can
apply to things beyond the justice system. Nowadays you'll most likely
hear this word describe something bad. If someone gets a deserved
punishment, you'd say "He got his comeuppance."

C is for COMEUPPANCE which means a punishment or fate that someone
deserves "He's a dishonest guy now he's free but one day he'll get his
comeuppance and end up in prison."
* TODO dodge                                                            :sat:
* dodgy :Gideon:
[2021-05-13 Thu 19:18]

A dodgy situation is risky and suspicious. A dodgy person is skilled
in lying and deceiving. Neither should be trusted.

When a person or situation is called dodgy, it's a clue that they
should be dodged if at all possible. A job might be dodgy because it's
illegal or dangerous. A shortcut might be dodgy if it could damage
your car. Running a marathon without preparation is very
dodgy. Similarly, a dodgy person is untrustworthy because they’re
evasive, cunning, sly, or just a flat-out liar.

D is for DODGY. DODGY is a great word because it has so many uses. It
can mean suspicious or bad quality or strange for example: "it's got a
dodgy haircut" "There's a dodgy man outside". "My position in this
company is a bit dodgy: I might lose my job any minute."
* incite :Gideon:
[2021-05-13 Thu 19:21]

To incite is to cause to act or occur. Violent words can incite
violent actions which, in turn, might incite public outcry against
violence.

Incite comes from a Latin verb meaning "to move into action" and if
you incite someone to do something, that is exactly how to describe
it. Usually it is used in a negative context. Radical and intolerant
teachings can incite hatred in those who listen. And if a government
restricts its people too much, it can incite unrest and rebellion in
the population.

by the way egg on doesn't have anything to do with eggs. It comes from
an old-world Old Norse world EGGJA (not sure I'm pronouncing that
right) which means to incite and it's been in the English language
since around 1200.

* flustered                                                          :Gideon:
[2021-05-17 Mon 17:08]

To be flustered is to lose your cool. When you're flustered, you're
embarrassed, agitated, or just confused.

If your pants fell down in the middle of class while you were giving a
presentation, you'd probably be flustered: highly embarrassed, out of
breath, and a little freaked out. It's hard to concentrate when you're
flustered — it's a distracting state of mind. Being flustered isn't
quite as bad as being panicked, but it's close. People can also get
flustered by good things, like if someone you had a crush on kissed
you.

F is for flustered. Flustered which means to be confused and nervous
at the same time. "I always get flustered when lots of people are
asking me lots of questions at same time."; "I was getting flustered
because my train was delayed and I thought I would miss my flight."
* galore                                                             :Gideon:
[2021-05-17 Mon 17:09]

At a party with more cupcakes than anyone could imagine, you’ll hear
guests say, “There are cupcakes galore!”  Galore means there’s so much
that it’s unbelievable.

The Irish phrase go lear literally translates as “to sufficiency.”  If
there are sufficient enough bananas to build a house with them, you’d
say that there are bananas galore.  The word is an example of a
postpositive adjective, which means it comes after the word it
describes.  So when you go to a circus and 700 clowns surround you,
don’t say “There are galore clowns,” because the correct way to
express your terror is this: “There are clowns galore. Help!”

G is for galore isn't that beautiful word galore and galore comes from
Scottish Gaelic. There aren't many words in English language from
Gaelic but this is one of them and it just means a lot, much or many
but in a positive way. But the trick about galore is that it comes
after the noun. It's quite a literary and poetic word but it's common
enough so do use it for example "For my birthday everybody bought me a
bottle of whisky. So now I have whisky galore." whiskey is also a
Gaelic word which means water of life. So whisky galore is the only
phrase in the English language just using words from Gaelic. "I went
to the tech show and there were gadgets galore. Wonderful wonderful
gadgets."
* TODO hullabaloo                                                    :Gideon:
[2021-05-17 Mon 17:19]

H is for hullabaloo now this means a lot of noise, a fuss, a
disturbance a commotion. For example "On the first day of the sales
there was quite a hullabaloo outside the shop just before it
opened". "I just wanted to get a refund but God what a hullabaloo they
made of it all."
* commotion                                                          :Gideon:
[2021-05-17 Mon 17:19]

A commotion is a noisy disturbance. If you're trying to quietly
concentrate on reading this, you wouldn't want the person next to you
to cause a commotion, or it would distract you.

Commotion, which comes from the Middle French word commocion, means
"violent motion, agitation." It can be a disorderly outburst or
disruption, like someone yelling in the street at night, or five
people arguing about someone talking on a cellphone while a play is
being performed in front of them. Commotion can also describe
out-of-control movement, like people pushing and shoving to get to the
front row of a concert.

H is for hullabaloo now this means a lot of noise, a fuss, a
disturbance a commotion. For example "On the first day of the sales
there was quite a hullabaloo outside the shop just before it
opened". "I just wanted to get a refund but God what a hullabaloo they
made of it all."
* inkling                                                            :Gideon:
[2021-05-17 Mon 17:22]

Is someone yapping on and on and you only have the vaguest idea of
what they're talking about? Then you understood just an inkling — a
glimmer, a fraction — of what they were saying.

Inkling can also mean a sly suggestion or faint implication. If
someone drops a hint you're not wanted they've given you an inkling
you're not wanted. The word comes from the medieval English word
inclen, which suitably enough means "to utter in an undertone." In
other words, what's really being said is in between the lines of
what's actually being said on the surface. By now you've probably got
the inkling that inklings can be sneaky things.

I is for inkling. Now inkling is another way of saying that you have a
feeling that something might happen or something is true an idea even
though you're not 100% sure. So for example "I have an inkling that
Jane might break up with Jim. Something she said gave me the
impression that she's not happy." "I have an inkling that Johnson had
something to do with the murder even though he denies it. Yes indeed I
think Johnson"
* jaunt :Gideon:
[2021-05-17 Mon 17:23]

Running out to get pizza to bring back before the big game? This
short, quick, pleasurable trip could be called a jaunt (unless of
course, you get your pizza from Italy, that’s called “time to get a
closer pizza place”).

Jaunt was used in the 17th century to describe a journey on a horse
just long enough to tire the horse out. Nebraska has what they call a
Junk Jaunt, which is a yard sale that includes up to 40 towns and
stretches nearly 300 miles and draws up to 20,000 people. That’s more
than enough to make any horse tired, but they call it a jaunt
nevertheless.

J is for jaunt. Now jaunt is usually a noun and it means taking a
short trip for pleasure. For example "I say Samantha, do you fancy
taking a jaunt with me in my vintage Bugatti this Sunday." "I don't
travel much these days except for the occasional jaunt to visit my
family in Scotland"
* knack :Gideon:
[2021-05-17 Mon 17:24]

If you have a knack for doing something, you do it well. You may have
a knack for baking cakes or a knack for cracking jokes. These things
come easy to you.

Although the noun knack refers to a special talent, the sense is that
it is a more innate talent — as opposed to a certain technique. So if
someone instinctively has a talent for fixing plumbing, for example,
you can say they have a knack for it. If, however, they unclog a sink
by having a wrench in one hand and a how-to book in the other, then
they may have the technique, but they probably don't have the knack.

K is for knack. knack means a skill or an ability or a talent.
