-*- coding: utf-8 -*-


* irascible :misc:
[2021-03-01 Mon 15:49]

If you're irascible, you get angry easily — perhaps blowing up in rage
when someone brushes into you.

Irascible comes from the Latin root ira, which means "anger" or
"rage," the same root that gives us the word ire, "anger." The -sc in
the middle of irascible, means "becoming," so irascible doesn't just
mean you're angry — it's got action built into it. If you're looking
for a fight most of the time, then you're irascible — ready for the
spark that's going to set you on fire.

He begins to get more irascible and one day while his wife is out
he decides that he's going to collect all his childhood mementos the
memories of his youth and burn them as if he's trying to eradicate his
past.

* heir :misc:
[2021-03-03 Tue 17:07]

If your grandfather leaves his candy factory to you in his will, it
means you're the heir to the family candy business, and after your
grandfather dies, you will inherit the factory.

When you're named in a will or are legally entitled to inherit
something, you're an heir. You can be the heir to someone's money,
business, or title; in a monarchy, the king or queen's oldest son is
usually the heir to the throne. The word heir isn't pronounced like
"hair," but instead has a silent h and sounds like "air."

The bats weren't surprised you to know that some
men blamed their own midlife crises on the menopause, their wife's
menopause as well so let me go back to Reginald Perrin.

*  wee                                                                 :misc:
[2021-03-03 Wed 12:54]

I had a flashback to when I was a wee girl.

* presbyterian                                                         :misc:
[2021-03-03 Wed 13:03]

Not even the one that says, "Did you know that Britney Spears is an
anagram for Presbyterian?".

* hourglass :misc:
[2021-03-03 Wed 13:10]

So it's kind of like an hourglass effect: when you're young you're
great at being yourself; when you're old you're great at being
yourself; but the bit in the middle is sometimes the most problematic.

* inferiority :misc:
[2021-03-03 Wed 13:11]

Inferiority is the quality of being worse than other things or people.

You know how some movies are terrible — inferior — compared to other
movies? You've noticed the inferiority of those films. Inferiority is
a quality possessed by people and things that are not as good as
others. To a king, the common people are defined by their inferiority.
Most people agree on the inferiority of a TV dinner to a home-cooked
meal. When someone feels like they are always worse off than others,
they have an inferiority complex. Inferiority is the opposite of
superiority.

If you've got an inferiority complex you suffer from an over-modest
self-regard.
* vantage :misc:
[2021-03-03 Wed 13:15]

A vantage is a really good place from which to survey a scene. You
might find that the roof of the house offers an excellent vantage from
which to drop water balloons on your kid brother’s head.

Vantage is a variation of advantage, but when we use vantage we’re
almost always talking about a position, not just general superiority.
If you had extra tutoring for a big exam, you would have the advantage
over a classmate who didn’t. But if your seat for the test allowed you
to see the answer sheet lying on the desk, well then you would have a
superior vantage — not that you would take advantage of that, of
course!

Interiority is entirely unrelative, so to operate from this position
of interiority, it's like a perceptual vantage point.

* lodging :misc:
[2021-03-16 Tue 22:23]

Lodging is a name for the place you stay when you're not at home. Your
lodging could be a luxury hotel, a yurt in the woods, or a college
dormitory.

Your accommodations while traveling, going away to school, being an
exchange student, or doing temporary work are all called lodging or
lodgings. A room in a hotel is one kind of lodging, and a sleeping bag
on the floor of a tent is another kind. Lodging comes from lodge and
its earlier form, loggen, "to set up camp," from the Old French root
loge, "hut or cabin."

One afternoon, at low water, Mr. Isbister, a young artist lodging at
Boscastle, walked from that place to the picturesque cove of Pentargen,
desiring to examine the caves there.
* cove :misc:
[2021-03-16 Tue 22:23]

A cove is a small, sheltered part of an ocean's coast. A cove can be a
good place to put a sea kayak in the water and start paddling along
the shore.

A cove is basically the same thing as a "bay," but smaller. Coves are
protected coastal areas affected by tides and connected to the open
sea by a narrow entrance. The water in a cove is calmer than the open
ocean, and the cove itself is often oval or circular in shape. The
earliest meaning of cove was "den or cave," and later "small bay,"
probably influenced by a Scottish meaning of the word, "hollow place
in coastal rocks."

One afternoon, at low water, Mr. Isbister, a young artist lodging at
Boscastle, walked from that place to the picturesque cove of Pentargen,
desiring to examine the caves there.

* precipitous                                                          :misc:
[2021-03-16 Tue 22:24]

A sharp, steep drop — whether it's in a stock price, a roller coaster,
or a star's popularity — could be described as a precipitous one. Put
simply, precipitous means perilously steep.

Look closely and you'll spot most of the word precipice (a sheer,
almost vertical cliff) in precipitous. Now imagine how you'd feel
standing at the edge peering over, and you'll grasp the sense of
impending danger that precipitous tends to imply. Precipitous declines
in sales lead to bankruptcy. Precipitous mountainside hiking trails
are not for the acrophobic. It can describe an ascent, but precipitous
is most often used for things going literally or figuratively
downhill.

Halfway down the precipitous path to the Pentargen beach he came
suddenly upon a man sitting in an attitude of profound distress
beneath a projecting mass of rock. The hands of this man hung limply
over his knees, his eyes were red and staring before him, and his face
was wet with tears.
* disconcert                                                           :misc:
[2021-03-16 Tue 22:25]

A concert is a choreographed harmony of sounds but throw the prefix
"dis" in front it and you have the opposite: disconcerted — a word
used to describe someone whose composure has been disturbed or
unsettled.

Disconcerted is a combination of the French prefix des- which
indicates reversal and the word concerter meaning "bring together," so
something disconcerted is not brought together, but rather torn apart,
or thrown into confusion. If you are under a lot of stress or worried
about something, you're in a disconcerted or discombobulated state.
Take a breath. Relax a moment. Everything will be OK.

He glanced round at Isbister’s footfall. Both men were disconcerted,
Isbister the more so, and, to override the awkwardness of his
involuntary pause, he remarked, with an air of mature conviction, that
the weather was hot for the time of year.
* involuntary :misc:
[2021-03-16 Tue 22:26]

Involuntary describes a reflex or action done without conscious
control or will — like a blink, a sneeze, a yawn, or “the giggles.”

If you volunteered to do it, it’s voluntary. If you didn’t volunteer,
but you find yourself doing it anyway, it’s involuntary. This can go
for the involuntary hiccups you wrestle with on your blind date, as
well as the involuntary task you do at your manager’s
insistence. Involuntary gets a lot of blame, but something that is
involuntary is not necessarily bad: Breathing is involuntary, but you
would probably do it anyway if given the choice.

He glanced round at Isbister’s footfall. Both men were disconcerted,
Isbister the more so, and, to override the awkwardness of his
involuntary pause, he remarked, with an air of mature conviction, that
the weather was hot for the time of year.
