-*- coding: utf-8 -*-


* irascible :misc:
[2021-03-01 Mon 15:49]

If you're irascible, you get angry easily — perhaps blowing up in rage
when someone brushes into you.

Irascible comes from the Latin root ira, which means "anger" or
"rage," the same root that gives us the word ire, "anger." The -sc in
the middle of irascible, means "becoming," so irascible doesn't just
mean you're angry — it's got action built into it. If you're looking
for a fight most of the time, then you're irascible — ready for the
spark that's going to set you on fire.

He begins to get more irascible and one day while his wife is out
he decides that he's going to collect all his childhood mementos the
memories of his youth and burn them as if he's trying to eradicate his
past.

* heir :misc:
[2021-03-03 Tue 17:07]

If your grandfather leaves his candy factory to you in his will, it
means you're the heir to the family candy business, and after your
grandfather dies, you will inherit the factory.

When you're named in a will or are legally entitled to inherit
something, you're an heir. You can be the heir to someone's money,
business, or title; in a monarchy, the king or queen's oldest son is
usually the heir to the throne. The word heir isn't pronounced like
"hair," but instead has a silent h and sounds like "air."

The bats weren't surprised you to know that some men blamed their own
midlife crises on the menopause, their wife's menopause as well so let
me go back to Reginald Perrin.

* wee                                                                  :misc:
[2021-03-03 Wed 12:54]

I had a flashback to when I was a wee girl.

* presbyterian                                                         :misc:
[2021-03-03 Wed 13:03]

Not even the one that says, "Did you know that Britney Spears is an
anagram for Presbyterian?".

* hourglass :misc:
[2021-03-03 Wed 13:10]

So it's kind of like an hourglass effect: when you're young you're
great at being yourself; when you're old you're great at being
yourself; but the bit in the middle is sometimes the most problematic.

* inferiority :misc:
[2021-03-03 Wed 13:11]

Inferiority is the quality of being worse than other things or people.

You know how some movies are terrible — inferior — compared to other
movies? You've noticed the inferiority of those films. Inferiority is
a quality possessed by people and things that are not as good as
others. To a king, the common people are defined by their inferiority.
Most people agree on the inferiority of a TV dinner to a home-cooked
meal. When someone feels like they are always worse off than others,
they have an inferiority complex. Inferiority is the opposite of
superiority.

If you've got an inferiority complex you suffer from an over-modest
self-regard.
* vantage :misc:
[2021-03-03 Wed 13:15]

A vantage is a really good place from which to survey a scene. You
might find that the roof of the house offers an excellent vantage from
which to drop water balloons on your kid brother’s head.

Vantage is a variation of advantage, but when we use vantage we’re
almost always talking about a position, not just general superiority.
If you had extra tutoring for a big exam, you would have the advantage
over a classmate who didn’t. But if your seat for the test allowed you
to see the answer sheet lying on the desk, well then you would have a
superior vantage — not that you would take advantage of that, of
course!

Interiority is entirely unrelative, so to operate from this position
of interiority, it's like a perceptual vantage point.

* whence :misc:
[2021-03-10 Wed 13:47]

Use the adverb whence as an old-fashioned way to say "from which" or
"from where." If you found a hundred dollar bill on the ground, you
might ask, "Whence did this money come?"

Not many people use the word whence these days — you're most likely to
hear it in a Shakespeare play or if a speaker is trying to sound
especially formal. Many people say, "from whence," as in "Throw that
fish back in the sea from whence it came," although strictly speaking
the "from" is unnecessary. Instead, a dinner party guest could ask,
"Whence came this delicious fish?"

That's from whence that creative spark of genius often comes.
* leftover :misc:
[2021-03-10 Wed 13:56]

This was one of those leftover Victorian ideals from England, where my
mother grew up.
* patchwork :misc:
[2021-03-11 Thu 12:09]

You don't develop an identity that's predicated on being a patchwork
personality.
* bifurcation :misc:
[2021-03-11 Thu 12:26]

Bifurcation is a process in which something splits in two.

Bifurcation is a word that sounds fancy but has a very simple meaning:
splitting or cutting in two. If a stream divides into two smaller
streams, that's a bifurcation. If you split a company into two
divisions, that's a bifurcation too. This word can also refer to the
exact spot where one thing splits into two. Since bi means two in many
words, such as bimonthly, that's a good reminder of what bifurcation
means.

Now, they're not always as well sign-posted as this one, but you know
those times in your life when you come to a bifurcation on the path,
and you sense that the potential for change is heightened.
* castigation :misc:
[2021-03-11 Thu 12:31]

If your coach yells at your team for sloppy play, her post-game speech
might be called a castigation. A castigation is a harsh verbal
reprimand.

No one likes to be on the receiving end of castigation. The word comes
from the Latin castigus which means "to make pure." Try to remember
during castigation that the castigator is, in their own misguided way,
trying to make you a better person. But that may be hard to think of
when someone is bawling you out.

Those are two extremes of your ego, and one of them is about
self-congratulation, and the other one is about self-castigation.
* toast :misc:
[2021-03-11 Thu 12:33]

What do you get when you heat a piece of bread long enough for it to
become golden-brown on both sides? Congratulations, you've made a
piece of toast!

To make toast, you simply toast bread, or heat it on a grill, in a
toaster, or in an oven. People put all kinds of things on toast, from
butter to jam to baked beans. Making or giving a toast is another
thing all together — this kind of toast is a brief speech given while
raising glasses and drinking together: "A toast to the birthday girl!"
And if you are so highly regarded in a particular area that you're
almost famous, you're "the toast of the town."

If you didn't have an ego you'd be toast.
* equanimity :misc:
[2021-03-11 Thu 12:34]

If you take the news of your parakeet's death with equanimity, it
means you take it calmly without breaking down. Equanimity refers to
emotional calmness and balance in times of stress.

If equanimity reminds you of equal, that's because the words have a
lot in common. The noun equanimity was borrowed from Latin
aequanimitās, from aequanimus "even-tempered, fair," formed from
aequus "even, level, equal" plus animus "mind." The archaic phrase to
bear with equal mind means "to bear with a calm mind," and is a
translation from the Latin. The phrase a level mind also refers to
calmness. A near synonym is composure.

That's what I would call equanimity, or equilibrium, and it's the kind
of state of mind that cannot be perfumed in any way by anything that
happens outside you.
* gorgeous :misc:
[2021-03-11 Thu 12:34]

Reach for the adjective gorgeous to describe jaw-droppingly beautiful,
magnificent people or things.

Good-looking is one thing. Beautiful is another. But reserve gorgeous
for the kind of looks that take your breath away. Some synonyms
include resplendent, dazzling, spectacular, and splendid. We know that
the word comes from Old French gorgias, meaning "elegant," but beyond
that it's hard to say for sure. It might have something to do with
fancy necklaces adorning the throat — la gorge in French. If calling
someone gorgeous isn't enough, pack some extra punch and say
"drop-dead gorgeous" instead.

When you look at the sky, and it's made a rainbow, and it's absolutely
gorgeous, there's no question that the sky's up there going, "Ha, did
you see my rainbow?"
* impermanence :misc:
[2021-03-11 Thu 12:35]

No, the sky just is, because the sky sees the impermanence of the
clouds, and the impermanence of the rainbows, and you have to develop
an inner state of mind that's as impervious to all the good shit and
bad shit that happens to you as the sky is to the weather.
* impervious                                                           :misc:
[2021-03-11 Thu 12:35]

An impervious surface is one that can't be penetrated. The word is
often followed by "to," as in "His steely personality made him
impervious to jokes about his awful haircut."

Most of the sentences you'll run across using impervious will be
followed by the word "to" and a noun. Things are often described as
being impervious to physical assaults like heat, water, bullets,
weather, and attack, but just as frequently to less tangible things,
like reason, criticism, pain, and pressure. The word comes from Latin:
in- + pervius, meaning "not letting things through." A common synonym
is impermeable.

No, the sky just is, because the sky sees the impermanence of the
clouds, and the impermanence of the rainbows, and you have to develop
an inner state of mind that's as impervious to all the good shit and
bad shit that happens to you as the sky is to the weather.
* lass                                                                 :misc:
[2021-03-11 Thu 13:18]

A lass is a girl. Your Scottish folk dance teacher might announce,
"Lads line up on that side, lasses on this side!"

Lass is an old-fashioned way to say "young girl," and it's more common
in parts of Britain than in the US. You're most likely to hear this
word in Scotland and the north of England, although lass is most
likely rooted in Scandinavian languages, like the Old Swedish løsk
kona, "unmarried woman," or the Old Norse löskr, "idle or weak."

One night my mother came up to get us and we were having pillow fights
she showed up and she said, "Right lasses, everybody's ready.
* disregard :misc:
[2021-03-11 Thu 13:20]

If everyone at the city council meeting tends to disregard anything
that's said by the eccentric gentleman with the parrot on his
shoulder, it means that no one pays any attention to him.

To disregard something is to ignore it, or to deliberately pay it no
attention. Sometimes the word is used to mean "neglect," implying that
something important is not being taken care of. Disregard can also be
a noun; you could complain that your family has a complete disregard
for your privacy when they gather outside your bedroom door to
eavesdrop on your telephone conversations.

But what it has left me with is spectacular disregard for where my
abilities end, and spectacular disregard for being the center of
attention.
* dial :misc:
[2021-03-11 Thu 13:25]

A dial is a circle that has a series of numbers or marks representing
numbers, like the dial of a clock face, a compass, or an old-fashioned
telephone. If you have a watch that glows in the dark, it's the dial
you can see even in a dark movie theater.

Old telephones and televisions both have dials — the first has numbers
from zero to nine in a circle, and the latter has a round disc for
changing channels. When you call someone, you can say that you dial
their number. In fact, people tend to use the word dial when they use
a phone, even if they're pushing buttons or tapping a touch screen.
The Latin root is dialis, "daily," and the earliest dial was a
sundial.

That's what happens when you dial in to the personal pronoun.

