-*- coding: utf-8 -*-



* muster :misc:
[2021-02-02 Tue 13:43]

Originally meaning "to gather soldiers," muster has been expanded to
include gathering up just about anything — you can muster up some
dinner, some friends, or even some ketchup, pickles and mustard.

Remember that muster used to involve getting reluctant soldiers out of
bed and into the field of battle — so it involves overcoming a certain
inertia. When you muster up the courage to face something, it's clear
that this is pretty scary for you.

When I didn’t feel like I was having an impact during office hours, it
was that much harder to muster the effort to have an impact afterward.

* feasible :misc:
[2021-02-03 Wed 15:10]

If something is feasible, then you can do it without too much
difficulty. When someone asks "Is it feasible?" the person is asking
if you'll be able to get something done.

Feasible things are possible. If you have enough time, money, or
energy to do something, it's feasible. Something might be feasible at
one time and then not feasible at another time. Because of
technological advances and competition with the Russians, going to the
moon was feasible for the United States in the sixties. Often, people
disagree about what's feasible, especially in politics, where how
feasible a project is counts for a lot.

The music industry is too cruel an
environment for this to be a feasible plan.
* facets :misc:
[2021-02-03 Wed 15:15]

A facet is one side or aspect of something. If you’re thinking about
quitting your day job to become a circus performer, you should first
consider every facet of what your new life would be like.

Facet, which is related to the word face, can also refer to one of the
flat “faces” of a diamond or other gem. This was the word’s original
definition, and it was evidently seen as an apt metaphor for one side
of a complex idea. When a problem has many parts to consider (or when
it’s just a huge mess), you can describe it as multifaceted.

And we’ll see how these four facets
can be applied to our careers:
* languish :misc:
[2021-02-03 Wed 15:20]

To languish is to become pitiful or weak because you're sick, in love,
or stuck somewhere. A prisoner might languish in jail, longing for her
freedom.

Languish, like languid, is from the Latin word languere which means
"to be weak or faint." Your houseplants might languish in a dark dry
corner. A Romantic poet might languish on a velvet couch with the back
of her hand to her forehead. People in operas love to languish: The
main character in La Traviata, Violetta, languishes from longing and
eventually tuberculosis.

Remarkable software developers don’t languish.
* recoup :misc:
[2021-02-03 Wed 15:26]

To recoup is a kind of recovery: If you lost some money but then made
that amount back, you recouped your loss.

When you recuperate, you get better after being sick. And when you
recoup something, you get better or bounce back after a loss.
Businesses that lose money try to recoup it by throwing a sale or
cutting their budget. If a runner falls behind in a race but then
speeds up to the front of the pack, he's recouped his lead. In some
cases this word also means "to reimburse."

On the other hand, you have no guarantee that you’ll even recoup your
original investment.
* pundits :misc:
[2021-02-03 Wed 15:32]

A pundit is a well-known expert, someone whose opinions show up on
television, online, or in the newspaper. Some TV news programs are
nothing more than a bunch of pundits arguing about current events.

Why not just call them experts? Because pundit is a lovely word that
is very close to its Sanskrit root, payndita-s, "learned man or
scholar." Originally, a pundit was a "learned Hindu" or Sanskrit
expert. Today's classic examples of the pundit are guests on talk
radio and professional sports commentators, all brilliant dispensers
of insights, statistics, and occasional hot air.

The platform created a
definite buzz, and the pundits were giddy in anticipation of a solid new contender on the
operating system block.
* stalwarts :misc:
[2021-02-04 Thu 14:25]

To be stalwart is to be loyal, no matter what, like your friend who
remains a devoted fan of an actor she's admired since childhood, even
if that was the last time the guy made a decent movie.

Stalwart can describe someone who's able to keep on going even when
things get hard, like a marathon runner who doesn't slow down, even
after spraining an ankle, or a supporter of a political cause that
everyone else has long declared over. In U.S. history, the word
stalwart was used in 1877 to describe Republicans who remained
unwilling to trust the South, even though the Civil War was long over
by that time.

It’s easy to imagine
that the careers of the last-remaining stalwarts of an aged and dying technology are in the
same death spiral as the technology itself.
* tykes :misc:
[2021-02-04 Thu 14:27]

A tyke is a child, especially a small one. A nursery school is full of
tykes.

Little kids are a handful, as all parents and teachers know. Maybe
that's why there are some slangy words for them, such as rugrat and
tyke. Tyke is a very informal word: a letter from the principal
wouldn't call a kid a tyke. However, an uncle or friend of the family
might say, "How are you tykes doing?" This word is a little
old-fashioned, but it's still used.

Typically, the young tykes don’t know (or want to know) how to make the old systems listen.
* clump :misc:
[2021-02-04 Thu 14:32]

A clump is a "bunch" or a "cluster." If you're a gardener, the last
thing you want to see is a clump of weeds growing in the middle of
your newly groomed lawn.

Essentially, a clump is a grouping. You might see a clump of sheep
grazing in a field or you might throw a clump of clothes into the
washing machine. Clump can also mean lump, like when you find a clump
of grass stuck to your shoe. As a verb, clump means "to gather," as in
"a flock of birds clumped together in a tree."

Do they clump?
* caters :misc:
[2021-02-04 Thu 14:41]

To cater means to supply food for meetings or celebrations. If you're
having a big barbecue party but would rather hang out with your
friends than grill, you could pay someone to cater it.

In Middle English, the food supply in a big household was known as the
cates, and so to cater meant keeping the pantry full. These days,
caterers don't do pantries. They cook food for many different
households or offices. Cater has also come to mean "giving what is
desired or needed." You might cater to your grandfather by bringing
him tea, reading to him, and laughing at his bad jokes.

India caters to the
already balanced IT services markets.
* nimble :misc:
[2021-02-04 Thu 14:45]

If you're nimble, you can move quickly and with ease. That spryness
can be both physical and mental, so even if your granny isn't very
nimble on her feet, she can probably still whip you in chess.

A toddler might recognize the word nimble from the nursery rhyme:
"Jack be nimble / Jack be quick / Jack jump over / The candlestick,"
but may not be nimble enough to deduce the meaning. Nimble, from the
14th century Old English næmel, meaning "quick to grasp," can refer to
one's mental quickness or physical agility.

In either case, it pays to understand the forces at work and to be skilled and nimble
enough to react to them.