-*- coding: utf-8 -*-



* muster :misc:
[2021-02-02 Tue 13:43]

Originally meaning "to gather soldiers," muster has been expanded to
include gathering up just about anything — you can muster up some
dinner, some friends, or even some ketchup, pickles and mustard.

Remember that muster used to involve getting reluctant soldiers out of
bed and into the field of battle — so it involves overcoming a certain
inertia. When you muster up the courage to face something, it's clear
that this is pretty scary for you.

When I didn’t feel like I was having an impact during office hours, it
was that much harder to muster the effort to have an impact afterward.

* feasible :misc:
[2021-02-03 Wed 15:10]

If something is feasible, then you can do it without too much
difficulty. When someone asks "Is it feasible?" the person is asking
if you'll be able to get something done.

Feasible things are possible. If you have enough time, money, or
energy to do something, it's feasible. Something might be feasible at
one time and then not feasible at another time. Because of
technological advances and competition with the Russians, going to the
moon was feasible for the United States in the sixties. Often, people
disagree about what's feasible, especially in politics, where how
feasible a project is counts for a lot.

The music industry is too cruel an environment for this to be a
feasible plan.
* facet                                                                :misc:
[2021-02-03 Wed 15:15]

A facet is one side or aspect of something. If you’re thinking about
quitting your day job to become a circus performer, you should first
consider every facet of what your new life would be like.

Facet, which is related to the word face, can also refer to one of the
flat “faces” of a diamond or other gem. This was the word’s original
definition, and it was evidently seen as an apt metaphor for one side
of a complex idea. When a problem has many parts to consider (or when
it’s just a huge mess), you can describe it as multifaceted.

And we’ll see how these four facets can be applied to our careers:
* languish :misc:
[2021-02-03 Wed 15:20]

To languish is to become pitiful or weak because you're sick, in love,
or stuck somewhere. A prisoner might languish in jail, longing for her
freedom.

Languish, like languid, is from the Latin word languere which means
"to be weak or faint." Your houseplants might languish in a dark dry
corner. A Romantic poet might languish on a velvet couch with the back
of her hand to her forehead. People in operas love to languish: The
main character in La Traviata, Violetta, languishes from longing and
eventually tuberculosis.

Remarkable software developers don’t languish.
* recoup :misc:
[2021-02-03 Wed 15:26]

To recoup is a kind of recovery: If you lost some money but then made
that amount back, you recouped your loss.

When you recuperate, you get better after being sick. And when you
recoup something, you get better or bounce back after a loss.
Businesses that lose money try to recoup it by throwing a sale or
cutting their budget. If a runner falls behind in a race but then
speeds up to the front of the pack, he's recouped his lead. In some
cases this word also means "to reimburse."

On the other hand, you have no guarantee that you’ll even recoup your
original investment.
* pundit                                                               :misc:
[2021-02-03 Wed 15:32]

A pundit is a well-known expert, someone whose opinions show up on
television, online, or in the newspaper. Some TV news programs are
nothing more than a bunch of pundits arguing about current events.

Why not just call them experts? Because pundit is a lovely word that
is very close to its Sanskrit root, payndita-s, "learned man or
scholar." Originally, a pundit was a "learned Hindu" or Sanskrit
expert. Today's classic examples of the pundit are guests on talk
radio and professional sports commentators, all brilliant dispensers
of insights, statistics, and occasional hot air.

The platform created a definite buzz, and the pundits were giddy in
anticipation of a solid new contender on the operating system block.
* stalwart                                                             :misc:
[2021-02-04 Thu 14:25]

To be stalwart is to be loyal, no matter what, like your friend who
remains a devoted fan of an actor she's admired since childhood, even
if that was the last time the guy made a decent movie.

Stalwart can describe someone who's able to keep on going even when
things get hard, like a marathon runner who doesn't slow down, even
after spraining an ankle, or a supporter of a political cause that
everyone else has long declared over. In U.S. history, the word
stalwart was used in 1877 to describe Republicans who remained
unwilling to trust the South, even though the Civil War was long over
by that time.

It’s easy to imagine that the careers of the last-remaining stalwarts
of an aged and dying technology are in the same death spiral as the
technology itself.
* tyke                                                                 :misc:
[2021-02-04 Thu 14:27]

A tyke is a child, especially a small one. A nursery school is full of
tykes.

Little kids are a handful, as all parents and teachers know. Maybe
that's why there are some slangy words for them, such as rugrat and
tyke. Tyke is a very informal word: a letter from the principal
wouldn't call a kid a tyke. However, an uncle or friend of the family
might say, "How are you tykes doing?" This word is a little
old-fashioned, but it's still used.

Typically, the young tykes don’t know (or want to know) how to make
the old systems listen.
* clump :misc:
[2021-02-04 Thu 14:32]

A clump is a "bunch" or a "cluster." If you're a gardener, the last
thing you want to see is a clump of weeds growing in the middle of
your newly groomed lawn.

Essentially, a clump is a grouping. You might see a clump of sheep
grazing in a field or you might throw a clump of clothes into the
washing machine. Clump can also mean lump, like when you find a clump
of grass stuck to your shoe. As a verb, clump means "to gather," as in
"a flock of birds clumped together in a tree."

Do they clump?
* cater                                                                :misc:
[2021-02-04 Thu 14:41]

To cater means to supply food for meetings or celebrations. If you're
having a big barbecue party but would rather hang out with your
friends than grill, you could pay someone to cater it.

In Middle English, the food supply in a big household was known as the
cates, and so to cater meant keeping the pantry full. These days,
caterers don't do pantries. They cook food for many different
households or offices. Cater has also come to mean "giving what is
desired or needed." You might cater to your grandfather by bringing
him tea, reading to him, and laughing at his bad jokes.

India caters to the
already balanced IT services markets.
* nimble :misc:
[2021-02-04 Thu 14:45]

If you're nimble, you can move quickly and with ease. That spryness
can be both physical and mental, so even if your granny isn't very
nimble on her feet, she can probably still whip you in chess.

A toddler might recognize the word nimble from the nursery rhyme:
"Jack be nimble / Jack be quick / Jack jump over / The candlestick,"
but may not be nimble enough to deduce the meaning. Nimble, from the
14th century Old English næmel, meaning "quick to grasp," can refer to
one's mental quickness or physical agility.

In either case, it pays to understand the forces at work and to be
skilled and nimble enough to react to them.

* unnerving :misc:
[2021-02-08 Mon 12:06]

Use the adjective unnerving to describe situations and experiences
that cause you to lose your courage. No matter how brave you are, a
walk alone through a cemetery at night is bound to be a little
unnerving.

You might find it unnerving to get a flat tire on a deserted country
road at sunset, or to find yourself onstage mid-play having completely
forgotten your lines. In the 1620's, the root word unnerve meant "to
destroy the strength of," but by the early 1700's it came to mean "to
deprive of courage."

Yes, it’s extremely unnerving at first.
* sore :misc:
[2021-02-08 Mon 12:07]

A sore is a broken patch of skin — something you might put a bandage
on — or it's something that gives you pain, like a sore throat, that’s
red and scratchy and painful.

You can have a sore and you can also be sore: if you've just ridden
your bike over the Alps, you're probably pretty sore — achy and
hurting all over. Maybe you've heard phrases like "Don't be sore at
me, boss," from old gangster movies, meaning "don't be angry." A sore
point or a sore subject is something you don't want to discuss, like
the sensitive topic of your last history quiz, the one you slept
through.

As a young musician, I would find myself in situations where I was so
obviously the worst guy in the band that I was sure I would stick out like a
sore thumb.
* glamorous :misc:
[2021-02-08 Mon 12:10]

Movie stars look glamorous when they walk down the red carpet in their
designer gowns. Glamorous means full of glamour, beauty, and
excitement.

Glamorous comes from the Scottish gramarye meaning "magic,
enchantment, spell." See a glamorous woman walking down the street and
you might be captivated or enchanted by her beauty. A person can
appear or act glamorous. An event like a really over-the-top party can
be glamorous. Or a lifestyle that one chooses for herself can be
glamorous, full of parties and swanky events.

I’d like to think I had some kind of superhuman
ability to morph into a genius simply by standing next to one, but in
retrospect I think it’s a lot less glamorous than that.
* slurs :misc:
[2021-02-08 Mon 12:14]

A slur is an insulting remark. In a political campaign, it’s not
unheard of for a candidate to launch a slur at her opponent, though
doing so is usually frowned upon.

Slur can also be used as a verb meaning “to insult,” and it has a
number of additional meanings as well. To slur one’s speech is to
pronounce words in a clumsy, lazy way. In the context of music, to
slur is to slide smoothly from one note to another. The word history
of slur is hazy, but some scholars have suggested a relationship with
a Dutch word meaning "to drag."

Also, like an alcoholic who slurs his speech even when he’s not drunk, I’d find
the bad habits of the bar bands carrying over to my non-bar-band nights.
* outright :misc:
[2021-02-08 Mon 13:26]

If you do something outright, you do it in a wholehearted,
unrestricted way. If you declare outright that you’re never eating
another cupcake, that’s the end of that. If you eat one anyway, you
told an outright lie.

If an event is cancelled outright, there's no question about it being
rescheduled, and if you buy a new car outright, you pay for it all at
once, instead of making monthly payments. Outright means direct and
immediate — whether it's an adverb or an adjective: "The child's
outright refusal to put on his shoes exasperated his babysitter." It
can also mean “right away.” If you step on a slug, you’ll probably
kill it outright. Ew.

Acknowledging outright that you’re not the best
wipes away the fear of being discovered for the not-best person you are.


* provable :misc:
[2021-02-08 Mon 13:34]

It’s definitely not a scientifically provable measure of popularity,
but it’s a pretty good indicator.


* liability :misc:
[2021-02-16 Tue 13:42]

A liability is a debt or obligation or a personal flaw that stands in
your way. A company's liabilities are simply the debts on its ledger,
but a personal liability might be your extreme shyness in social
situations.

Depending on how you use it, the word liability has very different
meanings. In a business or financial sense, a liability is a debt or
fiscal obligation, like a mortgage or a loan. A limited liability
company means if the company fails, the partners are on the hook for
only what they initially invested in the company. A personal
liability, however, is some element of your past, your character, or
your behavior that might give you a disadvantage.

Now it’s a liability.

* ensconced :misc:
[2021-02-22 Thu 11:34]

If you ensconce yourself somewhere, you settle in for quite a while,
such as when you're home with the flu and ensconce yourself on the
couch with the remote control, tissues, your phone, and a big glass of
orange juice.

Ensconce dates to the 1580s, when it literally meant "to cover with a
fort." It isn't quite clear whether the word can be traced to French
or Dutch, which has a word schans that describes "earthwork." Today,
you don't need a protective structure like a fort in order to be
ensconced, but the idea of being surrounded is key to the word's
meaning.

At one end of the big barn, on a sort of raised platform,
Major was already ensconced on his bed of straw, under a
lantern which hung from a beam.
* hoofs :misc:
[2021-02-22 Thu 11:36]

A foot is to a human what a hoof is to a horse, a goat, or a giraffe.
Each hoof protects the animal and helps it to walk and run.

A hoof is made of keratin, just like your fingernails, but it tends to
be thicker and harder since it has to bear the weight of the animal.
Hoof can also be a verb that, surprisingly enough, applies to humans.
Maybe you have offered someone a ride, only to be told, "No, I think
I'll just hoof it," meaning walk or otherwise go on foot. Hoof is
sometimes substituted for dance if the person doing it is getting
paid.

The hens
perched themselves on the window-sills, the pigeons
fluttered up to the rafters, the sheep and cows lay down
behind the pigs and began to chew the cud.The two
cart-horses, Boxer and Clover, came in together, walking
very slowly and setting down their vast hairy hoofs with
great care lest there should be some small animal
concealed in the straw.
* concealed :misc:
[2021-02-22 Thu 11:36]

If something's concealed, it's out of sight. People may have concealed
motives for carrying concealed weapons.

This is a word for the many things people like to hide. If the
government has a secret agenda, they have a concealed agenda they
don't want anyone to know. Magicians use many concealed objects and
people to do their tricks. Someone might win a poker game because they
concealed their emotions. A concealed ace up your sleeve will help
too. Once something is revealed—like an affair or a scandal—it's no
longer concealed.

The hens
perched themselves on the window-sills, the pigeons
fluttered up to the rafters, the sheep and cows lay down
behind the pigs and began to chew the cud.The two
cart-horses, Boxer and Clover, came in together, walking
very slowly and setting down their vast hairy hoofs with
great care lest there should be some small animal
concealed in the straw.
* stout :misc:
[2021-02-22 Thu 11:37]

Stout describes something fat, dependable, or rugged. If someone calls
you stout, ask them exactly what they mean before bursting into tears
and skipping dinner. It could be a compliment!

Most supermodels would not want to be described as stout, which is
often a nicer way of saying "fat." But a little teapot doesn't mind
being "short and stout." Something stout is dependable, too, like your
favorite snow boots that keep your feet dry winter after winter. Since
it also means "sturdy," if you call that supermodel stout when he
prances through the finish line of a triathlon, he'll just pump his
fist in agreement.

Clover was a stout motherly mare
approaching middle life, who had never quite got her
figure back after her fourth foal.
* mare :misc:
[2021-02-22 Thu 11:37]

A mare is an adult female horse. If your new horse is a filly, a
female baby horse, she'll grow up to be a mare.

Horse experts have many words to distinguish the age and sex of their
animals, from foal, for any newborn horse, to stallion, a full grown
male, to colt, a young male horse. Mares are known for being more
easy-going than stallions, and because they're equally fast and
powerful, they're as likely as males to be used for racing. Another
meaning of mare ("sea" in Latin) is "dark areas of the moon," once
believed to be actual oceans.

Clover was a stout motherly mare
approaching middle life, who had never quite got her
figure back after her fourth foal.
* foal :misc:
[2021-02-22 Thu 11:37]

A foal is a baby horse. Most horses give birth to only one foal at a
time, though occasionally they have two.

You can use the word foal for a horse that's younger than one year old
— after turning one, a foal becomes a yearling. Foals can be either
male, also called a colt, or female, also called a filly. When a mare,
or adult female horse, has a baby, you can say she foals. The Old
English root word, fola, means "foal" or "colt."

Clover was a stout motherly mare
approaching middle life, who had never quite got her
figure back after her fourth foal.
* mane :misc:
[2021-02-22 Thu 11:41]

Use the noun mane when you talk about an animal's ruff of neck hair. A
male lion's mane can be very fluffy and dramatic.

A mane is a patch or growth of long hair, whether it's found on a lion
or down the neck of a pony, or even on a human's head. You might
stroke a horse's mane while sitting on its back, or you could
compliment your friend on her beautiful mane of long blonde hair. The
Old English root is manu, which comes from a Proto-Indo-European root,
mon, which means "neck" or "nape of the neck."

She
took a place near the front and began flirting her white
mane, hoping to draw attention to the red ribbons it was
plaited with.
* contentedly :misc:
[2021-02-22 Thu 11:42]



nil

Last of all came the cat, who looked round,
as usual, for the warmest place, and finally squeezed
herself in between Boxer and Clover; there she purred
contentedly throughout Major’s speech without listening
to a word of what he was saying.
* hideous :misc:
[2021-02-22 Thu 11:44]

Hideous is a word that means extremely ugly. Anything or anybody that
is painful — and a little scary — to look at is hideous.

This is a strong word. If you have a zit on your nose, you might feel
hideous, but you're probably not. Only terrifyingly ugly people and
things are truly hideous. In horror movies, the special effects team
tries to make the monsters hideous, so moviegoers will be scared. This
word can also be a more general term for awful things. For example,
you could say the effects of a concussion are so severe that they're
hideous.

We are born, we are given just so much food as
will keep the breath in our bodies, and those of us who
are capable of it are forced to work to the last atom of
our strength; and the very instant that our usefulness
has come to an end we are slaughtered with hideous
cruelty.
* slaughtered :misc:
[2021-02-22 Thu 11:44]

Slaughter refers to the killing of large numbers of animals or people.
When cattle are old enough, they're sent to slaughter and their meat
is processed and shipped to stores.

The noun slaughter was first used in the 1300s and comes from the Old
Norse word slahtr, which also described the mass killing of animals or
people. A verb form came along later, in the 1530s. You might hear
slaughter used to describe the killing of large numbers of people in a
war, a genocide, or a massacre. It also can be used figuratively to
describe a crushing defeat, like the slaughter of your basketball team
by your bitter rivals.

We are born, we are given just so much food as
will keep the breath in our bodies, and those of us who
are capable of it are forced to work to the last atom of
our strength; and the very instant that our usefulness
has come to an end we are slaughtered with hideous
cruelty.

* confinements :misc:
[2021-02-26 Fri 10:56]

If you're dealing with confinement to a jail cell, or your classroom,
or the broom closet, you're stuck there and you can't leave.
Confinement means you're being held and you can't move freely.

Confinement doesn't have to be punishment. If you've got a contagious
disease, your doctor may recommend confinement to your hospital room.
Puppies sometimes prefer confinement in a crate to sleeping in an open
room. You may also come across an old-fashioned use of the word
confinement, referring to a woman in childbirth, which goes back to
when women retired to their rooms to give birth and recuperate.
Confinement contains the Latin root finis, "end, limit” — confinement
certainly is limiting.

In
return for your four confinements and all your labour in
the fields, what have you ever had except your bare
rations and a stall?
* bare :misc:
[2021-02-26 Fri 10:57]

When you kick off your shoes to walk on the beach, you are enjoying
the feeling of your bare feet in the warm sand. The adjective bare
describes something or someone that is naked or unclothed.

Bare can be used in many different ways: to describe the inside of
your nearly-empty refrigerator, an uncarpeted floor, or your
unadorned, sparsely decorated bedroom. The word bare can also be used
as a verb meaning "to uncover or expose." When you reveal deep truths
about yourself to another person — imagine confessing your passion for
stamp collecting to a girl you like — you "bare your soul."

In
return for your four confinements and all your labour in
the fields, what have you ever had except your bare
rations and a stall?
* grumble :misc:
[2021-02-26 Fri 10:57]

When you grumble, you complain about something clearly but quietly, in
a low mutter. Some people grumble a hundred times a day, about
everything from the weather to the traffic to their bad luck at
bowling.

The verb grumble is a great example of onomatopoeia, a word that
sounds just like what it means. When you say "grumble" out loud,
you're practically already grumbling about something. The origin of
grumble is the Middle French word grommeler, or "mutter through the
teeth." Just think about the things in life that make you want to
mutter through your teeth and you'll probably start to grumble.

For myself I do not grumble,
for I am one of the lucky ones.
* vivacious :misc:
[2021-02-26 Fri 11:13]

A vivacious person is lively and spirited: a vivacious dancer might do
a back-flip off the wall and then jump into the arms of her partner.

Some people are just naturally fun to be around; they sparkle, they
animate any group they're part of, they're full of life. That, in
fact, is the root meaning of the word: it's from Latin vivere "to
live." It has more of a sense of playfulness than lively or animated.
Even the most sedentary slob can feel revitalized in the presence of a
vivacious soul.

Snowball was a more vivacious pig than Napoleon, quicker in speech and
past.more inventive, but was not considered to have the same depth of
past.character.

