-*- coding: utf-8 -*-


* irascible :misc:
[2021-03-01 Mon 15:49]

If you're irascible, you get angry easily — perhaps blowing up in rage
when someone brushes into you.

Irascible comes from the Latin root ira, which means "anger" or
"rage," the same root that gives us the word ire, "anger." The -sc in
the middle of irascible, means "becoming," so irascible doesn't just
mean you're angry — it's got action built into it. If you're looking
for a fight most of the time, then you're irascible — ready for the
spark that's going to set you on fire.

He begins to get more irascible and one day while his wife is out
he decides that he's going to collect all his childhood mementos the
memories of his youth and burn them as if he's trying to eradicate his
past.

* heir :misc:
[2021-03-03 Tue 17:07]

If your grandfather leaves his candy factory to you in his will, it
means you're the heir to the family candy business, and after your
grandfather dies, you will inherit the factory.

When you're named in a will or are legally entitled to inherit
something, you're an heir. You can be the heir to someone's money,
business, or title; in a monarchy, the king or queen's oldest son is
usually the heir to the throne. The word heir isn't pronounced like
"hair," but instead has a silent h and sounds like "air."

The bats weren't surprised you to know that some
men blamed their own midlife crises on the menopause, their wife's
menopause as well so let me go back to Reginald Perrin.

*  wee                                                                 :misc:
[2021-03-03 Wed 12:54]

I had a flashback to when I was a wee girl.

* presbyterian                                                         :misc:
[2021-03-03 Wed 13:03]

Not even the one that says, "Did you know that Britney Spears is an
anagram for Presbyterian?".

* hourglass :misc:
[2021-03-03 Wed 13:10]

So it's kind of like an hourglass effect: when you're young you're
great at being yourself; when you're old you're great at being
yourself; but the bit in the middle is sometimes the most problematic.

* inferiority :misc:
[2021-03-03 Wed 13:11]

Inferiority is the quality of being worse than other things or people.

You know how some movies are terrible — inferior — compared to other
movies? You've noticed the inferiority of those films. Inferiority is
a quality possessed by people and things that are not as good as
others. To a king, the common people are defined by their inferiority.
Most people agree on the inferiority of a TV dinner to a home-cooked
meal. When someone feels like they are always worse off than others,
they have an inferiority complex. Inferiority is the opposite of
superiority.

If you've got an inferiority complex you suffer from an over-modest
self-regard.
* vantage :misc:
[2021-03-03 Wed 13:15]

A vantage is a really good place from which to survey a scene. You
might find that the roof of the house offers an excellent vantage from
which to drop water balloons on your kid brother’s head.

Vantage is a variation of advantage, but when we use vantage we’re
almost always talking about a position, not just general superiority.
If you had extra tutoring for a big exam, you would have the advantage
over a classmate who didn’t. But if your seat for the test allowed you
to see the answer sheet lying on the desk, well then you would have a
superior vantage — not that you would take advantage of that, of
course!

Interiority is entirely unrelative, so to operate from this position
of interiority, it's like a perceptual vantage point.
