-*- coding: utf-8 -*-


* epistemic :Elephant:
[2022-01-11 Tue 10:56]



nil

Rationalization is a kind of epistemic forgery, if you will. When others ask us to
give reasons for our behavior, they’re asking about our true, underlying motives. So
when we rationalize or confabulate, we’re handing out counterfeit reasons (see Box
5). We’re presenting them as an honest account of our mental machinations, when in
fact they’re made up from scratch.
* counterfeit :Elephant:
[2022-01-11 Tue 10:58]

A counterfeit is a fake or a forgery. If you painted an uncanny copy
of the "Mona Lisa" and tried to pass it off as the original, you'd
have a counterfeit on your hands.

An exact imitation of anything — a work of art, a ten dollar bill — is
a counterfeit, and the act of creating the fake copy is the verb to
counterfeit.  You can also describe the forgery using the adjective
form of counterfeit: a counterfeit Rolex watch. In Old French, the
word contre, "counter or against", together with the word faire, "to
make," joined together to mean "to make in imitation," which led to
our counterfeit.

Rationalization is a kind of epistemic forgery, if you will. When others ask us to
give reasons for our behavior, they’re asking about our true, underlying motives. So
when we rationalize or confabulate, we’re handing out counterfeit reasons (see Box
5). We’re presenting them as an honest account of our mental machinations, when in
fact they’re made up from scratch.
* legitimate :Elephant:
[2022-01-11 Tue 11:02]

Something legitimate is the real deal — according to the law.

Legitimate has other variations of meaning. To legitimate something is
to make it legal, either by passing a law or publicly recognizing it
as in accordance with the law. A government can be legitimized by
being invited to world talks, or a movie by winning a prestigious
award.

Why did you vote for Barack Obama? Why are you a Christian? Each of these questions
demands a reason, and in most cases we dutifully oblige. But how many of our
explanations are legitimate, and how many are counterfeit? Just how pervasive is our
tendency to rationalize?
* tenuous :Elephant:
[2022-01-11 Tue 11:11]

If something is tenuous it's thin, either literally or
metaphorically. If you try to learn a complicated mathematical concept
by cramming for 45 minutes, you will have a tenuous grasp of that
concept, at best.

Tenuous comes from the Latin word tenuis, for thin, and is related to
our word tender. Something can be physically tenuous, like a spiderweb
or ice on a pond. We more often use it in a metaphorical sense, to
talk about weak ideas. Tenuous arguments won't win any debate
tournaments. Synonyms for tenuous, also used physically or
metaphorically, are flimsy and shaky.

Well, what Gazzaniga concludes from his years of research, including later work on
healthy patients, is that all human brains contain a system he calls the
“interpreter module.”9 The job of this module is to interpret or make sense of our
experiences by constructing explanations: stories that integrate information about
the past and present, and about oneself and the outside world. This interpreter
works to the best of its abilities given the information available to it. So in
whole-brained patients, when information is flowing freely between the two
hemispheres, the explanations produced by the interpreter typically make a lot of
sense. But when the information flow breaks down, whether because of brain damage or
any other reason, the interpreter is forced to weave more tenuous, inventive
explanations, or even whole-cloth fabrications.
* hazardous :Elephant:
[2022-01-11 Tue 11:37]

The noun "hazard" means something dangerous, and the adjective
hazardous refers to anything that involves danger. A golf course with
lots of sand traps is especially hazardous for golfers. That's why
those traps are called hazards.

If your car blows a tire in the middle of the night, make sure to turn
on your hazard lights. Being invisible to other drivers is hazardous
to everyone, especially yourself. Life is, by definition,
hazardous. It's full of dangers, both obvious and
otherwise. Acknowledge that fact and keep going anyway. If you spend
all your time focusing on what's hazardous, you end up missing all the
wonderful things in life.

This is what makes the role of press secretary so hazardous—epistemically if not
also morally. It’s structured to deliver counterfeit explanations, but also to make
those explanations hard to detect, which is as close as you can get without actually
lying.
* judicious :Elephant:
[2022-01-11 Tue 11:41]

If you're judicious, you've got a good head on your shoulders and make
good decisions. Humpty Dumpty's decision to sit on a wall? NOT
judicious.

As its sound implies, judicious comes from the same Latin word from
which we get judge and judiciary, and not surprisingly a judicious
decision is one that only comes after all sides have been weighed up
and opposing points of view taken into consideration. Judicious
decisions are never split-second decisions.

This realization flies in the face of common sense. In everyday life, there’s a
strong bias toward treating the self as the mind’s ultimate decision-maker—the
iron-fisted monarch, or what Dennett calls the mind’s Boss or Central Executive.12
As Harry Truman said about his presidency, “The buck stops here”—and we often
imagine the same is true of the self. But the conclusion from the past 40 years of
social psychology is that the self acts less like an autocrat and more like a press
secretary. In many ways, its job—our job—isn’t to make decisions, but simply to
defend them. “You are not the king of your brain,” says Steven Kaas. “You are the
creepy guy standing next to the king going, ‘A most judicious choice, sire.’ “
* upshot :Elephant:
[2022-01-11 Tue 11:45]

The upshot of an action is the end result, whatever happens last as a
consequence of the original action.  The upshot of reading this
sentence is that you will understand what the word upshot means.

In the 16th century, the last arrow launched in an archery competition
was called the upshot.  Like that final arrow, the upshot is the
conclusion, the outcome.  Sure, you can eat ice cream really fast, but
the upshot is that you’ll have a brain freeze.  The upshot of eating
ice cream slowly is that it will melt.  Decisions, decisions.

The upshot is that every time we give a reason, there’s a risk we’re just making
things up. Every “because” clause, every answer to a “Why?” question, every
justification or explanation of a motive—every one of these is suspect. Not all will
turn out to be rationalizations, but any of them could be, and a great many are.* stall                                                            :Elephant:
[2022-01-12 Wed 11:41]

Instead these toddlers simply don’t want to go to sleep—that’s their
true motive—and they’re using “potty” as a bedtime stalling
tactic. It’s an excuse, a pretext, a counterfeit reason.
* commensurate                                                     :Elephant:
[2022-01-12 Wed 11:42]

The word commensurate has to do with things that are similar in size
and therefore appropriate. Many people think the death penalty is a
commensurate punishment for murder. In other words, the penalty fits
the crime.

When things are commensurate, they're fair, appropriate, and the right
size. If you got a ticket for jaywalking, you shouldn't get ten years
in prison — that penalty is not commensurate with the crime. The word
commensurate is usually followed by with or to; one thing is
commensurate with or to another.

Adults, of course, are more cunning about their counterfeit reasons,
and it’s commensurately harder to catch them in the act.
* plausible :Elephant:
[2022-01-12 Wed 11:43]

If something is plausible, it's reasonable or believable. Things that
are plausible could easily happen. A woman becoming President is very
plausible. A giraffe becoming President is not.

Plausible things are not far-fetched at all. Things in fantasy stories
— such as wizards, dragons, and unicorns — are not plausible. On the
other hand, some things in science fiction stories might be plausible:
who knows where spaceships will eventually go? If something really
seems like it could happen, then it's plausible. One of the many
tricky parts of life is figuring out what's plausible and what's not.

Adult Press Secretaries are highly trained professionals, their skills
honed through years of hard experience; above all, they know how to
give rationalizations that are plausible.
* accuse :Elephant:
[2022-01-12 Wed 11:46]

If you charge someone with misdeeds or misconduct, you accuse that
person. If the last piece of devil's food cake is missing, your sister
may accuse you of eating it — especially if you have chocolate on your
mouth.

The verb accuse comes from the Latin word accusare, which itself is
formed from the roots ad, meaning toward, and causa, reason or
lawsuit. "Cause," "excuse," and even "ruse" are all from that same
root word. Today, if you're accused of a crime, you may still be
headed toward a lawsuit. However, to accuse someone of a crime doesn't
necessarily make them guilty — plenty of people have been falsely
accused.

To identify other examples, we’ll have to relax our standards of
proof. It’s hard to accuse a particular reason of being
counterfeit—that’s the whole point; we can never be perfectly
certain—but here we appeal to our readers’ common sense and lived
experience.
