-*- coding: utf-8 -*-


* preposterous :Stupidity:
[2022-02-02 Wed 11:51]

To a vegetarian, the idea of eating a 52-ounce T-bone steak would seem
preposterous — absolutely absurd.

When the word preposterous was first used, it meant reversing the
normal order of things — putting what was last first, and vice
versa. Imagine putting on your underwear over your pants and you'll
see that there's a kind of absurdity in something that's backwards,
which is why preposterous came to mean "ridiculous." The word is often
used as part of an exclamation: a chef who is asked to cook with
nothing but jelly beans might exclaim, "That's preposterous!"

Our daily life is mostly made up of cases in which we lose money
and/or time and/or energy and/or appetite, cheerfulness, and good
health because of the improbable action of some preposterous creature
who has nothing to gain and indeed gains nothing from causing us
embarrassment, difficulties or harm.
* proclivity :Stupidity:
[2022-02-02 Wed 11:52]

A proclivity is a natural tendency to like something, such as your
sister's proclivity for restaurants that serve hot, spicy food.

When you have a proclivity, it feels automatic — you like what you
like; you don't even have to think about it. The origin of the word
proclivity supports this feeling. Proclivity comes from the Latin word
proclivis, which literally means "sloping forward." You slide toward a
proclivity — no effort is needed. You just give in to it, since you're
headed in that direction naturally.

Most people do not act consistently. Under certain circumstances a given person
acts intelligently and under different circumstances the same person will act
helplessly. The only important exception to the rule is represented by the stupid
people, who normally show a strong proclivity toward perfect consistency in all
fields of human endeavors.
* butts :Stupidity:
[2022-02-02 Wed 12:17]

Your butt is your buttocks, your tush, your rear end. Saying butt is
more childish than offensive.

Butt is a four-letter word, though using it won't get you in much
trouble — It's much less offensive than ass. It also has plenty of
other meanings, like butting into a conversation (interrupting it) or
the butt of a gun (the thick end). If you make fun of someone, they
are the butt of your jokes. The used end of a cigarette is called a
butt, too. But you'll hear it more often in phrases like "Get your
butt in here!"

The other kind of sensitive information our brains “leak” through laughter is how
we feel toward those who become the objects of our comedy, the butts of our jokes.
* pinprick :Stupidity:
[2022-02-02 Wed 12:18]

A pinprick is what it sounds like — a tiny prick or hole created by
something as small as a pin. People also use this word to represent
something that is as annoying or irritating as the feeling of being
pricked by a pin.

The word pinprick can evoke the image of something so tiny that it is
the size of a pinprick, like seeing the stars in the sky as pinpricks
of light. And then there is the sensation of a pinprick that is
annoying and quick. This latter meaning has a metaphorical use, like
when something refers to a tiny problem as a pinprick in comparison to
more weighty troubles. No matter how you experience it, a pinprick is
tiny. Don't sweat the pinpricks in life.

Actually two variables are important here. The first is, simply, how much pain is
involved. We’re more likely to laugh at a pinprick than at a broken bone, and more
likely to laugh at a broken bone than a violent death.
* condemn :Stupidity:
[2022-02-02 Wed 12:23]

You can condemn, or openly criticize, someone who is behaving
inappropriately. If you are an animal rights activist, you would
probably condemn someone for wearing fur.

Condemn originally comes, through Old French, from the Latin word
condemnāre, "to sentence, condemn." You may see politicians condemn
each other in political ads during a campaign in hopes of improving
their chances of winning an election. You also might hear of a convict
being "condemned to death." In this sense of the word, to condemn
still carries on its Latin meaning of "to sentence."

Now, we need to be careful how we moralize about what these popular girls are
doing. It would be easy to condemn them for laughing at the misfortune of another
human being. But that’s not the real problem; we all laugh at other people in this
way. Consider the Darwin Awards, a website that “commemorates those who improve our
gene pool by removing themselves from it.” It’s a catalog of gruesome deaths
(usually involving irony, stupidity, or both), played entirely for laughs. But
although the accidents described in the Darwin Awards are vastly more serious than
Maggie’s stumble, we find it funny because the victims are strangers, and thus
their pain doesn’t register as serious for us. For better or worse, this is how
we’re wired.
* odious :Stupidity:
[2022-02-02 Wed 12:24]

If something is odious, it's hateful. If you become a historian of
slavery, you'll learn all the details of that odious trade.

Odious is from the Latin noun odium, which means hatred. It is a
strong word, so don't call someone odious unless you want to accuse
someone of being loathsome or vile. Actions can also be called
odious. A typical use is Shakespeare's in Othello: "You told a lie, an
odious damned lie." Some synonyms are hateful, contemptible,
detestable, and abominable.

To give an even more disturbing example, consider how often we joke and laugh about
prison rape—“Don’t drop the soap!” for example. On sober reflection, we may realize
these jokes are distasteful, if not morally odious; rape should be universally
condemned, no matter who the victims are. And yet, when the victims are convicted
criminals, our brains don’t send us the same “danger!” signals that they would send
if the victims were innocent citizens. People behind bars are remote, both socially
and psychologically, and we tend not to empathize with them to the same degree we
empathize with our friends and neighbors.
* preemptively :Stupidity:
[2022-02-02 Wed 12:27]

A preemptive action is made to keep some other action from being
taken.  Before you could be accused of eating the whole cake, you
decided to make a preemptive apology, which was met with awkward
silence.

Tired of being disturbed by your roommate's loud music, your
preemptive strike was to crank up your favorite opera as soon as you
arrived home.  Unfortunately, he'd already made a preemptive strike of
his own by borrowing your stereo.  Don't confuse preemptive with
peremptory, a word meaning “arrogant.” You don't have to be arrogant
to make a preemptive move, just cautious.

If we insist on moralizing about what the popular girls are doing, we should focus
on the fact that their laughter itself contributes to further suffering. Most of us
strive to laugh only in situations where our laughter is harmless, or even (on
occasion) helpful. When a friend spills wine on her shirt, we want to laugh,
ideally, only after she’s given us the “all clear” by laughing herself. Or we might
take a risk and laugh preemptively, hoping that our laughter will help her to
appreciate the non-seriousness of the situation. But such laughter needs to be very
gentle indeed, and we’ll want to back off if she shows any sign of taking offense,
lest our laughter be the cause of further suffering.
* affinity :Stupidity:
[2022-02-02 Wed 12:29]

If you get along with someone very well, you have an affinity with
them. Sometimes opposites attract, so you might feel a strange
affinity to someone who is seemingly very different from you.

When you are attracted to someone or something a great deal, we say
that you have an affinity, a natural connection. Likewise, scientists
use affinity to describe organisms that are alike or resemble each
other. Interestingly, the Middle English word, affinite, originally
applied to people who were connected or related by marriage, rather
than by biology.

Teasing hinges on a similar dynamic. To tease is to provoke a small amount of
suffering in a playful manner, often accompanied by laughter. The interesting cases
lie between good-natured teasing, which strengthens a relationship, and
mean-spirited teasing, which weakens it. Teasing is good-natured when it provokes
only light suffering, and when the offense is offset by enough warmth and affinity
that the person being teased generally feels more loved than ridiculed. The fact
that it’s hard to tease strangers—because there’s no preexisting warmth to help
mitigate the offense—means that the people we tease are necessarily close to us.
* involuntary :Stupidity:
[2022-02-02 Wed 12:33]

Involuntary describes a reflex or action done without conscious
control or will — like a blink, a sneeze, a yawn, or “the giggles.”

If you volunteered to do it, it’s voluntary. If you didn’t volunteer,
but you find yourself doing it anyway, it’s involuntary. This can go
for the involuntary hiccups you wrestle with on your blind date, as
well as the involuntary task you do at your manager’s
insistence. Involuntary gets a lot of blame, but something that is
involuntary is not necessarily bad: Breathing is involuntary, but you
would probably do it anyway if given the choice.

It’s worth reiterating that our brains do most of this on autopilot. We rarely make
conscious calculations about the strength of our relationships, or how much
suffering is too much to laugh at—but our brains perform these calculations all the
same, automatically and unconsciously. As Provine points out, it’s precisely
because laughter is involuntary that it’s such a powerful probe into social
relationships.
* disparaging :Dahl:
[2022-02-16 Wed 02:23]

When you are disparaging, you express negative, low opinions in order
to lower someone's reputation. Your friend will probably not
appreciate it if you make disparaging comments about his girlfriend.

In its original use, disparage meant "to marry unequally," and it was
considered a disgrace if a very wealthy son married, say, the kitchen
maid. Nowadays we use disparaging for any derogatory or belittling
expression or comment. If you just won an Olympic gold medal, it's
just rude and unnecessary to be disparaging about the silver medalist
in an interview. Making disparaging remarks about your friend's
cooking is unlikely to result in better food — he'll just get mad.

It's a bit disparaging.
* brash :Dahl:
[2022-02-16 Wed 02:23]

Brash sounds like what it means: harsh, loud, and maybe a little
rude. Sometimes that’s good, like when you have a serious rash on your
face and give Aunt Nell a brash warning before she showers you with
kisses.

There's nothing warm and fuzzy about brash. New Yorkers are sometimes
thought of as the poster children for brash behavior: they can be bold
and brazen. Pushy even. You might find brashness offensive, or maybe
you think it's refreshingly direct. If you're a cab driver, a tough
exterior might be useful, but being brash probably won’t advance your
career if you work in a hotel, where you’re supposed to be polite and
welcoming.

Sort of very brash way of describing it
that he does.
* rogue :Dahl:
[2022-02-16 Wed 02:25]

A rogue is a sneaky person who has tricks up his sleeve, not like a
magician, but like someone who would steal your wallet or cheat at
cards.

Dishonesty won’t get you far in life, unless you are a rogue who
survives by lying and exploiting others.  The word comes from the
Latin rogare, which means “beg,” and while some rogues dress like
beggars to get your money, anyone who deceives is a rogue, like the
presidents of corrupt corporations who steal from their employees, or
that rogue Uncle Marvin who promises you chocolate for washing his
car, but afterward tells you he has no chocolate.  That rogue!

You put that into investments, maybe in the stock market, if you're
particularly rogue.