-*- coding: utf-8 -*-


* epistemic :Elephant:
[2022-01-11 Tue 10:56]



nil

Rationalization is a kind of epistemic forgery, if you will. When others ask us to
give reasons for our behavior, they’re asking about our true, underlying motives. So
when we rationalize or confabulate, we’re handing out counterfeit reasons (see Box
5). We’re presenting them as an honest account of our mental machinations, when in
fact they’re made up from scratch.
* counterfeit :Elephant:
[2022-01-11 Tue 10:58]

A counterfeit is a fake or a forgery. If you painted an uncanny copy
of the "Mona Lisa" and tried to pass it off as the original, you'd
have a counterfeit on your hands.

An exact imitation of anything — a work of art, a ten dollar bill — is
a counterfeit, and the act of creating the fake copy is the verb to
counterfeit.  You can also describe the forgery using the adjective
form of counterfeit: a counterfeit Rolex watch. In Old French, the
word contre, "counter or against", together with the word faire, "to
make," joined together to mean "to make in imitation," which led to
our counterfeit.

Rationalization is a kind of epistemic forgery, if you will. When others ask us to
give reasons for our behavior, they’re asking about our true, underlying motives. So
when we rationalize or confabulate, we’re handing out counterfeit reasons (see Box
5). We’re presenting them as an honest account of our mental machinations, when in
fact they’re made up from scratch.
* legitimate :Elephant:
[2022-01-11 Tue 11:02]

Something legitimate is the real deal — according to the law.

Legitimate has other variations of meaning. To legitimate something is
to make it legal, either by passing a law or publicly recognizing it
as in accordance with the law. A government can be legitimized by
being invited to world talks, or a movie by winning a prestigious
award.

Why did you vote for Barack Obama? Why are you a Christian? Each of these questions
demands a reason, and in most cases we dutifully oblige. But how many of our
explanations are legitimate, and how many are counterfeit? Just how pervasive is our
tendency to rationalize?
* tenuous :Elephant:
[2022-01-11 Tue 11:11]

If something is tenuous it's thin, either literally or
metaphorically. If you try to learn a complicated mathematical concept
by cramming for 45 minutes, you will have a tenuous grasp of that
concept, at best.

Tenuous comes from the Latin word tenuis, for thin, and is related to
our word tender. Something can be physically tenuous, like a spiderweb
or ice on a pond. We more often use it in a metaphorical sense, to
talk about weak ideas. Tenuous arguments won't win any debate
tournaments. Synonyms for tenuous, also used physically or
metaphorically, are flimsy and shaky.

Well, what Gazzaniga concludes from his years of research, including later work on
healthy patients, is that all human brains contain a system he calls the
“interpreter module.”9 The job of this module is to interpret or make sense of our
experiences by constructing explanations: stories that integrate information about
the past and present, and about oneself and the outside world. This interpreter
works to the best of its abilities given the information available to it. So in
whole-brained patients, when information is flowing freely between the two
hemispheres, the explanations produced by the interpreter typically make a lot of
sense. But when the information flow breaks down, whether because of brain damage or
any other reason, the interpreter is forced to weave more tenuous, inventive
explanations, or even whole-cloth fabrications.
* hazardous :Elephant:
[2022-01-11 Tue 11:37]

The noun "hazard" means something dangerous, and the adjective
hazardous refers to anything that involves danger. A golf course with
lots of sand traps is especially hazardous for golfers. That's why
those traps are called hazards.

If your car blows a tire in the middle of the night, make sure to turn
on your hazard lights. Being invisible to other drivers is hazardous
to everyone, especially yourself. Life is, by definition,
hazardous. It's full of dangers, both obvious and
otherwise. Acknowledge that fact and keep going anyway. If you spend
all your time focusing on what's hazardous, you end up missing all the
wonderful things in life.

This is what makes the role of press secretary so hazardous—epistemically if not
also morally. It’s structured to deliver counterfeit explanations, but also to make
those explanations hard to detect, which is as close as you can get without actually
lying.
* judicious :Elephant:
[2022-01-11 Tue 11:41]

If you're judicious, you've got a good head on your shoulders and make
good decisions. Humpty Dumpty's decision to sit on a wall? NOT
judicious.

As its sound implies, judicious comes from the same Latin word from
which we get judge and judiciary, and not surprisingly a judicious
decision is one that only comes after all sides have been weighed up
and opposing points of view taken into consideration. Judicious
decisions are never split-second decisions.

This realization flies in the face of common sense. In everyday life, there’s a
strong bias toward treating the self as the mind’s ultimate decision-maker—the
iron-fisted monarch, or what Dennett calls the mind’s Boss or Central Executive.12
As Harry Truman said about his presidency, “The buck stops here”—and we often
imagine the same is true of the self. But the conclusion from the past 40 years of
social psychology is that the self acts less like an autocrat and more like a press
secretary. In many ways, its job—our job—isn’t to make decisions, but simply to
defend them. “You are not the king of your brain,” says Steven Kaas. “You are the
creepy guy standing next to the king going, ‘A most judicious choice, sire.’ “
* upshot :Elephant:
[2022-01-11 Tue 11:45]

The upshot of an action is the end result, whatever happens last as a
consequence of the original action.  The upshot of reading this
sentence is that you will understand what the word upshot means.

In the 16th century, the last arrow launched in an archery competition
was called the upshot.  Like that final arrow, the upshot is the
conclusion, the outcome.  Sure, you can eat ice cream really fast, but
the upshot is that you’ll have a brain freeze.  The upshot of eating
ice cream slowly is that it will melt.  Decisions, decisions.

The upshot is that every time we give a reason, there’s a risk we’re just making
things up. Every “because” clause, every answer to a “Why?” question, every
justification or explanation of a motive—every one of these is suspect. Not all will
turn out to be rationalizations, but any of them could be, and a great many are.
* heed :DarkPersuasion:
[2022-01-12 Wed 10:45]

Heed is an old word, meaning "to listen to and follow." It can also be
used as a noun: "Take heed of my instructions," said the wizard, "for
the magic potion will work only by the light of the full moon."

The most common use of heed is with warnings, as in "You'd better heed
my advice, or you'll be in serious trouble!" The word derives from Old
English hēdan and is related to the Dutch hoeden and German hüten —
from Germanic cultures where fairy tales with mysterious warnings and
magical consequences abound.

. For many persons have such strength of body and soul that they heed pain very
little, so that there is no means of obtaining the truth from them . . . while
others are so susceptible to pain that they will tell any lie rather than suffer
it.”3
* threat :DarkPersuasion:
[2022-01-12 Wed 10:48]

A threat is an impending danger that has the potential to cause
serious harm — it just hasn't done so yet. In The Wizard of Oz, the
huge tornado that spiraled across the Kansas countryside posed a
threat to the little girl named Dorothy in its path.

If a huge thug carrying an equally huge knife approaches you in a dark
alley and demands, "Your wallet or your life," you feel the imminent
threat. Your safety is at risk, especially if you don't hand over that
wallet. Threats don't have to be big and scary, though. An extra-large
slice of chocolate cake isn't armed and dangerous, but it's still a
serious threat to any dieter who's trying to cut calories. Or, you
could see a gray cloud as promising the threat of rain showers.

Interestingly, we have centuries of data teaching us that the threat of torture
works just as well as the physical torture itself, without the mess. So, if one
wants to extract a confession, one could just as well bring in the implements of
torture without actually employing them. The victim tortures himself simply with
his imagination.
* aberrant :DarkPersuasion:
[2022-01-12 Wed 10:50]

Use the adjective aberrant to describe unusual conduct. Sitting in a
bathtub and singing show tunes all day long might be considered
aberrant behavior.

For conduct that departs from the norm, aberrant is at hand to
describe it if you want to set a formal, or even scientific tone to
the discussion. You can put the accent on either the first syllable
(AB-er-ent) or the second (uh-BER-ent); both pronunciations are
acceptable. The Latin root aberrare means "to go astray," from the
prefix ab- "off, away" plus errare "to wander."  Other descendants of
errare in English, like error and errant, have that double -r- and
also refer to something that's either not wanted or not expected.

Rulers commonly cite self-defense to justify torture. Stalin commented that since
“bourgeois intelligence services use methods of physical influence against the
representatives of the Socialist proletariat, . . . why [should] the Socialist
intelligence service be more humanitarian toward the mad agents of the
bourgeoisie?”6 Currently, allegations of torture are met with outright denial,
claims that it was a one-off instance of aberrant behavior, protestations that
the reports were exaggerated, or else justifications that the techniques were not
“real torture.” This issue of “real torture,” incidentally, surfaces repeatedly
when authorities try to decide the degree of guilt or responsibility of an
individual who caved in under the pressures of coercive persuasion. We will
encounter that argument in circumstances as diverse as returning Korean War POWs
in the 1950s and Patricia Hearst’s trial for bank robbery in the 1970s.
* riveting :DarkPersuasion:
[2022-01-12 Wed 10:57]

A rivet is a fastener that holds something closed or down, and
something riveting keeps you glued to your seat and grabs your
attention. Sometimes a movie is so riveting that not even free popcorn
refills can lure you away.

Riveting is an adjective for things that really draw you in, like a
book you read in one sitting or a song you turn up so you can hear
every lyric. Beautiful scenes are riveting, but terrible and ugly
things are also riveting, like the site of an accident you can't stop
looking at. Words from a teacher or actor have a riveting effect when
they're full of impact and interest, and when you exaggerate a story
for your best friend, that's riveting too.

Case histories of torture give vivid evidence of the techniques used to persuade
the victim. Historian Carlo Ginzburg recounts one riveting case from
sixteenth-century Italy. A miller named Menocchio was an eccentric outspoken man
who openly scorned the Church. He held pantheistic beliefs that he shared all too
readily, denied the virgin birth of Jesus, and read prohibited books.
* lapsed :DarkPersuasion:
[2022-01-12 Wed 11:00]

Someone who's lapsed has stopped participating in some activity or
following some particular rules. A lapsed Baptist was raised in the
Baptist church but no longer practices this religion.

If you describe yourself as a lapsed Catholic or a lapsed Hindu, you
once took an active part in your religion and now you don't — in fact,
you may no longer believe. This adjective can also mean "expired,"
like your dog's lapsed license, which ran out months ago and you keep
forgetting to renew. Lapsed comes from the verb lapse, which stems
from either the Latin lapsus, "a slipping and falling," or lapsare,
"to lose one's footing."

His first set of interrogations began on February 7, 1584. Disregarding his
friends’ advice, he incautiously told the Inquisition his beliefs about the
beginning of time: “In my opinion, all was chaos, that is, earth, air, water, and
fire were mixed together; and out of that bulk a mass formed—just as cheese is
made out of milk—and worms appeared in it, and these were the angels. . . . And
among that number of angels, there was also God.” The inquisitors interrogated
him off and on for two years, admonished him to stop blaspheming, and released
him from prison in 1586. However, he continued making imprudent public comments
and was rearrested in 1599 as a lapsed heretic. This time, the interrogation was
unrelenting and months later, he finally conceded that his beliefs were false.
* conceded :DarkPersuasion:
[2022-01-12 Wed 11:00]

If you concede something, you admit that it is true, proper, or
certain — usually in an unwilling way and often in the context of a
competition, as in "At midnight, the candidate finally conceded
defeat."

In its most common senses, a near synonym of concede is acknowledge —
if your mom is pointing out that you need sleep before the test, you
should concede the truth of what she's saying. But another meaning of
concede is to give away or grant something, as when an unpopular
leader is unwilling to concede power. Concede is from Latin concēdere,
from the prefix com-, "completely," plus cēdere, "to go along, grant,
yield." The corresponding noun is concession.

His first set of interrogations began on February 7, 1584. Disregarding his
friends’ advice, he incautiously told the Inquisition his beliefs about the
beginning of time: “In my opinion, all was chaos, that is, earth, air, water, and
fire were mixed together; and out of that bulk a mass formed—just as cheese is
made out of milk—and worms appeared in it, and these were the angels. . . . And
among that number of angels, there was also God.” The inquisitors interrogated
him off and on for two years, admonished him to stop blaspheming, and released
him from prison in 1586. However, he continued making imprudent public comments
and was rearrested in 1599 as a lapsed heretic. This time, the interrogation was
unrelenting and months later, he finally conceded that his beliefs were false.
* inexorable :DarkPersuasion:
[2022-01-12 Wed 11:04]

When a person is inexorable, they're stubborn. When a thing or process
is inexorable, it can't be stopped.

This is a word for people and things that will not change
direction. An inexorable person is hard-headed and cannot be convinced
to change their mind, no matter what. You can also say that a process,
like the progress of a deadly illness, is inexorable because it can't
be stopped. A speeding train with no brakes is inexorable; it's not
stopping till it crashes. When you see the word inexorable, think "No
one's stopping that."

There is a quality to this interrogation that will become familiar as we examine
interrogation techniques employed centuries later in so many countries across the
world. It is the inexorable weight of a glacier pressing slowly forward.
* extirpate :DarkPersuasion:
[2022-01-12 Wed 11:06]

The verb extirpate originally meant "to weed out by the roots." Now
you can use it more broadly to describe getting rid of something
completely.

Use the verb extirpate when you mean to destroy completely or get rid
of completely. If you came home from vacation with your luggage
infested by bedbugs, you will need to call an exterminator to
extirpate them. The dodo bird was extirpated due to hunting and the
introduction of predators in their habitat.

The practices of the Inquisition bore no resemblance to our ideas of law. There
was no presumed innocence; if people were denounced and apprehended, they must
have been guilty. Often, the inquisitors did not even bother to disclose the
reasons for arrest. Instead, they told prisoners to search their conscience for
their sins and confess the truth. Since the defendant’s guilt was already
established (at least to the Church’s satisfaction), the only purpose of an
eventual trial was to extirpate heresy, to obtain a very public confession, and
submit to authority. Stalin’s show trials very much followed in this tradition.
* longed :DarkPersuasion:
[2022-01-12 Wed 11:08]

To strongly crave or desire something is to long for it. No matter how
healthful your diet is, you'll still occasionally long for chocolate,
cookies, and cake.

The adjective long describes something that stretches over a large
distance. If you're trying to avoid a prolonged visit with your crazy
Aunt Martha, you might decide to take the long way to her house. The
adjective long also describes something that lasts for an extended
amount of time. When your Aunt Martha comes to your house, a half-hour
can seem like a long, long time.

Many of the Inquisition’s techniques for eliciting confessions were also used by
the czarist Okhrana (secret police).14 Prisoners were held indefinitely under
severe conditions because interrogators observed that confessions were easier to
obtain when the prisoner was exhausted, confused, and anxious from a combination
of sleep deprivation and malnutrition. While the Okhrana could precisely control
the amount of sleep deprivation in jail, the police also let their anxious
suspects do the work of self-torment at home, thereby continuing the sleep
disruption. Bombarded with contradictory instructions, promises, and threats,
prisoners became increasingly confused. As English psychiatrist William Sargant
observed, the goal was to try to make prisoners feel so guilty that they longed
to be punished to achieve eventual salvation.15 Sargant’s observation harkens
back to the Inquisition, which saw its role as punishing in order to achieve
atonement through public humiliation.16
* harkens :DarkPersuasion:
[2022-01-12 Wed 11:08]



nil

Many of the Inquisition’s techniques for eliciting confessions were also used by
the czarist Okhrana (secret police).14 Prisoners were held indefinitely under
severe conditions because interrogators observed that confessions were easier to
obtain when the prisoner was exhausted, confused, and anxious from a combination
of sleep deprivation and malnutrition. While the Okhrana could precisely control
the amount of sleep deprivation in jail, the police also let their anxious
suspects do the work of self-torment at home, thereby continuing the sleep
disruption. Bombarded with contradictory instructions, promises, and threats,
prisoners became increasingly confused. As English psychiatrist William Sargant
observed, the goal was to try to make prisoners feel so guilty that they longed
to be punished to achieve eventual salvation.15 Sargant’s observation harkens
back to the Inquisition, which saw its role as punishing in order to achieve
atonement through public humiliation.16
* atonement :DarkPersuasion:
[2022-01-12 Wed 11:09]

When you apologize for doing something wrong, that’s an act of
atonement. Many religions have rituals of atonement, such as Yom
Kippur, the Day of Atonement, on which people of the Jewish faith
repent for their sins.

As a religious act, atonement is an effort to make up for wrongdoings
so you can be in harmony with a higher power. Look closely at the
word: you can break it down to "at," "one," and "ment."  Atonement
first appears in English in the 1510s, when it meant "the condition of
being at one (with others)." About ten years later, the word shows up
with a meaning that included “being at one with God.”

Many of the Inquisition’s techniques for eliciting confessions were also used by
the czarist Okhrana (secret police).14 Prisoners were held indefinitely under
severe conditions because interrogators observed that confessions were easier to
obtain when the prisoner was exhausted, confused, and anxious from a combination
of sleep deprivation and malnutrition. While the Okhrana could precisely control
the amount of sleep deprivation in jail, the police also let their anxious
suspects do the work of self-torment at home, thereby continuing the sleep
disruption. Bombarded with contradictory instructions, promises, and threats,
prisoners became increasingly confused. As English psychiatrist William Sargant
observed, the goal was to try to make prisoners feel so guilty that they longed
to be punished to achieve eventual salvation.15 Sargant’s observation harkens
back to the Inquisition, which saw its role as punishing in order to achieve
atonement through public humiliation.16
* incapacitated :Elephant:
[2022-01-12 Wed 11:30]

If you’ve been sick with the flu for a week, barely able to get out of
bed, then you’ve got an idea of what it’s like to be
incapacitated. Incapacitated means "empty of strength," "helpless," or
"powerless."

Incapacitated is an adjective that describes a state where you don’t
have the capacity, or ability, to accomplish anything. When someone
becomes incapacitated, illness or injury is usually to blame. This
adjective is often used in the same manner as disabled. Incapacitated
can also mean "ineligible." For instance, if you are too old to join
the army, then your age makes you incapacitated from serving in the
army.

Our challenge in this chapter, then, as well the rest of the book, is to sneak
past the gatekeeper,15 to catch a glimpse of what’s really going on in the mind,
behind the Press Secretary’s smoke screen. We’ve already seen one fruitful
approach: studying split-brain patients and stroke victims. In such patients, the
Press Secretary is partially incapacitated, cut off from vital sources of
information that would normally be available to it. But there’s another
time-honored approach to sneaking past the gatekeeper—misdirecting it.
* counterfeit :Elephant:
[2022-01-12 Wed 11:34]

A counterfeit is a fake or a forgery. If you painted an uncanny copy
of the "Mona Lisa" and tried to pass it off as the original, you'd
have a counterfeit on your hands.

An exact imitation of anything — a work of art, a ten dollar bill — is
a counterfeit, and the act of creating the fake copy is the verb to
counterfeit.  You can also describe the forgery using the adjective
form of counterfeit: a counterfeit Rolex watch. In Old French, the
word contre, "counter or against", together with the word faire, "to
make," joined together to mean "to make in imitation," which led to
our counterfeit.

Here again, as in the split-brain experiments, we (third parties with privileged
information) know what’s really going on. The subjects simply preferred the
blue-and-yellow box. But because they were asked to evaluate the detergents, and
because they thought the detergents were actually different, their Press
Secretaries were tricked into making up counterfeit explanations.
* stall                                                            :Elephant:
[2022-01-12 Wed 11:41]

Instead these toddlers simply don’t want to go to sleep—that’s their
true motive—and they’re using “potty” as a bedtime stalling
tactic. It’s an excuse, a pretext, a counterfeit reason.
* commensurate                                                     :Elephant:
[2022-01-12 Wed 11:42]

The word commensurate has to do with things that are similar in size
and therefore appropriate. Many people think the death penalty is a
commensurate punishment for murder. In other words, the penalty fits
the crime.

When things are commensurate, they're fair, appropriate, and the right
size. If you got a ticket for jaywalking, you shouldn't get ten years
in prison — that penalty is not commensurate with the crime. The word
commensurate is usually followed by with or to; one thing is
commensurate with or to another.

Adults, of course, are more cunning about their counterfeit reasons,
and it’s commensurately harder to catch them in the act.
* plausible :Elephant:
[2022-01-12 Wed 11:43]

If something is plausible, it's reasonable or believable. Things that
are plausible could easily happen. A woman becoming President is very
plausible. A giraffe becoming President is not.

Plausible things are not far-fetched at all. Things in fantasy stories
— such as wizards, dragons, and unicorns — are not plausible. On the
other hand, some things in science fiction stories might be plausible:
who knows where spaceships will eventually go? If something really
seems like it could happen, then it's plausible. One of the many
tricky parts of life is figuring out what's plausible and what's not.

Adult Press Secretaries are highly trained professionals, their skills
honed through years of hard experience; above all, they know how to
give rationalizations that are plausible.
* accuse :Elephant:
[2022-01-12 Wed 11:46]

If you charge someone with misdeeds or misconduct, you accuse that
person. If the last piece of devil's food cake is missing, your sister
may accuse you of eating it — especially if you have chocolate on your
mouth.

The verb accuse comes from the Latin word accusare, which itself is
formed from the roots ad, meaning toward, and causa, reason or
lawsuit. "Cause," "excuse," and even "ruse" are all from that same
root word. Today, if you're accused of a crime, you may still be
headed toward a lawsuit. However, to accuse someone of a crime doesn't
necessarily make them guilty — plenty of people have been falsely
accused.

To identify other examples, we’ll have to relax our standards of
proof. It’s hard to accuse a particular reason of being
counterfeit—that’s the whole point; we can never be perfectly
certain—but here we appeal to our readers’ common sense and lived
experience.

* alludes :Elephant:
[2022-01-13 Thu 10:33]

When you allude to something, you don't identify it or mention it
specifically. If you allude to the fact that a cop is sitting right
behind you, your friends might stop talking about their plans to rob a
bank.

Allude is from Latin allūdere "to play with, joke" from the prefix ad-
"toward" plus lūdere "to play." The corresponding noun is allusion,
which is often used of an indirect reference in literature: Helen, a
fitting name for a woman of great beauty, is an allusion to Helen of
Troy.

Now, it’s wrong to say (as many have mistakenly repeated) that “over 90 percent
of communication is nonverbal.”1 But the myth persists in part because it alludes
to something true, which is that, for social creatures like us, body language is
very important. Our bodies convey vital information about our emotions—serenity
and anxiety, excitement and boredom, pride and shame—as well as our social
attitudes—trust and distrust, self-assurance and self-doubt, intimacy and
formality, loyalty and defiance. And we use body language (see Box 7) to
coordinate some of our most meaningful activities: making friends, falling in
love, and negotiating our position in a hierarchy.
* defiance :Elephant:
[2022-01-13 Thu 10:34]

Stand up when the powers that be order you to sit down, and you've
given a fine example of defiance. It happens when someone or a group
of someones openly flouts or challenges authority.

Refusing to go to bed when your parents tell you to? That's an act of
defiance. Defiance comes from French — specifically to the Old French
word defier, which means "to defy." (Don't mix it up with deify; that
means to make someone or something into a god.) If you've ever studied
Latin, you'll spot the fi in fidare, "to trust."

Now, it’s wrong to say (as many have mistakenly repeated) that “over 90 percent
of communication is nonverbal.”1 But the myth persists in part because it alludes
to something true, which is that, for social creatures like us, body language is
very important. Our bodies convey vital information about our emotions—serenity
and anxiety, excitement and boredom, pride and shame—as well as our social
attitudes—trust and distrust, self-assurance and self-doubt, intimacy and
formality, loyalty and defiance. And we use body language (see Box 7) to
coordinate some of our most meaningful activities: making friends, falling in
love, and negotiating our position in a hierarchy.
* savvier :Elephant:
[2022-01-13 Thu 10:36]

You are known as someone with a lot of business savvy, but only
because you've managed to keep your staggering debts a secret. Which
is actually pretty savvy. Someone who is savvy is shrewd and
perceptive.

Most English words stem directly from other European languages, like
French and Latin.  Not savvy.  It comes from the West Indies, a twist
on the French savez vous? — “Do you know?”  Savvy was first recorded
in its adjective form in 1905. Synonyms for the noun form include
acumen, discernment, grasp, perception, and sharpness.

We can see the importance of nonverbal skills even from a very early age. One
study of 60 kindergarteners, for example, found that children who were better at
reading emotions (from photographs of both adults and children) were also more
popular among their classmates. The savvier the child, the more likely he or she
was to be chosen as an activity partner.3 These are just correlations, but we
also know from personal experience how useful it can be to read body language
well.
* deftly :Elephant:
[2022-01-13 Thu 10:37]

When something's done deftly, it's accomplished with style and
skill. You'd be sure to impress your friends if you grabbed three
grapefruits, juggled them deftly, and returned them to their bowl, all
while carrying on a conversation.

A physical or athletic act can be done deftly, or easily and well, but
deftly can also describe something done with cleverness or wit, like a
musician writing song lyrics deftly. The Old English word gedæfte,
which means "mild" or "gentle," is the root of the word deftly, whose
meaning still has that sense of doing something both skillfully and
gently, or effortlessly.

Let’s set this question aside for a moment to consider another, related puzzle:
the fact that we’re largely unconscious of the messages we’re sending with our
bodies.4 Certainly we’re aware of some of these messages, but not nearly to the
extent that we’re aware of our spoken messages. And given the importance of
nonverbal communication, we might expect to be hyper-aware of it. But in fact the
opposite is true. With hardly any deliberate thought, we manage to deftly
position our limbs and torsos, flash meaningful facial expressions, laugh at all
the right moments, take up an appropriate amount of space, modulate our tone of
voice, make or break eye contact as needed, and decipher and react to all these
behaviors in others. As physicist-turned-psychologist Leonard Mlodinow says in
Subliminal, “Much, if not most, of the nonverbal signaling and reading of signals
is automatic and performed outside our conscious awareness and control.”5
* involuntary :Elephant:
[2022-01-13 Thu 10:39]

Involuntary describes a reflex or action done without conscious
control or will — like a blink, a sneeze, a yawn, or “the giggles.”

If you volunteered to do it, it’s voluntary. If you didn’t volunteer,
but you find yourself doing it anyway, it’s involuntary. This can go
for the involuntary hiccups you wrestle with on your blind date, as
well as the involuntary task you do at your manager’s
insistence. Involuntary gets a lot of blame, but something that is
involuntary is not necessarily bad: Breathing is involuntary, but you
would probably do it anyway if given the choice.

It’s not just that we happen to be partially oblivious to our body language. In
many ways, we seem to prefer it this way. We feel it’s appropriate for people to
act spontaneously. When body language becomes a deliberate performance, it seems
forced, perhaps even creepy. Consider the glad-handing salesman who (perhaps
after reading a book on body language) starts greeting his customers with a clasp
on the shoulder in an attempt to cultivate intimacy and affection. Thankfully,
this is the exception rather than the rule; most body language remains
involuntary.
* frenetic :Elephant:
[2022-01-13 Thu 10:41]

The adjective frenetic is another way to say frenzied, frantic, or
totally worked up. Kind of how you'd run around the kitchen madly
trying to cook a last-minute dinner for 30 of your closest friends.

Sometimes tinged with fear and often quite maniacal, frenetic comes
from the Latin phreneticus, meaning “delirious.” The Latin word, in
turn, came from a similarly spelled Greek word which, when translated
literally, means “inflammation of the brain.” So it's no surprise that
a frenetic person looks absolutely crazed and super anxious.

One answer is that consciousness is simply too slow to manage the frenetic
give-and-take of body language. When an enemy lunges in your direction, your body
needs to react instantly; a delay of even a few hundred milliseconds might prove
fatal.7 Consciousness is also too narrow. We can focus our spotlight attention on
only a small handful of things at once. But in order to weave through a crowd,
for example, our brains need to monitor dozens, hundreds, or even thousands of
things simultaneously—a task only the unconscious can perform.
* treacherous :Elephant:
[2022-01-13 Thu 10:55]

Treacherous means either not trusted or dangerous. A treacherous road
might be icy or otherwise likely to cause a car accident. A
treacherous friend will betray you.

Treachery refers to harmful acts you might do to someone who trusts
you. It can also refer to being disloyal to your native country, but
the word treason is more common in this sense. Treachery is from
Middle English trecherie, from Old French, from trichier "to trick or
cheat." The English word trick is from trikier, a slightly different
spelling that was used in some dialects of Old French.

Let’s now turn our attention to how we use (honest) body language to navigate the
often treacherous waters of human social life. As we do, keep in mind that people
may have differing levels of awareness in different domains. What’s obvious to
you might be revelatory to someone else, and vice versa. Books on “how to read
body language” are popular precisely because we don’t all have perfect intuitive
awareness of these things.
* rapport :Elephant:
[2022-01-14 Fri 10:50]

Rapport is a good sense of understanding and trust. If you have good
rapport with your neighbors, they won't mind if you kick your ball
onto their property every now and then.

If you have rapport with someone, you two communicate with trust and
sympathy. The word is often used to mean good interaction between
people in different positions or roles such as parent and teacher,
teacher and student, doctor and patient, supervisor and worker, or
speaker and audience. It is always important to establish rapport with
people you come into contact with regularly. Pronounce this borrowed
word from the French ra-POOR.

Even in conversation, what Alison and Ben say to each other may be less
significant than how they interact physically. As they develop a rapport, they’ll
begin to mirror each other’s posture. They’ll lean in and broach the bubble of
personal space that mere strangers are reluctant to violate.24 They’ll even begin
to touch each other, perhaps starting with light contact on the back, shoulder,
or elbow, then moving to areas reserved for greater intimacy: hands, legs, neck.
* broach :Elephant:
[2022-01-14 Fri 10:50]

Broach means to bring up or introduce a sensitive issue. If your best
friend has severe phobia of spiders, you might want to delicately
broach the topic of your new pet tarantula, Mr. Fuzzy.

Let's say you want to go on vacation with a friend and you ask your
dad because he is more likely to say yes. He will probably tell you
that he will broach the subject with your mom and let you know. In a
less common (and older) usage of broach, if you put a hole in
something in order to get out what's inside you broach it. The
piercing tool you use is also called a broach. Think of piercing
someone with your idea the next time you broach a touchy issue.

Even in conversation, what Alison and Ben say to each other may be less
significant than how they interact physically. As they develop a rapport, they’ll
begin to mirror each other’s posture. They’ll lean in and broach the bubble of
personal space that mere strangers are reluctant to violate.24 They’ll even begin
to touch each other, perhaps starting with light contact on the back, shoulder,
or elbow, then moving to areas reserved for greater intimacy: hands, legs, neck.
* blurt :Elephant:
[2022-01-14 Fri 10:52]

If you blurt something out, you're speaking abruptly and without
thinking about what you're saying.

Usually, when you blurt something, you end up regretting it. Saying
something without considering your words can end up making you feel
stupid or hurting someone's feelings — just imagine what might happen
if you were to blurt out what you really think about your
grandmother's cooking. The best thing about the word blurt is that
it's onomatopoeic, or a word that sounds exactly like what it means.

Now, if this were a romantic comedy—emphasis on comedy—Ben might remain oblivious
to Alison’s come-ons, until finally she’s forced to blurt it out: “Take me home
already!” But this strikes us as funny only because most people don’t need words
to get the message.
* lenient :DarkPersuasion:
[2022-01-14 Fri 10:59]

If you're not overly strict, and you show tolerance and mercy when
someone does something wrong, you're being lenient.

Lenient means tolerant or relaxed, and is usually used when we’re
talking about someone’s attitude toward discipline. In 19th-century
child-rearing books, we often read about strict teachers who punish
children just for squirming in their seats. These days teachers are
more likely to be lenient, more understanding. If you're a big fan of
discipline and punishment, however, lenient might mean "soft" or
"indulgent."

In the 1970s, the Khmer Rouge developed a primer for novice torturers. Prisoners
were interrogated repeatedly and forced to continually write and rewrite
confessions. The goal was to obtain adequate confessions before the prisoners’
execution. The “Interrogator’s Manual” described how this was to be done. Above
all else, the novice torturers were instructed, “don’t be hasty.” More detailed
instructions included the following: “Reassure them by giving them something,
some food for instance. . . . Terrify them, confuse them in clever ways. Arrange
little ploys to make them give up any hope that they will . . . be able to
survive. . . . Don’t step up the pressure all the time. Say something like ‘Don’t
make us torture you or torture you severely. It’s bad for your health, and it
makes it harder for us to deal with each other in the future.’ If they reveal
small matters, encourage them to reveal the big ones. Tell them that if they
reveal important matters, . . . [we] will be lenient with them.”17
* surreptitiously :DarkPersuasion:
[2022-01-14 Fri 11:01]

When you're doing things secret and sneakily, you're doing them
surreptitiously.

This is an adverb that applies to actions that you're trying to do
covertly: you don't want anyone to know about them, so you have to be
sneaky. Burglars approach a house surreptitiously. If you plan a
surprise party for your mother, you have to go about it
surreptitiously or she'll find out and the surprise will be
ruined. Anything you don't reveal fully or do on the sly is an example
of going about it surreptitiously.

State-mandated conversions have swept up countless millions. Some people choose
to die rather than convert; some go into exile; some adopt the external
appearances of having converted but surreptitiously hold onto their original
faith. Many go along with imposed conversion out of necessity, spinelessness,
opportunism, or religious indifference, and some even come to cherish their new
faith.18
* zeal :DarkPersuasion:
[2022-01-14 Fri 11:05]

Zeal is dedication or enthusiasm for something. If you have zeal,
you're willing, energized, and motivated.

Zeal is often used in a religious sense, meaning devotion to God or
another religious cause, like being a missionary. Zeal doesn't have to
be religious, though: a feeling of gusto and enthusiasm for anything
can be called zeal. People have zeal for sports teams, bands, causes,
and (often, but not always) their jobs. If you have passion for
something, you have zeal, which is kind of a mix of eagerness and
energy and devotion.

Both brainwashing and religious conversion rely on strong group pressure. They
target people who are exhausted and dejected from extensive self-criticism,
doubt, fear, and guilt. When potential converts abandon their old ways of
thinking, they feel relief, gratitude, and zeal. They sense a new beginning with
a cleansed life. These aspects of conversion are the same whether one is
converting to a common established belief or to an uncommon new one. Churches
grow and morph; today’s traditional or “heritage” church probably was
revolutionary generations ago.22
* thicket :DarkPersuasion:
[2022-01-14 Fri 11:10]

A thicket refers to a dense growth of bushes or trees — what you try
to avoid by tending to the plants in your backyard.

The word thicket comes from the word thick, which means close together
or dense. If you are "thick as thieves," then you are close friends. A
thicket is a growth of trees, bushes, or shrubbery that is very close
together, often making it difficult for people to walk through or for
Red Riding Hood to find her way out of to Grandmother's.

Conversion offers a path out of the thicket of one’s current life. It can be
facilitated by physical activities like fasting, vigils, drugs, dancing, and
intense exercise. It is also easier if new converts distance themselves from the
influence of their families and former friends.28 In brainwashing, we find
similar features, but they have been twisted (starvation, sleep deprivation,
drugs, exhaustion, social isolation).
* ventrally :Elephant:
[2022-01-20 Thu 11:48]



nil

Of course, our politically charged body language extends far beyond proximity and
touch—just as one might expect from the most intensely political species on the
planet. When we feel threatened, for example, we naturally adopt an alert and
defensive posture. We hunch our shoulders or cross our arms. We sit forward with
feet planted firmly on the floor, the better to stand up quickly if tensions
escalate. Conversely, when we’re in the presence of trusted friends, we let our
guards down—by maintaining an open, vulnerable posture, by showing our palms, or
by relaxing our shoulders and leaving our necks exposed. “It has always been my
impression,” says Joe Navarro, a Federal Bureau of Investigation interrogator and
body-language expert, “that presidents often go to Camp David to accomplish in
polo shirts what they can’t seem to accomplish in business suits forty miles away
at the White House. By unveiling themselves ventrally (with the removal of coats)
they are saying, ‘I am open to you.’ ”37
* amity :Elephant:
[2022-01-20 Thu 11:51]

The word amity refers to a peaceful, friendly nature, much like the
French word ami, or "friend."

From the Latin amicus, "friend," amity means "friendly relations."
That strong sense of friendship lends irony to the name of the book,
and later the movie, called The Amityville Horror, about a horrifying
town with a weirdly cheerful name. In truth, though, amity means
"mutual understanding and peace." Wouldn't it be nice if all of the
world's nations lived in amity?

It’s instructive to compare and contrast two greeting rituals: the handshake,
currently the predominant greeting ritual in Western countries, and the
hand-kiss, which was popular among European aristocrats in the 18th and 19th
centuries (but which has since fallen out of fashion).41 Both are gestures of
trust and amity, but they differ in their political implications. Shaking hands
is symmetric and fundamentally egalitarian; it’s a ritual between supposed
equals. Hand-kissing, however, is inherently asymmetric, setting the kisser apart
from, and subordinate to, the recipient of the kiss. The kisser must press his
lips on another person’s (potentially germ-ridden) hands, while simultaneously
lowering his head and possibly kneeling. This gesture is submissive, and when
it’s performed freely, it’s an implicit pledge of loyalty. Even when the ritual
is somewhat coerced, it can send a powerful political message. Kings and popes,
for example, would often “invite” their subjects to line up for public
kiss-the-ring ceremonies, putting everyone’s loyalty and submission on
conspicuous display and thereby creating common knowledge of the leader’s
dominance.
* inflection :Elephant:
[2022-01-20 Thu 11:54]

Inflection refers to the ups and downs of a language. Even if you
can’t understand Italian yet, the inflection in your professor’s voice
should tip you off to whether she's asking a question, giving a
command, or making a joke.

What began in the 1500s as a noun of action spelled inflexion has
since evolved into inflection, a word with grammatical
connotation. Inflection most often refers to the pitch and tone
patterns in a person’s speech: where the voice rises and falls. But
inflection also describes a departure from a normal or straight
course. When you change, or bend, the course of a soccer ball by
bouncing it off another person, that’s an example of inflection.

“Suddenly we understood that every inflection and movement implies a status, and
that no action is due to chance, or really ‘motiveless.’ It was hysterically
funny, but at the same time very alarming. All our secret manoeuvrings were
exposed.”—Keith Johnstone42
* tad :DarkPersuasion:
[2022-01-20 Thu 12:20]

A tad is a very small amount, so if a recipe calls for a tad of hot
pepper, it's not a good idea to dump in the whole bottle.

The informal noun or adverb tad is useful when you want another way to
say "a bit" or "a smidge." If you stumble over one of your lines in
the school play, you might be just a tad embarrassed, but if you fall
in the middle of your big scene and pull the curtain down with you,
you'll feel more than a tad humiliated. Before it meant "small
amount," tad meant "young child."

Religious conversion practices have been studied extensively with reference to
John Wesley’s Methodism—the new religion of the eighteenth century. As a small
boy, Wesley quite literally experienced salvation. A fire trapped him on the top
floor of his house until he was rescued at the last moment. Years later, at a
time of personal disappointment, he found salvation in the belief that Christ had
taken away his sins. When he was ordained, he led a small group that prayed for
three hours every day, fasted regularly, and visited prisoners to bring them
comfort. He found strength in hymns and kept a meticulous diary, hourly charting
his religious devotion on a scale from 1 to 9. Perhaps the charting on a 1 to 9
scale was a tad unusual, but in other respects, the faith he espoused does not
sound so unusual to us in the twenty-first century.
* whiff :DarkPersuasion:
[2022-01-20 Thu 12:26]

A whiff can mean the hint of something you smell. When you drive past
the sewage treatment plant and suddenly roll up your car windows, it's
usually because you've gotten a whiff of the plant's special odor.

Whiff can be used as either a noun or verb, and it implies a brief or
small puff or sniff. A person can have "a whiff of the exotic," which
means they are living like the rest of us, but there is a little
something about them that seems foreign or different. Sometimes, of
course, odors are so overpowering that a small sniff is all you need:
"Take a whiff of this," your friend might say to you, holding out a
carton of sour milk. In that case, one whiff will be more than enough.

Commenting about Sargant’s diverse interests and activities, psychopharmacologist
Malcolm Lader remarked, “There was a whiff of sulphur about him.”33 I mention all
this not just because it is interesting, but because it helps provide context for
his diverse comments about potential links between religious conversion and
brainwashing.
* dollop :DarkPersuasion:
[2022-01-20 Thu 12:30]

A dollop is a small, indefinite amount of something. You might ask for
a dollop of sour cream on your taco.

English has many words for amounts of something that aren't exact. For
example, a load is a lot of something, but a dollop is a little. If
you're watching your weight, you may only want a dollop of dressing on
your salad. Most people use a dollop of shampoo when washing their
hair. You can't measure a dollop, but it should be a fairly small
amount. If you use a whole bottle of ketchup, that's far more than a
dollop.

Reflecting on Saul’s conversion on the road to Damascus, he pointed out that many
factors were at work. After all, Acts 9:9 plainly states that Saul’s conversion
was preceded by three days during which he “neither ate nor drank.” With this
dollop of reductionism, Sargant went on to comment about the power of conversion.
* approvingly :DarkPersuasion:
[2022-01-20 Thu 12:30]



nil

Citing William James, Sargant notes approvingly, “Emotional occasions, especially
violent ones, are extremely potent in precipitating mental rearrangements. The
sudden and explosive ways in which love, jealousy, guilt, fear, remorse or anger
can seize upon one are known to everybody. Hope, happiness, security, resolve,
emotions characteristic of conversion, can be equally explosive. And emotions
that come in this explosive way seldom leave things as they found them.”35
* precipitating :DarkPersuasion:
[2022-01-20 Thu 12:31]



nil

Citing William James, Sargant notes approvingly, “Emotional occasions, especially
violent ones, are extremely potent in precipitating mental rearrangements. The
sudden and explosive ways in which love, jealousy, guilt, fear, remorse or anger
can seize upon one are known to everybody. Hope, happiness, security, resolve,
emotions characteristic of conversion, can be equally explosive. And emotions
that come in this explosive way seldom leave things as they found them.”35
* consonant :DarkPersuasion:
[2022-01-20 Thu 12:33]

A consonant is a speech sound that is not a vowel. It also refers to
letters of the alphabet that represent those sounds: Z, B, T, G, and H
are all consonants.

Consonants are all the non-vowel sounds, or their corresponding
letters: A, E, I, O, U and sometimes Y are not consonants. In hat, H
and T are consonants. Consonant can also be an adjective that
describes things that seem like they should go together, things that
are "agreeable." You could say a nation's offer of aid is consonant
with their treaties. When you hear consonant sounds in music, they are
pleasing, the opposite of "dissonant" sounds which are harsh.

Some of Sargant’s ideas, when given a different spin, are consonant with
contemporary anthropological insights. Tanya Luhrmann’s insightful book about
contemporary evangelicals notes that religious experience is commonly accompanied
by periods of silence, fasting, hard labor, repetitive hymns, and isolation.
* pilloried :DarkPersuasion:
[2022-01-20 Thu 12:35]

A pillory is a wooden frame with cutouts for someone's head and
hands. Long ago, people found guilty of a crime could be sentenced to
be locked in a pillory for a certain amount of time for punishment but
also for public humiliation.

The verb pillory means to be punished by being locked in a pillory,
but references to this form of punishment are historic and it is no
longer used — you might see references today to someone in a pillory
in a cartoon. As a modern verb, pillory means both to criticize
harshly and to expose to public ridicule. Someone who is caught doing
something immoral may be pilloried and people who believe they have
been unfairly criticized say they have been pilloried, but often only
after they've been exposed!

Psychiatrist John Clark was pilloried because he warned about the risks of cults
that regard science and medicine as the enemy.39 Although he was quick to say
that people have the right to their opinions and that cults could well serve as
leavening agents in a stagnant culture, critics remember him for his forceful
criticisms of absolutist groups that embrace magic and faith healing. He and
other clinicians based their observations on their patients who were ex-cult
members. Needless to say, people who are happy with their conversion to these new
sects do not come to see clinicians. Nonetheless, the clinicians’ warnings would
become tragically prophetic in the case of some new religious groups.
* kennel :DarkPersuasion:
[2022-01-21 Fri 11:07]

A kennel is a structure or business that houses animals, particularly
dogs and cats. You might leave your dog at a kennel while you go on
vacation.

You might have a small kennel for your dog in your backyard, or have
your pet groomed or boarded at a professional kennel. Some kennels are
kept for breeding animals — when you buy a puppy from a breeder, you
might pick him up at a kennel. The word kennel, by way of the
Anglo-French kenil, and the Vulgar Latin canile, has its roots in the
Latin canis, or "dog."

THE DOGS WERE RESTLESS. Penned in their cages in the basement of the Institute of
Experimental Medicine, they were lonely and weary from their daytime jobs in the
professor’s laboratory. But it wasn’t the dark or the isolation or fatigue that
got to them. It was the incessant dripping and lapping of water on the floor of
their kennel.
* fetid :DarkPersuasion:
[2022-01-21 Fri 11:09]

If you want to understand the true meaning of fetid, leave your sweaty
gym clothes in your locker for a few days.  Fetid is a fancy way of
saying that something smells really bad.

From the Latin word meaning "stinking," this adjective has been in use
since the early 15th century, which was a particularly fetid time in
history — showers, laundry detergent, and deodorant had not yet been
invented.  Here's an easy way to remember it: "the fe(e)t (d)id
stink." It's sometimes spelled foetid.

At the last moment, a dog handler raced through the flooded streets to the
institute, where he encountered chaos—panicked dogs, floating cages, and the
fetid water of the Neva. One by one, he rescued the dogs, but to get them out of
their cages, he had to first force their heads under the water. The dogs resisted
out of panic.
* disdained :DarkPersuasion:
[2022-01-21 Fri 11:14]

If you feel that something isn't worthy of your consideration, you may
disdain it (or treat it with disdain).

In Old French, deignier meant "to treat something as worthy." To
disdain something, then, is to treat it with contempt: "Management at
[the company] displayed a certain disdain for safety and appeared to
regard safety-conscious workers as wimps in the organization." As a
verb, disdain carries an air of self-righteousness not associated with
similar words like despise, abhor, detest, loathe and scorn. So if you
disdain something, you might reject it with a haughty scoff, "Ha!"

He disdained the autocratic and incompetent czarist rule but felt this legacy was
modifiable.2 Despite his distaste for the czarist past, he also disparaged the
Russian Revolution, partially because he almost starved during the ensuing chaos.
* retaliation :DarkPersuasion:
[2022-01-21 Fri 11:15]

Retaliation is an act of revenge. Before you initiate retaliation on
someone who has wronged you, consider whether he or she might have a
ninja alter ego and a set of nunchucks stashed away.

The noun retaliation stems from the Latin retaliare, meaning “pay back
in kind.” Notice the word kind in that definition. Retaliation used to
have both good and evil connotations. Now, though, it’s important to
read that kind as synonymous with type or sort because retaliation has
since lost its positive sense. Martin Luther King, Jr. once said, “Man
must evolve for all human conflict a method which rejects revenge,
aggression and retaliation. The foundation of such a method is love.”

While Pavlov was quite open about his political opinions, he was safe from
retaliation because he was the first Russian to receive the Nobel Prize in
medicine (1904), and the Soviets pointed to him with pride. Like today’s
scientists, he used his prominence as a bargaining chip to obtain more resources
for his laboratory. Even in the midst of the country’s severe poverty, his
laboratory expanded. As Pavlov begrudgingly acknowledged, “Yes, you must give our
barbarians one thing: they understand the value of science.”3
* bolster :DarkPersuasion:
[2022-01-21 Fri 11:17]

When you cheer up a friend who's feeling down, you bolster them. To
bolster is to offer support or strengthen.

A bolster is also the name of a long pillow you might use to make your
back feel better. And the two uses are not dissimilar. When you
bolster your friends, you support them and prop them up, just like the
pillow does for your back. When you're trying to bolster your
credibility, you find people and/or documents that support you or your
view. Bolster efforts to learn this word!

The Communists applauded these ideas. In October 1919, Lenin visited Pavlov at
the Institute of Experimental Medicine. He stayed for two hours; it was more than
just a “photo-op” visit. Lenin hoped that Pavlov’s experiments could bolster the
State’s efforts to mold the New Man. As recounted by one of Pavlov’s colleagues,
Lenin described the challenges of building the new world of Communism and asked
Pavlov’s advice. How could he control individualism and shape human behavior so
that it would conform to Communist thinking?
* hereditary :DarkPersuasion:
[2022-01-21 Fri 11:19]

Things that are hereditary are inherited — passed down through the DNA
of your biological parents.

Has anyone ever said "You have your mom's eyes" or "Wow, you look like
your grandfather"? They're commenting on hereditary features — things
you got from your parents, and their parents, and all the other family
genes you carry. Hair color, height, and even parts of your
personality tend to be hereditary, or passed down genetically. Not all
hereditary things are good: you can also inherit health conditions,
crooked teeth, or your grandpa's bald spot.

LENIN: “Does this mean that hereditary factors can be overcome by proper
education?”
* elicits :DarkPersuasion:
[2022-01-21 Fri 11:21]

When you elicit, you're bringing out a response of some sort. A good
comedian elicits a lot of laughs.

Elicit has to do with creating or provoking a response. A great speech
will elicit cheers — a bad speech will elicit boos. Teachers try to
elicit responses from students. If a friend smiles at you, it will
probably elicit a smile of your own. In court, a lawyer might try to
elicit mistakes and inconsistencies in the testimony of a witness. In
all cases, whatever is elicited is some kind of response.

Pavlov observed that intense stress elicits predictable responses. When dogs were
presented with a stimulus that they didn’t know how to respond to or were given
inconsistent or conflicting commands, their behavior deteriorated into what he
called “transmarginal collapse.” Every dog had its breaking point. In the face of
transmarginal collapse, their dispositions changed: outgoing dogs became shy, shy
ones became aggressive. Furthermore, after such collapse, the dogs even changed
their preferences for people: they became friendly to keepers they had previously
disliked and vice versa. In the face of intense stress, some dogs became so quiet
they looked like they were in a hypnotic trance, and Pavlov viewed this behavior
as a coping strategy. Pavlov reported that his techniques could reliably produce
experimental neurosis or even psychosis and that such experiments could help
evaluate new treatments. He experimented with drugs (bromides) to make dogs more
tractable in such circumstances.7
* garner :DarkPersuasion:
[2022-01-21 Fri 11:25]

To garner means to gather or earn. If you want to run for office
without belonging to a political party, you must garner enough
signatures — usually a few thousand — to get onto the ballot.

The word garner comes from the Latin granarium which means
"store-house," usually for grain. The current use of the word carries
with it the sense of something being stored up. It’s not only that you
can gather enough yes-votes to overcome the opposition, there is the
sense that all the things you have garnered have some weight of their
own. In its other use, garner means “earn” or "merit." Think of movie
stars garnering Oscar nominations for their excellent work.

Many of Pavlov’s ideas helped him garner Stalin’s support. In addition to
believing that behavior was modifiable, Pavlov thought that acquired behaviors
could be inherited. This view of genetics corresponded with Stalin’s views, and
Pavlov’s findings were disseminated throughout the Soviet Union.11 Stalin
vociferously attacked those who said Pavlov’s work only applied to animals.12
* flaunt :Elephant:
[2022-01-21 Fri 16:43]

Flaunt is "to display proudly or show off," like when you flaunt your
new Italian leather jacket by wearing it to the beach and pretending
you're cold to make sure everyone sees it.

Although we love it when a peacock flaunts his colorful feathers, when
a person does the same thing we feel bad. Flaunt is like bragging,
which can bum people out because they don't have whatever you're
showing off, like that cool jacket. When rich people flaunt their
wealth by speeding past you in their limo, they may as well splash a
mud puddle on your white clothes. Leave the flaunting for peacocks and
stars in bad reality TV shows.

Of all the signals sent and received by our bodies, the ones we seem least aware
of are those related to social status. And yet, we’re all downright obsessed with
our status, taking great pains to earn it, gauge it, guard it, and flaunt it.
* hesitantly :Elephant:
[2022-01-21 Fri 16:44]



nil

Because of their privileged position, high-status individuals have less to worry
about in social situations.43 They’re less likely to be attacked, for example,
and if they are attacked, others are likely to come to their aid. This allows
them to maintain more relaxed body language. They speak clearly, move smoothly,
and are willing to adopt a more open posture. Lower-status individuals, however,
must constantly monitor the environment for threats and be prepared to defer to
higher-status individuals. As a result, they glance around, speak hesitantly,
move warily, and maintain a more defensive posture.
* leeway :Elephant:
[2022-01-21 Fri 16:48]

Leeway is a term used to describe the amount of freedom available. If
you know you have a paper due on Monday, you might ask your teachers
if there is any leeway––could you, say, bring it first thing Tuesday
morning?

Leeway is a nautical term, referring to a vessel's drift to the lee,
(nautical for "downwind"). Now, it is very useful in describing those
gray areas in life––for example, everyone has a ten-minute leeway when
meeting friends where you're not officially late, even if you're not
actually on time.

But status is more than just an individual attribute or attitude—it’s
fundamentally an act of coordination. When two people differ in status, both have
to modify their behavior.45 Typically the higher-status person will take up more
space, hold eye contact for longer periods of time (more on this in just a
moment), speak with fewer pauses, interrupt more frequently, and generally set
the pace and tenor of interaction.46 The lower-status person, meanwhile, will
typically defer to the higher-status person in each of these areas, granting him
or her more leeway, both physically and socially. In order to walk together, for
example, the lower-status person must accommodate to match the gait of the
higher-status person.
* bask :Elephant:
[2022-01-21 Fri 16:54]

To bask in something is to take it in, receive its warmth, or bathe in
its goodness. On the first warm day of the spring, you may bask in the
sunshine. When you win the Pulitzer, you bask in your own glory.

In Shakespeare’s “As You Like It,” Jaques says: “...As I do live by
food, I met a fool; Who laid him down and bask'd him in the sun,; And
rail'd on Lady Fortune in good terms...” That was most likely the
first time bask was used in the way that we most often use it now: to
bask is to warm yourself, either literally or figuratively, in the
glow of the sun, good fortune, happiness, or a job well done.

In contexts governed by prestige, however, eye contact is considered a gift: to
look at someone is to elevate that person. In prestige situations, lower-status
individuals are ignored, while higher-status individuals bask in the limelight.52
In this case, attention (rather than information) is the key resource, which
lower-status admirers freely grant to higher-status celebrities.
* laced :Elephant:
[2022-01-21 Fri 17:01]

When something is fastened with a cord that's passed through eyelets,
it's laced. While their formal dress boots have no fasteners, a
horseback rider's laced field boots have ties on the front.

If a shoe or item of clothing has laces, you can describe it as
laced. The word can also be used for other things that are
intertwined: "He knelt his head over his laced fingers and prayed."
Another meaning is "tainted" or "slightly colored," as when your hot
chocolate is laced with peppermint syrup or the morning sky is laced
with pink.

The three areas of social life we’ve examined in this chapter—sex, politics, and
status—are laced with norms governing our behavior.58 What we may hope to
accomplish in each area is often at odds with the interests of others, which can
easily lead to conflict. That’s why societies have so many norms to regulate
behavior in these areas, and why we (as individuals) must take pains to conduct
ourselves discreetly.
* appallingly :Elephant:
[2022-01-21 Fri 17:03]



nil

Consider how we use our bodies to “say” a lot of things we’d get in trouble for
saying out loud. It would be appallingly crass to announce, “I’m the most
important person in the room”—but we can convey the same message, discreetly,
simply by splaying out on a couch or staring at people while talking to them.
* impropriety :Elephant:
[2022-01-21 Fri 17:04]

When the boss's husband shows up at a formal dinner party and proceeds
to stuff his pockets full of hors d'oeuvres, no one dares to mention
his impropriety above a whisper, especially to the boss.

Impropriety is a violation of a rule of behavior, manners, or
etiquette. So while it is fitting and proper to wear a bikini top and
a sarong to the beach, to do so at church would be considered an
impropriety. Some find a bit of impropriety charming. Somerset Maugham
went so far as to say, “Impropriety is the soul of wit.”

The point is, relative to spoken messages, nonverbal messages are much harder to
pin down precisely, making it easier to avoid accusations of impropriety. In a
meeting at work, for example, Peter may use nonverbals to marginalize his rival
Jim (e.g., by ignoring him while he speaks). But if Peter is accused of acting
“politically,” he’ll quickly deny it, arguing that his accuser has misread the
situation. Later, at a party, he may use body language to flirt with another
woman. But if his wife accuses him, he’s likely to explain that he was merely
being friendly.
* trove :stupidity:
[2022-01-24 Mon 12:36]

A trove is a valuable collection of something. You might discover a
trove of old comic books in the basement of your uncle's house, or a
trove of candy bars at the back of a kitchen cabinet.

If you found a treasure chest full of gold doubloons buried in your
back yard, you could absolutely call that a trove — but you can also
use trove for any wonderful or precious stash of stuff. Archaeologists
might uncover a trove of fossils, and Easter egg hunters are hoping to
discover a trove of eggs and candy. Trove was first used in the phrase
treasure trove, from the Anglo-French tresor trové, rooted in the Old
French trover, "to find."

You're always starting with abundance. You're starting with this
pre-existing treasure trove of information that you yourself have
decided in the past that was worth saving.

* fluster :Elephant:
[2022-01-24 Mon 13:06]

To fluster someone is to make them feel upset or agitated. There are
many things that might fluster you: giving a speech in front of the
whole school, solving a challenging math problem, or even getting a
love note from an admirer.

If your coworker is about to give the biggest presentation of his
life, you’ll probably only fluster, or upset, him if you point out
that his socks don’t match. Use the adjective form, flustered, to
describe someone when they’re feeling this way. Most of us get
flustered once in a while, but if you’re “easily flustered,” it
happens to you quite often. Don’t worry, though; that just gives you
more opportunities to practice using this vocabulary word.

Not all of our nonverbal messages are taboo in this way, of course. We’re all
perfectly aware that droopy eyes mean we’re feeling tired, outstretched arms mean
we’re feeling proud, and smiles mean we’re feeling happy. It doesn’t fluster us
to admit these meanings or to comment on them in conversation. But as soon as
someone points out our sex-, politics-, or status-related body language, we begin
to fumble about self-consciously. And like a murder suspect turning suddenly
awkward during an interrogation, we’re uncomfortable because we have something to
hide.
* derision :Elephant:
[2022-01-24 Mon 13:12]

If people are laughing at you, making fun of you, and acting as if
you're worthless, they're treating you with derision. Derision is mean
and attacking — it's a form of contempt.

Derision is more than just making fun of someone — it's mocking
someone so forcefully and with such venom that you discredit the
person completely. Derision can include literally laughing at someone
or just treating a person like a joke. You know how celebrities and
politicians do embarrassing things from time to time? They're usually
treated with derision afterward: people mock them, treat them with
contempt, and try to make the person who messed up seem completely
worthless.

According to the superiority theory (Plato, Aristotle, Thomas Hobbes, and René
Descartes7), laughter is fundamentally mean-spirited, a form of mockery,
derision, or scorn. The superiority theory says that we laugh primarily at other
people, because we feel superior to them. The problems with this theory are that
it can’t explain why we laugh when we’re tickled, or why we don’t laugh when we
see a beggar on the street.
* squarely :Elephant:
[2022-01-24 Mon 13:20]



nil

Picture an infant giggling at a game of peekaboo with her father—what could be
more wholesome and innocent? But from earlier chapters, we know that ignorance
often serves a deceptive purpose; our brains hide certain things from us in order
to hide them more effectively from others. This suggests there may be a hidden
dark side to laughter. Consider how we often use humor as an excuse to trot out
our most taboo subjects: race, sex, politics, and religion. Or how we laugh at
people who are different from us or people who aren’t in the room. We can say
things in the comedic register that we’d never dream of saying in a
straight-faced discussion. The paradox of laughter is that it puts us at ease in
social situations, and yet its meaning and purpose seem to reside squarely in our
introspective blind spot.

* masterly :Stupidity:
[2022-01-25 Tue 12:39]



nil

A masterly book.
* supererogation :Stupidity:
[2022-01-25 Tue 12:42]

Supererogation is a fancy way of saying "doing more than you're
expected or obligated to." If your school requires that all students
perform ten hours of community service, but you volunteer at the soup
kitchen for twenty hours, that's supererogation.

The Late Latin supererogatio means "a payment in addition," from
super, "above or over" and erogare, "pay out." In English, this word
was originally used in a religious context, for good works that go
beyond what God requires. Today, supererogation typically describes an
ethical or religious decision to act beyond what's required for being
a good person: "Donating twenty percent of their income to charity is
an act of supererogation."

The Mad Millers printed only a limited number of copies of this book, which
addresses itself not to stupid people but to those who on occasion have to deal
with such people. To add that none of those who will receive this book can
possibly fall in area S of the basic graph (figure 1) is therefore a work of
supererogation. Nevertheless, like most works of supererogation, it is better
done than left undone. For, as the Chinese philosopher said: “Erudition is the
source of universal wisdom: but that does not prevent it from being an occasional
cause of misunderstanding between friends.”
* deplorable :Stupidity:
[2022-01-25 Tue 12:44]

Deplorable is an adjective used to describe something extremely bad or
unfortunate, like the deplorable destruction and loss of life in Japan
after the earthquake and tsunami.

Deplorable comes from the French word déplorer meaning "to give up as
hopeless," meaning something is so bad, there is no hope of
improvement like the deplorable actions of the arsonist who burned
down the museum filled with priceless antiques. Deplorable can also
describe something that is of terrible quality or unhealthful, like
the deplorable state of the area under your bed — is that a moldy
sandwich under there?

Human affairs are admittedly in a deplorable state. This, however, is no novelty.
* inception :Stupidity:
[2022-01-25 Tue 12:44]

The inception is the beginning. Since its inception, Wikipedia has
been created by its users.

Inception sounds like conception, but their meanings are distinct.
Conception usually refers to the moment of becoming
pregnant. Inception refers more to the beginning, to entering upon an
undertaking. Inception implies the start of a specific thing like a
campaign or a company. Subsequent events take place after the
inception. At the moment of conception, most women are at the
inception of motherhood.

The heavy load of troubles and miseries that human beings have to bear as
individuals as well as members of organized societies is basically a by-product
of the most improbable—and I would dare say, stupid—way in which life was set up
at its very inception.
* ordeals :Stupidity:
[2022-01-25 Tue 12:45]

An ordeal is something difficult or painful to go through. Something
kind of hard like taking a test can be an ordeal, but often an ordeal
is a serious and long-lasting event, like an illness or tragedy.

When you go through an ordeal you have to deal with something
tough. Waiting for someone you love to recover from an injury and come
home from the hospital is an ordeal––for both of you––and being a
victim of a crime is a different kind of ordeal. You can use this noun
in an exaggerated way, too, as when you endure the long ordeal of
cleaning the garage on a sunny weekend.

After Darwin, we know that we share our origin with the lower members of the
animal kingdom, and worms as well as elephants have to bear their daily share of
trials, predicaments, and ordeals. Human beings, however, are privileged insofar
as they have to bear an extra load—an extra dose of tribulations originated daily
by a group of people within the human race itself. This group is much more
powerful than the Mafia, or the military industrial complex, or international
communism—it is an unorganized, unchartered group which has no chief, no
president, no by-laws and yet manages to operate in perfect unison, as if guided
by an invisible hand, in such a way that the activity of each member powerfully
contributes to strengthen and amplify the effectiveness of the activity of all
other members. The nature, character, and behavior of the members of this group
are the subject of the following pages.
* insofar :Stupidity:
[2022-01-25 Tue 12:45]

Use insofar to mean "as much" or "to the extent." You might, for
example, say, "I will get my math homework done insofar as I can.

The adverb insofar is somewhat old fashioned and uncommon these days,
but it's a good way to talk about doing something to a certain degree
or extent. You might accuse your boss of treating her employees well
only insofar that it improves her business, or decide that math is
only interesting to you insofar as it seems useful in daily life. The
British form of insofar is in so far.

After Darwin, we know that we share our origin with the lower members of the
animal kingdom, and worms as well as elephants have to bear their daily share of
trials, predicaments, and ordeals. Human beings, however, are privileged insofar
as they have to bear an extra load—an extra dose of tribulations originated daily
by a group of people within the human race itself. This group is much more
powerful than the Mafia, or the military industrial complex, or international
communism—it is an unorganized, unchartered group which has no chief, no
president, no by-laws and yet manages to operate in perfect unison, as if guided
by an invisible hand, in such a way that the activity of each member powerfully
contributes to strengthen and amplify the effectiveness of the activity of all
other members. The nature, character, and behavior of the members of this group
are the subject of the following pages.
* tribulations :Stupidity:
[2022-01-25 Tue 12:45]

Tribulation is suffering or trouble, usually resulting from
oppression. The tribulations of a coal miner include a dangerous work
environment, lung disease from black dust and a cramped, dark work
space.

When you encounter the word tribulation, it will usually be in the
company of the word trial as in, “She suffered many trials and
tribulations as an early feminist.” The two words, while not
identical, emphasize each other as they essentially mean testing and
suffering. Tribulation comes from the Latin verb tribulare "to
oppress, afflict."

After Darwin, we know that we share our origin with the lower members of the
animal kingdom, and worms as well as elephants have to bear their daily share of
trials, predicaments, and ordeals. Human beings, however, are privileged insofar
as they have to bear an extra load—an extra dose of tribulations originated daily
by a group of people within the human race itself. This group is much more
powerful than the Mafia, or the military industrial complex, or international
communism—it is an unorganized, unchartered group which has no chief, no
president, no by-laws and yet manages to operate in perfect unison, as if guided
by an invisible hand, in such a way that the activity of each member powerfully
contributes to strengthen and amplify the effectiveness of the activity of all
other members. The nature, character, and behavior of the members of this group
are the subject of the following pages.
* juncture :Stupidity:
[2022-01-25 Tue 12:47]

A juncture is a crucial point in time when a decision must be made. At
this juncture, a president might say, the government must decide
whether to go ahead with war or to try to solve things diplomatically.

A juncture is a joint or connection between two things. Originally
used in the physical sense, it has broadened in meaning to refer to an
often urgent decision-making crossroads. At some point you and your
partner will reach a critical juncture and have to decide whether to
get serious or break up. It can also simply mean "point in time." She
had never learned how to drive and, at this juncture, she knew she
never would.

Let me point out at this juncture that most emphatically this little book is
neither a product of cynicism nor an exercise in defeatism—no more than a book on
microbiology is. The following pages are in fact the result of a constructive
effort to detect, know, and thus possibly neutralize one of the most powerful
dark forces that hinder the growth of human welfare and happiness.
* veracity :Stupidity:
[2022-01-25 Tue 12:49]

Veracity sounds like some kind of disease you don't want to catch, but
in fact, it means truthfulness. If you question the veracity of a
statement or story, you wonder whether it is truthful or accurate.

Veracity is linked to the adjective veracious or "truthful." But don't
confuse veracious with voracious. A voracious person eats very large
amounts of food. If you were veracious, or "truthful," you'd tell them
they look fat.

At first, the statement sounds trivial, vague and horribly ungenerous. Closer
scrutiny will, however, reveal its realistic veracity. No matter how high are
one’s estimates of human stupidity, one is repeatedly and recurrently startled by
the fact that
* harassed :Stupidity:
[2022-01-25 Tue 12:49]



nil

b) day after day, with unceasing monotony, one is harassed in one’s
 activities by stupid individuals who appear suddenly and unexpectedly in the
 most inconvenient places and at the most improbable moments.
* internalize :Stupidity:
[2022-01-25 Tue 13:37]

If you feel anger, pain, fear or hurt but never show it, you
internalize it — you keep it inside.

If you think about the prefix inter- which always indicated something
within, you have the meaning of the adjective internalize, "to keep or
take something in." It can be used in either a positive or negative
way. If you are a debater who internalizes a topic, then you know it
inside and out. On the other hand, you're not doing yourself any
favors if you internalize your guilt.

Next we have the idea that you only know what you make and this is
like a big part of the building second brain thing. This is a big part
of my personal spiel as well. These days is that like we can read watch
and listen to all the stuff that we want, but really the stuff that
we're really going to internalize and that's really going to affect
our lives and that we can feasibly use in our future projects is going
to be the stuff that we have created ourselves. So whether that's
reading a book and then writing a summary of it or whether it's
listening to a podcast and kind of turning it into like a tweet storm
of like insights from the podcast or even if it's having a random idea
and then writing like fleshing out that idea into an intermediate
packet and chucking it into our second brain.
* feasibly :Stupidity:
[2022-01-25 Tue 13:37]



nil

Next we have the idea that you only know what you make and this is
like a big part of the building second brain thing. This is a big part
of my personal spiel as well. These days is that like we can read watch
and listen to all the stuff that we want, but really the stuff that
we're really going to internalize and that's really going to affect
our lives and that we can feasibly use in our future projects is going
to be the stuff that we have created ourselves. So whether that's
reading a book and then writing a summary of it or whether it's
listening to a podcast and kind of turning it into like a tweet storm
of like insights from the podcast or even if it's having a random idea
and then writing like fleshing out that idea into an intermediate
packet and chucking it into our second brain.
* conjectured :Elephant:
[2022-01-25 Tue 17:48]

Can you guess what conjecture means? It's a word to use when you are
not sure of something and have to "guess or surmise."

You can see how the word conjecture means that you create a theory or
opinion about something without basing it in fact because the original
definition of conjecture, from Old French, is "interpretation of signs
and omens." Since signs and omens are pretty subjective, it makes
sense that the word would then move to its current meaning. However,
even though it only seems like weather reports are conjectures, they
are actually based on evidence!

In order to explain laughter, then, we’ll have to look beyond the psychology of
humor. And that’s our cue to introduce Robert Provine, a professor of
neurobiology at the University of Maryland. Now, Provine wasn’t the first to
crack the code of laughter; others, like Max Eastman, had conjectured the
solution half a century earlier. But Provine’s research has done more to solidify
our understanding of laughter than the legion of armchair theorists who preceded
him.
* roving :Elephant:
[2022-01-25 Tue 17:57]

Roving things or people are in motion, like a roving reporter who
travels to cover stories instead of staying put at her desk.

Some roving animals are migrating, moving from one point on the globe
to another. Roving travelers might be folks who live out of their
camper as they wander across the country. And your job might be
described as roving, too: "I work as a roving news photographer."
Roving comes from the verb rove, "wander," which earlier meant "shoot
arrows at a mark selected at random."

Newton had his moment under an apple tree. And Eastman—an American journalist and
roving intellectual—had his flash of insight about laughter while playing with an
infant. Here’s how he describes that insight in his 1936 book The Enjoyment of
Laughter:
* bout :Elephant:
[2022-01-27 Thu 17:14]

A bout is a fight. If you want to be a boxer, start with some easy
bouts before challenging the champ.

A bout is a period of time in which something intense happens, like
fighting, binging, or being sick, and comes from the word for bending,
or going round in a circle. We usually use it these days for something
you wouldn't want to go on for too long of a time. If the full moon
makes you crazy, you might suffer a bout of madness.

At the time, it wasn’t clear to Bateson exactly how the monkeys were telegraphing
their playful intentions to each other, just that they must have had some means
of doing it. But biologists have since studied these play signals in detail, and
it’s not only primates who use them. “We’re just playing” is such an important
message, it turns out, that many species have developed their own vocabulary for
it.25 Dogs, for example, have a “play bow”—forearms extended, head down,
hindquarters in the air—which they use to initiate a bout of play.26 Chimps use
an open-mouthed “play face,” similar to a human smile,27 or double over and peer
between their legs at their play partners.28 And many animals, in addition to
using specific gestures, will also move slowly or engage in exaggerated or
unnecessary movement, as if to convey playful intent by conspicuously wasted
effort that no animal would undertake if it were in serious danger. All of these
signals serve to reassure playmates of one’s happy mood and friendly intentions.
* clod :Elephant:
[2022-01-27 Thu 17:24]

A clod is a lump or chunk of something. You begin the process of
making a bowl by throwing a clod of clay onto a potter's wheel.

Clod usually describes a mass or ball of dirt: "She intended to plant
vegetables in her yard, but found the soil was full of hard clods and
stones." An annoyingly awkward person can also be called a clod: "He
always says the wrong thing — he's such a clod." The word comes from
clot, which originally meant "a mass," and comes from the German
Klotz, "lump or block."

It’s only after you’ve rushed to her side and discovered that she’s perfectly
safe that maybe it becomes reasonable to laugh about the situation—especially if
she starts laughing first. In fact, the logic of laughter explains why her
laughter is likely to trigger yours, rather than the other way around. If she
laughs first, it means she feels safe, so you can feel safe too. But if you laugh
first, she’s liable to take offense. How could you feel safe when she hasn’t
given the “all clear” (you insensitive clod)? It must mean you don’t really care
what happens to her.
* propensity :Elephant:
[2022-01-27 Thu 17:25]

A propensity is a natural tendency to behave in a certain way. We all
have propensities — things we tend to do. Dogs have a propensity to
bark, and many people have a propensity for getting annoyed by it.

If you have a propensity for something, then it's something that comes
naturally to you or something you just do a lot. Some people have a
propensity to laugh. Other people have a propensity for making others
laugh, or for being generous, or for getting angry. It's hard to
change your propensities. Sometimes a propensity is a bad thing, as in
a criminal with a propensity for theft or murder.

In light of all this, we’re now equipped to think about the relationship between
laughter and humor. In any given comedic situation, humor precedes and causes
laughter, but when we step back and take a broader perspective, the order is
reversed. Our propensity to laugh comes first and provides the necessary goal for
humor to achieve.34 Humor can thus be seen as an art form, a means of provoking
laughter subject to certain stylistic constraints. Humorists, in general, work in
the abstract media of words and images. They don’t get credit, as humorists, for
provoking laughter by physical means—by tickling their audiences, for example.
* aboveboard :Elephant:
[2022-01-27 Thu 17:30]

If something is aboveboard, it's done in a completely honest,
straightforward way. When a company's business dealings are
aboveboard, they act in an honorable, open manner.

It would be nice to think that everyone acts in a way that's
aboveboard, but scandals involving money and shady business deals
prove otherwise. You might say, "I don't trust that guy — it just
doesn't seem aboveboard, the way he avoids answering my questions."
This word was first used in the 17th century, reportedly from the idea
that it's harder to cheat at cards if you keep your hand above the
table, rather than hiding it in your lap.

As we’ve hinted, such ignorance may be strategic; our brains may be trying to
hide something. And yet the meaning of laughter—“We’re playing!”—seems entirely
innocent and aboveboard.
* scowl :Elephant:
[2022-01-27 Thu 17:37]

When you scowl you make an angry face. The angry face you make is also
called a scowl. Lighten up.

Scowl is an expressive word: it shares "ow" with frown, and if you say
it like you mean it you might end up scowling yourself. Being scowled
at is more unsettling than being frowned at. A scowl is like an angry
frown you would give someone if you disapproved of them. A frown
expresses sadness, but a scowl expresses disdain.

Consider a five-year-old girl who finds potty humor hilarious. She knows it’s
rude to perform (or talk about) certain bodily functions in front of others, and
that she risks being punished if she does. But at the same time, she can’t take
every rule at face value; she needs to probe her boundaries. Just how serious are
these norms, really? If she soils her pants, of course, she may feel legitimately
ashamed—and thus, no laughter. But if she merely farts, she’ll quickly learn that
the danger is quite small; her parents may scowl, but they’re not going to send
her to her room. And this realization—that farting can be safe, even though it’s
officially discouraged—is liable to provoke some laughter. And a whoopie cushion
may be even funnier to the young girl, since it produces only fake fart noises,
and is entirely benign.
* cushion :Elephant:
[2022-01-27 Thu 17:37]

Fabric filled with foam, feathers, or other padding material makes a
cushion, which can be used to make something like a chair or sofa more
comfortable.

The noun cushion can also refer to anything that is used to soften an
impact or absorb shocks. In modern cars, for example, sometimes in a
crash or accident, air bags will deploy and act as cushions for the
passengers to prevent them from injuring themselves on hard surfaces
like the dashboard or steering wheel. A cushion isn't necessarily a
physical one, however, as you may want to keep an emergency fund as a
cushion in case of unexpected expenses. As a verb, cushion means to
protect from the impact of negative information so if you have bad
news, you'll want to cushion the blow as much as possible.

Consider a five-year-old girl who finds potty humor hilarious. She knows it’s
rude to perform (or talk about) certain bodily functions in front of others, and
that she risks being punished if she does. But at the same time, she can’t take
every rule at face value; she needs to probe her boundaries. Just how serious are
these norms, really? If she soils her pants, of course, she may feel legitimately
ashamed—and thus, no laughter. But if she merely farts, she’ll quickly learn that
the danger is quite small; her parents may scowl, but they’re not going to send
her to her room. And this realization—that farting can be safe, even though it’s
officially discouraged—is liable to provoke some laughter. And a whoopie cushion
may be even funnier to the young girl, since it produces only fake fart noises,
and is entirely benign.
* consummate :Elephant:
[2022-01-28 Fri 11:22]

Consummate means complete, finished, or masterful. If you refer to
someone as a consummate chef, then you are saying he is the ultimate
chef. If you say someone is a consummate jerk, then you are saying he
is the ultimate jerk.

Consummate can be used to describe something good or bad: consummate
joy, a consummate liar. To consummate means to bring something to
completion, but it often refers specifically to making a marriage
complete by having sexual relations. The adjective is pronounced
KÄN-sə-mit, but the verb is pronounced KÄN-sə-māt.

Here, for example, is a joke that flirts with, but doesn’t actually consummate, a
norm violation:
* squirm :Elephant:
[2022-01-28 Fri 11:25]

To squirm is to wiggle or twist your body, the way an excited puppy
will squirm when you try to hold him in your arms.

Small children and animals squirm from excitement or eagerness, while
uncomfortable adults also sometimes squirm: "She was so upset by her
friends' argument that she started to squirm in her chair." When the
word squirm first appeared in the 17th century, it was used
specifically to talk about eels. Experts aren't sure of its roots, but
some guess squirm is connected to worm or swarm.

The humor here plays off the norm against racism. After Mary’s setup, John starts
to squirm uncomfortably, afraid his friend is about to tell an offensive joke. But
when Mary delivers the punchline, it’s sweet, safe relief. She wasn’t telling a
racist joke after all. She was just playing! And a hearty chuckle ensues.42
* ensues :Elephant:
[2022-01-28 Fri 11:26]

If something happens after something else, it will ensue, meaning it
will follow after or be the result. When a sneeze comes out, and he
hears the "Achoo!," a "Bless you" or "Gesundheit" soon will ensue.

One way to remember the verb ensue is to rhyme it with "due." A
happening that is due to happen will ensue, "Throwing a glass of ice
water in his face guaranteed that a chase would ensue." Often what
follows is a response to words or actions, so what will ensue is what
will happen as a consequence. A struggle might ensue if a thief grabs
a purse, and a discussion might ensue if two sides disagree.

The humor here plays off the norm against racism. After Mary’s setup, John starts
to squirm uncomfortably, afraid his friend is about to tell an offensive joke. But
when Mary delivers the punchline, it’s sweet, safe relief. She wasn’t telling a
racist joke after all. She was just playing! And a hearty chuckle ensues.42
* tamping :Elephant:
[2022-01-28 Fri 11:30]

To tamp is to push or pack down a loose or granular material. If you
work as a barista, you'll learn to tamp espresso grounds before
running hot water through them.

Before a road is paved or a patio is laid out, workers will tamp
gravel to provide a sturdy, level base. Old-fashioned, muzzle-loading
guns had to be filled with gunpowder, which the user would need to
tamp firmly before firing. The tool used to do the tamping is
sometimes also called a tamp.

A real danger of laughter, then, is the fact that we don’t all share the same norms
to the same degree. What’s sacred to one person can be an object of mere play to
another. And so when we laugh at norm violations, it often serves to weaken the
norms that others may wish to uphold. This helps explain why people charged with
maintaining the highest standards of propriety—schoolmarms, religious leaders, the
guardians in Plato’s Republic, the Chinese officials who banned puns in 201443—have
an interest in tamping down on laughter and humor.
* tantamount :DarkPersuasion:
[2022-01-28 Fri 11:37]

When something is tantamount to another thing it is essentially its
equivalent. For some animal activists, wearing fur is tantamount to
murder.

Tantamount often refers to an action or thing being compared to
another greater action or quality, as in, “Missing your finals is
tantamount to dropping out of college.” While the two sides are
essentially equal, you would not say, "Dropping out of school is
tantamount to missing your finals.” A related word is paramount, which
means “the highest” or “primary.”

Algebraically, therefore, the slightest opposition to the regime, or failure to
report such opposition, was tantamount to terrorism.”20
* beleaguered :DarkPersuasion:
[2022-01-28 Fri 11:37]

Beleaguer means to pester or badger with persistence. A babysitter
might find annoying the children who beleaguer her with requests for
candy, cookies, games, and piggyback rides all at the same time.

Beleaguer originally meant to lay siege to, and originates from a 16th
century Dutch term which meant to camp all around. It was not until
later that beleaguer came to mean harass or bother in a determined
way. Remember that there is a league in the middle of be-league-r and
the spelling will be easy.

In this context of a disastrous economy and a beleaguered state, public trials of
traitors were enormous media events that served as an excellent distraction from
the country’s troubles. There was no pretense of dispassionate inquiry. Instead,
the courtrooms were decked out in banners reading “TO THE MAD DOGS—A DOG’S
DEATH.”21 Courtroom observers reported extraordinary, bizarre confessions, and
speculated that the Soviets had mastered some secret technique for persuading
defendants to incriminate themselves. Many suspected that this was Pavlov’s
handiwork, and from the show trials of the 1930s to today, Pavlov’s name is
associated with brainwashing.
* bewildered :DarkPersuasion:
[2022-01-31 Mon 13:14]

If a conversation about quantum mechanics leaves you feeling
bewildered, or lost and befuddled, don't feel bad: physics is a
baffling and confusing subject.

Be- + wildered = "thoroughly gone astray, into the wild," which is
pretty much what our minds do when we don't understand something, when
we don't even come close to understanding it. If you're bewildered,
you are confused on a whole new level. You may even find your
confusion confusing. Great synonyms for this word include at sea,
bemused, confounded, and mixed-up.

Whenever I analyzed the blue-collar workers I found that the fraction σ of them
were stupid. As σ’s value was higher than I expected (First Law), paying my tribute
to fashion I thought at first that segregation, poverty, lack of education were to
be blamed. But moving up the social ladder I found that the same ratio was
prevalent among the white-collar employees and among the students. More impressive
still were the results among the professors. Whether I considered a large
university or a small college, a famous institution or an obscure one, I found that
the same fraction σ of the professors were stupid. So bewildered was I by the
results that I made a special point to extend my research to a specially selected
group, to a real elite, the Nobel laureates. The result confirmed Nature’s supreme
powers: σ fraction of the Nobel laureates were stupid.
* veracity :Stupidity:
[2022-01-31 Mon 13:16]

Veracity sounds like some kind of disease you don't want to catch, but
in fact, it means truthfulness. If you question the veracity of a
statement or story, you wonder whether it is truthful or accurate.

Veracity is linked to the adjective veracious or "truthful." But don't
confuse veracious with voracious. A voracious person eats very large
amounts of food. If you were veracious, or "truthful," you'd tell them
they look fat.

This idea was hard to accept and digest, but too many experimental results proved
its fundamental veracity. The Second Basic Law is an iron law, and it does not
admit exceptions. The Women’s Liberation Movement will support the Second Basic
Law; as it shows that stupid individuals are proportionally as numerous among men
as among women. The “developing” of the “Third World” will probably take solace in
the Second Basic Law as they can find in it the proof that after all the developed
are not so developed. Whether the Second Basic Law is liked or not, however, its
implications are frightening: the law implies that whether you move in
distinguished circles or you take refuge among the headhunters of Polynesia,
whether you lock yourself in a monastery or decide to spend the rest of your life
in the company of beautiful and lascivious women, you always have to face the same
percentage of stupid people—which percentage (in accordance with the First Law)
will always surpass your expectations.
* solace :Stupidity:
[2022-01-31 Mon 13:17]

If something eases your disappointment or grief, consider it a
solace. If you're sad, you might find solace in music or in talking to
your friends.

It is no surprise that consolation and solace are similar in meaning
as they share a root in the Latin verb sōlārī, "to comfort." In fact,
solace and consolation are synonyms meaning "relief from grief or
disappointment." When you go to sleepaway camp, your parents will miss
you, but they'll find solace in knowing that you are having fun.

This idea was hard to accept and digest, but too many experimental results proved
its fundamental veracity. The Second Basic Law is an iron law, and it does not
admit exceptions. The Women’s Liberation Movement will support the Second Basic
Law; as it shows that stupid individuals are proportionally as numerous among men
as among women. The “developing” of the “Third World” will probably take solace in
the Second Basic Law as they can find in it the proof that after all the developed
are not so developed. Whether the Second Basic Law is liked or not, however, its
implications are frightening: the law implies that whether you move in
distinguished circles or you take refuge among the headhunters of Polynesia,
whether you lock yourself in a monastery or decide to spend the rest of your life
in the company of beautiful and lascivious women, you always have to face the same
percentage of stupid people—which percentage (in accordance with the First Law)
will always surpass your expectations.
* elucidate :Stupidity:
[2022-01-31 Mon 13:18]

If you elucidate something, you explain it very clearly. If you don't
understand fractions, a visit to the pie shop may elucidate the
subject for you.

Elucidate, meaning "to make clear," is from the Late Latin elucidare,
from the Latin prefix e-, "thoroughly," and lucidus, "clear, bright."
See the word lucid in elucidate? That's an adjective which describes
someone who thinks clearly or something that is clear enough to
understand.

At this point it is imperative to elucidate the concept of human stupidity and to
define the dramatis personae.