-*- coding: utf-8 -*-

* commence :Dahl:
[2022-12-02 Fri 19:57]

Commence is a fancy way of saying "begin." Your invitation to a formal
wedding might note, "The ceremony will commence at noon."

If a congressman wants to start a meeting to vote on an important
bill, he might say, "This meeting will begin immediately." Or, he
could make the same statement in a more formal way by saying, "This
meeting will commence immediately." Interestingly enough, while the
word commence means to start, a commencement ceremony marks the end of
a college career.

commence
* derisive :Dahl:
[2022-12-02 Fri 20:02]

Use the adjective derisive to describe something or someone that
mocks, expresses contempt, or ridicules. You may sometimes catch your
kids making derisive comments — especially if you ask them to do
chores instead of whatever they think is more important.

Derisive comes from the Latin word deridere, meaning "to ridicule,"
and is from the roots de-, which means "down," and ridere, which means
"to laugh." The adjective derisory comes from the same Latin word, but
it has a different sense. If you say something derisive, you show
contempt or ridicule, as in a derisive glare at your noisy
neighbors. If you say something is derisory, you mean it invites or
deserves ridicule or contempt, especially if it is laughably small,
such as a derisory diamond chip in an engagement ring.

derisive
    adj 1: abusing vocally; expressing contempt or ridicule;
           "derisive laughter"; "a jeering crowd"; "her mocking
           smile"; "taunting shouts of `coward' and `sissy'" [syn:
           derisive, gibelike, jeering, mocking, taunting]
* Trial                                                                :Dahl:
[2022-12-02 Fri 20:03]

When you run a series of tests on something, it's called a trial. If
you invent a computer game and want to run it through a trial before
releasing it, you might hire a bunch of teenagers to play it.

A trial is also a court hearing to legally determine the result of a
particular case. If your cousin is arrested for stealing her
neighbor's dog, she may be put on trial. This term can also be used
more generically, especially to talk about something being tried in
the court of public opinion. The fate of music education is on trial
in many school districts facing budget cuts.

1. Trial; attempt; essay. [Obs.] --Chaucer.
* mugging :Dahl:
[2022-12-02 Fri 20:04]



nil

mugging
    n 1: assault with intent to rob
* abstruse :Dahl:
[2022-12-02 Fri 20:09]

Abstruse things are difficult to understand because they are so deep
and intellectually challenging. It might be hard to figure out how a
toilet flushes but the technology that goes into making the Internet
function is abstruse.

The Latin roots of the word abstruse are about concealing or hiding
something, which is a good way to remember the meaning of this
word. It is useful when describing something that is overly confusing,
or if someone is deliberately making a story or a situation more
complicated than necessary. It sounds and looks like obtuse, but
abstruse is almost its opposite. Obtuse is dull or lacking a sharpness
of intellect. While Abstruse is president of the chess club, Obtuse is
hanging out by the parking lot smoking cigarettes.

abstruse
    adj 1: difficult to penetrate; incomprehensible to one of
           ordinary understanding or knowledge; "the professor's
           lectures were so abstruse that students tended to avoid
           them"; "a deep metaphysical theory"; "some recondite
           problem in historiography" [syn: abstruse, deep,
           recondite]
* Secern :Dahl:
[2022-12-02 Fri 20:11]



nil

Secern \Se*cern"\, v. t. [imp. & p. p. Secerned; p. pr. & vb.
* daisy :Dahl:
[2022-12-04 Sun 13:01]

A daisy is a cheerful white flower with yellow in the center. Drive
through the countryside in mid-summer and you can often see whole
fields full of daisies.

Daisies grow wild in many places, and they're also cultivated in
gardens as a perennial, a plant that returns year after year. One
invasive variation is called a "lawn daisy" because it quickly and
easily takes over grassy lawns and is notoriously hard to mow
down. The word daisy comes from day's eye, an informal name that arose
from the flower's habit of closing its petals when the sun goes down
at the end of the day.

So she was considering in her own mind (as well as she could, for the
hot day made her feel very sleepy and stupid), whether the pleasure
of making a daisy-chain would be worth the trouble of getting up and
picking the daisies, when suddenly a White Rabbit with pink eyes ran
close by her.
* dipped :Dahl:
[2022-12-04 Sun 13:02]



nil

The rabbit-hole went straight on like a tunnel for some way, and then
dipped suddenly down, so suddenly that Alice had not a moment to
think about stopping herself before she found herself falling down a
very deep well.
* curtsey :Dahl:
[2022-12-04 Sun 13:08]

A curtsey is a feminine version of a formal bow, a head-dipping,
knee-bending gesture of greeting. A woman might curtsey when meeting a
Queen.

You show respect when you curtsey, but it's so formal that it isn't
often necessary in most cultures. When a woman meets a member of
royalty — like a prince or an empress — it's appropriate for her to
curtsey. Figure skaters and some dancers also do a ceremonial curtsey
at the end of a performance. A more common way to spell it is curtsy —
both versions come from the root word courtesy, which you show when
you curtsey.

Presently she began again. “I wonder if I shall fall right through
the earth! How funny it’ll seem to come out among the people that
walk with their heads downward! The Antipathies, I think—” (she was
rather glad there was no one listening, this time, as it didn’t sound
at all the right word) “—but I shall have to ask them what the name
of the country is, you know. Please, Ma’am, is this New Zealand or
Australia?” (and she tried to curtsey as she spoke—fancy curtseying
as you’re falling through the air! Do you think you could manage it?)
