-*- coding: utf-8 -*-


* adhering :SmartNotes:
[2022-04-20 Wed 09:22]

If you don't want monkey droppings to adhere to the sole of your shoe,
watch where you’re walking. Maybe if you'd adhere, or stick to, the
zoo rules and stay on the walking path, you wouldn't have to worry
about it.

Adhere is from the 15th-century French verb meaning "to stick." Things
that are sticky will adhere, or attach, to surfaces and stay there,
whether you want them to or not; in other words, they're adhesive, an
adjective that comes from the same Latin source as the French
verb. When a person chooses to adhere to something, it is more of a
choice to stick with it or agree to abide by rules or guidelines. You
can also adhere by being loyal, as when you adhere to the high moral
standards or behavior expected of some organization.

A typical mistake is made by many diligent students who are adhering
to the advice to keep a scientific journal. A friend of mine does not
let any idea, interesting finding or quote he stumbles upon dwindle
away and writes everything down. He always carries a notebook with him
and often makes a few quick notes during a conversation. The advantage
is obvious: No idea ever gets lost. The disadvantages are serious,
though: As he treats every note as if it belongs to the “permanent”
category, the notes will never build up a critical mass. The
collection of good ideas is diluted to insignificance by all the other
notes, which are only relevant for a specific project or actually not
that good on second sight. On top of that, the strict chronological
order does not offer any help to find, combine or rearrange ideas in a
productive sense. It is not surprising that my friend has a bookshelf
filled with notebooks full of wonderful ideas, but not a single
publication to show.
* dilute                                                         :SmartNotes:
[2022-04-20 Wed 09:22]

A typical mistake is made by many diligent students who are adhering
to the advice to keep a scientific journal. A friend of mine does not
let any idea, interesting finding or quote he stumbles upon dwindle
away and writes everything down. He always carries a notebook with him
and often makes a few quick notes during a conversation. The advantage
is obvious: No idea ever gets lost. The disadvantages are serious,
though: As he treats every note as if it belongs to the “permanent”
category, the notes will never build up a critical mass. The
collection of good ideas is diluted to insignificance by all the other
notes, which are only relevant for a specific project or actually not
that good on second sight. On top of that, the strict chronological
order does not offer any help to find, combine or rearrange ideas in a
productive sense. It is not surprising that my friend has a bookshelf
filled with notebooks full of wonderful ideas, but not a single
publication to show.

* mingle :SmartNotes:
[2022-04-20 Wed 09:29]

When things mingle, that means they mix together while still retaining
their individual qualities. At a club you may hear laughter that seems
to mingle with the sound of the band playing in the background.

Mingle often describes abstract things, like smells or tastes or
feelings. The look on your face may mingle compassion and horror when
you taste your brother’s attempt at making Key Lime Pie. Mingle can
also describe what you do at a social gathering when you move around a
lot and talk to many different people. If you’re an outgoing person,
at a party you probably like to mingle and talk to friends and also
chat with new people.

What all these category-confusing approaches have in common is that
the benefit of note-taking decreases with the number of notes you
keep. More notes will make it more difficult to retrieve the right
ones and bring related ones together in a playful way. But it should
be just the opposite: The more you learn and collect, the more
beneficial your notes should become, the more ideas can mingle and
give birth to new ones – and the easier it should be to write an
intelligent text with less effort.
