-*- coding: utf-8 -*-


* renowned :48:
[2023-05-20 Sat 11:33]

Celebrated, gushed over, and even legendary, something that's renowned
is really famous. If you not only find a cure for cancer, but you also
go on lots of talk shows so everyone knows who you are, then you'll be
a renowned scientist.

Renown comes from the Anglo-Norman for "re-name," as in repeatedly
name, so something is renowned is something that people are talking
about, or naming, over and over. If you are a huge celebrity, people
from your home town might boast, "The renowned Madame X was born
here." Something renowned is really good, not just famous. Just
because you make the cover of a trashy tabloid magazine doesn't mean
you're a renowned actress. But if you win an Oscar, you are.

In 1971, during the Vietnam War, Henry Kissinger was the target of an
unsuccessful kidnapping attempt, a conspiracy involving, among others,
the renowned antiwar activist priests the Berrigan brothers, four more
Catholic priests, and four nuns.

* pauper :48:
[2023-05-20 Sat 11:33]

Pauper is an old-fashioned word for someone who is poor — really poor,
like the paupers described by Charles Dickens or Mark Twain.

The noun pauper has been around for over 500 years, but today, the
word tends to mostly crop up in literature. If people use it in
conversation, they tend to use the word self-deprecatingly. "I'm
sorry, I can't afford to go with you to the movies. I'm living like a
pauper this week, until I get paid."

No pauper is friend to the rich, no fool to the wise, no coward to
thebrave.

* ploy :48:
[2023-05-20 Sat 11:35]

A ploy is a clever plan that helps you get what you want. A
manipulative little girl might shed tears simply as a ploy to get her
mother to buy her ice cream.

A politician might add amendments to a bill as a ploy to delay voting,
or a hooligan might yell, "Fire!" in a movie theater as a ploy to
sneak his friends in. A sneaky move in a game is a ploy, and
sensational news about a celebrity can be just a ploy to get him more
media attention. The first recorded use of ploy was in 1722, meaning
"anything with which one amuses oneself" in Scottish and Northern
English dialects.

This was not just a onetime ploy: Kissinger made a policy of working
with those who disagreed with him.

* ragtag :48:
[2023-05-20 Sat 11:37]

A ragtag is a disorganized or motley group of people. When a parade
marching band is described as a ragtag, it probably has mismatched
outfits and an odd collection of instruments.

The noun ragtag comes from the old-fashioned phrase rag, tag, and
bobtail — bobtail was once slang for "contemptible rascal," while tag
was used to mean "torn cloth." Together, the phrase meant "riffraff"
or "an unsavory bunch of folks." Today, you're more likely to see
ragtag used as an adjective, as it is in the musical "Hamilton," in
which the Continental Army is described as "a ragtag volunteer army in
need of a shower."

To fight a formidable foe like the Japanese, in fact, would be the
perfect training for the Communists’ ragtag army.

* awry :48:
[2023-05-20 Sat 12:01]

When something goes wrong with a decent plan, you say it has gone
awry. Losing your backpack is a mistake, but when you realize it
contained your ticket and your passport, your vacation plans really go
awry.

Wry means "twisted" — so going awry means getting "twisted up." Awry
is similar to askew, which means "off, out of line." Though when you
compare the roots skew, "turned at an angle" and wry, "twisted," you
see the subtle difference between the two words.

Also, if your plans go awry for some reason, you can use a friend as
a convenient scapegoat.

* venture :48:
[2023-05-20 Sat 12:03]

A venture is a risky undertaking. If your latest venture is a dog food
store, you hope there are some hungry dogs around. Also, to venture is
to go somewhere possibly dangerous, like if you venture out into a
snowstorm.

Venture is a shortened form of adventure. This happened sometime
between 1100 CE and 1400 CE during the time that Middle English was
spoken. While the two words are similar in meaning, when you subtract
the ad, you lose a teaspoon or two of fun, and add a heaping
tablespoon of risk.

You must never let your guard down in such a venture, however; always
be on the lookout for any signs of emotional disturbance such as envy
and ingratitude.

* lookout :48:
[2023-05-20 Sat 12:04]

The neighborhood kids might use a tree house as a lookout, from which
they can keep an eye out for the local bully.

A lookout is usually so high that a person can see for a long distance
in many directions when she stands on or in it. Armies sometimes use
lookouts to scout for approaching troops, and navy ships include a
lookout at the top of a tall mast, also called a "crow's nest."
Lookout can also be spelled as a hyphenated word, "look-out," and used
as well to refer to the person whose job it is to stay in the lookout
and keep watch.

You must never let your guard down in such a venture, however; always
be on the lookout for any signs of emotional disturbance such as envy
and ingratitude.

* dashing :48:
[2023-05-20 Sat 12:10]

Someone who's dashing is stylish, with a certain bold, attractive
spirit. Your dashing uncle might charm and impress your friends with
his stories of travels around the world and his fashionable outfits.

Characters in old books are frequently dashing — adventurous and
gallant, like a dashing hero on a white horse or a dashing pirate
seeking his fortune at sea. The adjective dashing is almost always
used to describe men, and for that reason it's a bit old-fashioned. In
the 18th and 19th centuries "to cut a dash" meant "to act brilliantly"
or "to give a showy appearance," and dashing came from this meaning.

Ninon was sixty-two at the time, and more than experienced in matters
of love; the marquis was a lad of twenty-two, handsome, dashing, but
hopelessly inexperienced in romance.

* nonchalance :48:
[2023-05-20 Sat 12:11]

Nonchalance is a casual lack of concern, a relaxed state without
anxiety or enthusiasm.  Like how you'd act if the girl you've had a
secret crush on since grade school asks you to the prom.  (Or maybe
not.)

It's hard to achieve nonchalance. If you're like most people, there's
always going to be something that will rattle you.  And you can forget
about behaving with chalance, because chalance isn't a word. Sometimes
you hear people say that so-and-so acted with "studied nonchalance,"
which means to sort of fake it. Oddly, the word's origins go back to
the Latin calere, which is the same word as the root of calorie.  A
calorie is a unit of energy, and to act with nonchalance is to refrain
from showing too much energy or excitement, so actually, it makes
sense.

Instructing the marquis to start over, Ninon told him to approach the
countess with a bit of distance, an air of nonchalance.

* seething :48:
[2023-05-20 Sat 12:13]

Seething describes anger you can barely contain. If you are seething
and something sets you off, you just might explode into a rage.

Someone who's seething with anger is furious but keeping it a
secret. Maybe someone insulted you in front of others and you want to
let it go — on the inside, though, you might be seething. Or during
the big game, an opponent's harsh words can have you seething, but you
want to stay focused on scoring points. Seething sometimes describes
something that's boiling over, like a seething pot of soup, and this
is also the root of the word.

This beautiful young woman had equally beautiful friends, so that
wherever the countess would now see the marquis, he would be
surrounded by the most stunning young women in Paris. Not only would
the countess be seething with jealousy, she would come to see the
marquis as someone who was desired by others. It was hard for Ninon
to make the marquis understand, but she patiently explained that a
woman who is interested in a man wants to see that other women are
interested in him, too. Not only does that give him instant value, it
makes it all the more satisfying to snatch him from their clutches.
* beguile :48:
[2023-05-20 Sat 12:14]

To beguile is to entertain and convince by flattery. Someone who
beguiles is tricky and often charming, like when a smooth-talking
friend tries to beguile you into giving them your allowance.

The word beguile is from Middle English, and while guile involves
deceit, to beguile means to spend time pleasantly, even if it involves
trickery. If someone beguiles you for an afternoon, you were amused,
entertained, or otherwise pleased. The word can also have a darker
tone, as when the person who beguiled you for the afternoon was
actually trying to steal your car. Con artists and cat videos tend to
beguile people.

Once the countess was jealous but intrigued, it would be time to
beguile her. On Ninon’s instructions, the marquis would fail to show
up at affairs where the countess expected to see him. Then, suddenly,
he would appear at salons he had never frequented before, but that
the countess attended often. She would be unable to predict his
moves. All of this would push her into the state of emotional
confusion that is a prerequisite for successful seduction.
* prerequisite :48:
[2023-05-20 Sat 12:15]

A prerequisite is a required prior condition. If something is required
in advance of something else, like if you have to take a beginning
Spanish class before signing up for Spanish II, then it’s a
prerequisite.

Add pre meaning "before" to require and you have something that's
"required before." (That's helpful when trying to spell prerequisite!)
Prerequisites to be able to graduate from college can seem like a
pain, but most schools offer some fun ways to fulfill them. For
example, you can often meet the physical education prerequisite by
taking bowling.  Prerequisites aren't just for school: “The most
called-upon prerequisite of a friend is an accessible ear,” said Maya
Angelou, the American poet.

Once the countess was jealous but intrigued, it would be time to
beguile her. On Ninon’s instructions, the marquis would fail to show
up at affairs where the countess expected to see him. Then, suddenly,
he would appear at salons he had never frequented before, but that
the countess attended often. She would be unable to predict his
moves. All of this would push her into the state of emotional
confusion that is a prerequisite for successful seduction.
* spell :48:
[2023-05-20 Sat 12:53]

A spell is a series of words that has magical powers. If you’re under
a spell, then what you do is out of your control — your thoughts and
actions are dictated by the spell.

Spell can refer to the magic words you say, or it can describe being
under the influence of those words. You probably don’t encounter many
magic spells in real life, but the word is often used figuratively to
describe those times when you feel like a magical power controls your
action. Of course, this word can also mean the verb "to spell" which
refers to reciting the letters in a word, like the competitive
spellers in a spelling bee.

The spell was broken.
* feign :48:
[2023-05-21 Sun 11:23]

For a more formal way to say pretend to or imitate, choose the verb
feign. You might feign indifference when you hear about some gossip,
but you're probably dying to know.

Feign comes from the Latin fingere "to devise, fabricate." The word
fiction comes from the same source, so if you feign something such as
sleep, you give off the fiction that you are sleeping. This can be
done to be polite but also to deceive such as when you feign an injury
or the flu so you can stay home from school or work. You can also
feign an accent, though some are better at this than others.

Ninon knew that men and women are very different, but when it comes
to seduction they feel the same: Deep down inside, they often sense
when they are being seduced, but they give in because they enjoy the
feeling of being led along. It is a pleasure to let go, and to allow
the other person to detour you into a strange country. Everything in
seduction, however, depends on suggestion. You cannot announce your
intentions or reveal them directly in words. Instead you must throw
your targets off the scent. To surrender to your guidance they must
be appropriately confused. You have to scramble your signals—appear
interested in another man or woman (the decoy), then hint at being
interested in the target, then feign indifference, on and on. Such
patterns not only confuse, they excite.
* ulterior :48:
[2023-05-21 Sun 11:24]

An ulterior interest, argument, or revelation is one you try to keep
hidden, like your ulterior motive for weeding your grandmother's
garden is to have a conversation with your crush — and Grandma's
neighbor — who happens to be outside, too.

The adjective ulterior is a Latin word which means “more distant” or
“future.” Something that is ulterior may lay the groundwork for what
comes later, like a new friend who hangs out with you at your house
but whose ulterior motive is to date one of your siblings, or the
incredible popularity of a series of novels set in a real place having
the ulterior consequences of that place becoming a tourist
destination.

Imagine this story from the countess’s perspective: After a few of
the marquis’s moves, she sensed the marquis was playing some sort of
game, but the game delighted her. She did not know where he was
leading her, but so much the better. His moves intrigued her, each of
them keeping her waiting for the next one—she even enjoyed her
jealousy and confusion, for sometimes any emotion is better than the
boredom of security. Perhaps the marquis had ulterior motives; most
men do. But she was willing to wait and see, and probably if she had
been made to wait long enough, what he was up to would not have
mattered.
* conniving :48:
[2023-05-21 Sun 11:24]

Someone conniving is calculating, scheming, and shrewd — in other
words, sneaky and up to no good.

Do you know anyone who is always trying to get away with things? Do
they constantly look for ways to get out of trouble or work? Those
kind of people are conniving. This is a word for secretive, shifty
behavior. However, being conniving isn't the worst thing in the world
— it's negative, but you probably wouldn't say a murderer is
conniving. It's usually reserved for con men, shady business moguls,
and manipulative social climbers.

This put everything he had done in a new light. All that before had
been charming now seemed ugly and conniving; the countess felt
embarrassed and used. A door closed that would never open again.
* appease :48:
[2023-05-21 Sun 11:25]

Appease means to make or preserve peace with a nation, group, or
person by giving in to their demands, or to relieve a problem, as in
"the cold drink appeased his thirst."

Appease often implies abandoning your moral principles to satisfy the
demands of someone who is greedy for power: think of British Prime
Minister Chamberlain's attempt to appease the Nazis at Munich. The
verb appease comes from the Old French apaisier, "to pacify, make
peace, or be reconciled," from the phrase "a paisier," which combines
a-, or "to," and pais, "peace," from the Latin pax.

In 1850 the young Otto von Bismarck, then a thirty-five-year-old
deputy in the Prussian parliament, was at a turning point in his
career. The issues of the day were the unification of the many states
(including Prussia) into which Germany was then divided, and a war
against Austria, the powerful neighbor to the south that hoped to
keep the Germans weak and at odds, even threatening to intervene if
they tried to unite. Prince William, next in line to be Prussia’s
king, was in favor of going to war, and the parliament rallied to the
cause, prepared to back any mobilization of troops. The only ones to
oppose war were the present king, Frederick William IV, and his
ministers, who preferred to appease the powerful Austrians.
* infamous :48:
[2023-05-21 Sun 11:26]

Someone who is infamous has a very bad reputation. If you become a
Hollywood star and find yourself on the pages of gossip magazines for
your affairs and addictions, you will have succeeded in becoming
infamous.

Infamous is from Latin infamis, for negative fame. If you're bad but
unknown, then you're not infamous — it's reserved for those wicked and
well-known people that capture our collective imagination.  It is a
strong and resonant term. Some synonyms are notorious, disgraceful,
and odious. The stress is on the first syllable.

A few weeks after Bismarck’s infamous speech, the king, grateful that
he had spoken for peace, made him a cabinet minister. A few years
later he became the Prussian premier. In this role he eventually led
his country and a peace-loving king into a war against Austria,
crushing the former empire and establishing a mighty German state,
with Prussia at its head.
* attained :48:
[2023-05-22 Mon 18:50]

By being completely insincere and sending misleading
signals, however, he deceived everyone, concealed his
purpose, and attained everything he wanted. Such is the
power of hiding your intentions.
* gewgaw                                                               :48:
[2023-05-22 Mon 18:54]

A gewgaw is a little ornament or piece of jewelry. Gewgaws are cheap
and don't have any purpose besides decoration.

* dangle :48:
[2023-05-23 Tue 15:00]

Dangle means to hang or swing loosely. If you dangle string above a
kitten you will both be entertained.

The verb dangle probably comes from a late 16th century Danish or
Swedish word meaning “loose or pendulous,” though we don’t know for
sure. You may have a taste for big, showy earrings that dangle. Or,
you might even dangle a possibility — "If you were to dangle the
prospect of dessert to a child, then you better follow through!"

Basic to an ability to conceal one’s intentions is a simple
truth about human nature: Our first instinct is to always
trust appearances. We cannot go around doubting the reality
of what we see and hear—constantly imagining that
appearances concealed something else would exhaust and
terrify us. This fact makes it relatively easy to conceal
one’s intentions. Simply dangle an object you seem to
desire, a goal you seem to aim for, in front of people’s
eyes and they will take the appearance for reality. Once
their eyes focus on the decoy, they will fail to notice
what you are really up to. In seduction, set up conflicting
signals, such as desire and indifference, and you not only
throw them off the scent, you inflame their desire to
possess you.
* apparent :48:
[2023-05-23 Tue 15:00]

Apparent means obvious, but — and this is confusing — it can also mean
something that seems to be true but isn't definite. "The train's
arrival is apparent — it's in the station — but apparently my friend
missed it because she is not getting off."

It makes sense that apparent has the same ancient root as appear
because it's about what is plain to see. Its subtle power of
suggestion, however, is wonderfully useful. The "heir apparent"
technically means next in line, but the ink isn't dry. The power of
apparent is that it leaves the door open for a little ambiguity. Maybe
the heir apparent will be the next king, or maybe he'll be overthrown
in a bloodless coup by his apparently more ambitious cousin.

Another powerful tool in throwing people off the scent is
false sincerity. People easily mistake sincerity for
honesty. Remember—their first instinct is to trust
appearances, and since they value honesty and want to
believe in the honesty of those around them, they will
rarely doubt you or see through your act. Seeming to
believe what you say gives your words great weight. This is
how Iago deceived and destroyed Othello: Given the depth of
his emotions, the apparent sincerity of his concerns about
Desde mona’s supposed infidelity, how could Othello
distrust him? This is also how the great con artist Yellow
Kid Weil pulled the wool over suckers’ eyes: Seeming to
believe so deeply in the decoyed object he was dangling in
front of them (a phony stock, a touted racehorse), he made
its reality hard to doubt. It is important, of course, not
to go too far in this area. Sincerity is a tricky tool:
Appear overpassionate and you raise suspicions. Be measured
and believable or your ruse will seem the put-on that it
is.
* phony :48:
[2023-05-23 Tue 15:01]

Whether you're talking about your attitude, a gigantic diamond, or
that obnoxious guy's claims that he knows everything about quantum
physics, you can use phony to say that something’s not real.

Use the adjective phony to describe anything that’s fake. If you’re
making phony money in the basement, you’ll be in trouble if you get
caught using it. Phony has a noun version with a similar meaning. If
you say someone or something is a phony, then you’re saying it isn’t
what it pretends to be. Someone who’s a phony isn’t sincere, like your
classmate who pretended to be your best friend just to try to steal
your boyfriend.

Another powerful tool in throwing people off the scent is
false sincerity. People easily mistake sincerity for
honesty. Remember—their first instinct is to trust
appearances, and since they value honesty and want to
believe in the honesty of those around them, they will
rarely doubt you or see through your act. Seeming to
believe what you say gives your words great weight. This is
how Iago deceived and destroyed Othello: Given the depth of
his emotions, the apparent sincerity of his concerns about
Desde mona’s supposed infidelity, how could Othello
distrust him? This is also how the great con artist Yellow
Kid Weil pulled the wool over suckers’ eyes: Seeming to
believe so deeply in the decoyed object he was dangling in
front of them (a phony stock, a touted racehorse), he made
its reality hard to doubt. It is important, of course, not
to go too far in this area. Sincerity is a tricky tool:
Appear overpassionate and you raise suspicions. Be measured
and believable or your ruse will seem the put-on that it
is.
* ruse :48:
[2023-05-23 Tue 15:01]

Movie bank robbers always seem to pull some kind of ruse, a deceptive
trick or tactic like hiding the money underneath the bank while they
drive off in the getaway car to avoid capture by the police.

You'd use a ruse if you were up to something sneaky and were trying to
get away with it without being discovered. The wife planning a
surprise birthday party for her husband could send him out to the
supermarket as a ruse, a trick so she could sneak one hundred of his
closest friends into the house without him noticing.

Another powerful tool in throwing people off the scent is
false sincerity. People easily mistake sincerity for
honesty. Remember—their first instinct is to trust
appearances, and since they value honesty and want to
believe in the honesty of those around them, they will
rarely doubt you or see through your act. Seeming to
believe what you say gives your words great weight. This is
how Iago deceived and destroyed Othello: Given the depth of
his emotions, the apparent sincerity of his concerns about
Desde mona’s supposed infidelity, how could Othello
distrust him? This is also how the great con artist Yellow
Kid Weil pulled the wool over suckers’ eyes: Seeming to
believe so deeply in the decoyed object he was dangling in
front of them (a phony stock, a touted racehorse), he made
its reality hard to doubt. It is important, of course, not
to go too far in this area. Sincerity is a tricky tool:
Appear overpassionate and you raise suspicions. Be measured
and believable or your ruse will seem the put-on that it
is.
* espouse :48:
[2023-05-23 Tue 15:02]

Use the verb espouse to describe the actions of someone who lives
according to specific beliefs, such as your friends who espouse
environmentalism and as a result walk whenever possible instead of
taking the car.

You can see the word spouse in espouse, so you may be wondering what
husbands and wives have to do with it. Originally espouse did mean "to
marry," but its meaning has evolved to include other long-term
commitments as well, such as support for a principle or a
cause. Similar to marriage, if you espouse a belief system, the idea
is that you've chosen to wed yourself to it.

To make your false sincerity an effective weapon in
concealing your intentions, espouse a belief in honesty and
forthrightness as important social values. Do this as
publicly as possible. Emphasize your position on this
subject by occasionally divulging some heartfelt
thought—though only one that is actually meaningless or
irrelevant, of course. Napoleon’s minister Talleyrand was a
master at taking people into his confidence by revealing
some apparent secret. This feigned confidence—a decoy—would
then elicit a real confidence on the other person’s part.
* heartfelt :48:
[2023-05-23 Tue 15:03]

If something is heartfelt, it's sincere and warm. It's clear from your
elderly neighbor's heartfelt invitation that she genuinely wants you
to come over for tea and cookies.

When you're profoundly grateful to your favorite teacher, you'll offer
her your heartfelt thanks. And when your best friend's dog dies,
you'll give him your heartfelt sympathy. Things that are heartfelt are
deeply emotional, believed or felt very strongly. The word dates from
the 18th century, from heart, with its Old English root heorte,
"heart, spirit, or mind."

To make your false sincerity an effective weapon in
concealing your intentions, espouse a belief in honesty and
forthrightness as important social values. Do this as
publicly as possible. Emphasize your position on this
subject by occasionally divulging some heartfelt
thought—though only one that is actually meaningless or
irrelevant, of course. Napoleon’s minister Talleyrand was a
master at taking people into his confidence by revealing
some apparent secret. This feigned confidence—a decoy—would
then elicit a real confidence on the other person’s part.
* roguish :48:
[2023-05-23 Tue 15:03]

To be roguish is to be up to no good, which could mean being
untrustworthy like a criminal or playful and mischievous. If someone
gives you a roguish smile, he’s totally flirting with you.

You can't trust someone who acts roguish in the bad way, like the
roguish crook who picks your pocket while telling you how lovely you
look. On the other hand, you might like someone who acts roguish in
the second sense, which means playfully mischievous. Being roguish in
this way might mean playing pranks, telling racy jokes, and being a
little wild. Roguish behavior like this can still be annoying, like if
your roguish roommate at camp short-sheets your bed.

Remember: The best deceivers do everything they can to
cloak their roguish qualities. They cultivate an air of
honesty in one area to disguise their dishonesty in others.
* grudge :48:
[2023-05-23 Tue 15:04]

If you tend to hold a grudge, you don't let it go when you feel
someone's insulted or wronged you.  I hope you won't hold a grudge
against me for bringing it up.

Grudge comes from the now dead Middle English word "grutch," which
meant "to complain or grumble."  Someone who bears a grudge might
often be grouchy.  You can specify a type of grudge: political grudge,
personal grudge, etc.  You know Grandpa's been holding a grudge
against the neighbors for years, but you have to wonder: How long can
he hold that shotgun?

For reasons—good reasons—of his own, the uncle had been nursing a
grudge against the millionaires for years; this was his chance to get
back at them.

* retribution :48:
[2023-05-23 Tue 15:04]

Retribution is the act of taking revenge. If you pull a prank on
someone, expect retribution.

Retribution comes from the Latin for giving back what's due, either
reward or punishment. But when we talk about retribution, we only talk
about punishment. The old punishment code of "an eye for an eye, a
tooth for a tooth," is an example of retribution. Some people think
about large events like tornados or earthquakes as cosmic retribution
for human pride. Some synonyms are compensation, recompense, requital.

It was all legal and for a good cause—the uncle’s just retribution.

* paunchy :48:
[2023-05-23 Tue 15:04]

Someone who's paunchy has a round belly. If you're more paunchy than
you used to be, you might want to invest in slightly larger, more
comfortable clothes.

This adjective is often used in a mildly derogatory way, to describe
someone who carries a bit of extra weight around their middle. Has
your vet put your dog on a diet? It might be because she's gotten a
little paunchy. The word comes from paunch, "round stomach," from a
root that simply means "belly or stomach."

Weil also brought along a companion, a somewhat paunchy man named
George Gross.

* flabby :48:
[2023-05-23 Tue 15:05]

If you're flabby, you're out of shape, with a soft, slack body. Some
people join a gym when they're feeling a little flabby.

People who are flabby aren't star athletes — you may be flabby after a
long, cold winter spent mostly indoors, or feel flabby as you struggle
to hike up a mountain. You can describe other things as figuratively
flabby too, if they're a little sloppy or weak. Flabby writing is
messy and disorganized, and a flabby politician is ineffective. Flabby
started as flappy, "softly fleshy," in the 16th century.

For a promising fighter, Gross was unimpressive looking—he had gray
hair and a beer belly—but Geezil was so excited about the deal that he
didn’t really think about the man’s flabby appearance.

* banter :48:
[2023-05-23 Tue 15:05]

Good friends usually banter back and forth easily, like they're trying
to keep a step ahead of each other in witty responses. This type of
banter is their special language of friendship.

Banter is both a noun and a verb about talking. It comes from unknown
origins, but even as a word, it seems to be playful and teasing. You
can engage in banter with friends, siblings, parents, and even
good-natured strangers. Banter usually ends with everyone feeling
better for the talk and verbal play. Joking, joshing, and teasing are
all related to banter.

This minor business now settled, the financiers sat back in their
chairs and began to banter about high finance, throwing out the name
“J. P. Morgan” as if they knew the man.

* entourage                                                            :48:
[2023-05-23 Tue 15:06]

You know that group of people — friends, assistants, bodyguards — that
are always surrounding you everywhere you go?  That's your entourage!

Entourage comes from the French word entourer, meaning “to surround,”
and means "the people who surround someone."  It's also pronounced
like a French word, ending with the soft sound “razh” (not “rage”):
"ON-too-razh."  The size of a pop star's entourage might grow with
every hit record she releases. You know you've really made it when
your entourage won't fit in one limo.

Weil explained what he was doing there. The financier countered that
he too had a boxer in his entourage, whom he named.

* glum :48:
[2023-05-23 Tue 15:07]

To be glum is to be sad. Glum is a word for being depressed, bummed
out, or down in the dumps.

People who are glum are sometimes said to be sullen, brooding, morose,
and moody. Glum folks don't smile, giggle, or laugh — and they're
rarely seen holding balloons. Being glum is a little more
outward-directed than just being sad. To be glum is to act sad in
front of other people, almost like you want them to ask, "Why so
glum?"


The financiers were looking glum at how badly their fighter was doing,
and Geezil was dreaming about the easy money he was about to make.

* con :48:
[2023-05-23 Tue 15:07]

A con, or confidence game, is a swindle — when you take advantage of
someone's trust.  If you con someone out of their life savings, you
might wind up a con — as in convict.

The word con has many meanings, none of them good.  An argument has
pros and cons, and the cons are always the downside. An ex-con is
someone who spent time in jail as a convict, and a con artist is
someone who scams people out of their money.

The whole affair had been masterminded by Weil, better known as “the
Yellow Kid,” one of the most creative con artists in history.

* adaptable :Lucy:
[2023-05-23 Tue 15:40]

Something that is adaptable can change to fit its environment, whether
that environment is natural or social. The level to which a species is
adaptable to changing surroundings is an important factor in the study
of evolution.

Let’s look at the Latin word adaptāre, from the root aptus "fitted."
The ad- means "to, while the aptare means "join." Since 15th-century
medieval French, the word adapt has come to mean "to fit in or
adjust." So something adaptable is something that "fits in or
adjusts." An example of an adaptable creature is the arctic fox, whose
fur changes from dirt-dark in summer to snow-white in winter, to
better blend in with its surroundings.

If somebody is an adaptable person, it means they are someone who is
able to change to successfully deal with new situations, especially
difficult ones.

* Affable :Lucy:
[2023-05-23 Tue 15:42]

Affable means friendly, pleasant, and easy to talk to. An affable host
offers you something to drink and makes you feel at home.

The adjective affable entered English by way of the Latin word
affābilis, which means "kind, friendly." If you’re stuck on an
airplane next to someone affable, the trip won’t be so bad because
that person will be easy to chat with but won’t talk your ear
off. Synonyms of affable also refer to a pleasant and mild
friendliness, such as genial, hospitable, and gracious. Affable people
generally seem like they’re in a good mood and are happy to see you.

Affable could
be used to describe somebody who is pleasant, polite, and easy to
talk to.
* ambitious :Lucy:
[2023-05-23 Tue 15:43]

Ambitious means wanting to succeed. If you want to climb Mount
Everest, start your own business, and write a great philosophical
treatise all before you are 30, then wow, you are really ambitious.

Having an ambition is a good thing, like wanting to get good grades,
or to become a doctor. But if we say someone is ambitious, often we
mean they have too much ambition. An ambitious politician might want
power so badly that he’ll abandon his ideals in order to win a
race. If you hatch a business plan and someone tells you it’s too
ambitious, that means you’re probably not being reasonable about how
much you can get done.

He's very ambitious and I think he'll
do very well in life.
* amicable :Lucy:
[2023-05-23 Tue 15:44]

The adjective amicable means "friendly" — but in particular, use it
when describing relations one might otherwise expect to be
unfriendly. The end of a romantic relationship that's less than
amicable might involve broken dishes or broken bones.

Amicable, not surprisingly, comes from the Latin word for "friend,"
amicus. Perhaps the things most commonly described as amicable are
divorces. The parties in a divorce often tend to be so childish and
the proceedings so messy that it's nice to have a word that reflects
the absence of those qualities. Other nouns that commonly pair with
amicable include relationship, split, parting, solution, and breakup.

He seemed very amicable on the telephone, so I was
shocked at his rude email.
* bright :Lucy:
[2023-05-23 Tue 15:45]

After a long, gray winter, it's hard to remember what a bright, sunny
day is like. Bright means shining with light.

The adjective bright is good for describing anything that emits,
reflects, or is full of light — like the bright moon, the bright sky
or the bright, well-lit room. Bright can also mean vivid or vibrant —
such as a bright purple three-piece suit. More figuratively, bright
means "full of hope or possibility" — like your bright future as a
marine biologist.

You're a bright
girl, I know you'll pass the exam.
* broad-minded :Lucy:
[2023-05-23 Tue 15:46]

Luckily, our boss is quite broad-minded, so I'm sure he won't mind you
wearing that today.

* conscientious :Lucy:
[2023-05-23 Tue 15:47]

If someone is conscientious, that person strives to do what's right
and to carry out her duties. Conscientious people show care and put in
a big effort.

Being conscientious has to do with being careful, thoughtful, and
decent. A conscientious doctor will do everything possible to help a
patient. A conscientious teacher will spend extra time with students,
just to make sure they're learning. A boss wishes every worker could
be conscientious: it's a rare and wonderful trait. To be
conscientious, you have to be willing to do the right thing even when
it's difficult. Unfortunately, many people aren't conscientious.

His conscientious manner
makes him a fantastic engineer.
* courteous :Lucy:
[2023-05-23 Tue 15:48]

If you are courteous, your good manners show friendliness and concern
for others, like your courteous habit of holding the door for people
entering a building with you.

The adjective courteous comes from the Old French word curteis, which
means “having courtly bearing or manners.” Courtly described the court
— nobles who hung around the castle, the entourage of kings and
queens. Their refined manners, not to mention their wealth and power,
set them apart from the masses. So courteous behavior is a reminder of
the value of good manners.

If
somebody is courteous, they are a respectful and polite person.
* decisive :Lucy:
[2023-05-23 Tue 15:49]

If you make decisions quickly, you are someone who is decisive. A
decisive event can settle something, like a war.

People who are wishy-washy are the opposite of decisive: being
decisive means you don't waffle or take forever to make up your mind,
and then you stick by what you decided. People admire politicians,
coaches, and friends who are decisive. In sports, if a home run won
the game, that was the decisive run. When you reach a crisis point in
life — when things are going to change one way or the other — you've
reached a decisive moment.

She's quite decisive, so I don't think she'll change her mind.
* convivial :Lucy:
[2023-05-23 Tue 15:49]

Use the adjective convivial to describe your friend who is "the life
of the party."

The Latin word convivium means "a feast," and when convivial was first
coined in the 1660s, its meaning related to the excess of food and
drink during such celebrations. You can also see convivial in
convivere, meaning "to carouse together." Just when it seemed all
convivial could ever do was describe people who overindulge, a new
shade of meaning emerged: loving to be around people. After all, a big
part of feasting is being with people you care about.

She was a convivial party
host who made everyone feel welcomed.
* determined :Lucy:
[2023-05-23 Tue 15:50]

Olympic athletes are some of the most determined people you're going
to meet. At that level, they've got to be driven to
succeed. Otherwise, their opponents will surely beat them.

If you want to reach your goal, you must be determined to do so. To be
determined is to be motivated, driven, or really focused on the task
at hand — and that can be something as big as winning a prize or as
small as fixing a squeaky door. No matter the task, the folks who get
the job done are almost always the most determined. Determined can
also mean "decided." For instance, a judge can determine what the
sentence will be. If that sentence is predetermined, then it's already
been decided.

Her determined nature made her the perfect Olympian.

* eudaimonia :misc:
[2023-05-24 Wed 12:22]

In works of Aristotle, eudaimonia was the term for the highest
human good in older Greek tradition. It is the aim of practical
philosophy-prudence, including ethics and political philosophy, to
consider and experience what this state really is, and how it can
be achieved. It is thus a central concept in Aristotelian ethics
and subsequent Hellenistic philosophy, along with the terms aretē
(most often translated as 'virtue' or 'excellence') and phronesis
('practical or ethical wisdom').[1]
* phronesis :misc:
[2023-05-24 Wed 12:27]

The Greek philosopher Aristotle (384 BCE – 322 BCE) wrote Nicomachean
Ethics, in which he defined personal development as a category of
phronesis or practical wisdom, where the practice of virtues (arête)
leads to eudaimonia,[21] commonly translated as "happiness" but more
accurately understood as "human flourishing" or "living well".[22]
Aristotle continues to influence the Western concept of personal
development to this day, particularly in the economics of human
development[23] and in positive psychology.[24][25]

* wry                                                             :sattelite:
[2023-05-25 Thu 12:30]

A wry sense of humor is a sarcastic one. You were late for work,
stepped into a mud puddle, and you forgot your lunch. If your
co-worker asks how your morning is going, you can reply with a wry
tone, "Perfectly perfect."

The original use for the adjective wry was to describe something that
was bent or twisted, so a sprained ankle could be described as "a wry
ankle." Today, the word wry is often used to describe less tangible
twists. Wry humor and wry wit both describe a sense of humor that is a
little twisted from the norm.

Wry means "twisted" — so going awry means getting "twisted up." Awry
is similar to askew, which means "off, out of line." Though when you
compare the roots skew, "turned at an angle" and wry, "twisted," you
see the subtle difference between the two words.

* rattle :sattelite:
[2023-05-25 Thu 12:41]

To rattle is to make a very rapid, short series of knocking or tapping
sounds. You might impatiently rattle the quarters in your pocket as
you await your turn at the pinball machine.

Ice cubes rattle in your glass of lemonade, and beads rattle in a
jar. Something else that rattles is a baby's rattle, a noisy toy
that's filled with small balls or pellets. Figuratively, to rattle
someone is to upset or irritate them, like the way a sudden
thunderstorm might rattle your timid poodle. Experts trace this word
back to the Middle Dutch ratelen, which they believe to be imitative
since it sounds a bit like a rattle.

It's hard to achieve nonchalance. If you're like most people, there's
always going to be something that will rattle you.

* furious :sattelite:
[2023-05-25 Thu 12:44]

If you've ever been so angry you'd swear you felt your blood boiling,
you could reasonably say that you were furious. The word basically
means "full of fury," so you get the picture.

Think about the angriest you've ever been. Now double it and you might
be getting close to furious, from the Latin furiōsus, meaning "full of
rage," which in turn comes from furia, "fury." Greek and Roman
mythology had the Furies, who dispensed justice by harshly punishing
criminals, sometimes driving them mad. They were merciless, fearsome,
and feared, with snakes for hair and bloody eyes. When not on earth,
they were tormenting the damned in Hell. Now, that's furious!

Someone who's seething with anger is furious but keeping it a
secret. Maybe someone insulted you in front of others and you want to
let it go — on the inside, though, you might be seething. Or during
the big game, an opponent's harsh words can have you seething, but you
want to stay focused on scoring points. Seething sometimes describes
something that's boiling over, like a seething pot of soup, and this
is also the root of the word.
