-*- coding: utf-8 -*-


* renowned :48:
[2023-05-20 Sat 11:33]

Celebrated, gushed over, and even legendary, something that's renowned
is really famous. If you not only find a cure for cancer, but you also
go on lots of talk shows so everyone knows who you are, then you'll be
a renowned scientist.

Renown comes from the Anglo-Norman for "re-name," as in repeatedly
name, so something is renowned is something that people are talking
about, or naming, over and over. If you are a huge celebrity, people
from your home town might boast, "The renowned Madame X was born
here." Something renowned is really good, not just famous. Just
because you make the cover of a trashy tabloid magazine doesn't mean
you're a renowned actress. But if you win an Oscar, you are.

In 1971, during the Vietnam War, Henry Kissinger was the target of an
unsuccessful kidnapping attempt, a conspiracy involving, among others,
the renowned antiwar activist priests the Berrigan brothers, four more
Catholic priests, and four nuns.

* pauper :48:
[2023-05-20 Sat 11:33]

Pauper is an old-fashioned word for someone who is poor — really poor,
like the paupers described by Charles Dickens or Mark Twain.

The noun pauper has been around for over 500 years, but today, the
word tends to mostly crop up in literature. If people use it in
conversation, they tend to use the word self-deprecatingly. "I'm
sorry, I can't afford to go with you to the movies. I'm living like a
pauper this week, until I get paid."

No pauper is friend to the rich, no fool to the wise, no coward to
thebrave.

* ploy :48:
[2023-05-20 Sat 11:35]

A ploy is a clever plan that helps you get what you want. A
manipulative little girl might shed tears simply as a ploy to get her
mother to buy her ice cream.

A politician might add amendments to a bill as a ploy to delay voting,
or a hooligan might yell, "Fire!" in a movie theater as a ploy to
sneak his friends in. A sneaky move in a game is a ploy, and
sensational news about a celebrity can be just a ploy to get him more
media attention. The first recorded use of ploy was in 1722, meaning
"anything with which one amuses oneself" in Scottish and Northern
English dialects.

This was not just a onetime ploy: Kissinger made a policy of working
with those who disagreed with him.

* ragtag :48:
[2023-05-20 Sat 11:37]

A ragtag is a disorganized or motley group of people. When a parade
marching band is described as a ragtag, it probably has mismatched
outfits and an odd collection of instruments.

The noun ragtag comes from the old-fashioned phrase rag, tag, and
bobtail — bobtail was once slang for "contemptible rascal," while tag
was used to mean "torn cloth." Together, the phrase meant "riffraff"
or "an unsavory bunch of folks." Today, you're more likely to see
ragtag used as an adjective, as it is in the musical "Hamilton," in
which the Continental Army is described as "a ragtag volunteer army in
need of a shower."

To fight a formidable foe like the Japanese, in fact, would be the
perfect training for the Communists’ ragtag army.

* awry :48:
[2023-05-20 Sat 12:01]

When something goes wrong with a decent plan, you say it has gone
awry. Losing your backpack is a mistake, but when you realize it
contained your ticket and your passport, your vacation plans really go
awry.

Wry means "twisted" — so going awry means getting "twisted up." Awry
is similar to askew, which means "off, out of line." Though when you
compare the roots skew, "turned at an angle" and wry, "twisted," you
see the subtle difference between the two words.

Also, if your plans go awry for some reason, you can use a friend as
a convenient scapegoat.

* venture :48:
[2023-05-20 Sat 12:03]

A venture is a risky undertaking. If your latest venture is a dog food
store, you hope there are some hungry dogs around. Also, to venture is
to go somewhere possibly dangerous, like if you venture out into a
snowstorm.

Venture is a shortened form of adventure. This happened sometime
between 1100 CE and 1400 CE during the time that Middle English was
spoken. While the two words are similar in meaning, when you subtract
the ad, you lose a teaspoon or two of fun, and add a heaping
tablespoon of risk.

You must never let your guard down in such a venture, however; always
be on the lookout for any signs of emotional disturbance such as envy
and ingratitude.

* lookout :48:
[2023-05-20 Sat 12:04]

The neighborhood kids might use a tree house as a lookout, from which
they can keep an eye out for the local bully.

A lookout is usually so high that a person can see for a long distance
in many directions when she stands on or in it. Armies sometimes use
lookouts to scout for approaching troops, and navy ships include a
lookout at the top of a tall mast, also called a "crow's nest."
Lookout can also be spelled as a hyphenated word, "look-out," and used
as well to refer to the person whose job it is to stay in the lookout
and keep watch.

You must never let your guard down in such a venture, however; always
be on the lookout for any signs of emotional disturbance such as envy
and ingratitude.

* dashing :48:
[2023-05-20 Sat 12:10]

Someone who's dashing is stylish, with a certain bold, attractive
spirit. Your dashing uncle might charm and impress your friends with
his stories of travels around the world and his fashionable outfits.

Characters in old books are frequently dashing — adventurous and
gallant, like a dashing hero on a white horse or a dashing pirate
seeking his fortune at sea. The adjective dashing is almost always
used to describe men, and for that reason it's a bit old-fashioned. In
the 18th and 19th centuries "to cut a dash" meant "to act brilliantly"
or "to give a showy appearance," and dashing came from this meaning.

Ninon was sixty-two at the time, and more than experienced in matters
of love; the marquis was a lad of twenty-two, handsome, dashing, but
hopelessly inexperienced in romance.

* nonchalance :48:
[2023-05-20 Sat 12:11]

Nonchalance is a casual lack of concern, a relaxed state without
anxiety or enthusiasm.  Like how you'd act if the girl you've had a
secret crush on since grade school asks you to the prom.  (Or maybe
not.)

It's hard to achieve nonchalance. If you're like most people, there's
always going to be something that will rattle you.  And you can forget
about behaving with chalance, because chalance isn't a word. Sometimes
you hear people say that so-and-so acted with "studied nonchalance,"
which means to sort of fake it. Oddly, the word's origins go back to
the Latin calere, which is the same word as the root of calorie.  A
calorie is a unit of energy, and to act with nonchalance is to refrain
from showing too much energy or excitement, so actually, it makes
sense.

Instructing the marquis to start over, Ninon told him to approach the
countess with a bit of distance, an air of nonchalance.

* seething :48:
[2023-05-20 Sat 12:13]

Seething describes anger you can barely contain. If you are seething
and something sets you off, you just might explode into a rage.

Someone who's seething with anger is furious but keeping it a
secret. Maybe someone insulted you in front of others and you want to
let it go — on the inside, though, you might be seething. Or during
the big game, an opponent's harsh words can have you seething, but you
want to stay focused on scoring points. Seething sometimes describes
something that's boiling over, like a seething pot of soup, and this
is also the root of the word.

Not only would the countess be seething with jealousy, she would come
to see the marquis as someone who was desired by others.

* beguile :48:
[2023-05-20 Sat 12:14]

To beguile is to entertain and convince by flattery. Someone who
beguiles is tricky and often charming, like when a smooth-talking
friend tries to beguile you into giving them your allowance.

The word beguile is from Middle English, and while guile involves
deceit, to beguile means to spend time pleasantly, even if it involves
trickery. If someone beguiles you for an afternoon, you were amused,
entertained, or otherwise pleased. The word can also have a darker
tone, as when the person who beguiled you for the afternoon was
actually trying to steal your car. Con artists and cat videos tend to
beguile people.

Once the countess was jealous but intrigued, it would be time to
beguile her.

* prerequisite :48:
[2023-05-20 Sat 12:15]

A prerequisite is a required prior condition. If something is required
in advance of something else, like if you have to take a beginning
Spanish class before signing up for Spanish II, then it’s a
prerequisite.

Add pre meaning "before" to require and you have something that's
"required before." (That's helpful when trying to spell prerequisite!)
Prerequisites to be able to graduate from college can seem like a
pain, but most schools offer some fun ways to fulfill them. For
example, you can often meet the physical education prerequisite by
taking bowling.  Prerequisites aren't just for school: “The most
called-upon prerequisite of a friend is an accessible ear,” said Maya
Angelou, the American poet.

All of this would push her into the state of emotional confusion that
is a prerequisite for successful seduction.

* spell :48:
[2023-05-20 Sat 12:53]

A spell is a series of words that has magical powers. If you’re under
a spell, then what you do is out of your control — your thoughts and
actions are dictated by the spell.

Spell can refer to the magic words you say, or it can describe being
under the influence of those words. You probably don’t encounter many
magic spells in real life, but the word is often used figuratively to
describe those times when you feel like a magical power controls your
action. Of course, this word can also mean the verb "to spell" which
refers to reciting the letters in a word, like the competitive
spellers in a spelling bee.

The spell was broken.

* feign :48:
[2023-05-21 Sun 11:23]

For a more formal way to say pretend to or imitate, choose the verb
feign. You might feign indifference when you hear about some gossip,
but you're probably dying to know.

Feign comes from the Latin fingere "to devise, fabricate." The word
fiction comes from the same source, so if you feign something such as
sleep, you give off the fiction that you are sleeping. This can be
done to be polite but also to deceive such as when you feign an injury
or the flu so you can stay home from school or work. You can also
feign an accent, though some are better at this than others.

You have to scramble your signals—appear interested in another man or
woman (the decoy), then hint at being interested in the target, then
feign indifference, on and on.

* ulterior :48:
[2023-05-21 Sun 11:24]

An ulterior interest, argument, or revelation is one you try to keep
hidden, like your ulterior motive for weeding your grandmother's
garden is to have a conversation with your crush — and Grandma's
neighbor — who happens to be outside, too.

The adjective ulterior is a Latin word which means “more distant” or
“future.” Something that is ulterior may lay the groundwork for what
comes later, like a new friend who hangs out with you at your house
but whose ulterior motive is to date one of your siblings, or the
incredible popularity of a series of novels set in a real place having
the ulterior consequences of that place becoming a tourist
destination.

Perhaps the marquis had ulterior motives; most men do.

* conniving :48:
[2023-05-21 Sun 11:24]

Someone conniving is calculating, scheming, and shrewd — in other
words, sneaky and up to no good.

Do you know anyone who is always trying to get away with things? Do
they constantly look for ways to get out of trouble or work? Those
kind of people are conniving. This is a word for secretive, shifty
behavior. However, being conniving isn't the worst thing in the world
— it's negative, but you probably wouldn't say a murderer is
conniving. It's usually reserved for con men, shady business moguls,
and manipulative social climbers.

This put everything he had done in a new light. All that before had
been charming now seemed ugly and conniving; the countess felt
embarrassed and used. A door closed that would never open again.
* appease :48:
[2023-05-21 Sun 11:25]

Appease means to make or preserve peace with a nation, group, or
person by giving in to their demands, or to relieve a problem, as in
"the cold drink appeased his thirst."

Appease often implies abandoning your moral principles to satisfy the
demands of someone who is greedy for power: think of British Prime
Minister Chamberlain's attempt to appease the Nazis at Munich. The
verb appease comes from the Old French apaisier, "to pacify, make
peace, or be reconciled," from the phrase "a paisier," which combines
a-, or "to," and pais, "peace," from the Latin pax.

In 1850 the young Otto von Bismarck, then a thirty-five-year-old
deputy in the Prussian parliament, was at a turning point in his
career. The issues of the day were the unification of the many states
(including Prussia) into which Germany was then divided, and a war
against Austria, the powerful neighbor to the south that hoped to
keep the Germans weak and at odds, even threatening to intervene if
they tried to unite. Prince William, next in line to be Prussia’s
king, was in favor of going to war, and the parliament rallied to the
cause, prepared to back any mobilization of troops. The only ones to
oppose war were the present king, Frederick William IV, and his
ministers, who preferred to appease the powerful Austrians.
* infamous :48:
[2023-05-21 Sun 11:26]

Someone who is infamous has a very bad reputation. If you become a
Hollywood star and find yourself on the pages of gossip magazines for
your affairs and addictions, you will have succeeded in becoming
infamous.

Infamous is from Latin infamis, for negative fame. If you're bad but
unknown, then you're not infamous — it's reserved for those wicked and
well-known people that capture our collective imagination.  It is a
strong and resonant term. Some synonyms are notorious, disgraceful,
and odious. The stress is on the first syllable.

A few weeks after Bismarck’s infamous speech, the king, grateful that
he had spoken for peace, made him a cabinet minister. A few years
later he became the Prussian premier. In this role he eventually led
his country and a peace-loving king into a war against Austria,
crushing the former empire and establishing a mighty German state,
with Prussia at its head.
* attained :48:
[2023-05-22 Mon 18:50]

By being completely insincere and sending misleading
signals, however, he deceived everyone, concealed his
purpose, and attained everything he wanted. Such is the
power of hiding your intentions.
* gewgaw                                                               :48:
[2023-05-22 Mon 18:54]

A gewgaw is a little ornament or piece of jewelry. Gewgaws are cheap
and don't have any purpose besides decoration.

* dangle :48:
[2023-05-23 Tue 15:00]

Dangle means to hang or swing loosely. If you dangle string above a
kitten you will both be entertained.

The verb dangle probably comes from a late 16th century Danish or
Swedish word meaning “loose or pendulous,” though we don’t know for
sure. You may have a taste for big, showy earrings that dangle. Or,
you might even dangle a possibility — "If you were to dangle the
prospect of dessert to a child, then you better follow through!"

Basic to an ability to conceal one’s intentions is a simple
truth about human nature: Our first instinct is to always
trust appearances. We cannot go around doubting the reality
of what we see and hear—constantly imagining that
appearances concealed something else would exhaust and
terrify us. This fact makes it relatively easy to conceal
one’s intentions. Simply dangle an object you seem to
desire, a goal you seem to aim for, in front of people’s
eyes and they will take the appearance for reality. Once
their eyes focus on the decoy, they will fail to notice
what you are really up to. In seduction, set up conflicting
signals, such as desire and indifference, and you not only
throw them off the scent, you inflame their desire to
possess you.
* apparent :48:
[2023-05-23 Tue 15:00]

Apparent means obvious, but — and this is confusing — it can also mean
something that seems to be true but isn't definite. "The train's
arrival is apparent — it's in the station — but apparently my friend
missed it because she is not getting off."

It makes sense that apparent has the same ancient root as appear
because it's about what is plain to see. Its subtle power of
suggestion, however, is wonderfully useful. The "heir apparent"
technically means next in line, but the ink isn't dry. The power of
apparent is that it leaves the door open for a little ambiguity. Maybe
the heir apparent will be the next king, or maybe he'll be overthrown
in a bloodless coup by his apparently more ambitious cousin.

Another powerful tool in throwing people off the scent is
false sincerity. People easily mistake sincerity for
honesty. Remember—their first instinct is to trust
appearances, and since they value honesty and want to
believe in the honesty of those around them, they will
rarely doubt you or see through your act. Seeming to
believe what you say gives your words great weight. This is
how Iago deceived and destroyed Othello: Given the depth of
his emotions, the apparent sincerity of his concerns about
Desde mona’s supposed infidelity, how could Othello
distrust him? This is also how the great con artist Yellow
Kid Weil pulled the wool over suckers’ eyes: Seeming to
believe so deeply in the decoyed object he was dangling in
front of them (a phony stock, a touted racehorse), he made
its reality hard to doubt. It is important, of course, not
to go too far in this area. Sincerity is a tricky tool:
Appear overpassionate and you raise suspicions. Be measured
and believable or your ruse will seem the put-on that it
is.
* phony :48:
[2023-05-23 Tue 15:01]

Whether you're talking about your attitude, a gigantic diamond, or
that obnoxious guy's claims that he knows everything about quantum
physics, you can use phony to say that something’s not real.

Use the adjective phony to describe anything that’s fake. If you’re
making phony money in the basement, you’ll be in trouble if you get
caught using it. Phony has a noun version with a similar meaning. If
you say someone or something is a phony, then you’re saying it isn’t
what it pretends to be. Someone who’s a phony isn’t sincere, like your
classmate who pretended to be your best friend just to try to steal
your boyfriend.

Another powerful tool in throwing people off the scent is
false sincerity. People easily mistake sincerity for
honesty. Remember—their first instinct is to trust
appearances, and since they value honesty and want to
believe in the honesty of those around them, they will
rarely doubt you or see through your act. Seeming to
believe what you say gives your words great weight. This is
how Iago deceived and destroyed Othello: Given the depth of
his emotions, the apparent sincerity of his concerns about
Desde mona’s supposed infidelity, how could Othello
distrust him? This is also how the great con artist Yellow
Kid Weil pulled the wool over suckers’ eyes: Seeming to
believe so deeply in the decoyed object he was dangling in
front of them (a phony stock, a touted racehorse), he made
its reality hard to doubt. It is important, of course, not
to go too far in this area. Sincerity is a tricky tool:
Appear overpassionate and you raise suspicions. Be measured
and believable or your ruse will seem the put-on that it
is.
* ruse :48:
[2023-05-23 Tue 15:01]

Movie bank robbers always seem to pull some kind of ruse, a deceptive
trick or tactic like hiding the money underneath the bank while they
drive off in the getaway car to avoid capture by the police.

You'd use a ruse if you were up to something sneaky and were trying to
get away with it without being discovered. The wife planning a
surprise birthday party for her husband could send him out to the
supermarket as a ruse, a trick so she could sneak one hundred of his
closest friends into the house without him noticing.

Another powerful tool in throwing people off the scent is
false sincerity. People easily mistake sincerity for
honesty. Remember—their first instinct is to trust
appearances, and since they value honesty and want to
believe in the honesty of those around them, they will
rarely doubt you or see through your act. Seeming to
believe what you say gives your words great weight. This is
how Iago deceived and destroyed Othello: Given the depth of
his emotions, the apparent sincerity of his concerns about
Desde mona’s supposed infidelity, how could Othello
distrust him? This is also how the great con artist Yellow
Kid Weil pulled the wool over suckers’ eyes: Seeming to
believe so deeply in the decoyed object he was dangling in
front of them (a phony stock, a touted racehorse), he made
its reality hard to doubt. It is important, of course, not
to go too far in this area. Sincerity is a tricky tool:
Appear overpassionate and you raise suspicions. Be measured
and believable or your ruse will seem the put-on that it
is.
* espouse :48:
[2023-05-23 Tue 15:02]

Use the verb espouse to describe the actions of someone who lives
according to specific beliefs, such as your friends who espouse
environmentalism and as a result walk whenever possible instead of
taking the car.

You can see the word spouse in espouse, so you may be wondering what
husbands and wives have to do with it. Originally espouse did mean "to
marry," but its meaning has evolved to include other long-term
commitments as well, such as support for a principle or a
cause. Similar to marriage, if you espouse a belief system, the idea
is that you've chosen to wed yourself to it.

To make your false sincerity an effective weapon in
concealing your intentions, espouse a belief in honesty and
forthrightness as important social values. Do this as
publicly as possible. Emphasize your position on this
subject by occasionally divulging some heartfelt
thought—though only one that is actually meaningless or
irrelevant, of course. Napoleon’s minister Talleyrand was a
master at taking people into his confidence by revealing
some apparent secret. This feigned confidence—a decoy—would
then elicit a real confidence on the other person’s part.
* heartfelt :48:
[2023-05-23 Tue 15:03]

If something is heartfelt, it's sincere and warm. It's clear from your
elderly neighbor's heartfelt invitation that she genuinely wants you
to come over for tea and cookies.

When you're profoundly grateful to your favorite teacher, you'll offer
her your heartfelt thanks. And when your best friend's dog dies,
you'll give him your heartfelt sympathy. Things that are heartfelt are
deeply emotional, believed or felt very strongly. The word dates from
the 18th century, from heart, with its Old English root heorte,
"heart, spirit, or mind."

To make your false sincerity an effective weapon in
concealing your intentions, espouse a belief in honesty and
forthrightness as important social values. Do this as
publicly as possible. Emphasize your position on this
subject by occasionally divulging some heartfelt
thought—though only one that is actually meaningless or
irrelevant, of course. Napoleon’s minister Talleyrand was a
master at taking people into his confidence by revealing
some apparent secret. This feigned confidence—a decoy—would
then elicit a real confidence on the other person’s part.
* roguish :48:
[2023-05-23 Tue 15:03]

To be roguish is to be up to no good, which could mean being
untrustworthy like a criminal or playful and mischievous. If someone
gives you a roguish smile, he’s totally flirting with you.

You can't trust someone who acts roguish in the bad way, like the
roguish crook who picks your pocket while telling you how lovely you
look. On the other hand, you might like someone who acts roguish in
the second sense, which means playfully mischievous. Being roguish in
this way might mean playing pranks, telling racy jokes, and being a
little wild. Roguish behavior like this can still be annoying, like if
your roguish roommate at camp short-sheets your bed.

Remember: The best deceivers do everything they can to
cloak their roguish qualities. They cultivate an air of
honesty in one area to disguise their dishonesty in others.
* grudge :48:
[2023-05-23 Tue 15:04]

If you tend to hold a grudge, you don't let it go when you feel
someone's insulted or wronged you.  I hope you won't hold a grudge
against me for bringing it up.

Grudge comes from the now dead Middle English word "grutch," which
meant "to complain or grumble."  Someone who bears a grudge might
often be grouchy.  You can specify a type of grudge: political grudge,
personal grudge, etc.  You know Grandpa's been holding a grudge
against the neighbors for years, but you have to wonder: How long can
he hold that shotgun?

For reasons—good reasons—of his own, the uncle had been nursing a
grudge against the millionaires for years; this was his chance to get
back at them.

* retribution :48:
[2023-05-23 Tue 15:04]

Retribution is the act of taking revenge. If you pull a prank on
someone, expect retribution.

Retribution comes from the Latin for giving back what's due, either
reward or punishment. But when we talk about retribution, we only talk
about punishment. The old punishment code of "an eye for an eye, a
tooth for a tooth," is an example of retribution. Some people think
about large events like tornados or earthquakes as cosmic retribution
for human pride. Some synonyms are compensation, recompense, requital.

It was all legal and for a good cause—the uncle’s just retribution.

* paunchy :48:
[2023-05-23 Tue 15:04]

Someone who's paunchy has a round belly. If you're more paunchy than
you used to be, you might want to invest in slightly larger, more
comfortable clothes.

This adjective is often used in a mildly derogatory way, to describe
someone who carries a bit of extra weight around their middle. Has
your vet put your dog on a diet? It might be because she's gotten a
little paunchy. The word comes from paunch, "round stomach," from a
root that simply means "belly or stomach."

Weil also brought along a companion, a somewhat paunchy man named
George Gross.

* flabby :48:
[2023-05-23 Tue 15:05]

If you're flabby, you're out of shape, with a soft, slack body. Some
people join a gym when they're feeling a little flabby.

People who are flabby aren't star athletes — you may be flabby after a
long, cold winter spent mostly indoors, or feel flabby as you struggle
to hike up a mountain. You can describe other things as figuratively
flabby too, if they're a little sloppy or weak. Flabby writing is
messy and disorganized, and a flabby politician is ineffective. Flabby
started as flappy, "softly fleshy," in the 16th century.

For a promising fighter, Gross was unimpressive looking—he had gray
hair and a beer belly—but Geezil was so excited about the deal that he
didn’t really think about the man’s flabby appearance.

* banter :48:
[2023-05-23 Tue 15:05]

Good friends usually banter back and forth easily, like they're trying
to keep a step ahead of each other in witty responses. This type of
banter is their special language of friendship.

Banter is both a noun and a verb about talking. It comes from unknown
origins, but even as a word, it seems to be playful and teasing. You
can engage in banter with friends, siblings, parents, and even
good-natured strangers. Banter usually ends with everyone feeling
better for the talk and verbal play. Joking, joshing, and teasing are
all related to banter.

This minor business now settled, the financiers sat back in their
chairs and began to banter about high finance, throwing out the name
“J. P. Morgan” as if they knew the man.

* entourage                                                            :48:
[2023-05-23 Tue 15:06]

You know that group of people — friends, assistants, bodyguards — that
are always surrounding you everywhere you go?  That's your entourage!

Entourage comes from the French word entourer, meaning “to surround,”
and means "the people who surround someone."  It's also pronounced
like a French word, ending with the soft sound “razh” (not “rage”):
"ON-too-razh."  The size of a pop star's entourage might grow with
every hit record she releases. You know you've really made it when
your entourage won't fit in one limo.

Weil explained what he was doing there. The financier countered that
he too had a boxer in his entourage, whom he named.

* glum :48:
[2023-05-23 Tue 15:07]

To be glum is to be sad. Glum is a word for being depressed, bummed
out, or down in the dumps.

People who are glum are sometimes said to be sullen, brooding, morose,
and moody. Glum folks don't smile, giggle, or laugh — and they're
rarely seen holding balloons. Being glum is a little more
outward-directed than just being sad. To be glum is to act sad in
front of other people, almost like you want them to ask, "Why so
glum?"


The financiers were looking glum at how badly their fighter was doing,
and Geezil was dreaming about the easy money he was about to make.

* con :48:
[2023-05-23 Tue 15:07]

A con, or confidence game, is a swindle — when you take advantage of
someone's trust.  If you con someone out of their life savings, you
might wind up a con — as in convict.

The word con has many meanings, none of them good.  An argument has
pros and cons, and the cons are always the downside. An ex-con is
someone who spent time in jail as a convict, and a con artist is
someone who scams people out of their money.

The whole affair had been masterminded by Weil, better known as “the
Yellow Kid,” one of the most creative con artists in history.

* adaptable :Lucy:
[2023-05-23 Tue 15:40]

Something that is adaptable can change to fit its environment, whether
that environment is natural or social. The level to which a species is
adaptable to changing surroundings is an important factor in the study
of evolution.

Let’s look at the Latin word adaptāre, from the root aptus "fitted."
The ad- means "to, while the aptare means "join." Since 15th-century
medieval French, the word adapt has come to mean "to fit in or
adjust." So something adaptable is something that "fits in or
adjusts." An example of an adaptable creature is the arctic fox, whose
fur changes from dirt-dark in summer to snow-white in winter, to
better blend in with its surroundings.

If somebody is an adaptable person, it means they are someone who is
able to change to successfully deal with new situations, especially
difficult ones.

* affable                                                              :Lucy:
[2023-05-23 Tue 15:42]

Affable means friendly, pleasant, and easy to talk to. An affable host
offers you something to drink and makes you feel at home.

The adjective affable entered English by way of the Latin word
affābilis, which means "kind, friendly." If you’re stuck on an
airplane next to someone affable, the trip won’t be so bad because
that person will be easy to chat with but won’t talk your ear
off. Synonyms of affable also refer to a pleasant and mild
friendliness, such as genial, hospitable, and gracious. Affable people
generally seem like they’re in a good mood and are happy to see you.

Affable could
be used to describe somebody who is pleasant, polite, and easy to
talk to.
* ambitious :Lucy:
[2023-05-23 Tue 15:43]

Ambitious means wanting to succeed. If you want to climb Mount
Everest, start your own business, and write a great philosophical
treatise all before you are 30, then wow, you are really ambitious.

Having an ambition is a good thing, like wanting to get good grades,
or to become a doctor. But if we say someone is ambitious, often we
mean they have too much ambition. An ambitious politician might want
power so badly that he’ll abandon his ideals in order to win a
race. If you hatch a business plan and someone tells you it’s too
ambitious, that means you’re probably not being reasonable about how
much you can get done.

He's very ambitious and I think he'll
do very well in life.
* amicable :Lucy:
[2023-05-23 Tue 15:44]

The adjective amicable means "friendly" — but in particular, use it
when describing relations one might otherwise expect to be
unfriendly. The end of a romantic relationship that's less than
amicable might involve broken dishes or broken bones.

Amicable, not surprisingly, comes from the Latin word for "friend,"
amicus. Perhaps the things most commonly described as amicable are
divorces. The parties in a divorce often tend to be so childish and
the proceedings so messy that it's nice to have a word that reflects
the absence of those qualities. Other nouns that commonly pair with
amicable include relationship, split, parting, solution, and breakup.

He seemed very amicable on the telephone, so I was
shocked at his rude email.
* bright :Lucy:
[2023-05-23 Tue 15:45]

After a long, gray winter, it's hard to remember what a bright, sunny
day is like. Bright means shining with light.

The adjective bright is good for describing anything that emits,
reflects, or is full of light — like the bright moon, the bright sky
or the bright, well-lit room. Bright can also mean vivid or vibrant —
such as a bright purple three-piece suit. More figuratively, bright
means "full of hope or possibility" — like your bright future as a
marine biologist.

You're a bright
girl, I know you'll pass the exam.
* broad-minded :Lucy:
[2023-05-23 Tue 15:46]

Luckily, our boss is quite broad-minded, so I'm sure he won't mind you
wearing that today.

* conscientious :Lucy:
[2023-05-23 Tue 15:47]

If someone is conscientious, that person strives to do what's right
and to carry out her duties. Conscientious people show care and put in
a big effort.

Being conscientious has to do with being careful, thoughtful, and
decent. A conscientious doctor will do everything possible to help a
patient. A conscientious teacher will spend extra time with students,
just to make sure they're learning. A boss wishes every worker could
be conscientious: it's a rare and wonderful trait. To be
conscientious, you have to be willing to do the right thing even when
it's difficult. Unfortunately, many people aren't conscientious.

His conscientious manner
makes him a fantastic engineer.
* courteous :Lucy:
[2023-05-23 Tue 15:48]

If you are courteous, your good manners show friendliness and concern
for others, like your courteous habit of holding the door for people
entering a building with you.

The adjective courteous comes from the Old French word curteis, which
means “having courtly bearing or manners.” Courtly described the court
— nobles who hung around the castle, the entourage of kings and
queens. Their refined manners, not to mention their wealth and power,
set them apart from the masses. So courteous behavior is a reminder of
the value of good manners.

If
somebody is courteous, they are a respectful and polite person.
* decisive :Lucy:
[2023-05-23 Tue 15:49]

If you make decisions quickly, you are someone who is decisive. A
decisive event can settle something, like a war.

People who are wishy-washy are the opposite of decisive: being
decisive means you don't waffle or take forever to make up your mind,
and then you stick by what you decided. People admire politicians,
coaches, and friends who are decisive. In sports, if a home run won
the game, that was the decisive run. When you reach a crisis point in
life — when things are going to change one way or the other — you've
reached a decisive moment.

She's quite decisive, so I don't think she'll change her mind.
* convivial :Lucy:
[2023-05-23 Tue 15:49]

Use the adjective convivial to describe your friend who is "the life
of the party."

The Latin word convivium means "a feast," and when convivial was first
coined in the 1660s, its meaning related to the excess of food and
drink during such celebrations. You can also see convivial in
convivere, meaning "to carouse together." Just when it seemed all
convivial could ever do was describe people who overindulge, a new
shade of meaning emerged: loving to be around people. After all, a big
part of feasting is being with people you care about.

She was a convivial party
host who made everyone feel welcomed.
* determined :Lucy:
[2023-05-23 Tue 15:50]

Olympic athletes are some of the most determined people you're going
to meet. At that level, they've got to be driven to
succeed. Otherwise, their opponents will surely beat them.

If you want to reach your goal, you must be determined to do so. To be
determined is to be motivated, driven, or really focused on the task
at hand — and that can be something as big as winning a prize or as
small as fixing a squeaky door. No matter the task, the folks who get
the job done are almost always the most determined. Determined can
also mean "decided." For instance, a judge can determine what the
sentence will be. If that sentence is predetermined, then it's already
been decided.

Her determined nature made her the perfect Olympian.

* eudaimonia :misc:
[2023-05-24 Wed 12:22]

In works of Aristotle, eudaimonia was the term for the highest
human good in older Greek tradition. It is the aim of practical
philosophy-prudence, including ethics and political philosophy, to
consider and experience what this state really is, and how it can
be achieved. It is thus a central concept in Aristotelian ethics
and subsequent Hellenistic philosophy, along with the terms aretē
(most often translated as 'virtue' or 'excellence') and phronesis
('practical or ethical wisdom').[1]
* phronesis :misc:
[2023-05-24 Wed 12:27]

The Greek philosopher Aristotle (384 BCE – 322 BCE) wrote Nicomachean
Ethics, in which he defined personal development as a category of
phronesis or practical wisdom, where the practice of virtues (arête)
leads to eudaimonia,[21] commonly translated as "happiness" but more
accurately understood as "human flourishing" or "living well".[22]
Aristotle continues to influence the Western concept of personal
development to this day, particularly in the economics of human
development[23] and in positive psychology.[24][25]

* wry                                                             :sattelite:
[2023-05-25 Thu 12:30]

A wry sense of humor is a sarcastic one. You were late for work,
stepped into a mud puddle, and you forgot your lunch. If your
co-worker asks how your morning is going, you can reply with a wry
tone, "Perfectly perfect."

The original use for the adjective wry was to describe something that
was bent or twisted, so a sprained ankle could be described as "a wry
ankle." Today, the word wry is often used to describe less tangible
twists. Wry humor and wry wit both describe a sense of humor that is a
little twisted from the norm.

Wry means "twisted" — so going awry means getting "twisted up." Awry
is similar to askew, which means "off, out of line." Though when you
compare the roots skew, "turned at an angle" and wry, "twisted," you
see the subtle difference between the two words.

* rattle :sattelite:
[2023-05-25 Thu 12:41]

To rattle is to make a very rapid, short series of knocking or tapping
sounds. You might impatiently rattle the quarters in your pocket as
you await your turn at the pinball machine.

Ice cubes rattle in your glass of lemonade, and beads rattle in a
jar. Something else that rattles is a baby's rattle, a noisy toy
that's filled with small balls or pellets. Figuratively, to rattle
someone is to upset or irritate them, like the way a sudden
thunderstorm might rattle your timid poodle. Experts trace this word
back to the Middle Dutch ratelen, which they believe to be imitative
since it sounds a bit like a rattle.

It's hard to achieve nonchalance. If you're like most people, there's
always going to be something that will rattle you.

* furious :sattelite:
[2023-05-25 Thu 12:44]

If you've ever been so angry you'd swear you felt your blood boiling,
you could reasonably say that you were furious. The word basically
means "full of fury," so you get the picture.

Think about the angriest you've ever been. Now double it and you might
be getting close to furious, from the Latin furiōsus, meaning "full of
rage," which in turn comes from furia, "fury." Greek and Roman
mythology had the Furies, who dispensed justice by harshly punishing
criminals, sometimes driving them mad. They were merciless, fearsome,
and feared, with snakes for hair and bloody eyes. When not on earth,
they were tormenting the damned in Hell. Now, that's furious!

Someone who's seething with anger is furious but keeping it a
secret. Maybe someone insulted you in front of others and you want to
let it go — on the inside, though, you might be seething. Or during
the big game, an opponent's harsh words can have you seething, but you
want to stay focused on scoring points. Seething sometimes describes
something that's boiling over, like a seething pot of soup, and this
is also the root of the word.

* grandeur :48:
[2023-05-31 Wed 11:50]

Use the noun grandeur to describe something that is splendid or
magnificent, such as a lofty idea or an impressive building: “The
gilded domes and ornate detail added to the grandeur of the church on
Red Square.”

Derived from the Old French word grand, meaning “great,” the word
grandeur is used to describe things that are distinguished,
extraordinary, and impressive in scope. Consider the French origins of
grandeur as a clue and note that this is a fancy word, best saved for
describing things that are truly magnificent on a large scale. The
simple beauty of a shadow’s pattern on a sidewalk probably doesn’t
have grandeur, but a sunset over the Rocky Mountains probably does.

Since the citizens knew little about him, all kinds of legends became
attached to his name. The moment he appeared before the Roman
citizens, however, and spoke his mind, all that grandeur and mystery
vanished.


* rapt :48:
[2023-05-31 Wed 11:50]

To be rapt is to be carried away, caught up, or otherwise engrossed in
something. If a performer is really good or particularly mesmerizing,
the audience will be totally rapt.

Rapt developed from the Latin raptus, meaning to “seize, carry off."
So imagine something so interesting that it seizes your attention and
carries you off to another world. In fact, rapt is related to the word
rapture, which is an experience of extreme, other-worldly
happiness. So do your teacher a favor and give her your rapt attention
during math class.

Coriolanus did appear one last time before the people, who listened
to him in rapt silence. He started slowly and softly, but as the
speech went on, he became more and more blunt.


* wrath :48:
[2023-05-31 Wed 11:50]

Wrath is great anger that expresses itself in a desire to punish
someone: Noah saw the flood as a sign of the wrath of God.

Wrath is also used figuratively of things that behave in a violent
way: Earthquakes are the wrath of the sea. This noun and the
corresponding adjective wrathful are in literary use but are formal or
old-fashioned words, that crop up in fantasy fiction or movies set in
prehistoric times.

The senate, fearing the people’s wrath, finally voted in favor of the
grain distribution. The tribunes were appeased, but the people still
demanded that Coriolanus speak to them and apologize. If he repented,
and agreed to keep his opinions to himself, he would be allowed to
return to the battlefield.


* braggart :48:
[2023-05-31 Wed 11:50]

If you know someone who is a real show off and is always bragging
about how great they are, then you might call this boaster a braggart.

Braggart is a pejorative word, which means it is used as an insult, so
you shouldn’t call your boss or your teacher a braggart — unless
you’re looking for trouble. Braggart is similar to other pejoratives
like blowhard or bigmouth. Braggarts are characterized by talking
loudly (usually in praise of themselves, their possessions, or their
accomplishments) and are quick to assert their superiority over
others.

This time the people listened: They had not realized that this
legendary soldier was also a common braggart.


* insolent :48:
[2023-05-31 Wed 11:51]

Someone who's insolent is either really doing her own thing, even if
it goes against what everyone else is doing, or she’s mildly
disrespectful.

That student in your class who is constantly snubbing the teacher,
snorting when he gives assignments, and rolling her eyes when he reads
passages aloud from your vocabulary textbook? Insolent, definitely
insolent. There might be another student who adorns her school uniform
with pins and ribbons, cuts her hair shorter than the dress code
allows, and rolls her socks down. This student is also insolent, in
the sense that she defies the rules.

And then Coriolanus spoke again, mostly addressing the wealthy
citizens who had accompanied him. His words were arrogant and
insolent.


* quack :48:
[2023-05-31 Wed 11:51]

There are good quacks and bad quacks. A good quack is the sound a duck
makes. A bad quack is someone pretending to be a doctor. (You'd be
better off visiting the duck with your ailment.)

If you ever get a chance to interview a celebrity duck, prepare to
write the word quack in your notebook many, many times, because that’s
all that ducks can say. The way you spell animal sounds changes
depending what language you speak. In English a duck quacks, but in
Danish a duck "raps," while Indonesian ducks "wek," and Romanian ducks
say "mac." And that "MD" who isn’t really a doctor, but is good at
pretending to be one? He's a quack. If you ever meet a quack that
"quacks," please run.

Clowns, tightrope walkers, and star entertainers would accompany him,
pulling people in to his demonstrations of elixirs and quack potions.


* potion                                                                 :48:
[2023-05-31 Wed 11:51]

If you meet up with any witches on Halloween, don’t drink the potion
they offer you. This liquid could be poisonous, magical, or it could
simply taste very strange.

While a potion can be any drinkable liquid, it usually refers to
medicinal concoctions or mysterious brews, as found in fairy tales and
fables. This noun is related to the Latin verb, potare, which means,
“to drink.” You might also notice its similarity to the adjective
potable, another word for “drinkable.” Some common types you may read
about or hear about are “sleeping potions,” “love potions,” and “magic
potions.”

The charlatan made entertainment seem like the business of the day;
the business of the day was actually the sale of the elixirs and quack
potions.


* recess                                                                 :48:
[2023-06-01 Thu 12:44]

Recess is a break from doing something, like work or school. Almost
everyone looks forward to taking a recess — even if you don't have
access to monkey bars.

Recess comes from the Latin word recessus, meaning "a going back,
retreat." You may have heard children talking about recess as their
favorite part of school. This meaning of the word refers to the break
in a school day for children to play, usually outside in a
playground. As a verb, recess means to take a break at the end of a
session — usually in a court proceeding: "The judge announced the
court would recess until the following day."

Their characters have secret recesses that they never reveal. The
unknowableness of other people could prove disturbing if we thought
about it long enough, since it would make it impossible for us really
to judge other people. So we prefer to ignore this fact, and to judge
people on their appearances, on what is most visible to our
eyes—clothes, gestures, words, actions. In the social realm,
appearances are the barometer of almost all of our judgments, and you
must never be mis led into believing otherwise. One false slip, one
awkward or sudden change in your appearance, can prove disastrous.


* scurry                                                                 :48:
[2023-06-01 Thu 12:46]

It can also send people scurrying away from you. Whether the exact
same deeds appear brilliant or dreadful can depend entirely on the
reputation of the doer.


* graciousness :48:
[2023-06-01 Thu 12:47]

In the ancient Chinese court of the Wei kingdom there was a man named
Mi Tzu-hsia who had a reputation for supreme civility and
graciousness. He became the ruler’s favorite.


* liable :48:
[2023-06-01 Thu 12:48]

If you drive into someone's fence, you’ll probably be held liable —
legally responsible — for fixing it. Liable can also mean “likely,”
usually with something unpleasant: "If you don't brush your teeth,
they're liable to fall out."

When liable refers to legal responsibility, it's used with "for":
"You're liable for the court costs" (meaning you have to pay
them). When liable means "likely," it's with "to": "If you build your
house on that cliff, it's liable to fall into the river," or "That
part of town is liable to mudslides." Don't confuse liable with libel,
which is a legal term for slander, or saying something false and
damaging about someone.

When the ruler found out, he said, “How dutiful is Mi Tzu-hsia! For
his mother’s sake he even forgot that he was committing a crime making
him liable to lose his feet!”


* instill :48:
[2023-06-01 Thu 12:51]

Parents work hard to develop, or instill, positive beliefs and values
in their children. Interestingly, there's no corresponding word for
when parents pass down their bad habits.

Instill comes from the Latin verb stillare, meaning "to drip." For
some people, this word provides an apt metaphor for the way that
parents and teachers cultivate understanding in young learners,
patiently introducing wisdom "drop by drop." (Of course, for others,
instill conjures up the image of a persistently dripping faucet that
just won't be quiet.)

It can also create an aura around you that will instill respect, even
fear.


* sway :48:
[2023-06-01 Thu 12:52]

Back and forth...back and forth...back and forth...are you sea-sick
yet? The sway, or rocking motion, of a boat is too much for many
stomachs.

People can sway if they're dizzy, tilting from side to side as they
walk. On a windy day you can see trees swaying and bending in the
wind. Swaying is usually a gentle motion, but if you're easily swayed,
you're in trouble. That means you're easily influenced by
others. People of power often "hold sway" over their followers,
controlling them with the seeming ease of the breeze.

Your success seems destined by your past triumphs. Much of the
success of Henry Kissinger’s shuttle diplomacy rested on his
reputation for ironing out differences; no one wanted to be seen as
so unreasonable that Kissinger could not sway him.


* sterling :48:
[2023-06-01 Thu 12:53]

Sterling is British money, but it also describes anything of very high
quality. A sterling report card has all A’s, and sterling manners are
needed for a visit with the Queen of England.

Sterling is a word for British currency, and although the jury is
still out, the word sterling may be from the Middle English word for
"star," sterre from the stars that appeared in the design of certain
Norman (really old British) coins. Sterling can still refer to money,
but it also describes something great. A sterling reputation is a
flawless, immaculate reputation.

Make your reputation simple and base it on one sterling quality.


* stained :48:
[2023-06-01 Thu 12:55]

Stained things are dirtied or marked in some way. You should probably
reserve your stained pants for painting your bedroom instead of
wearing them to a fancy restaurant.

Accidentally stained things are just dirty, usually
permanently. Deliberately stained things, on the other hand, have a
tint or dye applied to their surface: "I'm pretty proud of the stained
walnut coffee table I made." An image or reputation can also be
figuratively stained: "A stained reputation at work will make it
harder to find a new job."

Perhaps you have already stained your reputation, so that you are
prevented from establishing a new one.


* desist :48:
[2023-06-04 Sun 12:46]

You can use the verb desist as a way to say "stop" or "cease." Instead
of yelling "Cut it out!" the new neighbor asked the tween girls to
desist from playing any more loud, screeching music from that
long-haired boy-band.

If you want to insist that someone stop doing something, the word
desist is a solid choice. It's often used as part of a legal order
called a "cease and desist," which forces an action to come to a
halt. "Cease" is a synonym for desist, so using the two together says
"stop it!" loud and clear — and kind of redundantly. "If she will
desist from camping on the lawn in front of the star's Hollywood home,
she won’t be arrested."

By the end of the first day, the brick man had drawn over a thousand
people into the museum. A few days later the police ordered him to
cease and desist from his walks—the crowds were blocking traffic.


* timid :48:
[2023-06-04 Sun 12:47]

Timid means "overly cautious or fearful," like a timid driver who
drives very slowly or avoids highways altogether.

Timid comes from the Middle French word timide, meaning "easily
frightened, shy." Those who are timid often worry that things will go
wrong: a timid eater orders bland food to avoid the possibility not
liking the flavor of something new, just as a timid partygoer talks to
people he already knows, afraid that he won't be able to talk to
strangers.

Everything is judged by its appearance; what is unseen counts for
nothing. Never let yourself get lost in the crowd, then, or buried in
oblivion. Stand out. Be conspicuous, at all cost. Make yourself a
magnet of attention by appearing larger, more colorful, more
mysterious than the bland and timid masses.


* conspicuous :48:
[2023-06-04 Sun 12:47]

Keep your eye on the adjective conspicuous for something that stands
out so much you notice it right away — like that zit in the center of
your friend's forehead.

Conspicuous comes from the adjectival form of the Latin verb,
conspicere, meaning "to look at." Conspicuous can mean either very
obvious to the eye (like something that is conspicuous from a
distance) or attracting attention (like conspicuous consumption). If
you are doing something wrong, it's wise not to be conspicuous about
it!

Everything is judged by its appearance; what is unseen counts for
nothing. Never let yourself get lost in the crowd, then, or buried in
oblivion. Stand out. Be conspicuous, at all cost. Make yourself a
magnet of attention by appearing larger, more colorful, more
mysterious than the bland and timid masses.


* insolence :48:
[2023-06-04 Sun 12:48]

Insolence is a rude, disrespectful act. The teenager's insolence got
her in trouble with her teachers.

Insolence is an act of or the trait of being a jerk, especially to
someone you should respect. Insolence is what rude and stuck-up people
show off every chance they get. They ignore their parents, walk out on
dinner bills, elbow old people out of the way, and tell professors
their clothes look cheap. Insolence is a trait to get rid of, not
flaunt. Teenagers often embrace insolence when they get to the age
when they think their parents are stupid. (It usually wears off.)

There is no possible Reversal. Reputation is critical; there are no
exceptions to this law. Perhaps, not caring what others think of you,
you gain a reputation for insolence and arrogance, but that can be a
valuable image in itself—Oscar Wilde used it to great advantage.


* bolster :48:
[2023-06-04 Sun 12:48]

When you cheer up a friend who's feeling down, you bolster them. To
bolster is to offer support or strengthen.

A bolster is also the name of a long pillow you might use to make your
back feel better. And the two uses are not dissimilar. When you
bolster your friends, you support them and prop them up, just like the
pillow does for your back. When you're trying to bolster your
credibility, you find people and/or documents that support you or your
view. Bolster efforts to learn this word!

Authority: Therefore I should wish our courtier to bolster up his
inherent worth with skill and cunning, and ensure that whenever he
has to go where he is a stranger, he is preceded by a good
reputation....


* luster :48:
[2023-06-04 Sun 12:49]

Something with luster has a certain kind of sheen or shininess, like
the way a new pair of shoes looks right before you step into a pile of
mud.

Luster is a noun that commonly refers to a soft sheen, glossy surface,
or brightness. It comes from the Italian word lustro, which means "to
make bright." Daniel Defoe, author of the novel Robinson Crusoe, once
famously said, “The soul is placed in the body like a rough diamond,
and must be polished, or the luster of it will never appear.”

Guard it with your life. Robbers and thieves will appear from all
sides. Never take your wealth for granted, and constantly renew
it—time will diminish the jewels’ luster, and bury them from sight.


* vengeance :48:
[2023-06-04 Sun 12:52]

If someone hurts you, you might be inspired to plan an act of
vengeance: some type of payback in order to settle the score. Be
careful, though, because you might inspire someone to take vengeance
on you in return.

Vengeance is a downward spiral of pain and betrayal, one person
hurting another, who hurts another, and so on. You might demand
vengeance if your brother throws your favorite jeans into a tree, and
your brother might feel the same way after you spit gum in his
hair. The phrase “with a vengeance” means to do something with a lot
of intensity. Vengeance shares roots with the word revenge, and
someone who wants revenge usually pursues it with a vengeance.

Barnum used such campaigns to great effect in his early career. But
this tactic must be practiced with skill; you must not seem to engage
in petty vengeance.

* despise                                                                :48:
[2023-06-04 Sun 12:53]

If the mere thought of a burrito with sour cream in it turns your
stomach, you could say that you despise sour cream. You loathe it,
abhor it, hate it, and think it's vile.

Despise dates all the way back to the Latin word despicare, which
combines de "down" with specere "to look at." So if you look down your
nose at something, you could say you despise it. Nowadays the word
gets used a lot to describe things people really, really dislike,
too. Note how similar in meaning and spelling despise is to Sylvester
the cartoon cat's old favorite catchphrase despicable. Despicable
means something worth of being despised.

For, as Cicero says, even those who argue against fame still want the
books they write against it to bear their name in the title and hope
to become famous for despising it.

* boo                                                                    :48:
[2023-06-04 Sun 13:49]

But Barnum took pains to hire the worst musicians he could find, and
soon after the band struck up, people would hurry to buy tickets to
the museum, where they would be out of earshot of the band’s noise,
and of the booing of the crowd.


* purport                                                                :48:
[2023-06-04 Sun 13:55]

Use purport when you want to convince people about something that
might not be true, like when you purport that the dog ate your
homework.

The verb purport can mean "to claim" — whether you mean it or not — or
"to intend," like when you purport to study all night. So it makes
sense that as a noun, purport means the intention or purpose, like the
purport of a political candidate's speech was to get your vote. If the
speech was long and hard to follow, you might be lucky just to get the
purport, which here means "the main point or meaning."

In 1842, Barnum purchased the carcass of what was purported to be a
mermaid. This creature resembled a monkey with the body of a fish,
but the head and body were perfectly joined—it was truly a wonder.


* veer                                                                   :48:
[2023-06-04 Sun 14:00]

To veer is to make a sudden turn, like when a driver veers off the
pavement or a pleasant conversation veers off in a troubling
direction.

When you make any quick change of direction you veer. You can veer
toward an attractive person at a party, leaving your friends
mid-sentence. You veer away from an oncoming truck on the highway to
avoid getting crushed. Originally, veer described a change in the
direction of the wind, but as you can see, today, anyone or anything
that changes direction veers.

If it veers toward other people, it does so at your expense. Barnum
would ruthlessly suck attention from his competitors, knowing what a
valuable commodity it is.


* slanderous                                                             :48:
[2023-06-04 Sun 14:01]

No matter how badly his shows were reviewed, or how slanderously
personal were the attacks on his hoaxes, Barnum would never complain.


* revile                                                                 :48:
[2023-06-04 Sun 14:01]

If something is reviled, you alone don’t dislike it; a whole community
of like-minded souls has to hate its guts. For instance, spam is
widely reviled. (The junk e-mails, not the potted meat. Somebody out
there really does like that potted meat.)

If you’re the only one who hates, say, your math teacher, it’s not
fair to say that person is reviled. If she is majestically unpopular
with the entire senior class and is routinely the butt of
geometry-themed insults, well then sadly, this instructor is indeed
reviled.  Generally, when someone or something is reviled, much of the
poison aimed is in print, such as critical reviews or insulting
editorials.

If a newspaper critic reviled him particularly badly, in fact, he made
sure to invite the man to an opening and to give him the best seat in
the house.

* vantage :48:
[2023-06-04 Sun 14:02]

A vantage is a really good place from which to survey a scene. You
might find that the roof of the house offers an excellent vantage from
which to drop water balloons on your kid brother’s head.

Vantage is a variation of advantage, but when we use vantage we’re
almost always talking about a position, not just general
superiority. If you had extra tutoring for a big exam, you would have
the advantage over a classmate who didn’t. But if your seat for the
test allowed you to see the answer sheet lying on the desk, well then
you would have a superior vantage — not that you would take advantage
of that, of course!

From Barnum’s vantage, attention—whether negative or positive—was the
main ingredient of his success. The worst fate in the world for a man
who yearns fame, glory, and, of course, power is to be ignored.


* lodestone :48:
[2023-06-04 Sun 14:04]

If the courtier happens to engage in arms in some public spectacle
such as jousting ... he will ensure that the horse he has is
beautifully caparisoned, that he himself is suitably attired, with
appropriate mottoes and ingenious devices to attract the eyes of the
onlookers in his direction as surely as the lodestone attracts iron.


* humbug :48:
[2023-06-05 Mon 12:13]

It is a common mistake to imagine that this peculiar appearance of
yours should not be controversial, that to be attacked is somehow
bad. Nothing could be further from the truth. To avoid being a flash
in the pan, and having your notoriety eclipsed by another, you must
not discriminate between different types of attention; in the end,
every kind will work in your favor. Barnum, we have seen, welcomed
personal attacks and felt no need to defend himself. He deliberately
courted the image of being a humbug.


* insolent :48:
[2023-06-05 Mon 16:46]

Someone who's insolent is either really doing her own thing, even if
it goes against what everyone else is doing, or she’s mildly
disrespectful.

That student in your class who is constantly snubbing the teacher,
snorting when he gives assignments, and rolling her eyes when he reads
passages aloud from your vocabulary textbook? Insolent, definitely
insolent. There might be another student who adorns her school uniform
with pins and ribbons, cuts her hair shorter than the dress code
allows, and rolls her socks down. This student is also insolent, in
the sense that she defies the rules.

The duke was short, almost dwarfish, and he was prone to the most
insolent kinds of behavior—he slept with the king’s mistress, and
openly insulted not only other courtiers but the king himself.


* ostentatious :48:
[2023-06-05 Mon 17:20]

Reach for the adjective ostentatious when you want a flashy way to say
— well, "flashy" or "showy."

No one wants to be described as ostentatious, a word whose cousins
include pretentious, flamboyant, and gaudy. It originates from the
Latin word ostentare, "to display," but in English it's often used for
displays of the crass or vulgar sort. A rapper's diamond-encrusted
teeth might be an ostentatious display of "bling," and someone wailing
especially loudly at a funeral of a distant acquaintance might be
making an ostentatious show of sorrow.

Authority: Be ostentatious and be seen.

* adjunct :misc:
[2023-06-20 Tue 11:07]

Adjunct means something added on, but not part of the whole. An
adjunct professor is someone who is hired by a college to teach but
isn't a full member of the faculty.

This is a word you can figure out by taking it apart. From ad- "to"
and -junct "join" (think "junction"), you can see that this is about
joining something to another. "During lunch, Tim always sat at the
girls' lacrosse-team lunch table, and they joked that he was an
adjunct member of the team."

I was going to forego mentioning it but after my Clocktables post, I
decided that would be a useful adjunct to that post.
