-*- coding: utf-8 -*-

* dagger :48:
[2023-09-20 Wed 11:03]

A dagger is a weapon, a sharp knife that's used for self-defense or
fighting. During the Late Middle Ages, daggers were a sort of back-up
to the longer sword, both carried during battles.

Most daggers have a sharp, pointed blade and a handle with a
"crossguard" that protects a fighter's hand from sliding forward and
getting cut. Throughout history, various kinds of daggers have been
used in close combat. The word comes from the Old French dague, though
its origin beyond that isn't known. The ancient last name Dagard,
dating from the 13th century or earlier, meant "one who carries a
dagger."

He took a house near the cathedral and never ventured outdoors without
a sword and a dagger.

* alcalde :48:
[2023-09-20 Wed 11:05]

When freed, Aguirre announced his intention of killing the official
who had sentenced him, the alcalde Esquivel. Esquivel’s term of office
expired and he fled to Lima.

* permeable :48:
[2023-09-20 Wed 11:07]

Something that is permeable can be passed through, especially by
liquids or gases. "I wish I hadn't worn my permeable sweater to the
picnic when the weatherman called for thunderstorms. The rain seeped
right through the fabric, soaking me to the skin."

A permeable surface allows materials like liquids to pass through —
either in or out. Inside the body, the walls of cells are permeable
membranes that allow fluids and nutrients to get in and nourish the
cells. A permeable shirt is good to wear in the summer, because it
helps release the sweat sticking to the skin.

You need to be permeable, able to float in and out of different
circles and mix with different types. That kind of mobility and social
contact will protect you from plotters, who will be unable to keep
secrets from you, and from your enemies, who will be unable to isolate
you from your allies.

* shady :48:
[2023-09-20 Wed 11:07]

Any place that's protected from the glare and heat of the sun is
shady, as in a "shady nook." But as its darkened nature implies, shady
has the equally popular meaning of "suspicious, dangerous, or
deceitful." A "shady character" is up to no good.

The metaphorical meaning of shady has long been embraced by
slang. Since at least the 1950's, the phrase "got it made in the
shade" means having a great and easy life or job (picture eastern
sultans being shaded by servants holding giant leaves). The rap sultan
Eminem calls his evil alter-ego "Slim Shady," conjuring up a devilish
suggestion of the Prince of Darkness himself — someone who definitely
lives in a shady neighborhood.

Although he came from one of the oldest aristocratic families in
France, he made a point of always staying in touch with what was
happening in the streets of Paris, allowing him to foresee trends and
troubles. He even got a certain pleasure out of mingling with shady
criminal types, who supplied him with valuable information.

* mingling :48:
[2023-09-20 Wed 11:08]

Although he came from one of the oldest aristocratic families in
France, he made a point of always staying in touch with what was
happening in the streets of Paris, allowing him to foresee trends and
troubles. He even got a certain pleasure out of mingling with shady
criminal types, who supplied him with valuable information.

* impregnable :48:
[2023-09-20 Wed 11:09]

When something is impregnable it is not easily taken by force and can
stand up to any attack. We usually use it in reference to some form of
protection, like a fort or a solid defensive line in football.

The genealogy of the adjective impregnable includes the Middle French
word prenable, meaning "vulnerable, easily conquered," which itself
came from the verb prendre, which meant "to take." The addition of the
negative prefix im- flipped the meaning. Impregnable can be used to
describe anything that cannot be entered or successfully
attacked. Seventeenth-century theater critic Jeremy Collier once said,
"True courage is a result of reasoning. A brave mind is always
impregnable."

Machiavelli makes the argument that in a strictly military sense a
fortress is invariably a mistake. It becomes a symbol of power’s
isolation, and is an easy target for its builders’ enemies. Designed
to defend you, fortresses actually cut you off from help and cut into
your flexibility. They may appear impregnable, but once you retire to
one, everyone knows where you are; and a siege does not have to
succeed to turn your fortress into a prison.

* factions :48:
[2023-09-20 Wed 11:09]

Fractions are smaller parts of whole numbers: one-quarter, one-tenth,
one-half, and a faction is a smaller portion of a larger group that
breaks away from it. A faction might take a fraction of the people
from a large group and start a new group.

The Latin source of the word faction means to "do" or "make," though a
faction can seem to be a taking away or un-doing. Politics is one area
where faction gets a lot of use, because a political party often
starts with a large group but has some members who disagree with a
belief or direction. These members separate from the larger party and
become a faction of their own, with many of the same beliefs as the
original group but with a few new differences, too.

The once proud nobility was reduced to squabbling over the right to
help the king put on his robes in the morning. There was no
possibility here of privacy—no possibility of isolation. Louis XIV
very early grasped the truth that for a king to isolate himself is
gravely dangerous. In his absence, conspiracies will spring up like
mushrooms after rain, animosities will crystallize into factions,
and rebellion will break out before he has the time to react.

* animosity                                                              :48:
[2023-09-20 Wed 11:10]

Animosity is hatred. If your (supposed) best buddy embarrasses you in
front of a big crowd, your friendship could turn into animosity.

Animosity comes from the Latin word animus, meaning "spirit" or
"mind." That's also the root of the word animated — literally, "full
of spirit." So how did animosity get so negative? Over the centuries,
the original meaning of "high spirits" soured into "hatred." Today we
most often speak of animosity toward, between, among, or against
people. Keeping your animosity in check might make steam come out your
ears.

In his absence, conspiracies will spring up like mushrooms after rain,
animosities will crystallize into factions, and rebellion will break
out before he has the time to react. To combat this, sociability and
openness must not only be encouraged, they must be formally organized
and channeled.

* instigator :48:
[2023-09-20 Wed 11:10]

Louis XIV came to power at the end of a terrible civil war, the
Fronde. A principal instigator of the war had been the nobility, which
deeply resented the growing power of the throne and yearned for the
days of feudalism, when the lords ruled their own fiefdoms and the
king had little authority over them.

* scruple :48:
[2023-09-20 Wed 11:11]

Your scruples are what keep you from doing things you consider to be
morally or ethically wrong. Your scruples won't allow you to cheat on
a test, or steal from your brother's Halloween candy stash.

The noun scruple comes from a Latin word, scrupulus, which means a
small, sharp stone. Some say that the philosopher Cicero first used
the word analogously to compare a worry to a small, sharp stone in
your shoe that bothers you. From there the word scruple took on the
ethical principles meaning. If you are doing something bad, your
scruples will bother you — but emptying your shoe probably won't help.

Shih Huang Ti started off as the king of Ch’in, a fearless warrior
of unbridled ambition. Writers of the time described him as a man
with “a waspish nose, eyes like slits, the voice of a jackal, and
the heart of a tiger or wolf.” He could be merciful sometimes, but
more often he “swallowed men up without a scruple.”

* slit                                                                   :48:
[2023-09-20 Wed 11:11]

A very narrow slot or cut in something is a slit. You might fill your
pita bread with falafel by first making a slit in its side.

A long strip of sunlight might shine through a slit in your curtains
and wake you up in the morning. Or you may narrow your eyes to slits
in anger when you see the mess your sister made in your room. You can
also use this word as a verb, to mean "cut into," like when you slit a
croissant and insert jam, or slit an envelope with an old-fashioned
letter opener.

Shih Huang Ti started off as the king of Ch’in, a fearless warrior
of unbridled ambition. Writers of the time described him as a man
with “a waspish nose, eyes like slits, the voice of a jackal, and
the heart of a tiger or wolf.”

* unbridled :48:
[2023-09-20 Wed 11:12]

Unbridled means unrestrained. When you find out that you just won the
lottery, feel free to jump up and down with unbridled joy. Go ahead,
most people would probably let loose in the same way.

A bridle is the contraption used to control a horse, including the
reins held by the rider and the bit that goes into the horse’s
mouth. Add the un prefix and it means there is no control. Unbridled
is often used to describe people’s emotions or actions and it can be
either a good or a bad thing. If you have unbridled spending, you’re
in danger of going in debt. If you tackle homework with unbridled
enthusiasm, you’re likely going to get good grades.

Shih Huang Ti started off as the king of Ch’in, a fearless warrior of
unbridled ambition.
