-*- coding: utf-8 -*-

* glutton :misc:
[2023-01-10 Tue 12:36]

Do you like to eat and drink — I mean, really like to eat and drink?
Then you might be a glutton.

We all have our favorite foods and drinks, but some people are a
little more into it than others — these people are gluttons. Someone
who's a glutton because they just eat too much is different from a
gourmet or gourmand, who enjoys only the best food. This word also is
used in phrases like "glutton for punishment," which you might say
about a student who asks for extra homework.

He's such a =glutton= that he ate the whole cake.

* preclude :Dahl:
[2023-01-27 Fri 09:43]

To preclude something is to prevent it from happening. A muzzle
precludes a dog from biting.

This is a very formal word, but it has a simple meaning: when
something is precluded, it can't happen. See the prefix pre in
preclude and in prevent? It is signaling that these words are all
about things done before another action would happen — to make it
impossible. Staying away from water precludes the possibility of
drowning, though it also precludes any chance of having fun swimming.

which seemed to preclude the short sleeper category.