-*- coding: utf-8 -*-


* renowned :misc:
[2023-05-20 Sat 11:33]

Celebrated, gushed over, and even legendary, something that's renowned
is really famous. If you not only find a cure for cancer, but you also
go on lots of talk shows so everyone knows who you are, then you'll be
a renowned scientist.

Renown comes from the Anglo-Norman for "re-name," as in repeatedly
name, so something is renowned is something that people are talking
about, or naming, over and over. If you are a huge celebrity, people
from your home town might boast, "The renowned Madame X was born
here." Something renowned is really good, not just famous. Just
because you make the cover of a trashy tabloid magazine doesn't mean
you're a renowned actress. But if you win an Oscar, you are.

In 1971, during the Vietnam War, Henry Kissinger was the target of an
unsuccessful kidnapping attempt, a conspiracy involving, among
others, the renowned antiwar activist priests the Berrigan brothers,
four more Catholic priests, and four nuns. In private, without
informing the Secret Service or the Justice Department, Kissinger
arranged a Saturday-morning meeting with three of the alleged
kidnappers. Explaining to his guests that he would have most American
soldiers out of Vietnam by mid-1972, he completely charmed them. They
gave him some “Kidnap Kissinger” buttons and one of them remained a
friend of his for years, visiting him on several occasions. This was
not just a onetime ploy: Kissinger made a policy of working with
those who disagreed with him. Colleagues commented that he seemed to
get along better with his enemies than with his friends.
* pauper :misc:
[2023-05-20 Sat 11:33]

Pauper is an old-fashioned word for someone who is poor — really poor,
like the paupers described by Charles Dickens or Mark Twain.

The noun pauper has been around for over 500 years, but today, the
word tends to mostly crop up in literature. If people use it in
conversation, they tend to use the word self-deprecatingly. "I'm
sorry, I can't afford to go with you to the movies. I'm living like a
pauper this week, until I get paid."

The brahman cries out when he sees the king, “Recognize me, your
friend!” The king answers him with contempt and then explains: “Yes,
we were friends before, but our friendship was based on what power we
had.... I was friends with you, good brahman, because itserved my
purpose. No pauper is friend to the rich, no fool to the wise, no
coward to thebrave. An old friend—who needs him? It is two men of
equal wealth and equal birth who contract friendship and marriage,
not a rich man and a pauper.... An old friend—who needs him?
* ploy :misc:
[2023-05-20 Sat 11:35]

A ploy is a clever plan that helps you get what you want. A
manipulative little girl might shed tears simply as a ploy to get her
mother to buy her ice cream.

A politician might add amendments to a bill as a ploy to delay voting,
or a hooligan might yell, "Fire!" in a movie theater as a ploy to
sneak his friends in. A sneaky move in a game is a ploy, and
sensational news about a celebrity can be just a ploy to get him more
media attention. The first recorded use of ploy was in 1722, meaning
"anything with which one amuses oneself" in Scottish and Northern
English dialects.

In 1971, during the Vietnam War, Henry Kissinger was the target of an
unsuccessful kidnapping attempt, a conspiracy involving, among
others, the renowned antiwar activist priests the Berrigan brothers,
four more Catholic priests, and four nuns. In private, without
informing the Secret Service or the Justice Department, Kissinger
arranged a Saturday-morning meeting with three of the alleged
kidnappers. Explaining to his guests that he would have most American
soldiers out of Vietnam by mid-1972, he completely charmed them. They
gave him some “Kidnap Kissinger” buttons and one of them remained a
friend of his for years, visiting him on several occasions. This was
not just a onetime ploy: Kissinger made a policy of working with
those who disagreed with him. Colleagues commented that he seemed to
get along better with his enemies than with his friends.
* ragtag :misc:
[2023-05-20 Sat 11:37]

A ragtag is a disorganized or motley group of people. When a parade
marching band is described as a ragtag, it probably has mismatched
outfits and an odd collection of instruments.

The noun ragtag comes from the old-fashioned phrase rag, tag, and
bobtail — bobtail was once slang for "contemptible rascal," while tag
was used to mean "torn cloth." Together, the phrase meant "riffraff"
or "an unsavory bunch of folks." Today, you're more likely to see
ragtag used as an adjective, as it is in the musical "Hamilton," in
which the Continental Army is described as "a ragtag volunteer army in
need of a shower."

Fearing that the Japanese would wipe them out, some Communist leaders
advocated leaving the Nationalists to fight the Japanese, and using
the time to recuperate. Mao disagreed: The Japanese could not
possibly defeat and occupy a vast country like China for long. Once
they left, the Communists would have grown rusty if they had been out
of combat for several years, and would be ill prepared to reopen
their struggle with the Nationalists. To fight a formidable foe like
the Japanese, in fact, would be the perfect training for the
Communists’ ragtag army. Mao’s plan was adopted, and it worked: By
the time the Japanese finally retreated, the Communists had gained
the fighting experience that helped them defeat the Nationalists.
* awry :misc:
[2023-05-20 Sat 12:01]

When something goes wrong with a decent plan, you say it has gone
awry. Losing your backpack is a mistake, but when you realize it
contained your ticket and your passport, your vacation plans really go
awry.

Wry means "twisted" — so going awry means getting "twisted up." Awry
is similar to askew, which means "off, out of line." Though when you
compare the roots skew, "turned at an angle" and wry, "twisted," you
see the subtle difference between the two words.

Also, if your plans go awry for some reason, you can use a friend as
a convenient scapegoat. This “fall of the favorite” was a trick often
used by kings and sovereigns: They would let their closest friend at
court take the fall for a mistake, since the public would not believe
that they would deliberately sacrifice a friend for such a purpose.
* venture :misc:
[2023-05-20 Sat 12:03]

A venture is a risky undertaking. If your latest venture is a dog food
store, you hope there are some hungry dogs around. Also, to venture is
to go somewhere possibly dangerous, like if you venture out into a
snowstorm.

Venture is a shortened form of adventure. This happened sometime
between 1100 CE and 1400 CE during the time that Middle English was
spoken. While the two words are similar in meaning, when you subtract
the ad, you lose a teaspoon or two of fun, and add a heaping
tablespoon of risk.

Finally, the problem about working with friends is that it confuses
the boundaries and distances that working requires. But if both
partners in the arrangement understand the dangers involved, a friend
often can be employed to great effect. You must never let your guard
down in such a venture, however; always be on the lookout for any
signs of emotional disturbance such as envy and ingratitude. Nothing
is stable in the realm of power, and even the closest of friends can
be transformed into the worst of enemies.
* lookout :misc:
[2023-05-20 Sat 12:04]

The neighborhood kids might use a tree house as a lookout, from which
they can keep an eye out for the local bully.

A lookout is usually so high that a person can see for a long distance
in many directions when she stands on or in it. Armies sometimes use
lookouts to scout for approaching troops, and navy ships include a
lookout at the top of a tall mast, also called a "crow's nest."
Lookout can also be spelled as a hyphenated word, "look-out," and used
as well to refer to the person whose job it is to stay in the lookout
and keep watch.

Finally, the problem about working with friends is that it confuses
the boundaries and distances that working requires. But if both
partners in the arrangement understand the dangers involved, a friend
often can be employed to great effect. You must never let your guard
down in such a venture, however; always be on the lookout for any
signs of emotional disturbance such as envy and ingratitude. Nothing
is stable in the realm of power, and even the closest of friends can
be transformed into the worst of enemies.
* dashing :misc:
[2023-05-20 Sat 12:10]

Someone who's dashing is stylish, with a certain bold, attractive
spirit. Your dashing uncle might charm and impress your friends with
his stories of travels around the world and his fashionable outfits.

Characters in old books are frequently dashing — adventurous and
gallant, like a dashing hero on a white horse or a dashing pirate
seeking his fortune at sea. The adjective dashing is almost always
used to describe men, and for that reason it's a bit old-fashioned. In
the 18th and 19th centuries "to cut a dash" meant "to act brilliantly"
or "to give a showy appearance," and dashing came from this meaning.

Over several weeks, Ninon de Lenclos, the most infamous courtesan of
seventeenth-century France, listened patiently as the Marquis de
Sevigné explained his struggles in pursuing a beautiful but difficult
young countess. Ninon was sixty-two at the time, and more than
experienced in matters of love; the marquis was a lad of twenty-two,
handsome, dashing, but hopelessly inexperienced in romance. At first
Ninon was amused to hear the marquis talk about his mistakes, but
finally she had had enough. Unable to bear ineptitude in any realm,
least of all in seducing a woman, she decided to take the young man
under her wing. First, he had to understand that this was war, and
that the beautiful countess was a citadel to which he had to lay
siege as carefully as any general. Every step had to be planned and
executed with the utmost attention to detail and nuance.
* nonchalance :misc:
[2023-05-20 Sat 12:11]

Nonchalance is a casual lack of concern, a relaxed state without
anxiety or enthusiasm.  Like how you'd act if the girl you've had a
secret crush on since grade school asks you to the prom.  (Or maybe
not.)

It's hard to achieve nonchalance. If you're like most people, there's
always going to be something that will rattle you.  And you can forget
about behaving with chalance, because chalance isn't a word. Sometimes
you hear people say that so-and-so acted with "studied nonchalance,"
which means to sort of fake it. Oddly, the word's origins go back to
the Latin calere, which is the same word as the root of calorie.  A
calorie is a unit of energy, and to act with nonchalance is to refrain
from showing too much energy or excitement, so actually, it makes
sense.

Instructing the marquis to start over, Ninon told him to approach the
countess with a bit of distance, an air of nonchalance. The next time
the two were alone together, she said, he would confide in the
countess as would a friend but not a potential lover. This was to
throw her off the scent. The countess was no longer to take his
interest in her for granted—perhaps he was only interested in
friendship.
* seething :misc:
[2023-05-20 Sat 12:13]

Seething describes anger you can barely contain. If you are seething
and something sets you off, you just might explode into a rage.

Someone who's seething with anger is furious but keeping it a
secret. Maybe someone insulted you in front of others and you want to
let it go — on the inside, though, you might be seething. Or during
the big game, an opponent's harsh words can have you seething, but you
want to stay focused on scoring points. Seething sometimes describes
something that's boiling over, like a seething pot of soup, and this
is also the root of the word.

This beautiful young woman had equally beautiful friends, so that
wherever the countess would now see the marquis, he would be
surrounded by the most stunning young women in Paris. Not only would
the countess be seething with jealousy, she would come to see the
marquis as someone who was desired by others. It was hard for Ninon
to make the marquis understand, but she patiently explained that a
woman who is interested in a man wants to see that other women are
interested in him, too. Not only does that give him instant value, it
makes it all the more satisfying to snatch him from their clutches.
* beguile :misc:
[2023-05-20 Sat 12:14]

To beguile is to entertain and convince by flattery. Someone who
beguiles is tricky and often charming, like when a smooth-talking
friend tries to beguile you into giving them your allowance.

The word beguile is from Middle English, and while guile involves
deceit, to beguile means to spend time pleasantly, even if it involves
trickery. If someone beguiles you for an afternoon, you were amused,
entertained, or otherwise pleased. The word can also have a darker
tone, as when the person who beguiled you for the afternoon was
actually trying to steal your car. Con artists and cat videos tend to
beguile people.

Once the countess was jealous but intrigued, it would be time to
beguile her. On Ninon’s instructions, the marquis would fail to show
up at affairs where the countess expected to see him. Then, suddenly,
he would appear at salons he had never frequented before, but that
the countess attended often. She would be unable to predict his
moves. All of this would push her into the state of emotional
confusion that is a prerequisite for successful seduction.
* prerequisite :misc:
[2023-05-20 Sat 12:15]

A prerequisite is a required prior condition. If something is required
in advance of something else, like if you have to take a beginning
Spanish class before signing up for Spanish II, then it’s a
prerequisite.

Add pre meaning "before" to require and you have something that's
"required before." (That's helpful when trying to spell prerequisite!)
Prerequisites to be able to graduate from college can seem like a
pain, but most schools offer some fun ways to fulfill them. For
example, you can often meet the physical education prerequisite by
taking bowling.  Prerequisites aren't just for school: “The most
called-upon prerequisite of a friend is an accessible ear,” said Maya
Angelou, the American poet.

Once the countess was jealous but intrigued, it would be time to
beguile her. On Ninon’s instructions, the marquis would fail to show
up at affairs where the countess expected to see him. Then, suddenly,
he would appear at salons he had never frequented before, but that
the countess attended often. She would be unable to predict his
moves. All of this would push her into the state of emotional
confusion that is a prerequisite for successful seduction.
* spell :misc:
[2023-05-20 Sat 12:53]

A spell is a series of words that has magical powers. If you’re under
a spell, then what you do is out of your control — your thoughts and
actions are dictated by the spell.

Spell can refer to the magic words you say, or it can describe being
under the influence of those words. You probably don’t encounter many
magic spells in real life, but the word is often used figuratively to
describe those times when you feel like a magical power controls your
action. Of course, this word can also mean the verb "to spell" which
refers to reciting the letters in a word, like the competitive
spellers in a spelling bee.

The spell was broken.
* feign :misc:
[2023-05-21 Sun 11:23]

For a more formal way to say pretend to or imitate, choose the verb
feign. You might feign indifference when you hear about some gossip,
but you're probably dying to know.

Feign comes from the Latin fingere "to devise, fabricate." The word
fiction comes from the same source, so if you feign something such as
sleep, you give off the fiction that you are sleeping. This can be
done to be polite but also to deceive such as when you feign an injury
or the flu so you can stay home from school or work. You can also
feign an accent, though some are better at this than others.

Ninon knew that men and women are very different, but when it comes
to seduction they feel the same: Deep down inside, they often sense
when they are being seduced, but they give in because they enjoy the
feeling of being led along. It is a pleasure to let go, and to allow
the other person to detour you into a strange country. Everything in
seduction, however, depends on suggestion. You cannot announce your
intentions or reveal them directly in words. Instead you must throw
your targets off the scent. To surrender to your guidance they must
be appropriately confused. You have to scramble your signals—appear
interested in another man or woman (the decoy), then hint at being
interested in the target, then feign indifference, on and on. Such
patterns not only confuse, they excite.
* ulterior :misc:
[2023-05-21 Sun 11:24]

An ulterior interest, argument, or revelation is one you try to keep
hidden, like your ulterior motive for weeding your grandmother's
garden is to have a conversation with your crush — and Grandma's
neighbor — who happens to be outside, too.

The adjective ulterior is a Latin word which means “more distant” or
“future.” Something that is ulterior may lay the groundwork for what
comes later, like a new friend who hangs out with you at your house
but whose ulterior motive is to date one of your siblings, or the
incredible popularity of a series of novels set in a real place having
the ulterior consequences of that place becoming a tourist
destination.

Imagine this story from the countess’s perspective: After a few of
the marquis’s moves, she sensed the marquis was playing some sort of
game, but the game delighted her. She did not know where he was
leading her, but so much the better. His moves intrigued her, each of
them keeping her waiting for the next one—she even enjoyed her
jealousy and confusion, for sometimes any emotion is better than the
boredom of security. Perhaps the marquis had ulterior motives; most
men do. But she was willing to wait and see, and probably if she had
been made to wait long enough, what he was up to would not have
mattered.
* conniving :misc:
[2023-05-21 Sun 11:24]

Someone conniving is calculating, scheming, and shrewd — in other
words, sneaky and up to no good.

Do you know anyone who is always trying to get away with things? Do
they constantly look for ways to get out of trouble or work? Those
kind of people are conniving. This is a word for secretive, shifty
behavior. However, being conniving isn't the worst thing in the world
— it's negative, but you probably wouldn't say a murderer is
conniving. It's usually reserved for con men, shady business moguls,
and manipulative social climbers.

This put everything he had done in a new light. All that before had
been charming now seemed ugly and conniving; the countess felt
embarrassed and used. A door closed that would never open again.
* appease :misc:
[2023-05-21 Sun 11:25]

Appease means to make or preserve peace with a nation, group, or
person by giving in to their demands, or to relieve a problem, as in
"the cold drink appeased his thirst."

Appease often implies abandoning your moral principles to satisfy the
demands of someone who is greedy for power: think of British Prime
Minister Chamberlain's attempt to appease the Nazis at Munich. The
verb appease comes from the Old French apaisier, "to pacify, make
peace, or be reconciled," from the phrase "a paisier," which combines
a-, or "to," and pais, "peace," from the Latin pax.

In 1850 the young Otto von Bismarck, then a thirty-five-year-old
deputy in the Prussian parliament, was at a turning point in his
career. The issues of the day were the unification of the many states
(including Prussia) into which Germany was then divided, and a war
against Austria, the powerful neighbor to the south that hoped to
keep the Germans weak and at odds, even threatening to intervene if
they tried to unite. Prince William, next in line to be Prussia’s
king, was in favor of going to war, and the parliament rallied to the
cause, prepared to back any mobilization of troops. The only ones to
oppose war were the present king, Frederick William IV, and his
ministers, who preferred to appease the powerful Austrians.
* infamous :misc:
[2023-05-21 Sun 11:26]

Someone who is infamous has a very bad reputation. If you become a
Hollywood star and find yourself on the pages of gossip magazines for
your affairs and addictions, you will have succeeded in becoming
infamous.

Infamous is from Latin infamis, for negative fame. If you're bad but
unknown, then you're not infamous — it's reserved for those wicked and
well-known people that capture our collective imagination.  It is a
strong and resonant term. Some synonyms are notorious, disgraceful,
and odious. The stress is on the first syllable.

A few weeks after Bismarck’s infamous speech, the king, grateful that
he had spoken for peace, made him a cabinet minister. A few years
later he became the Prussian premier. In this role he eventually led
his country and a peace-loving king into a war against Austria,
crushing the former empire and establishing a mighty German state,
with Prussia at its head.