-*- coding: utf-8 -*-


* bungle :Gene:
[2024-03-13 Wed 10:42]

Saying the wrong thing at the wrong time, dropping something, tripping
and falling: these are some classic bungles — and they’re always
embarrassing.



I have noticed that, with few exceptions, men bungle their affairs. Everywhere I
see incompetence rampant, incompetence triumphant.

* rampant :Peter:
[2024-03-13 Wed 10:44]

Rampant means wild or out of control. Unruly children might run
rampant at the supermarket, knocking cereal boxes off shelves and
thoroughly annoying the customers.



I have noticed that, with few exceptions, men bungle their affairs. Everywhere I
see incompetence rampant, incompetence triumphant.

* lofty :Peter:
[2024-03-13 Wed 10:45]

Lofty is a good word for describing something that's high above the ground, or someone who acts like she's high above everyone else.



AS AN AUTHOR and journalist, I have had exceptional opportunities to study the
workings of civilized society. I have investigated and written about government,
industry, business, education and the arts. I have talked to, and listened
carefully to, members of many trades and professions, people of lofty, middling
and lowly stations.