-*- coding: utf-8 -*-


* circuitous :Iain:
[2024-05-10 Fri 11:20]

Circuitous means indirect or roundabout. If you're already late for
school, you'll want to take the straightest, fastest way there, not a
circuitous one!

* contested :Iain:
[2024-05-13 Mon 11:04]

Something that's contested is argued over or questioned. Contested
election results may need to be re-counted, since the two sides can't
agree on their validity.

To cut an extremely long story short what I came to real. And this is
not contested by any NE neurologist I know of anywhere in the world is
that the difference is one of attention, - so after a right hemisphere
stroke patients are often said to have a pathological narrowing of the
window of attention, but more than that they have a particular use of
that attention which is to get things so they're intent on getting
things controlling things.

* daunting :Iain:
[2024-05-14 Tue 15:24]

Something daunting can scare you off. If you have a lot of studying to
do, it may seem like a daunting task. Good news is you can get through
it by working hard. Or weasel out of it by playing sick.



This work may seem daunting, but in practice it should take you only a few
hours. That said, it might not be easy. You will have to challenge
yourself and go beyond the obvious. But you shouldn’t give up, because the
answers you’ll discover are so worthwhile. After all, what’s more
important than your life? Commit to thinking strategically about it, look
forward to the insights you will gain, and enjoy the journey.

* blatantly :Iain:
[2024-05-30 Thu 16:14]

When you do something blatantly, you do it obviously, without trying
to hide it. You might blatantly lie to your boss if you don't care
about getting in trouble.



Notes: You’ll see some code examples using lambda that seem to blatantly
ignore Python style best practices. This is only intended to illustrate
lambda calculus concepts or to highlight the capabilities of Python lambda.
