-*- coding: utf-8 -*-


* bungle :Gene:
[2024-03-13 Wed 10:42]

Saying the wrong thing at the wrong time, dropping something, tripping
and falling: these are some classic bungles — and they’re always
embarrassing.



I have noticed that, with few exceptions, men bungle their affairs. Everywhere I
see incompetence rampant, incompetence triumphant.

* rampant :Peter:
[2024-03-13 Wed 10:44]

Rampant means wild or out of control. Unruly children might run
rampant at the supermarket, knocking cereal boxes off shelves and
thoroughly annoying the customers.



I have noticed that, with few exceptions, men bungle their affairs. Everywhere I
see incompetence rampant, incompetence triumphant.

* lofty :Peter:
[2024-03-13 Wed 10:45]

Lofty is a good word for describing something that's high above the ground, or someone who acts like she's high above everyone else.



AS AN AUTHOR and journalist, I have had exceptional opportunities to study the
workings of civilized society. I have investigated and written about government,
industry, business, education and the arts. I have talked to, and listened
carefully to, members of many trades and professions, people of lofty, middling
and lowly stations.
* insolent :Peter:
[2024-03-28 Thu 10:44]

Someone who's insolent is either really doing her own thing, even if it goes against what everyone else is doing, or she’s mildly disrespectful.



We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* indolent :Peter:
[2024-03-28 Thu 10:44]

Indolent is an adjective meaning slow or lazy. It can take an indolent teenager hours to get out of bed on a weekend morning. Often it's noon before he finally comes shuffling down to breakfast in his pajamas.



We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* timidity :Peter:
[2024-03-28 Thu 10:45]

Do you suffer from timidity? If so, you probably feel uneasy in new places and situations. You might fear having to make decisions. But as you get more comfortable, your timidity will go away.



We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* belies :Peter:
[2024-03-28 Thu 10:45]

To belie means to contradict. If you are 93 but look like you are 53, then your young looks belie your age.



We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* servility :Peter:
[2024-03-28 Thu 10:45]



nil

We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* shrug :Peter:
[2024-03-28 Thu 10:46]



nil

We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* muddled :Peter:
[2024-03-28 Thu 10:47]

Muddled things are all mixed-up and confused. Your mind might feel muddled when you first wake up from a long nap.



We see indecisive politicians posing as resolute statesmen and the “authoritative
source” who blames his misinformation on “situational imponderables.” Limitless
are the public servants who are indolent and insolent; military commanders whose
behavioral timidity belies their dreadnaught rhetoric, and governors whose innate
servility prevents their actually governing. In our sophistication, we virtually
shrug aside the immoral cleric, corrupt judge, incoherent attorney, author who
cannot write and English teacher who cannot spell. At universities we see
proclamations authored by administrators whose own office communications are
hopelessly muddled; and droning lectures from inaudible or incomprehensible
instructors.
* affability :Peter:
[2024-03-28 Thu 10:48]

Affability is the quality of being easy to talk to. If you walk into a party smiling and generally seeming up for whatever, your affability will draw people to you. Affability and intelligence will get you far in this world!



MUNICIPAL GOVERNMENT FILE, CASE NO. 17 J. S. Minion1 was a maintenance foreman in
the public works department of Excelsior City. He was a favorite of the senior
officials at City Hall. They all praised his unfailing affability.
* foreman :Peter:
[2024-03-28 Thu 10:52]

On many job sites, the boss or supervisor is called the foreman. If you get a job on a construction crew, the foreman is the person in charge.



Minion still says “Yes” to everyone, and carries messages briskly back and forth
between his superiors and his subordinates. Nominally a superintendent, he
actually does the work of a messenger. The maintenance department regularly
exceeds its budget, yet fails to fulfill its program of work. In short, Minion, a
competent foreman, became an incompetent superintendent.
* zealous :Peter:
[2024-03-28 Thu 10:53]

Use the adjective zealous as a way to describe eagerness or
enthusiastic activity. If you are too zealous in your efforts to
decorate the house with Christmas lights, you might cause a power
outage for the whole neighborhood.



SERVICE INDUSTRIES FILE, CASE NO. 3 E. Tinker was exceptionally zealous and
intelligent as an apprentice at G. Reece Auto Repair Inc., and soon rose to
journeyman mechanic. In this job he showed outstanding ability in diagnosing
obscure faults, and endless patience in correcting them. He was promoted to
foreman of the repair shop.
* journeyman :Peter:
[2024-03-28 Thu 10:54]

A journeyman is someone who's advanced beyond being an apprentice, but
who works for someone else. A journeyman who works for a stone mason
is fairly experienced at masonry.



SERVICE INDUSTRIES FILE, CASE NO. 3 E. Tinker was exceptionally zealous and
intelligent as an apprentice at G. Reece Auto Repair Inc., and soon rose to
journeyman mechanic. In this job he showed outstanding ability in diagnosing
obscure faults, and endless patience in correcting them. He was promoted to
foreman of the repair shop.
* obscure :Peter:
[2024-03-28 Thu 10:54]

If something is obscure, it's vague and hard to see. Be careful if
you're driving in heavy rain — the painted lines can be obscure.



SERVICE INDUSTRIES FILE, CASE NO. 3 E. Tinker was exceptionally
zealous and intelligent as an apprentice at G. Reece Auto Repair Inc.,
and soon rose to journeyman mechanic. In this job he showed
outstanding ability in diagnosing obscure faults, and endless patience
in correcting them. He was promoted to foreman of the repair shop.
* liabilities :Peter:
[2024-03-28 Thu 10:55]



nil

But here his love of things mechanical and his perfectionism become liabilities.
* meddles :Peter:
[2024-03-28 Thu 10:56]

To meddle is to interfere. You can meddle in someone else's affairs,
and you can meddle with someone else's things. Either way, you’re
messing with someone else’s stuff and she probably doesn’t like it.



He meddles constantly. He is seldom to be found at his desk. He is usually up to
his elbows in a dismantled motor and while the man who should be doing the work
stands watching, other workmen sit around waiting to be assigned new tasks. As a
result the shop is always overcrowded with work, always in a muddle, and delivery
times are often missed.
