-*- coding: utf-8 -*-



* muddle :Peter:
[2024-04-09 Tue 15:59]

A muddle is something that's messy and confusing. If your bedroom
looks like a hurricane just hit it, you might describe it as a muddle.



He meddles constantly. He is seldom to be found at his desk. He is usually up to
his elbows in a dismantled motor and while the man who should be doing the work
stands watching, other workmen sit around waiting to be assigned new tasks. As a
result the shop is always overcrowded with work, always in a muddle, and delivery
times are often missed.

* racy :Peter:
[2024-04-09 Tue 16:00]

Something that's racy is zesty and exciting. The racy thriller you
checked out of the library is so engrossing that you can't put it
down, even at bedtime.



Goodwin. His hearty, informal manner, his racy style of speech, his scorn for
petty regulations and his undoubted personal bravery made him the idol of his
men. He led them to many well-deserved victories.

* scorn :Peter:
[2024-04-09 Tue 16:00]

Scorn is open disrespect for someone or something. It can also be
disrespect coupled with feelings of intense dislike.



Goodwin. His hearty, informal manner, his racy style of speech, his scorn for
petty regulations and his undoubted personal bravery made him the idol of his
men. He led them to many well-deserved victories.


