
* To mess around with (someone or something)

** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  Grandpa's [still] [messing around] with that old radio, but I doubt
  he'll [get] it to work again.


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  He [has been] [messing around] with [piston] engines since he was
  old enough to hold a [wrench], and he knew he had a problem.

* To tinker (around) with smth

  To make unprofessional or experimental attempts at repairing or
  improving something.

** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  I've been [tinkering with] the washing machine all afternoon, but
  nothing [I do] seems to fix it.


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  Bud likes to [tinker with] old car engines and see if he can make
  [them] run better than they [used to].

* get out of a jam

  To remedy a troublesome or difficult situation. 

** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  I have to [get out] of a jam, so is there [any chance] you can bring me
  those papers I left at home?


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  To free someone else from a [troublesome] or difficult situation. In
  this usage, a noun or pronoun is used between "get" and "out." Any
  chance you could bring me those papers I left at home? It would
  really [get me out of a jam].


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  He [got] himself of [out a jam] by calling his friends for help.

* be in (one's) dotage

To be in a state of senility or mental decline due to old age. 

** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  Just because we are in our 70s doesn't mean we are in our [dotage]! 


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide2cloze
  :END:

  You'd best treat your children [well], for [it is] [they] who will
  [look after] you when you're in your [dotage].

* to winnow away

  To remove some material, such as chaff, from grain by means of a current of air.


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  Modern machines can [winnow away] all the [chaff] very efficiently.


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  The farmers [winnow] the chaff [away] by [flinging] the grain into
  the air with a large blanket.


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  The process will [winnow away] the weakest candidates. 


** -->                                                                :drill:
  :PROPERTIES:
  :DRILL_CARD_TYPE: hide1cloze
  :END:

  Water currents [pick up] mud from the riverbank and [winnow] it
  [away], exposing the rock.
