-*- coding: utf-8 -*-

* snore                                                           :satellite:
[2017-10-10 Tue 05:16]

If you're snoring through a movie, you're probably not that
[interested] in it.

* vine :Satellite:
[2017-11-27 Mon 17:00]

In the grape-vine above our heads the geckos crept along the gnarled
branches, eagerly watching the drifts of insects that were drawn, like
a tide, by the lamplight.


* excitedly :Satellite:
[2017-11-27 Mon 17:00]

Down by the well the tree-frogs croaked excitedly to each other.


* bulging :Satellite:
[2017-11-27 Mon 17:02]

* tuck                                                            :satellite:
[2018-03-10 Sat 11:53]

Sandra, who is warm and calm and often wears a flower tucked into her
hair, arrived at the hospital at ten o’clock.


* tore :satellite:
[2018-03-12 Mon 14:39]

In the fields the maize was starting to fill out, the silken tassels
turning from brown to butter-blond; when you tore off the wrapping of
leaves and bit into the rows of pearly seeds the juice would spurt
into your mouth like milk.


* mantid                                                          :satellite:
[2018-03-12 Mon 14:42]

Among the myrtles the mantids moved, lightly, carefully, swaying
slightly, the quintessence of evil.


* swell                                                           :satellite:
[2018-03-12 Mon 14:44]

With bulging eyes staring as though hypnotized, their backs as shiny
as the leaves they sat amongst, they swelled out their vocal sacs and
croaked harshly and with such violence that they seemed in danger of
splitting their damp bodies with the effort.


* insidiously :satellite:
[2018-03-12 Mon 14:50]

But gradually the atmosphere of the island worked its way insidiously
under his skin, and he relaxed and became quite human.


* diffidently                                                     :satellite:
[2018-03-12 Mon 14:53]

Diffidently, I suggested I wrote a book, and Peter, somewhat startled,
but not being able to think of any reason why I should not write a
book, agreed.


It was an ancient brick wall that had been plastered over, but now
this outer skin was green with moss, bulging and sagging with the damp
of many winters.


* sagging :Satellite:
[2017-11-27 Mon 17:02]

It was an ancient brick wall that had been plastered over, but now
this outer skin was green with moss, bulging and sagging with the damp
of many winters.


* enrapture                                                       :Satellite:
[2017-12-03 Sun 13:13]

I was enraptured by this family, and I made up my mind to smuggle them
into the house and up to my bedroom so that I might keep them and
watch them grow up.


* dawdling                                                        :Satellite:
[2017-12-03 Sun 13:14]

Dawdling over my food, feeding Roger surreptitiously under the table
and listening to the family arguing, I completely forgot about my
exciting new captures.


* glibly :Satellite:
[2017-12-03 Sun 13:15]

Oblivious of my impending doom I watched him interestedly as, still
talking glibly, he opened the matchbox.


* utter                                                           :Satellite:
[2017-12-03 Sun 13:18]

He uttered a roar of fright that made Lugaretzia drop a plate and
brought Roger out from beneath the table, barking wildly.


* imploring :Satellite:
[2017-12-03 Sun 13:21]

Mother kept imploring, mopping her glasses.


* scone                                                           :satellite:
[2017-12-25 Mon 10:24]

Theodore would carefully place his half-eaten scone on his plate.


* bated :satellite:
[2017-12-25 Mon 10:27]

Theodore, eyes narrowed, beard bristling, watched it with bated
breath.


* keel                                                            :satellite:
[2018-01-04 Thu 17:12]

She gave her series of “Come to the cookhouse, boys” trills—then
promptly keeled over again.


* tug                                                             :satellite:
[2018-01-04 Thu 17:13]

For the last few minutes, something had been tugging at my memory.


* aid                                                             :satellite:
[2018-01-31 Wed 09:47]

The programming tools will include program development aids such as
specification analysers, interrogators, checkers, and animators


* interleave                                                      :satellite:
[2018-02-02 Fri 15:27]

Interleave


* porch :satellite:
[2018-02-02 Fri 15:28]

After the initial subdued greetings, they sat on the porch, looking
out to sea while the robot fussed around bearing drinks and plates of
assorted fruit.


* unreconciled :satellite:
[2018-02-02 Fri 15:30]

Delegation The President of Thalassa had been in office for only two
months and was still unreconciled to his misfortune.


* discourteous :satellite:
[2018-02-02 Fri 15:33]

It might seem discourteous to refuse, and after all, they were anxious
to make friends as quickly as possible.


* derate                                                          :satellite:
[2018-02-02 Fri 15:34]

'It's a derated quantum ramjet, adapted for atmospheric flight by
using air as a working fluid.


* ramjet :satellite:
[2018-02-02 Fri 15:34]

'It's a derated quantum ramjet, adapted for atmospheric flight by
using air as a working fluid.


* discordantly                                                    :satellite:
[2018-02-02 Fri 15:46]

Perhaps it was just as well that their tides were barely perceptible,
the thought of five- and seven-day cycles clashing discordantly
together was so comically horrible that she could not help smiling and
immediately felt much better.


* squinting :satellite:
[2018-02-02 Fri 15:47]

Brant shielded his eyes and peered around the edge, squinting against
the glare.


* untarnished :satellite:
[2018-02-02 Fri 15:49]

Spilling round the edges of the still-untarnished cylinder was a flood
of light, apparently from a single brilliant source.

* percussive                                                      :satellite:
[2018-04-17 Tue 10:57]

And I can’t find any behavioral science research on terms such as
“Percussive Sublimation” (“being kicked upstairs: a pseudo promotion
”) and “Peter’s Circumambulation” (“a detour around a
super-incumbent,” who is “a person above you who, having reached his
level of incompetence, blocks your path to promotion”).


* perversely :satellite:
[2018-04-18 Wed 11:51]

Peter (and coauthor Raymond Hull) decided to cloak these ideas in such
a delightfully weird and perversely funny package.


* disguised :satellite:
[2018-04-18 Wed 11:53]

Peter’s intentions, writing a serious business book disguised as a
parody was a stroke of genius.


* upends :satellite:
[2018-04-17 Tue 10:53]

Satire works when it exposes the truth and upends fallacy.


* devilishly :satellite:
[2018-04-17 Tue 10:52]

Another reason The Peter Principle has no peer is that it somehow
manages to be devilishly silly yet accurate and useful all at the same
time.


* barring :satellite:
[2018-04-17 Tue 10:51]

But when his coach refused to stop Jericho from pitching, the league
hierarchy responded by barring Jericho from pitching and disbanding
his undefeated team.



* relishing :satellite:
[2018-02-02 Fri 15:55]

'I agree completely with the councillor,' Mayor Waldron said,
relishing this unusual opportunity.


* remorselessly :satellite:
[2018-02-02 Fri 16:06]

He knew how, as the centuries ticked remorselessly by, the
astronomers' diagnosis became ever more confident, the date of their
prediction steadily more precise.



* disconfirming :Holmes:
[2018-05-12 Sat 10:48]

In the case of the pink elephants the disconfirming process is simple.


* slyly :Holmes:
[2018-05-13 Sun 14:52]

That those same thoughts, properly filtered, can no longer slyly
influence your behavior without your knowledge.


* prominently :Holmes:
[2018-05-14 Mon 14:49]

When I first heard the term brain attic—back in the days of firelight
and the old crimson hardcover—all I could picture in my seven-year-old
head was the cover of the black-and-white Shel Silverstein book that
sat prominently on my bookshelf, with its half-smiling, lopsided face
whose forehead was distended to a wrinkled triangle, complete with
roof, chimney, and window with open shutters.


* jumbled :Holmes:
[2018-05-14 Mon 14:53]

As Holmes explains to Watson, “A fool takes in all the lumber of every
sort that he comes across, so that the knowledge which might be useful
to him gets crowded out, or at best is jumbled up with a lot of other
things, so that he has a difficulty in laying his hands upon it.


* outward :Holmes:
[2018-05-14 Mon 14:59]

Guessing at the contents of a person’s attic from his outward
appearance becomes one of Sherlock’s surest ways of determining who
that person is and what he is capable of.


