-*- coding: utf-8 -*-

* snore                                                           :satellite:
[2017-10-10 Tue 05:16]

If you're snoring through a movie, you're probably not that
[interested] in it.

* vine :Satellite:
[2017-11-27 Mon 17:00]

In the grape-vine above our heads the geckos crept along the gnarled
branches, eagerly watching the drifts of insects that were drawn, like
a tide, by the lamplight.


* excitedly :Satellite:
[2017-11-27 Mon 17:00]

Down by the well the tree-frogs croaked excitedly to each other.


* bulging :Satellite:
[2017-11-27 Mon 17:02]

* tuck                                                            :satellite:
[2018-03-10 Sat 11:53]

Sandra, who is warm and calm and often wears a flower tucked into her
hair, arrived at the hospital at ten o’clock.


* tore :satellite:
[2018-03-12 Mon 14:39]

In the fields the maize was starting to fill out, the silken tassels
turning from brown to butter-blond; when you tore off the wrapping of
leaves and bit into the rows of pearly seeds the juice would spurt
into your mouth like milk.


* mantid                                                          :satellite:
[2018-03-12 Mon 14:42]

Among the myrtles the mantids moved, lightly, carefully, swaying
slightly, the quintessence of evil.


* swell                                                           :satellite:
[2018-03-12 Mon 14:44]

With bulging eyes staring as though hypnotized, their backs as shiny
as the leaves they sat amongst, they swelled out their vocal sacs and
croaked harshly and with such violence that they seemed in danger of
splitting their damp bodies with the effort.


* insidiously :satellite:
[2018-03-12 Mon 14:50]

But gradually the atmosphere of the island worked its way insidiously
under his skin, and he relaxed and became quite human.


* diffidently                                                     :satellite:
[2018-03-12 Mon 14:53]

Diffidently, I suggested I wrote a book, and Peter, somewhat startled,
but not being able to think of any reason why I should not write a
book, agreed.


It was an ancient brick wall that had been plastered over, but now
this outer skin was green with moss, bulging and sagging with the damp
of many winters.


* sagging :Satellite:
[2017-11-27 Mon 17:02]

It was an ancient brick wall that had been plastered over, but now
this outer skin was green with moss, bulging and sagging with the damp
of many winters.


* enrapture                                                       :Satellite:
[2017-12-03 Sun 13:13]

I was enraptured by this family, and I made up my mind to smuggle them
into the house and up to my bedroom so that I might keep them and
watch them grow up.


* dawdling                                                        :Satellite:
[2017-12-03 Sun 13:14]

Dawdling over my food, feeding Roger surreptitiously under the table
and listening to the family arguing, I completely forgot about my
exciting new captures.


* glibly :Satellite:
[2017-12-03 Sun 13:15]

Oblivious of my impending doom I watched him interestedly as, still
talking glibly, he opened the matchbox.


* utter                                                           :Satellite:
[2017-12-03 Sun 13:18]

He uttered a roar of fright that made Lugaretzia drop a plate and
brought Roger out from beneath the table, barking wildly.


* imploring :Satellite:
[2017-12-03 Sun 13:21]

Mother kept imploring, mopping her glasses.


* scone                                                           :satellite:
[2017-12-25 Mon 10:24]

Theodore would carefully place his half-eaten scone on his plate.


* bated :satellite:
[2017-12-25 Mon 10:27]

Theodore, eyes narrowed, beard bristling, watched it with bated
breath.


* keel                                                            :satellite:
[2018-01-04 Thu 17:12]

She gave her series of “Come to the cookhouse, boys” trills—then
promptly keeled over again.


* tug                                                             :satellite:
[2018-01-04 Thu 17:13]

For the last few minutes, something had been tugging at my memory.


* aid                                                             :satellite:
[2018-01-31 Wed 09:47]

The programming tools will include program development aids such as
specification analysers, interrogators, checkers, and animators


* interleave                                                      :satellite:
[2018-02-02 Fri 15:27]

Interleave


* porch :satellite:
[2018-02-02 Fri 15:28]

After the initial subdued greetings, they sat on the porch, looking
out to sea while the robot fussed around bearing drinks and plates of
assorted fruit.


* unreconciled :satellite:
[2018-02-02 Fri 15:30]

Delegation The President of Thalassa had been in office for only two
months and was still unreconciled to his misfortune.


* discourteous :satellite:
[2018-02-02 Fri 15:33]

It might seem discourteous to refuse, and after all, they were anxious
to make friends as quickly as possible.


* derate                                                          :satellite:
[2018-02-02 Fri 15:34]

'It's a derated quantum ramjet, adapted for atmospheric flight by
using air as a working fluid.


* ramjet :satellite:
[2018-02-02 Fri 15:34]

'It's a derated quantum ramjet, adapted for atmospheric flight by
using air as a working fluid.


* discordantly                                                    :satellite:
[2018-02-02 Fri 15:46]

Perhaps it was just as well that their tides were barely perceptible,
the thought of five- and seven-day cycles clashing discordantly
together was so comically horrible that she could not help smiling and
immediately felt much better.


* squinting :satellite:
[2018-02-02 Fri 15:47]

Brant shielded his eyes and peered around the edge, squinting against
the glare.


* untarnished :satellite:
[2018-02-02 Fri 15:49]

Spilling round the edges of the still-untarnished cylinder was a flood
of light, apparently from a single brilliant source.

* percussive                                                      :satellite:
[2018-04-17 Tue 10:57]

And I can’t find any behavioral science research on terms such as
“Percussive Sublimation” (“being kicked upstairs: a pseudo promotion
”) and “Peter’s Circumambulation” (“a detour around a
super-incumbent,” who is “a person above you who, having reached his
level of incompetence, blocks your path to promotion”).


* perversely :satellite:
[2018-04-18 Wed 11:51]

Peter (and coauthor Raymond Hull) decided to cloak these ideas in such
a delightfully weird and perversely funny package.


* disguised :satellite:
[2018-04-18 Wed 11:53]

Peter’s intentions, writing a serious business book disguised as a
parody was a stroke of genius.


* upends :satellite:
[2018-04-17 Tue 10:53]

Satire works when it exposes the truth and upends fallacy.


* devilishly :satellite:
[2018-04-17 Tue 10:52]

Another reason The Peter Principle has no peer is that it somehow
manages to be devilishly silly yet accurate and useful all at the same
time.


* barring :satellite:
[2018-04-17 Tue 10:51]

But when his coach refused to stop Jericho from pitching, the league
hierarchy responded by barring Jericho from pitching and disbanding
his undefeated team.



* relishing :satellite:
[2018-02-02 Fri 15:55]

'I agree completely with the councillor,' Mayor Waldron said,
relishing this unusual opportunity.


* remorselessly :satellite:
[2018-02-02 Fri 16:06]

He knew how, as the centuries ticked remorselessly by, the
astronomers' diagnosis became ever more confident, the date of their
prediction steadily more precise.



* disconfirming :Holmes:
[2018-05-12 Sat 10:48]

In the case of the pink elephants the disconfirming process is simple.


* slyly :Holmes:
[2018-05-13 Sun 14:52]

That those same thoughts, properly filtered, can no longer slyly
influence your behavior without your knowledge.


* prominently :Holmes:
[2018-05-14 Mon 14:49]

When I first heard the term brain attic—back in the days of firelight
and the old crimson hardcover—all I could picture in my seven-year-old
head was the cover of the black-and-white Shel Silverstein book that
sat prominently on my bookshelf, with its half-smiling, lopsided face
whose forehead was distended to a wrinkled triangle, complete with
roof, chimney, and window with open shutters.


* jumbled :Holmes:
[2018-05-14 Mon 14:53]

As Holmes explains to Watson, “A fool takes in all the lumber of every
sort that he comes across, so that the knowledge which might be useful
to him gets crowded out, or at best is jumbled up with a lot of other
things, so that he has a difficulty in laying his hands upon it.


* outward :Holmes:
[2018-05-14 Mon 14:59]

Guessing at the contents of a person’s attic from his outward
appearance becomes one of Sherlock’s surest ways of determining who
that person is and what he is capable of.


* instill                                                         :satellite:
[2018-05-03 Thu 11:45]

The concept of continuous delivery showed how we can more effectively
and efficiently get our software into production, instilling in us the
idea that we should treat every check-in as a release candidate.


* taunting :Holmes:
[2018-05-04 Fri 15:32]

And then there’s the one thing that wedged its way so deeply into my
brain that it remained there, taunting me, for years to come, when the
rest of the stories had long since faded into some indeterminate
background and the adventures of Holmes and his faithful Boswell were
all but forgotten: the steps.


* exquisitely                                                        :Holmes:
[2018-05-04 Fri 15:49]

And because of the inherent newness of our surroundings, we are
exquisitely alert; we are absorbed; we take it all in.


* mindlessness                                                       :Holmes:
[2018-05-05 Sat 08:51]

And while that’s not inherently a bad thing—in fact, we’ll be talking
repeatedly about the need to automate certain processes that are at
first difficult and cognitively costly—it is dangerously close to
mindlessness.


* thoughtlessness                                                    :Holmes:
[2018-05-05 Sat 08:51]

It’s a fine line between efficiency and thoughtlessness—and one that
we need to take care not to cross.


* mutilations                                                        :Holmes:
[2018-05-05 Sat 08:59]

In 1903, twenty-seven-year-old Edalji was sentenced to seven years of
hard labor for one of the sixteen mutilations, that of a pony whose
body had been found in a pit near the vicar’s residence.


* legitimately                                                       :Docker:
[2018-05-05 Sat 10:13]

In addition, some part of your domain may be legitimately complex,
requiring more code.


* windup                                                             :Holmes:
[2018-05-05 Sat 16:39]

Finally, he came upon a promising beginning: a series of pictures, of
a windup toy, an automobile, and a boy on a bicycle.


* acknowledged                                                       :Holmes:
[2018-05-05 Sat 16:42]

These questions weren’t ever acknowledged, never mind answered.


* inquisitiveness                                                    :Holmes:
[2018-05-10 Thu 09:08]

One of the things that characterizes Holmes’s thinking—and the
scientific ideal—is a natural skepticism and inquisitiveness toward
the world.


* jumbled :Holmes:
[2018-05-15 Tue 14:30]

Our default System Watson attic is jumbled and largely mindless.


* woozily :Holmes:
[2018-05-15 Tue 14:34]

Though the rats’ motor function declined and some had to hobble or
crawl their way woozily through the twists and turns, the animals
never altogether forgot their way, leading Lashley to conclude that
there was no single location that stored a given memory.


* plainness :Holmes:
[2018-05-19 Sat 21:07]

There was, however, a plainness and simplicity about her costume which
bore with it a suggestion of limited means.


* clogging :Holmes:
[2018-05-19 Sat 21:15]

Or, maybe Joe Stranger is actually Jane Stranger and her hair is dyed
the same shade of blue as your childhood best friend dyed her hair
right before you stopped talking to each other, and you always thought
the hair was the first sign of your impending break, and now all of a
sudden, all of these memories are clogging your brain and coloring the
way you see this new person, innocent Jane.


* steadfastness :Holmes:
[2018-05-20 Sun 11:32]

His steadfastness will be all the stronger because of the physical
nature of the initial trigger: faces are perhaps the most powerful cue
we have—and the most likely to prompt associations and actions that
just won’t go away.


* hoop                                                               :Holmes:
[2018-05-20 Sun 11:46]

All the while, Watson will likely remain completely unaware of the
hoops through which his mind is jumping to maintain a coherent
impression of Mary, to form a narrative based on discrete inputs that
makes sense and tells an intuitively appealing story.
* wit                                                                :Holmes:
[2018-05-21 Mon 12:12]

But only after she has bested him in a battle of wits, showing herself
to be a more formidable opponent, male or female, than he has ever
encountered.)


* gravely :Holmes:
[2018-05-21 Mon 16:53]

But Holmes shook his head gravely.


* dodging                                                            :Ferris:
[2018-06-02 Sat 16:11]

3 Dodging Bullets


* envisioning :Ferris:
[2018-06-03 Sun 10:23]

Then, one day, in my bliss of envisioning how bad my future suffering
would be, I hit upon a gem of an idea.


* prudent :Ferris:
[2018-06-03 Sun 10:22]

Describe an action as prudent if it is the wise thing to do under the
existing circumstances. If you're getting in trouble, it is probably
prudent to keep your mouth closed and just listen.

If you show good and careful judgment when handling practical matters,
you can be described as prudent. Similarly, a wise and
well-thought-through decision or action can be called prudent. The
word comes from a contracted form of the Latin prōvidēns from the verb
"to foresee." The English word provident "wise in planning for the
future" is the non-contracted descendent of the same Latin root.

First, I felt it
prudent to dance around with my shame, embarrassment, and anger for six
months, all the while playing an endless loop of reasons why my cop-out
fantasy trip could never work.
`* spook :Ferris:
[2018-06-03 Sun 10:25]

I suppose someone would probably spit on my head from a high-rise
balcony while I’m feeding food scraps to a stray dog, which would then
spook and bite me squarely on the face.


* squarely :Ferris:
[2018-06-03 Sun 10:25]

I suppose someone would probably spit on my head from a high-rise
balcony while I’m feeding food scraps to a stray dog, which would then
spook and bite me squarely on the face.


* disguised :Ferris:
[2018-06-03 Sun 10:56]

This is fear of the unknown disguised as optimism.


* disservice :Docker:
[2018-06-03 Sun 20:38]

When we compare ourselves to engineers or architects, we are in danger
of doing everyone a disservice.


* gunk :Holmes:
[2018-05-29 Tue 16:59]

That gunk between your teeth that comes out when you floss?


* perversely :Holmes:
[2018-06-02 Sat 11:20]

Peter (and coauthor Raymond Hull) decided to [cloak] these ideas in
   such a [delightfully weird] and [perversely funny] package.


* inalterable :Ferris:
[2018-06-02 Sat 16:00]

Absolute income is measured using one holy and inalterable variable:
the raw and almighty dollar.


* subpar :Ferris:
[2018-06-02 Sat 16:09]

2 How has doing what you “should” resulted in subpar experiences or
 regret for not having done something else?


* elves :Ferris:
[2018-06-03 Sun 10:18]

I could hire magic elves and connect my brain to a supercomputer—it
didn’t matter.


* undying :Ferris:
[2018-06-03 Sun 10:34]

In my undying quest to make myself miserable, I accidentally began to
backpedal.


* upswing :Ferris:
[2018-06-03 Sun 11:09]

What steps could you take to repair the damage or get things back on
the upswing, even if temporarily?


* overly :Docker:
[2018-06-03 Sun 19:40]

It doesn’t talk enough about real-world, practical ways to ensure that
services do not become overly coupled.


* subpar :Ferris:
[2018-05-28 Mon 14:56]

If everyone is defining a problem or solving it one way and the
results are subpar, this is the time to ask, What if I did the
opposite?


* lest :Holmes:
[2018-05-28 Mon 15:54]

He remains constantly active and constantly vigilant, lest a stray
prime worm its way into the walls of his pristine mind space.


* nestled                                                            :Ferris:
[2018-05-28 Mon 14:09]

Nestled in the tropics of the Coral Sea, New Caledonia was a French
territory and where Julie and Marc had just sold the sailboat that
took them 15,000 miles around the world.


* sheared :Coelho:
[2018-06-13 Wed 14:03]

The merchant was the proprietor of a dry goods shop, and he always
demanded that the sheep be sheared in his presence, so that he would
not be cheated.


* nourishment :Coelho:
[2018-06-13 Wed 14:10]

They trust me, and they’ve forgotten how to rely on their own
instincts, because I lead them to nourishment.


* imploring :Durrell:
[2018-06-24 Sun 09:03]

Mother kept imploring, mopping her glasses.


* dawdling                                                          :Durrell:
[2018-06-24 Sun 08:51]

Dawdling over my food, feeding Roger surreptitiously under the table
and listening to the family arguing, I completely forgot about my
exciting new captures.


* boastful :Ferris:
[2018-07-08 Sun 12:39]

When a character from Shakespeare calls the world his oyster, that's
  his boastful way of saying that all the riches of the world are his
  for the taking, like plucking a pearl from an oyster shell.


* flagellation :Ferris:
[2018-07-08 Sun 07:31]

I realized during the 80/20 analysis that these two people were the
source of nearly all my unhappiness and anger throughout the day, and
it usually spilled over into my personal time, keeping me up at night
with the usual “I should have said X, Y, and Z to that penis”
self-flagellation.


* skeweed :Ferris:
[2018-07-08 Sun 07:09]

The list is infinitely long and diverse, and the ratio is often
skeweed even more severely: 90/10, 95/5, and 99/1 are not uncommon,
but the minimum ratio to seek is 80/20.



* destine :satellite:
[2018-08-17 Fri 18:12]

On the flip side of that coin, there are those whose biological traits
destine them to be intelligent


* splintering :Durrell:
[2018-08-16 Thu 20:04]

To begin with, her eyes not having become accustomed to the dark,
Mother skilfully steered us in a tight circle, so that after ten
minutes' strenuous rowing the jetty suddenly loomed up and we ran into
it with a splintering crash.


* coyly :Durrell:
[2018-08-16 Thu 17:23]

Eventually, however, under constant pressure from us, Mother paid a
visit into town and returned to the villa coyly bearing a mysterious
parcel.


* nightjars :Durrell:
[2018-08-16 Thu 16:36]

The nightjars on silent, silky wings would slide as smoothly as great
black swallows along the rows of olives, sweeping across the grass in
pursuit of the drunken, whirling crane-flies.


* locust                                                            :Durrell:
[2018-08-16 Thu 11:48]

The grasshoppers and locusts whirred like clockwork under my feet, and
flew drunkenly across the heather, their wings shining in the sun.


* mantids :Durrell:
[2018-08-16 Thu 11:48]

Among the myrtles the mantids moved, lightly, carefully, swaying
slightly, the quintessence of evil.


* insidiously :Durrell:
[2018-08-16 Thu 11:54]

But gradually the atmosphere of the island worked its way insidiously
under his skin, and he relaxed and became quite human.


* startled :Durrell:
[2018-08-16 Thu 11:56]

Diffidently, I suggested I wrote a book, and Peter, somewhat startled,
but not being able to think of any reason why I should not write a
book, agreed.


* plodding :Durrell:
[2018-08-16 Thu 11:42]

So we would walk on through the hot afternoon, pausing by the pools
and ditches and stream, wading through the heavily scented
myrtle-bushes, over the hillsides crisp with heather, along white,
dusty roads where we were occasionally passed by a drooping, plodding
donkey carrying a sleepy peasant on its back.


* unsettle :satellite:
[2018-08-16 Thu 11:07]

strange or mysterious, especially in an unsettle way.


* unsettling :satellite:
[2018-08-16 Thu 11:07]

strange or mysterious, especially in an unsettling way.


* overhanging :satellite:
[2018-08-16 Thu 11:04]

overhanging.


* boast                                                           :satellite:
[2018-08-14 Tue 08:37]

When a character from Shakespeare calls the world his oyster, that's
his boastful way of saying that all the riches of the world are his
for the taking, like plucking a pearl from an oyster shell.



* condemning :satellite:
[2018-09-09 Sun 14:40]

If he had known more of that power, he would not have made the mistake
of condemning genius without giving it an opportunity.



* missteps :Duke:
[2018-09-09 Sun 16:09]

Many decision-making missteps originate from the pressure on the
reflexive system to do its job fast and automatically.


* undergird :satellite:
[2018-12-06 Thu 00:50]

These life-support factors also undergird every other dimension of
life.


* proactivity :satellite:
[2018-12-05 Wed 12:37]

Once you have that sense of mission, you have the essence of your own
proactivity.


* comp :satellite:
[2018-12-04 Tue 18:57]

So, for example, after ordering my iced latte, I’ll give a Starbucks
barista a $20.00 bill and tell him or her to comp the person right
after the person behind me for whatever he or she wants, and to give
that person the change as well.


* unflagging :satellite:
[2018-12-04 Tue 17:26]

It’s especially hard for me because of my inherent optimism and my
unflagging enthusiasm, and because I always lean into each moment and
every encounter expecting magic or miracles, and because life has
rewarded me increasingly with tantalizing offers.


* bestie :satellite:
[2018-12-04 Tue 17:04]

Then, about two years ago, my bestie, Josh Wateskin, recognizing that
I couldn’t unwind or disengage from my relentless analyzing of the
world – especially the financial world – recommended that I take up
meditation.


* lawnmower :Covey:
[2018-10-19 Fri 13:08]

A few years ago, I purchased a physical asset—a power lawnmower.


* dwindling :Covey:
[2018-10-19 Fri 13:10]

And the dwindling capital becomes smaller and smaller until it no
longer supplies even basic needs.


* wobbly :Covey:
[2018-10-20 Sat 14:01]

But everyone agrees on the current meaning: someone who falters is
  unsteady, wobbly, or unsure.


* bratty :Covey:
[2018-10-24 Wed 18:27]

Environmental determinism basically says your boss is doing it to
you—or your spouse, or that bratty teenager, or your economic
situation, or national policies.


* conditioning :Covey:
[2018-10-24 Wed 18:40]

They do not blame circumstances, conditions, or conditioning for their
behavior.


* excitedly :Covey:
[2018-10-24 Wed 18:47]

Once in Sacramento when I was speaking on the subject of proactivity,
a woman in the audience stood up in the middle of my presentation and
started talking excitedly.


* wasting :Covey:
[2018-10-30 Tue 09:09]

One of the most inspiring times Sandra and I have ever had took place
over a four-year period with a dear friend of ours named Carol, who
had a wasting cancer disease.


* undistorted :Covey:
[2018-10-30 Tue 09:19]

By respecting the proactive nature of other people, we provide them
with at least one clear, undistorted reflection from the social
mirror.


* tempered :Napoleon:
[2018-09-03 Mon 16:19]

Take courage, for these experiences have tempered the spiritual metal
of which you are made--they are assets of incomparable value.


* handicapped :Napoleon:
[2018-09-04 Tue 11:03]

Washington was born in slavery, handicapped by race and color.


* fiddling :satellite:
[2018-09-06 Thu 09:24]

You can change that format to whatever you want by fiddling with the
‘gnus-group-line-format’ variable.




* swerve                                                               :Duke:
[2018-09-09 Sun 16:12]

We have habits and defaults that we rarely examine, from gripping a
pencil to swerving to avoid an auto accident.


* reconcile                                                            :Duke:
[2018-09-09 Sun 16:30]

Poker players don’t need to know the underlying science to understand
the difficulty of reconciling the two systems.


* breakneck :Duke:
[2018-09-09 Sun 16:32]

This means a poker player makes hundreds of decisions per session, all
of which take place at breakneck speed.


* irresolvable :Duke:
[2018-09-09 Sun 16:35]

The best players must find ways to harmonize otherwise irresolvable
conflicts.


