* 26 advanced words                                                  :Gideon:
  Can you speak English ok and yet you find it difficult to understand
native English speakers? can you have a conversation but find it hard
to understand films and TV shows in English? Can you write an email
without problem but when you read a newspaper article or a novel you
kind of get lost? If so then you may be suffering from that well-known
malady - stuck at intermediate. You can't sleep at night you feel
nervous, anxious.

  You wake up in the middle of the night in a cold sweat. No? okay
exaggerating a bit but listen - learning a language, any language, is
like a triangle: lots of beginners stuck at the bottom and a large
section in the middle trapped at intermediate and just a few reaching
advanced level. Now my job here at LetThemTalk is to get you from
intermediate to advanced level from B1 or B2 to C1 or C2 and if I
manage to do that then my job is done and I'll give up making videos
and spend the rest of my days on the sofa eating donuts and watching
Netflix and trying to learn the ukulele.

  So today we've got 26 words to propel you from intermediate to
advanced and these words you can start using in written and spoken
English. Twenty six - one for each letter of the alphabet from A to Z
and I'll show you how you can use each word with a definition and an
example sentence. Let me just give you an example before we start this.
Take the word CONFUSED. It's an intermediate word, I'm sure you know
what it means. For example I was confused this morning: I put the keys
in the fridge and I tried to lock the door with the butter.

  No problem there we might use that - native speakers might say it
like that, but you could use another word. A native speaker might use
an advanced words such as MUDDLE or IN A MUDDLE: "I was in such a
muddle this morning - I tried to put my trousers on my head and I
stepped into my hat". So this is just one example.

  So words that native speakers or advanced users will use. 26 words
that will help your speaking and help your comprehension coming right
up so stay tuned.

  Hello and welcome to LetThemTalk and today we've got 26 words to
take you from intermediate to advanced English. Now these are all
common words with one possible exception which I'll explain in a
minute so let's go.

  A is for ALBEIT. Now this is an extremely useful word that you use
to show a contrast to a statement that you've just made for example
"You made a lot of progress, albeit slowly." So you have a statement
followed by ALBEIT followed by an adverb or adverbial phrase or an
adjective which contradicts or modifies the earlier phrase. And the
beautiful thing about ALBEIT is that it can be followed by just one
word you don't need a pronoun, you don't need a verb - just an adverb
or an adjective phrase. Another example: "he arrived at the meeting
albeit an hour late". You see no verb no pronoun.

  B is for BUDGE and this is a synonym of to move or change position
and we especially use it when we want to talk about people changing
their minds or their decisions so for example: "we asked them to
improve their offer but they wouldn't budge." "We tried to convince
the President to resign but he wouldn't budge." You can also use it to
mean move something heavy "hey! can you help me budge the sofa." So
there you are you can use BUDGE instead of MOVE.

  C is for COMEUPPANCE which means a punishment or fate that someone
deserves "He's a dishonest guy now he's free but one day he'll get his
comeuppance and end up in prison."  "All those people who try to hide
their millions in tax havens got their comeuppance when the newspaper
published their names."

  D is for DODGY. DODGY is a great word because it has so many
uses. It can mean suspicious or bad quality or strange for example:
"it's got a dodgy haircut" "There's a dodgy man outside". "My position
in this company is a bit dodgy: I might lose my job any minute."

  E is for TO EGG ON. Now you all know what an egg is but TO EGG ON is
a phrasal verb meaning to encourage but in a bad way we could also say
to incite for example "the accused would never normally steal anything
but his so-called friends egged him on. It was a case of peer pressure
Your Honor." "Look I don't want to take any drugs stop egging me on."
by the way EGG ON doesn't have anything to do with eggs It comes from
an old-world Old Norse world EGGJA (not sure I'm pronouncing that
right) which means to incite and it's been in the English language
since around 1200.

  F is for flustered. Flustered which means to be confused and nervous
at the same time. "I always get flustered when lots of people are
asking me lots of questions at same time."; "I was getting flustered
because my train was delayed and I thought I would miss my flight."

  G is for GALORE isn't that beautiful word GALORE and GALORE comes
from Scottish Gaelic. There aren't many words in English language from
Gaelic but this is one of them and it just means a lot, much or many
but in a positive way. But the trick about GALORE is that it comes
after the noun. It's quite a literary and poetic word but it's common
enough so do use it for example "For my birthday everybody bought me a
bottle of whisky. So now I have whisky galore." WHISKEY is also a Gaelic
word which means water of life. So WHISKY GALORE is the only phrase in
the English language just using words from Gaelic. "I went to the tech
show and there were gadgets galore. Wonderful wonderful gadgets."

  H is for HULLABALOO now this means a lot of noise, a fuss, a
disturbance a commotion. For example "On the first day of the sales
there was quite a hullabaloo outside the shop just before it
opened". "I just wanted to get a refund but God what a hullabaloo they
made of it all."

  I is for INKLING. Now INKLING is another way of saying that you have
a feeling that something might happen or something is true an idea
even though you're not 100% sure. So for example "I have an inkling
that Jane might break up with Jim. Something she said gave me the
impression that she's not happy." "I have an inkling that Johnson had
something to do with the murder even though he denies it. Yes indeed I
think Johnson"

  J is for JAUNT. Now JAUNT is usually a noun and it means taking a
short trip for pleasure. For example "I say Samantha, do you fancy
taking a jaunt with me in my vintage Bugatti this Sunday." "I don't
travel much these days except for the occasional jaunt to visit my
family in Scotland"

  K is for KNACK. KNACK means a skill or an ability or a talent.
Usually something positive but not always. For example "you've got a
knack for choosing the right moment" but it could be used to describe
a negative talent - for example: "you really have a knack for saying the
wrong thing at the wrong time"

  L is for LEEWAY and it means a little bit of freedom or space to act.
We often use it to talk about a little extra or additional time we've
been given. So for example: "I think we should get to the airport two
hours ahead and not one and a half hours that will give us a little
leeway in case we are held up in bad traffic."  "The deadline for tax
returns is the 31st of March however they usually give you a few days
leeway so it arrives on the second or third of April you are probably
still OK."

  M is for MAVERICK this is a noun and refers to someone who acts in a
non conformist way often breaking the rules but it's used positively
"She is a maverick politician she didn't join any political party but
still got elected as an independent." "Detective Jones was something
of a maverick his techniques and his investigations were really
unconventional but he got results."

  N is for NITPCIK to NITPICK is the verb and NITPICKING is the noun
and it means to criticize someone for small unimportant details for
example "you are complaining because I use the American spelling of
color C-o-l-o-r does it matter you're just nitpicking" "so I forgot to
clean one teaspoon and you complain to the manager you like to nitpick
don't you"

  O is for OOZE which has two meanings it can mean a liquid coming out
slowly from inside of something such as blood oozing out of a wound
but the meaning I want to talk about today is when we use it
figuratively to mean a powerful impression of something so for example
"she used confidence", "he used sex appeal", "she used charisma."

  P is for PUSSYFOOT yeah I know it sounds kind of strange PUSSYFOOT
but yes it is a fairly common verb it's a verb TO PUSSYFOOT now it
means to tread carefully often to take too much care, too much
attention or maybe when you don't want to commit to something and it's
usually followed by AROUND so the phrasal verb would be to PUSSYFOOT
AROUND for example "stop pussyfooting around and tell me exactly what
it is you want". "Politicians should stop pussyfooting around and
commit themselves to one side or the other."  "John stop pussyfooting
around and just cross the room and speak to the girl"

  Q is for QUALM usually used in the plural form QUALMS and it's a
noun and you use it when you want to talk about having doubts or
worries about something so for example "yes I have a few qualms about
moving to Dubai but it's a good job so I'll take it."  "I left her
twenty years ago without any qualms"

  R is for READILY really is an adverb which means without hesitation
or willingly. "I readily admit that swimming across the river is not
the preferred option but the bridge has collapsed and we have no
choice." "If you let me keep the house and the kids I will readily
agree to the divorce"

  S is for SPARK and it's a very useful word and it's both a verb and
a noun as a noun it literally refers to the first flame of a fire but
not yet a fire just a spark and we can use it to mean a small amount
of something a hint a touch of something for example "when he was
found guilty by the jury and sentenced to life imprisonment he stood
there without a spark of emotion." "After working all night finally
there was a spark of inspiration." As a verb it means to create or
emit something so for example "He insulted his colleague and this
sparked a fight"

  T is for THRICE now I said that all the words on this list were very
useful with one exception and this is possibly it because THRICE means
three times but it's rarely used these days yes we use ONCE we use
TWICE but why not THRICE it's logical and it's a beautiful word so I'm
encouraging you to start using it so it becomes much more common in
the English language as it once was so for example "it's incredible he
thrice won the lottery" Yes, you told me that once, you told me that
twice and he told me it thrice. That's enough!"

  U is four UTMOST another extremely useful word that's used to
emphasize how important or serious something is and it means to the
greatest extends to the highest degree for example "I will do my
utmost to ensure that you get the best deal." "This is a delicate
situation and you should handle it with the utmost care." "I will do
my utmost to stop brexit."

  V is for VIE. VIE is a verb and this means to compete for or to
strive for something and it's usually, though not always, followed by
the preposition FOR for example "Jim has been vying for a place in the
English football team." "LetThemTalk are vying to be the best English
language learning channel on YouTube"

  W is for WHIM. WHIM is a noun and it means a sudden desire or change
of mind especially one that is unusual or unexplained usually we say
ON A WHIM for example "you know one day I was in a boring meeting at
work when, on a whim, I walked out, got my passport and took the first
flight to Fiji and I've been here ever since and that was 20 years
ago." "We had only known each other for a week when we decided, on a
whim, to get married. Unfortunately within a month we had broken up
yes be careful about getting married on a whim."

  X is for XENOMANIA. Now we are on the Xs here and obviously there's
not a lot of choice with the X's there aren't many common words in
English beginning with X now there is XENOPHOBIA I was initially going
to choose, which means the suspicion or the dislike of foreigners or
outsiders but it's a very negative word so instead I've chosen as my X
word XENOMANIA which is the delight and the pleasure of meeting
strangers or visiting foreign countries and yes I am a XENOMANIAC what
about you? Let me know in the comments.

  Y is for YEARN now YEARN is a verb and a noun and it means an
intense desire or feeling for something for example "I live in Paris
but I yearn to be back in London my hometown" ok that's not
necessarily true it's just an example. "I yearn to retire and spend
the rest of my days eating donuts and learning the ukulele just as I
said earlier" Is that true well maybe yes maybe no.

  Z IS for ZIGZAG ZIGZAG and that is a line that has sharp right and
left turns "she was drunk and drove in a zigzag across town." "The
wallpaper had a zigzag pattern."

  So go out and start using those amazing advanced words and let me
know how you do also I'm sure when you start watching TV shows and
speaking with native speakers you'll start recognizing those words and
hearing those words a lot.  what was your favorite word in the list?
do you have a word you'd like to add to the list? do you prefer donuts
or broccoli answer these questions and more in the comments.
