((last-sort-comparer
  (bmkp-bookmark-last-access-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("css-hooligan" 0 12
                                   (bmkp-full-record #1#))
                                 (buffer-name . "css")
                                 (front-context-string)
                                 (rear-context-string . "03 May 20  2020 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #2=(24559 6733 10262 928000))
                                 (created . #2#)
                                 (position . 390)
                                 (filename . #3="/usr/local/git/0--key/0--key.github.io/assets/themes/hooligan/css/")
                                 (dired-directory . #3#)
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #4=(#("site-lisp" 0 9
                                   (bmkp-full-record #4#))
                                 (buffer-name . "site-lisp")
                                 (front-context-string . "bookmark-plus\n  ")
                                 (rear-context-string . "96 May 20  2020 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #5=(24559 6636 930336 776000))
                                 (created . #5#)
                                 (position . 231)
                                 (filename . #6="/usr/local/share/emacs/site-lisp/")
                                 (dired-directory . #6#)
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #7=(#("Working with Source Code" 0 24
                                   (bmkp-full-record #7#))
                                 (buffer-name . "*info*")
                                 (front-context-string . "include “center”")
                                 (rear-context-string . "pes, which also\n")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #8=(24557 58917 619544 410000))
                                 (created . #8#)
                                 (position . 588428)
                                 (filename . "/home/alioth/.emacs.d/elpa/org-20201216/org")
                                 (info-node . #9="Working with Source Code")
                                 (handler . Info-bookmark-jump)
                                 (defaults "(org) Working with Source Code" "org" #9#))
                             #10=(#("MK61" 0 4
                                    (bmkp-full-record #10#))
                                  (filename . "/usr/local/git/0--key/org-pub/2020-12-29-dissecting-python.org")
                                  (buffer-name . "2020-12-29-dissecting-python.org")
                                  (front-context-string . "\n\n  Unconsciousl")
                                  (rear-context-string . "-bee\" named one.")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #11=(24557 47470 205229 995000))
                                  (created . #11#)
                                  (position . 2905))
                             #12=(#("ColorThemes" 0 11
                                    (bmkp-full-record #12#))
                                  (filename . "~/.emacs")
                                  (buffer-name . ".emacs")
                                  (front-context-string . "olorthemes\"))\n\n(")
                                  (rear-context-string . "-lisp/\nreplace-c")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 4)
                                  (time 24574 47933 521669 986000)
                                  (created 24557 45053 2989 410000)
                                  (position . 878))
                             #13=(#("ImgHTML" 0 7
                                    (bmkp-full-record #13#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "\n13.9.9 Images i")
                                  (rear-context-string . "Up: HTML Export\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #14=(24557 44715 945793 17000))
                                  (created . #14#)
                                  (position . 463802)
                                  (filename . "/home/alioth/.emacs.d/elpa/org-20201216/org")
                                  (info-node . #15="Images in HTML export")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(org) Images in HTML export" "org" #15#))
                             #16=(#("recentPub" 0 9
                                    (bmkp-full-record #16#))
                                  (buffer-name . "scratch.init")
                                  (visits . 2)
                                  (time 24574 48003 948428 422000)
                                  (created 24556 27687 104264 101000)
                                  (position . 41821)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/pub.desktop")
                                  (handler . bmkp-jump-desktop))
                             #17=(#("Pinker" 0 6
                                    (bmkp-full-record #17#))
                                  (filename . "~/Desktop/Books/0670025852SenseStyle.epub")
                                  (buffer-name . "0670025852SenseStyle.epub")
                                  (front-context-string . "\nI love style ma")
                                  (rear-context-string . "ds\n\n\f\n\nPrologue\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24554 57940 830564 588000)
                                  (created 24540 35664 643500 270000)
                                  (position . 865))
                             #18=(#("Quotes" 0 6
                                    (bmkp-full-record #18#))
                                  (buffer-name . "*eww*")
                                  (buffer-name . "*eww*")
                                  (front-context-string . "      *    \"Prog")
                                  (rear-context-string . "    \n          \n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24540 26773 853535 333000)
                                  (created 24539 8538 628600 405000)
                                  (position . 975)
                                  (location . "http://www.paulgraham.com/quo.html")
                                  (handler . bmkp-jump-eww))
                             #19=(#("pub" 0 3
                                    (bmkp-full-record #19#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "2020-12-15-python-inside-out-initial.org")
                                  (visits . 1)
                                  (time 24554 61353 164662 326000)
                                  (created 24540 35486 281156 790000)
                                  (position . 2032)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/pub.desktop")
                                  (handler . bmkp-jump-desktop))
                             #20=(#("captureSet" 0 10
                                    (bmkp-full-record #20#))
                                  (filename . "/usr/local/git/0--key/lib/Emacs/init_generic.el")
                                  (buffer-name . "init_generic.el")
                                  (front-context-string . "\n  (\"s\" \"SRE\" en")
                                  (rear-context-string . "rill:\\n%i\")\n  ;;")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #21=(24539 1887 704387 585000))
                                  (created . #21#)
                                  (position . 3311))
                             #22=(#("emacs" 0 5
                                    (bmkp-full-record #22#))
                                  (buffer-name . ".emacs")
                                  (visits . 2)
                                  (time 24536 30051 175615 16000)
                                  (created 24444 51673 997724 273000)
                                  (position . 1853)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/emacustom.desktop")
                                  (handler . bmkp-jump-desktop))
                             #23=(#("reading" 0 7
                                    (bmkp-full-record #23#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "scratch.init")
                                  (visits . 0)
                                  (time . #24=(24554 61337 495753 824000))
                                  (created . #24#)
                                  (position . 41719)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/reading.desktop")
                                  (handler . bmkp-jump-desktop))
                             #25=(#("Auster" 0 6
                                    (bmkp-full-record #25#))
                                  (filename . "~/Desktop/Books/Auster, Paul - Hand to Mouth (Picador, 2012).epub")
                                  (buffer-name . "Auster, Paul - Hand to Mouth (Picador, 2012).epub")
                                  (front-context-string . "\f\nHAND TO MOUTH.")
                                  (rear-context-string . "House in 1983.\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #26=(24444 50272 298718 640000))
                                  (created . #26#)
                                  (position . 227944))
                             #27=(#("2010" 0 4
                                    (bmkp-full-record #27#))
                                  (filename . "/usr/local/git/0--key/lib/org/vocabulary/202010.org")
                                  (buffer-name . "202010.org")
                                  (front-context-string . "* faintest :Ange")
                                  (rear-context-string . "ng in my class.\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24521 65222 227379 285000)
                                  (created 24444 12075 407125 221000)
                                  (position . 4004))
                             #28=(#("vocabulary" 0 10
                                    (bmkp-full-record #28#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "vocabulary")
                                  (visits . 4)
                                  (time 24444 51722 904326 693000)
                                  (created 24444 50555 413966 390000)
                                  (position . 1629)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/vocabulary.desktop")
                                  (handler . bmkp-jump-desktop))
                             #29=(#("Angela" 0 6
                                    (bmkp-full-record #29#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/Angela Duckworth - Grit.epub")
                                  (buffer-name . "Angela Duckworth - Grit.epub")
                                  (front-context-string . "EFFORT COUNTS TW")
                                  (rear-context-string . "\n\f\n\n Chapter 3\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #30=(24444 15035 689844 631000))
                                  (created . #30#)
                                  (position . 68987))
                             #31=(#("Greene" 0 6
                                    (bmkp-full-record #31#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/The Laws of Human Nature by Robert Greene/The Laws of Human Nature by Robert Greene.epub")
                                  (buffer-name . "The Laws of Human Nature by Robert Greene.epub")
                                  (front-context-string . ": The reason you")
                                  (rear-context-string . "Analytic empathy")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #32=(24444 50097 368404 75000))
                                  (created . #32#)
                                  (position . 134159))
                             #33=(#("Registers" 0 9
                                    (bmkp-full-record #33#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "\n* Menu:\n\n* Posi")
                                  (rear-context-string . "n this chapter.\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #34=(24411 7703 353462 755000))
                                  (created . #34#)
                                  (position . 242773)
                                  (filename . "/snap/emacs/current/usr/share/info/emacs")
                                  (info-node . #35="Registers")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(emacs) Registers" "emacs" #35#))
                             #36=(#("Vanessa" 0 7
                                    (bmkp-full-record #36#))
                                  (end-position . 45088)
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/Captivate_ The Science of Succeeding with People by Vanessa Van Edwards ePUB eBOOK-ZAK/Captivate The Science of Succeeding with People by Vanessa Van Edwards.epub")
                                  (buffer-name . "Captivate The Science of Succeeding with People by Vanessa Van Edwards.epub")
                                  (front-context-string . "\nHow to make a k")
                                  (rear-context-string . "PTER 2\n\nCAPTURE\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 6)
                                  (time 24520 47317 646861 727000)
                                  (created 24427 21094 488100 110000)
                                  (position . 45088))
                             #37=(#("Macros" 0 6
                                    (bmkp-full-record #37#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "\n17.1 Basic Use\n")
                                  (rear-context-string . "Keyboard Macros\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24556 37369 100238 346000)
                                  (created 24406 18267 867320 557000)
                                  (position . 435269)
                                  (filename . "/snap/emacs/current/usr/share/info/emacs")
                                  (info-node . #38="Basic Keyboard Macro")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(emacs) Basic Keyboard Macro" "emacs" #38#))
                             #39=(#("scratch.init" 0 12
                                    (bmkp-full-record #39#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/.emacs.d/scratch.init")
                                  (buffer-name . "scratch.init")
                                  (front-context-string)
                                  (rear-context-string . "rse tree option.")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24436 20406 602288 897000)
                                  (created 24436 20391 486835 680000)
                                  (position . 40271))
                             #40=(#("Big Potential by Shawn Achor.epub" 0 33
                                    (bmkp-full-record #40#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Downloads/Big Potential by Shawn Achor EPUB/Big Potential by Shawn Achor.epub")
                                  (buffer-name . "Big Potential by Shawn Achor.epub")
                                  (front-context-string . "CHAPTER 2\n\nLIFTI")
                                  (rear-context-string . "with Oprah.\n\n\f\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24378 22622 420591 98000)
                                  (created 24373 5837 601075 574000)
                                  (position . 20432))
                             #41=(#("org-drill.el – flashcards and spaced repetition for org-mode" 0 60
                                    (bmkp-full-record #41#))
                                  (buffer-name . "*eww*")
                                  (buffer-name . "*eww*")
                                  (front-context-string . "\nDuring review, ")
                                  (rear-context-string . "a is [Tallinn].\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24406 18306 194586 2000)
                                  (created 24353 36168 174051 541000)
                                  (position . 5423)
                                  (location . "https://orgmode.org/worg/org-contrib/org-drill.html")
                                  (handler . bmkp-jump-eww))
                             #42=(#("current" 0 7
                                    (bmkp-full-record #42#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "*Bookmark List*")
                                  (visits . 6)
                                  (time 24520 44246 853715 738000)
                                  (created 24353 36203 830806 470000)
                                  (position . 1)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/Desktop/current.desktop")
                                  (handler . bmkp-jump-desktop))
                             #43=(#("Make_It_Stick_-_Peter_C_Brown.epub" 0 34
                                    (bmkp-full-record #43#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/Make_It_Stick_-_Peter_C_Brown.epub")
                                  (buffer-name . "Make_It_Stick_-_Peter_C_Brown.epub")
                                  (front-context-string . "\nAll new learnin")
                                  (rear-context-string . "as of weakness.\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24338 59723 573018 109000)
                                  (created 24337 60658 527220 0)
                                  (position . 12129))
                             #44=(#("Derek Sivers - Anything You Want.epub" 0 37
                                    (bmkp-full-record #44#))
                                  (filename . "~/Desktop/Books/Anything You Want_ 40 Lessons for a New Kind of Entrepreneur by Derek Sivers ePUB eBOOK-ZAK/Derek Sivers - Anything You Want.epub")
                                  (buffer-name . "Derek Sivers - Anything You Want.epub")
                                  (front-context-string . "\n \n\nTen years of")
                                  (rear-context-string . "ut the Cover\n\n\f\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #45=(24308 27740 486659 763000))
                                  (created . #45#)
                                  (position . 937))
                             #46=(#("buildout.cfg" 0 12
                                    (bmkp-full-record #46#))
                                  (filename . "/usr/local/git/spynner/buildout.cfg")
                                  (buffer-name . "buildout.cfg")
                                  (front-context-string . "lxml = 2.3.6\nBea")
                                  (rear-context-string . "]\nautopy = 0.51\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #47=(24308 27700 964042 162000))
                                  (created . #47#)
                                  (position . 694))
                             #48=(#("spynner" 0 7
                                    (bmkp-full-record #48#))
                                  (buffer-name . "spynner")
                                  (front-context-string)
                                  (rear-context-string . "71 Jun  9 11:04 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #49=(24308 27681 472848 334000))
                                  (created . #49#)
                                  (position . 1259)
                                  (filename . #50="/usr/local/git/spynner/")
                                  (dired-directory . #50#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #51=(#("202006.org" 0 10
                                    (bmkp-full-record #51#))
                                  (annotation)
                                  (tags)
                                  (filename . "/usr/local/git/0--key/lib/org/vocabulary/202006.org")
                                  (buffer-name . "202006.org")
                                  (front-context-string . ":\n[2020-06-28 Su")
                                  (rear-context-string . " renounced :misc")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #52=(24312 23398 58022 130000))
                                  (created . #52#)
                                  (position . 187978))
                             #53=(#("LocalLib" 0 8
                                    (bmkp-full-record #53#))
                                  (buffer-name . "Books")
                                  (front-context-string . "03_RAlgebra.pdf\n")
                                  (rear-context-string . "76 Oct  9  2017 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #54=(24305 64288 496019 946000))
                                  (created . #54#)
                                  (position . 244)
                                  (filename . "/home/alioth/Desktop/Books/")
                                  (dired-directory . "~/Desktop/Books/")
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #55=(#("KeyChords" 0 9
                                    (bmkp-full-record #55#))
                                  (end-position . 3264)
                                  (filename . "~/.emacs")
                                  (buffer-name . ".emacs")
                                  (front-context-string . "\n(key-chord-defi")
                                  (rear-context-string . "fledged keyboard")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 3)
                                  (time 24559 14306 305935 541000)
                                  (created 24287 16592 539048 943000)
                                  (position . 3264))
                             #56=(#("Emacs customization" 0 19
                                    (bmkp-full-record #56#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . ".emacs")
                                  (visits . 4)
                                  (time 24336 24364 258344 806000)
                                  (created 24264 32538 905806 36000)
                                  (position . 4090)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/emacs.desktop")
                                  (handler . bmkp-jump-desktop))
                             #57=(#("Emacs tuning" 0 12
                                    (bmkp-full-record #57#))
                                  (buffer-name . ".emacs")
                                  (visits . 1)
                                  (time 24260 39114 357016 809000)
                                  (created 24260 35960 644257 274000)
                                  (position . 408)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/emacs.desktop")
                                  (handler . bmkp-jump-desktop))
                             #58=(#("EmacsWiki: Bookmark Plus" 0 24
                                    (bmkp-full-record #58#))
                                  (buffer-name . "*eww*")
                                  (buffer-name . "*eww*")
                                  (front-context-string . "          (requi")
                                  (rear-context-string . "markplus-dir 0)\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24260 35473 661849 709000)
                                  (created 24260 35429 321441 745000)
                                  (position . 6553)
                                  (location . "https://www.emacswiki.org/emacs/BookmarkPlus")
                                  (handler . bmkp-jump-eww))
                             #59=(#("Emacs main config file" 0 22
                                    (bmkp-full-record #59#))
                                  (end-position . 1411)
                                  (filename . "~/.emacs")
                                  (buffer-name . ".emacs")
                                  (front-context-string . "(require 'bookma")
                                  (rear-context-string . "ookmark-plus/\")\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 3)
                                  (time 24577 23156 962571 73000)
                                  (created 24260 32930 950318 337000)
                                  (position . 1411)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #60="")
 (last-bmenu-title . #60#)
 (last-bmenu-bookmark)
 (last-specific-buffer . #60#)
 (last-specific-file . #60#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "/home/alioth/.emacs.d/bookmarks")
 (last-previous-bookmark-file . "/home/alioth/.emacs.d/bookmarks"))
