((last-sort-comparer
  (bmkp-bookmark-last-access-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("pasture" 0 7
                                   (bmkp-full-record #1#))
                                 (filename . "/usr/local/git/0--key/lib/org/vocabulary/202103.org")
                                 (buffer-name . "202103.org")
                                 (front-context-string . "* pasture :misc:")
                                 (rear-context-string . " of their wits.\n")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 1)
                                 (time 24673 31323 776880 413000)
                                 (created 24672 35516 455838 642000)
                                 (position . 23565))
                             #2=(#("March11" 0 7
                                   (bmkp-full-record #2#))
                                 (buffer-name . "2020-12-29-dissecting-python.org")
                                 (visits . 2)
                                 (time 24652 34335 505791 159000)
                                 (created 24649 52336 382019 327000)
                                 (position . 49722)
                                 (filename . "   - no file -")
                                 (desktop-file . "~/.emacs.d/march.desktop")
                                 (handler . bmkp-jump-desktop))
                             #3=(#("BagofWords" 0 10
                                   (bmkp-full-record #3#))
                                 (end-position . 6315)
                                 (filename . "/usr/local/git/0--key/org-pub/2020-12-29-dissecting-python.org")
                                 (buffer-name . "2020-12-29-dissecting-python.org")
                                 (front-context-string . "\n\n**** Competito")
                                 (rear-context-string . "e biases\n\n***** ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 1)
                                 (time 24648 45097 660522 358000)
                                 (created 24648 31533 332898 360000)
                                 (position . 6315))
                             #4=(#("MachineCode" 0 11
                                   (bmkp-full-record #4#))
                                 (filename . "/usr/local/git/0--key/org-pub/2020-12-29-dissecting-python.org")
                                 (buffer-name . "2020-12-29-dissecting-python.org")
                                 (front-context-string . "achine Code vs S")
                                 (rear-context-string . "ervations:\n\n** M")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #5=(24646 16891 154767 495000))
                                 (created . #5#)
                                 (position . 23866))
                             #6=(#("Feb1" 0 4
                                   (bmkp-full-record #6#))
                                 (buffer-name . "2020-12-29-dissecting-python.org")
                                 (visits . 1)
                                 (time 24634 7743 289033 107000)
                                 (created 24632 52980 858645 787000)
                                 (position . 23866)
                                 (filename . "   - no file -")
                                 (desktop-file . "~/.emacs.d/feb1.desktop")
                                 (handler . bmkp-jump-desktop))
                             #7=(#("animal-farm-a-fairy-story.epub" 0 30
                                   (bmkp-full-record #7#))
                                 (annotation)
                                 (tags)
                                 (filename . "~/Downloads/animal-farm-a-fairy-story.epub")
                                 (buffer-name . "animal-farm-a-fairy-story.epub")
                                 (front-context-string . "THE SEVEN COMMAN")
                                 (rear-context-string . "y ran thus:\n\n \n\n")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 1)
                                 (time 24672 36313 69263 445000)
                                 (created 24672 36253 478013 100000)
                                 (position . 27806))
                             #8=(#("February" 0 8
                                   (bmkp-full-record #8#))
                                 (buffer-name . "2020-12-29-dissecting-python.org")
                                 (visits . 1)
                                 (time 24631 6053 879368 758000)
                                 (created 24630 17959 171059 677000)
                                 (position . 25426)
                                 (filename . "   - no file -")
                                 (desktop-file . "~/.emacs.d/feb.desktop")
                                 (handler . bmkp-jump-desktop))
                             #9=(#("bag of words" 0 12
                                   (bmkp-full-record #9#))
                                 (filename . "/usr/local/git/0--key/org-pub/2020-12-29-dissecting-python.org")
                                 (buffer-name . "2020-12-29-dissecting-python.org")
                                 (front-context-string . "\n\n\n**** Competit")
                                 (rear-context-string . "concepts\n\n***** ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #10=(24611 41206 350855 371000))
                                 (created . #10#)
                                 (position . 5941))
                             #11=(#("The Passionate Programmer (2009) - (Malestrom).epub" 0 51
                                    (bmkp-full-record #11#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Downloads/The Passionate Programmer (2009) - (Malestrom).epub")
                                  (buffer-name . "The Passionate Programmer (2009) - (Malestrom).epub")
                                  (front-context-string . "If you want to r")
                                  (rear-context-string . "4\n\nBe a Mentor\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24672 47037 392100 936000)
                                  (created 24654 15410 15952 888000)
                                  (position . 135292))
                             #12=(#("2020-12-29-dissecting-python.org" 0 32
                                    (bmkp-full-record #12#))
                                  (buffer-name . "2020-12-29-dissecting-python.org")
                                  (visits . 2)
                                  (time 24621 6755 285873 663000)
                                  (created 24595 55981 668980 378000)
                                  (position . 7055)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/current.desktop")
                                  (handler . bmkp-jump-desktop))
                             #13=(#("Dissection" 0 10
                                    (bmkp-full-record #13#))
                                  (buffer-name . "2020-12-29-dissecting-python.org")
                                  (visits . 2)
                                  (time 24583 62009 390400 507000)
                                  (created 24582 58112 482134 823000)
                                  (position . 15112)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/dissect_init.desktop")
                                  (handler . bmkp-jump-desktop))
                             #14=(#("org.css" 0 7
                                    (bmkp-full-record #14#))
                                  (filename . "/usr/local/git/0--key/0--key.github.io/assets/themes/css/org.css")
                                  (buffer-name . "org.css")
                                  (front-context-string . ";}  \npre span.or")
                                  (rear-context-string . "round-color:#000")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #15=(24582 41040 636280 619000))
                                  (created . #15#)
                                  (position . 64))
                             #16=(#("Ordering" 0 8
                                    (bmkp-full-record #16#))
                                  (filename . "/usr/local/git/0--key/org-pub/2020-12-29-dissecting-python.org")
                                  (buffer-name . "2020-12-29-dissecting-python.org")
                                  (front-context-string . "g as an ordered ")
                                  (rear-context-string . "  - \n\n** Indexin")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #17=(24580 8233 67898 411000))
                                  (created . #17#)
                                  (position . 4860))
                             #18=(#("css-hooligan" 0 12
                                    (bmkp-full-record #18#))
                                  (buffer-name . "css")
                                  (front-context-string)
                                  (rear-context-string . "03 May 20  2020 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #19=(24559 6733 10262 928000))
                                  (created . #19#)
                                  (position . 390)
                                  (filename . #20="/usr/local/git/0--key/0--key.github.io/assets/themes/hooligan/css/")
                                  (dired-directory . #20#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #21=(#("site-lisp" 0 9
                                    (bmkp-full-record #21#))
                                  (buffer-name . "site-lisp")
                                  (front-context-string . "bookmark-plus\n  ")
                                  (rear-context-string . "96 May 20  2020 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #22=(24559 6636 930336 776000))
                                  (created . #22#)
                                  (position . 231)
                                  (filename . #23="/usr/local/share/emacs/site-lisp/")
                                  (dired-directory . #23#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #24=(#("Working with Source Code" 0 24
                                    (bmkp-full-record #24#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "include “center”")
                                  (rear-context-string . "pes, which also\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #25=(24557 58917 619544 410000))
                                  (created . #25#)
                                  (position . 588428)
                                  (filename . "/home/alioth/.emacs.d/elpa/org-20201216/org")
                                  (info-node . #26="Working with Source Code")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(org) Working with Source Code" "org" #26#))
                             #27=(#("MK61" 0 4
                                    (bmkp-full-record #27#))
                                  (filename . "/usr/local/git/0--key/org-pub/2020-12-29-dissecting-python.org")
                                  (buffer-name . "2020-12-29-dissecting-python.org")
                                  (front-context-string . "\n\n  Unconsciousl")
                                  (rear-context-string . "-bee\" named one.")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #28=(24557 47470 205229 995000))
                                  (created . #28#)
                                  (position . 2905))
                             #29=(#("ColorThemes" 0 11
                                    (bmkp-full-record #29#))
                                  (filename . "~/.emacs")
                                  (buffer-name . ".emacs")
                                  (front-context-string . "olorthemes\"))\n\n(")
                                  (rear-context-string . "-lisp/\nreplace-c")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 12)
                                  (time 24652 51101 201401 121000)
                                  (created 24557 45053 2989 410000)
                                  (position . 878))
                             #30=(#("ImgHTML" 0 7
                                    (bmkp-full-record #30#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "\n13.9.9 Images i")
                                  (rear-context-string . "Up: HTML Export\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #31=(24557 44715 945793 17000))
                                  (created . #31#)
                                  (position . 463802)
                                  (filename . "/home/alioth/.emacs.d/elpa/org-20201216/org")
                                  (info-node . #32="Images in HTML export")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(org) Images in HTML export" "org" #32#))
                             #33=(#("recentPub" 0 9
                                    (bmkp-full-record #33#))
                                  (buffer-name . "scratch.init")
                                  (visits . 2)
                                  (time 24574 48003 948428 422000)
                                  (created 24556 27687 104264 101000)
                                  (position . 41821)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/pub.desktop")
                                  (handler . bmkp-jump-desktop))
                             #34=(#("Pinker" 0 6
                                    (bmkp-full-record #34#))
                                  (filename . "~/Desktop/Books/0670025852SenseStyle.epub")
                                  (buffer-name . "0670025852SenseStyle.epub")
                                  (front-context-string . "\nI love style ma")
                                  (rear-context-string . "ds\n\n\f\n\nPrologue\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24554 57940 830564 588000)
                                  (created 24540 35664 643500 270000)
                                  (position . 865))
                             #35=(#("Quotes" 0 6
                                    (bmkp-full-record #35#))
                                  (buffer-name . "*eww*")
                                  (buffer-name . "*eww*")
                                  (front-context-string . "      *    \"Prog")
                                  (rear-context-string . "    \n          \n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24540 26773 853535 333000)
                                  (created 24539 8538 628600 405000)
                                  (position . 975)
                                  (location . "http://www.paulgraham.com/quo.html")
                                  (handler . bmkp-jump-eww))
                             #36=(#("pub" 0 3
                                    (bmkp-full-record #36#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "2020-12-15-python-inside-out-initial.org")
                                  (visits . 1)
                                  (time 24554 61353 164662 326000)
                                  (created 24540 35486 281156 790000)
                                  (position . 2032)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/pub.desktop")
                                  (handler . bmkp-jump-desktop))
                             #37=(#("captureSet" 0 10
                                    (bmkp-full-record #37#))
                                  (filename . "/usr/local/git/0--key/lib/Emacs/init_generic.el")
                                  (buffer-name . "init_generic.el")
                                  (front-context-string . "\n  (\"s\" \"SRE\" en")
                                  (rear-context-string . "rill:\\n%i\")\n  ;;")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #38=(24539 1887 704387 585000))
                                  (created . #38#)
                                  (position . 3311))
                             #39=(#("emacs" 0 5
                                    (bmkp-full-record #39#))
                                  (buffer-name . ".emacs")
                                  (visits . 2)
                                  (time 24536 30051 175615 16000)
                                  (created 24444 51673 997724 273000)
                                  (position . 1853)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/emacustom.desktop")
                                  (handler . bmkp-jump-desktop))
                             #40=(#("reading" 0 7
                                    (bmkp-full-record #40#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "scratch.init")
                                  (visits . 0)
                                  (time . #41=(24554 61337 495753 824000))
                                  (created . #41#)
                                  (position . 41719)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/reading.desktop")
                                  (handler . bmkp-jump-desktop))
                             #42=(#("Auster" 0 6
                                    (bmkp-full-record #42#))
                                  (filename . "~/Desktop/Books/Auster, Paul - Hand to Mouth (Picador, 2012).epub")
                                  (buffer-name . "Auster, Paul - Hand to Mouth (Picador, 2012).epub")
                                  (front-context-string . "\f\nHAND TO MOUTH.")
                                  (rear-context-string . "House in 1983.\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24577 38119 693412 417000)
                                  (created 24444 50272 298718 640000)
                                  (position . 227944))
                             #43=(#("2010" 0 4
                                    (bmkp-full-record #43#))
                                  (end-position . 4008)
                                  (filename . "/usr/local/git/0--key/lib/org/vocabulary/202010.org")
                                  (buffer-name . "202010.org")
                                  (front-context-string . "* faintest :Ange")
                                  (rear-context-string . "ng in my class.\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 3)
                                  (time 24604 64589 734268 620000)
                                  (created 24444 12075 407125 221000)
                                  (position . 4008))
                             #44=(#("vocabulary" 0 10
                                    (bmkp-full-record #44#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "vocabulary")
                                  (visits . 4)
                                  (time 24444 51722 904326 693000)
                                  (created 24444 50555 413966 390000)
                                  (position . 1629)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/vocabulary.desktop")
                                  (handler . bmkp-jump-desktop))
                             #45=(#("Angela" 0 6
                                    (bmkp-full-record #45#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/Angela Duckworth - Grit.epub")
                                  (buffer-name . "Angela Duckworth - Grit.epub")
                                  (front-context-string . "EFFORT COUNTS TW")
                                  (rear-context-string . "\n\f\n\n Chapter 3\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #46=(24444 15035 689844 631000))
                                  (created . #46#)
                                  (position . 68987))
                             #47=(#("Greene" 0 6
                                    (bmkp-full-record #47#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/The Laws of Human Nature by Robert Greene/The Laws of Human Nature by Robert Greene.epub")
                                  (buffer-name . "The Laws of Human Nature by Robert Greene.epub")
                                  (front-context-string . ": The reason you")
                                  (rear-context-string . "Analytic empathy")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #48=(24444 50097 368404 75000))
                                  (created . #48#)
                                  (position . 134159))
                             #49=(#("Registers" 0 9
                                    (bmkp-full-record #49#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "\n* Menu:\n\n* Posi")
                                  (rear-context-string . "n this chapter.\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #50=(24411 7703 353462 755000))
                                  (created . #50#)
                                  (position . 242773)
                                  (filename . "/snap/emacs/current/usr/share/info/emacs")
                                  (info-node . #51="Registers")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(emacs) Registers" "emacs" #51#))
                             #52=(#("Vanessa" 0 7
                                    (bmkp-full-record #52#))
                                  (end-position . 45088)
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/Captivate_ The Science of Succeeding with People by Vanessa Van Edwards ePUB eBOOK-ZAK/Captivate The Science of Succeeding with People by Vanessa Van Edwards.epub")
                                  (buffer-name . "Captivate The Science of Succeeding with People by Vanessa Van Edwards.epub")
                                  (front-context-string . "\nHow to make a k")
                                  (rear-context-string . "PTER 2\n\nCAPTURE\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 6)
                                  (time 24520 47317 646861 727000)
                                  (created 24427 21094 488100 110000)
                                  (position . 45088))
                             #53=(#("Macros" 0 6
                                    (bmkp-full-record #53#))
                                  (buffer-name . "*info*")
                                  (front-context-string . "\n17.1 Basic Use\n")
                                  (rear-context-string . "Keyboard Macros\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24556 37369 100238 346000)
                                  (created 24406 18267 867320 557000)
                                  (position . 435269)
                                  (filename . "/snap/emacs/current/usr/share/info/emacs")
                                  (info-node . #54="Basic Keyboard Macro")
                                  (handler . Info-bookmark-jump)
                                  (defaults "(emacs) Basic Keyboard Macro" "emacs" #54#))
                             #55=(#("scratch.init" 0 12
                                    (bmkp-full-record #55#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/.emacs.d/scratch.init")
                                  (buffer-name . "scratch.init")
                                  (front-context-string)
                                  (rear-context-string . "rse tree option.")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24436 20406 602288 897000)
                                  (created 24436 20391 486835 680000)
                                  (position . 40271))
                             #56=(#("Big Potential by Shawn Achor.epub" 0 33
                                    (bmkp-full-record #56#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Downloads/Big Potential by Shawn Achor EPUB/Big Potential by Shawn Achor.epub")
                                  (buffer-name . "Big Potential by Shawn Achor.epub")
                                  (front-context-string . "CHAPTER 2\n\nLIFTI")
                                  (rear-context-string . "with Oprah.\n\n\f\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24378 22622 420591 98000)
                                  (created 24373 5837 601075 574000)
                                  (position . 20432))
                             #57=(#("org-drill.el – flashcards and spaced repetition for org-mode" 0 60
                                    (bmkp-full-record #57#))
                                  (buffer-name . "*eww*")
                                  (buffer-name . "*eww*")
                                  (front-context-string . "\nDuring review, ")
                                  (rear-context-string . "a is [Tallinn].\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24406 18306 194586 2000)
                                  (created 24353 36168 174051 541000)
                                  (position . 5423)
                                  (location . "https://orgmode.org/worg/org-contrib/org-drill.html")
                                  (handler . bmkp-jump-eww))
                             #58=(#("current" 0 7
                                    (bmkp-full-record #58#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "*Bookmark List*")
                                  (visits . 6)
                                  (time 24520 44246 853715 738000)
                                  (created 24353 36203 830806 470000)
                                  (position . 1)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/Desktop/current.desktop")
                                  (handler . bmkp-jump-desktop))
                             #59=(#("Make_It_Stick_-_Peter_C_Brown.epub" 0 34
                                    (bmkp-full-record #59#))
                                  (annotation)
                                  (tags)
                                  (filename . "~/Desktop/Books/Make_It_Stick_-_Peter_C_Brown.epub")
                                  (buffer-name . "Make_It_Stick_-_Peter_C_Brown.epub")
                                  (front-context-string . "\nAll new learnin")
                                  (rear-context-string . "as of weakness.\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24338 59723 573018 109000)
                                  (created 24337 60658 527220 0)
                                  (position . 12129))
                             #60=(#("Derek Sivers - Anything You Want.epub" 0 37
                                    (bmkp-full-record #60#))
                                  (filename . "~/Desktop/Books/Anything You Want_ 40 Lessons for a New Kind of Entrepreneur by Derek Sivers ePUB eBOOK-ZAK/Derek Sivers - Anything You Want.epub")
                                  (buffer-name . "Derek Sivers - Anything You Want.epub")
                                  (front-context-string . "\n \n\nTen years of")
                                  (rear-context-string . "ut the Cover\n\n\f\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #61=(24308 27740 486659 763000))
                                  (created . #61#)
                                  (position . 937))
                             #62=(#("buildout.cfg" 0 12
                                    (bmkp-full-record #62#))
                                  (filename . "/usr/local/git/spynner/buildout.cfg")
                                  (buffer-name . "buildout.cfg")
                                  (front-context-string . "lxml = 2.3.6\nBea")
                                  (rear-context-string . "]\nautopy = 0.51\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #63=(24308 27700 964042 162000))
                                  (created . #63#)
                                  (position . 694))
                             #64=(#("spynner" 0 7
                                    (bmkp-full-record #64#))
                                  (buffer-name . "spynner")
                                  (front-context-string)
                                  (rear-context-string . "71 Jun  9 11:04 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #65=(24308 27681 472848 334000))
                                  (created . #65#)
                                  (position . 1259)
                                  (filename . #66="/usr/local/git/spynner/")
                                  (dired-directory . #66#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #67=(#("202006.org" 0 10
                                    (bmkp-full-record #67#))
                                  (annotation)
                                  (tags)
                                  (filename . "/usr/local/git/0--key/lib/org/vocabulary/202006.org")
                                  (buffer-name . "202006.org")
                                  (front-context-string . ":\n[2020-06-28 Su")
                                  (rear-context-string . " renounced :misc")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #68=(24312 23398 58022 130000))
                                  (created . #68#)
                                  (position . 187978))
                             #69=(#("LocalLib" 0 8
                                    (bmkp-full-record #69#))
                                  (buffer-name . "Books")
                                  (front-context-string . "03_RAlgebra.pdf\n")
                                  (rear-context-string . "76 Oct  9  2017 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #70=(24305 64288 496019 946000))
                                  (created . #70#)
                                  (position . 244)
                                  (filename . "/home/alioth/Desktop/Books/")
                                  (dired-directory . "~/Desktop/Books/")
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #71=(#("KeyChords" 0 9
                                    (bmkp-full-record #71#))
                                  (end-position . 3512)
                                  (filename . "~/.emacs")
                                  (buffer-name . ".emacs")
                                  (front-context-string . "\n(key-chord-defi")
                                  (rear-context-string . "fledged keyboard")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 4)
                                  (time 24630 7733 240812 23000)
                                  (created 24287 16592 539048 943000)
                                  (position . 3512))
                             #72=(#("Emacs customization" 0 19
                                    (bmkp-full-record #72#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . ".emacs")
                                  (visits . 4)
                                  (time 24336 24364 258344 806000)
                                  (created 24264 32538 905806 36000)
                                  (position . 4090)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/emacs.desktop")
                                  (handler . bmkp-jump-desktop))
                             #73=(#("Emacs tuning" 0 12
                                    (bmkp-full-record #73#))
                                  (buffer-name . ".emacs")
                                  (visits . 1)
                                  (time 24260 39114 357016 809000)
                                  (created 24260 35960 644257 274000)
                                  (position . 408)
                                  (filename . "   - no file -")
                                  (desktop-file . "~/.emacs.d/emacs.desktop")
                                  (handler . bmkp-jump-desktop))
                             #74=(#("EmacsWiki: Bookmark Plus" 0 24
                                    (bmkp-full-record #74#))
                                  (buffer-name . "*eww*")
                                  (buffer-name . "*eww*")
                                  (front-context-string . "          (requi")
                                  (rear-context-string . "markplus-dir 0)\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24260 35473 661849 709000)
                                  (created 24260 35429 321441 745000)
                                  (position . 6553)
                                  (location . "https://www.emacswiki.org/emacs/BookmarkPlus")
                                  (handler . bmkp-jump-eww))
                             #75=(#("Emacs main config file" 0 22
                                    (bmkp-full-record #75#))
                                  (end-position . 1411)
                                  (filename . "~/.emacs")
                                  (buffer-name . ".emacs")
                                  (front-context-string . "(require 'bookma")
                                  (rear-context-string . "ookmark-plus/\")\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 3)
                                  (time 24577 23156 962571 73000)
                                  (created 24260 32930 950318 337000)
                                  (position . 1411)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #76="")
 (last-bmenu-title . #76#)
 (last-bmenu-bookmark)
 (last-specific-buffer . #76#)
 (last-specific-file . #76#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "/home/alioth/.emacs.d/bookmarks")
 (last-previous-bookmark-file . "/home/alioth/.emacs.d/bookmarks"))
