#+AUTHOR:    Anton S. Kosinov
#+TITLE:     Programming Theory Dissection
#+SUBTITLE:  Life in a plain text
#+EMAIL:     a.s.kosinov@gmail.com
#+LANGUAGE: en
#+STARTUP: showall
* Basic Theories
** Binary Theory
*** >>>                                                               :drill:
    SCHEDULED: <2018-02-21 Wed>
    :PROPERTIES:
    :DRILL_CARD_TYPE: hide2cloze
    :ID:       006ab9b4-2812-43b8-bafe-83f3ef305407
    :DRILL_LAST_INTERVAL: 3.86
    :DRILL_REPEATS_SINCE_FAIL: 2
    :DRILL_TOTAL_REPEATS: 1
    :DRILL_FAILURE_COUNT: 0
    :DRILL_AVERAGE_QUALITY: 3.0
    :DRILL_EASE: 2.36
    :DRILL_LAST_QUALITY: 3
    :DRILL_LAST_REVIEWED: [2018-02-17 Sat 11:07]
    :END:
    Binary Theory, also known as [boolean algebra], or [logic], was
    designed as an [aid] to reasoning, and we will use it to [reason]
    about computation.
*** >>>                                                               :drill:
    SCHEDULED: <2018-02-21 Wed>
    :PROPERTIES:
    :DRILL_CARD_TYPE: hide2cloze
    :ID:       8ffa33dc-5f91-4bb5-90d2-40809a52a369
    :DRILL_LAST_INTERVAL: 3.86
    :DRILL_REPEATS_SINCE_FAIL: 2
    :DRILL_TOTAL_REPEATS: 1
    :DRILL_FAILURE_COUNT: 0
    :DRILL_AVERAGE_QUALITY: 3.0
    :DRILL_EASE: 2.36
    :DRILL_LAST_QUALITY: 3
    :DRILL_LAST_REVIEWED: [2018-02-17 Sat 11:08]
    :END:
    The expressions of Binary Theory are called [binary expressions].
    We call some binary expressions [theorems], and others
    [antitheorems].


* Vocabulary

** aid                                                            :satellite:
 [2018-02-17 Sat 10:08]

*** >>>                                                               :drill:
    :PROPERTIES:
    :DRILL_CARD_TYPE: hide2cloze
    :ID:       fef997f8-31ea-4f08-8f64-95cd98ff960e
    :END:

  [Aid] is what you do when you help someone — you come to their
  [aid]. Rich countries provide economic aid to poor countries, and
  if you cut your hand, you'll be looking in the first [aid] kit for
  a Band-Aid.

  You can also use aid as a verb: "The librarian will aid you in your
  search." English has some words with meanings related to aid, but
  they're spelled with an -e on the end, because they come from the
  French. A nurse's aide is someone who assists a nurse. An aide-de-camp
  is a close assistant and confidant to a military officer, a word often
  shortened to just aide, to refer to an assistant to a political
  official.

  Binary Theory, also known as boolean algebra, or logic, was
  designed as an aid to reasoning, and we will use it to reason
  about computation.
** reason                                                         :satellite:
 [2018-02-17 Sat 10:08]

 A reason explains why you do something. The reason you go to school is
 to learn things (and because it's the law).

 Reason usually has to do with thought and logic, as opposed to
 emotion. If people think you show good reason, or are reasonable, it
 means you think things through. If people think you have a good reason
 for doing something, it means you have a motive that makes sense.
 Reason can also be a verb. You might reason something out, which means
 that you look at all sides of the issue and then and decide what to
 do.

 Binary Theory, also known as boolean algebra, or logic, was
 designed as an aid to reasoning, and we will use it to reason
 about computation.
** negate                                                         :satellite:
 [2018-02-17 Sat 10:10]

 If something neutralizes the effect of something else, then you can
 say the effect is negated. Hanging a disco ball from your living room
 ceiling negates the sleek modern effect created by the contemporary
 furniture.

 If something is proved false or untrue, it has been negated. The
 discovery of one dinosaur jaw negated the conventional wisdom that all
 dinosaurs were vegetarians, since the tooth structure proved that guy
 definitely ate meat. The verb negate can also mean to counteract or
 counterbalance — so a really strong serve can negate your other
 weaknesses on the tennis court.

 If we negate a theorem we obtain an antitheorem, if we negate an
 antitheorem we obtain a theorem.
** obtain                                                         :satellite:
 [2018-02-17 Sat 10:11]

 Obtain means to get something that is not so easy to come by such as
 knowledge, rights, or a large amount of money. You wouldn't say you
 obtained a pair of pants, unless they were one of a kind.

 At times in its history, obtain has meant to be victorious or to
 succeed. Today, it mostly means to acquire, but keeping its prior
 meanings in mind helps you to use it in the right way. College degrees
 are something that you obtain as is permission from your parents to go
 to a party. When you obtain something, you have worked hard to get it,
 so you are pretty happy to have it.

 If we negate a theorem we obtain an antitheorem, if we negate an
 antitheorem we obtain a theorem.
