
* 2016
** 2016-08 August
*** 2016-08-01 Monday
**** Three things really bothered me:

      1. If I'm not sitting at my desk typing, I'm not working.
      You hired me as a programmer, not as a typist.  You could
      have saved yourself a fortune if all you wanted was a clerk.
      Programming is problem-solving, it's not typing.

      2. Program specifications that specify something completely
	 different than what the client actually wants.
	 (It happens a lot if the client thinks he knows programming
	 and specifies the program in what he thinks are programming
	 terms, not in the terms of his business.
	 I can lean accounting a lot faster than you can get 20 years
	 of programming experience.)

      3. Making "just this little change - it's no work at all, so don't
	 add it to the bill".  If it's no work at all, YOU do it. If I
	 have to spend 3 hours clearing up exactly what you want changed
	 and how you want it changed, that's 3 hours you're going to pay
	 for and nothing's been written yet.  And making one little
	 change may impact other areas, which will also have to be changed.
	 Programmers know the word side-effects - clients don't.
	 ("You can't do just one thing.")  Your "little change" may be 80
	 man-hours of work.  You're not getting that for free.  Read your
	 contract.  ANY changes from the specifications in the contract
	 will be billed additionally.

**** The "dolla dolla bills" argument:
   For internet businesses, website
   performance is super-critical to their bottom line. There are studies
   that show that: 

       "Amazon found every 100ms of latency cost them 1% in sales. Google
       found an extra .5 seconds in search page generation time dropped
       traffic by 20%. A broker could lose $4 million in revenues per
       millisecond if their electronic trading platform is 5 milliseconds
       behind the competition."

   For this reason, there is a lot of investment into
   performance/productivity improvements from the big players. Google
   built the v8 engine that powers Chrome and Node.js. Facebook created
   and open-sourced the React.js framework. Google maintains the
   Angular.js framework.
**** Risk and failure don’t necessarily equate
   You could be a high failure and low risk person.
   Being an entrepreneur in Silicon Valley is way lower
   risk than working at a big company. Your downside scenario is you learn a
   lot, you grow a ton…your worst case scenario at a larger company is you
   get stuck, you might not be growing much, you might be unhappy.
*** 2016-08-02 Tuesday
**** being a good programmer
     keep improving yourself and updating with the current developments
     of languages, tools, libraries, application design trends
*** 2016-08-03 Wednesday
**** information sponge
     An aggressive little yellow one that chases people and data around
*** 2016-08-12 Friday
**** What are the biggest myths software engineers believe?
   1 "There's no existing code that does what I need. I'll have to write
     it from scratch."
   2 "This code I'm inheriting is crap. I'll have to write it from
     scratch."
   3 "This is just a temporary hack - I'll come back and fix it later."
   4 "Just two more weeks."
   5 The solution to any problem (poverty, starvation, drought) is
     technology.
   6 Edit: I originally had 'Open plan is less productive than offices'
     because I'd read old research about it. I now believe Open Plan is
     bad for Engineering.
   7 Half an hour isn't long enough to get in "the zone" and write good
     code.
*** 2016-08-16 Tuesday
**** Code smells
   One of the biggest advantages of following a test-driven development process
   is that the tests that we write are always around to make sure that we don't
   break anything. This gives us a safety net to tinker with the code and make
   sure that it is easy to read, easy to maintain, and well written.
*** 2016-08-17 Wednesday
**** Tests as a safety net 
   Having a solid set of tests is critical before we do refactoring. This is
   because tests give us the confidence that we haven't broken anything
   during the refactoring. We will be running the tests multiple times
   during a refactoring as we proceed from step to step.
*** 2016-08-18 Thursday
**** _single_leading_underscore
   weak "internal use" indicator.  E.g. "from M import *" *does not import*
   objects whose name starts with an underscore.
**** Single Responsibility Principle (SRP)
     Class should have a single, clear, coherent purpose. A class that tries
     to do too many different things is an indicator of a poor design.
*** 2016-08-25 Thursday
**** worth their weight in gold
   To get a GOOD programmer, with that level of experience, passion and
   dedication to their career is very hard to find. When you do find one,
   they're worth their weight in gold.
*** 2016-08-29 Monday
**** Part of healthy self-esteem
   Part of healthy self-esteem is the ability to see both your strengths
   and your weaknesses rationally. Belief in yourself will let you do
   many, many things. It will not let you do anything.
*** 2016-08-31 Wednesday
**** If I could do it all again
   If I could do it all again I would choose something that I was
   passionately interested in to make my college experience more
   enthralling.
**** Incredible advantage
   I believe "do what you love" puts you at an incredible advantage
   because it's much easier to work harder at what you enjoy.
** 2016-09 September
*** 2016-09-05 Monday
**** personal philosophy
   One of the pillars of my personal philosophy is a firm belief that
   inaction is the only foolproof method to fail. If I don't do anything,
   I won't accomplish anything. If I give up, the results will never
   come.
**** personal philosophy
   You *should* be in job the younger, cheaper
   person couldn't do nearly as well, if at all
**** "Everyone has a story you don't know"
   It is a pretty known statement, but since the first time I heard it,
   it touched me deeply. 

   It makes me always remember to not judge people and to respect
   everyone's choices.
**** back-end devs on CSS
   First, understand what this language is

   CSS is a style language. It's probably closer to declarative
   programming or rule-based programming. CSS is to HTML what XSLT is to
   XML.

   With this kind of language, does it make sense that there be compile
   errors and message logs? No, it doesn't. The web wouldn't be very user
   friendly if a page stopped working the moment it encountered an error
   in a stylesheet.

   So it's a good thing that CSS is a declarative language that can still
   be parsed, even when the browser encounters an error. That means that
   one mistake doesn't crash the site!

   Now, let's, learn the parts of CSS

   Let's look at this:

   .myClass {
   padding: .25em 1em;
   }

   This is called a ruleset. A ruleset is composed of two parts:

   The selector, .myClass
   The declaration block, {padding: .25em 1em;}

   A declaration block is composed of declarations. Each declaration
   contains two things:

   A property, padding:
   A value, .25em 1em

   You come from a backend world. So look at declaration blocks like you
   would look at JSON; they're key value pairs!

   What does this mean for debugging?

   That a problem could be in one of five places:

   1 The ruleset: not formatted correctly, not present
   2 The selector: not formatted correctly, not applicable to any element
   3 The declaration block: not formatted correctly, not present
   4 A property: not valid, not applicable to the element
   5 A value: not valid, not formatted correctly

   Next, Learn the Cascades

   Let's talk about the "C" in CSS. The "C" is for Cascade.

   There are many cascades. In CSS 2.1, there were three:

   1 User Agent (the browser)
   2 Author (what you write)
   3 User (the person looking at the web page)

   Now there are 10 cascades. [1] It's a bit more confusing. But what it
   amounts to is that the CSS that you're writing and debugging is in the
   middle. Your CSS comes after the browser's, but before the end-user's.

   What does that mean for debugging?

   Some issues are from the user agent cascade
   Some issues, albeit rarely, an issue comes from the user cascade
   Most issues come from attempting to modify the cascade (use of !
     important, unnecessarily high specificity)

   Then, learn how the browser parses a selector

   This is important for back end devs, because this fact is not
   intuitive:

   The browser parses a selector from right to left.

   When you write this:

   #thisId .thisClass .thatClass div ul li a {
           color: red;
   }

   Do you know what the browser reads first?

   a {}

   Why?

   Because, that's what you're styling. Everything in front of is just a
   "filter" to speak of. And think about it:

   Do filters improve performance? Do they decrease the likelihood of
   errors?

   No. No they don't.

   JavaScript does not behave this way, by the way. Longer selectors can
   be helpful in JavaScript, after all, this will be parsed left to
   right. But don't write CSS selectors like you would JavaScript.

   What does this mean for debugging?

   The longer a selector is, the more likely it is to not apply
   If a declaration block is not being applied at all, it is because of
     the selector

   Now, understand the basics of "specificity"

   I could write a whole essay on specificity. But that won't help you in
   debugging.

   When do you need to focus on specificity?

   1 If you have two matching properties,
   2 being styled in two different rulesets,
   3 whose selectors apply to the same element

   e.g., this doesn't matter. It's different properties.

   .someClass {
   color: red;
   }
   #someID{
   font-family: Arial;
   }

   But this could matter:

   .someClass {
   color: red;
   }
   #someID{
   color: blue;
   }

   Only if this is also true:

   <div id="someID" class="someClass">
   </div>

   Now, sometimes, people will opt to "break" the cascade with !
   important:

   .someClass {
   color: red !important;
   }
   #someID{
   color: blue;
   }

   This is the wrong time for !important. Whoever does that is an
   asshole. Don't be that guy.

   What does this mean for debugging?

   If a style is not being applied, but you know that the declaration
   block and ruleset are correct:

   The property is being overwritten in another ruleset with a more
   specific selector
   The property is being overwritten in another ruleset with an equal,
     or less specific selector, where the property has an !important
     declaration

   Browsers are hard

   There are standards
   Browsers are supposed to follow standards
   Most of the browsers are pretty good about following standards
   IE7, 6 were not good about following standards
   IE8 followed html4 and css2.1 standards
   Where a standards doesn't say how to do it, browsers will be
   different

   What does this mean for debugging?

   You'll need whisky. Lots and lots of whisky.
   https://www.w3.org/TR/css-cascade-3/#cascade-origin
*** 2016-09-09 Friday
**** What is profiling?
     profiling in any language and anything is knowing heuristics about
     what is running in your program, and for example how many times is
     a function called, and how long does it take for this section of
     code to run. And it's simply like a statistical thing. Like you
     get a profile of your code, you see all the parts of your code
     that are fast or slow for example.
** 2016-10 October
*** 2016-10-02 Sunday
**** Heisenberg uncertainty
   ...that it's a little bit like the Heisenberg uncertainty principle. If you observe a thing, by the fact that you've observed it, you've altered it.
    file:/usr/local/share/DVCS/talk-python-transcripts/transcripts/028.txt::that%20it's%20a%20little%20bit%20like%20the%20Heisenberg%20uncertainty%20principle.%20If%20you%20observe%20a%20thing,%20by%20the%20fact%20that%20you've%20observed%20it,%20you've%20altered%20it.
**** PyCallGraph
   I was searching around more and I found PyCallGraph, which is amazing at showing you the flow of your program and it gives you great graphical representation of what cProfile is also showing you
    file:/usr/local/share/DVCS/talk-python-transcripts/transcripts/028.txt::I%20was%20searching%20around%20more%20and%20I%20found%20PyCallGraph,%C2%A0which%20is%20amazing%20at%20showing%20you%20the%20flow%20of%20your%20program%20and%20it%20gives%20you%20great%20graphical%20representation%20of%20what%20cProfile%20is%20also%20showing%20you
**** just pip install PyCallGraph
   Yeah, super simple. It's one of the best things about pip as a package manager
    file:/usr/local/share/DVCS/talk-python-transcripts/transcripts/028.txt::Yeah,%20super%20simple.%20It's%20one%20of%20the%20best%20things%20about%20pip%20as%20a%20package%20manager
**** built in data structures instead of creating your own
   Then there is some other interesting things you can do as well like you could use like
   name tuples instead of actual class, or you could use built in data structures instead
   of creating your own. Because a lot of times, the built in structures like list, an array,
   and dictionary and so on are implemented deep down in C and they're much faster
    file:/usr/local/share/DVCS/talk-python-transcripts/transcripts/028.txt::Then%20there%20is%20some%20other%20interesting%20things%20you%20can%20do%20as%20well%20like%20you%20could%20use%20like%20name%20tuples%20instead%20of%20actual%20class,%20or%20you%20could%20use%20built%20in%20data%20structures%20instead%20of%20creating%20your%20own.%20Because%20a%20lot%20of%20times,%20the%20built%20in%20structures%20like%20list,%20an%20array,%20and%20dictionary%20and%20so%20on%20are%20implemented%20deep%20down%20in%20C%20and%20they're%20much%20faster
**** using a nuke to deal with a fly
   When you are about to give up is much too late to motivate. It's not
   as though some Tony-Robbins-like techniques will not help you at this
   last moment, but it's like using a nuke to deal with a fly.
*** 2016-10-30 Sunday
**** Grok
   This one comes from the book Stranger in a Strange Land, but
   it's been tweaked a bit and co-opted in coding to mean something along
   the lines of dismantling a concept and understanding it on a
   relatively deep level.
**** Everything from scratch
   Because they haven't walked up and down the hills and haven't hit the
   dead ends and the brambles before, so it feels like a much more
   tractable problem or task than it actually is.
** 2016-11 November
*** 2016-11-14 Monday
**** A reader lives a thousand lives and writer creates a million dreams
**** turn something upside down
   How to describe doing a thorough search for something in a very messy
   way
** 2016-12 December
*** 2016-12-29 Thursday
**** Aristotle said
   "We are what we do repeatedly, therefore, excellence is not an act, but a habit."
**** Plan those steps into feasible deadlines
   should be flexible enough that you don't have to stress AT ALL about
   getting them done
*** 2016-12-30 Friday
**** specific topic
   Automate the Boring Stuff with Python
* 2017
** 2017-01 January
*** 2017-01-02 Monday
**** measure of a good programmer
   The only measure of a good programmer is the ability to make good
   programs. Anything beyond that is just hand waving.
*** 2017-01-12 Thursday
**** "Classes" and "objects"
   Classes can be thought of as blueprints for creating objects.
**** problem of isolating tests from each other
   mock objects are any objects that you can use as
   substitutes in your test code, to keep your tests from overlapping and
   your tested code from infiltrating the wrong tests.
*** 2017-01-23 Monday
**** https://www.buzzfeed.com/ailbhemalone/sleeping-apps?utm_term=.oc71aMv22#.xi7RxdYJJ
   a list of 17 apps to help you fall asleep easily
**** http://thesleepdoctor.com/all-about-sleep/how-to-sleep-better/sleep-calculator/
   Sleep Doctor’s sleep calculator
**** The Sleep Revolution: Transforming  Your Life, One Night at a Time
   Read Arianna Huffington’s book
**** https://www.headspace.com/headspace-meditation-app
   turn on an app to start your day on the right foot
**** Keep a gratitude journal
     For five minutes each morning, write 3
     things you are grateful for today: it can be something as simple as
     a roof over your head, food in the fridge, a warm bed, running
     water, a positive relationship with people you love the most, etc.
     Practicing gratitude about what we have going for us can restructure
     our brain to focus on positive things, which sets the tone for the
     rest of the day, and that directly impacts our productivity.
** 2017-02 February
*** 2017-02-08 Wednesday
**** Robert Louis Stevenson
     To know what you like is the beginning of
     wisdom and of old age
**** Five whys
     When confronted with a problem, have you ever stopped and
     asked why five times? It is difficult to do even though it
     sounds easy.
*** 2017-02-09 Thursday
**** If we could live without it, we did. 
     She knew every step in life has the potential to be a chain if it comes at the wrong time.
*** 2017-02-24 Friday
**** Programming requires a lot of patience,
     and the ability to learn on your own. Don’t be discouraged
**** To me, the ability that differentiates the brilliant programmers
     from the pack is the ability to mentally visualize their art.
*** 2017-02-28 Tuesday
**** The maximal level of performance  
     for individuals in a given domain is not attained automatically
     as a function of extended experience, but the level of performance
     can be increased even by highly experienced individuals as a
     result of deliberate efforts to improve.
**** The most effective learning requires
   a well-defined task with an appropriate difficulty level for the
   particular individual, informative feedback, and opportunities for  
   repetition and corrections of errors
**** Bad programming is easy  
     Idiots can learn it in 21 days, even if they are dummies
**** The key is deliberative practice:
     not just doing it again and again, but challenging yourself with a task
     that is just beyond your current ability, trying it, analyzing your
     performance while and after doing it, and correcting any mistakes
**** Socrates put it well
   We are what we repeatedly do.
   Excellence, then, is not an act, but a habit.
** 2017-03 March
*** 2017-03-02 Thursday
**** Just as nobody becomes a piano player without playing the piano,
     nobody becomes a program designer without creating actual programs
     and getting them to work properly.
**** The modern way to build applications is to go as serverless as possible.
     - For your web services use something like Amazon Lambda.
     - For static files just use S3.
     - For the database? Amazon RDS.
     - For email and other notifications? Amazon SES.
     - Welcome to 2017.
**** Our Values
***** Mission First
      We place long-term, collective impact ahead of personal
      achievement.
***** Drive
      We aim high and do whatever it takes to get things done.
***** Agility
      We are nimble in our processes and systems, ready to adapt to a
      changing world.
***** Awareness
      We are rigorous in our decisions and candid in our
      communication.
***** Pragmatism
      We stay grounded in the outcomes that truly matter for our
      mission.
*** 2017-03-08 Wednesday
**** You don't start out writing good stuff.
     You start out writing crap and thinking it's good stuff, and then
     gradually you get better at it. That's why I say one of the most
     valuable traits is persistence.
*** 2017-03-10 Friday
**** A stone's throw
   A short distance.
**** As quick as greased lightning
   Very fast.
**** My method to overcome a difficulty
     is to go around it
     file:/usr/local/share/DVCS/lib/org/motto.org::is%20to%20go%20around%20it
**** THE SUN IS so dazzlingly bright
   so comforting in cold climates, so mercilessly scorching in hot
   ones, it is no wonder many peoples have worshipped it as a god.
*** 2017-03-21 Tuesday
**** http://www.kdnuggets.com/2017/03/dataiku-top-algorithms.html
   Algorithms are sets of
   rules that a computer is able to follow.
** 2017-04 April
*** 2017-04-23 Sunday
**** Like an african adage would say:
     “Remove the dirt in your eyes first before that of another
     person.”
*** 2017-04-24 Monday
**** Inspiration comes to those who are ready for it.
     It doesn’t strike randomly.
** 2017-05 May
*** 2017-05-02 Tuesday
**** The machine learning approach,
     is to say, instead of writing each program by hand for each
     specific task, for particular task, we collect a lot of examples,
     and specify the correct output for given input.
     2017-03-21-why-machine-learning.org
*** 2017-05-04 Thursday
**** Wisdom begins in wonder
     Socrates
**** simplicity is
     the easiest way to instruct, teach, inform and pass information
     onto another person.
**** simplicity is
     much harder to achieve than complexity.
**** Intelligent people know
     that it is easy to complicate things.
*** 2017-05-07 Sunday
**** Our life is
     a list of the experiments we try, the discoveries we make, the
     failures we encounter along the way to greater successes and
     rewards.
**** If you just listen,
     you never learn. If you just learn, you never do.
*** 2017-05-08 Monday
**** With enough neurons and enough time,
     a recurring neuron network can compute anything that can be
     computed by your computer.
**** We have two ears and one mouth so that we can listen twice as much as we speak.
     Epictetus
*** 2017-05-14 Sunday
**** Software testing
     is an investigation conducted to provide stakeholders with
     information about the quality of the product or service under
     test.
**** To my way of thinking,
     anything sent via courier or mail should have a cover letter, but
     using a letter for such a purpose can also accomplish several
     things.
**** The proper use of a cover letter
     can be a gesture of personal courtesy which lends dignity and
     weight to the related transaction.
** 2017-07 July
*** 2017-07-14 Friday
** 2017-08 August
*** 2017-08-18 Friday
**** “The mass of men lead lives of quiet desperation”
     Thoreau was totally correct when he said, “The mass of men lead
     lives of quiet desperation”
* 2018
** 2018-01 January
*** 2018-01-27 Saturday
**** The eloquent leader definition
     A leader is the one who brings even the persons with different
     ideologies, mindsets and creed to come in a group and follow one
     direction towards achieving any certain goal.
