-*- coding: utf-8 -*-

* burglar :Feynman:
  [2017-09-22 Fri 20:52]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       4aeff98f-903b-4e86-bbe9-2cae4a03ce43
   :END:
   burglar

*** --->
    взломщик

    noun
    1. грабитель (robber, burglar, mugger, plunderer, looter, snatcher)
    2. взломщик (burglar, housebreaker, breaker, cracksman, picklock,
       yegg)
    3. вор (thief, burglar, prowler, drummer, gunsmith, hook)
    4. ночной грабитель (burglar)
    5. вор-взломщик (burglar, passkey man)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       83891a69-0a48-4d13-b28a-5a757f9b5540
   :END:

   noun
   1. a person who commits [burglar]y. "A pioneering scheme to gate off
      alleys to [burglar]s and thieves could be on its way to parts of
      central York."

   Use the word [burglar] when you're talking about someone who steals
   things from inside a house or a building.

   A [burglar] often breaks a window or forces a lock, intending to take
   valuable items. The act of doing this is [burglar]y, and to do it is
   to [burglar]ize in the United States, or to burgle in Britain. In the
   1540's, [burglar] was a short form of the word burglator, from the
   Latin burgare, "to break open."

   About that time I invented a [burglar] alarm, which was a very
   simple-minded thing: it was just a big battery and a bell connected
   with some wire.

* tremendous :Feynman:
  [2017-09-22 Fri 20:53]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       7fccf2dd-9f45-490d-ac00-b8b249637cfd
   :END:
   tremendous

*** --->
    огромный

    adjective
    1. огромный (huge, enormous, great, vast, immense, tremendous)
    2. потрясающий (tremendous, terrific, shocking, startling,
       incredible, breathtaking)
    3. громадный (enormous, huge, vast, great, tremendous, immense)
    4. страшный (terrible, fearful, horrible, frightful, frightening,
       tremendous)
    5. ужасный (terrible, horrible, awful, appalling, dreadful,
       tremendous)
    6. потрясный (incredible, zingy, super, cool, killing, tremendous)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       300274e7-8fca-4178-9bea-a3173c43b7f2
   :END:

   adjective
   1. very great in amount, scale, or intensity. "Penny put in a
      [tremendous] amount of time"

   [Tremendous] means extraordinarily large in size, extent, amount,
   power, or degree. It can also mean really marvelous and fantastic —
   or really awful and terrible.

   We often use [tremendous] if something is super wonderful. If someone
   comes into your office and tells you you just won a big contract and
   are getting a huge bonus, you might exclaim, “[Tremendous]!”
   [Tremendous] comes from the Latin for "trembling," and is connected
   with fear. Something [tremendous] can be big in a terrifying way, like
   the [tremendous] noise of an approaching hurricane, or a [tremendous]
   tidal wave about to crash on the shore.

   All of a sudden this [tremendous] bell went off with a helluva
   racket–BONG BONG BONG BONG BONG!!!

* helluva                                                           :Feynman:
  [2017-09-22 Fri 20:53]

** ===>                                                               :drill:
   :PROPERTIES:
   :ID:       0d999795-12a8-48d7-9cd8-5d1455296064
   :END:
   helluva

*** >>
    адский

    adjective
    1. адский (hellish, infernal, diabolical, helluva, devilish, Stygian)
    2. чертовский (damn, devilish, fucking, helluva, damned, plaguy)


** >>                                                                 :drill:
   :PROPERTIES:
   :ID:       250765da-f59c-4334-a59b-5bf955910132
   :END:
   All of a sudden this tremendous bell went off with a
   [helluva||devilish] racket–BONG BONG BONG BONG BONG!!!

* coax :Twain:
  [2017-09-22 Fri 21:00]
** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       b9d04cef-e83b-41d5-88fa-178428c5d243
   :END:
   coax
*** --->
    уговаривать

    verb
    1. уговаривать (persuade, coax, reason, sell, win, blandish)
    2. задобрить (cajole, coax, wheedle)
    3. упрашивать (entreat, beg, coax, beseech, solicit, blandish)
    4. задабривать (coax, jolly, blandish)
    5. увещевать (exhort, admonish, remonstrate, coax, expostulate)
    6. добиваться с помощью лести (coax)
    7. добиваться с помощью уговоров (coax)

    noun
    1. пулемет комплексной установки (coax)
**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       b0c5c93f-7d49-4647-b990-52f5a476deb9
   :END:

   verb
   1. persuade (someone) gradually or by flattery to do something. "the
      trainees were [coax]ed into doing hard, boring work"

   noun
   1. [coax]ial cable. "After all, you can't lay fiber, buy cable modems
      and pay for cable TV with surplus [coax] ."

   adjective
   1. [coax]ial. "[coax] connectors"

   When you [coax] someone, you try to convince him gently, with pleasant
   words and maybe a little flattery. You’ll have to be patient, as you
   can’t rush someone you’re trying to [coax].

   When you [coax], you have to be nice about it – you can’t threaten or
   force. You put on a little charm and gently urge, so that the person
   or thing is happy about being [coax]ed. You might [coax] the runaway
   elephant back into the zoo by patting her gently and talking into
   her ear. If you wake up with a terrible bedhead, you might [coax] your
   hair back into place with the help of a little hair gel and a comb.

   Everybody that could get a chance at him tried their best to [coax]
   him off of his horse so they could lock him up and get him sober;
   but it warn't no use—up the street he would tear again, and give
   Sherburn another cussing.

* reeling :Twain:
  [2017-09-22 Fri 21:02]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       83cca877-9f5b-4a1f-b786-692f8ec8cd69
   :END:
   reeling

*** --->
    наматывание

    noun
    1. наматывание (winding, reeling)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       3c0106ad-15eb-4b78-9335-89e541485eb0
   :END:

   verb
   1. wind a line onto a reel by turning the reel. "That's his hand
      holding my spent target, after I emptied a round in it and reeled
      it in ."
   2. lose one's balance and stagger or lurch violently. "he punched
      Connolly in the ear, sending him [reeling]"
   3. dance a reel. "Anyone who wanted to dance could reel to the sound
      of the ceilidh band playing at the Butter Cross."

   A reel is a cylinder that can be wound with flexible material like
   film or fishing line. If you found dozens of reels of old home
   movies in your grandparents' attic, you'd search for a projector.

   You might find an old movie reel, a reel of copper wire, or a
   fishing reel. Use the reel on your fishing pole to reel in your
   fish! Yes, it’s a verb, too. And it’s a lively folk dance — or the
   music for it — from Scotland (Highland reel), or America (Virginia
   reel). As a verb, reel also means to sway from dizziness. If an ear
   infection messes with your balance, you might reel down the hall
   like you were drunk.

   He was a-[reeling] across the street towards me, bare-headed, with a
   friend on both sides of him a-holt of his arms and hurrying him
   along.

* uneasy :Twain:
  [2017-09-22 Fri 21:03]

** ==>                                                                :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       e093a8b8-6d7c-46d8-86c7-d88ce531d27f
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:05]
   :END:
   uneasy

*** --->
    беспокойный

    adjective
    1. беспокойный (restless, troubled, troublesome, hectic, anxious,
       uneasy)
    2. неудобный (inconvenient, uncomfortable, awkward, fiddly, uneasy,
       unhandy)
    3. неловкий (awkward, clumsy, uneasy, ungainly, gauche, ungraceful)
    4. тревожный (alarming, anxious, disquieting, worried, uneasy,
       restless)
    5. стесненный (cramped, constrained, uneasy, straitened,
       embarrassed, pinched)
    6. связанный (connected, bound, related, tied, associated, uneasy)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       c819cd7f-f747-4034-b955-7004d855e209
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:07]
   :END:

   adjective
   1. causing or feeling anxiety; troubled or uncomfortable. "she felt
      guilty now and a little [uneasy]"


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       755ba07c-0ebe-493d-96ed-94385532a4fe
   :END:
   [Uneasy] describes an uncomfortable feeling. You might feel socially
   [uneasy] when dining with your girlfriend's parents if they don't like
   you very much. Your stomach may also feel [uneasy] at that same dinner
   and gurgle in an embarrassing way.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       594ee560-c153-4566-8e17-20134cda05c1
   :END:
   The adjective [uneasy] has many shades of meaning, most involving mild
   discomfort. It can refer to a lack of a sense of security. If
   McDonald's and Burger King team up to develop a new sandwich, that
   would be an [uneasy] alliance, because neither side would fully trust
   the other. [Uneasy] can also describe causing someone to feel anxious
   or nervous. If you see someone staring at you mumbling, "That's him,
   that's the one," you might feel [uneasy].
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       d275cb85-66ea-4bc1-9ae2-9a080edb5c2f
   :END:
   He was quiet, and looked [uneasy]; and he warn't hanging back any, but
   was doing some of the hurrying himself.

* aiming :Twain:
  [2017-09-22 Fri 21:03]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       a821949b-c06a-4ff2-9a3b-866deeaa5f39
   :END:
   aiming

*** --->
    прицеливание

    noun
    1. прицеливание (aiming, aim, sighting)
    2. наводка (aiming, leveling, laying, levelling)

    adjective
    1. прицельный (aiming, aimed, pinpoint)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       db80eecb-93c3-4986-bed9-cda720cac845
   :END:

   verb
   1. point or direct (a weapon or camera) at a target. "aim the
      camcorder at some suitable object"
   2. have the intention of achieving. "new French cooking aims at
      producing clear, fresh flavors and light textures"

   If you wad up a piece of paper and line up a shot at a wastebasket,
   you are taking aim. If instead, the paper bounces off your teacher's
   head, then your aim was way off.

   A purpose or goal is an aim. When you were little, your aim might
   have been to be a famous astronaut, a movie star, or a police
   officer. As a verb, aim means to intend, try, or aspire. You may aim
   to take your dog for three walks every day, but your fenced-in yard
   tends to make both of you lazy.

   He was standing perfectly still in the street, and had a pistol
   raised in his right hand—not [aiming] it, but holding it out with the
   barrel tilted up towards the sky.

* tilt                                                                :Twain:
  [2017-09-22 Fri 21:04]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       5c6d7d12-450b-4b14-bca7-85bfe16bf3a9
   :END:
   tilt

*** --->
    наклон

    noun
    1. наклон (incline, lean, tilt, slope, inclination, tip)
    2. тент (awning, tilt, canopy, sunshade, sunblind, penthouse)
    3. крен (bank, roll, heel, heeling, list, tilt)
    4. наклонное положение (tilt, cant)
    5. скос (bevel, slant, chamfer, skew, rake, tilt)
    6. спор (dispute, controversy, argument, debate, quarrel, tilt)
    7. ссора (quarrel, row, altercation, contention, bickering, tilt)
    8. стычка (hassle, skirmish, encounter, engagement, brush, tilt)
    9. парусиновый навес (tilt)

    verb
    1. наклонять (cant, tilt, lean, bend, tip, incline)
    2. наклоняться (tilt, lean, bend, tip, incline, stoop)
    3. опрокидывать (overturn, upset, tip over, topple, tilt, keel over)
    4. опрокидываться (overturn, upset, tip over, topple, tilt, keel
       over)
    5. бороться (fight, struggle, combat, deal, contend, tilt)
    6. поворачивать (turn, turn off, swing, twist, tilt, bend)
    7. критиковать (criticize, attack, damn, carp, rap, tilt)
    8. откидывать (recline, tilt)
    9. биться (beat, fight, struggle, chip, pound, tilt)
    10. сталкиваться (face, encounter, collide, clash, interfere, tilt)
    11. биться на копьях (tilt)
    12. сражаться на турнире (tilt, tourney)
    13. ковать (forge, hammer, work, tilt, beat out)
    14. покрывать парусиновым навесом (tilt)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       10a986ea-3086-478e-b4bf-fbe1eb6e0f97
   :END:

   noun
   1. a sloping position or movement. "the [tilt] of her head"
   2. a combat for exercise or sport between two men on horseback with
      lances; a joust.

   verb
   1. move or cause to move into a sloping position. "the floor [tilt]ed
      slightly"
   2. (in jousting) thrust at with a lance or other weapon. "he [tilt]s
      at his prey"


   He was standing perfectly still in the street, and had a pistol
   raised in his right hand—not aiming it, but holding it out with the
   barrel [tilt]ed up towards the sky.

* cock                                                                :Twain:
  [2017-09-22 Fri 21:05]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       5b0ed9da-b195-44e6-a2ec-d582c271b445
   :END:
   cock

*** --->
    петух

    noun
    1. петух (cock, rooster, bantam, chicken, cock-a-doodle-doo)
    2. кран (crane, tap, faucet, cock, spigot, water tap)
    3. хуй (dick, cock, prick, penis, pecker)
    4. курок (hammer, cock, dog, nab)
    5. самец (male, buck, bull, cock, mate, male beast)
    6. пенис (penis, cock, dick, willy, organ, prick)
    7. елдак (cock, prick, whoremonger)
    8. флюгер (vane, weather vane, weathercock, windvane, cock)
    9. хер (dick, prick, cock, pecker, penis)
    10. сторожок (cock)
    11. петушиный крик (cock)
    12. бред (rave, delirium, ravings, drivel, ramble, cock)
    13. стрелка (arrow, hand, pointer, cursor, switch, cock)
    14. копна (shock, stack, cock)
    15. сиденье летчика (cock)
    16. кубрик (cockpit, orlop, orlop deck, cock)
    17. чушь (nonsense, rubbish, drivel, garbage, hooey, cock)
    18. стог (stack, rick, mow, cock)
    19. друг (friend, mate, lover, chum, sidekick, cock)
    20. половой член (penis, dick, cock, pecker, tool, prick)
    21. коновод (ringleader, cock)
    22. вожак (leader, bellwether, fugleman, ringleader, cock, foregoer)
    23. забияка (bully, rooster, blusterer, hothead, bantam, cock)

    verb
    1. взводить курок (cock)
    2. поднимать (lift, raise, up, pick up, put up, cock)
    3. взметать (cock)
    4. взметнуть (cock)
    5. взметнуться (cock)
    6. складывать сено в стога (cock)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       ebe463ae-e2a4-4d13-a978-2fcaf36998a4
   :END:

   noun
   1. a male bird, especially a rooster. "Pheasants are handsome birds,
      especially the [cock]s , which are larger than the hens."
   2. a penis.
   3. nonsense. "that's all a lot of [cock]"
   4. a firing lever in a gun which can be raised to be released by the
      trigger.
   5. a stop[cock].
   6. a small pile of hay, straw, or other material, with vertical
      sides and a rounded top. "Country people will recall the
      mini-cyclones lifting [cock]s of hay into the air and carrying them
      for a distance before dropping them back to ground again."

   verb
   1. tilt (something) in a particular direction. "she [cock]ed her head
      slightly to one side"
   2. raise the [cock] of (a gun) in order to make it ready for firing.
      "The sound of fifty plus guns being [cock]ed ready to fire echoed
      throughout the enclosed hangar."
   3. shape (hay, straw, or other material) into a pile with vertical
      sides and a rounded top.

   [Cock] is most often used to refer to either birds or guns. A [cock] is
   a rooster, but it's also the hammer on a gun that you adjust so you
   can fire it.

   You might hear the word [cock] used to mean "penis," but that's a
   vulgar form of the word, so be sure you're in the right company if
   you opt to use it. A [cock] is a male bird, particularly a rooster.
   When you [cock] a gun, you raise its [cock] to make it ready for firing.
   When you [cock] something in a certain direction, you are tilting it
   that way.

   Boggs and the men turned round to see who called him, and when they
   see the pistol the men jumped to one side, and the pistol-barrel
   come down slow and steady to a level—both barrels [cock]ed.

* squirm                                                              :Twain:
  [2017-09-22 Fri 21:10]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       5ef97051-f686-4244-9ce9-7c1c38edfa98
   :END:
   squirm

*** --->
    извиваться

    verb
    1. извиваться (wriggle, squirm, coil, meander, serpentine, wiggle)
    2. корчиться (squirm)
    3. испытывать неловкость (squirm, hate)

    noun
    1. ерзание (wiggle, squirm, wiggle-waggle)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       7c20fed9-fd84-4a53-a800-f9302c1a3762
   :END:

   noun
   1. a wriggling movement. "Okay, so the album's not a step forward so
      much as a [squirm] in quicksand."

   verb
   1. wriggle or twist the body from side to side, especially as a
      result of nervousness or discomfort. "all my efforts to [squirm]
      out of his grasp were useless"

   To [squirm] is to wiggle or twist your body, the way an excited puppy
   will [squirm] when you try to hold him in your arms.

   Small children and animals [squirm] from excitement or eagerness,
   while uncomfortable adults also sometimes [squirm]: "She was so upset
   by her friends' argument that she started to [squirm] in her chair."
   When the word [squirm] first appeared in the 17th century, it was used
   specifically to talk about eels. Experts aren't sure of its roots,
   but some guess [squirm] is connected to worm or swarm.

   Well, pretty soon the whole town was there, [squirm]ing and scrouging
   and pushing and shoving to get at the window and have a look, but
   people that had the places wouldn't give them up, and folks behind
   them was saying all the time, "Say, now, you've looked enough, you
   fellows; 'tain't right and 'tain't fair for you to stay thar all the
   time, and never give nobody a chance; other folks has their rights
   as well as you."

* jawing :Twain:
  [2017-09-22 Fri 21:11]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       d3d95821-3a73-461c-b372-2786ff0ecb10
   :END:
   jawing

*** --->
    jawing

    verb
    1. отчитывать (lecture, jaw, blast, tax, reprehend, school)
    2. говорить (say, speak, tell, talk, refer, jaw)
    3. читать нравоучение (jaw)
    4. вести скучный разговор (jaw)
    5. пережевывать одно и то же (jaw)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       c5cef3af-a55e-4df2-9e85-72b247f1f72b
   :END:

   verb
   1. talk at length; chatter. "he could still hear men [jawing] away
      about the vacuum cleaners"

   Your jaw is the bottom, hinged part of your skull that holds your
   teeth. When you have a cavity, it can make your whole jaw hurt.

   In humans, our jaw is the bony part of the head that contains our
   mouth and teeth. All animals with spines have jaws. Besides this
   anatomical meaning, you can use jaw as a verb to mean "chat." You
   might love to get together with your friends and jaw about
   unimportant things. You can also say "My jaw dropped" to mean "I was
   shocked or amazed." Jaw comes from the Old French joue, which means
   "cheek or jaw."

   There was considerable [jawing] back, so I slid out, thinking maybe
   there was going to be trouble.

* algae :NY:
  [2017-09-22 Fri 21:23]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       56672216-6836-4be7-8e3d-b46259c525ec
   :END:
   algae

*** --->
    водоросли

    noun
    1. волны (surge, water, algae)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       49faef00-f927-4c7b-9aa0-e1aa275dc3df
   :END:

   noun
   1. a simple nonflowering plant of a large group that includes the
      seaweeds and many single-celled forms. [Algae] contain chlorophyll
      but lack true stems, roots, leaves, and vascular tissue. "That
      is, a simple alga like Volvox and a complex metazoan like an
      octopus both occupy the same sublevel."

   Ever walk in the ocean and feel your feet slipping and sliding along
   the rocks? That slimy green stuff under your feet is [algae], a
   nonflowering plant that grows in the water and has no stems, roots,
   or leaves.

   [Algae] is actually the plural form of the word alga, which in Latin
   means, you guessed it: "seaweed." [Algae] isn't just something gross
   looking floating on the water. It's actually important in aquatic
   ecology because the tiny organisms that live suspended in [algae] are
   the food base for most marine food chains.

   The migrants are single-celled green [algae]; they are kin to seaweed,
   but instead of living in the sea they live in snow.

* kin :NY:
  [2017-09-22 Fri 21:23]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       d2368a82-e6bc-4cdb-8e93-6c192f4c8f79
   :END:
   kin

*** --->
    родня

    noun
    1. род (genus, race, kind, family, generation, kin)
    2. родственники (relatives, kin, people, kindred, kinsfolk, kinfolk)
    3. родня (relatives, kin, kinsfolk, kinfolk, my folks, folk)
    4. семья (family, household, home, colony, kin, house)
    5. родство (kinship, relationship, kin, consanguinity, relation,
       connection)
    6. свойство (property, characteristic, feature, attribute, affinity,
       kin)

    adjective
    1. родственный (related, kindred, akin, sister, cognate, kin)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       a80abbed-4ee1-4712-a3a8-3097c3c6c97f
   :END:

   adjective
   1. related. "he was [kin] to the brothers"

   noun
   1. one's family and relations. "he is expected to make a payment to
      his wife's [kin]"

   suffix
   1. forming diminutive nouns such as bump[kin] , cat[kin].

   Some say [kin], others "family," or "relatives." Call them what you
   will, but you’re stuck with those people related to you by blood or
   marriage.

   When someone refers to their kith and [kin], she means her friends and
   family. Both words date back to Old English, [kin] reaching back to
   the 700s. Originally referring to one’s family or race, [kin] narrowed
   to refer just to one’s blood relations. Your "next of [kin]" is your
   closest family member: spouse, child, parent, or sibling.

   The migrants are single-celled green algae; they are [kin] to seaweed,
   but instead of living in the sea they live in snow.

* dormant :NY:
  [2017-09-22 Fri 21:23]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       bbc1b14b-3c53-4e5e-9303-4972b09769b1
   :END:
   dormant

*** --->
    бездействующий

    adjective
    1. бездействующий (inactive, dormant, idle)
    2. спящий (sleeping, dormant, asleep, sleeper)
    3. дремлющий (dormant, dozing, somnolent, drowsy, dozy)
    4. в спячке (dormant, torpid)
    5. скрытый (hidden, latent, covert, occult, ulterior, dormant)
    6. пассивный (passive, dormant, quiescent, effortless, floppy, tame)
    7. потенциальный (potential, dormant, would-be)
    8. находящийся в состоянии покоя (dormant)

    noun
    1. слуховое окно (dormer, gable window, dormant)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       bad955e3-e74a-4e2f-9db6-ee2eb8e28c85
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:07]
   :END:

   adjective
   1. (of an animal) having normal physical functions suspended or
      slowed down for a period of time; in or as if in a deep sleep.
      "[dormant] butterflies"


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       53d4ee8c-1a2a-444f-ab87-719d3f6b1d88
   :END:
   That old dog was [dormant] for so long he was confused for a furry
   doormat, but a doormat is likely to stay [dormant], or inactive,
   because it is lifeless: that old dog has some life in him yet.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       0ee4fe2f-8b6d-4ece-a658-38dbdfb02ac2
   :END:
   Volcanoes are described as [dormant] when they stay cool for a long
   time, without spewing hot lava and ash. They may have the ability to
   come to life, but they remain [dormant], or inactive. [Dormant] comes
   from French dormir, "to sleep," and it refers to living things that
   are on a break rather than things that have died. Being [dormant] is
   being temporarily at rest, although sometimes, as with some cancer
   cells, things become permanently — and thankfully — [dormant].
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       78c3b49f-01dc-4f50-88fa-5f2ae5cdb963
   :END:
   They spend the winter deep in the snowpack, atop last summer’s snow,
   as [dormant] cysts.

* cyst                                                                   :NY:
  [2017-09-22 Fri 21:24]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       22acbdd4-4fb5-4854-9e5f-5afa8dbe9c94
   :END:
   cyst

*** --->
    киста

    noun
    1. киста (cyst, sac)
    2. циста (cyst)
    3. пузырь (bubble, bladder, blister, bleb, cyst, blowhole)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       4debb6a1-9bd4-4188-aed5-32e24af5c587
   :END:

   noun
   1. in an animal or plant, a thin-walled, hollow organ or cavity
      containing a liquid secretion; a sac, vesicle, or bladder. "In
      the lumen of the [cyst]s , eosinophilic or blue secretions were
      frequently seen, with sometimes targetoid secretion."

   A [cyst] is a small growth that forms in the body. That squishy,
   fluid-filled mass on your calf could be a [cyst].

   The word [cyst] entered English in the 18th century by way of the
   Latin word [cyst]is, tracing all the way back to the Greek word
   kustis, meaning “bladder.” Like your bladder, a [cyst] is sort of like
   a small pouch, one that’s typically filled with liquid. Unlike the
   bladder, however, a [cyst] is closed, meaning the liquid can’t get
   out. A [cyst] is often an abnormal formation in the body, so doctors
   often remove them.

   They spend the winter deep in the snowpack, atop last summer’s snow,
   as dormant [cyst]s.

* rivulet                                                                :NY:
  [2017-09-22 Fri 21:24]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       bc531a96-80af-4806-9377-1193074dde7a
   :END:
   rivulet

*** --->
    речушка

    noun
    1. речушка (rivulet)
    2. ручей (stream, creek, brook, rivulet, groove, watercourse)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       592d7fa6-36b1-497b-a1e0-8b964e3d8e07
   :END:

   noun
   1. a very small stream. "sweat ran in [rivulet]s down his back"

   A [rivulet] is a small stream. A [rivulet] is to a river as a baby is to
   an adult.

   There are several ways to remember this word. One is the similarity
   of its sound to "river." Another is the suffix -let, which indicates
   small things. For example, a piglet is a small pig or baby pig. A
   300-pound pig probably wouldn't drown in a tiny [rivulet], but a
   piglet should stay clear. Another word for [rivulet] is "streamlet."

   This creates what scientists call pink snow or watermelon
   snow—drifts and glaciers that look like Slush Puppies and eventually
   reduce to [rivulet]s of crimson.

* crimson :NY:
  [2017-09-22 Fri 21:25]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       ca7b05c3-70f0-4207-b922-e8dc203458dd
   :END:
   crimson

*** --->
    малиновый

    adjective
    1. малиновый (crimson)
    2. пунцовый (crimson)
    3. темно-красный (dark-red, murrey, crimson, mulberry, wine-colored,
       wine-coloured)

    noun
    1. малиновый цвет (crimson)
    2. багрянец (purple, crimson, blush)
    3. румянец (blush, glow, flush, color, bloom, crimson)

    verb
    1. окрашивать в малиновый цвет (crimson)
    2. окрашиваться в малиновый цвет (crimson)
    3. краснеть (blush, redden, flush, color, crimson, color up)
    4. покрываться румянцем (crimson, suffuse)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       090c2d10-11d5-4166-9e8d-8fa8f740ff40
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:06]
   :END:

   adjective
   1. of a rich deep red color inclining to purple. "she blushed
      [crimson] with embarrassment"

   verb
   1. (of a person's face) become flushed, especially through
      embarrassment. "my face [crimson]ed and my hands began to shake"

   noun
   1. a rich deep red color inclining to purple. "The artist's palette
      encompasses earthy, weather worn colours, rich burnished [crimson]s
      and flashes of red."


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       1f0eb412-104f-4a31-b597-6d057324b660
   :END:
   [Crimson] is a deep, vivid shade of red. You could describe flowers,
   blood, or blushing cheeks as [crimson].
** >>>                                                                :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :ID:       7ec6b40f-b798-424e-9437-f52ba279ec96
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 2.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:28]
   :END:
   The ruby red color [crimson] shows up brilliantly in nature, in the
   form of flowers, birds, and insects. In fact, it was an insect that
   led to the word [crimson] in the first place; an insect called kermes
   was used for centuries to make a deep red dye, which was called
   cremesin in Old Spanish and eventually became [crimson].
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       bc500d54-a97e-4d0d-b5af-cf1b10686fd7
   :END:
   This creates what scientists call pink snow or watermelon
   snow—drifts and glaciers that look like Slush Puppies and eventually
   reduce to rivulets of [crimson].

* thirsty :NY:
  [2017-09-22 Fri 21:26]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       3bba6f09-6566-4f40-a62a-45f35fba511c
   :END:
   thirsty

*** --->
    жаждущий

    adjective
    1. жаждущий (thirsty, hungry, desirous, emulous, zealous, panting)
    2. томимый жаждой (thirsty, parched, athirst)
    3. иссохший (thirsty, exsiccated)
    4. вызывающий жажду (thirsty)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       0de6800e-80f9-44a0-bee9-41cfc1f7b332
   :END:

   adjective
   1. feeling a need to drink something. "the hikers were hot and
      [thirsty]"

   When you're thirty, you crave liquids. [Thirsty] people want a drink.

   To be [thirsty] is to feel like you need to drink something. People
   tend to get more [thirsty] on very hot days or during exercise, when a
   lot of their body's fluid is being sweated out. Eating can also make
   you [thirsty], and so can waking up in the morning. The word [thirsty]
   comes from the Proto-Indo-European root ters, or "dry."

   It’s like if you were out camping and your water bottle was frozen,
   you’d be [thirsty] until it melted.”

* keen :NY:
  [2017-09-22 Fri 21:28]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       b57d47fe-2289-45d5-a89a-4fd9c965fab6
   :END:
   keen

*** --->
    острый

    adjective
    1. острый (acute, sharp, keen, spicy, poignant, pointed)
    2. проницательный (discerning, penetrating, shrewd, astute,
       perspicacious, keen)
    3. сильный (strong, keen, powerful, severe, heavy, hard)
    4. тонкий (thin, fine, subtle, small, slim, keen)
    5. сильно желающий (keen, eager, hungry, anxious, longing)
    6. глубокий (deep, profound, thorough, rich, keen, sound)
    7. стремящийся (aspiring, eager, anxious, keen, endeavoring,
       solicitous)
    8. резкий (cutting, sharp, abrupt, harsh, severe, keen)
    9. обостренный (keen)
    10. энергичный (vigorous, energetic, spirited, strenuous, dynamic,
	keen)
    11. пронзительный (piercing, shrill, shrilly, penetrating, sharp,
	keen)
    12. ревностный (zealous, earnest, ardent, jealous, keen, intense)
    13. напряженный (tense, strained, intense, stressful, strenuous,
	keen)
    14. строгий (strict, stringent, rigorous, severe, stern, keen)
    15. трудный (difficult, hard, tough, tight, arduous, keen)
    16. интенсивный (intensive, intense, high, crash, rich, keen)
    17. трескучий (keen)
    18. жестокий (cruel, brutal, fierce, severe, ruthless, keen)
    19. низкий (low, lower, poor, deep, short, keen)
    20. сниженный (reduced, discounted, lowered, cut, depressed, keen)

    verb
    1. голосить (keen)
    2. причитать (wail, keen, snivel)

    noun
    1. плач по покойнику (keen)
    2. причитание по покойнику (keen)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       005fb5e2-1ecb-4000-ae95-43dfe27586f4
   :END:

   adjective
   1. having or showing eagerness or enthusiasm. "[keen] believers in the
      monetary system"
   2. sharp or penetrating, in particular. "St. John has a particularly
      roman face and expression, a sharp nose and a [keen] ability to
      perceive the interior state of his subject, at all costs."
   3. excellent. "I would soon fly to distant stars—how [keen]!"
   4. (of prices) very low; competitive. "Most well-run companies will
      have mainstream costs under control and will have professional
      buyers negotiating [keen] prices for all raw materials."

   verb
   1. wail in grief for a dead person; sing a [keen]. "She could hear
      voices speaking in soothing tones, but Anna [keen]ed and wailed,
      and Kathleen tried not to imagine the scene on the other side of
      the door."

   noun
   1. an Irish funeral song accompanied by wailing in lamentation for
      the dead.

   If you have a [keen] interest in something, you are really, really
   into it. [Keen] is an adjective that describes something that is
   intense, sharp, or focused.

   The adjective [keen] comes from the Old English word cene that
   translates to "bold and brave" and while the spelling is now really
   different, the sounds are similar. Variations of [keen] as being
   "bold" and "strong" show up in other languages like Old Norse,
   German, Dutch, but apparently only English has the meaning of
   "sharp" — relating to "an edge or blade." [Keen] has a lot of close —
   and brutal — synonyms, such as caustic, cutting, piercing, and
   penetrating!

   Snow algae have since drawn the attention of climate scientists and
   of biologists [keen] to understand the conditions under which life
   might develop on other planets.



* rage                                                                :Twain:
  [2017-09-30 Sat 15:51]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       500bf2b8-b08d-4ea1-ba37-d2b97c17abfa
   :END:
   rage

*** --->
    ярость

    noun
    1. ярость (fury, rage, anger, wrath, ire, rampage)
    2. гнев (anger, wrath, rage, fury, ire, passion)
    3. раж (rage)
    4. бешенство (rabies, rage, fury, frenzy, furiousness, madness)
    5. неистовство (fury, frenzy, rage, raving, rampage, violence)
    6. мода (fashion, mode, vogue, style, craze, rage)
    7. повальное увлечение (craze, rage, bandwagon)
    8. увлечение (enthusiasm, passion, interest, devotion, crush, rage)
    9. страсть (passion, desire, lust, love, ardor, rage)
    10. общее увлечение (rage)
    11. приступ сильного гнева (rage)
    12. сильное стремление (longing, rage)
    13. вспышка (flash, outbreak, flare, outburst, burst, rage)
    14. предмет общего увлечения (rage)

    verb
    1. бушевать (rage, storm, bluster, rave, ramp, tear)
    2. свирепствовать (rage, storm)
    3. беситься (rage, rave about)
    4. психовать (rage, rave about)
    5. злиться (rage, peeve)
    6. неистовствовать (rampage, rage, rave, tear, ramp, be on the
       rampage)
    7. яриться (rage, be in heat)
    8. бесноваться (rage, rave about, maffick)
    9. войти в раж (rage)
    10. разбушеваться (rage, storm, rave)
    11. веселиться (rejoice, joy, make merry, celebrate, jollify, rage)
    12. кутить (carouse, revel, dissipate, rage)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       fd428acc-cf3b-470d-be0d-eac45c943e20
   :END:

   noun
   1. violent, uncontrollable anger. "her face was distorted with [rage]"

   verb
   1. feel or express violent uncontrollable anger. "he [rage]d at the
      futility of it all"



   THEY swarmed up towards Sherburn's house, a-whooping and [raging]
   like Injuns, and everything had to clear the way or get run over
   and tromped to mush, and it was awful to see.


* tromp                                                               :Twain:
  [2017-09-30 Sat 15:52]

** ==>                                                                :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       258fea30-2abd-4d0b-8c9d-583cbd8314a7
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:03]
   :END:
   tromp

*** --->
    топать

    verb
    1. топать (stomp, stamp, tromp, clatter along, drub, drum)
    2. идти топоча (tromp)
    3. затаптывать (tread down, tromp, tread out)
    4. насмехаться (mock, taunt, scoff, razz, sneer, tromp)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       6d4a5524-cbcb-429b-ad00-ca368e2357be
   :END:

   verb
   1. walk heavily; trudge. "she [tromp]ed across the yard"


   THEY swarmed up towards Sherburn's house, a-whooping and raging like
   Injuns, and everything had to clear the way or get run over and
   [tromp]ed to mush, and it was awful to see.

* mush :Twain:
  [2017-09-30 Sat 15:53]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       01e6959f-4737-4351-ba46-a792892d7948
   :END:
   mush

*** --->
    кашица

    noun
    1. кашица (gruel, paste, mush, pulp, squash, pap)
    2. слащавость (mush, rosewater, treacle)
    3. помехи (interference, stray, mush)
    4. чепуха (nonsense, stuff, crap, applesauce, malarkey, mush)
    5. маисовая каша (mush, samp)
    6. сантименты (sentimentality, mush, slop)
    7. вздор (nonsense, blah, rubbish, baloney, humbug, mush)
    8. радиопомехи (mush)
    9. зонтик (umbrella, parasol, umbel, gingham, brolly, mush)
    10. путешествие с собаками (mush)
    11. что-либо мягкое (mush)

    verb
    1. путешествовать с собаками (mush)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       9f569162-6f1f-42ad-b1c0-2ec13146eb01
   :END:

   noun
   1. a soft, wet, pulpy mass. "red lentils cook quickly and soon turn
      to [mush]"
   2. feeble or cloying sentimentality. "the film's not just romantic
      [mush]"
   3. a journey across snow with a dogsled. "a twelve-day [mush]"

   verb
   1. reduce (a substance) to a soft, wet, pulpy mass. "simmer until
      the apples and potatoes are tender but not [mush]ed"
   2. go on a journey across snow with a dogsled. "by the end of winter
      he will have snowshoed up to 700 miles and [mush]ed about the same"

   exclamation
   1. a command urging on dogs pulling a sled during a journey across
      snow.

   [Mush] is a soft, squishy clump of something. That bowlful of [mush]
   your grandfather gave you for breakfast might be oatmeal.

   [Mush] is a soggy mass, and cornmeal [mush] is a kind of porridge that
   fits this description. [Mush] is also something so overly sentimental
   that it's almost disgusting: "Oh, that movie was terrible, just a
   bunch of romantic [mush]!" When you use [mush] as a verb or an
   exclamation, it's usually in the context of dogsledding, meaning
   "Go!" or "Move forward!" This last meaning comes from the French
   marche, "walk" or "go."

   THEY swarmed up towards Sherburn's house, a-whooping and raging like
   Injuns, and everything had to clear the way or get run over and
   tromped to [mush], and it was awful to see.

* wench                                                               :Twain:
  [2017-09-30 Sat 15:53]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       74850cce-7688-466e-a785-0db7c51815b0
   :END:
   wench

*** --->
    девка

    noun
    1. девка (wench, broad, tit, hussy, baggage, bag)
    2. девушка (girl, lady, maiden, lass, maid, wench)
    3. телка (heifer, chick, tit, pigmeat, wench, slattern)
    4. молодая женщина (girl, quean, wench)

    verb
    1. распутничать (whore, wench, wanton, philander)
    2. ходить к проституткам (wench)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       5fa97925-7036-42f2-87b1-f1b30eea564e
   :END:

   noun
   1. a girl or young woman. "Before the night is out they will no
      doubt have all found the attentions of a pretty young serving
      [wench] ."

   verb
   1. (of a man) consort with prostitutes.

   [Wench] used to mean young girl, so if you find someone describing a
   lovely [wench] in Shakespeare, it means a lovely girl.

   [Wench] comes from Middle English, and was a common word for girl,
   child, or servant. Over time it came to mean mainly serving girls,
   as in a bar [wench], who serves drinks at a tavern. Eventually it came
   to mean prostitute. If you find [wench] in a love poem from the 16th
   century, think of it as an informal version of maiden. But if
   someone called you a [wench] last week, you should be insulted.

   Children was heeling it ahead of the mob, screaming and trying to
   get out of the way; and every window along the road was full of
   women's heads, and there was nigger boys in every tree, and bucks
   and [wench]es looking over every fence; and as soon as the mob would
   get nearly to them they would break and skaddle back out of reach.

* paling                                                              :Twain:
  [2017-09-30 Sat 15:54]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       e65c8f1b-ad25-4cbb-a3a6-f76a8a49ed69
   :END:
   paling

*** --->
    частокол

    noun
    1. частокол (stockade, palisade, paling, pale)
    2. забор (fence, fencing, palisade, paling)
    3. палисад (palisade, paling, zareba, zariba)
    4. кол (stake, pole, pale, pile, picket, paling)
    5. колья (paling, pegging)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       06350adf-753d-4267-86d5-090c1f57a7c2
   :END:

   noun
   1. a fence made from pointed wooden or metal stakes. "The post and
      wire fence at the end of the road needed attention - in the long
      term, a hedge, wooden [paling] or stone wall would be attractive if
      a replacement is considered."

   verb
   1. become pale in one's face from shock or fear. "I paled at the
      thought of what she might say"
   2. seem less impressive or important. "all else pales by comparison"



   They swarmed up in front of Sherburn's [paling]s as thick as they
   could jam together, and you couldn't hear yourself think for the
   noise.

* racket :Twain:
  [2017-09-30 Sat 15:55]

** ==>                                                                :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       dd07b30a-73b2-4d31-9f74-1aff048a668d
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 3.0
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 10:45]
   :END:
   racket

*** --->
    ракетка

    noun
    1. ракетка (racket, racquet, bat, battledore)
    2. рэкет (racket)
    3. шум (noise, sound, uproar, din, clamor, racket)
    4. вымогательство (extortion, blackmail, racketeering, racket,
       exaction, shakedown)
    5. гам (uproar, noise, hubbub, racket, clutter, hullabaloo)
    6. мошенничество (fraud, cheating, swindle, cheat, dishonesty,
       racket)
    7. шантаж (blackmail, intimidation, racket, squeeze, chantage)
    8. обман (deception, deceit, fraud, trick, hype, racket)
    9. разгульный образ жизни (racket)
    10. комбинация (combination, slip, combs, racket)
    11. занятие (employment, occupation, class, exercise, business,
	racket)
    12. работа (working, work, job, operation, labor, racket)

    verb
    1. вести шумный образ жизни (racket, racket about)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       3aa92424-e68b-4818-a5dc-29194297ec0d
   :END:

   noun
   1. a type of bat with a round or oval frame strung with catgut,
      nylon, etc., used especially in tennis, badminton, and squash.
      "Anyway, I can't just go to some tennis court with my racquet and
      balls, I need someone to play with and that's why I need a club."
   2. a loud unpleasant noise; a din. "the kids were making a [racket]"
   3. an illegal or dishonest scheme for obtaining money. "a protection
      [racket]"

   verb
   1. make a loud unpleasant noise. "trains [racket]ed by"

   If you're carrying a [racket] and wearing a sporty visor, people will
   guess that you're on your way to play tennis. A [racket] has a handle
   and a rounded frame laced with strings, and it's used to hit a ball.

   A [racket] is used to play tennis, badminton, or squash, and it can
   also be spelled racquet. Another definition of [racket] is an
   unpleasantly loud noise; if your neighbors were playing horrible,
   loud music, you could yell out the window, "Stop that [racket]!"
   Informally, the word [racket] also means "illegal scheme," especially
   for making money. The French word requette means "palm of the hand,"
   and racquet originally referred to a tennis-like game played by
   hitting a ball with the hand.

   Then there was a [racket] of ripping and tearing and smashing, and
   down she goes, and the front wall of the crowd begins to roll in
   like a wave.

* porch :Twain:
  [2017-09-30 Sat 15:55]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       547328c5-290c-4fc0-9ff7-96f65391170a
   :END:
   porch

*** --->
    крыльцо

    noun
    1. крыльцо (porch)
    2. веранда (veranda, verandah, porch, terrace, piazza, stoop)
    3. подъезд (porch)
    4. терраса (terrace, veranda, porch, verandah, bench)
    5. паперть (porch, parvis, church-porch)
    6. портик (portico, porch, gallery)
    7. балкон (balcony, porch, gallery, upper circle, family circle)
    8. крытая галерея (porch)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       2ff52521-b987-463b-874d-a161afc77216
   :END:

   noun
   1. a covered shelter projecting in front of the entrance of a
      building. "There is a covered [porch] and two front doors to the
      dwelling and an arched entrance at the side."



   Just then Sherburn steps out on to the roof of his little front
   [porch], with a double-barrel gun in his hand, and takes his stand,
   perfectly ca'm and deliberate, not saying a word.

* pluck :Twain:
  [2017-09-30 Sat 15:57]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       1864b4c5-9459-4a66-8eca-089bee849ab2
   :END:
   pluck

*** --->
    срывать

    verb
    1. ощипывать (pluck, plume, pick, nip off)
    2. срывать (tear, pluck, tear off, frustrate, disrupt, pick)
    3. щипать (tweak, pluck, pinch, nip, bite, tingle)
    4. проваливать (get out, defeat, naff, pluck)
    5. собирать (collect, gather, pick, assemble, congregate, pluck)
    6. выдергивать (pull, pluck, pull up, twitch from, draw, pick out)
    7. общипывать (pluck)
    8. перебирать (sort out, pluck, look over, handle, travel)
    9. обирать (fleece, despoil, pick, pluck, shave, pill)
    10. обманывать (deceive, cheat, kid, fool, spoof, pluck)

    noun
    1. смелость (courage, boldness, daring, audacity, confidence, pluck)
    2. ливер (pluck)
    3. мужество (courage, bravery, guts, fortitude, virility, pluck)
    4. потроха (offal, pluck, bejesus, chitterlings, harslet, haslet)
    5. отвага (courage, daring, valor, prowess, heart, pluck)
    6. дерганье (pull, wrench, pluck, yank, lug)
    7. провал (failure, fail, collapse, failing, flop, pluck)
    8. дергающее усилие (pluck, tug)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       3f335629-c91f-43b7-939a-b41d69e57afc
   :END:

   noun
   1. spirited and determined courage. "And when I was here a few weeks
      ago, I met with a number of those families, and I was impressed
      by their [pluck] , their spirit."
   2. the heart, liver, and lungs of an animal as food. "Put the [pluck]
      into cold salted water, boil, then skim and simmer for 1 hour."

   verb
   1. take hold of (something) and quickly remove it from its place;
      pick. "she [pluck]ed a blade of grass"
   2. quickly or suddenly remove someone from a dangerous or unpleasant
      situation. "the baby was [pluck]ed from a grim foster home"
   3. sound (a musical instrument or its strings) with one's finger or
      a plectrum. "I sat with the lute in my lap, trying to reach for
      forgotten notes as my fingers [pluck]ed the strings."

   To [pluck] is to pick or pull a single item out of many, like a flower
   or a hair. As a noun, [pluck] is energy or enthusiasm, even when
   things are looking grim.

   Don't [pluck] only the best cherries off the tree: that's
   cherry-picking! Before you cook a goose, you need to [pluck] its
   feathers. If it looks like your goose is cooked, however, then show
   some [pluck], and figure out a way to save yourself. Some characters
   who are famous for showing [pluck] include the Artful Dodger, Little
   Orphan Annie, and Benji the dog. They all kept their chins up and
   kept on trying, even when things looked really dark.

   The idea of you thinking you had [pluck] enough to lynch a man!

* acquit :Twain:
  [2017-09-30 Sat 16:00]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       cbb43b88-aae3-4a55-ae0f-df56d27cfe2b
   :END:
   acquit

*** --->
    оправдать

    verb
    1. оправдывать (justify, warrant, defend, excuse, acquit, explain)
    2. освобождать (rid, free, exempt, release, loose, acquit)
    3. выполнять (perform, carry out, fulfill, execute, do, acquit)
    4. выплатить долг (acquit)
    5. вести себя (behave, act, do, conduct oneself, carry, acquit)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       b1ccbcbb-2bc3-4aa3-8625-fe046e9f4785
   :END:

   verb
   1. free (someone) from a criminal charge by a verdict of not guilty.
      "she was [acquit]ted on all counts"
   2. conduct oneself or perform in a specified way. "all the young
      women in the contest [acquit]ted themselves well"

   To [acquit] someone is to clear them of charges. [Acquit]ting also has
   to do with how you carry or present yourself.

   If you're accused of a crime, then the best thing that can happen to
   you is being [acquit]ted — that means you were cleared or exonerated
   of the charges. A defense lawyer wants to have his client [acquit]ted.
   But watch out for another unrelated meaning: [acquit]ting can mean how
   you behave, conduct, or carry yourself. If you [acquit] yourself like
   a champion, then you're acting like a champion.

   "So they always [acquit]; and then a man goes in the night, with a
   hundred masked cowards at his back and lynches the rascal.

* rascal :Twain:
  [2017-09-30 Sat 16:00]

** ==>                                                                :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       f52f036c-94bb-4f5a-9d3a-dcade571be7f
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 4.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 10:52]
   :END:
   rascal

*** --->
    мошенник

    noun
    1. негодяй (scoundrel, villain, rascal, wretch, rogue, knave)
    2. мошенник (rogue, swindler, fraud, rascal, impostor, knave)
    3. плут (rogue, rascal, cheat, knave, crook, juggler)
    4. каналья (rascal)
    5. шельма (rascal, rogue, scoundrel)
    6. шельмец (rascal, bugger)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       3e72845d-cabd-4cad-8aa3-188c5e34ca99
   :END:

   noun
   1. a mischievous or cheeky person, especially a child or man
      (typically used in an affectionate way). "As a result, liars are
      passed off as scoundrels or [rascal]s , or even lovable rogues."

   A [rascal] is a scoundrel or a trickster. If your new puppy cheerfully
   chews on your shoes and chases the cat, you might want to consider
   naming her [Rascal].

   [Rascal]s are mischievous, but their intentions are to have fun,
   rather than to be cruel. An armed robber is not a [rascal], but the
   class clown is a [rascal]. The word's origins had a more negative
   connotation, though: the fourteenth century rascaile meant "low
   class people," from the Old French rascaille, "rabble or mob."

   "So they always acquit; and then a man goes in the night, with a
   hundred masked cowards at his back and lynches the [rascal].

* pitiful :Twain:
  [2017-09-30 Sat 16:01]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       05783e18-1f92-4f32-894b-c1d0d5e822b5
   :END:
   pitiful

*** --->
    жалкий

    adjective
    1. жалкий (pitiful, miserable, pathetic, sorry, wretched, pitiable)
    2. жалостливый (compassionate, pitiful)
    3. несчастный (unhappy, miserable, unfortunate, poor, wretched,
       pitiful)
    4. жалостный (pathetic, pitiful)
    5. презренный (despicable, contemptible, abject, pitiful, paltry,
       picayune)
    6. сострадательный (compassionate, merciful, pitiful, compassive)
    7. ничтожный (insignificant, paltry, little, small, puny, pitiful)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       ba658248-a28e-410c-9791-89a122b33ed6
   :END:

   adjective
   1. deserving or arousing pity. "It makes us look [pitiful] and pity is
      not something that we want, we want respect."

   [Pitiful] means pathetic. If you don't even study for your test,
   you're making a pretty [pitiful] effort to do well.

   The word [pitiful] can be used in a range of contexts. Most commonly,
   you'll see it used as an expression of contempt and pity, the way
   the word pathetic might be used. You might also see it used in
   reference to something unfortunate or deserving of pity — like a
   homeless mother and her child, begging for money on the street.
   Something [pitiful] might also be something very small or inadequate.
   A [pitiful] attempt, is one that isn't good enough.

   The [pitiful]est thing out is a mob; that's what an army is—a mob;
   they don't fight with courage that's born in them, but with courage
   that's borrowed from their mass, and from their officers.

* droop :Twain:
  [2017-09-30 Sat 16:02]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       269a1725-519d-4176-a392-28b34c9c0aea
   :END:
   droop

*** --->
    свисать

    verb
    1. свисать (hang, droop, hang down, dangle, sag, trail)
    2. потупить (droop)
    3. виснуть (hang on, droop, cling to)
    4. клониться к закату (droop)
    5. поникать (droop, wilt)
    6. наклонять (cant, tilt, lean, bend, tip, droop)
    7. вешать (hang, weigh, suspend, drape, swing, droop)
    8. понурить (droop)
    9. склоняться (incline, decline, trend, vail, droop)
    10. спускаться (get down, descend, go down, come down, fall, droop)
    11. сползать (slip down, droop)
    12. ослабевать (wane, fail, abate, ease up, fall off, droop)
    13. увядать (fade, wither, droop, rot off, die down, die away)
    14. изнемогать (pine, droop, pine away)
    15. унывать (despond, be depressed, be cast down, droop, hang down
	one's head)
    16. падать духом (collapse, despond, droop, crumple)
    17. опускаться (go down, descend, fall, drop, sink, droop)

    noun
    1. наклон (incline, lean, tilt, slope, inclination, droop)
    2. понижение (decrease, reduction, drop, falling, degradation,
       droop)
    3. изнеможение (exhaustion, prostration, collapse, droop)
    4. сутулость (slouch, stoop, droop, round shoulders, round back)
    5. поникание (droop)
    6. упадок духа (discouragement, despondency, depression, despond,
       droop, regression)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       38f18f69-83e9-45db-b2fd-f530d7c83862
   :END:

   noun
   1. an act or instance of [droop]ing; a limp or weary attitude. "the
      exhausted [droop] of her shoulders"

   verb
   1. bend or hang downward limply. "a long black cloak [droop]ed from
      his shoulders"

   To [droop] is to limply or loosely hang downward. Have you ever seen
   the long, floppy ears of a basset hound hanging down? Those ears are
   [droop]ing.

   When things [droop], they're loose and hanging down. On a day without
   wind, a flag will [droop]. If you are sad or embarrassed, your head
   might [droop] a little. Evidently, [droop]ing your head when you’re
   feeling down is something people have been doing for a long time.
   [Droop] is also related to the words drop and drip.

   Now the thing for you to do is to [droop] your tails and go home and
   crawl in a hole.

* toss                                                                :Twain:
  [2017-09-30 Sat 16:03]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       d4224cb7-fd2a-4018-b87c-8892c7d14079
   :END:
   toss

*** --->
    бросать

    verb
    1. бросать (throw, cast, drop, quit, toss, fling)
    2. вскидывать (throw up, toss, cast up)
    3. подниматься и опускаться (heave, toss)
    4. кидать (throw, toss, fling, cast, shoot, pitch)
    5. швырять (toss, throw, fling, hurl, slam, sling)
    6. поднимать на рога (toss)
    7. сбрасывать (discard, drop, shed, dump, throw, toss)
    8. отбрасывать (cast, reject, discard, throw, cast aside, toss)
    9. носиться (wear, scamper, toss, scamper about, play, skirr)
    10. беспокойно метаться (toss, toss about)
    11. разметаться (toss)
    12. реять (toss, flaunt)
    13. промывать руду (jig, toss, hutch)

    noun
    1. жеребьевка (draw, toss, drawing, sortition, ballot, toss of the
       coin)
    2. бросание (throwing, cast, toss, casting, throw, fling)
    3. толчок (push, impetus, impulse, thrust, kick, toss)
    4. подбрасывание монеты (toss, toss-up)
    5. метание (throw, casting, projection, dart, toss, jactitation)
    6. сотрясение (shake, concussion, shaking, shock, jar, toss)
    7. падение (drop, fall, incidence, falling, decline, toss)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       84a1a2e9-8c9a-48f6-9ec4-c2367e68c8fe
   :END:

   noun
   1. an action or instance of [toss]ing something. "a defiant [toss] of
      her head"

   verb
   1. throw (something) somewhere lightly, easily, or casually. "Suzy
      [toss]ed her bag onto the sofa"
   2. search (a place). "I could demand her keys and [toss] her office"

   When you lightly throw something, you [toss] it. You might [toss] your
   lifejacket and backpack into a canoe before climbing in with the
   paddles.

   You can [toss] a baseball to your friend in the backyard, or [toss] your
   trash in a wastebasket when you're finished with lunch. You can also
   [toss] a coin or [toss] a salad. Another way to [toss] is to move back and
   forth — or thrash — like an insomniac in bed or a boat on a stormy
   ocean.

   Now leave—and take your half-a-man with you"—[toss]ing his gun up
   across his left arm and cocking it when he says this.

* cheap :Twain:
  [2017-09-30 Sat 16:04]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       b87e1dbd-26d8-44db-a9d2-df9e0cf0de6f
   :END:
   cheap

*** --->
    дешево

    adverb
    1. дешево (cheap, cheaply, low, inexpensively, at a low figure, at
       an easy rate)

    adjective
    1. дешевый (cheap, inexpensive, tatty, dime, sixpenny, gimcrack)
    2. низкий (low, lower, poor, deep, short, cheap)
    3. плохой (bad, poor, ill, low, inferior, cheap)
    4. легкий (easy, light, lightweight, slight, mild, cheap)
    5. подлый (vile, sneaky, despicable, dastardly, mean, cheap)
    6. доставшийся легко (cheap, runaway)
    7. обесцененный (cheap, at a discount)
    8. матерный (obscene, abusive, foul, worthless, cheap)
    9. сраный (shitty, crappy, covered with shit, cheap)

    noun
    1. дешевка (cheap, sleaze, cheap whore, bargain basement rates)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       6762ab8b-3918-4e95-8ca4-a8784d4fac86
   :END:

   adjective
   1. (of an item for sale) low in price; worth more than its cost.
      "they bought some [cheap] fruit"

   adverb
   1. at or for a low price. "a house that was going [cheap]"

   Something [cheap] doesn't cost much money. But watch out, because
   [cheap] things are also often [cheap]ly made.

   When prices are low, they're [cheap]: that's a good thing. However,
   this word is often an insult. Hitting someone who isn't looking is a
   [cheap] shot. Things that aren't very well made and use low-quality
   materials are [cheap]. When someone — especially a woman — is dressed
   in a trashy way, people say "You look [cheap]!" And if you have a
   stingy Uncle Scrooge in your family, you can call him [cheap] or even
   a [cheap]skate.

   The crowd washed back sudden, and then broke all apart, and went
   tearing off every which way, and Buck Harkness he heeled it after
   them, looking tolerable [cheap].

* bully :Twain:
  [2017-09-30 Sat 16:05]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       378a5a58-80f8-436b-acf5-77aeff870d78
   :END:
   bully

*** --->
    задира

    noun
    1. хулиган (bully, hooligan, hoodlum, ruffian, tough, rowdy)
    2. задира (bully, teaser, tease, rooster, bantam, scrapper)
    3. забияка (bully, rooster, blusterer, hothead, bantam, cock)
    4. хвастун (braggart, bouncer, boaster, blowhard, braggadocio,
       bully)
    5. сутенер (souteneur, ponce, bully, gigolo, cadet)
    6. мясные консервы (bully beef, potted meat, bully, army beef)

    verb
    1. запугивать (intimidate, bully, cow, browbeat, bluff, daunt)
    2. задирать (lift up, bully, pull up, huff, hector, ruffle)
    3. задрать (screw up, bully, pester, bug)

    adjective
    1. великолепный (great, sumptuous, gorgeous, magnificent, excellent,
       bully)
    2. первоклассный (classy, superfine, topnotch, crack, exclusive,
       bully)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       f766b5d3-e886-4623-abd8-d1607e0340d3
   :END:

   noun
   1. a person who uses strength or power to harm or intimidate those
      who are weaker. "If we can all come together to make our parks
      safe, and we can all support zero tolerance in schools so that
      our children can enjoy a good education free from fear,
      intimidation and bullies , then we can surely do the same for our
      roads."
   2. corned beef. "She opened the back door only to see thrown down on
      the lawn an empty can of her [bully] beef and, to make matters
      worse, an empty tin of her cat's food!"

   verb
   1. use superior strength or influence to intimidate (someone),
      typically to force him or her to do what one wants. "a local man
      was bullied into helping them"

   adjective
   1. very good; first-rate. "the statue really looked [bully]"

   exclamation
   1. an expression of admiration or approval. "he got away—[bully] for
      him"

   You might still have terrifying dreams about the [bully] who harassed
   you on the playground in second grade. A [bully] is someone who
   intimidates people, usually those who are weaker or smaller.

   The classic example of a [bully] is a mean kid in a schoolyard who
   hassles or beats up younger students. While a child or a teenager
   can be a [bully], so is anyone who uses power or strength to scare or
   harm other people. The word [bully] has gone through a mysterious
   evolution, from the 1530s when it meant "sweetheart," through the
   17th century's meanings of "fine fellow," then "blusterer," and
   finally "harasser of the weak."

   It was a real [bully] circus.

* splendid                                                            :Twain:
  [2017-09-30 Sat 16:06]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       26b1fb71-92c7-418b-b284-37f6cc5ae39d
   :END:
   splendid

*** --->
    великолепный

    adjective
    1. великолепный (great, sumptuous, gorgeous, magnificent, excellent,
       splendid)
    2. роскошный (luxurious, sumptuous, splendid, deluxe, palatial,
       rich)
    3. замечательный (remarkable, wonderful, great, admirable,
       marvelous, splendid)
    4. превосходный (excellent, superb, superior, superlative, fine,
       splendid)
    5. блестящий (brilliant, shiny, shining, bright, glossy, splendid)
    6. отличный (great, excellent, cool, splendid, classy, super)
    7. первоклассный (classy, superfine, topnotch, crack, exclusive,
       splendid)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :ID:       98d9081e-27fd-4d4b-8ed5-40a4bca152ea
   :DRILL_LAST_INTERVAL: 4.14
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 5.0
   :DRILL_EASE: 2.6
   :DRILL_LAST_QUALITY: 5
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:15]
   :END:

   adjective
   1. magnificent; very impressive. "a [splendid] view of Windsor Castle"


** >>>                                                                :drill:
   Looking truly magnificent today? Then someone (probably British)
   might stop you to say "Wow! You look [splendid], darling!" Thanks the
   person, because [splendid] means glorious, fabulous, wonderful, and/or
   splendiferous.
** >>>                                                                :drill:
   Use the adjective [splendid] to describe something of the highest
   quality. If you're so lucky as to have someone buy you, say, a Harry
   Winston diamond, [splendid]! But [splendid] doesn't apply only to
   expensive items such as jewelry, clothing, or art. You can also have
   a [splendid] idea, morning walk, or encounter with an old friend. For
   some, using Splenda in their coffee instead of sugar is, for them,
   well, [splendid]!
** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide1cloze
   :END:

   It was the [splendid]est sight that ever was when they all come
   riding in, two and two, a gentleman and lady, side by side, the men
   just in their drawers and undershirts, and no shoes nor stirrups,
   and [resting] their hands on their thighs easy and comfortable —
   there must a been twenty of them—and every lady with a lovely
   complexion, and perfectly beautiful, and looking just like a gang
   of real sure-enough queens, and dressed in clothes that [cost]
   millions of dollars, and just [litter]ed with diamonds.

* rest                                                                :Twain:
  [2017-09-30 Sat 16:06]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       8b575f87-d1b3-4264-aace-2b8ebb65afef
   :END:
   rest

*** --->
    отдых

    noun
    1. отдых (rest, recreation, relaxation, refreshment, repose,
       comfort)
    2. остальные (rest)
    3. остальное (rest, remain)
    4. остаток (residue, balance, remainder, rest, remnant, residual)
    5. покой (peace, rest, quiet, comfort, repose, quietness)
    6. другие (rest)
    7. упор (stop, thrust, rest, detent, pawl, catch)
    8. опора (support, prop, reliance, bearing, mainstay, rest)
    9. перерыв (break, interruption, pause, interval, rest,
       intermission)
    10. пауза (pause, break, interval, rest, stop, hold)
    11. подставка (stand, rack, pedestal, support, coaster, rest)
    12. сон (sleep, dream, sleeping, slumber, rest, repose)
    13. передышка (respite, truce, breathing space, reprieve, rest,
	pause)
    14. место отдыха (rest, resting-place)
    15. неподвижность (immobility, stillness, stiffness, immovability,
	quiescence, rest)
    16. суппорт (support, carriage, saddle, rest)
    17. вечный покой (rest)
    18. смерть (death, dying, demise, end, passing, rest)
    19. стойка (rack, stand, counter, bar, pillar, rest)
    20. база отдыха (recreation center, rest)
    21. подпорка (prop, support, brace, post, stanchion, rest)
    22. цезура (caesura, pause, rest, break)
    23. резервный фонд (reserve, rest)

    verb
    1. отдыхать (rest, relax, vacation, holiday, repose, take a rest)
    2. покоиться (rest, repose, sleep)
    3. опираться (lean, rest, be based, bear, abut, recline)
    4. лежать (lie, lay, rest, lie with, couch, lie up)
    5. оставаться (stay, remain, continue, keep, stay on, rest)
    6. спать (sleep, bed, rest, be asleep, slumber, do)
    7. основываться (found, build, rest, bottom, lean, repose)
    8. держаться (keep, hold, hold on, stick, stand, rest)
    9. оставаться спокойным (rest)
    10. давать покой (rest)
    11. возлагать (lay, place, rest, entrust, put on, intrust)
    12. давать отдых (rest, unbend, repose)
    13. не волноваться (rest)
    14. класть (put, place, lay, deposit, rest, set)
    15. прислонять (rest, put)
    16. держать (keep, hold, carry, rest, keep hold of, stand by)
    17. основывать (base, found, establish, rest, ground, set up)
    18. быть возложенным (rest)
    19. быть прикованным (rest)
    20. оставаться без изменений (rest)
    21. оставаться под паром (rest)
    22. находиться под паром (rest)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       c705ef1d-68c1-4f92-bd54-96820927b732
   :END:

   noun
   1. an instance or period of relaxing or ceasing to engage in
      strenuous or stressful activity. "you look as though you need a
      [rest]"
   2. an object that is used to support something. "a chin-[rest]"
   3. the remaining part of something. "what do you want to do for the
      [rest] of your life?"

   verb
   1. cease work or movement in order to relax, refresh oneself, or
      recover strength. "he needed to [rest] after the feverish activity"
   2. be placed or supported so as to stay in a specified position.
      "her elbow was [rest]ing on the arm of the sofa"
   3. remain or be left in a specified condition. "you can [rest] assured
      she will do everything she can to help her"

   To [rest] means to relax into something and let it support you. [Rest]
   yourself on the couch for a while, if you're tired.

   The word [rest] comes from the German rasta meaning "league of miles."
   If you walked that far, you'd need a good [rest] too. Whatever way you
   choose to use the word [rest] — whether it's something you do,
   something you take, or something you put your arm up on — you're
   describing a moment of stillness and calm. [Rest] also means "the
   stuff left over." Who will eat the [rest] of the cookies when you have
   to [rest] from eating so many of them?

   It was the splendidest sight that ever was when they all come riding
   in, two and two, a gentleman and lady, side by side, the men just in
   their drawers and undershirts, and no shoes nor stirrups, and
   [rest]ing their hands on their thighs easy and comfortable—there must
   a been twenty of them—and every lady with a lovely complexion, and
   perfectly beautiful, and looking just like a gang of real
   sure-enough queens, and dressed in clothes that cost millions of
   dollars, and just littered with diamonds.

* airy :Twain:
  [2017-09-30 Sat 16:07]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       350cabba-cd8e-4a76-8c96-f7b4eb18bfba
   :END:
   airy

*** --->
    воздушный

    adjective
    1. просторный (spacious, roomy, ample, airy, spacey, wide)
    2. воздушный (air, airy, aerial, overhead, light, ethereal)
    3. легкий (easy, light, lightweight, slight, mild, airy)
    4. полный воздуха (airy)
    5. грациозный (graceful, airy, slender, gracile, lightsome,
       sylphlike)
    6. легкомысленный (frivolous, careless, flippant, giddy,
       light-headed, airy)
    7. хорошо проветриваемый (airy)
    8. веселый (cheerful, merry, gay, glad, happy, airy)
    9. изящный (elegant, graceful, fine, delicate, neat, airy)
    10. ветреный (windy, flighty, giddy, flyaway, volatile, airy)
    11. пустой (empty, blank, vacant, unoccupied, idle, airy)
    12. эфирный (ethereal, aethereal, aerial, airy)
    13. заносчивый (arrogant, toplofty, airy, chesty, assuming,
	proud-spirited)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       5bf24dc4-9130-4721-9de1-e7503c990ae8
   :END:

   adjective
   1. (of a room or building) spacious, well lit, and well ventilated.
      "The old ginger wine storage facility has been divided into
      spacious, [airy] rooms with stylish features such as Spanish wood
      doors and window frames and brightly coloured original beams."
   2. giving an impression of being unconcerned or not serious,
      typically about something taken seriously by others. "her [airy]
      unconcern for economy"

   An [airy] place is full of fresh air. Other [airy] things are either
   light like air or without substance like air.

   Air surrounds us, and it has a lot of meanings. If a place is
   described as [airy], that means it's full of fresh air. An open
   stadium is [airy], while a stuffy apartment is not. If a house has
   lots of open windows, it's [airy]. Also, an argument that has no
   substance can be called [airy], because there's nothing to it. Light
   things are [airy] too: a flimsy, light dress or a low-fat dessert
   could both be called [airy].

   And then one by one they got up and stood, and went a-weaving around
   the ring so gentle and wavy and graceful, the men looking ever so
   tall and [airy] and straight, with their heads bobbing and skimming
   along, away up there under the tent-roof, and every lady's
   rose-leafy dress flapping soft and silky around her hips, and she
   looking like the most loveliest parasol.

* bob                                                                 :Twain:
  [2017-09-30 Sat 16:07]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       04474322-881f-4fbc-a175-c65fd863f0ab
   :END:
   bob

*** --->
    боб

    noun
    1. боб (bean, bob, legume)
    2. отвес (plumb, bob, plumb-line, lead)
    3. маятник (pendulum, balance, bob, balance wheel, ticker, swing of
       the pendulum)
    4. поплавок (float, bobber, cork, bob, swimmer)
    5. шиллинг (shilling, schilling, bob, twelver)
    6. бобслей (bobsled, bobsleigh, bob)
    7. короткая стрижка (butch, bob)
    8. балансир (balance, rocker, beam, equalizer, walking beam, bob)
    9. помпон (pompon, bob)
    10. припев (chorus, refrain, burden, bob, tag, burthen)
    11. завиток (curl, swirl, scroll, tendril, whorl, bob)
    12. книксен (bob)
    13. завиток волос (bob)
    14. подстриженный хвост (bob)
    15. хвост (tail, trail, queue, train, brush, bob)
    16. толчок (push, impetus, impulse, thrust, kick, bob)
    17. приседание (squatting, curtsy, curtsey, bob)
    18. чашка (cup, bowl, pan, basin, bob)
    19. шарообразный предмет (bob)
    20. пучок (sheaf, bundle, bunch, tuft, bun, bob)
    21. рефрен (refrain, chorus, burden, burthen, repetend, bob)
    22. гиря (weight, poise, bob)
    23. резкое движение (flick, jerk, flounce, fling, hoick, bob)
    24. женская короткая стрижка (bob)
    25. лот (lot, lead, plumb, plummet, sea gauge, bob)
    26. груз отвеса (bob)

    verb
    1. подскакивать (jump, bob, jump about, bob up and down)
    2. подпрыгивать (bounce, jump, hop, bob up and down, bob, jump
       about)
    3. коротко стричься (bob, cut one's hair close)
    4. качаться (sway, swing, shake, rock, dangle, bob)
    5. стукаться (bob, clash)
    6. ловить угрей (bob, sniggle)
    7. неуклюже приседать (bob)
    8. стукать (bob)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       2003071b-467d-4963-b137-c716410dade9
   :END:

   noun
   1. a style in which the hair is cut short and evenly all around so
      that it hangs above the shoulders. "She had auburn hair styled in
      a [bob] cut, gentle, hazel eyes, and the greatest smile that had
      ever graced any thin, yet soft face."
   2. a weight on a pendulum, plumb line, or kite-tail. "The
      functioning of a key depends on its rigidity whilst that of
      clocks and watches depend crucially on the weight of pendulum
      [bob]s or the elasticity of springs."
   3. a [bob]sled. "If we sent the skaters down the [bob] run, there would
      be no politics, no guessing, no favors exchanged."
   4. a short line at or near the end of a stanza.
   5. a horse's tail docked short.
   6. a shilling. "Now 72, his first taste of the life was as a boy
      when he'd earn ‘two [bob] or a shilling’ for helping out various
      traders until nine o'clock at night."
   7. a change of order in bell-ringing. "This table illustrates how
      you will be affected if the conductor calls a [Bob] or Single."

   verb
   1. (of a thing) make a quick short movement up and down. "I could
      see his red head [bob]bing around"
   2. cut (someone's hair) in a [bob]. "she tied a headscarf over her
      [bob]bed brown hair"
   3. ride on a [bob]sled. "Initially, though, people came to the Alps
      for their health, for skating, for [bob]bing , for being seen and -
      only marginally - for skiing."

   To [bob] is to dip up and down, the way something does when it floats
   on the surface of water. A lobster buoy [bob]s in the ocean, marking
   the spot where a lobsterman's trap is set.

   Your friend stands out when her red hat [bob]s among a crowd of
   people, and so does a red boat as it [bob]s on a lake. You might [bob]
   your head to indicate agreement or get a short haircut that's also
   called a [bob]. The motion [bob] comes from the Old English [bob]ben, "to
   strike," while the hair style stems from the earlier [bob]be, or
   "cluster," and first referred a trimmed horse's tail.

   And then one by one they got up and stood, and went a-weaving around
   the ring so gentle and wavy and graceful, the men looking ever so
   tall and airy and straight, with their heads [bob]bing and skimming
   along, away up there under the tent-roof, and every lady's
   rose-leafy dress flapping soft and silky around her hips, and she
   looking like the most loveliest parasol.

* bobbing


** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       0db58b29-e73c-44fd-9789-cf42b99ec930
   :END:
   bobbing

*** --->
    флюктуация интенсивности светового пятна на экране радиолокатора

    verb
    1. подскакивать (jump, bob, jump about, bob up and down)
    2. подпрыгивать (bounce, jump, hop, bob up and down, bob, jump
       about)
    3. коротко стричься (bob, cut one's hair close)
    4. качаться (sway, swing, shake, rock, dangle, oscillate)
    5. стукаться (bob, clash)
    6. ловить угрей (bob, sniggle)
    7. неуклюже приседать (bob)
    8. стукать (bob)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       f21a0c5e-5b38-416d-b30d-46fce5ef9289
   :END:

   verb
   1. (of a thing) make a quick short movement up and down. "I could
      see his red head [bobbing] around"
   2. cut (someone's hair) in a bob. "she tied a headscarf over her
      bobbed brown hair"
   3. ride on a bobsled. "Initially, though, people came to the Alps
      for their health, for skating, for [bobbing] , for being seen and -
      only marginally - for skiing."

* skimming                                                            :Twain:
  [2017-09-30 Sat 16:07]

** ==>                                                                :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       adbe8a85-75ed-4269-b865-e987cbf25ad1
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:03]
   :END:
   skimming

*** --->
    скимминга

    noun
    1. снятие пены (skim, skimming)
    2. снимание сливок с молока (skimming)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       d5fa14bb-52de-47d4-b8fb-7493780d757b
   :END:

   verb
   1. remove (a substance) from the surface of a liquid. "as the scum
      rises, skim it off"
   2. go or move quickly and lightly over or on a surface or through
      the air. "he let his fingers skim across her shoulders"

   And then one by one they got up and stood, and went a-weaving around
   the ring so gentle and wavy and graceful, the men looking ever so
   tall and airy and straight, with their heads bobbing and [skimming]
   along, away up there under the tent-roof, and every lady's
   rose-leafy dress flapping soft and silky around her hips, and she
   looking like the most loveliest parasol.

* parasol :Twain:
  [2017-09-30 Sat 16:08]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       4830bf8f-a640-4585-a5f4-c36828a073e5
   :END:
   parasol

*** --->
    зонтик от солнца

    noun
    1. зонтик (umbrella, parasol, umbel, gingham, brolly, gamp)
    2. зонтик от солнца (parasol, sunshade)
    3. парасоль (parasol)
    4. небольшой зонтик (parasol)
    5. авиационное прикрытие войск (parasol)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       60ef8261-f70f-4f0c-92cd-581c63276166
   :END:

   noun
   1. a light umbrella used to give shade from the sun. "As for the
      sun, I had a [parasol] ; it shaded my skin from the light."
   2. a widely distributed large mushroom with a broad, scaly,
      grayish-brown cap and a tall, slender stalk, growing typically in
      grassy places. "The day of the election I picked and ate a
      delicious [parasol] mushroom - three months early."

   A [parasol] is a little umbrella that protects you from the sun. If
   you are trying to imitate a fancy Victorian lady, get yourself a
   [parasol].

   An umbrella is a collapsible shade that people use to keep from
   getting wet in the rain or burned in the sun. A similar device is a
   [parasol]. [Parasol]s are smaller than umbrellas, so they're not as
   useful in the rain. However, many people, especially on the beach,
   use [parasol]s to keep the sun from beating down on them. If you don't
   want a sunburn, a [parasol] is handy.

   And then one by one they got up and stood, and went a-weaving around
   the ring so gentle and wavy and graceful, the men looking ever so
   tall and airy and straight, with their heads bobbing and skimming
   along, away up there under the tent-roof, and every lady's
   rose-leafy dress flapping soft and silky around her hips, and she
   looking like the most loveliest [parasol].

* rein                                                                :Twain:
  [2017-09-30 Sat 16:09]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       c2ba8c5e-94e8-4e0f-a29e-02025b56b528
   :END:
   rein

*** --->
    поводья

    noun
    1. поводья (reins, rein)
    2. вожжи (rein, ribbons, leading strings, riband)
    3. повод (occasion, reason, cause, rein, bridle, halter)
    4. вожжа (rein)
    5. узда (bridle, rein, curb)
    6. контроль (control, monitoring, inspection, check, verification,
       rein)
    7. сдерживающее средство (disincentive, rein)
    8. рукоять (handle, grip, helve, rein)

    verb
    1. сдерживать (hold back, restrain, constrain, curb, contain, rein)
    2. управлять (control, manage, run, drive, operate, rein)
    3. держать в узде (rein in, rein, have a cinch on)
    4. править (rule, correct, govern, king, rein, sway)
    5. управлять вожжами (rein)
    6. править вожжами (rein)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       9c1957d8-3ac1-4fc8-9555-4de5456a1bbc
   :END:

   noun
   1. a long, narrow strap attached at one end to a horse's bit,
      typically used in pairs to guide or check a horse while riding or
      driving. "Spotting them, she quickly grabbed the [rein]s and led
      the horses back at a trot."

   verb
   1. check or guide (a horse) by pulling on its [rein]s. "he [rein]ed in
      his horse and waited for her"

   [Rein] is both a noun and a verb for guiding and restraining. You can
   use the long strap, or [rein], on a horse to control its speed and
   direction, and you can [rein] in your own tongue by closing your
   mouth.

   [Rein] rhymes with rain but the two words describe very different
   things. Rain comes down all over the place, uncontrolled, while a
   [rein] holds things in place or controls what comes out. As a noun,
   [rein] is often used as a plural word "[rein]s" when talking about
   actual leather restraints used in horse riding, but a [rein] also is
   something non-physical like when you put a [rein] on spending by
   shopping less.

   and the clown cracking jokes behind him; and by and by all hands
   dropped the [rein]s, and every lady put her knuckles on her hips and
   every gentleman folded his arms, and then how the horses did lean
   over and hump themselves!

* scamper                                                             :Twain:
  [2017-09-30 Sat 16:09]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       06e4a08b-c4cb-4a58-814b-27480f555d65
   :END:
   scamper

*** --->
    носиться

    noun
    1. пробежка (scamper)
    2. быстрый бег (scamper)
    3. беглое чтение (scamper)
    4. поспешное бегство (scoot, lam, scamper)
    5. бегство (escape, flight, getaway, stampede, evasion, scamper)

    verb
    1. носиться (wear, scamper, toss, scamper about, play, skirr)
    2. бежать стремглав (scamper)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       115fabf7-1672-4e80-af12-ecebc21b32bb
   :END:

   noun
   1. an act of [scamper]ing. "The dim, yellow light each one was
      shedding cast shadows off the crates and barrels carelessly piled
      along the length of the alley, and occasionally a squeak and a
      [scamper] echoed throughout the area."

   verb
   1. (especially of a small animal or child) run with quick light
      steps, especially through fear or excitement. "he [scamper]ed in
      like an overgrown puppy"

   To [scamper] is to move in a hurry. You and your friends might [scamper]
   to catch the bus, or your kitten might [scamper] to catch a mouse.

   The verb [scamper] describes something that's moving in disorderly
   haste, often out of fear or excitement. You might notice that
   chipmunks [scamper] the instant your dog goes outside. You can also
   use [scamper] as a noun, when you talk about your death-defying
   [scamper] across town in an effort to be on time for your first day of
   work. [Scamper] was a very popular word in the late 1800s.

   And so one after the other they all skipped off into the ring, and
   made the sweetest bow I ever see, and then [scamper]ed out, and
   everybody clapped their hands and went just about wild.

* pat :Twain:
  [2017-09-30 Sat 16:10]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       1c22283e-361b-4761-90e1-f33213f67cbd
   :END:
   pat

*** --->
    похлопывание

    verb
    1. потрепать (pat, pull about, wear out, thrash)
    2. похлопывать (pat, clap)
    3. поглаживать (stroke, pat)
    4. шлепать (slap, splash, smack, flap, cuff, pat)

    noun
    1. похлопывание (pat)
    2. хлопок (cotton, clap, pat, flap, smack, swat)
    3. кусок (piece, chunk, lump, bit, bite, pat)
    4. шлепок (slap, smack, swat, spank, pat, flap)
    5. хлопанье (slam, clap, pat, flip-flap)
    6. шлепанье (flop, pat, flap)
    7. кружочек (pat, areola)
    8. кусок сбитого масла (pat)
    9. кружочек сбитого масла (pat)

    adverb
    1. кстати (apropos, appositely, pat, to the purpose)
    2. своевременно (timely, in good time, early, opportunely, in due
       course, pat)
    3. с готовностью (readily, willingly, pat)
    4. удачно (happily, felicitously, pat)
    5. как раз (just, exactly, right, even as, even, pat)
    6. свободно (free, freely, loose, loosely, easily, pat)
    7. быстро (fast, quickly, quick, prompt, swift, pat)

    adjective
    1. подходящий (suitable, appropriate, right, suited, fitting, pat)
    2. уместный (relevant, pertinent, opportune, apt, germane, pat)
    3. своевременный (timely, opportune, early, seasonable, forehanded,
       pat)
    4. удачный (successful, fortunate, lucky, felicitous, happy, pat)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       24e1afc9-02a0-4300-9f7c-f7545f7b0b71
   :END:

   adjective
   1. simple and somewhat glib or unconvincing. "instead of enlightened
      minds I found prejudice and [pat] answers"

   adverb
   1. at exactly the right moment or in the right way; conveniently or
      opportunely. "the happy ending came rather [pat]"

   noun
   1. a light stroke with the hand. "giving him a friendly [pat] on the
      arm, she went off to join the others"
   2. a compact mass of soft material. "a [pat] of butter"

   verb
   1. touch quickly and gently with the flat of the hand. "he [pat]ted
      him consolingly on the shoulder"

   When you [pat], you tap lightly with your hand. A sad friend might be
   comforted by a kind [pat] on the shoulder. But that sad friend would
   not be comforted by a [pat], insincere, comment.

   Your grandfather might [pat] you on the head just like when you were
   little, even though you're taller than he is now. Dogs like getting
   a [pat] on the head, or maybe a [pat] of butter from the dinner table.
   When it's an adjective, [pat] means "way too simple" or "glib," as in
   "I asked a serious question — please don't give me a [pat] answer." To
   "have something down [pat]" is to know it by heart.

   The ringmaster couldn't ever say a word to him but he was back at
   him quick as a wink with the funniest things a body ever said; and
   how he ever could think of so many of them, and so sudden and so
   [pat], was what I couldn't noway understand.

* holler :Twain:
  [2017-09-30 Sat 16:11]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       3da67bbf-d2c1-41b6-853c-633237074391
   :END:
   holler

*** --->
    окликать

    verb
    1. кричать (shout, cry, yell, holler, call out, clamor)
    2. окликать (hail, holler, call, challenge, speak, hallo)
    3. вопить (yell, scream, cry, wail, shriek, holler)
    4. вскрикнуть (scream, give a cry, holler, yaup, yawp, yip)
    5. шуметь (make noise, noise, bluster, sound off, din, holler)

    noun
    1. вскрик (holler)
    2. крик (cry, shout, crying, call, outcry, holler)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       06bfd432-594c-4c5f-a8d1-0a7d59d92a02
   :END:

   verb
   1. (of a person) give a loud shout or cry. "he [holler]s when he wants
      feeding"

   noun
   1. a loud cry or shout. "They make odd squeaky noises and suddenly
      explode in girlful shouts, screams and [holler]s of exuberance
      shattering the perfect calm of a quiet summer night."

   When you [holler], you yell a little too loudly and abruptly. A kid
   stuck in a tree might [holler] for help until someone shows up to help
   him climb down.

   [Holler] is an informal verb, useful for those times you call out or
   shout. Your teacher might [holler] at the class if she gets angry
   enough, and you might [holler] at your sister to get out of your room
   at least once a day. A [holler] can also be a dip or depression in the
   land, a hollow. The word dates from the 17th century, a colloquial
   form of hollo, a variation on hello.

   Then the people begun to [holler] at him and make fun of him, and that
   made him mad, and he begun to rip and tear; so that stirred up the
   people, and a lot of men begun to pile down off of the benches and
   swarm towards the ring, saying, "Knock him down!

* stir                                                                :Twain:
  [2017-09-30 Sat 16:11]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       86a5d885-d563-4936-80dd-62a71faeb047
   :END:
   stir

*** --->
    размешать

    noun
    1. переполох (stir, alarm, flutter, hurly-burly)
    2. движение (movement, motion, traffic, move, stir, go)
    3. ажиотаж (agiotage, boom, stir, rush, agio)
    4. шевеление (stir)
    5. суматоха (turmoil, bustle, ado, flurry, clutter, stir)
    6. суета (vanity, bustling, bustle, rush, scurry, stir)
    7. размешивание (agitation, kneading, stir)
    8. заваруха (commotion, stir)
    9. тюрьма (prison, jail, gaol, pokey, prison house, stir)
    10. кутузка (bullpen, slammer, hoosegow, slam, calaboose, stir)

    verb
    1. размешивать (stir, mix up, churn, poach)
    2. шевелить (stir, move)
    3. мешать (interfere, disturb, prevent, stir, interrupt, hinder)
    4. шевелиться (stir, move, budge)
    5. помешивать (stir, stir slowly)
    6. болтать (chat, talk, dangle, chatter, prattle, stir)
    7. всколыхнуть (stir, rusty)
    8. взболтать (stir, shake up)
    9. всколыхнуться (stir, become agitated, rock, be roused)
    10. двигаться (move, travel, run, stir, traverse, dance)
    11. взбалтывать (stir, shake up, agitate, churn, roil)
    12. волновать (excite, disturb, agitate, ferment, stir, move)
    13. возбуждать (excite, stir, stir up, arouse, bring, stimulate)
    14. разбалтывать (blab, chatter, stir, prate, shake)
    15. шелохнуться (stir)
    16. шелохнуть (stir)
    17. двигать (move, propel, stir)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       2b310979-14ac-4d78-b47f-bb554b997312
   :END:

   noun
   1. a slight physical movement. "I stood, straining eyes and ears for
      the faintest [stir]"
   2. an act of mixing food or drink with a spoon or other implement.
      "he gives his chocolate milk a [stir]"
   3. prison. "I've spent twenty-eight years in [stir]"

   verb
   1. move a spoon or other implement around in (a liquid or other
      substance) in order to mix it thoroughly. "[stir] the batter until
      it is just combined"
   2. move or cause to move slightly. "nothing [stir]red except the wind"
   3. arouse strong feelings in (someone); move or excite. "they will
      be [stir]red to action by what is written"


   Then the people begun to holler at him and make fun of him, and that
   made him mad, and he begun to rip and tear; so that [stir]red up the
   people, and a lot of men begun to pile down off of the benches and
   swarm towards the ring, saying, "Knock him down!

* cavort :Twain:
  [2017-09-30 Sat 16:12]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       b1ee7854-7a68-4b52-b7d6-9373886ebf56
   :END:
   cavort

*** --->
    скакать

    verb
    1. скакать (jump, skip, leap, dance, cavort, spring)
    2. прыгать (jump, leap, hop, skip, spring, cavort)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       fa807f2c-01d6-4fb5-8519-8d67f8b848be
   :END:

   verb
   1. jump or dance around excitedly. "spider monkeys leap and [cavort]
      in the branches"

   How to [cavort], in one easy step: dance around all crazy, jumping on
   and over anything nearby like you just ate a lot of sugar. Give it a
   try!

   [Cavort]ing requires a good mood, lots of energy, and some running
   room. Children love to [cavort], and so do parents when they win the
   lottery. The origins of the word are unclear, perhaps coming from
   the word curvet, meaning “leap gracefully or energetically,” and
   leaping is a great addition to any [cavort]ing. There are lots of
   synonyms, so if you ever get tired of [cavort]ing, you could always
   prance, frolic, lark, rollick, romp, or carouse. The choice is
   yours.

   The minute he was on, the horse begun to rip and tear and jump and
   [cavort] around, with two circus men hanging on to his bridle trying
   to hold him, and the drunk man hanging on to his neck, and his heels
   flying in the air every jump, and the whole crowd of people standing
   up shouting and laughing till tears rolled down.

* bridle :Twain:
  [2017-09-30 Sat 16:13]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       c56b5fc2-babd-4694-b382-7f163b1e3875
   :END:
   bridle

*** --->
    /ˈbraɪd l/
    уздечка

    noun
    1. уздечка (bridle, snaffle, lore, snaffle-bit)
    2. узда (bridle, rein, curb)
    3. повод (occasion, reason, cause, rein, bridle, halter)
    4. бридель (bridle)

    verb
    1. обуздывать (restrain, curb, bridle, moderate, put a bridle on,
       refrain)
    2. взнуздывать (bridle, bit)
    3. сдерживать (hold back, restrain, constrain, curb, contain,
       bridle)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       9262f828-26ce-4b51-bf08-54e38be32cc6
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:05]
   :END:

   noun
   1. the headgear used to control a horse, consisting of buckled
      straps to which a bit and reins are attached. "The king ordered
      eight horses with gold-plaited [bridle]s led into the hall."

   verb
   1. put a [bridle] on (a horse). "Saddling and bridling a horse would
      be a subject of its own and I will certainly follow up."
   2. show one's resentment or anger, especially by throwing up the
      head and drawing in the chin. "ranchers have [bridle]d at excessive
      federal control"


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       1b3f77e3-7b4c-4c78-b812-af70462c61ab
   :END:
   When you're riding a horse and scream "Whoa!" to make it stop,
   you're pulling on the reins, which are attached to a thing called
   the [bridle], the buckled straps around a horse's head that help you
   control its movements.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       8f4bbff1-d854-436c-9de2-9a383fbf38b0
   :END:
   The word [bridle] comes from the Old English bridel meaning "rein,
   curb, restraint," which is precisely what the purpose of a [bridle] is
   — to help restrain a horse's movements when necessary. You can
   [bridle] a horse, which is the act of putting a [bridle] on it. If you
   yank too hard on the reins, your horse might [bridle], or take offense
   to your aggressiveness, just like you might [bridle] if someone
   insulted you.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       6e87d4a6-b5b9-46a0-9e9b-c9c5d6aea5f9
   :END:
   The minute he was on, the horse begun to rip and tear and jump and
   cavort around, with two circus men hanging on to his [bridle] trying
   to hold him, and the drunk man hanging on to his neck, and his heels
   flying in the air every jump, and the whole crowd of people standing
   up shouting and laughing till tears rolled down.

* sot :Twain:
  [2017-09-30 Sat 16:13]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       e137a7d5-fbff-4b9d-9b2b-4e5e4e7a0bc3
   :END:
   sot

*** --->
    квасить

    verb
    1. квасить (booze, make sour, sot, bib, boose)
    2. пить (drink, imbibe, tipple, bib, sot)
    3. напиваться (get drunk, become drunk, swizzle, fuddle, lush, sot)

    noun
    1. горький пьяница (habitual drunkard, sot)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :ID:       4cbec8ef-21b8-4e35-8ccf-a6b4e8f387cb
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 4.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:08]
   :END:

   noun
   1. a habitual drunkard. "A few nifty lighting tricks later, and
      we're riding the rails with a host of yin-yang character pairs:
      the suited businessman and his wayward brother, the heartbroken
      [sot] and her vivacious new friend, and so on."

   verb
   1. drink habitually.


** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide1cloze
   :END:

   A [sot||habitual drinkard] is someone who frequently drinks too
   much alcohol. If you see someone [stumbling] out of a bar in the
   middle of the day, you might be tempted to describe him as a [sot].
** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: show2cloze
   :END:

   [Sot] is a somewhat old-fashioned word for a heavy drinker, also
   known as a lush or a wino. It's also considered insulting and
   [derogatory||humiliating]. The character of the [sot] has featured
   in literature and film for years, going at least as far back as
   Shakespeare, whose famous [sot]s included the drunken Falstaff in
   "Henry IV" and Sir Toby Belch in "Twelfth Night." In Old English, a
   [sot]t was a "stupid person or a fool."
** >>>                                                                :drill:
   And at last, sure enough, all the circus men could do, the horse
   broke loose, and away he went like the very nation, round and round
   the ring, with that [sot] laying down on him and hanging to his neck,
   with first one leg hanging most to the ground on one side, and then
   t'other one on t'other side, and the people just crazy.

* astraddle :Twain:
  [2017-09-30 Sat 16:14]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       38675a54-6c69-402d-a258-6834983c6f66
   :END:
   astraddle

*** --->
    верхом

    adverb
    1. верхом (horseback, on horseback, astride, astraddle, ahorse)
    2. широко расставив ноги (astraddle)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       5e9e6f81-39d8-49ca-8e76-48cd0c1109c0
   :END:

   preposition
   1. with the legs stretched widely on each side of. "policemen
      sitting [astraddle] motorcycles"

   adjective
   1. with the legs stretched widely on each side.

   When you sit or stand [astraddle] something, you have one leg on each
   side of it. Kids on a seesaw sit [astraddle] as they bounce up and
   down.

   The typical way to ride a horse is [astraddle], with one leg on each
   side of the horse's back, and people also ride bikes and motorcycles
   while sitting [astraddle]. You might even have had a teacher or two
   who preferred to address the class while sitting [astraddle] the
   chair. [Astraddle] comes from the verb straddle, which comes from the
   same Old English root as the word stride — stridan, "to straddle."

   But pretty soon he struggled up [astraddle] and grabbed the bridle,
   a-reeling this way and that; and the next minute he sprung up and
   dropped the bridle and stood!

* clogged                                                             :Twain:
  [2017-09-30 Sat 16:15]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       8e4c6726-9959-4486-8815-196d1b7eb6b0
   :END:
   clogged

*** --->
    засоренный

    verb
    1. засорять (clog, block, foul, choke, choke up, corrupt)
    2. засоряться (clog, block, foul)
    3. надевать путы (clog, jess)
    4. обременять (burden, encumber, charge, load, saddle, embarrass)
    5. препятствовать (let, prevent, hinder, impede, inhibit, hamper)
    6. мешать (interfere, disturb, prevent, stir, interrupt, hinder)
    7. спутывать (confuse, snarl, knot, clog, confound, muddle)
    8. застопоривать (clog)
    9. застопориваться (clog)
    10. быть заполненным (clog)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       292278aa-625c-49eb-8639-ac895f5a2173
   :END:

   verb
   1. block or become blocked with an accumulation of thick, wet
      matter. "the gutters were [clogged] up with leaves"

   Something that's [clogged] is blocked or stopped up. When your sink is
   [clogged], the soapy water can't flow down the drain.

   If your gutters are [clogged] with leaves, rain water will simply flow
   and drip over the edges, and if your arteries become [clogged], you'll
   be at a higher risk for having a heart attack. In both cases, the
   [clogged] things need to be cleared or cleaned out in order to work
   properly. Another way something can be [clogged] is to be clotted or
   thickened: "I don't like this oatmeal because the pieces are all
   [clogged] together."

   He shed them so thick they kind of [clogged] up the air, and
   altogether he shed seventeen suits.

* clog


** ==>                                                                :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       0cc49f60-3152-4916-bbae-c90362dadb6f
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 11:07]
   :END:
   clog

*** --->
    загромождать

    verb
    1. засорять (clog, block, foul, choke, choke up, corrupt)
    2. засоряться (clog, block, foul)
    3. надевать путы (clog, jess)
    4. обременять (burden, encumber, charge, load, saddle, clog)
    5. препятствовать (let, prevent, hinder, impede, inhibit, clog)
    6. мешать (interfere, disturb, prevent, stir, interrupt, clog)
    7. спутывать (confuse, snarl, knot, clog, confound, muddle)
    8. застопоривать (clog)
    9. застопориваться (clog)
    10. быть заполненным (clog)

    noun
    1. помеха (hindrance, noise, obstacle, impediment, nuisance, clog)
    2. засорение (clog, impurity, stoppage, lodgement, lodgment)
    3. башмак (shoe, boot, chock, clog, saddle, scotch)
    4. препятствие (let, obstacle, obstruction, barrier, hurdle, clog)
    5. колодка (block, shoe, last, cheek, clog, shoe-tree)
    6. тяжесть (gravity, weight, burden, heaviness, load, clog)
    7. груз (cargo, goods, load, freight, loading, clog)
    8. башмак на деревянной подошве (clog)
    9. деревянная колода (clog)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       2b3644d9-8ab1-4bfb-b77d-ebd979608136
   :END:

   noun
   1. a shoe with a thick wooden sole. "Traditional footwear is sandals
      or wooden [clog]s with a thong that passes between the big toe and
      the second toe."
   2. an encumbrance or impediment. "a [clog] in the system"

   verb
   1. block or become blocked with an accumulation of thick, wet
      matter. "the gutters were [clog]ged up with leaves"


* gaudy                                                               :Twain:
  [2017-09-30 Sat 16:16]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       83877205-b79e-429e-8734-bebf676a0a01
   :END:
   gaudy

*** --->
    безвкусный

    adjective
    1. яркий (bright, vivid, colorful, shining, flamboyant, gaudy)
    2. безвкусный (tasteless, gaudy, flavorless, insipid, inelegant,
       bland)
    3. кричащий (screaming, flashy, crying, glaring, showy, gaudy)
    4. цветастый (gaudy, garish)
    5. витиеватый (ornate, florid, flowery, gorgeous, gaudy)
    6. цветистый (flowery, flamboyant, florid, exuberant, gaudy,
       colorific)

    noun
    1. большое празднество (gaudy)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       4aa28459-3e69-4aa2-a5d5-6d831b3e0b8c
   :END:

   adjective
   1. extravagantly bright or showy, typically so as to be tasteless.
      "silver bows and [gaudy] ribbons"

   noun
   1. a celebratory reunion dinner or entertainment held by a college.

   Something that's [gaudy] is showy, bright and definitely tacky. So
   think twice about that [gaudy] rainbow-colored suit and shiny gold
   shoes ensemble.

   [Gaudy] is an adjective that means "ostentatious" — in other words,
   flashy and in your face, and not in a good way. Someone in a
   [gaudy] outfit is probably trying too hard to be cool and stylish.
   [Gaudy] evolved from the Middle English gaud “deception, trick” in
   the 1520’s. That word, in turn, came from gaudi, used to describe a
   “large, ornamental bead in a rosary.”

   And, then, there he was, slim and handsome, and dressed the
   [gaudi]est and prettiest you ever saw, and he lit into that horse
   with his whip and made him fairly hum—and finally skipped off, and
   made his bow and danced off to the dressing-room, and everybody
   just a-howling with pleasure and astonishment.

* whip :Twain:
  [2017-09-30 Sat 16:16]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       241a8b97-5b02-4d51-acce-a89fac2966e0
   :END:
   whip

*** --->
    кнут

    noun
    1. кнут (whip, knout)
    2. хлыст (whip, switch, horsewhip)
    3. бич (scourge, whip, pest, curse, plague, lash)
    4. нагайка (whip)
    5. кучер (coachman, driver, whip, flyman)
    6. выжлятник (whip, whipper-in)
    7. обметка (whip)
    8. взбитые сливки (whipped cream, Chantilly, whip)
    9. конный спорт (equestrian sport, whip)
    10. крыло ветряной мельницы (fan, whip, sail, sweep)
    11. подъемный гордень (whip)

    verb
    1. взбить (whip, shake up, beat up)
    2. хлестать (slash, whip, lash, beat, lace)
    3. спереть (whip, crook)
    4. сечь (flog, whip, shred)
    5. трепаться (gab, yak, whip, waffle, yackety-yack)
    6. влетать (fly into, fly in, whip, blow in, breeze in)
    7. подхлестывать (whip)
    8. побить (break, whip, trim, drub, nip)
    9. побеждать (win, overcome, conquer, defeat, vanquish, whip)
    10. превосходить (exceed, transcend, surpass, excel, beat, whip)
    11. подгонять (match, urge, hurry, rush, prod, whip)
    12. вбегать (run into, whip, breeze in)
    13. юркнуть (whisk, whisk out, whip, whid)
    14. резко критиковать (criticize hard, assail, flay, slash, whip,
	knock)
    15. ругать (swear, scold, abuse, berate, revile, whip)
    16. пропустить стаканчик (whip, whip off)
    17. опрокинуть рюмочку (whip, whip off)
    18. обметывать через край (whipstitch, whip)
    19. сшивать через край (whipstitch, oversew, overcast, whip)
    20. удить рыбу на мушку (whip a stream, whip)
    21. заделывать конец троса маркой (whip)
    22. украсть (scrounge, pinch, filch, thieve, nick, whip)
    23. стегнуть (whip)
    24. сбивать (bring down, shoot down, knock, down, churn, whip)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-08 Sun>
   :PROPERTIES:
   :ID:       dc230a2b-7754-466c-809e-7566a7081538
   :DRILL_LAST_INTERVAL: 4.0
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 1
   :DRILL_FAILURE_COUNT: 0
   :DRILL_AVERAGE_QUALITY: 4.0
   :DRILL_EASE: 2.5
   :DRILL_LAST_QUALITY: 4
   :DRILL_LAST_REVIEWED: [2017-10-04 Wed 10:52]
   :END:

   noun
   1. a strip of leather or length of cord fastened to a handle, used
      for flogging or beating a person or for urging on an animal. "I
      wouldn't be surprised if they walked around their office wearing
      tight leather and vinyl with [whip]s and riding crops at their
      sides."
   2. a thing or person resembling a [whip] in form or function. "a
      licorice [whip]"
   3. an official of a political party appointed to maintain discipline
      among its members in Congress or Parliament, especially so as to
      ensure attendance and voting in debates. "It is almost certain
      that a government with a decent Parliamentary majority will win
      this as the bill represents what that government wants and the
      party [whip]s will ensure that a smooth vote takes place."
   4. a dessert consisting of cream or eggs beaten into a light fluffy
      mass with fruit, chocolate, or other ingredients. "The fritters
      and walnut [whip] are now ready to be enjoyed."
   5. a violent striking or beating movement.

   verb
   1. beat (a person or animal) with a [whip] or similar instrument,
      especially as a punishment or to urge them on. "There they kicked
      us, beat us, [whip]ped us with electric cables and shocked us with
      electricity!"
   2. move fast or suddenly in a specified direction. "I [whip]ped around
      the corner"
   3. bind (something) with spirally wound twine. "The edges are
      [whip]ped with wool yarns."


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       22b07aed-7119-432b-9f11-9d991517e929
   :END:
   A [whip] is a cord or piece of leather used for hitting an animal or a
   person, and to [whip] something or someone is to strike them with a
   [whip]. You can also figuratively [whip] an opponent or [whip] someone in
   shape. Giddy up!
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       9ce5e2b3-5a06-4078-a95e-398d1bcf0a1b
   :END:
   When you hit an animal with a [whip], you [whip] it. Some animal rights
   activists object to horse racers using [whip]s. You can also use this
   verb to mean "defeat by a lot," like when your basketball team [whip]s
   the opposing team. A chef [whip]s cream by whisking or mixing it until
   it's airy and frothy. If your teacher says he's going to "crack the
   [whip]," he means he's planning to use his authority to make the class
   work harder. And, fittingly, a political [whip] is someone who
   enforces discipline among party members.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       f44ee4d9-13fe-4d2e-9405-805c2754f5a9
   :END:
   And, then, there he was, slim and handsome, and dressed the gaudiest
   and prettiest you ever saw, and he lit into that horse with his [whip]
   and made him fairly hum—and finally skipped off, and made his bow
   and danced off to the dressing-room, and everybody just a-howling
   with pleasure and astonishment.

* contemptuous :satellite:
  [2017-10-02 Mon 15:14]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       4e826578-9bfb-4039-b610-9313e231487a
   :END:
   contemptuous

*** --->
    презрительный

    adjective
    1. презрительный (contemptuous, disdainful, scornful, sniffy,
       snooty, supercilious)
    2. высокомерный (arrogant, haughty, contemptuous, lofty,
       supercilious, snooty)
    3. пренебрежительный (disparaging, contemptuous, disdainful,
       slighting, insolent)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       6df05931-40f2-424a-b468-f947ddfc2a1b
   :END:

   adjective
   1. showing contempt; scornful. "she was intolerant and [contemptuous]
      of the majority of the human race"


   smile or speak in a [contemptuous] or mocking manner.

* mocking :satellite:
  [2017-10-02 Mon 15:14]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       eadba5e7-6fe3-4399-90d8-a46a43951302
   :END:
   mocking

*** --->
    осмеяние

    noun
    1. осмеяние (mockery, ridicule, derision, mocking, mock, jesting)
    2. пародирование (mocking)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :ID:       0084028b-4e28-4d83-94a8-8bc37aef5ea9
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:31]
   :END:

   adjective
   1. making fun of someone or something in a cruel way; derisive. "the
      [mocking] [hostility||enmity] in his voice made her wince"

   verb
   1. tease or laugh at in a scornful or contemptuous manner. "he [mock]s
      them as Washington insiders"


** >>>                                                                :drill:
   When you talk to or about someone in a [mocking] tone, you're making
   fun of them in a nasty, mean way.
** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: show1cloze
   :END:

   But if you're a comedy writer or political satirist, a [mocking]
   attitude is a tool of your trade. If you're writing a
   [skit||sketch] about the outrageous proposal some politician has
   just made, you'll write it in a [mocking] tone, imitating the
   politician's voice and mannerisms in a way that makes him look as
   [ridiculous||ludicrous] as you think he is. Seen any [mocking]birds lately?
   That's the bird that sings almost nonstop, imitating the calls of
   other birds.
** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide1cloze
   :END:

   smile or speak in a [contemptuous] or [mocking] manner.

* resentment :satellite:
  [2017-10-02 Mon 15:16]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       bde541ba-9692-454e-a5d6-9175773c7aa0
   :END:
   resentment

*** --->
    чувство обиды

    noun
    1. негодование (indignation, resentment, dander)
    2. возмущение (disturbance, perturbation, indignation, resentment,
       rebellion, clamor)
    3. чувство обиды (resentment, soreness, ill feeling)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       87acf97b-d82c-4984-a6d8-6fd307e08aef
   :END:

   noun
   1. bitter indignation at having been treated unfairly. "his
      [resentment] at being demoted"

   [Resentment], or the strong and painful bitterness you feel when
   someone does something wrong to you, doesn’t have actual physical
   weight, but it feels very heavy and can last a long time.
   Forgiveness is one way to get rid of [resentment].

   Sometimes [resentment] lasts for years. It can be strong and hard to
   pull out, like an old, gnarled tree root. While [resentment] over
   being wronged can come from just one act against you, it also can
   get stronger over time, as in "your growing [resentment] might just
   come from the fact that the team captain always picks you last." It
   also comes from misunderstandings, like feeling [resentment] over a
   dirty look you thought was directed at you but really wasn't. It's
   usually best to root out [resentment] early.

   annoyance and [resentment].

* pester :satellite:
  [2017-10-02 Mon 15:17]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       adbcf86d-b5b8-43f0-b0bb-7146447eac25
   :END:
   pester

*** --->
    донимать

    verb
    1. докучать (bother, pester, annoy, importune, interfere, bug)
    2. донимать (pester, bombard)
    3. надоедать (bother, annoy, nag, bore, pall, pester)
    4. выклянчивать (pester, cadge, plague)
    5. задрать (screw up, bully, pester, bug)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       6eafcc50-e7d6-46de-95f8-8eae23965e1e
   :END:

   verb
   1. trouble or annoy (someone) with frequent or persistent requests
      or interruptions. "she constantly [pester]ed him with telephone
      calls"

   To [pester] someone is to annoyingly nag them about something.
   [Pester]ing is repetitive and bothersome.

   When a child asks a parent something over and over again — like "Can
   I have candy? Please? Can I have candy now?" — that's an example of
   [pester]ing. Parents also [pester] kids when they say "Clean your room"
   or "Take out the garbage" over and over. [Pester]ing is like
   requesting, but doing it many times, usually to the point of
   annoyance. No one likes to be [pester]ed.



* prosody :satellite:
  [2017-10-02 Mon 15:32]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       9053aa76-8476-4368-87c2-f77d394e3ca3
   :END:
   prosody

*** --->
    просодия

    noun
    1. просодия (prosody, versification)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       d7cbabba-645f-4684-8b84-c22651409161
   :END:

   noun
   1. the patterns of rhythm and sound used in poetry. "the translator
      is not obliged to reproduce the [prosody] of the original"

   [Prosody] is the rhythm and sounds used in poetry. Kids who can
   freestyle rap fit the [prosody] of their words to a rhythm that's
   already laid down.

   [Prosody] can also mean the study of the rhythms and sounds of
   language, and sometimes you can talk about the [prosody] of prose.
   It's about where the emphasis falls in the words and how those work
   together. When you read great writers like Alice Munro aloud, you
   will see that their [prosody], as much as anything, is what carries
   the story forward.

   "First, with respect to [prosody], he believes that the syllable count
   of poetic lines, strophes, [stanza]s , and poems was essential to
   the writing of biblical poetry."

* plenum :satellite:
  [2017-10-02 Mon 15:44]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       f4adc0fc-828a-4149-a01b-1acd4a2cc562
   :END:
   plenum

*** --->
    пленум

    noun
    1. пленум (plenum)
    2. полнота (completeness, fullness, fulness, entirety, plenitude,
       plenum)
    3. заполнение (filling, fill, plenum, suffusion)
    4. заполненность (plenum)
    5. безраздельность (plenum)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       b1964913-26ba-4b07-8957-6bf46b862bb4
   :END:

   noun
   1. an assembly of all the members of a group or committee. "He said
      the next [plenum] of the central committee, scheduled after local
      party congresses from August this year to before March next year,
      will touch upon personnel matters for a new party leadership."
   2. a space completely filled with matter, or the whole of space so
      regarded. "Imagine fracturing a material body such as a piece of
      wood, regarded as a [plenum] (full of matter)."



   "In a second arrangement, the first gas supply opens into the
   central region above an upper [baffle] plate and the second gas
   supply opens into the periphery of a [plenum] between the upper
   [baffle] plate and a lower [baffle] plate."

* semolina :satellite:
  [2017-10-02 Mon 15:46]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       14cc8ea4-97f9-4efa-b97d-02d38e643c2a
   :END:
   semolina

*** --->
    манная крупа

    noun
    1. манная крупа (semolina, farina, manna-croup)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :ID:       f8e4dcbf-178b-4cc2-8aba-90a354b7a719
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 3
   :DRILL_FAILURE_COUNT: 2
   :DRILL_AVERAGE_QUALITY: 1.333
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:32]
   :END:

   noun
   1. the hard grains left after the milling of flour, used in puddings
      and in pasta. "Smeeda or large grain [semolina] flour is the grain
      of choice to make couscous."


** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide1cloze
   :END:

   "These new noodles substitute soy flour for [semolina] flour and may
   contain egg whites or [yolk]s to boost protein."

* bewilder :satellite:
  [2017-10-02 Mon 15:54]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       c54b69cb-169a-4e11-8c52-88769212c2da
   :END:
   bewilder

*** --->
    смущать

    verb
    1. сбивать с толку (confuse, bewilder, baffle, mislead, perplex,
       obfuscate)
    2. смущать (embarrass, confuse, disturb, perplex, disconcert,
       bewilder)
    3. озадачивать (puzzle, perplex, bewilder, baffle, mystify, amuse)
    4. ставить в тупик (confound, nonplus, perplex, bewilder, puzzle,
       baffle)
    5. изумлять (astonish, amaze, astound, daze, stupefy, bewilder)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       88f38289-c39f-45e3-bef8-228c9d68d90e
   :END:

   verb
   1. cause (someone) to become perplexed and confused. "she seemed
      frightened and [bewilder]ed"


** >>>                                                                :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide2cloze
   :ID:       c4da75e5-8f18-42c6-aeae-38c6dbb294d8
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 2.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:28]
   :END:
   To [bewilder] is to [amaze], [baffle], [dumbfound], [flummox],
   [perplex], or [stupefy]. When you [bewilder] people, you confuse them.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       9f107328-5062-4df2-a2c4-6bdf65efbd1d
   :END:
   [Bewilder] is a fun-sounding word for confusion-causing. A complicated
   math problem will [bewilder] many students. A magician's tricks should
   [bewilder] the audience. Mystery stories should be a little
   [bewilder]ing, at least until the end. Sometimes, being [bewilder]ed has
   a more emotional element. If someone you know died in a freak
   accident, that would [bewilder] you in a very sad way.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       fb3c75ac-d65e-46f4-9443-1d9d73e8cee6
   :END:
   totally [bewilder] or perplex.

* perplex :satellite:
  [2017-10-02 Mon 15:54]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       c81ce76f-596f-460e-ad93-7e4d0d29b88b
   :END:
   perplex

*** --->
    запутывать

    verb
    1. смущать (embarrass, confuse, disturb, perplex, disconcert,
       bewilder)
    2. ставить в тупик (confound, nonplus, perplex, bewilder, puzzle,
       baffle)
    3. приводить в недоумение (perplex)
    4. озадачивать (puzzle, perplex, bewilder, baffle, mystify, amuse)
    5. усложнять (complicate, tangle, perplex, puzzle, ravel, intricate)
    6. запутывать (tangle, entangle, foul, knot, kink, perplex)
    7. сбивать с толку (confuse, bewilder, baffle, mislead, perplex,
       obfuscate)
    8. ошеломлять (stun, overwhelm, bemuse, numb, knock, perplex)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       99c1f650-3461-4619-ba6f-35028964e5a1
   :END:

   verb
   1. (of something complicated or unaccountable) cause (someone) to
      feel completely baffled. "she was [perplex]ed by her husband's
      moodiness"


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       d1018557-4eda-44a4-a6c9-2c5d79aba64e
   :END:
   To [perplex] someone is to amaze, baffle, bewilder, dumbfound,
   flummox, mystify, or puzzle them. [Perplex]ing things are hard to
   understand.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       84c76c2d-738e-45c2-a9e2-f64c15c4bcb9
   :END:
   If you're [perplex]ed, then you're confused. Different things [perplex]
   different people. In football, a tricky defense will [perplex] a
   quarterback. Complicated formulas can [perplex] math students. When
   people do weird things, it can be [perplex]ing. Anything hard to
   understand might [perplex] you. [Perplex]ing also means to make
   something more complicated. So when you see the word [perplex], think
   "Huh?"
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       f6fae671-37af-4916-8e6d-a42138271d24
   :END:
   totally bewilder or [perplex].

* obstruct                                                        :satellite:
  [2017-10-02 Mon 15:58]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       bfd6e0e5-7e2f-4ad3-9cd7-86560b68ae2a
   :END:
   obstruct

*** --->
    препятствовать

    verb
    1. препятствовать (let, prevent, hinder, impede, inhibit, obstruct)
    2. мешать (interfere, disturb, prevent, stir, interrupt, obstruct)
    3. затруднять (obstruct, impede, hamper, trouble, embarrass,
       encumber)
    4. загромождать (obstruct, encumber, lumber, jam, lumber up, choke
       up)
    5. заслонять (obstruct, hide, shield, eclipse, occult, buckler)
    6. преграждать (block, obstruct, bar, stop, interrupt, head back)
    7. заграждать (obstruct, block, barrier, barrier in, barrier off,
       secure)
    8. затруднять проходимость (obstruct)
    9. устраивать обструкцию (obstruct)
    10. вызывать запор (constipate, bind, bound, obstruct)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       f9d3c3ac-4a25-4de2-9a4e-fcc567500b3a
   :END:

   verb
   1. block (an opening, path, road, etc.); be or get in the way of.
      "she was [obstruct]ing the entrance"


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       1346a7db-eb31-4caa-bd08-507294c806b9
   :END:
   When you [obstruct] something, you block it. If you’re gobbling down
   your pizza, a chunk of crust you didn’t chew so well might [obstruct]
   your airway and you'll choke.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       bfff4bd3-742f-40cd-85ca-163ccdee2a68
   :END:
   [Obstruct] also means to get in the way so that you hide something
   from view. That fast food tower being built next to your beach house
   will [obstruct] your lovely ocean vistas. And that scene gives you a
   vivid illustration of the Latin roots the word comes from: ob-
   "against," and struere, "build." You can also [obstruct] something or
   someone by putting up a roadblock, literal or figurative: when you
   park yourself by the exit door, you [obstruct] everybody's way out.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       ef95bfd1-7b86-4ef2-967a-e1705e852282
   :END:
   a mass of ice [obstruct]ing a narrow passage, especially a river.

* crevice :satellite:
  [2017-10-02 Mon 15:58]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       dc8d082d-634d-4b04-8f77-a2efb324465b
   :END:
   crevice

*** --->
    расщелина

    noun
    1. щель (gap, slot, slit, crack, crevice, cleft)
    2. расщелина (cleft, crevice, fissure, crack, chimney, opening)
    3. трещина, содержащая жилу (crevice)

**     DEFINITION                                                     :drill:
   SCHEDULED: <2017-10-11 Wed>
   :PROPERTIES:
   :ID:       c0938718-ebdd-4e6b-b3bb-691b4d73e48c
   :DRILL_LAST_INTERVAL: 3.86
   :DRILL_REPEATS_SINCE_FAIL: 2
   :DRILL_TOTAL_REPEATS: 2
   :DRILL_FAILURE_COUNT: 1
   :DRILL_AVERAGE_QUALITY: 1.5
   :DRILL_EASE: 2.36
   :DRILL_LAST_QUALITY: 3
   :DRILL_LAST_REVIEWED: [2017-10-07 Sat 11:31]
   :END:

   noun
   1. a narrow opening or fissure, especially in a rock or wall. "A
      lack of legs helps them fit into tight gaps and [crevice||crack]s and down
      narrow holes."


** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       e060209c-0cf8-4926-9bed-80d13f44bbf2
   :END:
   A [crevice] is a long, tight space often found on the face of a
   mountain or other geological formation. A [crevice] can be large or
   small, but because it is usually hard reach, it is a great hiding
   place for all things like reptiles, bugs, and lost climbers.
** >>>                                                                :drill:
   :PROPERTIES:
   :ID:       b240da3f-3d5a-4f2b-8f9f-85e01cafa2e4
   :END:
   The word [crevice] often refers to a natural formation, but it can be
   used to describe any long, narrow space that’s hard to access. If
   you’ve lost something you might say, “I’m going to look in every
   crack and [crevice],” to describe the search. Chances are you’ll find
   that lost item in the long narrow space — the [crevice] — between the
   cushions of your sofa, along with other things you didn't even know
   were missing!
** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide1cloze
   :ID:       2cbdcf1f-b66e-41e6-8bbd-55fbbd20b184
   :END:

   A [gorge] is a very deep [crevice] between two mountains or hills.

* erode                                                           :satellite:
  [2017-10-02 Mon 15:58]

** ==>                                                                :drill:
   :PROPERTIES:
   :ID:       61e365b8-ebd4-41bf-bc25-03c1c96c1b9a
   :END:
   erode

*** --->
    разъедать

    verb
    1. разрушать (destroy, ruin, break, break down, disrupt, erode)
    2. разъедать (fret, corrode, eat, eat away, erode, attack)
    3. размывать (erode, wash out, wash, fret, degrade, wear)
    4. эродировать (erode)
    5. вытравлять (erode, corrode)
    6. выветривать (erode, weather, sculpture)

**     DEFINITION                                                     :drill:
   :PROPERTIES:
   :ID:       9d8f3540-7041-440e-b45d-6c7dcf853de1
   :END:

   verb
   1. (of wind, water, or other natural agents) gradually wear away
      (soil, rock, or land). "the cliffs have been [erode]d by the sea"


** >>>                                                                :drill:
   :PROPERTIES:
   :DRILL_CARD_TYPE: hide1cloze
   :ID:       d7c8e742-f842-434e-9786-e1f6e56a138c
   :END:

   [Gorge]s are formed by rivers running through and [erod]ing rock over
   a very long period of time.

* snoring :satellite:
[2017-10-10 Tue 05:16]

</p>
		
		<a role="button" class="signup button green"
		href="/signup/">Get Started</a>
		
	</div> </div> </section>


<footer class="page-footer"> <nav class="sitelinks limited-width
hide-mobile clearfloat screen-only"> <div class="col2 "> <h3>For
Everyone</h3> <ul> <li><a href="/play/">Play the Challenge</a></li>
<li><a href="/lists/">Vocabulary Lists</a></li> <li><a
href="/dictionary/">Dictionary</a></li> <li><a
href="/articles/chooseyourwords/">Choose Your Words</a></li> </ul>
</div>
			
		<div class="col2 "> <h3><a
			href="/educator-edition/">For
			Educators</a></h3> <ul> <li><a
			href="/educator-edition/">Educator
			Edition</a></li> <li><a
			href="/educator-edition/pricing/">Plans &amp;
			Pricing</a></li> <li><a
			href="/educator-edition/sales/">Contact
			Sales</a></li> <li><a
			href="/educator-edition/success-stories/">Success
			Stories</a></li> </ul> </div>
		
		<div class="col2 "> <h3><a href="/help/">Help</a></h3>
			<ul> <li><a href="/help/">Help Articles /
			FAQ</a></li> <!-- <li><a
			href="/help/videos/">How-to Videos</a></li>-->
			<li><a href="/help/webinars">Training &amp;
			Webinars</a></li> <li><a
			href="/help/contactus">Contact
			Support</a></li> <li><a>&nbsp;</a></li> </ul>
			</div>
					
		<div class="col2 "> <h3><a
			href="/leaderboards/">Leaderboards</a></h3>
			<ul> <li><a href="/bowl/">Vocabulary
			Bowl</a></li> <li><a
			href="/leaderboards/bowl/">Bowl
			Leaders</a></li> <li><a
			href="/leaderboards/today/">Today's
			Leaders</a></li> <li><a
			href="/leaderboards/thisweek/">Weekly
			Leaders</a></li> <li><a
			href="/leaderboards/thismonth/">Monthly
			Leaders</a></li> </ul> </div>
				
		<div class="col2 "> <h3><a
			href="/blog/">Connect</a></h3> <ul> <li><a
			href="/blog/">Vocabulary.com Blog</a></li>
			<li><a
			href="https://twitter.com/VocabularyCom">Twitter</a></li>
			<li><a
			href="https://www.facebook.com/vocabularycom">Facebook</a></li>
			
			</ul> </div>
		
		<div class="col2 "> <h3><a href="/about/">Our
			Story</a></h3> <ul> <li><a href="/about/">Our
			Mission</a></li> <li><a
			href="/about/team/">Team / Jobs</a></li>
			<li><a href="/about/news/">News &amp;
			Events</a></li> <li><a
			href="/about/partnerships/">Partnerships</a></li>
			</ul> </div>

</nav> <nav class="legal limited-width clearfloat"> <a
href="/terms/">&copy; Vocabulary.com</a> <a href="/terms/"
class="screen-only">Terms of Use</a> <a href="/privacy/"
class="screen-only">Privacy Policy</a> </nav></footer>

<nav class="sitemap screen-only"> <div class="scrollable"> <div> <div
class="limited-width mobile-5050 pad2y">
	
	<div class="col9"> <div class="col4 pad1x"> <h3>For
		Everyone</h3> <ul> <li><a href="/play/">Play the
		Challenge</a></li> <li><a href="/lists/">Vocabulary
		Lists</a></li> <li><a
		href="/dictionary/">Dictionary</a></li> <li><a
		href="/articles/chooseyourwords/">Choose Your
		Words</a></li> </ul> </div>
			
		<div class="col4 pad1x"> <h3><a
			href="/educator-edition/">For
			Educators</a></h3> <ul> <li><a
			href="/educator-edition/">Educator
			Edition</a></li> <li><a
			href="/educator-edition/pricing/">Plans &amp;
			Pricing</a></li> <li><a
			href="/educator-edition/sales/">Contact
			Sales</a></li> <li><a
			href="/educator-edition/success-stories/">Success
			Stories</a></li> </ul> </div>
		
		<div class="col4 pad1x"> <h3><a
			href="/help/">Help</a></h3> <ul> <li><a
			href="/help/">Help Articles / FAQ</a></li>
			<li><a href="/help/videos/">How-to
			Videos</a></li> <li><a
			href="/help/webinars">Training &amp;
			Webinars</a></li> <li><a
			href="/help/contactus">Contact
			Support</a></li> <li><a>&nbsp;</a></li> </ul>
			</div>
					
		<div class="col4 pad1x"> <h3><a
			href="/leaderboards/">Leaderboards</a></h3>
			<ul> <li><a href="/bowl/">Vocabulary
			Bowl</a></li> <li><a
			href="/leaderboards/bowl/">Bowl
			Leaders</a></li> <li><a
			href="/leaderboards/today/">Today's
			Leaders</a></li> <li><a
			href="/leaderboards/thisweek/">Weekly
			Leaders</a></li> <li><a
			href="/leaderboards/thismonth/">Monthly
			Leaders</a></li> </ul> </div>
		
		

		<div class="col4 pad1x"> <h3><a
			href="/blog/">Connect</a></h3> <ul> <li><a
			href="/blog/">Vocabulary.com Blog</a></li>
			<li><a
			href="https://twitter.com/VocabularyCom">Twitter</a></li>
			<li><a
			href="https://www.facebook.com/vocabularycom">Facebook</a></li>
			
			</ul> </div>
		
		<div class="col4 pad1x"> <h3><a href="/about/">Our
			Story</a></h3> <ul> <li><a href="/about/">Our
			Mission</a></li> <li><a
			href="/about/team/">Team / Jobs</a></li>
			<li><a href="/about/news/">News &amp;
			Events</a></li> <li><a
			href="/about/partnerships/">Partnerships</a></li>
			</ul> </div> </div> <div class="col3 pad1x">
			<h3><a href="/account/">My Account</a></h3>
			<div class="loggedout-only clearfloat
			signinoptions"> <a role="button" class="google
			button" href="/login/google">Sign in with
			Google</a> <a role="button" class="facebook
			button" href="/login/facebook">Sign in with
			Facebook</a> <p>or, <a href="/login/">sign in
			with email.</a></p> <p>Don't have an account
			yet?<br> <a href="/signup">Sign up. It's free
			and takes five seconds.</a> </p> </div> <ul
			class="loggedin-only"> <li><a
			href="/auth/logout"><i class="ss-logout">Log
			Out</a></li> <li
			class="perms-school-reports-only"><a
			href="/account/schools"><i class="ss-school
			ss-symbolicons-block">Schools &amp;
			Teachers</a></li>
			
			<li class="nav-classes
			perms-create-class-only"><a
			href="/account/classes"><i class="ss-users">My
			Classes</a></li>
			
			<li class="nav-assignments"><a
			href="/account/activities/"><i
			class="ss-attach">Assignments &amp;
			Activities</a></li> <li ><a
			href="/account/lists/"><i class="ss-list">My
			Lists</a> <ul> <li><a href="/lists/"><i
			class="ss-search">Find a List to
			Learn...</a></li> <li><a href="/lists/new"><i
			class="ss-hospital
			ss-symbolicons-block">Create a New
			List...</a></li> </ul> </li> <li><a
			href="/progress/"><i class="ss-barchart">My
			Progress</a> <ul> <li><a
			href="/account/progress/words/learning"><i
			class="ss-hiker ss-symbolicons-block">Words
			I'm Learning</a></li> <li><a
			href="/account/progress/words/trouble"><i
			class="ss-bullseye ss-symbolicons-block">My
			Trouble Words</a></li> <li><a
			href="/account/progress/words/mastered"><i
			class="ss-check ss-symbolicons-block">Words
			I've Mastered</a></li> <li><a
			href="/account/progress/achievements"><i
			class="ss-award ss-symbolicons-block">My
			Achievements</a></li> </ul> </li> <li
			class="perms-user-admin-only"><a
			href="/account/users"><i class="ss-usergroup
			ss-symbolicons-block ">User
			Administration</a></li> <li
			class="perms-auth-admin-only"><a
			href="/account/authentication"><i
			class="ss-key">User Authentication</a></li>
			<li> <a href="/account/"><i
			class="ss-settings">My Account</a> </li> </ul>
			</div> </div> <div class="copyright pad2y">
			<div class="limited-width"> <span>&copy;
			Vocabulary.com</span> <div class="terms"> <a
			href="/terms/">Terms of Use</a> <a
			href="/privacy/">Privacy Policy</a> </div>
			</div> </div> </div></div> <div
			class="nub"></div> </nav> </div>


</body>

</html>


</p> <p>Don't have an account yet?<br> <a href="/signup">Sign up. It's
			free and takes five seconds.</a> </p> </div>
			<ul class="loggedin-only"> <li><a
			href="/auth/logout"><i class="ss-logout">Log
			Out</a></li> <li
			class="perms-school-reports-only"><a
			href="/account/schools"><i class="ss-school
			ss-symbolicons-block">Schools &amp;
			Teachers</a></li>
			
			<li class="nav-classes
			perms-create-class-only"><a
			href="/account/classes"><i class="ss-users">My
			Classes</a></li>
			
			<li class="nav-assignments"><a
			href="/account/activities/"><i
			class="ss-attach">Assignments &amp;
			Activities</a></li> <li ><a
			href="/account/lists/"><i class="ss-list">My
			Lists</a> <ul> <li><a href="/lists/"><i
			class="ss-search">Find a List to
			Learn...</a></li> <li><a href="/lists/new"><i
			class="ss-hospital
			ss-symbolicons-block">Create a New
			List...</a></li> </ul> </li> <li><a
			href="/progress/"><i class="ss-barchart">My
			Progress</a> <ul> <li><a
			href="/account/progress/words/learning"><i
			class="ss-hiker ss-symbolicons-block">Words
			I'm Learning</a></li> <li><a
			href="/account/progress/words/trouble"><i
			class="ss-bullseye ss-symbolicons-block">My
			Trouble Words</a></li> <li><a
			href="/account/progress/words/mastered"><i
			class="ss-check ss-symbolicons-block">Words
			I've Mastered</a></li> <li><a
			href="/account/progress/achievements"><i
			class="ss-award ss-symbolicons-block">My
			Achievements</a></li> </ul> </li> <li
			class="perms-user-admin-only"><a
			href="/account/users"><i class="ss-usergroup
			ss-symbolicons-block ">User
			Administration</a></li> <li
			class="perms-auth-admin-only"><a
			href="/account/authentication"><i
			class="ss-key">User Authentication</a></li>
			<li> <a href="/account/"><i
			class="ss-settings">My Account</a> </li> </ul>
			</div> </div> <div class="copyright pad2y">
			<div class="limited-width"> <span>&copy;
			Vocabulary.com</span> <div class="terms"> <a
			href="/terms/">Terms of Use</a> <a
			href="/privacy/">Privacy Policy</a> </div>
			</div> </div> </div></div> <div
			class="nub"></div> </nav> </div>


</body>

</html>


If you're snoring through a movie, you're probably not that [interested]
    in it.
* arrears :satellite:
[2017-10-11 Wed 05:38]

If you are in arrears, you are behind in the payment of a debt. Think:
rears=behind. Arrears also refers to the unpaid, overdue debt itself.
Your rent arrears are the money you own on rent.

Arrears is a term often used in a legal context––like, when you've had
to hire a lawyer because you're being sued by your landlord, or being
evicted because you're in arrears on your rent. Before it comes to
eviction, though, you should try negotiating with your landlord first.
They would probably be more interested in collecting arrears, even
late, than in evicting you and starting with a new tenant from
scratch.

he was suing the lessee for the arrears of rent
* seedy :satellite:
[2017-10-11 Wed 05:42]

When a place is seedy, it's sleazy, run-down — not the kind of place
you'd take your mom. The East Village of New York was once known for
being seedy, but now it's safe for children of all ages.

It's a mystery how the word seedy came to mean darkly rundown, slummy,
and seamy, but it probably came from the appearance of flowers after
they've shed their seeds. That's when they start to lose their color
and eventually die. You'll find seedy used to describe places like
dive bars, brothels, and those sections of town where dealers ply
their drugs. Certain writers, such as Dennis Cooper and even Charles
Dickens, are fascinated by the seedy underbelly of life in big cities,
in scenes populated by wretched people and other outcasts.

But today seedy glamour is being replaced by the dim light of
   computer screens and the unhealthy pallor of those who stare into
   them for most of their waking hours.
* mortar :satellite:
[2017-10-11 Wed 05:45]

A mortar is a bowl-shaped container that you can grind things in using
a pestle. You probably buy your spices pre-ground at the store, but if
you wanted to be old-school, you could grind them yourself with a
mortar and pestle.

Mortar is an old word — it comes from Old English, and using a mortar
to smash things up is old way of cooking. It's also the builder's
paste used between bricks. If you've heard the phrase "brick and
mortar," that's a style of building, as well as a general phrase for
something with a real building (as opposed to an internet business).
And it's also a gun that fires high bullets that land short-range.

Once the mortar is dry, you can attach a cutting board to the side
   of the barbecue with fluted masonry nails.
* ramification :satellite:
[2017-10-11 Wed 05:47]

A ramification is an accidental consequence that complicates things.
Remember that time you borrowed your father's car without asking? The
ramification was that Dad missed an important meeting, his company
went under, and he had to sell the car. Oops!

The ramifications are the broader effects that fan out into the world
from one situation, or decision, that kicks it all off. Ramification
also refers to something branching out, like limbs on a tree — which
is what bad decisions tend to do. Ramification is like consequence,
but usually unintended and bad. The word is often used in political
discussions about laws or government decisions because they might be
made locally but could affect people worldwide.

ramification
* skirmishes :satellite:
[2017-10-11 Wed 09:56]

A skirmish is a small fight — more a dust-up than a full-out battle —
and it can refer to a physical fight or just a battle of words. It is
definitely confrontational, though.

Think of a skirmish as kind of a mini-battle, although a military
skirmish can end with casualties. Still, although such an encounter
can be serious, even the very word skirmish sounds slight, like a
stirring of dust in the breeze. Shakespeare referred to the combative
nature of his characters Beatrice and Benedick, in "Much Ado About
Nothing," as "a kind of merry war betwixt Signior Benedick and her:
they never meet but there's a skirmish of wit between them."

watchman had so many skirmishes with them."
* harass :satellite:
[2017-10-14 Sat 07:32]

When you harass someone, you bother them to the point of exhaustion.
It’s not that each attack is so severe, it’s the constant small
attacks that wear someone out. If you harass your boss for a raise,
you might end up getting fired instead!

Harass probably comes from the Old French word harer meaning "to set a
dog on." Think of someone being hounded when you use this word. You
can harass your parents with questions or requests, but in turn, they
can also harass you to clean your room! While this is annoying, it's
much worse if you are harassed in the sense of being verbally abused.
The bully at school who harasses some poor kid will be subject to
disciplinary action if a complaint is filed.


* diminutive :satellite:
[2017-10-14 Sat 07:41]

Diminutive means small. A diminutive person is short and small. A
diminutive word is a "cute" version of a word or name: for example,
"duckling" is a diminutive of "duck" and Billy is a diminutive form of
the name William.

A diminutive name or word is formed from another by the addition of a
suffix expressing smallness in size: a booklet is a small book, a
dinette is a small version of a dining set. The adjective diminutive
descends from Middle English, from Old French, from Late Latin
dīminūtīvus, from Latin dēminuere "to lessen."

"He was diminutive, and how he managed to lift the
      heavy [harness] on the draught horses for ploughing was more
      than I could understand."
* concave :satellite:
[2017-10-14 Sat 07:50]

Concave describes an inward curve; its opposite, convex, describes a
curve that bulges outward. They are used to describe gentle, subtle
curves, like the kinds found in mirrors or lenses.

A valley is a concave curve, a mountain is a convex curve—you can
remember this by thinking that things that vex you tend to stick out,
and that caves tend to be holes that go in, like valleys or innie
belly buttons. If you want to describe a bowl, you might say there is
a large blue spot on the center of the concave side.

"It has a large posterior [auricle] that has a concave posterior
    margin meeting the hinge at an [acute] angle."
* posterior :satellite:
[2017-10-14 Sat 07:50]

Use the adjective posterior to describe something that's in the back.
It’s often used in anatomy — a posterior cerebral artery supplies
blood to the back of the brain, and the tail is on the posterior of a
fish.

The prefix post means “after,” and things that are posterior come
after the things in the front. The opposite of posterior is anterior,
which refers to the front, usually of body parts. You can also use the
word posterior to jokingly refer to the part of your body that you sit
on — your backside. Posterior is also a formal way to say later in
time.

"It has a large posterior [auricle] that has a concave posterior
    margin meeting the hinge at an [acute] angle."