
* Jargon

** Munge/Munging/Wrangling
   Describes the overall process of manipulating unstructured and/or messy data
   into a structured or clean form. The word has snuck its way into the jargon
   of many modern day data hackers. Munge rhymes with “lunge”.

** Interacting with the outside world
   Reading and writing with a variety of file formats and databases.

** Preparation
   Cleaning, munging, combining, normalizing, reshaping, slicing and dicing, and
   transforming data for analysis.

** Transformation
   Applying mathematical and statistical operations to groups of data sets to
   derive new data sets. For example, aggregating a large table by group variables.

** Modeling and computation
   Connecting your data to statistical models, machine learning algorithms, or other
   computational tools

** Presentation
   Creating interactive or static graphical visualizations or textual summaries



* Knowledge is power;						       :True:

** it is product of education;					       :True:

*** TODO reading;

*** TODO thinking;

*** TODO practicing;

** all knowledges reside in the memory;

*** they require repetition;

*** the spaced repetition is the best approach;
* Dive into Python programming language

** in six months

** with:

*** Standard approaches
*** NLTK
*** NumPy
*** pandas
*** matplotlib
*** IPython
*** SciPy

http://github.com/pydata/pydata-book


* Python for Data Analyse
** DONE Preliminaries
** TODO Introductory Examples
*** collections pack
** TODO IPython: An Interactive Computing and Development Environment
